<?php $this->partial('blog/sidebar', array()); ?>
<?php $this->headTitle($this->escape('2011-08-31 IRC Meeting Log - ZF2 DevBlog'), 'SET'); ?>
<?php $this->headLink()->appendStylesheet('/css/zf2-blog.css', 'all'); ?>
<?php echo $this->dynamicHeader('subPageMainHeader', 'Zend Framework 2 Blog'); ?>
<h2>2011-08-31 IRC Meeting Log</h2>
<div class="dotted-line"></div>

<div class="metadata">
    <p>
        Posted on 2011-08-31 14:50 
        by <a href="http://weierophinney.net/matthew/">Matthew Weier O'Phinney</a>    </p>
    </div>


<div class="post-content">
    <p>
    Today we held our second Zend Framework community IRC meeting. The meeting 
    was held on Freenode IRC in the #zf2-meeting channel, and moderated by 
    Pieter Kokx. The meeting ran long (15 minutes over), had several heated 
    exchanges, but gained general consensus on a variety of topics.
</p>

<p>
    Specifically, we discussed:
</p>

<ul class="ul">
    <li>Modules - defining what "module" means, and differentiating it from 
        "component", as well as defining these terms in relation to "library" 
        and "application".
    </li>
    <li>Distribution categories - what broad categories we'll define as "buckets"
        for components, and which categories will be considered necessary for the 
        "standard distribution" -- which defines what needs to be done to be 
        considered stable.
    </li>
    <li>Timeframes for potential releases.</li>
</ul>

<p>
    The full transcript, as well as a summary of decisions, can be found on the
    <a href="http://framework.zend.com/wiki/display/ZFDEV2/2011-08-31+Meeting+Log">ZF2 
    wiki</a>.
</p></div>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_developer = 0;
    var disqus_shortname = 'zf2blog'; // required: replace example with your forum shortname
    var disqus_identifier = 'zf2-2011-08-31-IRC-Meeting-Log';
    var disqus_url = 'http://framework.zend.com/zf2/blog/entry/2011-08-31-IRC-Meeting-Log';
    var disqus_title = '2011-08-31 IRC Meeting Log';


    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

<?php $this->partial('blog/highlight', array()); ?>
