<?php $entry = $this->entry; ?>
<?php 
echo "<?php \$this->partial('blog/sidebar', array()); ?>\n";
echo "<?php \$this->headTitle(\$this->escape('{$entry->title} - ZF2 DevBlog'), 'SET'); ?>\n";
echo "<?php \$this->headLink()->appendStylesheet('/css/zf2-blog.css', 'all'); ?>\n";
echo "<?php echo \$this->dynamicHeader('subPageMainHeader', 'Zend Framework 2 Blog'); ?>\n"; 
?>
<h2><?php echo $this->escape($entry->title) ?></h2>
<div class="dotted-line"></div>

<div class="metadata">
    <p>
        Posted on <?php echo $entry->date->format('Y-m-d H:i') ?> 
        by <?php echo $this->author($entry->author) ?>
    </p>
    <?php echo $this->tags($entry->tags) ?>
</div>


<div class="post-content">
    <?php echo $entry->content ?>
</div>

<?php 
echo $this->partial('blog/disqus.phtml', array(
    'entry'       => $entry,
    'development' => $this->development,
    'host'        => ($this->host ? $this->host : 'framework.zend.com'),
));
echo "<?php \$this->partial('blog/highlight', array()); ?>\n";
