<?php
$this->layout()->active = 'participate';
$this->render('page-controller/participate/sidebar');
$headTitle = $this->headTitle();
$headTitle->prepend('Participate');
$headTitle->prepend('Blogs');
?>
<section class="participate">
    <h1>Blogs</h1>

    <blockquote>
        Featured Blogs From Community Members Who Regularly Cover ZF Topics
    </blockquote>

    <hr/>

    <?php
    $blogs = array(
        array('Abdul Malik Ikhsan', 'http://samsonasik.wordpress.com/'),
        array('Adam Lundrigan', 'http://adam.lundrigan.ca/'),
        array('Ben Scholzen', 'http://www.dasprids.de/'),
        array('Enrico Zimuel', 'http://www.zimuel.it/en'),
        array('Evan Coury', 'http://blog.evan.pro/'),
        array('Jurian Sluiman', 'http://juriansluiman.nl/en/'),
        array('Matt Cockayne', 'http://devincharge.com/'),
        array("Matthew Weier O'Phinney", 'http://mwop.net/blog.html'),
        array('Michael Gallego', 'http://www.michaelgallego.fr/blog/'),
        array('Pádraic Brady', 'http://blog.astrumfutura.com/'),
        array('Ralph Schindler', 'http://ralphschindler.com/'),
        array('Rob Allen', 'http://akrabat.com/'),
        array('Ryan Mauger', 'http://www.rmauger.co.uk/'),
        array('Sascha-Oliver Prolic', 'http://www.sasaprolic.com/')
    );
    ?>
    <ol>
        <?php foreach($blogs as $blog): ?>

        <li><a href="<?php echo $blog[1] ?>"><?php echo $blog[0] ?></a></li>
        <?php endforeach; ?>
    </ol>

    <p class="note">
        Want to be on the above list? <a href="https://github.com/zendframework/zf-web">Fork 
        our website repository</a> and submit a pull request!
    </p>
</section>
