<?php
$this->layout()->active = 'participate';
$this->render('page-controller/participate/sidebar');
$headTitle = $this->headTitle();
$headTitle->prepend('Participate');
$headTitle->prepend('Contributor Guide');
?>
<section class="participate">
    <h1>Contributor Guide</h1>

    <blockquote>
        Have something you want to contribute back? Follow this helpful guide.
    </blockquote>

    <hr/>

    <p>
        In the spirit of open-source software, you can contribute as little or
        as much as you like: bug reports, patches, full components or
        documentation are all equally appreciated.  The following section
        describes contributing for Zend Framework version 2.
    </p>

    <p>
        If you are wanting to contribute back to version 1 of the framework,
        please read
        <a href="/participate/contributor-guide-v1">"Zend Framework v1 Contributions"</a>.
    </p>

    <h2>So, You Want to File A Bug Report ... </h2>

    <p>
        So, you've found what you think might be a bug.  Before you file it,
        we'd ask that you ensure that what you have is indeed a bug, by doing
        a little due-diligence (which also is good information to add to the
        bug report):
    </p>

    <ul>
        <li>See if your use case is covered in the <a href="/manual/2.0/en/index.html">manual</a></li>
        <li>See if your use case is demonstrated by the <a href="/api/#">API docs.</a></li>
        <li>Ask the <a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">mailing list</a> about your particular use case</li>
        <li>Discuss your issue with someone in the IRC channel (see below)</li>
        <li>Write a failing <a href="https://github.com/zendframework/zf2/tree/master/tests">test case</a></li>
    </ul>

    <p>
        <img src="/images/participate/icon_issue.gif" align="right" />
        You don't have to do all of those, but by doing a few of them, it helps
        ensure that your bug report is complete and will get tended to.  When
        you're finally ready, go to our <a href="https://github.com/zendframework/zf2/issues">issue tracker for
        ZF2</a>.
    </p>

    <h2>So, You Want to Contribute Code ... </h2>

    <p>
        By and large, this framework is built and maintained by the community.
        This means that process for submitting something back, be it a patch,
        some documentation, or new feature requires some level of community
        interactions.  As you can see with the "Fork Me On Github" banner on
        the top right of this page, we proudly host our code on
        <a href="http://github.com/zendframework/zf2/">github.com</a>.
    </p>

    <p>
        If you're not already familar with git or github, take a moment to
        read through our <a href="https://github.com/zendframework/zf2/blob/master/README-GIT.md">README-GIT.md</a>.
        Committing code is easy:
    </p>

    <ol>
        <li><b>Fork</b> the <a href="https://github.com/zendframework/zf2">zf2 project</a></li>

        <li>Create a local development <b>Branch</b> for the bugfix.</li>

        <li><b>Commit</b> a change and <b>push</b> your local branch to your github fork.</li>

        <li>Send us a <b>pull request</b> for your changes to be included.</li>
    </ol>

    <h2>So, You Want to Hang-out With A Great Community ... </h2>

    <p>
        ZFers, as they are called, hang out in a number of different places.
        Offline hangouts:
    </p>

    <ul>
        <li><a href="/participate/user-groups">User Groups With ZF Community Members</a></li>

        <li><a href="/participate/conferences">Conferences With ZF Talks</a></li>
    </ul>

    <p>
        Online, ZFers can be found (links to more information on how to connect):
    </p>

    <ul>
        <li>
            <a name="irc" href="/irc">In IRC:</a> on freenode, chat rooms:

            <ul>
                <li><a href="irc://irc.freenode.net/zftalk">#zftalk</a></li>
                <li><a href="irc://irc.freenode.net/zftalk.dev">#zftalk.dev</a></li>
            </ul>

        </li>

        <li>
            <a name="mailing-list" href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">On the mailing list</a>
        </li>
    </ul>
</section>

