<?php
$this->layout()->active = 'participate';
$this->render('page-controller/participate/sidebar');
$headTitle = $this->headTitle();
$headTitle->prepend('Participate');
$headTitle->prepend('Contributor Guide v1');
?>
<section class="participate" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <h1>Contributor Guide (ZF v1)</h1>

    <hr />

    <p>
        Zend Framework version 1 will be supported through __ of ____.  At which point
        it will be EOL.  Version 1.12 is the last version in the 1.x series with new features.
        If it is a new feature you wish to contribute, the best place to take this is ZF2.
    </p>

    <p>
        For ZF1, we are accepting bug fixes to existing components.  Security fixes will
        be provided on both the 1.11 and 1.12 branch until EOL.  If you have a fix for
        a ZF1 issue, please carefully read
        <a href="http://framework.zend.com/wiki/display/ZFDEV/Contributing+to+Zend+Framework">this document.</a>
        It explains the procedures as it relates to the ZF1 process: using subversion, gaining access
        to the repository, and signing/sending in the Contributor License Agreement (CLA).
    </p>

    <p>
        Note: while ZF2 is CLA free, ZF1 and its contribution process still require this.
        The license has not changed, and like ZF2 is the New BSD license.
    </p>

</section>