<?php 
if ($this->pageCount < 2) return;

$urlPattern = $this->url;
if ($this->substitution) {
    $urlPattern = str_replace('%s', str_replace(' ', '+', $this->substitution), $urlPattern);
}
$firstUrl   = str_replace('-p%d', '', $urlPattern);
?>
<div class="paginationControl">
<?php // First page link
    if ($this->first && $this->first != $this->current): ?>
        <a href="<?php echo $firstUrl ?>" class="first">&lt;&lt; First</a> |
<?php endif;

    // Previous page
    if ($this->previous): ?>
        <a href="<?php echo (($this->previous == $this->first) ? $firstUrl : sprintf($urlPattern, $this->previous)) ?>"> &lt; Previous </a> |
<?php endif;

    // Numbered page links
    foreach ($this->pagesInRange as $page):
        if ($page == $this->current): ?>
        <span class="current"><?php echo $page ?></span> |
    <?php elseif ($page == $this->first): ?>
        <a href="<?php echo $firstUrl ?>"><?php echo $page ?></a> |
    <?php else: ?>
        <a href="<?php printf($urlPattern, $page) ?>"><?php echo $page ?></a> |
    <?php endif ?>
<?php endforeach;

    // Next page link
    if ($this->next): ?>
        <a href="<?php printf($urlPattern, $this->next) ?>"> Next &gt;</a> |
<?php endif;

    // Last page link
    if ($this->last && $this->last !== $this->current): ?>
        <a href="<?php printf($urlPattern, $this->last) ?>" class="last"> Last &gt;&gt;</a>
<?php endif; ?>
</div>

