<?php if (isset($this->message)): ?> 
    <b><?php echo $this->message ?></b> <br /> <br />
<?php endif; ?>

<?php if (isset($this->user)): ?>

    You are currently logged in as <?php echo $this->user->name ?> (<?php echo $this->user->email ?>).<br />
    <?php if (isset($this->previousUrl)): ?>
        Go back to your <a href="<?php echo $this->previousUrl ?>">previous location</a>.
    <?php endif; ?> <br /> <br /> Or 
    <a href="/auth/logout">Logout</a>

<?php else: ?>

    You are not logged in.
    
    <div style="width: 350px">
        <?php echo $this->authForm; ?>
    </div>
    

<?php endif; ?>

<br />
<br />

