<?php
$this->render('manual/page-controller/learn/sidebar', array('active' => 'api'));

$this->layout()->bodyId = 'api';
$this->layout()->active = 'learn';
?>

<h1>API</h1>

<h2 id="zf2">Zend Framework 2</h2>

<table class="twelve">
    <thead>
        <tr>
            <th width="45%">
                API Documentation
            </th>
            <th width="25%">
                Browse
            </th>
            <th width="25%">
                Download
            </th>
        </tr>
    </thead>
    <tbody>

        <?php echo
        $this->render('manual/page-controller/api/download-list', array(
            'versions' => $this->versions[2],
        ));
        ?>

    </tbody>
</table>

<h2 id="zf1">Zend Framework 1</h2>

<table class="twelve">
    <thead>
        <tr>
            <th width="45%">
                API Documentation
            </th>
            <th width="25%">
                Browse
            </th>
            <th width="25%">
                Download
            </th>
        </tr>
    </thead>
    <tbody>

        <?php echo
        $this->render('manual/page-controller/api/download-list', array(
            'versions' => $this->versions[1],
        ));
        ?>

    </tbody>
</table>
