<?php
$this->render('manual/page-controller/learn/sidebar', array('active' => 'overview'));

$this->headTitle()->prepend('Learn');
?>

<h1>Learn</h1>
<p>
    No matter what your preferred format or experience level, we have the docs you're looking for.
</p>

<h2>Getting started</h2>

<p>
    Our QuickStart will take you on a short tour of some important Zend Framework components while demonstrating how a ZF2 or ZF1 application can be built from the ground up.     
</p>

<ul class="button-group">
    <li><a href="<?php echo $this->basePath('manual/current/en/user-guide/overview.html') ?>" class="small button">Zend Framework 2</a></li>
    <li><a href="<?php echo $this->basePath('manual/1.12/en/learning.quickstart.html') ?>" class="small button">Zend Framework 1</a></li>
</ul>

<h2>Reference Guide</h2>

<p>
    With over 1000 pages and 500 examples, our Reference Guide complements quality code with quality documentation. 
</p>

<ul class="button-group">
    <li><a href="<?php echo $this->basePath('manual/current/en/index.html') ?>" class="small button">Zend Framework 2</a></li>
    <li><a href="<?php echo $this->basePath('manual/1.12/en/manual.html') ?>" class="small button">Zend Framework 1</a></li>
</ul>

<h2>API</h2>

<p>
    Looking for a particular method's signature? Can't remember the name of a constant? With Zend Framework's thoroughly self-documenting codebase, you can answer all your API questions with a few clicks. 
</p>

<ul class="button-group">
    <li><a href="<?php echo $this->url('docs/api') ?>#zf2" class="small button">Zend Framework 2</a></li>
    <li><a href="<?php echo $this->url('docs/api') ?>#zf1" class="small button">Zend Framework 1</a></li>
</ul>

<h2>Training & Certification</h2>

<p>
    Specialized Training Curriculum from Zend designed with leaders from the 
    Zend Framework Community. <a href="<?php echo $this->url('learn/training-and-certification') ?>">Learn more.</a>
</p>

<div class="row">
    <div class="three columns training">
        <a href="http://www.zend.com/en/services/training/zf2-fundamentals">
            <img src="<?php echo $this->basePath('/images/training-fundamentals.gif') ?>">
            <br>
            Zend Framework 2: Fundamentals Course
        </a>
    </div>

    <div class="three columns training">
        <a href="http://www.zend.com/en/services/training/zf2-advanced-concepts">
            <img src="<?php echo $this->basePath('/images/training-advanced.gif') ?>">
            <br>
            Zend Framework 2: Advanced Course
        </a>
    </div>

    <div class="three columns training">
        <a href="http://shop.zend.com/en/php-training/zend-framework2-training-certification-bundle.html">
            <img src="<?php echo $this->basePath('/images/training-bundle.gif') ?>">
            <br>
            Money Saving ZF2 Training Bundle
        </a>
    </div>

    <div class="three columns training">
        <a href="http://shop.zend.com/en/zend-certification/zend-framework-certification-voucher.html">
            <img src="<?php echo $this->basePath('/images/training-certification.gif') ?>">
            <br>
            Become ZF2 Certified
        </a>
    </div>
</div>

<h2>Support &amp; Consulting</h2>

<p>
    Zend provides support for Zend Framework via Zend Server. Additionally, 
    Zend offers a variety of consulting services for PHP and Zend Framework.
    <a href="<?php echo $this->url('learn/training-and-certification') ?>">Learn more.</a>
</p>

<h2>Webinars</h2>

<p>
    With everything from webinars to podcasts, you'll be able to find presentations, interviews, and howto's in your preferred format. 
    Visit the <a href="http://www.zend.com/en/company/events/">Zend's Events Page</a> to view a list of upcoming Webinars or <a href="http://www.zend.com/en/resources/webinars/framework">click here</a> to watch the recorded webinars.
</p>

<hr />

<p>
   Still haven't found exactly what you're looking for? More articles can be 
   found at <a href="http://devzone.zend.com/category/zend-framework/">Zend's 
   DevZone</a>.
</p>
