<?php 
$this->layout()->active = 'learn';
foreach ($this->css as $css) {
    $this->headLink()->prependStylesheet($this->basePath() . $css);
}

$this->render('manual/page-controller/manual/sidebar', array(
    'sidebar'  => $this->sidebar,
    'versions' => $this->versions,
    'version'  => $this->version
));

echo $this->body; 

$identifier = 'zfmanual-' . $this->name;
$url        = $this->manualUrl($this->name, $this->lang, $this->version);
echo $this->disqus($identifier, $url, $this->title, 'zfmanual');
?>
