<h2>ZF-11618: Zend_Soap_Server does not return boolean values correctly if part of a complex class</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-27T16:15:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-09T20:18:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Server</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14730/ZF-11618_notreproduced.patch">ZF-11618_notreproduced.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following code should demonstrate the issue:</p>

<pre class="literal">

ini_set("soap.wsdl_cache_enabled", "0"); // disabling WSDL cache

require_once('/Zend/Loader/Autoloader.php');
$loader = Zend_Loader_Autoloader::getInstance();

if(isset($_GET['wsdl'])) { 
                  
    $autodiscover = new Zend_Soap_AutoDiscover('Zend_Soap_Wsdl_Strategy_ArrayOfTypeSequence');
    
    $autodiscover-&gt;setOperationBodyStyle(array('use' =&gt; 'literal'));
    $autodiscover-&gt;setBindingStyle(array('style' =&gt; 'rpc'));
    
    $autodiscover-&gt;setClass('BooleanTestClass');
    $autodiscover-&gt;handle();
    
} else if (isset($_GET['client'])) {
    
    $client = new Zend_Soap_Client('http://' . $_SERVER['HTTP_HOST'] . $_SERVER['SCRIPT_NAME'] .'?wsdl');
    
    $result1 = $client-&gt;isStringHello("hello");
    
    print_r($result1);
    
    $result2 = $client-&gt;isStringHello("hello2");
    
    print_r($result2);  
    
} else {

    $server = new Zend_Soap_Server('http://' . $_SERVER['HTTP_HOST'] . $_SERVER['SCRIPT_NAME'] .'?wsdl');   
    $server-&gt;setClass("BooleanTestClass");
    $server-&gt;handle();  
}

exit();

class BooleanTestClass {
    /**
     * isStringHello method
     * @param string
     * @return ReturnTestClass
     */
    public function isStringHello($string) {
        $return = new ReturnTestClass();
        
        if ($string == "hello") {
            $return-&gt;ReturnStatus = true;
        } else {
            $return-&gt;ReturnStatus = false;          
        }           
    }
}

class ReturnTestClass {
    /**
     * @var boolean
     */
    public $ReturnStatus = false;
}

</pre>

<p>The AutoDiscovered WSDL is fine but it only ever returns empty strings for the ReturnStatus.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-11-08T17:43:18.000+0000</p> 
        <div class="body">
            <p>I've attempted to reproduce your problem in a unit test, but I have been unsuccessful thus far.  I've attached a patch ({{ZF-11618_notreproduced.patch}}) showing my test, which passes against trunk.  Could you have a look and make sure i've not missed something or didn't properly capture your case?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ashleigh Vincent (avincent) on 2011-11-09T09:40:59.000+0000</p> 
        <div class="body">
            <p>I wrote a class that wrapped around Zend_Soap_Server but logged all the XML it sent and received. This showed that the XML was always blank for the boolean. I was testing under PHP 5.2.6 as this is our deployed production version.</p>

<p>I am not really familiar at all with the test framework stuff as I am still learning my way around ZF.</p>

        </div>
    </div>
    </div>

