<h2>ZF-10331: Zend_Dojo_Form_Element_NumberSpinner is not supporting decimal deltas</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-18T04:33:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-28T15:30:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Robert Basic (robertbasic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13853/ZF-10331-tests.diff">ZF-10331-tests.diff</a></li>
            <li><a href="/issues/secure/attachment/13852/ZF-10331.diff">ZF-10331.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It is not possible to increment/decrement values in steps less than 1 in a dojo numberspinner.</p>

<p>The setSmallDelta method from Zend_Dojo_Form_Element_NumberSpinner currently takes as parameter an int value for delta, which is causing this mis-behaviour. Hence specifying any decimal value will be casted to int.</p>

<p>Also setting smallDelta to a decimal value in an options array to be used in setOptions method doesn't work (i assume the options is somehow translated to a setSmallDelta call)</p>

<p>Current workaround is to set the dijit parameter explicitly like this:
$formelement-&gt;setDijitParam('smallDelta', 0.01);</p>

<p>Trivial correction is to change the setSmallDelta parameter type from int to float.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2011-04-22T22:45:41.000+0000</p> 
        <div class="body">
            <p>Patch and tests for this issue. Can set small and large deltas to decimal values and min and max values to decimal.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-05-02T19:16:44.000+0000</p> 
        <div class="body">
            <p>Patches applied to trunk and 1.11 release branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2011-07-28T15:30:21.000+0000</p> 
        <div class="body">
            <p>Pull request for porting the patch in ZF2 is sent: <a href="https://github.com/zendframework/zf2/pull/270">https://github.com/zendframework/zf2/pull/270</a></p>

        </div>
    </div>
    </div>

