<h2>ZF-1683: Write offline functional tests for service classes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Task</dd>

    <dt>Created:</dt>
    <dd>2007-07-05T19:35:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-17T13:50:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Postponed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Right now, all testing of the various service classes is conducted via online tests. The online components of these tests needs to be mocked out and used to build offline functional tests.</p>

<p>While this likely wouldn't catch any new bugs, it would significantly speed up the build/test cycle and enable automated tests to be run.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-02-26T17:23:08.000+0000</p> 
        <div class="body">
            <p>This is now possible, since for protocol v2 support I added a mock HTTP adapter for offline testing.</p>

<p>It's just a matter of going through and porting some of the online tests to offline now.</p>

        </div>
    </div>
    </div>

