<h2>ZF-11188: Ipv6 host</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-18T02:24:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-03T15:47:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Uri</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11334">ZF-11334</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13937/ZF-11188.patch">ZF-11188.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Actualy it's not possible to validate an url contains an ipv6 host with Zend_Uri, like <a href="http://www.ietf.org/rfc/rfc2732.txt">http://www.ietf.org/rfc/rfc2732.txt</a></p>

<p>This affect many others componements, like Zend_Http_Client_Adapter, that could run fine if validation passed.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2011-03-18T02:38:58.000+0000</p> 
        <div class="body">
            <p>Code to reproduce:</p>

<pre class="highlight"><code>&lt;?php
require_once 'Zend/Uri.php';

var_dump(Zend_Uri::check('<a href="http://[::1]/foo.html">http://[::1]/foo.html</a>', 'Uri'));</code></pre>

<p>I would propose to use Zend_Validate_Hostname for the hostname part, I think running the zend_validate_hostname unittests on zend_uri_http would reveal more flaws.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T05:38:10.000+0000</p> 
        <div class="body">
            <p>Zend_Validate_Hostname does not detect IPv6 addresses with hex decimal f in them before r23900</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T05:45:55.000+0000</p> 
        <div class="body">
            <p>Reproducing test case plus fix. Applying patch had no visible consequence w.r.t execution of test suite.</p>

<p>NOTE: Your ZF repo must be at r23900 or higher due to dependence on fix for ZF-11334</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T05:48:03.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23901</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-03T15:47:27.000+0000</p> 
        <div class="body">
            <p>Fixed in release branch 1.11 at r23970</p>

        </div>
    </div>
    </div>

