<h2>ZF-10330: Zend_Form_Decorator_HtmlTag does not render twice the same when using options (openOnly/closeOnly/noAttribs)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-08-17T22:51:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7320">ZF-7320</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form_Decorator_HtmlTag does not render twice the same string when used with options openOnly/closeOnly/noAttribs. This is because these options are removed while rendering. Then any subsequent rendering will not have original options anymore. Here is a simple test case:</p>

<pre class="highlight"><code>
&lt;?php
include('Zend/Form/Decorator/HtmlTag.php');

$deco = new Zend_Form_Decorator_HtmlTag();
$deco-&gt;setOptions(array('class' =&gt; 'myClass', 'openOnly' =&gt; true));
$content = "hello world";

echo $deco-&gt;render($content); // OK: This will print only opening tag
echo "\n";
echo $deco-&gt;render($content); // WRONG: This will print both tag
</code></pre>

<p>This test case generate the following HTML:</p>

<pre class="highlight"><code>
</code></pre><div class="myClass"><code>hello world
</code><div class="myClass"><code>hello world</code><div><code>


</code><p><code>I would suggest to modify Zend so the options are never removed from the array $this-&gt;_options but instead temporarily removed from the array which is only used while rendering. So the source file would look like that:</code></p><code>

</code><pre class="highlight"><code><code>
    public function render($content)
    {
        $tag       = $this-&gt;getTag();
        $placement = $this-&gt;getPlacement();
        $noAttribs = $this-&gt;getOption('noAttribs');
        $openOnly  = $this-&gt;getOption('openOnly');
        $closeOnly = $this-&gt;getOption('closeOnly');

        $attribs = null;
        if (!$noAttribs) {
            $attribs = $this-&gt;getOptions();
            
            // Prevent reserved options to appear in HTML
            unset($attribs['noAttribs']);
            unset($attribs['openOnly']);
            unset($attribs['closeOnly']);
        }

        [...]
</code></code></pre><code>
</code></div><code></code></div><code></code></div><code></code>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adrien Crivelli (powerkiki) on 2010-08-17T23:06:34.000+0000</p> 
        <div class="body">
            <p>This is somewhat related to the old issue ZF-7320 for Matthew mentioned the same bug as explained in this issue. However as it was only a comment and nothing changed since then (one year), I reckon it is ok to fill a new, specific issue about that.</p>

        </div>
    </div>
    </div>

