<h2>ZF-10737: Improvement of .htaccess RewriteRule</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-11-24T02:59:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-15T00:53:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The file "Zend/Tool/Project/Context/Zf/HtaccessFile.php" contains following rules.</p>

<p>RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.<em>$ - [NC,L]
RewriteRule ^.</em>$ index.php [NC,L]</p>

<p>This rules can be optimized by the following change</p>

<p>RewriteEngine On
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [NC,L]
RewriteRule ^ index.php [NC,L]</p>

<p>The only change is, that the RewriteRule not looks like: RewriteRule ^
This means, match every pattern that starts. Witch is the same as ^.*$. The parsing of the regex rule might be some millisecond or nanosecond faster then the old method.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

