<h2>ZF-11398: Model resource types not autoloading in application</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-23T06:42:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-23T23:51:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I had a number of models and related classes (mappers and dbtables) in a module and followed the structure and 'namespace' convention so that the classes would be autoloaded without no configuration required (example, Module_Model_Name would discover the class located in application/modules/module/models/Name.php).</p>

<p>However, I decided to move some of the models to be directly under the application, as they are generic and would be needed across multiple modules. My configuration is set such that appnamespace = "Application"</p>

<p>I moved the models to application/models and renamed them using the form Application_Model_Name. Now, I just get 'class not found' errors from PHP - I've tried a number of 'fixes', including setting the resource types specifically in the application bootstrap as per <a href="http://framework.zend.com/manual/1.10/en/zend.loader.autoloader-resource.html">http://framework.zend.com/manual/1.10/…</a>, but no joy.</p>

<p>Can we have the application namespace work like the modules?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2011-05-23T07:29:44.000+0000</p> 
        <div class="body">
            <p>Closing as not an issue.</p>

<p>Please direct support requests to either the mailing list, or #zftalk on freenode irc. and provide an outline of your directory structure, and the rest of your configuration.</p>

<p>The resources for the application namespace are loaded in the same way as the module resource, they simply use the namespace from the config rather than the module name.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stuart Jones (horuskol) on 2011-05-23T23:51:44.000+0000</p> 
        <div class="body">
            <p>Apologies if this was the wrong place - but I was doing exactly as the manual instructed (as per the information in the description) and not getting the expected behaviour.</p>

        </div>
    </div>
    </div>

