<h2>ZF-1382: missing method Zend_Locale::getCountry() and Zend_Locale::get[Country|Language]Translation() with empty parameter list</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2007-05-14T15:02:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marc Bennewitz (GIATA mbH) (mben)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>missing method Zend_Locale::getCountry()</p>

<p>Than it is very simple to get the translated country:</p>

<pre class="highlight"><code>
$locate = new Zend_Locale('en_US');
$locale2 = new Zend_Locale('de_DE');
echo $locale-&gt;getCountryTranslation($locale2-&gt;getCountry());  // Germany
echo $locale-&gt;getCountryTranslation($locale-&gt;getCountry());  // United States
echo $locale-&gt;getCountryTranslation();  // United States
echo $locale-&gt;getCountryTranslation(null, $locale2);  // Vereinigte Staaten
</code></pre>

<p>use empty param to translate language:</p>

<pre class="highlight"><code>
$locate = new Zend_Locale('en_US');
$locale2 = new Zend_Locale('de_DE');
echo $locale-&gt;getLanguageTranslation($locale2-&gt;getLanguage());  // German
echo $locale-&gt;getLanguageTranslation($locale-&gt;getLanguage());  // english
echo $locale-&gt;getLanguageTranslation();  // english
echo $locale-&gt;getLanguageTranslation(null, $locale2);  // Englisch
</code></pre>

<p>If parameter $what not set or null use $this-&gt;...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-05-14T16:08:05.000+0000</p> 
        <div class="body">
            <p>For receiving the translation for a country just use
getTranslation("country", $locale-&gt;getRegion());</p>

<p>for a language use
getTranslation("language", $locale-&gt;getLanguage());</p>

<p>The requested data can already be returned with actual API.
This should already be stated out in the actual documentation.</p>

<p>No need to add aditional functions.</p>

        </div>
    </div>
    </div>

