<h2>ZF-11539: http://zendframework.com/about/casestudies</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-07T22:47:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-04T13:53:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11491">ZF-11491</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>I noticed the following issue @ <a href="http://zendframework.com/about/casestudies">http://zendframework.com/about/casestudies</a></p>

<p>The footer div hovers over the second base pane div instead of being pushed to the bottom of the page like the other "about" pages. Scroll down about 1/4 of the page to see the issue @ Magento. This was rendered the same in Firefox 5.0 and Safari 5.0.5 and Chrome 12.0.742.112.</p>

<p>In trying to send an email regarding this issue @ <a href="http://zendframework.com/contact">http://zendframework.com/contact</a>
I was unable to submit the CONTACT FORM due to "Input error: Invalid referer" regarding the CAPTCHA plugin. On submission "Missing Captcha Fields" is returned and the email is not submitted.</p>

<p>I did not see any other way to contact the Zend Team so I submitted the issue here. Maybe someone can forward it to a site maintainer @ zendframework.com.</p>

<p>Thanks,</p>

<p>MG</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-12T19:12:00.000+0000</p> 
        <div class="body">
            <p>We're getting changes to the case studies page soon; most of these are out-of-date, but I need to get approval from marketing as to whether or not to remove them and/or replace them (and content for the latter!). While I may be able to fix the layout as an interim measure, I'd rather not do so if we'll be changing the page entirely anyways.</p>

<p>Regarding the captcha, we were hit by ZF-10991, which I've now fixed -- and I've deployed the fix to the site.</p>

        </div>
    </div>
    </div>

