<h2>ZF-10422: Zend_Form_Decorator_ViewHelper doesn't allow for the creation of custom buttonTypes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-09-05T14:52:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If a Form element decorated with a viewHelper is of Zend_Form_Decorator_ViewHelper::_buttonTypes, it takes it's value from it's label. However, if you have a Element that doesn't extend any of these buttonTypes, but still renders out a form button, it ends up with no value.</p>

<p>Came across then when implementing the JQuery's button() for submit buttons.</p>

<p>class My_ZendX_JQuery_View_Helper_SubmitButton extends ZendX_JQuery_View_Helper_UiWidget
{
    public function submitButton($id, $value = "", array $params = array(), array $attribs = array())
    {
        $attribs = $this-&gt;_prepareAttributes($id, $value, $attribs);</p>

<pre><code>    if(!isset($params['start']) &amp;&amp; is_numeric($value)) {
        $params['start'] = $value;
    }

    if(count($params)) {
        $params = ZendX_JQuery::encodeJson($params);
    } else {
        $params = '{}';
    }

    $js = sprintf('%s("#%s").button(%s);',
        ZendX_JQuery_View_Helper_JQuery::getJQueryHandler(),
        $attribs['id'],
        $params
    );

    $this-&gt;jquery-&gt;addOnLoad($js);

    return $this-&gt;view-&gt;formSubmit($id, $value, $attribs);
}
</code></pre>

<p>}</p>

<p>The class delegates the rendering to formSubmit, but because My_ZendX_JQuery_View_Helper_Button doesn't extend any class named in _buttonTypes, $value is null, as the code in getValue doesn't call getLabel as it doesn't identify it as a buttonType.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

