<h2>ZF-1008: Cannot search by Artist</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-02T15:23:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.2 (06/Apr/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following code produces Uncaught exception 'Zend_Service_Exception' with message 'The following parameters are invalid: Artist'</p>

<pre class="highlight"><code>&lt;?php

require_once 'Zend/Service/Amazon.php';
$amazon = new Zend_Service_Amazon('AMAZON_API_KEY');
$response = $amazon-&gt;itemSearch(array('SearchIndex' =&gt; 'Music', 'Artist' =&gt; 'Amy Winehouse'));

?&gt;</code></pre>

<p>According to the Amazon docs (<a href="http://www.amazon.com/gp/aws/sdk/main.html/103-9285448-4703844?s=AWSEcommerceService&amp;v=2005-10-05&amp;p=ApiReference/ItemSearchOperation">http://amazon.com/gp/aws/…</a>) Artist is a valid parameter.</p>

<p>So please add it to the list of valid parameters. I added it in my copy (version 0.8.0) at line 949 of Zend/Service/Amazon.php</p>

<p>Thanks!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris van der Wel (kritz) on 2007-03-02T15:23:54.000+0000</p> 
        <div class="body">
            <p>fixed typo.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-04T17:40:10.000+0000</p> 
        <div class="body">
            <p>I believe this issue to have been resolved with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4357">SVN r4357</a>. If this is not the case, please feel free to reopen with additional comment.</p>

        </div>
    </div>
    </div>

