<h2>ZF-11394: Testcase has bad doc block that makes auto-complete less efficient</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-21T12:59:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-08T21:18:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.9 (14/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rafael Machado Dohms (rdohms)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Rafael Machado Dohms (rdohms)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Test_PHPUnit</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14220/testcase_patch.diff">testcase_patch.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Test_PHPUnit_ControllerTestCase class has a bad doc block in getRequest and getResponse.</p>

<p>The doc block reports the return to be a Zend_Controller_Request_Abstract/Zend_Controller_Response_Abstract, when writing tests with this it means the autocomplete does not pickup in specific functions available in the Zend_Controller_Request_HttpTestCase/Zend_Controller_Response_HttpTestCase classes, making auto-complete less efficient.</p>

<p>Since the method always returns a Zend_Controller_Request_HttpTestCase i recommend altering the docblock.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rafael Machado Dohms (rdohms) on 2011-05-21T13:00:45.000+0000</p> 
        <div class="body">
            <p>I have written a patch for this. I have a CLA but i need to setup my svn env for contributing, this is easier right now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rafael Machado Dohms (rdohms) on 2011-06-11T22:37:24.000+0000</p> 
        <div class="body">
            <p>Updated doc blocks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rafael Machado Dohms (rdohms) on 2011-07-08T21:17:36.000+0000</p> 
        <div class="body">
            <p>Not merged into release-1.11 branch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rafael Machado Dohms (rdohms) on 2011-07-08T21:18:12.000+0000</p> 
        <div class="body">
            <p>Merged into branch.</p>

        </div>
    </div>
    </div>

