<h2>ZF-10479: Setting value on Zend_Dojo_Form_Element_HorizontalSlider does not work in programmatic mode</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-09-21T07:41:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-01T14:31:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Webdevilopers (tridem)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Martijn Swaagman (swaagie)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10480">ZF-10480</a></li>
            <li><a href="/issues/browse/ZF-11301">ZF-11301</a></li>
            <li><a href="/issues/browse/ZF-10480">ZF-10480</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13856/Zend_Dojo_View_Helper_Slider.patch">Zend_Dojo_View_Helper_Slider.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Setting a value on the slider does not work in programmatic mode. - Declarative works fine.</p>

<pre class="highlight"><code>
&lt;?
class Dojo_Form_Slider extends Zend_Dojo_Form
{
    public function init()
    {
        $severityElement = new Zend_Dojo_Form_Element_HorizontalSlider('severity');
        $severityElement-&gt;setValue(2);
        $severityElement-&gt;setMinimum(1);
        $severityElement-&gt;setMaximum(3);
        $severityElement-&gt;setDiscreteValues(100);
        $severityElement-&gt;setBottomDecorationLabels(array(
            'easy', 'medium', 'hard'
        ));
        $severityElement-&gt;setBottomDecorationParams(array(
            'list' =&gt; array(
                'style' =&gt; 'height:1em; font-size=75%;color:gray;',
            )
        ));
        $this-&gt;addElement($severityElement);
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Martijn Swaagman (swaagie) on 2011-04-23T09:31:47.000+0000</p> 
        <div class="body">
            <p>Correct final patch, overrides patch of bug 11301</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-05-02T20:07:32.000+0000</p> 
        <div class="body">
            <p>Applied to trunk and 1.11 release branch, and noted that it supercedes ZF-11301 patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2011-08-01T14:31:37.000+0000</p> 
        <div class="body">
            <p>Pull request for porting the patch in ZF2 is sent: <a href="https://github.com/zendframework/zf2/pull/311">https://github.com/zendframework/zf2/pull/311</a></p>

        </div>
    </div>
    </div>

