<h2>ZF-12433: Zend\Http\Request documentation inacurate</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-10-02T12:21:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-02T12:41:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
            <li>ZF2</li>
            <li>Zend\Http\Request</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>All examples and method documentation out of date <a href="http://framework.zend.com/manual/2.0/en/modules/zend.http.request.html">http://framework.zend.com/manual/2.0/…</a>
And here is the pull request that attempts to fix that: <a href="https://github.com/zendframework/zf2-documentation/pull/340">https://github.com/zendframework/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Uncle Fred (uncle-fred) on 2012-10-02T12:23:40.000+0000</p> 
        <div class="body">
            <p>Thought so. This one went to ZF1 project. How do I select ZF2 fro the drop down if there is no such option?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-10-02T12:35:36.000+0000</p> 
        <div class="body">
            <p>ZF2 issues have been moved to GitHub:  <a href="https://github.com/zendframework/zf2/issues">https://github.com/zendframework/zf2/issues</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Uncle Fred (uncle-fred) on 2012-10-02T12:41:19.000+0000</p> 
        <div class="body">
            <p>I see. Thanks</p>

        </div>
    </div>
    </div>

