<h2>ZF-11391: Typo in Zend_Validate manual page for Zend_Validate_Digits</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-05-20T12:32:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-24T20:18:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.7 (02/Jun/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Shinya Ohyanagi (heavenshell)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi, I found typo in <a href="http://framework.zend.com/manual/en/zend.validate.set.html#zend.validate.set.digits">http://framework.zend.com/manual/en/…</a></p>

<p>It might be Zend_Validate_Digits not Zend_Valicate_Digit.</p>

<p>Regards,</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-30T16:50:30.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24088
Merged to release-1.11 in r24089</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-07-24T20:18:09.000+0000</p> 
        <div class="body">
            <p>Added to ZF2 with Github Pull #246</p>

        </div>
    </div>
    </div>

