<h2>ZF-1720: Zend_Session setId doesn't work right from PHP CLI</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-07-13T14:53:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-01-09T13:56:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Long (phareous)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you try to use Zend_Session setId to restablish a session inside of a PHP CLI script, you get hit by one or two errors:</p>

<p><em>The session has already been started.  The session id must be set first.</em></p>

<p>Also if your script happens to output anything to the screen:</p>

<p><em>You must call Zend_Session::setId() before any output has been sent to the browser; output started in</em></p>

<p>(This shouldn't matter because you're using a CLI so headers has no bearing on anything. There should be a way to override this check)</p>

<p>The code I am using is as simple as:</p>

<pre class="highlight"><code>
Zend_Session::setId($input['TOKEN']);
Zend_Session::start();
</code></pre>

<p>It makes no difference if I call Zend_Session::destroy() prior to this. The code above works fine from CLI using Zend_XMLRpc, but it won't work if I call the functions directly from my own CLI script.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michael Long (phareous) on 2007-07-13T15:03:30.000+0000</p> 
        <div class="body">
            <p>Although I don't know all the ramifications, etc., but one easy solution I might suggest is to add an IF statement around the first two checks, like this:</p>

<p>if (php_sapi_name() != 'cli')
{
        if (defined('SID')) {
            throw new Zend_Session_Exception('The session has already been started.  The session id must be set first.');
        }</p>

<pre><code>    if (headers_sent($filename, $linenum)) {
        throw new Zend_Session_Exception("You must call ".__CLASS__.'::'.__FUNCTION__.
            "() before any output has been sent to the browser; output started in {$filename}/{$linenum}");
    }
</code></pre>

<p>}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:33.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:12:02.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-04-22T11:00:00.000+0000</p> 
        <div class="body">
            <p>Zend_Session (currently) is not supported in the CLI environment.  This is in part due to the fact that php's ext/session is unpredictable in the CLI env.</p>

<p>Scheduling for 2.0 to evaluate.</p>

<p>Updating project management info.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-01-09T13:56:25.000+0000</p> 
        <div class="body">
            <p>Unsupported use case, if you think this should be a supported use case, please add comments here:</p>

<p><a href="http://framework.zend.com/wiki/display/ZFDEV/Zend_Session+2.0">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
    </div>

