<h2>ZF-11382: Unable to retrieve metadata from pdf using Zend_Pdf</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-16T19:55:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-27T02:48:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Postponed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Have successfully created PDF using Zend_Pdf, but cannot retrieve metadata.  The code:
$pdf = Zend_Pdf::load($pdfPath);  //I can open this PDF and am able to see and save the xmp
$metadata = $pdf-&gt;getMetadata();  //$metadata is null</p>

<p>The xmp file, saved from the xmp dialogue box after opening the PDF is:</p>

<p>&lt;?xpacket begin="ï»¿" id="W5M0MpCehiHzreSzNTczkc9d"?&gt;
www.w3.org/1999/02/22-rdf-syntax-ns#"&gt;
      D:201105030111-08'00'XMP UsernameXMP ProducerXMP TheraScan2011-05-08T13:54:53ZXMP Therapeias Health Management
            XMP Subject
            batch6747.pdf
            XMP Username
            </p>

&lt;?xpacket end="w"?&gt;

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-27T02:47:40.000+0000</p> 
        <div class="body">
            <p>Is this still an issue?  Can you supply us with the actual PDF so we can reproduce the issue?</p>

        </div>
    </div>
    </div>

