<h2>ZF-18: Translate font changes in Zend_Pdf English documentation to other languages</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2006-06-17T12:50:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Willie Alberty (willie)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6">ZF-6</a></li>
            <li><a href="/issues/browse/ZF-14">ZF-14</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>ZF-6 and ZF-14 added new functionality and changed the existing public API for using fonts. The English manual has been updated appropriately. The other manual translations now need to be updated.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2006-06-17T12:53:44.000+0000</p> 
        <div class="body">
            <p>Linked to relevant issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:16:40.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.6.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-01-30T14:35:02.000+0000</p> 
        <div class="body">
            <p>Translation teams trace changes themselves.</p>

        </div>
    </div>
    </div>

