<h2>ZF-10702: Zend_Cache_Backend cannot attach logger form application.ini</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-11-17T16:52:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-11T15:02:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bartosz Cembor (cemborek)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13639/10702.patch">10702.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>resources.cachemanager.foo.backend.logger = something
gives $this-&gt;_directives['logger'] = someting<br />
in Zend_Cache_Backend 
{quote}if ($this-&gt;_directives['logger'] instanceof Zend_Log) {
    return;
}
Zend_Cache::throwException('Logger object is not an instance of Zend_Log class.');
{quote}
i think there should alsow be check if $this-&gt;_directives['logger'] instanceof Zend_Config and used Zend_Log::factory then</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bartosz Cembor (cemborek) on 2011-02-11T15:02:11.000+0000</p> 
        <div class="body">
            <p>Patch attached</p>

        </div>
    </div>
    </div>

