<h2>ZF-11127: cloning Zend_Controller_Action_Helper_ViewRenderer does not separates _viewSuffix properly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-01T13:15:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-03T17:36:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{{Zend_Controller_Action_Helper_ViewRenderer::_viewSuffix}} can become a reference after {{Zend_Controller_Action_Helper_ViewRenderer::init()}} is called, which results in the following behavior:</p>

<pre class="highlight"><code>
$a = new Zend_Controller_Action_Helper_ViewRenderer;
$a-&gt;init();
$a-&gt;setViewSuffix('A');

var_dump($a-&gt;getViewSuffix()); // "A"

$b = clone $a;
$b-&gt;setViewSuffix('B');

var_dump($a-&gt;getViewSuffix()); // "B"
</code></pre>

<p>This affects {{Zend_View_Helper_Action}}, which clones the {{viewRenderer}} helper to avoid side effects. If the sub-request changes the _viewSuffix property, it also changes in the original request.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by arnaud-lb (arnaud-lb) on 2011-03-01T13:21:17.000+0000</p> 
        <div class="body">
            <p>{{Zend_Controller_Action_Helper_ViewRenderer::_viewSuffix}} becomes a reference after calling {{$this-&gt;_inflector-&gt;setStaticRuleReference('suffix', $this-&gt;_viewSuffix)}} in {{init()}}.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T19:26:23.000+0000</p> 
        <div class="body">
            <p>I created a unit test to reproduce your issue:</p>

<pre class="highlight"><code>
Index: tests/Zend/Controller/Action/Helper/ViewRendererTest.php
===================================================================
--- tests/Zend/Controller/Action/Helper/ViewRendererTest.php    (revision 23911)
+++ tests/Zend/Controller/Action/Helper/ViewRendererTest.php    (working copy)
@@ -839,6 +839,25 @@
         $body = $this-&gt;response-&gt;getBody();
         $this-&gt;assertContains('SampleZfHelper invoked', $body, 'Received ' . $body);
     }
+
+    /**
+     * @group ZF-11127
+     */
+    public function testViewSuffixInstanceNotSharedWhenViewHelperIsCloned()
+    {
+        $a = new Zend_Controller_Action_Helper_ViewRenderer();
+        $a-&gt;init();
+        $a-&gt;setViewSuffix('A');
+
+        $this-&gt;assertEquals('A', $a-&gt;getViewSuffix());
+
+        $b = clone $a;
+        $this-&gt;assertEquals('A', $b-&gt;getViewSuffix());
+        $b-&gt;setViewSuffix('B');
+
+        $this-&gt;assertEquals('B', $b-&gt;getViewSuffix());
+        $this-&gt;assertNotEquals('B', $a-&gt;getViewSuffix());
+    }

     protected function _normalizePath($path)
     {
</code></pre>

<p>and ran it:</p>

<pre class="highlight"><code>
[webadmin@spiral tests]$ ./runtests.sh ZF-11127
++ phpunit --verbose --group ZF-11127 AllTests
PHPUnit 3.5.13 by Sebastian Bergmann.

.

Time: 7 seconds, Memory: 413.25Mb

OK (1 test, 4 assertions)
</code></pre>

<p>but it did not show the behavior you report.</p>

<p>It's likely this has already been fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T19:30:26.000+0000</p> 
        <div class="body">
            <p>Unit test committed to trunk r23914</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-03T17:36:43.000+0000</p> 
        <div class="body">
            <p>Merged to release branch 1.11 in r23976</p>

        </div>
    </div>
    </div>

