<h2>ZF-10958: addDisplayGroup creates input fields twice when using long id's (names)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-17T08:09:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-22T19:21:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Halbach Media (halbach_media)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Richard Tuin (richardtuin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11729">ZF-11729</a></li>
            <li><a href="/issues/browse/ZF-10387">ZF-10387</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you create a Zend Form and add an Element with an id (name) like 'form_data_id234'. You can easily add this form to a displaygroup using addDisplayGroup().</p>

<p>But if your elements id is too long it will be added to the display group and remains in the "main" form too. (Outside of the desired display group.) So this element exists twice in a form. First it appears in the display group and also outside of the group but inside the form.</p>

<p>As the fields name is identical, this would raise a logical validation error... (You could never be sure which field value will be used as the correct input field value.)</p>

<p>Here are some example names which are too long and will appear twice in the form:
_form_personDetail_communication_COM_4c808f1c19cb1831254439-element
_form_personDetail_communication_COM_4c808f1c19cb1831254439-element</p>

<p>I stumbled upon this error afterI updated from 1.10.7 to 1.11.2. In 1.10.7 everythings works as expected.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Halbach Media (halbach_media) on 2011-01-18T01:07:32.000+0000</p> 
        <div class="body">
            <p>The duplicated fields also appear when you are trying to manually set a field name to something like</p>

<p>"_form_persondetail_communication[123]"</p>

<p>ZF removes the brackets but you will have the fields twice inside your form too.</p>

<p>I assume the fields-id is used as a key to access the field anytime later. So this key might be processed (removing brackets, change length, etc.) will be executed but the "original" id remains untouched anywhere in the form elements config data.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2011-01-20T12:53:06.000+0000</p> 
        <div class="body">
            <p>I was not able to reproduce this issue.
Can you provide a code sample that reproduces this issue?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-01-24T00:26:59.000+0000</p> 
        <div class="body">
            <p>I think, it is not a problem of length, but a problem with the hyphen in the name:</p>

<pre class="highlight"><code>
// Form
$form = new Zend_Form();

$form-&gt;setDecorators(array(
    'FormElements',
    'Form',
));

// Elements
$form-&gt;addElement('text', 'first-name', array(
    'label'      =&gt; 'First name',
    'decorators' =&gt; array(
        'ViewHelper',
        'Label',
    ),
));

$form-&gt;addElement('text', 'lastname', array(
    'label'      =&gt; 'Last name',
    'decorators' =&gt; array(
        'ViewHelper',
        'Label',
    ),
));

// Display group
$form-&gt;addDisplayGroup(array('first-name', 'lastname'), 'name', array(
    'decorators' =&gt; array(
        'FormElements',
        'Fieldset',
    ),
));

echo $form-&gt;render(new Zend_View());
</code></pre>

<pre class="highlight"><code>

    First name
    First name
        Last name
        
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2011-09-22T19:21:46.000+0000</p> 
        <div class="body">
            <p>Issue ZF-11729 is a duplicate of this and is resolved/fixed.
Tests inspected, no need to add additional unit tests for this specific issue.</p>

        </div>
    </div>
    </div>

