<h2>ZF-12480: PHP 5.4: Notice: Array to string conversion in Zend_Validate_Abstract</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2012-12-03T05:31:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-12-03T09:26:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Adrien Crivelli (powerkiki)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-12194">ZF-12194</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Validate_Abstract converts array to string and thus raise notices with PHP 5.4</p>

<p>How to reproduce:</p>

<pre class="highlight"><code>
&lt;?php 

require('Zend/Validate.php');
require('Zend/Validate/NotEmpty.php');

$validator = new Zend_Validate_NotEmpty();
$validator-&gt;isValid(array()); // Will raise a PHP 5.4 notice
</code></pre>

<p>According to what was done for <a href="http://framework.zend.com/issues/browse/ZF-11906">http://framework.zend.com/issues/browse/ZF-11906</a> (specifically in r24807), I suggest the modification of library/Zend/Validate/Abstract.php at line 233 as follow:</p>

<p>Before:</p>

<pre class="highlight"><code>
        } else {
            $value = (string)$value;
        }
</code></pre>

<p>After:</p>

<pre class="highlight"><code>
        } else {
            $value = implode(' ', (array)$value);
        }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

