<h2>ZF-11422: provide cascading write operations on Zend_Db_Table_Abstract / Zend_Db_Table_Row_Abstract for arbitrary columns</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-05-31T15:25:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T01:55:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
            <li>cascading</li>
            <li>operations</li>
            <li>relationships</li>
            <li>tables</li>
            <li>write</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6319">ZF-6319</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>At the moment (as of ZF 1.11), cascading write operations such as _cascadeDelete() operate on primary key columns, seemingly due to the assumption that relationships between database tables are established through the primary key of the parent table only.</p>

<p>Why is it necessary to establish a relationship on a column other than a primary key, you ask?</p>

<p>Especially in hybrid web/mobile projects, where data can be generated through a web interface as well as in a mobile app, you need to base your relationships on a uuid rather than an autoincremented ID, since the sequence of IDs in the web (= usually main) and the mobile app's database are very likely out of sync (e.g. while the ID sequence in the mobile app has advanced due to the generation of new data, the ID sequence of the same DB table in the main DB will remain unchanged until the next data synchronization. In the meanwhile, there could have been data entered through the web interface as well, resulting in ID conflicts).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-28T22:09:55.000+0000</p> 
        <div class="body">
            <p>Closing as Duplicate of ZF-1103</p>

        </div>
    </div>
    </div>

