<h2>ZF-11749: Zend_Http_UserAgent_AbstractDevice raises a notice on Safari Mobile v5.1 UA with no language</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-19T10:14:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-26T01:18:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marcin Gil (mgil)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is a notice coming from this class on following user agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A5313e Safari/7534.48.3</p>

<p>Notice error is:
Message: Undefined offset: 3
File: Zend/Http/UserAgent/AbstractDevice.php
Line: 557</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-26T01:18:54.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24532
Merged to release-1.11 in r24533</p>

<p>No forward-port to ZF2 as this component is not in the public ZF2 Git repository</p>

        </div>
    </div>
    </div>

