<h2>ZF-1392: useDefaultControllerAlways : default module renamed to Default !</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-05-16T02:48:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10526/zf-1392.patch">zf-1392.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
require_once('Zend/Controller/Front.php');
$controller = Zend_Controller_Front::getInstance();
$controller-&gt;setResponse('Zend_Controller_Response_Http');
$controller-&gt;setParam('useDefaultControllerAlways', true);
$controller-&gt;addControllerDirectory('../application/Pms/controllers'); // Default route
$controller-&gt;throwExceptions(true);

$controller-&gt;dispatch();
</code></pre>

<p>When browsing / it works ... I am in the index action of my index controller in ../application/Pms/controllers directory
When browsing /test/ , I obtain the following exception :</p>

<pre class="highlight"><code>
<br /><b>Fatal error</b>:  Uncaught exception 'Zend_Controller_Dispatcher_Exception' with message 'Invalid controller class ("Default_IndexController")' in /home/kabdi/workspace/cra/trunk/lib/ZendFramework-0.9.3-Beta/library/Zend/Controller/Dispatcher/Standard.php:250
Stack trace:
#0 /home/kabdi/workspace/cra/trunk/lib/ZendFramework-0.9.3-Beta/library/Zend/Controller/Dispatcher/Standard.php(187): Zend_Controller_Dispatcher_Standard-&gt;loadClass('IndexController')
#1 /home/kabdi/workspace/cra/trunk/lib/ZendFramework-0.9.3-Beta/library/Zend/Controller/Front.php(754): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#2 /home/kabdi/workspace/cra/trunk/deploy/index.php(12): Zend_Controller_Front-&gt;dispatch()
#3 {main}
  thrown in <b>/home/kabdi/workspace/cra/trunk/lib/ZendFramework-0.9.3-Beta/library/Zend/Controller/Dispatcher/Standard.php</b> on line <b>250</b><br /></code></pre>

<p>It search for <em>Default_IndexController</em> class !
After some investigations, it occurs in <em>Zend_Controller_DispatcherStandard::getDefaultControllerClass</em> method, the moduleName is formatted from <em>default</em> to <em>Default</em> by <em>formatModuleName</em> call (line 326)</p>

<p>This bug does not occur in ZF's older versions ...</p>

<p>Kal</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-23T10:05:40.000+0000</p> 
        <div class="body">
            <p>Assigning to Matthew.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eric Coleman (eric) on 2007-06-06T01:29:41.000+0000</p> 
        <div class="body">
            <p>Matthew,</p>

<p>This is what im using, possible what is also the proper solution.  I used the code from another method in the file, because it looks like you encountered this issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eric Coleman (eric) on 2007-06-06T01:30:11.000+0000</p> 
        <div class="body">
            <p>(sorry, I'm referring to my attachment)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-06-13T15:34:22.000+0000</p> 
        <div class="body">
            <p>Patch applied in r5288, along with a unit test that confirmed the buggy behaviour (and now reports success)</p>

        </div>
    </div>
    </div>

