<h2>ZF-10602: Small typo in PHPDoc comment</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-10-27T00:43:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-27T07:04:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>Index: Zend/Validate/Interface.php
===================================================================
--- Zend/Validate/Interface.php (revision 23259)
+++ Zend/Validate/Interface.php (working copy)
@@ -36,7 +36,7 @@
      *
      * @param  mixed $value
      * @return boolean
-     * @throws Zend_Valid_Exception If validation of $value is impossible
+     * @throws Zend_Validate_Exception If validation of $value is impossible
      */
     public function isValid($value);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-10-27T07:04:24.000+0000</p> 
        <div class="body">
            <p>Patch applied to trunk and 1.11 release branch; will release with 1.11.1</p>

        </div>
    </div>
    </div>

