<h2>ZF-10156: Zend_Db issue</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-07-14T14:56:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-14T15:28:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                M Z (charmdream)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Here is code:</p>

<p>$db = Zend_Db::factory('Pdo_Mysql', array(
'host' =&gt; '****',
'username' =&gt; '****',
'password' =&gt; '****',
'dbname' =&gt; 'test_db'
));
$result = $db-&gt;fetchAll('SELECT * FROM bugs_products WHERE bug_id = ?', 1);</p>

<p>Zend_Debug::dump($result);</p>

<p>Zend_Debug::dump($db-&gt;describeTable('bugs_products'));</p>

<p>Here is output:</p>

<p>array(1) {
[0] =&gt; array(5) {
["bug_id"] =&gt; string(1) "1"
["product_id"] =&gt; string(1) "0"
["bugs_products"] =&gt; string(1) "4"
["test_db"] =&gt; string(1) "5"
["def"] =&gt; string(1) "6" }
}</p>

<p>array(6) {
["bug_id"] =&gt; array(14) {
["SCHEMA_NAME"] =&gt; NULL
["TABLE_NAME"] =&gt; string(13) "bugs_products"
["COLUMN_NAME"] =&gt; string(6) "bug_id"
["COLUMN_POSITION"] =&gt; int(1)
["DATA_TYPE"] =&gt; string(3) "int"
["DEFAULT"] =&gt; NULL
["NULLABLE"] =&gt; bool(false)
["LENGTH"] =&gt; NULL
["SCALE"] =&gt; NULL
["PRECISION"] =&gt; NULL
["UNSIGNED"] =&gt; NULL
["PRIMARY"] =&gt; bool(true)
["PRIMARY_POSITION"] =&gt; int(1)
["IDENTITY"] =&gt; bool(false)
}
["product_id"] =&gt; array(14) {
["SCHEMA_NAME"] =&gt; NULL
["TABLE_NAME"] =&gt; string(13) "bugs_products"
["COLUMN_NAME"] =&gt; string(10) "product_id"
["COLUMN_POSITION"] =&gt; int(2)
["DATA_TYPE"] =&gt; string(3) "int"
["DEFAULT"] =&gt; NULL
["NULLABLE"] =&gt; bool(false)
["LENGTH"] =&gt; NULL
["SCALE"] =&gt; NULL
["PRECISION"] =&gt; NULL
["UNSIGNED"] =&gt; NULL
["PRIMARY"] =&gt; bool(false)
["PRIMARY_POSITION"] =&gt; NULL
["IDENTITY"] =&gt; bool(false)
}
["name"] =&gt; array(14) {
["SCHEMA_NAME"] =&gt; NULL
["TABLE_NAME"] =&gt; string(13) "bugs_products"
["COLUMN_NAME"] =&gt; string(4) "name"
["COLUMN_POSITION"] =&gt; int(3)
["DATA_TYPE"] =&gt; string(7) "varchar"
["DEFAULT"] =&gt; NULL
["NULLABLE"] =&gt; bool(true)
["LENGTH"] =&gt; string(2) "50"
["SCALE"] =&gt; NULL
["PRECISION"] =&gt; NULL
["UNSIGNED"] =&gt; NULL
["PRIMARY"] =&gt; bool(false)
["PRIMARY_POSITION"] =&gt; NULL
["IDENTITY"] =&gt; bool(false)
}
["col4"] =&gt; array(14) {
["SCHEMA_NAME"] =&gt; NULL
["TABLE_NAME"] =&gt; string(13) "bugs_products"
["COLUMN_NAME"] =&gt; string(4) "col4"
["COLUMN_POSITION"] =&gt; int(4)
["DATA_TYPE"] =&gt; string(3) "int"
["DEFAULT"] =&gt; NULL
["NULLABLE"] =&gt; bool(true)
["LENGTH"] =&gt; NULL
["SCALE"] =&gt; NULL
["PRECISION"] =&gt; NULL
["UNSIGNED"] =&gt; NULL
["PRIMARY"] =&gt; bool(false)
["PRIMARY_POSITION"] =&gt; NULL
["IDENTITY"] =&gt; bool(false)
}
["col5"] =&gt; array(14) {
["SCHEMA_NAME"] =&gt; NULL
["TABLE_NAME"] =&gt; string(13) "bugs_products"
["COLUMN_NAME"] =&gt; string(4) "col5"
["COLUMN_POSITION"] =&gt; int(5)
["DATA_TYPE"] =&gt; string(3) "int"
["DEFAULT"] =&gt; NULL
["NULLABLE"] =&gt; bool(true)
["LENGTH"] =&gt; NULL
["SCALE"] =&gt; NULL
["PRECISION"] =&gt; NULL
["UNSIGNED"] =&gt; NULL
["PRIMARY"] =&gt; bool(false)
["PRIMARY_POSITION"] =&gt; NULL
["IDENTITY"] =&gt; bool(false)
}
["col6"] =&gt; array(14) {
["SCHEMA_NAME"] =&gt; NULL
["TABLE_NAME"] =&gt; string(13) "bugs_products"
["COLUMN_NAME"] =&gt; string(4) "col6"
["COLUMN_POSITION"] =&gt; int(6)
["DATA_TYPE"] =&gt; string(3) "int"
["DEFAULT"] =&gt; NULL
["NULLABLE"] =&gt; bool(true)
["LENGTH"] =&gt; NULL
["SCALE"] =&gt; NULL
["PRECISION"] =&gt; NULL
["UNSIGNED"] =&gt; NULL
["PRIMARY"] =&gt; bool(false)
["PRIMARY_POSITION"] =&gt; NULL
["IDENTITY"] =&gt; bool(false)
}
}</p>

<p>================
Just to be clear:</p>

<p>This is query result:</p>

<p>array(1) {
  [0] =&gt; array(5) {
    ["bug_id"] =&gt; string(1) "1"
    ["product_id"] =&gt; string(1) "0"
    ["bugs_products"] =&gt; string(1) "4"
    ["test_db"] =&gt; string(1) "5"
    ["def"] =&gt; string(1) "6"
  }
}</p>

<p>This is table columns:</p>

<p>array(6) {
  [0] =&gt; string(6) "bug_id"
  [1] =&gt; string(10) "product_id"
  [2] =&gt; string(4) "name"
  [3] =&gt; string(4) "col4"
  [4] =&gt; string(4) "col5"
  [5] =&gt; string(4) "col6"
}</p>

<p>Why the query result don't match the table definition? Is there anything wrong with code? Or is it a bug?</p>

<p>Hopefully there is someone could help me!</p>

<p>Thanks</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-07-14T14:58:46.000+0000</p> 
        <div class="body">
            <p>My guess would be that every Zend_Db issue is a 'zend_db issue'.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2010-07-14T15:02:15.000+0000</p> 
        <div class="body">
            <p>This is not an issue, Zend_Db returns exactly that what you asked it for.</p>

<p>PS: Please don't abuse the issue tracker as support system, use the mailing list or IRC for those questions.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by M Z (charmdream) on 2010-07-14T15:12:09.000+0000</p> 
        <div class="body">
            <p>Table bugs_products has 6 columns:
    "bug_id" 
    "product_id" 
    "name" 
    "col4" 
    "col5" 
    "col6"</p>

<p>The query is:
   SELECT * FROM bugs_products WHERE bug_id = 1</p>

<p>And return result:
array(1) {
[0] =&gt; array(5) { 
       ["bug_id"] =&gt; string(1) "1" 
       ["product_id"] =&gt; string(1) "0" 
       ["bugs_products"] =&gt; string(1) "4" 
       ["test_zend_db"] =&gt; string(1) "5" 
       ["def"] =&gt; string(1) "6" 
      }
}</p>

<p>The columns don't match. How could this happen?</p>

<p>BTW, I asked the questions in Zend Forums. Someone suggested me to ask here.
Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by M Z (charmdream) on 2010-07-14T15:28:06.000+0000</p> 
        <div class="body">
            <p>Here are my other findings:</p>

<p>It seems if the table has only two columns, it will be good.
But if it has 3 or more columns:
- the first two columns will be correct.
- the third one will be using 
- the fourth will be using 
- the fifth will be ['def']</p>

<p>And once the table has 7 or more columns, it will stop working (the error "CGI/FastCGI has stopped working" message)
BTW, I am using Zend Stutio 7.</p>

        </div>
    </div>
    </div>

