<h2>ZF-10580: Getting an error while doing device detection</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-19T12:26:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-28T01:00:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kevin Schroeder (kschroeder)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Julian Somesan (julian)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13360/index.phtml">index.phtml</a></li>
            <li><a href="/issues/secure/attachment/13361/SPH-D700+user+agent.txt">SPH-D700 user agent.txt</a></li>
            <li><a href="/issues/secure/attachment/13638/ZF-10580-a.patch">ZF-10580-a.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is relatively minor thing, but it breaks the coding standards where code can be run with E_NOTICE turned on.</p>

<p>I'm going through <a href="http://en.wikipedia.org/wiki/List_of_user_agents_for_mobile_phones">http://en.wikipedia.org/wiki/…</a> and seeing how the mobile detection works for WURFL for the various user agents.  It didn't detect mine very well (it found that my Samsung Epic was a generic Android, even though there is a match for the user agent in the XML file).  But I get an E_NOTICE when I tried one of the other user agents.</p>

<p>Mozilla/5.0 (webOS/1.4.0; U; en-US) AppleWebKit/532.2 (KHTML, like Gecko) Version/1.0 Safari/532.2 Pre/1.0</p>

<p>Notice:  Undefined offset: 3 in D:\Program Files (x86)\Zend\ZendServer\share\ZendFramework-1.11.0b1\library\Zend\Http\UserAgent\AbstractDevice.php on line 570</p>

<p>And when I tried</p>

<p>Mozilla/5.0 (Linux; U; Android 2.1-update1; en-us; SPH-D700 Build/ECLAIR) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17</p>

<p>I got</p>

<p>Notice:  Trying to get property of non-object in C:\workspace\Test\library\Wurfl\CapabilitiesHolder.php on line 67</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Business&amp;Decision / Interakting (interakting) on 2010-10-19T14:54:46.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>The first E_NOTICE is now fixed but the second one is not reproductible.</p>

<p>Note that the notice message is coming from the Wurfl Api and not Zend_Http_UserAgent : you have maybe to verify the config of Wurfl Api in C:\workspace\Test\library\Wurfl</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kevin Schroeder (kschroeder) on 2010-10-19T14:56:44.000+0000</p> 
        <div class="body">
            <p>It seems to be an issue with detecting Android-based phones.  I don't think I've been able to detect any of the Android phones I've tried.  I will attach a test script.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kevin Schroeder (kschroeder) on 2010-10-19T14:58:35.000+0000</p> 
        <div class="body">
            <p>This tests with several user agents for different types of phones.  The Android-based phones will not be caught.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Business&amp;Decision / Interakting (interakting) on 2010-10-19T15:15:45.000+0000</p> 
        <div class="body">
            <p>It's strange</p>

<p>In attachment the var_dump of features identified with the second user agent mentionned : 
Mozilla/5.0 (Linux; U; Android 2.1-update1; en-us; SPH-D700 Build/ECLAIR) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Mobile Safari/530.17</p>

<p>I think there is maybe an issue with "$device-&gt;getBrowser()" =&gt; I will study this point</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Business&amp;Decision / Interakting (interakting) on 2010-10-19T16:00:23.000+0000</p> 
        <div class="body">
            <p>getBrowser method fixed : the value of "browser_name" provided by Wurfl is now used instead of the value extracted from UserAgent chain</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-10-26T07:26:23.000+0000</p> 
        <div class="body">
            <p>I've merged the changes from Raphael to the 1.11 release branch, and they'll be incorporated in the 1.11 final release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Julian Somesan (julian) on 2010-11-03T04:57:47.000+0000</p> 
        <div class="body">
            <p>Still not fixed in released ZF 1.11.0 
Trying with Firefox 4 beta 6 
 I got the same " PHP Notice:  Undefined offset: 3 in /usr/local/PEAR/Zend/Http/UserAgent/AbstractDevice.php on line 651"</p>

<p>** if you try with latest wurfl xml file, this notice is not showing. But i presume using some exotic user agent will trigger it again.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adrian Mester (ilogik) on 2011-02-11T05:49:16.000+0000</p> 
        <div class="body">
            <p>The notice in AbstractDevice.php on line 651 still appears in ZF 1.11.3 (to reproduce, use Firefox 4 Beta 11)
Here is the code in question:</p>

<p>if (isset($comment[4])) {
  $result['browser_build'] = trim($comment[4]);
}
$result['browser_language'] = trim($comment[3]); // &lt;-- this line creates the notice</p>

<p>Adding an if to check if $comment[3] is set (just like the one for $comment[4]) should fix the problem, I think.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Teodora Marusca (teo) on 2011-02-11T07:01:25.000+0000</p> 
        <div class="body">
            <p>ZF-10580-a.patch
Added the patch for fixing the issue with " PHP Notice: Undefined offset: 3 in /usr/local/PEAR/Zend/Http/UserAgent/AbstractDevice.php on line 651"</p>

<pre class="literal">

Index: library/Zend/Http/UserAgent/AbstractDevice.php
===================================================================
--- library/Zend/Http/UserAgent/AbstractDevice.php  (revision 23692)
+++ library/Zend/Http/UserAgent/AbstractDevice.php  (working copy)
@@ -648,7 +648,9 @@
                     if (isset($comment[4])) {
                         $result['browser_build'] = trim($comment[4]);
                     }
-                    $result['browser_language'] = trim($comment[3]);
+                   if (isset($comment[3])) {
+                       $result['browser_language'] = trim($comment[3]);
+                   }

</pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bhupendra Singh Thakur (techgyani) on 2011-04-21T06:51:36.000+0000</p> 
        <div class="body">
            <p>This problem also exists in zend 1.11.5 and can be resolved by using the patch above.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-08-02T18:10:03.000+0000</p> 
        <div class="body">
            <p>Can anybody test current trunk for me? I think I may have resolved these issues with ZF-11557.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Leandro Rodrigues Chaves (leandrorc) on 2011-08-20T23:37:39.000+0000</p> 
        <div class="body">
            <p>I remember already got this error in two situations:</p>

<p>1 - At work, using firefox 3.6 in Linux behind a proxy.</p>

<p>2 - At home, using firefox 6 in Windows with no proxy (this one i'm getting right now).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-28T01:00:15.000+0000</p> 
        <div class="body">
            <p>The original issue has been resolved.  Please open a new ticket if you encounter new issues with UA detection.</p>

        </div>
    </div>
    </div>

