<h2>ZF-1051: Zend_Mime::encodeQuotedPrintable E_NOTICE if str is certain length</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-14T12:02:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:55.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.1 (23/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Simon Mundy (peptolab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mime</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is a problem in encodeQuotedPrintable that triggers an E_NOTICE.  Check out line 140.</p>

<pre class="literal">
139                 // Ensure we are not splitting across an encoded character
140                 if (($pos = strrpos(substr($str, 0, $ptr), '=')) &gt;= $ptr - 2) {
141                     $ptr = $pos;
142                 }
143     
144                 // Check if there is a space at the end of the line and rewind
145                 if ($str[$ptr - 1] == ' ') {
146                     --$ptr;
147                 }
</pre>

<p>If {{$ptr}} is 2, and {{$pos = strrpos(substr($str, 0, $ptr), '=')}} evaluates to 0, {{$ptr}} will be assigned a value of 0.<br />
When {{$str[$ptr - 1]}} is evaluated, an E_NOTICE will occur with the message:
{{Uninitialized string offset: -1 in ....}}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2007-03-14T17:52:54.000+0000</p> 
        <div class="body">
            <p>Do you have a snippet of the content that causes the condition? It will help debugging.</p>

<p>Cheers</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-15T13:54:03.000+0000</p> 
        <div class="body">
            <p>Assigning to Nico.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2007-03-18T05:47:24.000+0000</p> 
        <div class="body">
            <p>Fixed in SVN r4097</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-19T11:38:40.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.9.1.</p>

        </div>
    </div>
    </div>

