<h2>ZF-12037: Zend_Service_Amazon_S3::copyObject discards either ACL or other Metadata</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-02-01T21:47:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-01T21:47:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jan Hapke (hopka)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Enrico Zimuel (zimuel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
            <li>Zend_Service_Amazon_S3</li>
            <li>Zend_Service_Amazon_S3::copyObject</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using Zend_Service_Amazon_S3::copyObject without the $meta array, it copies the metadata from the source object to the destination object. However, the ACL of the destination object is always set to private by Amazon S3:
{quote}The default ACL for the copied object is private regardless of the ACL of the source object. To use a different ACL, specify the <em>x-amz-acl</em> header as you would with a regular PUT request.
(source: [<a href="http://doc.s3.amazonaws.com/proposals/copy.html">http://doc.s3.amazonaws.com/proposals/copy.html</a>]){quote}
Specifying the <em>x-amz-acl</em> header however results in Zend_Service_Amazon_S3::copyObject discarding all other Metadata by setting the <em>x-amz-metadata-directive</em> to REPLACE instead of COPY. It is also not possible to change the <em>x-amz-metadata-directive</em> header via the $meta array as it is always overwritten.</p>

<p>So in order to copy a public object including metadata, I have to set both the ACL and the metadata manually in the $meta array when calling copyObject. In my opinion, it would be better if the <em>x-amz-metadata-directive</em> was only set by Zend_Service_Amazon_S3::copyObject if it wasn't already present in the $meta array.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

