<h2>ZF-10456: OpenID SREG extension should check for valid property fields</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-09-15T01:56:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Frank Groeneveld (frenkel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As per the official specification, SREG only accepts a number of fields. There should be a check in the constructor because it might not be obvious otherwise. This code will fix it:</p>

<h1>Index: OpenId/Extension/Sreg.php</h1>

<p>--- OpenId/Extension/Sreg.php   (revision 22938)
+++ OpenId/Extension/Sreg.php   (working copy)
@@ -55,6 +55,15 @@
      */
     public function __construct(array $props=null, $policy_url=null, $version=1.0)
     {
+       /* make sure only properties of the specification are set */
+       if (is_array($props)) {
+           foreach ($props as $name =&gt; $value) {
+               if (!in_array($name, self::getSregProperties())) {
+                   throw new Zend_Exception('Invalid property set for SREG extension: ' . $name);
+               }
+           }
+       }
+
         $this-&gt;_props = $props;
         $this-&gt;_policy_url = $policy_url;
         $this-&gt;_version = $version;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

