<h2>ZF-1557: Unsetting headers requires passing the header in a case-sensitive fashion</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-12T16:58:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following code in Zend_Http_client::setHeaders allows unsetting a header by passing a value of null or false for the header.  However, the name of the header is no converted to lowercase before unsetting it-- However, for setting a header, the name is converted to lowercase.  I think the strtolower call can be moved to be above the if block, provided there is no way to set a upper-case header in Zend_Http_Client.</p>

<pre class="highlight"><code>
// If $value is null or false, unset the header
if ($value === null || $value === false) {
    unset($this-&gt;headers[$name]);

// Else, set the header
} else {
    // Header names are storred lowercase internally.
    $name = strtolower($name);
    if (is_string($value)) $value = trim($value);
    $this-&gt;headers[$name] = $value;
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-12T17:56:32.000+0000</p> 
        <div class="body">
            <p>Assign to Shahar.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-12T17:57:13.000+0000</p> 
        <div class="body">
            <p>Reformat code in description.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-06-13T05:44:21.000+0000</p> 
        <div class="body">
            <p>Thanks for the report.</p>

<p>Fixed in revision 5278 + unit test added to avoid regression.</p>

        </div>
    </div>
    </div>

