<h2>ZF-10799: add htdig to searchbots</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-12-09T00:20:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-18T12:02:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Philip Iezzi (iezzip)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Udo Telaar (udo)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13536/ZF-10799.patch">ZF-10799.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a>ht://Dig</a> is a terribly old search engine software which is still in rare use nowadays.
Standard user agent for <a>ht://Dig</a> is "htdig", see <a href="http://www.htdig.org/attrs.html#user_agent">http://www.htdig.org/attrs.html#user_agent</a></p>

<p>Please patch Zend_Http_UserAgent_Bot:</p>

<pre class="highlight"><code>
Index: Bot.php
===================================================================
--- Bot.php (revision 23462)
+++ Bot.php (working copy)
@@ -64,6 +64,7 @@
         'gigabot', 
         'girafabot', 
         'google', 
+        'htdig', 
         'infoseek', 
         'inktomi', 
         'java', 
</code></pre>

<p>Thanks!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Udo Telaar (udo) on 2010-12-16T07:07:34.000+0000</p> 
        <div class="body">
            <p>htdig bot added like Philip lezzi suggested</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-12-18T12:02:11.000+0000</p> 
        <div class="body">
            <p>Applied to trunk in r2355, merged to release branch 1.11 in r23556.</p>

        </div>
    </div>
    </div>

