<h2>ZF-1098: Missing php-tag in Row/Abstract.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-21T11:24:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.1 (23/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Till Klampaeckel (till)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1080">ZF-1080</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>ZendFramework-0.9.0-Beta/library/Zend/Db/Table/Row</p>

<p>The first line reads "?php", but should be "&lt;?php"</p>

<p>I downloaded the entire framework twice to verify this - the .tgz both times.</p>

<p>You'll notice this error when all of the sudden the entire Abstract.php is served (in plain text).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-21T11:47:27.000+0000</p> 
        <div class="body">
            <p>Duplicate of ZF-1080.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-21T11:47:44.000+0000</p> 
        <div class="body">
            <p>Resolved as duplicate.</p>

        </div>
    </div>
    </div>

