<h2>ZF-11767: zf create db-table.from-database disallow to use force-overwrite without module name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-09-25T14:33:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-02T23:16:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sergey Boroday (simpliest)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Raphael de Almeida (jaguarnet7)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14667/ZF-11767.diff">ZF-11767.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We can't use force-overwrite option if project's db-table models was created by default (without module name definition)
But we can to create models without module name at first time.</p>

<p>Steps to reproduce:</p>

<pre class="highlight"><code>
zf create project demo
cd demo
zf configure db-adapter "adapter=Mysqli&amp;dbname=mysql&amp;host=localhost&amp;username=user&amp;password=user_pass"
zf create db-table.from-database
</code></pre>

<p>all created - ok.</p>

<p>Then try to recreate</p>

<pre class="highlight"><code>
zf create db-table.from-database // Error as expected
zf create db-table.from-database force-overwrite // Error - we should define module name (but we doesn't have it) 
zf create db-table.from-database default force-overwrite // Error - yep, we doesn't created default module, then error expected
zf create db-table.from-database application force-overwrite //Error - same
</code></pre>

<p>So, there no way to recreate....</p>

<p>Workaround
Remove manually all files from application/models/DbTables
And remove appropriate sections for tables in  in .zfproject.xml</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Raphael de Almeida (jaguarnet7) on 2011-09-27T00:30:26.000+0000</p> 
        <div class="body">
            <p>try</p>

<pre class="highlight"><code>
zf create db-table.from-database --force-overwrite=true
</code></pre>

<p>Its ran for me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sergey Boroday (simpliest) on 2011-09-27T09:15:13.000+0000</p> 
        <div class="body">
            <p>Thanks, it works...
But could you give one more advice? Where can i find this in documentation?
Because tool's commandline help does not describe such syntax for keys</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Raphael de Almeida (jaguarnet7) on 2011-09-28T03:17:38.000+0000</p> 
        <div class="body">
            <p>Suggest for improvement documentation</p>

        </div>
    </div>
    </div>

