<h2>ZF-12156: there is a &quot;f&quot; before &lt;?php at the very beginning of Zend/Feed/Writer/Deleted.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-16T17:34:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-09-25T10:46:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                jerome (jerome@chaman.ca)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Writer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-12135">ZF-12135</a></li>
            <li><a href="/issues/browse/ZF-12383">ZF-12383</a></li>
            <li><a href="/issues/browse/ZF-12384">ZF-12384</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend/Feed/Writer/Deleted.php</p>

<p>there is a "f" before &lt;?php at the very beginning of the file from revision 24641</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2012-04-16T18:55:56.000+0000</p> 
        <div class="body">
            <p>Fixed in r24710.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mike Pavlak (mpavlak) on 2012-08-22T13:14:25.000+0000</p> 
        <div class="body">
            <p>Appears this bug persists in 1.11.12 and 1.11.13.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-08-31T11:13:02.000+0000</p> 
        <div class="body">
            <p>Fixed in 1.11.14 and 1.12.</p>

        </div>
    </div>
    </div>

