<h2>ZF-105: Zend_Db_Select::bind() missing? (TRAC#111)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-21T21:54:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.5 (11/Jul/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zend Framework (zend_framework)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10035/Select-bind-patch.diff">Select-bind-patch.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/developer/ticket/111">http://framework.zend.com/developer/ticket/111</a></p>

<p>Documentation of Zend_Db_Select refer to bind() method, which seems to be not exists.</p>

<pre class="highlight"><code>
     /**
     * Adds a HAVING condition to the query by AND.
     * [...]
     * Array values are quoted and comma-separated.
     *
     * <code>
     * // simplest but non-secure
     * $select-&gt;having("COUNT(id) = $count");
     *
     * // secure
     * $select-&gt;having('COUNT(id) = ?', $count);
     *
     * // equivalent security with named binding
     * $select-&gt;having('COUNT(id) = :count');
     * $select-&gt;bind('count', $count); // &lt;---
     * </code>
     * [...]
     */
</code></pre>

<p>The same story with where() documentation.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mislav Marohni? (mislav) on 2006-07-07T05:41:38.000+0000</p> 
        <div class="body">
            <p>Obviously something was planned for binding values directly into the Select instance, but that was never implemented (maybe abandoned?).</p>

<p>This patch fixes the API docs.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-07-07T17:12:21.000+0000</p> 
        <div class="body">
            <p>Applied patch from Mislav Marohnic to resolve ZF-105 by simply removing documentation for not-yet-implemented features.  See the FishEye link for more information.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jayson Minard (jayson) on 2006-07-11T11:54:37.000+0000</p> 
        <div class="body">
            <p>0.1.5 released</p>

        </div>
    </div>
    </div>

