<h2>ZF-10249: Missing inclusion of SMTP status code in Zend_Mail_Protocol_Exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-07-30T04:48:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-24T10:09:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10741">ZF-10741</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I asked this month before but never received a satisfying answers:</p>

<p>If I Use a Zend_Mail_Transport_Smtp for mail transport. How could I receive the Status code returned by the server on any errors.</p>

<p>Example: 451 greylisted - try again later</p>

<p>The Zend_Mail_Protocol_Exception only contains the "greylisted - try again later" which may vary between servers. The getCode() Method only returns 0.</p>

<p>To me this is a bug of the Zend_Mail_Transport_Smtp and I can't believe that noone else had this problem before.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Eutychus (eutychus) on 2010-07-30T05:43:41.000+0000</p> 
        <div class="body">
            <p>Maybe it could be possible to modify Zend_Mail_Protocol_Abstract::_expect() to submit servers response code via Exception code (which should solve my problem):</p>

<p>{color:red} $errCode = 0;{color}
do {
            $this-&gt;_response[] = $result = $this-&gt;_receive($timeout);
            list($cmd, $more, $msg) = preg_split('/([\s-]+)/', $result, 2, PREG_SPLIT_DELIM_CAPTURE);</p>

<pre><code>        if ($errMsg !== '') {
            $errMsg .= ' ' . $msg;
        } elseif ($cmd === null || !in_array($cmd, $code)) {
            {color:red} $errCode = $cmd;{color}
            $errMsg =  $msg;
        }
</code></pre>

<p>} while (strpos($more, '-') === 0);</p>

<p>if ($errMsg !== '') {
            /**
             * @see Zend_Mail_Protocol_Exception
             */
            require_once 'Zend/Mail/Protocol/Exception.php';
            throw new Zend_Mail_Protocol_Exception($errMsg{color:red}, $errCode{color});
}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-24T10:09:08.000+0000</p> 
        <div class="body">
            <p>Thanks for the bug report.  Addressed this in the patch attached to ZF-10741 as it was necessary to have access to the SMTP status codes for the unit tests on ZF-10741.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-24T10:09:20.000+0000</p> 
        <div class="body">
            <p>Closing this ticket as duplicate for now and linking to ZF-10741 for resolution.</p>

        </div>
    </div>
    </div>

