<h2>ZF-10685: Nesting level too deep - recursive dependency when combining Zend_Translate log &amp; cache</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-15T03:17:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-18T10:33:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Peter Zentjens (zwendel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have a situation where I combine a DB log, cache and a self written adapter for Zend_Translate resulting in a "Nesting level too deep - recursive dependency" error when the translation was retrieved from the cache. I was able to solve this issue based on a solution to an older issue with Zend_Pdf.</p>

<p>I changed the Zend_Translate_Adapter on line 338
from:
} else if ((isset($this-&gt;_options[$key]) and ($this-&gt;_options[$key] != $option)) or
to:
} else if ((isset($this-&gt;_options[$key]) and ($this-&gt;_options[$key] !== $option)) or</p>

<p>which fixes the issue</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-12-18T10:33:00.000+0000</p> 
        <div class="body">
            <p>Fixed with GH-89</p>

        </div>
    </div>
    </div>

