<h2>ZF-11014: Zend_Service_Twitter::statusFriendsTimeline does not include option to include retweets</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-01-31T14:03:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-28T20:18:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jason Austin (jfaustin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jason Austin (jfaustin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13617/zf-11014.patch">zf-11014.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The statusFriendsTimeline does not include options as specified by Twitter's API: <a href="http://dev.twitter.com/doc/get/statuses/friends_timeline">http://dev.twitter.com/doc/get/…</a></p>

<p>Missing are max_id, trim_user, include_rts, and include_entities.</p>

<p>These should be able to be passed in the params array when calling the method.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jason Austin (jfaustin) on 2011-01-31T14:42:45.000+0000</p> 
        <div class="body">
            <p>Patch file attached, including a new testcase to test the method and it's arguments.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jason Austin (jfaustin) on 2011-01-31T14:55:14.000+0000</p> 
        <div class="body">
            <p>The fix for this is attached in the patch file, as well as a unit test for the method.  If I need to make additional changes, let me know.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jason Austin (jfaustin) on 2011-04-28T20:09:49.000+0000</p> 
        <div class="body">
            <p>Fixed issue by adding options for max_id, trim_user and include_rts in options.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-04-28T20:18:10.000+0000</p> 
        <div class="body">
            <p>Fixed in r23876 in trunk and r23877 in release branch 1.11</p>

        </div>
    </div>
    </div>

