<h2>ZF-10323: French documentation : refactoring around the word Émail</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-08-16T10:46:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-08-19T12:00:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
            <li>Zend_Log</li>
            <li>Zend_Mail</li>
            <li>Zend_Mime</li>
            <li>Zend_Service_Flickr</li>
            <li>Zend_Session</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13243/Archive.zip">Archive.zip</a></li>
            <li><a href="/issues/secure/attachment/13244/ZF-10323.patch">ZF-10323.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It is disturbing to Frenchify the word "email" by "Émail", and leave invariant in the plural because the plural suffix "ail" is "aux". I would therefore replace it by "courriel" translation, or "adresse mail".</p>

<p>The specific case of the phrase "email list" by "liste de diffusion".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-08-16T11:14:14.000+0000</p> 
        <div class="body">
            <p>your zip file contains much more than documentation. Also, it is preferred that you generate just one patchfile of your entire changeset.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2010-08-16T11:53:09.000+0000</p> 
        <div class="body">
            <p>Michael told me what he prefers : "regarding the patches, the more little the simpler".
It's easier for me to generate just one patchfile. I add unified patch to leave the choice to the person who will do.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2010-08-19T12:00:24.000+0000</p> 
        <div class="body">
            <p>Patch applied with r22852</p>

        </div>
    </div>
    </div>

