<h2>ZF-1203: 34.4.1. Initial Helpers is false</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-04-04T13:59:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T18:31:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{{Zend_View comes with an initial set of helper classes, all of which relate to form element generation. They each perform the appopriate output escaping automatically.}}</p>

<p>The documentation doesn't speak about Zend_View_Helper_Url</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-05-15T12:04:21.000+0000</p> 
        <div class="body">
            <p>Resolved and updated docs in r4802</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T18:31:13.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

