<h2>ZF-11195: _helper vs getHelper() misleading</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-03-18T21:04:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-20T06:12:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13811/Zend_Controller-ActionHelpers.patch">Zend_Controller-ActionHelpers.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On the page:
<a href="http://framework.zend.com/manual/en/zend.controller.actionhelpers.html">http://framework.zend.com/manual/en/…</a></p>

<p>in the section: Helper Initialization</p>

<p>one variant is missing:
$flashMessenger = $this-&gt;getHelper('FlashMessenger');</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Aleksey 'Xerkus' Khudyakov (xerkus) on 2011-03-20T06:12:27.000+0000</p> 
        <div class="body">
            <p>patch for Zend_Controller-ActionHelpers.xml added</p>

        </div>
    </div>
    </div>

