<h2>ZF-11747: Zend_View_Helper_Form omits closing tag when no content is passed</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-18T00:16:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-24T07:34:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.11 (29/Sep/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11800">ZF-11800</a></li>
            <li><a href="/issues/browse/ZF-12166">ZF-12166</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14670/ZF-11747_fixedfiles.tar.gz">ZF-11747_fixedfiles.tar.gz</a></li>
            <li><a href="/issues/secure/attachment/14669/ZF-11747_revert.patch">ZF-11747_revert.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The closing form tag is set only if the content is passed, so unlike false.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-09-23T03:03:01.000+0000</p> 
        <div class="body">
            <p>Reproducing Unit Test:</p>

<pre class="highlight"><code>
Index: Zend/View/Helper/FormTest.php
===================================================================
--- Zend/View/Helper/FormTest.php       (revision 24462)
+++ Zend/View/Helper/FormTest.php       (working copy)
@@ -167,6 +167,19 @@
         $form = $this-&gt;helper-&gt;form('FormName', array('action' =&gt; '/foo', 'method' =&gt; 'get'));
         $this-&gt;assertNotRegexp('/]*(name="FormName")/', $form);
     }
+
+    /**
+     * @group ZF-11747
+     */
+    public function testClosingTagIsPrintedWhenContentIsOmitted()
+    {
+        $this-&gt;view-&gt;doctype('XHTML11');
+        $form = $this-&gt;helper-&gt;form('FormName');
+        // Check that opening tag was printed
+        $this-&gt;assertContains('assertContains('', $form);
+    }
 }

 // Call Zend_View_Helper_FormTest::main() if this source file is executed directly.
</code></pre>

<p>Proposed fix:</p>

<pre class="highlight"><code>
Index: library/Zend/View/Helper/Form.php
===================================================================
--- library/Zend/View/Helper/Form.php   (revision 24462)
+++ library/Zend/View/Helper/Form.php   (working copy)
@@ -73,10 +73,11 @@
                . '&gt;';

         if (false !== $content) {
-            $xhtml .= $content
-                   .  '';
+            $xhtml .= $content;
         }

+        $xhtml .= '';
+
         return $xhtml;
     }
 }
</code></pre>

<p>I don't see any harm in correcting this (obviously) incorrect behavior.  Unless there are any objections, I will commit to trunk and merge to release-1.11.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-09-26T19:53:03.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24477
Merged to release-1.11 in r24478</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by piet bijl (pbijl) on 2011-10-01T10:04:05.000+0000</p> 
        <div class="body">
            <p>I really dont understand this merge as this just broken numerous projects. Why was this implemented in the first place? For what gain? What was the problem? Why is it a "BUG" that you can render the form decorator WITH or WITHOUT a closing tag.</p>

<p>Now there is no way to render the form decorator APART from the other decorators. Now we are forced to buffer the output of custom form, and pass it as content to the form decorator.</p>

<p>Even when using a custom viewscript, there is no way to render the form now without the closing tag.</p>

<p>I ended up wrapping all the form decorators in a static function which removes the closing tag. Great decision.</p>

<p>No gain, alot of pain. Cool commit</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by piet bijl (pbijl) on 2011-10-01T10:12:24.000+0000</p> 
        <div class="body">
            <p>Please re-open, this craves for a revert.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-01T23:32:38.000+0000</p> 
        <div class="body">
            <p>Apologies.  That use case was missed while discussing and producing the fix, and the unit tests for Zend_View don't enforce this use case.  I will add a test to enforce it so the problem doesn't reoccur.</p>

<p>Fix backed out from release (r24487) and trunk (r24488).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michiel Thalen (chielsen) on 2011-10-04T08:31:47.000+0000</p> 
        <div class="body">
            <p>Just broke my project as well. Second bugfix release in 2 months that brakes my project :(
Revert please.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2011-10-04T10:06:24.000+0000</p> 
        <div class="body">
            <p>@Michiel
Please show us your code snippet which breaks your project. Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-04T11:54:40.000+0000</p> 
        <div class="body">
            <p>I imagine it's this use case (from a view script), which I missed when vetting the fix:</p>

<pre class="highlight"><code>
&lt;?php echo $this-&gt;form('foo'); ?&gt;
    

</code></pre>

<p>In 1.11.11, this now produces the following HTML:</p>

<pre class="highlight"><code>

    

</code></pre>

<p>As the committed patch closes the tag regardless of whether or not content was passed into the form helper's third argument.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-04T12:28:03.000+0000</p> 
        <div class="body">
            <p>I've attached two methods to fix the v1.11.11 release:
 * A tarball (ZF-11747_fixedfiles.tar.gz) containing full, fixed versions of both files. Apply:</p>

<pre class="highlight"><code>
 * A patch (ZF\-11747_revert.patch) which can be used to reverse the changes.  Apply:
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michiel Thalen (chielsen) on 2011-11-14T23:53:49.000+0000</p> 
        <div class="body">
            <p>This bug has been listed Resolved as not an issue? Well it is, and it seems to me that the fixed version is also in the trunk.
So if that is true, maybe change this status. When is the release coming out?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christiaan Kras (htbaa) on 2011-11-27T15:33:17.000+0000</p> 
        <div class="body">
            <p>I'd like to request this 'fix' to be reverted as well. In a big webapplication I use custom view scripts in which I call (from within the view) $this-&gt;form() with only 2 parameters, a form ID and an array with attributes, and later in the template I close the form with a manually inserted . I omit the 3rd parameter. Now this suddenly closes the form tag? I've been using this form since ZF 1.5. This release totally breaks my application, so I'll stick to a previous version for now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dominic Luechinger (dol) on 2011-11-30T14:49:11.000+0000</p> 
        <div class="body">
            <p>+1 for revert this modification.
This fix/bug broke all some of our production code. We use a similar rendering to Adam Lundrigan comment. By passing false to the renderer, the closing form tag won't be added.</p>

<pre class="highlight"><code>
&lt;?php echo $this-&gt;form-&gt;getDecorator('Form')-&gt;setElement($this-&gt;form)-&gt;render(false); ?&gt;
    

</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-11-30T14:55:24.000+0000</p> 
        <div class="body">
            <p>This will be fixed in v1.11.12 and/or v1.12.0 (not sure if 1.11.12 is axed now that 1.12.x is coming down the pipe soon)
Those who want to upgrade to v1.11.11 can, in the interim, follow my instructions above to revert the botched fix (<a href="http://framework.zend.com/issues/browse/ZF-11747?focusedCommentId=48602&amp;page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-48602">here</a>).</p>

<p>I do sincerely apologize for the inconvenience this has caused to everyone involved.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dominic Luechinger (dol) on 2011-11-30T15:03:38.000+0000</p> 
        <div class="body">
            <p>Sorry, if wasn't reading carefully. It's fixed in r24487 and r24488. Thx for reverting. No problem at all. Was funny to debug. Was looking everywhere (different browser, javascript, ...). ;-)</p>

        </div>
    </div>
    </div>

