<h2>ZF-10838: Add ZendX_JQuery_Form as a default element and decorator path</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-16T11:18:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-17T11:00:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I want to use the ZendX_JQuery_Form_Element in lazy load.</p>

<pre class="highlight"><code>
$form = new Zend_Form(array(
    'elements' =&gt; array(
        'type' =&gt; 'datePicker',
        'name' =&gt; 'date'
    )
));
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T07:12:17.000+0000</p> 
        <div class="body">
            <p>ZendX_JQuery_Form will do what you are looking for:</p>

<pre class="highlight"><code>
$zf = new ZendX_JQuery_Form(array(
    'elements' =&gt; array(
        'date' =&gt; array(
            'type' =&gt; 'datePicker'
        )
    )
));
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2010-12-17T10:24:13.000+0000</p> 
        <div class="body">
            <p>Outch, I never noticed this class &gt;<em>&lt; My mistake.
The solution is not the same between ZendX_Application_Resource</em>* and ZendX_JQuery_Form_Element_*. If you look the issue ZF-8751, you have any class ZendX_Application, and the path is updated for the plugin loader.
I made a patch in the same way.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-17T10:44:26.000+0000</p> 
        <div class="body">
            <p>Not an issue you should use ZendX_JQuery_Form that already resolved this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T11:00:03.000+0000</p> 
        <div class="body">
            <p>Issue resolved:  User should use ZendX_JQuery_Form instead of Zend_Form</p>

        </div>
    </div>
    </div>

