<h2>ZF-10708: Cannot redeclare class</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-11-18T11:55:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-18T12:53:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Richard Tuin (richardtuin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Unit tests of ZF2 fail with the following information:</p>

<pre class="highlight"><code>
E_COMPILE_ERROR: Cannot redeclare class ZendTest\File\Transfer\Adapter\HttpTest
#0 /home/rtuin/projects/github/zf2/tests/Zend/File/Transfer/Adapter/HTTPTest.php(283)
PHP Fatal error:  Cannot redeclare class ZendTest\File\Transfer\Adapter\HttpTest in /home/rtuin/projects/github/zf2/tests/Zend/File/Transfer/Adapter/HTTPTest.php on line 283
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-18T11:58:12.000+0000</p> 
        <div class="body">
            <p>It turns out there are 2 files containing the same class: HTTPTest.php and HttpTest.php</p>

<p>Working on a fix now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-11-18T12:33:58.000+0000</p> 
        <div class="body">
            <p>Have you been tracking for some time? and if so, are you using a case insensitive file system (such as Mac, Windows)? We've noticed oddities like that before when we've renamed files to switch case.</p>

<p>Currently, master only shows a Zend/File/Transfer/Adapter/Http.php file, which leads me to believe this is the case for you. As such, I recommend either doing a new clone, or switching to a case sensitive drive partition.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-18T12:40:49.000+0000</p> 
        <div class="body">
            <p>Please note this issue is related to a Unit Test, rather than the library part of the framework.
The exact path both of the files are in are in the "/tests/Zend/File/Transfer/Adapter/" folder.</p>

<p>I am running Ubuntu linux, on a case sensitive partition.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-18T12:42:23.000+0000</p> 
        <div class="body">
            <p>I think i have valid arguments for reopening this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-11-18T12:53:14.000+0000</p> 
        <div class="body">
            <p>Missed that it was in "tests"; fixed in current master.</p>

        </div>
    </div>
    </div>

