<h2>ZF-11366: Redirect loop detected (max_redirect = 7)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-11T18:06:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-11T23:02:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller_Router</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Above all, please forgive me for my bad english !</p>

<p>Since an upgrade from Zend 1.9.6 to 1.11.5, "Google Webmaster Tools" is warning me about an infinite redirect loop.</p>

<p>W3C's markup check (<a href="http://validator.w3.org">http://validator.w3.org</a>) results in the following:
"I got the following unexpected response when trying to retrieve &lt;<a href="http://mydomain.fr/">http://mydomain.fr/</a>&gt;:
301 Moved Permanently
More information about why this is happening may be available from warnings reported by the validator's HTTP (and other protocol) client library:
Redirect loop detected (max_redirect = 7)"</p>

<p>Thanks,</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2011-05-11T18:15:49.000+0000</p> 
        <div class="body">
            <p>How do you know if this is an issue with the router? Do you have any details?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by pegcreation (pegcreation) on 2011-05-11T18:31:11.000+0000</p> 
        <div class="body">
            <p>I choosed the Zend_Controller_Router component.
In fact, I don't know the cause of this bug.
I can just notice that redirections errors appear with 1.11.5 and dissapear if  I restore 1.9.6.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2011-05-11T18:39:08.000+0000</p> 
        <div class="body">
            <p>That could also be a bug of <em>your</em> code due to the upgrade. From time to time, there are some small BC breaks. Without any further information, I have to close this bug as "not an issue".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by pegcreation (pegcreation) on 2011-05-11T22:56:05.000+0000</p> 
        <div class="body">
            <p>Ok, it's probably a bug in my code.
You can close the bug.
Thanks you</p>

        </div>
    </div>
    </div>

