<h2>ZF-1443: Zend_Service_Amazon seems is not working</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-05-28T16:58:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Seems there is a bug or something into Zend_Service_Amazon.</p>

<p>I can't get any results using any sample from Manual (using my won API key of course):</p>

<p><a href="http://framework.zend.com/manual/en/zend.service.amazon.html">http://framework.zend.com/manual/en/…</a></p>

<p>By accessing directly (sample, by Rest) AWS services seems to be all fine.</p>

<p>I posted this under fwd-general but seems is none using Zend_Service_Amazon.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-05-29T09:48:52.000+0000</p> 
        <div class="body">
            <p>Hi Cristian,</p>

<p>Can you please post the code needed to reproduce the problem (excluding your API key, of course :) )?</p>

<p>Thank you!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Cristian Bichis (avantis) on 2007-05-29T14:44:34.000+0000</p> 
        <div class="body">
            <p>OK, i just updated to RC1 and problem seems to no longer exists.</p>

<p>So i guess issue is solved...</p>

        </div>
    </div>
    </div>

