<h2>ZF-11778: Zend_Validate_Iban treating locale=&gt;false wrong in __construct</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-29T14:39:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-29T16:08:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10556">ZF-10556</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Validate_Iban takes a locale to determine against which regex to match the IBAN.
However you can supply false as locale to match wider against ANY valid IBAN. However if you set locale=&gt;false over constructor, it tries to read the locale from registry and sets found locale. 
On the other hand if you setLocale(false) on it, it just sets it to false as expected.</p>

<p>This is somewhat confusing as locale=false should just stay false in constrcutor.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-29T16:08:00.000+0000</p> 
        <div class="body">
            <p>Closing as duplicate of ZF-10556 which has already been solved</p>

        </div>
    </div>
    </div>

