<h2>ZF-1016: Erroneous links to offsetSet() and offsetGet() methods in PHP doc. </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-03-05T17:34:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T18:32:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Olivier Lépine (crapougnax)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Registry</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The links pointing to the PHP documentation in Zend-Register.xml and Zend-Registry.xml give a 404 error code.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-15T13:30:31.000+0000</p> 
        <div class="body">
            <p>The documentation for Zend_Registry has been rewritten, and there are no longer links to offsetGet or offsetSet methods.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-04T15:53:04.000+0000</p> 
        <div class="body">
            <p>Add Zend_Registry to components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T18:32:01.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

