<h2>ZF-1086: Zend Filter string casts improvement</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-03-19T09:15:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.1 (23/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi, I have an improvement to ask :</p>

<p>While using Zend_Filter_StringToLower::filter() as well as Zend_Filter_StringTrim::filter() as well as any filter function that expects an only string to be passed as param; you should cast the param to String inside the function itself :</p>

<p>StringToLower.php before :</p>

<pre class="highlight"><code>
class Zend_Filter_StringToLower implements Zend_Filter_Interface
{
     public function filter($value)
    {
        return strtolower($value);
    }
}
</code></pre>

<p>StringToLower.php after (asked) :</p>

<pre class="highlight"><code>
class Zend_Filter_StringToLower implements Zend_Filter_Interface
{
     public function filter($value)
    {
        return strtolower( (string)$value);
    }
}
</code></pre>

<p>That is, think about that use case :</p>

<p>GET /mypage.php?my_message='Hi' HTTP 1.1
(...)</p>

<pre class="highlight"><code>Zend_Filter_StringToLower::filter($_GET['my_message']);
// will output 'hi' ; all right.
</code></pre>

<p>Now consider this use :
GET /mypage.php?my_message[]='Hi' HTTP 1.1
(...)</p>

<pre class="highlight"><code>Zend_Filter_StringToLower::filter($_GET['my_message']);
// will generate a Notice : Array to string conversion in my\file\dot\php on line my_line.
</code></pre>

<p>Note that my_message is passed as an array this time, anyone can modify the type of params in the URL for a GET request, thus generating in that case a Notice : Array to string conversion in my\file\dot\php on line my_line.</p>

<p>Some of you would say that it's the programmer's job to cast the GET variable manually before passing it to the filter, by I personally think that the filter function should do it by itself, as it expects a string in all cases, and nothing else...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-19T09:32:04.000+0000</p> 
        <div class="body">
            <p>Fix for version 1.0.0 RC1</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-19T15:08:37.000+0000</p> 
        <div class="body">
            <p>Updated fix version to 0.9.1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-19T16:12:02.000+0000</p> 
        <div class="body">
            <p>Also affects {{Zend_Validate_*}} classes</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-20T07:48:33.000+0000</p> 
        <div class="body">
            <p>Resolved with SVN <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4135">r4135</a>.</p>

        </div>
    </div>
    </div>

