<h2>ZF-10689: create config not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-16T07:00:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-16T07:38:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>excuse me!
 I use zf configure for creating db files based on this tutorial  : 
  <a href="http://framework.zend.com/manual/en/learning.quickstart.create-model.html">http://framework.zend.com/manual/en/…</a></p>

<h2>and i executed this command :</h2>

<h2> zf configure db-adapter "adapter=oracle&amp;dbname=APPLICATION_PATH \"/../data/db/korosh.db\"" -s production</h2>

<p>but zf command line tool response to me :</p>

<h6>#</h6>

<p>A db configuration for the production section has been written to the application config file.</p>

<h6>#</h6>

<p>i created data/db directories . but zf do not create db files in those directories too i search for other solution for create db file such as use zend studio but not found any thing .<br />
can i use Zend ORM(Table Data Gateway and DataMapper pattern) with simple connection that create by Zend_Db::factory('oracle',$param)</p>

<p>I do not use db file with ORM . 
????????????????</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-11-16T07:02:29.000+0000</p> 
        <div class="body">
            <p>Please provide a description of the problem, and steps to reproduce when reporting a bug. Closing as incomplete.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-11-16T07:38:00.000+0000</p> 
        <div class="body">
            <p>You have specified oracle as the driver, instead of the pdo_sqlite as specified in the quickstart.</p>

<p>oracle would not be expected to create a datafile, as it is a server based rdbms, and not file based as sqlite is.</p>

<p>For support, could you direct questions to the mailing list, or #zftalk on freenode irc?</p>

        </div>
    </div>
    </div>

