<h2>ZF-1445: Zend_Gdata_Spreadsheets_CellFeedTest failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-05-29T01:03:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1441">ZF-1441</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-05-29T01:03:56.000+0000</p> 
        <div class="body">
            <p>1) testToAndFromString(Zend_Gdata_Spreadsheets_CellFeedTest)
Failed asserting that  is identical to .
/home/sebastian/Work/ZendFramework/tests/Zend/Gdata/Spreadsheets/CellFeedTest.php:46</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-05-30T03:33:14.000+0000</p> 
        <div class="body">
            <p>Fails for the same reason as ZF-1441.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-09T16:41:11.000+0000</p> 
        <div class="body">
            <p>Resolved in svn revision 5201 - told file_get_contents to search include_path for test data</p>

        </div>
    </div>
    </div>

