<h2>ZF-1488: Document Zend_Filter and Zend_Validate classes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-06-04T13:47:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T18:04:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We have documentation for the general Zend_Filter and Zend_Validate interfaces, but no docs for specific classes.</p>

<p>This is a request to add sections to the manual (e.g. Zend_Filter-Classes.xml and Zend_Validate-Classes.xml) to document each of the supported filter and validate concrete classes.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-06-04T15:32:47.000+0000</p> 
        <div class="body">
            <p>Thanks to <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=5104">~andries] for committing [SVN r5104</a> as first documentation for the filter classes. Initial documentation for the validation classes is coming soon.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-06-11T15:20:18.000+0000</p> 
        <div class="body">
            <p>Resolved with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=5229">SVN r5229</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T18:04:16.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

