<h2>ZF-11466: Zend_Tool_Project_Provider_Controller checks for existing controller before canonicalizing name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-10T09:06:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-14T00:36:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.8 (07/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When creating controllers with:</p>

<p>{{zf create action}}</p>

<p>we can sometimes override existing controller (without any warning).</p>

<p>To override controller {{LoremController.php}} type the command:</p>

<p>{{zf create controller lorem}}</p>

<p>or</p>

<p>{{zf create controller}}</p>

<p>and then when prompted type:</p>

<p>{{lorem}}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-06-14T00:09:11.000+0000</p> 
        <div class="body">
            <p>The issue here is that it appears <code>zf create controller</code> checks to see if the controller exists before it's converted to canonical form.</p>

<p>Reproduced below against trunk:</p>

<pre class="highlight"><code>
[adam@zfdev zf]$ zf create project ZF-11466
[adam@zfdev ZF-11466]$ zf create controller Test
Creating a controller at /tmp/zf/ZF-11466/application/controllers/TestController.php
Creating an index action method in controller Test
Creating a view script for the index action method at /tmp/zf/ZF-11466/application/views/scripts/test/index.phtml
Creating a controller test file at /tmp/zf/ZF-11466/tests/application/controllers/TestControllerTest.php
Updating project profile '/tmp/zf/ZF-11466/.zfproject.xml'

[adam@zfdev ZF-11466]$ zf create controller Test
                          An Error Has Occurred
 This project already has a controller named Test

Zend Framework Command Line Console Tool v1.11.0dev
Details for action "Create" and provider "Controller"
  Controller
    zf create controller name index-action-included[=1] module

[adam@zfdev ZF-11466]$ zf create controller test
Note: The canonical controller name that is used with other providers is "Test"; not "test" as supplied
Creating a controller at /tmp/zf/ZF-11466/application/controllers/TestController.php
Creating an index action method in controller Test
Creating a view script for the index action method at /tmp/zf/ZF-11466/application/views/scripts/test/index.phtml
Creating a controller test file at /tmp/zf/ZF-11466/tests/application/controllers/TestControllerTest.php
Updating project profile '/tmp/zf/ZF-11466/.zfproject.xml'
</code></pre>

<p><code>zf create controller Test</code> run twice will trigger an error the second time, but running <code>zf create controller test</code> subsequent to that will overwrite the existing TestController, despite the fact that all three reference the same controller.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-06-14T00:36:46.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24135
Merged to release-1.11 in r24136</p>

<p>Thanks for your bug report.</p>

        </div>
    </div>
    </div>

