<h2>ZF-12324: Zend_Mobile: GCM collapse_key does not encode as a string in json when using a numeric</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-07-06T17:38:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-06T17:49:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mike Willbanks (digitalstruct)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>FixForZF1.12</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you enter a numeric id, you will get a Zend_Mobile_Push_Exception_InvalidPayload Exception with the response:
"Field "collapse_key" must be a JSON String".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mike Willbanks (digitalstruct) on 2012-07-06T17:49:44.000+0000</p> 
        <div class="body">
            <p>Committed to trunk: 25021
Committed to release branch 1.12: 25022</p>

        </div>
    </div>
    </div>

