<h2>ZF-11823: Fatal error: Undefined class constant 'CLEANING_MODE_OLD'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-14T10:12:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-01-08T15:38:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11463">ZF-11463</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm using Zend_Cache as Session Handler, which works fine. I'm not sure where this issue was introduced, but every time when the automatic_cleaning_factor will remove old keys, I'll see the following error:</p>

<p>Fatal error: Undefined class constant 'CLEANING_MODE_OLD' in library/Zend/Cache/Core.php on line 0 Call Stack: 1.0006 14868608 1. My_Session_SaveHandler_ZendCache-&gt;write() library/My/Session/SaveHandler/ZendCache.php:0 1.0006 14868920 2. Zend_Cache_Core-&gt;save() library/My/Session/SaveHandler/ZendCache.php:29</p>

<p>I'm calling Zend_Cache_core with liek the following:</p>

<pre class="highlight"><code>   public function write($id, $sessionData) {
        $this-&gt;cache-&gt;save($sessionData, $id, array() , $this-&gt;maxLifetime);
        return true;
    }</code></pre>

<p>Where $this-&gt;cache is a cache from cachemanager, in my exampel with Zend_Cache_Core as frontend and Zend_Cache_Backend_Memcache as backend.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-14T16:16:40.000+0000</p> 
        <div class="body">
            <p>I think this issue is related to ZF-11463.  See <a href="http://framework.zend.com/issues/browse/ZF-11463?focusedCommentId=47397&amp;page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-47397">this comment</a>.</p>

<p>In that issue, the same sort of error manifests itself ("undefined class constant" error), and happens because the write and close session handlers are called after object destruction, and therefore the objects no longer have class constants. In the comment i've linked to above, the poster suggests a workaround which worked his case.  Could you try it for your case and report back the result?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2012-01-08T15:37:34.000+0000</p> 
        <div class="body">
            <p>as adam sayed it's a doublicate of ZF-11463</p>

        </div>
    </div>
    </div>

