<h2>ZF-12268: Zend_Mail with Methode generateMessage() throw a Fatal error with Call to a member function getContent() on a non-object</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-02T07:31:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-04T13:55:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Robert (bob)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
$mail = new Zend_Mail();
$mail-&gt;setFrom("test@test.com", "TEST");
$mail-&gt;setSubject("Subject");
$mail-&gt;setBodyHtml("Body");
$mail-&gt;addTo("someone@someone.com");
$messageString = $mail-&gt;generateMessage();
</code></pre>

<p>generateMessage() throw this error message:
Fatal error: Call to a member function getContent() on a non-object in /Volumes/library/Zend/Mime/Message.php on line 140'</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

