<h2>ZF-10379: Wrong formatting with Zend_Currency for locale pl_PL</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-25T07:04:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Currency</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$curr = new Zend_Currency('pl_PL');
echo $curr-&gt;toCurrency('1234567.6789', array('display' =&gt; Zend_Currency::USE_SYMBOL)); // you get: "1 234 567,68 zł"
echo $curr-&gt;toCurrency('1234567.6789', array('display' =&gt; Zend_Currency::NO_SYMBOL)); // you get: "1234567,68", should be "1 234 567,68"</p>

<p>Using Zend_Currency::NO_SYMBOL the formatting ignores grouping. The output should be: "1 234 567,68". I suppose it is dependent on Zend_Locale, but don't know on which part exactly. The above works fine for example for locale "de_AT".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marcin Dec (md23128) on 2010-08-26T01:40:00.000+0000</p> 
        <div class="body">
            <p>pl.xml look like this:</p>

<p>#,##0.00 ¤{0} {1}</p>

<p>and suppose to be fine. pls help!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stefan Staudenmeyer (hadean) on 2010-12-29T00:49:21.000+0000</p> 
        <div class="body">
            <p>Its nopt the Formats section, its the Symbols-Section!</p>

<p>Er... If the whitespaces are the problem:</p>

<h1>Index: trunk/library/Zend/Locale/Data/pl.xml</h1>

<p>--- trunk/library/Zend/Locale/Data/pl.xml   (revision 278)
+++ trunk/library/Zend/Locale/Data/pl.xml   (working copy)
@@ -2136,7 +2136,7 @@
    ,
-           Â 
+           .;%0</p>

<p>Greetings, Dörte, Mayflower.</p>

        </div>
    </div>
    </div>

