<h2>ZF-1644: Order of parameters in Extension_FeedLink and Extension_EntryLink is not optimal</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-06-27T18:04:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 (30/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Gdata_Extension_FeedLink currently has it's constructor parameters in the following order:
* countHint
* href
* readOnly
* rel
* feed</p>

<p>This is inconvenient, since the most likely used parameters are not at the beginning. Instead, they should be rearranged as follows:
* rel
* href
* (others)</p>

<p>This will break backwards compatibility, so we should think about this before implementing it. However, I think the improvement in usability justifies the change.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-28T10:07:40.000+0000</p> 
        <div class="body">
            <p>Assigning to Ryan.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-06-29T19:00:22.000+0000</p> 
        <div class="body">
            <p>Added Extension_EntryLink to the title since this applies equally to both.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-29T19:09:04.000+0000</p> 
        <div class="body">
            <p>Resolved in svn 5519</p>

        </div>
    </div>
    </div>

