<h2>ZF-12362: Not working Zend_Validate_Hostname is Punycode Format URI</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-08-09T01:56:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-17T08:01:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
            <li>validating</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>testscript: validate-host.php ===========</p>

<p>&lt;?php
require_once 'Zend/Validate/Hostname.php';</p>

<p>$punycode_hostname = 'xn--wgv71a119e.jp';</p>

<p>// ======================================</p>

<p>$validator = new Zend_Validate_Hostname(array(
        'allow' =&gt; Zend_Validate_Hostname::ALLOW_DNS,
        'idn' =&gt; false,
        'tld' =&gt; false,
    ));
var_dump($validator-&gt;isValid($punycode_hostname));
var_dump($validator-&gt;getMessages());</p>

<p>die();</p>

<p>// ===================================</p>

<p>/* bool(false) <em>/
/</em> array(1) { <em>/
/</em>   ["hostnameCannotDecodePunycode"]=&gt; <em>/
/</em>   string(98) "'xn--wgv71a119e.jp' appears to be a DNS hostname but the given punycode notation cannot be decoded" <em>/
/</em> } */</p>

<p>=========== testscript:validate-host.php</p>

<p>the point at issue: Zend/Validate/Hostname.php ===================
Line: 596-601
if (strpos($domainPart, 'xn--') === 0) {
    $domainPart = $this-&gt;decodePunycode(substr($domainPart, 4));
    if ($domainPart === false) {
        return false;
    }
}</p>

<p>and</p>

<p>Line: 708-717 (in decodePunycode function)
$separator = strrpos($encoded, '-');
if ($separator &gt; 0) {
    for ($x = 0; $x &lt; $separator; ++$x) {
        // prepare decoding matrix
        $decoded[] = ord($encoded[$x]);
    }
} else {
    $this-&gt;_error(self::CANNOT_DECODE_PUNYCODE);
    return false;
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Egor Chernodarov (eg321) on 2012-08-17T08:01:14.000+0000</p> 
        <div class="body">
            <p>Seems it's duplicate of <a href="http://framework.zend.com/issues/browse/ZF-12035">http://framework.zend.com/issues/browse/ZF-12035</a>.
Please vote it.</p>

        </div>
    </div>
    </div>

