<h2>ZF-1966: Documentation missing getUserParam() for Request object</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-09-19T14:10:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T14:10:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.3 (30/Nov/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Joó Ádám (ceriak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Request Object's getUserParam() and getUserParams() methods are cannot be found neither in the manual (<a href="http://framework.zend.com/manual/en/zend.controller.request.html">http://framework.zend.com/manual/en/…</a>) nor in the API guide (<a href="http://framework.zend.com/apidoc/core/">http://framework.zend.com/apidoc/core/</a>).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-09-19T14:22:53.000+0000</p> 
        <div class="body">
            <p>Assigning to [~matthew] to initiate issue review.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-11-16T14:53:25.000+0000</p> 
        <div class="body">
            <p>Scheduling for 1.0.3</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-11-20T09:23:07.000+0000</p> 
        <div class="body">
            <p>Updated in current trunk; documentation placed in note concerning get/setParam().</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T14:10:11.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

