<h2>ZF-11654: 'Standard form elements' page missing from manual</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-08-09T08:44:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-09T16:43:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.11 (29/Sep/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The page "Standard Form Elements Shipped With Zend Framework" seems to be missing from the current manual (both online version and the downloaded one). This is the page that lists all of the different form elements and shows how they can be configured.</p>

<p>For reference, here is a mirror of the page from an older ZF release: <a href="http://framework.zend.com/manual/1.10/en/zend.form.standardElements.html">http://framework.zend.com/manual/1.10/…</a></p>

<p>The page is referenced in numerous places in the form docs that are present, but all of these links currently have an empty href and do nothing, e.g.:</p>

<p><a href="http://framework.zend.com/manual/en/zend.form.elements.html#zend.form.elements.standard">http://framework.zend.com/manual/en/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2011-08-09T16:43:29.000+0000</p> 
        <div class="body">
            <p>Fixed in 1.11branch with r24359 (no problem in trunk)</p>

        </div>
    </div>
    </div>

