<h2>ZF-11388: Hostname validation don't work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-19T02:13:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-27T20:24:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                TAJIRI Yasuhiro (tty)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Code:
$validator= new Zend_Validate_Hostname(
                    array(
                        'allow' =&gt; Zend_Validate_Hostname::ALLOW_DNS,
                        'idn'   =&gt; true
                    )
                );
$ret = $validator-&gt;isValid('xn--eckwd4c7cu47r2wf.com')</p>

<p>This code return false,but this idn is valid.
1.decodePunycode returns false.
   But idn_to_utf8 returns 'とろろ口コミ'.</p>

<p>2.$ret = $validator-&gt;isValid('とろろ口コミ.com')
This code return false. 
Is IDN Validate regexp  thought to use a mixture of hiragana, kanji,katakana?　</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-07-27T20:24:49.000+0000</p> 
        <div class="body">
            <p>No, a mixture of multiple scripts is actually not allowed.
The given domain does also not exist so I expext this not as failure.
Feel free to reopen this issue when you can give an living example of a multi-script domain in JP.</p>

        </div>
    </div>
    </div>

