<h2>ZF-10889: CLONE - Update all docblocks to use consistent copyright/license header. Version: 2011</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2011-01-01T10:59:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-20T03:52:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11122">ZF-11122</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There are quite a few code files throughout the library, tests, and incubator that have an inconsistent header docblock.</p>

<p>We need to have a single canonical header docblock that correctly describes the copyright and license for the code, and we need to make that docblock present in all files for PHP code, tests, scripts, etc.</p>

<p>Should be fixed in trunk, branch, incubator (well how in the standard and extras) and git zf2.</p>

<p>Thanks advance
Ramon</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-01T11:00:57.000+0000</p> 
        <div class="body">
            <p>Reassigned to [~matthew]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-01-02T13:27:12.000+0000</p> 
        <div class="body">
            <p>ZF2 done with GH-104</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-03-05T16:45:19.000+0000</p> 
        <div class="body">
            <p>I believe that have been fixed with issue ZF-11122.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-06-20T03:52:27.000+0000</p> 
        <div class="body">
            <p>Fix with issue ZF-11122.and pull of the [~thomas] to git ;).</p>

        </div>
    </div>
    </div>

