<h2>ZF-11061: ext/mcrypt is only required by Zend_Service_ReCaptcha_MailHide</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-02-09T09:03:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-06T07:47:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.4 (03/Mar/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_ReCaptcha</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The manual's requirements page lists ext/mcrypt as a hard dependency of Zend_Service_Recaptcha.</p>

<p>There's no mention or usage of mcrypt in the "normal" Zend_Service_Recaptcha code. It appears that mcrypt is only required if you use the Zend_Service_ReCaptcha_MailHide sub-component.</p>

<p>So, it seems like the requirements page should either list mcrypt as a "Soft" dependency, or as a hard dependency on the MailHide sub-component.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-02-19T13:06:35.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23734 merged to branch release 1.11 r23735.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by John Flatness (zerocrates) on 2011-02-22T07:34:00.000+0000</p> 
        <div class="body">
            <p>The committed change fixes the problem in {{requirements-php-extensions-table.xml}}, but not the reverse problem in {{requirements-zendcomponents-table.xml}}.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-03-06T07:47:57.000+0000</p> 
        <div class="body">
            <p>Done in trunk r23795 in the branch release r23796 - thanks.</p>

        </div>
    </div>
    </div>

