<h2>ZF-11970: Zend_File_Transfer online manual has a incorrect example.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2012-01-05T09:08:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-26T06:42:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Danny van der Sluijs (dannyvandersluijs)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_File_Transfer online manual has a incorrect example. On page <a href="http://framework.zend.com/manual/en/zend.file.transfer.introduction.html">http://framework.zend.com/manual/en/…</a>, Example #4 the method Zend_File_Trasfer::setOption is called, this is non-existend, and should be Zend_File_Transfer::setOptions</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-26T06:42:13.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24658
Merged to release-1.11 in r24659</p>

        </div>
    </div>
    </div>

