<h2>ZF-11627: Missing module in _forward() creates loop</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-29T16:15:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-29T16:15:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you call $this-&gt;_forward($action,$controller,$module) in a controller for a module which is missing the application ends up in a loop. Maybe there are other measures to prevent a loop at all but for this particular case in the _forward method where we have if (null !== $module) (~line 667) a check on $this-&gt;getFrontController()-&gt;getControllerDirectory() and array_key_exists() for the module name could be used to throw an exception instead.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

