<h2>ZF-11571: call to -&gt;_forward() from preDispatch method of Zend_Controller_Action subclass causes infinite loop</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-07-18T02:49:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-28T20:05:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zachary Burnham (zburnham)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>Zend_Controller_Action</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Adding a call to _forward() in the preDispatch() method of a subclass of Zend_Controller_Action gives an infinite loop.</p>

<p>My controller:</p>

<p>class IndexController extends Zend_Controller_Action
{</p>

<pre><code>public function init()
{
    /* Initialize action controller here */
}

public function preDispatch()
{
    if (true) {
        $this-&gt;_forward('forward');
    }
}

public function indexAction()
{
    // action body
}

public function forwardAction()
{

}
</code></pre>

<p>}</p>

<p>This is after a stock install of ZF using the shell script.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-18T13:40:30.000+0000</p> 
        <div class="body">
            <p>Calling _forward() in a controller to an action in the same controller is no different than calling one to an action in a different controller. In each case, a new iteration of the dispatch loop is invoked, which means that the preDispatch() method will be called again.</p>

<p>As such, you need to add some logic to test against the current action before forwarding:</p>

<pre class="highlight"><code>
if ('forward' != $this-&gt;getRequest()-&gt;getActionName()) {
    return $this-&gt;_forward('forward');
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Zachary Burnham (zburnham) on 2011-07-18T14:07:23.000+0000</p> 
        <div class="body">
            <p>It would be good if the documentation mentioned the possibility of a loop, lest someone new to ZF and to MVC in general make the same mistake I did.  Something like:</p>

<p>"Note that using _forward() will cause the preDispatch() method to be called again, so to avoid a loop, add logic to check for the action name around your call to _forward()."</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-28T20:05:50.000+0000</p> 
        <div class="body">
            <p>Edited to make this a documentation issue. Zach, would you like to tackle it?</p>

        </div>
    </div>
    </div>

