<h2>ZF-1775: Support Zend_Config in Zend_Db factory and constructor</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-07-26T13:37:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T14:49:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is a feature request to support usage of a Zend_Config object as an argument to {{Zend_Db::factory()}} or {{Zend_Db_Adapter_Abstract::__construct()}}.</p>

<p>The following examples of usage should work:</p>

<pre class="highlight"><code>
$db = Zend_Db::factory(Zend_Config $config);
</code></pre>

<pre class="highlight"><code>
$db = Zend_Db::factory(string $type, array $args);
</code></pre>

<pre class="highlight"><code>
$db = Zend_Db::factory(string $type, Zend_Config $args);
</code></pre>

<pre class="highlight"><code>
$db = new Zend_Db_Adapter_Type(array $args);
</code></pre>

<pre class="highlight"><code>
$db = new Zend_Db_Adapter_Type(Zend_Config $args);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-08-02T20:58:48.000+0000</p> 
        <div class="body">
            <p>Implementation of code, tests, and docs has been committed in revision 5970.</p>

<p>Now either argument of {{Zend_Db::factory()}} may be an object of type Zend_Config.  But the old usage is still supported, so there is no break in backward-compatibility.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T14:49:09.000+0000</p> 
        <div class="body">
            <p>Fixing Fix Version to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

