<h2>ZF-10781: Configuring zf to use certain application.ini section</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-12-05T09:51:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-28T10:46:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I would like to tell Zend_Tool_Project_Provider_DbTable::createFromDatabase which section of configuration to use when scaning the database. Maybe there is a way to configure zf.php (CLI)?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Przemys?aw Wróbel (wrobel) on 2011-10-28T10:46:11.000+0000</p> 
        <div class="body">
            <p>I have found that Zend_Tool_Project_Context_Zf_BootstrapFile has a hardcoded application.ini section name in getApplicationInstance() to 'development' which is not allways what I want! It would be nice if I could tell the DbTable provider to use a specified section or take one from the .zf.ini file.</p>

        </div>
    </div>
    </div>

