<h2>ZF-10741: Zend_Mail_Protocol_Smtp needs unit tests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-11-24T09:46:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-19T16:46:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8528">ZF-8528</a></li>
            <li><a href="/issues/browse/ZF-10249">ZF-10249</a></li>
            <li><a href="/issues/browse/ZF-10758">ZF-10758</a></li>
            <li><a href="/issues/browse/ZF-10853">ZF-10853</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13481/ZF-10741.patch">ZF-10741.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi Marc</p>

<p>You will push to git ZF2 to after close this issue?</p>

<p>Thanks advance</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-24T09:50:05.000+0000</p> 
        <div class="body">
            <p>Patch adds unit tests to Zend_Mail_Protocol_Smtp, with a small refactoring of calls to PHP stream functions in Zend_Mail_Protocol_Abstract to allow mocking of the protocol adapter for testing.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-12-06T13:28:59.000+0000</p> 
        <div class="body">
            <p>Applied to trunk in r23475, merged to release branch 1.11 in r23476.  Leaving open for now to remind myself to add these tests to ZF2.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-18T02:32:03.000+0000</p> 
        <div class="body">
            <p>Hi Marc</p>

<p>You will push to git ZF2 to after close this issue? (because i think convenient create a task with Fix Version/s Next Major Release).</p>

<p>Thanks advance</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-12-19T16:46:09.000+0000</p> 
        <div class="body">
            <p>Marking as resolved.  See ZF-10853 for implementation in ZF2.</p>

        </div>
    </div>
    </div>

