<h2>ZF-10932: Zend_Db_Pdo_mssql return null fetching uniqueidentifier data type </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-10T01:11:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-05T01:23:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramlan Gustian (rampog)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>i have found bugs when fetching uniqueidentifier data type using pdo_mssql/pdo_dblib
"SELECT NEWID() AS GUUID"
which always return null,
but in sql_srv work properly
&amp; i have tried too using mssql extension
return binary char</p>

<p>temporary solution,we cast in select query so return always in varchar datatype</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-10T01:43:03.000+0000</p> 
        <div class="body">
            <p>Assigned to mantainer and assigned component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2011-03-05T01:23:48.000+0000</p> 
        <div class="body">
            <p>This behavior is caused by a bug in the underlying PDO_DBLIB PHP extension.</p>

<p>I have posted a bug report and patch here [<a href="http://bugs.php.net/bug.php?id=54167">http://bugs.php.net/bug.php?id=54167</a>].  If you need an immediate fix, check out the php source, apply the patch and recompile the extension.  Otherwise this fix will need to wait until the patch is committed to PHP.</p>

<p>Closing as "won't fix" since this is not a ZF or Zend_Db_Adapter_Pdo_Mssql issue but rather a PHP issue.</p>

        </div>
    </div>
    </div>

