<h2>ZF-1162: Mysqli driver is handling transactions incorrectly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-29T12:49:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Adapter_Mysqli</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10405/zf-1162.diff">zf-1162.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The methods beginTransaction, commit and rollBack of the Mysqli driver are handling transactions incorrectly.</p>

<p>1) beginTransaction</p>

<p>This method is calling connection-&gt;beginTransaction. This method doesn't exist in mysqli class. According to the documentation, a transaction in mysqli must be started by the autocommit method.</p>

<pre class="highlight"><code>
// the line
$this-&gt;_connection-&gt;beginTransaction();
// should be changed to
$this-&gt;_connection-&gt;autocommit(false);
</code></pre>

<p>2) commit</p>

<p>After calling the commit method of the mysqli class, the autocommit mode should be turned on (or at least we could have an argument or property to configure this behavior).</p>

<pre class="highlight"><code>
// this line should be added after calling connection-&gt;commit
$this-&gt;_connection-&gt;autocommit(true);
</code></pre>

<p>3) rollBack</p>

<p>Same as commit.</p>

<pre class="highlight"><code>
// this line should be added after calling connection-&gt;rollback
$this-&gt;_connection-&gt;autocommit(true);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-10T16:29:24.000+0000</p> 
        <div class="body">
            <p>Assigning to Darby.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2007-04-11T15:14:16.000+0000</p> 
        <div class="body">
            <p>Diff to fix problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-18T15:35:39.000+0000</p> 
        <div class="body">
            <p>Attempted resolution with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4535">SVN r4535</a>.</p>

        </div>
    </div>
    </div>

