<h2>ZF-11591: Zend_Db bulk insert</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2011-07-22T15:11:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-22T15:11:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Tomáš Fejfar (tomas.fejfar@gmail.com)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be nice if {{$dbAdapter-&gt;insert()}} (and subsequent table methods) would use bulk inserts (more than one row in one statement) if data is array of arrays. It could use normal inserts in loop for DBMSs that don't support bulk inserts.</p>

<p>It would highly speedup inserts for many rows.</p>

<p>There is possible workaround now - use direct query, but it's not used much and developers constantly ask for such feature - one example for all <a href="http://stackoverflow.com/questions/6789189/bulk-insert-in-zend-framework">http://stackoverflow.com/questions/6789189/…</a>.</p>

<p>Note: I tried search for bulk insert issue first, but no such issue was found...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

