<h2>ZF-10473: Enable/disable referentical contraint checking</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-09-19T14:52:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-15T09:58:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rafal Radulski (rrafal)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I suggest to add one or two methods to Zend_Db_Adapter. They would enable and disable referential constraint checking (or foreign key checking). This is a common feature in databases, but it requires different SQL calls. For example:</p>

<p>MsSQL: ALTER TABLE ? NOCHECK CONSTRAINT ALL
MySQL: SET foreign_key_checks = 0
SQLite: PRAGMA foreign_keys = OFF
PgSQL: SET CONSTRAINTS ALL DEFERRED (?)</p>

<p>This feature would be useful was setting up database tables during testing, importing data, and dropping multiple tables. It would be used by Zend_Test_PHPUnit_Db_Operation_* classes. I know that it will be difficult or impossible to implement this consistently across all databases. However, I think it would be much worth it.</p>

<p>I suggest the following methods:
enableReferentialConstraints()
disableReferentialConstraints()
or:
enableReferentialConstraints(boolean)</p>

<p>usage:
$connection-&gt;enableReferentialConstriants(true);
try{
    // execute SQL statments
    //
    $connection-&gt;enableReferentialConstriants(false);
} catch(Exception ex) {
    $connection-&gt;enableReferentialConstriants(false);
    // handle or re-throw exception
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shawn Ostler (sosy) on 2011-03-11T12:48:26.000+0000</p> 
        <div class="body">
            <p>For SQLite, I am currently extending the Db_Adapter simply to turn on foreign keys. This should be added, at least for SQLite, since foreign keys are disabled.</p>

<p>-application.ini</p>

<p>resources.db.adapter = "pdo_sqlite"
resources.db.params.dbname = APPLICATION_PATH "/../database/production.sqlite3"
resources.db.params.adapterNamespace = 'My_Db_Adapter'
resources.db.params.enable_foreign_keys = 1</p>

<p>&lt;?php</p>

<p>class My_Db_Adapter_Pdo_Sqlite extends Zend_Db_Adapter_Pdo_Sqlite {</p>

<pre><code>protected function _connect() {

    /**
     * if we already have a PDO object, no need to re-connect.
     */
    if ($this-&gt;_connection) {
        return;
    }

    parent::_connect();

    if (isset($this-&gt;_config['enable_foreign_keys'])  &amp;&amp; $this-&gt;_config['enable_foreign_keys']) {
        $q = $this-&gt;_profiler-&gt;queryStart('enable_foreign_keys');

        $retval = $this-&gt;_connection-&gt;exec('PRAGMA foreign_keys=1');
        if ($retval === false) {
            $error = $this-&gt;_connection-&gt;errorInfo();
            /** @see Zend_Db_Adapter_Exception */
            require_once 'Zend/Db/Adapter/Exception.php';
            throw new Zend_Db_Adapter_Exception($error[2]);
        }

        $this-&gt;_profiler-&gt;queryEnd($q);
    }

}
</code></pre>

<p>}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2011-03-12T09:30:02.000+0000</p> 
        <div class="body">
            <p>Why would you want to have this feature implemented? If it's something you use regularly (or anywhere) you're doing something wrong. If you don't want referential integrity, then I'd suggest you simply don't enable it in  your RDBMS in the first place.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shawn Ostler (sosy) on 2011-03-15T09:50:50.000+0000</p> 
        <div class="body">
            <p>You are absolutely right and thank you for pointing this out. I have created another issue, <a href="http://framework.zend.com/issues/browse/ZF-11176">http://framework.zend.com/issues/browse/ZF-11176</a>, where I ask for enabling, only in sqlite and also to deny disabling.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2011-03-15T09:58:51.000+0000</p> 
        <div class="body">
            <p>Resolving issue as wont fix.</p>

        </div>
    </div>
    </div>

