<h2>ZF-1455: Zend_VersionTest failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-05-30T01:26:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC2 (08/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Version</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>2) testVersionCompare(Zend_VersionTest)
For version '1.0.0' and Zend_Version::VERSION = '1.0.0RC1': result=1, but expected -1
Failed asserting that </p>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-01T14:23:07.000+0000</p> 
        <div class="body">
            <p>Tests fixed in revision 5077.</p>

        </div>
    </div>
    </div>

