<h2>ZF-12228: Zend_Service_WindowsAzure requires non existing files</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-05-22T11:51:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-03-09T10:57:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Martin Hujer (mhujer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_WindowsAzure</li>
            <li>HipHopForPHP</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Just search Zend/Service/WindowsAzure sources for those:</p>

<p>Zend/Service/Console/Command.php
Zend/Service/Console/Exception.php
Zend/Service/Console/Exception.php
Zend/Service/Log/Formatter/Interface.php
Zend/Service/Log/Writer/Abstract.php
Zend/Service/Log/Exception.php
Zend/Service/Management/Exception.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-03-09T10:30:21.000+0000</p> 
        <div class="body">
            <ul><li>Zend/Service/Log/Formatter/Interface.php</li>
<li>Zend/Service/Log/Writer/Abstract.php</li>
<li>Zend/Service/Log/Exception.php</li>
<li>Zend/Service/Management/Exception.php</li>
</ul><p>Fixed on trunk (25284) and on release-1.12 branch (25285)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-03-09T10:34:43.000+0000</p> 
        <div class="body">
            <ul><li>Zend/Service/Console/Command.php</li>
<li>Zend/Service/Console/Exception.php</li>
<li>Zend/Service/Console/Exception.php</li>
</ul><p>What is this? There is no "Console"!
Any Ideas or comments?</p>

<p>By the way, the {{Zend/Service/WindowsAzure}} component is very ugly:</p>

<ul><li>Method calls outside a class</li>
<li>Sample files in library</li>
<li>Wrong coding format (we have a coding standard!)</li>
<li>...</li>
</ul>
        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Hujer (mhujer) on 2013-03-09T10:38:08.000+0000</p> 
        <div class="body">
            <p>It would be best to leave WindowsAzure out - the SDK is on the GitHub <a href="https://github.com/WindowsAzure/azure-sdk-for-php">https://github.com/WindowsAzure/azure-sdk-for-php</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-03-09T10:50:58.000+0000</p> 
        <div class="body">
            <p>@<a href="https://github.com/zendframework/ZendService_WindowsAzure">~mhujer]
Thanks for your very fast feedback! :)</a></p>

<p>I think, this would be a good solution. I will speak with Matthew, because on Github we still have [ZendService_WindowsAzure.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Hujer (mhujer) on 2013-03-09T10:57:14.000+0000</p> 
        <div class="body">
            <p>I'm not sure about the current quality of the SDK included in ZF, but when I tried Azure approx. 2y ago, I had to use the standalone SDK, because the one in the ZF worked with outdated service API.</p>

        </div>
    </div>
    </div>

