<h2>ZF-10381: Zend_Application_Resource_Locale: an unit test fails without locale configured</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-08-25T12:03:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-04T01:28:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.8 (07/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13270/ZF-10381.php.patch">ZF-10381.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The method testOptionsPassedToResourceAreUsedToSetLocaleState1() fails without locale configured (or if your locale configured is the same as the default value tested).</p>

<p>I propose to add a test to skip this test if you can not succeed.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2010-08-25T13:30:36.000+0000</p> 
        <div class="body">
            <p>@Dolf: Forgot my patch. I don't see how the test can be completed without call the function setlocale().</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2011-06-04T01:28:03.000+0000</p> 
        <div class="body">
            <p>Fixed in r24111. Merged in release 1.11 branch in r24112.</p>

        </div>
    </div>
    </div>

