<h2>ZF-10565: Zend_Console_Getopt does not allow an option with name of &quot;route&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-17T04:36:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-17T05:27:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Trevor Morse (trevormorse)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Console_Getopt</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have the following in my code:</p>

<p>$options = new Zend_Console_Getopt(
    array(
        'route|r=s' =&gt; 'Custom route of the action.'
    )
);</p>

<p>// ...
$action_route = $options-&gt;route;</p>

<p>var_dump($action_route);</p>

<p>Which when called like this: ./phpfile.php --route=text results in:
string(0) ""</p>

<p>I'd expect:
string(4) "text"</p>

<p>Changing the name of route to anything else(ie - froute) and everything works as expected. I am not sure what version of the zf this is, but below is from my Getopt.php</p>

<p>@version    $Id: Getopt.php 20096 2010-01-06 02:05:09Z bkarwin $</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Morse (trevormorse) on 2010-10-17T04:51:47.000+0000</p> 
        <div class="body">
            <p>I apologize, please remove this, it was an issue with my particular code.</p>

        </div>
    </div>
    </div>

