<h2>ZF-127: IIS Support? (TRAC#150)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-21T22:41:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-19T13:44:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zend Framework (zend_framework)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/developer/ticket/150">http://framework.zend.com/developer/ticket/150</a></p>

<p>I'm having trouble getting the framework to work on IIS, due to what appears to be the requirement for mod_rewrite.</p>

<p>There was a note in Chris Shiflett's phparchitect tutorial:</p>

<p>One of the TODO items for Zend_Controller is to remove the mod_rewrite dependency. In order to provide an example that works with the preview release, this tutorial uses mod_rewrite.</p>

<p>When is the mod_rewrite dependency going to be addressed and does anyone have any hacks in the meantime (without having to buy a 3rd party replacement for mod_rewrite for IIS)?</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Zend Framework (zend_framework) on 2006-06-21T22:41:35.000+0000</p> 
        <div class="body">
            <p>06/17/06 08:10:24: Modified by tolmi@lazycat.hu</p>

<p>Hello!</p>

<p>Your problem effectively is a duplicate of #2 (IN TRAC)</p>

<p>-- Mark Tolmacs</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2006-06-22T09:51:54.000+0000</p> 
        <div class="body">
            <p>Effective duplicate of ZF-25</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-19T13:44:21.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Closing old issues and assigning them to the person who ultimately resolved the issue.</p>

        </div>
    </div>
    </div>

