<h2>ZF-10530: Zend_Session_SaveHandler serialized data truncatcated if null values present</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-07T12:53:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13331/DbTable.php">DbTable.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have an issue with putting a Zend_Db_Row in a session.</p>

<p>The problem is "you'll get NULL characters in your serialized string, when you serialize objects containing private or protected member variables..."</p>

<p>Here is a fix found in the nabble by Ondrej Ivanič-3</p>

<p>--- library/Zend/Session/SaveHandler/DbTable.php    (revision 18687) 
+++ library/Zend/Session/SaveHandler/DbTable.php    (working copy) 
@@ -319,7 +319,7 @@</p>

<pre><code>     if (count($rows)) { 
         if ($this-&gt;_getExpirationTime($row = $rows-&gt;current()) &gt; time()) { 
</code></pre>

<p>-                $return = $row-&gt;{$this-&gt;_dataColumn}; 
+                $return = pack("H*", $row-&gt;{$this-&gt;_dataColumn}); 
             } else { 
                 $this-&gt;destroy($id); 
             } 
@@ -338,6 +338,7 @@ 
     public function write($id, $data) 
     { 
         $return = false; 
+        $data = bin2hex($data);</p>

<pre><code>     $data = array($this-&gt;_modifiedColumn =&gt; time(), 
                   $this-&gt;_dataColumn     =&gt; (string) $data);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Douglas Hammond (wizhippo) on 2010-10-07T13:02:20.000+0000</p> 
        <div class="body">
            <p>Fix using base64 instead</p>

        </div>
    </div>
    </div>

