<h2>ZF-1442: Should &quot;Refresh: 0&quot; header be considered as a redirect?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-05-28T16:10:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Simone Carletti (weppos)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm not really sure this behavior can be considered a bug, it might be an improvements or an additional feature.
BTW, here's the issue.</p>

<p>Sometimes HTTP request returns a particular response header called "Refresh:".
Consider this case</p>

<pre class="highlight"><code>
HTTP 200
Date: Mon, 28 May 2007 20:50:24 GMT
Server: Apache/1.3.37 (Unix) mod_auth_passthrough/1.8 mod_log_bytes/1.2 mod_bwlimited/1.4 PHP/4.4.4 FrontPage/5.0.2.2635.SR1.2 mod_ssl/2.8.28 OpenSSL/0.9.8a
X-powered-by: PHP/4.4.4
Refresh: 0; url=account-login.php?returnto=%2Ftorrents-details.php%3Fid%3D1797
Connection: close
</code></pre>

<p>If you try to open this URL in a browser it will be immediatly redirected to url=account-login.php?returnto=%2Ftorrents-details.php%3Fid%3D1797 .
Should Zend_Http_Client follow this responses a redirect?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-05-29T03:51:17.000+0000</p> 
        <div class="body">
            <p>The "Refresh" header is not standard AFAIK and I could not find it in any RFC. I understand many browsers support it, but I am not sure it should be implemented in the HTTP client but rather in a separate layer.</p>

<p>What do I mean?
Browsers are more than HTTP clients - they also render and "execute" HTTP response content. That is, if an HTTP server tells the browser to "Refresh" a page in 5 seconds, it will - this is not something we should implement in an HTTP client. The fact that "Refresh: 0" behaves like redirection is interesting, but I don't think it's the correct way to redirect, plus I don't think we should implement a special case just for "Refresh: 0" responses.</p>

<p>You can always implement this functionality yourself, and quite easily also, by either wrapping or extending the HTTP client class.</p>

<p>If you still think this is a good idea, I suggest moving the discussion to fw-general@lists.zend.com so everyone can have their say.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simone Carletti (weppos) on 2007-05-29T10:01:22.000+0000</p> 
        <div class="body">
            <p>Hi Shahar,
I agree with you. This functionality might easily be implemented in a custom extension of HTTP Client.</p>

<p>I agree as well browsers are more than a simple HTTP Client. :)</p>

<p>Thanks for your answer,
Simone</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-05-29T10:09:50.000+0000</p> 
        <div class="body">
            <p>Ok then - I am closing the issue. If you even want to discuss this further, please start a thread on one of the mailing lists. Feel free to reopen the issue if you thing the community shows interest in such feature.</p>

        </div>
    </div>
    </div>

