<h2>ZF-11512: Zend_Tool_Project_Provider_Layout not properly detecting existing layout configuration</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-29T05:22:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-29T20:23:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.8 (07/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Kim Blomqvist (kblomqvist)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14427/ZF-11512.patch">ZF-11512.patch</a></li>
            <li><a href="/issues/secure/attachment/14428/ZF-11512.rev2.patch">ZF-11512.rev2.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When enabling layout using "zf enable layout" on a project that has already has been enabled doesn't get picked up.
This is due to a typo in the if-statement.
Nothing drastic happens except another " resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts/" " is added to the application.ini file
Also, the .zfproject.xml file isn't updated correctly</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rod Pattison (rodp82) on 2011-06-29T05:30:39.000+0000</p> 
        <div class="body">
            <p>Apologies for pasting in the patch here, not sure how to attach it</p>

<h1>Index: Layout.php</h1>

<p>--- Layout.php  (revision 24161)
+++ Layout.php  (working copy)
@@ -70,7 +70,7 @@</p>

<pre><code>     $zc = $applicationConfigResource-&gt;getAsZendConfig();
</code></pre>

<ul><li>if (isset($zc-&gt;resources) &amp;&amp; isset($zf-&gt;resources-&gt;layout)) {</li>
<li><pre><code> if (isset($zc-&gt;resources) &amp;&amp; isset($zc-&gt;resources-&gt;layout)) {
     $this-&gt;_registry-&gt;getResponse()-&gt;appendContent('A layout resource already exists in this project\'s application configuration file.');
     return;
 }
</code></pre>

<p>@@ -93,6 +93,8 @@
             );</p>

<pre><code>     $this-&gt;_registry-&gt;getResponse()-&gt;appendContent('A layout entry has been added to the application config file.');
</code></pre></li>
<li></li>
<li>$this-&gt;_storeProfile();
     }</li>
</ul>
        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-06-29T11:30:38.000+0000</p> 
        <div class="body">
            <p>Hi Rob,</p>

<p>Thanks for the patch to contribute to ZF. However, before contributing code you should sign the cla (<a href="http://framework.zend.com/wiki/display/ZFPROP/Contributor+License+Agreement">http://framework.zend.com/wiki/display/…</a>). After then you can attach files.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-06-29T17:33:12.000+0000</p> 
        <div class="body">
            <p>Patch attached. Also implements {{zf disable layout}}.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-06-29T20:12:36.000+0000</p> 
        <div class="body">
            <p>Disable layout feature removed from the patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-06-29T20:17:01.000+0000</p> 
        <div class="body">
            <p>Reproduce (stdout trimmed for brevity):</p>

<pre class="highlight"><code>
[adam@zfdev tmp] zf create project ZF-11512
[adam@zfdev tmp] cd ZF-11512
[adam@zfdev ZF-11512] zf enable layout
[adam@zfdev ZF-11512] zf enable layout
</code></pre>

<p>Result: 
{{application/configs/application.ini}} now contains two {{resources.layout.layoutPath}} lines under the {{production}} group:</p>

<pre class="highlight"><code>
resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts/"
resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts/"
</code></pre>

<p>Rob's suggested fix:</p>

<pre class="highlight"><code>

Index: library/Zend/Tool/Project/Provider/Layout.php
===================================================================
--- library/Zend/Tool/Project/Provider/Layout.php       (revision 24163)
+++ library/Zend/Tool/Project/Provider/Layout.php       (working copy)
@@ -70,7 +70,7 @@

         $zc = $applicationConfigResource-&gt;getAsZendConfig();

-        if (isset($zc-&gt;resources) &amp;&amp; isset($zf-&gt;resources-&gt;layout)) {
+        if (isset($zc-&gt;resources) &amp;&amp; isset($zc-&gt;resources-&gt;layout)) {
             $this-&gt;_registry-&gt;getResponse()-&gt;appendContent('A layout resource already exists in this project\'s application configuration file.');
             return;
         }
@@ -95,8 +95,7 @@
             $this-&gt;_registry-&gt;getResponse()-&gt;appendContent('A layout entry has been added to the application config file.');
         }

-
-
+        $this-&gt;_storeProfile();
     }

     public function disable()
</code></pre>

<p>After applying patch, running reproduce sequence from above now shows desired result:
(most stdout trimmed for brevity):</p>

<pre class="highlight"><code>
[adam@zfdev tmp] zf create project ZF-11512
[adam@zfdev tmp] cd ZF-11512
[adam@zfdev ZF-11512] zf enable layout
[adam@zfdev ZF-11512] zf enable layout
A layout resource already exists in this project's application configuration file.

</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-06-29T20:21:38.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24164
Merged to release-1.11 in r24165</p>

        </div>
    </div>
    </div>

