<h2>ZF-10524: Ability to edit / delete comments made before in this Issue Tracker</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Community Driven Feature</dd>

    <dt>Created:</dt>
    <dd>2010-10-07T03:21:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-07T03:24:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I didn't know how to categorize this request so I have put it in here.</p>

<p>It would be nice to be able to edit or delete comments made before (here in the Issue Tracker) in case there are typos or other errors.
Actually editing nor deleting is possible.</p>

<p>Thank you!
With best regards
Inno</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-10-07T03:24:41.000+0000</p> 
        <div class="body">
            <p>You can already both edit and delete your own comments as long as you are logged in.</p>

        </div>
    </div>
    </div>

