<h2>ZF-1283: Zend_Service_Amazon_OfflineTest Unit Tests Failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-04-17T00:20:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>At revision 4519.:</p>

<p>13) testItemSearchOptionSearchIndexMissing(Zend_Service_Amazon_OfflineTest)
Expected Zend_Service_Exception not thrown
/home/sebastian/Work/ZendFramework/tests/Zend/Service/Amazon/OfflineTest.php:117</p>

<p>14) testItemLookupExceptionAsinInvalid(Zend_Service_Amazon_OnlineTest)
Failed asserting that  contains "not a valid value for ItemId".
/home/sebastian/Work/ZendFramework/tests/Zend/Service/Amazon/OnlineTest.php:235</p>

<p>15) testItemLookupExceptionSearchIndex(Zend_Service_Amazon_OnlineTest)
Failed asserting that  contains "restricted parameter combination".
/home/sebastian/Work/ZendFramework/tests/Zend/Service/Amazon/OnlineTest.php:268</p>

<p>16) testQueryExceptionCategoryInvalid(Zend_Service_Amazon_OnlineTest)
Failed asserting that  contains "SearchIndex is invalid".
/home/sebastian/Work/ZendFramework/tests/Zend/Service/Amazon/OnlineTest.php:312</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-17T11:16:48.000+0000</p> 
        <div class="body">
            <p>Updated priority, affects version, and fix version. Assigning to self.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-17T11:50:50.000+0000</p> 
        <div class="body">
            <p>Sebastian, what versions of PHP and PHPUnit are you using, and on which platform?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-17T12:07:17.000+0000</p> 
        <div class="body">
            <p>Online tests require a valid access key id to be specified in TestConfiguration.php. Resolved with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4525">SVN r4525</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-04-17T12:37:26.000+0000</p> 
        <div class="body">
            <p>I guess, the platform information is not required anymore?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-04-17T12:40:30.000+0000</p> 
        <div class="body">
            <p>Not fixed with 4525.</p>

<p>define('TESTS_ZEND_SERVICE_AMAZON_ONLINE_ENABLED', true);</p>

<p>should be changed to</p>

<p>define('TESTS_ZEND_SERVICE_AMAZON_ONLINE_ENABLED', true);</p>

<p>in tests/TestConfiguration.php.dist</p>

<p>or</p>

<p>TESTS_ZEND_SERVICE_AMAZON_ONLINE_ACCESSKEYID should be filled with something</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-17T14:34:30.000+0000</p> 
        <div class="body">
            <p>Oops - of course! Thank you, Sebastian, for pointing this out. :) Fixed \<a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4526">again] in [SVN r4526</a>.</p>

        </div>
    </div>
    </div>

