<h2>ZF-12147: Zend_Service_Twitter_Search::search does not support 'include_entities' parameter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-10T21:25:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-10T21:28:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Lloyd Watkin (lloydwatkin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Lloyd Watkin (lloydwatkin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In order to include entity information a user needs to be able to pass 'include_entities=1' as a paramter with twitter search. This is not supported at present</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Lloyd Watkin (lloydwatkin) on 2012-04-10T21:28:00.000+0000</p> 
        <div class="body">
            <p>Code to add at line 146 of Zend/Service/Twitter/Search:</p>

<pre><code>            case 'include_entities':
                if (true == $param) {
                    $_query[$key] = 1;
                }
                break;
</code></pre>

<p>I will do this as soon as I get some time to add myself unless anyone gets there first.</p>

        </div>
    </div>
    </div>

