<h2>ZF-10178: Zend_Mail_Storage_Imap::getNumberByUniqueId should cache unique ids </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Performance Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-07-19T07:18:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Maciej Wiercinski (mwiercinski)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
    public function getUniqueId($id = null)
    {
        if ($id) {
            return $this-&gt;_protocol-&gt;fetch('UID', $id);
        }

        return $this-&gt;_protocol-&gt;fetch('UID', 1, INF);
    }
</code></pre>

<pre class="highlight"><code>
    public function getNumberByUniqueId($id)
    {
        // TODO: use search to find number directly
        $ids = $this-&gt;getUniqueId();
        foreach ($ids as $k =&gt; $v) {
            if ($v == $id) {
                return $k;
            }
        }

        /**
         * @see Zend_Mail_Storage_Exception
         */
        require_once 'Zend/Mail/Storage/Exception.php';
        throw new Zend_Mail_Storage_Exception('unique id not found');
    }
</code></pre>

<p>As required in RFC 3501, UID must be at persistent at least during a single session. This makes it feasible to locally cache return of getUniqueId,  what will result with huge performance in certain situations.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

