<h2>ZF-10610: Zend_Service_Amazon_Sqs is not using the region to create queues</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-28T13:18:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-26T16:27:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.11 (29/Sep/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Enrico Zimuel (zimuel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14665/Sqs.patch">Sqs.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Create queue is not using the region to correctly create the queue on the specified Amazon Endpoint.
Amazon has four endpoints that can be used based on your location <a href="http://docs.amazonwebservices.com/AWSSimpleQueueService/2009-02-01/SQSDeveloperGuide/">http://docs.amazonwebservices.com/AWSSimpleQueueSe…</a>
Create is not using the region parameter to create queues on the correct endpoint.</p>

<p>In Zend_Service_Amazon_Sqs the _makeRequest method should take into account the region that was specified in the constructor.</p>

<p>$client-&gt;setUri('<a href="">http://'.$this</a>-&gt;_sqsEndpoint);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jesper Forsberg (uppe) on 2011-08-30T21:26:24.000+0000</p> 
        <div class="body">
            <p>I worked around this by extending the class with this method and putting it to use in the constructor.</p>

<p>protected function _setEndpoint($endpoint) 
{
    $this-&gt;_sqsEndpoint = $endpoint;
}</p>

<p>public function __construct($accessKey = null, $secretKey = null, $region = null)
{
    parent::__construct($accessKey, $secretKey, $region);
    $endpoint = "sqs.$region.amazonaws.com";
    $this-&gt;_setEndpoint($endpoint);
}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jesper Forsberg (uppe) on 2011-08-30T21:28:33.000+0000</p> 
        <div class="body">
            <p>Sorry for that terrible formatting. Let me try that again.</p>

<pre class="highlight"><code>
protected function _setEndpoint($endpoint) 
{
    $this-&gt;_sqsEndpoint = $endpoint;
}
    
public function __construct($accessKey = null, $secretKey = null, $region = null)
{
    parent::__construct($accessKey, $secretKey, $region);
    $endpoint = "sqs.$region.amazonaws.com";
    $this-&gt;_setEndpoint($endpoint);
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christoph Kempen (webpatser) on 2011-09-25T08:37:05.000+0000</p> 
        <div class="body">
            <p>Added the code to override the default region.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christoph Kempen (webpatser) on 2011-09-25T10:26:35.000+0000</p> 
        <div class="body">
            <p>Added a list of possible endpoints (as of 2011-09-25) and a method to add new regions if they appear..</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Enrico Zimuel (zimuel) on 2011-09-26T16:23:56.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk (commit #24469).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Enrico Zimuel (zimuel) on 2011-09-26T16:27:59.000+0000</p> 
        <div class="body">
            <p>Fixed in branches/release-1.11 (commit #24470)</p>

        </div>
    </div>
    </div>

