<h2>ZF-1256: Zend/Cache/Backend/ZendPlatform.php missing require_once for the class it extends</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-04-12T12:48:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                John Baldock (falesh)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend/Cache/Backend/ZendPlatform.php extends Zend_Cache_Backend but does not require_once it</p>

<pre class="highlight"><code>
/**
 * Zend_Cache_Backend
 */
require_once 'Zend/Cache/Backend.php';
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-12T16:19:00.000+0000</p> 
        <div class="body">
            <p>Resolve in revision 4486.</p>

        </div>
    </div>
    </div>

