<h2>ZF-11724: INSERT IGNORE</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-09-06T11:58:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-05T22:57:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Miriam Natanzon (mirian)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
            <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>how can I [erform "insert ignore" using the "insert" zend function and not the general "query" function???
thanks!
Miriam</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-05T22:57:59.000+0000</p> 
        <div class="body">
            <p>INSERT IGNORE is not portable and so is unlikely to be directly supported via the {{insert}} method.</p>

        </div>
    </div>
    </div>

