<h2>ZF-1318: HTTPS connection through Proxy</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-04-26T15:21:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I try to  make HTTPS connection through Proxy with Zend_Http_Client and Zend_Http_Client_Adapter_Proxy. but always get expection "Unable to read response, or response is empty". Proxy has been verified no problem. After some debugging, I found that the only message returned from the proxy is "Connection: close".</p>

<p>p.s. make direct HTTPS connection works fine with Zend_Http_Client.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-04-29T04:06:44.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>Is this proxy open? Can you pass some example code and if possible the address of a proxy I can test on?</p>

<p>TIA,</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by ming (myhusky) on 2007-04-29T13:11:07.000+0000</p> 
        <div class="body">
            <p>here are some code you can take a look. the proxy used is Tor,  I donot have a open to public proxy server , but you can easily install Tor on almost any platform.</p>

<pre class="highlight"><code>
&lt;?php

require_once 'Zend/Http/Client.php';
require_once('Zend/Http/CookieJar.php');
require_once 'Zend/Db.php';

session_start();

$client = new Zend_Http_Client();
$client-&gt;setConfig(
    array(
    'maxredirects'      =&gt; 5,
    'useragent'          =&gt; 'Mozilla/5.0 (Windows; U; Windows NT 5.1;
en-US; rv:1.8.1.3) Gecko/20070309 Firefox/2.0.0.3',
    'timeout'           =&gt; 30,
    'keepalive'      =&gt; true,
    'adapter'    =&gt; 'Zend_Http_Client_Adapter_Proxy',
    //'ssltransport' =&gt; 'ssl',
    'proxy_host' =&gt; 'localhost',
    'proxy_port' =&gt; 8118,
    )
);

$client-&gt;setUri('<a href="https://www.apache-ssl.org">https://www.apache-ssl.org</a>');
try {
   $response = $client-&gt;request();
} catch (Zend_Http_Client_Exception $ex) {
   // Report the exception to the user
   die('Client Excep'.$ex-&gt;getMessage());
} catch (Zend_Http_Exception $ex) {
    die('Http Excep'. $ex-&gt;getMessage());
}
echo $response-&gt;getBody();

?&gt;
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-05-01T07:11:22.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>I've done some research and I believe that in order to properly support tunneling of HTTPS connections, we need to properly implement the CONNECT method in the client.</p>

<p>This is a big change and thus cannot be applied on the main branch before 1.0 is released. Also, it would require some time to work on.</p>

<p>I will do my best to look into this, but I am not sure this will be supported soon.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by ming (myhusky) on 2007-05-02T12:25:01.000+0000</p> 
        <div class="body">
            <p>OK then, thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-05-09T02:41:11.000+0000</p> 
        <div class="body">
            <p>Changed to 'new feature' - add proper support for HTTP CONNECT requests</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-07-31T10:32:31.000+0000</p> 
        <div class="body">
            <p>Support was added in one of the latest revisions and should be available in SVN HEAD. I am still waiting for feedback (got none) to see if it properly works or not.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by ming (myhusky) on 2007-07-31T16:08:16.000+0000</p> 
        <div class="body">
            <p>I have tested the ZF latest revision. It did not work, I'm getting following errors</p>

<p>Warning:  stream_socket_enable_crypto() [streams.crypto]: this stream does not support SSL/crypto in /Applications/Zend/ZendStudio-5.5.0/bin/ZendFramework/library/Zend/Http/Client/Adapter/Proxy.php on line 194</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by ming (myhusky) on 2007-07-31T16:31:02.000+0000</p> 
        <div class="body">
            <p>above my last comment, the problem was because of I did not have openssl installed.</p>

<p>It works now!!!</p>

<p>Thanks!!!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-10-11T13:14:32.000+0000</p> 
        <div class="body">
            <p>No complaints yet - seems to be relatively well implemented. If any bugs appear they should be opened as new issues.</p>

        </div>
    </div>
    </div>

