<h2>ZF-1745: authenticate() not working with DB in fetch mode ASSOC</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-07-20T08:36:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T18:32:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.1 (30/Jul/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1397">ZF-1397</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When setting DB fetch mode to Zend_Db::FETCH_OBJ authentication returns exceptions as in DBTable authentication tries to retrieve via fetchAll and tries to get informations.</p>

<p>The problem is mainly in line 317 of file /Zend/Auth/Adapter/DBTable.php:</p>

<pre class="highlight"><code>
$resultIdentities = $this-&gt;_zendDb-&gt;fetchAll($dbSelect-&gt;__toString());
</code></pre>

<p>and in lines 340 and 346, array value is used:</p>

<pre class="highlight"><code>
$resultIdentity['zend_auth_credential_match']
</code></pre>

<p>Changing to fetchAssoc could solve this but there is a bug in the fetchAssoc() function that still returns an array of objects (I'm posting another issue for that).</p>

<p>For now I fixed the problem by adding this before line 315:</p>

<pre class="highlight"><code>
$oldFetchMode = $this-&gt;_zendDb-&gt;getFetchMode();
$this-&gt;_zendDb-&gt;setFetchMode(Zend_Db::FETCH_ASSOC);
</code></pre>

<p>And adding this after line 326:</p>

<pre class="highlight"><code>
$this-&gt;_zendDb-&gt;setFetchMode($oldFetchMode);
</code></pre>

<p>So this retrieves fetch mode, changes to assoc and gets back to what it was after the query is executed.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-07-20T09:13:43.000+0000</p> 
        <div class="body">
            <p>Resolved as duplicating [ZF-1397].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T18:32:34.000+0000</p> 
        <div class="body">
            <p>Updating Fix Version to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

