<h2>ZF-11877: The documentation about Zend_Validate_GreaterThan is wrong</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-11-09T11:43:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-11-11T16:42:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The documentation is on the following URL: <a href="http://framework.zend.com/manual/en/zend.validate.set.html#zend.validate.set.greaterthan">http://framework.zend.com/manual/en/…</a></p>

<p>It says that "The above example returns TRUE for all values which are equal to 10 or greater than 10."
The problem is that Zend_Validate_GreaterThan will never return true if the values are equal.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-11-09T17:36:18.000+0000</p> 
        <div class="body">
            <p>The manual page entry says that the {{min}} parameter "Sets the minimum allowed value", but that is not the implemented behavior:</p>

<pre class="highlight"><code>
$valid = new Zend_Validate_GreaterThan(array('min' =&gt; 10)));
$valid-&gt;isValid(9);   // returns FALSE
$valid-&gt;isValid(10);  // returns FALSE
$valid-&gt;isValid(11);  // returns TRUE
</code></pre>

<p>The manual page describes a "greater than or equal to" validator, but the implementation is strictly "greater than".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-11-09T17:40:59.000+0000</p> 
        <div class="body">
            <p>Possible fix:</p>

<pre class="highlight"><code>
Index: documentation/manual/en/module_specs/Zend_Validate-GreaterThan.xml
===================================================================
--- documentation/manual/en/module_specs/Zend_Validate-GreaterThan.xml  (revision 24554)
+++ documentation/manual/en/module_specs/Zend_Validate-GreaterThan.xml  (working copy)
@@ -28,7 +28,7 @@
         
-                    min: Sets the minimum allowed value.
+                    min: Sets the minimum border value.
                 
@@ -44,14 +44,13 @@

         
 $valid  = new Zend_Validate_GreaterThan(array('min' =&gt; 10));
-$value  = 10;
-$return = $valid-&gt;isValid($value);
-// returns true
+$valid-&gt;isValid(9);   // returns false
+$valid-&gt;isValid(10);  // returns false
+$valid-&gt;isValid(11);  // returns true
 
-            The above example returns TRUE for all values which are equal to 10
-            or greater than 10.
+            The above example returns TRUE for all values which are greater than 10.
         </code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-11-11T16:42:56.000+0000</p> 
        <div class="body">
            <p>Implementation fixed in ZF2</p>

        </div>
    </div>
    </div>

