<h2>ZF-140: Zend_DB PDO insert</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-23T08:10:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.4 (29/Jun/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Shaun Mitchell (shaun.mitchell)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-159">ZF-159</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using the PDO to perform an insert and the column name contains an underscore it can't find the binded paramater.</p>

<p>$db = Zend_Db::factory('pdoMssql', array(CONNECTION STUFF));
$db-&gt;insert('TABLENAME', array('column_name' =&gt; 1234));</p>

<p>Fails: SQLSTATE[HY093]: Invalid parameter number: parameter was not defined</p>

<p>In the Zend/Db/Adapter/Pdo/Abstract.php insert method the binded value replaces _ to nothing but the binded keys are not also replaced so PDO can't find the match.</p>

<p>Using the above as an example the SQL looks like: INSERT INTO TABLENAME(column_name) VALUES(:columnname) but the $bind array still looks like ('column_name' =&gt; 1234).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by jim kovalchuk (regulate) on 2006-06-23T13:03:18.000+0000</p> 
        <div class="body">
            <p>I'm pretty sure this is a dup and has been fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-06-28T19:25:58.000+0000</p> 
        <div class="body">
            <p>Yes, this should be fixed in the "developer" version.</p>

<p><a href="http://framework.zend.com/wiki/display/ZFDEV/Zend+Framework+Subversion+%28SVN%29+Standards">Downloading the latest Developer/Subversion version of the ZF</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-06-28T19:32:23.000+0000</p> 
        <div class="body">
            <p>Fixed in <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/trunk?cs=386">Changeset 386</a>.</p>

        </div>
    </div>
    </div>

