<h2>ZF-10253: Zend_Date improperly interprets ISO_8601 dates</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-07-30T13:21:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Description: When passing ISO_8601-compliant dates, complete with timezone, one expects Zend_Date to properly accept and parse that date. However, it does not.</p>

<p>Note the actual result below, Zend_Date ignores the timezone on the date and instead assumes the local timezone (which for me was America/New_York) while DateTime does not.</p>

<p>Code:</p>

&lt;?php
$time = '2010-07-29 17:11:52.241004+00';
$dt = new DateTime($time);
$dt2 = new Zend_Date($time, Zend_Date::ISO_8601);
echo 'Time: ' . $time . '<br />';
echo 'DateTime: ' . $dt-&gt;format('c') . '<br />';
echo 'Zend_Date: ' . $dt2-&gt;get(Zend_Date::ISO_8601);
?&gt;

<p>Expected Result:
Time: 2010-07-29 17:11:52.241004+00
DateTime: 2010-07-29T17:11:52+00:00
Zend_Date: 2010-07-29T17:11:52+00:00</p>

<p>Actual Result:</p>

<p>Time: 2010-07-29 17:11:52.241004+00
DateTime: 2010-07-29T17:11:52+00:00
Zend_Date: 2010-07-29T17:11:52-04:00</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-07-30T14:01:25.000+0000</p> 
        <div class="body">
            <p>Actually wether the millisecond part nor the truncated timezone are proper ISO_8601 inputs.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Brandon Savage (brandonsavage) on 2010-08-03T06:39:48.000+0000</p> 
        <div class="body">
            <p>According to the Wikipedia article on ISO 8601, the truncated UTC offset is valid. (See <a href="http://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators">http://en.wikipedia.org/wiki/ISO_8601/…</a> for more)</p>

<p>The fractional time is not ISO 8601; however, the removal of this does not affect the bug.</p>

        </div>
    </div>
    </div>

