<h2>ZF-11854: Zend_Json::prettyPrint causes warning when empty array given</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-27T19:02:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-28T14:00:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ondrej Machulda (ondram)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When empty array is given to Zend_Json::prettyPrint, it causes two warnings:</p>

<pre class="highlight"><code>
Zend_Json::prettyPrint(array());
</code></pre>

<p>Output:
{quote}
<em>Warning:</em> preg_split() expects parameter 2 to be string, array given in /usr/share/php5/Zend-1.11.11/Json.php on line 373
<em>Warning:</em> Invalid argument supplied for foreach() in /usr/share/php5/Zend-1.11.11/Json.php on line 403
{quote}</p>

<p>The encode() works properly:</p>

<pre class="highlight"><code>
echo Zend_Json::encode(array());
</code></pre>

<p>Output:
{quote}
[]
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-28T14:00:07.000+0000</p> 
        <div class="body">
            <p>This is not a valid usage of {{Zend_Json::prettyPrint}}.  That function accepts only JSON-encoded strings.  To work correctly, your first code sample would have to look like this:</p>

<pre class="highlight"><code>
Zend_Json::prettyPrint(Zend_Json::encode(array()));
</code></pre>

<p>Method signature for {{Zend_Json::prettyPrint}}:</p>

<pre class="highlight"><code>
/**
 * Pretty-print JSON string
 *
 * Use 'format' option to select output format - currently html and txt supported, txt is default
 * Use 'indent' option to override the indentation string set in the format - by default for the 'txt' format it's a tab
 *
 * @param string $json Original JSON string
 * @param array $options Encoding options
 * @return string
 */
public static function prettyPrint($json, $options = array())
</code></pre>

        </div>
    </div>
    </div>

