<h2>ZF-11027: Zend_Form_Element::loadDefaultDecorators now doesn't allow form to serialize correctly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-02-03T08:24:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-03T08:36:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Between versions 1.10 and 1.11, a change was made to the Zend_Form_Element::loadDefaultDecorators class method.</p>

<p>In 1.10 the method is as follows:</p>

<pre class="highlight"><code>
    public function loadDefaultDecorators()
    {
        if ($this-&gt;loadDefaultDecoratorsIsDisabled()) {
            return $this;
        }

        $decorators = $this-&gt;getDecorators();
        if (empty($decorators)) {
            $this-&gt;addDecorator('ViewHelper')
                -&gt;addDecorator('Errors')
                -&gt;addDecorator('Description', array('tag' =&gt; 'p', 'class' =&gt; 'description'))
                -&gt;addDecorator('HtmlTag', array('tag' =&gt; 'dd',
                                                'id'  =&gt; $this-&gt;getName() . '-element'))
                -&gt;addDecorator('Label', array('tag' =&gt; 'dt'));
        }
        return $this;
    }
</code></pre>

<p>In 1.11 it was changed to this:</p>

<pre class="highlight"><code>
    public function loadDefaultDecorators()
    {
        if ($this-&gt;loadDefaultDecoratorsIsDisabled()) {
            return $this;
        }

        $decorators = $this-&gt;getDecorators();
        if (empty($decorators)) {
            $getId = create_function('$decorator',
                                     'return $decorator-&gt;getElement()-&gt;getId()
                                             . "-element";');
            $this-&gt;addDecorator('ViewHelper')
                 -&gt;addDecorator('Errors')
                 -&gt;addDecorator('Description', array('tag' =&gt; 'p', 'class' =&gt; 'description'))
                 -&gt;addDecorator('HtmlTag', array('tag' =&gt; 'dd',
                                                 'id'  =&gt; array('callback' =&gt; $getId)))
                 -&gt;addDecorator('Label', array('tag' =&gt; 'dt'));
        }
        return $this;
    }
</code></pre>

<p>The anonymous function in the 1.11 release doesn't allow storing the element in the session properly, since the lambda function cannot be serialized.  The lamdba function should probably be replaced by a class method (that can be serialized).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-03T08:36:01.000+0000</p> 
        <div class="body">
            <p>Added code tags.</p>

        </div>
    </div>
    </div>

