<h2>ZF-10499: Invalid mapping of objects to xsd:struct</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-09-27T01:06:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to the <a href="http://www.zendframework.com/manual/en/zend.soap.wsdl.html#zend.soap.wsdl.types">manual</a> PHP objects are mapped to "xsd:struct" but i cant find any specification of this type.</p>

<p>A schema may work but eviware soapUI will throw</p>

<pre class="highlight"><code>org.apache.xmlbeans.XmlException:
<a href="http://example.org/index.php?wsdl=show:0">http://example.org/index.php?wsdl=show:0</a>: error: src-resolve.a:
Could not find type 'struct@<a href="http://www.w3.org/2001/XMLSchema">http://www.w3.org/2001/XMLSchema</a>'.
Do you mean to refer to the element named Struct@<a href="http://schemas.xmlsoap.org/soap/encoding/">http://schemas.xmlsoap.org/soap/encoding/</a> (in soapEncoding.xsd)?</code></pre>

<p>Trivial because one can always use mixed instead of object, but it's not clear and doesn't make sense at all if the type is not specified.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

