<h2>ZF-10081: Zend_Log_Writer_ZendMonitor  Wrong parameter type for monitor_custom_event() </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-06-30T02:46:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-08-13T02:22:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.7 (28/Jul/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10308">ZF-10308</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Warning: monitor_custom_event() expects parameter 3 to be boolean, array given in [...]/ZendMonitor.php on line 106</p>

<p>example Code:
$writer = new Zend_Log_Writer_ZendMonitor();
$log    = new Zend_Log($writer);
$log-&gt;log('testtext', Zend_Log::INFO);</p>

<p>Zend_Log_Writer_ZendMonitor-&gt;write();
should use bool value instead of arrray $event.</p>

<p>used in Zend Platform Version 3.6.2</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-06-30T10:11:56.000+0000</p> 
        <div class="body">
            <p>Assigned to component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-07-06T19:40:58.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r22531 merged in branch release-1.10 r22533.</p>

        </div>
    </div>
    </div>

