<h2>ZF-11234: Using Zend_Text_Table without autoloader results in: Class 'Zend_Text_Table_Column' not found</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-28T11:04:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-10T20:50:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jeroen Tietema (jtietema)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Text_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using the Zend_Text_Table class without an autoloader the class Zend_Text_Table_Column is not loaded by the Zend_Text_Table class.</p>

<p>PHP Fatal error:  Class 'Zend_Text_Table_Column' not found in /var/www/initium/ipp/lib/vendor/Zend/Text/Table.php on line 355</p>

<p>This can trivially be fixed by adding require_once 'Zend/Text/Table/Column.php'; at line 354</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-04-10T20:50:01.000+0000</p> 
        <div class="body">
            <p>Fix in trunk r23856 merged to branch release 1.11 r23857.</p>

        </div>
    </div>
    </div>

