<h2>ZF-11268: Zend_Translate_Adapter: option &quot;logUntranslated&quot; is described the wrong way</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-04-07T14:45:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-29T07:00:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.9 (14/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There's a mistake in the doc for the $_options var in the class Zend_Translate_Adapter. It is said for the option 'logUntranslated': "when true, untranslated messages are not logged". The word "not" should be removed.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-07-29T07:00:07.000+0000</p> 
        <div class="body">
            <p>I can not verify this mistake. Wether within the actual online documentation nor within svn.</p>

<p>The documentation reads: "When this option is set to TRUE, all message IDs which can not be translated will be written into the attached log"</p>

<p>This description is correct.</p>

<p>According to svn this text has not changed since more than 1.5 years.</p>

        </div>
    </div>
    </div>

