<h2>ZF-1656: Using specific lifetime record for cache with infinite lifetime</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-29T16:37:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T18:32:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.1 (30/Jul/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If i have cache with infinite lifetime, like</p>

<p>$frontendOptions = array(
   'lifetime' =&gt; null, 
   ...
);</p>

<p>$backendOptions = array(
    ...
);</p>

<p>$cache = Zend_Cache::factory('Core', 'File', $frontendOptions, $backendOptions);</p>

<p>And i want to save the record with specific lifetime:</p>

<p>$cache-&gt;save( $data, $id, $tags, 60 );</p>

<p>It couldn't work, because in Backend\File.php  in function save(), is used private function _expireTime():</p>

<pre><code>private function _expireTime($lifetime) 
{
    if (is_null($this-&gt;_directives['lifetime'])) {
        return 9999999999;
    }
    return time() + $lifetime;
}
</code></pre>

<p>And it always return the maximum lifetime 9999999999 in our example.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2007-07-02T15:48:34.000+0000</p> 
        <div class="body">
            <p>fixed in SVN</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-07-27T11:30:37.000+0000</p> 
        <div class="body">
            <p>Also fixes 1.1.0</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T18:32:35.000+0000</p> 
        <div class="body">
            <p>Updating Fix Version to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

