<h2>ZF-10421: Zend_Cache_Backend_Static doesn't set the directory umask correctly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-09-05T12:00:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-16T12:34:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Maxell (maxell)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Bennewitz (private) (mabe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following code in Zend_Cache_Backend_Static causes the problem (starts on line 264):</p>

<pre class="highlight"><code>
if ( !is_dir($path)
  &amp;&amp; !@mkdir($path, $this-&gt;_options['cache_directory_umask'], true)) {
    $lastErr = error_get_last();
    Zend_Cache::throwException("Can't create directory: {$lastErr['message']}");
}
</code></pre>

<p>Fix:</p>

<pre class="highlight"><code>
if ( !is_dir($path)
  &amp;&amp; !@mkdir($path, $this-&gt;_octdec($this-&gt;_options['cache_directory_umask']), true)) {
    $lastErr = error_get_last();
    Zend_Cache::throwException("Can't create directory: {$lastErr['message']}");
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-09-16T12:34:33.000+0000</p> 
        <div class="body">
            <p>fixed in trunk r22949 &amp; r22950</p>

        </div>
    </div>
    </div>

