<h2>ZF-1926: webSearch() returns wrong CacheUrl and CacheSize</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-09-09T13:51:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-26T12:56:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.4 (26/Feb/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Simone Carletti (weppos)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Yahoo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using webSearch() each item has the same CacheUrl and CacheSize. It seems that it's always the data form the first hit.</p>

<p>Reproduce code:</p>

<pre class="literal">
&lt;?php
require_once 'Zend/Service/Yahoo.php';
$yahoo = new Zend_Service_Yahoo("API-KEY");

$results = $yahoo-&gt;webSearch('php');
foreach ($results as $result) 
{
    echo "$result-&gt;Title<br />";
    echo "$result-&gt;Url<br />";
    echo "$result-&gt;CacheUrl<br />";
    echo "$result-&gt;CacheSize<br /><br />";
}    

</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-11T13:00:54.000+0000</p> 
        <div class="body">
            <p>Assigned to Darby</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simone Carletti (weppos) on 2007-12-03T14:21:46.000+0000</p> 
        <div class="body">
            <p>Fixed in r7026</p>

        </div>
    </div>
    </div>

