<h2>ZF-11661: Missing MIME Type for png uploads with Internet Explorer -&gt; image/x-png</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-08-11T09:34:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-26T17:13:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Schramm (schramm)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate_File</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Validate_File_IsImage::__construct</p>

<p>-&gt; default array with mime types without 
image/x-png 
missing for Internet Explorer uploads</p>

<p><a href="http://msdn.microsoft.com/en-us/library/ms775147%28v=vs.85%29.aspx#_replace">http://msdn.microsoft.com/en-us/library/…</a>
see under Uploaded MIME Types section</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-08-26T17:13:27.000+0000</p> 
        <div class="body">
            <p>Added in ZF2 with GH-342</p>

        </div>
    </div>
    </div>

