<h2>ZF-10368: Zend_View_Helper_Action &amp; preDispatch hooks</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-23T07:19:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using Zend_View_Helper_Action, preDispatch events aren't being fired properly for the action being run.
For instance, when using registered Action helpers (derived from Zend_Controller_Action_Helper_Abstract) with preDispatch functions, the hooks work properly.
However, when using Controller Plugins (derived from Zend_Controller_Plugin_Abstract) with those same preDispatch hooks, the functions won't get run.</p>

<p>When using a _forward call within a action, the preDispatch hooks always work properly.</p>

<p>This happends with postDispatch as well as other hooks as well.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

