<h2>ZF-11574: setAdapter('test') fails</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-18T19:11:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-28T20:18:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Till Klampaeckel (till)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I updated a project to use a more recent version of ZF and a unit test failed.</p>

<p>I had {{$client-&gt;setAdapter('test');}} in it in order to use {{Zend_Http_Client_Adapter_Test}}. I'm not really sure what version it used before (it doesn't say). But it's been a long, long while since ZF was updated.</p>

<p>Here's a patch to correct the problem:</p>

<pre class="highlight"><code>
Index: Client.php
===================================================================
--- Client.php  (revision 35)
+++ Client.php  (working copy)
@@ -861,6 +861,9 @@
     public function setAdapter($adapter)
     {
         if (is_string($adapter)) {
+            if (false === strpos($adapter, 'Zend_Http_Client_Adapter_', 0)) {
+                $adapter = 'Zend_Http_Client_Adapter_' . ucfirst(strtolower($adapter));
+            }
             try {
                 Zend_Loader::loadClass($adapter);
             } catch (Zend_Exception $e) {
</code></pre>

<p>If you need a test, let me know where to find them and I'll add a patch for that as well.</p>

<p>Till</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-28T20:18:31.000+0000</p> 
        <div class="body">
            <p>Convenient as this would be, what if you write a custom adapter that isn't in the "Zend_Http_Client_Adapter" vendor prefix, and pass that class name to setAdapter()? As written, the patch would still prepend that prefix, and thus try and load a non-existent class.</p>

<p>I think this is a situation where adding a broker would work best -- and that would need to be done in ZF2.</p>

        </div>
    </div>
    </div>

