<h2>ZF-11069: Label in foreign language isn't displayed!!</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-02-13T02:38:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-16T11:01:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benoît Durand (intiilapa)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I've created a form using Zend_Form but Hebrew labels are not displayed
 (the "escape" call removes them!)</p>

<p>Is there any known solution??</p>

<p>Thanks!!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-13T02:46:50.000+0000</p> 
        <div class="body">
            <p>Can you provide a code sample that reproduces this issue?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Miriam Natanzon (mirian) on 2011-02-14T00:47:20.000+0000</p> 
        <div class="body">
            <p>Sorry to bother the community.. not all my files were encoded in UTF8..</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-14T01:28:51.000+0000</p> 
        <div class="body">
            <p>{quote}
Sorry to bother the community.. not all my files were encoded in UTF8..
{quote}
No problem.</p>

<p>The issue can be closed.</p>

        </div>
    </div>
    </div>

