<h2>ZF-11703: Zend tool can't manage controllers with phpdoc</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-08-28T13:26:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-25T14:11:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Karol Ciba (keici)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Raphael de Almeida (jaguarnet7)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_CodeGenerator</li>
            <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14642/zf11703.r24451.patch">zf11703.r24451.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think there's bug in creating new action in controller with class php doc. Zend tools mangles controller code.</p>

<p>For example, i have class:</p>

<pre class="highlight"><code>
&lt;?php
/**
 * For manipulating files.
 * 
 * @author Karol Ciba
 */
class Admin_FileController extends Zend_Controller_Action
{

    public function init()
    {
    }

    public function indexAction()
    {
        // action body
    }
}
</code></pre>

<p>when i try to create new action with: zf create action list file 1 admin, then controller class looks like this:</p>

<pre class="highlight"><code>
/**
 * For manipulating files.
 *
 * @author Karol Ciba
 *
 */


/**
 * For manipulating files.
 *
 * @author Karol Ciba
 *
 */
class Admin_FileController extends Zend_Controller_Action
{

    public function init()
    {
    }

    public function indexAction()
    {
        // action body
    }

    public function listAction()
    {
        // action body
    }


}

&lt;?php
/* Zend_CodeGenerator_Php_File-DocblockMarker */ 
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Raphael de Almeida (jaguarnet7) on 2011-09-07T20:32:00.000+0000</p> 
        <div class="body">
            <p>The problem is with Zend_CodeGenerator</p>

<p>I create a UnitTest for this.</p>

<pre class="highlight"><code> 
    /**
    * @group ZF-11703
    */
    public function testNewMethodKeepPHPDoc(){
        $codeGenFile = Zend_CodeGenerator_Php_File::fromReflectedFileName(dirname(__FILE__).'/_files/zf-11703.php', true, true);
        $target = &lt;&lt;getClass()-&gt;setMethod(array(
            'name' =&gt; 'listAction',
            'body' =&gt; '// action body'
            ));

        $this-&gt;assertEquals($target, $codeGenFile-&gt;generate());
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Raphael de Almeida (jaguarnet7) on 2011-09-07T23:20:14.000+0000</p> 
        <div class="body">
            <p>The bug occurs in php files with only one docblock.
CodeGenerator don't known if one is for file or for class.</p>

<p>When file has docblock and the class too, this bug don't occurs.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-09-11T13:33:09.000+0000</p> 
        <div class="body">
            <p>Committed in r24456. Thanks for the patch and tests!!!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Karol Ciba (keici) on 2011-09-11T14:11:25.000+0000</p> 
        <div class="body">
            <p>Thanks for fixing, I can get much better documented code now!</p>

        </div>
    </div>
    </div>

