<h2>ZF-11498: No support of Load Balancer X-Forwarded-Proto for HTTPS in Zend_Controller_Request_Http</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-21T06:57:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-13T15:41:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5012">ZF-5012</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>this function only supports use of $_SERVER['HTTPS'], but not supporting 'X-Forwarded-Proto' header.</p>

<pre class="highlight"><code>
public function getScheme()
{
       return ($this-&gt;getServer('HTTPS') == 'on') ? self::SCHEME_HTTPS : self::SCHEME_HTTP;
}
</code></pre>

<p>The support of this header is easy and straight-forward:</p>

<pre class="highlight"><code>
public function getScheme()
{
    if ($this-&gt;getServer('HTTPS') == 'on' || 
        $this-&gt;getServer('HTTP_X_FORWARDED_PROTO') == 'https') {
        return self::SCHEME_HTTPS ;
    } else {        
        return self::SCHEME_HTTP;
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marco Brinkmann (marco.brinkmann) on 2011-07-22T10:18:05.000+0000</p> 
        <div class="body">
            <p>Same here, can't detect SSL behind a load balancer. The LB does SSL termination and provides only HTTP_X_FORWARDED_PROTO.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marco Brinkmann (marco.brinkmann) on 2011-07-22T10:22:25.000+0000</p> 
        <div class="body">
            <p>isSecure() is also affected.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-07-26T14:12:39.000+0000</p> 
        <div class="body">
            <p>Set component and auto-reassign</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordi (jsmolina) on 2012-11-13T15:30:39.000+0000</p> 
        <div class="body">
            <p>No movements since one year ago?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-11-13T15:41:18.000+0000</p> 
        <div class="body">
            <p>Please look here: ZF-5012</p>

        </div>
    </div>
    </div>

