<h2>ZF-11723: Zend_File_Transfer::getFileName() returns empty array when uploading file with name &quot;0&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-06T00:11:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-10T03:15:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Karol Malinowski (malin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
            <li>zf-crteam-review</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14957/ZF-11723.patch">ZF-11723.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_File_Transfer::getFileName() returns empty array when uploading file with name "0"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-06T16:14:28.000+0000</p> 
        <div class="body">
            <p>This happens because {{empty}} is used in {{Zend_File_Transfer_Adapter_Abstract}} on line 949 to determine if a filename was provided.  Since PHP considers the zero string (ie: '0') to be "empty", it skips the file.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-10T03:14:28.000+0000</p> 
        <div class="body">
            <p>Test:</p>

<pre class="highlight"><code>
Index: tests/Zend/File/Transfer/Adapter/AbstractTest.php
===================================================================
--- tests/Zend/File/Transfer/Adapter/AbstractTest.php   (revision 24672)
+++ tests/Zend/File/Transfer/Adapter/AbstractTest.php   (working copy)
@@ -856,6 +856,17 @@
                 'detectInfos' =&gt; false))
             , $this-&gt;adapter-&gt;getOptions('foo'));
     }
+
+    /**
+     * @group ZF-11723
+     */
+    public function testCanReceiveFileHavingNameZero()
+    {
+        $adapter = new ZF11723_MockAdapter();
+        $adapter-&gt;setDestination('/tmp');
+        $this-&gt;assertTrue($adapter-&gt;isValid('foo'));
+        $this-&gt;assertEquals('/tmp/0', $adapter-&gt;getFileName());
+    }
 }
 
 class Zend_File_Transfer_Adapter_AbstractTest_MockAdapter extends Zend_File_Transfer_Adapter_Abstract
@@ -988,6 +999,30 @@
     }
 }
 
+/**
+ * @see ZF-11723
+ */
+class ZF11723_MockAdapter extends Zend_File_Transfer_Adapter_AbstractTest_MockAdapter
+{
+    public function __construct()
+    {
+        parent::__construct();
+        $this-&gt;_files = array(
+            'foo' =&gt; array(
+                'name'      =&gt; '0',
+                'type'      =&gt; 'image/jpeg',
+                'size'      =&gt; 126976,
+                'tmp_name'  =&gt; '/tmp/489127ba5c89c',
+                'options'   =&gt; array('ignoreNoFile' =&gt; false, 'useByteString' =&gt; true, 'detectInfos' =&gt; true),
+                'validated' =&gt; false,
+                'received'  =&gt; false,
+                'filtered'  =&gt; false,
+            ),
+        );
+    }
+}
+
+
 // Call Zend_File_Transfer_Adapter_AbstractTest::main() if this source file is executed directly.
 if (PHPUnit_MAIN_METHOD == "Zend_File_Transfer_Adapter_AbstractTest::main") {
     Zend_File_Transfer_Adapter_AbstractTest::main();

</code></pre>

<p>Result:</p>

<pre class="highlight"><code>
1) Zend_File_Transfer_Adapter_AbstractTest::testCanReceiveFileHavingNameZero
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-/tmp/0
+Array
</code></pre>

<p>Fix:</p>

<pre class="highlight"><code>

Index: library/Zend/File/Transfer/Adapter/Abstract.php
===================================================================
--- library/Zend/File/Transfer/Adapter/Abstract.php (revision 24672)
+++ library/Zend/File/Transfer/Adapter/Abstract.php (working copy)
@@ -946,7 +946,7 @@
         $result    = array();
         $directory = "";
         foreach($files as $file) {
-            if (empty($this-&gt;_files[$file]['name'])) {
+            if (trim($this-&gt;_files[$file]['name']) == '') {
                 continue;
             }
 
</code></pre>

        </div>
    </div>
    </div>

