<h2>ZF-10815: assertQueryContentContains() errors on empty contents</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-12T09:05:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-16T19:42:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Test_PHPUnit</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I want to assert some div is empty by default:
```</p>

<p>Gives me:
{quote}strstr(): Empty delimiter</p>

<p>/home/dolf/Projects/MyProject/library/Zend/Test/PHPUnit/Constraint/DomQuery.php:304
/home/dolf/Projects/MyProject/library/Zend/Test/PHPUnit/Constraint/DomQuery.php:177
/home/dolf/Projects/MyProject/library/Zend/Test/PHPUnit/ControllerTestCase.php:333{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-12-12T12:29:37.000+0000</p> 
        <div class="body">
            <p>I suppose it's redundant, but $this is an instance of Zend_Test_PHPUnit_ControllerTestCase. Also, code is from trunk on svn.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Zachary C (zpchavez) on 2011-03-16T19:42:00.000+0000</p> 
        <div class="body">
            <p>It doesn't make any sense to assert that the query content <em>contains</em> an empty string.  You want to assert that it <em>is</em> an empty string, like so:</p>

<pre class="highlight"><code>
$this-&gt;assertQueryContentRegex('#someId', '/^$/');
</code></pre>

        </div>
    </div>
    </div>

