<h2>ZF-192: Zend_Db_Adapter_Oracle-&gt;describeTable() bad sql request</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-07-04T01:28:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Justin Plock (jplock)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10047/ZF-192.diff">ZF-192.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>SQL request is "descripbe $table".</p>

<p>This will work only in sqlplus tools. It won't via oci drivers</p>

<p>With OCI, you could use something like 
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT FROM USER_TAB_COLUMNS WHERE TABLE_NAME= '$table' ORDER BY COLUMN_NAME</p>

<p>BTW. $table should hold table name in uppercase.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Laurent Taupiac. (titerm) on 2006-07-04T01:49:57.000+0000</p> 
        <div class="body">
            <p>could be fixed this way
in Zend_Db_Adapter_Oracle</p>

<p>public function describeTable($table)
    {
        $table = strtoupper($table);
        $sql = "SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE, DATA_DEFAULT FROM USER_TAB_COLUMNS WHERE TABLE_NAME= '$table' ORDER BY COLUMN_NAME";
        $result = $this-&gt;query($sql);
        while ($val = $result-&gt;fetch() ) {
            $descr[$val['COLUMN_NAME']] = array(
                'name'    =&gt; $val['COLUMN_NAME'],
                'notnull' =&gt; (bool) ($val['NULLABLE'] === 'N'), // NULLABLE is N when mandatory
                'type'    =&gt; $val['DATA_TYPE'],
                'default'    =&gt; $val['DATA_DEFAULT'],
                'length'    =&gt; $val['DATA_LENGTH'],
            );
        }
        return $descr;
    }</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laurent Taupiac. (titerm) on 2006-07-11T04:27:13.000+0000</p> 
        <div class="body">
            <p>I attach patch to fixe this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-07-12T13:05:00.000+0000</p> 
        <div class="body">
            <p>Thanks Laurent!  Please submit a CLA, so we can consider your patch.</p>

<p><a href="http://framework.zend.com/wiki/display/ZFPROP/Home#Home-ContributionProcess">Contribution Process</a></p>

<p><a href="http://framework.zend.com/wiki/display/ZFPROP/Contributor+License+Agreement">How to Submit a CLA / CLA FAQ</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:14:33.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.8.0.</p>

        </div>
    </div>
    </div>

