<h2>ZF-1592: Gdata_Calendar_Extension unit tests need to test against sample data for extension attributes/elements</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-06-19T15:00:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1593">ZF-1593</a></li>
            <li><a href="/issues/browse/ZF-1591">ZF-1591</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The unit tests for Gdata_Calendar_Extension classes currently only check to make sure that <em>empty</em> instances have no extension attributes or elements. They should also check to make sure that normal instances (created using the existing element sample data files) have no extension attributes or elements.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-06-19T15:04:48.000+0000</p> 
        <div class="body">
            <p>I'm currently working on a fix for this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-06-19T21:28:47.000+0000</p> 
        <div class="body">
            <p>Fixed in my build for tests in tests/Zend/Gdata/Calender.</p>

<p>Waiting for ZF-1593 to be resolved so this fix can be applied to tests in tests/Zend/Gdata.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-20T13:21:30.000+0000</p> 
        <div class="body">
            <p>Assigning to Ryan.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-06-20T18:55:06.000+0000</p> 
        <div class="body">
            <p>All fixed in my build. Patch sent to rboyd for review.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-20T19:16:20.000+0000</p> 
        <div class="body">
            <p>Fixed in rev 5397</p>

        </div>
    </div>
    </div>

