<h2>ZF-10679: Form ID overrides Fieldset ID and causes dupe IDs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-12T14:14:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-09T05:53:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3896">ZF-3896</a></li>
            <li><a href="/issues/browse/ZF-10803">ZF-10803</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13441/ZF-10679.patch">ZF-10679.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This code:</p>

<pre class="highlight"><code>
$form1 = new Zend_Form();
$form1-&gt;setDecorators(
    array(
        'FormElements',
         array('Fieldset', array('legend' =&gt; '',
                'id' =&gt; 'fieldset-id')),
        'Form',
    )
);
$this-&gt;view-&gt;form1 = $form1;
</code></pre>

<p>produces this form:</p>

<pre class="highlight"><code>


</code></pre>

<p>While this code:</p>

<pre class="highlight"><code>
$form2 = new Zend_Form();
$form2-&gt;setDecorators(
    array(
        'FormElements',
        array('Fieldset', array('legend' =&gt; '',
                'id' =&gt; 'fieldset-id')),
        'Form',
    )
);
$form2-&gt;setAttrib('id', 'form2-id');
$this-&gt;view-&gt;form2 = $form2;
</code></pre>

<p>Produces this form:</p>

<pre class="highlight"><code>


</code></pre>

<p>Note the duplicate ID between the form and the fieldset.  In Zend_Form_Decorator_Fieldset::getOptions() the ID of the form is added to the options for the fieldset element.  Then in render(), because the fieldset has an ID attribute that attribute is not modified.</p>

<p>Expected behavior:</p>

<p>Form ID should not override fieldset ID and the two IDs should not match.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-13T15:09:18.000+0000</p> 
        <div class="body">
            <p>Thanks for the simple test case.  Patch with unit test to resolve issue is attached.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-22T14:43:47.000+0000</p> 
        <div class="body">
            <p>Applied to trunk in r23425, 1.11 release branch in r23426</p>

        </div>
    </div>
    </div>

