<h2>ZF-10250: Don't parse feed and return special result if feed is not modified</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-07-30T08:41:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-02-12T21:27:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Reader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I use Zend_Feed_Reader with cache and HTTP conditional get. It would be very useful to have option with special result when feed is not modified as now I must check that all entries in feed are already parsed earlier (query to my db).
I have my own solution in just "return true;" in if ($response-&gt;getStatus() == 304) { to stop any processing. But it would be useful to have an option "doNotParseAgain" (default disabled to keep BC) that will return something special in that case.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

