<h2>ZF-12448: Adding informing methods on Zend_Db_Select</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-10-19T20:45:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-04-05T16:07:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Db_Select should have methods to inform some things about the query created so far, 
like I have a query and depending on some parameters it can add where clauses or join some tables to it,
and I got to a point where i wanna know if I already concatenate something to the query before, it would be nice to have methods on the class that would inform that like something isTableJoined($tableName) returning a boolean</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-16T16:06:03.000+0000</p> 
        <div class="body">
            <p>If you could sign the CLA (<a href="http://framework.zend.com/wiki/display/ZFPROP/Contributor+License+Agreement">http://framework.zend.com/wiki/display/…</a>) and provide a patch, I'm happy to review it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2013-04-05T16:07:13.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf1/issues/26">https://github.com/zendframework/zf1/issues/26</a></p>

        </div>
    </div>
    </div>

