<h2>ZF-11544: Memcache seems to be offline</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-08T17:36:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-31T14:07:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
            <li>Zend_cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Sometimes, with memcache activated, it seems the memcache server is down.</p>

<p>An exception is thrown each times the problem occures "Can\'t get filling percentage."</p>

<p>The problem is in Zend/Cache/BackendMemcached.php
The function php function getExtendedStats() is buggy and sometimes return false, even if memcache servers are online. The bug is declared here : <a href="http://pecl.php.net/bugs/bug.php?id=22158">http://pecl.php.net/bugs/bug.php?id=22158</a></p>

<p>If you can have only one memcache server, you can use this patch :
//$mems = $this-&gt;_memcache-&gt;getExtendedStats();
$memsStats = $this-&gt;_memcache-&gt;getStats();
$mems = array($memsStats);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Iwan (istaveren) on 2011-09-16T06:23:25.000+0000</p> 
        <div class="body">
            <p>This problem can be reproduced by using the TwoLevel backend and memcached as the fast one.
Then when there is no memcached server available you get the following error:
{quote}
Exception 'Zend_Cache_Exception' with message 'Can't get filling percentage'
{quote}</p>

<p>The problem and fixed it like this:</p>

<pre class="highlight"><code>
Index: 1.11.4/Cache/Backend/Memcached.php
===================================================================
--- 1.11.4/Cache/Backend/Memcached.php  (revision 117)
+++ 1.11.4/Cache/Backend/Memcached.php  (revision 118)
@@ -399,8 +399,12 @@
             $memUsed += $eachUsed;
         }
 
-        if ($memSize === null || $memUsed === null) {
-            Zend_Cache::throwException('Can\'t get filling percentage');
+        if ($memSize === null || $memUsed === null) 
+        {
+          $memSize = 1;
+          $memUsed = 1;
+          $this-&gt;_log('Can\'t get filling percentage', Zend_Log::INFO);
         }
 
         return ((int) (100. * ($memUsed / $memSize)));
</code></pre>

<p>This will return a 100% filling percentage if the memcached server is not available.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nicolas Lescure (nlescure) on 2011-09-16T07:01:31.000+0000</p> 
        <div class="body">
            <p>@Iwan As you said, your patch returns 100% if memcache does not respond, even if memcache <em>is not down</em>. With your solution, you think the disk is full, and your application will generate errors.
You really have to know when there is a problem or not.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gonzalo Sainz-Trapaga (gomox) on 2012-05-31T14:07:31.000+0000</p> 
        <div class="body">
            <p>Workaround for this is just not restarting Memcached. Wipe your cache using the API functions.</p>

        </div>
    </div>
    </div>

