<h2>ZF-11048: View helper binds onload scripts to jQuery's ready event</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-02-08T01:57:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-19T19:24:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Juha Suni (zuhac)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
            <li>FixForZF1.12</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15044/ZendX_JQuery-View-JQuery.xml.patch">ZendX_JQuery-View-JQuery.xml.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Onload scripts registered using JQuery view helper are bound to jQuery's ready event, which is wrong. Even the documentation for ZendX jQuery component says that the view helper handles "$(document).onLoad() events", while it actually uses $(document).ready().</p>

<p>I think that the view helper should use $(window).load() instead of $(document).ready(). Using load event is safer solution, since at onload stage all document resources (including javascript files) are loaded, which is not necessary the case with the ready event.</p>

<p>This suggested solution is unfortunately not fully backwards compatible. See following example, which would be OK in current implementation (not tested):
$this-&gt;jQuery()-&gt;addOnLoad('$(window).load(alert("Registered window onload callback"););');</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-04-23T09:18:49.000+0000</p> 
        <div class="body">
            <p>bq. Using load event is safer solution, since at onload stage all document resources (including javascript files) are loaded, which is not necessary the case with the ready event.</p>

<p>This is not quite true, see [<a href="http://api.jquery.com/ready/">http://api.jquery.com/ready/</a>].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-04-27T17:39:41.000+0000</p> 
        <div class="body">
            <p>Documentation should be clarified so that ready() event is used instead of onLoad(). I think it would be sufficient if</p>

<p>"Handling $(document).onLoad() events."</p>

<p>is replaced by</p>

<p>"Handling $(document).ready() events."</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-04-27T08:19:32.000+0000</p> 
        <div class="body">
            <p>Patch added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-06-19T19:24:17.000+0000</p> 
        <div class="body">
            <p>Fixed in 24980(trunk) and 24981(release-1.12)</p>

        </div>
    </div>
    </div>

