<h2>ZF-11411: Passing DOMDocument to handle() does not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-26T09:39:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-28T19:43:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.7 (02/Jun/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christoph Roensch (croensch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14327/ZF-11411-library.patch">ZF-11411-library.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Soap_Server::handle() accepts a request in the form of DOMDocument, DOMNode, SimpleXMLElement, stdClass and of course string. The XML is saved by Zend_Soap_Server::_setRequest() in a protected member $this-&gt;_request. Instead of the protected member $this-&gt;_request, the function parameter $request is used with SoapServer::handle(), wich silently fails if the request wasnt a string in the first place.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoph Roensch (croensch) on 2011-05-26T22:56:55.000+0000</p> 
        <div class="body">
            <p>The fix is simple, but i guess this <em>should</em> be tested in the first place, regardless of how hard it may be.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-28T18:17:33.000+0000</p> 
        <div class="body">
            <p>Can you demonstrate the failing use case with some code?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-28T19:43:35.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk at r24065 and in release branch 1.11 at r24066</p>

        </div>
    </div>
    </div>

