<h2>ZF-10374: Zend_Controller_Response::setRawHeader() is untestable with Zend_Test_PHPUnit_ControllerTestCase</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-24T06:47:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-06T19:16:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>Zend_Test_PHPUnit</li>
            <li>zf-crteam-review</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm using {{Zend_Controller_Response::setRawHeader()}} in one of my actions:</p>

<pre class="highlight"><code>
$this-&gt;getResponse()-&gt;setRawHeader('HTTP/1.1 300 Multiple Choices');
</code></pre>

<p>In my test case ({{Zend_Test_PHPUnit_ControllerTestCase}}), I'm using the following assertion:</p>

<pre class="highlight"><code>
$this-&gt;assertResponseCode(300);
</code></pre>

<p>This however does not work, I dumped {{Zend_Controller_Response_HttpTestCase}} and noticed the following:</p>

<pre class="highlight"><code>
   '_headersRaw' =&gt; 
  array (
    0 =&gt; 'HTTP/1.1 300 Multiple Choices',
  ),
   '_httpResponseCode' =&gt; 200,
   '_isRedirect' =&gt; false,
   '_renderExceptions' =&gt; false,
   'headersSentThrowsException' =&gt; true,
))
</code></pre>

<p>So the assertion finds {{200}}.</p>

<p>When I {{curl}} my action ({{curl -I <a href="http://example.org/controller/action">http://example.org/controller/action</a>}} I receive 300 as well. So it seems to work indeed. However, I'm trying to avoid HTTP calls here.</p>

<p>The quickfix is the following:</p>

<pre class="highlight"><code>
$this-&gt;getResponse()-&gt;setRawHeader('HTTP/1.1 300 Multiple Choices');
$this-&gt;getResponse()-&gt;setHttpResponseCode(300);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-24T02:40:42.000+0000</p> 
        <div class="body">
            <p>Zend_Controller_Response_Http exhibits same behavior.  Is this an issue which should be fixed in ZF1? Or is it sufficient to update the manual to note that the HTTP status code cannot be set using {{setRawHeader}} alone?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Till Klampaeckel (till) on 2012-05-12T22:10:03.000+0000</p> 
        <div class="body">
            <p>I don't know – IMHO or ideally this would be fixed so setRawHeader() parses the code and end of story. I don't like writing code specific for tests.</p>

<p>I've almost made my peace with Zend_Test since it requires an older version of PHPUnit due to PHPUnit's constant BC breaks. It's a huge inconvenience for development since you have to maintain two versions of PHPUnit and developers need to use it anyway and running tests manually is already a problem and maintaining two setups blows.</p>

<p>Maybe I find some time to update Zend_Test or write a ZendX_Test? Would that be still taken into the tree if I did?</p>

        </div>
    </div>
    </div>

