<h2>ZF-11325: &quot;HeadMeta Usage with XHTML1_RDFA doctype&quot; example uses the wrong doctype constant</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-04-25T22:09:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-02T01:56:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
            <li>FixForZF1.12</li>
            <li>View_Helper</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14947/manual.patch">manual.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Example #21 at <a href="http://framework.zend.com/manual/en/zend.view.helpers.html#zend.view.helpers.initial.headmeta">http://framework.zend.com/manual/en/…</a> uses the incorrect doctype constant.  It should be XHTML1_RDFA rather than XHTML_RDFA.  Using the example results in the following error:</p>

<pre class="highlight"><code>

Patch:
</code></pre>

<h3>Eclipse Workspace Patch 1.0</h3>

<h1>P ZendFramework-trunk</h1>

<h1>Index: documentation/manual/ja/module_specs/Zend_View-Helpers-HeadMeta.xml</h1>

<p>--- documentation/manual/ja/module_specs/Zend_View-Helpers-HeadMeta.xml (revision 23872)
+++ documentation/manual/ja/module_specs/Zend_View-Helpers-HeadMeta.xml (working copy)
@@ -230,7 +230,7 @@
         </p>

<pre><code>     &lt;programlisting language="php"&gt;&lt;![CDATA[
</code></pre>

<p>-$this-&gt;doctype(Zend_View_Helper_Doctype::XHTML_RDFA);
+$this-&gt;doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
 $this-&gt;headMeta()-&gt;setProperty('og:title', 'my article title');
 $this-&gt;headMeta()-&gt;setProperty('og:type', 'article');
 echo $this-&gt;headMeta();</p>

<h1>Index: documentation/manual/en/module_specs/Zend_View-Helpers-HeadMeta.xml</h1>

<p>--- documentation/manual/en/module_specs/Zend_View-Helpers-HeadMeta.xml (revision 23872)
+++ documentation/manual/en/module_specs/Zend_View-Helpers-HeadMeta.xml (working copy)
@@ -226,7 +226,7 @@
         </p>

<pre><code>     &lt;programlisting language="php"&gt;&lt;![CDATA[
</code></pre>

<p>-$this-&gt;doctype(Zend_View_Helper_Doctype::XHTML_RDFA);
+$this-&gt;doctype(Zend_View_Helper_Doctype::XHTML1_RDFA);
 $this-&gt;headMeta()-&gt;setProperty('og:title', 'my article title');
 $this-&gt;headMeta()-&gt;setProperty('og:type', 'article');
 echo $this-&gt;headMeta();
```</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-03-02T15:43:31.000+0000</p> 
        <div class="body">
            <p>Patch includes changes in "ja", "en" and "fr".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-06-02T01:56:38.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk (1.12.0): r24868</p>

        </div>
    </div>
    </div>

