<h2>ZF-10228: Zend_Validate_Db_NoRecordExists: use (overwritten) select() method of specified adapter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-07-26T03:28:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-26T03:47:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I use this code to specify an adapter to the Zend_Validate_Db_NoRecordExists validator:</p>

<pre class="highlight"><code>
$foo = new Application_Model_Foo();
$fooDbTable = $content-&gt;getMapper()-&gt;getDbTable();
 
$noRecordExistsValidator = new Zend_Validate_Db_NoRecordExists(
    $fooDbTable-&gt;info(Zend_Db_Table_Abstract::NAME),
    'bar',
    null,
    $fooDbTable-&gt;getAdapter()
);
</code></pre>

<p>In the adapter I overwrite the Zend_Db_Table_Abstract select() method:</p>

<pre class="highlight"><code>
class Application_Model_DbTable_Foo extends Zend_Db_Table_Abstract
{
    protected $_name = 'foo';

    public function select() {
        $select = parent::select();
        $select-&gt;where('deletionDate ?', new Zend_Db_Expr('IS NULL'));
        return $select;
    }
}
</code></pre>

<p>As far as I understand the adapter is used to specify the database connection.
But what I expected additionally was that it would use my overwritten select method.</p>

<p>By now I had to use this workaround:</p>

<pre class="highlight"><code>
$foo = new Application_Model_Foo();
$fooDbTable = $content-&gt;getMapper()-&gt;getDbTable();

$exclude = $fooDbTable-&gt;getAdapter()-&gt;quoteInto('deletionDate ?', new Zend_Db_Expr('IS NULL'));

$noRecordExistsValidator = new Zend_Validate_Db_NoRecordExists(
    $fooDbTable-&gt;info(Zend_Db_Table_Abstract::NAME),
    'bar',
    $exclude
);
</code></pre>

<p>I guess there a some good reasons why the parent::select() method is used instead.
But maybe an option passed to the validator would be nice to involve the overwritten select() method?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-07-26T03:34:22.000+0000</p> 
        <div class="body">
            <p>Closing as non-issue.</p>

<p>You are not overwriting the select method of the adapter, you are overwriting the select method of that table class. This is not the same thing, your table uses the adapter, it is not the adapter itself, and as in your example, you are not even passing the table, you are passing the adapter which the table is using.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-07-26T03:47:35.000+0000</p> 
        <div class="body">
            <p>For what its worth by the way, your 'workaround' is actually the way that the I intended the component to be used for these situations.</p>

        </div>
    </div>
    </div>

