<h2>ZF-11687: Constructor throws Zend_Date_Exception exception when $date is null and $part is Zend_Date::TIMESTAMP</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-08-19T14:51:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-19T16:36:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If try create date object like this:</p>

<p>$date = new Zend_Date(null, Zend_Date::TIMESTAMP, $locale);</p>

<p>when we catch Zend_Date_Exception: "parameter $date must be set, null is not allowed"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-08-19T16:36:49.000+0000</p> 
        <div class="body">
            <p>As the exception said: "the parameter $date must not be null".
For deeper coding support please ask within the ZF mailinglist as this is no failure within the component.</p>

        </div>
    </div>
    </div>

