<h2>ZF-10134: Enclosure Problem within unittests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-07-11T12:02:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-18T12:58:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10371">ZF-10371</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When running the unittestbed (AllTests) under the minimum required PHP release for the framework (5.2.4), it fails.</p>

<pre class="highlight"><code>
Parse error: syntax error, unexpected T_FUNCTION, expecting ')' in C:\Voxtronic\
3rdParty\Zend Framework\tests\Zend\Loader\AutoloaderTest.php on line 394
</code></pre>

<p>Reason is that the test is written for PHP 5.3 but PHP 5.2 fails to read the code. So the complete unittest fails by design.</p>

<p>It would be better to extract the related code into a own php file which is called/included when the release is &gt;= 5.3.</p>

<p>Actually it is not possible to run AllTests under the 5.2 branch.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-07-11T12:05:49.000+0000</p> 
        <div class="body">
            <p>The world cup finale is going on at this moment. I'm not sure anybody cares about ZF and/or its issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-09-18T12:58:25.000+0000</p> 
        <div class="body">
            <p>Fixed with r22969.</p>

        </div>
    </div>
    </div>

