<h2>ZF-10603: Zend_Validate_Hostname Allows Illegal Domain &quot;foo.-.com&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-27T08:07:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-18T12:51:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When validating domain names, the following was found:</p>

<p>$validator = new Zend_Validator_Hostname();
$domain='foo.-.com';
echo ($validator-&gt;isValid($domain)) ? 'pass!' : 'fail!';</p>

<p>Expected: "fail!"
Recieved: "pass!"</p>

<p>Domain name containing only "-.com" passes validation.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Oleg Lobach (bladeofsteel) on 2010-12-17T06:22:31.000+0000</p> 
        <div class="body">
            <p>I cann`t repeat this bug - i allways got 'fail!' result</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Cornutt (enygma) on 2010-12-17T06:30:10.000+0000</p> 
        <div class="body">
            <p>This bug was noticed in a slightly older version of the framework, so it's entirely possible that it's been fixed since then. I can compare the versions but as long as it works in the current version, I'm good with that.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-12-18T12:51:32.000+0000</p> 
        <div class="body">
            <p>Closing as non reproducable.
Tested on 1.11 and 2.0. Both show "fail" as expected.</p>

        </div>
    </div>
    </div>

