<h2>ZF-11491: [Website] Layout broken</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-18T23:15:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-01-18T13:29:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11539">ZF-11539</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14420/Screen+shot+2011-06-19+at+01.12.19.png">Screen shot 2011-06-19 at 01.12.19.png</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Not sure where to report this, but it looks like following link has a broken layout:
<a href="http://framework.zend.com/about/casestudies">http://framework.zend.com/about/casestudies</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Anthony Van de Gejuchte (avdg) on 2011-06-18T23:17:04.000+0000</p> 
        <div class="body">
            <p>Screenshot of broken layout</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Anthony Van de Gejuchte (avdg) on 2011-06-18T23:18:01.000+0000</p> 
        <div class="body">
            <p>Browser: google chrome 13.0.782.24</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-01-18T13:29:11.000+0000</p> 
        <div class="body">
            <p>Is no longer included in the current version of the website.</p>

        </div>
    </div>
    </div>

