<h2>ZF-11968: Allow pre/post add/update/deletion logic to be applied to Zend_Ldap_Node</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2012-01-04T17:39:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-01-23T16:02:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Claude Duvergier (cduv)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Stefan Gehrig (sgehrig)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Ldap</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{{Zend_Db_Table_Row_Abstract}} offers the ability to execute some specific logic before and after a {{Row}} creation, update and deletion via the following methods:
* {{_preInsert()}}
* {{_postInsert()}}
* {{_preUpdate()}}
* {{_postUpdate()}}
* {{_preDelete()}}
* {{_postDelete()}}</p>

<p>There is no such thing in {{Zend_Ldap_Node}} or {{Zend_Ldap_Node_Abstract}}.
When one have subclassed {{Zend_Ldap_Node}} he could want to perform special actions when a LDAP entry/node gets updated (<em>eg.</em> recompute {{displayName}} from {{givenName}} and {{surname}}, password changed notification, etc.).</p>

<p>As {{Zend_Ldap_Node::update()}} performs all useful checks before calling the relevant {{Zend_Ldap}} methods ({{add()}}, ({{update()}} or ({{delete()}}) it would be fairly easy to add this feature.</p>

<p>+Patch file proposal:+
Here is a patch (based on {{Zend\Ldap\Node.php}} r24352) that adds pre/post add/update/rename/delete methods.</p>

<pre class="highlight"><code>
435a436
&gt;                 $this-&gt;_preDelete();
436a438
&gt;                 $this-&gt;_postDelete();
442a445
&gt;             $this-&gt;_preAdd();
443a447
&gt;             $this-&gt;_postAdd();
450a455
&gt;             $this-&gt;_preRename();
451a457
&gt;             $this-&gt;_postRename();
460a467
&gt;             $this-&gt;_preUpdate();
461a469
&gt;             $this-&gt;_postUpdate();
464a473,552
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows pre-add logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _preAdd ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows post-add logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _postAdd ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows pre-update logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _preUpdate ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows post-update logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _postUpdate ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows pre-rename logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _preRename ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows post-rename logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _postRename ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows pre-delete logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _preDelete ()
&gt;     {
&gt;     }
&gt; 
&gt;     /**
&gt;     * Allows post-delete logic to be applied to node.
&gt;     * Subclasses may override this method.
&gt;     *
&gt;     * @return void
&gt;     */
&gt;     protected function _postDelete ()
&gt;     {
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Claude Duvergier (cduv) on 2012-01-04T17:41:33.000+0000</p> 
        <div class="body">
            <p>Minor typos</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stefan Gehrig (sgehrig) on 2012-01-21T14:04:07.000+0000</p> 
        <div class="body">
            <p>Fixed in ZF1 trunk and in 1.11 release branch.
Patch implemented as provided by the OP</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stefan Gehrig (sgehrig) on 2012-01-21T14:34:56.000+0000</p> 
        <div class="body">
            <p>Also fixed in ZF2 - pull request <a href="https://github.com/zendframework/zf2/pull/745">https://github.com/zendframework/zf2/pull/745</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Claude Duvergier (cduv) on 2012-01-23T08:25:51.000+0000</p> 
        <div class="body">
            <p>Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-01-23T14:44:53.000+0000</p> 
        <div class="body">
            <p>Stefan -- please back this out of the 1.11 release branch. New features should not be added within a bugfix release, only with new minor/major releases. We can release this with 1.12.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-01-23T14:46:49.000+0000</p> 
        <div class="body">
            <p>Stefan -- also, for ZF2, this functionality should be implemented using an EventManager instance instead. If you want some ideas on how that might be accomplished, ping me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-01-23T14:47:19.000+0000</p> 
        <div class="body">
            <p>Re-opening, as the functionality needs to be backed out of the 1.11 release branch, and targetted for the 1.12.0 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stefan Gehrig (sgehrig) on 2012-01-23T15:51:36.000+0000</p> 
        <div class="body">
            <p>removed fix from the 1.11 branch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-01-23T16:02:27.000+0000</p> 
        <div class="body">
            <p>Thanks, Stefan. If you need any assistance with the ZF2 version of the patch, let me know.</p>

        </div>
    </div>
    </div>

