<h2>ZF-10392: Zend Gdata Youtube video entry class don't have getAuthor() method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-08-27T17:38:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi
the method for retrieve author on a video is missing but on raw xml response is present <a href="http://code.google.com/apis/youtube/2.0/developers_guide_protocol_understanding_video_feeds">http://code.google.com/apis/youtube/…</a>.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

