<h2>ZF-10616: Wrong method names in Docs - Zend_Layout Advanced Usage &gt;  Inflection can be disabled </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-10-30T18:37:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-02T14:53:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                jw (ronny stalker)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Layout</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the docs for ZF 1.8 (and possibly in later versions too):</p>

<p><a href="http://framework.zend.com/manual/1.8/en/zend.layout.advanced.html">http://framework.zend.com/manual/1.8/…</a> (bottom of the page)</p>

<p>It says:
{quote}
Zend_Layout Advanced Usage
...
Note: Inflection can be disabled
...
Simply use the enableInflection() and disableInflection() methods. 
{quote}</p>

<p>However, if you look at the code, those methods do not exist in the {{Zend_Layout}} class.</p>

<p>Instead, there are two other methods that do modify the {{$_inflectorEnabled}} property:</p>

<p>{{enableInflector()}}
and 
{{disableInflector()}}</p>

<p>I reckon the line in the docs, at the bottom of the page should be changed from:</p>

<p>bq. Simply use the enableInflection() and disableInflection() methods.</p>

<p>to</p>

<p>bq. Simply use the enableInflector() and disableInflector() methods.</p>

<p>Definitely in version 1.8, possibly in later versions too.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-02T14:53:29.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23286, merged 1.11 release branch r23287 - thanks.</p>

        </div>
    </div>
    </div>

