<h2>ZF-131: Zend_Mail_Transport_Abstract array_walk() creates E_NOTICE</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-22T07:37:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.4 (29/Jun/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>User Asger Hallas reports:</p>

<p>"I keep getting a warning about an undefined constant self in line 191 of the mail transport abstract:</p>

<pre><code>            array_walk($content, array(self, '_formatHeader'), $header);"
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-06-22T07:40:30.000+0000</p> 
        <div class="body">
            <p>This was an E_NOTICE produced by using the self keyword in a callback context. It has been fixed in patch 690.</p>

        </div>
    </div>
    </div>

