<h2>ZF-10907: Missing message in the resources</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-01-04T11:29:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-25T14:34:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>After fixed the issue ZF-10267 with r22830 was added the "'%value%' does not appear to be a valid URI hostname" (equivalent the key Zend_Validate_Hostname::INVALID_URI = 'hostnameInvalidUri')
Only that the files resoures/languages/*/Validate.php were not updated.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-02-25T14:34:11.000+0000</p> 
        <div class="body">
            <p>Fixed with GH-108</p>

        </div>
    </div>
    </div>

