<h2>ZF-1219: CLONE -Zend_Log_Exception' with message 'No instance of log</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-04-07T08:39:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>--- File: data/bootstrap.php ---
require_once 'Zend.php';
Zend::loadClass('Zend_Log');
Zend::loadClass('Zend_Log_Adapter_File');</p>

<p>Zend_Log::registerLogger(new Zend_Log_Adapter_File('data/logs/ecmc.log'),'File');
Zend_Log::log('First logging message.');</p>

<p>--- File EOF ---</p>

<p>--- Start output ---</p>

<p><b>Fatal error</b>:  Uncaught exception 'Zend_Log_Exception' with message 'No instance of log named "LOG"' in /html/Zend/Log.php:178
Stack trace:</p>

<h1>0 html/Zend/Log.php(337): Zend_Log::_getInstance('LOG')</h1>

<h1>1 html/Zend/Log.php(405): Zend_Log::getFields('LOG')</h1>

<h1>2 data/bootstrap.php(47): Zend_Log::log('First logging m...')</h1>

<h1>3 html/index.php(23): require_once('data/bootstr...')</h1>

<h1>4 {main}</h1>

<p>thrown in <b>html/Zend/Log.php</b> on line <b>178</b><br />
-- End output ---</p>

<p>Any solution?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mikael Österberg (mikael) on 2007-04-07T08:45:43.000+0000</p> 
        <div class="body">
            <p>Cloned by mistake. pleas kill!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-09T18:24:55.000+0000</p> 
        <div class="body">
            <p>Closed per request.</p>

        </div>
    </div>
    </div>

