<h2>ZF-12347: Zend_Json_Encoder doesn't support IteratorAggregate</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2012-07-25T11:43:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-12-18T20:08:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.1 (18/Dec/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Peter van der Wal (peter@almexx.nl)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json</li>
            <li>FixForZF1.12</li>
            <li>state:patch-ready-for-review</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15178/ZF-12347.patch">ZF-12347.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Json_Encoder only traverses over objects of type Iterator, but not of type IteratorAggregate</p>

<p>--- library/Zend/Json/Encoder.php   (revision 25022)
+++ library/Zend/Json/Encoder.php   (working copy)
@@ -138,7 +138,7 @@
         if (method_exists($value, 'toJson')) {
             $props =',' . preg_replace("/^{(.*)}$/","\1",$value-&gt;toJson());
         } else {
-            if ($value instanceof Iterator) {
+            if ($value instanceof Traversable) {
                 $propCollection = $value;
             } else {
                 $propCollection = get_object_vars($value);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-07-31T12:10:22.000+0000</p> 
        <div class="body">
            <p>Attached patch implementing handling of IteratorAggregate</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-07-31T13:49:18.000+0000</p> 
        <div class="body">
            <p>ZF2 Pull Request: <a href="https://github.com/zendframework/zf2/pull/2061">https://github.com/zendframework/zf2/pull/2061</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-02T21:01:34.000+0000</p> 
        <div class="body">
            <p>Applied patch to trunk (25058) and release-1.12 (25059)</p>

        </div>
    </div>
    </div>

