<h2>ZF-12158: Escape radio labels in Zend_View_Helper_FormRadio</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-16T22:00:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-16T22:05:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A cannot disable escaping radio labels. I have found the reason, the $escape variable is not defined.</p>

<pre class="highlight"><code>
// Should the label be escaped?
if ($escape) {
    $opt_label = $this-&gt;view-&gt;escape($opt_label);
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Szurovecz János (szjani) on 2012-04-16T22:05:15.000+0000</p> 
        <div class="body">
            <p>I didn't see the extract() function call. It works. Sorry.</p>

        </div>
    </div>
    </div>

