<h2>ZF-12332: class Zend_Feed_Reader contains double semi-colons ( ;; )</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-07-11T14:41:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-07T20:29:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.1 (18/Dec/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew C. Rice (conrad10781)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Reader</li>
            <li>FixForZF1.12.1</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15156/Reader.php.patch">Reader.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/svn/framework/standard/trunk/library/Zend/Feed/Reader.php">http://framework.zend.com/svn/framework/…</a></p>

<p>if ($lastModified === null) {
    $lastModified = $cache-&gt;load($cacheId.'_lastmodified');;
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-07-12T07:15:09.000+0000</p> 
        <div class="body">
            <p>Patch added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-07T20:29:33.000+0000</p> 
        <div class="body">
            <p>Applied patch to trunk (25102) and release-1.12 (25103)</p>

        </div>
    </div>
    </div>

