<h2>ZF-11085: Test Zend/Service/Amazon present Fatal error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2011-02-17T07:36:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-17T07:46:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.4 (03/Mar/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon_Ec2</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When running tests in the Zend/Service/Amazon is throwing the following failure.</p>

<pre class="highlight"><code>
PHP Fatal error:  Cannot redeclare class TestAmamzonAbstract in /var/www/zf-trunk/tests/Zend/Service/Amazon/Ec2/AbstractTest.php on line 105
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-02-17T07:46:49.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r26702 merged to release branch 1.11 r26703.</p>

        </div>
    </div>
    </div>

