<h2>ZF-1959: Demo script produces error notices ([function.iconv]) in some environment</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-09-18T11:53:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Output:</p>

<pre class="highlight"><code>
about-pear.html... authors.html... contributing.bugs.html... contributing.documentation.html... contributing.html... contributing.newpackage.html... contributing.patches.html... contributing.wishlist.html...
Notice: iconv() [function.iconv]: Detected an illegal character in input string in ...\Zend\Search\Lucene\Analysis\Analyzer\Common\Text.php on line 56

Notice: iconv() [function.iconv]: Detected an illegal character in input string in ...\Zend\Search\Lucene\Field.php on line 188
copyright.html... core.html...
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-11-19T06:20:53.000+0000</p> 
        <div class="body">
            <p>Fixed</p>

        </div>
    </div>
    </div>

