<h2>ZF-12277: Zend_Config_Yaml does not support null value</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-11T23:05:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-12-22T12:23:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.2 (25/Feb/13)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://www.yaml.org/spec/1.2/spec.html#id2803362">http://www.yaml.org/spec/1.2/spec.html#id2803362</a>
Probably this patch fixes:</p>

<pre class="highlight"><code>
diff --git a/Config/Yaml.php b/Config/Yaml.php
index 5f5ba84..c0b1c36 100755
--- a/Config/Yaml.php
+++ b/Config/Yaml.php
@@ -320,6 +320,8 @@ class Zend_Config_Yaml extends Zend_Config
                         $value = true;
                     } elseif (preg_match('/^(f(alse)?|off|n(o)?)$/i', $value)) {
                         $value = false;
+                    } elseif (preg_match('/^null$/i', $value)) {
+                        $value = null;
                     } elseif (!self::$_ignoreConstants) {
                         // test for constants
                         $value = self::_replaceConstants($value);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-06-13T19:12:13.000+0000</p> 
        <div class="body">
            <p>This needs a unit test before it can be added to the framework.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Evgeniy Makhrov (ezh) on 2012-06-13T21:35:03.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
diff --git library/Zend/Config/Yaml.php library/Zend/Config/Yaml.php
index 5f5ba84..c0b1c36 100755
--- library/Zend/Config/Yaml.php
+++ library/Zend/Config/Yaml.php
@@ -320,6 +320,8 @@ class Zend_Config_Yaml extends Zend_Config
                         $value = true;
                     } elseif (preg_match('/^(f(alse)?|off|n(o)?)$/i', $value)) {
                         $value = false;
+                    } elseif (preg_match('/^null$/i', $value)) {
+                        $value = null;
                     } elseif (!self::$_ignoreConstants) {
                         // test for constants
                         $value = self::_replaceConstants($value);
diff --git tests/Zend/Config/YamlTest.php tests/Zend/Config/YamlTest.php
index 92140be..79c0b9b 100755
--- tests/Zend/Config/YamlTest.php
+++ tests/Zend/Config/YamlTest.php
@@ -290,6 +290,17 @@ class Zend_Config_YamlTest extends PHPUnit_Framework_TestCase
         $this-&gt;assertFalse($config-&gt;usingCapitalOff);
     }
 
+    /**
+     * @group ZF-12277
+     */
+    public function testParsesTypesAccordingToOneDotTwoSpecification()
+    {
+        $config = new Zend_Config_Yaml($this-&gt;_booleansConfig, 'production');
+        $this-&gt;assertNull($config-&gt;usingLowerCasedNull);
+        $this-&gt;assertNull($config-&gt;usingTitleCasedNull);
+        $this-&gt;assertNull($config-&gt;usingCapitalNull);
+    }
+
     public function testHonorsPhpConstants()
     {
         if (!defined('ZEND_CONFIG_YAML_ENV')) {
diff --git tests/Zend/Config/_files/booleans.yaml tests/Zend/Config/_files/booleans.yaml
index 67a9277..45ee653 100644
--- tests/Zend/Config/_files/booleans.yaml
+++ tests/Zend/Config/_files/booleans.yaml
@@ -27,3 +27,7 @@ production:
     usingTitleCasedOff: Off
     usingCapitalOff: OFF
 
+    usingLowerCasedNull: null
+    usingTitleCasedNull: Null
+    usingCapitalNull: NULL
+
</code></pre>

<pre class="highlight"><code>
$ php -dinclude_path=.:library/:/usr/lib/php/pear/ /usr/bin/phpunit tests/Zend/Config/YamlTest.php
PHPUnit 3.6.10 by Sebastian Bergmann.

.........................

Time: 0 seconds, Memory: 3.75Mb

OK (25 tests, 100 assertions)
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2012-06-13T22:46:31.000+0000</p> 
        <div class="body">
            <p>It surely does not make any sense to use regular expressions for a simple comparision:</p>

<pre class="highlight"><code>
+                    } elseif (preg_match('/^null$/i', $value)) {
</code></pre>

<p>How about:</p>

<pre class="highlight"><code>
+                    } elseif (strcasecmp($value, 'null') === 0) {
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-12-22T12:23:25.000+0000</p> 
        <div class="body">
            <p>fixed in trunk (25168) and release-1.12 (25169)</p>

        </div>
    </div>
    </div>

