<h2>ZF-11987: Zend_Service_Amazon_SimpleDb deleteAttributes API can only attribute name request</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-01-10T09:26:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-26T06:19:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Yuta Kobayashi (alu)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Enrico Zimuel (zimuel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre><code>public function deleteAttributes($domainName, $itemName, array $attributes = array())
{
    $params               = array();
    $params['Action']     = 'DeleteAttributes';
    $params['DomainName'] = $domainName;
    $params['ItemName']   = $itemName;

    $attributeIndex = 0;
    foreach ($attributes as $attribute) {
        $params['Attribute.' . $attributeIndex . '.Name'] = $attribute-&gt;getName();
        foreach ($attribute-&gt;getValues() as $value) {
            $params['Attribute.' . $attributeIndex . '.Value'] = $value;
        }
         $attributeIndex++;
    }

    $response = $this-&gt;_sendRequest($params);

    return true;
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-26T06:19:37.000+0000</p> 
        <div class="body">
            <p>Can you please provide additional information about what you are trying to do?  In what other ways can you delete an attribute except by name?</p>

        </div>
    </div>
    </div>

