<h2>ZF-12496: Zend_Validate_Identical don't launches if form element value is empty</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2013-01-03T14:57:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-01-03T16:13:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
            <li>Zend_Validate_Identical</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Assume we have two form fields: password and password_repeat. Both of it is not required. The last one has attached Zend_Validate_Identical validator (token parameter points to password form field).
In case when values (password:'12345',password_repeat:'1') passed - anything works great. But if to pass (password:'12345',password_repeat:'') form has success validation.
It looks like since password_repeat form element has no any data submitted no any validation launches at all. I am not sure if it is exactly Zend_Validation_Identical class bug against Zend_Form::isValid mechanism. Anyway, '' is not identical to '12345', thus form shouldn't be validated successfully.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2013-01-03T15:12:27.000+0000</p> 
        <div class="body">
            <p>If the field is not required, and no value is provided, validators are not checked. As such, you need to either (a) mark it as required, or (b) create a custom validator that checks if the "password" field is non-empty and only then runs the Identical validator.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Anton Zelenski (zelibobla) on 2013-01-03T16:13:29.000+0000</p> 
        <div class="body">
            <p>Yes, thank you. There are also another ways to solve the trouble.</p>

<p>I guess this is a question of logic not a bug exactly. In described case non-required form field with no value provided needed validator to be launched though.</p>

        </div>
    </div>
    </div>

