<h2>ZF-10769: lost the facility in syslog</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-12-03T01:03:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-26T11:51:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11123">ZF-11123</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If the constructor of Zend_Log_Writer_Syslog is called with $params array, the _facility property will set by setFacility method. The Problem is, that setFacility will return $this or return void in older versions, the facility property will be overwritten.</p>

<h1>Index: library/Zend/Log/Writer/Syslog.php</h1>

<p>--- library/Zend/Log/Writer/Syslog.php  (revision 23466)
+++ library/Zend/Log/Writer/Syslog.php  (working copy)
@@ -103,7 +103,7 @@</p>

<pre><code>     $runInitializeSyslog = true;
     if (isset($params['facility'])) {
</code></pre>

<p>-            $this-&gt;_facility = $this-&gt;setFacility($params['facility']);
+            $this-&gt;setFacility($params['facility']);
             $runInitializeSyslog = false;
         }</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Siad Ardroumli (said) on 2010-12-03T01:05:12.000+0000</p> 
        <div class="body">
            <h1>Index: library/Zend/Log/Writer/Syslog.php</h1>

<p>--- library/Zend/Log/Writer/Syslog.php  (revision 23466)
+++ library/Zend/Log/Writer/Syslog.php  (working copy)
@@ -103,7 +103,7 @@</p>

<pre><code>     $runInitializeSyslog = true;
     if (isset($params['facility'])) {
</code></pre>

<p>-            $this-&gt;_facility = $this-&gt;setFacility($params['facility']);
+            $this-&gt;setFacility($params['facility']);
             $runInitializeSyslog = false;
         }</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-05T08:03:51.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23467 merged to release branch 1.11 r23468 - thanks.</p>

        </div>
    </div>
    </div>

