<h2>ZF-11855: Zend_Filter_PregReplace does not have a valid MatchPattern set (Array of matches)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-27T20:00:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-27T20:36:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Glauco Lins (gateon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li></li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When PregReplace filter is applied to a Zend_Form_Element_* it presents a strange behavior during match and replace.</p>

<p>Zend_Filter_PregReplace basically resumes itself to apply a "preg_replace()" on line 171 as shown below.</p>

<pre class="literal">
preg_replace($this-&gt;_matchPattern, $this-&gt;_replacement, $value);
</pre>

<p>preg_replace allows the use of arrays for the MATCH and REPLACEMENT variables.</p>

<p>When performing the following code, an excepetion is thrown during validation.
{{Message: Zend_Filter_PregReplace does not have a valid MatchPattern set.}}</p>

<pre class="highlight"><code>
class Application_Form_Example extends Zend_Form {

  public function init()
  {
    $price = new Zend_Form_Element_Text('price');
    $price-&gt;addFilter('PregReplace', array(
             'match' =&gt; array('|,|', '|[^0-9\.]|'), 
             'replace' =&gt; array('.', '')
       ));

    $this-&gt;addElement($price);
    $this-&gt;addElement(new Zend_Form_Element_Submit('submit'));
  }
}
</code></pre>

<p>The test case itself might not be the best approach to format a 'price', but it ilustrate the problem.
For the input string {{abc123,456.789}} the expected output should be {{123456.789}}.</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

