<h2>ZF-1624: Stopword analyzer removes words from a query</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-25T13:22:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T18:32:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.1 (30/Jul/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Stopword analyzer removes words from a query. Result set for empty query is empty set. Default boolean operator is "AND". So it gives "empty query" as a result.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-06-29T17:22:04.000+0000</p> 
        <div class="body">
            <p>I made several checks and tests.</p>

<p>To get complete solution issue should be resolved with an additional "full set" query type, but it affects large enough set of classes, so it should be postponed to post-1.0 period.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-07-09T08:30:04.000+0000</p> 
        <div class="body">
            <h2>Andrew Craft reported in <a href="http://www.nabble.com/Zend_Search-Stop-words-tf4049217s16154.html#a11501469">FW-General</a>:</h2>

<p>Hi,</p>

<p>We are implementing a stop word list and we have noticed an odd bit of
behaviour when doing searches and the order of stop words in the query.</p>

<p>Currenlty these are the stop words:</p>

<pre class="highlight"><code>
$stopWords = array('the', 'and', 'a', 'to', 'of', 'in', 
                   'i', 'is', 'that', 'it', 'on', 'you', 
                   'this', 'for', 'but', 'with', 'are', 
                   'have', 'be', 'at', 'or', 'as', 'was', 
                   'so', 'if', 'out', 'not');
</code></pre>

<p>If we do a query like: "it is this" it returns no results.</p>

<p>If we do a query like: "this is it" we get results.</p>

<p>I am just wondering if this is proper behaviour for the stop words and
searching?</p>

<p>TIA,</p>

<h2>Andrew</h2>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-07-16T16:31:50.000+0000</p> 
        <div class="body">
            <p>Fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T18:32:36.000+0000</p> 
        <div class="body">
            <p>Updating Fix Version to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

