<h2>ZF-10167: Format converting php natural =&gt; Zend_date failed for escaping backslash</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-07-16T04:47:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
            <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When we use format for Zend_Date which use escaped part it is not works.
Example:</p>

<p>include_once 'Zend/Date.php';
Zend_Date::setOptions(array('format_type' =&gt; 'php'));
$now = Zend_Date::now();
echo $now-&gt;toString('\Y\e\a\r: Y');</p>

<p>Expected:</p>

<p>Year: 2010</p>

<p>Result:</p>

<p>\2010\System/Localtime\PM\Fri, 16 Jul 2010 14:42:22 +0300: 2010</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-07-29T11:06:36.000+0000</p> 
        <div class="body">
            <p>And why is this a bug?
The backslash is no proper character for date formats within Zend_Date.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-07-29T14:46:40.000+0000</p> 
        <div class="body">
            <p>I think the point is that one can't escape letters, to make sure they're displayed on as-is basis.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-07-30T00:21:12.000+0000</p> 
        <div class="body">
            <p>But a feature which is not supported is not a bug.
It's a not supported feature.</p>

<p>So "new feature" would be the expected issuetype in my opinion.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ilya Gruzinov (shagren) on 2010-07-30T02:01:26.000+0000</p> 
        <div class="body">
            <p><a href="http://framework.zend.com/manual/en/zend.date.constants.html#zend.date.constants.phpformats">http://framework.zend.com/manual/en/…</a>
There absent information about this behavior, then i expect 100% working of my old php date formats.</p>

<p>Lets add some information to documentation.</p>

        </div>
    </div>
    </div>

