<h2>ZF-12432: Trying to clone a Zend_Date object but it returns a different date (and even time)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-10-02T03:11:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-04-05T16:07:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Prueba Prueba (prueba2306)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
            <li>getdate</li>
            <li>zend_date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I been coding some functions in a project that requires operations with dates. In one of the functions i got a problem with an operation and trying to figure it out what happened i found this issue.</p>

<p>When i create a Zend_Date object and try to clone it to perform some operations on the cloned object (and keep the original object "as is") i get a different date when i invoke "getDate" function. Here is an example:</p>

<pre class="highlight"><code>
$d = new Zend_Date('2012-04-01', 'yyyy-MM-dd');
echo $d . '; ' . $d-&gt;getDate();
</code></pre>

<p>$d displays "Apr 1, 2012 12:00:00 AM" but $d-&gt;getDate() displays "Apr 2, 2012 12:00:00 AM"</p>

<p>The issue is not all the time, in the next code the date part is cloned correctly (except the time part that is supposed to be 00:00:00):</p>

<pre class="highlight"><code>
$d = new Zend_Date('2012-04-23', 'yyyy-MM-dd');
echo $d . '; ' . $d-&gt;getDate();
</code></pre>

<p>$d displays "Apr 23, 2012 12:00:00 AM" but $d-&gt;getDate() displays "Apr 23, 2012 11:00:00 PM"</p>

<p>I though that the problem was the "date format" so i tried a different approach, but it still change the cloned date:</p>

<pre class="highlight"><code>
$d = Zend_Date::now();
$d-&gt;setMonth(1)-&gt;setDay(1);
echo $d . '; ' . $d-&gt;getDate()
</code></pre>

<p>$d displays "Jan 1, 2012 9:40:15 PM" but $d-&gt;getDate() displays "Jan 2, 2012 12:00:00 AM"</p>

<p>Any ideas?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2013-04-05T16:07:15.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf1/issues/21">https://github.com/zendframework/zf1/issues/21</a></p>

        </div>
    </div>
    </div>

