<h2>ZF-11009: Highlighting does not work as expected (accented characters)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-30T04:11:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-30T04:11:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The query get's tokenized twice ( ? ).
First time in class Zend_Search_Lucene_Search_Query_Preprocessing_Term on line 299:</p>

<pre class="highlight"><code>
$tokens = Zend_Search_Lucene_Analysis_Analyzer::getDefault()-&gt;tokenize($this-&gt;_word, $this-&gt;_encoding);
</code></pre>

<p>Now everything's okay - $this-&gt;_encoding = utf-8.
But what happens next is that we have another -&gt;tokenize() method call in Zend_Search_Lucene_Document_Html on line 427 (inside foreach):</p>

<pre class="highlight"><code>
$wordsToHighlightList[] = $analyzer-&gt;tokenize($wordString);
</code></pre>

<p>but the analyzer is missing encoding (line 424):</p>

<pre class="highlight"><code>
$analyzer = Zend_Search_Lucene_Analysis_Analyzer::getDefault();
</code></pre>

<p>... and unlike during the first tokenize call I get corrupted string, and in effect - no highlight.
In the analyzer the encoding appears as an empty string. When I change the code from line 427 to:</p>

<pre class="highlight"><code>
$wordsToHighlightList[] = $analyzer-&gt;tokenize($wordString, 'utf-8');
</code></pre>

<p>.. everything works fine.</p>

<p>Code:</p>

<pre class="highlight"><code>
$query = "jaźń";

try {
    $index = Zend_Search_Lucene::open($this-&gt;getOption('indexDirectory'));
}catch(Zend_Search_Lucene_Exception $e){
    $index = Zend_Search_Lucene::create($this-&gt;getOption('indexDirectory'));
}

Zend_Search_Lucene_Search_QueryParser::setDefaultEncoding('utf-8');
Zend_Search_Lucene_Analysis_Analyzer::setDefault(
    new Zend_Search_Lucene_Analysis_Analyzer_Common_Utf8Num_CaseInsensitive()
);

$doc = new Zend_Search_Lucene_Document();
$doc-&gt;addField(Zend_Search_Lucene_Field::text('title', 'żółć gęślą jaźń ąćź','utf-8'));
$index-&gt;addDocument($doc);
$index-&gt;commit();

$query = Zend_Search_Lucene_Search_QueryParser::parse($query);

try {
    $results = $index-&gt;find($query);
    foreach ($results as $result){
        echo $query-&gt;highlightMatches($result-&gt;title, 'utf-8') . '<br />';
    }
}catch(Exception $e){}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

