<h2>ZF-10668: Can't get input data</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-11T06:22:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter_Input</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm using Zend_Filter_Input to pass data to it and get escaped value of fields.</p>

<p>I notice if you want create a email Rule using Zend_Validate_emailAdress</p>

<pre><code>    $emailValidator = new Zend_Validate_EmailAddress(array('allow'=&gt;Zend_Validate_Hostname::ALLOW_DNS,'mx'=&gt;true));
</code></pre>

<p>Like this,</p>

<p>the $input-&gt;getEscaped(); give me empty value
If i remove the mx parameter to false it's give me the mail value (eg : ffff@tesfsdfsinsf.com)</p>

<p>There is maybe a problem with return function ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-11-11T07:27:42.000+0000</p> 
        <div class="body">
            <p>Can you please supply a reproduction script that includes the bit of code that shows how you are attempting to utilize Zend_FIlter_Input?  The above information is not enough to understand the problem you are attempting to describe.</p>

<p>Thanks! Ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nicolas Renardet (xenesis) on 2010-11-11T07:42:29.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
class Extras_Filter_Input extends Zend_Filter_Input
{
    
    public function __construct($data) 
    {

        $options = array('filterNamespace' =&gt; 'Extras_Filter','validatorNamespace' =&gt; 'Extras_Validate',
        'missingMessage'=&gt;"Le champs '%field%' est obligatoire");
        
        $filters = array(
                    '*'=&gt; array(array('StringTrim'),array('StripSlashes'),array('StringToLower',array('encoding'=&gt;'UTF-8')))
        );
        
        $validators = array(
            'loginF' =&gt; array(
                'NotEmpty',
                 array('Alnum'),
                 new Zend_Validate_Regex('/^[a-zA-Z]/'),
                        'messages' =&gt; array(
                            "Login requis!",
                            "Le login ne peut comporter que des numéros et/ou des chiffres",
                            "Le login doit commencer par une lettre"
                        )
            ),
                        
            'emailF'  =&gt; array(
                'NotEmpty',
                array('EmailAddress',array('allow'=&gt;Zend_Validate_Hostname::ALLOW_DNS,'mx'=&gt;false)),
                    'messages'=&gt; array("Veuillez renseigner votre adresse Email"                        )
                    )
                ),
                '*' =&gt; array()
            );
        
        parent::__construct($filters,$validators,$data,$options);
    }

</code></pre>

<p>And in my controller i have write this :</p>

<pre class="highlight"><code>
$_POST['emailF']='wrong@@value.fr';
$input = new Extras_Filter_Input($_POST);
</code></pre>

<p>$input-&gt;getEscaped('emailF') return nothing if i let MX = true in the validator</p>

<p>I add (following the official ZF doc) a empty validator to get the value (by using array_merge on $input-&gt;getUnknown()), so at the end of $validator i wrote this :</p>

<p>'*' =&gt; array()</p>

<p>I can get the input field by this way but if i encounter error like empty for this validator message, getErrors() present me the emailF error msg (empty value) and '*' empty value too.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nicolas Renardet (xenesis) on 2010-11-11T07:45:26.000+0000</p> 
        <div class="body">
            <p>I precise :</p>

<p>$input-&gt;getEscaped('emailF') return nothing if i let MX = true in the EmailAdress validator constructor
else if i let mx to false, i get the value : 'wrong@@value.fr' that i expected</p>

        </div>
    </div>
    </div>

