<h2>ZF-12006: FlashMessenger does not update messageAdded variable when message is added</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-01-17T15:03:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-22T16:52:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dominic Luechinger (dol)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dominic Luechinger (dol)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>zf-crteam-review</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14925/FlashMessenger.php.patch">FlashMessenger.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Controller_Action_Helper_FlashMessenger has a static variable '$_messageAdded', which is never changed. In ZF2, this issue is resolved by $_messageAdded to true after adding a message.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dominic Luechinger (dol) on 2012-01-17T15:04:30.000+0000</p> 
        <div class="body">
            <p>Patch to this problem</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-26T04:36:40.000+0000</p> 
        <div class="body">
            <p>Does this solve any particular problem with the ZFv1 flash messenger?  The code has changed considerably v1-&gt;v2, so is backporting this change appropriate?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-22T16:52:32.000+0000</p> 
        <div class="body">
            <p>After reviewing the suggestion more closely, this is indeed a bug, but it's side-effect is trivial ({{setExpirationHops}} is 
 called on each {{addMessage}} call instead of just the first)</p>

<p>Fixed in trunk (1.12.0): r24813</p>

        </div>
    </div>
    </div>

