<h2>ZF-10999: Adding ZendX_JQuery_Form_Element_AutoComplete to form display group doesn't work.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-25T12:18:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-07T13:57:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                M W (mateusz.wolszczak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$city = new ZendX_JQuery_Form_Element_AutoComplete('ac');
$city-&gt;setLabel('City:')
     -&gt;setRequired(true)
     -&gt;setJQueryParam('source', '/events/city')
     -&gt;addValidator(new Zend_Validate_NotEmpty(), true)
     -&gt;addValidator(new Zend_Validate_StringLength(0,40), true)
     -&gt;addFilter(new Zend_Filter_StringTrim(),true);<br />
$this-&gt;addElement($city);</p>

<p>$this-&gt;addDisplayGroup(array('place','addres', 'city'), 'where');</p>

<p>Adding autocomplete to display group doesn't work.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-04-23T17:45:55.000+0000</p> 
        <div class="body">
            <p>You have an error in your code where
{{$this-&gt;addDisplayGroup(array('place','addres', 'city'), 'where');}}</p>

<p>should be
{{$this-&gt;addDisplayGroup(array('place','addres', 'ac'), 'where');}}</p>

        </div>
    </div>
    </div>

