<h2>ZF-12087: Zend Route Chain Assembly of empty static routes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-03-03T13:53:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-03T13:53:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller_Router</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When chaining empty static routes, the chain route assembly method adds separator, despite an empty route.</p>

<p>Reproduction code:
$this-&gt;bootstrap('FrontController');
$front = $this-&gt;getResource('FrontController');
$router = $front-&gt;getRouter();</p>

<p>$router-&gt;removeDefaultRoutes();
$emptyRoute = new Zend_Controller_Router_Route_Static('');
$testRoute = new Zend_Controller_Router_Route_Static('test');
$chainedRoute = $emptyRoute-&gt;chain($testRoute);
$router-&gt;addRoute('test',$chainedRoute);</p>

<p>$emptyRoute2 = new Zend_Controller_Router_Route_Static('');
$testRoute2 = new Zend_Controller_Router_Route_Static('test');
$chainedRoute2 = $emptyRoute2-&gt;chain($testRoute2);
$testRoute2a = $chainedRoute2-&gt;chain($emptyRoute2);
$router-&gt;addRoute('test2',$testRoute2a-&gt;chain($testRoute2));</p>

<p>echo $router-&gt;assemble(array(),'test');
echo '<br />';
echo $router-&gt;assemble(array(),'test2');
exit;</p>

<p>RESULT:
//test
//test//test</p>

<p>Proposed fix in Zend\Controller\Router\Route\Chain.php
Line 138 from:
if ($key &gt; 0) {
to:
if( $key &gt; 0 &amp;&amp; strlen($value) &gt; 0 &amp;&amp; substr($value,-1) != $this-&gt;_separators[$key] ) {</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

