<h2>ZF-1965: Easier use of printf functionality. Maybe an enhancement of the _() method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-09-19T13:25:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-08T11:41:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Edit: Woops. This looks like a duplicate of <a href="http://framework.zend.com/issues/browse/ZF-1116">http://framework.zend.com/issues/browse/ZF-1116</a> .</p>

<p>The goal is to ease the typical use where one wishes to use the printf family of functions to substitute parameters into a translated string. I can not see why this should not be an enhancement of the _() method.</p>

<p>This suggested implementation is written as a method extending the current _() method:</p>

<p>public function _(/*$messageId, args... */){</p>

<pre><code>$args = func_get_args();

if(is_array($args[0])){
    $args = $args[0];   
}

$messageId = array_shift($args);        
return vsprintf(parent::_($messageId), $args);
</code></pre>

<p>}</p>

<p>An additional feature of this implementation is that it allows calling this method with the all parameters given in an array in the first parameter. This is to allow easy calling from other places, for instance a view helper, with the content from a func_get_args().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-09-19T14:24:29.000+0000</p> 
        <div class="body">
            <p>Assigning to [~thomas] to initiate issue review.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-19T15:18:53.000+0000</p> 
        <div class="body">
            <p>We already discussed such implementation details in the past.
It was declared that Zend_Translate should not do view-code.</p>

<p>As option I created a new proposal for adding a Translation_View_Helper... it is not finished for now as I added it some days ago.
But this component will add such feature in future.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-19T15:35:10.000+0000</p> 
        <div class="body">
            <p>The detailed resons for this decission can be found in these two issues:</p>

<p><a href="http://framework.zend.com/issues/browse/ZF-1096">http://framework.zend.com/issues/browse/ZF-1096</a>
<a href="http://framework.zend.com/issues/browse/ZF-1116">http://framework.zend.com/issues/browse/ZF-1116</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jacob Oettinger (oetting) on 2007-09-19T15:41:17.000+0000</p> 
        <div class="body">
            <p>Thank you for the clarification.</p>

<p>I guess my current helper methods is the way to do it then.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Keckeis (thadafinser) on 2010-12-07T01:02:18.000+0000</p> 
        <div class="body">
            <p>I this really planned for the view?</p>

<p>It would be nice for classes to just set the complete translation message.</p>

<p>Example:
Reading an excel file from an user and an error occure in cell "B2".
The errors are collected in an array, if you wand to translate it outside (view), you have to collect all untranslated message plus all parameters!</p>

<p>Easier is to translate and parse the parameter just in the class.
So currently you have to use the printf function in the parsing class.</p>

<p>+VOTE for it+</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-12-08T11:41:39.000+0000</p> 
        <div class="body">
            <p>This issue has been closed more than 3 years ago as won't fix.
Why do you come to the idea that it is now planned to integrate view code within Zend_Translate?</p>

        </div>
    </div>
    </div>

