<h2>ZF-10036: Zend_Validate_PostCodeTest present some failures</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-06-22T19:56:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-04T04:34:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.7 (28/Jul/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13164/ZF-10036.patch">ZF-10036.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>With the correction made Zend_Validate_PostCode in the issue ZF-8612 <a href="http://framework.zend.com/code/viewrep/Zend_Framework/standard/trunk/library/Zend/Validate/PostCode.php?r1=21106&amp;r2=21485">r21485</a>.</p>

<p>Some tests present failures are:</p>

<p><em>testErrorMessageText</em></p>

<pre class="highlight"><code>
Zend_Validate_PostCodeTest::testErrorMessageText
Failed asserting that  contains "not appear to be an postal code".

/my_path/tests/Zend/Validate/PostCodeTest.php:185
</code></pre>

<p><em>testSetGetFormat</em></p>

<pre class="highlight"><code>
Zend_Validate_PostCodeTest::testSetGetFormat
Failed asserting that <a> contains "a not empty string".

/my_path/tests/Zend/Validate/PostCodeTest.php:167
</a></code></pre>

<p><em>testSettingLocalesWithoutPostalCodes</em></p>

<pre class="highlight"><code>
Zend_Validate_PostCodeTest::testSettingLocalesWithoutPostalCodes
Failed asserting that  contains "Unable to detect a format".

/my_path/tests/Zend/Validate/PostCodeTest.php:134
</code></pre>

<p>Thanks advance</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-06-22T20:01:11.000+0000</p> 
        <div class="body">
            <p>Attached the patch to be parse.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-07-04T04:34:58.000+0000</p> 
        <div class="body">
            <p>Fixed with r22523</p>

        </div>
    </div>
    </div>

