<h2>ZF-1250: Zend_Filter_StringToLower to be encoding aware if capable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-04-11T15:27:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC2 (08/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Andries Seutens (andries)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Filter_StringToLower uses the current locale. This means that in i.e. the default "C" locale, characters such as umlaut-A (Ä) will not be converted. I want to suggest to add a feature to set the encoding of the input string, if mb_string is available.</p>

<p>I have working code for this enhancement available at: <a href="http://andries.systray.be/StringToLower.phps">http://andries.systray.be/StringToLower.phps</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2007-04-11T15:33:45.000+0000</p> 
        <div class="body">
            <p>It's important to note that, if no encoding has been provided through the ::setEncoding method, mb_string is not required.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2007-06-05T15:13:37.000+0000</p> 
        <div class="body">
            <p>Resolved in <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=5125">r5125</a></p>

        </div>
    </div>
    </div>

