<h2>ZF-1910: Remove Zend_Log_Writer_Null and instead make Zend_Log configurable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-09-05T10:27:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-30T07:11:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Taylor Ettema (tettema)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>From the manual: "The Zend_Log_Writer_Null is a stub that does not write log data to anything. It is useful for disabling logging or stubbing out logging during tests."</p>

<p>I would recommend removing Zend_Log_Writer_Null, and instead making either Zend_Log_Writer or Zend_Log configurable with an "enabled" boolean.</p>

<p>For example:</p>

<pre class="highlight"><code>
[config.ini]
log.enable = true

[test.php]
$config = new Zend_Config('config.ini');
$log = new Zend_Log(new Zend_Log_Writer, $config-&gt;log-&gt;toArray());
</code></pre>

<p>Alternatively, individual writers can be configurable, or both.</p>

<p>Patching in a value for enable/disable of logging is far easier than changing the actual object type to disable logging.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-08T12:08:02.000+0000</p> 
        <div class="body">
            <p>Assigned to Bill</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-10-17T15:28:45.000+0000</p> 
        <div class="body">
            <p>Changing to 'Unassigned'</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-30T07:11:56.000+0000</p> 
        <div class="body">
            <p>This is something that should be addressed by a general refactoring to make Zend_Log more configuration-driven. Because the extent of those changes would require a new proposal, we'll track it in the proposal process.
In the meantime, this is relatively easy to implement in application-level code.</p>

        </div>
    </div>
    </div>

