<h2>ZF-11738: Zend email validator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-13T14:16:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-08T07:46:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
            <li>mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Recently I came across a wired email address air&amp;breathe-dartford@vcc-cha.com. According to mail server the email address is valid. But when I try to validate this email using Zend_Validate_EmailAddress this returning me false.</p>

<p>I though of reporting it here. I use the latest zend library and my folder structure is zend 1.6 I think.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-13T14:22:57.000+0000</p> 
        <div class="body">
            <p>Which options have been used?</p>

<p>Please note that 1.10 is not the latest release.
I would propose to try the latest 1.11 release and see if the bug persists in the latest release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Karthik Vasudevan (mithralaya) on 2011-09-13T14:28:22.000+0000</p> 
        <div class="body">
            <p>We do update our library very often so I am pretty sure that the zend library is uptodate. only the zend folder structure and the config methods are old.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Karthik Vasudevan (mithralaya) on 2011-09-13T15:15:23.000+0000</p> 
        <div class="body">
            <p>The latest SVN version for the zend validate email I got is 24305</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-13T16:28:37.000+0000</p> 
        <div class="body">
            <p>I can not verify this behaviour:</p>

<pre class="highlight"><code>
$validator = new Zend_Validate_EmailAddress();
var_dump($validator-&gt;isValid('air&amp;breathe-dartford@vcc-cha.com'));
</code></pre>

<p>The above example returns true for me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-10-08T07:46:48.000+0000</p> 
        <div class="body">
            <p>Closing as non reproduceable as there is no further response from the reporter</p>

        </div>
    </div>
    </div>

