<h2>ZF-12303: useDefaultFilters option in Zend_Markup factory has no effect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-23T23:38:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-23T23:38:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Romanenko (alextech)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pieter Kokx (kokx)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Markup</li>
            <li>state:need-feedback</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$bbcode = Zend_Markup::factory('Bbcode', 'Html', array('useDefaultFilters' =&gt; false));
has no effect.  render() method in RendererAbstract calls getDefaultFilter() which in turn calls addDefaultFilters() without checking for the option.  It does not even have a way to check for that option because __constructor() keeps the options in local scope.
I suggest adding a protected property $_options and assign to it the $options array in construct so that addDefaultFilters() method can check for its value with</p>

<p>if (null === $this-&gt;_defaultFilter &amp;&amp; (!isset($this-&gt;_options['useDefaultFilters']) || ($this-&gt;_options['useDefaultFilters'] === true)) ) {</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

