<h2>ZF-1025: Zend_XmlRpc_Request should not cast incoming XML encoding</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-08T22:16:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_XmlRpc_Client</li>
            <li>Zend_XmlRpc_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>line 256 of Zend_XmlRpc_Request reads:</p>

<pre class="highlight"><code>
$request = iconv('', $this-&gt;getEncoding(), $request);
</code></pre>

<p>For incoming XML, this can mangle the text so that it's unreadable by SimpleXMLElement. Removing the line fixes it in all instances.</p>

<p>Encoding should still be honored when <em>creating</em> XML, just not for parsing it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-03-08T22:17:36.000+0000</p> 
        <div class="body">
            <p>This is actually true for the loadXml() methods of each of the Fault, Request, and Response objects.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-03-08T22:23:46.000+0000</p> 
        <div class="body">
            <p>Resolved in 3832</p>

        </div>
    </div>
    </div>

