<h2>ZF-11732: Error message spell miss in Zend_Pdf_Page</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-11T02:18:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-15T08:17:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I found tiny spell miss in Zend_Pdf_Page.</p>

<p>Here is a diff patch to svn HEAD.</p>

<pre class="literal">
617c617
&lt;             throw new Zend_Pdf_Exception('Page is attached to other documen. Use clone $page to get it context free.');
---
&gt;             throw new Zend_Pdf_Exception('Page is attached to other document. Use clone $page to get it context free.');
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-15T08:17:49.000+0000</p> 
        <div class="body">
            <p>Fixed in ZF2 with <a href="https://github.com/zendframework/zf2/pull/415">GH-415</a></p>

        </div>
    </div>
    </div>

