<h2>ZF-1580: Zend_TranslateTest tests failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-06-17T12:29:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1531">ZF-1531</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>5) testGetAdapter(Zend_TranslateTest)
Failed asserting that  is identical to .
/home/sebastian/Work/ZendFramework/tests/Zend/TranslateTest.php:67</p>

<p>6) testTranslate(Zend_Translate_TmxTest)
it
Failed asserting that  is equal to .
/home/sebastian/Work/ZendFramework/tests/Zend/Translate/TmxTest.php:61</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-06-17T12:35:48.000+0000</p> 
        <div class="body">
            <p>Issue is related to ZF-1531... in work and not finished for now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-06-17T15:08:03.000+0000</p> 
        <div class="body">
            <p>Related issue ZF-1531 fixed with SVN-5370.
Fixes also this issue.</p>

        </div>
    </div>
    </div>

