<h2>ZF-12397: Zend_View_Helper_Json handles $keepLayouts argument as array incorrectly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-08-31T13:36:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-07T19:58:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.1 (18/Dec/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
            <li>FixForZF1.12.1</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-12410">ZF-12410</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15197/Json.php.patch">Json.php.patch</a></li>
            <li><a href="/issues/secure/attachment/15198/JsonTest.php.patch">JsonTest.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If $keepLayouts is passed as an array, Zend_View_Helper_Json::json does not properly use the encodeData key from the array.  Additionally, it causes a "Warning: [2] array_key_exists() expects parameter 2 to be array, boolean given".  It should check $options for the array key instead of $keepLayouts.</p>

<pre class="highlight"><code>
public function json($data, $keepLayouts = false, $encodeData = true)
{
    $options = array();
    if (is_array($keepLayouts))
    {
        $options     = $keepLayouts;
//      $keepLayouts = (array_key_exists('keepLayouts', $keepLayouts))
//                      ? $keepLayouts['keepLayouts']
        $keepLayouts = (array_key_exists('keepLayouts', $options))
                        ? $options['keepLayouts']
                        : false;
        unset($options['keepLayouts']);
//      $encodeData  = (array_key_exists('encodeData', $keepLayouts))
//                      ? $keepLayouts['encodeData']
        $encodeData  = (array_key_exists('encodeData', $options))
                        ? $options['encodeData']
                        : $encodeData;
        unset($options['encodeData']);
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-08-31T15:17:10.000+0000</p> 
        <div class="body">
            <p>Patch and unit test added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-07T19:58:53.000+0000</p> 
        <div class="body">
            <p>Applied patch to trunk (25090) and release-1.12 (25091)</p>

        </div>
    </div>
    </div>

