<h2>ZF-10808: calling prepare on a mysqli object fails on internal prepare method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-10T07:09:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-01T19:46:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On line 70 of Zend_Db_Statement_Mysqli, there is a call made to $this-&gt;_stmt = $mysqli-&gt;prepare($sql); This call failed every time a sql query was being made because I don't believe you should be preparing the sql query from the mysqli object, and thus the statement object was never returned. this issue was a primary blocker from us using Zend_Db again.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T11:19:35.000+0000</p> 
        <div class="body">
            <p>Could you please provide an example illustrating the problem you are encountering and any resulting error message(s)?  Thanks!</p>

        </div>
    </div>
    </div>

