<h2>ZF-1229: Examples of multiple terms in WHERE clauses</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-04-09T17:04:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-15T17:09:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1204">ZF-1204</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>John Baldock writes:</p>

<p>All the examples I have seen only have one Where condition. What I could have used is either a section of the manual describing the Where clause or some of the examples having multiple conditions, OR as well as AND, to give people a nudge in the right direction. For example:</p>

<pre class="highlight"><code>
// multiple conditions seperated by OR
$nameOne = $table-&gt;getAdapter()-&gt;quote($nameOne);
$nameTwo = $table-&gt;getAdapter()-&gt;quote($nameTwo);
$where = "name = $nameOne OR name = $nameTwo"; 
$row = $users-&gt;fetchRow($where);

// multiple conditions seperated by AND
$where[] = $table-&gt;getAdapter()-&gt;quoteInto('name = ?', $nameOne); 
$where[] = $table-&gt;getAdapter()-&gt;quoteInto('name = ?', $nameTwo); 
$row = $users-&gt;fetchRow($where);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-10T16:29:24.000+0000</p> 
        <div class="body">
            <p>Assigning to Darby.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-17T18:47:52.000+0000</p> 
        <div class="body">
            <p>Linking to ZF-1204</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-20T16:21:43.000+0000</p> 
        <div class="body">
            <p>Resolved with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4564">SVN r4564</a>.</p>

        </div>
    </div>
    </div>

