<h2>ZF-12549: Zend_Service_Rackspace_Files::copyObject sets Content-Type to 'application/x-www-form-urlencoded'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2013-03-25T12:35:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-04-05T16:06:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15424/ZF-12549-test.patch">ZF-12549-test.patch</a></li>
            <li><a href="/issues/secure/attachment/15421/ZF-12549.patch">ZF-12549.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you try to copy an object from one cloud files location to another it sets the Content-Type header to 'application/x-www-form-urlencoded'. It should preserve the content type.</p>

<p>This looks like's it's being caused by Zend_Http_Client being overzealous with its encType. The workaround in the attached patch sets it to an empty string for PUT requests that have no body, which prevents the incorrect header being added (Z_H_C checks encType === null before adding the header).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matt Kynx (kynx) on 2013-03-25T16:51:44.000+0000</p> 
        <div class="body">
            <p>Added check for content type to existing copyObject test</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2013-04-05T16:06:54.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf1/issues/67">https://github.com/zendframework/zf1/issues/67</a></p>

        </div>
    </div>
    </div>

