<h2>ZF-11803: Wrong view base path in ViewRenderer</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-07T08:44:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T17:28:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi, 
I'm trying to use Twig as view renderer in Zend with modular convention. I created a class extends Zend_Application_Resource_View and it loads Twig in getView function.</p>

<p>Problem ;
In Zend_Controller_Action_Helper_ViewRenderer, _viewBasePathSpec property points to ':moduleDir/views' folder. But in standard modular convention, view scripts placed in ':moduleDir/views/scripts' folder. (CLI tool creates this folder for placing views.)</p>

<p>--</p>

<p>PS : I solved this problem with overwriting default value ;</p>

<p>Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer')-&gt;setView($view)-&gt;setViewSuffix('suffix')-&gt;setViewBasePathSpec(':moduleDir/views/scripts');</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-29T17:28:21.000+0000</p> 
        <div class="body">
            <p>This cannot be fixed in ZFv1 without introducing possible backwards-compatibility issues.  Those implementing alternative view renderers with ZFv1 will have to be responsible for setting up the configuration accordingly, as the OP's edit demonstrates</p>

        </div>
    </div>
    </div>

