<h2>ZF-12341: Add support for RDFa 1.1 doctype</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2012-07-19T13:40:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-07T20:27:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.1 (18/Dec/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
            <li>After1.12.0</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15161/Doctype.php.patch">Doctype.php.patch</a></li>
            <li><a href="/issues/secure/attachment/15162/DoctypeTest.php.patch">DoctypeTest.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{quote}The doctype for RDFa 1.0 is currently supported in the Doctype view helper (Zend_View_Helper_Doctype).</p>

<p>Since 7. June 2012 RDFa 1.1 is now a formal W3C recommendation: <a href="http://www.w3.org/TR/xhtml-rdfa/%7Bquote">http://www.w3.org/TR/xhtml-rdfa/{quote</a>}</p>

<p>See also: <a href="http://framework.zend.com/issues/browse/ZF2-401">ZF2-401</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-07-19T13:43:18.000+0000</p> 
        <div class="body">
            <p>Patch and unit tests added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-07T20:27:41.000+0000</p> 
        <div class="body">
            <p>Applied patch to trunk (25100) and release-1.12 (25101)</p>

        </div>
    </div>
    </div>

