<h2>ZF-11168: Headlink stylesheet requires media and type attr, but these can be omitted in HTML5</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-03-13T03:59:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-13T04:15:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                alexvandam (alex505)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have my doctype set as <em>Zend_View_Helper_Doctype::XHTML5.</em></p>

<p>When i add a stylesheet, I want to be able to specify the media types inside this stylesheet using the at-media rule (<a href="http://www.w3.org/TR/CSS2/media.html#at-media-rule">http://www.w3.org/TR/CSS2/media.html#at-media-rule</a>) to limit the use of multiple stylesheets. But <em>Zend_View_Helper_HeadLink</em> still adds the media attribute to the link tag, even if i set it to null or false.</p>

<p>The same goes for the type="text/css" attribute, which can be omitted in HTML5.</p>

<p>I think there should be a check to see if the doctype is HTML5, and that's true, the type attribute should not be required anymore. And I also think that the media attribute shouldn't be required either, but I think that it shouldn't be required for all doctypes and not just HTML5.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

