<h2>ZF-1703: Zend_Http_Response exists with FATAL Error when PHP has no zlib support</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-07-11T09:39:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-19T11:14:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mathias Leppich (muhqu)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Response</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1887">ZF-1887</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When Zend_Http_Response gets loaded with a "Content-encoding = gzip" the script just exits with a...</p>

<pre class="highlight"><code>
Fatal error: Call to undefined function gzinflate()
</code></pre>

<p>I suggest to check for the function and then throw an Exception like...</p>

<pre class="highlight"><code>
public static function decodeGzip($body)
{
    if (!function_exists('gzinflate'))
        throw new Zend_Http_Exception("Error decoding body - zlib required for content-encoding gzip");
    return gzinflate(substr($body, 10));
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-07-16T06:52:16.000+0000</p> 
        <div class="body">
            <p>Should be fixed in r. 5712. If you are using SVN HEAD, please update and try.
Also added a Accept-Encoding header that will automatically request unencoded response from the server if zlib is not available.</p>

        </div>
    </div>
    </div>

