<h2>ZF-1597: Zend_Gdata_Extension_Who does not properly recognize entryLink elements when importing from XML</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-19T18:12:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><em>Summary:</em>
When populating an instance of Zend_Gdata_Extension_Who from XML, entryLink elements are not properly converted to instances of Zend_Gdata_Extension_EntryLink.</p>

<p><em>Steps to Reproduce:</em>
1. Create a new XML document containing a gd:who element and a nested gd:entryLink element.
2. Instantiate a new Zend_Gdata_Extension_Who and populate it with the XML document created in Step 1.</p>

<p><em>Expected Results:</em>
The gd:entryLink should be converted to an instance of Zend_Gdata_Extension_EntryLink and Zend_Gdata_Extension_Who's entryLink property set appropriately.</p>

<p><em>Actual Results:</em>
The gd:entryLink is created as a generic Zend_Gdata_Extension and added as an extension element to the Zend_Gdata_Extension_Who instance.</p>

<p><em>Regression:</em>
Introduced in r4993, affects 1.0.0 RC1 and RC2.</p>

<p><em>Notes:</em>
A test for this will be included for this in ZF-1593.</p>

<p>Fixed in my build, patch sent to rboyd for review.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-20T13:21:32.000+0000</p> 
        <div class="body">
            <p>Assigning to Ryan.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-20T17:40:50.000+0000</p> 
        <div class="body">
            <p>Resolved in svn rev 5394</p>

        </div>
    </div>
    </div>

