<h2>ZF-1807: Add method Zend_Translate_Adapter::_() as an alias for Zend_Translate_Adapter::translate()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-08-03T08:13:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-11-15T14:49:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.3 (30/Nov/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Please add method Zend_Translate_Adapter::_() as an alias for Zend_Translate_Adapter::translate().
We need it, if we write own adapter and want to use it directly, but using exact the same interface as of Zend_Translate.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-08-09T15:58:36.000+0000</p> 
        <div class="body">
            <p>Integrated with SVN 6050.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-13T15:42:21.000+0000</p> 
        <div class="body">
            <p>Branch integration</p>

        </div>
    </div>
    </div>

