<h2>ZF-128: Developer wiki bugs on click on open issues histo bar (TRAC#152)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-21T22:42:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On the page <a href="http://framework.zend.com/wiki/display/ZFDEV/Home">http://framework.zend.com/wiki/display/ZFDEV/Home</a>, tab "Project Summary", click anywhere on the green histogram bar. This will yield a Java error.</p>

<p>It also displays a bunch of information that could be useful to less innocent people.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-09-25T19:44:21.000+0000</p> 
        <div class="body">
            <p>Reassigning from Jayson to Bill Karwin, pending further triage.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-09T16:10:11.000+0000</p> 
        <div class="body">
            <p>This is a bug in JIRA, reported at <a href="http://jira.atlassian.com/browse/JRA-10499">http://jira.atlassian.com/browse/JRA-10499</a></p>

<p>It is reportedly fixed in JIRA 3.6.3.  We are currently running JIRA 3.6.2.  When we upgrade next, this issue should be resolved for us.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-15T12:17:10.000+0000</p> 
        <div class="body">
            <p>This is not an issue with Zend Framework.</p>

        </div>
    </div>
    </div>

