<h2>ZF-11599: Adition of method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-07-23T14:26:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-30T02:53:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.10 (04/Aug/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I believe that should be added Zend_Http_Client_Adapter_Test::getConfig().
What would facilitate in tests with assertions.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-07-23T15:27:05.000+0000</p> 
        <div class="body">
            <p>Commit in trunk r24262.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-07-30T02:53:56.000+0000</p> 
        <div class="body">
            <p>Fix r24309</p>

        </div>
    </div>
    </div>

