<h2>ZF-1599: Output frontend with Sqlite backend bombs on setting automaticCleaningFactor to true</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-19T19:49:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T00:09:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Setting automaticCleaningFactor front-end option to true is bombing for Output frontend with Sqlite backend and only works on setting it to false:</p>

<p>Error: 2 
Text : sqlite_query() [function.sqlite-query ]: database schema has changed 
File  : \Library\Zend\Cache\Backend\Sqlite.php
Line : 355</p>

<p>Here is a backtrace with class/method names and line numbers:</p>

<p>sqlite_query("Resource id #118", "DELETE FROM tag WHERE id IN (SELECT id FROM cache WHERE expire&gt;0 AND expire&lt;=1182199839)")</p>

<p>Zend_Cache_Backend_Sqlite  _clean("old", Array[0])  227</p>

<p>Zend_Cache_Backend_Sqlite  clean("old", Array[0])  382</p>

<p>Zend_Cache_Core  clean("old")  320</p>

<p>Zend_Cache_Core  save( ... )    80</p>

<p>Zend_Cache_Frontend_Output  end()  1258</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-20T13:21:51.000+0000</p> 
        <div class="body">
            <p>Assigning to Fabien.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2007-06-23T10:48:47.000+0000</p> 
        <div class="body">
            <p>can you try to drop your database file and retry ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-06-24T00:22:12.000+0000</p> 
        <div class="body">
            <p>I've tried dropping the db file and noticed it recreating the file but it gives the same error for the first page load (cache-miss). Subsequent page-loads (cache-hit) are fine without errors. Here is my setup:</p>

<pre class="highlight"><code>
$frontendOptions = array
(
   'caching' =&gt; true,
   'lifeTime' =&gt; 7200,
   'automaticCleaningFactor' =&gt; 1
);


$backendOptions = array
(
   'cacheDBCompletePath' =&gt; '/temp/Cache.db',
   'automaticVacuumFactor'=&gt; 1
);


$cache = Zend_Cache::factory( 'Output', 'Sqlite', $frontendOptions, $backendOptions );
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2007-06-28T14:50:12.000+0000</p> 
        <div class="body">
            <p>works well on my linux box :(</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-07-02T01:45:48.000+0000</p> 
        <div class="body">
            <p>I've traced more info as for this error:</p>

<pre class="highlight"><code>
Text : sqlite_query() [function.sqlite-query]: database schema has changed 
File : \Library\Zend\Cache\Backend\Sqlite.php 
Line : 127 

[sql] =&gt; SELECT content FROM cache WHERE id='desc' AND (expire=0 OR expire&gt;1183357534)




Error: 2 
Text : sqlite_fetch_array() expects parameter 1 to be resource, {color:red}*strong*boolean*strong*{color} given 
File : \Library\Zend\Cache\Backend\Sqlite.php 
Line : 128 
</code></pre>

<p>The front-end used is OUTPUT.</p>

<p>HTH</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-07-02T01:48:16.000+0000</p> 
        <div class="body">
            <p>Oops! Wiki markup got messed up. Here it goes again:</p>

<p>I've traced more info as for this error:</p>

<pre class="highlight"><code>
Text : sqlite_query() [function.sqlite-query]: database schema has changed 
File : \Library\Zend\Cache\Backend\Sqlite.php 
Line : 127 

[sql] =&gt; SELECT content FROM cache WHERE id='desc' AND (expire=0 OR expire&gt;1183357534)

Error: 2 
Text : sqlite_fetch_array() expects parameter 1 to be resource, BOOLEAN given 
File : \Library\Zend\Cache\Backend\Sqlite.php 
Line : 128
</code></pre>

<p>The front-end used is OUTPUT.</p>

<p>HTH</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2007-07-02T15:51:27.000+0000</p> 
        <div class="body">
            <p>can you try to set  'automaticVacuumFactor'=&gt; 0, then drop your cache db, then retry your test ?</p>

<p>thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-07-21T04:11:43.000+0000</p> 
        <div class="body">
            <p>I set automatic_vacuum_factor to 0, dropped the database and ran the test. It gave me an error:</p>

<p>No such table: tag</p>

<p>Then I refreshed the page - it went well. Then I cleared the cache and reset the automatic_vacuum_factor to 1 and re-ran the test. But the problem remains the same :(</p>

<p>Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-07-21T04:14:47.000+0000</p> 
        <div class="body">
            <p>You said it works well on your *nix box. Have you tried Output frontend? I'm getting the problem on first page-load when the cache is empty. Once the content is cached, it's fine on subsequent page-loads.</p>

<p>TIA</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-08-15T23:27:39.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>I've re-tested it and found the exact same issue as reported before in Zend_Cache_Backend_Sqlite::_clean():</p>

<pre class="highlight"><code>
        if ($mode==Zend_Cache::CLEANING_MODE_OLD) {
            $mktime = time();
            $res1 = @sqlite_query($this-&gt;_db, "DELETE FROM tag WHERE id IN (SELECT id FROM cache WHERE expire&gt;0 AND expire&lt;=$mktime)");
</code></pre>

<p>While debugging, the script exits on the last line above where it tries to delete from tag table. Running the page in the browser gives the following error:</p>

<p>sqlite_query() [function.sqlite-query]: database schema has changed 
File: Library\Zend\Cache\Backend\Sqlite.php 
Line: 317</p>

<pre><code>    $result = @sqlite_query($this-&gt;_db, "SELECT num FROM version");
</code></pre>

<p>Executing  the above SQL statements on the Sqlite file run well without a problem. However, there are no errors on setting "automatic_cleaning_factor" to 0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2007-10-23T14:53:29.000+0000</p> 
        <div class="body">
            <p>it seems that you have a sort of disconnection (parameter 1 is not a resource), I just commited in SVN something which may help (i don't know because I can't reproduce your problem)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2007-11-07T00:47:28.000+0000</p> 
        <div class="body">
            <p>After applying the SVN upate, I've noticed that I'm getting these errors randomly/rarely even on pages that are NOT output-cached!:</p>

<p>"sqlite_query() [<a href="function.sqlite-query">function.sqlite-query</a>]: database schema has changed", "\Library\Zend\Cache\Backend\Sqlite.php", "364", Array[3]</p>

<p>sqlite_query("Resource id #114", "DELETE FROM tag WHERE id IN (SELECT id FROM cache WHERE expire&gt;0 AND expire&lt;=1193343468)") 364  \Library\Zend\Cache\Backend\Sqlite.php</p>

<p>Zend_Cache_Backend_Sqlite  _clean("old", Array[0])  217 \Library\Zend\Cache\Backend\Sqlite.php</p>

<p>Zend_Cache_Backend_Sqlite  clean("old", Array[0])   337  \Library\Zend\Cache\Core.php</p>

<p>Zend_Cache_Core  clean("old")                       272  \Library\Zend\Cache\Core.php</p>

<p>Zend_Cache-&gt;save(...)</p>

<p>I work on XP, PHP 5.2.3, MySQL 5, Apache 2.0.5.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-01-17T18:09:35.000+0000</p> 
        <div class="body">
            <p>This thread seems to say that it's a vacuum problem :</p>

<p><a href="http://www.mail-archive.com/sqlite-users@sqlite.org/msg04887.html">http://mail-archive.com/sqlite-users@sqlite.org/…</a></p>

<p>Can you try to set (one time more) 'automaticVacuumFactor'=&gt; 0 and try to reproduce the problem ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-01-22T14:39:25.000+0000</p> 
        <div class="body">
            <p>probably fixed in SVN</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2008-01-23T00:09:06.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>I'm currently traveling and shall try out the above and let you know by the end of this week when I get back to my win-box.</p>

<p>Regards,</p>

        </div>
    </div>
    </div>

