<h2>ZF-1150: Index reopening fails if it's used within one script execution.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-28T04:24:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.2 (06/Apr/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The problem is originally reported by Craig Duncan in <a href="http://www.nabble.com/Zend_Search_Lucene-dies-on-update-tf3475374s16154.html">FW-General</a>.</p>

<p>unset($index) doesn't really close the index and clean up resources.</p>

<p>script terminates at the moment of adding document with reopened index .</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-03-28T04:32:37.000+0000</p> 
        <div class="body">
            <p>$index object doesn't really destroyed because it's referenced from some dependent objects (ex. document writer).</p>

<p>So changes are not automatically committed and not cleaned up. It's done only at the end of script execution.
Index reopening may case deadlocks and script terminates because of this.</p>

<p>The problem may be solved with an additional "access controller" class (see details in FW-General)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-03-30T14:06:57.000+0000</p> 
        <div class="body">
            <p>Done.</p>

        </div>
    </div>
    </div>

