<h2>ZF-11030: Content-type set per default with PUT to '' has for consequence that Zend_Rest_Client PUT can't work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2011-02-03T11:47:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-21T08:06:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.10 (04/Aug/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jawad (jawadstouli)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bart McLeod (mcleod@spaceweb.nl)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
            <li>Zend_Rest_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10162">ZF-10162</a></li>
            <li><a href="/issues/browse/ZF-11669">ZF-11669</a></li>
            <li><a href="/issues/browse/ZF-10664">ZF-10664</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14523/Client-apply-to-test-Zend_Http_Client-directory.patch">Client-apply-to-test-Zend_Http_Client-directory.patch</a></li>
            <li><a href="/issues/secure/attachment/14524/Client.php.patch">Client.php.patch</a></li>
            <li><a href="/issues/secure/attachment/14525/Curl.php.patch">Curl.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am not able to successfully execute a PUT HTTP request via Zend_Rest_Client. I get the following error: Cannot handle content type '' automatically. Please use Zend_Http_Client::setRawData to send this kind of content.</p>

<p>The encoding type is in fact not set in such a request (while it is automatically set for POST request in Zend_HTTP_Client).</p>

<p>I made a small fix that I think is sufficient (line 358):
if ($method == self::POST &amp;&amp; $this-&gt;enctype === null) {</p>

<p>should be</p>

<p>if (($method == self::POST || $method == self::PUT) &amp;&amp; $this-&gt;enctype === null) {</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Grégory Eve (igreg) on 2011-03-17T11:23:08.000+0000</p> 
        <div class="body">
            <p>It's an issue between Zend_HTTP_Client and Zend_Rest_Client.</p>

<p>This issue has for consequence that the default use of Zend_Rest_Client PUT can't work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-11T10:38:39.000+0000</p> 
        <div class="body">
            <p>I experience the same issue. Thanks for proposing a fix. I will create unit tests and fix this as soon as possible.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-19T21:44:49.000+0000</p> 
        <div class="body">
            <p>I added patches that add extensive testing.
Allthough the proposed fix was good, I added support for DELETE as well.</p>

<p>PUT and DELETE were severely undertested, so the biggest patch is for the tests.</p>

<p>To support DELETE I also had to patch Zend_Http_Client_Adapter_Curl, that did not send the request body, hence no data.</p>

<p>I do not know if other adapters also fail to send DELETE data and I do not know if the curl adapter is the right one to fix if I want Zend_Rest_Client to send data with DELETE requests. However, I do know this fix is sufficient for the issue at hand.</p>

<p>I also know there is a failing test in the currently available tests for the curl client. That was there before I started and I communicated with Matthew WOP to make sure he is aware of this.</p>

<p>If no one complains about my patches for about a week, I will commit them and merge them back into the 1.11 branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-19T21:47:08.000+0000</p> 
        <div class="body">
            <p>set to patch, because now you can download two patches. The Curl patch will give you support for DELETE requests with data. Please note that in order for these to work with Zend_Rest_Client, we need to fix Zend_Rest_Client. It does not set the data on a DELETE request, but that is another issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-19T21:51:39.000+0000</p> 
        <div class="body">
            <p>Please not that the patch for the tests will have to be applied to tests/Zend/Http/Client directory. It contains a few new files and a patch for CommonHttpTests.php that is used by CurlTest.php, that itself did not need patching.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sergey Romanov (serhioromano) on 2011-07-21T11:00:01.000+0000</p> 
        <div class="body">
            <p>When this will be included in to ZF? In what version?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-21T12:08:17.000+0000</p> 
        <div class="body">
            <p>I will leave the issue open for review for about a week after submitting a patch. If within a week no-one has complained about the fix, I will commit it to trunk, and this case, merge it back into the 1.11 branch. So basically around july 26 2011 you should expect this to be in trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-25T19:05:20.000+0000</p> 
        <div class="body">
            <p>Patches and tests look good. The only change I'd make is in the Client patch -- change the "or" comparison operators to "||".</p>

<p>Feel free to apply at will.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-26T20:00:19.000+0000</p> 
        <div class="body">
            <p>Committed to trunk with the "or" to "||" change. Client.php had to be merged with changes by Roman.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2011-07-27T21:13:50.000+0000</p> 
        <div class="body">
            <p>Today I patched the 1.11 branch with these changes, verified that the new tests pass and that no additional tests fail.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by nike shox (nike shox) on 2012-11-21T08:06:52.000+0000</p> 
        <div class="body">
            <p>Linjene between basketball, skate <a href="">http://www.nikeshoxsko.biz</a>&gt;nike shox sko Og mote-orientert fottøy is uskarp with adidas Originals 'Hardland. Ankommer Originals forhandlere this month <a href="">http://www.nikeshoxsko.biz</a>&gt;shox sko is a brand new <a href="">http://www.nikeshoxsko.biz</a>&gt;nike shox colorway of the fasjonable Høy-top, kledd jeg premie falt hvitt skinn with sølv D-ring Blonder øjer and Signatur overdrevet Tunge.verdrevet Tunge.</p>

        </div>
    </div>
    </div>

