<h2>ZF-11802: Zend_Dojo_View_Helper_Dijitt Improvement</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-10-07T00:00:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-28T18:05:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently Zend_Dojo_View_Helper_Dijit::setDijitParam() does not allow Javascript objects to be passed as parameters. I propose we add support for Zend_Json_Expr to be passed. Many parameters require objects to be passed to have the dijit work properly.</p>

<p>A direct result of this change will require the Elements to support more than strings being passed to them.</p>

<p>Line 241 of Zend_Dojo_View_Helper_Dijit only allows scalar values to be passed.</p>

<pre class="highlight"><code>

                    foreach ($params[$param] as $key =&gt; $value) {
                        if (!is_scalar($value)) {
                            continue;
                        }
                        $values[$key] = $value;
                    }
</code></pre>

<p>to</p>

<pre class="highlight"><code>
                    foreach ($params[$param] as $key =&gt; $value) {
                        if (!is_scalar($value)) {
                            if(!($value instanceof Zend_Json_Expr))
                                continue;
                            
                        }
                        $values[$key] = $value;
                    }

</code></pre>

<p>One we allow Zend_Json_Expr we need to have Zend_Json look for the expressions on line 252:</p>

<pre class="highlight"><code>

                $values = Zend_Json::encode($values);
</code></pre>

<p>to</p>

<pre class="highlight"><code>
                 $values = Zend_Json::encode($values, false, array('enableJsonExprFinder' =&gt; true) );
</code></pre>

<p>Issue came up because I was trying to load additional plugins with Zend_Dojo_Form_Element_Editor. The plugin required more then a string to configure. Additional changes needed were in Zend_Dojo_Form_Element_Editor::addPlugin(). Has to remove the $plugin being cast to a string.</p>

<pre class="highlight"><code>
  public function addPlugin($plugin)
    {
        $plugin = (string) $plugin;
        $plugins = $this-&gt;getPlugins();
        if (in_array($plugin, $plugins) &amp;&amp; $plugin !== '|') {
            return $this;
        }

        $plugins[] = (string) $plugin;
        $this-&gt;setDijitParam('plugins', $plugins);
        return $this;
    }

</code></pre>

<p>to</p>

<pre class="highlight"><code>
  public function addPlugin($plugin)
    {
        $plugin = $plugin;
        $plugins = $this-&gt;getPlugins();
        if (in_array($plugin, $plugins) &amp;&amp; $plugin !== '|') {
            return $this;
        }

        $plugins[] = $plugin;
        $this-&gt;setDijitParam('plugins', $plugins);
        return $this;
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-28T18:05:47.000+0000</p> 
        <div class="body">
            <p>You will need to sign and submit a CLA before we can review and possibly implement your proposed solution.
See here: <a href="http://framework.zend.com/wiki/display/ZFPROP/Contributor+License+Agreement">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
    </div>

