<h2>ZF-10791: $form-&gt;setName('nameAttr'); has no effect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-08T01:49:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-26T08:12:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.8 (07/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marcus Häußler (testvogel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4342">ZF-4342</a></li>
            <li><a href="/issues/browse/ZF-6200">ZF-6200</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13540/ZF-10791.patch">ZF-10791.patch</a></li>
            <li><a href="/issues/secure/attachment/13542/ZF-10791.rev2-formatted.patch">ZF-10791.rev2-formatted.patch</a></li>
            <li><a href="/issues/secure/attachment/13546/ZF-10791.rev3.patch">ZF-10791.rev3.patch</a></li>
            <li><a href="/issues/secure/attachment/13550/ZF-10791.rev4.patch">ZF-10791.rev4.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This ticket is related to <a href="http://framework.zend.com/issues/browse/ZF-4342">http://framework.zend.com/issues/browse/ZF-4342</a> but I did not find a way to reopen.
The ticket was closed with the hint that name is not a valid form-element attribute.</p>

<p>I could not find any evidence for this statement.</p>

<p>W3C says for HTML401 and also 5 that name IS a valid attribute for the form-element:
HTML 401: <a href="http://www.w3.org/TR/html401/interact/forms.html#h-17.3">http://w3.org/TR/html401/…</a>
HTML 5  : <a href="http://www.w3.org/TR/2010/WD-html5-20101019/forms.html#the-form-element">http://w3.org/TR/2010/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2010-12-08T03:37:35.000+0000</p> 
        <div class="body">
            <p>??I could not find any evidence for this statement.??</p>

<p><a href="">www.w3.org/TR/xhtml1/#h-4.10</a>" rel="nofollow"&gt;XHTML 1.0 - 4.10. The elements with 'id' and 'name' attributes</p>

<p>I think the priority "major" is greatly exaggerated!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marcus Häußler (testvogel) on 2010-12-08T04:22:01.000+0000</p> 
        <div class="body">
            <p>Thank you for the link, couldn't find this by myself :(
I copied the priority from the source-ticket, so you are right.</p>

<p>I thought HTML5 will be the future, not XHTML, any opinions?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ulf Kirsten (ulfkirsten6) on 2010-12-08T05:09:06.000+0000</p> 
        <div class="body">
            <p>I strongly advise that HTML5 takes priority over XHTML. The simple reason: W3C declared XHTML as dead (<a href="http://www.w3.org/2009/06/xhtml-faq.html">http://www.w3.org/2009/06/xhtml-faq.html</a>). So the name atribute should be rendered by the ViewHelper of the form.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-12-08T10:52:17.000+0000</p> 
        <div class="body">
            <p>It is possible to detect the DTD in use via the doctype view helper.  The view helpers are already doing this (i.e. deciding whether to include a closing / in tags), so look there for an example.  This should be fixable in a way that maintains compatibility with both HTML4, XHTML and HTML5</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2010-12-09T02:41:19.000+0000</p> 
        <div class="body">
            <p>100 points for <em>Marc</em>! :-)</p>

<p>Example (not tested!):</p>

<pre class="highlight"><code>
/**
 * Render HTML form
 *
 * @param  string $name Form name
 * @param  null|array $attribs HTML form attributes
 * @param  false|string $content Form content
 * @return string
 */
public function form($name, $attribs = null, $content = false)
{
    $info = $this-&gt;_getInfo($name, $content, $attribs);
    extract($info);

    // Set the id attribute if it exists
    if (!empty($id)) {
        $id = ' id="' . $this-&gt;view-&gt;escape($id) . '"';
    } else {
        $id = '';
    }

    // Remove id from attributes
    if (array_key_exists('id', $attribs) &amp;&amp; empty($attribs['id'])) {
        unset($attribs['id']);
    }
    
    // Set the name attribute if it exists and the doctype is not XHTML
    if (false === $this-&gt;_isXhtml() &amp;&amp; !empty($name)) {
        $name = ' name="' . $this-&gt;view-&gt;escape($name) . '"';
    } else {
        $name = '';
    }
    
    // Remove name from attributes
    if (array_key_exists('name', $attribs) &amp;&amp; empty($attribs['name'])) {
        unset($attribs['name']);
    }

    $html = '_htmlAttribs($attribs)
          . '&gt;';

    if (false !== $content) {
        $html .= $content
              .  '';
    }

    return $html;
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ulf Kirsten (ulfkirsten6) on 2010-12-14T09:47:59.000+0000</p> 
        <div class="body">
            <p>I do not see the point why the attribute "name" should be removed when a xhtml doctype is set.</p>

<p>The W3C states in the XHTML 1.0 Recommendation taht the name attribute is formally deprecated and will be removes. As we all know there will be no future xhtml version and in the current 1.0 version it is allowed. Why then restrict the developer (especially under the fact that the older IE versions do not work properly and need the identical value for the "name"and "id" attribute)?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T08:38:52.000+0000</p> 
        <div class="body">
            <p>I agree with Ulf on this one.  XHTML 1.0 and 1.1 deprecated the name attribute on form tags but never formally removed it, and it is valid syntax in HTML5, so there is no reason to deny it's use here.</p>

<p>I thought that you could do the following regardless of whether the name attribute is added by the view helper:</p>

<pre class="highlight"><code>
// When creating a new form instance
$zf = new Zend_Form(array(
    'attribs' =&gt; array(
        'name' =&gt; 'NameOfForm'
    )
));

// ...or inside the init() method of your Zend_Form subclass:
$this-&gt;setAttrib('name', 'NameOfForm');
</code></pre>

<p>However, when I tried it against 1.11.1 it did not have the desired effect.  A change to Zend_View_Helper_Form like the one Kai suggested should fix that, though.   The other option would be to find out where in the call stack the name attribute is overridden (my money is on Zend_View_Helper_FormElement::_getInfo(..), but I haven't been able to prove that yet).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T09:20:37.000+0000</p> 
        <div class="body">
            <p>I've attached a patch which I think sorts out this issue:
 - single line change to Zend_View_Helper_FormElement::_getInfo(...)
   (Allows overriding of name attribute on all Form elements)
 - Added two tests to Zend_View_Helper_FormTest ala the existing tests for the ID attribute</p>

<p>Comments?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T09:35:59.000+0000</p> 
        <div class="body">
            <p>Made a few slight changes
 - Fixed: Providing NULL name attribute should not produce</p>

<p>&lt;</p>

<p>form name=""&gt;
 - Added: Test to enforce above
 - Fixed: Nomenclature on tests was clumsy.  Changed to follow ID tests more closely.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-17T10:10:05.000+0000</p> 
        <div class="body">
            <p>Reformatted patch to Zend Framework coding guidelines (ie: replaced tabs with spaces)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2010-12-18T04:45:26.000+0000</p> 
        <div class="body">
            
    
    

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-18T05:10:52.000+0000</p> 
        <div class="body">
            <p>Excellent point!  I failed to read the DTDs close enough, and took the W3C documents at their word that the element was deprecated and not removed.  Apologies for that.  I will modify my patch annd repost  later this morning.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2010-12-18T05:14:40.000+0000</p> 
        <div class="body">
            <p>A proposal (not tested!):</p>

<pre class="highlight"><code>
// Set the name attribute if it exists and the doctype is not XHTML Strict or XHTML 1.1
$isStrictXhtml = false;
if ($this-&gt;_isXhtml() &amp;&amp; stristr($this-&gt;view-&gt;doctype(), 'strict')
    || stristr($this-&gt;view-&gt;doctype(), 'XHTML 1.1')) {
    $isStrictXhtml = true;
}

if (false === $isStrictXhtml &amp;&amp; !empty($name)) {
    $name = ' name="' . $this-&gt;view-&gt;escape($name) . '"';
} else {
    $name = '';
}

</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-18T07:14:01.000+0000</p> 
        <div class="body">
            <p>I've updated my patch with the suggested modifications:
{quote}
- Narrowed scope of fix to only affect the form tag
- Will not render name attribute when using XHTML 1.0 strict or XHTML 1.1
- Extended test suite:
     [x] Passing name as attribute should override form name
     [x] Not specifying form name should not render name attrib
     [x] Specifying form name should render name attrib
     [x] Passing empty name attribute to unnamed form should not render name attrib
     [x] Passing empty name attribute to named form should not override name attrib
     [x] Name attribute should be omitted when using xhtml 1 strict
     [x] Name attribute should be omitted when using xhtml 11
- Removed incorrect test: testPassingIdAsAttributeShouldRenderIdAttribAndNotName()
  (name and id attributes can coexist in some doctypes)
{quote}</p>

<p>Comments?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2010-12-18T08:21:19.000+0000</p> 
        <div class="body">
            <p>@Adam
Thanks!</p>

<p>Two more ideas for Zend_View_Helper_Doctype:</p>

<pre class="highlight"><code>
public function isStrict()
{
    switch ($this-&gt;getDoctype()) {
        case self::XHTML11:
        case self::XHTML1_STRICT:
        case self::HTML4_STRICT:
            // ...
    }
}

public function getHtmlVersionNumber()
{
    // ...
}
</code></pre>

<p>@Ulf
??W3C declared XHTML as dead??
XHTML is not dead: <a href="http://www.w3.org/TR/html5/introduction.html#html-vs-xhtml">XHTML5</a> ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-18T08:44:51.000+0000</p> 
        <div class="body">
            <p>@Kai:
Thanks for the suggestion.  That does streamline the logic nicely :)
I've attached a patch to reflect the changes.</p>

<p>Regarding Ulf's statement, I think he was referring to the fact that HTML5 is the defacto successor to XHTML 1, and the future of the web (that is, if you believe the hype from Apple, et. al :P)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-12-18T12:07:39.000+0000</p> 
        <div class="body">
            <p>Thanks for your work on this Adam.  One small item of note regarding your latest patch - the test annotations should be "@group ZF-10791" and not "@see ZF-10791".  This allows running the tests in isolation via "runtests.sh ZF-10791"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2010-12-18T13:02:11.000+0000</p> 
        <div class="body">
            <p>@Marc
Thanks for pointing that out.  I have changed @see to @group for all of the bug-related tests in Zend_View_Helper_FormTest.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-02T22:49:12.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23945</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-02T22:59:33.000+0000</p> 
        <div class="body">
            <p>Test added in trunk r23947</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-28T16:32:45.000+0000</p> 
        <div class="body">
            <p>Test suite updated in r24058
* Removed incorrect test: testPassingIdAsAttributeShouldRenderIdAttribAndNotName()
  (name and id attributes can coexist in some doctypes)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-05T16:22:38.000+0000</p> 
        <div class="body">
            <p>Commits reviewed and merged to 1.11 release branch.</p>

        </div>
    </div>
    </div>

