<h2>ZF-10681: Array_merge redefines numeric keys</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-13T07:15:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-18T09:16:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jurian Sluiman (mithras)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller_Router</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13440/zf.patch">zf.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The default route in the router is merged with the existing routes through {{array_merge()}}. Unfortunately the php guys think this is no bug, though an report has been made (<a href="http://bugs.php.net/bug.php?id=18075">http://bugs.php.net/bug.php?id=18075</a>).</p>

<p>When routes are added and their keys have a special reason to be non-incremental, the preservation of keys is important (eg when they represent a page id). Suggestion is to use the plus-sign instead of {{array_merge()}}. Example:</p>

<pre class="highlight"><code>

To this:

</code></pre>

<p>This issue is a bit related to <a href="http://framework.zend.com/issues/browse/ZF-3726">http://framework.zend.com/issues/browse/ZF-3726</a> where also the preservation of keys is important.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurian Sluiman (mithras) on 2010-11-13T07:17:44.000+0000</p> 
        <div class="body">
            <p>Patch to solve this issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-11-13T07:18:34.000+0000</p> 
        <div class="body">
            <p>Why should the id of a route be equal (after parsing) to that of e.g. a page id?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurian Sluiman (mithras) on 2010-11-13T07:27:35.000+0000</p> 
        <div class="body">
            <p>bq. Why should the id of a route be equal (after parsing) to that of e.g. a page id?</p>

<p>Not in particular, but you could add a route "blog" for you blog-related route. This name is used when you later want to use that route. The same counts for other names. In my case, the names are numeric (representing page ids) which causes it to go wrong. The usage of names for routes in pretty common (<a href="http://framework.zend.com/manual/en/zend.controller.router.html">http://framework.zend.com/manual/en/…</a>), but only arise when numeric names (ie keys in the routes array) are used.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-11-18T09:16:27.000+0000</p> 
        <div class="body">
            <p>Commited to trunk in r23361</p>

        </div>
    </div>
    </div>

