<h2>ZF-11757: Zend_Service_Amazon_Sqs::receive does not provide an option for turning off urldecode on the message.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-09-21T23:48:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-21T12:57:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dan Danese (biouxtai)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Enrico Zimuel (zimuel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
            <li>Sqs</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>An option needs to be added to the receive function or the class needs a receive_raw function to enable receipt of a raw message.  Not all are urlencoded when placed on the queue.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kasper Pedersen (kasperjin) on 2012-08-21T12:57:18.000+0000</p> 
        <div class="body">
            <p>IMO the URL encoding should be turned off completely, as it messes with the message body without even looking at the supplied MD5 checksum. Other libraries may not use URL encoding. For instance Amazons SNS service puts JSON encoded message bodies in SQS, which may end up being unreadable because of the URL decoding.</p>

        </div>
    </div>
    </div>

