<h2>ZF-1352: Hard coded default module name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-05-06T08:58:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Default module name is hard coded in the code base as opposed to action and controller which keys and names are configurable by the framework user. Hard coding is a common anti-pattern which leads to problems down the road. I would really like to see that changed pre 1.0:</p>

<pre class="highlight"><code>
Index: /home/martel/WWW/ZendFramework/library/Zend/Controller/Dispatcher/Abstract.php
===================================================================
--- /home/martel/WWW/ZendFramework/library/Zend/Controller/Dispatcher/Abstract.php  (revision 4704)
+++ /home/martel/WWW/ZendFramework/library/Zend/Controller/Dispatcher/Abstract.php  (working copy)
@@ -51,6 +51,7 @@
      * @var string
      */
     protected $_defaultController = 'index';
+    protected $_defaultModule = 'default';
 
     /**
      * Front Controller instance
</code></pre>

<p>The problematic code already present in the code base includes:</p>

<pre class="highlight"><code>
Zend_Controller_Dispatcher_Standard:

244:        if ('default' != $this-&gt;_curModule) {
245:            $className = $this-&gt;formatModuleName($this-&gt;_curModule) . '_' . $className;
246:        }

275:        $this-&gt;_curModule    = 'default';
276:        $this-&gt;_curDirectory = $controllerDirs['default'];

320:        $this-&gt;_curModule    = 'default';
321:        $this-&gt;_curDirectory = $controllerDirs['default'];


Zend_Controller_Router_Route_Module:

123:                 $this-&gt;_moduleKey     =&gt; 'default'


Zend_Controller_Action:

166:         if (empty($module) || !isset($dirs[$module])) {
167:             $module = 'default';
168:         }

Zend_Controller_Front:

218:         if (empty($module) || is_numeric($module) || !is_string($module)) {
219:             $module = 'default';
220:         }

</code></pre>

<p>And it will only get worse in the future.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-05-16T14:53:33.000+0000</p> 
        <div class="body">
            <p>'default' is no longer hard coded, and changes were made throughout the Zend_Controller tree, including new classes introduced since the issue was raised.</p>

<p>See r4826 for full revision log.</p>

        </div>
    </div>
    </div>

