<h2>ZF-11906: Update library and test suite to be compatible with PHP 5.4</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-11-22T03:52:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-13T12:39:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>FixForZF1.12</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-12286">ZF-12286</a></li>
            <li><a href="/issues/browse/ZF-12093">ZF-12093</a></li>
            <li><a href="/issues/browse/ZF-12194">ZF-12194</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Update library and test suite to be compatible with PHP 5.4, starting now with 5.4.0RC1.</p>

<p>Complete list of changes in PHP 5.4.0RC1:  <a href="http://www.php.net/releases/NEWS_5_4_0_RC1.txt">http://www.php.net/releases/NEWS_5_4_0_RC1.txt</a></p>

<p>+Issues / Progress+</p>

<ul><li>Flood of notices from {{runtests.sh}}   [fixed r24627 r24628]</li>
</ul><pre class="highlight"><code>
PHP Notice:  Constant  already defined in tests/TestConfiguration.php.dist on line XXX
</code></pre>

<ul><li><p>Remove all references to ini key 'y2k_compliance', which was removed in 5.4.0  [fixed r24805]</p></li>
<li><p>Fix "Array to string conversion" errors turned up by unit tests [r24807]</p></li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-01-16T20:08:45.000+0000</p> 
        <div class="body">
            <p>First: don't use runtests.sh -- we should likely remove that. Second, I ran into this issue in ZF2, mainly in tests that use the "runInSeparateProcess" annotation; the solution for that is to do a "defined(...) || define(...)" style declaration. This, however, is not related to 5.4 specifically.</p>

<p>When we ran tests on 5.4rc2, what we found was:</p>

<ul><li>There were BC breaks in some ob*() functions -- but these were fixed in a subsequent RC.</li>
<li>Array to string conversion now raises warnings, which can break tests. These are cases where we <em>will</em> need to fix code for tests to run normally.</li>
<li>Classes extending an abstract class and redefining the constructor but with different arguments will now raise an E_FATAL. We only had one place we were doing this, and it shouldn't have occurred anyways -- but it will need to be corrected.</li>
</ul><p>The biggest thing to focus on is the second point, above.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-23T21:58:21.000+0000</p> 
        <div class="body">
            <p>Fixed declaration of TESTS_* constants in TestConfiguration.php.dist (r24627 r24628)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-10T01:40:39.000+0000</p> 
        <div class="body">
            <p>Additional fix for definition of TESTS_ZEND_SERVICE_RACKSPACE_* constants, which belong to component not yet merged into release branch.  (r24673)</p>

        </div>
    </div>
    </div>

