<h2>ZF-10918:  render*Decorator* overloader</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-05T08:30:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-20T13:12:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The content passed to the decorators render method is by default an empty string when no arguments are provided, this leaves Decorator_Form always closing the tag since the viewhelper strictly type-checks for false.</p>

<p>Zend_Form:3152</p>

<pre class="highlight"><code>
$seed = '';
if (0 &lt; count($args)) {
    $seed = array_shift($args);
}
if ($decoratorName === 'FormElements' ||
    $decoratorName === 'PrepareElements') {
        $this-&gt;_setIsRendered();
}
return $decorator-&gt;render($seed);
</code></pre>

<p>I randomly checked several decorators but this seem to be the only "wrapping" decorator so the empty string(@see $seed) seems to be compliant with most of the decorators, maybe change it to below if so?</p>

<p>Zend_View_Helper_Form:64
```</p>

<p>At the moment you will always have to decorate the tags yourself(OMG &lt;@:)) if you're not rendering the form through the decorator</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-01-06T07:11:40.000+0000</p> 
        <div class="body">
            <p>Please add an example to reproduce the problem.
Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2011-01-20T13:12:20.000+0000</p> 
        <div class="body">
            <p>Can you provide the expected, and given result?</p>

        </div>
    </div>
    </div>

