<h2>ZF-10787: urlencoded parameters - %2F is being treated as a /</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-06T08:58:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-04T18:05:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jonathan Dunn (jmd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3527">ZF-3527</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am redirecting to a log in form like so:</p>

<p>$this-&gt;_helper-&gt;redirector('login', 'auth', null, array('redirect' =&gt; $this-&gt;getRequest()-&gt;getRequestUri()));</p>

<p>Results in:
<a href="http://www.domain.com/admin/auth/login/redirect/%2Fadmin%2Fviewer%2Fshow%2FdateFrom%2F2010-12-13%2FdateTo%2F2011-01-03%2Fhighlight%2F2010-12-20%2Fshow%2F1%2Fmode%2Foccupancy-diary%2FmemberId%2F50000">http://domain.com/admin/auth/…</a></p>

<p>This seems to work fine in 1.10.8 but in the latest version (1.11.1) %2F is being treated as a /:</p>

<p>Ver 1.10.8
array(9) { ["module"]=&gt; string(5) "admin" ["controller"]=&gt; string(4) "auth" ["action"]=&gt; string(5) "login" ["redirect"]=&gt; string(120) "/admin/viewer/show/dateFrom/2010-12-13/dateTo/2011-01-03/highlight/2010-12-20/show/1/mode/occupancy-diary/memberId/50000" ["username"]=&gt; string(12) "jonathan" ["password"]=&gt; string(9) "mypassword" ["code1"]=&gt; string(1) "5" ["code2"]=&gt; string(1) "5" ["submit"]=&gt; string(5) "Login" }</p>

<p>Ver 1.11.1
array(16) { ["module"]=&gt; string(5) "admin" ["controller"]=&gt; string(4) "auth" ["action"]=&gt; string(5) "login" ["redirect"]=&gt; string(0) "" ["admin"]=&gt; string(6) "viewer" ["show"]=&gt; string(8) "dateFrom" ["2010-12-13"]=&gt; string(6) "dateTo" ["2011-01-03"]=&gt; string(9) "highlight" ["2010-12-20"]=&gt; string(4) "show" [1]=&gt; string(4) "mode" ["occupancy-diary"]=&gt; string(8) "memberId" ["username"]=&gt; string(12) "jonathan" ["password"]=&gt; string(9) "mypassword" ["code1"]=&gt; string(1) "5" ["code2"]=&gt; string(1) "5" ["submit"]=&gt; string(5) "Login" }</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-06T10:03:18.000+0000</p> 
        <div class="body">
            <p>I did not perform a battery of tests but believe that be after change ZF-3527.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Artiom Lunev (_artiom) on 2010-12-06T21:49:01.000+0000</p> 
        <div class="body">
            <p>I added a test case in comments for ZF-3527.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-04T17:03:23.000+0000</p> 
        <div class="body">
            <p>Potential fix in trunk at r24002 - asking for watchers to test now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-04T18:05:43.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk at r24002
Fixed in release branch 1.11 at r24003</p>

        </div>
    </div>
    </div>

