<h2>ZF-10913: Wrong structure of models/views</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-05T01:18:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-08T08:44:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Przemys?aw Wróbel (wrobel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I create a new module with zf create module test. I got the views directory nested under models directory.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-08T08:44:09.000+0000</p> 
        <div class="body">
            <p>Closing as non-reproduceable.
Feel free to reopen the issue as soon as you can provide additional informations.</p>

<p>Thanks
Ramon</p>

        </div>
    </div>
    </div>

