<h2>ZF-10227: Zend_Gdata_YouTube does not support  spell checker feature</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-07-26T01:14:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The component Zend_Gdata_YouTube in query does not support  spell checker feature,did you mean
see <a href="http://code.google.com/apis/youtube/2.0/reference.html#Spelling_Suggestions">http://code.google.com/apis/youtube/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

