<h2>ZF-12073: Clean up spam</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2012-02-27T15:45:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-12T00:56:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is comment spam on <a href="http://framework.zend.com/manual/en/">http://framework.zend.com/manual/en/</a></p>

<p>Give me delete access and I will clean it up when I come across some</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-05T18:18:16.000+0000</p> 
        <div class="body">
            <p>AFAIK, [~matthew] is working on changing the comments system to Disqus.  Not sure what the ETA on that being available is, though.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-03-05T18:40:25.000+0000</p> 
        <div class="body">
            <p>This week.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-12T00:56:31.000+0000</p> 
        <div class="body">
            <p>Disqus has replaced the old comments system, and the spam has disappeared with it. Thanks, Matthew!</p>

        </div>
    </div>
    </div>

