<h2>ZF-10404: sample code of authenticate() not found</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-09-01T01:18:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T13:15:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Yutaka Nakadouzono (yutaka.nakadouzono@gmail.com)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Document of Database Table Authentication of Zend_Auth,</p>

<p>quotation</p>

<h6>#</h6>

<p>At this point, the authentication adapter instance is ready to accept authentication queries. In order to formulate an authentication query, the input credential values are passed to the adapter prior to calling the authenticate() method:</p>

<p>1.// Set the input credential values (e.g., from a login form)
2.$authAdapter
3.    -&gt;setIdentity('my_username')
4.    -&gt;setCredential('my_password')
5.;
6. 
7.// Perform the authentication query, saving the result</p>

<h6>#</h6>

<p>In sample code, most important function authenticate() is not used.
Please add sample code of authenticate().
thank you.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-29T13:15:27.000+0000</p> 
        <div class="body">
            <p>The Database Table Authentication manual page shows how to set up the DbTable adapter, not how to use the Auth component as a whole.  Please refer to the <a href="http://framework.zend.com/manual/en/zend.auth.introduction.html">main Zend_Auth documentation</a> for examples on how to use the Auth class.</p>

        </div>
    </div>
    </div>

