<h2>ZF-1749: App::get returns fatal error: &quot;Call to a member function setConfig() on a non-object&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-07-20T19:25:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T18:44:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><em>Summary</em>
When calling Zend_Gdata_App::get, the following fatal error is encountered:</p>

<p>bq. Call to a member function setConfig() on a non-object</p>

<p>This is caused because get attempts to reference $client instead of $this-&gt;_httpClient.</p>

<p><em>Regression</em>
This was first introduced in r5162. Affects ZF 1.0 RC2 and later.</p>

<p><em>Notes</em>
 * No workaround is currently available.
 * Unit tests need to be expanded to cover this function.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-07-20T22:35:13.000+0000</p> 
        <div class="body">
            <p>I wasn't sure weather to categorize this as critical or not. It does cause crashing and comprises part of the  module's core functionality, so it fits the description. However, it seems that none of the higher level functions are calling this or we would have noticed it by now. The only reason I spotted it  was because I was writing a debug tool that was calling the low level GData functions.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-07-20T22:46:21.000+0000</p> 
        <div class="body">
            <p>I have a patch for this baked up. I'll send it to Ryan once I get back to a WiFi connection.</p>

<p>My patch doesn't address the lack of unit tests, which seems to apply to almost all of App.php. Perhaps this should be opened as a separate bug?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-07-23T07:22:12.000+0000</p> 
        <div class="body">
            <p>Assigned to Ryan</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-09-16T13:14:33.000+0000</p> 
        <div class="body">
            <p>Fixed in svn rev 6377</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T18:44:44.000+0000</p> 
        <div class="body">
            <p>Updating Fix Version to follow issue tracker convention.</p>

        </div>
    </div>
    </div>

