<h2>ZF-11058: Documentation of return type &quot;class instance&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-02-09T04:50:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-19T03:32:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.4 (03/Mar/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13632/UserAgent.php.patch">UserAgent.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>that IDEs like Zend Studio can support the suggestion, the return value has to be declared, from which class the instance is returned.</p>

<p>Example Zend_Http_UserAgent:</p>

<pre class="highlight"><code>
/**
 * @return Zend_Http_UserAgent_Device $device
 */
public function getDevice()
</code></pre>

<p>Now the IDE can support the suggestion of methods from this class instance.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-09T05:34:35.000+0000</p> 
        <div class="body">
            <p>This is just an oversight. All other methods are properly documented.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-09T05:48:25.000+0000</p> 
        <div class="body">
            <p>Patch added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-02-19T03:32:42.000+0000</p> 
        <div class="body">
            <p>Thank You for reporting. Solved at SVN r23728, 23729 with setServer($server).</p>

<p>Because setServer was explained as: Retrieve the "$_SERVER" array .</p>

        </div>
    </div>
    </div>

