<h2>ZF-11374: Override default translation for Zend_Validator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-13T18:18:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-30T20:30:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.10 (04/Aug/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Egesté (egeste)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
            <li>default</li>
            <li>override</li>
            <li>translation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm using Zend_Locale and Zend_Translate in a custom class</p>

<pre class="highlight"><code>
class pplib_Locale extends Zend_Locale {
    
    protected $_translate;
    
    public function __construct() {
        $locale = $this-&gt;findLocale();
        $auth = Zend_Auth::getInstance();
        if(($user = $auth-&gt;getIdentity()) !== null) {
            $locale = $user-&gt;getLocale();
        }
        parent::__construct($locale);
        $this-&gt;_translate = new Zend_Translate(array(
            'adapter'           =&gt;'gettext', 
            'content'           =&gt; APPLICATION_PATH.'/languages/',
            'scan'              =&gt; 'directory',
            'locale'            =&gt; $locale,
            'clear'             =&gt; true,
            'reload'            =&gt; true
        ));
        Zend_Registry::set('pplib_Locale', $this);
    }
    
    public function getTranslate() {
        return $this-&gt;_translate;
    }
    
}
</code></pre>

<p>and initializing the default translater in Bootstrap</p>

<pre class="highlight"><code>
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
[..]
    protected function _initLocale() {
        $locale = new pplib_Locale();
        Zend_Form::setDefaultTranslator($locale-&gt;getTranslate());
    }
[..]
}
</code></pre>

<p>and I want to override the translation for a form validator error message.</p>

<pre class="highlight"><code>
class Application_Form_Login extends Zend_Form
{
    public function init() {
[..]
        $password = new Zend_Form_Element_Password('password');
        $password-&gt;setLabel($view-&gt;translate('PP_PASSWORD'))
            -&gt;setRequired(true)
            -&gt;setAllowEmpty(false)
            -&gt;addFilter('StringTrim')
            -&gt;addValidator('StringLength', false, array(8))
            -&gt;addValidator('Regex', false, array(
                "/[..]/"
            ))
            -&gt;getValidator('Regex')
                -&gt;setDisableTranslator(true)
                -&gt;setMessage($view-&gt;translate('PP_PASSWORD_CHARS'), 'regexNotMatch');
        
[..]
    }   
}
</code></pre>

<p>this does not work - the validator still uses the default translation. Is this a bug or correct behavior? Is it possible to override a default translation?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-05-14T14:30:51.000+0000</p> 
        <div class="body">
            <p>"Does not work" is useless.
What did you do?
What result did you expect?
What result did you get?
What is the content of the locale?
Was the requested locale detected by Zend_Translate?</p>

<p>and so on...
PS: Zend_Locale does NOT TRANSLATE. Using it to translate things is bad behaviour and should really be avoided to prevent method-quirks.
PPS: You disabled translation for the validator... why do you expect to get translated content with a disabled translator?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-05-15T11:42:55.000+0000</p> 
        <div class="body">
            <p>Egesté - what do you mean with ... <em>the validator still uses the default translation</em>? Class' default or something else? In other words, is the output error "<em>'%value%' does not match against pattern '%pattern%'</em>" or something else?</p>

<p>bq. PPS: You disabled translation for the validator... why do you expect to get translated content with a disabled translator?</p>

<p>I think he disabled the translator to prevent possible double translation. However, as said, this issue is pretty much incomplete for me too.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Egesté (egeste) on 2011-05-15T15:46:30.000+0000</p> 
        <div class="body">
            <p>I didn't think I had left any room for ambiguity, did either of you read the source code I posted in the ticket? Can you see that there's source code in this ticket?.. I will try to explain without using code and assume you cannot see the code I posted...</p>

<p>What I'm doing is extending an instance of Zend_Locale and using it as a wrapper for other locale-specific classes, in this case I'm using it for translation. In the future I plan to also use it for timezone, currencies etc. The name of my Zend_Locale wrapper class is pplib_Locale. The pplib_Locale class creates and stores an instance of Zend_Translate with the following params:
*adapter = gettext
*content = APPLICATION_PATH.'/languages/'
*scan = directory
*locale = $locale (This is either the default locale, a detected locale, or a user-specified locale)
*clear = true
*reload = true</p>

<p>Once I have instantiated all the params I want in pplib_Locale, I save it to the registry.
Zend_Registry::set('pplib_Locale', $this);</p>

<p>Then, in Bootstrap, I set the defaul translator for Zend_Form to the translator I initialized in pplib_Locale, like so:
Zend_Form::setDefaultTranslator($locale-&gt;getTranslate()); // $locale is a valid pplib_Locale, created one line above it in bootstrap</p>

<p>In my gettext files, I have created entries for the various default error messages in various Zend_Validate classes. For example: In the Zend_Validate_Regex class, the error message "key" 'regexNotMatch' has been translated to "Invalid input.".</p>

<p>If I stop here, all my translations work. You don't need to know my locale, you don't need to know anything more than if I stop here all my translations work. My problem has nothing to do with getting translations to work.</p>

<p>Moving on to the issue...</p>

<p>There is one specific form for which I would like to OVERRIDE the default translation for a validation error. The form is my login form, the field is my password field, and the validator is the Regex validator, as you may or may not have seen in the source code I posted.</p>

<p>I have tried to set the error message manually via:
$element-&gt;getValidator('Regex')-&gt;setMessage('PP_PASSWORD_CHARS', 'regexNotMatch').
I expected the translated output of a 'regexNotMatch' error for this form&gt;element&gt;validator to then be the translated text for the gettext key 'PP_PASSWORD_CHARS', but it still gives the default 'regexNotMatch' error message "Invalid input."</p>

<p>So I tried to disable the default translator for the validator via:
$element-&gt;getValidator('Regex')-&gt;setDisableTranslator(true)-&gt;setMessage($view-&gt;translate('PP_PASSWORD_CHARS'), 'regexNotMatch');
I expected the validators default translator to be disabled, and instead use my translate view helper to set the error message manually for the validation error 'regexNotMatch'. This, too, still outputs the default 'regexNotMatch' error message "Invalid input."</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-05-15T16:17:20.000+0000</p> 
        <div class="body">
            <p>My humble guess is that if error message key, like <em>regexNotMatch</em>, is used as a string to be translated it may override the whole translation process in validator. If I may suggest, you should not use those in your language resource files but full message strings. See for example <a href="http://framework.zend.com/svn/framework/standard/trunk/resources/languages/en/Zend_Validate.php">this resource file</a>.</p>

<pre class="highlight"><code>
// Snippet from Zend_Validate_Abstract

    protected function _createMessage($messageKey, $value)
    {
        if (!isset($this-&gt;_messageTemplates[$messageKey])) {
            return null;
        }

        $message = $this-&gt;_messageTemplates[$messageKey];

        if (null !== ($translator = $this-&gt;getTranslator())) {
--&gt;         if ($translator-&gt;isTranslated($messageKey)) {
                $message = $translator-&gt;translate($messageKey);
            } else {
                $message = $translator-&gt;translate($message);
            }
        }

        ...

</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-07-30T20:30:14.000+0000</p> 
        <div class="body">
            <p>I can not reproduce this behaviour.
Therefor closing this issue as not reproduceable.</p>

<p>Please note that also other validators have a "invalid input" message.</p>

<p>Feel free to reopen when you have additional informations. When you have questions on coding problems please ask within the mailing list.</p>

        </div>
    </div>
    </div>

