<h2>ZF-1309: Unable to clone Zend_Pdf_Page</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-04-24T05:43:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T18:42:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Karol Grecki (antych)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-449">ZF-449</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This class does not implement __clone() and copying pages fails.
There's a hint that page cloning is done via constructor and not is implemented yet:</p>

<pre class="highlight"><code>
        if ($param1 instanceof Zend_Pdf_Page &amp;&amp; $param2 === null &amp;&amp; $param3 === null) {
            /** @todo implementation */
            throw new Zend_Pdf_Exception('Not implemented yet.');
</code></pre>

<p>This missing bit is a serious issue if you try to do proper OOP.
IMHO copying object belongs to clone keyword and __clone() method.
And if it's meant to be done by the constructor then at least __clone() should throw an exception.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-05-06T09:15:24.000+0000</p> 
        <div class="body">
            <p>Assigned to Alexander due to Zend_Pfd relation</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-05-25T02:52:00.000+0000</p> 
        <div class="body">
            <p>Postponed to post-1.0 period</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Paul Menheere (paulmenheere) on 2007-08-17T14:55:10.000+0000</p> 
        <div class="body">
            <p>Is there any Idea when this is going to be implemented ??</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-08-26T13:51:32.000+0000</p> 
        <div class="body">
            <p>I see it's an important feature.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-08-26T13:52:56.000+0000</p> 
        <div class="body">
            <p>I think it should be done as one of the first Zend_Pdf improvements.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-09-05T07:58:24.000+0000</p> 
        <div class="body">
            <p>Done.</p>

<p>Cloning mechanism is not used because we need access to the source object (that's of course possible to do this, but it complicates memory management).</p>

<p>Exception is thrown if clone keyword is used.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T18:42:10.000+0000</p> 
        <div class="body">
            <p>Updating Fix Version to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

