<h2>ZF-10675: Zend_View_Helper_Json does not enforce replace_header</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-12T07:18:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-19T12:09:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11686">ZF-11686</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_View_Helper_Json calls</p>

<p>Zend_Controller_Front::getInstance()
  -&gt;getResponse()
  -&gt;setHeader("Conten-type", "application/json")</p>

<p>without the 3rd argument enforced to TRUE, which
might lead to duplicate Content-type headers, which
in turn might cripple (500) Apache httpd + fastcgi:</p>

<p>FastCGI: comm with server "/srv/http/cgi-bin/virtual-php-fastcgi" aborted: error parsing headers: duplicate header 'Content-Type'</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2010-11-18T23:44:15.000+0000</p> 
        <div class="body">
            <p>Fixed in r23390.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-28T05:11:55.000+0000</p> 
        <div class="body">
            <p>Merged to branch release 1.11 r23451.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-28T05:13:27.000+0000</p> 
        <div class="body">
            <p>Assigned fix version.</p>

        </div>
    </div>
    </div>

