<h2>ZF-14: Remove Zend_Pdf_Const</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-06-16T23:42:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.4 (29/Jun/06)</li>
            <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Willie Alberty (willie)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-18">ZF-18</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Pdf_Const was initially conceived as the single home for all PDF-related constants. This worked well enough when the number of constants was small, but recent work (ZF-6 and Zend_Pdf_Image subclasses) has more than tripled the constant count, making a master class like this difficult to maintain.</p>

<p>None of the other components in the framework share this model; they all define constants in the base classes that use them. For consistency with the other components in the framework, and to improve maintainability going forward, move the constants currently defined in Zend_Pdf_Const to the base classes in which they are used.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2006-06-16T23:43:16.000+0000</p> 
        <div class="body">
            <p>This issue necessitates a change to the public API. Specific details to follow...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2006-06-17T14:33:53.000+0000</p> 
        <div class="body">
            <p>Done. This issue caused a backwards-incompatible API change. To repair your code, you will need to perform the following global search-and-replace operations:</p>

<pre class="literal"> 
Zend_Pdf_Const::PAGESIZE_     -&gt;  Zend_Pdf_Page::SIZE_
Zend_Pdf_Const::SHAPEDRAW_    -&gt;  Zend_Pdf_Page::SHAPEDRAW_
Zend_Pdf_Const::FILLMETHOD_   -&gt;  Zend_Pdf_Page::FILLMETHOD_
Zend_Pdf_Const::LINEDASHING_  -&gt;  Zend_Pdf_Page::LINEDASHING_
Zend_Pdf_Const::PDF_          -&gt;  Zend_Pdf::PDF_
Zend_Pdf_Const::pdfDate()     -&gt;  Zend_Pdf::pdfDate()
</pre>

<p>In addition, font object creation has been revamped. Font objects are now instantiated via a factory methods. You will also need to perform the following global search-and-replace operation:</p>

<pre class="literal"> 
new Zend_Pdf_Font_Standard(Zend_Pdf_Const::FONT_  -&gt;
  Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_
</pre>

<p>Finally, the old static arrays {{$pageSizeAliases}} and {{$standardFonts}} have been completely removed. There are no replacements.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2006-06-17T17:26:10.000+0000</p> 
        <div class="body">
            <p>On Jun 17, 2006, at 4:04 PM, andi@zend.com wrote:</p>

<p>I have one piece of feedback though. The constants (not sure if you are responsible for naming them or not) don't use underscores to separate words. I think it'd be much nicer to do so. I know we have it in the PHP coding standards, but not sure if we wrote it in the ZFW coding standards (if not we should).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2006-06-17T19:11:10.000+0000</p> 
        <div class="body">
            <p>Implemented Andi's request. All constants in Zend_Pdf now have underscores between words.</p>

<p>{panel:title=NOTE: Due to this change, ignore the instructions above and use these instead.|titleBGColor=#F7D6C1|bgColor=#FFFFCE}
To repair your code, you will need to perform the following global search-and-replace operations:</p>

<pre class="literal">
Zend_Pdf_Const::PAGESIZE_                 -&gt; Zend_Pdf_Page::SIZE_
Zend_Pdf_Const::SHAPEDRAW_FILLNSTROKE     -&gt; Zend_Pdf_Page::SHAPE_DRAW_FILL_AND_STROKE
Zend_Pdf_Const::SHAPEDRAW_                -&gt; Zend_Pdf_Page::SHAPE_DRAW_
Zend_Pdf_Const::FILLMETHOD_NONZEROWINDING -&gt; Zend_Pdf_Page::FILL_METHOD_NON_ZERO_WINDING
Zend_Pdf_Const::FILLMETHOD_EVENODD        -&gt; Zend_Pdf_Page::FILL_METHOD_EVEN_ODD
Zend_Pdf_Const::LINEDASHING_              -&gt; Zend_Pdf_Page::LINE_DASHING_
Zend_Pdf_Const::PDF_                      -&gt; Zend_Pdf::PDF_
Zend_Pdf_Const::pdfDate()                 -&gt; Zend_Pdf::pdfDate()
</pre>

<p>In addition, font object creation has been revamped. Font objects are now instantiated via a factory methods. You will also need to perform the following global search-and-replace operations:</p>

<pre class="literal">
new Zend_Pdf_Font_Standard(Zend_Pdf_Const::FONT_  -&gt;
  Zend_Pdf_Font::fontWithName(Zend_Pdf_Font::FONT_

_BOLDITALIC  -&gt;  _BOLD_ITALIC
</pre>

<p>Finally, the old static arrays $pageSizeAliases and $standardFonts have been completely removed. There are no replacements.
{panel}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2006-06-17T19:23:14.000+0000</p> 
        <div class="body">
            <p>Updated the coding standards document as well: <a href="http://framework.zend.com/wiki/display/ZFDEV/Zend+Framework+PHP+Coding+Standard">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2008-05-24T21:05:10.000+0000</p> 
        <div class="body">
            <p>This change was made eons ago (in Zend Framework time) but the file Zend/Pdf/Const.php still exists.  At this point it is safe to remove it entirely.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-30T04:05:37.000+0000</p> 
        <div class="body">
            <p>Fixed with 12192</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:22.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

