<h2>ZF-1010: Fatal error: Call to undefined method Zend_Filter::ishostname() in /home/sebastian/Work/ZendFramework/library/Zend/Uri/Http.php on line 338</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-03-02T23:58:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>sh-3.1$ svn up
At revision 3712.
sh-3.1$ phpunit -d include_path=.:incubator/library/:library/:tests/:/opt/php/lib/php AllTests tests/AllTests.php
PHPUnit 3.0.3 by Sebastian Bergmann.</p>

<p>.........................................
.........................................
.........................................
.........................................
.........................SSSSSSSS........
.........................................
.........................................
......................
Fatal error: Call to undefined method Zend_Filter::ishostname() in /home/sebastian/Work/ZendFramework/library/Zend/Uri/Http.php on line 338</p>

<p>Call Stack:
    0.0003      53032   1. {main}() /opt/php/bin/phpunit:0
    0.0026     168756   2. require('/opt/php/lib/php/PHPUnit/TextUI/Command.php') /opt/php/bin/phpunit:44
    0.0676    2696788   3. PHPUnit_TextUI_Command::main() /opt/php/lib/php/PHPUnit/TextUI/Command.php:401
    1.9246   36277076   4. PHPUnit_TextUI_TestRunner-&gt;doRun() /opt/php/lib/php/PHPUnit/TextUI/Command.php:100
    1.9250   36278120   5. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/TextUI/TestRunner.php:247
    2.1348   36289440   6. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    2.6055   37522532   7. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    2.6195   37530096   8. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    2.6535   37602008   9. PHPUnit_Framework_TestSuite-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:491
    2.6535   37602008  10. PHPUnit_Framework_TestCase-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:510
    2.6535   37602008  11. PHPUnit_Framework_TestResult-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:223
    2.6536   37602008  12. PHPUnit_Framework_TestCase-&gt;runBare() /opt/php/lib/php/PHPUnit/Framework/TestResult.php:529
    2.6540   37602692  13. PHPUnit_Framework_TestCase-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:243
    2.6540   37602692  14. ReflectionMethod-&gt;invoke() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:300
    2.6540   37602692  15. Zend_Controller_Dispatcher_StandardTest-&gt;testNoModuleOrControllerDefaultsCorrectly() /home/sebastian/Work/ZendFramework/tests/Zend/Controller/Dispatcher/StandardTest.php:0
    2.6540   37602692  16. Zend_Controller_Request_Http-&gt;__construct() /home/sebastian/Work/ZendFramework/tests/Zend/Controller/Dispatcher/StandardTest.php:273
    2.6540   37602692  17. Zend_Uri::factory() /home/sebastian/Work/ZendFramework/library/Zend/Controller/Request/Http.php:91
    2.6541   37602692  18. Zend_Uri_Http-&gt;__construct() /home/sebastian/Work/ZendFramework/library/Zend/Uri.php:128
    2.6543   37603492  19. Zend_Uri_Http-&gt;valid() /home/sebastian/Work/ZendFramework/library/Zend/Uri/Http.php:91
    2.6543   37603492  20. Zend_Uri_Http-&gt;validateHost() /home/sebastian/Work/ZendFramework/library/Zend/Uri/Http.php:176</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2007-03-04T02:42:23.000+0000</p> 
        <div class="body">
            <p>This is also a unit-testing problem, but Zend_Filter were changed but no classes using it were modified to use the new Zend_Filter class, so you cannot use it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-15T13:52:45.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 3721.</p>

        </div>
    </div>
    </div>

