<h2>ZF-1778: Mysqli: Statement object cannot be reused</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-07-26T19:54:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T14:07:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.1 (30/Jul/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Adapter_Mysqli</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Mysqli adapter has a bug that {{fetchAll()}} does not free the statement, and thus a subsequent statement fails silently, if we try to use the same Statement object.</p>

<pre class="highlight"><code>
$db = Zend_Db::factory('mysqli', ...);
$stmt1 = $db-&gt;query('SELECT ...');
$result1 = $stmt1-&gt;fetchAll();

$stmt1 = $db-&gt;query('SELECT ...');
$result2 = $stmt1-&gt;fetchAll();
</code></pre>

<p>The second result is always empty, because the Mysqli connection cannot execute a new query until the old one is closed properly.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-07-26T20:13:37.000+0000</p> 
        <div class="body">
            <p>Fix committed in trunk in revision 5873.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-07-27T22:19:21.000+0000</p> 
        <div class="body">
            <p>Changes reviewed by Darby.</p>

<p>Committed to ZF 1.0.1 branch in revision 5906.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T14:07:42.000+0000</p> 
        <div class="body">
            <p>Fixing Fix Version/s to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

