<h2>ZF-1055: Mistake in Zend_Console_Getopt-Configuration</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-03-15T06:11:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T18:33:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Console_Getopt</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10330/patch_zend_console_getopt.patch">patch_zend_console_getopt.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Console_Getopt::CONFIG_DASHDASH is in double in Zend_Console_Getopt-Configuration.xml instead of Zend_Console_Getopt::CONFIG_IGNORECASE in the listitem of the section "Adding Configuration"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2007-03-15T06:24:48.000+0000</p> 
        <div class="body">
            <p>Patch SVN</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-15T13:32:05.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3964.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-04T15:51:45.000+0000</p> 
        <div class="body">
            <p>Add Zend_Console_Getopt to components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T18:33:22.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

