<h2>ZF-11903: Some head* placeholders behave oddly with setIndent</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-11-21T22:05:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-11-21T22:05:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Some placeholders in Zend_View_Helper exhibit odd behavior when using setIndent.</p>

<p>Example code (layout.phtml):
&lt;?php
echo strlen($this-&gt;headScript()-&gt;setIndent(2));
echo strlen($this-&gt;headMeta()-&gt;setIndent(2));
echo strlen($this-&gt;headLink()-&gt;setIndent(2));
?&gt;</p>

<p>Expected result:
0
0
0</p>

<p>Actual result:
0
2
2</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

