<h2>ZF-11253: Db/Table/Abstract.php fetchRow discards any offset</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2011-04-01T21:56:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-04T06:10:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Kim Blomqvist (kblomqvist)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13854/Abstract.php.patch">Abstract.php.patch</a></li>
            <li><a href="/issues/secure/attachment/13855/TestCommon.php.patch">TestCommon.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The fetchRow function discards the offset, such that</p>

<pre class="highlight"><code>
$select = $teams-&gt;select()
  -&gt;where('colour = ?', 'orange')
  -&gt;order('result')
  -&gt;limit(1,10);
          
echo (string) $teams;
// SELECT `teams`.* FROM `teams` WHERE (colour = 'orange') ORDER BY `result` ASC LIMIT 1 OFFSET 10
        
$teams-&gt;fetchRow($teams);
// SELECT `teams`.* FROM `teams` WHERE (colour = 'orange') ORDER BY `result` ASC LIMIT 1
</code></pre>

<p>This is an old issue that has been marked resolved but it wasn't and has been ignored despite attempts to reawaken both old tickets.</p>

<p>patch from 1.10.8, but fix is still applicable:</p>

<pre class="highlight"><code>
Index: Zend/Db/Table/Abstract.php
===================================================================
--- Zend/Db/Table/Abstract.php  (revision 1791)
+++ Zend/Db/Table/Abstract.php  (working copy)
@@ -1358,10 +1358,10 @@
                 $this-&gt;_order($select, $order);
             }
 
-            $select-&gt;limit(1);
+            $select-&gt;limit(1, $select-&gt;getPart(Zend_Db_Select::LIMIT_OFFSET));
 
         } else {
-            $select = $where-&gt;limit(1);
+            $select = $where-&gt;limit(1, $select-&gt;getPart(Zend_Db_Select::LIMIT_OFFSET));
         }
 
         $rows = $this-&gt;_fetch($select);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by The Lone Coder (loconut) on 2011-04-01T21:57:32.000+0000</p> 
        <div class="body">
            <p>related tickets:
<a href="http://framework.zend.com/issues/browse/ZF-8944">http://framework.zend.com/issues/browse/ZF-8944</a>
and
<a href="http://framework.zend.com/issues/browse/ZF-10598">http://framework.zend.com/issues/browse/ZF-10598</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-04-22T22:40:09.000+0000</p> 
        <div class="body">
            <p>I don't see the problem here. You have specified the count and offset in {{limit(1,10)}}, so why not use {{$table-&gt;fetchAll($select)}} then? In my opinion, the key use case here is do we have to assemble the select object or could we quick fetch a row like this ...</p>

<pre class="highlight"><code>
$row = $table-&gt;fetchRow(array('colour = ?' =&gt; 'orange'), null, 10);
</code></pre>

<p>Of course to get this work, we have to add an $offset parameter into the {{fetchRow}} method ...</p>

<pre class="highlight"><code>
public function fetchRow($where = null, $order = null, $offset = null)
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-04-23T07:42:52.000+0000</p> 
        <div class="body">
            <p>Patch attached to support my suggested use case and fix the inconsistency pointed out here.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-04T06:10:12.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk at r23993 and in release branch 1.11 at r23994</p>

        </div>
    </div>
    </div>

