<h2>ZF-10768: URL Parameter encoded twice</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-02T23:21:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-29T18:12:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>Zend_Controller_Router</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you set a url GET parameter like "TESTPARAM%23001%20%2B%20xyz" (TESTPARAM#001 + xyz) and then try to get it in controller</p>

<pre class="highlight"><code> 
$this-&gt;getRequest()-&gt;getParam('testparam');
</code></pre>

<p>you will get something like "TESTPARAM#001  xyz"</p>

<p>In Zend_Controller_Request_Http it is decoded in line 626 and the second decoding is in Zend_Controller_Router_Route line 249 (called in Zend_Controller_Router_Rewrite line 398)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-06-29T18:12:00.000+0000</p> 
        <div class="body">
            <p>Could not reproduce against ZF 1.11.7</p>

<ol><li>Created standard project:</li>
</ol><pre class="highlight"><code>
zf create project ZF-10768
</code></pre>

<ol><li>Modified {{application/controllers/IndexController.php}}</li>
</ol><pre class="highlight"><code>
    public function indexAction()
    {
        // action body
        var_dump($this-&gt;getRequest()-&gt;getParam('testparam'));
    }
</code></pre>

<ol><li>Opened web browser and visited URI: {{/public/?testparam=TESTPARAM%23001%20%2B%20xyz}}
And we receive the expected result (with XDebug enabled):</li>
</ol><pre class="highlight"><code>
string 'TESTPARAM#001 + xyz' (length=19)
</code></pre>

        </div>
    </div>
    </div>

