<h2>ZF-11691: Additional nl when Docblock comes from reflection</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-08-23T08:54:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-23T09:06:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_CodeGenerator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>

class Bug
{
    /**
     * @var string
     */
    private $_property;
}

$classBug = Zend_CodeGenerator_Php_Class::fromReflection(new Zend_Reflection_Class('Bug'));

echo $classBug-&gt;getProperty('_property')-&gt;getDocblock();

</code></pre>

<p>Output:</p>

<pre class="literal">
/**
 * @var string
 *
 */
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

