<h2>ZF-11931: Missing closing bracket in code example</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-03-06T03:04:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-26T19:00:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11154">ZF-11154</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Missing closing bracket of if-clause in code example #6 of Normalization and Localization:
<a href="http://framework.zend.com/manual/en/zend.locale.parsing.html#zend.locale.number.test">http://framework.zend.com/manual/en/…</a></p>

<p>corrected:</p>

<pre class="highlight"><code>
$locale = new Zend_Locale();
if (Zend_Locale_Format::isNumber('13.445,36', array('locale' =&gt; 'de_AT'))) {
    print "Number";
} else {
    print "not a Number";
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

