<h2>ZF-10277: Constructor code for response header analysis throws &quot;PHP Notice:  Undefined offset: 1&quot; when instanciated with header array.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-07T09:37:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-08-08T03:35:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.8 (25/Aug/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Response</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is no clear format for the header-array required. But the constructor will fail anyway because of a curious call to explode().</p>

<pre class="highlight"><code>
list($name, $value) = explode(": ", $value, 1);
</code></pre>

<p>From the PHP manual ([<a href="http://www.php.net/manual/en/function.explode.php">http://www.php.net/manual/en/function.explode.php</a>]): ??If limit is set and positive, the returned array will contain a maximum of limit elements with the last element containing the rest of string.??</p>

<p>With the limit-parameter set to one explode() will always return an array having <em>exactly one</em> element. The list-keyword on the left side of the assignment expects two elements. Thus, no matter what $value contains this will issue PHP to complaining with "Undefined offset: 1".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2010-08-08T03:35:19.000+0000</p> 
        <div class="body">
            <p>Good catch (looks like it has been a bug for years...). Fixed in trunk in r. 22810 and in release-1.10 in r. 22811. Will be included in the next release.</p>

<p>Also, added a couple of unit tests.</p>

        </div>
    </div>
    </div>

