<h2>ZF-1085: Incorrect column selection syntax for multiple colums</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-19T08:57:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The SELECT statement is not incorrectly prepared when selecting multiple columns. The problem specifically is when quoting the column names - Currently all the columns selected are quoted togather, and they should be quoted seperately.</p>

<p>For example, if I select "columns id,name,password" from table "user", the framework creates the following statement:</p>

<pre class="highlight"><code>
SELECT `user`.`id,name,password` FROM `user` 
</code></pre>

<p>which returns MySQL error 1054.</p>

<p>The columns should be quoted seperately - using the previous example:</p>

<pre class="highlight"><code>
SELECT `user`.`id`,`user`.`name`,`user`.`password` FROM `user`
</code></pre>

<p>If there's only one table to choose from, the framework should recognize this and avoid using the table name before each column to create a shorter statement, i.e:</p>

<pre class="highlight"><code>
SELECT `id`,`name`,`username` FROM `user`
</code></pre>

<p>P.S 
This bug was present in the previous release as well (0.8.0) but release 0.7.0 worked fine.
I also believe this issue relates only to MySQL 5.0 and above</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-19T11:22:59.000+0000</p> 
        <div class="body">
            <p>This is as designed.</p>

<p>You must use an array of columns, not a comma-separated list of columns in a string.</p>

        </div>
    </div>
    </div>

