<h2>ZF-10523: OAuth support for Google Apps APIs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-10-06T14:58:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Hugo Leon (hugoleon46)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Google Apps administrators had to sign requests for calls to Google Apps APIs using ClientLogin Authorization. But since September 27, 2010 Google implemented OAuth to every Google Apps API as stated in <a href="http://googlecode.blogspot.com/2010/09/new-oauth-support-for-google-apps-apis.html">http://googlecode.blogspot.com/2010/09/…</a></p>

<p>You already have some Google APIs working this way and I think that this is not a huge problem for you to get it work.</p>

<p>We have two web apps that use your framework, and some customers asked us to integrate this new feature on them. But if we do it with the Google API directly, we would have to rewrite almost everything.</p>

<p>I hope you keep this issue in mind.</p>

<p>Have a great day!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

