<h2>ZF-10137: Zend_Dojo_Form_Element_NumberTextBox - setPlaces Function converts to int</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-07-12T02:14:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-02T17:20:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mario Knippfeld (gutzuwissen)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Robert Basic (robertbasic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>e.g. I want to have the Zend_Dojo_Form_Element_NumberTextBox allow any numbers with 0 to 6 places.
in dojo you have to set the places constraint to: 0,6
That isnt possible with the Zend_Dojo_Form_Element_NumberTextBox - setPlaces Function, because it converts the given var to integer:
line 135: $this-&gt;setConstraint('places', (int) $places);</p>

<p>the (int) should be removed</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2011-04-23T16:24:32.000+0000</p> 
        <div class="body">
            <p>A range for places can be set using constraints, like:</p>

<pre class="highlight"><code>
$this-&gt;addElement(
    'NumberTextBox',
    'number',
    array(
        'label' =&gt; 'Number',
        'constraints' =&gt; array(
            'places' =&gt; '0,6'
        )
    )
);
</code></pre>

<p>I'd leave the setPlaces as is and close this as a won't fix. Thoughts?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-05-02T17:20:09.000+0000</p> 
        <div class="body">
            <p>Agreed -- since it can be done in this way, no need to change existing functionality.</p>

        </div>
    </div>
    </div>

