<h2>ZF-11080: Semantical Problem on case-insensitive filesystems</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-02-16T12:43:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-13T13:58:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.4 (03/Mar/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jorge Niedbalski (niedbalski)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Barcode</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Some case insensitive filesystems ( such as HFS+ ) can present problems with this files :</p>

<p>Zend/Validate/Barcode/UpcA.php
Zend/Validate/Barcode/Upca.php</p>

<p>On a case insentive fs this is translated to : zend/validate/barcode/upca.php ( lowercase ) , raising an exception.</p>

<p>Use cases :</p>

<p>Loading the class, svn checkout.</p>

<p>Possible solution :</p>

<p>Rename the file/class.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2011-02-16T13:13:15.000+0000</p> 
        <div class="body">
            <p>In current trunk, we only use "Upca" and never "UpcA" :
<a href="http://framework.zend.com/code/filedetails.php?repname=Zend+Framework&amp;path=%2Ftrunk%2Flibrary%2FZend%2FBarcode%2FObject%2FUpca.php">http://framework.zend.com/code/filedetails.php/…</a>
or
<a href="http://framework.zend.com/code/filedetails.php?repname=Zend+Framework&amp;path=%2Ftrunk%2Flibrary%2FZend%2FValidate%2FBarcode%2FUpca.php">http://framework.zend.com/code/filedetails.php/…</a></p>

<p>Where do you find "UpcA"?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jorge Niedbalski (niedbalski) on 2011-02-18T13:59:33.000+0000</p> 
        <div class="body">
            <p>We are using the official release of 1.11.0 Final</p>

<p><a href="http://framework.zend.com/code/log.php?repname=Zend+Framework&amp;path=%2Ftrunk%2Flibrary%2FZend%2FValidate%2FBarcode%2FUpcA.php&amp;rev=16223&amp;peg=16223">http://framework.zend.com/code/log.php/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2011-02-20T12:45:03.000+0000</p> 
        <div class="body">
            <p>The case of the filename changed with r19692 (2009-12-16: <a href="http://framework.zend.com/code/revision.php?repname=Zend+Framework&amp;path=%2Ftrunk%2Flibrary%2FZend%2FValidate%2FBarcode%2FUpca.php&amp;rev=19692&amp;peg=19692">http://framework.zend.com/code/revision.php/…</a>)</p>

<p>Delete the file on your filesystem and reimport the one from tar.gz or zip file of 1.11 release.</p>

        </div>
    </div>
    </div>

