<h2>ZF-11078: when saving blob fields, memory usage is a multiple of blob object size</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-02-16T08:06:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-16T08:06:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We're using a database table to store images as blobs.
Everything is done with Zend_Db_Table, the save function that is finally used is Zend_Db_Table_Row_Abstract::save()</p>

<p>We're tracing memory usage with php's memory_get_usage() function and write that to firebug console with the logger.
From there I can see that when saving such a row with an image sized 13.8 MB it consumes about 55 MB of memory for that operation.
It seems the the amount of memory used id quite 4 times as big as the image itself.</p>

<p>I assume the reason are all the array operations in __insert()?</p>

<p>What I found strange is that the used memory is still bigger after the save operation, compared to before the save() operation, so looks like some stuff is kept in memory?</p>

<p>I guess blobs are not a usuas use case, but maybe someone can find a way to improve that?</p>

<p>Best regards, Anton</p>

<hr /><p><a href="http://www.pixeltalents.com">http://www.pixeltalents.com</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

