<h2>ZF-11230: DST problems with Zend_Date::set() with Zend_Date::TIMES</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-27T10:39:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-01T07:43:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13927/ZF-11230.patch">ZF-11230.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Use-case:
today is 2011-03-27 and DST change has been applied at night. Timezone - Europe/Kiev</p>

<pre class="highlight"><code>
$from = new Zend_Date();
$from-&gt;set('00:00:00', Zend_Date::TIMES);
</code></pre>

<p>expected result: 
2011-03-27 00:00:00</p>

<p>actual result:
2011-03-26T23:00:00+02:00</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andrey Shevchenko (distdev) on 2011-03-27T10:44:30.000+0000</p> 
        <div class="body">
            <p>Proposed patch:</p>

<p>Zend_Date::_calculate, around line 2262 (case self::TIMES)</p>

<pre class="highlight"><code>
return $this-&gt;_assign($calc, $this-&gt;mktime($parsed['hour'], $parsed['minute'], $parsed['second'], $month, $day, $year, true),
                             $this-&gt;mktime($hour,           $minute,           $second,           $month, $day, $year, true), false);
</code></pre>

<p>change last parameter from false to $parsed['hour'], so _assign method will correct DST offset</p>

<pre class="highlight"><code>
return $this-&gt;_assign($calc, $this-&gt;mktime($parsed['hour'], $parsed['minute'], $parsed['second'], $month, $day, $year, true),
                             $this-&gt;mktime($hour,           $minute,           $second,           $month, $day, $year, true), $parsed['hour']);
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-03-27T18:38:57.000+0000</p> 
        <div class="body">
            <p>Please give a complete date output for reproduction from the created and the changed date.
Complete outputs can be created by $date-&gt;getIso() as described in the manual and the FAQ.</p>

<p>The patch is not accepted as it breaks existing tests.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andrey Shevchenko (distdev) on 2011-03-27T20:08:12.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
$from = new Zend_Date();
print $from-&gt;getIso();
</code></pre>

<p>outputs</p>

<pre class="literal"> 


and
</pre><pre class="highlight"><code>
$from-&gt;set('00:00:00', Zend_Date::TIMES);
print $from-&gt;getIso();
</code></pre>
outputs


<p>2011-03-26T23:00:00+02:00
````</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andrey Shevchenko (distdev) on 2011-04-28T11:22:55.000+0000</p> 
        <div class="body">
            <p>Could you please specify, what test was broken? I've just run it with new test, result is OK:</p>

<p>{quote}
Zend Framework
 Zend Framework - Zend
   Zend_DateTest
  ..........................................................
  ........................I.............................</p>

<p>Zend Framework - Zend_Date_Date
     Zend_Date_DateObjectTest
   ...................</p>

<p>Time: 48 seconds, Memory: 276.50Mb</p>

<p>There was 1 incomplete test:</p>

<p>1) Zend_DateTest::testTimesync
NTP timeserver not available.</p>

<p>D:\Denwer\home\zf\www\tests\Zend\DateTest.php:4973
OK, but incomplete or skipped tests!
Tests: 131, Assertions: 1868, Incomplete: 1.
{quote}</p>

<p>Unfortunately, I can't attach a patch as a file, so I attach it inline :)</p>

<pre class="highlight"><code>
Index: library/Zend/Date.php
===================================================================
--- library/Zend/Date.php   (revision 23872)
+++ library/Zend/Date.php   (working copy)
@@ -2260,7 +2260,7 @@
                     }
                     $parsed = Zend_Locale_Format::getTime($date, array('locale' =&gt; $locale, 'format_type' =&gt; 'iso', 'fix_date' =&gt; true));
                     return $this-&gt;_assign($calc, $this-&gt;mktime($parsed['hour'], $parsed['minute'], $parsed['second'], $month, $day, $year, true),
-                                                 $this-&gt;mktime($hour,           $minute,           $second,           $month, $day, $year, true), false);
+                                                 $this-&gt;mktime($hour,           $minute,           $second,           $month, $day, $year, true), $parsed['hour']);
                 } catch (Zend_Locale_Exception $e) {
                     require_once 'Zend/Date/Exception.php';
                     throw new Zend_Date_Exception($e-&gt;getMessage(), 0, $e, $date);
Index: tests/Zend/DateTest.php
===================================================================
--- tests/Zend/DateTest.php (revision 23872)
+++ tests/Zend/DateTest.php (working copy)
@@ -5669,6 +5669,17 @@
         $date = new Zend_Date(array('year' =&gt; 2008, 'month' =&gt; 10, 'day' =&gt; 12));
         $this-&gt;assertEquals('2008年10月12日', $date-&gt;get(Zend_Date::DATE_LONG, 'zh'));
     }
+   
+    /**
+     * @ZF-11230
+     */
+    public function testSetDateWithTimesPartOnDSTChange()
+    {
+        date_default_timezone_set('Europe/Kiev');
+        $date  = new Zend_Date(strtotime('2011-03-27T23:04:32+03:00'));
+        $date-&gt;set('00:00:00', Zend_Date::TIMES);
+        $this-&gt;assertEquals('2011-03-27T00:00:00+02:00', $date-&gt;getIso());
+    }
 }
 
 class Zend_Date_TestHelper extends Zend_Date
</code></pre>

        </div>
    </div>
    </div>

