<h2>ZF-1009: Zend_Date doc render error in German docs.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-03-02T17:46:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T18:32:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The file Zend_Date-Introduction.xml does not render.</p>

<pre class="highlight"><code>
/usr/bin/xsltproc --xinclude --output html/index.html html.xsl manual.xml
module_specs/Zend_Date-Introduction.xml:11: parser error : Opening and ending tag mismatch: 
ulink line 10 and para
    
           ^
module_specs/Zend_Date-Introduction.xml:131: parser error : Opening and ending tag mismatch: 
para line 5 and sect1

        ^
module_specs/Zend_Date-Introduction.xml:135: parser error : Premature end of data in tag sect1 line 1

^
manual.xml:91: element include: XInclude error : could not load module_specs/Zend_Date-Introduction.xml, 
and no fallback was found
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-03-03T03:24:01.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN 3713</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T18:32:40.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

