<h2>ZF-1671: explain how to change font color</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-07-02T13:55:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-19T11:50:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Long (phareous)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13423/ZF-1671.patch">ZF-1671.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The PDF docs don't really explain how to set font color. It appears the only way to do it is to create a new Style, and then set the font and color that way, as in:</p>

<pre class="highlight"><code>
$style = new Zend_Pdf_Style();
$style-&gt;setFillColor(new Zend_Pdf_Color_HTML('#000077'));
$style-&gt;setFont(Zend_Pdf_font::fontWithName(Zend_pdf_font::FONT_HELVETICA),10);
$page-&gt;setStyle($style);
</code></pre>

<p>It might also be helpful to modify the color section of the manual to explicitly list where color can be used (i.e. within a style object, and not in a page object, etc.)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2007-09-26T20:17:44.000+0000</p> 
        <div class="body">
            <p>As with any other PDF drawing operations, text is drawn using the current fill color of the content stream's (page's) graphic state:</p>

<pre class="highlight"><code>
$page-&gt;setFillColor(new Zend_Pdf_Color_Rgb(1, 0, 0));  // red
</code></pre>

<p>{{Zend_Pdf_Style}} objects allow you to set multiple attributes of the graphics state at once, but are not required.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-25T16:53:30.000+0000</p> 
        <div class="body">
            <p>Does this information belong in the reference guide? If so, could you please add it or reassign to Alex, Willie? Otherwise resolve it as 'not an issue'. Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Willie Alberty (willie) on 2008-11-25T16:55:42.000+0000</p> 
        <div class="body">
            <p>Assigning to Alexander for documentation update.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-05T01:11:02.000+0000</p> 
        <div class="body">
            <p>Patch to documentation attached.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-19T11:50:54.000+0000</p> 
        <div class="body">
            <p>Patch applied to trunk in r23406, merged to 1.11 release branch in r23407</p>

        </div>
    </div>
    </div>

