<h2>ZF-1561: Wrong returned result in comparison to Luke toolbox</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-14T02:56:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 (30/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <h2>The problem is originaly reported by David in <a href="http://framework.zend.com/wiki/display/ZFMLGEN/mail/32869">ZF-General</a>:</h2>

<p>My question is about the zend_search_lucene. I have searched the index with
below:</p>

<p>"business controller"  AND shanghai</p>

<p>There is about 300 hits. But when I search with LUKE Toolbox again with the
same phrase string, there is about only 7 results, and that is correct for
my case.  And, there is only 14 documents in my index containing "business
controller"  phrase.</p>

<p>I need to know why the Luke toolbox's results is not the same with
zend_search_lucence. Is there some configuration needed? I use the Zend
1.0.0 RC1, and my demo script is below:</p>

<pre class="highlight"><code>
&lt;?php
require_once 'Zend/Search/Lucene.php';
$query = "\"business controller\" AND Shanghai";
//Zend_Search_Lucene_Analysis_Analyzer::setDefault(new
Zend_Search_Lucene_Analysis_Analyzer_Common_TextNum_CaseInsensitive());
//Zend_Search_Lucene_Search_QueryParser::setDefaultOperator(Zend_Search_Lucene_Search_QueryParser::B_AND);
$index = Zend_Search_Lucene::open('index');
$hits = $index-&gt;find($query);
echo "result:".count($hits);
?&gt;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-06-14T03:00:04.000+0000</p> 
        <div class="body">
            <p>```
should give the same result for Zend_Search_Lucene and Apache (Java) Lucene.</p>

<p>But it didn't help: [<a href="http://framework.zend.com/wiki/display/ZFMLGEN/mail/33168">http://framework.zend.com/wiki/display/…</a>]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-06-14T13:38:40.000+0000</p> 
        <div class="body">
            <p>Fixed.</p>

        </div>
    </div>
    </div>

