<h2>ZF-12105: Router Regex Inheritance</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-03-19T14:43:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-04T13:17:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rudolf Leye (rleye)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller_Router</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>After creating a subclass of Router_Regex, I noticed the route was not used:</p>

<p>Definition in Router_Regex:</p>

<pre class="highlight"><code>
public static function getInstance(Zend_Config $config)
{
    $defs = ($config-&gt;defaults instanceof Zend_Config) ? $config-&gt;defaults-&gt;toArray() : array();
    $map = ($config-&gt;map instanceof Zend_Config) ? $config-&gt;map-&gt;toArray() : array();
    $reverse = (isset($config-&gt;reverse)) ? $config-&gt;reverse : null;
    return new self($config-&gt;route, $defs, $map, $reverse);
}
</code></pre>

<p>I thing the last line should be replaced by</p>

<pre class="highlight"><code>
return new static($config...) 
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

