<h2>ZF-10211: Zend_Json_Server unable to pass objects</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-07-23T08:34:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kevin Schroeder (kschroeder)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13227/patch.txt">patch.txt</a></li>
            <li><a href="/issues/secure/attachment/13225/patch.txt">patch.txt</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Json_Server cannot handle objects that are returned from a result.  So if a mapper returns an object it ends up not getting serialized.  This patch will check to see if it's an object (or array of objects), check to see if it has a toArray() method and calls it, or casts it to (array) if toArray() doesn't exist.</p>

<p>Patch for library/Zend/Json/Server/Response.php:
181d180
&lt;             $result = $this-&gt;_convertObjectToArray($this-&gt;getResult());
183c182</p>

<h2>&lt;                 'result' =&gt; $result,</h2>

<blockquote>
<pre><code>            'result' =&gt; $this-&gt;getResult(),
</code></pre>
  
  <p>196,211d194
  &lt;<br />
  &lt;     protected function _convertObjectToArray($object)
  &lt;     {
  &lt;         if (is_object($object)) {
  &lt;               if (method_exists($object, 'toArray')) {
  &lt;                   $object = $object-&gt;toArray();
  &lt;               } else {
  &lt;                   $object = (array)$object;
  &lt;               }
  &lt;         } else if (is_array($object)) {
  &lt;             foreach ($object as $key =&gt; $value) {
  &lt;                 $object[$key] = $this-&gt;_convertObjectToArray($value);
  &lt;             }
  &lt;         }
  &lt;         return $object;
  &lt;     }
  268d250
  &lt;</p>
</blockquote>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kevin Schroeder (kschroeder) on 2010-07-23T10:44:52.000+0000</p> 
        <div class="body">
            <p>Non-mangled patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kevin Schroeder (kschroeder) on 2010-07-23T11:25:01.000+0000</p> 
        <div class="body">
            <p>Actually, scratch this.  I have a new patch that works combining issue <a href="http://framework.zend.com/issues/browse/ZF-10213">http://framework.zend.com/issues/browse/ZF-10213</a>.  Patch forthcoming.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kevin Schroeder (kschroeder) on 2010-07-23T11:26:14.000+0000</p> 
        <div class="body">
            <p>Patch added to Zend_Json_Server that works with issue <a href="http://framework.zend.com/issues/browse/ZF-10213">http://framework.zend.com/issues/browse/ZF-10213</a></p>

        </div>
    </div>
    </div>

