<h2>ZF-11218: Use statements are ignored in CodeGenerator\Php\PhpFile</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-23T17:33:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-23T21:16:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_CodeGenerator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend\CodeGenerator\Php\PhpFile in ZF2 allows you to define use statements (with aliases, even!) with "setUse()" and "setUses()". However, when generating the actual file, these values are never used.</p>

<pre class="highlight"><code>
$file = new PhpFile();
$file-&gt;setUse("Foo\Bar\Baz");
echo $file-&gt;generate();
</code></pre>

<p>I'd expect the output to contain:</p>

<pre class="highlight"><code>
use Foo\Bar\Baz;
</code></pre>

<p>However, no such line occurs.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-03-23T21:16:10.000+0000</p> 
        <div class="body">
            <p>A fix for this, and generation of a file-level namespace declaration, are in ZF2 git master.</p>

        </div>
    </div>
    </div>

