<h2>ZF-11272: Zend_Controller_Router not working with Zend_Translate translations with underscore characters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-04-07T20:07:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-16T21:55:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Grodzicki (sgrodzicki)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller_Router</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Consider the following Bootstrap file:</p>

<pre class="highlight"><code>
&lt;?php
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
    protected function _initRouting()
    {
        $this-&gt;bootstrap('frontController');
        
        $front  = $this-&gt;getResource('frontController');
        $router = $front-&gt;getRouter();
        $route  = new Zend_Controller_Router_Route(
            ':@country/:@slug', 
            array(
                'controller'    =&gt; 'index',
                'action'        =&gt; 'index',
                'slug'          =&gt; '',
            ), 
            array(
//              'country'       =&gt; '(France|Germany|Poland)',       // Working
                'country'       =&gt; '(_France|_Germany|_Poland)',    // Not working
                'slug'          =&gt; '[A-Za-z\d\-]+',
            )
        );
        
        $router-&gt;removeDefaultRoutes();
        $router-&gt;addRoute('sample', $route);
    }
    
    protected function _initTranslate ()
    {
        $this-&gt;bootstrap('Routing');
        
        $translator = new Zend_Translate(
            array(
                'adapter'   =&gt; 'array',
                'content'   =&gt; array(
//                  'France'    =&gt; 'Francja',   // Working
//                  'Germany'   =&gt; 'Niemcy',    // Working
//                  'Poland'    =&gt; 'Polska',    // Working
                    '_France'   =&gt; 'Francja',   // Not working
                    '_Germany'  =&gt; 'Niemcy',    // Not working
                    '_Poland'   =&gt; 'Polska',    // Not working
                ),
                'locale'    =&gt; 'pl',
            )
        );
        
        $translator-&gt;setLocale('pl');

        Zend_Controller_Router_Route::setDefaultTranslator($translator);
    }
}
</code></pre>

<p>and the following URL:</p>

<p><a href="http://localhost/public/Niemcy/Niemcy">http://localhost/public/Niemcy/Niemcy</a></p>

<p>The problem always occurs when the key has an underscore so it can also be:</p>

<p>"under_score_France", "__France" and so on.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-04-16T21:55:47.000+0000</p> 
        <div class="body">
            <p>Detaching Zend_Translate from the affected components as it's no problem from this component</p>

        </div>
    </div>
    </div>

