<h2>ZF-10326: An easy way to log any SQL query in a specified logfile</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-08-17T06:30:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mathieu Decaffmeyer (mathi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
            <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be nice to have a simple way to have all the SQL query strings that have been executed, in a logfile which you could specify. Additionally, be able to activate in an easy way the profiler for each SQL query. So each log would include the SQL query string and possibly the profiling of that query.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Konr Ness (konrness) on 2010-09-02T22:33:36.000+0000</p> 
        <div class="body">
            <p>I'd be interested in working on this feature.</p>

<p>It would likely be Zend_Db_Profiler_Log and use Zend_Log for the writing. This way, it could be used for outputting via any number of log writers. Interestingly, this method could likely invalidate the need for Zend_Db_Profiler_Firebug since Zend_Log already has a firebug writer.</p>

<p>Perhaps this should have a proposal written up for it.</p>

        </div>
    </div>
    </div>

