<h2>ZF-1490: Mime Message Generation is not generic/flexible</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-06-04T14:39:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Florian Hoenig (flo)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mime</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I've been using Zend_Mime to generate MM7 messages for MMS distribution and encountered that the module lacks genericness and is very specific to Email.</p>

<p>1) $body = 'This is a message in Mime Format.  If you see this, '
                  . "your mail reader does not support this format." . $EOL;</p>

<p>Why should a generic MIME message be tied to Email? IMO, this line should be removed.</p>

<p>2)  Mime_Message::generateMessage does not generate the multipart header info for the overall message. This is missing too.</p>

<p>3) I have seen this issue in the mailing lists before, but there should be an interface to create nested, generic mime messages.</p>

<p>4) Separation of Zend_Mime and Zend_Mime_Message is unclear.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-07T11:22:55.000+0000</p> 
        <div class="body">
            <p>Assign to Nico.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nico Edtinger (nico) on 2007-06-10T07:24:48.000+0000</p> 
        <div class="body">
            <p>Depends on merging with Zend_Mail_Message, which is planed after 1.0</p>

<p>ad 1)
This message will only be displayed by "clients" (programs, ...), that unterstand the mail message format (RFC 822), but not MIME. AFAIK only old or very minimal mail clients do this. MMS clients, et cetera should ignore it - it's called discard-text in RFC 2046.</p>

<p>ad 3)
It is possible to create nested multipart messages. But it seems it's not so clear how. This will be fixed with the merge with Zend_Mail_Message.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-11T21:33:47.000+0000</p> 
        <div class="body">
            <p>It seems to be one of issues for next major release (2.0) for me :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:39.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

