<h2>ZF-10658: Typo in Zend_Http_UserAgent</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-11-08T07:14:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-08T08:08:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It's</p>

<p>chmod -R o+rwX data/worful/cache</p>

<p>It should be</p>

<p>chmod -R o+rwX data/wurfl/cache</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-11-08T08:08:10.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.11 release branch.</p>

        </div>
    </div>
    </div>

