<h2>ZF-12155: Zend_Reflection_File doesn't handle complex parsed variable syntax properly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-16T03:58:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-14T12:47:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Reflection</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-301">ZF2-301</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15102/ZF-12155_fix.patch">ZF-12155_fix.patch</a></li>
            <li><a href="/issues/secure/attachment/15101/ZF-12155_test.patch">ZF-12155_test.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Reflection_File::_reflect() doesn't handle T_CURLY_OPEN | T_DOLLAR_OPEN_CURLY_BRACES as $openBraces given a parsing error.</p>

<p>I fixed the problem adding:</p>

<p>class: Zend_Reflection_File
339: switch ($type) {
340:   // Special curly open situations
341:   case T_CURLY_OPEN | T_DOLLAR_OPEN_CURLY_BRACES :
342:     $openBraces++;
343:     continue;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-08T19:29:50.000+0000</p> 
        <div class="body">
            <p>Can you provide a sample of code which causes Zend_Reflection_File to misbehave?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Facundo Cabrera (facundo) on 2012-05-09T11:17:39.000+0000</p> 
        <div class="body">
            <p>function test ( ) { 
  $hello = 'hello';
  $world = 'world';</p>

<p>$phrase = "{$hello} {$world}";
}</p>

<p>function test2 () {
  // you wont see this function after parsing because {$ doesn't match a common { but } does.
}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-14T11:28:16.000+0000</p> 
        <div class="body">
            <p>Attached reproducing unit test</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-14T12:19:52.000+0000</p> 
        <div class="body">
            <p>Attached fix and updated test</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-14T12:24:05.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk (1.12.0):  r24803</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-14T12:41:58.000+0000</p> 
        <div class="body">
            <p>No ZF2 PR issued, as this feature is incomplete in ZF2.  See: <a href="https://github.com/zendframework/zf2/blob/fa6f1df3b2d60380ac2bf6e5a4c0b39688ba8210/library/Zend/Code/Scanner/FunctionScanner.php">https://github.com/zendframework/zf2/…</a></p>

        </div>
    </div>
    </div>

