<h2>ZF-10743: calling addResource(resource) after calling allow(role, null) does not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-25T00:19:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-27T12:46:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Acl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10649">ZF-10649</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$acl = new Zend_Acl();
$acl
    -&gt;addRole('role')
    -&gt;addResource('a')
    -&gt;allow('role')
    -&gt;addResource('b')
    ;<br />
var_dump($acl-&gt;isAllowed('role', 'a', 'action')); // bool(true)
var_dump($acl-&gt;isAllowed('role', 'b', 'action')); // bool(false) (in Zend 1.10 returns true as expected)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-27T12:46:29.000+0000</p> 
        <div class="body">
            <p>Duplicates of ZF-10649.</p>

        </div>
    </div>
    </div>

