<h2>ZF-1336: Change Table::fetchNew() method to createRow(), deprecate fetchNew()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-05-01T12:39:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Db_Table::fetchNew() method is named in a confusing way.  After discussing it on the community mailing list, would be better to name it createRow().  Please make this change.</p>

<p>Make the old fetchNew() method proxy to the new createRow() method.  No need to remove the old method, it would break backward compatibility needlessly.</p>

<p>Document the createRow() method, and remove mention of the fetchNew() method.</p>

<p>Update unit tests.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-01T13:35:39.000+0000</p> 
        <div class="body">
            <p>Implemented code and unit test changes in revisions 4643, 4644.</p>

<p>Still need to change documentation.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-01T15:41:50.000+0000</p> 
        <div class="body">
            <p>Documentation changes committed in revision 4651.</p>

        </div>
    </div>
    </div>

