<h2>ZF-11081: Wrong item numbering with Zend_Paginator over Zend_Mail</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2011-02-16T14:51:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-05T11:29:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Helmuth Gronewold (hjjg)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi!</p>

<p>I'm trying to use pagination in my email listing. 
There are 52 items in my mailbox. On the first page it numbers from 1 to 10, but on the second page the listing starts with 10 again and goes up to 19. 20 to 29 on the following page and so on. Everything is fine without pagination. The items are correctly displayed with the numbers 1 to 52.</p>

<p>This is the code I'm using:</p>

<pre class="highlight"><code>
$mail = new Zend_Mail_Storage_Imap(array('host'     =&gt; 'host',
                                         'user'     =&gt; 'user',
                                         'password' =&gt; 'pass',
                     'ssl' =&gt; 'TLS'));

$this-&gt;view-&gt;number_messages = count($mail);
    
$paginator = new Zend_Paginator(new Zend_Paginator_Adapter_Iterator($mail));
$paginator-&gt;setCurrentPageNumber((int) $this-&gt;getRequest()-&gt;getParam('page'));
$this-&gt;view-&gt;mail = $paginator;
</code></pre>

<pre class="highlight"><code>
</code></pre><div><code>
&lt;?php foreach ($this-&gt;mail as $messageNum =&gt; $message): ?&gt; 
    </code><p><code>&lt;?=$messageNum?&gt;: &lt;?=$message-&gt;subject ?&gt;</code></p><code>
&lt;?php endforeach; ?&gt;
</code></div><code>

&lt;?php echo $this-&gt;paginationControl($this-&gt;mail, 'Sliding', 'my_pagination_control.phtml'); ?&gt;
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-18T00:53:10.000+0000</p> 
        <div class="body">
            <p>Components changed. It relates to Zend_Paginator and not Zend_Navigation.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Helmuth Gronewold (hjjg) on 2011-07-03T21:12:03.000+0000</p> 
        <div class="body">
            <p>Not fixed in trunk. Maybe it's a workaround but this does the job:</p>

<h1>Index: Mail/Storage/Abstract.php</h1>

<p>--- Mail/Storage/Abstract.php   (Revision 24182)
+++ Mail/Storage/Abstract.php   (Arbeitskopie)
@@ -360,7 +360,7 @@
         if ($pos &gt; $this-&gt;_iterationMax) {
             throw new OutOfBoundsException('this position does not exist');
         }
-        $this-&gt;_iterationPos = $pos;
+        $this-&gt;_iterationPos = $pos + 1;
      }</p>

<p>}</p>

<p>If I use the iterator with foreach, Zend_Mail_Storage_Abstract-&gt;valid() is called twice for the first page. I can't say if this is normal behaviour.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Helmuth Gronewold (hjjg) on 2011-07-05T11:29:26.000+0000</p> 
        <div class="body">
            <p>My last comment fixed the problem for me. I can't see any problems with that. Someone should review this.</p>

        </div>
    </div>
    </div>

