<h2>ZF-11471: bootstrap fails to interpret route</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-13T09:41:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-13T09:49:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                John Worthington (jhworth)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Route</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>My application works fine on XAMPP on the local host.</p>

<p>In moving it to a host with Redhat 6.0, the bootstrap breaks on _initRoutes().</p>

<p>The result is .htaccess is ignored and route not found.</p>

<p>I find suggestions to modify vhost.conf as follows:</p>

<p>
Order Allow Deny
Allow form All
  AllowOverride All
Include /var/www/vhosts/myhorseclinics.com/httpsdocs/public/.htaccess
</p>

<p>This change has no effect.</p>

<p>What am I missing?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2011-06-13T09:49:30.000+0000</p> 
        <div class="body">
            <p>Closing this as it appears to be as support request and not an issue.</p>

<p>Please direct support requests to #zftalk on irc, or the fw-general mailing list.</p>

<p>It is quite possible that overrides are not allowed by default on your new server so your update in the vhost.conf would be required.</p>

<p>the name _initRoutes could be conflicting with and routes defined in your config, but without code examples to back it up, it is impossible to know. This could also be a nameing case issue, as you appear to be moving from a case insensitive file system, to a case sensitive one.</p>

        </div>
    </div>
    </div>

