<h2>ZF-12240: remove unused $_logger  member in Zend_Queue</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-05-23T12:27:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-23T12:27:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Justin Plock (jplock)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Queue</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think it was not removed since incubator's code.</p>

<p>I alreay PullRequest to zf2
<a href="https://github.com/zendframework/zf2/pull/1339">https://github.com/zendframework/zf2/pull/1339</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

