<h2>ZF-12357: Typo in navigation links helper docs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2012-08-02T13:41:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-07T20:13:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.1 (18/Dec/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
            <li>FixForZF1.12.1</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15181/de.Zend_View-Helpers-Navigation.xml.patch">de.Zend_View-Helpers-Navigation.xml.patch</a></li>
            <li><a href="/issues/secure/attachment/15180/en.Zend_View-Helpers-Navigation.xml.patch">en.Zend_View-Helpers-Navigation.xml.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{quote}
Zend_View_Helper_Navigation_Link::RENDER_ALTERNATE
{quote}
"s" in {{Links}} is missing!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-08-02T13:43:55.000+0000</p> 
        <div class="body">
            <p>Patches for English and German added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-07T20:13:29.000+0000</p> 
        <div class="body">
            <p>Applied patch to trunk (25096) and release-1.12 (25097)</p>

        </div>
    </div>
    </div>

