<h2>ZF-1023: Response::prependBody()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-03-08T13:34:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1024">ZF-1024</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be nice to have prependBody() to complement the existing appendBody().
This helps reduce the total code needed in the bootstrap for prepending a header,
such as headers that depend on the results of the action dispatched.</p>

<p>Example: prepending a doctype tag or an xml tag.</p>

<pre class="highlight"><code>
Index: tests/Zend/Controller/Response/HttpTest.php
===================================================================
--- tests/Zend/Controller/Response/HttpTest.php (revision 3840)
+++ tests/Zend/Controller/Response/HttpTest.php (working copy)
@@ -134,6 +134,16 @@
         $this-&gt;assertEquals($expected . $additional, $this-&gt;_response-&gt;getBody());
     }

+    public function testPrependBody()
+    {
+        $expected = 'content for the response body';
+        $this-&gt;_response-&gt;setBody($expected);
+
+        $additional = '; and then there was more';
+        $this-&gt;_response-&gt;prependBody($additional);
+        $this-&gt;assertEquals( $additional . $expected, $this-&gt;_response-&gt;getBody());
+    }
+
     public function test__toString()
     {
         $skipHeadersTest = headers_sent();
Index: library/Zend/Controller/Response/Abstract.php
===================================================================
--- library/Zend/Controller/Response/Abstract.php       (revision 3840)
+++ library/Zend/Controller/Response/Abstract.php       (working copy)
@@ -316,6 +316,18 @@
     }

     /**
+     * Prepend content to the body content
+     *
+     * @param string $content
+     * @return Zend_Controller_Response_Abstract
+     */
+    public function prependBody($content)
+    {
+        array_unshift($this-&gt;_body, (string) $content);
+        return $this;
+    }
+
+    /**
      * Return the body content
      *
      * @param boolean $asArray Whether or not to return the body content as an
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-03-09T14:49:42.000+0000</p> 
        <div class="body">
            <p>You can do this with a workaround already:</p>

<pre class="highlight"><code>
$body = $request-&gt;getBody();
$request-&gt;setBody($header);
$request-&gt;appendBody($body);
</code></pre>

<p>I prefer the named segments issue/proposal you already brought up for this sort of thing, but I'll think on it some more.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-03-09T15:10:36.000+0000</p> 
        <div class="body">
            <p>Yes, I agree on both counts.</p>

<p>However, getBody() has a side-effect of merging array elements - unecessary step and not performanc-friendly ;)</p>

<p>If there is not enough time for the segments issue/proposal, I was hoping this tiny addition would make it into ZF 0.9, but I also prefer the segment naming approach.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-15T13:33:19.000+0000</p> 
        <div class="body">
            <p>Assign Zend_Controller issues to Matthew.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-03-15T13:43:32.000+0000</p> 
        <div class="body">
            <p>This patch is superseded by ZF-1024.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-03-15T13:45:07.000+0000</p> 
        <div class="body">
            <p>This proposed patch was a much simpler approach than ZF-1024, and was proposed in the even that ZF-1024 could not be implemented in time for ZF 0.9.</p>

<p>Since a patch has been committed for ZF-1024, this issue is no longer relevant.</p>

        </div>
    </div>
    </div>

