<h2>ZF-11730: Incorrect method name in title - Using the static staticFilter() method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-09-09T13:58:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-15T08:24:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The title of the section "Using the static staticFilter() method" is incorrect as the actual method discussed is filterStatic().  I'd argue minor rather than trivial as some people may skim through the documentation for the name of a method they cannot remember and not read the entire paragraph.</p>

<p>Also, and this may be a different issue, why does it need a different name from the non-static method?  Can the method not be written to work out if it is being called from an instantiated class or not - ala singleton pattern and either behave as static or not as needed?  I can't see any reason for the 'static' naming convention in the ZF coding standards.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-09-09T14:16:09.000+0000</p> 
        <div class="body">
            <p>Commenting only on your second paragraph.</p>

<p>In PHP4, it was possible to call a method both statically and as an instance method, and test for $this. In PHP5, the only way for a method to be static is to declare it as such from the outset. Additionally, when calling a static method from an object instance, $this remains unset. As an example, try the following:</p>

<pre class="highlight"><code>
class Foo                                                                       
{                                                                               
    protected $seed;                                                            
                                                                                
    public function __construct($seed)                                          
    {                                                                           
        $this-&gt;seed = $seed;                                                    
    }                                                                           
                                                                                
    public static function filter($value)                                       
    {                                                                           
        if (!isset($this)) {                                                    
            return strtoupper($value);                                          
        }                                                                       
                                                                                
        return strtoupper($this-&gt;seed . ' ' . $value);                          
    }                                                                           
}                                                                               
$f = new Foo('I say');                                                          
echo $f-&gt;filter('boo');
</code></pre>

<p>The result will still be "BOO". As such, you lose access to any state you might have set in the object.</p>

<p>Because many filters may depend on state (e.g. locale settings, configuration that alters behavior, etc.), Zend_Filter_Interface thus defines filter() as a public, non-static method. Even for filters that do not need state, in order to adhere to the interface, they need to declare the method non-static.</p>

<p>Finally, the Zend_Filter class itself serves two purposes. One is to provide filter chain capabilities -- and that is what the filter() method of that class is for (it iterates through all attached filters, passing the return value of one to the next until done).</p>

<p>The second purposes is where filterStatic() comes in; its purpose is for doing one-off filtering on a single line:</p>

<pre class="highlight"><code>
$filtered = Zend_Filter::filterStatic('boo', 'StringToUpper', array('encoding' =&gt; 'utf-8'));
echo $filtered; // 'BOO'
</code></pre>

<p>As such, the difference in naming is by design.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nick (uberteck) on 2011-09-10T09:57:17.000+0000</p> 
        <div class="body">
            <p>Thanks for the detail - makes total sense.  I was thinking in PHP4 terms where you declare filter() as a non-static method then the following works as expected and is perfectly valid (according to PHP4 docs on paamayim-nekudotayim, but not PHP5 docs):</p>

<pre class="highlight"><code>
echo Foo::filter('boo');
?&gt;<br />&lt;?php
$f = new Foo('I say');
echo $f-&gt;filter('boo');
</code></pre>

<p>FYI for anyone that tries this in PHP5 - calling a non-static method statically still works (according to various php bug reports this behaviour will be kept in for backward compatibility purposes) but certainly isn't good practice - sure enough it throws up a 'php Non-static method <em>method()</em> should not be called statically on line <em>#</em>' E_STRICT warning.  Thinking about it - it seems odd this was possible with PHP4 in the first place as it isn't in any other OOP language I am familiar with.  The fact that you can access a $this (from parent) within a static method in PHP5 if the class is inherited only adds to the confusion.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-15T08:24:50.000+0000</p> 
        <div class="body">
            <p>Fixed in ZF2 with <a href="https://github.com/zendframework/zf2/pull/414">GH-414</a></p>

        </div>
    </div>
    </div>

