<h2>ZF-10459: Zend_Navigation_Container-&gt;removePage() should have option to remove page recursively</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-09-15T13:29:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-03-13T20:55:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Mini Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9994">ZF-9994</a></li>
            <li><a href="/issues/browse/ZF-10641">ZF-10641</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-03-20T17:16:54.000+0000</p> 
        <div class="body">
            <p>I don't understand your problem. Can you give an example?</p>

<pre class="highlight"><code>
// Navigation
$container = new Zend_Navigation(array(
    array(
        'label' =&gt; 'Home',
        'uri'   =&gt; 'home',
    ),
    array(
        'label' =&gt; 'Products',
        'uri'   =&gt; 'products',
        'pages' =&gt; array(
            array(
                'label' =&gt; 'DVD',
                'uri'   =&gt; 'dvd',
            ),
            array(
                'label' =&gt; 'Games',
                'uri'   =&gt; 'games',
            ),
            array(
                'label' =&gt; 'Music',
                'uri'   =&gt; 'music',
            ),
        ),
    ),
    array(
        'label' =&gt; 'Contact',
        'uri'   =&gt; 'contact',
    ),
    array(
        'label' =&gt; 'imprint',
        'uri'   =&gt; 'imprint',
    ),
));

// View
$view = new Zend_View();

echo '</code></pre><h1><code>Output 1:</code></h1><code>';
echo $view-&gt;navigation($container)-&gt;menu();

// Remove page "Products"
$container-&gt;removePage(1);

echo '</code><h1><code>Output 2:</code></h1><code>';
echo $view-&gt;navigation($container)-&gt;menu();
</code>

<pre class="highlight"><code>
</code></pre><h1><code>Output 1:</code></h1><code>
</code><code>
        <a href="home">Home</a>
    
    
        <a href="products">Products</a>
        </code><code>
                <a href="dvd">DVD</a>
            
            
                <a href="games">Games</a>
            
            
                <a href="music">Music</a>
            
        
    
        <a href="contact">Contact</a>
    
    
        <a href="imprint">imprint</a>
    
</code><h1><code>Output 2:</code></h1><code>
</code><code>
        <a href="home">Home</a>
    
    
        <a href="contact">Contact</a>
    
    
        <a href="imprint">imprint</a>
    
</code>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-06-09T07:13:33.000+0000</p> 
        <div class="body">
            <p>Hi Jiri,
Any comments on this?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jiri Havlik (havlikjiri) on 2011-06-09T07:53:38.000+0000</p> 
        <div class="body">
            <p>Hi Kai,</p>

<p>my problem is that it is not possible to remove pages in subcontainers. Eg. page DVD cant be deleted by calling something like $container-&gt;removePageByUri(dvd, true); Where "true" means Search all containers recursively. You have to get the right container first and then delete your page.</p>

<p>I think that it would be nice to have a function which searches all containers recursively for page given to delete.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-06-09T08:41:10.000+0000</p> 
        <div class="body">
            <p>Ah, I understand.</p>

<p>|findOneBy|removeOneBy|
|findAllBy|removeAllBy|
|findBy|removeBy|</p>

<p>I think for the implementation, we can use all "find" methods.</p>

<pre class="highlight"><code>
public function removeOneBy($property, $value)
{
    $page = $this-&gt;findOneBy($property, $value);
    
    if (null !== $page) {
        return $this-&gt;removePage($page);
    }
    
    return false;
}

public function removeAllBy($property, $value)
{
    $pages = $this-&gt;findAllBy($property, $value);
    
    if (false !== empty($pages)) {
        foreach ($pages as $page) {
            $this-&gt;removePage($page);
        }
        
        return true
    }
    
    return false;
}

public function removeBy($property, $value, $all = false)
{
    if ($all) {
        return $this-&gt;removeAllBy($property, $value);
    } else {
        return $this-&gt;removeOneBy($property, $value);
    }
}
</code></pre>

<p>I will write some unit test.</p>

<p>Thanks for your fast feedback!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2011-09-23T08:15:28.000+0000</p> 
        <div class="body">
            <p>Based on the new filter options ({{useRegex}}). See ZF-9994</p>

        </div>
    </div>
    </div>

