<h2>ZF-11470: InfoCard XmlParsingTest has Invalid fail-testcase</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2011-06-11T00:18:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-13T23:46:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_InfoCard</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>InfoCard's XmlParsingTest has below's code.</p>

<pre class="highlight"><code>
 public function testKeyInfo() {
    try {
        Zend_InfoCard_Xml_KeyInfo::getInstance("");
        $this-&gt;fail("Expected Exception Not thrown"); 
    } catch(Exception $e) {
     /* yay */
    }
</code></pre>

<p>Zend_InfoCard_Xml_KeyInfo::getInstance() method will not throw Exception, if string is as argument?</p>

<p>Please evaluate this above testcase.
Is "" valid for KeyInfo?(sorry, I can't judge.)</p>

<p>If "" is valid ,please write assert-testcase for "", and write remove failmethod above.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-13T23:45:50.000+0000</p> 
        <div class="body">
            <p>The method actually checks for an XML DSig namespace in the given XML string later on and throws an Exception if not found. The test description sucks, but I think that's what it's verifying. Marking as a non-issue as a result.</p>

<p>Thanks for taking the time to report it though!</p>

        </div>
    </div>
    </div>

