<h2>ZF-109: Update website info. for CLA submission, and mail lists (announce, unsubscribe, etc.) (TRAC#122 gavin)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2006-06-21T22:01:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.5 (11/Jul/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jayson Minard (jayson)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/developer/ticket/122">http://framework.zend.com/developer/ticket/122</a></p>

<p>need to update text copy, etc.</p>

<p>{quote}
06/06/06 13:16:51: Modified by gavin</p>

<pre><code>* type changed from defect to task.
</code></pre>

<p>06/06/06 13:16:59: Modified by gavin</p>

<pre><code>* status changed from new to assigned.
</code></pre>

<p>{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jayson Minard (jayson) on 2006-07-09T00:27:29.000+0000</p> 
        <div class="body">
            <p>any remaining changes can easily be done in the wiki, we have most content covered completely now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jayson Minard (jayson) on 2006-07-11T11:54:37.000+0000</p> 
        <div class="body">
            <p>0.1.5 released</p>

        </div>
    </div>
    </div>

