<h2>ZF-10955: Pie: Exeption thrown if angle to small</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-17T02:22:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-17T02:23:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                André Schade (waswrongassembled)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by André Schade (waswrongassembled) on 2011-01-17T02:23:42.000+0000</p> 
        <div class="body">
            <h1>Index: com.ipoque.ims/library/Zend/Pdf/Page.php</h1>

<p>diff -u -N -rfcae7a01e0fad5a27ec93bf6005ba233ba724d9b -rf0ac6f0b810b3ea734dfaf981dd172a52732cb2b</p>

<pre class="literal"> 
--- com.ipoque.ims/library/Zend/Pdf/Page.php    (.../Page.php)  (revision fcae7a01e0fad5a27ec93bf6005ba233ba724d9b)
+++ com.ipoque.ims/library/Zend/Pdf/Page.php    (.../Page.php)  (revision f0ac6f0b810b3ea734dfaf981dd172a52732cb2b)
@@ -1179,7 +1179,11 @@
             $clipRadius  = max($x2 - $x1, $y2 - $y1);
 
             for($count = 0; $count &lt;= $clipSectors; $count++) {
-                $pAngle = $startAngle + ($endAngle - $startAngle)*$count/(float)$clipSectors;
+               if($clipSectors &gt; 0) {
+                   $pAngle = $startAngle + ($endAngle - $startAngle)*$count/(float)$clipSectors;
+               } else {
+                   $pAngle = 0;
+               }
 
                 $pX = new Zend_Pdf_Element_Numeric($x + cos($pAngle)*$clipRadius);
                 $pY = new Zend_Pdf_Element_Numeric($y + sin($pAngle)*$clipRadius);
</pre>

        </div>
    </div>
    </div>

