<h2>ZF-11206: Zend uri trows a fatal error when a % is used in the get</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-22T13:28:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-30T03:20:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Erik Maas (reefclaw)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Uri</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This throws a fatal error on urls containing a % inside the get.
Like:</p>

<p><a href="http://www.mysite.com/index.php?page">http://www.mysite.com/index.php?page</a>=%
<a href="http://www.mysite.com/index.php?page=%25g">http://www.mysite.com/index.php?page=%g</a>
<a href="http://www.mysite.com/index.php?%25=page">http://www.mysite.com/index.php?%=page</a>
<a href="http://www.mysite.com/index.php?pa%25ge">http://www.mysite.com/index.php?pa%ge</a>=
<a href="http://www.mysite.com/index.php?%25page">http://www.mysite.com/index.php?%page</a>=</p>

<p>But not on:
<a href="http://www.mysite.com/index.php?page=%13">http://www.mysite.com/index.php?page=%13</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2011-04-19T13:22:46.000+0000</p> 
        <div class="body">
            <p>This is not strictly a bug, as the URL you are providing is indeed not valid. Please specify the error message if you think otherwise.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T03:19:39.000+0000</p> 
        <div class="body">
            <p>I agree with Shahar.  The % symbol has special meaning in URIs - denotes encoded characters (ie: %20 is the code for an uri-encoded space) - so if you want to include a literal % you should use %25.  In your example, the last URI works because %13 is the uri-encoded ASCII character "DC3" (device control 3).</p>

        </div>
    </div>
    </div>

