<h2>ZF-11274: Zend_Http_UserAgent_AbstractDevice raises a notice</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-04-08T09:33:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-03T14:59:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
            <li>Zend_Http_UserAgent_AbstractDevice</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Http_UserAgent_AbstractDevice::extractFromUserAgent() raises a notice on given user agent:
Mozilla/5.0 (Windows NT 6.0; WOW64; rv:2.0) Gecko/20100101 Firefox/4.0</p>

<p>Bug is in line 651.
$comment[3] is not an existing element in $comment array.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marcin Gil (mgil) on 2011-04-19T15:12:58.000+0000</p> 
        <div class="body">
            <p>How can I attach a patch (diff file)?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-04-19T15:55:05.000+0000</p> 
        <div class="body">
            <p>Click "More Actions" and select the "Attach Files" option. If it's not present, that means we need a CLA from you (<a href="http://framework.zend.com/cla">http://framework.zend.com/cla</a>).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maksym Sliesarenko (sm) on 2011-04-20T08:30:52.000+0000</p> 
        <div class="body">
            <p>replace code on line 651:
{quote}
$result['browser_language'] = trim($comment[3]);
{quote}</p>

<p>with:</p>

<p>{quote}
if (isset($comment[3])) {
   $result['browser_language'] = trim($comment[3]);
}
{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maksym Sliesarenko (sm) on 2011-04-20T08:37:00.000+0000</p> 
        <div class="body">
            <p>Parser misunderstood prev comment :)</p>

<p>replace code on line 651:</p>

<pre class="highlight"><code>
    $result['browser_language'] = trim($comment[3]);
</code></pre>

<p>with:</p>

<pre class="highlight"><code>
if (isset($comment[3])) {
    $result['browser_language'] = trim($comment[3]);
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-29T18:27:54.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23892</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-05-03T10:12:46.000+0000</p> 
        <div class="body">
            <p>Hello, Adam. I will push [solve] button as proxy for You.
If You want to release at next mini, You can merge this commit fron trunk to 1.11 branch.</p>

<p>Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-05-03T14:59:05.000+0000</p> 
        <div class="body">
            <p>Fixed in release 1.11 branch at r23956</p>

        </div>
    </div>
    </div>

