<h2>ZF-1704: Zend_Controller_Response_Abstract send HTTP headers </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-07-11T11:01:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-11-16T12:44:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Julien Duponchelle (noplay)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>At line 305 Zend_Controller_Response_Abstract.http send use the header function. I think this code need to be in Zend_Controller_Response_HTTP else Zend_Controller_Response_CLI can't work.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-07-19T16:08:06.000+0000</p> 
        <div class="body">
            <p>Assigning to [~matthew] to initiate issue review.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-07-30T09:30:02.000+0000</p> 
        <div class="body">
            <p>Fix version after 1.0.1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-11-16T12:44:48.000+0000</p> 
        <div class="body">
            <p>Won't fix. The header logic is present so that if you re-purpose an HTTP application for the CLI, it won't break when calls to setHeader() are made (which will be sliently ignored in the CLI).</p>

        </div>
    </div>
    </div>

