<h2>ZF-10821: moveMessage() not executing with IMAP and gmail folders (tags)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-14T06:14:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                elzo valugi (valugi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I simplified the code that is not working. The folder exists. This code is not throwing any errors but is not actually moving the file. If I activate the commented line the email is marked as seen, so the unique id is correct.</p>

<p>foreach ($this-&gt;mail as $key =&gt; $email) {
    $uniqueId = $this-&gt;mail-&gt;getUniqueId ($key);
    if ('some@email.com' == $email-&gt;from &amp;&amp; $email-&gt;isMultipart()){
        //move it to the backup folder
        #$this-&gt;mail-&gt;setFlags($uniqueId, array(Zend_Mail_Storage::FLAG_SEEN));
        $this-&gt;mail-&gt;moveMessage($uniqueId, $this-&gt;destination_folder);
    }
}</p>

<p>While debugging I see that a copy is executed first. Zend/Mail/Protocol/Imap.php that sendRequest() is used to send :</p>

<p>TAG23 COPY 10807 "myTag"</p>

<p>and the response is TRUE.</p>

<p>Later a removeMessage($id) call is made with this content:
TAG24 STORE 10807 +FLAGS.SILENT (\Deleted)</p>

<p>The response is as well TRUE, but no real modifications happen in the Gmail mailbox. Is a pro Gmail account if this is relevant in any way.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

