<h2>ZF-11330: Zend_Loader_PluginLoader does not properly handle 5.3 namespaces</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-04-28T20:55:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-04T14:05:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
            <li>FixForZF1.12</li>
            <li>zf-crteam-priority</li>
            <li>zf-crteam-review</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7350">ZF-7350</a></li>
            <li><a href="/issues/browse/ZF-12173">ZF-12173</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15033/zf-11330-fix.diff">zf-11330-fix.diff</a></li>
            <li><a href="/issues/secure/attachment/15032/zf-11330-tests.diff">zf-11330-tests.diff</a></li>
            <li><a href="/issues/secure/attachment/15065/ZF-11330_adamlundrigan_fix.patch">ZF-11330_adamlundrigan_fix.patch</a></li>
            <li><a href="/issues/secure/attachment/15066/ZF-11330_adamlundrigan_tests.patch">ZF-11330_adamlundrigan_tests.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>load() method (line 373) improperly handles class file conversions with namespaces by only checking for underscores in the $name variable:</p>

<pre class="highlight"><code>
$classFile = str_replace('_', DIRECTORY_SEPARATOR, $name) . '.php';
</code></pre>

<p>The following patch corrects the issue:</p>

<pre class="highlight"><code>
diff --git a/Zend/Loader/PluginLoader.php b/Zend/Loader/PluginLoader.php
index d4003dc..55a4d4a 100755
--- a/Zend/Loader/PluginLoader.php
+++ b/Zend/Loader/PluginLoader.php
@@ -372,7 +372,11 @@ class Zend_Loader_PluginLoader implements Zend_Loader_PluginLoader_Interface
 
         $registry  = array_reverse($registry, true);
         $found     = false;
-        $classFile = str_replace('_', DIRECTORY_SEPARATOR, $name) . '.php';
+        if (false !== strpos($name, '\\')) {
+            $classFile = str_replace('\\', DIRECTORY_SEPARATOR, $name) . '.php';
+        } else {
+            $classFile = str_replace('_', DIRECTORY_SEPARATOR, $name) . '.php';
+        }
         $incFile   = self::getIncludeFileCache();
         foreach ($registry as $prefix =&gt; $paths) {
             $className = $prefix . $name;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Antonio J García Lagar (ajgarlag) on 2012-04-25T11:51:25.000+0000</p> 
        <div class="body">
            <p>Submitted a diff file with the unit tests and the patch to solve the bug.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-07T00:32:33.000+0000</p> 
        <div class="body">
            <p>The issue here is that Zend_Loader_PluginLoader supports namespaces in the class prefix (see ZF-7350), however one cannot load a class from a sub-namespace of the prefix namespace.  Test case which fails w/ current implementation:</p>

<pre class="highlight"><code>
$loader = new Zend_Loader_PluginLoader(array());
$loader-&gt;addPrefixPath('Zfns\\', dirname(__FILE__) . '/_files/Zfns');
$className = $loader-&gt;load('Foo\Bar');
</code></pre>

<p>I've tested the patch and verified that it works as advertised.  I've attached new patches as the OP's patches were in git format.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-06-04T14:05:13.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk (1.12.0): r24877</p>

        </div>
    </div>
    </div>

