<h2>ZF-108: Document Framework Requirements</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-06-21T21:59:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T21:26:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-691">ZF-691</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/developer/ticket/119">http://framework.zend.com/developer/ticket/119</a></p>

<ul><li>access to either MTA or "sendmail" equivalent for per use invocations via PHP's mail() * mod_rewrite (or equivalent) * PHP version * minimum versions of DB for each DB adapter * gd (some versions have memory leaks) * libjpeg - external dependency (used by gd) * etc.</li>
</ul><p>{quote}</p>

<p>06/05/06 18:09:10: Modified by gavin</p>

<pre><code>* owner changed from zend to gavin.
* status changed from new to assigned.
* component changed from Other to Documentation.
</code></pre>

<p>06/14/06 16:07:14: Modified by gavin</p>

<pre><code>* priority changed from major to critical.
* reporter changed from anonymous to gavin.
</code></pre>

<p><a href="http://www.zend.com/lists/fw-general/200605/msg01077.html">http://zend.com/lists/fw-general/…</a>
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-06-26T18:01:51.000+0000</p> 
        <div class="body">
            <p><a href="http://framework.zend.com/wiki/display/ZFMLGEN/mail/862">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-06-26T18:06:32.000+0000</p> 
        <div class="body">
            <p>Example showing how to check for zlib extension:</p>

<pre class="highlight"><code>
public static function encode($data, $params = null)
43     {
44         if ($params != null) {
45             $data = self::_applyEncodeParams($data, $params);
46         }
47
48         if (extension_loaded('zlib')) {
49             $trackErrors = ini_get( "track_errors");
50             ini_set('track_errors', '1');
51
52             if (($output = @gzcompress($data)) === false) {
53                 ini_set('track_errors', $trackErrors);
54                 throw new Zend_Pdf_Exception($php_errormsg);
55             }
56
57             ini_set('track_errors', $trackErrors);
58         } else {
59             throw new Zend_Pdf_Exception('Not implemented yet');
60         }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-09-05T22:17:49.000+0000</p> 
        <div class="body">
            <p>Configuration checks like the one above, extension_loaded('zlib'), should be moved to installation or configuration, instead of placed in code that executes on every request.  Zend_Environment will help support such checks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-10-19T20:36:46.000+0000</p> 
        <div class="body">
            <p>The iconv extension is required for several ZF components.</p>

<p>This extension is included by default with PHP 5.1.4+, and removal requires also removing libxml (also required for ZF).  Thus, it is unlikely people will lack access to iconv.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:09:06.000+0000</p> 
        <div class="body">
            <p>Changing fix version to unknown.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2006-12-27T13:27:43.000+0000</p> 
        <div class="body">
            <p>This issue should be resolved buy the section in the coding standards doc, specifically this section:</p>

<p><a href="http://framework.zend.com/wiki/display/ZFDEV/PHP+Coding+Standard+%28draft%2C+ZF+0.2+RC1%29#PHPCodingStandard%28draft%2CZF0.2RC1%29-PHPExtensions">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-29T20:15:58.000+0000</p> 
        <div class="body">
            <p>This task can not be completed until the devteam decides what requirements should be documented (e.g. minimum required PHP extensions for the entire ZF, or per component, or all extensions/libraries that might be optionally be used, if present).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-01T18:31:00.000+0000</p> 
        <div class="body">
            <p>Revision 5084 contains preliminary information about Zend Framework requirements.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-08-22T21:16:10.000+0000</p> 
        <div class="body">
            <p>Requirements stated in revision 6049, which should be in ZF 1.0.2.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T21:26:13.000+0000</p> 
        <div class="body">
            <p>Updating to comply with new IT component conventions.</p>

        </div>
    </div>
    </div>

