<h2>ZF-10840: Docs refer to non-existent getSelectedFolder() method on Zend_Mail_Storage_Imap -- should be getCurrentFolder()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-12-16T23:29:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-16T23:40:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-12-16T23:40:10.000+0000</p> 
        <div class="body">
            <p>Fixed in r23527, merged to release branch 1.11 in r23528</p>

        </div>
    </div>
    </div>

