<h2>ZF-10909: Zend_Config_Yaml and Zend_Config_Json couldn't be set as adapter for Zend_Navigation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-04T17:58:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-05T08:41:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Kai Uwe (kaiuwe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Like in the (XML) example here (<a href="http://framework.zend.com/manual/en/zend.navigation.containers.html#zend.navigation.containers.creating">http://framework.zend.com/manual/en/…</a>) you could set a Zend_Config_Xml as adapter for Zend_Navigation but if you try to this with Zend_Config_Yaml or Zend_Config_Json, Zend_Navigation_Page throws an Exception "Invalid argument: Unable to determine class to instantiate"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-01-05T01:31:54.000+0000</p> 
        <div class="body">
            <p>I think this is not a problem in Zend_Config and Zend_Navigation:</p>

<pre class="highlight"><code>
public function addPages($pages)
{
    if ($pages instanceof Zend_Config) {
        $pages = $pages-&gt;toArray();
    }

    // ...
}
</code></pre>

<p>It is a problem in your config file:</p>

<pre class="highlight"><code>
public static function factory($options)
{
    // ...

    $hasMvc = isset($options['action']) || isset($options['controller']) ||
              isset($options['module']) || isset($options['route']);

    if ($hasMvc) {
        require_once 'Zend/Navigation/Page/Mvc.php';
        return new Zend_Navigation_Page_Mvc($options);
    } elseif ($hasUri) {
        require_once 'Zend/Navigation/Page/Uri.php';
        return new Zend_Navigation_Page_Uri($options);
    } else {
        require_once 'Zend/Navigation/Exception.php';
        throw new Zend_Navigation_Exception(
            'Invalid argument: Unable to determine class to instantiate');
    }
}
</code></pre>

<p>Please show us your config file. Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by PHP4Dev (php4dev) on 2011-01-05T06:48:07.000+0000</p> 
        <div class="body">
            <p>Yaml-Navigation:</p>

<pre class="highlight"><code>
navigation:
  homesite:
    controller: index
    label: Homepage
    uri: /
  imprint:
    controller: imprint
    label: Imprint
    uri: /imprint
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-01-05T07:01:03.000+0000</p> 
        <div class="body">
            <p>Your configuration is wrong!</p>

<ul><li>MVC-Pages using MVC parameters (action, controller, module, route, params)</li>
<li>URI pages are defined by a single property uri</li>
</ul><p><a href="http://framework.zend.com/manual/en/zend.navigation.pages.html">http://framework.zend.com/manual/en/…</a></p>

<p>For user-defined routes (e.g. SEO-Links) use the routes from <a href="http://framework.zend.com/manual/en/zend.controller.router.html">Zend_Controller_Router</a>.</p>

<p>This not a bug in Zend_Navigation. <em>This ticket can be closed.</em></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by PHP4Dev (php4dev) on 2011-01-05T07:06:38.000+0000</p> 
        <div class="body">
            <p>I'm getting the same error if I also just use that:</p>

<pre class="highlight"><code>
navigation:
  homesite:
    label: Homepage
    uri: /
  imprint:
    label: Imprint
    uri: /imprint
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-01-05T07:28:58.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
homesite:
    label: Homepage
    uri: /
imprint:
    label: Imprint
    uri: /imprint
</code></pre>

<p>Or only:</p>

<pre class="highlight"><code>
-
    label: Homepage
    uri: /
-
    label: Imprint
    uri: /imprint
</code></pre>

<p>Please use the mailing list for support!</p>

<p>Greetings from Germany.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by PHP4Dev (php4dev) on 2011-01-05T08:11:32.000+0000</p> 
        <div class="body">
            <p>Okay, this works, thank you very much!
It would be nice if that would be added to the documentation.
This ticket can be closed.</p>

        </div>
    </div>
    </div>

