<h2>ZF-1286: Sync database schema used in manual, unit tests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2007-04-17T17:20:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T14:15:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1625">ZF-1625</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Please make sure the sample schema is the same and consistent as it is used in the manual sections for Zend_Db_Table, Zend_Db_Table_Rowset, Zend_Db_Table_Row, and Zend_Db_Table-Relationships.</p>

<p>This schema should be the same as that used in the Zend_Db unit tests.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-25T21:14:09.000+0000</p> 
        <div class="body">
            <p>This has been implemented as part of the rewrite of the Zend_Db_Adapter docs.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T14:15:14.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

