<h2>ZF-10163: Zend_Controller_Action_Helper_Redirector, duplicated port number if custom port used</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-07-15T05:21:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-26T05:52:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Hodgins (mjh_ca)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13391/ZF-10163.patch">ZF-10163.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If site runs on custom port for example:
<a href="http://example.org:50000/">http://example.org:50000/</a></p>

<p>In the IndexController/indexAction:
$redirector = $this-&gt;_helper-&gt;getHelper('Redirector');
$redirector-&gt;setUseAbsoluteUri()-&gt;setGotoSimple('example');</p>

<p>You will be redirected to:
<a href="http://example.org:50000/index/example">http://example.org:50000:50000/index/example</a></p>

<p>The problem is in the: Zend/Controller/Action/Helper/Redirector.php
the protected function _redirect append port number, but $_SERVER['HTTP_HOST'] contains port number too.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-10-26T01:50:16.000+0000</p> 
        <div class="body">
            <p>Patch with test attached.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-10-26T05:52:31.000+0000</p> 
        <div class="body">
            <p>Patch applied to trunk and 1.11 release branch -- thanks!</p>

        </div>
    </div>
    </div>

