<h2>ZF-10378: Zend_Db throws exception on empty result set</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-25T00:55:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-16T14:19:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Simon (_sims_)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm not sure what is going on here, as I'm sure this is a very common use case:
{quote}
$this-&gt;db = Zend_Db_Table_Abstract::getDefaultAdapter();
$select = $this-&gt;db-&gt;select()-&gt;from('category')-&gt;where('alias = ?', $alias);
$result = $this-&gt;db-&gt;fetchRow($select);
{quote}
OR as the docs state:
{quote}
$stmt = $select-&gt;query();
$result = $stmt-&gt;fetchRow();
{quote}</p>

<p>When $alias is a value that is not in the DB, I get and exception thrown:
bq. SQLSTATE[HY093]: Invalid parameter number: no parameters were bound</p>

<p>When $alias is set to a value that is in a record, I get a row returned. So basically, when an empty recordset is returned, I get this exception thrown.</p>

<p>When using Zend_Db_Table, I've never experienced such behavior. I would expect an empty result to be returned rather than and exception. When I run the SQL that echoing $select produces, I get no errors, just an empty result set.</p>

<p>It's possible I am doing something wrong. I wanted to test for illegal input and got this exception, which is unlike Zend_Db_Table. There are no question marks (?) or single quotes (') in $alias. It can be pure alphabet and I still get this thrown.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-08-25T01:01:34.000+0000</p> 
        <div class="body">
            <p>Edit: your variable probably is null or unset or something.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon (_sims_) on 2010-08-25T17:27:34.000+0000</p> 
        <div class="body">
            <p>I tried making the same query without Zend_Db (directly with PDO), and it fails. So I'm going to see W..T..F is wrong with my machine, but it seems there is an underlying problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon (_sims_) on 2010-08-25T22:20:03.000+0000</p> 
        <div class="body">
            <p>I've installed the project on another machine and it works. So looks like something else was wrong. I thought it was very strange as this is a common use scenario. This can be closed.</p>

        </div>
    </div>
    </div>

