<h2>ZF-10410: Using Zend_Service_Amazon_Sqs (possibly other Amazon services) after any other service that uses Zend_Service_Abstract's http client fails</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-09-02T13:13:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
            <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>First I am using Zend_Service_Akismet to validate the comment. Then I'm using Zend_Service_Amazon_Sqs to queue some data. 
Response from Amazon I'm getting:</p>

<p>Sender<code>SignatureDoesNotMatch</code>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details....</p>

<p>Replacing line 347:
$client-&gt;resetParameters();
with
$client-&gt;resetParameters(true); // which also resets the headers
fixes the problem.</p>

<p>The exact problem is that the host header is not being reset and that bothers Amazon. Here's a dump of request headers:</p>

<p>After talking to Akismet first:
GET /?Action=ListQueues&amp;AWSAccessKeyId=...&amp;SignatureVersion=2&amp;Timestamp=...&amp;Version=2009-02-01&amp;SignatureMethod=HmacSHA256&amp;Signature=... HTTP/1.1
User-Agent: Zend Framework/1.10.8 | Akismet/1.11
Host: rest.akismet.com</p>

<p>Without talking to Akismet: 
GET /?Action=ListQueues&amp;AWSAccessKeyId=...&amp;SignatureVersion=2&amp;Timestamp=...&amp;Version=2009-02-01&amp;SignatureMethod=HmacSHA256&amp;Signature=... HTTP/1.1
Host: queue.amazonaws.com
User-Agent: Zend_Http_Client</p>

<p>Possibly this is a bug in Zend_Http_Client and calling setUri() should automagically reset the host header.</p>

<p>Cheers,
- Andrei</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

