<h2>ZF-11295: no information about subcontroller support</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-04-15T19:16:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T17:24:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3590">ZF-3590</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>i think the manual should have information about zf's support to subcontrollers.</p>

<p>many people like me get frustated for seeing no submodule support but the implemented approach besides being subtly different is not documented in the official manual.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-04-16T09:26:02.000+0000</p> 
        <div class="body">
            <p>I could not agree more as this is the first time when I hear about subcontrollers. Google tells very little about these, so it would be nice to get those documented. The best catch was <a href="http://zend-framework-community.634137.n4.nabble.com/Controller-directory-tree-Url-mapping-of-sub-controllers-td668128.html">this post</a>.</p>

<p>edit: more on [<a href="https://github.com/adamlundrigan/zf1-nestedcontrollers">https://github.com/adamlundrigan/…</a>]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-29T17:24:42.000+0000</p> 
        <div class="body">
            <p>Closing as duplicate of ZF-3590.  Issue will be fixed there.</p>

        </div>
    </div>
    </div>

