<h2>ZF-11212: 'link' array entry works differently for RSS and Atom</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-03-23T01:26:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-13T20:29:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The 'link' key in an array passed to {{Zend_Feed::importArray()}} means different things for Zend_Feed_Atom and Zend_Feed_Rss.</p>

<p>The manual page says that 'link' is the 'canonical url to the feed'.</p>

<p>Zend_Feed_Rss, in {{_mapFieldHeaders()}}, simply creates a {{}} element in the channel. The RSS 2.0 spec says this means "The URL to the HTML website corresponding to the channel."</p>

<p>Zend_Feed_Atom, in its corresponding version of the same method, creates a {{}} element, which, like the manual would indicate, is intended to be a canonical url to the feed.</p>

<p>If the manual's text is indeed the intended behavior, then it seems Zend_Feed_Rss is creating bad output.
If Zend_Feed_Rss is doing it the "right" way, then it would seem that Zend_Feed_Atom should be creating a {{}}.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-05-13T20:29:45.000+0000</p> 
        <div class="body">
            <p>Please note that any missing or non-standard behaviour will not be fixed. Users are advised that Zend_Feed is basically deprecated (not in ZF2) and they should use/migrate to Zend_Feed_Reader/Zend_Feed_Writer which are far more comprehensive, adherent to all standards, easier to use, simple to extend for RSS/Atom extensions and which have somewhere in excess of 1000 unit tests to back those statements up (or was it almost 1500?). Anyway - I almost broke my fingers in testing ;). Using the newer components will also make transitioning new functionality to ZF2 that much easier.</p>

        </div>
    </div>
    </div>

