<h2>ZF-11339: Return type incorrect in docblock for Zend_Form_Decorator_Label::getLabel()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-05-02T21:25:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-03T15:03:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rene Roesch (reneroesch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>in form decorator label the function "getLabel()" implies
to return "void" but instead returns "string".</p>

<p>Greetings,
Rene</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-02T21:34:20.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23941</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-05-03T10:59:36.000+0000</p> 
        <div class="body">
            <p>Hello, Adam. I will push [solve] button as proxy for You.
If You want to release at next mini, You can merge this commit fron trunk to 1.11 branch.</p>

<p>Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-05-03T15:03:58.000+0000</p> 
        <div class="body">
            <p>Fixed 1.11 branch at r23960</p>

        </div>
    </div>
    </div>

