<h2>ZF-11817: magicKey generated in _recursiveJsonExprFinder lacks sufficient distinction</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-13T02:49:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-26T09:54:55.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                John Crenshaw (bugslayer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm submitting this as major because it is a class of error that often has security implications.</p>

<p>Zend_Json::_recursiveJsonExprFinder() uses the following code to generate magic keys</p>

<p>bq. $magicKey = "____" . $currentKey . "_" . (count($javascriptExpressions));</p>

<p>These keys are short and highly predictable. Constructing an input that will cause an incorrect replace is trivial:</p>

<p>bq. array('foo'=&gt;'___event_0', 'event'=&gt;new Zend_Json_Expr('function(){}'));</p>

<p>The old system of including the key in the match wouldn't work either, since this input would still break:</p>

<p>bq. array('foo'=&gt;array('event'=&gt;'___event_0'), 'event'=&gt;new Zend_Json_Expr('function(){}'));</p>

<p>The above examples only cause the result to be wrong, but I'm fairly certain that a more elaborate construct could be used to "break out" in certain cases (at which point this would become a security issue).</p>

<p>At a minimum something like the following should be used instead:</p>

<p>bq. $magicKey = "____" . $currentKey . "<em>" . (count($javascriptExpressions)) . '</em>' . md5($value-&gt;__toString()) . mt_rand() . time();</p>

<p>The base is the same, but it includes a couple of additions that dramatically reduce the chances of incorrectly matching rogue data:
md5($value-&gt;__toString()) - This tightly couples the key to the actual value it will be replaced with. This is still predictable, but the odds of an accidental match with legitimate data effectively drop to zero.</p>

<p>mt_rand() - Makes the key volatile. For malicious data to exploit the key replacement it would need to predict the value of mt_rand. This actually isn't sufficient; mt_rand is not cryptographically secure, and depending on the server's other outputs an attacker may be able to get enough data to predict all future outputs of mt_rand. Ideally something like openssl_random_pseudo_bytes should be used, but mt_rand is better than nothing.</p>

<p>time() - Limits the window of time where a malicious input can function. microtime would be better but doesn't work on all systems.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-10-26T09:54:55.000+0000</p> 
        <div class="body">
            <p>Set component and Auto-reassign</p>

        </div>
    </div>
    </div>

