<h2>ZF-10500: Empty array isn't being stored in cache</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-09-27T16:41:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-20T09:29:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Bennewitz (private) (mabe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Empty arrays cannot be stored in cache. Though, an empty array may result from a very expensive SQL.
So no matter the value of the variable that needs to be cached, it just should be cached.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-09-29T10:36:20.000+0000</p> 
        <div class="body">
            <p>Please tell us which Backend and Frontend you are using and your configuration options</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mathieu Decaffmeyer (mathi) on 2010-09-30T04:38:51.000+0000</p> 
        <div class="body">
            <p>Hi Marc, I'm using Core File, below is my configuration :</p>

<p>$frontendOptions = array('lifetime' =&gt; NULL, 'automatic_serialization' =&gt; true);
$backendOptions = array('cache_dir' =&gt; './tmp/', 'hashed_directory_level' =&gt; 2);
$cache = Zend_Cache::factory('Core', 'File', $frontendOptions, $backendOptions);</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-09-30T14:11:51.000+0000</p> 
        <div class="body">
            <p>I can't reproduce it.</p>

<p>The following is true on my machine with your cache object:</p>

<pre class="highlight"><code>
$cache-&gt;save(array(), 'test');
var_dump($cache-&gt;load('test')); // displays "array(0) {}"
</code></pre>

<p>Can you please create a small test script and tell me your used version of ZF.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mathieu Decaffmeyer (mathi) on 2010-09-30T15:48:45.000+0000</p> 
        <div class="body">
            <p>Marc, you are right. I took the code from the doc :</p>

<p>if(!$result = $cache-&gt;load('myresult')) { ... }</p>

<p>The empty array will of course execute the if block ... I hate loose typing :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mathieu Decaffmeyer (mathi) on 2010-09-30T15:56:05.000+0000</p> 
        <div class="body">
            <p>What about changing the doc a little bit ?</p>

<p>$result = $cache-&gt;load('myresult');
if($result === false) {
   ...
}</p>

<p>The cache could return "0", "", array(), etc.
Only strictly false should be checked because only false will be return when there is no cache hit.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-10-01T08:57:38.000+0000</p> 
        <div class="body">
            <p>changed type to doc</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-10-01T09:08:17.000+0000</p> 
        <div class="body">
            <p>changed in r23013</p>

        </div>
    </div>
    </div>

