<h2>ZF-10109: Zend_Rest_Server adding additional headers</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-07-05T02:37:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be great if developers could add additional headers to existing, for example 'Content-Encoding: gzip' makes sense; so, if I extend the Zend_Rest_Server class, it's not possible, because in line 178 $this-&gt;_headers = array('Content-Type: text/xml') will be declared as a new array; it would be better to push a variable to existing _headers array, $this-&gt;_headers[] = 'Content-Type: text/xml'</p>

<p>Like so, currently it's not possible to add additional headers; even better would be a public method addHeader($header);</p>

<p>In my case, I added json response type to the class and I had to rewrite the header functionalities;</p>

<p>cheers,
stefan</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

