<h2>ZF-11431: zf create db-table.from-database doesn't work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-02T20:07:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-30T22:51:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Renich Bon Ciric (renich)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This command doesn't work and it doesn't give an error. It fails horribly.</p>

<p>Here's some output:</p>

<p>[renich@introdesk test]$ cat application/configs/application.ini 
[production]
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0
includePaths.library = APPLICATION_PATH "/../library"
bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
appnamespace = "Application"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"
resources.frontController.params.displayExceptions = 0</p>

<p>resources.layout.layoutPath = APPLICATION_PATH "/layouts/scripts/"</p>

<p>resources.db.params.mysql'adapter = "PDO_MYSQL"
resources.db.params.host = "localhost"
resources.db.params.dbname = "zf_test"
resources.db.params.user = "zf_test"
resources.db.params.password = "password"</p>

<p>[staging : production]</p>

<p>[testing : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1</p>

<p>[development : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
resources.frontController.params.displayExceptions = 1
[renich@introdesk test]$ zf create db-table.from-database
PHP Fatal error:  Call to a member function listTables() on a non-object in /usr/share/pear/Zend/Tool/Project/Provider/DbTable.php on line 166
PHP Stack trace:
PHP   1. {main}() /usr/share/pear/zf.php:0
PHP   2. ZF::main() /usr/share/pear/zf.php:623
PHP   3. ZF-&gt;run() /usr/share/pear/zf.php:74
PHP   4. ZF-&gt;_runTool() /usr/share/pear/zf.php:117
PHP   5. Zend_Tool_Framework_Client_Abstract-&gt;dispatch() /usr/share/pear/zf.php:600
PHP   6. Zend_Tool_Framework_Client_Abstract-&gt;_handleDispatch() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:241
PHP   7. Zend_Tool_Framework_Client_Abstract-&gt;_handleDispatchExecution() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:318
PHP   8. call_user_func_array() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:324
PHP   9. Zend_Tool_Project_Provider_DbTable-&gt;createFromDatabase() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:324</p>

<p>Fatal error: Call to a member function listTables() on a non-object in /usr/share/pear/Zend/Tool/Project/Provider/DbTable.php on line 166</p>

<p>Call Stack:
    0.0010     794568   1. {main}() /usr/share/pear/zf.php:0
    0.0010     794568   2. ZF::main() /usr/share/pear/zf.php:623
    0.0037    1247488   3. ZF-&gt;run() /usr/share/pear/zf.php:74
    0.0037    1247488   4. ZF-&gt;_runTool() /usr/share/pear/zf.php:117
    0.0046    1368720   5. Zend_Tool_Framework_Client_Abstract-&gt;dispatch() /usr/share/pear/zf.php:600
    0.0882    7921456   6. Zend_Tool_Framework_Client_Abstract-&gt;_handleDispatch() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:241
    0.0883    7922024   7. Zend_Tool_Framework_Client_Abstract-&gt;_handleDispatchExecution() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:318
    0.0883    7922464   8. call_user_func_array() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:324
    0.0883    7922888   9. Zend_Tool_Project_Provider_DbTable-&gt;createFromDatabase() /usr/share/pear/Zend/Tool/Framework/Client/Abstract.php:324</p>

<p>[renich@introdesk test]$ mysql -u zf_test -p zf_test;
Enter password: 
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A</p>

<p>Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.5.12 MySQL Community Server (GPL)</p>

<p>Copyright (c) 2000, 2010, Oracle and/or its affiliates. All rights reserved.</p>

<p>Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.</p>

<p>Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.</p>

<p>mysql&gt; show tables;
+-------------------+
| Tables_in_zf_test |
+-------------------+
| albums            |
+-------------------+
1 row in set (0.00 sec)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Hovno Sk (hovno.sk) on 2012-04-27T21:39:58.000+0000</p> 
        <div class="body">
            <p>In Bootstrap::_initDb add to last line:</p>

<p>return $this-&gt;getPluginResource('db')-&gt;getDbAdapter();</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Io Yer (ioyer) on 2012-08-30T18:26:50.000+0000</p> 
        <div class="body">
            <p>Maybe try change this line:
resources.db.params.mysql'adapter = "PDO_MYSQL"
to:
resources.db.adapter = "PDO_MYSQL"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Renich Bon Ciric (renich) on 2012-08-30T22:51:40.000+0000</p> 
        <div class="body">
            <p>This actually worked... changing to db.adapter, that is...</p>

        </div>
    </div>
    </div>

