<h2>ZF-11992: Wrong date in Zend_Date</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-01-12T14:26:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-03-13T20:55:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Reopened</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Mini Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-12507">ZF-12507</a></li>
            <li><a href="/issues/browse/ZF-12506">ZF-12506</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have the code:
$days = 12
$today = new Zend_Date(date('Y-m-d'), 'YYYY-MM-dd');
$minusTwoWeeks = $today-&gt;subDay($days);
echo date('Y-m-d', $minusTwoWeeks-&gt;toValue());</p>

<p>Today is 2012-01-12
So I receive 2011-12-31 And it is correct.
If I change $days to 10, I receive 2012-01-02 and it is also correct. But if I change $days to 11 I receive 2011-01-02. The year is incorrect! I tried several times, the result was the same. Then I waited 15 minutes, after that everything became good. 2012-01-01. But why it has changed?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-26T05:22:35.000+0000</p> 
        <div class="body">
            <p>Can you provide an exact date/time (down to the second) at which is error occurs?  As you said it didn't recur when you tried again later, we'll need more than just the Ymd to dig deeper.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rafael Kassner (kassner) on 2012-03-20T21:14:29.000+0000</p> 
        <div class="body">
            <p>Just adding some example code that showing the problem <a href="http://pastebin.com/MFgbuy5f">http://pastebin.com/MFgbuy5f</a></p>

<p>This problem appears only when we use the 1st day of the year.</p>

<p>It happens in 1.11.11 and 1.9.6 (don't bother, it was a old Magento Install).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-06-12T20:56:17.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk with r24880; will release with 1.12.0.</p>

<p>Basically, Zend_Date converts all formats to ISO 8601 standards. This means that "o" is used for the year instead of "Y". If you look at <a href="http://php.net/date">http://php.net/date</a> you'll see an interesting note for "o" -- when the day of the week falls within the last <em>week</em> of the previous year, "o" will evaluate to the previous year. As such, I've added a regex that will replace "o" with "Y" when not preceded by an escape, thus giving us the desired behavior.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Peter Moolenaar (pmoolenaar) on 2013-01-12T15:42:49.000+0000</p> 
        <div class="body">
            <p>Uhm, however that was expected behaviour! See the note just before <a href="http://framework.zend.com/manual/1.12/en/zend.date.constants.html#zend.date.constants.phpformats">http://framework.zend.com/manual/1.12/…</a></p>

<p>I've been looking all over for this 'suddenly' altered behaviour. I'm sticking with the manual that states that using uppercase Y's will return me the week-based ISO year.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Peter Moolenaar (pmoolenaar) on 2013-01-17T11:14:27.000+0000</p> 
        <div class="body">
            <p>And, I'll add another comment to this one. I'd opened a new bug for this, however that got closed with the remark that the original one should be reopend. So, please do so. This implementation actually breaks my applications and it actually degrades my opinion of the stability of ZF since it doesn't even conform to its own manual anymore!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-01-17T11:32:27.000+0000</p> 
        <div class="body">
            <p>@Peter
Can you help me and provide some examples which I can use for unit test? That would be great.
I am very busy, because I work on the next release (1.12.2) and also on the ZF website.</p>

<p>Thanks in advance.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Peter Moolenaar (pmoolenaar) on 2013-01-17T11:48:09.000+0000</p> 
        <div class="body">
            <p>Sure, the test is quite simple (adhering to the manual that is :)).
{quote}
$date = new Zend_Date('2012-12-31');
echo $date-&gt;toString('c'); // ISO conforming string: 2012-12-31T00:00:00+01:00 (I'm in Europe/Amsterdam tz)
$calendarYear = $date-&gt;get(Zend_Date::YEAR); // Expect 2012
$isoBasedYear = $date-&gt;get(Zend_Date::YEAR_8601); // Expect 2013
echo '<br />'.$calendarYear.' vs. '.$isoBasedYear;
{quote}
The original mentioned problem is the other way around (the first day of 2012 (2012-01-01) falls in the last week of the previous year and should render '2012 vs. 2011'). However it is simply a misinterpretation of how the different tokens work. In the more elaborate example from pastebin he actually tests both uppercase and lowercase y and deduces that, without argumentation, they should actually be the same (with which I obviously disagree :)).</p>

        </div>
    </div>
    </div>

