<h2>ZF-11303: CLONE - Form Element Translator Bug</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-04-18T17:59:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-07T12:33:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marco Joneleit (majomadrid)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is a clone of ZF3313 which was solved for 1.6 and reappeared from 1.10.6 and still isn't fixed.</p>

<p>The default translator used by all forms may be set by calling:</p>

<pre><code>&lt;pre class="highlight"&gt;&lt;code&gt;
</code></pre>

<p>Then, when $form-&gt;isValid is called, each of the element validators have their translators set to that same default translator (if they don't have a translator explicitly defined).</p>

<p>This works fine, if you want to use the same error message for every validator instance of the same name. For example, NotEmpty, the validator automatically created by $element-&gt;setRequired(true), uses the key 'isEmpty' for its error message. If 'isEmpty' is mapped to a string in the default translator, it will be picked up and used as the error message when a value is not supplied for that field (element) of the form.</p>

<p>However, it is more-likely the case that in a large application, different fields will require different error messages when they are left blank. This is no problem if you're not relying on a translator. Each of those NotEmpty validator instances can be given customized messages by calling setMessage on them.</p>

<p>But in that case, the translator stops working, seemingly because of an oversight in the implementation:</p>

<p>(for this example, assume $messageKey has the value 'isEmpty')
_createMessage in Abstract.php line 191:</p>

<pre><code>    $message = $this-&gt;_messageTemplates[$messageKey];

    if (null !== ($translator = $this-&gt;getTranslator())) {
        if ($translator-&gt;isTranslated($messageKey)) {
            $message = $translator-&gt;translate($messageKey);
        }
    }
</code></pre>

<p>But what if the developer has specified:</p>

<p>
        $password-&gt;addValidator('NotEmpty', true);
        $password-&gt;getValidator('NotEmpty')-&gt;setMessage('form.login.password.errBlank');
```</p>

<p>with the following line in en_US.php:</p>

<pre><code>    'form.login.password.errBlank'    =&gt; "Please enter your password."
</code></pre>

<p>The above code in Zend Framework's Abstract::_createMessage will output only the translation key as the error message ('form.login.password.errBlank').</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-04-18T18:51:56.000+0000</p> 
        <div class="body">
            <p>Detaching Zend_Validate from the list of problematic components.</p>

<p>Note:
From the point of a translator giving a key is bad behaviour because of the above mentioned problem... no translation results in an unrecognised key instead of a meaningfull message</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-04-30T11:37:53.000+0000</p> 
        <div class="body">
            <p>Sorry, I am new to Zend_Form, so I will reassign automatically</p>

        </div>
    </div>
    </div>

