<h2>ZF-10155: Support for atom tag icon</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-07-14T13:09:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-12T10:28:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Writer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13214/atom_tag_icon.patch">atom_tag_icon.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm using Zend_Feed_Writer and I noticed that it is not possible to generate an Atom tag icon. I decided to study the code and implement this tag. I'm attaching the patch I create. Not sure if this is useful for the component and not sure if I implemented this functionality in a good way since this is my first contact with Zend_Framework.</p>

<p>If it is useful but the code is not code I'm willing to improved based on the feedback of other developers.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-07-14T13:46:34.000+0000</p> 
        <div class="body">
            <p>Rodrigo, thank you for your patch, and willingness to contribute to Zend Framework.</p>

<p>You have not yet signed the CLA which is a requirement for any code from yourself to be included in the codebase.</p>

<p>Please read the Contributng to Zend Framework Guide here <a href="http://framework.zend.com/wiki/display/ZFDEV/Contributing+to+Zend+Framework">http://framework.zend.com/wiki/display/…</a>
And you can find the CLA to be printed, signed and then emailed, or faxed here <a href="http://framework.zend.com/wiki/display/ZFPROP/Contributor+License+Agreement">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rodrigo Primo (rodrigosprimo) on 2010-07-26T08:13:15.000+0000</p> 
        <div class="body">
            <p>Ok, thanks Ryan. I just sent an e-mail with the CLA signed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-10-12T10:28:45.000+0000</p> 
        <div class="body">
            <p>Implemented in r23090 for ZF 1.11 :P</p>

        </div>
    </div>
    </div>

