<h2>ZF-1560:  Zend_Gdata_App_Util::formatTimestamp strips timezone offset</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-06-13T16:16:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>User reporting issue with timezone offset ('-05') being stripped when calling Zend_Gdata_CalendarEventQuery::setStartMin and setStartMax.  It appears that the formatTimestamp function is stripping this data.</p>

<p>Problem reported at:
<a href="http://groups.google.com/group/google-calendar-help-dataapi/browse_thread/thread/5ff89f7663b5a137/a423e6be45239b62#a423e6be45239b62">http://groups.google.com/group/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-20T18:46:25.000+0000</p> 
        <div class="body">
            <p>Fixed in rev 5396 by adding a regex to detect a pre-formatted RFC3339 date and not reformat if that's the case.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-06-20T22:43:16.000+0000</p> 
        <div class="body">
            <p>Ryan,
There's a problem with this fix. The new regex doesn't check for end of line properly, so any string that contains NNNN-NN-NN will match, regardless of what comes after. Also, RFC 3339 allows for the following two things which this won't match against:
    * The 'T' and 'Z' may be lowercase.
    * Milliseconds may be specified with arbitrary precision.</p>

<p>I've emailed you an updated regex which will should resolve these three things.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2007-06-20T23:56:06.000+0000</p> 
        <div class="body">
            <p>My last comment wasn't complete. I meant to say any string that contains NNNN-NN-NN(.*).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-22T16:55:35.000+0000</p> 
        <div class="body">
            <p>Problem with regex not detecting end of line appropriately</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-06-22T17:02:55.000+0000</p> 
        <div class="body">
            <p>Fixed in svn commit 5420</p>

        </div>
    </div>
    </div>

