<h2>ZF-1931: missing array() language-construct</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-09-10T18:46:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T21:55:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                NiKi Zh (nikizh)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.date.constants.html">http://framework.zend.com/manual/en/…</a></p>

<p>Example 8.16. Example usage for self-defined formats with PHP specifier</p>

<pre class="highlight"><code>
Zend_Date::setOptions('format_type' =&gt; 'php');
</code></pre>

<p>Should be</p>

<pre class="highlight"><code>
Zend_Date::setOptions(array('format_type' =&gt; 'php'));
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-11T12:57:20.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN 6293</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T21:55:59.000+0000</p> 
        <div class="body">
            <p>Updating to comply with new IT component conventions.</p>

        </div>
    </div>
    </div>

