<h2>ZF-10793: Zend_View_Helper_Placeholder_Registry::createContainer -  second param is unusable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-08T06:40:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-17T17:43:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>second param "$value" in method "createContainer" does not participate in containerClass constructor.</p>

<p>Real code:</p>

<p>class Zend_View_Helper_Placeholder_Registry
{
    public function createContainer($key, array {color:red} $value {color} = array())
    {
        $key = (string) $key;</p>

<pre><code>    $this-&gt;_items[$key] = new $this-&gt;_containerClass({color:red}array(){color});

    return $this-&gt;_items[$key];
}
</code></pre>

<p>}</p>

<p>Solution:</p>

<p>class Zend_View_Helper_Placeholder_Registry
{
    public function createContainer($key, array {color:red} $value {color} = array())
    {
        $key = (string) $key;</p>

<pre><code>    $this-&gt;_items[$key] = new $this-&gt;_containerClass( {color:red} $value {color} );

    return $this-&gt;_items[$key];
}
</code></pre>

<p>}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-17T17:43:35.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23544 merged to release branch 1.11 r23545 - thanks.</p>

        </div>
    </div>
    </div>

