<h2>ZF-187: Zend_Cache EXAMPLES.txt is out of accordance with Frontend\Output.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-07-03T01:12:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.5 (11/Jul/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10020/test.php">test.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>EXAMPLES.txt says concerning "Output" frontend:</p>

<p>if ($cache-&gt;start($id)) {
    // cache is not hit !</p>

<pre><code>// Output you want to cache
for ($i=0;$i&lt;10000;$i++) {
    echo($i);
}

// store "captured" output into cache
$cache-&gt;end();
</code></pre>

<p>}</p>

<p>But Zend_Cache_Frontend_Output::start() method returns true when cache hit and false otherwise, so the function or example should be changed.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2006-07-03T12:05:34.000+0000</p> 
        <div class="body">
            <p>test script</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2006-07-03T12:11:06.000+0000</p> 
        <div class="body">
            <p>you are right (I attached a test script)</p>

        </div>
    </div>
    </div>

