<h2>ZF-10734: Use getName instead of getId when adding element to DisplayGroup</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2010-11-23T13:30:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-01T09:54:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.3 (01/Feb/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Richard Tuin (richardtuin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Richard Tuin (richardtuin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13479/ZF-10491-rtuin-update.patch">ZF-10491-rtuin-update.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There should be a small change in the code.
Method {{Zend_Form_Element::getName()}} must be used instead of {{Zend_Form_Element::getId()}}</p>

<p>This part:</p>

<pre class="highlight"><code>
if($element instanceof Zend_Form_Element) {
    $element = $element-&gt;getId();
}
</code></pre>

<p>Should be:</p>

<pre class="highlight"><code>
if($element instanceof Zend_Form_Element) {
    $element = $element-&gt;getName();
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-23T13:30:54.000+0000</p> 
        <div class="body">
            <p>Patch fix included. With updated unit tests.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-01T09:54:27.000+0000</p> 
        <div class="body">
            <p>Fixed r23603 in trunk merged to release branch 1.11 r23604 - thanks.</p>

        </div>
    </div>
    </div>

