<h2>ZF-1228: correct class names</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-04-09T16:54:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC2 (08/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Rename following classes:</p>

<p>||from||to||
|Zend_Feed_EntryAtom|Zend_Feed_Entry_Atom|
|Zend_Feed_EntryRss|Zend_Feed_Entry_Rss|
|Zend_Feed_EntryAbstract|Zend_Feed_Entry_Abstract|</p>

<p>(and also the files in repository)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-04-14T02:46:14.000+0000</p> 
        <div class="body">
            <p>The classes should be consistent to Coding standard 3.2.</p>

<p>Entry should be the directory and Abstract, Atom and so on should be in this directory.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-06T13:19:47.000+0000</p> 
        <div class="body">
            <p>Thomas has volunteered to do this work.  Thanks very much Thomas.</p>

<p>What I would recommend is to create classes Entry/Abstract, Entry/Atom, Entry/Rss, but also keep the old names for backward compatibility.  They can be simple extends relationships, for example:</p>

<pre class="highlight"><code>
/**
 * @deprecated since 1.0.0
 */
class Zend_Feed_EntryAbstract extends Zend_Feed_Entry_Abstract
{
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-06T13:20:57.000+0000</p> 
        <div class="body">
            <p>Actually Zend_Feed_EntryAbstract would still be declared as an abstract class.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-05-06T14:54:58.000+0000</p> 
        <div class="body">
            <p>Fixed as with SVN 4733.</p>

<p>Old Entry* classes are depreciated and will be deleted before Release 1.0.
This issue will stay opened until the old classes are deleted.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-05-17T03:21:07.000+0000</p> 
        <div class="body">
            <p>Y'e old classes now throw an E_USER_NOTICE if they are initialized.</p>

<p>They will be deleted with the release of 1.0RC2.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-06-04T15:22:39.000+0000</p> 
        <div class="body">
            <p>Fixed as with SVN 5105.</p>

        </div>
    </div>
    </div>

