<h2>ZF-10707: the hidden field for ZendX_JQuery_Form_Element_Slider doesn't correct in a subform</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-11-18T09:06:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-28T07:20:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10572">ZF-10572</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When you add a ZendX_JQuery_Form_Element_Slider element in a subform, you've a problem this the html render, the name of the hidden field isn't correct:</p>

<pre class="literal"> 
</pre>

<p>Instead of this, you should have this content:</p>

<pre class="literal"> 
</pre>

<p>It's a problem when you validate the form, the name is wrong, you loose the values.</p>

<p>Thanks for your feedback.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoph, René Pardon (renepardon) on 2010-11-18T10:20:41.000+0000</p> 
        <div class="body">
            <p>Hi Ludovic,</p>

<p>this is a known problem. I've already uploaded a Patch for this.</p>

<p>regards
René</p>

<p><em>Edit:</em>
There is already an implementation for array notation. Have a look at:
<a href="http://framework.zend.com/manual/en/zend.form.advanced.html">http://framework.zend.com/manual/en/…</a></p>

<p>So you should use setBelongsTo and/or setIsArray.</p>

<p>best regards
René</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ludovic Gasc (gmludo) on 2010-11-22T01:45:58.000+0000</p> 
        <div class="body">
            <p>I've tested with your patch, Zend_Form::setIsArray($flag) and Zend_Form::setElementsBelongTo($array), nothing works.</p>

<p>I've tested without our patch too.</p>

<p>For all Zend_Form standard elements, it works, except of ZendX_JQuery_Form_Element_Slider, I've always the same issue.</p>

<p>Are you sure it isn't an issue ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ludovic Gasc (gmludo) on 2010-12-28T07:20:46.000+0000</p> 
        <div class="body">
            <p>Do you need a source code example to demonstrate the presence of this bug ?</p>

        </div>
    </div>
    </div>

