<h2>ZF-1389: Improve plugin accessors</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-05-15T13:32:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, once plugins are registered with the front controller, there's no way to retrieve them. As a result, if you no longer have the plugin object in scope, you cannot unregister it.</p>

<p>To correct these issues, I propose:</p>

<ul><li>Add an accessor to retrieve all plugins</li>
<li>Add an accessor to retrieve plugins my class name; would return either a single object or array of objects</li>
<li>Alter unregisterPlugin() to accept an optional class name; it would then unregister all plugins of that class.</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-05-15T17:26:49.000+0000</p> 
        <div class="body">
            <p>Functionality added in r4813.</p>

        </div>
    </div>
    </div>

