<h2>ZF-11306: $auth was not declare</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-04-19T07:21:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-23T21:53:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                netroby (netroby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
            <li>Authentication</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>SEE: <a href="http://framework.zend.com/manual/en/learning.multiuser.authentication.html">http://framework.zend.com/manual/en/…</a></p>

<p>With the above form, we can now go about creating our login action for our authentication controller. This controller will be called "AuthController", and will be located at application/controllers/AuthController.php. It will have a single method called " loginAction()" which will serve as the self-posting action. In other words, regardless of the url was POSTed to or GETed to, this method will handle the logic.
The following code will demonstrate how to construct the proper adapter, integrate it with the form:</p>

<pre class="highlight"><code>
class AuthController extends Zend_Controller_Action
{

    public function loginAction()
    {
        $db = $this-&gt;_getParam('db');

        $loginForm = new Default_Form_Auth_Login($_POST);

        if ($loginForm-&gt;isValid()) {

            $adapter = new Zend_Auth_Adapter_DbTable(
                $db,
                'users',
                'username',
                'password',
                'MD5(CONCAT(?, password_salt))'
                );

            $adapter-&gt;setIdentity($loginForm-&gt;getValue('username'));
            $adapter-&gt;setCredential($loginForm-&gt;getValue('password'));

            $result = $auth-&gt;authenticate($adapter);

            if ($result-&gt;isValid()) {
                $this-&gt;_helper-&gt;FlashMessenger('Successful Login');
                $this-&gt;redirect('/');
                return;
            }

        }

        $this-&gt;view-&gt;loginForm = $loginForm;

    }

}
</code></pre>

<p>{quote}$auth is not declare.{quote}</p>

<p>we should add :</p>

<p>```</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-04-19T08:49:34.000+0000</p> 
        <div class="body">
            <p>Code tags added</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-04-23T21:53:17.000+0000</p> 
        <div class="body">
            <p>Fix r23866 in the trunk and merged to branch release 1.11 r23867 - thanks.</p>

        </div>
    </div>
    </div>

