<h2>ZF-10887: Check with 'defined' for existence of a class constant triggers the autoloader when setFallbackAutoloader is true.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-31T10:49:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-02T09:54:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>class Test
{
    const DEF=0;
}
require_once 'Zend/Loader/Autoloader.php';
$za = Zend_Loader_Autoloader::getInstance();
$za-&gt;setFallbackAutoloader(true);
echo defined('Test::ND') ? 'yes' : 'no';</p>

<p>When executing the above sample code, the Zend Autoloader is triggered, when the checked constant doesn't exist and 'setFallbackAutoloader' is true.
The following warning is issued:</p>

<p>"Warning: include_once(9akf.php) [function.include-once]: failed to open stream: No such file or directory in D:\lib\ZendFramework\library\Zend\Loader.php on line 146"</p>

<p>The lenght of the cryptic filename the autoloader is trying to access (9akf) corresponds to the length of the classname (Test).
When checking for an existing constant everything works fine.
Also checking for the existence of a constant in the same class context works flawless.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-01T05:47:13.000+0000</p> 
        <div class="body">
            <p>Closing as non-reproduceable.
Feel free to reopen the issue as soon as you can provide additional informations.</p>

<p>Thanks
Ramon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by G. Wenda (gcw) on 2011-01-02T09:53:22.000+0000</p> 
        <div class="body">
            <p>I've dug a bit around and was able to reliably reproduce this issue.
The environment I've been using was as follows:
-OS: Virgin WinXP Pro SP3 with all security patches as of 1.1.11 running in a VM
-ZendServer-CE-php-5.3.3-5.0.4-Windows_x86 (Typical installation with additional Zend Guard Loader; Web-Server: Apache 2.2.16; everything else at standard values)</p>

<p>Now the above behaviour can be observed.
I've tracked down one of the involved components to be the Zend Guard Loader. If in the configuration file 'loader.ini' in /ZendServer/etc/cfg the 'entry zend_extension_manager.dir.loader' is active the described problem occurs. Commenting the line out resolves the issue.</p>

        </div>
    </div>
    </div>

