<h2>ZF-10948: option to disable translation of labels in zend navigation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-01-14T04:52:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-02-10T16:18:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14972/0001-Add-useTranslator-support-for-Zend_Navigation-contai.patch">0001-Add-useTranslator-support-for-Zend_Navigation-contai.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Navigation <em>always</em> translates labels and titles for the container.</p>

<p>There is an option in the view helper to disable the translation for the whole container, but there is no option to disable this translation for specific pages.</p>

<p>Example use case:</p>

<pre class="highlight"><code>
$page = new Zend_Navigation_Page_Mvc(}}
    array(
        'label' =&gt; $blogPost-&gt;alreadyTranslatedTitleFromDb
        // ... 
    )
);

$page2 = new Zend_Navigation_Page_Mvc(
    array(
        'title' =&gt; 'Edit: ' . $blogPost-&gt;alreadyTranslatedTitleFromDb
        // ... 
    )
);


$container-&gt;addPage($page);
$container-&gt;addPage($page2);

</code></pre>

<p>Now, when I use:</p>

<pre class="highlight"><code>
$page-&gt;getLabel();
</code></pre>

<p>or</p>

<pre class="highlight"><code>
$page2-&gt;getTitle();
</code></pre>

<p>the label is translated twice. The same for breadcrumbs, sitemaps etc.</p>

<p>Translation logs are filled with ~random messages.</p>

<p>Option to disable the translation is needed:</p>

<pre class="highlight"><code>
$page = new Zend_Navigation_Page_Mvc(
    array(
        'label' =&gt; $blogPost-&gt;alreadyTranslatedTitleFromDb
        'disableTranslation' =&gt; true
        // ... 
    )
);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-01-14T05:33:11.000+0000</p> 
        <div class="body">
            <p>This is not a bug, because the Zend_Navigation - view helpers translate the label and title only once! 
I think this is more of a suggestion for an improvement. Please change the type of these issue and remove it as an affected component Zend_Translate.</p>

<p>Can you write a few tests and a patch? That would be very useful for quick editing.
Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tomek Pęszor (admirau) on 2011-01-15T03:08:28.000+0000</p> 
        <div class="body">
            <p>Changed priority to major, because the patch with unit tests is available and can be easily fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tomek Pęszor (admirau) on 2011-01-15T03:17:48.000+0000</p> 
        <div class="body">
            <p>I wrote a fix for this issue, including unit tests.
The fix <em>is</em> backwards compatible.</p>

<p>Here is link to the patch and modified files:
<a href="http://taat.pl/useTranslator_Zend_Navigation_Container_patch.tar.gz">http://taat.pl/useTranslator_Zend_Navigation_Conta…</a>
(how can I upload it here? Could someone do this?)</p>

<p>This basically adds useTranslator property with getter and setter,
and some conditions in view helpers handling the new option.</p>

<p>The patch contains new methods for the unit tests
and the modifications to the library itself.</p>

<p>List of modified files.</p>

<p>Modified: library/Zend/Navigation/Container.php
Modified: library/Zend/Navigation/Page.php
Modified: library/Zend/View/Helper/Navigation/Breadcrumbs.php
Modified: library/Zend/View/Helper/Navigation/HelperAbstract.php
Modified: library/Zend/View/Helper/Navigation/Menu.php</p>

<p>Unit Tests:</p>

<p>Modified: tests/Zend/Navigation/ContainerTest.php
Modified: tests/Zend/Navigation/PageTest.php
Modified: tests/Zend/View/Helper/Navigation/BreadcrumbsTest.php
Modified: tests/Zend/View/Helper/Navigation/MenuTest.php
Modified: tests/Zend/View/Helper/Navigation/NavigationTest.php
Added: tests/Zend/View/Helper/Navigation/_files/expected/menu/translated_one_page_without_translator.html</p>

<p>Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2011-09-27T18:00:26.000+0000</p> 
        <div class="body">
            <p>Hi Tomek,
why the container must be changed?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tomek Pęszor (admirau) on 2011-09-29T07:22:39.000+0000</p> 
        <div class="body">
            <p>Frank,</p>

<p>When you want to add a page, which is already translated, currently there's no option to disable translation just for this particular page container on the pre-view helper level (without iteration).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-03-21T20:56:03.000+0000</p> 
        <div class="body">
            <p>Patch and unit tests from Tomek added.</p>

        </div>
    </div>
    </div>

