<h2>ZF-10644: Zend_Service_Twitter should support the 'include_rts' flag for statusUserTimeline()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-11-04T14:54:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-08T11:45:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Corey Frang (gnarf)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13420/Twitter.php.diff">Twitter.php.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There are 3 flags, include_rts, trim_user, and include_entities that are listed on the twitter API documentation that get thrown away by Zend_Service_Twitter() -- I'm having to write my own _Service_Twitter subclass to get around it, because I want to use the include_rts flag.</p>

<p>Twitter API for call: <a href="http://dev.twitter.com/doc/get/statuses/user_timeline">http://dev.twitter.com/doc/get/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Corey Frang (gnarf) on 2010-11-04T14:55:39.000+0000</p> 
        <div class="body">
            <p>This may be related to ZF-8841</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Corey Frang (gnarf) on 2010-11-04T14:57:31.000+0000</p> 
        <div class="body">
            <p>A quick patch to the Zend_Service_Twitter.php to allow these 3 parameters to the API call.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-11-08T11:45:29.000+0000</p> 
        <div class="body">
            <p>Flags added in trunk and 1.11 release branch, with corresponding unit test.</p>

        </div>
    </div>
    </div>

