<h2>ZF-10358: Zend_Date improperly recognize year when date with custom format is created</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-21T14:39:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-06T20:03:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14638/10358.patch">10358.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is an issue while creating new Zend_Date with specific format being set, in this case Twitter-specific date format (in which is e.g. 'created_at' field of zend_service_twitter response).</p>

<p>The date in its pure form is eg. "Sat Aug 21 18:50:20 +0000 2010", which corresponds to the format "EEE MMM d H:m:s ZZZ yyy" in en_US locale.</p>

<p>Example:
$date = new Zend_Date("Sat Aug 21 18:50:20 +0000 2010", 'EEE MMM d H:m:s ZZZ yyy', 'en_US');
echo $date-&gt;get(Zend_Date::ISO_8601);</p>

<p>Expected output:
2010-08-21T18:50:20+00:00</p>

<p>Current output:
2000-08-21T18:50:20+00:00 // the year is 2000 instead of 2010</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andreas Heigl (heiglandreas) on 2010-08-22T23:48:45.000+0000</p> 
        <div class="body">
            <p>Shouldn't it read $date = new Zend_Date("Sat Aug 21 18:50:20 +0000 2010", "EEE MMM d H:m:s ZZZ <em>yyyy</em>", 'en_US');?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ondrej Machulda (ondram) on 2010-08-23T04:26:41.000+0000</p> 
        <div class="body">
            <p>In fact, in this case is the output weird as well:</p>

<p>{{0-08-21T18:50:20+00:00}}</p>

<p>Looks like the year is not recognized at all...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christoph Kempen (webpatser) on 2011-04-24T22:09:15.000+0000</p> 
        <div class="body">
            <p>same happens in ZF 1.11.5</p>

<p>This is my workaround:</p>

<pre class="highlight"><code>
$date = new Zend_Date( strtotime($tweet['created_at']) );
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lucas Corbeaux (lucas.corbeaux@gmail.com) on 2011-09-06T20:03:42.000+0000</p> 
        <div class="body">
            <p>Still happens in 1.11.10.</p>

<p>The problem seems to be in Zend_Locale_Format : the _parseDate() method ignore the ZZZZ format, but consider the date part 0000 as the year instead of 2010.</p>

<p>I add a patch that solves the problem for me.</p>

        </div>
    </div>
    </div>

