<h2>ZF-10813: Setting the fetch mode during initialization (or in the config)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-12T07:23:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend\Db\Db the constant FETCH_MODE somehow got lost although it is present in the current 1.x release. The same is with the setting of the $_fetchMode property in the constructor of Zend\Db\Adapter\AbstractAdapter.</p>

<p>I wasn't sure if I should reopen this ticket: <a href="http://framework.zend.com/issues/browse/ZF-6620">http://framework.zend.com/issues/browse/ZF-6620</a> as it is related to the 1.x branch and this only affects 2.0.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-12T07:40:50.000+0000</p> 
        <div class="body">
            <p>I will make the push to the git so how another issues fixed in version greater than 1.10.x.</p>

<p>Greetings
Ramon</p>

        </div>
    </div>
    </div>

