<h2>ZF-10243: Zend_Gdata_App, using $this when not in object context</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-07-28T15:57:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-02-13T17:38:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.2 (25/Feb/13)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15231/App.php.patch">App.php.patch</a></li>
            <li><a href="/issues/secure/attachment/15233/AppTest.php.patch">AppTest.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Gdata_App, line 728</p>

<pre class="highlight"><code>
    public static function import($uri, $client = null,
        $className='Zend_Gdata_App_Feed')
    {
        $app = new Zend_Gdata_App($client);
        $requestData = $app-&gt;prepareRequest('GET', $uri);
        $response = $app-&gt;performHttpRequest(
            $requestData['method'], $requestData['url']);

        $feedContent = $response-&gt;getBody();
        if (!$this-&gt;_useObjectMapping) {
            return $feedContent;
        }
        $feed = self::importString($feedContent, $className);
        if ($client != null) {
            $feed-&gt;setHttpClient($client);
        }
        return $feed;
    }
</code></pre>

<p>This static function has $this inside.</p>

<p>Actually it's my IDE which highlighted the file as containing errors and I don't know when exactly this function is called and if it's really needed, but it just looks so wrong.</p>

<p>Perhaps it works with 5.2 php version, with &gt; 5.3 such a function will cause fatal error.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-07-28T18:39:56.000+0000</p> 
        <div class="body">
            <p>By the way, please someone unittest this...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-01-18T08:08:47.000+0000</p> 
        <div class="body">
            <p>Patch and unit test added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-02-13T17:38:15.000+0000</p> 
        <div class="body">
            <p>Fixed on trunk (25258) and release-1.12 (25259)</p>

        </div>
    </div>
    </div>

