<h2>ZF-11774: finding zend version not working</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-28T07:24:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-05T22:34:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                vimalnath (vimalnath53)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Version</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Version::getLatest();
this doesnt work 
but this works: Zend_Version::compareVersion('2.0.0');</p>

<p>Let me know the reason.
Regards,
Vimal</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pierre Jolly (shady) on 2011-09-30T00:49:05.000+0000</p> 
        <div class="body">
            <p>This works for me, try to update your ZF version.
Regards,
Pierre</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-03-05T22:34:26.000+0000</p> 
        <div class="body">
            <p>This is likely an issue with your PHP configuration.  The {{getLatest}} method uses PHP's {{fopen}} function to read the latest ZF version from <a href="http://framework.zend.com/api/zf-version">http://framework.zend.com/api/zf-version</a>.  If your PHP installation blocks using {{fopen}} with URLs the method will not work.</p>

        </div>
    </div>
    </div>

