<h2>ZF-12442: libxml_disable_entity_loader() call in ZF 1.12</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-10-15T13:23:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-21T13:49:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.1 (18/Dec/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,
  I have updated from ZF 1.11 to ZF 1.12 and found that I can`t use my SOAP calls. In Zend/Soap/Server.php on line 732 is method libxml_disable_entity_loader() called, but this method is available from PHP &gt;= 5.2.11. I am running on</p>

<pre class="highlight"><code>PHP 5.2.0-8+etch16 (cli)
</code></pre>

<p>and actually can not update until some issues are fixed or reimplemented. In install requirements instructions for ZF 1.12 you write that you need minimum PHP 5.2.4 or later (<a href="http://framework.zend.com/manual/1.12/en/requirements.introduction.html">http://framework.zend.com/manual/1.12/…</a>) so that is also my fault we run on 5.2.0 but this method libxml_disable_entity_loader() is only available from PHP 5.2.11. (<a href="http://php.net/manual/en/function.libxml-disable-entity-loader.php">http://php.net/manual/en/…</a>) So do you think about providing some patch for this (that would be just awesome) or will you update the requirements install instructions for ZF 1.12 for this issue and change the minimal version from 5.2.4 as you write to 5.2.11?</p>

<pre class="highlight"><code>
Zend recommends the most current release of PHP for critical security and performance enhancements, and currently supports PHP 5.2.11 or later.
</code></pre>

<p>Thank you very much for your time&amp;effort!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:17:28.000+0000</p> 
        <div class="body">
            <p>As this is the result of a security fix, we have updated the minimum version of PHp for ZF 1.12 to be 5.2.11</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Karel Trcalek (kareltrcalek) on 2012-11-21T09:48:18.000+0000</p> 
        <div class="body">
            <p>Hi, 
  thank you for new info.
In ZF v. 1.12. documentation is still written PHP 5.2.4
Thanks for your time.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-21T10:08:31.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>Where are you looking?  The change so far has been made in the source code.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Karel Trcalek (kareltrcalek) on 2012-11-21T10:16:30.000+0000</p> 
        <div class="body">
            <p>Hi, 
 here, to reference manual <a href="http://framework.zend.com/manual/1.12/en/requirements.introduction.html">http://framework.zend.com/manual/1.12/…</a>
Karel</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-21T13:49:20.000+0000</p> 
        <div class="body">
            <p>Okay. That should automatically change when we release 1.12.1.</p>

        </div>
    </div>
    </div>

