<h2>ZF-10491: addDisplayGroup with variable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-09-23T02:38:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-23T13:39:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Martin Keckeis (thadafinser)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Richard Tuin (richardtuin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10731">ZF-10731</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13467/ZF-10491-rtuin.patch">ZF-10491-rtuin.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>i use Zend_Form myself in this form:</p>

<p>$phone = new Zend_Form_Element_Text('phoneNr');
$phone-&gt;setLabel('phoneNr');
$phone-&gt;setFilters(array('StringTrim'));
$phone-&gt;setValue($this-&gt;_data-&gt;phoneNr);
$this-&gt;addElement($phone);</p>

<p>When i want to add such a form element to a display group, i have to type the "id" of the element, instead of the variable:</p>

<p>$this-&gt;addDisplayGroup(array('phoneNr'), 'name', ...);</p>

<p>Better would be:
$this-&gt;addDisplayGroup(array($phone), 'name', ...);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-19T10:29:53.000+0000</p> 
        <div class="body">
            <p>I think it would make sense to implement this functionality.
Precondition should be that the element defined in the variable is already added to the Zend_Form instance to be consistent with the current functionality.</p>

<p>I've uploaded a patch that enables this functionality, and a unit test.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-20T02:36:09.000+0000</p> 
        <div class="body">
            <p>[SVN:r23412:bittarman] ZF-10491: Applying patch from Richard Tuin (See: <a href="http://tinyurl.com/2853nos">http://tinyurl.com/2853nos</a>)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-21T05:23:02.000+0000</p> 
        <div class="body">
            <p>Merged to branch release 1.11 r23422.</p>

        </div>
    </div>
    </div>

