<h2>ZF-10135: Zend_Filter_NormalizedToLocalizedTest::testLocalizationToFloat presents failed</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-07-11T13:12:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-12T10:37:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.7 (28/Jul/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
Zend_Filter_NormalizedToLocalizedTest::testLocalizationToFloat
failed filter of '1234.5678'
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-1.234,56
+1.234,57
</code></pre>

<p>Information additional
||Tool||Version||
|PHPUnit|3.4.5|
|PHP-CLI|5.2.10|</p>

<p>Thanks very advance</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-07-12T10:37:15.000+0000</p> 
        <div class="body">
            <p>Fixed as duplicate of ZF-10090</p>

        </div>
    </div>
    </div>

