<h2>ZF-11596: ZendX's unit tests fail with 1 error and 4 failures</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-23T11:18:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-27T08:32:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kim Blomqvist (kblomqvist)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_Console_Process_Unix</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10460">ZF-10460</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14533/ZF-11596.patch">ZF-11596.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Steps to reproduce:</p>

<pre class="highlight"><code>
cd /path/to/zf-extras/tests
phpunit --include-path=/path/to/zf/tests AllTests.php
</code></pre>

<p>Test results:</p>

<pre class="highlight"><code>
There was 1 error:

1) ZendX_JQuery_Form_DecoratorTest::testUiWidgetPaneRenderingNoPaneWhenElementHasNoView
Zend_Form_Decorator_Exception: UiWidgetPane Decorators have to have a jQueryParam 'title' to render. This title can been set via setJQueryParam('title') on the parent element.

zf-extras/library/ZendX/JQuery/Form/Decorator/UiWidgetPane.php:115
zf-extras/library/ZendX/JQuery/Form/Decorator/UiWidgetPane.php:137
zf-extras/tests/ZendX/JQuery/Form/DecoratorTest.php:168

--


There were 4 failures:

1) ZendX_Console_Process_UnixTest::testAutomaticEnding
Failed asserting that </code></pre>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-07-23T15:54:01.000+0000</p> 
        <div class="body">
            <p>Patch attached...</p>

<p>I have removed the following test method because {{getView()}} inside the {{render()}} method will always return a view because it will be created if not set.</p>

<pre class="highlight"><code>
-    public function testUiWidgetPaneRenderingNoPaneWhenElementHasNoView()
-    {
-        $spinner = new ZendX_JQuery_Form_Element_Spinner("spinner1");
-
-        $pane = new ZendX_JQuery_Form_Decorator_TabPane();
-        $pane-&gt;setElement($spinner);
-
-        $this-&gt;assertEquals("justthis", $pane-&gt;render("justthis"));
-    }
-
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-07-29T03:29:28.000+0000</p> 
        <div class="body">
            <p>Set components and Auto-reassign</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-07-29T04:51:35.000+0000</p> 
        <div class="body">
            <p>Related with issue ZF-10460</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-04-27T08:31:56.000+0000</p> 
        <div class="body">
            <p>For ZendX_JQuery all tests passed. (Version 1.11.11)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-04-27T08:32:43.000+0000</p> 
        <div class="body">
            <p>ZendX_JQuery removed as an affected component.</p>

        </div>
    </div>
    </div>

