<h2>ZF-12190: Zend_Soap_AutoDiscover shows stranger behavior after migration on productive server</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-05-08T14:49:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-29T21:42:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Andre Flathmann (anfla)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>First of all:
On my local installation, the WSDL shows all datatypes correct by their type: xsd:string, xsd:int, soap-enc:Array, and so on..!
On my webserver, the WSDL shows ALL datatypes as xsd:anyType..!</p>

<p>My Soap-Client, which I use to test the functionality, doesn't show any results of my calls. There are no errors and even the easiest data dumps aren't displayed.</p>

<p>The configuration of my webserver and my local server are almost identical. I'm using, in both cases, lighttpd as server.</p>

<p>PHP version local: 5.3.5
PHP version productive: 5.3.2</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andre Flathmann (anfla) on 2012-05-09T07:10:54.000+0000</p> 
        <div class="body">
            <p>Small update: The methods of my webservice DO work. I let them write some textfiles on my server. But none of them returns any data. I assume it's because of the wrong data types inside of my wsdl. (As said in my first post) But I can't explain how it's possible, that my webserver can't identify any data type. It makes no sense to me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andre Flathmann (anfla) on 2012-05-09T08:16:40.000+0000</p> 
        <div class="body">
            <p>I was able to fix the problem with the incorrect data types. My webserver used eAccelerator, which doesn't work well with Zend_Soap_AutoDiscover. But my main problem remains: My webservice methods still don't return any values if I call them on my webserver. (Doesn't matter where they are called from)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andre Flathmann (anfla) on 2012-05-09T11:30:24.000+0000</p> 
        <div class="body">
            <p>Resolved.. I needed to filter the file with ini_set(). Disabling eAccelerator didn't work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-09T12:32:43.000+0000</p> 
        <div class="body">
            <p>Could you explain how {{ini_set}} fixed your problem, so future visitors can learn from your experience?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christoph Roensch (croensch) on 2012-10-29T21:42:30.000+0000</p> 
        <div class="body">
            <p>Had that too long time ago. eAccelerator makes reflection blind to what you have documented on your server class. Still you can disable it on a script basis before including your server class. To use the manual as an example:</p>

<pre class="highlight"><code>
/**
 * disable eAccelerator when installed
 */
if (ini_get('eaccelerator.enable')) {
    ini_set('eaccelerator.enable', 0);
}
/**
 * include 'My_SoapServer_Class' or let the autoloader include it
 */ 
$autodiscover = new Zend_Soap_AutoDiscover();
$autodiscover-&gt;setClass('My_SoapServer_Class');
$autodiscover-&gt;handle();
</code></pre>

        </div>
    </div>
    </div>

