<h2>ZF-10875: Zend_Locale_Format does not honor Zend_Registry::set('Zend_Locale', ...);</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-12-28T08:33:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The documentation states:</p>

<p>"... simply set an instance of Zend_Locale to the registry with the key 'Zend_Locale'. Then this instance will be used within all locale aware classes of Zend Framework. ..."</p>

<p>But with Zend_Locale_Format this is not true:</p>

<p>--- snip ---</p>

<p>// Just to be sure: set PHP locale to something else
setlocale(LC_ALL, "de");</p>

<p>// Instantiate and register a new Zend_Locale
$locale_en = new Zend_Locale('en');
Zend_Registry::set('Zend_Locale', $locale_en);</p>

<p>echo Zend_Locale_Format::toNumber(4711.0815);   // WRONG: 4.711,0815 (german as per setlocale)
echo "<br />\n";</p>

<p>// This works as expected:
$date = new Zend_Date();
echo $date-&gt;get(Zend_Date::WEEKDAY);        // OK - english weekday
echo "<br />\n";</p>

<p>// This extra step is required to make it work:
Zend_Locale_Format::setOptions(array("locale"=&gt;$locale_en));</p>

<p>echo Zend_Locale_Format::toNumber(4711.0815);   // OK: 4,711.0815 (english as per Zend_Locale)
echo "<br />\n";</p>

<p>--- snap ---</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-12-29T00:45:42.000+0000</p> 
        <div class="body">
            <p>A feature which does not exist in a class is an improvement and not a bug :-)</p>

        </div>
    </div>
    </div>

