<h2>ZF-1416: Can't set helper class prefix with addBasePath</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-05-22T02:36:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC1 (28/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ivan Shumkov (shumkov)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>method addBasePath set standart ('Zend_View_Helper') prefix to helpers and i can't change it. May be add second argument?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-05-22T07:00:22.000+0000</p> 
        <div class="body">
            <p>This was added in revision 4838 on 17 May 2007 (the class prefix argument was also added to setBasePath()). Please get a recent checkout from subversion or update your current checkout.</p>

        </div>
    </div>
    </div>

