<h2>ZF-11075: Modified numbers in source</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-02-15T01:56:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-15T01:56:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jeff Blu (jeffblu)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend Extension =&gt; 220060519
Zend Engine v2.2.0</p>

<p>Zend_Http_Client modifies certain numbers in retrieved source.</p>

<p>1.) Fetch URL <a href="http://www.immobilienscout24.de/Suche/S-T/Anlageobjekte/Hessen/Frankfurt-am-Main">http://immobilienscout24.de/Suche/S-T/…</a> and output HTML</p>

<pre class="highlight"><code>
$client = 
  new Zend_Http_Client(
    null,
    array(
      'keepalive'    =&gt; true,
      'maxredirects' =&gt; 5,
      'timeout'      =&gt; 10,
    )
  );

$client-&gt;setAdapter($adapter = new Zend_Http_Client_Adapter_Curl());

$client-&gt;setUri("http://www.immobilienscout24.de/Suche/S-T/Anlageobjekte/Hessen/Frankfurt-am-Main");
$html = $client-&gt;request(Zend_Http_Client::GET)-&gt;getBody();

var_dump($html);
</code></pre>

<p>2.) Look for Markup</p>

<pre class="highlight"><code>

3.) Look at the price after this markup. You probably need to check futher occurences.

4.) In my example one occurence was:
</code></pre>

<p>whereas the real code (checked with Firefox/IE) is
```</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

