<h2>ZF-1818: Create utilities to construct Feed and Entry URLs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-08-06T12:10:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-08-28T16:03:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The feed and entry URLs in GData APIs are frequently composed from a template consisting of things like "user", "security", "projection".   It might be helpful for users of services if there were a library distributed with each service's client lib that did the URL construction for you.</p>

<p>So from a user's point of view, a feed would be requested not by providing a URL, but by providing the parameters that instantiate the URL template.  The user would not necessarily see the URL itself.</p>

<hr /><p>NOTE: These utilities exist for many of the PHP client lib services, but we need to verify that they exist for all before closing out this bug.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2007-08-28T16:03:03.000+0000</p> 
        <div class="body">
            <p>As far as I can tell, the PHP client lib already does this for all supported services.</p>

        </div>
    </div>
    </div>

