<h2>ZF-11579: Resource_View should not create ViewRenderer object itself</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-19T12:16:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-28T20:40:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.10 (04/Aug/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>ZA_Resource_View creates itself a ViewRenderer and registers it in the HelperBroker stack.
It should not create the ViewRenderer, but instead, rely on HelperBroker to lazy-load it.</p>

<p>When back-adding the created ViewRenderer into HelperBroker, it is created with a wrong name into the HelperBroker stack.
Then, if ZA_Resource_View gets loaded <em>after</em> a plugin that did play with the ViewRenderer, we got two ViewRenderer objects in memory.</p>

<pre class="highlight"><code>
// diff
public function init()
    {
        $view = $this-&gt;getView();

-       $viewRenderer = new Zend_Controller_Action_Helper_ViewRenderer();
+       $viewRenderer = Zend_Controller_Action_HelperBroker::getStaticHelper('viewRenderer');
        $viewRenderer-&gt;setView($view);
-       Zend_Controller_Action_HelperBroker::addHelper($viewRenderer);
        return $view;
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-28T20:40:02.000+0000</p> 
        <div class="body">
            <p>Added a test for this, and applied the patch in trunk and the 1.11 release branch. Thanks!</p>

        </div>
    </div>
    </div>

