<h2>ZF-1891: Automatically synchronize Info structure and Metadata document</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-08-29T18:16:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-31T08:45:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Document properties can be retrieved and stored using properties document attribute:</p>

<pre class="highlight"><code>
echo $pdf-&gt;properties['Title'];
</code></pre>

<p>and Metadata document:</p>

<pre class="highlight"><code>
$metadata = $pdf-&gt;getMetadata();
</code></pre>

<p>Both method information structures should be automatically synchronized.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:12:04.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christopher Thomas (cwt137) on 2009-12-18T06:19:27.000+0000</p> 
        <div class="body">
            <p>I'm willing to work on this, but there is only one solution I can think of. It is easy to sync the properties and metadata when the developer calls setMetadata(), but there is no setProperties() method. This prevents syncing when the properties is updated. I think the solution is to make the properties attribute protected and then create a getter and setter for it. Then the developer is forced to use the setProperties() method and this will ensure the metadata will be synced. The only problem with this solution is that it changes the API. How do you feel about this Alex?</p>

<p>I thought of just doing the syncing when the pdf is being rendered/saved, but decided it was not a good idea. For example, there might be the title "foo" in the properties and the title "bar" in the metadata. Which way do you sync? This is why I thought the API change way is the way to implement this feature.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-12-18T07:39:31.000+0000</p> 
        <div class="body">
            <p>It's possible to use ArrayObject to intercept array elements update.</p>

<pre class="highlight"><code>
class MyCoolArray extends ArrayObject {
    public function offsetSet($index, $newval) {
        printf("Set operation: array[%s] = '%s'\n", $index, $newval);

        parent::offsetSet($index, $newval);
    }
}

$a = new MyCoolArray();
$a[5] = 'some_value';
</code></pre>

<p>produces
{panel}
Set operation: array[5] = 'some_value'
{panel}</p>

        </div>
    </div>
    </div>

