<h2>ZF-11276: Zend_Validate_Between</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-04-09T09:55:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-16T22:21:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>validating</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6577">ZF-6577</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>H Zend Team, like i saw the Zend_Validate_Between supports only english float values like "2.09".
It would be an good if it would support europe float convetion like "2,09".
Here is my sulution:
 Replace isValid Mehtod by this:</p>

<p>public function isValid($value) {
    $this-&gt;_setValue($value);</p>

<pre><code>$filter = new Zend_Filter_PregReplace(array('match' =&gt; '/\,/',
                                            'replace' =&gt; '.'));
$value = $filter-&gt;filter($value);

if ($this-&gt;_inclusive) {
    if ($this-&gt;_min &gt; $value || $value &gt; $this-&gt;_max) {
        $this-&gt;_error(self::NOT_BETWEEN);
        return false;
    }
} else {
    if ($this-&gt;_min &gt;= $value || $value &gt;= $this-&gt;_max) {
        $this-&gt;_error(self::NOT_BETWEEN_STRICT);
        return false;
    }
}
return true;
</code></pre>

<p>}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-04-09T20:20:51.000+0000</p> 
        <div class="body">
            <p>Duplication of ZF-6577</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-04-09T20:22:55.000+0000</p> 
        <div class="body">
            <p>Closing as duplicate</p>

<p>Note that the attached patch will not be integrated as it's behaviour is errorous.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Samuel (michizend) on 2011-04-10T21:15:54.000+0000</p> 
        <div class="body">
            <p>Because of the $this-&gt;_setValue($value); , or? filter than may fail?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-04-16T22:21:34.000+0000</p> 
        <div class="body">
            <p>No.. the preg_replace itself would allow german numbers be validated in english environment and visa-versa.
When we support localization then eighter all or non.
The other issue was intended to add full localization.
Therefor closing as duplicate and non-integration for this issue.</p>

        </div>
    </div>
    </div>

