<h2>ZF-1466: Include error file and line number in error messages</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-05-31T10:34:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-14T14:57:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Posting on behalf of [~coogle]:</p>

<p>Include the file and line # in your work around to throw exceptions on session start; otherwise when that error actually happens the error is meaningless without knowing where in your code it actually was thrown.</p>

<p>Example solution below:</p>

<pre class="highlight"><code>
class Zend_Session_Exception
{
    static public function handleSessionStartError($errno, $errstr, $file, $line)
    {
        self::$sessionStartError = $errstr . " ($file:$line)";
    }
}
</code></pre>

<p>Probably this should also be done for the {{handleSilentWriteClose()}} method; hiding error information cannot be good. ;)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Karol Grecki (antych) on 2007-05-31T11:29:30.000+0000</p> 
        <div class="body">
            <p>You can print a very nice compact stack trace using Exception::_toString() method.
It gives you all the information you need.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-02-14T14:57:25.000+0000</p> 
        <div class="body">
            <p>Karol, that is correct.  And since this Exception/error handling code is isolated to a very specific call session_start, there is little need to add any information to the error message itself (since the exception stack has line and file information in it).</p>

        </div>
    </div>
    </div>

