<h2>ZF-10927: Database query result gets truncated</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-01-07T13:45:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-08T11:10:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm in the process of creating an application based on ZF 1.10.8. This application utilizes a world border dataset that is stored in a MySQL database table (version 4.1.22). That table  keeps country borders as multi-polygons in the geometry type column. Retrieving borders geometry I found the following problem:
when I use Zend_Db_Table the query results gets truncated, I can't get more that 8192b of data. I repeated this task without ZF, just using build-in MySQL access functions (PHP version 5.1.6) and could get data in full. Here is the code:
1. With ZF</p>

<pre class="highlight"><code>
class Application_Model_DbTable_Borders extends Zend_Db_Table_Abstract
{
    protected $_name = 'borders';
    protected $_primary = 'OGR_FID';
    public function getAllBorders()
    {
        $select = $this-&gt;select();
        $select-&gt;from($this-&gt;_name, array('iso2','name', 'AsText(Shape) AS wkt'));
        $select-&gt;where('iso2 = ?', 'AT');
        $rowset = $this-&gt;fetchAll($select);
        if (count($rowset) == 0) {
            throw new Exception("Could not get borders");
        }
        $wkt = $rowset[0]-&gt;wkt;
            $l = strlen($wkt);
            echo 'L = ' . $l . '<br />';
        return $rowset;
    }
}
//L = 8192
</code></pre>

<ol><li>Without ZF</li>
</ol><pre class="highlight"><code>
$link = mysql_connect('localhost', '*****', '*****');
if (!$link) {
    die('Could not connect: ' . mysql_error());
}

if (!mysql_select_db('CO2_Emissions', $link)) {
    die('Could not select database<br />');
}

$sql    = "SELECT iso2, name, AsText(Shape) AS wkt FROM borders where iso2 = 'AT'";
$result = mysql_query($sql, $link);

if (!$result) {
    $error = mysql_error();
    die($error);
}

$row = mysql_fetch_assoc($result);
$l = strlen($row['wkt']);
mysql_free_result($result);
echo 'L = ' . $l;

//L = 11714
</code></pre>

<p>Thank you,
Misha</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2011-01-08T07:01:49.000+0000</p> 
        <div class="body">
            <p>As you note php version 5.1.6 in your description of the problem, could you confirm that you are not using this version with ZF, as the minimum requirement is 5.2.4.</p>

<p>if you are using &lt; 5.2.4, could you try upgrading, and confirming that this is still the case?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Misha Krassovski (mkrassovski) on 2011-01-14T11:58:19.000+0000</p> 
        <div class="body">
            <p>I'm sorry for the late reply! To make a long story short - I'm in the process of upgrading to something that will be &gt;= 5.2.4. As soon as it will be done, I'll test it again and let you know if the problem remains.</p>

<p>Thank you,
Misha</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-01-22T08:21:00.000+0000</p> 
        <div class="body">
            <p>I am unable to reproduce.  If you still have this issue after upgrading to 5.2.4+, please feel free to reopen.</p>

<p>Things to do before-so: make sure that the code you use is consistent with the driver for Zend_Db. For example, if your adapter is using mysqli_* functions, please test that extension.  If you are using Pdo with Mysql, then test that accordingly.</p>

<p>What I think is happening is you are hitting your lob_buffer_size in mysql with whichever extension you are using, perhaps tweak your settings in that regard.</p>

<p>If you still have the issue, reopen with some code (SQL data and row included) that we can use to reproduce the issue,</p>

<p>Thanks!
Ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-22T08:26:56.000+0000</p> 
        <div class="body">
            <p>@ralph
I believe that you forgot of close this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Misha Krassovski (mkrassovski) on 2011-02-08T11:10:00.000+0000</p> 
        <div class="body">
            <p>Ok, finally I upgraded everything and after having PHP 5.3.2 and ZF 1.11.3 all started to work as it supposed. Just want to confirm that the issue was due to the incorrect version of PHP and is resolved.
Thank you for your help!
Misha</p>

        </div>
    </div>
    </div>

