<h2>ZF-11412: Generating signed URL for private Bucket Object using Zend_Service_Amazon_S3</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2011-05-26T11:28:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-26T11:30:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Atkinson (layke)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Enrico Zimuel (zimuel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently there is no way using Zend_Service_Amazon_S3 to generate a time limited signed URL to access an object which has ACL_PRIVATE rules set for that resource.</p>

<p>The equivalanet Amazon S3 PHPSDK class is</p>

<pre class="highlight"><code>
/**
     * Gets the web-accessible URL for the Amazon S3 object or generates a time-limited signed request for
     * a private file.
     *
*/
public function get_object_url(){}
</code></pre>

<p>Avaialble to see: 
<a href="https://github.com/amazonwebservices/aws-sdk-for-php/blob/master/services/s3.class.php">https://github.com/amazonwebservices/…</a></p>

<p>Amazon Docs explaining usage and setting an Expiration time. 
<a href="http://docs.amazonwebservices.com/AWSSDKforPHP/latest/#m=AmazonS3/get_object_url">http://docs.amazonwebservices.com/AWSSDKforPHP/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

