<h2>ZF-11800: &lt;/form&gt; always included with form helper</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-06T19:01:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-19T01:05:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ketil Stadskleiv (stadskle)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
            <li>bug</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11747">ZF-11747</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This just happend when I upgrades to 1.11.11 is it is destroying all my forms. Hence the critical setting, for us who is using this extensively to create the form starter (but doing the form manually) this is critical.</p>

<p>The documentation states:</p>

<p>"form($name, $attribs, $content): Generates an XHTML form. All $attribs are escaped and rendered as XHTML attributes of the form tag. If $content is present and not a boolean FALSE, then that content is rendered within the start and close form tags; if $content is a boolean FALSE (the default), only the opening form tag is generated. "</p>

<p>So, if no content variable is set (or set to false) the  should not be included. However, in 1.11.11 this does not work. Looking at the code, the last part of the helper looks like this:</p>

<p>if (false !== $content) {
   $xhtml .= $content;
}
$xhtml .= '';</p>

<p>So it is obvious that  is included every time regardless of the value of $content. The code should be like this:</p>

<p>if (false !== $content) {
   $xhtml .= $content;
   $xhtml .= '';
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-06T20:11:30.000+0000</p> 
        <div class="body">
            <p>See ZF-11747 (specifically, <a href="http://framework.zend.com/issues/browse/ZF-11747?focusedCommentId=48602&amp;page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-48602">this comment</a>)</p>

        </div>
    </div>
    </div>

