<h2>ZF-11636: Zend_Application_Resource_Multidb with CacheManager doesn't cache</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-08-02T15:02:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-16T20:25:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
            <li>cache</li>
            <li>multidb</li>
            <li>zend</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have configured Multidb with CacheManager as per documentation (see below). No errors in logs, full access to filesystem, everything should work like charm, the only problem is that no cache is created...</p>

<p>1) CacheManager configuration:
resources.cachemanager.database.frontend.name = Core
resources.cachemanager.database.frontend.customFrontendNaming = false
resources.cachemanager.database.frontend.options.lifetime = 7200
resources.cachemanager.database.frontend.options.automatic_serialization = true
resources.cachemanager.database.backend.name = File
resources.cachemanager.database.backend.customBackendNaming = false
resources.cachemanager.database.backend.options.cache_dir = APPLICATION_PATH "/../temp/cache"
resources.cachemanager.database.frontendBackendAutoload = false</p>

<p>2) Multidb configuration:
resources.multidb.defaultMetadataCache = "database"</p>

<p>resources.multidb.db1.adapter = "pdo_mysql"
resources.multidb.db1.host = "localhost"
resources.multidb.db1.username = "webuser"
resources.multidb.db1.password = "XXXX"
resources.multidb.db1.dbname = "db1"
resources.multidb.db1.default = true</p>

<p>resources.multidb.db2.adapter = "pdo_pgsql"
resources.multidb.db2.host = "example.com"
resources.multidb.db2.username = "dba"
resources.multidb.db2.password = "notthatpublic"
resources.multidb.db2.dbname = "db2"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-08-06T04:35:09.000+0000</p> 
        <div class="body">
            <p>Exists a problem before 1.11.1 but already was fixed.
See here a reproduce <a href="https://gist.github.com/1129015">https://gist.github.com/1129015</a>.</p>

<p>Greetings
Ramon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-08-13T09:10:07.000+0000</p> 
        <div class="body">
            <p>Feel free to reopen case are given more information. 
See  <a href="http://ralphschindler.com/2010/02/18/the-anatomy-of-a-bug-issue-reproduction-script">http://ralphschindler.com/2010/02/…</a></p>

<p>Greetings
Ramon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eugene Istrati (eistrati) on 2011-08-16T20:25:39.000+0000</p> 
        <div class="body">
            <p>Why this issue was closed? It is not fixed at all... I am expecting caching files to be created in APPLICATION_PATH "/../temp/cache", but instead it does nothing!</p>

        </div>
    </div>
    </div>

