<h2>ZF-1151: FrontControllers phpDocs typing error. Makes code completion difficult for IDEs.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2007-03-28T06:13:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.2 (06/Apr/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is a typo, or maybe leftover after earlier versions of framework, in Zend_Controller_Front::getDispatcher() phpDocs at line 450
{{* @return Zend_Controller_DispatcherInteface}}
It should be fixed to
{{* @return Zend_Controller_Dispatcher_Interface}}
in order to correct code completion.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-28T09:53:24.000+0000</p> 
        <div class="body">
            <p>Assigning to [~matthew].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-04-02T12:08:46.000+0000</p> 
        <div class="body">
            <p>Resolved in r4309</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alan Gabriel Bem (alan.bem) on 2007-04-02T17:52:20.000+0000</p> 
        <div class="body">
            <p>Hehe, it is fixed only partially - typo still exists.</p>

<pre class="highlight"><code>
* @return Zend_Controller_Dispatcher_Inteface
</code></pre>

        </div>
    </div>
    </div>

