<h2>ZF-11783: Zend_Amf_Response_Http emits notice when $_SERVER['HTTPS'] not defined</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-30T16:41:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-11-09T17:22:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.12 (22/Jun/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5012">ZF-5012</a></li>
            <li><a href="/issues/browse/ZF-11776">ZF-11776</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Just upgraded from Zend AMF 1.11.10 to 1.11.11 and tried running my Flex application. It failed and the following error was generated:</p>

<h1>Undefined index: HTTPS</h1>

<h1>0  include() called at [/RCMS/Kernel/Bootstrap.php:16]</h1>

<h1>1  errorHandler(8, Undefined index: HTTPS, /Zend/Amf/Response/Http.php, 59, Array()) called at [/Zend/Amf/Response/Http.php:59]</h1>

<h1>2  Zend_Amf_Response_Http-&gt;isIeOverSsl() called at [/Zend/Amf/Response/Http.php:44]</h1>

<h1>3  Zend_Amf_Response_Http-&gt;getResponse() called at [/Zend/Amf/Response.php:147]</h1>

<h1>4  Zend_Amf_Response-&gt;__toString() called at [/DesktopAMF.php:58]</h1>

<p>========</p>

<p>Line 59 of Http.php reads:</p>

<p>$ssl = $_SERVER['HTTPS'];</p>

<p>Changing it to the following code resolves the issue:</p>

<p>$ssl = isset($_SERVER['HTTPS']);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-24T01:11:16.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r24523 r24524.
Merged to release-1.11 in r24525.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jani Mikkonen (janisto) on 2011-11-09T10:43:44.000+0000</p> 
        <div class="body">
            <p>I think it would be better to check it like this:</p>

<pre class="highlight"><code>
$ssl = false;
if ( isset($_SERVER['HTTPS']) &amp;&amp; ($_SERVER['HTTPS'] == 'on' || $_SERVER['HTTPS'] == 1)
  || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) &amp;&amp; $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') {
    $ssl = true;
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-11-09T17:22:17.000+0000</p> 
        <div class="body">
            <p>There has been discussion about HTTP_X_FORWARDED_PROTO in the past (see ZF-5012) and it was agreed then that we shouldn't rely on it.</p>

        </div>
    </div>
    </div>

