<h2>ZF-10544: Duplicate ID used in ZF programmer's guide docbook</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-10-10T19:49:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-19T06:32:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Quentin Zervaas (qzervaas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the following file:</p>

<p>en/module_specs/Zend_Http_UserAgent-Features_Wurfl.xml</p>

<p>In the section with ID "zend.http.user-agent-features-wurfl.methods", the refentry uses a duplicate ID</p>

<p>It uses "zend.http.user-agent-features.methods.get-from-request" but it should probably use something like "zend.http.user-agent-features-wfurl.methods.get-from-request"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-10-19T06:32:13.000+0000</p> 
        <div class="body">
            <p>Fixed just prior to the 1.11.0beta1 release.</p>

        </div>
    </div>
    </div>

