<h2>ZF-1191: Failure in Zend_Auth_Adapter_Http_ProxyTest</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-04-03T17:53:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-05T14:16:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bryce Lohr (gearhead)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>PHPUnit 3.0.0
PHP 5.2.0
Windows XP sp1
Xdebug 2.0.0RC1</p>

<p>Output of phpunit includes:</p>

<pre class="highlight"><code>
  Zend Framework - Zend_Auth
   Zend Framework - Zend_Auth Adapters
    Zend Framework - Zend_Auth_Adapter_Http
     Zend_Auth_Adapter_Http_ProxyTest
     .F.........
</code></pre>

<p>One failure.  I have expanded the output to make it more readable.</p>

<pre class="highlight"><code>
1) testDigestChallenge(Zend_Auth_Adapter_Http_ProxyTest)
Failed asserting that 

http://localhost/", 
  nonce="7c054837974d3d72ed140353f24097f2", 
  opaque="d75db7b160fe72d1346d2bd1f67bfd10", 
  algorithm="MD5", qop="auth"&gt; 

is equal to 

http://localhost/", 
  nonce="06e6bc0a3818468d0d3478fb757bdc51", 
  opaque="d75db7b160fe72d1346d2bd1f67bfd10", 
  algorithm="MD5", qop="auth"&gt;.

expected string 
http://localhost/", 
  nonce="06e6bc0a3818468d0d3478fb757bdc51", 
  opaque="d75db7b160fe72d1346d2bd1f67bfd10", 
  algorithm="MD5", qop="auth"&gt;

difference      &lt;                                                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&gt;
got string      
http://localhost/", 
  nonce="7c054837974d3d72ed140353f24097f2", 
  opaque="d75db7b160fe72d1346d2bd1f67bfd10", 
  algorithm="MD5", qop="auth"&gt;

C:\zf\tests\Zend\Auth\Adapter\Http\ProxyTest.php:413
C:\zf\tests\Zend\Auth\Adapter\Http\ProxyTest.php:160
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-04-03T18:08:04.000+0000</p> 
        <div class="body">
            <p>Deferring to [~gearhead] for initial comment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bryce Lohr (gearhead) on 2007-04-04T20:37:24.000+0000</p> 
        <div class="body">
            <p>Unfortunately, I'm unable to reproduce the problem. It works fine on my machine, so clearly this caused by an environment difference. Looking at the given output, the difference lies in the value of the nonce field. Something on the machine where this is being run is causing it to calculate a different value for the nonce than my machine does. Logically, either the input to the hash is different, or a very unlikely hash collision has occurred.</p>

<p>I ran the unit tests from a clean SVN checkout, and they were successful. Also, I currently use this Auth adapter every day, and it's still working in the browser. (Of course, that's probably no big surprise, since the unit tests also work for me.)</p>

<p>Another thing to consider is that the same exact code calculates the nonces for both Proxy auth and Origin server auth, so if there was an issue in the adapter, it should cause both the AuthTest.php <em>AND</em> ProxyTest.php to fail, in the same place. However, only ProxyTest.php is failing here, implying the problem is in the unit test itself, on that server.</p>

<p>Hope this helps. Let me know if I can be of any more help.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-05T09:48:48.000+0000</p> 
        <div class="body">
            <p>I also cannot reproduce this error on WinXP, PHP 5.1.4, PHPUnit 3.2.15.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-05T09:50:56.000+0000</p> 
        <div class="body">
            <p>I also cannot reproduce with PHP 5.2.5</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-05T09:52:08.000+0000</p> 
        <div class="body">
            <p>Maybe it's specific to PHP 5.2.0?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-05T14:16:29.000+0000</p> 
        <div class="body">
            <p>No, I can't reproduce on 5.2.0, either. I'm closing as "cannot reproduce" for now; please feel free to reopen with additional information.</p>

        </div>
    </div>
    </div>

