<h2>ZF-1508: Implement CROSS JOIN functionality for DB2</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-06-06T21:01:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-31T09:11:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Salvador Ledezma (ledezma)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3072">ZF-3072</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>DB2 does not support the CROSS JOIN syntax:</p>

<p>SELECT  "zfproducts".*, "zfbugs_products".* FROM "zfproducts" CROSS JOIN "zfbugs_products"</p>

<p>but this query should produce the equivalent result:</p>

<p>SELECT * FROM "zfproducts", "zfbug_products"</p>

<p>To implement this, there should probably be a Zend_Db_Select_Db2 class that inherits from Zend_Db_Select.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-07T11:25:53.000+0000</p> 
        <div class="body">
            <p>Assign to Bill Karwin.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-08T20:50:42.000+0000</p> 
        <div class="body">
            <p>We need to investigate whether this runs afoul of the same SQL semantics that have plagued MySQL 5.0.12.  SQL-99 defined an order of precedence for comma-style and {{JOIN}}-style joins that causes some grief:</p>

<pre class="highlight"><code>
SELECT *
FROM TableA AS a, 
  TableB AS b JOIN TableC AS c ON a.foo = c.bar
</code></pre>

<p>In the above example, SQL-99 says that {{JOIN}} should be evaluated before the comma-join, despite the comma appearing first.  So the correlation name for {{a.foo}} doesn't exist at this time, and the SQL parser gives up.  I don't know whether IBM DB2 implements the SQL-99 semantics, or if it will do so in the future.</p>

<p>The correct solution is to avoid mixing comma-style (aka SQL-89) and {{JOIN}}-style (aka SQL-92), and only use one or the other consistently in a given query.  That's why {{CROSS JOIN}} was defined in SQL-92, so there is a non-comma syntax to perform that type of join.</p>

<p>In any case, it's probably not a high priority to provide {{CROSS JOIN}} support, since few people even know about this syntax.  So I'm marking this issue Postponed for now.</p>

<p>Also, a possible workaround is to use {{INNER JOIN}} with a condition that is always true, resulting in the same query result as a {{CROSS JOIN}}:</p>

<pre class="highlight"><code>
SELECT *
FROM TableA AS a INNER JOIN TableB AS b ON 1 = 1
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-08T20:54:39.000+0000</p> 
        <div class="body">
            <p>Another possibility for extending Zend_Db_Select is that Zend_Db_Select_Db2 implements {{joinCross()}} as:</p>

<pre class="highlight"><code>
public function joinCross($name, $cols = '*', $schema = null)
{
    return $this-&gt;_join(self::INNER_JOIN, $name, '(1 = 1)', $cols, $schema);
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:11:51.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T13:17:30.000+0000</p> 
        <div class="body">
            <p>Reassigning to Ralph since he's the new maintainer of Zend_Db</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-01-09T13:52:25.000+0000</p> 
        <div class="body">
            <p>will evaluate within 2 weeks</p>

        </div>
    </div>
    </div>

