<h2>ZF-11606: getRowCount() dies in Zend_Test_PHPUnit_Db_Connection</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-07-25T11:40:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-25T11:58:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Test_PHPUnit</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>h1. ISSUE
with an test class implementation like this,</p>

<pre class="highlight"><code>
class MyTest extends Zend_Test_PHPUnit_DatabaseTestCase {
  ...
  public function testFoo (){
    ...
    $this-&gt;getConnection()-&gt;getRowCount('guestbook');
    ...
  }
  ...
}

# run it,
$ phpunit MyTest.php
</code></pre>

<p>then you get:
{quote}
Fatal error: Call to a member function query() on a non-object in /path/to/lib/php/PHPUnit/Extensions/Database/DB/DefaultDatabaseConnection.php on line 177
{quote}</p>

<p>h1. PROBLEM
* getRowCount() is not overridden by Zend_Test_PHPUnit_Db_Connection class, the original (parent class) PHPUnit_Extensions_Database_DB_DefaultDatabaseConnection's method is called.
* in this PHPUnit_Extensions_Database_DB_DefaultDatabaseConnection's getRowCount() implementation, it's using the property <em>$this-&gt;connection</em>
* this is not used with Zend_Test_PHPUnit_Db_Connection, <em>$this-&gt;_connection</em> is the correct property to use.
* thus, the non-object call.</p>

<p>h1. THE FIX
* getRowCount() should be overrided by Zend_Test_PHPUnit_Db_Connection
* below is the patch:</p>

<pre class="highlight"><code>
$ cd library/Zend/Test/PHPUnit/Db
$ diff -Naru Connection.php.original Connection.php 
--- Connection.php.original     2011-07-25 20:18:05.000000000 +0900
+++ Connection.php      2011-07-25 20:39:03.000000000 +0900
@@ -147,4 +147,14 @@
         return "DELETE";
     }
 
+    public function getRowCount($tableName, $whereClause = NULL)
+    {
+        $query = "SELECT COUNT(*) FROM ".$this-&gt;quoteSchemaObject($tableName);
+
+        if (isset($whereClause)) {
+            $query .= " WHERE {$whereClause}";
+        }
+
+        return (int) $this-&gt;_connection-&gt;query($query)-&gt;fetchColumn();
+    }
 }
</code></pre>

<p>h1. or...
{quote}
we can fiddle around *__get()* to pass $this-&gt;connection call to $this-&gt;_connection.
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

