<h2>ZF-11716: Problem with filter stringTrim and accented character à</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-09-02T09:24:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-25T09:05:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11752">ZF-11752</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you use String Trim filter in zend_form_element_text and the last char is the special char "à" the validation StringLength return this message:</p>

<p>Notice: iconv_strlen() [function.iconv-strlen]: Detected an incomplete multibyte character in input string in C:\Programmi\Zend\ZendServer\share\ZendFramework\library\Zend\Validate\StringLength.php on line 234</p>

<p>this is the code to reproduce the error:</p>

<pre class="highlight"><code>
class Application_Form_Form extends Zend_Form
{
    public function init()
    {
    $this-&gt;setAttrib('accept-charset', 'UTF-8');        
        $this-&gt;setName("form");
        $this-&gt;setMethod('post');
             
        $this-&gt;addElement('text', 'field', array(
            'filters'    =&gt; array('StringTrim'),
            'validators' =&gt; array(
                array('StringLength', false, array(2, 50,'encoding' =&gt; 'UTF-8')),
            ),
            'required'   =&gt; true,
            'label'      =&gt; 'field',
        ));     
        $this-&gt;addElement('submit', 'submit', array(
            'required' =&gt; false,
            'ignore'   =&gt; true,
            'label'    =&gt; 'submit',
        )); 
    }
}
</code></pre>

<pre class="highlight"><code>
class IndexController extends Zend_Controller_Action
{

    public function init()
    {
        /* Initialize action controller here */
    }

    public function indexAction()
    {
        $form = new Application_Form_Form();
        $request=$this-&gt;getRequest();
        if($request-&gt;isPost()){
            if($form-&gt;isValid($request-&gt;getPost())){
            }
        }

        $this-&gt;view-&gt;form=$form;
    }
}
</code></pre>

<pre class="highlight"><code>

&lt;?php 
echo $this-&gt;form;
?&gt;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-09-03T06:19:24.000+0000</p> 
        <div class="body">
            <p>Code tags added</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-03T07:03:57.000+0000</p> 
        <div class="body">
            <p>The heading says that StringTrim has problems, but the example error message you gave says that StringLength has the problem.
Can you please verify which of the two filters makes problem in your environment and fix heading or example?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-09-03T20:36:19.000+0000</p> 
        <div class="body">
            <p>Closing as duplicate of ZF-11551</p>

        </div>
    </div>
    </div>

