<h2>ZF-1401: Improve code coverage by Zend_Db_Statement tests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-05-16T16:48:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.0 RC3 (23/Jun/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Current code coverage for {{Zend_Db_Statement}} and related classes should be improved. For example, having tested both mysqli and pdo_mysql adapters, code coverage for {{Zend/Db/Statement.php}} was only 47.87%</p>

<ul><li>Revision: 4828</li>
<li>OS: Ubuntu 7.04</li>
<li>PHP: 5.2.1</li>
<li>PHPUnit 3.1.0beta4</li>
<li>Xdebug v2.0.0RC3).</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-05-18T20:38:48.000+0000</p> 
        <div class="body">
            <p>With revision 4874, there are some more tests for Zend_Db_Statement and its subclasses.</p>

<ul><li>Zend_Db_Statement: 66.67% coverage</li>
<li>Zend_Db_Statement_Db2: 61.17% coverage</li>
<li>Zend_Db_Statement_Mysqli: 97.70% coverage</li>
<li>Zend_Db_Statement_Oracle: 71.07% coverage</li>
</ul><p>PDO adapters do not exercise the Zend_Db_Statement classes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-13T19:08:28.000+0000</p> 
        <div class="body">
            <p>As of revision 5256, here are the testing coverage stats:</p>

<ul><li>Zend_Db_Statement: 81.15% coverage</li>
<li>Zend_Db_Statement_Db2: 65.45%</li>
<li>Zend_Db_Statement_Mysqli: 92.23%</li>
<li>Zend_Db_Statement_Oracle: 66.04%</li>
<li>Zend_Db_Statement_Pdo: 89.39%</li>
</ul><p>Overall coverage: 76%.</p>

<p>This is a significant enough improvement over the code coverage when this issue was raised.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-06-13T19:08:41.000+0000</p> 
        <div class="body">
            <p>Resolved.</p>

        </div>
    </div>
    </div>

