<h2>ZF-10543: Zend_Application_Resource_Db &amp;&amp; Zend_Application_Resource_Cachemanager</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-10T16:07:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-18T16:03:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13410/ZF-10543.patch">ZF-10543.patch</a></li>
            <li><a href="/issues/secure/attachment/13465/ZF-10543v2.patch">ZF-10543v2.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Setting cache for Zend_Db with CacheManager</p>

<pre class="highlight"><code>
resources.db.defaultMetadataCache = database
</code></pre>

<pre class="highlight"><code>
public function setDefaultMetadataCache($cache)
{
    $metadataCache = null;

    if (is_string($cache)) {
        $bootstrap = $this-&gt;getBootstrap();
        if ($bootstrap instanceof Zend_Application_Bootstrap_ResourceBootstrapper
            &amp;&amp; $bootstrap-&gt;hasPluginResource('CacheManager')
        ) {
            $cacheManager = $bootstrap-&gt;bootstrap('CacheManager')
                -&gt;getResource('CacheManager');
            if (null !== $cacheManager &amp;&amp; $cacheManager-&gt;hasCache($cache)) {
                $metadataCache = $cacheManager-&gt;getCache($cache);
            }
        }
    } else if ($cache instanceof Zend_Cache_Core) {
        $metadataCache = $cache;
    }

    if ($metadataCache instanceof Zend_Cache_Core) {
        Zend_Db_Table::setDefaultMetadataCache($metadataCache);
    }

    return $this;
}
</code></pre>

<p>options in resources set before init() is called and $this-&gt;getBootstrap() returns null before init(), so first condition is useless.</p>

<p>rev 23076</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-10-30T18:55:37.000+0000</p> 
        <div class="body">
            <p>Attached patch.</p>

<p>Forced the assignment of the object "bootstrap" in the start of the execution of the plugin resource.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-11T03:25:29.000+0000</p> 
        <div class="body">
            <p>Here a simple code reproduced:</p>

<pre class="highlight"><code>
require_once 'Zend/Loader/Autoloader.php';
Zend_Loader_Autoloader::getInstance();

$options = array(
    'resources' =&gt; array(
        'db'    =&gt; array(
            'adapter'  =&gt; 'Pdo_Sqlite',
            'params'   =&gt; array(
                'dbname'   =&gt; ':memory:'
             ),
             'defaultMetadataCache' =&gt; 'default'
        ),
        'cachemanager' =&gt; array(
            'default'  =&gt; array(
                'backend' =&gt; array('name' =&gt; 'black-hole')
            )
        )
    )
);
$application = new Zend_Application('testing', $options);
$application-&gt;bootstrap();

$resource = $application-&gt;getBootstrap()-&gt;getResource('cachemanager');
assert_options(ASSERT_ACTIVE, 1);
assert_options(ASSERT_WARNING, 1);
assert(Zend_Db_Table::getDefaultMetadataCache() == $resource-&gt;getCache('default'));
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-18T15:25:17.000+0000</p> 
        <div class="body">
            <p>Attach patch with new test.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-18T16:03:10.000+0000</p> 
        <div class="body">
            <p>Fixed in r23383 merged to release branch 1.11 r23384.</p>

        </div>
    </div>
    </div>

