<h2>ZF-10823: Zend_Service_Amazon_Sqs doesn't provide setAttribute method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-12-15T01:51:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Peter Svintsitskiy (peter.svintsitskiy)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to Amazon Simple Queue Service API Reference (API Version 2009-02-01) there are two methods for getting and modifying Queue attributes: GetQueueAttributes and SetQueueAttributes</p>

<p>Zend_Service_Amazon_Sqs provides only a wrapper getAttribute for GetQueueAttributes Amazon SQS API call.</p>

<p>So there is no way to change such queue param as MaximumMessageSize in Amazon Queue</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

