<h2>ZF-10315: Translate options put into content array</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-08-14T10:20:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-22T11:45:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.8 (25/Aug/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Szymon (heavypredator)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>sorry - my fault - didnt noticed that 1.10 adapters dont overwrite constructors</p>

<p>please close</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-08-14T14:34:35.000+0000</p> 
        <div class="body">
            <p>Closing as non-issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-11-22T11:45:34.000+0000</p> 
        <div class="body">
            <p>Correct fix version as it has been deleted unintentionally by another user</p>

        </div>
    </div>
    </div>

