<h2>ZF-1238: Docs: Change Zend_Date::MONTH_DIGIT to Zend_Date::MONTH_SHORT</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-04-10T10:47:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.3 (05/May/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Krebs (kingcrunch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.date.constants.html#zend.date.constants.phpformats">http://framework.zend.com/manual/en/…</a></p>

<p>There is no constant Zend_Date::MONTH_DIGIT in current release. Must be Zend_Date::MONTH_SHORT</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-04-10T16:19:38.000+0000</p> 
        <div class="body">
            <p>already fixed with latest SVN</p>

        </div>
    </div>
    </div>

