<h2>ZF-11101: Remove the reference to Gdata_EventEntry's Hidden attribute</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-02-21T23:45:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-30T12:52:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kim Blomqvist (kblomqvist)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2894">ZF-2894</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13881/ZF-2146_ZF-11101.patch">ZF-2146_ZF-11101.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Gdata_EventEntry does not provide <a href="http://framework.zend.com/manual/en/zend.gdata.calendar.html#zend.gdata.calendar.creating_events.single">hidden attribute</a> and it should be removed from the documentation.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-28T12:36:44.000+0000</p> 
        <div class="body">
            <p>I have checked this against the Google Calendar API reference for the Event kind (<a href="http://code.google.com/apis/gdata/docs/2.0/elements.html#gdEventKind">http://code.google.com/apis/gdata/…</a>), and there is no hidden attribute.  The closest thing is "visibility", which is already implemented in Zend_Gdata_Kind_EventEntry and is already referenced in the same attribute list on the documentation page for this component.</p>

<p>Attached is a patch which removes mention of "Hidden" attribute on events from the documentation for Zend_Gdata_Calendar (specifically, this section: <a href="http://framework.zend.com/manual/en/zend.gdata.calendar.html#zend.gdata.calendar.creating_events.single">http://framework.zend.com/manual/en/…</a>)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-28T22:35:35.000+0000</p> 
        <div class="body">
            <p>Fix in trunk r23879</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-04-30T12:21:59.000+0000</p> 
        <div class="body">
            <p>Hello, Adam, I will push [solve] button instead of You. And I have marged to 1.11 branch for next mini release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-04-30T12:52:14.000+0000</p> 
        <div class="body">
            <p>Thanks!</p>

        </div>
    </div>
    </div>

