<h2>ZF-11291: Incorrect date localisation with Zend_Date::DATE_MEDIUM</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-04-14T18:27:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-16T21:04:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Toni Wenzel (twenzel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
            <li>Zend_Locale</li>
            <li>zend_date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{quote}
$date = new Zend_Date();</p>

<p>$date-&gt;toString(Zend_Date::DATE_MEDIUM);
{quote}</p>

<p>With 'de' locale this code outputs a date with ??dd.MM.yyyy?? format (e.g 30.08.2009).
With 'en' locale it outputs a date with ??MMM d, y?? format (e.g. Aug 30, 2008) instead of a +MM/dd/yyyy+ format</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-04-16T21:04:07.000+0000</p> 
        <div class="body">
            <p>CLDR (or the official world) uses as medium date:</p>

<pre><code>      &lt;dateFormatLength type="medium"&gt;
        &lt;dateFormat&gt;
          &lt;pattern&gt;MMM d, y&lt;/pattern&gt;
        &lt;/dateFormat&gt;
      &lt;/dateFormatLength&gt;
</code></pre>

<p>When you think that these informations are wrong than there are three solutions:</p>

<p>1.) Use another constant which conforms your need
2.) Define the date format you want to have manually
3.) Add an issue to CLDR (<a href="http://cldr.unicode.org">http://cldr.unicode.org</a>)</p>

<p>My opinion is that unicode knows what the correct informations are.</p>

<p>Therefor closing this issue as non-issue.</p>

        </div>
    </div>
    </div>

