<h2>ZF-11008: Zend_Form custom decorator example error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2011-01-30T00:09:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-30T00:09:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Fabio Baleani (fbale)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi all,
in this page <a href="http://framework.zend.com/manual/en/zend.form.decorators.html">http://framework.zend.com/manual/en/…</a> (Creating Custom Form Markup Using Zend_Form_Decorator) the example for addPrefixPath says:</p>

<ol><li>// for all elements:</li>
<li>$form-&gt;addElementPrefixPath('My_Decorator',</li>
<li>'My/Decorator/',</li>
<li>'decorator');</li>
</ol><p>but I've wrote this to make it works:</p>

<ol><li>// for all elements:</li>
<li>$form-&gt;addElementPrefixPath('My',</li>
<li>'My',</li>
<li>'decorator');</li>
</ol><p>because this append <em>Decorator</em> and /Decorator according with type string.</p>

<p>regards,
Fabio</p>

<p>example:
-as documentation
setting:
elementPrefixPath.prefix = Ui_Decorator
elementPrefixPath.path = Ui/Decorator
elementPrefixPath.type = decorator
response:
Message:Plugin by name 'Uierrors' was not found in the registry; used paths: Ui_Decorator_Decorator_: Ui/Decorator/Decorator/ Zend_Form_Decorator_: Zend/Form/Decorator/</p>

<p>-as modified
setting:
elementPrefixPath.prefix = Ui
elementPrefixPath.path = Ui
elementPrefixPath.type = decorator
response:
Message:Plugin by name 'Uierrors' was not found in the registry; used paths: Ui_Decorator_: Ui/Decorator/ Zend_Form_Decorator_: Zend/Form/Decorator/</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

