<h2>ZF-1554: Document usage of Zend_Gdata with raw XML</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-06-12T13:57:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Some people may still prefer to use raw XML with Zend_Gdata--  This should be documented</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-25T16:55:15.000+0000</p> 
        <div class="body">
            <p>Trevor, is this still an issue? I'll send out a mail to you, Ryan, and Jochen so we can get a clear answer. Please close if this documentation is no longer planned.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-11-25T17:13:36.000+0000</p> 
        <div class="body">
            <p>Yes, this is still an issue, and something I'd like to see added. The code is in place to submit raw XML and is used quite frequently form what I see on mailing lists, but the manual does not explain this functionality.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:30.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

