<h2>ZF-1395: Result set limitation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-05-16T13:15:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-23T15:12:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.2 (25/Sep/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10571/result_set_limitation.diff">result_set_limitation.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There should be possibility to limit large result sets.</p>

<p>But it should be clearly described that it's not "top n" results. Just only result set size limitation feature.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-06-14T12:42:09.000+0000</p> 
        <div class="body">
            <p>That's a patch for ZF1.0 RC2 with result set limitation functionality.</p>

<p>I don't commit it right now because feature-freeze period. But it's tested and may be used.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-07-03T11:00:31.000+0000</p> 
        <div class="body">
            <p>Done.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-23T15:12:57.000+0000</p> 
        <div class="body">
            <p>Fixing Fix Version to follow issue tracker conventions.</p>

        </div>
    </div>
    </div>

