<h2>ZF-10609: Zend_File_Transfer_Http_Adapater multiple files</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-10-28T10:44:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Xavier (ksaf)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>File upload problem.</p>

<p>Example:</p>

<p>form</p>

<p>5 files to upload.</p>

<p></p>

<p>When using Zend_File_Transfer_Adapter_Http(), the files will be uploaded when I select the 5 files.
The moment I select less then 5 files, nothing will be uploaded.</p>

<p>Using move_uploaded_file, no problems ...</p>

<p>Code example</p>

<p>/** bug, only does upload when all files selected in form **/</p>

<p>/*
$upload = new Zend_File_Transfer_Adapter_Http();
$upload-&gt;setDestination($path);
$upload-&gt;receive();
*/</p>

<p>foreach($files as $key =&gt; $file){
    if(!empty($file['name'])){
    $ext = substr($file['name'],-4);
    $ext = explode('.',$file['name']);
    $ext = end($ext);
    $naam = $key.$ext;
    move_uploaded_file($file['tmp_name'],$path.$naam);
    $params[$key] = $naam; 
}</p>

<p>I'm using Zend 1.10.8</p>

<p>Regards,</p>

<p>Ksaf</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

