<h2>ZF-11961: Amelioration class Zend_Http_UserAgent_Features_Adapter_WurflApi</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2011-12-30T15:04:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-26T07:42:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Cédric CRISPIN (blackmennewstyle)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Business&amp;Decision / Interakting (interakting)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_UserAgent</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On line 83 :</p>

<p>Replace :</p>

<p>$wurflConfig-&gt;wurflFile($c['wurfl']['main-file'])
                                -&gt;wurflPatch($c['wurfl']['patches'])
                                -&gt;persistence($c['persistence']['provider'], $c['persistence']['dir']);</p>

<p>With :</p>

<p>$wurflConfig-&gt;wurflFile($c['wurfl']['main-file'])
                                -&gt;wurflPatch($c['wurfl']['patches'])
                                -&gt;persistence($c['persistence']['provider'], $c['persistence']['params'])
                                -&gt;allowReload($c['allow-reload']);</p>

<p>I do not understand why it requires a directory as a parameter so that we can pass any provider...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-26T07:03:20.000+0000</p> 
        <div class="body">
            <p>What problem does this code solve?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Cédric CRISPIN (blackmennewstyle) on 2012-02-26T07:42:07.000+0000</p> 
        <div class="body">
            <p>@Adam Lundrigan</p>

<p>With this code, you can easily use any persistance like memcached with WURFL because the original code "-&gt;persistence($c['persistence']['provider'], $c['persistence']['dir']);" forces you to use a directory which is not required with the others persistance methods allowed. Sometimes it cause a bug with some specifics apache server configurations.</p>

        </div>
    </div>
    </div>

