<h2>ZF-10055: Zend_Service_Twitter 1.10.6 authentication changes undocumented</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-06-25T10:48:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-10T16:00:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The construct of Zend_Service_Twitter is changed since 1.10.6.
Before, you just gave a username/password and it took care of the rest.</p>

<p>Now you need to give options in an array and/or a Zend_Oauth_Consumer object.
This is undocumented and unclear what a user has to do to be able to use Zend_Service_Twitter.</p>

<p>Apparently, this has something to do with the fact that Twitter doesn't allow HTTP Auth anymore.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-10-10T16:00:32.000+0000</p> 
        <div class="body">
            <p>Documentation was omitted by a documentation generation error - it's all there in subversion!</p>

        </div>
    </div>
    </div>

