<h2>ZF-12403: Cannot validate Date if end-user uses custom HTTP_ACCEPT_LANGUAGE</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-09-04T07:34:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-04-05T16:07:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
            <li>Zend_Locale</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Date validation throw exception if the end-user enter custom values for HTTP_ACCEPT_LANGUAGE which are used internally in Zend_Locale. Those values are 'root', 'auto' and 'browser'.</p>

<p>I believe those internal values should never be accepted from end-user. However I can't wrap my mind around Zend_Locale well enough to provide a patch for that.</p>

<p>Here is a test script to be used via CLI (so we can manually set HTTP_ACCEPT_LANGUAGE):</p>

<pre class="highlight"><code>&lt;?php
require_once('Zend/Version.php');
require_once('Zend/Locale.php');
require_once('Zend/Registry.php');
require_once('Zend/Validate/Date.php');

if (php_sapi_name() != 'cli')
    die('must run as CLI script');

// Extends Zend_Locale, so we can reset its state between tests
class Zend_LocaleReset extends Zend_Locale {
    public static function reset() {
        self::$_auto = null;
        self::$_browser = null;
        self::$_environment = null;
    }
}

function test($accept) 
{
    Zend_LocaleReset::reset();
    $_SERVER['HTTP_ACCEPT_LANGUAGE'] = $accept;

    $locale = new Zend_Locale();
    Zend_Registry::set('Zend_Locale', $locale);
    
    echo $accept . "\t=&gt;\t" . $locale-&gt;getLanguage() . ': ';
    try {
        $validator = new Zend_Validate_Date(array('format' =&gt; 'Y-m-d'));
        $validator-&gt;isValid('2012-08-08');
        echo 'OK';
    } catch (Exception $exc) {
        echo $exc-&gt;getMessage();
    }
    echo PHP_EOL;
    
}

echo 'Zend Version: ' . Zend_Version::VERSION . PHP_EOL . PHP_EOL;
test(null);
test('');
test('en');
test('en-US,en;q=0.8,ko;q=0.6');
test('fr');
test('non valid string');
test('root');
test('auto');
test('browser');
test('environment');
</code></pre>

<p>It will output the following:</p>

<pre class="highlight"><code>$ php test.php 
Zend Version: 1.11.0dev

    =&gt;  en: OK
    =&gt;  en: OK
en  =&gt;  en: OK
en-US,en;q=0.8,ko;q=0.6 =&gt;  en: OK
fr  =&gt;  fr: OK
non valid string    =&gt;  en: OK
root    =&gt;  root: The locale '' is no known locale
auto    =&gt;  root: The locale '' is no known locale
browser =&gt;  root: The locale '' is no known locale
environment =&gt;  en: OK

</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by fgibaux (fgibaux) on 2012-10-22T16:34:19.000+0000</p> 
        <div class="body">
            <p>In fact if the value of HTTP_ACCEPT_LANGUAGE is any word of letter up to 8 chars that is not a language or a country, it fails :</p>

<pre class="highlight"><code> 
test('null');
test('top');
</code></pre>

<p>will output</p>

<pre class="highlight"><code> 
null    =&gt;      root: The locale '' is no known locale
top     =&gt;      root: The locale '' is no known locale
</code></pre>

<p>A solution could be to validate input in static function getBrowser() of Zend_Locale :</p>

<p>something like this ??</p>

<pre class="highlight"><code>
if (!isset(self::$_localeData[$region]) &amp;&amp; !isset(self::$_territoryData[$region])) {
    continue;
}
foreach ($countrys as $country) {
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2013-04-05T16:07:21.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf1/issues/10">https://github.com/zendframework/zf1/issues/10</a></p>

        </div>
    </div>
    </div>

