<h2>ZF-1874: Zend_Pdf fails with some freware TTF fonts </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-08-23T08:49:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10730/New.ttf">New.ttf</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Pdf fails with some freware barcode fonts ([<a href="http://www.squaregear.net/fonts/free3of9.shtml">http://www.squaregear.net/fonts/free3of9.shtml</a>]).</p>

<p>It throws an exception:</p>

<pre class="highlight"><code>
Fatal error: Uncaught exception 'Zend_Pdf_Exception' with message 'Glyph number is out of range: 81' in /home/cawa/ZendFramework/trunk/library/Zend/Pdf/Resource/Font.php:477
Stack trace:
#0 /home/cawa/ZendFramework/trunk/library/Zend/Pdf/Resource/Font/OpenType.php(147): Zend_Pdf_Resource_Font-&gt;widthsForGlyphs(Array)
#1 /home/cawa/ZendFramework/trunk/library/Zend/Pdf/Resource/Font/OpenType/TrueType.php(53): Zend_Pdf_Resource_Font_OpenType-&gt;__construct(Object(Zend_Pdf_FileParser_Font_OpenType_TrueType), 0)
#2 /home/cawa/ZendFramework/trunk/library/Zend/Pdf/Font.php(720): Zend_Pdf_Resource_Font_OpenType_TrueType-&gt;__construct(Object(Zend_Pdf_FileParser_Font_OpenType_TrueType), 0)
#3 /home/cawa/ZendFramework/trunk/library/Zend/Pdf/Font.php(637): Zend_Pdf_Font::_extractTrueTypeFont(Object(Zend_Pdf_FileParserDataSource_File), 0)
#4 /home/cawa/ZendFramework/laboratory/Pdf/BarCodeFonts/test1.php(15): Zend_Pdf_Font::fontWithPath('./FRE3OF9X.TTF')
#5 {main}
  thrown in /home/cawa/ZendFramework/trunk/library/Zend/Pdf/Resource/Font.php on line 477
</code></pre>

<p>The interesting thing is that if this font is converted to another format and then back to the TTF, then it works proper.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-08-23T08:49:56.000+0000</p> 
        <div class="body">
            <p>An example of converted font</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mike Bowie (mbowie) on 2007-08-28T13:49:21.000+0000</p> 
        <div class="body">
            <p>Interestingly enough, I've been hanging out to post the same issue regarding 'Courier New'.  (COUR.TTF)</p>

<p>Aug 28 11:36:34 www3 httpd: PHP Fatal error:  Uncaught exception 'Zend_Pdf_Exception' with message 'Glyph number is out of range: 3' in /usr/local/www/strongaero.com/includes/Zend/Pdf/Resource/Font.php:477
Stack trace:</p>

<h1>0 /usr/local/www/strongaero.com/includes/Zend/Pdf/Resource/Font/OpenType.php(147): Zend_Pdf_Resource_Font-&gt;widthsForGlyphs(Array)</h1>

<h1>1 /usr/local/www/strongaero.com/includes/Zend/Pdf/Resource/Font/OpenType/TrueType.php(53): Zend_Pdf_Resource_Font_OpenType-&gt;__construct(Object(Zend_Pdf_FileParser_Font_OpenType_</h1>

<p>(Trace truncated thanks to syslog)</p>

<p>I'll try converting it to pfa and back and see if it helps; sadly I'm not sufficiently familiar with TTF and company to know where to start for a patch.</p>

<p>Much as I'd love to post a copy of the font, I don't think Microsoft class it as freeware just yet.</p>

<p>Cheers,</p>

<p>Mike.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-08-28T14:59:49.000+0000</p> 
        <div class="body">
            <p>Thanks for the info Mike!</p>

<p>Could you also attach font to the issue (if it's allowed by font license)?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mike Bowie (mbowie) on 2007-08-28T15:55:57.000+0000</p> 
        <div class="body">
            <p>Alexander,</p>

<p>It would seem they are available for download from <a href="http://umn.dl.sourceforge.net/sourceforge/corefonts/courie32.exe">http://umn.dl.sourceforge.net/sourceforge/…</a>  (As I understand it, the license does not allow distribution other than in their original form.)</p>

<p>The file can be extracted using cabextract on non-Windows platforms.</p>

<p>cour.ttf in that particular package is 2.82, which exhibits the behavior; as does 2.9, which I tried from one of the local Windows XP installations.</p>

<p>Hope that helps,</p>

<p>Mike.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Philip Iezzi (iezzip) on 2007-11-08T12:16:22.000+0000</p> 
        <div class="body">
            <p>I'm encountering the same issue with the freeware OCR-B font from <a href="http://ansuz.sooke.bc.ca/software/ocrb.php">http://ansuz.sooke.bc.ca/software/ocrb.php</a>
Any solution to this problem so far?
If not, is there any other freeware OCR font that works with Zend_Pdf_Resource_Font?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-12-06T18:55:06.000+0000</p> 
        <div class="body">
            <p>There was a problem in glyph width array processing. It may contain less elements than glyphs are presented in the font. 
Last element contains width for the rest of glyphs list.</p>

        </div>
    </div>
    </div>

