<h2>ZF-11351: Zend_Gdata_AuthSub falsely allows setting vanilla instance of Zend_Http_Client</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-05-08T02:33:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-28T17:25:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.7 (02/Jun/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14024/ZF-11351.patch">ZF-11351.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Gdata_AuthSub::getHttpClient allows passing of vanilla Zend_Http_Client instance, but then attempts to call setAuthSubToken() method on it, resulting in unhandled fatal error.</p>

<p>Reproduce (Zend_Gdata_AuthSubTest.php):</p>

<pre class="highlight"><code>
$client = new Zend_Http_Client();
$client-&gt;setUri('<a href="http://example.com/AuthSub">http://example.com/AuthSub</a>');
$gdclient = Zend_Gdata_AuthSub::getHttpClient('FakeToken', $client);
</code></pre>

<p>Result:</p>

<pre class="highlight"><code>
PHP Fatal error:  Call to undefined method Zend_Http_Client::setAuthSubToken() in /usr/local/apache2/htdocs/lib/zfdev/trunk/library/Zend/Gdata/AuthSub.php on line 242
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-08T02:45:24.000+0000</p> 
        <div class="body">
            <p>Attached patch with possible fix.  This avenue does technically break backwards-compatibility as you can no longer pass vanilla Zend_Http_Client instances into Zend_Gdata_AuthSub, however doing so before raised a fatal error in PHP, so IMHO I don't think that BC break is an issue.</p>

<p>Comments?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2011-05-11T02:04:31.000+0000</p> 
        <div class="body">
            <p>Looks good to me.</p>

<p>You have a commit bit, correct? Let me know if you need any further assistance with this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-11T02:31:46.000+0000</p> 
        <div class="body">
            <p>Excellent.  I've commited it to the trunk (r24033)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-05-28T17:25:13.000+0000</p> 
        <div class="body">
            <p>Merged to release-1.11 in r24061</p>

        </div>
    </div>
    </div>

