<h2>ZF-2847: Multi Element With Arrays Calling isTranslated Produces Warning</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-10T15:05:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-05-14T23:52:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li> 1.5.2 (15/May/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Arthur Kang (arthurkang)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11230/MultiselectTest.php.patch">MultiselectTest.php.patch</a></li>
            <li><a href="/issues/secure/attachment/11246/ZF-2847.patch">ZF-2847.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using translation and a multi element with arrays as the options (optgroup), warnings are raised.  Can be fixed by checking parameters prior to calling Translate::isTranslated and/or Translate::isTranslated should have some sanity checks on the parameters.</p>

<p>Controller:</p>

<pre class="highlight"><code>
$translate = new Zend_Translate('array', array('Select Test'=&gt;'Select Test Translated'), 'en');
Zend_Registry::set('Zend_Translate', $translate);
$form = new Zend_Form(array(
    'elements' =array(
        'test' =array('Select', array(
            'label' ='Select Test',
            'MultiOptions' =array(
                'Group 1' =array(
                    '1-1' ='Hi 1-1',
                    '1-2' ='Hi 1-2'
                ),
                'Group 2' =array(
                    '2-1' ='Hi 2-1',
                    '2-2' ='Hi 2-2'
                ),
            )
        ))
    )
));
$this-&gt;view-&gt;form = $form;
</code></pre>

<p>With...</p>

<p>View:
```</p>

<p>Produces...</p>

<p>Warning: array_key_exists() [function.array-key-exists]: The first argument should be either a string or an integer in /directory/library/Zend/Translate/Adapter.php on line 452</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:29:10.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-04-05T07:32:24.000+0000</p> 
        <div class="body">
            <p>Arthur: Please re-test this with the release.
I have in mind that such an error was already reported and fixed before the release.
Eighter with 1.5 or 1.5.1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Arthur Kang (arthurkang) on 2008-04-07T04:53:09.000+0000</p> 
        <div class="body">
            <p>The problem still exists with ZF version 1.5.1.</p>

<p>This may not necessarily be a Translate problem, but I categorized it under Form and Translate as that is where the problem occurs.  Form multi elements are passing ARRAYS to the Translate Adapter.  This can be easily duplicated by using the test code I posted.</p>

<p>Should check the value in the multielement and make sure it is not an array before calling, or in the translate adapter, should make sure the passed in parameter is acceptable, or both.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-04-09T15:49:21.000+0000</p> 
        <div class="body">
            <p>2 things to mention:</p>

<p>First:
It seems that 1.5.1 does not include the latest version of Zend_Translate. It has changed on 15.3, the release was done on 24.3 but does not include the change from 10 days ago... don't ask me why.</p>

<p>Second:
Even if you use the actual trunk version where this has changed, you will not have the nested array from your optgroup translated because nested arrays can not be supported at translation. So you would have no error but also your optgroup not translated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Arthur Kang (arthurkang) on 2008-04-09T16:16:19.000+0000</p> 
        <div class="body">
            <p>I will check out the latest trunk and try and test.</p>

<p>Like I said, I didn't necessarily think this was a Zend_Translate, problem.  If the errors are gone, that's good.</p>

<p>The optgroup will have to be iterated over and translated, which is Zend_Form.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-04-09T16:38:12.000+0000</p> 
        <div class="body">
            <p>Hah... I already know the problem...</p>

<p>API Doc for isTranslated() and translate() states that $messageId can only be string.
Zend_Form gives an array instead an string.</p>

<p>So in my opinion raising the error is ok because API doc states so.
What if anyone gives an object as $messageId... this would also throw errors.</p>

<p>I detach Zend_Translate from this issue, as it's behaving correct related to it's allowed input.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2008-04-14T03:36:12.000+0000</p> 
        <div class="body">
            <p>This is a (failing) test for this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2008-04-18T03:00:36.000+0000</p> 
        <div class="body">
            <p>I attached a patch that should fix this issue. Have a look at it. I'll be glad if it makes it into the framework.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-04-22T13:32:23.000+0000</p> 
        <div class="body">
            <p>Scheduling  for next mini release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2008-04-25T03:19:21.000+0000</p> 
        <div class="body">
            <p>Is it possible to include the fix in the current trunk, so we don't have to wait until 1.5.2 is released?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-04-25T06:55:58.000+0000</p> 
        <div class="body">
            <p>Emil: patience, please. I've scheduled it for the next mini release, but the fix will be in trunk first. I have a backlog of some 30 issues I need to hit before 1.5.2, and this is just one.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-08T07:30:41.000+0000</p> 
        <div class="body">
            <p>Fix committed to trunk and 1.5 release branch as of r9411</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2008-05-14T23:51:59.000+0000</p> 
        <div class="body">
            <p>The optgroup label does not get translated.</p>

        </div>
    </div>
    </div>

