<h2>ZF-2768: Zend_Controller_Response_HttpTest failures</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-02-29T14:44:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-04T12:45:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>With PHP 5.2.5 and PHPUnit 3.2.15 on Linux I get the following failures from running {{phpunit --verbose AllTests}} (under the default test configuration) in {{trunk/tests}}:</p>

<pre class="literal">
1) test__toString(Zend_Controller_Response_HttpTest)
Failed asserting that  is true.
/home/darby/framework/trunk/tests/Zend/Controller/Response/HttpTest.php:179

2) testCanSendHeadersIndicatesFileAndLine(Zend_Controller_Response_HttpTest)
Failed asserting that  matches PCRE pattern "/headers already sent in .+, line \d+$/".
/home/darby/framework/trunk/tests/Zend/Controller/Response/HttpTest.php:255
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-02-29T14:47:07.000+0000</p> 
        <div class="body">
            <p>I can also reproduce the failures by running {{phpunit Zend_Controller_Response_HttpTest}}, see <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=8477">SVN r8477</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-04T12:13:42.000+0000</p> 
        <div class="body">
            <p>I can also reproduce the same failures, though with different line numbers, on WinXP, PHP 5.1.4.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-03-04T12:45:22.000+0000</p> 
        <div class="body">
            <p>both tests rely on Zend_Controller_Response_Abstract's usage of header(), headers_sent() and headers_list() to be able to successfully test their correct behavoir.</p>

<p>Unfortunately, in PHP's Cli sapi, the calls to header() are ignored thus content provided via this method cannot be tested.  Also, since there is usage of output buffereing during unit tests (and in some cases, the actual component), headers_sent() 's state will not become true until some output is sent to the cli console.</p>

<p>This is the best we can do until we find an alternative means to test differnet php sapis or hijack php extension function calls (like header()).</p>

<p>-ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-03-04T12:45:45.000+0000</p> 
        <div class="body">
            <p>fixed in r8533</p>

        </div>
    </div>
    </div>

