<h2>ZF-2217: Zend_Db_Table_Abstract doesn't return the right primary key when inserting a new row</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-11-18T16:57:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-26T12:56:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.4 (26/Feb/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ulrich Berkmüller (thetiger2k)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10933/Abstract.php">Abstract.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Db_Table_Abstract::insert() - line 786 returns the wrong primary key (returns false) because array index wasn't resetted.</p>

<pre class="literal"> 
       $pkData = array_intersect_key($data, array_flip($primary));
       if (count($primary) == 1) {
            return current($pkData);
        } else {
            return $pkData;
        }
</pre>

<p>edit to:</p>

<pre class="literal"> 
        $pkData = array_intersect_key($data, array_flip($primary));
        if (count($primary) == 1) {
            reset($pkData);
            return current($pkData);
        } else {
            return $pkData;
        }
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ulrich Berkmüller (thetiger2k) on 2007-11-18T17:03:20.000+0000</p> 
        <div class="body">
            <p>the fixed version</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-02-11T18:48:56.000+0000</p> 
        <div class="body">
            <p>Resolved for next minor release with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=7937">SVN r7937</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-02-11T19:00:56.000+0000</p> 
        <div class="body">
            <p>Resolved for next mini-release with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=7938">SVN r7938</a>.</p>

        </div>
    </div>
    </div>

