<h2>ZF-2677: magic data model class creation methods throwing error if class isn't in first registered 'classpath'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-18T13:20:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-26T14:46:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.4 (26/Feb/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2674">ZF-2674</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Changes committed in r7577 removed error suppression (@) from the include_once call in Zend_Loader:83.  This was eliminated in order to make sure that parsing errors, etc are discoverable.  The magic method __call handing of 'new*' for data model class creation depended on these errors being suppressed.  Need to suppress these errors in Zend_Gdata_App and Zend_Gdata_Gapps.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2008-02-18T13:26:10.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk - r8131.</p>

        </div>
    </div>
    </div>

