<h2>ZF-2929: Problems with German Umlaute since ZF 1.5</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-19T12:48:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-21T11:32:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li> 1.5.2 (15/May/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2107">ZF-2107</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We have some strange behaviour with Zend_Filter_Alnum &amp;
Zend_Filter_Alpha since ZF 1.5. Everything works correct by using ZF 1.0.4.</p>

<p>By folowing code line
echo Zend_Filter_Alnum::filter("Lüge"); // in utf-8 encoding
delivers Lge instead of Lüge until ZF 1.0.x the result was correct.</p>

<p>Corresponding code block in Zend/Filter/Alnum.php:
<code>
        if (!self::$_unicodeEnabled) {
            // POSIX named classes are not supported, use alternative
a-zA-Z0-9 match
            $pattern = '/[^a-zA-Z0-9' . $whiteSpace . ']/';
        } else if (extension_loaded('mbstring')) {
            // Unicode safe filter for the value with mbstring
            $pattern = '/[^[:alnum:]'  . $whiteSpace . ']/u';
        } else {
            // Unicode safe filter for the value without mbstring
            $pattern = '/[^\p{L}\p{N}' . $whiteSpace . ']/u';
        }
</code></p>

<p>The problem is we have the mbstring enabled and this line don't work<br />
            $pattern = '/[^[:alnum:]'  . $whiteSpace . ']/u';
but this line
            $pattern = '/[^\p{L}\p{N}' . $whiteSpace . ']/u';
The internal-encoding is correctly set to UTF-8.</p>

<p>The question is why the [:alnum:] line don't work, and why it is useful to handle on another way  if the extension is enabled ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-03-19T19:19:51.000+0000</p> 
        <div class="body">
            <p>Hello, Dominik.
Is the mbstring extension used in German ?</p>

<p>In the last version, before changing in ZF-2107, only "^\p{L}\p{N}" pattern is used.</p>

<p>But I found it causes error in Japanese.  The problem is all character of Japanese is passed.
So, I changed because I thought mbstring extension used only in the language that has many multibyte characters.</p>

<p>But if the mbstring extension used in German , (or Czeck, Polish...etc)  ZF-2107 happens your problems.</p>

<p>Do you have any idea instead of using "if (extension_loaded('mbstring'))" ?
It seems to be better if we use language location in if statement.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T21:09:03.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dominik Bors (dom) on 2008-04-07T04:25:45.000+0000</p> 
        <div class="body">
            <p>Hello Satoru,</p>

<p>sorry for my late answer.</p>

<p>I don't think mbstring extension is used in German, it shouldn't. But the mbextension often is installed by default.</p>

<p>I think we should add a second condition to the if statement, maybe something that asks if the default zend_locale is japanese.</p>

<p>Best regards
Dominik</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-04-10T08:47:32.000+0000</p> 
        <div class="body">
            <p>Hello, Dominik.
Thank you for your reply.</p>

<p>Ok, I try to add some condition by using Zend_Locale. :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kirill (kupuyc) on 2008-04-16T18:05:46.000+0000</p> 
        <div class="body">
            <p>I have same problem with russian characters:</p>

<pre class="highlight"><code>$filter = new Zend_Filter_Alnum(true);  
Zend_Debug::dump($filter-&gt;filter('это странненько - mbstring enabled'));  
//string(19) "   mbstring enabled"</code></pre>

<pre class="highlight"><code>$filter = new Zend_Filter_Alnum(true);  
Zend_Debug::dump($filter-&gt;filter('это странненько - mbstring disabled'));  
//string(48) "это странненько  mbstring disabled"</code></pre>

<p>In my case $pattern = '/[^[:alnum:]'  . $whiteSpace . ']/u'; is used by filter.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-04-16T20:10:41.000+0000</p> 
        <div class="body">
            <p>Thank You for Your information, Kirill.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-04-21T01:14:24.000+0000</p> 
        <div class="body">
            <p>Resolved in SVN r9266</p>

        </div>
    </div>
    </div>

