<h2>ZF-2973: NotEmpty validator and &quot;0&quot; string</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-26T03:29:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-17T12:56:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Fabrizio Balliano (balliano)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jordan Ryan Moore (jordanryanmoore)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>line 62 of Validate/NotEmpty.php</p>

<p>if (empty($value)) {</p>

<p>should be replaced with</p>

<p>if (strlen($value) == 0) {</p>

<p>otherwise the "0" string will be seen as empty, but it isn't</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Martin Mayer (martin.mayer) on 2008-03-26T04:59:56.000+0000</p> 
        <div class="body">
            <p>In PHP "0" is supposed to be an empty string, see <a href="http://www.php.net/manual/en/function.empty.php">http://www.php.net/manual/en/function.empty.php</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabrizio Balliano (balliano) on 2008-03-26T08:27:08.000+0000</p> 
        <div class="body">
            <p>i know how php handle a "0" string but it should be done differently in ZF context!</p>

<p>if a user types "0" in an input field, ZF should not say "hey the field is empty"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabrizio Balliano (balliano) on 2008-03-26T12:11:06.000+0000</p> 
        <div class="body">
            <p>partially duplicated of bug ZF-2851 also if I think that the $value === "" is not the right choice</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2008-03-26T13:46:46.000+0000</p> 
        <div class="body">
            <p>Zend_Validate_NotEmpty is supposed to mimic PHP's built-in empty(). If you want to check for an empty string, use Zend_Validate_StringLength.</p>

<p>Also, changing the behavior of Zend_Validate_NotEmpty as you suggest would introduce a serious BC break.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabrizio Balliano (balliano) on 2008-03-26T15:57:18.000+0000</p> 
        <div class="body">
            <p>ok, anyway having the StringLength validator on a field and telling the user "this field should be at leat 1 char long" is not a nice thing, while telling "hey, this field is required" it's much better (only using default messages from ZF, not custom ones)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T12:56:02.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Assigning all resolved issues to the people who resolved them. The only unassigned issues should be those that are new and unreviewed.</p>

        </div>
    </div>
    </div>

