<h2>ZF-2111: PDO MSSQL Adapter does not work with port</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-10-29T18:08:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-12-15T21:46:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.3 (30/Nov/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The PDO_MSSQL Adapter does not work with a given port.</p>

<p>Line 92++ of Mssql.php</p>

<pre class="highlight"><code> 
        if (isset($dsn['port'])) {
            $dsn['host'] .= ',' . $port;
            unset($dsn['port']);
        }
</code></pre>

<p>should change from $port to $dsn['port']</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-21T06:57:55.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN 6890</p>

        </div>
    </div>
    </div>

