<h2>ZF-2021: Zend_Config::toArray() does not support generic object values</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-10-01T14:27:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-12-15T21:46:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.3 (30/Nov/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2016">ZF-2016</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{{Zend_Config::toArray()}} makes improper use of {{is_object()}} where {{instanceof}} is more appropriate, resulting in the inability to have object values, except other objects that happen to have a {{toArray()}} method defined.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-10-01T15:39:40.000+0000</p> 
        <div class="body">
            <p>Fixed for 1.1.0 with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=6556">SVN r6556</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2007-10-01T15:44:06.000+0000</p> 
        <div class="body">
            <p>Coo! You resolved it before I even got my editor up!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-11-15T10:19:33.000+0000</p> 
        <div class="body">
            <p>Fixed for 1.0.3 with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=6829">SVN r6829</a></p>

        </div>
    </div>
    </div>

