<h2>ZF-2553: Typo in zend.controller.plugins (German)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-02-03T05:16:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T21:09:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/de/zend.controller.plugins.html">http://framework.zend.com/manual/de/…</a>
{quote}</p>

<pre class="highlight"><code>
// Anendungsfehler
</code></pre>

<p>{quote}
-&gt;</p>

<pre class="highlight"><code>
// Anwendungsfehler
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-02-05T14:14:15.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T21:09:05.000+0000</p> 
        <div class="body">
            <p>Updating to comply with new IT component conventions.</p>

        </div>
    </div>
    </div>

