<h2>ZF-2160: Unit test failure: testStatementNextRowset(Zend_Db_Statement_Pdo_MysqlTest)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-11-06T10:10:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-19T02:30:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Results from PHP 5.2.4 (Linux):</p>

<p>testStatementNextRowset(Zend_Db_Statement_Pdo_MysqlTest)
Expected to catch Zend_Db_Statement_Exception
/usr/local/Zend/ZendFramework/tests/AllTests.php:45
/usr/local/Zend/ZendFramework/tests/AllTests.php:61</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-06T10:24:09.000+0000</p> 
        <div class="body">
            <p>Cannot reproduce with latest trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:33.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-19T02:30:23.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Assigning closed and resolved issues to those who resolved them. The only unassigned issues should be new and unreviewed.</p>

        </div>
    </div>
    </div>

