<h2>ZF-2522: Zend_Filter_Inflector __construct params ignored</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-01-29T18:29:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>@version    $Id: Inflector.php 7078 2007-12-11 14:29:33Z matthew $</p>

<p>Parameters $throwTargetExceptionsOn and $targetReplacementIdentifer in Zend_Filter_Inflector __construct method are ignored if boolean false.</p>

<p>Actual code:</p>

<pre class="highlight"><code>
    if ($throwTargetExceptionsOn != null) {
        $this-&gt;setThrowTargetExceptionsOn($throwTargetExceptionsOn);
    }

    if ($targetReplacementIdentifer != null) {
        $this-&gt;setTargetReplacementIdentifier($targetReplacementIdentifer);
    }
</code></pre>

<p>Proposed fix:</p>

<pre class="highlight"><code>
    if ($throwTargetExceptionsOn !== null) {
        $this-&gt;setThrowTargetExceptionsOn($throwTargetExceptionsOn);
    }

    if ($targetReplacementIdentifer !== null) {
        $this-&gt;setTargetReplacementIdentifier($targetReplacementIdentifer);
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-02-20T16:08:07.000+0000</p> 
        <div class="body">
            <p>Fixed in r8226.</p>

<p>The targetReplacementIdentifier actually should be checking that the string is not != ''.  The exception flag was fixed as well.</p>

<p>-ralph</p>

        </div>
    </div>
    </div>

