<h2>ZF-2150: OpenID Authentication</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-11-05T17:20:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dmitry Stogov (dmitry)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Provide an adapter for OpenID authentication</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-11-06T14:02:30.000+0000</p> 
        <div class="body">
            <p>Assigning to [~dmitry]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-01-15T13:08:29.000+0000</p> 
        <div class="body">
            <p>OpenID is now in core on trunk, so I'm closing this one out. Dmitry, please reopen if there is any pending work I'm unaware of.</p>

        </div>
    </div>
    </div>

