<h2>ZF-2555: Select count(*) with join not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-03T10:10:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-17T13:35:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Olivier Guilbaud (trevinfo)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jordan Ryan Moore (jordanryanmoore)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you want to make the following sql request  with Zend_Db_Select :</p>

<pre class="highlight"><code>
SELECT COUNT(*)
FROM table1 a
RIGHT JOIN table2 b on (b.id = a.id)
WHERE (a.xxx = 'yy')

$select-&gt;from(array('a'=&gt;'table1', 'count(*) as nbre', $this-&gt;_schema);
$select-&gt;joinRight(array('b'=&gt;'table2'), 'b.id = a.id', false);
</code></pre>

<p>This exemple, I do not want the fields of table2, I write "false" in joinRight()</p>

<p>The result SQL is :</p>

<pre class="highlight"><code>
SELECT COUNT(*), b.
FROM table1 a
RIGHT JOIN table2 b on (b.id = a.id)
WHERE (a.xxx = 'yy')
</code></pre>

<p>And not work.</p>

<p>For fix this, modify this :</p>

<pre class="highlight"><code>
protected function _tableCols($correlationName, $cols) {
        if (!$cols) return;  /*&lt;== added */
....
</code></pre>

<p>in Zend/db/select.php</p>

<p>Regards</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2008-02-20T12:42:06.000+0000</p> 
        <div class="body">
            <p>Pass an empty array() instead of false, and it works just fine.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T13:35:24.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Closing and assigning all old unassigned issues. The only unassigned issues should be new and unreviewed.</p>

        </div>
    </div>
    </div>

