<h2>ZF-254: use $token for an instance of Zend_Controller_Dispatcher_Token</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-07-14T10:36:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.2.0 (29/Oct/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10060/rewrite_router_token.diff">rewrite_router_token.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Very minor nit, but it makes sense to use the variable $token for an instance of Zend_Controller_Dispatcher_Token.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2006-07-14T10:36:43.000+0000</p> 
        <div class="body">
            <p>Patch to convert $actionObj to $token</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2006-07-14T10:54:25.000+0000</p> 
        <div class="body">
            <p>And again - thanks for the patch, Rob.</p>

        </div>
    </div>
    </div>

