<h2>ZF-240: Zend_Controller_Router</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-07-12T11:44:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.5 (11/Jul/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Lukasz Dywicki (splatch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have a small problem. If I drop my Front Controller into other than document root directory I have error, becose ZC_Router is broken. For me Front Controller should be works in any directory, not in <em>/</em> only. I created solution for this problem - I added lines in ZC_Router. 
Before:
        $path = $_SERVER['REQUEST_URI'];</p>

<p>After:
        $path = $_SERVER['REQUEST_URI'];
        if(strstr($path, $_SERVER['SCRIPT_NAME'])) {
            $path = str_replace($_SERVER['SCRIPT_NAME'], '', $path);
        } else {
            $path2 = substr($_SERVER['SCRIPT_NAME'], 0, strrpos($_SERVER['SCRIPT_NAME'], '/'));
            $path = str_replace($path2, '', $path);
        }</p>

<p>That will works for paths:
<a href="http://framework.zend.com/others/index.php/controller/action">http://framework.zend.com/others/index.php/…</a>
<a href="http://framework.zend.com/others/controller/action">http://framework.zend.com/others/controller/action</a></p>

<p>Regards.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2006-07-13T02:54:38.000+0000</p> 
        <div class="body">
            <p>"Fixed in 0.1.5 with the new RewriteRouter moving to core. Old router will not allow this and will be replaced by the new router in a future release." -- Jayson MInard</p>

<p>Duplicate of ZF-55</p>

        </div>
    </div>
    </div>

