<h2>ZF-2105: Zend_Filter::get() could be better named</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-10-26T15:02:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-25T10:09:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{{Zend_Filter::get()}} may be better named {{staticFilter()}} or something similar, the goal being to indicate what the method does.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:28.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:12:03.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T17:11:46.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize/assign as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2008-04-24T08:05:21.000+0000</p> 
        <div class="body">
            <p>+1 for getStaticFilter()</p>

<p>In the MVC layer Matthew has used this naming for the helperBroker too HelperBroker::getStaticHelper('x')</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-30T06:20:29.000+0000</p> 
        <div class="body">
            <p>Matthew, please decide what we should do with this. 3 possibilities that I see: close as 'will not fix', mark as 'postponed' and fix version 'next major release', or handle it now by deprecating the get() method and adding the new method. The last possibility has the advantage that users could start migrating their apps now, although we may need to firm up our deprecation policies and processes before taking such actions.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-06-26T12:59:22.000+0000</p> 
        <div class="body">
            <p>Under code review since 26.06.2009</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-25T10:09:18.000+0000</p> 
        <div class="body">
            <p>Implemented with r17073.</p>

<p>After discussion with the dev-team we changed the function name to Zend_Filter::filterStatic()</p>

        </div>
    </div>
    </div>

