<h2>ZF-2529: Make Zend_Db_Statement_Mysqli incorporate with PHP 5.3 and mysqlnd</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-01-30T10:56:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-14T00:53:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Adapter_Mysqli</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7081">ZF-7081</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11115/zend_db_statement-mysqli.diff">zend_db_statement-mysqli.diff</a></li>
            <li><a href="/issues/secure/attachment/11113/zend_db_statement-mysqli.diff">zend_db_statement-mysqli.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>mysqli_stmt_bind_param() expects bind parameters to be references, not values. The following patch ensures that references are given.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2008-01-31T06:50:15.000+0000</p> 
        <div class="body">
            <p>See <a href="http://bugs.php.net/bug.php?id=43568">http://bugs.php.net/bug.php?id=43568</a> for details</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2008-01-31T06:53:59.000+0000</p> 
        <div class="body">
            <p>Updated the patch. The type definition should not be a reference.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:43:56.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Olivier Doucet (ezameku) on 2008-08-21T10:12:10.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>Any news about this patch ? I have to apply it to every release I get from ZF Website. It is a fix to a major bug I think.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2009-01-13T10:38:10.000+0000</p> 
        <div class="body">
            <p>Reassigning to Ralph to bring closure to this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Tankersley (dragonmantank) on 2009-05-24T09:46:39.000+0000</p> 
        <div class="body">
            <p>I applied the 1/31/08 patch against Zend Framework 1.8.1 and still get this issue with PHP 5.3 RC built on 5/21/09. Any news on this bug?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Constantine Karnacevych (digital) on 2009-05-25T17:05:54.000+0000</p> 
        <div class="body">
            <p>strange thing, i've applied this path and everything work well. perhaps you've either missed something or applied a path incorrectly.
besides, this path would make sense after php 5.3 is released and it should be rearranged to gain back and forth compatibility</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Olivier Doucet (ezameku) on 2009-05-27T06:51:22.000+0000</p> 
        <div class="body">
            <p>This patch still need to be applied on ZF 1.8.1 when used with PHP 5.3RC2.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Tankersley (dragonmantank) on 2009-05-27T18:56:22.000+0000</p> 
        <div class="body">
            <p>Reapplied the patch and it worked this time, so I must have done something wrong the first time.</p>

<p>Any ideas when this will make it into trunk or is it just planned to be among the updates for Zend Framework to work with 5.3?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Edward Surov (zooh) on 2009-07-01T05:11:44.000+0000</p> 
        <div class="body">
            <p>I invented the same bicycle today when my site stopped working after upgrading to PHP 5.3.0 (released yesterday). I think it's time to fix the trunk already.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-01-11T07:08:36.000+0000</p> 
        <div class="body">
            <p>Ill run the tests one more time and close, this was fixed in 1.9.0 release though.</p>

<p>-ralph</p>

        </div>
    </div>
    </div>

