<h2>ZF-2255: Locale is over written with Automatic source detection</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-12-03T10:27:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-26T12:56:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.4 (26/Feb/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When we use Automatic source detection we are loosing the value of $locale set in the constructor. This appends because the same $locale variable is reuse to add the translation file with ::addTranslation().</p>

<p>So at the end of the directory scanning when the locale is set, $locale have the value of the last added file :</p>

<pre class="highlight"><code>
if ((array_key_exists($locale, $this-&gt;_translate)) and (count($this-&gt;_translate[$locale]) &gt; 0)) {
    $this-&gt;setLocale($locale);
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-12-03T13:00:39.000+0000</p> 
        <div class="body">
            <p>When you are using "automatic detection", any set locale is useless because the automatic detection will overwrite it.</p>

<p>Zend_Locale will in this case automatically search for the right locale. This is forced within the setLocale() method of the translation instance.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laurent Melmoux (laurent melmoux) on 2007-12-03T13:47:02.000+0000</p> 
        <div class="body">
            <p>Oh, In fact I mean automatic detection of the source files not the locale :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-12-15T15:42:02.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN-7143</p>

        </div>
    </div>
    </div>

