<h2>ZF-2843: Warning: array_merge_recursive(): recursion detected in Zend\Config\Ini.php on line 134</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-10T11:44:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T17:56:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.1 (25/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>While trying to figure out how Zend_Config_Ini deals with invalid ini-files, I stumbled upon this error message:
{quote}
Warning: array_merge_recursive() [function.array-merge-recursive]: recursion detected in [...]Zend\Config\Ini.php on line 134
{quote}</p>

<p>I can't figure out why this happens, but I can reproduce it.</p>

<p>Notice that there are no sections in the config file.</p>

<p>config.ini:</p>

<pre class="highlight"><code>
abc = def

ghi = jkl
</code></pre>

<p>index.php:</p>

<pre class="highlight"><code>
require_once('Zend/Loader.php');

Zend_Loader::loadClass('Zend_Config_Ini');
try
{
    $myIniConfig = new Zend_Config_Ini('./config.ini', null, array('nestSeparator' =&gt; '.'));
}
catch (Exception $e)
{
    echo "Could not load configuration - {$e-&gt;getMessage()}";
    exit;
}
</code></pre>

<p>Replacing line 134</p>

<pre class="highlight"><code>
$dataArray = array_merge_recursive($dataArray, $this-&gt;_processKey($config, $sectionName, $sectionData));
</code></pre>

<p>with the following code</p>

<pre class="highlight"><code>
$tmp = $this-&gt;_processKey($config, $sectionName, $sectionData);
$dataArray = array_merge_recursive($dataArray, $tmp);
</code></pre>

<p>seems to take care of it for whatever reason, but I still can't tell exactly why it happens so I'm not sure how to properly fix it.</p>

<p>Maybe this is a problem with PHP function array_merge_recursive() - I don't know.</p>

<p>A somewhat related issue, perhaps better suited for a mailing list than here, but I'm lazy..
While trying to debug this issue, I found it a little hard to figure out the meaning of a lot of code in Zend\Config\Ini.php.. For example, why is the $config variable being used as a parameter for a call to $this-&gt;_processKey() on that line (134)?
That variable holds settings that may be passed to Zend_Config_Ini to configure allowModifications and nestSeparator, so why did it suddenly change its purpose?
Or is it really supposed to do that? The result is that you can use $myIniConfig-&gt;nestSeparator or $myIniConfig-&gt;allowModifications (using $myIniConfig from my reproduction code above) to get those internal settings the same way you would get settings from the parsed ini file, I assume that this is not the intented behaviour.. (shouldn't only settings from the ini file be available as object members like that)?</p>

<p>I see that method _processKey() uses its own variable named $config, maybe that's what caused the confusion (assuming I'm not the one who's confused, but that may very well be a wrong assumption ;-))?</p>

<p>I guess that somewhere between the lines here I'm saying that it could be helpful with more code comments where it's not immediately obvious what's happening, just in case someone else are going to maintain the package sometime in the distant future.. I for one feel that I've spent far too much time on nothing trying to debug this thing, but it might have been a lot easier if it were easier to read what was going on.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2008-03-10T16:56:58.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>You are right. I've fixed the actual bug by renaming the constructor parameter to $options.</p>

<p>This is committed to trunk in svn r8741.</p>

<p>I will open a separate issue to refactor Zend_Config_Ini to make it more understandable.</p>

<p>Regards,</p>

<p>Rob...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2008-03-10T16:59:05.000+0000</p> 
        <div class="body">
            <p>Fixed.
I've opened <a href="http://framework.zend.com/issues/browse/ZF-2849">http://framework.zend.com/issues/browse/ZF-2849</a> for improving the internals of Zend_Config_Ini.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2008-03-10T17:11:43.000+0000</p> 
        <div class="body">
            <p>Darby,</p>

<p>Do you want me to apply to branch/release-1.5/ ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-12T14:32:03.000+0000</p> 
        <div class="body">
            <p>Yes, but please wait until after code freeze has been announced as lifted. Thanks! :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:19:05.000+0000</p> 
        <div class="body">
            <p>I'm assuming this fix is merged to the 1.5 release branch for release with 1.5.1. Please update JIRA if this is not the case.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2008-03-21T17:56:47.000+0000</p> 
        <div class="body">
            <p>It is now!</p>

<p>Sorry - I had it ready to go locally, but forgot to commit after 1.5.0 was released.</p>

<p>Rob...</p>

        </div>
    </div>
    </div>

