<h2>ZF-219: insert() parameter is array reference, so it cannot be an array literal</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-07-10T01:39:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>That's it ! insert and update use an old php4 reference ( public function insert(&amp; data) { ). It's unusefull in php5, isn't it ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Turland (elazar) on 2006-07-20T11:01:22.000+0000</p> 
        <div class="body">
            <p>You may be thinking of the ability to explicitly pass by reference at call time.</p>

<p><a href="http://www.php.net/manual/en/ini.core.php#ini.allow-call-time-pass-reference">http://php.net/manual/en/…</a></p>

<p>If not, I believe you are incorrect about the use of references not being useful here and in PHP 5 and in general and would advise you to read the manual section regarding references.</p>

<p><a href="http://www.php.net/manual/en/language.references.php">http://php.net/manual/en/…</a></p>

<p>In this particular case, I believe a reference was used for performance reasons so that the call time parameter would not be copied into the actual parameter since it has the potential to be large.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Adami (pitilezard) on 2006-07-21T01:28:38.000+0000</p> 
        <div class="body">
            <p>Of course but this removes the availability of quick calls !!</p>

<p>You have to do :</p>

<pre class="highlight"><code>
$myarray = array(...);
insert($myarray);
</code></pre>

<p>instead of</p>

<pre class="highlight"><code>
insert(array( ... ));
</code></pre>

<p>That's not an amazing mistake, just a convenient way pruned !</p>

<p>My two cents ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:22:38.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.8.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-05T17:06:24.000+0000</p> 
        <div class="body">
            <p>Recategorize as Zend_Db_Table component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-04T14:31:37.000+0000</p> 
        <div class="body">
            <p>Resolve in revision 3658.  Included in ZF 0.9.0.</p>

        </div>
    </div>
    </div>

