<h2>ZF-2940: self::NO_ACTION documented but not implimented</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-21T11:53:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-01-07T16:56:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Lewis Johnston (orangehairedboy)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.db.table.relationships.html#zend.db.table.relationships.cascading">http://framework.zend.com/manual/en/…</a></p>

<p>"No cascading update is done in the example below if the primary key value in the parent class is changed. The 'onUpdate' element of the reference map entry is self::RESTRICT. You can get the same result using the value self::NO_ACTION, or by omitting the 'onUpdate' entry."</p>

<p>The self::NO_ACTION constant is not defined in Zend_Db_Table_Abstract, but it is documented.</p>

<p>Either a) implement this or b) remove it from the documentation and inform users clearly that if onUpdate and onDelete are not specified, no cascading will be performed. The documentation causes some confusion here - it could be read that by declaring $_dependentTables that cascading WILL happen UNLESS you you specify self::NO_ACTION, but glancing at the source - this does not seem to be the case.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:43:51.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T13:17:29.000+0000</p> 
        <div class="body">
            <p>Reassigning to Ralph since he's the new maintainer of Zend_Db</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-01-07T16:56:26.000+0000</p> 
        <div class="body">
            <p>fixed by dropping the reference to self::NO_ACTION</p>

        </div>
    </div>
    </div>

