<h2>ZF-2031: testTemperatureSetType1(Zend_Measure_TemperatureTest) failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-10-03T04:15:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-11-06T12:51:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.3 (30/Nov/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Measure</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1.0-Branch, revision 6577:</p>

<p>1) testTemperatureSetType1(Zend_Measure_TemperatureTest)
Zend_Locale_Math_Exception: division overflow: -7.3333333333333E+240000000 / 1.25 != -INF
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Measure/Abstract.php:229
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/Measure/TemperatureTest.php:333</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-04T09:51:40.000+0000</p> 
        <div class="body">
            <p>Integrated trunk into branch.
Please check the latest revision and give us feedback.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-11-06T01:58:33.000+0000</p> 
        <div class="body">
            <p>Works with 1.0-Branch, revision 6754.</p>

        </div>
    </div>
    </div>

