<h2>ZF-2669: Zend_Db_Adapter_StaticTest failing (1.0-branch)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-17T06:12:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-17T13:18:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2033">ZF-2033</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1) testDbFactoryAlternateNamespace(Zend_Db_Adapter_StaticTest)
Caught exception of type Zend_Exception where none was expected: File "Static.php" was not found</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-04T15:59:32.000+0000</p> 
        <div class="body">
            <p>Resolved as duplicate of ZF-2033</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T13:18:16.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Closing and assigning all old unassigned issues. The only unassigned issues should be new and unreviewed.</p>

        </div>
    </div>
    </div>

