<h2>ZF-2397: Zend_Validate classes should have consistent values for error message constants</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-01-08T15:22:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-08T06:48:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3164">ZF-3164</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hector Virgen <a href="http://www.nabble.com/Zend_Validate-consistancy-to14695555s16154.html">writes @ fw-mvc</a>:</p>

<p>If it's not too much to ask, can we have some consistency in the values for the constants in the Zend_Validate classes?</p>

<p>Some of them have the class name in the constant value, while others don't.</p>

<p>For example, {{Zend_Validate_StringLength::TOO_LONG}} is {{'stringLengthTooLong'}}, while {{Zend_Validate_Between::NOT_BETWEEN}} is {{'notBetween'}}.</p>

<p>This probably wouldn't be a big issue but when creating validators for {{Zend_Filter_Input}} I find myself having to reference the API often to find the actual constant value when creating custom error messages:</p>

<pre class="highlight"><code>
$validators = array(
   'search'        =&gt; array(
   'presence'      =&gt; 'required',
   array('StringLength', 2, 96),
       'messages'      =&gt; array(
           array(
               'stringLengthTooShort' =&gt;
                   'Your search query must be at least %min% characters in length.',
               'stringLengthTooLong' =&gt;
                   'Your search query may not be greater than %max% characters in length.',
           )
       )
   )
)
</code></pre>

<p>Thank you.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:30.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:11:54.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2008-11-08T06:48:43.000+0000</p> 
        <div class="body">
            <p>This is a duplicate of #ZF-3164</p>

        </div>
    </div>
    </div>

