<h2>ZF-277: form helpers should generate a default id attribute</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-07-21T04:52:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sami Samhuri (sjs)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Right now each form element defined using the helpers requires an id attribute be explicitly passed in. I think it's safe to say most people would want an id attribute equal to the name to manipulate the element with CSS or JavaScript. If they want something different they can pass it in $attribs.</p>

<p>I propose that something like the following code be added to FormElement.php, after the readonly/disable stuff (line 118 or so here):</p>

<pre class="highlight"><code>
// set a default id equal to the name, unless attribs has an id key
if (isset($info['attribs']['id'])) {
    $info['id'] = $info['attribs']['id'];
} else {
    $info['id'] = $info['name'];
}
</code></pre>

<p>Then each of FormText, FormSubmit, FormReset, etc. needs a line similar to the following added to it.</p>

<pre class="highlight"><code>
. ' id="'    . htmlspecialchars($id)    . '"'
</code></pre>

<p>This has made my life much easier here. I can provide a patch if anyone wants it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-07T14:23:56.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 1484 of subversion. 'id' attribute now set for all form elements except checkboxes and radio buttons (these would need something quite a bit more complex); id attribute set to name attribute value if no id attribute provided.</p>

        </div>
    </div>
    </div>

