<h2>ZF-2556: Not delete mail from POP server</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-02-04T02:37:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-04-22T11:15:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bonneau Pierre (pmithrandir)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Nico Edtinger (nico)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In many webmail or mail software, i can configure my mail account with param : Keep messages on the server.</p>

<p>When i download message from my google account, there will be delete. The problem is that i don't create a full webmail but a simple read system.
Every time i open my site i empty my mail account.</p>

<p>If this is possible to make a param to configure this ?</p>

<p>Thanks
Pierre</p>

<p>Bonjour</p>

<p>Dans beaucoup de logiciels de mails on peut apercevoir une case : garder les messages sur le serveur qui permet de ne pas suprimer les message du serveur mail et donc de les retelecharger depuis un autre logiciel.
Dans zend mail, je ne vois pa cette fonctionnalité. Le probleme dans mon cas est que je fais juste un apercu des mails et donc aucune sauvegarde. A chaque ouverture de la page, je vide mon compte POP (Compte GMAIL).</p>

<p>Y a t'il moyen de permettre une telle configuration ?</p>

<p>Merci
Pierre Bonneau</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T15:48:53.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize/assign as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nico Edtinger (nico) on 2008-04-22T11:15:39.000+0000</p> 
        <div class="body">
            <p>We don't delete any messages unless you call removeMessage(), we are also not changing any flags, but an IMAP server will remove the recent flag. The option "keep mails on server" in your typical mail client does just this - do a second request to delete the message or change flags. I thought about adding such an option (mark as read/delete if fetched), but haven't done so yet (and it won't be the default).</p>

<p>You mentioned google any I guess the problem might be your gmail settings. Under "Forwarding and POP/IMAP" there is this option "When messages are accessed with POP" and if it's set to delete that's what it'll do.</p>

        </div>
    </div>
    </div>

