<h2>ZF-2678: Gbase demo has invalid code for adding a link (commented out)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-18T13:51:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-18T13:53:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The demo located at demos/Zend/Gdata/Gbase.php has some code inside a comment for adding a link to an item.  This code is invalid, as it doesn't take into account that $entry-&gt;link is an array.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2008-02-18T13:53:02.000+0000</p> 
        <div class="body">
            <p>Resolved in r8136.</p>

        </div>
    </div>
    </div>

