<h2>ZF-2450: New rows created with createRow() contain all null fields</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-01-17T23:22:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-17T16:17:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Hector Virgen (djvirgen)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Simon Mundy (peptolab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1870">ZF-1870</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When news rows are created with createRow(), all of the row's fields are set to null. This causes problems when attempting to save the row to the database using save() if the table does not allow null fields. An exception is thrown when using the MySQLi adapter.</p>

<p>If possible, createRow() should set all of its fields to the field's default value according to the meta data in order to be consistent with the database's normal operation of the simple insert query.</p>

<p>Alternatively, createRow() could return a row with no fields at all (or set to an internal "not set" value), thus allowing save() to determine which fields have been set before using save(), and only use those fields when constructing the INSERT statement. The resulting SQL would then be the simplest insert possible, and allow SQL to handle missing fields appropriately.</p>

<pre class="highlight"><code>
INSERT INTO `table` SET `id` = NULL
</code></pre>

<p>The PHP code to reproduce the same insert should be:</p>

<pre class="highlight"><code>
$row = $table-&gt;createRow();
$row-&gt;save();
</code></pre>

<p>The current alternative for saving new rows to a table is to use insert(), which works properly when fields are omitted.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2008-02-16T21:03:04.000+0000</p> 
        <div class="body">
            <p>We already have a way of tracking 'clean'/'dirty' data so this won't be hard to achieve. Will book it in ASAP.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2008-02-17T16:17:03.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk r8110</p>

        </div>
    </div>
    </div>

