<h2>ZF-2736: Add rerouting for translations</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-02-27T05:25:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-16T10:37:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A new feature should be added.
It should be possible to use a sort of routing mechanism for non-translated messageid's.</p>

<p>If a messageid is not translated in a particular language it should automatically look for another defined language...
So you should be possible to do something like this:</p>

<p>Translate Spain:
String 1 not translated in spain -&gt; goto French -&gt; String 1 not translated in French -&gt; goto German -&gt; String 1 not translated in german  -&gt; return messageid</p>

<p>a new "setDefault" method should be able to define such fallback rules.
So strings which are not translatable in one language will be returned in another language.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Loïc Frering (loic.frering) on 2009-05-27T01:55:34.000+0000</p> 
        <div class="body">
            <p>I would really enjoy to see this feature implemented =)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-05-16T10:37:07.000+0000</p> 
        <div class="body">
            <p>Feature implemented with r22182</p>

<p>See the manual or my blog for details</p>

        </div>
    </div>
    </div>

