<h2>ZF-2979: Form elements are not XHTML 1.0 strict</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-03-27T02:28:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-27T06:02:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Tom Holder (tholder)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The title says it all really. Standard form elements fail XHTML 1.0 Strict validation.</p>

<p>I've added as an 'improvement' because it's not technically broken, but it is a bit of a show stopper for anyone using strict.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-27T06:02:03.000+0000</p> 
        <div class="body">
            <p>In order for elements to be rendered using XHTML 1.0 Strict, you will first need to use the doctype() view helper to set your doctype:</p>

<pre class="highlight"><code>
$view-&gt;doctype('XHTML1_STRICT');
</code></pre>

<p>This should be done prior to rendering the form. Once you have done so, all elements <em>will</em> be rendered using that doctype.</p>

<p>You may re-open the issue if you find cases of individual element types that do not validate; if you do, please specify exactly which elements they are.</p>

        </div>
    </div>
    </div>

