<h2>ZF-211: can't commit on the file TestConfiguration.php.dist</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-07-08T15:50:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.5 (11/Jul/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-203">ZF-203</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I can't solve the issue ZF-203 ( <a href="http://framework.zend.com/issues/browse/ZF-203">http://framework.zend.com/issues/browse/ZF-203</a> ) because I have no commit rights on the file TestConfiguration.php.dist.</p>

<p>If zend doesn't want to increase my commit rights on this file, may someone with enough karma add following lines in this file ?</p>

<p>/**
 * Zend_Cache
 *
 * TESTS_ZEND_CACHE_SQLITE =&gt; sqlite extension has to be enabled
 */
define('TESTS_ZEND_CACHE_SQLITE', false);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jayson Minard (jayson) on 2006-07-09T00:54:33.000+0000</p> 
        <div class="body">
            <p>Please commit his patch, and resolve the related ZF-203 issue.  I'm marking for 0.1.5 in case it makes it in time, otherwise move fix version back to 0.2.0 for both issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jayson Minard (jayson) on 2006-07-09T00:54:58.000+0000</p> 
        <div class="body">
            <p>This is the patch for ZF-203, so I'm linking them.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jayson Minard (jayson) on 2006-07-11T11:54:40.000+0000</p> 
        <div class="body">
            <p>0.1.5 released</p>

        </div>
    </div>
    </div>

