<h2>ZF-2201: Apache Crash on Zend_Db_Select</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-11-14T08:48:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-07T13:27:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sean Holt-Carden (mordist)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
            <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is a simple function I use to get a parseable string out of for an AJAX call on the site. I put the die() at the end so that the header/footer are not sent to the client.</p>

<p>function getStatusAction() {
    $id = $this-&gt;_request-&gt;getParam("id");
    if (!$id)
        die(", No ID sent\n");
    $db = Zend_Registry::get('db');
    $stmt = $db-&gt;query("SELECT ds.*, st.id AS st_id, st.* FROM deliverables_status AS ds INNER JOIN status_types AS st ON ds.status_type=st.id WHERE ds.deliverable={$id}");
    $res = $stmt-&gt;fetchAll();
    // This is where i'd loop through the results to print out the list, but it never gets here. It crashes on the $db-&gt;query() line.
    print ", YAY\n";
    die();
}</p>

<p>This crashes Apache running :
httpd-2.0.59-1.el4s1.8.el4.centos
mysql-5.0.48-1.el4.centos
php-cli-5.1.6-3.el4s1.8
php-mysql-5.1.6-3.el4s1.8
php-pear-1.4.11-1.el4s1.1
php-5.1.6-3.el4s1.8
php-gd-5.1.6-3.el4s1.8
php-soap-5.1.6-3.el4s1.8
php-common-5.1.6-3.el4s1.8
php-pdo-5.1.6-3.el4s1.8
php-mbstring-5.1.6-3.el4s1.8
php-xmlrpc-5.1.6-3.el4s1.8</p>

<p>OS Version: CentOS release 4.5 (Final)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2008-02-20T23:49:14.000+0000</p> 
        <div class="body">
            <p>Could you post the error from your server log?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Holt-Carden (mordist) on 2008-02-21T00:43:11.000+0000</p> 
        <div class="body">
            <p>I'm afraid I no longer have access to those log files, I don't work at that company anymore. All I can tell you is that it was a standard Apache crash (core dump) error message... But I don't remember any specifics... If any relevant information was given I could have fixed it myself.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2008-02-21T00:49:23.000+0000</p> 
        <div class="body">
            <p>Was it using the Mysqli adapter?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Holt-Carden (mordist) on 2008-02-21T07:49:47.000+0000</p> 
        <div class="body">
            <p>Yes it was.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2008-02-21T10:26:24.000+0000</p> 
        <div class="body">
            <p>Were any of the fields LONGBLOB or LONGTEXT? There is a known issue (ZF-1498) where these columns cause Apache to crash.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Holt-Carden (mordist) on 2008-02-21T12:30:57.000+0000</p> 
        <div class="body">
            <p>No, neither were of that type... standard int or varchar fields.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:32.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:12:02.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:20:27.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-10-12T15:01:12.000+0000</p> 
        <div class="body">
            <p>I have a similar problem where Apache 2.x crashes on Vista Business, PHP 5.2.5. This happens when I try to update from Zend_Db_Table_Abstract inheritor. Zend_Db::update works fine with the same query setup.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-10-12T15:02:41.000+0000</p> 
        <div class="body">
            <p>I think this affect latest trunk, at least the crash on update does, see my comment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-10-12T15:07:21.000+0000</p> 
        <div class="body">
            <p>//works
$this-&gt;db-&gt;update($this-&gt;_name, $this-&gt;data,$this-&gt;buildCriteria($keys));</p>

<p>//crashes apache
$this-&gt;update($this-&gt;data, $this-&gt;buildCriteria($keys, false));</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-10-13T12:55:06.000+0000</p> 
        <div class="body">
            <p>Forget about my previous comments. The reason Apache crashed in my case on Zend_Db_Table was that I was calling $this-&gt;update() inside $this-&gt;update function. Stupid. It caused an infinite loop while calling itself. What I ment to do was call parent::update() inside $this-&gt;update().</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T13:17:31.000+0000</p> 
        <div class="body">
            <p>Reassigning to Ralph since he's the new maintainer of Zend_Db</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-01-10T10:42:57.000+0000</p> 
        <div class="body">
            <p>Is this still an issue?  Was that 64bit machine by chance?  If so I will attempt to create a unit test for this issue.  If not, i'll close.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-05-07T13:27:48.000+0000</p> 
        <div class="body">
            <p>Cannot reproduce this test case.  If you have a simple db &amp; simple use case code, please provide it.</p>

<p>Also, please note if this is a 64bit machine.</p>

        </div>
    </div>
    </div>

