<h2>ZF-2806: Zend_Form_Element NotEmpy validation when required is set to true</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-05T02:08:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-05T07:00:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11168/screenshot-1.jpg">screenshot-1.jpg</a></li>
            <li><a href="/issues/secure/attachment/11169/screenshot-2.jpg">screenshot-2.jpg</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I add to Zend_Form_Element_Text Alnum validation and set this field as required. Then automatically is applied NotEmpty validation. There is two problems i found. 
First you are not able to change the default message for NotEmpty validation. 
Second Alnum validation has  himself check for empty string but this is not applied until i add NotEmpty validation.</p>

<pre class="highlight"><code>
$form = new Zend_Form();

$form-&gt;addElement('text', 'username', array('label'=&gt;'Потербител'));

$userAlnum = new Zend_Validate_Alnum();
$userAlnum-&gt;setMessage(
    'Моля въведете потребителско име!',
    Zend_Validate_Alnum::STRING_EMPTY
);
$userAlnum-&gt;setMessage(
    'Потебителкото Ви име трябва да съдържа само букви и числа',
    Zend_Validate_Alnum::NOT_ALNUM
);
        
$userNotEmpty = new Zend_Validate_NotEmpty();
$userNotEmpty-&gt;setMessage(
    'Моля въведете потребителско име!',
    Zend_Validate_NotEmpty::IS_EMPTY
);
        
$form-&gt;username-&gt;addValidator($userNotEmpty);
$form-&gt;username-&gt;addValidator($userAlnum);
        
$form-&gt;username-&gt;setRequired(true);
</code></pre>

<p>See screen shot 1.</p>

<pre class="highlight"><code>
$form = new Zend_Form();

$form-&gt;addElement('text', 'username', array('label'=&gt;'Потербител'));

$userAlnum = new Zend_Validate_Alnum();
$userAlnum-&gt;setMessage(
    'Моля въведете потребителско име!',
    Zend_Validate_Alnum::STRING_EMPTY
);
$userAlnum-&gt;setMessage(
    'Потебителкото Ви име трябва да съдържа само букви и числа',
    Zend_Validate_Alnum::NOT_ALNUM
);
        
$userNotEmpty = new Zend_Validate_NotEmpty();
$userNotEmpty-&gt;setMessage(
    'Моля въведете потребителско име!',
    Zend_Validate_NotEmpty::IS_EMPTY
);
        
//$form-&gt;username-&gt;addValidator($userNotEmpty);
$form-&gt;username-&gt;addValidator($userAlnum);
        
$form-&gt;username-&gt;setRequired(true);
</code></pre>

<p>See screen shot 2.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-05T06:49:02.000+0000</p> 
        <div class="body">
            <p>First, in your second example you never associated your custom NotEmpty validator with the form -- you only added the $userAlnum validator. If you add your own NotEmpty validator to the element, then Zend_Form_Element will not attempt to add one itself.</p>

<p>Second, you can actually disable having required autoload a NotEmpty validator by calling:</p>

<pre class="highlight"><code>
$element-&gt;setAutoInsertNotEmptyValidator(false);
</code></pre>

<p>(this can be called from a configuration key as well as the key 'autoInsertNotEmptyValidator')</p>

<p>Finally, I'd recommend that you use translation files to set your messages instead of setting them manually. This will work globally and not require changes to your code.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hristo Angelov (hedonism) on 2008-03-05T07:00:46.000+0000</p> 
        <div class="body">
            <p>Yes i don't add NotEmpty validation second time to show that i cant costume the message for empty string. And i want to show that when i don't have NotEmpty validation Zend_Validate_Alnum::STRING_EMPTY message is not shown. But when i have it is shown. I think it is kind of mess there. When i insert Alnum validation this means that the string in field cannot be empty and when is empty Zend_Validate_Alnum::STRING_EMPTY message sholud be shown instead of non costuming NotEmpty validation message .</p>

        </div>
    </div>
    </div>

