<h2>ZF-2185: Public refresh() method in Zend_Db_Table_Row_Abstract</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-11-13T10:29:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Justin Plock (jplock)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10920/Zend_Db_Table_Row_Abstract+refresh.diff">Zend_Db_Table_Row_Abstract refresh.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I often find it useful to refresh a row from the database.  Can we either make the _refresh() method public (it is currently protected) or can we make a public refresh() method which executes the protected _refresh() to preserve BC?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Justin Plock (jplock) on 2007-11-27T12:54:05.000+0000</p> 
        <div class="body">
            <p>Is this going to make it into 1.0.3?  I have commit access to Zend_Db, can I commit this to the trunk at least?</p>

        </div>
    </div>
    </div>

