<h2>ZF-2559: Email subject encoding bug</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-04T09:11:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-28T02:16:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.3 (19/Jan/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sergey Voyachek (voyachek)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6263">ZF-6263</a></li>
            <li><a href="/issues/browse/ZF-3067">ZF-3067</a></li>
            <li><a href="/issues/browse/ZF-6267">ZF-6267</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11684/header.patch">header.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I tried to send letter using charset 'cp1251' or 'win1251'. For this purpose I created new instance of Zend_Mail passed this charset in constructor. Then called functions setSubject and setBodyHtml pointed my message.</p>

<pre class="highlight"><code>
$mail = new Zend_Mail('cp1251');
$mail-&gt;setSubject('Поздравляем с успешной регистрацией');
$mail-&gt;setBodyHtml("<b>Blah-blah</b>");
</code></pre>

<p>Receved message has problem with subject. 
The subject has useless symbol. 
GMail: 'Поздравляем с успешной рег<em>истрацией' ('</em>' means space) 
Yandex: 'Поздравляем с успешной рег=<em>истрацией' ('</em>' means space) 
Mail.ru: 'Поздравляем с успешной регE8истрацией'</p>

<p>I think that problem happened around cyrillic symbols.</p>

<p>Thank you!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jonathan Bond-Caron (jbondc) on 2008-02-08T12:11:40.000+0000</p> 
        <div class="body">
            <pre><code>protected function _encodeHeader($value)
{
  if (Zend_Mime::isPrintable($value)) {
      return $value;
  } else {
      return '=?' . $this-&gt;_charset . '?B?' . Zend_Mime::encodeBase64($value) . '?=';
  }
</code></pre>

<p>This should fix your problem, the problem is Zend_Mime::encodeQuotedPrintable looks buggy so I used a B encode (base64) on the subject . This was the quick fix for me, I'll try to put togheter a patch and fix  Zend_Mime::encodeQuotedPrintable.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T13:30:24.000+0000</p> 
        <div class="body">
            <p>Was this fixed in the repository? If not, this should probably be marked 'won't fix'.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T13:31:02.000+0000</p> 
        <div class="body">
            <p>Please verify resolved status.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sergey Voyachek (voyachek) on 2008-12-18T01:57:32.000+0000</p> 
        <div class="body">
            <p>I wrote the same patch and problem was resolved.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Bond-Caron (jbondc) on 2008-12-18T06:31:37.000+0000</p> 
        <div class="body">
            <p>The patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Bond-Caron (jbondc) on 2008-12-18T06:35:26.000+0000</p> 
        <div class="body">
            <p>I attached the 'quick fix' patch, please commit</p>

<p>Another issue should probably be opened for Zend_Mime::encodeQuotedPrintable, more testing with utf-8?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-02T22:54:20.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r13496.</p>

<p>1) Change _encodeHeader() can encode by not only quotedPrintable but also by Base64.</p>

<p>2) Add $_encodingOfHeaders and setter/getter functions.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-23T06:46:01.000+0000</p> 
        <div class="body">
            <p>I changed the name to $_headerEncoding</p>

        </div>
    </div>
    </div>

