<h2>ZF-2403: Zend_View_Helper_Head* muilt view support</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-01-09T13:20:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2399">ZF-2399</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When you call</p>

<pre class="highlight"><code>
$this-&gt;action('index2');
</code></pre>

<p>inside an action and the index2 action calls this</p>

<pre class="highlight"><code>
$this-&gt;headLink()-&gt;appendStylesheet('/css/talkback.css');
$this-&gt;headScript()-&gt;appendFile('/js/talkback/threaded.js');
</code></pre>

<p>whatever is added with head* helper in the second action does not get appended to the layout when it's rendered.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-01-09T15:12:03.000+0000</p> 
        <div class="body">
            <p>When you say "inside an action", do you mean inside an action controller method? I need more context.</p>

<p>The action() view helper by itself does not act as a placeholder, it simply returns content; as such, if you want it to appear in the layout script, you need to either put it in a placeholder, or include it in content that will be aggregated into the layout.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-01-09T19:08:51.000+0000</p> 
        <div class="body">
            <p>Ok here is what i do.</p>

<p>i request a page lets say <a href="http://test.com/news/story/My_Story">http://test.com/news/story/My_Story</a></p>

<p>In my setup that would make it Module of news controller of story and the defualt index action as My_Story is the title of the story which is how I know which story to fetch from the db.  inside of the index action i call get the story and assign it to a view.</p>

<p>inside of my view script i have the code to out put the story.</p>

<p>at the bottom of the view script i call this code.</p>

<pre class="highlight"><code>
&lt;?= $this-&gt;action('index', 'news', 'talkback', array('story_id' =&gt; $this-&gt;story-&gt;release_id)) ?&gt;
</code></pre>

<p>which call the talkback module news controller index action which if talkback exists for the passed in release then it will spit out the necessary code for the talkback module on the page.</p>

<p>The way i think this should work is that i should beable to specify any addition css/js/meta data that is needed in that action even though it's begin call through the action helper.</p>

<p>Doest that make sense?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-01-29T14:13:29.000+0000</p> 
        <div class="body">
            <p>When you say "inside of my view script", is this the view script rendered for the action, or your layout script?</p>

<p>If the call to $this-&gt;action() is occurring in your layout script, then this won't work; it's being executed <em>after</em> the other helpers have already created their output. If it's happening in your view script, but <em>before</em> the layout script is rendered, then there's a definite issue.</p>

<p>Could you confirm the sequence of events?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-01-29T15:02:32.000+0000</p> 
        <div class="body">
            <p>it it called from the action and not the layout.</p>

<p>so i call $this-&gt;render('designs') at the end of an action to render the designs.phtml for the current module.  Inside side of that i have the $this-&gt;action('design_nav','navigation','designid', array()) call to render the local navigation or some other piece of this page.  but when i try add scripts or css files from that action they do not get added.</p>

<p>does that make sense?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-01T11:26:55.000+0000</p> 
        <div class="body">
            <p>Changing release target to next minor release, as functionality will not be released before then.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-19T16:30:34.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk; please test.</p>

        </div>
    </div>
    </div>

