<h2>ZF-2732: senseless &quot;throw $e&quot; in deleteFile()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-26T04:22:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-14T01:55:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11170/Zend_Search_Lucene_Storage_Directory_Filesystem.patch">Zend_Search_Lucene_Storage_Directory_Filesystem.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Search_Lucene_Storage_Directory_Filesystem::deleteFile() at line 215</p>

<p>There is a "throw $e" without catching an exception... think it wasn´t removed before committing.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2008-02-26T04:22:54.000+0000</p> 
        <div class="body">
            <p>Added diff to fix problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-02-26T13:39:38.000+0000</p> 
        <div class="body">
            <p>I'm on it.
Some other improvements can be made as well.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eric Marden (xentek) on 2008-03-05T12:58:31.000+0000</p> 
        <div class="body">
            <p>Also ran into this issue. I know more clean up was needed, but wanted to report that I had success with applying the diff to my local. Using 1.5RC1</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-03-05T15:03:13.000+0000</p> 
        <div class="body">
            <p>The patch attached is a fix and adds different improvements to the file.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-03-05T17:26:00.000+0000</p> 
        <div class="body">
            <p>Yes, it was non-removed debugging statement.
Just fixed this.</p>

<p>I am not sure other things in offered patch should be applied.
As I described in e-mail, ini_restore() restores configuration option to 'configuration file value' instead of 'last effective value'.
There are also some reasons to use current if(...)  {...} else { if(...) ... } construction in the Zend_Search_Lucene_Storage_Directory_Filesystem constructor</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eric Marden (xentek) on 2008-03-18T11:07:13.000+0000</p> 
        <div class="body">
            <p>The throw $e; is still in the framework (v1.5 GA).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-21T14:59:53.000+0000</p> 
        <div class="body">
            <p>Is this still an issue in 1.5.1? Was the fix ever merged back to the 1.5 branch? Please take appropriate action and update the issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-04-21T15:06:36.000+0000</p> 
        <div class="body">
            <p>Alex should have fixed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by twk (twk) on 2008-06-13T20:58:33.000+0000</p> 
        <div class="body">
            <p>Not fixed in 1.5.2</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-06-14T01:55:21.000+0000</p> 
        <div class="body">
            <p>merged from trunk to 1.5 branch at r9683.
Should be ok for next 1.5 release</p>

        </div>
    </div>
    </div>

