<h2>ZF-2569: Missing ? in open PHP tag</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-02-05T03:26:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T20:50:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Curtis Kaffer (kaffer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Layout</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>in section 20.2.1 in the 2nd code snippet:</p>

<div>&lt;= $this-&gt;layout()-&gt;content ?&gt;</div>

<p>should be</p>

<div>&lt;?= $this-&gt;layout()-&gt;content ?&gt;</div>

<p>(note the missing ?)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-02-05T14:08:34.000+0000</p> 
        <div class="body">
            <p>Fixed within trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T20:50:13.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

