<h2>ZF-2042: set() doesn't accept a timezone with the RSS constant.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2007-10-04T10:14:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-10-16T07:17:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Paul Menheere (paulmenheere)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>set() function doesn't accept a timezone as some rss feeds use.</p>

<p>it only accepts +0100 or something like that.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Paul Menheere (paulmenheere) on 2007-10-04T10:33:08.000+0000</p> 
        <div class="body">
            <p>Okay,</p>

<p>I've found the problem...</p>

<p>although the RFC 822 specification states that you should use 2 digits for the year, every specification for RSS says you can use 4.</p>

<p>When you use the RSS constant in Zend_Date, it would match against Timezone identifiers as RFC_822 would do.</p>

<p>So you need only to make a small adjustment in Zend/Date.php on line 2529 :</p>

<pre class="highlight"><code>
case Zend_Date::RSS :
                $result = preg_match('/^\w{3},\s\d{2}\s\w{3}\s\d{4}\s\d{2}:\d{2}:\d{2}\s[+-]{1}\d{4}$/', $date, $match); 
      if(!$result)
{
// Check for timezone
$result = preg_match('/^\w{3},\s\d{2}\s\w{3}\s\d{4}\s\d{2}:\d{2}:\d{2}\s[+-]{1}\w{1,3}/', $date, $match);
}

if (!$result) {
                    throw new Zend_Date_Exception("invalid date ($date) operand, RSS date format expected", $date);
                }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Paul Menheere (paulmenheere) on 2007-10-04T10:35:59.000+0000</p> 
        <div class="body">
            <p>preg_match pattern should be</p>

<pre class="highlight"><code>
'/^\w{3},\s\d{2}\s\w{3}\s\d{4}\s\d{2}:\d{2}:\d{2}\s\w{1,3}/'
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-10-04T15:20:14.000+0000</p> 
        <div class="body">
            <p>Please give some real live examples...</p>

<p>Originally RSS only accepts the related RFC specification as also PHP itself does as output.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-10-04T15:38:53.000+0000</p> 
        <div class="body">
            <p>It seems that you are not using 1.0.2 as you stated, but the outdated 1.0 release.</p>

<p>Within release 1.0.2 the line 2529 is an empty whitespace line.
The mentioned line for RSS is line 2446 and the content is:</p>

<pre class="highlight"><code>
            case Zend_Date::RSS :
                $result = preg_match('/^\w{3},\s(\d{2})\s(\w{3})\s(\d{2,4})\s(\d{2}):(\d{2}):(\d{2})\s.{3,21}$/', $date, $match);
</code></pre>

<p>Which means that all represenations are accepted...
RSS 1.0
RSS 2.0
and both with numeric or textual timezone represenations.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-10-04T15:48:17.000+0000</p> 
        <div class="body">
            <p>Your problem is identical with an other issue which is already closed.
Please see old closed issues for Zend_Date.</p>

<p>The issue has not found it's way into the release because the code was not prooved by another person.
This has to be done before anything is committed into branch.</p>

<p>To get the actual fixed version, you can download the actual trunk where the mentioned change was already done a few weeks ago or wait for the next release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-10-10T13:54:50.000+0000</p> 
        <div class="body">
            <p>As an equal issue is already fixed within release 1.0.2 and we are not getting response from the reporter we are closing this issue.</p>

<p>The given code does not match with the given release 1.0.2</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Paul Menheere (paulmenheere) on 2007-10-16T04:52:41.000+0000</p> 
        <div class="body">
            <p>The changes aren't avaible in the download from the site in the release in version 1.0.2</p>

<p>Then another thing, in the feed <a href="http://www.nhl.com/rss/news.xml">http://www.nhl.com/rss/news.xml</a></p>

<p>they use 1 or 2 digits for the hours.
and that doesn't work either</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-10-16T06:40:42.000+0000</p> 
        <div class="body">
            <p>As already mentioned in an earlier reply:</p>

<p>{quote}
To get the actual fixed version, you can download the actual trunk where the mentioned change was already done a few weeks ago or wait for the next release.
{quote}</p>

<p>Related to 1 or 2 digit hours...
Then the field you expect to be a date is not an RSS Date.</p>

<p>see <a href="http://www.rssboard.org/rss-specification">http://www.rssboard.org/rss-specification</a> search for date
"RSS datefields" are to be defined with the RFC822 definition.</p>

<p>see <a href="http://asg.web.cmu.edu/rfc/rfc822.html">http://asg.web.cmu.edu/rfc/rfc822.html</a> search for hour
hour = 2 Digit  ":" 2 Digit [ ":" 2 Digit]</p>

<p>One digit is strictly against the RSS definition and will not be supported by the RSS constant.
Instead you can use the ISO8601 definition which is not so strict but needs more time for parsing.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Paul Menheere (paulmenheere) on 2007-10-16T07:16:59.000+0000</p> 
        <div class="body">
            <p>I'll contact the NFL so they can change it</p>

        </div>
    </div>
    </div>

