<h2>ZF-2883: Elements in DisplayGroups do not adhere to array notation of parent sub form</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-14T07:55:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-03-03T02:18:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li> 1.5.2 (15/May/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3146">ZF-3146</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you have a display group within a sub form, the elements contained by the display group do not get namespaced within the rendered form correctly, which leads to issues during form submission.</p>

<p>For example:</p>

<pre class="highlight"><code>
$subForm = new Zend_Form_SubForm();
$subForm-&gt;setLegend('Attributes');

$subForm-&gt;addElement('text', 'foo')
        -&gt;addElement('text', 'bar')
        -&gt;addDisplayGroup(array('foo', 'bar'), 'foobar');

$form = new Zend_Form();
$form-&gt;addSubForm($subForm, 'attributes');
echo $form-&gt;render(new Zend_View());
</code></pre>

<p>One would expect the following HTML:</p>

<pre class="highlight"><code>

    </code></pre><code>
        Attributes
            </code><code>
                </code><code>
                    
                    
                    
                
            
    
</code>

<p>But the following is actually received:</p>

<pre class="highlight"><code>

    </code></pre><code>
        Attributes
            </code><code>
                </code><code>
                    
                    
                    
                
            
    
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T22:02:49.000+0000</p> 
        <div class="body">
            <p>Resetting 'fix version priority' and 'fix version' to be re-evaluated for next release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-04-22T11:53:20.000+0000</p> 
        <div class="body">
            <p>Scheduling for next mini release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-08T07:00:02.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.5 release branch as of r9406</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by xqsys (xqsys.com) on 2013-03-03T02:18:02.000+0000</p> 
        <div class="body">
            <p>think it is fixed in 1.12</p>

        </div>
    </div>
    </div>

