<h2>ZF-2142: Allow the where() method of Zend_Db_Select to accept multiple arguments for automatic quoting</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-11-04T13:53:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-05T23:37:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Reopened</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2228">ZF-2228</a></li>
            <li><a href="/issues/browse/ZF-2227">ZF-2227</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently the where method of Zend_Db_Select allows to call the where() method with a second parameter that gets quoted substituted into the first parameter and replaces the placeholder (question mark).  Since the where() method can be called multiple times, multiple parameters can be quoted.</p>

<pre class="highlight"><code>
$select = $db-&gt;select()
    -&gt;from("products")
    -&gt;where("product_name = ?", $prod)
    -&gt;where("price &lt; ?", $minimumPrice)
    -&gt;orWhere("price &gt; ?", $maximumPrice);
</code></pre>

<p>Unfortunately this usage makes it more difficult when you need to evaluate Boolean expressions in a specific order.  In certain cases it becomes necessary to use the non-quoted format in order to clarify the query because AND has higher precedence than OR.  Quoting must be done separately.</p>

<pre class="highlight"><code>
$minPriceQuoted = $db-&gt;quote($minimumPrice);
$maxPriceQuoted = $db-&gt;quote($maximumPrice);
$select = $db-&gt;select()
    -&gt;from("products")
    -&gt;where("product_name = ?", $prod)
    -&gt;where("price &lt; $minPriceQuoted OR price &gt; $maxPriceQuoted");
</code></pre>

<p>If the where() method accepted multiple parameters for quoting, the usage would be much less awkward:</p>

<pre class="highlight"><code>
$select = $db-&gt;select()
    -&gt;from("products")
    -&gt;where("product_name = ? AND (price &lt; ? OR price &gt; ?)", $prod, $minimumPrice, $maximumPrice);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-11-05T14:46:19.000+0000</p> 
        <div class="body">
            <p>Assigning to [~thomas].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-17T07:07:35.000+0000</p> 
        <div class="body">
            <p>Integrated to trunk...
Please check SVN8640 or later and give us feedback.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-22T03:08:35.000+0000</p> 
        <div class="body">
            <p>Solution not accepted by community and main author.
Reverted the changes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-22T03:35:46.000+0000</p> 
        <div class="body">
            <p>Unassigned as original additional where methodology was not accepted.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-01-25T13:41:44.000+0000</p> 
        <div class="body">
            <p>Integrated with SVN7576. Cored with Release 1.5</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-03-12T13:01:17.000+0000</p> 
        <div class="body">
            <p>Erased from core for review of complete component</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-01-10T10:31:46.000+0000</p> 
        <div class="body">
            <p>Will evaluate within 2 weeks</p>

        </div>
    </div>
    </div>

