<h2>ZF-2227: Allow where method to accept multiple placeholders</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-11-22T15:03:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-05T23:37:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2142">ZF-2142</a></li>
            <li><a href="/issues/browse/ZF-2228">ZF-2228</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Allow where() to accept multiple placeholders.</p>

<p>This would allow users to build clauses which are not possible with the actual implementation.</p>

<pre class="highlight"><code>
-&gt;where("((price &gt; ? or price &lt;= ?) and name like ?) or price in (?)", 1, 5, 'user%', 20, 30, 40, 50);
// where ((price &gt; 1 or price &lt;= 5) and name like 'user%') or price in (20, 30, 40, 50)
</code></pre>

<p>Multiple placeholders are quite easy to implement.
Just 3 rules which are relevant:
* If the amount of placeholders and values are equal replace each placeholder with the value
* If there are more placeholders than values some placeholders would stay within the query
* If there are more values than placeholders the not filled values would be compressed with ", value"</p>

<p>Usecase:</p>

<pre class="highlight"><code>
-&gt;where("(price &gt; ? and price &lt; ?) or name like (?)", 2, 5, 'demo%');
// where (price &gt; 2 and price &lt; 5) or name like ('demo%')
</code></pre>

<p>Usecase:</p>

<pre class="highlight"><code>
-&gt;where("(price &gt; ? and price &lt; ?) or name like (?)", 2, 5);
// where (price &gt; 2 and price &lt; 5) or name like (?)
</code></pre>

<p>There are two possibilities...
Eigther allow not filled placeholders, or throw an exception if placeholders are not filled.</p>

<p>Usecase:</p>

<pre class="highlight"><code>
-&gt;where("(price &gt; ? and price &lt; ?) or price IN (?)", 2, 5, 20, 30, 40, 50);
// where (price &gt; 2 and price &lt; 5) or price like (20, 30, 40, 50)
</code></pre>

<p>This way the old undocumented behaviour would also be accepted...
Usecase:</p>

<pre class="highlight"><code>
-&gt;where("price IN (?)", 20, 30, 40, 50);
// where price like (20, 30, 40, 50)
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-01-25T13:47:31.000+0000</p> 
        <div class="body">
            <p>Integrated with SVN7576. Cored with Release 1.5</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by C Snover (snover) on 2008-03-10T19:11:49.000+0000</p> 
        <div class="body">
            <p>Documentation should be updated to reflect this change. Currently it says (Section 10.4 Example 10.54):
{quote}
This method accepts only one parameter. If you have an expression into which you need to substitute multiple variables, you must format the string manually, interpolating variables and performing quoting yourself.
{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-03-11T03:25:41.000+0000</p> 
        <div class="body">
            <p>Documentation change necessary</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-08T16:38:33.000+0000</p> 
        <div class="body">
            <p>Thomas, are you planning to update the docs? If not, please reassign to Ralph.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-12-09T00:24:21.000+0000</p> 
        <div class="body">
            <p>Reassigned to component lead.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-05T23:37:34.000+0000</p> 
        <div class="body">
            <p>AFAIK, this was never actually implemented in trunk or has been reverted between 1.5 and now as the where method does not work as described by OP.  Regardless, this is a duplicate of ZF-2142 so closing as duplicate.</p>

        </div>
    </div>
    </div>

