<h2>ZF-2608: Add method to retrieve the complete session content</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-02-09T19:46:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-05T03:18:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ota Mares (ota)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add method to retrieve the complete session content so you dont have to access $_SESSION directly.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-04-22T10:41:08.000+0000</p> 
        <div class="body">
            <p>Updating project management info.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-01-10T11:13:40.000+0000</p> 
        <div class="body">
            <p>Are you talking about retrieveing everything inside $_SESSION regardless of the __ZF settings? or just everything from the session?  If you are talking about getting everything from the sesison, why not use $_SESSION?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ota Mares (ota) on 2009-01-12T01:51:14.000+0000</p> 
        <div class="body">
            <p>I meant the contents of the session without the __ZF part of the array.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-05T03:18:10.000+0000</p> 
        <div class="body">
            <p>This is done easily enough without changes to ZF:</p>

<pre class="highlight"><code>
$sessionData = $_SESSION; 
unset($sessionData['__ZF']);
</code></pre>

        </div>
    </div>
    </div>

