<h2>ZF-2391: Values of Multi-Elements (select...) can be &quot;out of range&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-01-07T13:31:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11051/Zend_Form_check-multi-item.patch">Zend_Form_check-multi-item.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form currently doesn't prevent bad guys from submitting forms filled with "bad" values (not being part of the available options).</p>

<p>Kind regards,
Thomas Gelf</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Gelf (tgelf) on 2008-01-07T13:37:06.000+0000</p> 
        <div class="body">
            <p>Quick &amp; dirty patch.</p>

<p>A more elegant variant would be overriding getValidatorChain(), adding some kind of Zend_Validate_IsArrayKey(). As the latter doesn't exist (and as I'm really lazy) I have chosen the approach shown in the attached patch file.</p>

<p>Cheers,
Thomas</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-01-07T13:50:02.000+0000</p> 
        <div class="body">
            <p>Please post this to the mailing list fw-mvc@lists.zend.com, and not the issue tracker. Zend_Form is in its very early stages, and not even approved as a proposal yet; sharing this on list will illicit maximum discussion during the development phase of this component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Gelf (tgelf) on 2008-01-07T14:09:07.000+0000</p> 
        <div class="body">
            <p>Done, sent through gmane (<a href="http://article.gmane.org/gmane.comp.php.zend.framework.mvc/2035">http://article.gmane.org/gmane.comp.php.zend.frame…</a>).
I hope it will find it's way to the right destination (Nabble??)...</p>

        </div>
    </div>
    </div>

