<h2>ZF-2056: Not possible to fetch tracks from amazon via Zend_Service_Amazon when there's more than one disc</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-10-10T12:14:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-15T08:41:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The variable gets overwritten when there's more than one disc.</p>

<p>Row 154-158 in Zend_Service_Amazon_Item:</p>

<pre class="highlight"><code>
foreach ($result as $disk) {
    foreach ($xpath-&gt;query('./*/text()', $disk) as $t) {
        $this-&gt;Tracks[$disk-&gt;getAttribute('number')] = (string) $t-&gt;data;
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Johannes Schill (johannes) on 2007-10-10T12:57:20.000+0000</p> 
        <div class="body">
            <p>Ok, this was my first issue, sorry for the [code]. I hope you understand anyway.</p>

<p>Instead of:
$this-&gt;Tracks[$disk-&gt;getAttribute('number')] = (string) $t-&gt;data;</p>

<p>It should be:
$this-&gt;Tracks[$disk-&gt;getAttribute('number')][] = (string) $t-&gt;data;</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-10-15T13:58:32.000+0000</p> 
        <div class="body">
            <p>Assigned to Darby</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:34.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:11:59.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-11-15T08:41:58.000+0000</p> 
        <div class="body">
            <p>Will be fixed in 1.8 or as of trunk revision r12666.</p>

        </div>
    </div>
    </div>

