<h2>ZF-2769: form() view helper should allow requesting open tag only</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-02-29T14:44:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The form() helper currently requires content, which it then wraps in a form tag. In some cases, being able to open the form only would be useful, particularly as the helper escapes all attributes. This would allow easier creation of view scripts for rendering forms created with Zend_Form.</p>

<p>Suggested API is the same; simply allow passing a boolean false value for the content, which would trigger an opening tag only:</p>

<pre class="highlight"><code>
&lt;?= $this-&gt;form('login', false, $attribs) ?&gt;
...

</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-29T15:38:51.000+0000</p> 
        <div class="body">
            <p>Updated in trunk and release-1.5 branch.</p>

        </div>
    </div>
    </div>

