<h2>ZF-2013: Implement ArrayAccess to Zend_Db_Table_Row_Abstract</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-09-28T13:37:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Artur Jedlinski (nataniel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1970">ZF-1970</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10995/Zend_Db_Table_Row_Abstract.php.diff">Zend_Db_Table_Row_Abstract.php.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'd like to be able to use array access instead of object access sometimes:</p>

<pre class="highlight"><code>$row = $Users-&gt;findRow(1);
echo $row['user']; // instead of echo $row-&gt;user;</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-09-28T14:30:40.000+0000</p> 
        <div class="body">
            <p>Assigned to Bill</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2007-12-17T13:05:07.000+0000</p> 
        <div class="body">
            <p>Attaching a patch that makes Zend_Db_Table_Row_Abstract implement ArrayAccess.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:43:55.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:12:05.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-04-24T15:33:54.000+0000</p> 
        <div class="body">
            <p>Resolved as duplicate.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-10-02T10:57:43.000+0000</p> 
        <div class="body">
            <p>Re-opening this issue... it's not a duplicate! This one's about Zend_Db_Table_Row, while the other is about Zend_Db_Table_Rowset</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-10-15T08:04:32.000+0000</p> 
        <div class="body">
            <p>Resolved in rev. 11970. Waiting for unit tests to be fixed before closing the issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:01.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

