<h2>ZF-238: RewriteRouter improvement  - changed variable requirement handling</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-07-12T04:36:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.2.0 (29/Oct/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>RewriteRouter no longer will try to set a default when a requirement of a variable is is not met. It will result in a not matched route.</p>

<p>It allows for mapping routes like:</p>

<p>$router = new Zend_Controller_RewriteRouter();
$router-&gt;addRoute('articles', 'news/view/all', array('controller' =&gt; 'test', 'action' =&gt; 'all));
$router-&gt;addRoute('article', 'news/view/:id', array('controller' =&gt; 'test', 'action' =&gt; 'one'), array('id' =&gt; '\d+'));</p>

<p>With URLs:
<a href="http://test.nebula.intranet/news/view/1">http://test.nebula.intranet/news/view/1</a>
<a href="http://test.nebula.intranet/news/view/all">http://test.nebula.intranet/news/view/all</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

