<h2>ZF-2182: Zend_CurrencyTest, Zend_DateTest failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-11-11T09:33:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-11-22T09:18:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.3 (30/Nov/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
            <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1.0-Branch:</p>

<p>1) testSingleCreation(Zend_CurrencyTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:430
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:85
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/CurrencyTest.php:63</p>

<p>1) testTripleCreation(Zend_CurrencyTest)
expected string &lt;â¬ 1,000.00&gt;
difference      &lt;     xxxxx&gt;
got string      &lt;â¬ 1.000,00&gt;
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/CurrencyTest.php:200</p>

<p>1) testFailedCreation(Zend_CurrencyTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:430
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:85
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/CurrencyTest.php:241</p>

<p>1) testGetRegionList(Zend_CurrencyTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:430
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:85
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/CurrencyTest.php:424</p>

<p>1) testGetCurrencyList(Zend_CurrencyTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale/Data.php:249
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Currency.php:381
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/CurrencyTest.php:435</p>

<p>1) testCreation(Zend_DateTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/DateTest.php:77</p>

<p>2) testCreationDefaultFormat(Zend_DateTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/DateTest.php:86</p>

<p>3) testCreationDefaultFormatConsistency(Zend_DateTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/DateTest.php:118</p>

<p>4) testCreationTimestamp(Zend_DateTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/DateTest.php:130</p>

<p>5) testCreationDatePart(Zend_DateTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/DateTest.php:139</p>

<p>6) testCreationDefaultLoose(Zend_DateTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/DateTest.php:172</p>

<p>7) testCreationNull(Zend_Date_DateObjectTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/Date/DateObjectTest.php:58</p>

<p>8) testCreationNegative(Zend_Date_DateObjectTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/Date/DateObjectTest.php:67</p>

<p>9) testCreationFailed(Zend_Date_DateObjectTest)
Zend_Locale_Exception: Autodetection of Locale has been failed!
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Locale.php:904
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:4444
/home/sebastian/Work/ZendFramework-1.0/library/Zend/Date.php:172
/home/sebastian/Work/ZendFramework-1.0/tests/Zend/Date/DateObjectTest.php:77</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-11T13:09:04.000+0000</p> 
        <div class="body">
            <p>Do you have the same problem with the trunk ?</p>

<p>It seems that you environment does not provide a detectable locale.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-11T13:32:06.000+0000</p> 
        <div class="body">
            <p>I included a skip for those tests if no locale can be detected... would be nice if you can test it  (SVN6810 or higher) and give me feedback.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-11-22T09:18:01.000+0000</p> 
        <div class="body">
            <p>Fixed as described  before.
Integrated with SVN 6833 into branch.</p>

        </div>
    </div>
    </div>

