<h2>ZF-246: SetControllerMethod in Zend_Controller_Front has a redundant check for setControllerDirectory</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-07-13T03:13:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Since there are checks if custom dispatcher object implements an interface in getDispatcher and setDispatcher methods, it would be reasonable to add setControllerDirectory to a dispatcher interface instead of the method_exists call in front controller:</p>

<pre class="highlight"><code>
public function setControllerDirectory($directory)
{
   $dispatcher = $this-&gt;getDispatcher();
   if (!method_exists($dispatcher, 'setControllerDirectory')) {
      throw new Zend_Controller_Front_Exception('Custom dispatcher does not support setting controller directory.');
   }
   $dispatcher-&gt;setControllerDirectory($directory);
   return $this;
}
</code></pre>

<p>This way it will be easier to create a custom dispatcher since you don't have to rely on runtime errors to discover it's whole interface.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Aleksey V. Zapparov (ixti) on 2006-11-08T06:41:34.000+0000</p> 
        <div class="body">
            <p>I totally agree with Michael. And more than that. IMHO there must be a
getControllerDirectory() method in interface. It is useful sometimes :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Aleksey V. Zapparov (ixti) on 2006-11-08T06:46:49.000+0000</p> 
        <div class="body">
            <p>Sorry, didn't noticed that ZF-436 is about getControllerDirectory()...
Anyway IMHO it has to be in Interface, so every, even manually written Dispatchers had this method... Or maybe I'm wrong....</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-08T16:07:53.000+0000</p> 
        <div class="body">
            <p>Implemented in revision 1504 of subversion.</p>

        </div>
    </div>
    </div>

