<h2>ZF-283: 'Illegal Token' on decoding arrays with a blank or linebreak before right bracket</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-07-24T14:19:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Decoding a JSON-string like the following works fine.
But if you put a blank or a linebreak before the right bracket you get an "Uncaught exception 'Zend_Json_Exception' with message 'Illegal Token'"
However, putting a tab before the right bracket seems to be ok.</p>

<p>$json = '{
  "data" : [
      1,
      2,
      3,
      4]
}';
$decoded = Zend_Json::decode($json);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-02T01:48:37.000+0000</p> 
        <div class="body">
            <p>Wrote new tests in 1434 to check the report; tests pass, so unable to confirm.</p>

        </div>
    </div>
    </div>

