<h2>ZF-2943: Fixing for Zend_OpenId_Consumer_Storage_File::getDiscoveryInfo()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2008-03-21T17:50:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-15T09:08:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dmitry Stogov (dmitry)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Before:</p>

<pre class="highlight"><code>
$f = @fopen($name, 'r');
if ($f === false) {
        fclose($lock);
        return false;
}
$ret = false;
$data = stream_get_contents($f);
</code></pre>

<p>After:</p>

<pre class="highlight"><code>
if (file_exists($name) === false) {
        fclose($lock);
        return false;
}
$f = @fopen($name, 'r');
if ($f === false) {
        fclose($lock);
        return false;
}
$ret = false;
$data = stream_get_contents($f);
</code></pre>

<p>Added</p>

<pre class="highlight"><code>
if (file_exists($name) === false) {
        fclose($lock);
        return false;
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dmitry Stogov (dmitry) on 2008-03-24T03:33:47.000+0000</p> 
        <div class="body">
            <p>Why do we need this additional file_exists() check?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dmitry Stogov (dmitry) on 2008-06-17T00:09:53.000+0000</p> 
        <div class="body">
            <p>I'm going to close this bug with "Won't fix" resolution, as I don't understand what does this patch fix.
Any explanation?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dmitry Stogov (dmitry) on 2008-07-15T09:08:10.000+0000</p> 
        <div class="body">
            <p>nobody care</p>

        </div>
    </div>
    </div>

