<h2>ZF-2637: testDefaultFilterPath(Zend_ViewTest) fails</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-13T02:19:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-31T16:10:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Issue is split from ZF-2489</p>

<p>At revision 7971.</p>

<p>jmut@<a>dexter:/storage/www/frameworks/zendframework/tests</a>$ phpunit Zend_ViewTest Zend/ViewTest.php</p>

<p>There was 1 failure:</p>

<p>1) testDefaultFilterPath(Zend_ViewTest)
Failed asserting that  is true.
/storage/www/frameworks/zendframework/tests/Zend/ViewTest.php:142
/storage/www/frameworks/zendframework/tests/Zend/ViewTest.php:86</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-14T09:03:46.000+0000</p> 
        <div class="body">
            <p>Resolved in current trunk and applied to 1.0 branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-31T16:10:03.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
    </div>

