<h2>ZF-2583: Include TestHelper in any independent test suite and test class</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2008-02-06T10:32:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-20T08:48:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10837">ZF-10837</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>TestHelper should be require_once'd in any test suite that may be run independently.</p>

<p>Otherwise, Zend library will not be available in current include_path and you'll not be able to run a class specific unit test.</p>

<p>Let me show you a few examples:</p>

<p>// the following statement works fine
phpunit --verbose Zend_Service_Yahoo_AllTests</p>

<p>// the following statements fail
//  Failed opening required 'Zend/*' ...
phpunit --verbose Zend_Service_Yahoo_OfflineTest
phpunit --verbose Zend_OpenId_ConsumerTest</p>

<p>// the following statement fails for the same reason as above
phpunit --verbose Zend_OpenId_AllTests</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T13:59:56.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-20T08:48:28.000+0000</p> 
        <div class="body">
            <p>Fixed with the issue ZF-10837.</p>

        </div>
    </div>
    </div>

