<h2>ZF-2659: It should be noted that you must call close() before reference has gone.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task: Docs</dd>

    <dt>Created:</dt>
    <dd>2008-02-14T22:43:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T15:46:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                twk (twk)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Adapter_Mysqli</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The information of ZF-2558 should be noted on the following.
<a href="http://framework.zend.com/manual/en/zend.db.html#zend.db.adapter.adapter-notes">http://framework.zend.com/manual/en/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:43:57.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T14:05:48.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T13:17:29.000+0000</p> 
        <div class="body">
            <p>Reassigning to Ralph since he's the new maintainer of Zend_Db</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-08T06:41:42.000+0000</p> 
        <div class="body">
            <p>I think the description  duplicates the same of ZF-2558.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-09T00:06:54.000+0000</p> 
        <div class="body">
            <p>Document work on 
<a href="http://framework.zend.com/manual/en/zend.db.html#zend.db.adapter.adapter-notes">http://framework.zend.com/manual/en/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-09T00:14:40.000+0000</p> 
        <div class="body">
            <p>change the summary and description more understandably 
And auto reassign.</p>

<p>Thank twk-san to mail me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-15T19:03:38.000+0000</p> 
        <div class="body">
            <p>Please contact with ZF-2558
I think it is not adapter problem.<br />
It would be general attention of the exception handling about RDMS</p>

        </div>
    </div>
    </div>

