<h2>ZF-2897: Zend_Filter $namespaces search order</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-03-17T07:25:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-17T12:58:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                James Dempster (letssurf)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When providing Zend_Filter with a classBasename with the same name as a Zend_Filter class but different namespaces Zend_Filter becomes a higher priority in the include list.</p>

<p>e.g.
Zend_Filter::get('123asd', 'Int', null, array('MyWeb_Filter'));</p>

<p>This would include the Zend_Filter_Int before it would include MyWeb_Filter_Int I think this should be changed to make the users filter be included first.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by James Dempster (letssurf) on 2008-03-17T07:47:23.000+0000</p> 
        <div class="body">
            <p>Included in the Zend_Validate bug report</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T12:58:14.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Closing and assigning all resolved issues to the people who resolved them. The only unassigned issues should be those that are new and unreviewed.</p>

        </div>
    </div>
    </div>

