<h2>ZF-2589: __construct demands endpoint, no options to recycle object</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-02-06T15:31:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-22T09:21:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Lars Strojny (lars)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_XmlRpc_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be nice if I could create a {{Zend_XmlRpc_Client}} without passing a URL to the {{__construct}}.</p>

<p>Reason - I like to re-use my objects and didn't want to set up another client for every request I am doing (and I have 5 or so to different endpoints). So ideally I'd like to create a {{Zend_XmlRpc_Client}} without an endpoint and I would like to set another endpoint when I need.</p>

<p>For example:</p>

<pre class="highlight"><code>
$client = new Zend_XmlRpc_Client();
...
$client-&gt;setEndpoint('<a href="http://foo/bar/">http://foo/bar/</a>');
...
$client-&gt;setEndpoint('<a href="http://bar/foo">http://bar/foo</a>');
...
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-06T10:15:59.000+0000</p> 
        <div class="body">
            <p>Scheduling for first mini-release following 1.5.0GA release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-21T16:40:24.000+0000</p> 
        <div class="body">
            <p>Re-scheduling; bigger change than originally assumed, and could introduce BC issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-04-22T11:09:37.000+0000</p> 
        <div class="body">
            <p>Scheduling for next minor release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Till Klampaeckel (till) on 2008-07-21T22:55:20.000+0000</p> 
        <div class="body">
            <p>Any headsup?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2009-08-22T08:06:59.000+0000</p> 
        <div class="body">
            <p>Till, I would like not to provide this option. It's not expensive to create a new client object and it makes it much harder - or impossible - to verify invariance of the client object. 
I can only guess your usecase, but if you need to access different XML/RPC endpoints through one object I would suggest to create something like Till_XmlRpc_Composite which takes a map with namespaces as keys and XML/RPC client objects as values and dispatch the calls accordingly. Does that sound like a solution for you?</p>

        </div>
    </div>
    </div>

