<h2>ZF-2443: ViewRenderer's setViewBasePathSpec() does not recognize the placeholders :module, :controller or :action</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-01-17T07:55:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When changing the default script path using Zend_Controller_Action_Helper_ViewRenderer::setViewBasePathSpec(), the placeholders <em>:module</em>, <em>:controller</em> and <em>:action</em> are not recognized by the inflector.</p>

<p><em>Code:</em></p>

<pre class="literal">
$vr = $this-&gt;_helper-&gt;viewRenderer;
$vr-&gt;setView($this-&gt;view)
     -&gt;setViewBasePathSpec(':moduleDir/:module')
     -&gt;initView();
</pre>

<p><em>Exception thrown:</em>
Fatal error:  Uncaught exception 'Zend_Filter_Exception' with message 'A replacement identifier : was found inside the inflected target, perhaps a rule was not satisfied with a target source?  Unsatisfied inflected target: /data/W/mvc.vilagenet.com.br/application/modules/:module' in /data/W/mvc.vilagenet.com.br/library/Zend/Filter/Inflector.php:454
Stack trace:</p>

<h1>0 /data/W/mvc.vilagenet.com.br/library/Zend/Controller/Action/Helper/ViewRenderer.php(363): Zend_Filter_Inflector-&gt;filter(Array)</h1>

<h1>1 /data/W/mvc.vilagenet.com.br/library/Zend/Controller/Action/Helper/ViewRenderer.php(438): Zend_Controller_Action_Helper_ViewRenderer-&gt;_getBasePath()</h1>

<h1>2 /data/W/mvc.vilagenet.com.br/library/Vilage/Controller/Action.php(30): Zend_Controller_Action_Helper_ViewRenderer-&gt;initView()</h1>

<h1>3 /data/W/mvc.vilagenet.com.br/library/Zend/Controller/Action.php(129): Vilage_Controller_Action-&gt;init()</h1>

<h1>4 /data/W/mvc.vilagenet.com.br/library/Zend/Controller/Dispatcher/Standard.php(218): Zend_Controller_Action-&gt;__construct(Object(Zend_Controller_Request_Http in /data/W/mvc.vilagenet.com.br/library/Zend/Filter/Inflector.php on line 454</h1>

<p>I´m using the snapshot ZendFramework-20080117-7469.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Carlton Gibson (carlton) on 2008-01-19T07:44:10.000+0000</p> 
        <div class="body">
            <p>I looked into this briefly. This is not a solution but a possible line of enquiry:</p>

<blockquote>
  <p>From r7089, in ViewRenderer::_getBasePath() an empty array is passed to the inflector's filter method:</p>
</blockquote>

<p>[Lines 360 -363 : ViewRenderer::_getBasePath()]
$inflector = $this-&gt;getInflector();
$this-&gt;_setInflectorTarget($this-&gt;getViewBasePathSpec());
$path = $inflector-&gt;filter(array());
return $path;</p>

<p>Should it not pass $this-&gt;_inflectorTarget instead?</p>

<p>From Zend/Filter/Inflector.php:</p>

<p>Inflector::filter() begins with a foreach on the passed array, which isn't going to get very far if that is empty...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-04T15:31:00.000+0000</p> 
        <div class="body">
            <p>Assigning to Ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-14T11:22:34.000+0000</p> 
        <div class="body">
            <p>Upgrading status to must have for 1.5</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-02-19T15:20:34.000+0000</p> 
        <div class="body">
            <p>Please check revision 8177 for a fix.</p>

<p>-ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-02-20T08:56:25.000+0000</p> 
        <div class="body">
            <p>If there are any issues here, please reopen.</p>

<p>-ralph</p>

        </div>
    </div>
    </div>

