<h2>ZF-2855: Add definition data type to classes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-03-11T00:32:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-04T08:41:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2970">ZF-2970</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11176/soap.patch">soap.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently when there is a class defined as a parameter or return method, the type of data set for the wsdl is xsd:anyType.</p>

<p>Example:</p>

<pre class="highlight"><code>

class Parameter {
    
    /**
     * @var string
     */
    public $var1;
}

/**
 * Test Class
 */
class Zend_Soap_AutoDiscover_Test {
    /**
     * Test Function 2
     *
     * @param string $who Some Arg
     * @param Parameter $param
     */
    function testFunc2($who, Parameter $param)
    {
        return "Hello $who";
    }
}


$server = new Zend_Soap_AutoDiscover();
$server-&gt;setClass('Zend_Soap_AutoDiscover_Test');
$server-&gt;handle(true);
</code></pre>

<p>Wsdl generated to message testFunc2:</p>

<pre class="highlight"><code>
</code></pre>

<p>Expected:</p>

<pre class="highlight"><code>

</code></pre>

<p>This way is possible to make the SoapServer validate the envelopes sent in a call soap.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:22:57.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-06-04T08:41:50.000+0000</p> 
        <div class="body">
            <p>Resolved using offered patch with some minor improvements.</p>

        </div>
    </div>
    </div>

