<h2>ZF-2820: Zend_Controller_Router_Route_Regex missing protected $_map</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-03-07T02:46:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T18:53:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.1 (25/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the constructor $this-&gt;_map = (array)$map; is used, but $_map is never declared, so by default it's added as a public property to the class.</p>

<p>It works, but it should be declared protected because it's never accessed from the outside anyway.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-20T15:55:48.000+0000</p> 
        <div class="body">
            <p>Fixed for next minor release with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=8933">SVN r8933</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-20T15:59:19.000+0000</p> 
        <div class="body">
            <p>Fixed for next mini-release with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=8935">SVN r8935</a>.</p>

        </div>
    </div>
    </div>

