<h2>ZF-2033: testDbFactoryAlternateNamespace(Zend_Db_Adapter_StaticTest) failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-10-03T04:17:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-19T02:36:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2669">ZF-2669</a></li>
            <li><a href="/issues/browse/ZF-2159">ZF-2159</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1.0-Branch, revision 6577:</p>

<p>2) testDbFactoryAlternateNamespace(Zend_Db_Adapter_StaticTest)
Caught exception of type Zend_Exception where none was expected: File "Static.php" was not found</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-02-12T19:35:06.000+0000</p> 
        <div class="body">
            <p>That would be good to have it fixed for 1.0.4 release</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-06T10:18:37.000+0000</p> 
        <div class="body">
            <p>Resolving as cannot reproduce (with latest trunk SVN). Please feel free to reopen if the issue is found to still exist with latest trunk version.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:32.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-19T02:36:19.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Assigning closed and resolved issues to those who resolved them. The only unassigned issues should be new and unreviewed.</p>

        </div>
    </div>
    </div>

