<h2>ZF-2787: Zend_Controller_Action_Helper_FlashMessengerTest error and failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-03-03T13:53:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-04T15:45:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Errors:</p>

<pre class="literal">
1) testLoadFlashMessenger(Zend_Controller_Action_Helper_FlashMessengerTest)
Undefined variable: request
c:\Documents and Settings\dfelton\My Documents\SVN Remote\Zend Framework\trunk\tests\Zend\Controller\Action\Helper\Flash
MessengerTest.php:96
</pre>

<p>Failures:</p>

<pre class="literal">
1) testClearMessages(Zend_Controller_Action_Helper_FlashMessengerTest)
Failed asserting that  is true.
c:\Documents and Settings\dfelton\My Documents\SVN Remote\Zend Framework\trunk\tests\Zend\Controller\Action\Helper\Flash
MessengerTest.php:104

2) testDirectProxiesToAddMessage(Zend_Controller_Action_Helper_FlashMessengerTest)
Failed asserting that  is true.
c:\Documents and Settings\dfelton\My Documents\SVN Remote\Zend Framework\trunk\tests\Zend\Controller\Action\Helper\Flash
MessengerTest.php:115
</pre>

<p>Results from WinXP, PHP 5.1.4 and 5.2.5 (r8521 of trunk).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-03-04T15:18:39.000+0000</p> 
        <div class="body">
            <p>Skipping tests.  Resolved in r8545.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-03-04T15:45:32.000+0000</p> 
        <div class="body">
            <p>Confirmed as fixed</p>

        </div>
    </div>
    </div>

