<h2>ZF-2507: Zend_Db_Statement_Mysqli PHPDoc points to non-used exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2008-01-26T19:37:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T21:03:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Db_Statement_Mysqli::_bindParam() - line 98 (the PhpDoc block)</p>

<p>@throws Zend_Db_Statement_Db2_Exception</p>

<p>is wrong, considering this function is just a stub, and that it would (hopefully) not be throwing Db2 exceptions if it was a real function.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-02-07T16:26:07.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN-7856</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T21:03:29.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

