<h2>ZF-2617: Promote Zend_Service_Nirvanix to core.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-02-11T18:06:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This task tracks work required for promoting Zend_Service_Nirvanix to core. It should be closed only when Zend_Service_Nirvanix is on trunk with appropriate unit test coverage.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-05T13:08:19.000+0000</p> 
        <div class="body">
            <p>Promoted to core; need to know if I should push into release-1.5 branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-03-07T15:36:26.000+0000</p> 
        <div class="body">
            <p>I think we can close this issue.</p>

<p>The new service should be promoted to branch as stated in the RC2 text from wil on 3.March.
Additionally a new component should be added to jira for issues related to Nirvanix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-07T15:48:15.000+0000</p> 
        <div class="body">
            <p>Promoted to release branch earlier this week per approval from Wil.</p>

        </div>
    </div>
    </div>

