<h2>ZF-2821: Zend_Controller_Action_Helper_Redirector makes redirection using relative HTTP path</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-03-07T04:07:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T15:30:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2822">ZF-2822</a></li>
            <li><a href="/issues/browse/ZF-3361">ZF-3361</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Redirector helper makes relative redirect by default, despite the fact the HTTP specs forbid relative URLs in HTTP redirects. Redirects should be always to ubsolute URLs.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:41:12.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-04-22T10:17:42.000+0000</p> 
        <div class="body">
            <p>Scheduling for next minor release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2008-06-04T04:03:25.000+0000</p> 
        <div class="body">
            <p>I can give a shot at it if you like, Matthew.</p>

<p>I have moved url view helper logic to router, so setGotoRoute should also be changed at the same time.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-24T13:10:30.000+0000</p> 
        <div class="body">
            <p>The problem with fixing this issue is due to determining the server protocol, name, and port. The information in the $_SERVER superglobal is somewhat unreliable due to the fact that some keys vary from server to server, others are open to header injection, and others may be incorrect due to proxying. Additionally, if you are pregenerating content, having the various URL helpers set the fully qualified URL could have a negative impact as the incorrect protocol, server, and/or port could be selected during generation.</p>

<p>At best, this would have to be an opt-in behavior.</p>

<p>While I realize that the HTTP spec requires fully qualified URLs, I do not know of any clients that are unable to follow them; can the reporter please provide some background on a real-world technical need for this request?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-24T13:11:15.000+0000</p> 
        <div class="body">
            <p>Updated priorities; unsure how necessary this "fix" is.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-29T15:30:41.000+0000</p> 
        <div class="body">
            <p>No response from original author for 3+ years</p>

        </div>
    </div>
    </div>

