<h2>ZF-2593: When using file backend for cache, the files will never be locked.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-06T17:36:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Moshe (moshe)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Revision: 7826
Class: Zend_Cache_Backend_File
Methods: _fileGetContents, _filePutContents
Lines: 660, 668, 681, 683</p>

<p>In both methods flock() function is given parameters $f and $fp (??) that are nowhere declared, my guess they should be $file.</p>

<p>error-suppresion operator @ is successfully used to hide this error.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-02-07T12:43:08.000+0000</p> 
        <div class="body">
            <p>stupid error when refactoring the file backend, many thanks for the report, fixed in SVN trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Moshe (moshe) on 2008-02-07T13:38:03.000+0000</p> 
        <div class="body">
            <p>Here's what i get now:</p>

<p>Debug Warning: \home...\lib\Zend\Cache\Backend\File.php line 660 - flock() expects parameter 1 to be resource, string given
Debug Warning: \home...\lib\Zend\Cache\Backend\File.php line 668 - flock() expects parameter 1 to be resource, string given
Debug Warning: \home...\lib\Zend\Cache\Backend\File.php line 681 - flock() expects parameter 1 to be resource, string given
Debug Warning: \home...\lib\Zend\Cache\Backend\File.php line 683 - flock() expects parameter 1 to be resource, string given</p>

<p>I guess you'll have to fopen it</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Moshe (moshe) on 2008-02-07T14:47:13.000+0000</p> 
        <div class="body">
            <p>Also, maybe when testing, remove @ to see errors :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-02-10T08:11:31.000+0000</p> 
        <div class="body">
            <p>oooops...</p>

<p>thanks, I hope it's fixed in SVN trunk now</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Moshe (moshe) on 2008-02-14T16:44:32.000+0000</p> 
        <div class="body">
            <p>Somehow cache file with size 0 was created, and when it was attempted to be read by _fileGetContents it gave an error in $result = fread($f, $fsize); - apparently fread can't have $fsize==0</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-02-15T10:22:16.000+0000</p> 
        <div class="body">
            <p>fixed in SVN trunk, thanks Moshe</p>

        </div>
    </div>
    </div>

