<h2>ZF-2946: Zend_Http_Client_Adapter_Socket be able to set stream context options</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-03-22T17:09:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-31T20:24:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4838">ZF-4838</a></li>
            <li><a href="/issues/browse/ZF-5524">ZF-5524</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On a shared host making an out going connection I need to bind to a certain ip address. This is only possible though steam context handlers. Zend_Http_Client_Adapter_Socket already uses stream_context_create. I propose the ability to be able to pass stream context options via the config.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:26:42.000+0000</p> 
        <div class="body">
            <p>Changing fix version to follow IT conventions.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-25T20:27:28.000+0000</p> 
        <div class="body">
            <p>Please categorize/fix as needed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2009-07-23T14:43:21.000+0000</p> 
        <div class="body">
            <p>Implemented, documented and tested in CS-17009</p>

        </div>
    </div>
    </div>

