<h2>ZF-2256: Possibility to give a string as the source files in the array adapter Zend_Translate_Adapter_Array</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-12-03T10:38:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Laurent Melmoux (laurent melmoux)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It can easily implement by adding 3 lines of code in  Zend_Translate_Adapter_Array::_loadTranslationData()</p>

<pre class="highlight"><code>

if(!is_array($data)){
    $data = include($data); 
}
</code></pre>

<p>Then the array file should look like :</p>

<pre class="highlight"><code>
&lt;?php
return array(
    'user_id'  =&gt; 'Id',
    'username' =&gt; 'Non utilisateur',
    'password' =&gt; 'Mot de passe',
    'email'    =&gt; 'Email',
    'firstname'=&gt; 'Prénom',
    'lastname' =&gt; 'Nom',
    'created'  =&gt; 'Crée le',
    'modified' =&gt; 'Modifié le'
);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-12-03T13:07:18.000+0000</p> 
        <div class="body">
            <p>Why should an Array Adapter accept Strings ?</p>

<p>As per definition of the class name the usage is for "Arrays"...
You can simply extend any existing adapter or write your own.</p>

<p>But I don't think that a "string" Adapter is usefull, because you could simply do</p>

<pre class="highlight"><code>
$t-&gt;addTranslation(array($key =&gt; $value));
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laurent Melmoux (laurent melmoux) on 2007-12-03T13:56:56.000+0000</p> 
        <div class="body">
            <p>Well, if you can do both its even better don't you think? :)
There are a lot of classes in the frameworks were the argument is an object or a string, and in the later it will use a factory to get the object. So it could be done with array too.</p>

<p>But best, if you can provide a string the array adapter will work with the automatic source detection. My $0.2</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-12-06T07:49:41.000+0000</p> 
        <div class="body">
            <p>It's not just that 3 lines.
We have also to handle output and failures from the file.</p>

<p>Anyway, it has been integrated with SVN-7050.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laurent Melmoux (laurent melmoux) on 2007-12-06T08:09:49.000+0000</p> 
        <div class="body">
            <p>Thanks Thomas ! :)</p>

<p>{quote}
It's not just that 3 lines
We have also to handle output and failures from the file.
{quote}</p>

<p>That's right.</p>

<p>I think there is a more appropriated test</p>

<pre class="highlight"><code>
if(is_string($data)) 
</code></pre>

<p>Instead of the one I first suggested</p>

<pre class="highlight"><code>
if(!is_array($data))
</code></pre>

        </div>
    </div>
    </div>

