<h2>ZF-2342: setPathDelimiter() should accept arrays of string as per the phpdoc description</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-12-20T14:23:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-26T12:56:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.4 (26/Feb/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The setPathDelimiter() in ZendFramework-1.0.3\library\Zend\Controller\Dispatcher\Abstract.php should accept an array but currently this is not allowed. 
Need to allow arrays to be passed in as per the comments.</p>

<pre><code>/**
 * Set path delimiter
 *
 * Set the path delimiter to use in controllers. May be a single string or
 * an array of strings.
 *
 * @param string|array $spec
 * @return Zend_Controller_Dispatcher_Abstract
 */
public function setPathDelimiter($spec)
{
    if (!is_string($spec)) {
        require_once 'Zend/Controller/Dispatcher/Exception.php';
        throw new Zend_Controller_Dispatcher_Exception('Invalid path delimiter');
    }
    $this-&gt;_pathDelimiter = $spec;

    return $this;
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-14T11:57:02.000+0000</p> 
        <div class="body">
            <p>For now, we'll simply modify the phpdoc to reflect actual functionality.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-18T15:18:07.000+0000</p> 
        <div class="body">
            <p>docblock updated in trunk and release-1.0 branch.</p>

        </div>
    </div>
    </div>

