<h2>ZF-2329: Zend_Cache should remember HTTP headers (Content-Type) when using Zend_Cache_Frontend_Page</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-12-19T12:47:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-17T14:02:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Daniel Skinner (skina)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Example: An XML document is output with the Content-Type header set to text/xml. Zend_Cache_Frontend_Page is used and when retrieving a cached copy, the Content-Type header is incorrectly set to text/html.</p>

<p>See <a href="http://xeaura.xeaura-host.co.uk/sitemap.xml">http://xeaura.xeaura-host.co.uk/sitemap.xml</a> for an example. The cache time is about 15 seconds. Initiall you will see the document with the correct content-type (and correctly formatted in Firefox), refreshing will give you the cached copy (wrong content-type and not formatted in Firefox).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2007-12-19T13:46:25.000+0000</p> 
        <div class="body">
            <p>Zend_Cache doesn't send Content-Type header.</p>

<p>Something like this should work, no ?</p>

<pre class="literal"> 

require 'Zend/Cache.php')
[...] we make $cache object

header("Content-Type...");

$cache-&gt;start()

require_once 'Model.php'
[...]

[...] your work to make the XML file
echo($xmlString);

</pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Skinner (skina) on 2007-12-19T14:08:46.000+0000</p> 
        <div class="body">
            <p>It's a possible solution but that wouldn't work in my case or most common cases when using Zend_Controller.</p>

<p>In my case the module/controller/action route will determine the Content-Type header which will be set on the Response object. Since Zend_Cache is setup in the bootstrap, it does not go through the entire route sequence to determine what the Content-Type should be.</p>

<p>As it stands your solution would work for a lot of cases when using Zend_Cache/Zend_Cache_Frontend_Page in a simple application. However, when using Zend_Cache/Zend_Cache_Frontend_Page with Zend_Controller you are essentially limited to produce text/html responses.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-01-30T17:24:41.000+0000</p> 
        <div class="body">
            <p>I just commited a change for this into the SVN trunk</p>

<p>please try it (you will have to set the backend option content_type_memorization = true) and reopen this task if problem</p>

<p>regards</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Skinner (skina) on 2008-01-31T05:23:09.000+0000</p> 
        <div class="body">
            <p>The new Zend_Cache_Frontend_Page class definately works in my case. The Content-Type header is correctly remembered and sent along with the cached output.</p>

<p>The content_type_memorization is a frontend option, not a backend one.</p>

<p>Thanks for this fix!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Geoff Speicher (gspeicher) on 2008-05-12T11:48:24.000+0000</p> 
        <div class="body">
            <p>Problem is not limited to Content-type header; other important headers (Expires, for example) are also lost.  Is there any good reason not to remember and re-use <em>all</em> response headers for cached pages?  The patch is even simpler than the patch to add content_type_memorization.  Just save the entire headers_list() array in the cache and spit them all back.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T13:49:32.000+0000</p> 
        <div class="body">
            <p>Can I close this bug? Have all issues been resolved? It's not entirely clear from the comments.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Geoff Speicher (gspeicher) on 2008-12-17T13:55:52.000+0000</p> 
        <div class="body">
            <p>fine by me</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-12-17T14:02:58.000+0000</p> 
        <div class="body">
            <p>Yes Wil, you can close it</p>

        </div>
    </div>
    </div>

