<h2>ZF-2601: Zend_Cache_Backend_File - invalid resources and undefined variables (ZF 1.0.5PR)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-08T02:49:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-12T11:58:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bruno VIBERT (flyingbono)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Cache_Backend_File triggers warnings and notice in methods _fileGetContents and _filePutContents.</p>

<p>{panel:title=Warning|borderStyle=dashed| borderColor=#ccc| titleBGColor=red}
{{flock() expects parameter 1 to be resource, null given, Zend/Cache/Backend/File.php, 660}}
{{flock() expects parameter 1 to be resource, null given, Zend/Cache/Backend/File.php, 668}}
{{flock() expects parameter 1 to be resource, null given, Zend/Cache/Backend/File.php, 681}}
{{flock() expects parameter 1 to be resource, null given, Zend/Cache/Backend/File.php, 683}}
{panel}</p>

<p>{panel:title=Notice|borderStyle=dashed| borderColor=#ccc| titleBGColor=orange}
{{Zend/Cache/Backend/File.php, line 660 : Undefined variable: f}}
{{Zend/Cache/Backend/File.php, line 668 : Undefined variable: fp}}
{panel}</p>

<p><em>NOTE</em>
However, cache is correctly saved / loaded</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Toni Wenzel (twenzel) on 2008-02-12T00:57:20.000+0000</p> 
        <div class="body">
            <p>I get this warnings and noticses too. This issue should be fixed for final release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-02-12T11:58:15.000+0000</p> 
        <div class="body">
            <p>fixed in SVN trunk</p>

        </div>
    </div>
    </div>

