<h2>ZF-2587: Issues with calculate dates</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-06T12:00:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-07T03:29:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When i try to calculate dates with the Zend_Date-&gt;set() method, i get wrong values.</p>

<pre class="highlight"><code>
date_default_timezone_set('UTC');

$date = new Zend_Date(mktime(1, 1, 1, 1, 22, 2008));
$date-&gt;set(
    array(
        'day' =&gt; $date-&gt;get(Zend_Date::DAY),
        'month' =&gt; $date-&gt;get(Zend_Date::MONTH),
        'year' =&gt; $date-&gt;get(Zend_Date::YEAR),
        'hour' =&gt; 23,
        'minute' =&gt; 59,
        'second' =&gt; 59
    )
);

$date-&gt;add(6, Zend_Date::MONTH);
$date-&gt;setTimezone('Europe/Berlin');
echo $date-&gt;get(Zend_Date::DATE_MEDIUM) . ' ' . $date-&gt;get(Zend_Date::TIME_MEDIUM);  
</code></pre>

<p>Example 1 works good. The result is 23.07.2008 01:59:59.</p>

<pre class="highlight"><code>
date_default_timezone_set('UTC');

$date = new Zend_Date(mktime(1, 1, 1, 1, 22, 2008));
$date-&gt;setTimezone('Europe/Berlin');
$date-&gt;set(
    array(
        'day' =&gt; $date-&gt;get(Zend_Date::DAY),
        'month' =&gt; $date-&gt;get(Zend_Date::MONTH),
        'year' =&gt; $date-&gt;get(Zend_Date::YEAR),
        'hour' =&gt; 23,
        'minute' =&gt; 59,
        'second' =&gt; 59
    )
);

$date-&gt;add(6, Zend_Date::MONTH);
echo $date-&gt;get(Zend_Date::DATE_MEDIUM) . ' ' . $date-&gt;get(Zend_Date::TIME_MEDIUM);  
</code></pre>

<p>Example 2: When i set the timezone first the result is 02.07.2008 00:59:59.</p>

<pre class="highlight"><code>
date_default_timezone_set('UTC');

$date = new Zend_Date(mktime(1, 1, 1, 1, 22, 2008));
$date-&gt;set(
    array(
        'day' =&gt; $date-&gt;get(Zend_Date::DAY),
        'month' =&gt; $date-&gt;get(Zend_Date::MONTH),
        'year' =&gt; $date-&gt;get(Zend_Date::YEAR),
        'hour' =&gt; 23,
        'minute' =&gt; 59,
        'second' =&gt; 59
    )
);
$date-&gt;setTimezone('Europe/Berlin');
$date-&gt;add(6, Zend_Date::MONTH);
echo $date-&gt;get(Zend_Date::DATE_MEDIUM) . ' ' . $date-&gt;get(Zend_Date::TIME_MEDIUM);  
</code></pre>

<p>Example 3: When i set the timezone before i add the 6 months the result is 01.07.2008 01:59:59.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-02-06T14:39:34.000+0000</p> 
        <div class="body">
            <p>In your case you should set the option "extended_month" to true.
This option handles how months are calculated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-02-06T14:43:15.000+0000</p> 
        <div class="body">
            <p>Sorry, there was an typo.... this is an working example... it has to be set before working with date (set/add/sub)</p>

<pre class="highlight"><code>
Zend_Date::setOptions(array('extend_month' =&gt; true));
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Kaps (akkie) on 2008-02-07T02:52:36.000+0000</p> 
        <div class="body">
            <p>Hello Thomas</p>

<p>The code works almost. Example 1 and Example 3 are correct. Example 2 is one hour in the past. Is there anything to note?</p>

<p>I have found an other issue with the add method.</p>

<pre class="highlight"><code>
date_default_timezone_set('UTC');

$date = new Zend_Date();
$date-&gt;set(30, Zend_Date::DAY);
$date-&gt;set(7, Zend_Date::MONTH);
$date-&gt;set(2008, Zend_Date::YEAR);
$date-&gt;set(0, Zend_Date::HOUR);
$date-&gt;set(0, Zend_Date::MINUTE);
$date-&gt;set(0, Zend_Date::SECOND);
echo $date-&gt;get(Zend_Date::DATE_MEDIUM) . ' ' . $date-&gt;get(Zend_Date::TIME_MEDIUM);
</code></pre>

<p>This example displays 01.07.2008 00:00:00. When is set 29 as day it works correct.</p>

<p>Best regards
Christian</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-02-07T03:19:25.000+0000</p> 
        <div class="body">
            <p>Your problem is that UTC does not have summer/wintertime...
So you set CET... and then you set a date... now summer/wintertime calculation is done, the resulting date has set +1...
And THEN you add 6 months... now we have +2 (summertime)... but the difference from +1 to +2 is only one hour and not 2 hours.</p>

<p>This is the difference you have seen.
Please note that date-calculation differs is you use timezones or UTC/GMT.</p>

<p>You second problem is also simple:
We have February...</p>

<p>You are setting the actual date with new Zend_Date()...
Then you try to set the 30.February... but there is no 30.February... by default Zend_Date corrects dates automatically so what you get is 1.March... 
Normally you would set values from greatest to smallest... so you have to do Year, Month, Day, Hour, Minute, Second... then you will have no problem, or you use array, or you give the date as string... there are several ways.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Kaps (akkie) on 2008-02-07T03:29:03.000+0000</p> 
        <div class="body">
            <p>Ok. This is blausible.</p>

<p>Thanks a lot!</p>

        </div>
    </div>
    </div>

