<h2>ZF-2206: Wrong phpDoc of Zend_Controller_Front::getRouter() method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2007-11-15T17:52:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-26T12:56:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.0.4 (26/Feb/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alan Gabriel Bem (alan.bem)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>    /**
     * Return the router object.
     *
     * Instantiates a Zend_Controller_Router_Rewrite object if no router currently set.
     *
     * @return null|Zend_Controller_Router_Interface
     */
    public function getRouter()
    {
        if (null == $this-&gt;_router) {
            require_once 'Zend/Controller/Router/Rewrite.php';
            $this-&gt;setRouter(new Zend_Controller_Router_Rewrite());
        }

        return $this-&gt;_router;
    }</code></pre>

<p>This method always return some Router object, so phpDoc @return should be corrected</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-11-16T12:34:39.000+0000</p> 
        <div class="body">
            <p>Scheduling for 1.0.3</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2008-01-11T07:33:27.000+0000</p> 
        <div class="body">
            <p>Corrected in revision 7387. Thanks.</p>

        </div>
    </div>
    </div>

