<h2>ZF-2600: isValid() function unexpected behavior</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-02-07T21:54:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-02-08T12:18:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                jaap vstr (jaapvstr)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form seems to validate unrequired elements when it should not.</p>

<p><em>Case in which this strange behavior occurs:</em></p>

<pre class="highlight"><code> 
$POSTDATA['name'] = 'x';
$POSTDATA['age'] = ''; //not required, but posted empty
Zend_Form-&gt;isValid($POSTDATA);
</code></pre>

<p><em>What happens:</em>
Zend_Form validates age, because the array key was set</p>

<p><em>Expected behavior:</em>
Zend_Form skips age, because the value was empty</p>

<p><em>Possible fixes:</em></p>

<h1>1 Add a strict option to the method (backwards compatible)</h1>

<pre class="highlight"><code>
public function isValid(array $data, $strict = true) {
        $valid = true;
        foreach ($this-&gt;getElements() as $key =&gt; $element) {
            if (!isset($data[$key])) {
                if ($element-&gt;getRequired()) {
                    $valid = $element-&gt;isValid(null, $data) &amp;&amp; $valid;
                }
            } else {
                //Changed
                if (($element-&gt;getRequired()) &amp;&amp; ($data[$key] != '') &amp;&amp; ($strict == false)) {
                    $valid = $element-&gt;isValid($data[$key], $data) &amp;&amp; $valid;
                } else {
                    $valid = $element-&gt;isValid($data[$key], $data) &amp;&amp; $valid;
                }
                //Change end
            }
        }
// etc.. etc..*/ 
}
</code></pre>

<h1>2 Just change the behavior</h1>

<pre class="highlight"><code>
public function isValid(array $data)
{
 $valid = true;
        foreach ($this-&gt;getElements() as $key =&gt; $element) {
            if (!isset($data[$key])) {
                if ($element-&gt;getRequired()) {
                    $valid = $element-&gt;isValid(null, $data) &amp;&amp; $valid;
                }
            } else {
               //Changed
                if (($element-&gt;getRequired()) &amp;&amp; ($data[$key] != '')) {
                    $valid = $element-&gt;isValid($data[$key], $data) &amp;&amp; $valid;
                } 
               //Change end
            }
        }
//etc.. etc..
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-08T06:46:49.000+0000</p> 
        <div class="body">
            <p>I'm assuming this behaviour was observed using the Preview Release, and not current trunk.</p>

<p>Earlier this week (week of 3 Feb 2008), I added the ability to allow non-required values to be empty, and made this the default behaviour. To override that behaviour (i.e., make a non-required value also require validation when present), you must call:</p>

<pre class="highlight"><code>
$element-&gt;setAllowEmpty(false);
</code></pre>

<p>Please verify what version of ZF you are using (preview release, snapshot (if so, which one), or current trunk).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by jaap vstr (jaapvstr) on 2008-02-08T07:01:44.000+0000</p> 
        <div class="body">
            <p>I first used the preview 1.5 release, then downloaded a snapshot to see if the problem was still there
ZendFramework-20080207-7833-en</p>

<p>It doesn't seem to be fixed in the latest snapshot either
ZendFramework-20080208-7862</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-08T07:39:05.000+0000</p> 
        <div class="body">
            <p>I cannot recreate the issue. I've got the following code:</p>

<pre class="highlight"><code>
$form = new Zend_Form();
$form-&gt;addElement('text', 'username')-&gt;getElement('username')
      // Note: the following line is unnecessary; elements are optional 
      // by default. Doing this simply to be explicit.
      -&gt;setRequired(false)  
      -&gt;addValidator('stringLength', false, array(1, 64));

$data = array('username' =&gt; '');

if (!$form-&gt;isValid($data)) {
    var_export($form-&gt;getMessages());
} else {
    echo "Form validated";
}
</code></pre>

<p>The expected result is:</p>

<pre class="highlight"><code>
Form validated
</code></pre>

<p>And that's what I receive. Are you certain you are using code from the latest trunk (i.e., that you are pointing your include_path at the new snapshot you downloaded)?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by jaap vstr (jaapvstr) on 2008-02-08T12:00:56.000+0000</p> 
        <div class="body">
            <p>Oh, you're right, i get the same when linking to the snapshot version.</p>

<p>I just looked for the fix, expecting it to be in the Zend_Form, but you fixed it in Zend_Form_Element.</p>

<p>Anyway, great job on writing Zend_Form. I was quite disappointed that 1.0 didn't came with it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-02-08T12:18:00.000+0000</p> 
        <div class="body">
            <p>Fixed in a revision earlier this week (week of 3 Feb 2008)</p>

        </div>
    </div>
    </div>

