<h2>ZF-2407: PHP Warning within Zend_Db_Statement</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-01-11T03:31:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Under windows there is an PHP Warning raised when initiating Zend_Db (trunk) under Windows (PHP5.2.3)...</p>

<pre class="highlight"><code>
PHP Warning:  preg_replace()  .... Compilation failed: missing terminating ] for character class at offset 7 in ....Statement.php on line 187
</code></pre>

<p>This line reads within Statement.php reads:</p>

<pre class="highlight"><code>
        $sql = preg_replace("/$q($qe|[^$q])*$q/", '', $sql);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-01-11T16:21:57.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN-7396</p>

        </div>
    </div>
    </div>

