<h2>ZF-2819: Allow ViewScript decorator to have access to content and to replace it</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-03-06T19:42:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Several people have requested the ability to have access to decorator content within the view script rendered by the ViewScript decorator, as well as the ability to replace the content provided to it. This can be accomplished by doing the following:</p>

<ul><li>add an additional variable to the view, 'content';</li>
<li>add the decorator itself as the 'decorator' view variable; </li>
<li>and allow a null value for the 'placement' option, which would allow you to replace the content instead of appending or prepending it.</li>
</ul><p>You would then be able to either:</p>

<ul><li>pass a null 'placement' option to the decorator at initialization</li>
<li>in your view script, call $this-&gt;decorator-&gt;setPlacement(null) </li>
</ul><p>in order to make the content of the view script replace it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-03-07T14:47:24.000+0000</p> 
        <div class="body">
            <p>Works as per the bullet points in the posted issue, with the exception that the value 'false' should be passed as the 'placement' decorator option when desiring to replace content.</p>

<p>Applied to trunk and 1.5 release branch.</p>

        </div>
    </div>
    </div>

