<h2>ZF-3356: Couldn't index data with Z_S_L</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-05-30T02:28:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-19T08:52:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rauan Maemirov (quessir)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I'm trying to store into index my data it returns the following errors:</p>

<p>1).<b>Notice</b>:  Undefined offset:  78573 in <b>...Zend/Search/Lucene/Index/SegmentInfo.php</b> on line <b>165</b><br /></p>

<p>public function getField($fieldNum) {
        return $this-&gt;_fields [$fieldNum];  // row number 165 of SegmentInfo.php
    }</p>

<p>2). <b>Notice</b>:  Trying to get property of non-object in <b>...Zend/Search/Lucene/Index/SegmentMerger.php</b> on line <b>72</b><br /></p>

<pre><code>private function _mergeStoredFields() {
    ....
    if (! ($bits &amp; 2)) {
        $storedFields [] = new Zend_Search_Lucene_Field ( $fieldInfo-&gt;name, $fdtFile-&gt;readString (), 'UTF-8', true, $fieldInfo-&gt;isIndexed, $bits &amp; 1 ); // row number 72 of SegmentMerger.php
    } else {
        $storedFields [] = new Zend_Search_Lucene_Field ( $fieldInfo-&gt;name, $fdtFile-&gt;readBinary (), '', true, $fieldInfo-&gt;isIndexed, $bits &amp; 1, true );
    }
    .....
    }
</code></pre>

<p>3). <b>Notice</b>:  Trying to get property of non-object in <b>...Zend/Search/Lucene/Index/SegmentWriter.php</b> on line <b>55</b><br /></p>

<pre><code>public function addStoredFields($storedFields) {
    .....
    foreach ( $storedFields as $field ) {
        $this-&gt;_fdtFile-&gt;writeVInt ( $this-&gt;_fields [$field-&gt;name]-&gt;number ); // row number 55 of SegmentWriter.php
    .....
    }
</code></pre>

<p>4). <b>Fatal error</b>:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1335492579 bytes</p>

<p>) in <b>...Zend/Search/Lucene/Storage/File/Filesystem.php</b> on line</p>

<p><b>50</b><br /></p>

<pre><code>protected function _fread($length = 1) {
    .....
    while ( $length &gt; 0 &amp;&amp; ($nextBlock = fread ( $this-&gt;_fileHandle, $length )) != false ) { //row number 50 of Filesystem.php
    .....
    }
</code></pre>

<p>I don't know how allowed memory size is exhausted... My index size is only 270Kb. I didn't notice such troubles on previous versions (1.5.1) of ZF. OS: Linux 2.6.18-53.el5 #1 SMP Mon Nov 12 02:14:55 EST 2007 x86_64 x86_64 x86_64 GNU/Linux (CentOS 5.1). php 5.2.6.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rauan Maemirov (quessir) on 2008-06-01T11:37:45.000+0000</p> 
        <div class="body">
            <p>Maybe this because of using APC?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-01T12:37:30.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rauan Maemirov (quessir) on 2008-06-04T02:41:33.000+0000</p> 
        <div class="body">
            <p>Hi, I noticed that indexing fails only for non-empty index.</p>

<p>For example if do this way</p>

<p>foreach($items as $item) {</p>

<pre><code> new $doc = ZFLD();...
 $index-&gt;addDoc($doc);...
</code></pre>

<p>}</p>

<p>$index-&gt;commit();
$index-&gt;optimize();</p>

<p>That's work great. Tried to index over 1 Mb.</p>

<p>But if i would add values to existing index and call commit and optimize(tried to switch it off) it fails.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fernando de (fernandolkf) on 2008-06-09T08:18:26.000+0000</p> 
        <div class="body">
            <p>i got exactly the same problem here
i'm still trying add all documments and then commit, but i got too much documments and some large ones, so maybe i got memory problems too</p>

<p>but this means that each new documment i get i would have to index all of them again?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-11-19T08:52:04.000+0000</p> 
        <div class="body">
            <p>Should be fixed in newer ZF versions</p>

        </div>
    </div>
    </div>

