<h2>ZF-3138: Nonces should be unique by Identity Provider.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-18T00:20:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dmitry Stogov (dmitry)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The isUniqueNonce function doesn't provide a way to pass in the IdP endpoint URL.</p>

<p>According to the spec, nonces shouldn't be unique overall, just by provider.  In a high traffic environment it's possible that legitimate nonce collisions could occur, though it will only happen occasionally.</p>

<p>The spec says (11.3):</p>

<p>'To prevent replay attacks, the agent checking the signature keeps track of the nonce values included in positive assertions and never accepts the same value more than once for the same OP Endpoint URL.'</p>

<p>The Zend_OpenId_Consumer_Storage interface needs to be altered to allow for unique nonces by endpoint provider, and the verify function in the consumer should start passing in the endpoint provider.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Paul Huff (phuff) on 2008-04-18T00:20:38.000+0000</p> 
        <div class="body">
            <p>We don't have a fix for this one, because I was afraid to alter the interface without checking in.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-04-21T13:47:46.000+0000</p> 
        <div class="body">
            <p>Marking as fixed for next minor release pending merge of changes to release-1.5 branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:29.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

