<h2>ZF-3710: Wrong class name in @return clause of Zend_Db_Adapter_Pdo_Abstract::query()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-21T23:32:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-28T02:14:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.2 (13/Oct/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Martin Mayer (martin.mayer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>@return clause of docblock for {{Zend_Db_Adapter_Pdo_Abstract::query()}} should contain {{Zend_Db_Statement_Pdo}} instead of {{Zend_Db_Pdo_Statement}}. Class {{Zend_Db_Pdo_Statement}} doesn't exist.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-09-01T03:17:59.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r11186</p>

        </div>
    </div>
    </div>

