<h2>ZF-3109: Zend/Locale/Data.php (Line 974) should check that the array index exists</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-14T15:22:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-04-14T15:37:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Anders Petersen (anpeters)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Line 974 in Zend/Locale/Data.php should check that the array index exists before comparing to avoid causing "Undefined index" notices. I only noticed this because I used Zend Locale as a standalone module, and use my own error handler (which shows notices).</p>

<p>Example fix: Change from "if ($val[$key] != $value) {" to "if (isset($val[$key]) &amp;&amp; $val[$key] != $value) {".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Anders Petersen (anpeters) on 2008-04-14T15:29:04.000+0000</p> 
        <div class="body">
            <p>Sorry for the duplicate (ZF-3110), but there is a bug in the bugreporter... After submitting (or editing) the bug, a 404 error is encountered:
"HTTP Status 404 - No view for result [error] exists for action [ViewIssue]"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-04-14T15:37:32.000+0000</p> 
        <div class="body">
            <p>see ZF-3110</p>

        </div>
    </div>
    </div>

