<h2>ZF-3068: Zend_Auth_Adapter_DbTable does not honor the case folder of the underlying database</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-08T07:23:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-10T11:50:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mike Coakley (mcoakley)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>(Note: I only picked Zend_Auth because Zend_Auth_Adapter_DbTable is not available.)</p>

<p>When using the Zend_Auth_Adapter_DbTable to authenticate against a database in which I was using Zend_Db::CASE_FOLDING =&gt; Zend_Db::CASE_UPPER I found that the authentication would fail stating that the "zend_auth_credential_match" was an invalid index. In order to fix the issue I had to modify three lines in the source to using the DB method to use the requested case folding.</p>

<p>In Zend_Auth_Adapter_DbTable.php</p>

<p>Here is my new modified version of _authenticateValidateResult:</p>

<pre class="highlight"><code>
    protected function _authenticateValidateResult($resultIdentity)
    {
        if ($resultIdentity[$this-&gt;_zendDb-&gt;foldCase('zend_auth_credential_match')] != '1') {
            $this-&gt;_authenticateResultInfo['code'] = Zend_Auth_Result::FAILURE_CREDENTIAL_INVALID;
            $this-&gt;_authenticateResultInfo['messages'][] = 'Supplied credential is invalid.';
            return $this-&gt;_authenticateCreateAuthResult();
        }

        unset($resultIdentity[$this-&gt;_zendDb-&gt;foldCase('zend_auth_credential_match')]);
        $this-&gt;_resultRow = $resultIdentity;

        $this-&gt;_authenticateResultInfo['code'] = Zend_Auth_Result::SUCCESS;
        $this-&gt;_authenticateResultInfo['messages'][] = 'Authentication successful.';
        return $this-&gt;_authenticateCreateAuthResult();
    }
</code></pre>

<p>Also here is a new _authenticateCreateSelect method:</p>

<pre class="highlight"><code>
    protected function _authenticateCreateSelect()
    {
        // build credential expression
        if (empty($this-&gt;_credentialTreatment) || (strpos($this-&gt;_credentialTreatment, "?") === false)) {
            $this-&gt;_credentialTreatment = '?';
        }

        $credentialExpression = new Zend_Db_Expr(
            '(CASE WHEN ' . 
            $this-&gt;_zendDb-&gt;quoteInto(
                $this-&gt;_zendDb-&gt;quoteIdentifier($this-&gt;_credentialColumn, true)
                . ' = ' . $this-&gt;_credentialTreatment, $this-&gt;_credential
                )
            . ' THEN 1 ELSE 0 END) AS '
            . $this-&gt;_zendDb-&gt;quoteIdentifier($this-&gt;_zendDb-&gt;foldCase('zend_auth_credential_match'))
            );

        // get select
        $dbSelect = $this-&gt;_zendDb-&gt;select();
        $dbSelect-&gt;from($this-&gt;_tableName, array('*', $credentialExpression))
                 -&gt;where($this-&gt;_zendDb-&gt;quoteIdentifier($this-&gt;_identityColumn, true) . ' = ?', $this-&gt;_identity);

        return $dbSelect;
    }
</code></pre>

<p>All I have really done is used the _zendDb-&gt;foldCase method to properly case the inserted "zend_auth_credential_match" key.</p>

<p>Thanks,</p>

<p>Mike</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:29:28.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Toni Wenzel (twenzel) on 2009-01-17T11:23:35.000+0000</p> 
        <div class="body">
            <p>I've the same problem. Please fix as soon as possible.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-01-17T12:33:54.000+0000</p> 
        <div class="body">
            <p>Assigning to Ralph.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luiz Fernando Furtado (kgbfernando) on 2009-09-03T08:32:25.000+0000</p> 
        <div class="body">
            <p>It's affect the use of Zend_Auth_Adapter_DbTable with Firebird. Interbase and Oracle OCI.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-09-10T11:50:26.000+0000</p> 
        <div class="body">
            <p>Fixed in 1.9 in 18066 and in trunk at 18065</p>

        </div>
    </div>
    </div>

