<h2>ZF-387: saved datatypes in Zend_Config_ini::load()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2006-09-19T14:41:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>create a alternative to load ini file without using the function parse_ini_file()</p>

<p>Ini-Values with geted datatypes:</p>

<pre class="highlight"><code>
true/on/yes  -&gt; boolean : true
false/off/no -&gt; boolean : false
null         -&gt; null
             -&gt; null
0            -&gt; int : 0
1            -&gt; int : 1
1.1          -&gt; float : 1.1
"0"          -&gt; string : 0
"1"          -&gt; string : 1
"1.1"        -&gt; string : 1.1
abc          -&gt; string : abc
"abc"        -&gt; string : abc
"ab\nc"      -&gt; string : "ab\nc"  (\n = parsed)
'ab\nc'      -&gt; string : 'ab\nc' (\n = not parsed)
"ab
c"           -&gt; string : "ab\nc" (\n = parsed)
</code></pre>

<p>And allowing a numeric key to create lists in the ini value:</p>

<pre class="highlight"><code>
foo.bar.0 = "element"
foo.bar.1 = true
foo.bar.2 = no
foo.bar.3 = 345
foo.bar.4 = -345
-&gt; get array(
    0 =&gt; "element",
    1 =&gt; true,
    2 =&gt; false,
    3 =&gt; 345,
    4 =&gt; -345
)
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2006-09-19T16:34:46.000+0000</p> 
        <div class="body">
            <p>If you allow numeric keys in the ini file, I think that you would get PHP parse errors for the case of:</p>

<pre class="highlight"><code>
$x = $config-&gt;foo-&gt;bar-&gt;0;
</code></pre>

<p>How should that be handled?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (GIATA mbH) (mben) on 2006-09-19T16:51:57.000+0000</p> 
        <div class="body">
            <p>Numeric Keys are only allowed as last key in the ini file then it can handled as array.
These keys are not keys in the normal sense. It is a list-value of the key foo.bar</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (GIATA mbH) (mben) on 2006-09-19T17:34:19.000+0000</p> 
        <div class="body">
            <p>In Zend_Config_Array and Zend_Config_Xml these lists can use too.</p>

<p>Example Array:</p>

<pre class="highlight"><code>
$config['system_requirements'] = array(
    'php' =&gt; array(
        'extension' =&gt; array('mbstring', 'libxml', gd2)
    )
);
</code></pre>

<p>Example Xml:</p>

<pre class="highlight"><code>
mbstringlibxmlgd2</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2006-10-03T15:57:54.000+0000</p> 
        <div class="body">
            <p>After some discussion with Darby, I'm resolving this as won't fix as it's possible to do</p>

<pre class="highlight"><code>
$array = array_values($config-&gt;foo-&gt;bar);
</code></pre>

<p>for those cases when you must have a numeric array rather than an associative one.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (GIATA mbH) (mben) on 2006-10-04T12:33:05.000+0000</p> 
        <div class="body">
            <p>OK, then I must create a list manuely.
But are the saved data types without array-lists as "Won't fix" too?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2006-10-04T13:26:15.000+0000</p> 
        <div class="body">
            <p>Certainly not going to be looked at before 0.2.</p>

<p>In general, I'm not in favour of reimplementing parse_ini_file() in PHP though as parse_ini_file() is nice and quick. I suppose it depends on how useful type information is for a config class. What uses do you have that require type information?</p>

        </div>
    </div>
    </div>

