<h2>ZF-3111: Specify HeadLink setAlternate with 'media' attribute</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-04-15T05:49:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-21T08:12:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4902">ZF-4902</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I would render this code</p>

<pre class="highlight"><code> 
</code></pre>

<p>But with this code</p>

<pre class="highlight"><code>
$this-&gt;headLink()-&gt;setAlternate('/mydocument.pdf', "application/pdf", "foo")
</code></pre>

<p>I'm able to render only</p>

<pre class="highlight"><code> 
</code></pre>

<p>Why not add an extra parameter like $extras to do things like this?</p>

<pre class="highlight"><code>
$this-&gt;headLink()-&gt;setAlternate('/mydocument.pdf', "application/pdf", "foo", array('media'=&gt;'print'))
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-09T12:22:08.000+0000</p> 
        <div class="body">
            <p>Scheduling for next minor release (new functionality)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T15:23:03.000+0000</p> 
        <div class="body">
            <p>Trying to assign unassigned issues to smallify our unresolved issue pile. If this can be a community fix, then please unassign it and leave some instruction for proceeding in a comment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-12-10T16:19:39.000+0000</p> 
        <div class="body">
            <p>The fix was checked in with r13141</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by nike shox (nike shox) on 2012-11-21T08:12:16.000+0000</p> 
        <div class="body">
            <p>Inspirert av sprinter Usain "Lightning" <a href="http://www.nikeshoxsko.biz">http://www.nikeshoxsko.biz</a> Bolt, has PUMA with Paris-baserte forhandleren Shinzo for a collection of environmentally friendly <a href="http://www.nikeshoxsko.biz">http://www.nikeshoxsko.biz</a> joggesko pyntet i fargene the jamaicanske nasjonale Flagg.</p>

        </div>
    </div>
    </div>

