<h2>ZF-3853: http://framework.zend.com/issues/browse/ZF-3514 still present in 1.5.3</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-05T10:51:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-08T16:33:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3514">ZF-3514</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>ncaught exception 'Zend_Search_Lucene_Exception' with message 'File './Data/CacheSearch/_14p_1i.del' is not readable.' in /opt/ZendFramework-1.5.3/library/Zend/Search/Lucene/Storage/File/Filesystem.php:59
Stack trace:</p>

<h1>0 /opt/ZendFramework-1.5.3/library/Zend/Search/Lucene/Storage/Directory/Filesystem.php(358): Zend_Search_Lucene_Storage_File_Filesystem-&gt;__construct('./Data/CacheSea...')</h1>

<h1>1 /opt/ZendFramework-1.5.3/library/Zend/Search/Lucene/Index/SegmentInfo.php(309): Zend_Search_Lucene_Storage_Directory_Filesystem-&gt;getFileObject('_14p_1i.del')</h1>

<h1>2 /opt/ZendFramework-1.5.3/library/Zend/Search/Lucene.php(390): Zend_Search_Lucene_Index_SegmentInfo-&gt;__construct(Object(Zend_Search_Lucene_Storage_Directory_Filesystem), '_14p', 1145, 54, 1, true)</h1>

<h1>3 /opt/ZendFramework-1.5.3/library/Zend/Search/Lucene.php(460): Zend_Search_Lucene-&gt;_readSegmentsFile()</h1>

<h1>4 /opt/ZendFramework-1.5.3/library/Zend/Search/Lucene.php(186): Zend_Search_Lucene-&gt;__construct('./Data/CacheSea...', false)</h1>

<h1>5 /home/mangler/CEWebS/TransformationEngi in <b>/opt/ZendFramework-1.5.3/library/Zend/Search/Lucene/Storage/File/Filesystem.php</b> on line <b>59</b><br /></h1>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-08T16:32:53.000+0000</p> 
        <div class="body">
            <p>In the future, please add a comment to the original issue and/or vote for it.</p>

<p>,Wil</p>

        </div>
    </div>
    </div>

