<h2>ZF-3606: testWithOption(Zend_TranslateTest) unit tests failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-07-08T09:32:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is unit tests failure with the following diagnostic:</p>

<p>{panel}
8) testWithOption(Zend_TranslateTest)
Failed asserting that two strings are equal.
expected string 
difference      &lt;         ?????&gt;
got string      
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-07-14T14:40:20.000+0000</p> 
        <div class="body">
            <p>Fixed with r 10086... is the problem remains please reopen the issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-07-26T11:21:02.000+0000</p> 
        <div class="body">
            <p>Changes are merged into release-1.5 branch to fix the problem for next mini-release</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:42.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

