<h2>ZF-3924: isValid() throws exception with deeply nested subforms</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-11T09:24:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-31T09:51:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jason Eisenmenger (jasoneisen)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9348">ZF-9348</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
    public function testAction()
    {
       $subForm1 = new Zend_Form_Subform(array('legend'=&gt;'Subform 1'));
       $subForm2 = new Zend_Form_Subform(array('legend'=&gt;'Subform 2'));
       $subForm3 = new Zend_Form_Subform(array('legend'=&gt;'Subform 3'));
       
       $subForm3-&gt;addElement('checkbox', '1', array('label' =&gt; 'Checkbox'));
       $subForm3-&gt;addElement('text', '2', array('label' =&gt; 'Textbox'));
       
       $subForm2-&gt;addElement('checkbox', '1', array('label' =&gt; 'Checkbox'));
       $subForm2-&gt;addElement('text', '2', array('label' =&gt; 'Textbox'));
       
       $subForm2-&gt;addSubform($subForm3, '3');
       $subForm1-&gt;addSubForm($subForm2, '2');
       
       $form = new Zend_Form();
       $form-&gt;addSubform($subForm1, '1');
       
       $form-&gt;addElement('submit', 'submit', array('label' =&gt; 'Submit'));
       
       if ($this-&gt;getRequest()-&gt;isPost() &amp;&amp; $form-&gt;isValid($this-&gt;getRequest()-&gt;getPost())) {
            echo "Succeeded";
       }
       
       $this-&gt;view-&gt;form = $form;
    }
</code></pre>

<p>This throws the following exception:</p>

<pre class="highlight"><code>
exception 'Zend_Form_Exception' with message 'Zend_Form::Zend_Form::isValid expects an array' in /Users/Jason/Sites/asdf/library/Zend/Form.php:1973 Stack trace: 
#0 /Users/Jason/Sites/asdf/library/Zend/Form.php(1995): Zend_Form-&gt;isValid('') 
#1 /Users/Jason/Sites/asdf/library/Zend/Form.php(1993): Zend_Form-&gt;isValid(Array) 
#2 /Users/Jason/Sites/asdf/library/Zend/Form.php(1993): Zend_Form-&gt;isValid(Array) 
#3 /Users/Jason/Sites/asdf/application/modules/default/controllers/TestController.php(47): Zend_Form-&gt;isValid(Array)
</code></pre>

<p>Things to note:</p>

<p>1: This will work fine when the elements from subform 2 are removed
2: This will work fine when subform 3 is removed entirely
3: When all element names are unique and not the same name of any subform it works fine, but if you name the elements '1', '2', '3', and '4' respectively, subform 3 won't be displayed, and the form will still fail.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bernd Matzner (bmatzner) on 2009-01-27T17:28:12.000+0000</p> 
        <div class="body">
            <p>The problem occurs when subform names are identical with element names, so it's probably good advice to always keep subform, display group, and element names unique in a form. It would be great if there was an exception that makes clear that unique names are required.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-05T21:54:20.000+0000</p> 
        <div class="body">
            <p>Had the same problem and found a fix for this, having equal names for a Child Element of a SubForm and the SubForm itself should work, imho.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-18T08:21:51.000+0000</p> 
        <div class="body">
            <p>Fixed in [ZF-9348]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-25T13:24:02.000+0000</p> 
        <div class="body">
            <p>Reopened because suggested fix is not reviewed and committed yet.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-31T09:51:14.000+0000</p> 
        <div class="body">
            <p>Matthew Weier O'Phinney resolved [ZF-9348] Patch applied to trunk and 1.10 release branch.</p>

        </div>
    </div>
    </div>

