<h2>ZF-3991: Add possibility to change loader class</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-08-19T01:27:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-14T05:46:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Constantine Yurevich (cyurevich)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4167">ZF-4167</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When developer has his own loader class and uses it (for example My_Loader) there is no possibility to use it in Zend_Db_Table and Zend_Db_Table_Rowset to load custom rowset and row classes. Now developer needs to override in extended class WHOLE fetchRow and createRow methods of class Zend_Db_Table_Abstract, and change only one row in this methods for example
from:
@Zend_Loader::loadClass($this-&gt;_rowClass);
to:
@My_Loader::loadClass($this-&gt;_rowClass);</p>

<p>Is it possible to have some method setLoaderClass (similar to setRowClass and setRowsetClass)? Or is it possible just to check somehow if registerAutoload class already registered and use already registered loader class?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-14T05:46:22.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk and 1.8 release branch</p>

        </div>
    </div>
    </div>

