<h2>ZF-3006: Zend_Cache SQLite backend creates SQLite 2.x databases</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-03-31T23:57:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-01-28T10:28:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Shekar Reddy (zendfw)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Bennewitz (private) (mabe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Apparently, Zend_Cache SQLite backend creates SQLite 2.x databases that most GUI tools fail to open them because they support only SQLite 3.x databases. Need an option to specify which version of SQLite database files to create (2.x, 3.x). Maybe, use PDO sqlite while creating the database file?</p>

<p>Further, under unix, the sqlite db file is created as a unix executable with the following privileges:</p>

<p>_www : Read &amp; Write
staff : Read &amp; Write
everyone : Read &amp; Write</p>

<p>Is this an issue with not being able to open the file in sqlite GUI tools?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shekar Reddy (zendfw) on 2008-04-01T12:19:11.000+0000</p> 
        <div class="body">
            <p>Zend_Cache_SQLite is creating sqlite2 databases probably because it is using the library:
<a href="http://www.php.net/manual/en/ref.sqlite.php">http://www.php.net/manual/en/ref.sqlite.php</a></p>

<p>To create sqlite3 databases, it may have to use:
<a href="http://www.php.net/manual/en/ref.pdo-sqlite.php">http://www.php.net/manual/en/ref.pdo-sqlite.php</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T15:53:09.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize/assign as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-04-19T03:29:00.000+0000</p> 
        <div class="body">
            <p>I agree with you, this could be an option of the Sqlite backend</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by thing2b (thing2b) on 2008-11-04T13:45:14.000+0000</p> 
        <div class="body">
            <p>It would be great to use SQLite 3.x databases.</p>

<p>What I can not understand is why Zend_Cache_Backend_Sqlite makes native database calls when calls could be made through Zend_Db_Adapter_Pdo_Sqlite. If I am correct, Zend_Db_Adapter_Pdo_Sqlite supports SQLite2 and SQLite3 databases. Surely making calls on a Zend_Db_Adapter would make things more flexable?</p>

<p>I think Zend_Cache_Backend_Sqlite should be able to be constructed with a path to a Sqlite file OR a Zend_Db_Adapter. Although it might not be wise to use many other Zend_Db_Adapter types, the choice should be mine.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2009-06-22T23:31:01.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>I'm working on a Zend_Cache refactoring proposal.
This would handle all SQLite versions and php adapters.</p>

<p>Please take a look and tell your opinions.</p>

<p>PS: A native sqlite call is much faster and some sql's ( e.g. CREATE ) are not same on all databases ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2009-07-17T11:03:33.000+0000</p> 
        <div class="body">
            <p>change Assignee because I'm inactive now</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-04-16T11:02:20.000+0000</p> 
        <div class="body">
            <p>This will be fixed in ZF 2.0 on using one of the installed extensions sqlite3, pdo_sqlite or sqlite and/or based on Pádraic's 
<a href="http://framework.zend.com/wiki/pages/viewpage.action?pageId=9437191">Zend_Cache_Backend_Database</a> proposal.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ame Nomade (ame_nomade) on 2011-10-26T13:38:59.000+0000</p> 
        <div class="body">
            <p>Hi, did you noticed that in Ubuntu 11.10, support of Sqlite 2.x has been dropped down? It is true for the desktop version, and also for the server one. See, the issue in Launchpad: <a href="https://bugs.launchpad.net/ubuntu/+source/php5/+bug/875262">https://bugs.launchpad.net/ubuntu/+source/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gencer (gencer) on 2012-01-28T10:28:29.000+0000</p> 
        <div class="body">
            <p>For who want to use Zend_Cache with SQLite3 support on v1x follow this link:
<a href="http://gencergenc.wordpress.com/2012/01/28/zend-zend_cache-with-sqlite3-support/">http://gencergenc.wordpress.com/2012/01/…</a></p>

        </div>
    </div>
    </div>

