<h2>ZF-3523: Zend layout is &quot;bubbling&quot; exception?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-26T11:28:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marcin Lulek (ergo14)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Layout</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11345/default-setup.tar.gz">default-setup.tar.gz</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Ive filed a sample test case(add zf1.5.2 to lib)  where it appears that exception gets handled by error controller, and at the same time php complains about unhandled exception.</p>

<p>The issue does not appear when i take out Zend_Layout::startMvc(...), from my bootstrap and the exception is handled properly...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marcin Lulek (ergo14) on 2008-06-26T11:29:03.000+0000</p> 
        <div class="body">
            <p>test case for the problem</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-07-09T06:29:13.000+0000</p> 
        <div class="body">
            <p>Assigning to Ralph.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-10-22T16:52:36.000+0000</p> 
        <div class="body">
            <p>I just tested this application that that error is coming up because it can't find the layout phtml file.  Which is not handled by the view error controller.  Once i created default.phtml file in the Application/Layouts folder that exception went away.</p>

<p>To me this is the expected action as you should have a layout there if you are going to be using the layout component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:12.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

