<h2>ZF-3881: Zend_Form::setDefaults( array $defaults ) does not  reset the values null</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-07T02:33:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-18T12:04:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Huszár Andor (huandy)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12220/ZF-3881.patch.txt">ZF-3881.patch.txt</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>the phpdoc says:
 "If an element's name is not specified as a key in the array, its value is set to null."</p>

<p>well it doesn't do what it says.
I suppose there is a missing else clause in the first if statement of this method, where it should call the setDefault( $name, null ) method to reset the form elements value</p>

<p>this is unless I got something misunderstood.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Travis Pew (travisp) on 2009-09-18T06:47:46.000+0000</p> 
        <div class="body">
            <p>This behavior was changed for ZF-2735 with r8633, but the phpdoc was never updated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-09-18T12:04:18.000+0000</p> 
        <div class="body">
            <p>Docblock updated in trunk and 1.9 release branch</p>

        </div>
    </div>
    </div>

