<h2>ZF-3843: Framework uses not supported encodings on AIX in iconv</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-04T00:21:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-13T22:11:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3072">ZF-3072</a></li>
            <li><a href="/issues/browse/ZF-5133">ZF-5133</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The problem occured to me when I tried Zend_Pdf on an i5. It uses "CP1252//IGNORE" as encoding for iconv which is not supported by AIX. The right encoding for AIX should be "IBM-1252". "//IGNORE" doesn't work altogether. Although it's IBMs fault in my opinion, it prevents the use of a lot of parts of Zend Framework.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-09-01T21:36:23.000+0000</p> 
        <div class="body">
            <p>link to ZF-3072</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-11-08T00:28:44.000+0000</p> 
        <div class="body">
            <p>Added to component "Zend_Pdf", reassigned automatically.</p>

        </div>
    </div>
    </div>

