<h2>ZF-3508: API to get metadate for a given id</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-06-25T01:35:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be nice to have an API to read the meta data of a given cache entry (when was the item cached, what tags does the item have or maybe custom metadata).</p>

<p>Here is an example scenario:
An application that displays financial data should be updated every minute. However if updated financial data is not available, the existing data should still be used for up to 4 hours along with a timestamp in red to display the time when the data was last updated.</p>

<p>For implement this, the cache TTL would be set to 4 hours. In the code the metadata would first be read to determine if the data is older than 1 minute. If so a request is made and the cache is updated if new data is available. Otherwise the current data will be read.</p>

<p>Ideally there would even be a way to write some more custom metadata like "lastchecked" so that the check if the data is older than 1 minute is only done every 30 seconds at most.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-07-05T05:45:02.000+0000</p> 
        <div class="body">
            <p>the test() method is a good solution for mtime</p>

<p>for other things, it requires big changes (but i agree with you)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-08-29T12:55:54.000+0000</p> 
        <div class="body">
            <p>just commited into SVN trunk new methods "touch($id, $extendedLifetime) or getMetadatas($id)" (for File and Apc backend only, for the moment)</p>

<p>can you try it ?</p>

<p>thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-09-06T09:45:59.000+0000</p> 
        <div class="body">
            <p>fixed in SVN trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:15.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

