<h2>ZF-3976: Zend_View_Helper_Action should give option to bypass the current request parameters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-08-17T19:38:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the views &lt;?= $this-&gt;action() ?&gt; is usually used to call page related controls. The helper dose not give an option to merge or bypass the current request user parameters by force set them to null, Why?</p>

<p>public function resetObjects(array $newParams) 
    { 
        $params = $this-&gt;request-&gt;getUserParams(); 
        foreach ($newParams as $key =&gt; $value) { 
            $this-&gt;request-&gt;setParam($key, $value); 
        }</p>

<p>public function action($action, $controller, $module = null, array $params = array() , $merge = false)</p>

<p>and one more parameter to the action function to merge the user request parameters with the give parameters. 
The current code is require set variable from the view control and if this in a layout view like my layout, it will be a nightmare  :)</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:48.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

