<h2>ZF-3978: Zend_Session_Namespace is PHP 5.3 incompatible</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-18T01:07:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Pawel Przeradowski (squeaky)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>PHP 5.3 will warn about __get magic call not being public.</p>

<p>Warning: The magic method __get() must have public visibility and can not be static in /home/squeaky/workspace/www/squeaky/lib/Zend/Session/Namespace.php on line 247</p>

<p>Changing</p>

<pre class="highlight"><code>
protected function &amp; __get($name)
</code></pre>

<p>to</p>

<pre class="highlight"><code>
public function &amp; __get($name)
</code></pre>

<p>resolves issue.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Olivier Doucet (ezameku) on 2008-08-22T11:25:05.000+0000</p> 
        <div class="body">
            <p>Bug confirmed with PHP 5.3.0alpha2-dev
Snapshot used :
21 Aug 2008 20:04:06 -0400</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-22T14:57:41.000+0000</p> 
        <div class="body">
            <p>Scheduling for RC3.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-24T07:44:18.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.6 release branch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:28.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

