<h2>ZF-3730: &lt;form&gt; should not render id attribute if ID is not present (invalid XHTML)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-23T15:09:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11410/Form.php">Form.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is no reason why every</p>

<p>&lt;</p>

<p>form&gt; should have own unique ID</p>

<p>If I dont specify ID for Zend_Form then form is rendered as</p>

<p>&lt;</p>

<p>form id=""&gt; which is also XHTML invalid</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michal Vrchota (techi) on 2008-07-23T17:58:56.000+0000</p> 
        <div class="body">
            <p>patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-04T06:06:15.000+0000</p> 
        <div class="body">
            <p>Scheduling for 1.6 final release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-05T09:52:20.000+0000</p> 
        <div class="body">
            <p>Already fixed in trunk and 1.6 release branch in previous round of fixes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:11.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

