<h2>ZF-3854: Promote Zend_Wildfire to trunk and 1.6 release branch</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2008-08-05T12:29:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Wildfire</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Promote Zend_Wildfire component to trunk and 1.6 release branch.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoph Dorn (cadorn) on 2008-08-05T22:40:08.000+0000</p> 
        <div class="body">
            <p>I can merge over the demo, library and tests to the trunk and 1.6 release branch.</p>

<p>You should probably do the Documentation to ensure it will fit into the overall flow properly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christoph Dorn (cadorn) on 2008-08-05T22:47:28.000+0000</p> 
        <div class="body">
            <p>Should I delete the code out of the incubator as I merge it?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-06T07:43:46.000+0000</p> 
        <div class="body">
            <p>All artifacts merged to trunk and 1.6 release branch and removed from incubator.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:41.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

