<h2>ZF-3114: Zend_Db_Table_Row_Abstract--&gt;__set() modified detection</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-04-15T12:32:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Lanin (alexl)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm just gonna give an example. Please delete/close this if I'm wrong.</p>

<p>my current code:</p>

<pre class="highlight"><code>
if($photo-&gt;albumId    != $albumId)    $photo-&gt;albumId = $albumId;
if($photo-&gt;name        != $name)    $photo-&gt;name = $name;
$photo-&gt;save();</code></pre>

<p>better code:</p>

<pre class="highlight"><code>
$photo-&gt;albumId = $albumId;
$photo-&gt;name = $name;
$photo-&gt;save();</code></pre>

<p>fix required:
in Zend_Db_Table_Row_Abstract
old:</p>

<pre class="highlight"><code>
public function __set($columnName, $value)
{
    $columnName = $this-&gt;_transformColumn($columnName);
    if (!array_key_exists($columnName, $this-&gt;_data)) {
        require_once 'Zend/Db/Table/Row/Exception.php';
        throw new Zend_Db_Table_Row_Exception("Specified column \"$columnName\" is not in the row");
    }
    $this-&gt;_data[$columnName] = $value;
    $this-&gt;_modifiedFields[$columnName] = true;
}</code></pre>

<p>new:</p>

<pre class="highlight"><code>
public function __set($columnName, $value)
{
    $columnName = $this-&gt;_transformColumn($columnName);
    if (!array_key_exists($columnName, $this-&gt;_data)) {
        require_once 'Zend/Db/Table/Row/Exception.php';
        throw new Zend_Db_Table_Row_Exception("Specified column \"$columnName\" is not in the row");
    }
    
    if($this-&gt;_data[$columnName] != $value) {
        $this-&gt;_data[$columnName] = $value;
        $this-&gt;_modifiedFields[$columnName] = true;
    }
}</code></pre>

<p>This is not tested. Just to make clear what I want.</p>

<p>version: trunk 9228</p>

<p>// edit: made code readable
// edit2: second attempt :D</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:20:28.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-04-21T12:33:16.000+0000</p> 
        <div class="body">
            <p>This is not an issue; if you examine the code of {{_doUpdate()}}, you'll see that this functionality already exists. For example:</p>

<pre class="literal">
        /**
         * Compare the data to the modified fields array to discover
         * which columns have been changed.
         */
        $diffData = array_intersect_key($this-&gt;_data, $this-&gt;_modifiedFields);
</pre>

<p>Please feel free to reopen if I have missed something. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Lanin (alexl) on 2008-04-21T14:00:05.000+0000</p> 
        <div class="body">
            <p>array_intersect_key() does not evaluate the value at all. I just checks the keys.
<a href="http://de.php.net/manual/en/function.array-intersect-key.php">http://de.php.net/manual/en/…</a></p>

<p>and ``` is just "true" anyway</p>

<p>so I think whats happening is that doUpdate updates all fields, even if value was "changed" but remains the same.</p>

<p>maybe you didn't understood my point. I was saying that when sql returns me a "name=fritz" and I do tableRow-&gt;name = "fritz" than I did <em>not</em> change the value - no need to include it into doUpdate()</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-04-21T14:05:08.000+0000</p> 
        <div class="body">
            <p>I see now; thanks for clarifying this. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-12-08T05:01:59.000+0000</p> 
        <div class="body">
            <p>It's a little more complicated than a simple '!='. For example, we must differently manage 'null', '', 'false' and '0'.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Lanin (alexl) on 2008-12-08T09:10:37.000+0000</p> 
        <div class="body">
            <p>!== ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-12-08T09:45:12.000+0000</p> 
        <div class="body">
            <p>See <a href="http://mikaelkael.fr/ZF-3114.php">http://mikaelkael.fr/ZF-3114.php</a> for a first try. We must read by lines (not by columns).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:30.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

