<h2>ZF-3422: Defining the validation error of each element of an array of elements in a form</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-06-09T13:03:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-08-04T06:55:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jérémy Lajotte (pengu)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In a form with an array of elements, only the last validation error message is saved for each type of validation. It is therefore not possible to display the appropriate error message for each fields.</p>

<p>Exemple :</p>

<pre class="highlight"><code> 
$form-&gt;addElement('text', 'test',
        array(
          'validators' =&gt; array('int'),
          'IsArray' =&gt; true
        );
</code></pre>

<p>HTML :</p>

<pre class="highlight"><code>
</code></pre>

<p>Let's say we entered A in the first field, B in the second one, and C in the last one.</p>

<p>After validation, we have this :</p>

<pre class="highlight"><code> 
[_messages:protected] =&gt; Array
        (
            [notInt] =&gt; 'C' does not appear to be an integer
        )
</code></pre>

<p>Something like this would be more usefull :</p>

<pre class="highlight"><code>
[_messages:protected] =&gt; Array
        (
            [0] =&gt; Array
                (
                    [notInt] =&gt; 'A' does not appear to be an integer
                )
            [1] =&gt; Array
                (
                    [notInt] =&gt; 'B' does not appear to be an integer
                )
            [2] =&gt; Array
                (
                    [notInt] =&gt; 'C' does not appear to be an integer
                )
        )
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-04T06:54:06.000+0000</p> 
        <div class="body">
            <p>The issue is that you're treating a single element as if it were multiple elements. You can better achieve what you want to accomplish with sub forms.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-04T06:55:00.000+0000</p> 
        <div class="body">
            <p>To change this would require a major overhaul of Zend_Form for what is considered an edge use case. The poster is referred to the comment regarding sub form usage for a solution.</p>

        </div>
    </div>
    </div>

