<h2>ZF-3376: $element-&gt;setDecorators($element-&gt;getDecorators()) not works</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-03T09:53:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$element-&gt;setDecorators($element-&gt;getDecorators()) not works</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-06-03T23:22:41.000+0000</p> 
        <div class="body">
            <p>Could you indicate what does not work about it, please? What errors are presented? What expectations are not met?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by F LAdislav (bloom) on 2008-06-04T22:30:29.000+0000</p> 
        <div class="body">
            <p>I expect this line of code to has no effect on element decorators. Instead, some decorators are lost. It seems it does not get decorators aliases.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-07-25T08:02:07.000+0000</p> 
        <div class="body">
            <p>This was corrected with some refactoring done for 1.6.0; you can now pass the results of getDecorators() to setDecorators(), and all aliasing is preserved. A test has been added to verify this.</p>

<p>Test added in trunk and merged to 1.6 release branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:12.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

