<h2>ZF-3661: Wrong  var name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-16T12:18:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-26T08:37:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.2 (13/Oct/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Davide (netcelli)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Wrong variable name at line 97 in OpenID/Consumer.php 
private $_erro = '';
should be 
private $_error = '';</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-08-24T23:06:59.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r11040</p>

        </div>
    </div>
    </div>

