<h2>ZF-3813: URL delimiter in route is only '/', should also be '.'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-31T00:50:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-31T14:25:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Postponed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using routes i'd like to have one like this:</p>

<pre class="highlight"><code>
Static:staticUrl.htmlshopindexstatic</code></pre>

<p>But the '_urlDelimiter' variable in Zend_Controller_Router_Route contains only '/' character, so the route is not exploded as expected (not to 'staticUrl' parameter  and suffix, but to 'staticUrl.html' parameter). I don't know if it's bug or 'feature'.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-07-31T06:07:15.000+0000</p> 
        <div class="body">
            <p>Assigning to Martel to triage.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2008-07-31T06:42:26.000+0000</p> 
        <div class="body">
            <p>This is by design. I'm planning to rewrite Route object (for Route chaining) so this will work without any effort on user part. But for now you have to extend the route and override _urlDelimiter,  Tomas.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tomáš Fejfar (tomas.fejfar@gmail.com) on 2008-07-31T14:25:20.000+0000</p> 
        <div class="body">
            <p>OK, from the code it's just what I expected, I just want to "let know" about this. As long as that some people can be upset by this not working... ;)</p>

        </div>
    </div>
    </div>

