<h2>ZF-3567: Add something like getFullName() to Zend_Form_Element</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-07-03T05:47:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-09T09:54:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Move method Zend_Form_Decorator_ViewHelper::getName() to Zend_Form_Element::getFullName() to allow use it with ViewScript decorator to properly render element. Now rendering element with ViewScript decorator I have to do:</p>

<pre class="highlight"><code>
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-07-09T09:54:30.000+0000</p> 
        <div class="body">
            <p>getFullyQualifiedName() and getId() added to Zend_Form, Zend_Form_SubForm, Zend_Form_DisplayGroup, and Zend_Form_Element as of r10008.</p>

        </div>
    </div>
    </div>

