<h2>ZF-3526: HtmlTag Decorator with empty tag name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-27T05:28:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-21T09:49:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When configuring an element with the config like the following (leaving HtmlTag.options.tag empty):</p>

<p>elements.flightsearchhourstart.type = "hidden"
elements.flightsearchhourstart.name = "hourStart"
elements.flightsearchhourstart.options.decorators.helper = "ViewHelper"
elements.flightsearchhourstart.options.decorators.HtmlTag.decorator = "HtmlTag"
elements.flightsearchhourstart.options.decorators.HtmlTag.options.tag = ""</p>

<p>the hidden field will be sourrunded by empty openening and closing tags:</p>

<p>&lt;&gt;&lt;/&gt;</p>

<p>I fixed it with the following code within the HtmlTag-Decorator</p>

<pre><code>protected function _getOpenTag($tag, array $attribs = null)
{
    $html='';
    if($tag!=''){
        $html = '&lt;' . $tag;
        if (null !== $attribs) {
            $html .= $this-&gt;_htmlAttribs($attribs);
        }
        $html .= '&gt;';
    }
    return $html;
}
</code></pre>

<p>...............</p>

<pre><code>protected function _getCloseTag($tag)
{
    if($tag!=''){
        return '&lt;/' . $tag . '&gt;';
    }
    return '';
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-04-03T04:00:34.000+0000</p> 
        <div class="body">
            <p>I do not understand why you are adding the HtmlTag Decorator at all
if you do not want it to be rendered.</p>

<p>Even i do not know what the state was in 1.5.2, in current trunk,
setting the ViewHelper Decorator in config disables loading default
Decorators, so this issue is now a non issue for me, and i am closing
it now.</p>

        </div>
    </div>
    </div>

