<h2>ZF-3578: Zend_Config_Xml throws warnings when loading of xml file was NOT successfull</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-04T02:53:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Patrick van Dissel (tdm)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the __construct() of Zend_Config_Xml, the function simplexml_load_file() is used for loading the xml file. But there is not checked if loading of the file was successfull, which causes multiple PHP warning to be thrown.</p>

<p>It would be nice/better to just throw an Exception when loading of the XML file was not-successfull.
Something like the following would do the job:</p>

<pre class="highlight"><code>
$config = @simplexml_load_file($filename);
if (false === $config) {
    throw new Zend_Config_Exception('File could not be loaded');
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-07-16T15:34:39.000+0000</p> 
        <div class="body">
            <p>fixed at r10147</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:42.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

