<h2>ZF-3525: Missing ['attribs']</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-27T02:51:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-20T14:35:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think I found an error in "Zend/View/Helper/FormElement.php"</p>

<p>the following should be changed on line 159:</p>

<pre><code>    // Remove attribs that might overwrite the other keys. We do this LAST 
    // because we needed the other attribs values earlier.
</code></pre>

<p>-foreach ($info as $key =&gt; $val) {-
+foreach ($info['attribs'] as $key =&gt; $val) {+
    if (isset($info['attribs'][$key])) {
        unset($info['attribs'][$key]);
    }
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andreas Huber (andreashuber) on 2008-06-27T16:11:23.000+0000</p> 
        <div class="body">
            <p>After I gave it some more thought and understood the comment I realised that this is not a bug.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-08-25T03:07:20.000+0000</p> 
        <div class="body">
            <p>I think from the comment  of  Andreas,  it is not issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:02.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

