<h2>ZF-3721: PhotosOnlineTest does not clean up after itself</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-07-22T17:01:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-26T18:22:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.5 (16/Feb/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Gdata_PhotosOnlineTest test suite does not clean up after itself. This leaves the account used to run tests littered with albums and photos. Eventually the test account hits its upper limit on albums, causing tests to fail.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-02-26T17:26:54.000+0000</p> 
        <div class="body">
            <p>I believe [~jhartmann] is working on this. Assigning to him.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2009-02-26T18:22:08.000+0000</p> 
        <div class="body">
            <p>Not sure who fixed the tests as Fisheye seems to be down. Looks like all tests in PhotosOnlineTest have clean up methods, so marking this resolved as of 1.7.5</p>

        </div>
    </div>
    </div>

