<h2>ZF-3374: Fatal error when Zend_Search_Lucene can't delete an index file</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-03T03:43:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-25T09:16:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.3 (28/Jul/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sharique Abdullah (shabeepk)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend search lucene gives a fatal error occasionally when it can't delete an index file. 
An error occurs on Zend\Search\Lucene\Storage\Directory\Filesystem.php on line 215.</p>

<p>The problem is probably with the statement</p>

<p>throw $e;</p>

<p>and this should be removed.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-06-03T12:37:59.000+0000</p> 
        <div class="body">
            <p>r8564 resolved the bug, but it has not been merged to 1.5.2 branch (as well as others regarding the same file)
You can get a clean copy from trunk, 1.5.3 will integrate these patches ( 8564 to 8568 ), sorry about that.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-07-25T09:16:14.000+0000</p> 
        <div class="body">
            <p>Fixed for the release-1.5 branch with the <a href="http://framework.zend.com/code/changelog/Zend_Framework?cs=9683">CS-9683</a>.</p>

        </div>
    </div>
    </div>

