<h2>ZF-3650: Clarify standard PDF fonts limitations</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-07-15T10:40:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T06:04:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.1 (01/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3649">ZF-3649</a></li>
            <li><a href="/issues/browse/ZF-588">ZF-588</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Standard PDF fonts support only Latin1 character set (actually some superset of Latin1 CS), even input string fro text drawing is represented in 'UTF-8' or any other encoding.
Appropriate TTF fonts should be used for other character sets.</p>

<p>It should be described in the documentation.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-25T16:59:32.000+0000</p> 
        <div class="body">
            <p>Alex, can we fit this in to 1.7.1?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-03T06:18:45.000+0000</p> 
        <div class="body">
            <p>Done.</p>

        </div>
    </div>
    </div>

