<h2>ZF-393: Crash loading PDF created with &quot;accessibility and reflow&quot; option</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-09-21T15:53:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.2.0 (29/Oct/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sylvain Martel (fairlight)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I create a simple document in Word 2000 then convert it in PDF using the Acrobat 6.0 conversion toolbar in Word.  In the conversion settings, if the "enable accessibility and reflow with Tagged PDF" option is checked, I get the following error when loading the file with Zend_Pdf::load  :</p>

<p>"Uncaught exception 'Zend_Pdf_Exception' with message 'Unknown trailer dictionary key: 'XRefStm'.'"</p>

<p>Exporting the document with PDF 4.0, 5.0 or 6.0 compatibility settings doesn't help.  It's definitely the "accessibility and reflow" option that causes the bug, as a document converted without this option loads fine in Zend_Pdf.</p>

<p>A Google search brings up this issue from the Office of Academic Technology web site; maybe it's related?   :
<a href="http://etd.circa.ufl.edu/present/pdfconversion.html">http://etd.circa.ufl.edu/present/…</a>
Excerpt : The "Enable accessibility and reflow with a tagged PDF" option is causing a corruption of the original master document and subdocuments.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-09-22T04:19:45.000+0000</p> 
        <div class="body">
            <p>It means that file is stored as PDF V1.6 but in PDF V1.4 compatibility mode.</p>

<p>It adds XRefStm entry to the file trailer, which is not known by PDF V1.4. But it entry can be simply omitted by PDF reader.
I just made necessary changes. Please take current SVN version (and please let me know if it helps).</p>

<p>That would be also good if you could send an example of such file for future tests (to alexander.v@zend.com)</p>

<p>PS Link you sent is also useful!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sylvain Martel (fairlight) on 2006-09-25T11:17:02.000+0000</p> 
        <div class="body">
            <p>Hi!  I tried with the current SVN version and it does work now!  I will soon send you an example file for tests by e-mail.</p>

<p>Thank you very much!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-09-25T17:19:07.000+0000</p> 
        <div class="body">
            <p>Fixed by changeset -1110</p>

        </div>
    </div>
    </div>

