<h2>ZF-3354: Final and to process variable define in elements of Zend_Form</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-05-29T23:22:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-05-30T05:09:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Rafa? Nauka (kanciak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When we send form some elements are put into the base and with other we do some operation and then add to base or not. The example: 
We have form with data and one photo file. All data without photo file is ready to add but we want to copy somewhere photo and change the name eg rand with time stamp and then add to database.</p>

<p>How that's could work: We would define variable "process" to file_element to state "1". After send form we will getValues() and it will be:</p>

<pre class="highlight"><code>
array(0=&gt;array('first_name'=&gt;'Lucas'), 1=&gt;array('photo'=&gt;'my photo.jpg'));
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-30T05:09:41.000+0000</p> 
        <div class="body">
            <p>The "issue" is not a bug or feature request for Zend_Form, but rather a request for guidance in how to approach a particular form-related development problem. This would be best asked on the fw-mvc@lists.zend.com mailing list.</p>

        </div>
    </div>
    </div>

