<h2>ZF-3265: CSS to XPath (Zend_Dom_Query_Css2XPath)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2008-05-15T10:37:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-14T19:45:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-15T13:21:39.000+0000</p> 
        <div class="body">
            <p>Currently have support for:
* id selectors
* class selectors
* child selectors
* relative associations between atoms
* multiple paths (comma separated CSS selectors)</p>

<p>At this point, we have pretty much all we need to create XPath from CSS selectors</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-19T09:16:22.000+0000</p> 
        <div class="body">
            <p>Branching for class selectors is now implemented and functional.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-07-14T19:45:21.000+0000</p> 
        <div class="body">
            <p>Complete in incubator</p>

        </div>
    </div>
    </div>

