<h2>ZF-3821: Zend_InfoCard does not interpret namespace prefixes from the XML token</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-31T14:49:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-13T23:18:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.11 (29/Sep/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                John Coggeshall (coogle)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_InfoCard</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_InfoCard seems to be expecting the enc: prefix for the <a href="http://www.w3.org/2001/04/xmlenc">http://www.w3.org/2001/04/xmlenc</a># namespace, even when the submitted XML token assigns a different prefix (such as xenc: ) to that namespace. This causes Zend_InfoCard to fail to parse a submitted information card token from card selectors other than Microsoft Cardspace.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Arthur Frankel (afrankel) on 2010-07-09T14:56:24.000+0000</p> 
        <div class="body">
            <p>Since there are several other card selectors available has there been any movement on this fix?  Besides the enc (to xenc) issue there are others related to the namespaces.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-13T23:18:19.000+0000</p> 
        <div class="body">
            <p>Fixed in r24374 and ZF2 hotfix branch.</p>

<p>Sorry for the long wait! It only needed a quick patch to register the namespace for XPath so the default prefix was not relied on.</p>

        </div>
    </div>
    </div>

