<h2>ZF-3036: View Filters can have an incorrect View assigned to them</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-03T12:26:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-15T10:53:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I found what appears to be a bug in the code that performs filtering for views. In the View-&gt;getFilter method there is a check for a setView method on the retrieved Filter object. If this method is found the current view will be assigned to the Filter. Since Filters are "cached" in the _filterXXX variables of the View class they can be persistent through multiple runs of the View if a global View has been assigned to the ViewRenderer helper. This is especially true for Layout based sites. This leads to two issues: (a) one View that has Controller Action specified values assigned to it could have those values be available by another View script and (b) Controller assigned View script values not being made available to already instantiated Filters.</p>

<p>The simple fix to this issue is to have the check for the "setView" method pulled out of the current IF block and made in parallel to the primary IF.</p>

<p>Here is the current code (as of 1.5.0):</p>

<p>(Zend_View_Abstract.php)</p>

<pre class="highlight"><code>
    public function getFilter($name)
    {
        if (!isset($this-&gt;_filterClass[$name])) {
            $class = $this-&gt;_loadClass('filter', $name);
            $this-&gt;_filterClass[$name] = new $class();
            if (method_exists($this-&gt;_filterClass[$name], 'setView')) {
                $this-&gt;_filterClass[$name]-&gt;setView($this);
            }
        }
        return $this-&gt;_filterClass[$name];
    }
</code></pre>

<p>Here is my new proposed code:</p>

<pre class="highlight"><code>
    public function getFilter($name)
    {
        if (!isset($this-&gt;_filterClass[$name])) {
            $class = $this-&gt;_loadClass('filter', $name);
            $this-&gt;_filterClass[$name] = new $class();
        }
        if (method_exists($this-&gt;_filterClass[$name], 'setView')) {
            $this-&gt;_filterClass[$name]-&gt;setView($this);
        }
        return $this-&gt;_filterClass[$name];
    }

</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T16:01:32.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize/assign as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2008-04-22T10:40:25.000+0000</p> 
        <div class="body">
            <p>Updating project management info.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-10-23T18:48:38.000+0000</p> 
        <div class="body">
            <p>Have you tested this since 1.6 got released where it's using hte plugin manager now instead of the _loadClass Method?  If not can you please provide a unitTest for this so we can work on the problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-02-06T09:34:21.000+0000</p> 
        <div class="body">
            <p>Making the code readable.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-10-15T10:53:16.000+0000</p> 
        <div class="body">
            <p>Closed as Not an Issue as there has been no activity for a while.  Please reopen if this is still an issue.</p>

        </div>
    </div>
    </div>

