<h2>ZF-3224: Zend_Controller_Router_Route code cleaning (for readability) and optimization</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-05-08T11:24:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Clean the code and optimize standard framework route.</p>

<p>Testing 10000 matches of:</p>

<pre class="highlight"><code>
$route = new Zend_Controller_Router_Route('archives/:year/:month/*', array('controller' =&gt; 'archive'));

for ($i = 1; $i &lt;= 10000; $i++) {
    $values = $route-&gt;match('archives/2006/' . $i . '/controller/test/year/' . $i . '/sort/author');
}
</code></pre>

<p>Before refactoring:
Test took: 0.6967
Test took: 0.6868
Test took: 0.7009
Test took: 0.6913
Test took: 0.6931
= 3,4688 s</p>

<p>After first:
Test took: 0.5861
Test took: 0.5835
Test took: 0.5802
Test took: 0.5799
Test took: 0.5826
= 2.9123 s</p>

<p>Approx 20% gain.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-05-09T11:18:51.000+0000</p> 
        <div class="body">
            <p>Scheduling for next minor release; Martel, let me know if this will be backwards incompatible, so I can re-schedule and provide a branch for your development.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-05T11:08:53.000+0000</p> 
        <div class="body">
            <p>I believe these changes were incorporated in 1.6.0</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:11.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

