<h2>ZF-3294: Zend_Db_Table_Select failes with ORA-00942 due to extra asterisk (*) after the FROM clause</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-05-19T21:45:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-02T09:32:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li> 1.5.2 (15/May/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ranga Chakravarthi (ranga.chakravarthi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>EmpModel.php :
&lt;?php
require_once 'Zend/Db/Table/Abstract.php';
class EmpModel extends Zend_Db_Table_Abstract {
   protected $_name = 'emp';
}</p>

<p>The following code produces an error:
        $emp = new EmpModel();
        $rows = $emp-&gt;fetchAll();</p>

<p>PHP Fatal error:  Uncaught exception 'Zend_Db_Statement_Oracle_Exception' with message '942 ORA-00942: table or view does not exist SELECT "emp".* FROM *"emp"' in D:\ZendFramework\library\Zend\Db\Statement\Oracle.php:244
Stack trace:</p>

<h1>0 D:\ZendFramework\library\Zend\Db\Statement.php(283): Zend_Db_Statement_Oracle-&gt;_execute(Array)</h1>

<h1>1 D:\ZendFramework\library\Zend\Db\Adapter\Abstract.php(405): Zend_Db_Statement-&gt;execute(Array)</h1>

<h1>2 D:\ZendFramework\library\Zend\Db\Table\Abstract.php(1184): Zend_Db_Adapter_Abstract-&gt;query(Object(Zend_Db_Table_Select))</h1>

<h1>3 D:\ZendFramework\library\Zend\Db\Table\Abstract.php(1039): Zend_Db_Table_Abstract-&gt;_fetch(Object(Zend_Db_Table_Select))</h1>

<h1>4 D:\test\application\default\controllers\IndexController.php(45): Zend_Db_Table_Abstract-&gt;fetchAll()</h1>

<h1>5 D:\ZendFramework\library\Zend\Con in D:\ZendFramework\library\Zend\Db\Statement\Oracle.php on line 244</h1>

<p>Notice the extra asterisk after the FROM clause.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-05-24T03:05:33.000+0000</p> 
        <div class="body">
            <p>When you use Oracle, you must specify a param: autoQuoteIdentifier = false in your config or use the good case-folding.</p>

<p>See <a href="http://framework.zend.com/manual/en/zend.db.html#zend.db.adapter.connecting.parameters">10.1.1.4. Adapter Parameters</a>, and <a href="http://framework.zend.com/manual/en/zend.db.html#zend.db.adapter.connecting.parameters.example2">Example 10.6. Passing the auto-quoting option to the factory</a></p>

<p>or</p>

<pre class="highlight"><code>
&lt;?php
require_once 'Zend/Db/Table/Abstract.php';
class EmpModel extends Zend_Db_Table_Abstract { protected $_name = 'EMP'; }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-01T15:28:13.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ranga Chakravarthi (ranga.chakravarthi) on 2008-06-02T09:00:12.000+0000</p> 
        <div class="body">
            <p>Both suggestions worked. Thank you. The error was misleading as there was an extra asterisk.</p>

        </div>
    </div>
    </div>

