<h2>ZF-307: Confusion about inflected versus native in $_cols array</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-08-05T11:03:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                restman (restman)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-338">ZF-338</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello</p>

<p>I'm writing third application in ZF
and there is one confusing thing:</p>

<p>When I want to write sth into row from db
once i have to use _cols keys, and other time _cols values</p>

<p>explain:
in class Zend_Db_Table_Row we have method setFromArray
and input array must has keys equal to _cols keys
in insert we also should use _cols keys</p>

<p>but in other methods like __get __set __update etc
we access by _cols values</p>

<p>so maybe it should be one standard ??
It's very difficult to guess what use where....</p>

<p>I propose to everywhere use _cols values</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by restman (restman) on 2006-08-05T11:11:47.000+0000</p> 
        <div class="body">
            <p>and my solution, which I use in insert,update etc</p>

<p>foreach ($this-&gt;_cols as $k=&gt;$v) {
           if (in_array($v,$input_array)) 
                   $data[$k] = $input_array[$v];
}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-08-25T11:04:27.000+0000</p> 
        <div class="body">
            <p>Superbiji writes:
{quote}add Zend_DB_Row::fromArray()</p>

<p>currently there is only Zend_DB_Row::setfromArray()
{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:22:39.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.8.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-05T17:06:25.000+0000</p> 
        <div class="body">
            <p>Recategorize as Zend_Db_Table component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-17T17:44:40.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 3725.</p>

<p>The $_cols array is just the keys from describeTable(), there is no longer any distinction between the "native" column name and the inflected column name.</p>

        </div>
    </div>
    </div>

