<h2>ZF-3435: Zend_Validate_Ip does not work as expected/documented</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-11T00:21:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:09:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>phpdoc of Zend_Validate_Ip::isValid() says "Returns true if and only if $value is a valid IP address". But in ZF Versions 1.5.2 and before strings like "192.168.10" or "192.168.10.10   asdf" are successfully validated, too. What in my opinion should not happen, especially the second case.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maurice Fonk (naneau) on 2008-06-23T10:28:13.000+0000</p> 
        <div class="body">
            <p>Seeing as how this bug could have <em>serious</em> security issues for those who rely on the validator, and the relative ease it can be fixed with, I would like to attract a bit of attention to it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-06T12:29:40.000+0000</p> 
        <div class="body">
            <p>Added unittest for this case with r12342. Issue already fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:09:59.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

