<h2>ZF-3472: Zend_Controller_Request_Abstract::setParams is not unsetting pre-existing values </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-17T18:47:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-13T21:49:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.11 (29/Sep/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
require_once 'Zend/Controller/Request/Simple.php';
$r = new Zend_Controller_Request_Simple();
$r-&gt;setParam('key', 'value');
$r-&gt;setParams(
    array(
        'key' =&gt; null
    )
);
var_dump($r-&gt;getParams());
</code></pre>

<p>The preceding code should output:</p>

<pre class="highlight"><code>
array(0) {
}
</code></pre>

<p>but is actually outputting:</p>

<pre class="highlight"><code>
array(1) {
  ["key"]=&gt;
  string(5) "value"
}
</code></pre>

<p>{{getParams()}} should be returning an empty array because {{setParams}} is defining {{key}} to be {{null}} and should therefore be calling {{unset}} on that value.</p>

<p>If I modified the code to the following, then everything works as expected.</p>

<pre class="highlight"><code>
&lt;?php
require_once 'Zend/Controller/Request/Simple.php';
$r = new Zend_Controller_Request_Simple();
$r-&gt;setParam('key', 'value');
$r-&gt;setParam('key', null);
var_dump($r-&gt;getParams())
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stefano Tamagnini (yoghi) on 2010-03-05T12:15:08.000+0000</p> 
        <div class="body">
            <p>REFERENCE ZF 1.10.1
try:</p>

<pre class="highlight"><code>
$request-&gt;setParam('variable',null);
unset($_GET['variable']);
unset($_POST['variable']);
</code></pre>

<p>correct unset variable into Zend_Controller_Request_Http, because into Zend_Controller_Request_Http on getParam(...)
it try to find variable name into $_GET &amp; $_POST :</p>

<pre class="highlight"><code>
    public function getParam($key, $default = null)
    {
        $keyName = (null !== ($alias = $this-&gt;getAlias($key))) ? $alias : $key;

        $paramSources = $this-&gt;getParamSources();
        if (isset($this-&gt;_params[$keyName])) {
            return $this-&gt;_params[$keyName];
        } elseif (in_array('_GET', $paramSources) &amp;&amp; (isset($_GET[$keyName]))) {
            return $_GET[$keyName];
        } elseif (in_array('_POST', $paramSources) &amp;&amp; (isset($_POST[$keyName]))) {
            return $_POST[$keyName];
        }

        return $default;
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-02-17T15:37:28.000+0000</p> 
        <div class="body">
            <p>Matthew, any notes on this?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-13T21:49:33.000+0000</p> 
        <div class="body">
            <p>Fixed r24372. No apparent test breakages. Null check in method doesn't verify against original parameter so it missed the array addition issue.</p>

        </div>
    </div>
    </div>

