<h2>ZF-3739: Stream wrapper should be disabled by default</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-24T05:35:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The new implementation of Zend_View in 1.6.0 provides a stream wrapper that can be used when short tags are disabled. This needs to be disabled by default as it:
* degrades performance
* causes issues with suhosin (user stream wrappers are considered attack vectors by suhosin)
When disabling, the stream wrapper should also be documented with examples of how to enable it, a note about issues with suhosin, and a note about performance degradation.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-04T09:53:14.000+0000</p> 
        <div class="body">
            <p>Fixed and documented in trunk and 1.6 release branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:12.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

