<h2>ZF-3122: Bad Link in Zend_Session Docs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-04-16T12:48:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Yannick Lyn Fatt (axle_foley00)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The link in <em>"See the most recently published version of this document"</em> in the Introduction for Zend_Session does not seem to be working. It links to the following URL:</p>

<p>[<a href="http://framework.zend.com/wiki/x/iVc">http://framework.zend.com/wiki/x/iVc</a>]</p>

<p>Which gives a System Error, stating the following:</p>

<p>{quote}
java.lang.IllegalStateException
 at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:404)</p>

<p>Stack Trace: [hide]</p>

<p>java.lang.IllegalStateException
    at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:404)
    at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:107)
    at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:107)
    at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:107)
    at com.opensymphony.module.sitemesh.filter.PageResponseWrapper.sendError(PageResponseWrapper.java:180)
    at com.opensymphony.webwork.dispatcher.ServletDispatcher.sendError(ServletDispatcher.java:349)
    at com.opensymphony.webwork.dispatcher.ServletDispatcher.serviceAction(ServletDispatcher.java:235)
    at com.opensymphony.webwork.dispatcher.ServletDispatcher.service(ServletDispatcher.java:199)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:802)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:252)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.opensymphony.module.sitemesh.filter.PageFilter.parsePage(PageFilter.java:118)
    at com.atlassian.confluence.util.profiling.ProfilingPageFilter.parsePage(ProfilingPageFilter.java:143)
    at com.opensymphony.module.sitemesh.filter.PageFilter.doFilter(PageFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.confluence.util.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:30)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.confluence.util.UserThreadLocalFilter.doFilter(UserThreadLocalFilter.java:45)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.seraph.filter.SecurityFilter.doFilter(SecurityFilter.java:182)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.seraph.filter.LoginFilter.doFilter(LoginFilter.java:181)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.johnson.filters.JohnsonFilter.doFilter(JohnsonFilter.java:96)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.springframework.orm.hibernate.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:170)
    at bucket.custom.FlushingSpringSessionInViewFilter.doFilterInternal(FlushingSpringSessionInViewFilter.java:31)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:73)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.util.profiling.filters.ProfilingFilter.doFilter(ProfilingFilter.java:122)
    at com.atlassian.confluence.util.error.ProfilingAndErrorFilter.doFilter(ProfilingAndErrorFilter.java:27)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.core.filters.gzip.GzipFilter.doFilter(GzipFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at com.atlassian.core.filters.AbstractEncodingFilter.doFilter(AbstractEncodingFilter.java:37)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:541)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
    at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
    at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
    at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
    at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
    at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
    at java.lang.Thread.run(Thread.java:595)</p>

<p>Referer URL: <a href="http://framework.zend.com/manual/en/zend.session.html">http://framework.zend.com/manual/en/…</a></p>

<p>Build Information:
Confluence Home: /var/www/tools/confluence-data
Uptime: 1 day, 18 hours, 44 minutes, 3 seconds
Version: 2.2.3
Build Number: 518</p>

<p>Server Information:
Application Server: Apache Tomcat/5.5.17
Servlet Version: 2.4
Database Dialect: bucket.dialect.MySQLDialect
Database Driver Name: N/A
Database Driver Version: N/A</p>

<p>Memory Information:
Total Memory: 1241 MB
Free Memory: 576 MB
Used Memory: 665 MB</p>

<p>System Information:
System Date: Wednesday, 16 Apr 2008
System Time: 12:41:26
System Favourite Colour: Taupe
Java Version: 1.5.0_12
Java Vendor: Sun Microsystems Inc.
JVM Version: 1.0
JVM Vendor: Sun Microsystems Inc.
JVM Implementation Version: 1.5.0_12-b04
Java Runtime: Java(TM) 2 Runtime Environment, Standard Edition
Java VM: Java HotSpot(TM) Server VM
User Name: root
User Timezone: US/Central
Operating System: Linux 2.6.9-22.ELsmp
OS Architecture: i386
Filesystem Encoding: UTF-8</p>

<p>Enabled Plugins:
Utilities Plugin (org.randombits.confluence.utilities, Version: 2.1.3)
Plugin Information (com.atlassian.confluence.ext.plugininfo, Version: 0.3)
Labeling Manager (confluence.extra.revlabelingmacros, Version: 1.0)
Basic Macros (confluence.macros.basic, Version: 1.3)
Adaptavist Advanced Search (com.adaptavist.confluence.advancedSearch, Version: 1.0.2)
Chart Plugin (confluence.extra.chart, Version: 1.5)
HTML Macros (confluence.macros.html, Version: 1.3)
User Listener (confluence.extra.userlister, Version: 1.2)
Global Labels Sections (confluence.sections.labels, Version: 1.0)
Information Macros (confluence.extra.information, Version: 0.1)
Cache Plugin (org.apache.geronimo.confluence.plugin.cache, Version: 1.0)
Confluence Remote API (confluence.extra.confluencerpc, Version: 1.4)
Profile Tabs (confluence.sections.profile, Version: 1.0)
French language pack (confluence.languages.fr_FR, Version: 1.2)
Admin Sections (confluence.sections.admin, Version: 1.0)
Scaffolding Macros (org.randombits.confluence.scaffolding, Version: 1.4.18)
Navigation Plugin (com.pentec.confluence.navigation, Version: 1.11)
Table of Contents Macros (org.randombits.confluence.toc, Version: 1.4.7)
Space Pages Sections (confluence.sections.space.pages, Version: 1.0)
Voting Macros (com.nearinfinity.confluence.macros.vote, Version: 1.2)
Site Builder Theme (com.adaptavist.confluence.themes.sitebuilder, Version: 1.6)
News Tabs (confluence.sections.news, Version: 1.0)
Space Advanced Sections (confluence.sections.space.advanced, Version: 1.0)
Attachments Macros (confluence.extra.attachments, Version: 1.3)
IM Presence Macros (confluence.extra.impresence, Version: 0.1)
Footnote Macros (com.adaptavist.confluence.footnoteMacros, Version: 1.1.2)
Space Actions Sections (confluence.sections.space.actions, Version: 1.0)
Task List Macros (confluence.extra.tasklist, Version: 1.3)
Redirection Macros (org.randombits.confluence.redirection, Version: 1.4.4)
New Code Macro (confluence.ext.code, Version: 1.0.3)
Space Labels Sections (confluence.sections.space.labels, Version: 1.0)
Dynamic Task List Macros (confluence.extra.dynamictasklist, Version: 1.3)
Core Extractors (confluence.extractors.core, Version: 1.4)
Composition Plugin (org.randombits.confluence.composition, Version: 2.2)
Compatibility Macros (confluence.macros.compatibility, Version: 1.3)
Page Tabs (confluence.sections.page, Version: 1.0)
Page Tree (bnpparibas.confluence.pagetree, Version: 1.3)
Core Listeners (confluence.listeners.core, Version: 1.3)
Dashboard Macros (confluence.macros.dashboard, Version: 1.3)
Linking Plugin (org.randombits.confluence.linking, Version: 2.2.1)
Live Search Macros (confluence.extra.livesearch, Version: 1.3)
Flash Plugin (org.swift.confluence.flash, Version: 3.0)
JIRA Macros (confluence.extra.jira, Version: 1.4)
Layout Macros (confluence.extra.layout, Version: 0.1)
Reporting Plugin (org.randombits.confluence.reporting, Version: 1.0.2)
German language pack (confluence.languages.de_DE, Version: 1.0)
Russian language pack (confluence.languages.ru_RU, Version: 1.0)
United Status English language pack (confluence.languages.en_US, Version: 1.2)
Portuguese language pack (confluence.languages.pt_BR, Version: 1.0)
Tabular Metadata (confluence.extra.masterdetail, Version: 1.0)
Space Admin Sections (confluence.sections.space.admin, Version: 1.0)
Calendar Plugin (confluence.extra.calendar, Version: 2.1.13)
Confluence Repository Client (confluence.repository.client, Version: 1.2)
Advanced Macros (confluence.macros.advanced, Version: 1.3)
IM Presence NG Plugin (confluence.extra.impresence2, Version: 2.0)
HTML Plugin (org.swift.confluence.html, Version: 3.0.1)
Edit Profile Sections (confluence.sections.profile.edit, Version: 1.0)
Visibility Macros (org.randombits.visiblity, Version: 1.4.4)
Attachment Extractors (confluence.extractors.attachments, Version: 1.4)
Left Navigation Theme (com.atlassian.confluence.themes.leftnavigation, Version: 1.0)
Create Page Macro (com.adaptavist.confluence.createpage, Version: 1.0)
Zones Plugin (com.atlassian.confluence.contrib.zones, Version: 1.1)
Space Item Tabs (confluence.sections.space, Version: 1.0)
Code Macro (confluence.macros.code, Version: 1.4)
Multi Excerpt (biz.artemissoftware.confluence.multiexcerpt.MultiExcerptMacro, Version: 1.1)
Request</p>

<p>Information:
URL: <a href="http://framework.zend.com/wiki/500page.jsp">http://framework.zend.com/wiki/500page.jsp</a>
- Scheme: http
- Server: framework.zend.com
- Port: 80
- URI: /wiki/500page.jsp
- - Context Path: /wiki
- - Servlet Path: /500page.jsp
- - Path Info: null
- - Query String: urlIdentifier=iVc</p>

<p>Attributes:
- javax.servlet.forward.request_uri : /wiki/pages/tinyurl.action
- javax.servlet.forward.context_path : /wiki
- javax.servlet.forward.servlet_path : /pages/tinyurl.action
- javax.servlet.forward.path_info : /500page.jsp
- javax.servlet.forward.query_string : urlIdentifier=iVc
- javax.servlet.error.message :
- javax.servlet.error.exception : java.lang.IllegalStateException
- os_securityfilter_already_filtered : true
- com.atlassian.johnson.filters.JohnsonFilter_already_filtered : true
- javax.servlet.error.request_uri : /wiki/pages/tinyurl.action
- javax.servlet.error.status_code : 500
- __sitemesh__filterapplied : true
- javax.servlet.error.servlet_name : action
- webwork.valueStack : com.opensymphony.xwork.util.OgnlValueStack@bca50e
- atlassian.core.seraph.original.url : /pages/tinyurl.action?urlIdentifier=iVc
- loginfilter.already.filtered : true
- javax.servlet.jsp.jspException : java.lang.IllegalStateException
- sessioninview.FILTERED : true
- com.atlassian.core.filters.gzip.GzipFilter_already_filtered : true</p>

<p>Parameters:
- urlIdentifier = iVc
Confluence User:
- anonymous</p>

<p>Logging:
0 log statements generated by this request. {quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-04-17T09:11:56.000+0000</p> 
        <div class="body">
            <p>Already resolved with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=9117">SVN r9117</a>. The website should be updated with a new build of the documentation by no later than the next release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T14:04:28.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:06.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

