<h2>ZF-3129: Automatic quoting for Zend_Db_Table::delete</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2008-04-17T10:26:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-19T06:11:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3074">ZF-3074</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11242/ZendDbTable_Delete_AutoQuote.patch">ZendDbTable_Delete_AutoQuote.patch</a></li>
            <li><a href="/issues/secure/attachment/11241/ZendDbTable_Delete_AutoQuote.patch">ZendDbTable_Delete_AutoQuote.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I was always very unhappy about how ugly quoting with Zend_db is. See this "simple" delete for example:</p>

<pre class="highlight"><code>
$myModel-&gt;delete(Zend_Db_Table::getDefaultAdapter()-&gt;quoteInto('foo = ?', $foo)
                 . ' AND '
                 . Zend_Db_Table::getDefaultAdapter()-&gt;quoteInto('bar = ?', $bar));
</code></pre>

<p>I have now written a patch which solves this problem. With this patch, this horrible long line can look like this:</p>

<pre class="highlight"><code>
$myModel-&gt;delete('foo = ? AND bar = ?', $foo, $bar);
</code></pre>

<p>Any comments or improvements on this are welcome.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2008-04-17T10:48:36.000+0000</p> 
        <div class="body">
            <p>Ignore the second patch, obviously I cannot delete wrong attachements. The patch #1 is the right one.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-04-17T12:16:50.000+0000</p> 
        <div class="body">
            <p>I agree, (if I remember) : delete() is the only method provided by Zend_Db_Table that doesn't escape automatically the parameters it is passed.
That seems nonsense, but perhaps there is a good reason ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2008-04-17T17:48:04.000+0000</p> 
        <div class="body">
            <p>Well I can't see any, at least not in this implementation. When there are no additional paremeters given, any question mark in the $where clause is ignored, so it will all stay backward compatible.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jason Eisenmenger (jasoneisen) on 2008-04-17T18:44:00.000+0000</p> 
        <div class="body">
            <p>For the sake of uniformity I would suggest passing the second arg as an array.  IIRC $db-&gt;query() works this way.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:20:28.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by James Dempster (letssurf) on 2008-05-26T00:50:29.000+0000</p> 
        <div class="body">
            <p>It would certainly make using delete easier.</p>

<p>I think it would be better to make it...</p>

<pre class="highlight"><code>
$myModel-&gt;delete('foo = ? AND bar = ?', array($foo, $bar));
</code></pre>

<p>Just in case we would ever want to add a third argument.
Also it make's it easy to pass a list of elements to bind.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2008-07-28T10:00:30.000+0000</p> 
        <div class="body">
            <p>An update from my side, Zend_Db_Table::update() should also have that quoting functionallity.
By the way another nice thing would be, if you could also supply a Zend_Db_Select() for both update() and delete() method for more complex operations.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2009-01-06T14:29:56.000+0000</p> 
        <div class="body">
            <p>This issue has gone unaddressed for too long. I'm re-assigning to Ralph for re-evaluation and categorization.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andy Thompson (at465) on 2009-07-30T13:24:55.000+0000</p> 
        <div class="body">
            <p>I wouldn't recommend doing this as a variable number of arguments. It makes calling the function when you have an array of bind parameters much harder. See #ZF-3074 for an alternate way, just as James suggested, including patch and tests, along with Zend_Db_Table implementations as well.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2010-07-30T06:51:08.000+0000</p> 
        <div class="body">
            <p>Just taking out the "Fixed Version".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-07-30T07:52:39.000+0000</p> 
        <div class="body">
            <p>Why can't you use the where format that is expected (by Zend_Db_Adapter_Abstract in update and delete):</p>

<pre class="highlight"><code>
$model-&gt;delete(array('foo = ?' =&gt; $foo, 'bar = ?' =&gt; $bar));
</code></pre>

<p>Seems like this is a non issue, if the issue is about automatic quoting.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jason Eisenmenger (jasoneisen) on 2010-07-30T07:59:15.000+0000</p> 
        <div class="body">
            <p>This issue has been tossed from one "fix version" to the next for 2.5 years.  Does this even still apply?  If so, I still hold firm on my previous comment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-11-19T06:09:40.000+0000</p> 
        <div class="body">
            <p>linking related issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2010-11-19T06:11:32.000+0000</p> 
        <div class="body">
            <p>I'm closing this one, as we have discussed this a few times, and there is a solution to this problem available already, it simply is not the one suggested. As mentioned in ralphs previous comment, this notation will allow bindings for where clauses on update / delete calls.</p>

<pre class="highlight"><code>
$db-&gt;update('table', $data, array('foo  = ?' =&gt; $bar, 'baz = ?' =&gt; $bat));
</code></pre>

<pre class="highlight"><code>
$db-&gt;delete('table', array('foo  = ?' =&gt; $bar, 'baz = ?' =&gt; $bat));
</code></pre>

<p>There is no point keeping this open for another 2 years!</p>

        </div>
    </div>
    </div>

