<h2>ZF-3308: exception when Zend_Auth::getInstance()-&gt;setStorage(new My_Auth_Storage_CustomStorage()); is called more than one time</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-05-22T05:16:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-12-02T02:37:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Didier Maurer (ploum)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think there are some "side effects" I don't understand (currently) which are setting
self::$_destroyed of Zend_Session at something else than a boolean.</p>

<p>I posted on Nabble's forum :
<a href="http://www.nabble.com/Zend_Session-coupled-with-Zend_Auth-throws-an-exception-in-ZF-%3E1.0.3-td17364322.html#a17401565">http://nabble.com/Zend_Session-coupled-with-Zend_A…</a></p>

<p>So, I'm not a pretty good developer, but it could be nice to add some code du Zend_Session, in the start function, at the beginning:
if (! is_bool(self::$_destroyed) &amp;&amp; !empty(self::$_destroyed) ) {
            require_once 'Zend/Session/Exception.php';
            throw new Zend_Session_Exception('The session is set as destroyed with the value "'.self::$_destroyed.'" but has not been explicitly destroyed during this request.');
}
//the code below already exists, I've just added the '===true'<br />
if (self::$_sessionStarted &amp;&amp; self::$_destroyed===true) {
            require_once 'Zend/Session/Exception.php';
            throw new Zend_Session_Exception('The session was explicitly destroyed during this request, attempting to re-start is not allowed.');
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-01T13:28:13.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-01-11T20:24:49.000+0000</p> 
        <div class="body">
            <p>Is this sill and issue?  Also, if so, what is My_Auth_Storage_CustomStorage() doing?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-12-02T02:37:01.000+0000</p> 
        <div class="body">
            <p>Closing due to lack of response from origin poster.</p>

        </div>
    </div>
    </div>

