<h2>ZF-3263: option in a select gets automatically translated in a fom while this is not desired</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-05-15T01:57:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-08-04T07:11:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bart McLeod (mcleod@spaceweb.nl)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you set MultiSelectOptions on a Zend_Form_Element_Select AND you have a translator on the form, then values will be translated if a translation happens to be available.</p>

<p>Concrete example:
My form has a <em>code</em> field with a label <em>code</em>. This label is translated in Dutch as <em>code tbv. van vertaling</em>. That is the intended behavior. The translation is performed by the form's translator.</p>

<p>If someone enters a valid code, named <strong>code</strong> the value gets translated if displayed in a MultiSelect. So then you get</p>

<pre class="highlight"><code> This is obviously not the desired behavior, since the user of the form will want to select the code he entered and not the arbitrary translation of a label. This bug appears with any value for which there is a translation in the language file. 

If I would add the option array('bogus' =&gt; 'save') this would yield </code></pre>

<p><em>Opslaan</em> is Dutch for <em>save</em> and it is present in the Dutch language file that is available to the translator.</p>

<p>This applies to the version I just checked out of svn. I suppose that is 1.5.1.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-01T15:33:48.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-04T07:11:53.000+0000</p> 
        <div class="body">
            <p>In this case, I'd have to recommend that you disable the translator for this particular element (use the setDisableTranslator() method and/or 'disableTranslator' configuration option). We cannot and will not support allowing translations selectively on multi-option element options.</p>

        </div>
    </div>
    </div>

