<h2>ZF-3647: Zend_Rest_Client_Result::getStatus() incorrectly assumes $this-&gt;_sxml is an object</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-14T21:05:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3705">ZF-3705</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><em>note</em> Consider this post Public Domain.</p>

<p>line 43 of Rest/Client/Result.php, within __construct():
$this-&gt;_sxml = simplexml_load_string($data);</p>

<p>If the $data is malformed or invalid xml, $this-&gt;_sxml can contain (bool) False.</p>

<p>line 147 of Rest/Client/Result.php, within getStatus():
$status = $this-&gt;_sxml-&gt;xpath('//status/text()');</p>

<p>Since $this-&gt;_sxml is (bool) False, it breaks.</p>

<p>Insert at line 147:
if ($this-&gt;_sxml === false) return False;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dave Hall (skwashd) on 2008-07-25T16:26:50.000+0000</p> 
        <div class="body">
            <p>Similar issue reported in ZF-3705</p>

<p>I hope this gets fixed in 1.6 as we can not guarantee that a remote service will always serve up valid xml - although it should</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-11-07T04:28:49.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk. Implementation is using a simple error handler for the Xml parsing to show a specific error message.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:10.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

