<h2>ZF-3371: Label decorator's setTag() should cast empty values as null</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-02T23:10:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-24T09:23:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.3 (28/Jul/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, Zend_Form_Decorator_Label::setTag() casts all values passed to string. However, empty values, such as false, null, or '' should cast the value to null, thus allowing the ability to disable the tag surrounding a label.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-07-24T09:23:09.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.5 and 1.6 release branches.</p>

        </div>
    </div>
    </div>

