<h2>ZF-3097: Create new route for multilanguage sites</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-04-11T07:39:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-11T16:29:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3223">ZF-3223</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>An oft-used URL pattern for multi-lingual sites is to use the form '/:lang/...'. Currently, however, this is a difficult routing schema to achieve if you want to leave the flexibility to create a conventional modular site.</p>

<p>The suggestion is to create a route that extends the current Module route, and which takes an argument of a default language to use:</p>

<pre class="highlight"><code>
$router-&gt;addRoute('default', new Zend_Controller_Router_Route_Multilingual('de')); // default language is German
</code></pre>

<p>This would give such routes first-class support in the ZF MVC.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-04T10:24:55.000+0000</p> 
        <div class="body">
            <p>Postponing to 1.7.0; Martel and DASPRiD are working on a solution, part of which is included in 1.6, but the rest of which will happen for 1.7.0. At that time, we can easily add language-based routes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2008-10-18T17:44:36.000+0000</p> 
        <div class="body">
            <p>I'm only responsible for the config- and hostname-part. Martel is the maintainer of the actual partial path chaining. As he is currently quite busy, I don't think that partial path chaining will make it into 1.7. Even 1.8 isn't really clear.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-05T11:11:47.000+0000</p> 
        <div class="body">
            <p>Assigning to Ben; this is addressed with chained routes in 1.7.0, IIRC.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-04-18T13:50:07.000+0000</p> 
        <div class="body">
            <p>Partial path route implemented in 1.8.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thorsten Ruf (saphir2k) on 2009-05-11T15:05:12.000+0000</p> 
        <div class="body">
            <p>Can anybody  of the participants explain, how to solve the requirements of a default multilanguage route? I can't see an solution using chained routes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-05-11T16:29:34.000+0000</p> 
        <div class="body">
            <p>You simply take a standard route ":language", and all your other routes. Then you say for example</p>

<pre class="highlight"><code>
$languageRoute = new Zend_Controller_Router_Route(':language', array('language' =&gt; 'de');
$blogRoute = new Zend_Controller_Router_Route_Static('blog');
$blogRoute = $languageRoute-&gt;chain($blogRoute);
$router-&gt;addRoute($blogRoute);
</code></pre>

<p>For more examples, see documentation or ask in #zftalk on chat.freenode.org.</p>

        </div>
    </div>
    </div>

