<h2>ZF-3779: Zend_Locale : some methods accept object or string and are not properly coded</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-28T08:46:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Locale's constructor docblock says</p>

<pre class="highlight"><code>
@param  string $locale (Optional) Locale for parsing input
</code></pre>

<p>The constructor looks for a string, but also looks for a Zend_Locale object to call its toString() method. The docblock should reflect that fact.</p>

<p>Same (revert) for the setDefault() method, docblock says</p>

<pre class="highlight"><code>
@param  string|Zend_Locale $locale Locale to set
</code></pre>

<p>But this time, the method doesn't accept a Zend_Locale object as param, it should ( calling its toString() method).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-07-28T09:36:05.000+0000</p> 
        <div class="body">
            <p>Just because the Docblock is wrong, you can not say that the complete class is coded wrong :-)
I think this is a hard word ;-)</p>

<p>Related to your second example you are wrong.
Looking at the code you can see that the locale is casted to a string which does exactly the same as calling toString but is a little more performant.</p>

<p>I will correct the docblock.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-07-28T09:48:11.000+0000</p> 
        <div class="body">
            <p>I did not say the complete class is wrong, perhaps my english sentence meant that, so I apologyze :-D</p>

<p>For my second example, I'm sorry I'm right, I'm really talking about setDefault() method, not the setLocale() method ( whitch effectively casts to string like you say )</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-07-28T11:47:43.000+0000</p> 
        <div class="body">
            <p>Fixed with r10510</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:07.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

