<h2>ZF-3603: testAddFunctionMultiple(Zend_Soap_AutoDiscoverTest) unit tests error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-07-08T09:23:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-08T11:19:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Client</li>
            <li>Zend_Soap_Server</li>
            <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is unit tests error with the following diagnostic:</p>

<p>{panel}
7) testAddFunctionMultiple(Zend_Soap_AutoDiscoverTest)
Non-static method DOMDocument::loadXML() should not be called statically, assuming $this from incompatible context
/home/cawa/ZendFramework/trunk/library/Zend/Soap/Wsdl.php:89
/home/cawa/ZendFramework/trunk/library/Zend/Soap/AutoDiscover.php:140
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-07-08T11:19:39.000+0000</p> 
        <div class="body">
            <p>Fixed.</p>

        </div>
    </div>
    </div>

