<h2>ZF-3323: Zend_View_Helper_Doctype should be set in bootstrap</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-05-25T13:07:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:38:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Joó Ádám (ceriak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Joó Ádám (ceriak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Doctype should be set in bootstrap, however the manual says the layout script, in which case view scripts won't know about it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Joó Ádám (ceriak) on 2008-05-26T03:10:38.000+0000</p> 
        <div class="body">
            <p>Fixed with revision 9531.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T20:36:41.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:38:57.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

