<h2>ZF-3485: Zend_Db_Table_Select with join fails</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-19T18:35:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-19T12:11:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2546">ZF-2546</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Because of the problem described in ZF-2546, joins will fail on a Zend_Db_Table_Select:</p>

<pre class="highlight"><code>$categoryTable = new CategoryTable(array(
                                       'db'      =&gt; 'db',
                                       'name'    =&gt; 'category',
                                       'primary' =&gt; 'id'));
// Get categories belonging to a product--
// A many-to-many relationship
$select = $categoryTable-&gt;select()
    -&gt;join('category_product',
           'category_product.category_id = category.id',
           array())
    -&gt;where('category_product.product_id=?', 123);

echo "\$select: ", $select, "\n";
// SELECT `category`.* FROM `category_product`
//  INNER JOIN `category` WHERE (category_product.product_id='123')
// WRONG:
//   1) Incorrect table in 'FROM'
//   2) Missing 'ON' clause in 'INNER JOIN'

// The workaround:
// This time, include a from()
$select = $categoryTable-&gt;select()
    -&gt;from('category')
    -&gt;join('category_product',
           'category_product.category_id = category.id',
           array())
    -&gt;where('category_product.product_id=?', 123);

echo "\$select: ", $select, "\n";
// SELECT `category`.* FROM `category`
//  INNER JOIN `category_product` ON category_product.category_id=category.id
//  WHERE (category_product.product_id='123')
// *CORRECT*
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-05-19T12:11:51.000+0000</p> 
        <div class="body">
            <p>This was fixed in part by the feature added in ZF-2798.</p>

<p>To make your join queries work, use this logic:</p>

<p>$table-&gt;select(Zend_Db_Table_Abstract::SELECT_WITH_FROM_PART)-&gt;setIntegrityCheck(false);</p>

<p>The documentation was also updated.</p>

        </div>
    </div>
    </div>

