<h2>ZF-3275: WSDL Accessor documentation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2008-05-16T09:53:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-23T03:23:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2969">ZF-2969</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>WSDL Accessor documentation</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-06-19T07:53:49.000+0000</p> 
        <div class="body">
            <p>See ZF-2969 FishEye entry for the initial svn commit.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-06-23T03:23:12.000+0000</p> 
        <div class="body">
            <p>Finished</p>

        </div>
    </div>
    </div>

