<h2>ZF-3642: Wrong count of executed queries</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-14T02:23:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T03:56:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.6 (24/Nov/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Profiler</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11390/archive_bench.php">archive_bench.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Set up a small benchmark to check performance between InnoDB and ARCHIVE storage engine of mysql. Used <a href="http://framework.zend.com/manual/en/zend.db.profiler.html#zend.db.profiler.using">example</a> from manual to output results. Here the results:</p>

<pre class="highlight"><code>             Executed: 15 queries in 0.59294509887695 seconds
 Average query length: 0.039529673258464 seconds
   Queries per second: 25.297451700689
 Longest query length: 0.28680014610291
        Longest query: SELECT * FROM history LIMIT 50000</code></pre>

<pre class="highlight"><code>             Executed: 14 queries in 1.0089721679688 seconds
 Average query length: 0.072069440569196 seconds
   Queries per second: 13.875506623919
 Longest query length: 0.48813700675964
        Longest query: SELECT * FROM history_072008 LIMIT 50000</code></pre>

<p>There you can see that the first result contains 15 queries, the second result only 14. There should be only 14, so I think this is because of an initial sql query that will be executed before the first application based query will be executed. So I am forced to execute one senseless query to get correct count of queries.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2008-07-14T02:25:00.000+0000</p> 
        <div class="body">
            <p>Attached benchmark (archive_bench.php).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2008-07-14T02:29:21.000+0000</p> 
        <div class="body">
            <p>Oh sorry, I´ve attached a file where I already "fixed" my results. Please ignore lines 13 and 14.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-11-20T03:52:23.000+0000</p> 
        <div class="body">
            <p>If you invert your tables, it's the same.</p>

<p>The first count include the 'connect' query. This query is of course erased by your lines 13 &amp; 14.</p>

<p>Try this to see:</p>

<pre class="highlight"><code>
    foreach ($oProfiler-&gt;getQueryProfiles() as $oQuery)
    {
        if ($oQuery-&gt;getElapsedSecs() &gt; $iLongestTime)
        {
            $iLongestTime  = $oQuery-&gt;getElapsedSecs();
            $iLongestQuery = $oQuery-&gt;getQuery();
        }
        echo $oQuery-&gt;getQuery() . "\n";
    }
</code></pre>

<p>My result with your code (on very small table):</p>

<pre class="highlight"><code>
             Executed: 15 queries in 0.0053527355194092 seconds
 Average query length: 0.00035684903462728 seconds
   Queries per second: 2802.3054652354
 Longest query length: 0.0035429000854492
        Longest query: connect

             Executed: 14 queries in 2.0547692775726 seconds
 Average query length: 0.14676923411233 seconds
   Queries per second: 6.8134170355801
 Longest query length: 0.2819390296936
        Longest query: SELECT * FROM tableau_planning LIMIT 7500
</code></pre>

<p>Closed as 'not an issue'</p>

        </div>
    </div>
    </div>

