<h2>ZF-3996: Helper DocType not found</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-19T05:24:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-08-19T09:55:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Radek Siman (radius)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3997">ZF-3997</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On case sensitive systems there is a problem with loading DocType helper. The problem can be quickly fixed by renaming Doctype.php -&gt; DocType.php. Please pay the attention to the change of letter "t" -&gt; "T" inside the filename.</p>

<p>Uncaught exception 'Zend_View_Exception' with message 'helper 'DocType' not found in path' in '/www/iradius/time/application/Zend/View/Abstract.php:1004
Stack trace:</p>

<h1>0 /www/iradius/time/application/Zend/View/Abstract.php(497): Zend_View_Abstract-&gt;_loadClass('helper', 'DocType')</h1>

<h1>1 /www/iradius/time/application/Zend/View/Abstract.php(294): Zend_View_Abstract-&gt;getHelper('docType')</h1>

<h1>2 [internal function]: Zend_View_Abstract-&gt;__call('docType', Array)</h1>

<h1>3 /www/iradius/time/application/views/scripts/login.phtml(1): Zend_View-&gt;docType('XHTML1_STRICT')</h1>

<h1>4 /www/iradius/time/application/Zend/View.php(46): include('/data/web/virtu...')</h1>

<h1>5 /www/iradius/time/application/Zend/View/Abstract.php(769): Zend_View-&gt;_run('../application/...')</h1>

<h1>6 /www/iradius/time/application/Zend/Layout.php(729): Zend_View_Abs in /www/iradius/time/application/Zend/View/Abstract.php on line 1004</h1>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Radek Siman (radius) on 2008-08-19T05:55:15.000+0000</p> 
        <div class="body">
            <p>Unfortunately I have mistyped one command. Please ignore this bug, it was my fault:
&lt;?php echo $this-&gt;doctype('XHTML1_STRICT'); ?&gt;
vs.
&lt;?php echo $this-&gt;docType('XHTML1_STRICT'); ?&gt;</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-19T09:54:27.000+0000</p> 
        <div class="body">
            <p>The helper is called 'doctype', not 'docType' -- do not capitalize the 't' in 'doctype'.</p>

        </div>
    </div>
    </div>

