<h2>ZF-3314: Create consistences to test before invoking array_key_exists on Adapter.php Line 398</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-05-22T22:53:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-05-24T13:41:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramses Paiva (rpaiva)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>To avoid the warning below, it's needed to create consistences testing if the $messageId really is an integer or a string.</p>

<p>Warning: array_key_exists(): The first argument should be either a string or an integer in \Zend\Translate\Adapter.php on line 398</p>

<p>Maybe using is_string() and is_int() PHP functions like below:</p>

<pre class="highlight"><code>
    /**
     * Translates the given string
     * returns the translation
     *
     * @param  string              $messageId  Translation string
     * @param  string|Zend_Locale  $locale     OPTIONAL Locale/Language to use, identical with locale identifier,
     *                                         see Zend_Locale for more information
     * @return string
     */
    public function translate($messageId, $locale = null)
    {
        if ($locale === null) {
            $locale = $this-&gt;_options['locale'];
        }

        if (!$locale = Zend_Locale::isLocale($locale)) {
            // language does not exist, return original string
            return $messageId;
        }

        if ((is_array($this-&gt;_translate) and array_key_exists($locale, $this-&gt;_translate)) and
            (is_string($messageId) or is_int($messageId)) and
            (is_array($this-&gt;_translate[$locale]) and array_key_exists($messageId, $this-&gt;_translate[$locale]))) {
            // return original translation
            return $this-&gt;_translate[$locale][$messageId];
        } else if (strlen($locale) != 2) {
            // faster than creating a new locale and separate the leading part
            $locale = substr($locale, 0, -strlen(strrchr($locale, '_')));

            if ((is_array($this-&gt;_translate) and array_key_exists($locale, $this-&gt;_translate)) and
                (is_string($messageId) or is_int($messageId)) and
                (is_array($this-&gt;_translate[$locale]) and array_key_exists($messageId, $this-&gt;_translate[$locale]))) {
                // return regionless translation (en_US -&gt; en)
                return $this-&gt;_translate[$locale][$messageId];
            }
        }

        // no translation found, return original
        return $messageId;
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramses Paiva (rpaiva) on 2008-05-22T22:56:42.000+0000</p> 
        <div class="body">
            <p>My suggestion would implement the code like this:</p>

<pre><code>/**
 * Translates the given string
 * returns the translation
 *
 * @param  string              $messageId  Translation string
 * @param  string|Zend_Locale  $locale     OPTIONAL Locale/Language to use, identical with locale identifier,
 *                                         see Zend_Locale for more information
 * @return string
 */
public function translate($messageId, $locale = null)
{
    if ($locale === null) {
        $locale = $this-&gt;_options['locale'];
    }

    if (!$locale = Zend_Locale::isLocale($locale)) {
        // language does not exist, return original string
        return $messageId;
    }

    if ((is_array($this-&gt;_translate) and array_key_exists($locale, $this-&gt;_translate)) and
        (is_string($messageId) or is_int($messageId)) and
        (is_array($this-&gt;_translate[$locale]) and array_key_exists($messageId, $this-&gt;_translate[$locale]))) {
        // return original translation
        return $this-&gt;_translate[$locale][$messageId];
    } else if (strlen($locale) != 2) {
        // faster than creating a new locale and separate the leading part
        $locale = substr($locale, 0, -strlen(strrchr($locale, '_')));

        if ((is_array($this-&gt;_translate) and array_key_exists($locale, $this-&gt;_translate)) and
            (is_string($messageId) or is_int($messageId)) and
            (is_array($this-&gt;_translate[$locale]) and array_key_exists($messageId, $this-&gt;_translate[$locale]))) {
            // return regionless translation (en_US -&gt; en)
            return $this-&gt;_translate[$locale][$messageId];
        }
    }

    // no translation found, return original
    return $messageId;
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-05-23T00:11:21.000+0000</p> 
        <div class="body">
            <p>This issue has already been fixed several months ago and was integrated within 1.5.2</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramses Paiva (rpaiva) on 2008-05-24T11:47:33.000+0000</p> 
        <div class="body">
            <p>Hi, Thomas! Yes, I just saw it. You're using is_array() to test the param's type.
But I still believe that would be better to use is_string() combined to is_int() to validate it, because you could receive other invalid types in the function that could be not an array type, like an object, for example.
Then you fix the param only for the valid types to be received on the next tests.
What about?</p>

<p>Here, an example:</p>

<pre class="highlight"><code>
if (!(is_string($messageId) or !is_int($messageId))) {
    return $messageId;
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-05-24T13:41:51.000+0000</p> 
        <div class="body">
            <p>Still no issue...</p>

<p>When you give an issue the __toString method will automatically be called.
This is better than involving several other checks.</p>

<p>You must have in mind that this is the base method for all translations and when you have a multilingual application you will have really much translations. And even with the two checks (which are useless in my eyes) you will still not have the expected output.</p>

<p>When you give a object you will get exactly this object returned as it's not translatable. So you will have problems anyway.</p>

<p>Translation itself MUST NOT RETURN EXCEPTIONS !!!
If anything goes wrong we MUST return the input as output which is done in case of an object. You will get the object returned.</p>

        </div>
    </div>
    </div>

