<h2>ZF-3520: Zend_Loader::loadFile() fails on PHP bug#45288  &quot;set_include_path() functionality broken&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-26T09:29:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-22T08:52:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>See: <a href="http://bugs.php.net/bug.php?id=45288">http://bugs.php.net/bug.php?id=45288</a></p>

<p>Zend_Loader::loadFile() cannot effectively use the $dirs argument in affected PHP versions (as of 2008/6/26: 5.1.2, 5.2.5-6), because the include_path state cannot be changed.</p>

<p>This method and argument is used throughout the Framework, including Zend_Controller_Dispatcher_Standard, rendering the MVC inflection useless.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-22T08:52:12.000+0000</p> 
        <div class="body">
            <p>This behavior was changed for 1.7.0; the previous include_path is cached using get_include_path(), allowing us to reset it following the include.</p>

        </div>
    </div>
    </div>

