<h2>ZF-3880: Zend_Form_Decorator_HtmlTag creates invalid XHTML</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-07T02:08:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-08T12:23:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Wahl (awahl)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form_Decorator_HtmlTag does not close single tags.</p>

<p></p>

<p>it should be</p>

<p></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Goran Juric (gog) on 2008-09-08T12:01:06.000+0000</p> 
        <div class="body">
            <p>It works for me.</p>

<p>Are you sure you told Zend_View to use XHTML in your Bootstrap, or somewhere else prior to the form rendering?</p>

<p>Try something like this in your Bootstrap:</p>

<p>$view = new Zend_View;
$view-&gt;doctype('XHTML1_STRICT');</p>

<p>If you don't tell the view to use XHTML tags it defaults to HTML.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-08T12:23:50.000+0000</p> 
        <div class="body">
            <p>As noted in another comment, ZF defaults to HTML4 compliance, not XHTML1. You must call $view-&gt;doctype('XHTML1_STRICT') (or one of the other XHTML constant strings) <em>prior</em> to rendering the form for XHTML compliance to be enabled.</p>

        </div>
    </div>
    </div>

