<h2>ZF-3450: LDAP won't work on a default Zend Core installation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-06-12T02:22:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-25T16:51:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ashley Kitson (akzincdig)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
            <li>Zend_Ldap</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The current documentation for Zend_Auth relating to LDAP and for Zend_Ldap both fail to mention that you need to have the ldap extension compiled into PHP.  The Zend Core distribution does not install ldap support.  According to the PHP guide at <a href="http://uk.php.net/manual/en/ldap.installation.php">http://uk.php.net/manual/en/ldap.installation.php</a> it needs to be compiled in.  This effectively makes ldap usage unavailable for Zend Core (and most standard php) installations.  At a minimum the documentation for Framework needs to mention this caveat.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-25T16:51:54.000+0000</p> 
        <div class="body">
            <p>This information is kept in the requirements appendix. I've added the dependency with r12847.</p>

        </div>
    </div>
    </div>

