<h2>ZF-3142: Zend_Form_Element_Text::isValid returns wrong value with NotEmpty validator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-18T03:37:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-07-09T14:37:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When assigning a NotEmpty validator to a Zend_Form_Element, the element's isValid method returns true with an empty value.</p>

<p>The workaround I found is to set the elements allowEmpty property to false by hand, because the default value is true.</p>

<pre class="highlight"><code>
&lt;?php
require_once 'Zend/Form/Element/Text.php';
require_once 'Zend/Validate/NotEmpty.php';
        
//element one, with NotEmpty validator and allowEmpty = true (default value)
$elementOne = new Zend_Form_Element_Text('emptyFieldOne');
$elementOne-&gt;addValidator(new Zend_Validate_NotEmpty());
$elementOne-&gt;isValid(''); // returns true
        
//element two, with NotEmpty validator and allowEmpty = false (assigned by hand)
$elementTwo = new Zend_Form_Element_Text('emptyFieldTwo');
$elementTwo-&gt;addValidator(new Zend_Validate_NotEmpty());
$elementTwo-&gt;setAllowEmpty(false);
        
$elementTwo-&gt;isValid(''); //returns false
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:16:14.000+0000</p> 
        <div class="body">
            <p>Please evaluate and categorize as necessary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-04-22T12:18:26.000+0000</p> 
        <div class="body">
            <p>If you do not mark the element as required, then the results you see are exactly as I would expect. When the element is not required and passed as empty, then no validators will be run unless you have marked allowEmpty as false.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Walter Treur (wtreur) on 2008-04-23T07:40:45.000+0000</p> 
        <div class="body">
            <p>I suppose you're right. I've tested this with another validator and was a little confused by the API Documentation</p>

<pre class="highlight"><code>$element = new Zend_Form_Element_Text('element1');
$element-&gt;addValidator(new Zend_Validate_StringLength(5, 10));
if($element-&gt;isValid('')) {
    echo "Element is valid";
} else {
    echo "Element is invalid";
}</code></pre>

<p>The above example results in "Element is valid"</p>

<p>I was confused because the API doc on Zend_Form_Element::setAllowEmpty() states:
??When the allow empty flag is enabled and the required flag is false, the element will validate with empty values??
So I thought the validators would run and $element-&gt;isValid('') would return false when allowEmpty = true and required=false (wich are the default values), but they don't as the example showed.</p>

<p>In any case, thanks for your patience</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kyle (rekamso) on 2008-07-09T14:37:03.000+0000</p> 
        <div class="body">
            <p>It may be worth adding a note about this to the documentation.</p>

<p>The only way to set the text for NotEmpty is to add it yourself, and to get the validator to run after adding it, you have to call setAllowEmpty properly.</p>

        </div>
    </div>
    </div>

