<h2>ZF-3634: Fisheye does not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-07-12T23:54:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-08-24T14:23:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jason Qi (jason qi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As a translator, I need fisheye system to check the document version and differences in docs.</p>

<p>I noticed that it did work for a couple of weeks, can anyone fix this problem?</p>

<p>Many thanks.</p>

<p>Jason.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-08-24T14:23:14.000+0000</p> 
        <div class="body">
            <p>Already fixed in the past.
Fisheye works as I use it myself as translator.</p>

        </div>
    </div>
    </div>

