<h2>ZF-3417: protected magic functions</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-06-09T04:34:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Daniel Hartmann (danielmitd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>current php 5.3 snapshot throws the following fatal errors:</p>

<p>[09-Jun-2008 14:26:08] PHP Fatal error:  The magic method __get() must have public visibility and can not be static in /usr/local/lib/php/Zend/Session/Namespace.php on line 247
[09-Jun-2008 14:27:14] PHP Fatal error:  The magic method __set() must have public visibility and can not be static in /usr/local/lib/php/Zend/Session/Namespace.php on line 269
[09-Jun-2008 14:27:39] PHP Fatal error:  The magic method __isset() must have public visibility and can not be static in /usr/local/lib/php/Zend/Session/Namespace.php on line 354
[09-Jun-2008 14:28:07] PHP Fatal error:  The magic method __isset() must have public visibility and can not be static in /usr/local/lib/php/Zend/Session/Namespace.php on line 354
[09-Jun-2008 14:28:33] PHP Fatal error:  The magic method __unset() must have public visibility and can not be static in /usr/local/lib/php/Zend/Session/Namespace.php on line 374
[09-Jun-2008 14:28:50] PHP Fatal error:  The magic method __isset() must have public visibility and can not be static in /usr/local/lib/php/Zend/Config.php on line 181
[09-Jun-2008 14:29:33] PHP Fatal error:  The magic method __unset() must have public visibility and can not be static in /usr/local/lib/php/Zend/Config.php on line 193</p>

<p>perhaps there are more of them</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Daniel Hartmann (danielmitd) on 2008-06-09T05:05:27.000+0000</p> 
        <div class="body">
            <p>an other one is located in:</p>

<p>PHP Fatal error:  The magic method __call() must have public visibility and can not be static in /usr/local/lib/php/Zend/Db/Select.php on line 1162</p>

<p>its a general issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-09T09:48:56.000+0000</p> 
        <div class="body">
            <p>Re-assigning to Matthew as he is more familiar with the PHP 5.3-related issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-06-12T10:10:33.000+0000</p> 
        <div class="body">
            <p>I'm wondering why did the PHPGroup take such a decision ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-06-16T08:57:17.000+0000</p> 
        <div class="body">
            <p>Julien -- I have no idea why; probably to be present a more "pure" implementation.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-06-16T08:58:24.000+0000</p> 
        <div class="body">
            <p>Stas corrected all places this occurred during the week of 9 June 2008.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-06-16T09:16:51.000+0000</p> 
        <div class="body">
            <p>That could help :
<a href="http://wiki.php.net/rfc/protectedlookup">http://wiki.php.net/rfc/protectedlookup</a>
<a href="http://marc.info/?l=php-internals&amp;m=121170592408361&amp;w=2">http://marc.info//…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:18.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

