<h2>ZF-3752: Change command line arguments for Blogger.php sample to exclude extraneous '--'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-24T22:20:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T14:54:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, the Blogger.php sample for Zend_Gdata lists the following as usage:</p>

<pre><code>php Blogger.php -- --user=[username] --pass=[password]
</code></pre>

<p>The extra -- is extraneous and doesn't follow Unix conventions, so should be removed:</p>

<pre><code>php Blogger.php --user=[username] --pass=[password]
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-07-24T22:43:10.000+0000</p> 
        <div class="body">
            <p>I have a changelist waiting on my server to fix this, pending resolution of CLA issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-09-06T09:02:33.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r11272.  demos/Zend/Ggata/Blogger.php .</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-09-06T14:37:11.000+0000</p> 
        <div class="body">
            <p>Looks good to me. Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-09-07T22:04:57.000+0000</p> 
        <div class="body">
            <p>Hi, Trevor. you are welcome ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:09:57.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

