<h2>ZF-3211: for doc and pdf documents</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-05-06T18:00:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-17T15:12:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>When we search any pdf or doc - does it give us both binery and text values of keyword or just text value of keyword</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-01T16:38:40.000+0000</p> 
        <div class="body">
            <p>Rob, is this an issue or a question?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Keckeis (thadafinser) on 2010-05-25T07:01:00.000+0000</p> 
        <div class="body">
            <p>I think this can be marked as resolved...</p>

        </div>
    </div>
    </div>

