<h2>ZF-3927: Read process: Enable the configuration of a &quot;max attachment size&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-08-11T12:21:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-19T08:28:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexandre Lemaire (saeven)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I've found on some customer machines, that email attachments read through Zend_Mail's mailbox reading features, that larger attachments quickly explode and bust the PHP max memory limit (php.ini) at Zend_Mime without any catchable error.  PHP simply "dies" with its "memory busted" error.</p>

<p>It would be handy, if we could specify an attachment size ceiling to prevent this type of behavior.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-18T01:20:40.000+0000</p> 
        <div class="body">
            <p>Hi, Alexandre.</p>

<p>It is necessary to be able change value of the <em>upload_max_filesize</em> and the <em>post_max_size</em> to satisfy your demand.</p>

<p>However, We can not change the values on PHP script because they are defined as <em>PHP_INI_PERDIR</em>.</p>

<p>But, you could use some HTML tags instead, I think;</p>

<pre class="highlight"><code>
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexandre Lemaire (saeven) on 2009-11-18T06:25:27.000+0000</p> 
        <div class="body">
            <p>I believe that the feedback may have been misunderstood.</p>

<p>This is to do with pre-detection of email object attachment size based on the information made available by Zend_Mail and downloaded mail headers, and has nothing to do with forms, their encoding, or limitations imposed by PHP's max allowable upload filesize.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-18T14:27:34.000+0000</p> 
        <div class="body">
            <p>Oh, I am sorry that I misunderstood it, Alexandre.</p>

<p>You might mean files that already exist on Web server when Zend_Mail runs.
Is it right?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michael Kliewe (mkliewe) on 2009-11-19T08:04:29.000+0000</p> 
        <div class="body">
            <p>I think the idea is to "protect" the script against such big mails.</p>

<p>Lets say we have a script that is reading mails and parsing them. The script works fine.
Then a person sends a mail to the mailbox that has a size of 100MB. Zend_Mail cannot detect this and tries to read that mail into memory for parsing mime parts and so on. But if memory usage of php is limited to 64MB, the script dies unexpectedly.</p>

<p>So the idea is to check the memory limit, and if Zend_Mail sees a Mail that is 100MB in size (by Content-Length header or via IMAP RFC822.SIZE), Zend_Mail should not receive this mail (because php memory limit would be reached and php would exit).</p>

<p>Alexandre would like to have a function or setting for that, e.g. 
$mail-&gt;setParseMaxMessageSize(50000000);
Zend_Mail_Storage_Imap::ParseMaxMessageSize = 50000000
so mails &gt; 50MB should not be parsed.</p>

<p>I don't know if this is possible, but it would be very nice.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nico Edtinger (nico) on 2009-11-19T08:28:35.000+0000</p> 
        <div class="body">
            <p>So do you mean Zend_Mail or Zend_Mail_Storage? In Zend_Mail your script controls, what's added as attachment ant it's easy to check before you do so. Thus I've changed the component of this issue.</p>

<p>If you have a Content-Length header you don't need anything new. Zend_Mail_Storage only fetches the headers and doesn't load the content or any part until you fetch them.</p>

<p>A different problem is reading a chunk that can't be parsed, because of memory limitations (as in splitting the message in its parts). Maildir and Mbox shouldn't have a problem as they both use Zend_Mail_[Message|Part]_File. In POP3 and IMAP we'd need to stop loading at a defined limit, which makes the storage class not usable anymore (it'd be stuck in the reading state).</p>

<p>The best thing to do is use more of the IMAP features, but keeping compatibility to the other storage classes in mind.</p>

        </div>
    </div>
    </div>

