<h2>ZF-3113: Make Zend_Db_Profiler optionaly able to use Zend_Log to log its stuff</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-04-15T10:37:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-31T09:09:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Profiler</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think that Zend_Db_Profiler should get some mechanisms to be added a Zend_Log component that could just log its work.</p>

<p>Some kind of $profiler-&gt;setLog(Zend_Log $log);
$profiler-&gt;enableLog()
$profiler-&gt;disableLog();</p>

<p>the $log element could then create its own Zend_Log_Formatter_Dbprofiler(), to choose what infos to log.</p>

<p>What do you think about that ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

