<h2>ZF-3176: Zend_Form_Element_Checkbox::isChecked expects a value it doesn't need</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-25T09:59:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-17T12:42:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Eddo Rotman (karnaf)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Eddo Rotman (karnaf)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form_Element_Checkbox::isChecked($flag) doesn't really need that flag or does anything with it</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Eddo Rotman (karnaf) on 2008-04-25T10:17:25.000+0000</p> 
        <div class="body">
            <p>Checked SVN and saw this was fixed already.  Only left to remove the comment from the function's phpDoc</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eddo Rotman (karnaf) on 2008-04-25T11:00:36.000+0000</p> 
        <div class="body">
            <p>Read the SVN code, saw that this was already fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-17T12:42:33.000+0000</p> 
        <div class="body">
            <p>Did you fix this with a commit? If so, please include the issue id in the commit log; it will automatically link to the commit in Fisheye from JIRA.</p>

        </div>
    </div>
    </div>

