<h2>ZF-3086: Zend_OpenId_Consumer doesn't properly handle delegation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-09T14:09:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dmitry Stogov (dmitry)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When you use the Zend_OpenId_Consumer class to authenticate against an OpenID URL that uses delegation, it always passes back the delegated identity instead of the original identity.</p>

<p>For example, if I delegate <a href="http://mysite.com">http://mysite.com</a> to <a href="http://myaccount.myopenid.com">http://myaccount.myopenid.com</a>, the Zend_OpenId_Consumer class will return <a href="http://myaccount.myopenid.com">http://myaccount.myopenid.com</a> as the identity instead of <a href="http://mysite.com">http://mysite.com</a>.</p>

<pre class="highlight"><code>
&lt;?php
require_once "Zend/OpenId/Consumer.php";
$consumer = new Zend_OpenId_Consumer();

// First call
$identifier = '<a href="http://mysite.com">http://mysite.com</a>';
$consumer-&gt;login($identifier);

// On return, call
$consumer-&gt;verify($_GET, $identifier);
echo $identifier;
    // Echoes <a href="http://myaccount.myopenid.com">http://myaccount.myopenid.com</a>
    // Instead of <a href="http://mysite.com">http://mysite.com</a>
?&gt;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Morrell (inxilpro) on 2008-04-09T14:10:14.000+0000</p> 
        <div class="body">
            <p>This also affects the OpenId adapter of Zend_Auth</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dmitry Stogov (dmitry) on 2008-04-10T08:43:11.000+0000</p> 
        <div class="body">
            <p>Fixed in SVN trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2008-04-21T13:51:34.000+0000</p> 
        <div class="body">
            <p>Marking as fixed for next minor release pending merge of changes to release-1.5 branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:03.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

