<h2>ZF-3539: Document the test() method in Zend_Cache</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-06-30T11:23:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-29T18:43:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Lukas Smith (lsmith)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jordan Ryan Moore (jordanryanmoore)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4577">ZF-4577</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Right now there is no API call to read the metadata, besides test(), which does not seem to be documented and I only found out it returns the mtime, while reading the source.</p>

<p>This makes it possible to implement a "fallback" solution. For example one can store an external feed in Zend_Cache. The lifetime is set to lets say 1 day. When trying to update the cache one can first check if the mtime is older than lets say 1 hour. If so an attempt is made to read the data from the original source. If that request fails, I can still fallback on the data in the cache for 1 day since the last request succeeded.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2008-07-05T05:43:10.000+0000</p> 
        <div class="body">
            <p>sure, you are right</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2009-07-17T11:03:34.000+0000</p> 
        <div class="body">
            <p>change Assignee because I'm inactive now</p>

        </div>
    </div>
    </div>

