<h2>ZF-3550: Missing params in requst with view_action_helper</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-07-01T23:39:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-18T07:15:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,
I'm using action helper in my view scripts (I realy like this one :-)).Last day I notticed that request in this "nested action" is missing some useful params 
(module/controller/action)</p>

<p>class SomeController{
.....
  nestedAction{
     $this-&gt;_request-&gt;getParam('controller') // return NULL
.
     $this-&gt;_request-&gt;getControllerName()  // return "some"
  }
......
}</p>

<p>VIEW:
$this-&gt;action('nested','some','default',array());</p>

<p>For consistency I think that both method should return same value.</p>

<p>Thanks for your hard work</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-10-22T17:03:48.000+0000</p> 
        <div class="body">
            <p>I disagree with you on that both functions should return the value as controller is not a param but way to tell the system what to do.  I think the system is functioning the way it should.</p>

        </div>
    </div>
    </div>

