<h2>ZF-3170: include_path problem</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-04-23T20:34:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-05-14T04:46:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2985">ZF-2985</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I just did an svn update and out of the blue the only thing I was seeing on my site was:
Action Helper by name ViewRenderer not found</p>

<p>After some checking i found this code in Zend_Loader:</p>

<pre class="highlight"><code>    /**
     * Returns TRUE if the $filename is readable, or FALSE otherwise.
     * This function uses the PHP include_path, where PHP's is_readable()
     * does not.
     *
     * @param string   $filename
     * @return boolean
     */
    public static function isReadable($filename)
    {
        if (!file_exists($filename) || !$fh = @fopen($filename, 'r', true)) {
            return false;
        }

        return true;
    }</code></pre>

<p>I fixed it to:
```
because if fopen can open the file, than it IS readable =&gt; return true</p>

<p>this way I got rid of the error mentioned above.</p>

<p>// edit: submited it too fast :D
// edit2: error appeared in trunk 9295:  * @version    $Id: Loader.php 9295 2008-04-23 15:31:51Z yoshida@zend.co.jp $</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-04-24T03:08:57.000+0000</p> 
        <div class="body">
            <p>We are on it ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-04-24T08:17:54.000+0000</p> 
        <div class="body">
            <p>Fixed in r9300 trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rafal Piekarski (ravbaker) on 2008-04-25T00:58:56.000+0000</p> 
        <div class="body">
            <p>But in my opinion this sollution is incomplete:</p>

<pre class="highlight"><code>
if (!file_exists($filename) &amp;&amp; !$fh = @fopen($filename, 'r', true)) {
</code></pre>

<p>So here is my sollution.</p>

<pre class="highlight"><code>
if (!file_exists($filename) || file_exists($filename) &amp;&amp; !$fh = @fopen($filename, 'r', true)) {
</code></pre>

<p>Brackets outside &amp;&amp; are optional.</p>

<p>What do you think?</p>

<p>Because I've tested it in my application and it works.</p>

        </div>
    </div>
    </div>

