<h2>ZF-3251: Add tidy decorator for Zend_Form</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-05-13T04:45:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-02-13T22:23:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Several users have requested a way to make the output of Zend_Form tidier. This can be accomplished relatively easily by creating a 'Tidy' decorator for Zend_Form that takes the content provided, and passes it to either DOM or ext/tidy in order to format it. This decorator should be entirely optional.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-05T12:52:08.000+0000</p> 
        <div class="body">
            <p>This should actually be a Zend_View filter.</p>

        </div>
    </div>
    </div>

