<h2>ZF-3491: Zend_Http_Client should auto-detect Authentication values from a Zend_Uri object.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-06-21T19:01:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-17T07:59:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Christer Edvartsen (cogo)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
            <li>Zend_Uri</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A Zend_Http_Client object can be passed a Zend_Uri object through it's setUri method, although this is not really promoted in the documentation. Often it is useful to 'build' a Uri using a Zend_Uri object rather than pass a string directly.</p>

<p>Although Zend_Uri does provide a facility for setting a Username/Password combination (presumably for HTTP authentication), this is not detected when the Zend_Uri object is passed in. Theoretically this would also therefore work for with strings formatted like '<a href="http://uri.com/">http://username:password@uri.com/</a>' since they are automatically converted to Zend_Uri objects anyway.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christer Edvartsen (cogo) on 2009-08-17T07:59:20.000+0000</p> 
        <div class="body">
            <p>Fixed in r17648. Added a line in the documentation and unit tests for the new feature as well. All tests pass.</p>

        </div>
    </div>
    </div>

