<h2>ZF-3312: CLONE -Module name mapping from URI to directory</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-05-22T17:42:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-05T11:48:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li> 1.5.2 (15/May/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3034">ZF-3034</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Not sure if case-sensitive comparison is an intentional behavior; if it is, would it make sense to add an extra argument to allow mapping the module name case-insensitively from the URI to the physical module directory on the file system?</p>

<pre class="highlight"><code>
$zcf = Zend_Controller_Front::getInstance();

$zcf-&gt;setParam('noViewRenderer', true);
$zcf-&gt;setParam('prefixDefaultModule', true);
$zcf-&gt;setModuleControllerDirectoryName('.');
$zcf-&gt;addModuleDirectory('/path/to/module/directory');
$zcf-&gt;dispatch();
</code></pre>

<pre class="highlight"><code>
module/
|-- default/
|   |-- ErrorController.php
|   `-- IndexController.php
`-- module1/
    `-- IndexController.php
</code></pre>

<p><a href="http://somewhere/module1">http://somewhere/module1</a> hits the IndexController in the module1 directory
<a href="http://somewhere/Module1">http://somewhere/Module1</a> hits the ErrorController in the default module directory</p>

<p>Some users type everything capitalized, and since MODULE1 !== module1 (I'm gussing isValidModule() returns false); the request doesn't go to the intended controller.</p>

<p>If this is an intentional behavior; what's the best way to overcome this?  Create a custom dispatcher, or perhaps this can be worked around by configuring the router?</p>

<p>Eric</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Eric Yao (sourceboy) on 2008-05-22T17:44:14.000+0000</p> 
        <div class="body">
            <p>isValidModule() now returns true; however,</p>

<p>It seems Zend_Controller_Dispatcher_Standard::_curDirectory gets a wrong value:
When tested with all caps:  Value is /path/to/the/default/module/directory  // wrong
When tested with all lower case:  Value is /path/to/the/correct/module/directory  // correct</p>

<p>When tested with all caps:  $dispatchDir in Zend_Controller_Dispatcher_Standard::isDispatchable() is NULL  // wrong
When tested with all lower case:  $dispatchDir in Zend_Controller_Dispatcher_Standard::isDispatchable() is /path/to/the/module/directory  // correct</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-05T11:47:43.000+0000</p> 
        <div class="body">
            <p>You can extend the dispatcher and router to achieve this functionality; we do not plan to support it directly, however.</p>

        </div>
    </div>
    </div>

