<h2>ZF-4872: Add core support for Google Data protocol version 2</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-11-07T19:09:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:09:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add core support for Google Data protocol version 2, including support for the final AtomPub specification as defined in RFC 5023.</p>

<p>Changes include:</p>

<ul><li>Support for the new 'GData-Version' HTTP header.</li>
<li>New namespaces for AtomPub (app) and OpenSearch (openSearch) in version 2.</li>
<li>Support for using ETags to implement optimistic concurrency (ETag headers and gd:etag XML elements are recognized, and later used to set 'If-Match' HTTP headers).</li>
<li>Support for setting arbitrary headers on most HTTP-bound operations.</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-11-10T13:04:52.000+0000</p> 
        <div class="body">
            <p>Marking as fixed for the 1.7 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:09:55.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

