<h2>ZF-4809: Zend_Validate_Ip detects 1.2.333 as valid IP</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-11-05T08:52:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-06T11:50:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Validate_Ip detects 1.2.333 as valid IP as this, in case of ip2long() IS a valid IP (1.2.1.77), but in case you want the user to enter a full IP this is an invalid IP.
A better check would be:
if(ip2long($valueString) === false || long2ip(ip2long($valueString)) !== $valueString)
as this checks that the specified IP is exactly the same as the one returend from long2ip().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-06T11:50:02.000+0000</p> 
        <div class="body">
            <p>Fixed with r12340</p>

        </div>
    </div>
    </div>

