<h2>ZF-4627: Updating playlist entries fails due to invalid atom:category</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-17T14:37:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Here is some code:</p>

<p>$playlistListEntry-&gt;title-&gt;setText('New Text'); 
$playlistListEntry-&gt;description-&gt;setText('New
Description');
$playlistListEntry-&gt;save();</p>

<p>It seems the client library is sending malformed atom:categories:</p>

<p>http://gdata.youtube.com/schemas/2007/…&gt;
http://schemas.google.com/g/2005#kind'/&gt;</p>

<p>The second is spurious and causes a 400 error. The first has the wrong term.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-11-05T15:07:06.000+0000</p> 
        <div class="body">
            <p>I can't reproduce this. If I have an authenticated client and do this on my first playlist:</p>

<p>$first-&gt;title-&gt;setText('Updated PL');
$first-&gt;description-&gt;setText('new desc');
$first-&gt;save();</p>

<p>The following XML gets generated:</p>

<p>www.w3.org/2005/Atom"&gt;
... [ snip ]
</p>

<p>and the response is a 200 OK. After the put, the categories are also correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-11-05T16:29:58.000+0000</p> 
        <div class="body">
            <p>Fixed by Ryan Boyd in r12155.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:07.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

