<h2>ZF-4743: Zend_Session is too aggressive about catching errors during session_start</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-29T14:05:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-19T11:12:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Session installs an error handler to catch any errors triggered by session_start, and then rethrows them as an exception if it caught any. However, it catches all errors (mask set to E_ALL)</p>

<p>This causes problems when session_start writes NOTICE level errors which probably do not signify a session_start problem.</p>

<p>I'd propose changing the set_error_handler call:</p>

<pre><code>    set_error_handler(array('Zend_Session_Exception', 'handleSessionStartError'), E_ALL);
</code></pre>

<p>to
        set_error_handler(array('Zend_Session_Exception', 'handleSessionStartError'), E_ALL &amp; ~E_NOTICE);</p>

<p>Not sure what version this is, but the RCS tags at the top say:</p>

<ul><li>@version    $Id: Session.php 5500 2007-06-29 14:39:50Z darby $</li>
<li>@since      Preview Release 0.2</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Till Klampaeckel (till) on 2009-05-02T11:12:05.000+0000</p> 
        <div class="body">
            <p>This is a show stopper.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-05-19T11:12:55.000+0000</p> 
        <div class="body">
            <p>Resolved as part of r15640 for ZF-3020, see the option throw_startup_exceptions- the ability to pass in a integer (error level)</p>

        </div>
    </div>
    </div>

