<h2>ZF-441: Multiple ARO Registry Support</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-10-12T12:13:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.2.0 (29/Oct/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Simon Mundy (peptolab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Acl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Acl currently utilizes a "registry" (class Zend_Acl_Aro_Registry) to store ARO objects in an organized manner. The underlying storage mechanism follows the Singleton pattern, and multiple instances of Zend_Acl appear to be forced to use the same ARO registry.</p>

<p>It may be desirable, however, that each instance of Zend_Acl would be able to encapsulate its own ARO registry. Though we do need to support the use case of multiple ACLs using the same ARO registry, it seems arbitrary and counterintuitive to impose that multiple ACL instances may exist and that they must share a single ARO registry. It is conceivable that completely unrelated ACL instances would not use the same ARO registry.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2006-10-12T16:47:18.000+0000</p> 
        <div class="body">
            <p>The singleton approach was a good idea for the proof of concept but not, as you pointed out, for real-world usage! Have updated to allow one registry per ACL. To avoid unnecessary duplication and memory bloat, the registry is stored only in the root node of the ACL, and if the ARO Registry is requested from a child node it will work its way back to root before returning the ARO registry instance.</p>

<p>Unit tests have also been updated to ensure registries are unique.</p>

        </div>
    </div>
    </div>

