<h2>ZF-4121: Zend_View_Stream is registered in Zend_View regardless of preference</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Performance Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-08-29T10:33:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-19T10:12:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11502/View.php.patch">View.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_View_Stream is not used by default in Zend_View; however, if PHP's "short_open_tag" is disabled, Zend_View_Stream is required and registered as a stream (regardless if it's going to be used or not).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2008-08-29T10:56:39.000+0000</p> 
        <div class="body">
            <p>Attached a fix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-10-23T20:09:33.000+0000</p> 
        <div class="body">
            <p>Your fix will not work.  It will break registering the stream when short tags are enabled.  I will work on a better patch and submit it when i get it done and tested.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-10-24T08:10:45.000+0000</p> 
        <div class="body">
            <p>This will not work because you need short tags enabled to use the stream feature.  If you look at the _run() method you have to have short tags enabled and pass in useStreamWrapper in your config to actually enabled it and run it.</p>

<pre class="highlight"><code>
protected function _run()
    {
        if ($this-&gt;_useViewStream &amp;&amp; $this-&gt;useStreamWrapper()) {
            include 'zend.view://' . func_get_arg(0);
        } else {
            include func_get_arg(0);
        }
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-09-19T10:12:40.000+0000</p> 
        <div class="body">
            <p>A quick look using a basic app skeleton, XDebug, and KCacheGrind clearly shows that registering a stream has no perceptible measurable performance impact. If a future demonstration of a performance problem arises, then the issue may be revisited.</p>

        </div>
    </div>
    </div>

