<h2>ZF-4265: Captcha bad image quality</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-12T04:55:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-01-16T20:16:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
            <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10867">ZF-10867</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The image quality of Zend_Form_Element_Captcha('image' ...  really needs improvement. We should be able at least to choose a %tage of image deformation, an image background, or no image deformation at all. 
The black and white backgound image makes it often difficult to read.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-12T05:58:19.000+0000</p> 
        <div class="body">
            <p>Assigning to Stas</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ota Mares (ota) on 2008-09-12T06:12:24.000+0000</p> 
        <div class="body">
            <p>Yep also an option to define some colors would be nice.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2008-09-12T09:44:20.000+0000</p> 
        <div class="body">
            <p>I will look into making it more configurable - but also it would be really easy to use your own image generator (including amending the existing one) if you wanted to - just extend the Zend_Captcha_Image class and override  _generateImage.</p>

<p>As for colors I'm not sure it's a good idea - having different colors rarely adds much since it is very easy for a robot to convert it back to b&amp;w, but it often makes it easier to read characters - e.g. if noise and symbols have different colors, the robot could just filter the "noisy" color out automatically.</p>

<p>However, if you have an idea for using colors that you think would add strength - please share.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ota Mares (ota) on 2008-09-12T11:21:57.000+0000</p> 
        <div class="body">
            <p>Hehe yeah you could but most of us dont have the time to create an own image generator and to think up some sin/cos mathematical stuff :)
So thanks for looking into it.</p>

<p>The color option was just an idea, there a cases where you want the captcha make more readable and a colored font adds to that option.
But you could create a gradient or color spots to the background to make it harder for robots.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2008-10-23T14:47:11.000+0000</p> 
        <div class="body">
            <p>added setDotNoise() and setLineNoise() so that noise level can be configured. Also added setStartImage() so that image could be initialized with some non-empty image (should be PNG)</p>

        </div>
    </div>
    </div>

