<h2>ZF-4714: Using mutliple file elements via setMultiFile causes Zend_File_Transfer to fail</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-26T23:13:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Adam Kosecki (adamkosecki)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11612/TestController.php">TestController.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am very sad that I cannot use Zend_Form_Element_File::setMultiFile($cnt) function when using Zend_File_Transfer.</p>

<p>The simple code in the file attached to this issue will produce this exception:</p>

<p><b>Fatal error</b>:  Uncaught exception 'Zend_File_Transfer_Exception' with message '"projectImage_2_" not found by file transfer adapter' in C:\inetpub\AK\library\Zend\File\Transfer\Adapter\Abstract.php:1160
Stack trace:</p>

<h1>0 C:\inetpub\AK\library\Zend\File\Transfer\Adapter\Abstract.php(564): Zend_File_Transfer_Adapter_Abstract-&gt;_getFiles('projectImage')</h1>

<h1>1 C:\inetpub\AK\library\Zend\Form\Element\File.php(416): Zend_File_Transfer_Adapter_Abstract-&gt;isValid('projectImage')</h1>

<h1>2 C:\inetpub\AK\library\Zend\Form.php(1985): Zend_Form_Element_File-&gt;isValid(NULL, Array)</h1>

<h1>3 C:\inetpub\AK\application\default\controllers\TestController.php(39): Zend_Form-&gt;isValid(Array)</h1>

<h1>4 C:\inetpub\AK\library\Zend\Controller\Action.php(494): TestController-&gt;indexAction()</h1>

<h1>5 C:\inetpub\AK\library\Zend\Controller\Dispatcher\Standard.php(285): Zend_Controller_Action-&gt;dispatch('indexAction')</h1>

<h1>6 C:\inetpub\AK\library\Zend\Controller\Front.php(934): Zend_Controller_Dispatcher_Standard-&gt;dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_ in <b>C:\inetpub\AK\library\Zend\File\Transfer\Adapter\Abstract.php</b> on line <b>1160</b><br /></h1>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Kosecki (adamkosecki) on 2008-10-26T23:14:51.000+0000</p> 
        <div class="body">
            <p>I have attached this file b/c pasting the code into the description didn't work so well...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-27T00:36:21.000+0000</p> 
        <div class="body">
            <p>This issue has already been solved about 5 weeks ago.
Please look always first if such a problem was already filled and/or solved.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Kosecki (adamkosecki) on 2008-10-27T07:30:42.000+0000</p> 
        <div class="body">
            <p>Can you provide me with a link to the issue? I did in fact look, for a while, and found nothing.</p>

<p>It's also worth point out that, if the problem was in fact solved, it is still broken in the 1.7 pre-release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-27T08:03:57.000+0000</p> 
        <div class="body">
            <p>The code freeze for 1.7 was about 4-5 weeks ago.
Code freeze is always several days before the official release.</p>

<p>I tested your code with the actual trunk (1.7) and got no errors so it's already fixed in 1.7</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Kosecki (adamkosecki) on 2008-10-27T08:12:44.000+0000</p> 
        <div class="body">
            <p>Alright. Thanks for the quick responses.</p>

<p>I'd still be curious to see the corresponding issue, if for no other reason to see what words should have been in my search phrase.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:10.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

