<h2>ZF-4070: Zend_Test_PHPUnit_ControllerTestCase::setQuery() GET params are erased during Zend_Test_PHPUnit_ControllerTestCase::dispatch()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-26T04:52:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-11T06:39:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Piotr Czachur (zimnyx)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Test_PHPUnit</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>&lt;?php
class Controllers_Default_IndexControllerTest extends Zend_Test_PHPUnit_ControllerTestCase
{
    public function testIndexAction() 
    { 
        $this-&gt;request-&gt;setQuery('mr', 'proper');
        $this-&gt;dispatch('/index/index?james=bond');
        var_dump($this-&gt;request-&gt;getParams());

=====echoes======

....................................array(4) {
  ["controller"]=&gt;
  string(5) "index"
  ["action"]=&gt;
  string(5) "index"
  ["module"]=&gt;
  string(7) "default"
  ["james"]=&gt;
  string(4) "bond"
}
</code></pre>

<p>Why 'mr' GET param is not set?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-26T05:51:36.000+0000</p> 
        <div class="body">
            <p>The parameter is not set because you passed parameters via the query string; these overwrite those previously set with setQuery().</p>

<p>Either set all GET parameters using setQuery() or pass them as part of the URL to dispatch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-26T07:30:32.000+0000</p> 
        <div class="body">
            <p>The following better demonstrates the issue:</p>

<pre class="highlight"><code>
    public function testIndexAction()
    {
        $this-&gt;request-&gt;setQuery('mr', 'proper')
                      -&gt;setQuery('james', 'bond');
        $this-&gt;dispatch('/index/index');
        $this-&gt;fail(var_export($this-&gt;request-&gt;getParams(), 1));
    }
</code></pre>

<p>The expected result would show both the 'mr' and 'james' parameters in the request. However, these are not present. exporting getQuery() results in an empty array as well.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-08-26T07:31:35.000+0000</p> 
        <div class="body">
            <p>Scheduling for next mini release (1.6.1)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-11T06:39:30.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.6 release branch; will release with 1.6.1</p>

        </div>
    </div>
    </div>

