<h2>ZF-4153: The PaginationControl view helper should check for &quot;paginator&quot;, if possible</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-01T09:05:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-04T11:38:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>From Simon Corless:</p>

<p>{quote}
It would be good if the view helper tried to detect the paginator instance in the view itself. The docs suggest calling it $view-&gt;paginator would it not make sense for the helper to use this by default unless another instance is supplied in the helper call?
{quote}</p>

<p>Not sure this is possible, but worth looking into.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2008-09-03T19:40:26.000+0000</p> 
        <div class="body">
            <p>Added in revision 11220.</p>

        </div>
    </div>
    </div>

