<h2>ZF-4193: Filter / Validate The Page Number on setCurrentPageNumber()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-04T13:58:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-05T21:38:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be a good idea for Zend_Paginator to filter or validate (as appropriate) that the page number being set is actually a number. The docs state it is good practice to make sure it's a number in the route but this may not always be possible, or the feature may be used in another way. Therefore Zend_Paginator should make sure the data given to it is of the correct type.</p>

<p>The same should also apply to setItemCountPerPage() and any other functions which require user input.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2008-09-05T21:38:24.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 11246.</p>

        </div>
    </div>
    </div>

