<h2>ZF-4610: Add Zend_Paginator support to Zend_View_Helper_PartialLoop</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-10-15T11:49:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-16T10:09:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Hector Virgen (djvirgen)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, an instance of Zend_Paginator cannot be passed in to Zend_View_Helper_PartialLoop.</p>

<p>From within a view script:
&lt;?php 
// $this-&gt;paginator is a Zend_Paginator
echo $this-&gt;partialLoop('item.phtml', $this-&gt;paginator); 
?&gt;</p>

<p>The code above throws an exception "PartialLoop helper requires iterable data".</p>

<p>If Zend_Paginator_Adapter_Interface implemented Traversable, it would be possible to use the items in the paginator with PartialLoop. The current workaround is to use a foreach loop and Zend_View_Helper_Partial:</p>

&lt;?php
foreach ($this-&gt;paginator as $item) {
    echo $this-&gt;partial('item.phtml', $item);
}
?&gt;

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-10-16T05:35:29.000+0000</p> 
        <div class="body">
            <p>Paginator already implements IteratorAggregate, which is a child-interface of Traversable, so I'm not sure if this is a Paginator issue...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hector Virgen (djvirgen) on 2008-10-16T09:11:12.000+0000</p> 
        <div class="body">
            <p>My mistake, I didn't realize I was using an outdated PartialLoop view helper. The old one checked if the object was an instance of Iterable, which did not work with the Paginator.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tobias Gies (ruunstalker) on 2008-10-16T09:13:45.000+0000</p> 
        <div class="body">
            <p>@Hector: So it works now? If yes, please close as "not an issue".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hector Virgen (djvirgen) on 2008-10-16T09:20:00.000+0000</p> 
        <div class="body">
            <p>@Tobias: Yes, it works now. It looks like I don't have permission to close this ticket.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tobias Gies (ruunstalker) on 2008-10-16T10:09:44.000+0000</p> 
        <div class="body">
            <p>Resolving as "not an issue"</p>

        </div>
    </div>
    </div>

