<h2>ZF-4258: testBasic(Zend_Validate_File_NotExistsTest)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-09-11T12:39:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-14T02:05:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate_File</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Output:
{panel}
15) testBasic(Zend_Validate_File_NotExistsTest)
Failed asserting that  matches expected value .
{panel}</p>

<p>(tested with the release-1.6 branch)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-11T23:16:44.000+0000</p> 
        <div class="body">
            <p>Erased linking...</p>

<p>Extension tests for string, NotExists tests for file_exists... these are completly different tests and have nothing to do with each other.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-11T23:17:35.000+0000</p> 
        <div class="body">
            <p>Can you please verify this with trunk ?</p>

<p>Both have the same code base and I am not getting any error at all.
Maybe a environment problem ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-09-12T04:12:19.000+0000</p> 
        <div class="body">
            <p>Seems problem depends on an environment.</p>

<p>I tested it under Linux, PHP 5.2.5. 
It's the same environment which was used for ZF 1.6.0 testing.</p>

<p>Was there any code change which may affect Zend_Validate_File behavior? or is it definitely unit tests problem?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-12T14:28:04.000+0000</p> 
        <div class="body">
            <p>There has been changes to allow user definition of case sensitivy.</p>

<p>But in my environment all tests pass.
So the problem must be Linux specific.</p>

<p>Can you evaluate on which line of the testbed the test fails so I can see the input and how the code runs ?
Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-09-13T02:56:41.000+0000</p> 
        <div class="body">
            <p>Line 104, first pass of the foreach() loop</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-13T11:51:49.000+0000</p> 
        <div class="body">
            <p>Probably fixed with r11388.
False directory separator used.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-09-14T02:05:37.000+0000</p> 
        <div class="body">
            <p>Yes, that fixes the issue.</p>

<p>Merged into release-1.6 branch with the <a href="http://fw02.zend.com:8060/code/changelog/Zend_Framework?cs=11392">cs-11392</a>.</p>

        </div>
    </div>
    </div>

