<h2>ZF-40: Zend_Db_Select SQL: FOR UPDATE</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-19T23:10:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zend Framework (zend_framework)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When Zend_Db_Select::<em>toString() is called the FOR UPDATE syntax should be processed by the Zend_Db_Adapter</em>* that it belongs to. The current method generates a syntax that is incompatible with MySQL. Allowing the Zend_Db_Adapter_*::limit() method to process a $forUpdate flag would solve the problem.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-07-06T17:21:43.000+0000</p> 
        <div class="body">
            <p>There should also be support for SELECT ... LOCK IN SHARE, and the corresponding locking modes in SQLite ( <a href="http://www.sqlite.org/lockingv3.html">http://www.sqlite.org/lockingv3.html</a> ), and similar for the other adapters.  This issue overlaps with [ZF-39].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:14:32.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.8.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-05T17:06:23.000+0000</p> 
        <div class="body">
            <p>Recategorize as Zend_Db_Table component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-04-17T17:59:13.000+0000</p> 
        <div class="body">
            <p>Marking this issue Postponed, to be revisited in a later release of Zend_Db.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2008-01-18T21:50:56.000+0000</p> 
        <div class="body">
            <p>The SQL-only version of this has been resolved in r7508 in trunk.</p>

        </div>
    </div>
    </div>

