<h2>ZF-4426: Unintended side effect of using new Zend_Translate($type,$dir);</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-30T11:13:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ashley Kitson (akzincdig)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to the code of Zend_Translate_Adapter::addTranslation() if you pass it a directory, it does a recursive seek through the directory tree from the point given searching for files it can use as translation sources.</p>

<p>Unfortunately, it also picks up subdirs beginning with . (period / full stop) and traverses through them.  Consequence of this is that it goes through things like Subversion (.svn) directories and adds OLD copies of files.</p>

<p>I couldn't figure out why when I had deleted some TMX tagnames they still kept getting used.  The previous version was in the svn archive folder!!! which translate_adaptor happily saw as being valid.</p>

<p>I understand that it may be an intended effect to give the root of a language file hierarchy, but perhaps consideration can be given to <em>excluding</em> otherwise normally hidden directories from the directory span. (perhaps passing a flag that defaults to NOT traversing hidden directories)</p>

<p>Now all I got to do is figure out how to unravel it :-}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-30T11:40:08.000+0000</p> 
        <div class="body">
            <p>Simply use the 'ignore' option already available since several weeks in trunk.
Per default it ignores files and directories beginning with '.'</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:09.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

