<h2>ZF-4606: Multi-page forms example code introduces confusion</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-15T06:27:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-01T10:52:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10251">ZF-10251</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The example code for a multi-page form (<a href="http://framework.zend.com/manual/en/zend.form.advanced.html#zend.form.advanced.multiPage">http://framework.zend.com/manual/en/…</a>) suggests adding 
"public function setSubFormDecorators(Zend_Form_SubForm $subForm)" 
to the Zend_Form_Extension it tells you to make, but Zend_Form (and so Zend_Form_SubForm) already has a method with that name, that type-hints an array as its argument, and does something completely different. Renaming it to something else (I'm using "setDecoratorsForSubForm", which is still a bit confusing...) would prevent confusion/errors</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-15T06:54:30.000+0000</p> 
        <div class="body">
            <p>Mis-assigned... sorry</p>

        </div>
    </div>
    </div>

