<h2>ZF-4636: Zend_Dojo_View_Helper_Tooltip</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2008-10-18T12:35:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-21T10:51:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4635">ZF-4635</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A new view helper for dijit.Tooltip:</p>

<p>class Zend_View_Helper_Tooltip extends Zend_Dojo_View_Helper_Dijit
{
   protected $_dijit  = 'dijit.Tooltip';</p>

<p>protected $_module = 'dijit.Tooltip';</p>

<p>public function tooltip($id, $params = array(), array $attribs = array())
   {
      if (!isset($attribs['id']) $attribs['id'] = $id; 
      $attribs = $this-&gt;_prepareDijit($attribs, $params, null); //see [1]
       $html = '</p>

<div>_htmlAttribs($attribs) . '&gt;</div>

<p>\n";</p>

<pre><code>   return $html;
</code></pre>

<p>}
}</p>

<p>[1] note here $type param set to null. Could equally be set to tooltip if custom behaviour is required within _prepareDijit()</p>

<p>/* and in your view scripts */</p>

&lt;?php echo $this-&gt;tooltip('test', array(
   'connectId' =&gt; 'username',
   'label' =&gt; 'My Tooltip',
)); ?&gt;

<p>A few concerns:</p>

<ul><li>The div markup still needs to be created and returned even when using
 programmatic otherwise the main dojo helper will not attach the params. </li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

