<h2>ZF-4212: Cannot executing a database function where any argument contains a period</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-06T14:14:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-27T09:13:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Steven Almeroth (huntercheif)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I try to execute a stored procedure in a (postgres) database, if any of the arguments contain a period, the _uniqueCorrelation() method thinks this is a correlation indicator, even if the string contains parentheses which should convert it to an expression.</p>

<p>This code:</p>

<pre class="highlight"><code>
public String getFoo()
{
    $sql = "SELECT * FROM new_user ('Robert', 'Marley', 'jah@love.ire')";
    $select = $this-&gt;select();
    $select-&gt;from($sql, '*');
    $stmt = $this-&gt;getAdapter()-&gt;query($select);
}
</code></pre>

<p>produces this assemble error:</p>

<pre class="literal"> Warning: Select query cannot join with another table in 
/var/www/html/library/Zend/Db/Select.php on line 1222
</pre>

<p>and the select object looks like:</p>

<pre class="literal"> object(Zend_Db_Table_Select)#182 (5) {
  ...
  ["_parts:protected"] =&gt; array(11) {
    ["distinct"] =&gt; bool(false)
    ["columns"] =&gt; array(1) {
      [0] =&gt; array(3) {
        [0] =&gt; string(5) "ire')"
        [1] =&gt; string(1) "*"
        [2] =&gt; NULL
      }
    }
    ["union"] =&gt; array(0) {
    }
    ["from"] =&gt; array(1) {
      ["ire')"] =&gt; array(4) {
        ["joinType"] =&gt; string(10) "inner join"
        ["schema"] =&gt; string(50) "SELECT * FROM new_user ('Rob', 'Marley', 'jah@love"
        ["tableName"] =&gt; string(5) "ire')"
        ["joinCondition"] =&gt; NULL
      }
    }
  }
</pre>

<p>Expected results should be:</p>

<pre class="literal"> 
    ["from"] =&gt; array(1) {
      ["SELECT * FROM new_user ('Rob', 'Marley', 'jah@love.ire)"] =&gt; array(4) {
        ["joinType"] =&gt; string(10) "inner join"
        ["schema"] =&gt; NULL
        ["tableName"] =&gt; string(55) "SELECT * FROM new_user ('Rob', 'Marley', 'jah@love.ire)"
        ["joinCondition"] =&gt; NULL
      }
    }
</pre>

<p>If I wrap it in an expression:</p>

<pre class="highlight"><code>
public String getFoo()
{
    $sql = "SELECT * FROM tms_create_user_api ('Robert', 'Marley', 'jah@love.ire')";
    $select = $this-&gt;select();
    $select-&gt;from(new Zend_Db_Expr($sql), '*');
    $stmt = $this-&gt;getAdapter()-&gt;query($select);
}
</code></pre>

<p>then the _join() method runs $this-&gt;_uniqueCorrelation('t') with the following results:</p>

<pre class="literal"> 
    ["from"] =&gt; array(1) {
      ["t"] =&gt; array(4) {
        ["joinType"] =&gt; string(10) "inner join"
        ["schema"] =&gt; NULL
        ["tableName"] =&gt; object(Zend_Db_Expr)#182 (1) {
          ["_expression:protected"] =&gt; string(56) "SELECT * FROM new_user ('Rob', 'Marley', 'jah@love.ire')"
        }
        ["joinCondition"] =&gt; NULL
      }
    }
</pre>

<p>which looks like it should work, but I get the same error.  I can run this thing from the Zend_Db_Adapter-&gt;query() method which, happily, works; but, there is nowhere to specify the schema this way other than gluing it on the front of the sql string, so that's why I wanted to get the select() to work.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-27T09:12:21.000+0000</p> 
        <div class="body">
            <p>I cannot trigger the warning in question, that might in fact be from the database you are using?</p>

<p>Ideally, I would like to see a couple of things:</p>

<p>-1) information on the database you are using, adapter and so on-
2) the target query you think Zend_Db_Select should be producing</p>

<p>If you still find the issue, please reopen with above information. Thanks!</p>

<p>Edit:
I see you are using Postgres, but I still need the target SQL you are attempting to build, and ideally, some kind of scheme i can compare it against.</p>

        </div>
    </div>
    </div>

