<h2>ZF-4205: Add breakchainonfailure for validators</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-05T10:32:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-10T14:41:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.2 (13/Oct/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The form validators allow the usage of breakchainonfailure.
Actually this parameter is ignored by Zend_File_Transfer.</p>

<p>It should be added for consistency.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-19T02:29:51.000+0000</p> 
        <div class="body">
            <p>The new feature "breakChainOnFailure" has been added with r11430.</p>

<p>The syntax for form validation and file validation is now consistent.
But as this is a small BC break it could be possible that you have to adopt your scripts validator creation calls.</p>

        </div>
    </div>
    </div>

