<h2>ZF-4527: Include slide notes in indexer (Zend_Search_Lucene_Document_Pptx)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-10-09T00:29:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-09T23:07:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Maarten Balliauw (maartenba)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Include slide notes in indexer (Zend_Search_Lucene_Document_Pptx)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maarten Balliauw (maartenba) on 2008-10-09T23:07:07.000+0000</p> 
        <div class="body">
            <p>Resolved issue + added documentation in en manual</p>

        </div>
    </div>
    </div>

