<h2>ZF-4556: Checkbox, can't toggle anymore, wrong checkValue</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-11T02:29:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-06T12:57:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bert Van Hauwaert (becoded)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bart McLeod (mcleod@spaceweb.nl)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In ZF 1.5.2, you could use a checkbox to toggle between 0 and 1. (Without specifying any values in your config)
Now, in ZF 1.6.1, this doesn't work any more.</p>

<p>In the the static function, determineCheckboxInfo from the FormCheckbox viewhelper there is a check if the value !== null. Then the unCheckedValue will be set with the value of self::$_defaultCheckedOptions['unChecked'] but checkedValue remains null.
Later on in the function there is a check if the checkedValue is null and if so, then the checkedValue will be set to the value given to the function.</p>

<p>So that means that if the initial value of the checkbox is 0 (so checkbox is unChecked), only the unCheckedValue will be set with the default value. This means that checkedValue remains null and will be changed to 0 in the last if-statement. So this results in a checkedValue of 0 and an unCheckedValue of 0. So you can't toggle anymore because the value will always be 0.</p>

<p>It seems related to <a href="http://framework.zend.com/issues/browse/ZF-4274">http://framework.zend.com/issues/browse/ZF-4274</a> but without the use of Dojo</p>

<p>For the moment, I changed on line 135<br />
} elseif ($value !== null) {
to<br />
} elseif ($value !== null &amp;&amp; $value != self::$_defaultCheckedOptions['unChecked']) {
to make it backwards compatible</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-11-06T07:27:52.000+0000</p> 
        <div class="body">
            <p>I noticed the same behavior a long time ago as I updated from svn. It can be easily worked around by setting the checked value.</p>

<pre class="highlight"><code>//in navigation checkbox
        $in_mainmenu = new Zend_Form_Element_Checkbox('in_mainmenu');
        $in_mainmenu-&gt;setLabel('in main menu')-&gt;setCheckedValue('ja');
        $form-&gt;addElement($in_mainmenu);
</code></pre>

<p>Because It can be so easily worked around, I do not think of this as a critical bug. Will therefore change it to major, although minor would be even better.</p>

<p>Will also try to fix it in the meantime, because it was a great feature that you could just toggle it without doing anything.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-11-06T12:46:41.000+0000</p> 
        <div class="body">
            <p>This is no longer an issue. If you create the most basic form, you will not be able to reproduce the error. Try this form:</p>

<pre class="highlight"><code>
require_once 'Zend/Loader.php';
/**
 * Loads all Zend Framework classes automagically
 *
 * @param string $className
 */
function __autoload($className){
    Zend_Loader::loadClass($className);
}

$form = new Zend_Form('test');
$form-&gt;setView(new Zend_View());
$form-&gt;setAction('');
$form-&gt;setMethod('post');
$form-&gt;addElement('checkbox', 'mine');
$form-&gt;addElement('submit','metoo');
$form-&gt;isValid($_POST);
echo $form;
</code></pre>

<p>This form will post to itself and populate itself as a result of $form-&gt;isValid($_POST); It is perfectly able to toggle.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2008-11-06T12:57:29.000+0000</p> 
        <div class="body">
            <p>Now that I think of it more carefully, I noticed this behavior before and it still 'exists' if the checkedValue that you populate the form with is different from '1'. But that is by design.</p>

<p>Before 1.6 you could toggle it with ANY value on populate. Say you would not set a checkedValue in your config or explicitly on a class instance, you could check the box  by passing in 'anyvalue' as opposed to null, false or 0 (I guess). That was kind a fun, but also a little unexpected.</p>

<p>So now you can only toggle by populating with '1', unless you set the checkedValue to the value you desire.</p>

        </div>
    </div>
    </div>

