<h2>ZF-4629: The render() method of Zend_Capture_Image is missing the required XHTML 1.0 Strict attribute &quot;alt&quot;.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-10-18T03:52:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-20T14:54:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                brian pizzey (brianp)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4630">ZF-4630</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Suggest change to:</p>

<p>public function render(Zend_View $view, $element = null)
    {
        return '<img alt="" src="'%20.%20$this-" /><br />';
    }</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-10-22T06:18:47.000+0000</p> 
        <div class="body">
            <p>It duplicates ZF-4630</p>

        </div>
    </div>
    </div>

