<h2>ZF-4408: Precision and number_format seems to be broken</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-28T14:49:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-17T09:02:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Peter Myllykoski (kvarnfors)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3473">ZF-3473</a></li>
            <li><a href="/issues/browse/ZF-9698">ZF-9698</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I encountered a bug when trying to use 
$number = Zend_Locale_Format::toNumber('26.7857142857', array('precision' =&gt; 2, 'locale' =&gt; 'sv_SE'); Instead of 26,79 it returned 26,78.</p>

<p>I then tried with the examples given in the reference guide and they also returned wrong results.</p>

<p>{quote}
$locale = new Zend_Locale('de_AT');
$number = Zend_Locale_Format::getNumber('13.524,678', array('precision' =&gt; 1, 'locale' =&gt; $locale));
print $number; // will return 13524.7
{quote}</p>

<p>In fact this code will return 13524.6</p>

<p>{quote}
$locale = new Zend_Locale('de_AT');
$number = Zend_Locale_Format::getNumber('13.524,678', array('number_format' =&gt; '#.00', 'locale' =&gt; $locale));
print $number; // will return 13524.67
{quote}
This is currently returning a value of 13524.678</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-28T23:39:29.000+0000</p> 
        <div class="body">
            <p>Duplicate of ZF-3473</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-02-05T14:39:33.000+0000</p> 
        <div class="body">
            <p>Fixed with r13990</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Lasak (mlasak) on 2010-04-02T07:59:45.000+0000</p> 
        <div class="body">
            <p>I've noticed when bcmath extension is <em>enabled</em> the problem reoccurs.</p>

<pre class="highlight"><code>
$number = Zend_Locale_Format::toNumber(13547.3678,
                                       array('precision' =&gt; 2,
                                             'locale' =&gt; $locale));
</code></pre>

<p>returns 13547.36 with bcmath enabled. Zend Server 5.0, ZF 1.10.2, PHP 5.2.12, Windows 7.</p>

        </div>
    </div>
    </div>

