<h2>ZF-4812: Add PrepareElements decorator for Zend_Form</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-11-05T15:06:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-06T13:46:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, the default decorators do a lot of behind the scenes work that goes AWOL if you use the ViewScript decoator with a form or sub form. This can be alleviated with a PrepareElements decorator that sets the view in each element, injects the translator, etc. It might contain the following:</p>

<pre class="highlight"><code>
$belongsTo  = ($element instanceof Zend_Form) 
            ? $element-&gt;getElementsBelongTo() 
            : null;
$translator = $element-&gt;getTranslator();
      
foreach ($element as $item) {
  $item-&gt;setView($view)
       -&gt;setTranslator($translator);
  if ($item instanceof Zend_Form_Element) {
      $item-&gt;setBelongsTo($belongsTo);
  } elseif (!empty($belongsTo) &amp;&amp; ($item instanceof Zend_Form)) {
      if ($item-&gt;isArray()) {
          $name = $this-&gt;_mergeBelongsTo($belongsTo, $item-&gt;getElementsBelongTo());
          $item-&gt;setElementsBelongTo($name, true);
      } else {
          $item-&gt;setElementsBelongTo($belongsTo, true);
      }
  } elseif (!empty($belongsTo) &amp;&amp; ($item instanceof Zend_Form_DisplayGroup))
{
      foreach ($item as $element) {
          $element-&gt;setBelongsTo($belongsTo);
      }
  }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-06T13:46:13.000+0000</p> 
        <div class="body">
            <p>Added with r12347 to trunk; will release with 1.7.0</p>

        </div>
    </div>
    </div>

