<h2>ZF-4898: Must have components (Zend_Image and Zend_Tree) for Zend_Framework 1.8 or 2.0!</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-11-10T16:58:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-11T11:10:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello, sorry for my English ;)</p>

<p>I work with Zend Framework &gt; 1 year and i can't understand why it becoming more
and more (when it will be &gt; 50 MB? ;) ).
New classes with unnecessary functionality created bun must have components does't.
I and other programmers save tree-like structures in database (for example i need store
categories or menu tree in database). I think Zend_Framework
MUST HAVE Zend_Tree component and subclasses for store trees in database with
algorithm Nested Sets, Materialized Path and Adjacency List. Many programmers
work with other libraries because Zend Framework does not have this functionality.
For example, in russian ZF Google group you can find attachment:
<a href="http://ru-zend-framework.googlegroups.com/web/Cruiser_NSTree.zip?hl=ru&amp;gda=tVSbSkMAAAAnsXPTBSTwvvEiQl47W2aw1cV37LgCvZcrZMc_JrevFmM3e0ofW_ESUbUL5VV8IJVV6u9SiETdg0Q2ffAyHU-dAG9nkNl0lhQpRrba6tRLEA">http://ru-zend-framework.googlegroups.com/web/…</a>
I saw proposal Zend_Tree but it does not develop. I think because it to hard, but now Zend Framework has all necessary components (without the proposed mine).</p>

<p>Other MUST HAVE component is Zend_Image. Almost all CMS work with images (resizing,
converting from one format to other (for example from .png to .jpg), etc).</p>

<p>I understand that it too hard, but you are best in PHP programming and i think you can
do it. Zend Framework will be best if you can do it. I think many programmers will be
very glad if you will decide to create this two components.</p>

<p>Thank you. Best regards, Evgeniy.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2008-11-10T17:12:55.000+0000</p> 
        <div class="body">
            <p>Though I wonder if this is the right place to discuss this, I would like you to know that there is a proposal for the Zend_Image component <a href="http://framework.zend.com/wiki/display/ZFPROP/Zend_Image+-+Dolf+Schimmel%2C+Marcin+Lulek">http://framework.zend.com/wiki/display/…</a>  already. It will however need to be recommended, approved, developed, unittested and documentated (and be promoted), if all goes to plan (I got usecase 1 and 2 working, but that's about it). This could be done however in less than 20 weeks :D</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hinikato Dubrai (hinikato) on 2008-11-10T17:16:17.000+0000</p> 
        <div class="body">
            <p>I fixed it (20 weeks) :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-11T11:10:37.000+0000</p> 
        <div class="body">
            <p>This should definitely be tracked in the proposal section of the wiki: <a href="http://framework.zend.com/wiki/display/ZFPROP/Home">http://framework.zend.com/wiki/display/ZFPROP/Home</a>. I'm closing this issue so that we can track it there (otherwise we'd end up with an issue that could indefinitely stay open).</p>

        </div>
    </div>
    </div>

