<h2>ZF-4849: add a format to output measures</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-11-07T04:53:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Measure</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I would like to output some measures in an own format:
e.g: I get the time "485500 ms" and would output it as "8 min 05 s"</p>

<p>A format code can be:</p>

<pre class="highlight"><code>
[:.:]
</code></pre>

<p>method can be:</p>

<pre class="highlight"><code>
toString(int $round, $locale=null) : string
toString(string $format, $locale=null) : string
</code></pre>

<p>examples:
-&gt; higher values will sub from the original value</p>

<pre class="highlight"><code>
$time = new Zend_Measure_Time(57500,Zend_Measure_TIME::MILLISECOND);
echo $time-&gt;toString('[minute:1.0:3] [second:2.0:1]');  // 8 min 05 s
// [minute:1.0:3] -&gt; 8 min    (485500ms - 8min = 5.5s)
// [second:2.0:1] -&gt; 05 s min (5.5s - 5s = 500ms)

echo $time-&gt;toString('[minute:2.0:1] [second:1.2:3]');  // 08 m 05.50 sec
// [minute:2.0:1] -&gt; 08 m
// [second:1.2:3] -&gt; 05.50 sec

echo $time-&gt;toString('[minute]:[second:2].[millisecond:3] [minute:0.0:N]');  // 8:05.500 minutes
// [minute]        -&gt; 8
// [second:2]      -&gt; 05
// [millisecond:3] -&gt; 500
// [minute:0.0:N]  -&gt; minutes (0.0 means no value | N means the full name)
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-10T04:31:41.000+0000</p> 
        <div class="body">
            <p>This is really very complicated, don't you think so ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (GIATA mbH) (mben) on 2008-11-10T05:01:58.000+0000</p> 
        <div class="body">
            <p>Hi Thomas</p>

<p>Yes the format string is very complicated but I don't know a better format structure to create a way to display the measure in different formats.
A standard similar to the date format I can't find.</p>

<p>Do you have a other idea to display measures in different formats ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:40.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

