<h2>ZF-4225: Throw an exeption when the file is not readable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-08T08:03:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-10T11:43:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                João Bertolino (joaobsneto)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On Ini.php constructor, an exception is thrown when the $filename is empty, but if php wasn't able to open the file, it's not treated.
I've got a simple solution. Maybe there is a smarter solution, but this one works fine.</p>

<p>-&gt; Existing code:</p>

<p>$iniArray = parse_ini_file($filename, true);</p>

<p>-&gt; Suggested code:</p>

<p>$iniArray = @parse_ini_file($filename, true);
        $error = error_get_last();
        if (strpos($error["message"], "parse_ini_file") !== false) {
            require_once 'Zend/Config/Exception.php';
            throw new Zend_Config_Exception('File is not readable'); 
        }</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-09-08T11:49:36.000+0000</p> 
        <div class="body">
            <p>Sorry, but error_get_last() is PHP5.2 only, and ZF supports PHP 5.1.4 so we cant use your solution.
However, be advised that such a bug has found a fix in 1.6 branch of ZF, you should consider upgrading your ZF version thought.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-10T11:43:30.000+0000</p> 
        <div class="body">
            <p>Fixed in 1.6.0</p>

        </div>
    </div>
    </div>

