<h2>ZF-466: Zend_Xmlrpc_Client violates standards. Header User-Agent missing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-10-30T09:22:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Lars Strojny (lars)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_XmlRpc_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10123/Zend_Xmlrpc_Client-fix-user-agent.diff">Zend_Xmlrpc_Client-fix-user-agent.diff</a></li>
            <li><a href="/issues/secure/attachment/10122/Zend_Xmlrpc_Client-fix-user-agent.diff">Zend_Xmlrpc_Client-fix-user-agent.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Xmlrpc_Client::_sendRequest() does not send a User-Agent-header which is required in the XML-RPC-standard. See <a href="http://www.xmlrpc.com/spec">http://www.xmlrpc.com/spec</a> (Chapter: Header requirements).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2006-10-31T04:18:38.000+0000</p> 
        <div class="body">
            <p>Fix for the user-agent issue. Signed my CLA a few minutes ago, you can apply this patch soon.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2006-10-31T10:04:43.000+0000</p> 
        <div class="body">
            <p>Removing the "; charset="-part in the Content-Type header. According to Dave Winers specification this is not recommended. He just writes about "text/xml", not about "text/xml; charset=.*".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-01T23:39:35.000+0000</p> 
        <div class="body">
            <p>I'll add the charset as well, as the client and server send back utf-8 encoded xml</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-01T23:52:39.000+0000</p> 
        <div class="body">
            <p>Fixed in [1426]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2006-11-02T01:30:18.000+0000</p> 
        <div class="body">
            <p>The problem with the charset is, that from my point of view, XmlRPC misses some standardization there. I guess we should go with <a href="http://effbot.org/zone/xmlrpc-errata.htm">http://effbot.org/zone/xmlrpc-errata.htm</a> make it possible for the user to set the charset and per default use UTF-8, which is much more common in the XML-world.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2006-11-02T01:41:33.000+0000</p> 
        <div class="body">
            <p>OK, I took a look at the fix and I would guess it is wrong and worse than before. The XmlRPC-client now sends the incorrect charset because in _buildRequest(), and ISO-8859-1 XML-payload is generated (line371).  So either remove the charset on both side (_buildRequest() and _sendRequest()) and leave it completely to the user to supply the correct data or make it UTF-8 everywhere.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-02T01:55:58.000+0000</p> 
        <div class="body">
            <p>I've made it UTF-8 everywhere, as this keeps it compatible then with the xmlrpc server as well as any class that might use i18n charsets.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2006-11-02T03:12:30.000+0000</p> 
        <div class="body">
            <p>OK, thank you very much.</p>

        </div>
    </div>
    </div>

