<h2>ZF-4366: Adding missing setObject() to Zend_Soap_Server</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2008-09-24T01:57:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11551/Server.php.patch">Server.php.patch</a></li>
            <li><a href="/issues/secure/attachment/11552/ServerTest.php.patch">ServerTest.php.patch</a></li>
            <li><a href="/issues/secure/attachment/11562/Zend_Soap_Server.xml.patch">Zend_Soap_Server.xml.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>SoapServer-&gt;setObject($object) is an undocumeneted but very useful method of the SoapServer extension. Its missing in the Zend Soap Server wrapper. The attached patch contains a new method setObject on the Zend_Soap_Server object that registers one object and injects the object into the SoapServer in _getSoap().</p>

<p>I have also added the patch to the ServerTest.php to add one unittest that checks functionality of setObject().</p>

<p>I have made some tests and found out that using both setClass and setObject does not work for SoapServer, but i haven't implemented an Exception yet that warns on usage of both of them. SoapServer just processes the first one of both calls and /dev/null's all the requests to the second. I havent throughly tested this though, so I cant give a final word on this (and left out the exception respectivly).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-09-24T01:59:36.000+0000</p> 
        <div class="body">
            <p>Patch for setObject() addition</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-09-24T02:00:02.000+0000</p> 
        <div class="body">
            <p>Attached Unit-Test for setObject()</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-10-06T11:07:33.000+0000</p> 
        <div class="body">
            <p>Added missing documentation part. This now shows how setObject is used inside the already existing setClass example.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-10-26T11:40:55.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:10.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

