<h2>ZF-4318: Action_Helper_Redirector: Non-SSL handling</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-17T06:55:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Wolfgang Gruber (arcolf)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Although the variable $_SERVER['HTTPS'] should be empty when it isn't a HTTPS request, a few webserver set the value to 'off'. The PHP reference manual ([<a href="http://at.php.net/manual/en/reserved.variables.server.php">http://at.php.net/manual/en/…</a>]) mentions IIS and I encountered the problem with Abyss webserver. If the value is set to 'off', Action_Helper_Redirector redirects the request to https which is wrong.
Therefore the Action_Helper_Redirector should be changed in function  *_redirect($url)* from</p>

<pre class="highlight"><code>
$proto = (empty($_SERVER['HTTPS'])) ? 'http' : 'https';
</code></pre>

<p>to</p>

<pre class="highlight"><code>
$proto = ((empty($_SERVER['HTTPS'])) || (strcasecmp($_SERVER['HTTPS'],'off') == 0)) ? 'http' : 'https';
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-11-07T23:55:24.000+0000</p> 
        <div class="body">
            <p>Fixed in r12413</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:14.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

