<h2>ZF-4188: photo api returns wrong links - missing s800 folder</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-04T07:23:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-04T15:16:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mario Küster (prettyfly)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Code:
$oService = new Zend_Gdata_Photos();
$oQuery = new Zend_Gdata_Photos_PhotoQuery();
$oQuery-&gt;setUser("mario.kuester");
$oQuery-&gt;setAlbumId(5241165006900562897);
$oQuery-&gt;setPhotoId(5241168085922423490);
$photoFeed = $oService-&gt;getPhotoFeed($oQuery);
$oGroup = $photoFeed-&gt;getMediaGroup();
$oContent = $oGroup-&gt;getContent();
$oContent = reset($oContent);
$oContent-&gt;setWidth(700);
$strUrl = $oContent-&gt;getUrl();
$this-&gt;_redirect($strUrl);</p>

<p>Redirects to:
<a href="http://lh4.ggpht.com/mario.kuester/SLxemvGFIsI/AAAAAAAAAC8/T7BFwCK27Rc/IMG_0078.JPG">http://lh4.ggpht.com/mario.kuester/SLxemvGFIsI/…</a></p>

<p>Should be:
<a href="http://lh4.ggpht.com/mario.kuester/SLxemvGFIsI/AAAAAAAAAC8/T7BFwCK27Rc/s800/IMG_0078.JPG">http://lh4.ggpht.com/mario.kuester/SLxemvGFIsI/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-09-04T15:14:05.000+0000</p> 
        <div class="body">
            <p>Mario, 
To get the s800 URL, you should set the 'imgmax' parameter on your query object before calling getPhotoFeed():</p>

<p>```</p>

<p>This is documented here: <a href="http://code.google.com/apis/picasaweb/reference.html#Parameters">http://code.google.com/apis/picasaweb/…</a></p>

<p>Don't call setWidth(), all this does is modifies what you'd get if you were to subsequently call getWidth(). There's no logic in the client library that actually does anything with this value, other than converting to/from XML for communicating with Google's servers.</p>

        </div>
    </div>
    </div>

