<h2>ZF-4710: Zend_Form_Element_Captcha refuses addDecorator(..)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-26T10:02:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-07T09:04:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>i tried to add a decorator to my Zend_Form_Element_Captcha object by calling -&gt;addDecorator(..). This ends in "Exception caught by form: Plugin by name ... was not found in the registry."</p>

<p>I think there's a bug in Line 204 in file Captcha.php.</p>

<pre><code>      "default:
            return parent::addPrefixPath($prefix, $path, $type = null);"
</code></pre>

<p>As I replaced "$type = null" with "$type" it worked as expected. More Infos about this issue can be found on the german ZF forum: <a href="http://www.zfforum.de/showthread.php?p=25418#post25418">http://zfforum.de/showthread.php/?p=25418…</a></p>

<p>Thanks
Rossi</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-07T09:04:57.000+0000</p> 
        <div class="body">
            <p>Already fixed in trunk.</p>

        </div>
    </div>
    </div>

