<h2>ZF-4621: Zend_Form_File does not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-16T23:48:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                rollenc Luo (rollenc)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I create a form with a ini config. But after upgrade ZF from 1.6.1,  The file input does not work well. 
It show: 
<b>Warning</b>:  Unknown file in <b>D:\WorkProgram\php5\PEAR\Zend\Form\Element.php</b> on line <b>1923</b><br /></p>

<p>I got the trace as follow:</p>

<p>Zend_File_Transfer_Adapter_Abstract-&gt;getFilters('Avatar')</p>

<h1>1 D:\WorkProgram\php5\PEAR\Zend\Form\Element.php(524): Zend_Form_Element_File-&gt;getFilters()</h1>

<h1>2 D:\WorkProgram\php5\PEAR\Zend\Form\Element.php(541): Zend_Form_Element-&gt;_filterValue(NULL, NULL)</h1>

<h1>3 D:\WorkProgram\php5\PEAR\Zend\Form\Decorator\ViewHelper.php(201): Zend_Form_Element-&gt;getValue()</h1>

<h1>4 D:\WorkProgram\php5\PEAR\Zend\Form\Decorator\ViewHelper.php(231): Zend_Form_Decorator_ViewHelper-&gt;getValue(Object(Zend_Form_Element_File))</h1>

<h1>5 D:\WorkProgram\php5\PEAR\Zend\Form\Element.php(1905): Zend_Form_Decorator_ViewHelper-&gt;render('')</h1>

<h1>6 D:\WorkProgram\php5\PEAR\Zend\Form\Element.php(1920): Zend_Form_Element-&gt;render()</h1>

<h1>7 D:\DevRep\SmarterV2CN\Source_Code\smarter_space\web\files\templates_c\%%9B^9B5^9B538F2C%%editprofile.tpl.php(112): Zend_Form_Element-&gt;__toString()</h1>

<h1>8 D:\WorkProgram\php5\Smarty-2.6.11\libs\Smarty.class.php(1265): include('D:\DevRep\Smart...')</h1>

<h1>9 D:\WorkProgram\php5\Smarty-2.6.11\libs\Smarty.class.php(1108): Smarty-&gt;fetch('User/editprofil...', NULL, NULL, true)</h1>

<h1>10 D:\DevRep\SmarterV2CN\Source_Code\smarter_space\web\lib\classes\action\class.BaseAction.php(572): Smarty-&gt;display('User/editprofil...')</h1>

<h1>11 D:\DevRep\SmarterV2CN\Source_Code\smarter_space\web\lib\classes\action\class.BaseAction.php(458): BaseAction-&gt;display(Object(HttpRequest), Object(HttpResponse))</h1>

<h1>12 D:\DevRep\SmarterV2CN\Source_Code\smarter_space\web\scripts\user.php(26): BaseAction-&gt;execute()</h1>

<h1>13 {main}"</h1>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-17T09:32:46.000+0000</p> 
        <div class="body">
            <p>Seems that you are calling getValues() somewhere.</p>

<p>This issue has already been solved several days ago.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:25.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

