<h2>ZF-443: Zend Guard fails: SegmentInfo.php(line 172): Only variables can be passed by reference</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-10-13T10:38:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend Guard 4.0  ( Zend Encoder) Fails to encode Zend framework:
{quote}
Zend/Search/Lucene/Index/SegmentInfo.php: SegmentInfo.php(line 172): Only variables can be passed by reference
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-10-15T05:46:00.000+0000</p> 
        <div class="body">
            <p>As I see it's array_multisort() call.
It has variable length parameter list.</p>

<p>I have tried it with current SVN version and Zend Guard v4.0.1. SegmentInfo.php was encoded without any error.
Can you try Zend Guard v4.0.1?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roman Roan (videinfra) on 2006-11-01T12:05:05.000+0000</p> 
        <div class="body">
            <p>Works with Guard 4.0.1, ZF 0.2</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-11-01T19:31:06.000+0000</p> 
        <div class="body">
            <p>Looks like a Zend Guard bug. Works with Zend Guard 4.0.1</p>

        </div>
    </div>
    </div>

