<h2>ZF-428: Zend_Rest_Server causes fatal error, because it doesn't implement Zend_Server_Interface properly.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-10-08T02:54:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Taco Jung (tjung)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Davey Shafik (davey)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Rest_Server implements the Zend_Server_Interface. As it doesn't implement it correctly a fatal error occurs:</p>

<p>Fatal error: Declaration of Zend_Rest_Server::fault() must be compatible with that of Zend_Server_Interface::fault() in c:\Zend_Framework_Subversion\incubator\library\Zend\Rest\Server.php on line 49</p>

<p>The Zend_Rest_Server sets both parameter values of fault() to null, while the interface expects a string and an integer.</p>

<p>P.S. The same error occurs with Zend_Json_Server.....</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Davey Shafik (davey) on 2006-10-08T04:14:14.000+0000</p> 
        <div class="body">
            <p>Fixed. I found this issue when testing, so I've committed both the fix and the tests :)</p>

<ul><li>Davey</li>
</ul>
        </div>
    </div>
    </div>

