<h2>ZF-4071: Lucene doesn't work on 64-bit </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-26T05:54:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-03T03:19:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5141">ZF-5141</a></li>
            <li><a href="/issues/browse/ZF-4113">ZF-4113</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11707/lucene-64bit.diff">lucene-64bit.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I tried Zend_Search_Lucene on a 32 bit and all was fine. Trying on a 64 bit simply doesn't work.
The same index correctly opened on the 32 bit machine raises an exception on 64 bit.
Looking in the code I discovered that there's a problem with integer precision:
on line 422 of Zend/Search/Lucene.php the code:</p>

<p>$numField          = $segmentsFile-&gt;readInt();</p>

<p>gives -1 on 32 bit, 4294967295 on 64 bit, reading the same index.</p>

<p>moreover, on line 425 the code</p>

<p>if ($numField != (int)0xFFFFFFFF)</p>

<p>fails, since 0xFFFFFFFF has a different value on 32 bit and 64 bit.
As workaround I changed numField to -1 and skipped the check and it works. So I think it's sufficent to change the test and the readInt function.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Piotr Gabryjeluk (gabrys) on 2009-01-20T10:01:26.000+0000</p> 
        <div class="body">
            <p>Hello guys,</p>

<p>I've just experienced this issue, quick-looked into the code and just made a patch for this. It's changing -1 to (int)0xFFFFFFFF in more places, like in other places it is done already.</p>

<p>The patch (looks like this is reverse patch, but you'll deal with it):</p>

<h1>Index: library/Zend/Search/Lucene.php</h1>

<p>--- library/Zend/Search/Lucene.php      (revision 13711)
+++ library/Zend/Search/Lucene.php      (working copy)
@@ -413,7 +413,7 @@
             if ($this-&gt;_formatVersion == self::FORMAT_2_3) {
                 $docStoreOffset = $segmentsFile-&gt;readInt();</p>

<ul><li>if ($docStoreOffset != -1) {</li>
<li>if ($docStoreOffset != (int)0xFFFFFFFF) {
                 $docStoreSegment        = $segmentsFile-&gt;readString();
                 $docStoreIsCompoundFile = $segmentsFile-&gt;readByte();</li>
</ul><h1>Index: library/Zend/Search/Lucene/Index/Writer.php</h1>

<p>--- library/Zend/Search/Lucene/Index/Writer.php (revision 13711)
+++ library/Zend/Search/Lucene/Index/Writer.php (working copy)
@@ -496,7 +496,7 @@
                     if ($srcFormat == Zend_Search_Lucene::FORMAT_2_3) {
                         $docStoreOffset = $segmentsFile-&gt;readInt();</p>

<ul><li>if ($docStoreOffset != -1) {</li>
<li>if ($docStoreOffset != (int)0xFFFFFFFF) {
                         $docStoreSegment        = $segmentsFile-&gt;readString();
                         $docStoreIsCompoundFile = $segmentsFile-&gt;readByte();</li>
</ul>
        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Piotr Gabryjeluk (gabrys) on 2009-01-20T10:06:21.000+0000</p> 
        <div class="body">
            <p>This is patch to hopefully fix the Lucene addDocument on 64bit systems. It seems it is a reverse patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Piotr Gabryjeluk (gabrys) on 2009-02-15T05:52:01.000+0000</p> 
        <div class="body">
            <p>Any information on this, ZF team?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-06-19T04:44:27.000+0000</p> 
        <div class="body">
            <p>Fixed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Piotr Gabryjeluk (gabrys) on 2009-06-19T15:25:12.000+0000</p> 
        <div class="body">
            <p>This: <a href="http://framework.zend.com/code/viewrep/Zend_Framework/standard/trunk/library/Zend/Search/Lucene.php?r1=15946&amp;r2=16167">http://framework.zend.com/code/viewrep/…</a>
seams to include what I suggested.</p>

<p>I'll test it. Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by John (bj) on 2010-05-03T03:19:11.000+0000</p> 
        <div class="body">
            <p>Hello guys, I need your help.</p>

<p>I've installed Drupal (<a href="http://drupal.org/">http://drupal.org/</a>), module Search Lucene API (<a href="http://drupal.org/project/luceneapi">http://drupal.org/project/luceneapi</a>) with Zend Framework components (<a href="http://drupal.org/node/521604">http://drupal.org/node/521604</a>) and module Search Lucene DidYouMean (<a href="http://drupal.org/project/luceneapi_dym">http://drupal.org/project/luceneapi_dym</a>). First partial indexings were successful, but now "Index statistics" for Search Lucene DidYouMean is: "Number of documents in index: 13500; Number of terms: 90598", and I'm getting "Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 71 bytes) in /var/www/<strong><em>/data/www/</em></strong>/modules/luceneapi_dym/luceneapi_dym.index.inc on line 64" when I'm trying to perform indexing.
Replacing -1 with (int)0xFFFFFFFF, as you suggested, doesn't solve a problem. Applying fixes from <a href="http://framework.zend.com/code/viewrep/Zend_Framework/standard/trunk/library/Zend/Search/Lucene.php?r1=15946&amp;r2=16167">http://framework.zend.com/code/viewrep/…</a> makes search inoperative. Replacing library folder with one, extracted from <a href="http://framework.zend.com/download/latest">http://framework.zend.com/download/latest</a>, too.</p>

<p>Please upload to somewhere an archive, which I should to use instead of Zend Framework components (<a href="http://sourceforge.net/projects/luceneapi">http://sourceforge.net/projects/luceneapi</a>) to get things working. Or give me to know what I need to change in code. I'll be very grateful!</p>

        </div>
    </div>
    </div>

