<h2>ZF-4717: Zend_Form_Element  issue in _loadFilter  method when you use Zend_Filter with  an &quot;options&quot; array  </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-27T02:46:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-07T09:04:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>considering this Zend_Form class</p>

<p>class MyForm extends Zend_Form</p>

<p>public function __construct () {</p>

<p>...</p>

<p>/* country is a Zend_Form_Element_Text object */
$this-&gt;country
     -&gt;addFilter('AutocompleteHelper', array('minlength' =&gt; 2, 'url' =&gt; '/json/coutries'));</p>

<p>}</p>

<p>...</p>

<p>}</p>

<p>As you can see I add a filter to  text field with  options associative array. 
Zend_Form_Element class doesn't instance well the Zend_Filter object and during the initializing phase it loose "options" parameters.</p>

<p>To solve this  I've change the way how  Zend_Filter is initialized on line 1920 (_loadFilter method) of Zend_Form_Element class</p>

<pre><code>        if ($r-&gt;hasMethod('__construct')) {
            $instance = new $name($filter['options']);
            //$instance = $r-&gt;newInstanceArgs($filter['options']);
        } else {
            $instance = new $name();
            //$instance = $r-&gt;newInstance();
        }
</code></pre>

<p>Regards</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-07T09:03:56.000+0000</p> 
        <div class="body">
            <p>Simply wrap your associative array in another array:</p>

<pre class="highlight"><code>
$this-&gt;country-&gt;addFilter('AutocompleteHelper', array(array('minlength' =&gt; 2, 'url' =&gt; '/json/countries')));
</code></pre>

        </div>
    </div>
    </div>

