<h2>ZF-4870: Zend_Tool - Wrong exception class thrown in ZendL_Tool_Rpc_Endpoint_Abstract</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-11-07T15:04:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-24T11:03:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In class  in method  there are two lines:</p>

<p>throw new ZendL_Tool_Endpoint_Exception('Endpoint failed to setup the action name.');
throw new ZendL_Tool_Endpoint_Exception('Endpoint failed to setup the provider name.');</p>

<p>these should probably be:</p>

<p>throw new ZendL_Tool_Rpc_Endpoint_Exception('Endpoint failed to setup the action name.');
throw new ZendL_Tool_Rpc_Endpoint_Exception('Endpoint failed to setup the provider name.');</p>

<p>(Zend_Tool from 1.6.2 Bundle)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-11-07T23:22:47.000+0000</p> 
        <div class="body">
            <p>Assigned to ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-02-16T22:20:12.000+0000</p> 
        <div class="body">
            <p>Set component</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-04-24T11:03:11.000+0000</p> 
        <div class="body">
            <p>This was fixed in previous incarations where RPC was renamed to the "Client".</p>

<p>Please see that your needs are met within the Zend_Tool_Framework_Client system.</p>

        </div>
    </div>
    </div>

