<h2>ZF-4500: testGetAdapter(Zend_TranslateTest) unit tests error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-06T07:48:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
4) testGetAdapter(Zend_TranslateTest)
Zend_Exception: File "xmltm.php" does not exist or class "xmltm" was not found in the file
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/Translate.php:91
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/Translate.php:72
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-06T14:20:25.000+0000</p> 
        <div class="body">
            <p>A sort of case dependency... I wonder why this have not shown up before.
Should be fixed with r11709</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-08T04:00:54.000+0000</p> 
        <div class="body">
            <p>Yes, fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:17.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

