<h2>ZF-4480: testBasic(Zend_Validate_File_IsCompressedTest)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-03T11:24:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
32) testBasic(Zend_Validate_File_IsCompressedTest)
Failed asserting that  matches expected value .
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-03T13:35:42.000+0000</p> 
        <div class="body">
            <p>Why is this component assigned to Wil ???
What is the dev-branch 1.7 ?</p>

<p>I can't find it in SVN... how should I solve this when no branch is available ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-04T03:16:32.000+0000</p> 
        <div class="body">
            <p>I can not verify this on my environment.</p>

<p>I increased the faliure output.
Can you please verify this on your environment ?</p>

<p>A possible reason is that this test is related to the fileinfo component.
And therefor fully depends on the used magic.mime file.
Probably the 'zip' mimetype can not be detected by your environment. We will see on the added output where the problem is.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-08T04:06:18.000+0000</p> 
        <div class="body">
            <p>Updated output:</p>

<p>{panel}
26) testBasic(Zend_Validate_File_IsCompressedTest)
Tested with array (
  0 =&gt; NULL,
  1 =&gt; true,
)
Failed asserting that  matches expected value .
{panel}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-10T11:50:05.000+0000</p> 
        <div class="body">
            <p>Silly me...
I forgot to add the file which is tested against. :-)</p>

<p>Should work now with latest trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-10T12:47:07.000+0000</p> 
        <div class="body">
            <p>Fixed!</p>

<p>Also merged fixes into release-1.6 branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:16.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

