<h2>ZF-4001: Zend_Paginator_Adapter_DbSelect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-08-19T19:10:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-10T19:18:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mina R Waheeb (mina)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have two issues in the Zend_Paginator_Adapter_DbSelect class :</p>

<p>1- The class checks  if (!isset($result[self::ROW_COUNT_COLUMN])) then throw excpetion, why? some databases like MySQL when inner joining empty tables returns empty record set which makes the adapter fails. It should not throw exception just set the row count to zero is fair enough.</p>

<p>Example: SELECT COUNT(*) FROM ANY_EMPTY_TABLE GROUP BY TABLE_PRIMARY_KEY; // this will return empty record set</p>

<p>2- The class fetch the count by reseting Zend_Db_Select::COLUMNS, Zend_Db_Select::ORDER and Zend_Db_Select::LIMIT_OFFSET. Also should clear the Zend_Db_Select::GROUP, Because some databases or all! return a count of each group as a recordset. The count function mainly effected by the GROUP BY modifier.</p>

<p>Example: SELECT COUNT(*) from NONE_EMPTY_TABLE GROUP BY TABLE_PRIMARY_KEY; //a count for each pk group</p>

<p>For more information <a href="http://dev.mysql.com/doc/refman/5.0/en/counting-rows.html">http://dev.mysql.com/doc/refman/…</a></p>

<p>Unfortunately, Removing the GROUP BY modifier in most cases will give invalid count of rows.</p>

<p>Benjamin Gonzales solution is PERFECT.</p>

<p>Between I HAVE NO COMMENT OPTION :( I only have (Edit, Convert, Vote, Worklog and Google) in the left nav, Its really wired positioning ;)</p>

<p>Thanks</p>

<p>PS: There is no way to comment on the issue just editing it? :)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-08-20T00:08:35.000+0000</p> 
        <div class="body">
            <p>Could you perhaps give an example of the first problem? What tables (with how much data) do you have an what query do you have?</p>

<p>As for the second issues.. you're saying a GROUP BY can return multiple rows, even if the query only selectes COUNT(*) AS zend_paginator_row count? Again, an example would be greatly appreciated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-08-20T06:28:03.000+0000</p> 
        <div class="body">
            <p>Yes there is a comment option, without editing. It's just well hidden in the left nav-bar ; )</p>

<p>For the non-empty table Benjamin Gonzales suggested the following on the Wiki:</p>

<pre class="highlight"><code>
public function count(){    
        if ($this-&gt;_rowCount === null){    
            $rowCount   = clone $this-&gt;_select;    
            
            $group = implode(",",$rowCount-&gt;getPart(Zend_Db_Select::GROUP));    
            $expression =  empty($group) ? "COUNT(*)" : "COUNT(DISTINCT $group)" ;    
            $expression =  new Zend_Db_Expr($expresion .' AS '. self::ROW_COUNT_COLUMN);    
               
               
            $rowCount-&gt;reset(Zend_Db_Select::COLUMNS)    
                     -&gt;reset(Zend_Db_Select::ORDER)    
                     -&gt;reset(Zend_Db_Select::GROUP)    
                     -&gt;columns($expression);    
                        
            $this-&gt;setRowCount($rowCount);    
        }    
        return $this-&gt;_rowCount;    
    } 
</code></pre>

<p>I'm going to look at implementing a similar solution.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-08-20T08:14:00.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 10942</p>

        </div>
    </div>
    </div>

