<h2>ZF-483: [Improvement] Fewer parameters for Zend_Cache factory</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-11-03T21:17:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-19T13:23:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Wouldn't it be better to set the frontend and backend types in the parameter arrays themselves?  Then you could simply have two parameters, not four:</p>

<p>```</p>

<p>You might use "type" as the array key for Core, File, etc.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2006-11-04T04:02:37.000+0000</p> 
        <div class="body">
            <p>I won't change the API for a question of taste :)</p>

<p>The syntax with 4 parameters is more clear for me</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2006-11-27T13:39:45.000+0000</p> 
        <div class="body">
            <p>Fair enough.  ;)  Just a suggestion.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-19T13:23:32.000+0000</p> 
        <div class="body">
            <p>Bookkeeping. Closing old issues and assigning them to the person who ultimately resolved the issue.</p>

        </div>
    </div>
    </div>

