<h2>ZF-4475: Set of unit tests problems with listed languages</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-03T11:09:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
16) testList(Zend_Translate_Adapter_TbxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [fr] =&gt; fr
 )</p>

<p>17) testOptionLocaleDirectory(Zend_Translate_Adapter_TbxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -2,5 +2,4 @@
 (
     [en] =&gt; en
     [fr] =&gt; fr
-    [de] =&gt; de
 )</p>

<p>18) testOptionLocaleFilename(Zend_Translate_Adapter_TbxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -2,5 +2,4 @@
 (
     [en] =&gt; en
     [fr] =&gt; fr
-    [de] =&gt; de
 )
{panel}
.......
{panel}
20) testList(Zend_Translate_Adapter_TmxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [fr] =&gt; fr
 )</p>

<p>21) testOptionLocaleDirectory(Zend_Translate_Adapter_TmxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,6 +1,5 @@
 Array
 (
-    [de] =&gt; de
     [en] =&gt; en
     [fr] =&gt; fr
 )</p>

<p>22) testOptionLocaleFilename(Zend_Translate_Adapter_TmxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,6 +1,5 @@
 Array
 (
-    [de] =&gt; de
     [en] =&gt; en
     [fr] =&gt; fr
 )
{panel}
........
{panel}
24) testList(Zend_Translate_Adapter_XliffTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [fr] =&gt; fr
 )</p>

<p>25) testOptionLocaleDirectory(Zend_Translate_Adapter_XliffTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,6 +1,5 @@
 Array
 (
-    [de] =&gt; de
     [en] =&gt; en
     [fr] =&gt; fr
 )</p>

<p>26) testOptionLocaleFilename(Zend_Translate_Adapter_XliffTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,6 +1,5 @@
 Array
 (
-    [de] =&gt; de
     [en] =&gt; en
     [fr] =&gt; fr
 )
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-08T12:14:16.000+0000</p> 
        <div class="body">
            <p>Probably fixed with r11751</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-09T01:32:49.000+0000</p> 
        <div class="body">
            <p>Yes, fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:19.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

