<h2>ZF-4316: Assigning values to Zend_Dojo_Form_Elements on $form-&gt;populate()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-17T05:29:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-20T10:20:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using $form-&gt;populate() does not assign values to the Dojo form elements, such as DateTextBox and TimeTextBox, treating them as a usual TextBox elements.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-05T12:19:16.000+0000</p> 
        <div class="body">
            <p>I'm not sure what you mean. I personally see values in those fields after populate() or isValid() are called.</p>

<p>Please provide a reproduce case, the expected results, and the actual results; otherwise, I will close this ticket as incomplete.</p>

        </div>
    </div>
    </div>

