<h2>ZF-4962: An iterator cannot be used with foreach by reference</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-11-17T06:52:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-08T07:47:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Endi (e_hunter)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have some construction like this:</p>

<p>$_paginator = Zend_Paginator::factory($query);
$_paginator-&gt;setCurrentPageNumber($page);
$items = $_paginator-&gt;setItemCountPerPage($perPage);</p>

<p>foreach ($items as &amp;$item) {
    $item['some_key'] = 'some value'
}</p>

<p>Until revision 11970 - this works fine
After revision 11970 - throw an exception:: "An iterator cannot be used with foreach by reference"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-11-17T12:00:11.000+0000</p> 
        <div class="body">
            <p>That error appears since PHP 5.2.
It's not a ZF problem, I think it's a PHP version problem. Anyway, since PHP5.2 : An iterator cannot be used with foreach by reference</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2008-12-09T13:12:59.000+0000</p> 
        <div class="body">
            <p>Endi, could you discuss your use case here?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-12-23T11:05:12.000+0000</p> 
        <div class="body">
            <p>Postponing this issue, since it appears to be a PHP problem instead of a Paginator problem. Please update this issue if this actually is a Paginator issue .</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2009-06-08T07:47:57.000+0000</p> 
        <div class="body">
            <p>As this issue hasn't been updated in six months and it's reported to be a PHP change, I'm closing it.</p>

        </div>
    </div>
    </div>

