<h2>ZF-4739: ' ' strings as nulls</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-29T07:08:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-29T08:03:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gonzalo (gonzalo123@gmail.com)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Adapter_Oracle</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Probably it is a bug of PDO_OCI instead of  ZF adapter but affets to ZF. 
If you want to insert one space into one table with a not null column, you get the exception:</p>

<p>{panel:title=Error| borderStyle=dashed| borderColor=#ccc| titleBGColor=#F7D6C1| bgColor=#FFFFCE} 
SQLSTATE[HY000]: General error: 1400 OCIStmtExecute: ORA-01400: cannot
insert NULL into ("WEB"."TBLDUMMY"."COL1")
 (/opt/PDO_OCI-1.0/oci_statement.c:142)
{panel}</p>

<p>I know Oracle behaviour with nulls and blank strings, but here there is not a blank string. Apparently PDO does a rtrim when you bind a variable and as far as I know there is not possible to avoid this 'feature'.</p>

<p>Some comercial applications do not uses ' ' instead '' or null values (thinking in multidatabase applicacions). It is a bit nightmare use those tables with Zend_DB</p>

<p>This is an example of code to get the error:</p>

<pre class="highlight"><code>
// create table WEB.TBLDUMMY (COL1 VARCHAR2(3) not null)
try {
    $db = new Zend_Db_Adapter_Pdo_Oci(array(
        'host'     =&gt; '**',
        'username' =&gt; '**',
        'password' =&gt; '**',
        'dbname'   =&gt; '**'
    ));
    $db-&gt;insert('WEB.TBLDUMMY', array('COL1'  =&gt; ' ', /* one space */ ));
} catch (Exception $e) {
    echo $e-&gt;getMessage();
}
</code></pre>

<p>I have reported the bug to PDO
[PECL-BUG] Bug #14915</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gonzalo (gonzalo123) on 2009-05-29T02:13:35.000+0000</p> 
        <div class="body">
            <p>Solved. Not a ZF BUG. Solved in PHP 5.2.9</p>

<p>Bug #14915</p>

        </div>
    </div>
    </div>

