<h2>ZF-4246: Zend_Db_Table_Row_Abstract adds ZEND_DB_ROWNUM to data on _refresh()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-11T01:40:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-13T05:56:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Roger Hunwicks (rhunwicks)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2243">ZF-2243</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Db_Table_Row_Abstract-&gt;_refresh() adds ZEND_DB_ROWNUM to the $this-&gt;_data and $this-&gt;_cleanData arrays.</p>

<p>I am saving a row to the database as part of a transaction (which succeeds and adds ZEND_DB_ROWNUM to the fields). If the subsequent $dbAdapter()-&gt;commit() fails, I want to save the row so that I can retrieve the values in the next request cycle.</p>

<p>When you try and reconnect the row to the database using $row-&gt;setTable(), or $row-&gt;setFromArray() you get an error because ZEND_DB_ROWNUM isn't in the list of columns for the table.</p>

<p>Either Zend_Db_Table_Abstract() should remove the ZEND_DB_ROWNUM from the _data and _cleanData arrays, or Zend_Db_Table-&gt;fetchRow() should.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-10-04T03:39:47.000+0000</p> 
        <div class="body">
            <p>Could be fixed in conjunction of ZF-2243</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-10-19T03:36:01.000+0000</p> 
        <div class="body">
            <p>testStatementFetchColumnEmptyResult in Zend_Db_Statement_OracleTest fails because of this issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-01-24T00:29:08.000+0000</p> 
        <div class="body">
            <p>Fixed in SVN13759 for Oracle and Pdo_Oci
Additional tests must follow to close this issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-04-29T02:08:23.000+0000</p> 
        <div class="body">
            <p>Current tests cover the functionality for Oracle's adapter</p>

        </div>
    </div>
    </div>

