<h2>ZF-4476: testErrorMessagesAreTranslatedWhenTranslatorPresent(Zend_Validate_AbstractTest) unit tests failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-03T11:19:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
28) testErrorMessagesAreTranslatedWhenTranslatorPresent(Zend_Validate_AbstractTest)
Failed asserting that  contains "This is the translated message for ".
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-06T13:09:44.000+0000</p> 
        <div class="body">
            <p>Zend_Validate is not my component... false assignment of issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-08T05:19:18.000+0000</p> 
        <div class="body">
            <p>Occures only if whole ZF unit tests set is passed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-08T05:22:32.000+0000</p> 
        <div class="body">
            <p>Problem doesn't occure if Zend_Translate tests are turned off</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-08T12:13:10.000+0000</p> 
        <div class="body">
            <p>Probably fixed with r11751</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-09T01:31:21.000+0000</p> 
        <div class="body">
            <p>Yes, fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:04.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

