<h2>ZF-4619: isLocale needs changes related to BC problems</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-10-16T14:11:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:09:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to discussion of SL-13 isLocale needs to be slightly adpoted:</p>

<p>Method:
isLocale()</p>

<p>Solution:
STATIC PROPERTY SET TO TRUE BUT THROWING A NOTICE WHEN TRUE... TRUE = OLD BEHAVIOUR, FALSE = NEW BEHAVIOUR</p>

<p>Information:
There are several things to make sure.
isXXX functions should generally only return boolean regarding to OOP and Coding Standard.
Returning a object was a thing which I used to add for internal reasons.
This is no longer needed as rerouting has been added so it is automatically be done by all I18N classes.
Also there is another solution:
We could add a static boolean option/property 'CREATE_LOCALE_ON_VALIDATION'.
A simple note to set this property on true for old behaviour should be ok, shouldn't it ?
Because returning an object on a boolean function is really a bad bad behaviour.
And we should get rid of this false behaviour as soon as we can.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-17T15:04:34.000+0000</p> 
        <div class="body">
            <p>Implemented with r12003</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:09:58.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

