<h2>ZF-4105: Check if German Zend_Soap_Autodiscovery documentation needs update.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2008-08-28T04:27:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T11:56:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Client</li>
            <li>Zend_Soap_Server</li>
            <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Soap_Autodiscovery documentation was merged into one 'sect1' section.</p>

<p>So it was necessary to update manual.xml.in files to keep them in a consistent state (otherwise it broke build for the languages which didn't have Zend_Soap_Autodiscovery documentation translated).</p>

<p>That, in turn, required German documentation section for Zend_Soap_Autodiscovery to be merged.</p>

<p>It made 'de/module_specssZend_Soap_AutoDiscovery.xml' file newer than 'de/module_specssZend_Soap_AutoDiscovery.xml'  so it's not presented by the <a href="http://framework.zend.com/manual/status">Documentation status</a> page as 'need to be translated".</p>

<p>This issue is created to check if French Zend_Soap_Autodiscovery documentation needs update.</p>

<p>See <a href="http://fw02.zend.com:8060/code/changelog/Zend_Framework?cs=11097">cs-11097</a> for the details.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-02T11:56:02.000+0000</p> 
        <div class="body">
            <p>German docu fixed</p>

        </div>
    </div>
    </div>

