<h2>ZF-472: Zend_Pdf docs/demo creates race condition</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2006-11-02T07:18:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mark Tyndall (mark.tyndall)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>ZendFramework-0.2.0/documentation/end-user/core/en/zend.pdf.usage.html</p>

<p>gives an example of the Zend_Pdf module usage. It includes the lines:</p>

<pre class="highlight"><code>
if (file_exists($argv[1])) {
    $pdf = Zend_Pdf::load($argv[1]);
} else {
    $pdf = new Zend_Pdf();
}
</code></pre>

<p>which encourages users to introduce race conditions into their file-opening code, rather than using Exceptions:</p>

<pre class="highlight"><code>
try {
    $pdf = Zend_Pdf::load($argv[1]);
} catch (Exception $e) {
# we only care whether $argv[1] is the name of a loadable PDF file *when we call a function to load it*,
# not $variable microseconds before that time.
    $pdf = new Zend_Pdf();
}
</code></pre>

<p>NB: the documentation describes the demo at:
ZendFramework-0.2.0/demos/Zend/Pdf/demo.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:26:53.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.6.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-03-06T16:44:17.000+0000</p> 
        <div class="body">
            <p>Fixed.</p>

        </div>
    </div>
    </div>

