<h2>ZF-4011: Wrong naming of Word Filter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-08-20T06:33:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-26T14:22:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter_Inflector</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In some places in the manual where Zend_Filter_Inflector is explained. There are pieces of example code tha tlook like this.</p>

<p><a href="http://framework.zend.com/manual/en/zend.layout.advanced.html#zend.layout.advanced.inflector">http://framework.zend.com/manual/en/…</a></p>

<p>$inflector-&gt;setRules(array(
    ':script' =&gt; array('CamelCaseToUnderscore'),
    'suffix' =&gt; 'phtml'
));</p>

<p>This however triggers an error :</p>

<p>Zend_Loader_PluginLoader_Exception: Plugin by name CamelCaseToUnderscore was not found in the registry. in Zend\Loader\PluginLoader.php on line 370</p>

<p>Because the Filter 'CamelCaseToUnderscore is not present in the root of the Filter directory. It's inside a sub folder 'Word'. Prefixing CamelCaseToUnderscore with Word_ fixes this.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-25T16:22:36.000+0000</p> 
        <div class="body">
            <p>Ralph, is this the correct fix? If so, I will fix it in the ref guide.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-11-26T14:22:36.000+0000</p> 
        <div class="body">
            <p>fixed in trunk with r12891</p>

        </div>
    </div>
    </div>

