<h2>ZF-4554: Zend_Gdata_GdataOnlineTest::testPostRetrieveEntryAndDelete failing as of r11768</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-10T22:00:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11576/capture.txt">capture.txt</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Gdata_GdataOnlineTest::testPostRetrieveEntryAndDelete is failing on my machine:</p>

<pre class="highlight"><code>testPostRetrieveEntryAndDelete(Zend_Gdata_GdataOnlineTest)
Zend_Gdata_App_HttpException: Unable to read response, or response is empty
library/Zend/Gdata/App.php:483
library/Zend/Gdata.php:201
library/Zend/Gdata/App.php:610
library/Zend/Gdata/App.php:541
library/Zend/Gdata/App.php:159
library/Zend/Gdata.php:169</code></pre>

<p>I'm tracked the breakage to r11768. I'm currently attempting to isolate the cause.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-10-10T22:34:40.000+0000</p> 
        <div class="body">
            <p>Attaching packet capture.</p>

<p>This part is interesting:</p>

<pre class="highlight"><code>No.     Time        Source                Destination           Protocol Info
     17 0.453789    172.19.246.207        209.85.133.191        TCP      [TCP segment of a reassembled PDU]
     18 0.535081    209.85.133.191        172.19.246.207        TCP      http &gt; 49705 [ACK] Seq=1769 Ack=681 Win=7040 Len=0 TSV=3186164309 TSER=299462861
     19 0.548198    209.85.133.191        172.19.246.207        TCP      http &gt; 49706 [ACK] Seq=1 Ack=443 Win=6784 Len=0 TSV=3185779522 TSER=299462861
     20 20.454967   172.19.246.207        209.85.133.191        TCP      49706 &gt; http [FIN, ACK] Seq=443 Ack=1 Win=524280 Len=0 TSV=299463061 TSER=3185779522</code></pre>

<p>It seems that my client begins a request, the server ACKs, and then nothing happens for 20 seconds until my client sends a FIN.</p>

<p>(172.19.246.207 = me, 209.85.133.191 = remote server)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-10-10T23:10:40.000+0000</p> 
        <div class="body">
            <p>Alright, it seems that there's a problem has to do with the Content-Length HTTP header.</p>

<p>If, in Zend_Http_Client, I change:</p>

<pre><code>const CONTENT_LENGTH = 'Content-Length';
</code></pre>

<p>to:</p>

<pre><code>const CONTENT_LENGTH = 'content-length';
</code></pre>

<p>then the test passes. (This would be a partial revert of r11768.)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-10-11T00:34:31.000+0000</p> 
        <div class="body">
            <p>Moving to component Zend_Http_Client.</p>

<p>The problem was that Zend_Http_Client's internal header's array is indexed by lowercase header names, regardless of the actual header. The changes in r11768 were looking up headers using a non-normalized name, which would always fail.</p>

<p>Fixed in r11857.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-11T13:02:21.000+0000</p> 
        <div class="body">
            <p>Fixed also for the 1.6.2 (r11880).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:30.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

