<h2>ZF-4447: testDestinationMutatorsShouldProxyToTransferAdapter(Zend_Form_Element_FileTest) Unit tests error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-02T03:20:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-02T12:16:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
1) testDestinationMutatorsShouldProxyToTransferAdapter(Zend_Form_Element_FileTest)
Zend_File_Transfer_Exception: The given destination is no directory or does not exist
/home/cawa/ZendFramework/svn/framework/branches/release-1.6/library/Zend/Form/Element/File.php:379
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-02T12:16:02.000+0000</p> 
        <div class="body">
            <p>Fixed with r11601.</p>

        </div>
    </div>
    </div>

