<h2>ZF-4949: Incorrect handling of delegation to LiveJournal</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-11-14T04:17:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-18T07:41:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ciaran McNulty (ciaranmcnulty)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth_Adapter_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have delegated my site's (ciaranmcnulty.com) OpenID to my LiveJournal account with the following in the head of the html:</p>

<pre><code>&lt;meta http-equiv="X-XRDS-Location" content="http://ciaranmcnulty.livejournal.com/" /&gt;
&lt;link rel="openid.server" href="http://&lt;a rel="nofollow" href="www.livejournal.com/openid/server.bml"&gt;www.livejournal.com/openid/server.bml&lt;/a&gt;" /&gt;
&lt;link rel="openid.delegate" href="http://ciaranmcnulty.livejournal.com/" /&gt;
</code></pre>

<p>I used the example code from the reference guide to create a simple OpenID login page.  However, the identity returned by the adapter varies:</p>

<ol><li>If I'm already authenticated with LiveJournal my identity is returned (correctly) as <a href="http://ciaranmcnulty.com">http://ciaranmcnulty.com</a></li>
<li>If I am logged out of LiveJournal and need to authenticate, my identity is returned as <a href="http://ciaranmcnulty.livejournal.com">http://ciaranmcnulty.livejournal.com</a></li>
</ol><p>I believe it should be the same in both cases, i.e. delegation should be transparent to users of the adapter.</p>

<p>It may be that this is an error at the LJ end rather than in the component and I'm happy to report it to LJ if that is the case.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ciaran McNulty (ciaranmcnulty) on 2008-11-14T08:34:35.000+0000</p> 
        <div class="body">
            <p>As an additional data point, I can log into another OpenID site (stackoverflow.com) with my ciaranmcnulty.com OpenID and it recognises me as ciaranmcnulty.com even if I've had to log in at LiveJournal.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-02-18T07:41:43.000+0000</p> 
        <div class="body">
            <p>Can you provide some bits of code that can better demonstrate the issue?
I am inclined to say that the LJ implementation might be triggering the behavior you are seeing.  If this is still an issue for you, please attach a reproduction case and reopen.</p>

        </div>
    </div>
    </div>

