<h2>ZF-4567: Unittests error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-11T14:43:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-14T09:57:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Tested under WinXP, PHP5.2.5, r11871</p>

<pre class="highlight"><code>
4) testRoutePerformance(Zend_Controller_Router_RouteTest)
This test may be failing on slow systems and shouldn't be failing on production.
 Tests if 1000 complicated routes can be matched in a tenth of a second. Actual
test matches 10000 times to make the test more reliable.
Failed asserting that </code></pre>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-10-14T06:51:45.000+0000</p> 
        <div class="body">
            <p>Assigning to Martel</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2008-10-14T09:57:05.000+0000</p> 
        <div class="body">
            <p>Not an issue. As per unit test failure description. This unit test guards routing performance.</p>

        </div>
    </div>
    </div>

