<h2>ZF-4379: Fail to validate empty array</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-25T08:28:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-05T23:13:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Felix De Vliegher (felixdv)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter_Input</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11710">ZF-11710</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It's possible to make an empty array pass as a valid Int or any other type of validation because the validation step is completly skip in Zend_Filter_Input.</p>

<p>&lt;?php
set_include_path('../library/ZendFramework/' . PATH_SEPARATOR . get_include_path());</p>

<p>require_once "Zend/Loader.php"; 
Zend_Loader::registerAutoload();
$validator = array(
    'age' =&gt; array(
        'presence' =&gt; 'required',
        'Int'
    )
);</p>

<p>$data = array(
    'age' =&gt; array()
);</p>

<p>$input = new Zend_Filter_Input(null, $validator, $data, array(Zend_Filter_Input::ALLOW_EMPTY =&gt; false));</p>

<p>if ( $input-&gt;isValid() ) {
    echo 'Age ';
    var_dump($data['age']);
    echo ' is valid!';
} else {
    echo 'Age is not valid';
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Felix De Vliegher (felixdv) on 2008-11-08T06:49:05.000+0000</p> 
        <div class="body">
            <p>Fixed in revision #12430.
Fix empty array validation with Zend_Filter_Input.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:09:58.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

