<h2>ZF-4397: getLastRequest() when _request is AJAXed`</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-09-27T05:20:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Radek Antoniuk (warden)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>It would be very useful to have a possibility of having this while using with AJAX requests, i.e.
when AJAX request is invoked then two fields are set in $_SERVER:
HTTP_REFERER
and 
[HTTP_X_REQUESTED_WITH] =&gt; XMLHttpRequest</p>

<p>and HTTP_REFERER contains the original page URI that is in browser.
This is useful when I am having tabs that are being fed with HTML AJAX output and I want to render the proper viewscript basing on the page that I am really on (and not on the request itself where I don't have the information about the controller/action that is requesting by AJAX)</p>

<p>A sample implementation in the Controller's init():</p>

<pre><code>if (isset($_SERVER["HTTP_REFERER"])){
  preg_match('#&lt;a rel="nofollow" href="http://[^/]+/"&gt;http://[^/]+/&lt;/a&gt;([^/]+)/([^/]+)/(.+)#',$_SERVER["HTTP_REFERER"],$matches);
  $params = array();
  foreach ((array)split("/",$matches[3]) as $val){
    if (isset($param)) {
      $param[key($param)] = $val;
      $params[] = $param;
      unset($param);
    }else {
      $param = array($val=&gt;null);
    }  
  }
  $this-&gt;origRequest["controller"] = $matches[1];
  $this-&gt;origRequest["action"] = $matches[2];
  $this-&gt;origRequest["params"] = $params;
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:39.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

