<h2>ZF-465: Redirection handler issue in Zend_Http_Client</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-10-30T05:41:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Some requests can cause a redirection loop.
I try to make a GET request on the url: <a href="http://bonnetdane.midiblogs.com/">http://bonnetdane.midiblogs.com/</a>.
In this case, the Zend_Http_Client sends a request for the URI "/?".
The call returns a redirection to the url: <a href="http://bonnetdane.midiblogs.com/index.html">http://bonnetdane.midiblogs.com/index.html</a> so the Zend_Http_Client send another request for the URI "/index.html?".
The calls returns a redirection to the url: <a href="http://bonnetdane.midiblogs.com/index.html">http://bonnetdane.midiblogs.com/index.html</a> and so on.
However, if the request is for the URI "/index.html" the server does not send back a redirection answer.
I have tried to use the new Zend_Http_Client in the incubator but there is the same issue.</p>

<p>A small example to show the problem with netcat:</p>

<p>$ nc bonnetdane.midiblogs.com 80
GET /? HTTP/1.0
Host: bonnetdane.midiblogs.com</p>

<p>HTTP/1.1 302 Found
Date: Mon, 30 Oct 2006 10:36:24 GMT
Server: Apache
Vary: Host
Location: <a href="http://bonnetdane.midiblogs.com/index.html">http://bonnetdane.midiblogs.com/index.html</a>
Connection: close
Content-Type: text/html; charset=utf-8</p>

<p>$ nc bonnetdane.midiblogs.com 80
GET /index.html? HTTP/1.0
Host: bonnetdane.midiblogs.com
Connection: close</p>

<p>HTTP/1.1 302 Found
Date: Mon, 30 Oct 2006 10:43:19 GMT
Server: Apache
Vary: Host
Location: <a href="http://bonnetdane.midiblogs.com/index.html">http://bonnetdane.midiblogs.com/index.html</a>
Connection: close
Content-Type: text/html; charset=utf-8</p>

<p>$ nc bonnetdane.midiblogs.com 80
GET /index.html HTTP/1.0
Host: bonnetdane.midiblogs.com
Connection: close</p>

<p>HTTP/1.1 200 OK
Date: Mon, 30 Oct 2006 10:44:23 GMT
Server: Apache
Vary: Host
Last-Modified: Mon, 30 Oct 2006 10:44:28 GMT
Connection: close
Content-Type: text/html; charset=utf-8</p>

<p>ofollow" href="www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"&gt;www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"&gt;
[...]</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2006-10-30T15:21:09.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>Do you have any possibility to test the issue with the incubator version of the Http_Client ? 
It will soon replace the old Http_Client, and I would like to spend as much less time as possible on fixing bugs in the old client.</p>

<p>Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:24:58.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.6.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2006-11-21T07:07:42.000+0000</p> 
        <div class="body">
            <p>Does not happen in the incubator version r. 1799</p>

        </div>
    </div>
    </div>

