<h2>ZF-4970: Zend_Dojo_Form_Element_CheckMultiSelect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-11-17T23:30:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-23T13:21:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthias Sch. (matthias-sch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>please include this form element:
<a href="http://archive.dojotoolkit.org/nightly/dojotoolkit/dojox/form/tests/test_CheckedMultiSelect.html">http://archive.dojotoolkit.org/nightly/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Atul Shrivastava (atulshr) on 2009-02-19T09:04:13.000+0000</p> 
        <div class="body">
            <p>Please let me know by when can this be fixed. Its required to use multiple checkboxes which is a standard use case.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-02-19T09:46:52.000+0000</p> 
        <div class="body">
            <p>Actually, we're typically not going to support dojox features from Zend_Dojo, as their stability cannot be counted on.</p>

<p>There are features for 1.8 that will make it potentially possible for you to consume arbitrary dijits/dojox components, as well as make it easy to create your own view helpers for targettting them.</p>

<p>At this point, I'm closing the issue, as it's not likely we will directly implement the component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Atul Shrivastava (atulshr) on 2009-02-23T12:16:19.000+0000</p> 
        <div class="body">
            <p>When is ver 1.8 released?
I didn't see the dates in the calender for 1.8
If you specify the date, I can schedule things accordingly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-02-23T13:21:01.000+0000</p> 
        <div class="body">
            <p>Please note that I said we'll have a helper for consuming <em>arbitrary</em> dijits ready for 1.8, not for the requested dijit. 1.8 will likely be sometime in April, but we do not have a hard date yet.</p>

<p>BTW, we are open to having dojox view helpers/form elements/decorators in ZendX; we simply won't be supporting them directly with the standard library.</p>

        </div>
    </div>
    </div>

