<h2>ZF-4364: Using SkipData info to improve search performance</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2008-09-23T10:48:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-04T13:36:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Each term within an index has a list of matched documents.
This list may be large enough and it may take a long time to load it.</p>

<p>This list also has some additional subindex known as "skip data". This info allows to check directly if some document matches specified term.</p>

<p>Zend_Search_Lucene should use skipData to optimize search performance.</p>

<p>That may be done by reordering of subsearches execution.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T13:36:27.000+0000</p> 
        <div class="body">
            <p>I believe this was implemented for 1.7. If not, please reopen, Alex.</p>

        </div>
    </div>
    </div>

