<h2>ZF-4096: Incorrect code example for Zend_Dojo_View_Helper_TabContainer</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-08-27T16:00:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-09T12:19:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Nick Daugherty (nd987)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the documentation for using Zend_Dojo's Dijit layout helpers, the code example for using the tabContainer() helper incorrectly shows the code example for stackContainer(), which was the previous example. Here is the link <a href="http://framework.zend.com/manual/en/zend.dojo.view.html#zend.dojo.view.dijit.layout">http://framework.zend.com/manual/en/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-09T12:19:33.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.6 release branch.</p>

        </div>
    </div>
    </div>

