<h2>ZF-4564: Unittests error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-11T14:36:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Tested under WinXP, PHP5.2.5</p>

<pre class="highlight"><code>
5) testFactoryReturnsDbSelectAdapter(Zend_PaginatorTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Select.php:639
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Paginator\Adapter\DbSelect.php
:112
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Paginator\Adapter\DbSelect.php
:186
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Paginator.php:772
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Paginator.php:546
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Paginator.php:365
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Paginator.php:263

6) testGetsItemsAtOffsetZero(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

7) testGetsItemsAtOffsetTen(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

8) testAcceptsIntegerValueForRowCount(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

9) testThrowsExceptionIfInvalidQuerySuppliedForRowCount(Zend_Paginator_Adapter_D
bSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

10) testAcceptsQueryForRowCount(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

11) testThrowsExceptionIfInvalidRowCountValueSupplied(Zend_Paginator_Adapter_DbS
electTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

12) testReturnsCorrectCountWithAutogeneratedQuery(Zend_Paginator_Adapter_DbSelec
tTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

13) testDbTableSelectDoesNotThrowException(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

14) testGroupByQueryReturnsOneRow(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

15) testGroupByQueryOnEmptyTableReturnsRowCountZero(Zend_Paginator_Adapter_DbSel
ectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

16) testGroupByQueryReturnsCorrectResult(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

17) testDistinctColumnQueryReturnsCorrectResult(Zend_Paginator_Adapter_DbSelectT
est)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

18) testSelectSpecificColumns(Zend_Paginator_Adapter_DbSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

19) testSelectDistinctAllUsesRegularCountAll(Zend_Paginator_Adapter_DbSelectTest
)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

20) testSelectDoesReturnZendDbTableRowset(Zend_Paginator_Adapter_DbTableSelectTe
st)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

21) testGetsItemsAtOffsetZero(Zend_Paginator_Adapter_DbTableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

22) testGetsItemsAtOffsetTen(Zend_Paginator_Adapter_DbTableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

23) testAcceptsIntegerValueForRowCount(Zend_Paginator_Adapter_DbTableSelectTest)

Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

24) testThrowsExceptionIfInvalidQuerySuppliedForRowCount(Zend_Paginator_Adapter_
DbTableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

25) testAcceptsQueryForRowCount(Zend_Paginator_Adapter_DbTableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

26) testThrowsExceptionIfInvalidRowCountValueSupplied(Zend_Paginator_Adapter_DbT
ableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

27) testReturnsCorrectCountWithAutogeneratedQuery(Zend_Paginator_Adapter_DbTable
SelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

28) testDbTableSelectDoesNotThrowException(Zend_Paginator_Adapter_DbTableSelectT
est)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

29) testGroupByQueryReturnsOneRow(Zend_Paginator_Adapter_DbTableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

30) testGroupByQueryOnEmptyTableReturnsRowCountZero(Zend_Paginator_Adapter_DbTab
leSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

31) testGroupByQueryReturnsCorrectResult(Zend_Paginator_Adapter_DbTableSelectTes
t)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

32) testDistinctColumnQueryReturnsCorrectResult(Zend_Paginator_Adapter_DbTableSe
lectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

33) testSelectSpecificColumns(Zend_Paginator_Adapter_DbTableSelectTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276

34) testSelectDistinctAllUsesRegularCountAll(Zend_Paginator_Adapter_DbTableSelec
tTest)
Zend_Db_Adapter_Exception: The sqlite driver is not currently installed
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:11
6
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:137
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Abstract.php:414
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Abstract.php:22
0
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Adapter\Pdo\Sqlite.php:206
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:660
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:589
C:\Voxtronic\3rdParty\Zend Framework\library\Zend\Db\Table\Abstract.php:276
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-10-11T23:59:39.000+0000</p> 
        <div class="body">
            <p>Closing as Won't Fix. These unit tests require a DB to run. SQLite is the most logical choice in this case. Please make sure you have PDO_SQLite installed for the PHP install that runs the tests.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-12T01:58:22.000+0000</p> 
        <div class="body">
            <p>According to ZF policy all tests have to run on an out-of-the-box php installation.
I used PHP 5.2.5 Win* installation without any modifications except include path.</p>

<p>So when your tests rely on a component which is not available in all OSes you must set these tests to "ignore" if the extention is not found.
Even then I would recommend to make this check in the testbed as when someone has no SqLite Database available the tests should also run without throwing errors. Setting them as ignored is the correct behaviour.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-10-12T02:00:03.000+0000</p> 
        <div class="body">
            <p>See <a href="http://www.phpunit.de/manual/3.3/en/incomplete-and-skipped-tests.html">http://phpunit.de/manual/3.3/…</a> for the correct behaviour.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-10-30T13:50:07.000+0000</p> 
        <div class="body">
            <p>Ok, fixed at r12205</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-11-03T12:48:09.000+0000</p> 
        <div class="body">
            <p>Completed with <a href="http://framework.zend.com/code/changelog/Zend_Framework/?cs=12278">SVN12278</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:24.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

