<h2>ZF-4295: Zend_Pdf_Page::drawText() with UTF-8 strips multibyte characters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-15T07:04:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-06T07:07:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>drawText() draws text without multibyte UTF-8 characters (lithuanian letters in particular). E. g. aąbcčd becomes abcd with ą and č skipped. (I hope this board supports those characters). 
Source text is encoded in UTF-8.</p>

<pre class="highlight"><code>
drawText($myUtf8Text, $x, $y, 'UTF-8');
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Zoran Lazic (zoki) on 2008-11-24T00:25:23.000+0000</p> 
        <div class="body">
            <p>It strips them because of //IGNORE is passed into converting charset.</p>

<p>Problem is also that iconv throws notices whent converting from UTF-8 to CP1252</p>

<p>iconv() [function.iconv]: Detected an illegal character in input string in /Zend_1.7.0/Zend/Pdf/Resource/Font/Simple.php on line 265</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-05-06T07:07:14.000+0000</p> 
        <div class="body">
            <p>Standard PDF fonts support only Latin1 encoding (actually some superset of Latin1 encoding).
To use non-Latin1 characters you have to use them with TTF fonts.</p>

<p>See <a href="http://framework.zend.com/manual/en/zend.pdf.drawing.html#zend.pdf.drawing.using-fonts">Using fonts</a> and <a href="http://framework.zend.com/manual/en/zend.pdf.drawing.html#zend.pdf.drawing.standard-fonts-limitations">Standard PDF fonts limitations</a> documentation sections for details.</p>

        </div>
    </div>
    </div>

