<h2>ZF-4425: Create demo code for using secure AuthSub</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-30T08:52:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-21T11:16:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7064">ZF-7064</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Secure AuthSub now works.  Create some demo code that uses it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Eric Bidelman (api.eric) on 2009-06-20T11:36:37.000+0000</p> 
        <div class="body">
            <p>Sample code is available here:
<a href="http://framework.zend.com/svn/framework/standard/trunk/demos/Zend/Gdata/Health.php">http://framework.zend.com/svn/framework/…</a></p>

<p>and Secure AuthSub is documented here:
<a href="http://code.google.com/apis/gdata/authsub.html">http://code.google.com/apis/gdata/authsub.html</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-06-21T11:15:56.000+0000</p> 
        <div class="body">
            <p>Marking as fixed.</p>

<p>Fix Version: 1.7.2</p>

<p>I've also created ZF-7064 to add documentation to the reference manual for this.</p>

        </div>
    </div>
    </div>

