<h2>ZF-4771: Testcoverage of Zend_Soap_* is to low</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-11-01T14:47:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-09T11:10:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Client</li>
            <li>Zend_Soap_Server</li>
            <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <ul><li><p>The test-coverage for all Zend_Soap_ components is too low.</p></li>
<li><p>Special cases are not checked. Many tests cannot fail (or hardly ever do so) due to non test driven construction.</p></li>
<li><p>Tests have to be more end-user centric, not so much check for obvious fucntionality.</p></li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2008-11-05T02:18:23.000+0000</p> 
        <div class="body">
            <p>As of r12294 Zend_Soap_Server has an extended test-coverage.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-09-09T11:10:14.000+0000</p> 
        <div class="body">
            <p>Has been fixed already was just not closed yet</p>

        </div>
    </div>
    </div>

