<h2>ZF-4329: Keep Image Dimensions in Zend_Validated_File_ImageSize and provide methods for access</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-19T03:15:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-19T05:21:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                malt (malt)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate_File</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When doing an image size validation, it would be nice to keep the results of the getimagesize() call in the validator object to retrieve them, for example the height and width of the image, later for processing. This would make appropriate methods necessary to access them from outside.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-19T03:35:21.000+0000</p> 
        <div class="body">
            <p>This is against the nature of validators. Validators return only true or false.</p>

<p>But we will have a ResizeImageFilter which can process image informations.</p>

<p>Also what will you do when you get multiple images at once ?
This would be very inconsistent to the user and hard to handle.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-19T03:35:52.000+0000</p> 
        <div class="body">
            <p>Not a feature for validators !</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by malt (malt) on 2008-09-19T04:09:58.000+0000</p> 
        <div class="body">
            <p>Well Upload Validator has a getFiles() function, so i thought something like this would be nice to have in the ImageSize validator.</p>

<p>I mean you make the getimagesize() call in the validator and to get the height/width i need to make another unnecessary call to getimagesize(). And i dont want to resize the image.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-19T05:21:57.000+0000</p> 
        <div class="body">
            <p>Upload Validator has a setFiles method and you can only get the previously set files.
But there is no way to have informations returned which are provided by the validation. This would brake validation rules.</p>

        </div>
    </div>
    </div>

