<h2>ZF-4228: CLONE -Zend_Dojo_Form_SubForm decorator ContentPane renders invalid name attribute on surrounding div</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-09T02:16:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-14T12:30:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jan Wagner-Rosenkranz (skywalker)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3877">ZF-3877</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Dojo_Form_SubForm decorator ContentPane renders a name attribute in the surrounding div with the value of the subform name. This is not XHTML compliant, as there is no name attribute for divs.</p>

<p>Here is an example that produces this behavior:</p>

<pre class="highlight"><code>
$form = new Zend_Dojo_Form();
$subform = new Zend_Dojo_Form_SubForm();
$subform-&gt;addElement('text', 'test');
$form-&gt;addSubForm($subform, 'test');

echo $form;
</code></pre>

<p>This gets the following html output:</p>

<pre class="highlight"><code>
</code></pre><code></code><div><code></code><code> 

</code></div><code>

</code>

<p>You notice the name attribute on the test-ContentPane div. Just tested with latest trunk (r11304).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-09T05:46:07.000+0000</p> 
        <div class="body">
            <p>Duplicates ZF-3877, which I am re-opening.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-14T12:30:08.000+0000</p> 
        <div class="body">
            <p>Resolved as duplicate of ZF-3877</p>

        </div>
    </div>
    </div>

