<h2>ZF-4387: Use Controller_Front's baseUrl</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2008-09-26T04:52:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-01T13:50:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.1 (01/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2822">ZF-2822</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form::setAction($this-&gt;_helper-&gt;url(...)) and other components relying on Zend/Controller/Action/Helper/Url.php get wrong URLs when Zend_Controller_Front::setBaseUrl() is used.</p>

<p>I've noticed this in a modularized directory layout when setting form's action. I was unable to continue developing in my environment without this fix.</p>

<p>Please review, and explain me if something is wrong with the patch, as I've been using ZF only for three days now.</p>

<p>Regards,
Flavius Aspra
-- The diff
--- library/Zend/Controller/Action/Helper/Url.php   (revision 11520)
+++ library/Zend/Controller/Action/Helper/Url.php   (working copy)
@@ -56,10 +56,12 @@</p>

<pre><code>     if (null === $module) {
         $module = $request-&gt;getModuleName();
</code></pre>

<p>-        }
+   }</p>

<ul><li>$fc = $this-&gt;getFrontController();</li>
<li>
     $url = $controller . '/' . $action;</li>
<li>if ($module != $this-&gt;getFrontController()-&gt;getDispatcher()-&gt;getDefaultModule()) {</li>
<li>if ($module != $fc-&gt;getDispatcher()-&gt;getDefaultModule()) {
         $url = $module . '/' . $url;
     }</li>
</ul><p>@@ -72,7 +74,7 @@
             $url .= '/' . $paramString;
         }</p>

<ul><li>$url = '/' . ltrim($url, '/');</li>
<li><pre><code> $url = '/' . ltrim($fc-&gt;getBaseUrl() . '/' . $url, '/');

 return $url;
</code></pre>

<p>}</p></li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Luiz Fernando Furtado (kgbfernando) on 2008-10-23T20:45:57.000+0000</p> 
        <div class="body">
            <p>Same ZF-2822</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-01T13:50:45.000+0000</p> 
        <div class="body">
            <p>Updating these issues to mark them resolved for 1.7.1.</p>

        </div>
    </div>
    </div>

