<h2>ZF-4986: Refactor Zend_Pdf_Page: View Helper pattern</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-11-19T01:16:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It is possible, without much performance overhead, to refactor Zend_Pdf_Page to implement a view helper pattern for all its drawing capabilities.</p>

<p>This way people can easily plugin their own features and those of others, that faciliate the basic drawing capabilites to do stuff like tables, headers, whatever.</p>

<p>This change would include using the PluginLoader for loading of the helpers. It would not change backwards compability since Zend_Pdf_Page::__call would proxy against the helpers.</p>

<p>To even make backwards compability no problem at all, one could think about letting the basic "already defined" options part of Zend_Pdf_Page and only put extra helpers into the plugin loader __call circle.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:48.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

