<h2>ZF-471: in Chinese document 5.4.9,  fetchRow must be fetchAll</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2006-11-02T05:55:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-15T17:09:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                cykit luo (cykit)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$where = $db-&gt;quoteInto('noble_title = ?', 'Sir');
$order = 'first_name';
$count = 10;
$offset = 20;
$rowset = $table-&gt;fetchRow($where, $order, $count, $offset);</p>

<p>should be
$rowset = $table-&gt;fetchAll($where, $order, $count, $offset);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-22T15:00:35.000+0000</p> 
        <div class="body">
            <p>Completed minor change to doc.</p>

        </div>
    </div>
    </div>

