<h2>ZF-4154: Change a code example in the documentation to better reflect recommended usage</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-01T09:15:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-03T20:27:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>From SiCo007 <a href="mailto:simon@sico.co.uk">simon@sico.co.uk</a>:</p>

<p>{quote}
I would like to suggest that in the documentation the code for the suggested paginaton techniques is changed slightly to make the id attribute in</p>

<p>&lt;</p>

<p>div id="paginationControl"&gt; a class attribute instead...</p>

<p>&lt;</p>

<p>div class="paginationControl"&gt;.</p>

<p>Nothing major but people will be copying the code and it's best practice to have one id of said name per page, it's quite common however to display multiple paginators per page.
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2008-09-03T20:27:45.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 11224.</p>

        </div>
    </div>
    </div>

