<h2>ZF-4264: Zend_Form_Element_Captcha : captcha validation needed only once</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-09-12T04:51:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-10-29T17:55:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
            <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A user should needs only to validate once the captcha.</p>

<p>Ex : On a registration form, I have 4 Elements : username, password, password confirmation and a Captcha image</p>

<p>Suppose the users enters correctly the Captcha, but fails to validate password and password confirmation. We don't need to retest the Captcha once it's been validated, it's boring, and not user friendly.</p>

<p>Ideally I should be able to choose if I require my users to validate multiple times the Captcha or not.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-12T05:57:07.000+0000</p> 
        <div class="body">
            <p>Security-wise, if the form fails validation, it's best to re-ask the captcha. However, if you don't want this behavior, it's trivial to remove the captcha element if it validated, and set a token in the session to remove it in future form submissions prior to validation</p>

<pre class="highlight"><code>
$session = new Zend_Session_Namespace('form_captcha');
$captchaValidated = false;
if (isset($session-&gt;validated) &amp;&amp; $session-&gt;validated) {
    $captchaValidated = true;
    $form-&gt;removeElement('captcha');
}

if (!$form-&gt;isValid($data)) {
    if (!$captchaValidated &amp;&amp; $form-&gt;captcha-&gt;isValid($data['captcha'])) {
        $form-&gt;removeElement('captcha');
        $session-&gt;validated = true;
    } else {
        $session-&gt;validated = false;
    }
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-12T05:57:37.000+0000</p> 
        <div class="body">
            <p>Closing; this is something that can be resolved in userland code, and does not need a ZF solution.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by thing2b (thing2b) on 2008-10-29T17:55:16.000+0000</p> 
        <div class="body">
            <p>The problem with the given solution is that it tries solve the issue at the form level.
When you have a large number of forms that all use the captcha form element, this code would be needed for every form. It would be duplicated many times.</p>

<p>Another reason that this is not really a good solution is that if you have many instances (like in different browser windows) of the same form, it would only check the captcha once per session for each form (if the session namespace is different for each form). Instead it should check (show the captcha) the first time the form is shown, and not be required when the form is shown again due to invalid inputs (of other fields).</p>

<p>A better solution would be to do this in Zend_Form_Element_Captcha or by extending it. When the captcha is correct, it should be replaced with a hidden field that contains a random value. This random value should then be looked up in the session (with a timeout period). After the value is looked up, it should be removed from the session so that the same form can not be submitted multiple times after the captcha has been completed. If the random value is not set, the validation should fail and the Captcha shown again. If it is done this way, I do not see it being any less secure and why it could not be added to Zend_Form_Element_Captcha.</p>

<p>The problem with doing this by extending Zend_Form_Element_Captcha is that you are half way towards re-writing the element anyway. It is for this reason that I think this issue should be re-opened and reconsidered.</p>

        </div>
    </div>
    </div>

