<h2>ZF-4675: Zend_Paginator_Adapter_Interface::getItems has wrong parameters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-22T03:09:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The parameter definition for Zend_Paginator_Adapter_Interface::getItems is different to the ones for Zend_Paginator_Adapter_DbSelect and Zend_Paginator_Adapter_DbTableSelect.</p>

<p>The Interface definition is:</p>

<pre class="highlight"><code>     /**
     * Returns a collection of items for a page.
     *
     * @param  integer $pageNumber Page number
     * @param  integer $itemCountPerPage Number of items per page
     * @return mixed
     */
    public function getItems($pageNumber, $itemCountPerPage);
}</code></pre>

<p>whereas the DbSelect definition is:</p>

<pre class="highlight"><code>    /**
     * Returns an array of items for a page.
     *
     * @param  integer $offset Page offset
     * @param  integer $itemCountPerPage Number of items per page
     * @return array
     */
    public function getItems($offset, $itemCountPerPage)</code></pre>

<p>I.e. the first parameter for the DbSelect is the offset, whereas for the Interface it is pageNumber. The call from $paginator-&gt;getItemsByPage() passes in the $offset, so this appears to be the correct usage.</p>

<p>I think the parameter definition in the interface should be changed</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-10-22T03:22:03.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 12071</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:28.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

