<h2>ZF-4828: testAuthenticateVerifyInvalid(Zend_Auth_Adapter_OpenIdTest) unit test failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-11-06T09:01:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-17T03:17:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dmitry Stogov (dmitry)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth_Adapter_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
3) testAuthenticateVerifyInvalid(Zend_Auth_Adapter_OpenIdTest)
expected string 
difference      &lt;xxxxxxxxxxxxxxxxxxxxxx???????????????????????????????????????????????????????????&gt;
got string      http://www.zf-test.com/test.php' != '<a href="http://AllTests.php">http://AllTests.php</a>'&gt;
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

