<h2>ZF-4166: findParentRow fails when foriegn key is null</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-02T19:14:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-20T15:08:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3347">ZF-3347</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using the examples from the manual for <a href="http://framework.zend.com/manual/en/zend.db.table.relationships.html#zend.db.table.relationships.fetching.parent">fetching parent rows</a> which uses <a href="http://framework.zend.com/manual/en/zend.db.html#zend.db.adapter.example-database">the example database</a>, the following code will result in a SQL error when the <code>reported_by</code> field is null for a record. Assume the DB Table classes are set up exactly as <a href="http://framework.zend.com/manual/en/zend.db.table.relationships.html#zend.db.table.relationships.defining">they are in the manual</a>.</p>

<pre class="highlight"><code>
$bugsTable = new Bugs();
$bugsRowset = $bugsTable-&gt;fetchAll(array('bug_status = ?' =&gt; 'NEW'));
$bug1 = $bugsRowset-&gt;current();

$reporter = $bug1-&gt;findParentRow('Accounts', 'Reporter');
</code></pre>

<p>When the <code>reported_by</code> field is null, the generated Statement does not get any values bound to it which results in a where statement similar to "where account_name = ?" with no parameters to bind to the question mark. With a MySQLi adapter the error says:
Zend_Db_Statement_Mysqli_Exception: Mysqli statement execute error : No data supplied for parameters in prepared statement in ... library/Zend/Db/Statement/Mysqli.php on line 215</p>

<p>Expected Behavior:
I would expect any of the following options:
* generate an exception about having a null value in the foreign key column.
* gracefully fail similar to the result returned from something like $bugsTable-&gt;find('bogus').
* correctly bind a null value and execute the query and hope for the best.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Claude Duvergier (cduv) on 2008-10-23T09:01:37.000+0000</p> 
        <div class="body">
            <p>I did run into the same exception.
With a {{pdo_mysql}} adapter, the message is:
{quote}
exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: no parameters were bound' in [...]library\Zend\Db\Statement\Pdo.php:238
{quote}</p>

<p>I disagree with <em>Grady Kuhnline</em> about generating an exception to warn about a {{null}} value in the foreign key column: why would it be an error?</p>

<p>What I would expect is {{Zend_Db_Table_Row_Abstract::findParentRow()}} to return {{null}} (no parent found).
So an Exception could be thrown by {{Zend_Db_Statement_Pdo}} and caught by {{Zend_Db_Table_Row_Abstract::findParentRow()}} for it to be aware there is no parent on that Row.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-06-06T04:53:42.000+0000</p> 
        <div class="body">
            <p>It seems to duplicate ZF-3347</p>

        </div>
    </div>
    </div>

