<h2>ZF-4440: UNION does not work with Zend_Db_Table_Select</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-10-01T10:22:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-17T14:27:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Trying to use a UNION with a Zend_Db_Table_Select fails because it tries to call joinInner when it assembles the query (to ensure data is being selected from the correct table), which results in an exception being thrown (because you can't join on a UNION).</p>

<p>A (somewhat bad, but workable) workaround is to do something like this:</p>

<pre class="highlight"><code>
--- Db/Table/Select.php (revision 7)
+++ Db/Table/Select.php (working copy)
@@ -150,6 +150,10 @@
      */
     public function from($name, $cols = self::SQL_WILDCARD, $schema = null)
     {
+        if (count($this-&gt;_parts[self::UNION])) {
+            return $this;
+        }
+
         if ($name instanceof Zend_Db_Table_Abstract) {
             $info = $name-&gt;info();
             $name = $info[Zend_Db_Table_Abstract::NAME];

</code></pre>

<p>Regards,</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by C Snover (snover) on 2009-07-24T15:12:48.000+0000</p> 
        <div class="body">
            <p>9 months on, this is still not fixed. I have been using the provided patch since this issue was first entered into the tracker and it has been working fine. I would recommend committing it, since it is very small and does not seemingly cause any side-effects even with many complex built queries.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-09-17T14:26:43.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and merged into 1.9 release branch.</p>

<p>I modified your patch a little to check for the union in the assemble() method, which seems to be a more appropriate location for me.</p>

        </div>
    </div>
    </div>

