<h2>ZF-4199: Zend_Form_Element_File::isValid misuse of $value ?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-05T06:57:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-06T05:07:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.1 (15/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Patrick Barroca (patbator)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As I anderstand the code, this method receive a $value that can only be null as a value of an input type file is not present in $_POST.
The line 259 : $this-&gt;setValue($adapter-&gt;getFileName($this-&gt;getName())) just show the construction of the value using the Adapter.</p>

<p>The problem is that lines 261 &amp; 275 use the $value instead of $this-&gt;_value that was computed by the adapter.
This leads to, if file is not required, no upload at all, the "if" line 261 is always true as empty(null) == true.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-09-06T05:07:39.000+0000</p> 
        <div class="body">
            <p>Duplication of ZF-4140.</p>

        </div>
    </div>
    </div>

