<h2>ZF-4244: ContextSwitch and AjaxContext issue using actionStack</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-11T00:03:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-14T12:13:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I use {{actionStack}} helper in {{init()}} method (to create menu links and capture it's content).
I also use {{ContextSwitch}} helper to make one action for ajax (json). Now, even when I try {{AjaxContext}}, when I call action with ajax call (?format=json) server returns 500 Internal Server error. When I removed actionStack from init() method it works well. Example code below.</p>

<pre class="highlight"><code>
class EditorController extends Zend_Controller_Action
{
    public function init()
    {
        $this-&gt;_helper-&gt;actionStack('menu', 'navigation');

        $contextSwitch = $this-&gt;_helper-&gt;getHelper('ContextSwitch');
        $contextSwitch-&gt;addActionContext('load', 'json')
                      -&gt;initContext();
    }

    public function indexAction()
    {
    }

    public function loadAction()
    {
    }
</code></pre>

<p>Call to /editor/load/format/json makes response unreachable.</p>

<p>However i found that I can workaround it this way (part of {{init()}}:</p>

<pre class="highlight"><code>
        $actionContext = $contextSwitch-&gt;getActionContexts($this-&gt;_request-&gt;getActionName());
        if (!in_array('json', $actionContext)) {
            $this-&gt;_helper-&gt;actionStack('menu', 'navigation');
        }
</code></pre>

<p>...but I think it should be automated, isn't it?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-09-11T05:44:47.000+0000</p> 
        <div class="body">
            <p>What's happening here is that a context is activated -- which sets a new view
script suffix. As a result, any later actions on the ActionStack are now using
that altered view script suffix -- and likely do not have matching view scripts.</p>

<p>There are a few solutions. Probably the best, though, is simply to clear the
action stack when a context is detected. You can do this with code like the
following:</p>

<pre class="highlight"><code>
if (null !== $this-&gt;_helper-&gt;contextSwitch-&gt;getCurrentContext()) {
    $front = Zend_Controller_Front::getInstance();
    if ($front-&gt;hasPlugin('Zend_Controller_Plugin_ActionStack')) {
        $plugin = $front-&gt;getPlugin('Zend_Controller_Plugin_ActionStack');
        $registry = $plugin-&gt;getRegistry();
        unset($registry[$plugin-&gt;getRegistryKey()]);
    }
}
</code></pre>

<p>If you swap the "$this-&gt;_helper-&gt;contextSwitch" part with "Zend_Controller_Action_HelperBroker::getStaticHelper('ContextSwitch')", you could even push that into a postDispatch() plugin.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Zoran Lazic (zoki) on 2008-11-13T03:31:43.000+0000</p> 
        <div class="body">
            <p>That's not working as it should.
You shouldn't unset the whole key in the registry otherwise you'll get  "Notice: Undefined index:  Zend_Controller_Plugin_ActionStack in ./Zend_svn/Zend/Plugin/ActionStack.php on line 136"</p>

<p>instead
  unset($registry[$plugin-&gt;getRegistryKey()]);
it should be 
  $registry-&gt;{$plugin-&gt;getRegistryKey()} = array();</p>

<p>My ZF is: r12605</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-14T12:13:25.000+0000</p> 
        <div class="body">
            <p>Resolved as Won't Fix on the basis of there being a known workaround since 2008.</p>

        </div>
    </div>
    </div>

