<h2>ZF-4312: SQL &quot;--&quot; comments in queries, where the comment contains an apostrophe, break parameterised query parsing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-09-16T21:24:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-21T13:01:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Kings-Lynne (chriskl)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>(I'm using MSSQL, but it may well apply to any driver)</p>

<p>I have this in an SQL query:</p>

<pre class="highlight"><code>
   AND dfcond.inetblock = 'R'
                        -- check the subject isn't a regular one anyway
                        AND NOT EXISTS (
                            SELECT 1
</code></pre>

<p>The apostrophe in "isn't" breaks parameter parsing when I go:</p>

<p>$this-&gt;db-&gt;query($sql, array(blah, blah, blah))</p>

<p>If I remove the apostrophe, it works perfectly.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-21T13:01:35.000+0000</p> 
        <div class="body">
            <p>Feel free to reopen with exception or error messages.  This appears to be a driver level issue.</p>

        </div>
    </div>
    </div>

