<h2>ZF-4544: Zend_Amf_ServerTest - &quot;Invalid method or class&quot; exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-10-10T08:20:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-13T14:10:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wade Arnold (wadearnold)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
1) testSetClassShouldRaiseExceptionOnInvalidClassname(Zend_Amf_ServerTest)
Zend_Amf_Server_Exception: Invalid method or class</p>

<p>2) testSetClassShouldRaiseExceptionOnInvalidClasstype(Zend_Amf_ServerTest)
Zend_Amf_Server_Exception: Invalid method or class; must be a classname or object
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-10-10T09:15:47.000+0000</p> 
        <div class="body">
            <p>It was necessary to update PHPUnit</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-13T14:10:21.000+0000</p> 
        <div class="body">
            <p>Changing issues in preparation for the 1.7.0 release.</p>

        </div>
    </div>
    </div>

