<h2>ZF-493: Zend_Controller_Front + Zend_Http_Request</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-11-04T06:58:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When a new request object is instantiate (with no parameter ) in the dispatch method in Zend_Controller_Front ( line 397 $request = new Zend_Controller_Request_Http() ) setRequestUri() is never call in Zend_Http_Request (line 66)</p>

<p>Then $request-&gt;getPathInfo() return nothing in Zend_Controller_Router (line 112)</p>

<p>Then no match is fond for controller/action</p>

<p>Then we end up on default controller/action</p>

<p>I put a else statment in Zend_Http_Request  with $this-&gt;setRequestUri(); and it work for me</p>

<pre class="highlight"><code>
    public function __construct($uri = null)
    {
        if (null !== $uri) {
            if (!$uri instanceof Zend_Uri) {
                $uri = Zend_Uri::factory($uri);
            } 
            if ($uri-&gt;valid()) {
                $path  = $uri-&gt;getPath();
                $query = $uri-&gt;getQuery();
                if (!empty($query)) {
                    $path .= '?' . $query;
                }

                $this-&gt;setRequestUri($path);
            }
        } else {
            $this-&gt;setRequestUri();
        }
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-05T12:40:32.000+0000</p> 
        <div class="body">
            <p>Resolved in 1472.</p>

        </div>
    </div>
    </div>

