<h2>ZF-4176: Add/include user parameters in pagination_control</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-09-03T09:27:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-03T20:41:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>I have created a datagrid component, and i would like to use the same pagination control for the pager of all my datagrid component in my pages.
In the same html page, i can use multiple datagrid component, and i want to customize  with other parameters.</p>

<p>Really I want this in the pagination control (You can observe the new variable "$this-&gt;pageName"):</p>

<p>
&lt;?php foreach ($this-&gt;pagesInRange as $page): ?&gt;
  &lt;?php if ($page != $this-&gt;current): ?&gt;
    <a href="">&lt;?php echo $page; ?&gt;</a> |
  &lt;?php else: ?&gt;
    &lt;?php echo $page; ?&gt; |
  &lt;?php endif; ?&gt;
&lt;?php endforeach; ?&gt;</p>

<p>In place of:

&lt;?php foreach ($this-&gt;pagesInRange as $page): ?&gt; 
  &lt;?php if ($page != $this-&gt;current): ?&gt;
    <a href="">&lt;?= $page; ?&gt;</a> | 
  &lt;?php else: ?&gt;
    &lt;?= $page; ?&gt; | 
  &lt;?php endif; ?&gt;
&lt;?php endforeach; ?&gt;</p>

<p>In the example, in execution, the datagrid component replace $this-&gt;pageName by myDataGridName_page, and not conflits appear if I have more datagrid in the same page.</p>

<p>To have features, I propose to add this code to Zend_Paginator:</p>

&lt;?php 

protected $_params = array();

public function addParam($param, $value)
 {
 $this-&gt;_params[$param] = $value;
 }


public function getPages($scrollingStyle = null)
 {
 if ($this-&gt;_pages === null) {
       $this-&gt;_pages = $this-&gt;_createPages($scrollingStyle);

           //code that I added to include more parameters
            foreach ($this-&gt;_params as $p=&gt;$v)
                $this-&gt;_pages-&gt;$p = $v;
        }


        return $this-&gt;_pages;
    }
?&gt;

<p>Excuz for my bad english
Thanks for good job</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2008-09-03T20:41:48.000+0000</p> 
        <div class="body">
            <p>Please refer to the last parameter of Zend_View_Helper_PaginationControl::paginationControl:</p>

<pre class="highlight"><code>
    /**
     * Render the provided pages.  This checks if $view-&gt;paginator is set and,
     * if so, uses that.  Also, if no scrolling style or partial are specified, 
     * the defaults will be used (if set).
     *
     * @param  Zend_Paginator (Optional) $paginator
     * @param  string $scrollingStyle (Optional) Scrolling style
     * @param  string $partial (Optional) View partial
     * @param  array|string $params (Optional) params to pass to the partial
     * @return string
     * @throws Zend_View_Exception
     */
    public function paginationControl(Zend_Paginator $paginator = null, $scrollingStyle = null, $partial = null, $params = null);
</code></pre>

        </div>
    </div>
    </div>

