<h2>ZF-4580: Improving exception messages for failed database queries</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-10-13T00:20:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Eran Galperin (erangalp)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When a query fails against a database adapter, it is most commonly during the query process which throws an exception with the database error message. It would be most useful to include the statement that failed to help with further debugging (especially when reading error messages from an error log).</p>

<p>For example, for the Mysqli adapter you would see:
Fatal error:  Uncaught exception 'Zend_Db_Statement_Mysqli_Exception' with message 'Mysqli prepare error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near .... in /home/www/production/library/Zend/Db/Statement/Mysqli.php:85</p>

<p>A small change to the exception throwing code could deliver a much more useful message:</p>

<p>Zend_Db_Statement_Mysqli line 85:
throw new Zend_Db_Statement_Mysqli_Exception("Mysqli prepare error: " . $mysqli-&gt;error 
  . '. Statement was: ' . (string) $sql); //Adding the sql statement to the error message</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:47.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

