<h2>ZF-4510: Zend_Filter_StripSlashes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-10-07T06:27:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>&lt;?php
/**
 * Zend Framework
 *
 * LICENSE
 *
 * This source file is subject to the new BSD license that is bundled
 * with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * <a href="http://framework.zend.com/license/new-bsd">http://framework.zend.com/license/new-bsd</a>
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@zend.com so we can send you a copy immediately.
 *
 * @category   Zend
 * @package    Zend_Filter
 * @copyright  Copyright (c) 2005-2008 Zend Technologies USA Inc. (<a href="http://www.zend.com">http://www.zend.com</a>)
 * @license    <a href="http://framework.zend.com/license/new-bsd">http://framework.zend.com/license/new-bsd</a>     New BSD License
 * @version    $Id: $
 */</p>

<p>/**
 * @see Zend_Filter_Interface
 */
require_once 'Zend/Filter/Interface.php';</p>

<p>/**
 * @category   Zend
 * @package    Zend_Filter
 * @copyright  Copyright (c) 2005-2008 Zend Technologies USA Inc. (<a href="http://www.zend.com">http://www.zend.com</a>)
 * @license    <a href="http://framework.zend.com/license/new-bsd">http://framework.zend.com/license/new-bsd</a>     New BSD License
 */
class Zend_Filter_StripSlashes implements Zend_Filter_Interface
{</p>

<pre><code>/**
 * Defined by Zend_Filter_Interface
 *
 * Returns $value without newline control characters
 *
 * @param  string $value
 * @return string
 */
public function filter ($value)
{
    return stripslashes($value);
}
</code></pre>

<p>}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by François Lecluse (openbsdiste) on 2009-03-10T02:10:53.000+0000</p> 
        <div class="body">
            <p>filter function should be better with a test of magic quotes...</p>

<p>public function filter ($value) {
    if (get_magic_quotes_gpc ()) {
        $value = stripslashes ($value);
    }
    return $value;
}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-03-10T02:14:44.000+0000</p> 
        <div class="body">
            <p>Not really.</p>

<p>a) magic_quotes_gpc should be disabled for ZF projects anyway.
b) A filter is not only supposed for values comming from GPC, but also for example values from a web service.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Joe Gornick (jgornick) on 2009-12-29T00:10:39.000+0000</p> 
        <div class="body">
            <p>Here's my version:</p>

<pre class="highlight"><code>
&lt;?php
/**
* @see Zend_Filter_Interface
*/
require_once 'Zend/Filter/Interface.php';

class My_Filter_StripSlashes implements Zend_Filter_Interface
{
    /**
    * Defined by Zend_Filter_Interface
    *
    * Returns a string with slashes stripped out.
    *
    * @param string $value
    * @return string
    */
    public function filter($value)
    {
        return is_array($value)
          ? array_map(array($this, 'filter'), $value)
          : stripslashes($value);
    }
}
</code></pre>

<p>Curious to know if this is something that should be added to ZF?  Would Zend_Filter_Callback do the job?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:40.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

