<h2>ZF-4985: Zend_Form_Element_File does not translate error message when translator is set at the form level</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-11-18T19:29:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:43:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.1 (01/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
            <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There was a similar ticket opened which was marked as resolved (ZF-4150), but I am still having the error in ZF 1.7</p>

<p>When setting a translator at the form level, the error messages are all translated for all elements except for the File  element</p>

<p>Code to reproduce error, submit the form without selecting a file and you will see the error message remains un-translated:</p>

<pre class="highlight"><code>
$form = new Zend_Form();

$translate = new Zend_Translate('array', array(
    Zend_Validate_File_Upload::NO_FILE =&gt; 'Test translation',
), 'en');
Zend_Form::setDefaultTranslator($translate);

$form-&gt;setAttrib('enctype', 'multipart/form-data');

$form-&gt;addElement('file', 'upload', array(
    'label' =&gt; 'Upload',
    'required' =&gt; true
));

$form-&gt;addElement('submit', 'save', array(
    'label' =&gt; 'Upload'
));

if ($this-&gt;getRequest()-&gt;isPost() &amp;&amp; $form-&gt;isValid($_POST)) {
    // process form
}

$this-&gt;view-&gt;form = $form;

</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-19T00:00:44.000+0000</p> 
        <div class="body">
            <p>Feature only integrated at adapter and validator level for now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-20T14:30:33.000+0000</p> 
        <div class="body">
            <p>Feature added with r12728</p>

        </div>
    </div>
    </div>

