<h2>ZF-5630: Zend_Config_Ini examples are wrong</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-01-25T09:00:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-21T13:12:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In several places you see this example:</p>

<p>$options['nestSeparator'] = ':';
$config = new Zend_Config_Ini('/path/to/config.ini',
                              'staging',
                              $options);</p>

<p>Followed by this example ini code:</p>

<p>; Production site configuration data
[production]
webhost                  = <a href="www.example.com">www.example.com</a>
database.adapter         = pdo_mysql
database.params.host     = db.example.com
database.params.username = dbuser
database.params.password = secret
database.params.dbname   = dbname</p>

<p>However, when the user follows this example literally, the resulting $config object is not correctly populated.  For instance:</p>

<p>echo $config-&gt;database-&gt;params-&gt;host</p>

<p>Results in Notice:  Trying to get property of non-object in</p>

<p>Changing the nestSeparator character to a dot (which is the character used in the ini sample above, results in a correctly populated config object.</p>

<p>This is prevelant in these pages:</p>

<p><a href="http://framework.zend.com/manual/en/zend.config.adapters.ini.html">http://framework.zend.com/manual/en/…</a></p>

<p>For new users this could be very frustrating and lead them to believe it's a bug in Zend code.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Olsen (janpolsen) on 2009-02-11T11:05:48.000+0000</p> 
        <div class="body">
            <p>I can see why the documentation can be confusing, but I actually don't think it's wrong.</p>

<p>The first 3 lines of code you write is just an example of how you can change the "nestSeparator"-option, while the sample ini code is an example in general. The "nestSeparator" defaults to a dot "." and that should work correctly with the sample ini code.</p>

<p>At least that's how I read it, but I agree that it could be written (and visualised) better :).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2009-03-21T13:12:08.000+0000</p> 
        <div class="body">
            <p>Not an issue, as the example on <a href="http://framework.zend.com/manual/en/zend.config.adapters.ini.html">http://framework.zend.com/manual/en/…</a> has the code under the INI file that correctly uses the dot separator.</p>

<p>It would be nice if a "note" in the docs was visually separated with a border though.</p>

        </div>
    </div>
    </div>

