<h2>ZF-5583: Failure with Zend_Db_Statement_Oracle unit test</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-19T14:19:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-18T02:25:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.4 (02/Feb/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
            <li>Zend_Db_Adapter_Oracle</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2962">ZF-2962</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1) testStatementFetchObjectEmptyResult(Zend_Db_Statement_OracleTest)
Zend_Db_Statement_Oracle_Exception: Unknown exception</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-01-19T14:27:44.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN13705</p>

<p>If oci_fetch_object returns false, then there are no more rows.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-04-01T05:30:17.000+0000</p> 
        <div class="body">
            <p>correct fix version and component</p>

        </div>
    </div>
    </div>

