<h2>ZF-5592: CLONE -Zend_Amf does not properly serialize Zend_Amf_Value_ByteArray instances</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-20T18:00:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-18T13:08:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.8 (30/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Wade Arnold (wadearnold)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In attempting to switch from AMFPHP to Zend_Amf, I ran across the following issue:</p>

<p>The AMF3 encoding doesn't seem to be correct for ByteArray instances.  When returning a Zend_Amf_Value_ByteArray instance, the serializer attempts to pass the instance to its writeString method, which attempts to treat it as a simple string, causing php to send the incorrect data as well as emit a notice as follows:</p>

<p>bq. Notice: Object of class Zend_Amf_Value_ByteArray to string conversion</p>

<p>One way to avoid this and properly return the binary data to the server is to modify line 81 of Zend\Amf\Parse\Amf3\Serializer.php to read:</p>

<p>bq. $this-&gt;writeString($data instanceof Zend_Amf_Value_ByteArray ? $data-&gt;getData() : $data);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by caspar harmer (rapsac) on 2009-01-20T18:02:16.000+0000</p> 
        <div class="body">
            <p>Hi Wade,</p>

<p>This issue is not fixed in the minimal framework version 1.7.3 that I am using. 
The fix noted above (from the earlier issue) seems to work well though.</p>

<p>Caspar.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wade Arnold (wadearnold) on 2009-04-18T13:08:07.000+0000</p> 
        <div class="body">
            <p>I am not sure what version this was resolved in but I know that it is in the ZF 1.7.8 release. Thanks!</p>

        </div>
    </div>
    </div>

