<h2>ZF-5173: Create Zend_Captcha_Exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-12-06T13:05:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T15:41:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.0 (17/Nov/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Tobias Petry (ice-breaker)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Captcha_Image does not use any method or class of Zend_Form, so why does it throw an Zend_Form_Exception?
Wouldn't it be much more clear to throw a Zend_Captcha_Exception?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-27T18:02:04.000+0000</p> 
        <div class="body">
            <p>It seems to be already fixed in 1.7.0</p>

        </div>
    </div>
    </div>

