<h2>ZF-5196: Invalid XHTML strict produced by form decorator about  Zend_Form_Element_Captcha</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-10T02:15:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-29T21:11:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Andrei Nikolov (viperx)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5855">ZF-5855</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As described in 
<a href="http://www.nabble.com/Zend_Form-Captcha-Invalid-xhtml-maybe-bug---td19917080.html">http://nabble.com/Zend_Form-Captcha-Invalid-xhtml-…</a>
The html produced by the form decorator about "Zend_Form_Element_Captcha" is not valid XHTML strict. Here is an example html:</p>

<p></p>

<p>the "helper" attribute should not be there</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by David Siembab (dsims) on 2009-01-13T15:55:52.000+0000</p> 
        <div class="body">
            <p>pass 'helper' =&gt; null
example:
$captcha    = new Zend_Form_Element_Captcha(
                      'captcha', array(
                      'helper' =&gt; null,
                        'captcha'    =&gt; array(
                          'captcha' =&gt; 'Image',
                          'wordLen' =&gt; 6,
                          'timeout' =&gt; 300,
                          'imgDir'  =&gt; 'img/captcha',
                          'imgUrl' =&gt; '<a href="http://urlpath/img/captcha">http://urlpath/img/captcha</a>',
                          'width' =&gt; 200,
                          'height' =&gt; 60,
                          'font' =&gt;  '/absolute/path/to/your/font.ttf'
                      )));
this works for me, but unfortunately this is not the default with the decorator for the captcha element
line 89 Zend/Form/Decorator/ViewHelper.php I think</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-02-27T10:53:51.000+0000</p> 
        <div class="body">
            <p>It uses formHidden so it's probably form view helper issue...</p>

        </div>
    </div>
    </div>

