<h2>ZF-5702: Memcached backend performs set() calls unecessarily</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-02-05T16:31:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-22T11:24:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jonathan Owens (niralisse)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8856">ZF-8856</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11732/zf-5702.diff">zf-5702.diff</a></li>
            <li><a href="/issues/secure/attachment/11731/zf-5702.diff">zf-5702.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the memcached backend's save() call, a set() is performed even after it is ensured that the key does not exist. set() is rather slow in memcache, and calling it when an add() will do is only a drag.</p>

<p>Additionally, save() performs a replace() when it's intending to do a set(), and replace() apparently doesn't work on older (&lt;= 1.2.3) versions of memcached.</p>

<p>The attached patch resolves the issue.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jonathan Owens (niralisse) on 2009-02-05T16:32:05.000+0000</p> 
        <div class="body">
            <p>Attaching diff instead.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Owens (niralisse) on 2009-02-05T16:32:30.000+0000</p> 
        <div class="body">
            <p>Noting attached rather than inline patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Owens (niralisse) on 2009-02-05T16:45:20.000+0000</p> 
        <div class="body">
            <p>Improved version that fixes a return bug in touch() and removes another uneccessary add()</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2009-02-07T01:35:42.000+0000</p> 
        <div class="body">
            <p>just commited something into SVN trunk inspired by your patch</p>

<p>please reopen this issue if it's not ok for you</p>

<p>thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2009-02-07T08:32:14.000+0000</p> 
        <div class="body">
            <p>Shouldn't that should be $newLifetime on line 440?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2009-02-08T00:58:51.000+0000</p> 
        <div class="body">
            <p>of course, fixed in SVN trunk</p>

        </div>
    </div>
    </div>

