<h2>ZF-5588: Zend_Search_Lucene hangs on &quot;*&quot; searches</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-20T07:46:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-01-20T07:51:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3321">ZF-3321</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is a critical bug i've discovered a few days ago on a production site of mine. When i make a search with "*" the zend_search_lucene system research cause php to time out and i've only a few record in the lucene index. And also any subsequent requests to the same site will go in time out. This is to resolve immediately.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-01-20T07:51:06.000+0000</p> 
        <div class="body">
            <p>Duplicate.</p>

        </div>
    </div>
    </div>

