<h2>ZF-5694: /Soap/Wsdl/Strategy/Abstract.php: no inline docs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-05T01:10:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-05T01:19:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>file in @package default
<a href="http://framework.zend.com/apidoc/core/">http://framework.zend.com/apidoc/core/</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-02-05T01:19:09.000+0000</p> 
        <div class="body">
            <p>This has already been fixed in the trunk and will be updated the next time the API doc is generated.</p>

        </div>
    </div>
    </div>

