<h2>ZF-5092: Form element validators added before setName does not take effect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-11-28T04:43:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-14T17:04:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you set validators like the following, the size validator runs but the extension one does not.
This might be because setName updates $_name but remains update _adapter -&gt; _files array.
I am not sure whether it occurs with other form elements or not.</p>

<p>$element = new Zend_Form_Element_File('hoge');
$element-&gt;setDestination('/tmp')
        -&gt;addValidator('Size', false, 1024)
        -&gt;setName('foo')
        -&gt;addValidator('Extension', false, 'jpg,png,gif')
        ;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Diogo Piçarra (xpete) on 2011-08-08T02:07:31.000+0000</p> 
        <div class="body">
            <p>I have a problem like this and maybe it's related...
When i have $form-&gt;setName("formname") the validation doesn't work...
but if i remove the setName it works...
i fixed some forms by removing the name but i have a form where i really need the name on it
and this is blocking my project...
I'am using Zend_Dojo_Form and Zend 1.11.10...
thx</p>

        </div>
    </div>
    </div>

