<h2>ZF-5176: multiple calls with the same Zend_Rest_Client  instance not working</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-06T22:20:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-14T05:54:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Onno Schmidt (fino69)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I found a problem using 1 instance of Zend_Rest_Client and doing multiple calls with parameters to the same server.
The problem is that the method is never being set in the data array with the second call.</p>

<p>This worked fine with version 1.6.2, so it looks like the last changes in the __call() method in Zend_Rest_Client  broke the external interface.</p>

<p>I suggest to reset the data array after the call to the webservice is being made in the __call method.
Or to create a reset() method for resetting the data array.</p>

<p>$client = new Zend_Rest_Client("http://localhost/service.php");</p>

<p>print_r($client-&gt;getMoo(66)-&gt;get());</p>

<p>returns:
Zend_Rest_Client Object
(
    [_data:protected] =&gt; Array
        (
            [method] =&gt; getMoo
            [arg1] =&gt; 44
            [getMoo] =&gt; 44
            [rest] =&gt; 1
        )</p>

<p>print_r($client-&gt;getBlah(88)-&gt;get());</p>

<p>returns:
Zend_Rest_Client Object
(
    [_data:protected] =&gt; Array
        (
            [method] =&gt; getMoo
            [arg1] =&gt; 44
            [getMoo] =&gt; 44
            [rest] =&gt; 1
            [getBlah] =&gt; 77
        )</p>

<p>?&gt;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-11T02:31:33.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r13151</p>

        </div>
    </div>
    </div>

