<h2>ZF-5878: Zend_Form_Element_File does not register errors nor display them</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-02-24T11:04:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-05T23:02:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Remy Damour (remy215)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I add an error to a Zend_Form_Element_File element:
- -error is not registered- error is registered, it is not returned by ::getErrors() but returned by ::getErrorMessages()
- error is not outputed when element is rendered
whereas same piece of code on non-file element (text / textarea / checkbox ...) works perfectly.</p>

<p>Example:</p>

<pre class="highlight"><code>
&lt;?php
// note: $form points to a Zend_Form instance and 'attachment' is a Zend_Form_Element_File object
$form-&gt;attachment-&gt;addError('An error occured');
...
echo $form-&gt;attachment; 
?&gt;</code></pre>

<p>Actual result:</p>

<pre class="highlight"><code>
Attach file

</code></pre>

<p>Expected result:</p>

<pre class="highlight"><code>
Attach file
</code></pre><code>An error occured
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Remy Damour (remy215) on 2009-02-24T11:27:05.000+0000</p> 
        <div class="body">
            <p>``` does not work either (but works on non-file items)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-02-24T23:26:58.000+0000</p> 
        <div class="body">
            <p>Please give a complete example of your element and form creation/validation.
Because errors are rendered and tested in the testbed and displayed in my browser.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Remy Damour (remy215) on 2009-02-25T00:52:07.000+0000</p> 
        <div class="body">
            <p>I've created a very simple controller action that does only one thing, output a form with an error attached on File element.</p>

<p>Here is /application/controllers/IndexController.php:</p>

<pre class="highlight"><code>
&lt;?php
require_once 'Zend/Controller/Action.php';

/**
 * Default controller, used for redirections only
 */
class IndexController extends Zend_Controller_Action
{
    /**
     * Show upload form
     */
    public function indexAction()
    {
        require_once 'Zend/Form.php';
        $form = new Zend_Form();
        $form-&gt;setAction('/file/upload')
                 -&gt;setMethod('post');
        $attachment = $form-&gt;createElement('file', 'attachment')-&gt;setLabel('Upload a file')-&gt;addError('An error occured');
        $form-&gt;addElement($attachment);
        $this-&gt;view-&gt;form = $form;
    }
}
</code></pre>

<p>Here is /application/views/scripts/index/index.phtml:</p>

<pre class="highlight"><code>
&lt;?php echo $this-&gt;form-&gt;render(); </code></pre>

<p>Actual Result:</p>

<pre class="highlight"><code>
</code></pre><code>Upload a file

    </code>
        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-02-25T02:02:49.000+0000</p> 
        <div class="body">
            <p>I see...
To describe this:</p>

<p>The file element is based on the file transfer adapter.
So also the error is thrown from the adapter.</p>

<p>When you create a new error type with addError, this is not supported by files because the adapter would not know where he should attach it. Files themself do not have a error, they are working with validators.</p>

<p>Also, when you add a new errortype where should it be attached
...at the first validator ? What when you delete this validator ?
...at all validators ? Same error would be displayed multiple times ?
...and when this works, only displaying the attached error ? Or also the file errors ?</p>

<p>I would solve this different, at the time you validate / receive the file as shown in several examples.</p>

<p>Btw:
renderErrors() works by me, but displays as described previously only file errors.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-02-25T03:39:07.000+0000</p> 
        <div class="body">
            <p>Changed type from bug to improvement.
Will be reviewed internally.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Remy Damour (remy215) on 2009-02-25T05:25:41.000+0000</p> 
        <div class="body">
            <p>If addError method is not used, it may be interesting for it to throw an exception.
Thanks for the explanation anyway.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-03-05T23:02:34.000+0000</p> 
        <div class="body">
            <p>Integrated with r14233</p>

        </div>
    </div>
    </div>

