<h2>ZF-5835: Zend_form_element_file has wrong name when is nested in subform</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-19T04:10:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-09T14:10:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Vita Plsek (winsik)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5864">ZF-5864</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have found bug in File element. when I put file element into subform, then it doesn't have proper name.</p>

<p>Code snipet:</p>

<pre class="literal"> 
        $filesForm = new Zend_Form_SubForm();

        for ($h1=1;$h1&lt;=5;$h1++) {
            $subForm = new Zend_Form_SubForm();
            $subForm-&gt;addElement('text', 'name', array(

            'filters'    =&gt; array('StringTrim' ),
            'validators'  =&gt; array('NotEmpty'),
            'label'      =&gt; 'Název ' ,
                    ));

            }

            $subForm-&gt;addElement('file', 'file', array(
            'filters'    =&gt; array('StringTrim', ),
            'label'      =&gt; 'Obrázek',
            'validators' =&gt; array (array('Size', false, 5*1024*1024),
                        array('Extension', false, 'jpg,png,gif'),
                        array('Count',false,1)),
                ));

            $filesForm-&gt;addSubForm($subForm,$h1);
        }

        $this-&gt;addSubForm($filesForm,'new_files');
</pre>

<p>...</p>

<p>then text elements have the proper names like : <em>new_files[1][name]</em> , so should file element, bu it is still named only <em>file</em> instead of  <em>new_files[1][file]</em></p>

<p>View script produces code like :</p>

<pre class="literal">
</pre> Název  


Obrázek

label of File Element is properly set, but its id and name doesn't contain parent arrays.

I have found that 1.7.5 should have support for FileElement in subforms, but there is still this issue.

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Vita Plsek (winsik) on 2009-03-16T10:14:12.000+0000</p> 
        <div class="body">
            <p>I have probably discovered solution :</p>

<p>In Zend_Form_Decorator_File in the version 1.7.5, there is</p>

<p>$name      = $element-&gt;getName();</p>

<p>on line 91</p>

<p>and there probably should be</p>

<p>$name      = $element-&gt;getFullyQualifiedName();</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Vita Plsek (winsik) on 2009-03-16T10:25:12.000+0000</p> 
        <div class="body">
            <p>Also for right id line 94</p>

<p>should be -</p>

<p>$attribs['id'] = $element-&gt;getId();</p>

<p>instead of original</p>

<p>$attribs['id'] = $name;;</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-09T14:10:01.000+0000</p> 
        <div class="body">
            <p>Closed as duplicate of ZF-5864.
Read manual, FAQ and ZF-5864 for details.</p>

        </div>
    </div>
    </div>

