<h2>ZF-5723: Zend_Date outputs wrong year</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-10T05:30:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-10T07:09:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5297">ZF-5297</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Try this code:</p>

<pre class="highlight"><code>
$date = new Zend_Date();
$date-&gt;set($from, Zend_Date::TIMESTAMP);

//$from is dynamically passed timestamp

Zend_Debug::dump($from);
Zend_Debug::dump(date('Y-m-d H:i:s', $from)); 
Zend_Debug::dump($date-&gt;get(Dnez_Date::DB_DATETIME));
exit();

//source of Dnez_Date class

class Dnez_Date extends Zend_Date
{

    const DB_DATE = 'YYYY-MM-dd';
    const DB_DATETIME = 'YYYY-MM-dd HH:mm:ss';

}
</code></pre>

<p>The result is:</p>

<pre class="literal">
int 1262296800
string '2010-01-01 00:00:00' (length=19)
string '2009-01-01 00:00:00' (length=19)
</pre>

<p>For some reason Zend_Date give me wrong year.</p>

<p>p.s. I just downloaded the latest trunk version of framework.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-02-10T07:08:16.000+0000</p> 
        <div class="body">
            <p>Please see the documentation on what your problem is (hint: Y vs y).</p>

        </div>
    </div>
    </div>

