<h2>ZF-5620: Column 'xxx' in field list is ambiguous </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-23T01:57:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-17T06:59:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5278">ZF-5278</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>PATCH:</p>

<p>$ diff -u Zend/Paginator/Adapter/DbSelect.php Zend/Paginator/Adapter/DbSelect.php.new
--- Zend/Paginator/Adapter/DbSelect.php 2008-11-04 23:49:22.000000000 +0200
+++ Zend/Paginator/Adapter/DbSelect.php.new     2009-01-26 22:44:30.000000000 +0200
@@ -163,7 +163,7 @@
                     if ($part[1] == '*' || $part[1] instanceof Zend_Db_Expr) {
                         $columns[] = $part[1];
                     } else {</p>

<ul><li><pre><code>                 $columns[] = $rowCount-&gt;getAdapter()-&gt;quoteIdentifier($part[1], true);
</code></pre></li>
<li><pre><code>                 $columns[] = $rowCount-&gt;getAdapter()-&gt;quoteIdentifier($part[0] . '.' . $part[1], true);

             }
         }
</code></pre></li>
</ul><hr /><p>Without Zend_Paginator everything works well (I use Zend_Db_Select).</p>

<p>SQL query :</p>

<p>SELECT DISTINCT j.JobId, j.Type, j.Name AS JobName, j.Level, j.ClientId, DATE_FORMAT(j.StartTime, '%y-%b-%d %H:%i') AS StartTime, DATE_FORMAT(j.EndTime,   '%y-%b-%d %H:%i') AS EndTime, j.VolSessionId, j.VolSessionTime, j.JobFiles, j.JobBytes, j.JobErrors, j.PoolId, j.FileSetId, j.PurgedFiles, j.JobStatus, TIMEDIFF(EndTime, StartTime) AS DurationTime, s.JobStatusLong, c.Name AS ClientName, p.Name AS PoolName, f.FileSet FROM Job AS j
 LEFT JOIN Status AS s ON j.JobStatus = s.JobStatus
 LEFT JOIN Client AS c ON j.ClientId = c.ClientId
 LEFT JOIN Pool AS p ON j.PoolId = p.PoolId
 LEFT JOIN FileSet AS f ON j.FileSetId = f.FileSetId WHERE (('2008-01-22 09:48:06' &lt;= j.StartTime) AND (j.StartTime &lt;= '2009-01-23 09:48:06')) ORDER BY JobId ASC</p>

<p>I try to use Zend_Paginator and get an error:</p>

<p>Zend_Db_Statement_Exception: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'Name' in field list is ambiguous in /opt/prog/webacula/trunk/library/Zend/Db/Statement/Pdo.php on line 238</p>

<p>Code :
$select = new Zend_Db_Select($db);</p>

<p>// make SQL query code
...</p>

<p>$paginator = Zend_Paginator::factory($select);
Zend_Paginator::setDefaultScrollingStyle('Sliding');
$paginator-&gt;setItemCountPerPage(self::ROW_LIMIT_JOBS);
$paginator-&gt;setCurrentPageNumber($this-&gt;_getParam('page', 1));
$this-&gt;view-&gt;paginator = $paginator;
$paginator-&gt;setView($this-&gt;view);</p>

<p>--- Zend/Db/Statement/Pdo.php  line 228
public function _execute(array $params = null)
    {
print_r($this-&gt;_stmt);</p>

<p>result below:</p>

<p>PDOStatement Object
(
    [queryString] =&gt; SELECT COUNT(DISTINCT JobId,Type,Name,Level,ClientId,DATE_FORMAT(j.StartTime, '%y-%b-%d %H:%i'),DATE_FORMAT(j.EndTime,   '%y-%b-%d %H:%i'),VolSessionId,VolSessionTime,JobFiles,JobBytes,JobErrors,PoolId,FileSetId,PurgedFiles,JobStatus,TIMEDIFF(EndTime, StartTime),JobStatusLong,Name,Name,FileSet) AS <code>zend_paginator_row_count</code> FROM Job AS j
 LEFT JOIN Status AS s ON j.JobStatus = s.JobStatus
 LEFT JOIN Client AS c ON j.ClientId = c.ClientId
 LEFT JOIN Pool AS p ON j.PoolId = p.PoolId
 LEFT JOIN FileSet AS f ON j.FileSetId = f.FileSetId WHERE (('2008-01-22 19:40:51' &lt;= j.StartTime) AND (j.StartTime &lt;= '2009-01-23 19:40:51'))
)</p>

<p>ps. Zforum topic: <a href="http://www.zfforums.com/zend-framework-components-13/databases-20/column-xxx-field-list-ambiguous-2203.html">http://zfforums.com/zend-framework-components-13/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Yuri Timofeev (tim4dev) on 2009-01-23T02:15:18.000+0000</p> 
        <div class="body">
            <p>Possible, Paginator does not understand the LEFT JOIN ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-02-21T16:55:16.000+0000</p> 
        <div class="body">
            <p>This should be resolved in revision 14136, along with ZF-5231</p>

        </div>
    </div>
    </div>

