<h2>ZF-5529: Zend_Controller_Request_Http setBaseUrl method fails for Windows.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-12T07:24:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-18T12:05:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>dirname($baseUrl) returns '\' in windows and '/' in linux. But the code expects '/' and checks for a condition with "0 === strpos($requestUri, dirname($baseUrl)) "</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-11-18T12:05:48.000+0000</p> 
        <div class="body">
            <p>I believe this duplicates this issue: ZF-4810</p>

<p>If you still have an issue, feel free to reopen.</p>

        </div>
    </div>
    </div>

