<h2>ZF-527: Index created with Lucene 1.9</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-11-10T11:04:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-11-25T16:37:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Atali DAOUD (arahox)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I created an index with the Lucene .NET implementation and get an Exception from Zend Framework about the limit size of Windows size file 2GB but my index file is about 8Mb.
I can send you my index if you.
I think the index binary file is incompatible.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-11-10T15:17:24.000+0000</p> 
        <div class="body">
            <p>PHP and Zend_Search_Lucene uses longs to position within files.
Thus larges supported index file is 2Gb.</p>

<p>Large indexes may be used on 64-bit platforms.</p>

<p>It 's an issue to describe thisin a documentation</p>

<p>PS You may set upper bound for index auto-optimization.
It's setMaxMergeDocs() method of IndexWriter in Java Lucene and setMaxMergeDocs() method of Zend_Search_Lucene object.</p>

<p>Take a look on <a href="http://framework.zend.com/manual/en/zend.search.index-creation.html#zend.search.index-creation.optimization">http://framework.zend.com/manual/en/…</a>
You should never optimize index in this case. Unoptimized index will have several segments. Each less then 2Gb.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:26:53.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.6.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-12-14T09:39:44.000+0000</p> 
        <div class="body">
            <p>Documented</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2006-12-21T18:34:48.000+0000</p> 
        <div class="body">
            <p>I've already heard three requests of large index support.</p>

<p>It's possible to limit segment merging (optimization) procedure in such a way that it will not merge segments if target may be greater than 2Gb.</p>

<p>It'll not help with large indices already prepared and <em>optimized</em> with Java Lucene, but will close problem for Zend_Search_Lucene.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-18T18:42:05.000+0000</p> 
        <div class="body">
            <p>Update target fix version.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:11:55.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-11-25T16:37:05.000+0000</p> 
        <div class="body">
            <p>If this is a documentation issue, it seems to have been resolved in the Zend_Search_Lucene-IndexCreation.xml file. Alex, if you have other ideas on how to address this, please create a new code feature or improvement issue.</p>

        </div>
    </div>
    </div>

