<h2>ZF-5812: Zend_Db_Select __toString() should cast its return to string</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-17T06:31:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-17T06:34:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.5 (16/Feb/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Even if we know that the return of __toString is a string, it's not in one particular use-case :</p>

<pre class="highlight"><code>
echo new Zend_Db_Select($db);
</code></pre>

<p>In that use case, the select object is empty of any value, resulting in echoing nothing, and __toString() complains about that :
Catchable fatal error: Method Zend_Db_Select::__toString() must return a string value in xxxx</p>

<p>I suggest just to cast the return of __toString() to string.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-02-17T06:34:16.000+0000</p> 
        <div class="body">
            <p>Fixed at r14097</p>

        </div>
    </div>
    </div>

