<h2>ZF-5631: Zend_Mail needs refactoring</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-01-26T01:29:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T14:07:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.5 (16/Feb/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I will refactor Zend_Mail</p>

<p>Big two are following.</p>

<p>1) unifies  _addRecipient() into _addRecipient AndHeader()</p>

<p>2) makes _formatAddress() . It is used by setFrom() and _addRecipient AndHeader()</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-26T01:32:20.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r13804</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-30T21:12:56.000+0000</p> 
        <div class="body">
            <p>I copied to 1.7 branch at SVN r13886.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-02-02T17:57:19.000+0000</p> 
        <div class="body">
            <p>needs some more fix</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-02-16T20:21:08.000+0000</p> 
        <div class="body">
            <p>I ensure to be released in 1.7.5 .</p>

        </div>
    </div>
    </div>

