<h2>ZF-5147: partialLoop counter does not reset between calls</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-03T05:09:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The partialLoop counter remembers its position between calls to the partialLoop helper. This is undesired, as separate calls to the partialLoop represent essentially separate loops, with unrelated counters.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-12-04T18:42:50.000+0000</p> 
        <div class="body">
            <p>Fixed with <a href="http://framework.zend.com/code/changelog/Zend_Framework?cs=13031">r13031</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dave Hall (skwashd) on 2008-12-11T03:31:10.000+0000</p> 
        <div class="body">
            <p>Any chance of getting this backported to 1.7.x ?</p>

<p>It is a pretty annoying bug if you are trying to treat the first element differently.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2008-12-11T04:39:41.000+0000</p> 
        <div class="body">
            <p>It will be release in 1.7.2 when ever that gets released.</p>

        </div>
    </div>
    </div>

