<h2>ZF-5327: Release Zend with extended class shells for every class</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-12-19T14:45:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-01-15T07:11:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kirk Madera (aredamkrik)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Certain classes in Zend are not very easy to extend because they extend on multiple levels. For example, extending Zend_Form_Element_Text requires a few runarounds to avoid adding much code to the standard codebase. It would be very helpful to have Zend already released with a complete set of class shells that extend each Zend class.</p>

<p>example:</p>

<pre class="highlight"><code>
class ZendExt_Form_Element_Text extends Zend_Form_Element_Text
{
 // empty shell class
}

class Zend_Form_Element_Text extends ZendExt_Form_Element_Xhtml
{
  // standard zend class
}

class ZendExt_Form_Element_Xhtml extends Zend_Form_Element_Xhtml
{
  // empty shell class
}

class Zend_Form_Element_Xhtml extends ZendExt_Form_Element
{
  // standard zend class
}

class ZendExt_Form_Element extends Zend_Form_Element
{
  // empty shell class
}

class Zend_Form_Element implements Zend_Validate_Interface
{
  // standard zend class
}
</code></pre>

<p>This is my current setup and I am able to customize zend form elements completely without having to touch Zend itself, making it easier to update. It would have helped me a great deal to have this from the get go.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2009-01-14T13:43:31.000+0000</p> 
        <div class="body">
            <p>Assigning to Matthew as this is a design issue. Frankly, I don't see the benefit of such class shells, but maybe I'm missing something. Extending framework classes should be done entirely in user-land code IMO.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-01-15T07:10:52.000+0000</p> 
        <div class="body">
            <p>I see absolutely no benefit to this. If you need to alter the behavior of a class, you extend it using your own class prefix, and then inform your Zend_Form instance of that prefix. This allows you to drop in your own replacements while still allowing you to use the dynamic features of Zend_Form; it also allows you to selectively choose which types of elements you override. This is fully documented, and I've written a number of tutorials on the subject.</p>

        </div>
    </div>
    </div>

