<h2>ZF-5652: adding filters in  Zend_File_Transfer</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-29T05:10:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-01-29T07:27:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kamil Nowakowski (kamiln)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5126">ZF-5126</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
$adapter = new Zend_File_Transfer_Adapter_Http(array('ignoreNoFile' =&gt; true));
$adapter-&gt;setDestination(Zend_Registry::get('config')-&gt;files)
$adapter-&gt;addFilter('Rename', array('target' =&gt; Zend_Registry::get('config')-&gt;files.'note_'.$id,'overwrite' =&gt; true), 'note')
    -&gt;addFilter('Rename', array('target' =&gt; Zend_Registry::get('config')-&gt;files.'terms_'.$id,'overwrite' =&gt; true), 'terms');
</code></pre>

<p>There is a note in manual 
Note that even though setting the same filter multiple times is allowed, doing so can lead to issues when using different options for the same filter.</p>

<p>It is a bug you cant add the same filter or validator diffrebt files with diffrent options , you cant manpulate multiple files with this</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-01-29T06:50:59.000+0000</p> 
        <div class="body">
            <p>As you mentioned it is clearly described in the manual.
So it is not a bug, it's a feature improvement.</p>

<p>And it duplicates an existing issue ZF-5126 where this improvement is described.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kamil Nowakowski (kamiln) on 2009-01-29T07:27:06.000+0000</p> 
        <div class="body">
            <p>Ok   thanks for the info</p>

        </div>
    </div>
    </div>

