<h2>ZF-5926: Inconsistency in docs at 22.1.12, post() vs. insertEntry()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-03-02T13:36:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-03T11:04:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.7 (16/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zachary Burnham (zburnham)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The text refers to the post() method on Zend_GData but the example refers to insertEntry.  These two methods have the same first two arguments, with the second being optional for post().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-03-02T15:23:36.000+0000</p> 
        <div class="body">
            <p>The difference between post() and insetEntry() is that post() returns an instance of Zend_Http_Response, whereas insertEntry() returns an Zend_Gdata_App_Entry.</p>

<p>I think most people don't want to deal with the raw HTTP response, so I'll update the documentation to use insertEntry() exclusively.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-03-02T15:29:10.000+0000</p> 
        <div class="body">
            <p>Patch sent to [~jhartmann] for review:</p>

<p><a href="http://codereview.appspot.com/22060">http://codereview.appspot.com/22060</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-03-03T11:04:18.000+0000</p> 
        <div class="body">
            <p>Committed to trunk as r14212.
Committed to release-1.7 as r14213.
Marking as resolved for next mini release.</p>

<pre class="literal">
commit 9da63b9568a8d4751fdf4fbc06322b781211191e
Author: tjohns 
Date:   Tue Mar 3 18:52:45 2009 +0000

    ZF-5926: Fix erroneous call to post() instead of insertEntry() in
    Zend_Gdata-Introduction manual page.
    
    Review URL: <a href="http://codereview.appspot.com/22060">http://codereview.appspot.com/22060</a>
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/trunk@14212">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac1e357ba

commit 3946df841160c3ed5e97dab392b9402d828e9a17
Author: tjohns 
Date:   Tue Mar 3 19:03:44 2009 +0000

    Merge r14212 from trunk to release-1.7.
    
    ZF-5926: Fix erroneous call to post() instead of insertEntry() in
    Zend_Gdata-Introduction manual page.
    
    Review URL: <a href="http://codereview.appspot.com/22060">http://codereview.appspot.com/22060</a>
    
    
    Conflicts:
    
        documentation/manual/en/module_specs/Zend_Gdata-Introduction.xml
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/branches/release-1.7@14213">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac
</pre>

        </div>
    </div>
    </div>

