<h2>ZF-5298: Zend_Db_Adapter_Pdo_Abstract-&gt;getServerVersion PDO_OCI - SQLSTATE[IM001]: Driver does not support this function: driver does not support getting attributes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-17T07:56:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-01-22T12:00:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.3 (19/Jan/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>First time I seen this problem with ZF 13325 SVN revision.</p>

<p>On first connect (when building metadata cache  i'm getting</p>

<p>PDOException::SQLSTATE[IM001]: Driver does not support this function: driver does not support getting attributes
Full exception below</p>

<p>From  my observations it looks like server related problem - it appears only on production server: Linux Debian, Apache 2.2.9-10+lenny1, PHP 5.2.6-5,  PDO-1.0.3, PDO_OCI-1.0, instantclient-linuxAMD64-10.1.0.5.0-20060519</p>

<p>trying and catching this exception and returning null value works ( app is working as expected ).</p>

<pre><code>/**
 * Retrieve server version in PHP style
 *
 * @return string
 */
public function getServerVersion()
{
    $this-&gt;_connect();
    // ********************* BEGIN OWN PATCH *********************
    try {
    // ********************** END OWN PATCH **********************
        $version = $this-&gt;_connection-&gt;getAttribute(PDO::ATTR_SERVER_VERSION);
        $matches = null;
        if (preg_match('/((?:[0-9]{1,2}\.){1,3}[0-9]{1,2})/', $version, $matches)) {
            return $matches[1];
        } else {
            return null;
        }
    // ********************* BEGIN OWN PATCH *********************
    } catch ( PDOException $e) {
        return null;
    }
    // ********************** END OWN PATCH **********************
}
</code></pre>

<p>Almost whole exception:</p>

<p>PDOException Object
(
    [message:protected] =&gt; SQLSTATE[IM001]: Driver does not support this function: driver does not support getting attributes
    [string:private] =&gt; 
    [code:protected] =&gt; IM001
    [file:protected] =&gt; /home/www/some_project/library/Zend/Db/Adapter/Pdo/Abstract.php
    [line:protected] =&gt; 361
    [trace:private] =&gt; Array
        (
            [0] =&gt; Array
                (
                    [file] =&gt; /home/www/some_project/library/Zend/Db/Adapter/Pdo/Abstract.php
                    [line] =&gt; 361
                    [function] =&gt; getAttribute
                    [class] =&gt; PDO
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; 4
                        )</p>

<pre><code>            )

        [1] =&gt; Array
            (
                [file] =&gt; /home/www/some_project/library/Zend/Db/Adapter/Pdo/Oci.php
                [line] =&gt; 173
                [function] =&gt; getServerVersion
                [class] =&gt; Zend_Db_Adapter_Pdo_Abstract
                [type] =&gt; -&gt;
                [args] =&gt; Array
                    (
                    )

            )

        [2] =&gt; Array
            (
                [file] =&gt; /home/www/some_project/library/Zend/Db/Table/Abstract.php
                [line] =&gt; 696
                [function] =&gt; describeTable
                [class] =&gt; Zend_Db_Adapter_Pdo_Oci
                [type] =&gt; -&gt;
                [args] =&gt; Array
                    (
                        [0] =&gt; PACJ
                        [1] =&gt; 
                    )

            )

        [3] =&gt; Array
            (
                [file] =&gt; /home/www/some_project/library/Zend/Db/Table/Abstract.php
                [line] =&gt; 722
                [function] =&gt; _setupMetadata
                [class] =&gt; Zend_Db_Table_Abstract
                [type] =&gt; -&gt;
                [args] =&gt; Array
                    (
                    )

            )

        [4] =&gt; Array
            (
                [file] =&gt; /home/www/some_project/library/Zend/Db/Table/Abstract.php
                [line] =&gt; 762
                [function] =&gt; _getCols
                [class] =&gt; Zend_Db_Table_Abstract
                [type] =&gt; -&gt;
                [args] =&gt; Array
                    (
                    )

            )

        [5] =&gt; Array
            (
                [file] =&gt; /home/www/some_project/library/Zend/Db/Table/Abstract.php
                [line] =&gt; 846
                [function] =&gt; _setupPrimaryKey
                [class] =&gt; Zend_Db_Table_Abstract
                [type] =&gt; -&gt;
                [args] =&gt; Array
                    (
                    )

            )

        [6] =&gt; Array
            (
                [file] =&gt; /home/www/some_project/library/Zend/Db/Table/Select.php
                [line] =&gt; 99
                [function] =&gt; info
                [class] =&gt; Zend_Db_Table_Abstract
                [type] =&gt; -&gt;
                [args] =&gt; Array
                    (
                    )

            )

            ------- TRUNCATED UNRELATED TRACE ----------

[errorInfo] =&gt; Array
    (
        [0] =&gt; IM001
        [1] =&gt; 0
    )
</code></pre>

<p>)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-01-11T14:33:24.000+0000</p> 
        <div class="body">
            <p>Fixed with SVN 13600</p>

        </div>
    </div>
    </div>

