<h2>ZF-5081: Zend_View_Helper_FormSelect escaping html entities</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-11-27T04:40:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-16T02:02:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Lock (catharsisjelly)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8722">ZF-8722</a></li>
            <li><a href="/issues/browse/ZF-7403">ZF-7403</a></li>
            <li><a href="/issues/browse/ZF-9400">ZF-9400</a></li>
            <li><a href="/issues/browse/ZF-9388">ZF-9388</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am trying to create a select with currency and Im providing it a HTML entity for the Euro, which then gets encoded again</p>

<pre class="literal"> 
 $this-&gt;addElement('select', 'Currency', array(
    'label' =&gt; '/h',
    'multiOptions' =&gt; array('null' =&gt; 'Select...', 'EUR' =&gt; '€', 'GBP' =&gt; '£', 'USD' =&gt; '$' )
 ))
</pre>

<p>ouputs</p>

<pre class="literal"> 
Select...&amp;euro;&amp;pound;$</pre>

<p>What Id like is to be able to switch escaping off perhaps.  I can see the need to do this on a per option basis.  Providing a Euro symbol does not escape to &amp;euro;</p>

<p>Update : I found out how to do non formatted text so updated my example to be more accurate</p>

<p>Thanks :)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Loïc Frering (loic.frering) on 2008-12-01T03:33:12.000+0000</p> 
        <div class="body">
            <p>It would also be nice to render $nbsp; :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dan Entous (dan_nl) on 2009-05-04T19:21:35.000+0000</p> 
        <div class="body">
            <p>Is it possible to use utf-8 in your application and then use the actual € and £ symbols just like the $ symbol?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-05T05:31:22.000+0000</p> 
        <div class="body">
            <p>Tell Zend_View to use utf-8 encoding: $view-&gt;setEncoding('utf-8') if you want to use UTF-8 symbols directly.</p>

<p>As for the original reporter's issue, you can do this already. Pull the 'ViewHelper' decorator from the element, and set the 'escape' option to a boolean false:</p>

<pre class="highlight"><code>
$decorator = $multi-&gt;getDecorator('viewHelper');
$decorator-&gt;setOption('escape', false);
</code></pre>

        </div>
    </div>
    </div>

