<h2>ZF-550: Possible Alternative for ctype_alpha()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-11-14T12:24:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-249">ZF-249</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If any i18n/l10n components need ctype_alpha(), instead of implementing ctype_alpha() using PHP, see possible alternative described in ZF-249.</p>

<p>```</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-11-17T11:19:19.000+0000</p> 
        <div class="body">
            <p>Thomas wrote:
{quote}1.) Not all languages seemed to be supported
2.) Performance problems if used in standard... should be selectable when 
used if use it or not
3.) This way ALL characters would be given... So if we have "Exámplé" it 
would also returned but á and è are not
contained within the english characterset. Could lead to problems...</p>

<p>Not sure if there are other related issues but this was what came me in 
mind.{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2006-11-17T14:18:31.000+0000</p> 
        <div class="body">
            <p>This issue is not exactly a dependency, but use of this trick in the ZF should be consistent, if it is used at all.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2006-12-17T12:37:15.000+0000</p> 
        <div class="body">
            <p>We already fixed the related issue by using the /u parameter with preg_match.</p>

        </div>
    </div>
    </div>

