<h2>ZF-5938: Zend_Cache_Backend_Memcached failure_callback option</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-03-04T07:40:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-10T09:16:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6239">ZF-6239</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We should have an option to set failure call back function. I am trying to get failure count and report to admin if the memcache server is failing.</p>

<p>if (!array_key_exists('failure_callback', $server)) {
    $server['failure_callback'] = '';
}
$this-&gt;_memcache-&gt;addServer($server['host'], $server['port'], $server['persistent'],
    $server['weight'], $server['timeout'],
    $server['retry_interval'], $server['status'],
    $server['failure_callback']<br />
);</p>

<p>for now I am extending the class and over ruled the constructor.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-03-28T04:04:03.000+0000</p> 
        <div class="body">
            <p>Hi, Imthiaz.</p>

<p>The failure_callback requires only string ?</p>

<p>I have afraid because the failure_callback may become varied types.
<a href="http://jp.php.net/manual/en/language.pseudo-types.php#language.types.callback">http://jp.php.net/manual/en/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-04-03T20:41:26.000+0000</p> 
        <div class="body">
            <p>I add the option to addServer. 
But , please tell me if the fix will break compatibility  from ZF-5887</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Imthiaz (hmimthiaz) on 2009-04-03T22:20:39.000+0000</p> 
        <div class="body">
            <p>Hi</p>

<p>Thanks for the update, I used this file and it worked perfect.</p>

<p><a href="http://framework.zend.com/svn/framework/standard/trunk/library/Zend/Cache/Backend/Memcached.php">http://framework.zend.com/svn/framework/…</a></p>

<p>Can we have one function to get the memcache object</p>

<p>public function getMemcacheObject(){
    return $this-&gt;_memcache;
}</p>

<p>This can be really usefull when to get stats from the connected servers.</p>

<p>$allServerFailed = true;
$cacheServerStatus = $this-&gt;cacheAdapterClassInstance-&gt;getMemcacheObject ()-&gt;getExtendedStats ();
if (! empty ( $cacheServerStatus )) {
    foreach ( $cacheServerStatus as $server =&gt; $status ) {
        if ($status !== false) {
            $allServerFailed = FALSE;
        }
    }
}</p>

<p>Thanks for your update.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-04-04T03:39:07.000+0000</p> 
        <div class="body">
            <p>Hi, Imthiaz.</p>

<p>I feel happy because you feel good on this update. :-)</p>

<p>I will be also happy if you create new issue about getMemcacheObject() .</p>

<p>With Best Wishes.</p>

        </div>
    </div>
    </div>

