<h2>ZF-57: Zend_Db_Table functionality for working with table structure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-06-20T03:14:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.2.0 (29/Oct/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-113">ZF-113</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Some very usefull enhancements for Zend_Db.</p>

<p>Zend_Db functionality for working with table structure.</p>

<p>Possible interface:
$table = new Table(); // extends Zend_Db_Table
$schema = new Zend_Table_Schema($table);
$schema-&gt;addField('fieldname', array('type' =&gt; 'VARCHAR', 'null' =&gt; true));</p>

<p>$schema-&gt;deleteField(
    title // field title in DB
);</p>

<p>$schema-&gt;addField(
    title, // field title in DB
    'VARCHAR', //type
    255, // length
    null, // default value
    ...
);</p>

<p>$schema-&gt;alterField(
    title, // field title in DB
    'VARCHAR', //type
    255, // length
    null, // default value
    ...
);</p>

<p>Functionality for table structure import into DB and export to xml or other format would be very usefull too.</p>

<p>Possible interface:
$schema-&gt;importStructure('table_structure.xml');
$schema-&gt;exportStructure('table_structure.xml');</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Justin Hendrickson (toxygene) on 2006-07-12T11:20:50.000+0000</p> 
        <div class="body">
            <p>This appears to be a duplicate of ZF-113, or vice versa.</p>

        </div>
    </div>
    </div>

