<h2>ZF-5705: Zend_Controller_Request_Http::getHeader returns false for an &quot;Content Type&quot; lookup in some installations.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-06T03:51:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-10T15:38:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bas K (bas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The method for retrieving headers is not complete so when the method apache_request_headers() is not available false will be returned on some systems</p>

<p>This happens when the $<em>SERVER does not contains 'HTTP_CONTENT_TYPE' but 'CONTENT_TYPE', since the system looks for HTTP</em> + requestvar.</p>

<p>(line 950)</p>

<p>$temp = 'HTTP_' . strtoupper(str_replace('-', '_', $header));
if (!empty($_SERVER[$temp])) {
            return $_SERVER[$temp];
}</p>

<p>After the above the following could be added
        $temp = strtoupper(str_replace('-', '_', $header));
        if (!empty($_SERVER[$temp])) {
            return $_SERVER[$temp];
        }</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Joe Gornick (jgornick) on 2011-05-09T19:39:51.000+0000</p> 
        <div class="body">
            <p>The issue here is that CONTENT_TYPE and CONTENT_LENGTH are not prefixed with HTTP_.  The reason is because CONTENT_TYPE and CONTENT_LENGTH are not protocol specific meta-variables (<a href="http://www.ietf.org/rfc/rfc3875">http://www.ietf.org/rfc/rfc3875</a>).</p>

<p>So, unless you have the apache_request_headers method available, the type and length of the request are never obtained for the request.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Aaron S. Hawley (ashawley) on 2011-05-09T19:51:37.000+0000</p> 
        <div class="body">
            <p>Never say, "never".</p>

<p>The current test in Zend_Controller_Request_HttpTest::testGetHeader() has</p>

<pre class="highlight"><code>
$_SERVER['HTTP_CONTENT_TYPE']    = 'text/json';
</code></pre>

<p>So it would seem some PHP environments do put HTTP_CONTENT_TYPE in $_SERVER.</p>

<p>I'm not sure what the appropriate patch to Zend_Controller_Request_Http is, but I know I add this to dispatch script (public/index.php).</p>

<pre class="highlight"><code>
if (isset($_SERVER['CONTENT_TYPE'])
    &amp;&amp; !isset($_SERVER['HTTP_CONTENT_TYPE'])
) {
    $_SERVER['HTTP_CONTENT_TYPE'] = $_SERVER['CONTENT_TYPE'];
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Joe Gornick (jgornick) on 2011-05-09T20:31:17.000+0000</p> 
        <div class="body">
            <p>I'd be interested to find out what environments return HTTP_CONTENT_TYPE.</p>

<p>In regards to a patch for HTTP requests, I would say we try to load the requested meta variable without the HTTP prefix, then if not found, add the HTTP prefix and try that.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bas K (bas) on 2011-05-10T15:30:19.000+0000</p> 
        <div class="body">
            <p>i believe when i submitted this issue i was developing on an CentOS 5 system with php5.2.something</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Joe Gornick (jgornick) on 2011-05-10T15:38:23.000+0000</p> 
        <div class="body">
            <p>I'm experiencing it on Windows XP with Apache 2.2/PHP5.3.x.</p>

        </div>
    </div>
    </div>

