<h2>ZF-5811: Zend_Http_Client_Adapter_Socket does not use close response header for HEAD request</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-17T04:28:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-17T22:01:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Socket adapter does not close connection when receive "Connection: close" response for HEAD request with persistent connect.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2009-07-23T15:25:15.000+0000</p> 
        <div class="body">
            <p>Thanks for reporting, should be fixed in CS-17012 (svn trunk) - please test and close or reopen.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-17T22:01:58.000+0000</p> 
        <div class="body">
            <p>I set fix version. I find this at SVN r17118 in 1.9 branch.</p>

        </div>
    </div>
    </div>

