<h2>ZF-5001: Two &quot;Your 'upload_max_filesize' config setting allows only 2048. You set 3000.&quot; unit tests errors</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-11-20T01:21:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-01T13:50:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.1 (01/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
1) testRenderMaxFileSize(Zend_Form_Decorator_FileTest)
Your 'upload_max_filesize' config setting allows only 2048. You set 3000.
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/Form/Element/File.php:566
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/Form/Element/File.php:566</p>

<p>2) testSettingMaxFileSize(Zend_Form_Element_FileTest)
Your 'upload_max_filesize' config setting allows only 2048. You set 3000.
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/Form/Element/File.php:566
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/Form/Element/File.php:566
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-20T10:03:53.000+0000</p> 
        <div class="body">
            <p>Should work with r12717.</p>

<p>Default ini settings for MAX_UPLOAD_FILES are now used from ini.
Windows default is much higher than 3000 bytes</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-11-20T10:41:19.000+0000</p> 
        <div class="body">
            <p>Fixed!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-01T13:50:46.000+0000</p> 
        <div class="body">
            <p>Updating these issues to mark them resolved for 1.7.1.</p>

        </div>
    </div>
    </div>

