<h2>ZF-5379: require_once 'Zend/Search/Lucene/Analysis/Analyzer/Common.php'; give me a Fatal error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-30T06:49:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-12T12:07:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2456">ZF-2456</a></li>
            <li><a href="/issues/browse/ZF-5109">ZF-5109</a></li>
            <li><a href="/issues/browse/ZF-5717">ZF-5717</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11693/patch_ZSL.patch">patch_ZSL.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This sample of code:</p>

<pre class="highlight"><code>
&lt;?php
set_include_path ( '../library');
require_once 'Zend/Search/Lucene/Analysis/Analyzer/Common.php';
</code></pre>

<p>give me</p>

<pre class="highlight"><code>
Fatal error: Class 'Zend_Search_Lucene_Analysis_Analyzer_Common' not found in D:\web\ZendFramework\standard\trunk\library\Zend\Search\Lucene\Analysis\Analyzer\Common\Utf8.php on line 35
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2008-12-30T06:53:14.000+0000</p> 
        <div class="body">
            <p>I remove all unnecessary require_once and apply a lazy-loading</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-02-09T04:31:33.000+0000</p> 
        <div class="body">
            <p>See [<a href="http://framework.zend.com/issues/browse/ZF-2456?focusedCommentId=18717#action_18717%7Ccomment">http://framework.zend.com/issues/browse/…</a>] on the [ZF-2456] issue.</p>

<p>Analysers don't require lazy loading (possible performance improvement doesn't comparable with index operations time) and in the same time current implementation gives the possibility to "turn on" all existing analyzers by one require once - require_once 'Zend/Search/Lucene/Analysis/Analyzer.php' or require_once 'Zend/Search/Lucene.php'</p>

<p>On the other hand that should be described in the documentation, so I've just created another issue for this - [ZF-5717].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-02-09T09:01:17.000+0000</p> 
        <div class="body">
            <p>I understand well but the loading is realized by a script which analyses the code, thus some files could be load before 'Zend/Search/Lucene.php'. BTW, I think it's not a good thing that we obtain 'Fatal error' when we wanted to load a particular file.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-11-12T12:07:08.000+0000</p> 
        <div class="body">
            <p>Problem is resolved.</p>

<p>Zend_Search_Lucene doesn't use any special require_once policy now.</p>

        </div>
    </div>
    </div>

