<h2>ZF-5825: Zend_Service_Amazon tracklist fetching</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-18T04:48:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-20T08:17:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.6 (02/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Fetching tracklist from Amazon search is not working properly when product (album) has more than 1 disc.</p>

<pre class="highlight"><code>
require_once 'Zend/Service/Amazon/Query.php';
$query = new Zend_Service_Amazon_Query('XXXXXXXXXXXX','UK');
$query-&gt;Category('Blended')-&gt;Keywords("5036742001123")-&gt;ResponseGroup('Tracks,Small,Medium,ItemAttributes');
$results = $query-&gt;search();
Zend_Debug::dump($results-&gt;current()-&gt;Tracks);
</code></pre>

<p>outputs:</p>

<pre class="highlight"><code>
array(1) {
  [""] =&gt; string(14) "Rock Tha House"
}
</code></pre>

<p>output should be:</p>

<pre class="highlight"><code>
array(2) {
  [1] =&gt; array(11) {
    [0] =&gt; string(12) "Ressurection"
    [1] =&gt; string(6) "Creeps"
    [2] =&gt; string(15) "White lightning"
    [3] =&gt; string(14) "Check-out Time"
    [4] =&gt; string(6) "Pacman"
    [5] =&gt; string(9) "Reach out"
    [6] =&gt; string(7) "Syringe"
    [7] =&gt; string(14) "Rock Tha House"
    [8] =&gt; string(5) "Greed"
    [9] =&gt; string(10) "Flightpath"
    [10] =&gt; string(8) "Fastlane"
  }
  [2] =&gt; array(13) {
    [0] =&gt; string(6) "Creeps"
    [1] =&gt; string(10) "Flightpath"
    [2] =&gt; string(12) "Ressurection"
    [3] =&gt; string(9) "Reach out"
    [4] =&gt; string(7) "Syringe"
    [5] =&gt; string(14) "Check out time"
    [6] =&gt; string(15) "White lightning"
    [7] =&gt; string(6) "Pacman"
    [8] =&gt; string(5) "Greed"
    [9] =&gt; string(11) "Bleep bleep"
    [10] =&gt; string(12) "Kerb crawler"
    [11] =&gt; string(8) "Fastlane"
    [12] =&gt; string(14) "Rock Tha House"
  }
}
</code></pre>

<p>To resolve this problem: 
Line 156 in file Zend/Service/Amazon/Item.php is</p>

<pre class="highlight"><code>
But it should be </code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-02-18T05:01:18.000+0000</p> 
        <div class="body">
            <p>Assigning to Jon Whitcraft.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-02-20T07:08:52.000+0000</p> 
        <div class="body">
            <p>I am not seeing that code in the Zend/Service/Amazon/Item.php file.  Can you tell me what version of ZF you are using?  You can check in the Zend/Version.php file.</p>

<p>The latest trunk file has this on like 156</p>

<pre class="highlight"><code>
require_once 'Zend/Service/Amazon/Image.php';
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Timo Vildersen (timo.vildersen@gmail.com) on 2009-02-20T07:51:51.000+0000</p> 
        <div class="body">
            <p>Version 1.7.5 ... downloaded few days ago.</p>

<p>And line 156 in Zend/Service/Amazon/Item.php <em>IS</em>
```</p>

<p>I can't look what's in trunk ... Code Browser is down at the moment :(</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-02-20T08:09:17.000+0000</p> 
        <div class="body">
            <p>Trunk has a lot of other fixes in it that was the release branch has.  I'm looking into why the trunk never got synced to the release branch on these fixes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-02-20T08:17:26.000+0000</p> 
        <div class="body">
            <p>These have been merged into the release branch (r14126) and will come out with the next release.</p>

        </div>
    </div>
    </div>

