<h2>ZF-5715: Zend_Validate_Abstract, _translatorDisabled</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-02-08T02:55:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-08T12:28:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Piotr Kabacinski (kabot)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend_Form and Zend_Form_Element there is possibility to turn off translator with method setDisableTranslator().
My propose is to add such a functionality to method Zend_Validate_Abstract::getTranslator like in below code</p>

<pre class="highlight"><code>
    public function getTranslator()
    {
        if ($this-&gt;translatorIsDisabled()) {
            return null;
        }

        if (null === $this-&gt;_translator) {
            return self::getDefaultTranslator();
        }

        return $this-&gt;_translator;
    }
</code></pre>

<p>By default translator could be enabled but when you disable translation in Zend_Form_Element it will be disabled in validator also.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-03-08T12:27:50.000+0000</p> 
        <div class="body">
            <p>New feature added with r14249</p>

        </div>
    </div>
    </div>

