<h2>ZF-5349: Pass null value to setItemCountPerPage()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-12-24T05:15:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-27T12:37:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Lock (catharsisjelly)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I wanted to give the user the ability to return all rows from the DB on the same page, so in a user interface you can select 'All' which then sends a 0 to setItemCountPerPage()</p>

<p>This produces a warning of divide by 0 when it runs _calculatePageCount internally, therefore we should probably test to see if _itemCountPerPage is 0 or null first, and return a 0 if it is?  Something like :</p>

<pre class="literal">
   /**
     * Calculate the page count
     *
     * @return integer
     */
   protected function _calculatePageCount()
   {
        if ( $this-&gt;_itemCountPerPage &gt; 0 )
            return (integer) ceil($this-&gt;_adapter-&gt;count() / $this-&gt;_itemCountPerPage);
        return 0;
   }
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2008-12-24T05:29:12.000+0000</p> 
        <div class="body">
            <p>Use the All ScrollingStyle</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-12-24T05:34:06.000+0000</p> 
        <div class="body">
            <p>Actual code is :</p>

<pre class="highlight"><code>
public function setItemCountPerPage($itemCountPerPage)
    {
        $this-&gt;_itemCountPerPage = (integer) $itemCountPerPage;
        if ($this-&gt;_itemCountPerPage == 0) {
            $this-&gt;_itemCountPerPage = 1;
        }
        $this-&gt;_pageCount        = $this-&gt;_calculatePageCount();
// ... ... ...
</code></pre>

<p>If 0 is set, _itemCountPerPage is set to 1, so there cant be division by zero.</p>

<p>Have you got a use case ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Lock (catharsisjelly) on 2008-12-27T09:04:54.000+0000</p> 
        <div class="body">
            <p>Ah sorry my bad, we still might need to change something though.  Found out that I was passing a null value to setItemCountPerPage()  which made it throw the warnings regarding the divide by 0 error.  Might want to add code in to protect against that.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2008-12-27T12:37:02.000+0000</p> 
        <div class="body">
            <p>It might depend on your ZF version.
We had such a bug some versions ago (dont remember), but it has been resolved. Read the SVN log.
(Casting null to int gives 0, which is then converted to 1 in the actual code)</p>

        </div>
    </div>
    </div>

