<h2>ZF-5609: Zend_Form_Element_Checkbox checkedValue is not set</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-22T04:31:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-21T08:09:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Benoit Delporte (benoit)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11955/May-27-2009-2nd.patch">May-27-2009-2nd.patch</a></li>
            <li><a href="/issues/secure/attachment/11954/May-27-2009.patch">May-27-2009.patch</a></li>
            <li><a href="/issues/secure/attachment/11957/May-28-2009.patch">May-28-2009.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have trouble with Zend_Form_Element_Checkbox;
I have a custom Form, and I want to add a Zend_Form_Element_Checkbox like this:</p>

<p>$agreement = new Zend_Form_Element_Checkbox('agreement');<br />
$agreement-&gt;setLabel('cguLabel')
            -&gt;setCheckedValue('1')
            -&gt;setUncheckedValue('0')
                -&gt;setValue('0');
$this-&gt;addElement($agreement);</p>

<p>In my view I do this:(I have the default Decorator):
</p>
    &lt;?= $this-&gt;registerForm-&gt;agreement-&gt;renderViewHelper() ?&gt;


<p>This is the generate HTML:
</p>

<p>So because the input's value is set to 0, I can't know when the checkbox is checked...
I use the renderViewHelper because our graphiste made some template, and I wanr to display each party of the Element like I want where I want.
After some  debugging, I can't fix this comportement with put this line in commentary:</p>

<p>// In Zend/View/Helper/FormCheckbox.php
// In function determineCheckboxInfo</p>

<p>if (is_array($checkedOptions)) {
  if (array_key_exists('checked', $checkedOptions)) {
    $checkedValue = (string) $checkedOptions['checked'];
    unset($checkedOptions['checked']);
  }
  if (array_key_exists('unChecked', $checkedOptions)) {
    $unCheckedValue = (string) $checkedOptions['unChecked'];
    unset($checkedOptions['unChecked']);
  }
  if (null === $checkedValue) {
    $checkedValue = array_shift($checkedOptions);
  }
  if (null === $unCheckedValue) {
    $unCheckedValue = array_shift($checkedOptions);
  }
  // Comment these two lines
  //} elseif ($value !== null) {
  //  $unCheckedValue = self::$_defaultCheckedOptions['unChecked'];
} else {
  $checkedValue   = self::$_defaultCheckedOptions['checked'];
  $unCheckedValue = self::$_defaultCheckedOptions['unChecked'];
}</p>

<p>After commenting these line, the html ouput is good:
</p>

<p>Is this a bug, or i made a mistake somewhere ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benoit Delporte (benoit) on 2009-01-22T12:59:21.000+0000</p> 
        <div class="body">
            <p>Sorry for the unformated code, I re-post it:</p>

<pre class="highlight"><code>

// In function determineCheckboxInfo
// Checked/unchecked values
$checkedValue   = null;
$unCheckedValue = null;
if (is_array($checkedOptions)) {
    if (array_key_exists('checked', $checkedOptions)) {
        $checkedValue = (string) $checkedOptions['checked'];
        unset($checkedOptions['checked']);
    }
    if (array_key_exists('unChecked', $checkedOptions)) {
        $unCheckedValue = (string) $checkedOptions['unChecked'];
        unset($checkedOptions['unChecked']);
    }
    if (null === $checkedValue) {
         $checkedValue = array_shift($checkedOptions);
    }
    if (null === $unCheckedValue) {
         $unCheckedValue = array_shift($checkedOptions);
    }
// Comment these two next lines
//} elseif ($value !== null)  {
//    $unCheckedValue = self::$_defaultCheckedOptions['unChecked'];
} else {
    $checkedValue   = self::$_defaultCheckedOptions['checked'];
    $unCheckedValue = self::$_defaultCheckedOptions['unChecked'];
}

</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoit Delporte (benoit) on 2009-01-28T03:55:43.000+0000</p> 
        <div class="body">
            <p>Nobody for helping me ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-01-28T04:53:02.000+0000</p> 
        <div class="body">
            <p>Patience, please -- there's a huge backlog of bugs, and we can't address all bugs immediately. In this particular case, I know that there are at least two other issues reporting similar problems that also need to be addressed, and I will need to link each of these to ensure that the bugfix addresses each.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoit Delporte (benoit) on 2009-01-28T06:10:21.000+0000</p> 
        <div class="body">
            <p>Ok no probleme, sorry for my impatience. Good luck and thanks for your good work Matthew ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gerard van Helden (drm) on 2009-04-28T07:14:12.000+0000</p> 
        <div class="body">
            <p>Hi Matthew,</p>

<p>Part of the bug is that the render() method of Zend_Form_Element_Checkbox sets the options 'checked' and 'unChecked' correctly before rendering. This is obviously the wrong place to do this.</p>

<pre class="highlight"><code>
public function render(Zend_View_Interface $view = null)
{
    $this-&gt;options = array(
        'checked'   =&gt; $this-&gt;getCheckedValue(),
        'unChecked' =&gt; $this-&gt;getUncheckedValue(),
    );
    return parent::render($view);
}
</code></pre>

<p>My proposed fix:
let the constructor call setCheckedValue('1') and setUncheckedValue('0') by default, and add the following lines:</p>

<pre class="highlight"><code>    
public function setCheckedValue($value)
{
    $this-&gt;_checkedValue = (string) $value;
    // add this:
    $this-&gt;options['checked'] = $this-&gt;_checkedValue;
    return $this;
}

/* ... snip ... */
public function setUncheckedValue($value)
{
    $this-&gt;_uncheckedValue = (string) $value;
    // add this:
    $this-&gt;options['unChecked'] = $this-&gt;_uncheckedValue;
    return $this;
}
</code></pre>

<p>And remove the render() method from Zend_Form_Element_Checkbox.</p>

<p>The neater fix would be to let Zend_View_Helper_FormCheckbox use the same naming scheme for the options as Zend_Form_Element_Checkbox (which is the root of the problem)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Utt (ohdotoh) on 2009-05-20T18:51:15.000+0000</p> 
        <div class="body">
            <p>Maybe I'm off base here, but it seems at least part of this problem is inconsistency in not only naming, but case as well. In some places, checked and unchecked values are called just that, checked and unchecked. Right away this seems to be asking for trouble because checked is also an attribute. Some places they are called checkedValue and uncheckedValue, and then in others they are called checkedValue and unCheckedValue.</p>

<p>(this is from 1.8.0)</p>

<p>Dojo/View/Helper/CheckBox.php:62:     * @param  array $checkedOptions Should contain either two items, or the keys checkedValue and unCheckedValue
Dojo/Form/Element/CheckBox.php:55:    protected $_checkedValue = '1';
Dojo/Form/Element/CheckBox.php:61:    protected $_uncheckedValue = '0';
Dojo/Form/Element/CheckBox.php:80:        if (array_key_exists('checkedValue', $options)) {
Dojo/Form/Element/CheckBox.php:84:        if (array_key_exists('uncheckedValue', $options)) {
Dojo/View/Helper/CheckBox.php:92:            $html .= $this-&gt;_renderHiddenElement($id, $checkboxInfo['unCheckedValue']);
View/Helper/FormCheckbox.php:45:        'checked'   =&gt; '1',
View/Helper/FormCheckbox.php:46:        'unChecked' =&gt; '0'
View/Helper/FormCheckbox.php:92:            $xhtml = $this-&gt;_hidden($name, $checkedOptions['unCheckedValue']);
View/Helper/FormCheckbox.php:159:            'unCheckedValue' =&gt; $unCheckedValue,</p>

<p>In general there seems to be a bit of an anything goes policy for camel casing. we have Checkbox and CheckBox, as well as Multiselect and MultiCheckbox.</p>

<p>That aside, I am seeing this same problem in Dojo Check[Bb]oxes, and need to get this working. I will get my CLA sent in ASAP and other acronyms. If someone (Matthew?) would be so kind as to point me toward the previously mentioned other issues, I would be happy to get out my wrenches and bend some metal.</p>

<p>Sean</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Utt (ohdotoh) on 2009-05-27T13:36:51.000+0000</p> 
        <div class="body">
            <p>This patch (May-27-2009.patch) attempts to bring case and naming consistency to checkedValue and uncheckedValue in:</p>

<p>View/Helper/FormCheckbox.php
Form/Element/Checkbox.php
Dojo/View/Helper/CheckBox.php
Dojo/Form/Element/CheckBox.php</p>

<p>I'm still poking around finding the root source of the problem in Dojo CheckBox. It appears that the checkedValue and uncheckedValue should be getting passed into the options array somewhere along the way and they are not, or they got passed in and then got removed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Utt (ohdotoh) on 2009-05-28T00:02:10.000+0000</p> 
        <div class="body">
            <p>This patch includes changes to setOptions in both Form/Element/Checkbox.php and in Dojo/Form/Element/CheckBox.php to remove the overriden render and set the options for checkedValue and uncheckedValue in setOptions instead and let the parent render method do the work</p>

<p>Also includes all the changes in the previous patch file.
So far it's working for me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Utt (ohdotoh) on 2009-05-28T00:04:08.000+0000</p> 
        <div class="body">
            <p>I meant, "This patch (May-27-2009-2nd.patch)" in the previous comment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sean Utt (ohdotoh) on 2009-05-28T00:43:13.000+0000</p> 
        <div class="body">
            <p>I looked it over a little and reworked the patch (May-28-2009.patch) to use Gerard's suggestion to set the options for checkedValue and uncheckedValue in setCheckedValue and setUncheckedValue, otherwise calling one of them after calling setOptions might mangle things. Also, had to check to be sure options was an array before setting.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jelle-Jan van Veelen (pelle) on 2009-08-21T06:25:14.000+0000</p> 
        <div class="body">
            <p>Yesterday I also bumped into this bug. Took me a few hours to see what was wrong (including a ZF update to the latest version, hoping that would fix it - but it didn't ;)). 
It would be nice if this can be fixed soon. I've got the feeling that more people will encounter this behaviour.</p>

<p>Thanks :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-08-21T08:09:29.000+0000</p> 
        <div class="body">
            <p>I've applied the most recent patch, though with some modifications (the $options array needs to be present by default for the default use case (not setting either value) to work correctly). Patch has been ported to the 1.9 release branch as well.</p>

        </div>
    </div>
    </div>

