<h2>ZF-5956: Zend_Paginator factory chokes when Zend_Db_Select has UNION</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-06T09:42:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-18T17:24:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Panupan Sriautharawong (lionpeal)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Lets say $select1 and $select2 are Zend_Db_Selects that give identical fields.</p>

<p>Then we do $select1 UNION $select2:
$select = $db-&gt;select()-&gt;union(array($select1, $select2));</p>

<p>If we do:
print_r($this-&gt;_db-&gt;fetchAll($select));</p>

<p>It will return arrays of the expected union of $select1 and $select2</p>

<p>But when we try to make our paginator:
$paginator = Zend_Paginator::factory($select);</p>

<p>We get a crash:
exception 'Zend_Db_Select_Exception' with message 'No table has been specified for the FROM clause'</p>

<p>The expected result is no crash.</p>

<p>The workaround (inefficient) right now is just to give the factory the whole array:
Zend_Paginator::factory($this-&gt;_db-&gt;fetchAll($select));</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thorsten Ruf (saphir2k) on 2009-05-26T05:30:32.000+0000</p> 
        <div class="body">
            <p>There is no assigned developer at the moment. Is this bug not critical?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-26T05:37:32.000+0000</p> 
        <div class="body">
            <p>Since April 3rd this issue has been assigned to  Jurrien Stutterheim.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-05-26T14:33:25.000+0000</p> 
        <div class="body">
            <p>Could you give me a simple use-case including:</p>

<ul><li>A simple UNION query</li>
<li>A COUNT query, based on that UNION query.</li>
</ul><p>This will help me greatly in formulating a patch.</p>

<p>Cheers,</p>

<ul><li>Jurriën</li>
</ul>
        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thorsten Ruf (saphir2k) on 2009-05-27T00:34:00.000+0000</p> 
        <div class="body">
            <p>Here are the two use-cases:</p>

<pre class="highlight"><code>
$select1-&gt;from('user',array('firstname','lastname'));
$select1-&gt;where('id = ?',1);
        
$select2 = $this-&gt;db-&gt;select();
$select2-&gt;from('user',array('firstname','lastname'));
$select2-&gt;where('id = ?',2);
        
$selectUnion = $this-&gt;db-&gt;select();    
$selectUnion-&gt;union(array($select1,$select2));
</code></pre>

<p>Its hard to create a fast count with a union statement, i'm pretty sure this one is the slowest. Hopefully a database expert is watching this issue. ;-)</p>

<pre class="highlight"><code>
$select1-&gt;from('user',array('firstname','lastname'));
$select1-&gt;where('id = ?',1);
        
$select2 = $this-&gt;db-&gt;select();
$select2-&gt;from('user',array('firstname','lastname'));
$select2-&gt;where('id = ?',2);
        
$selectUnion = $this-&gt;db-&gt;select();    
$selectUnion-&gt;union(array($select1,$select2));

// Wrap a SELECT count(*) statement around the union 
$selectCount = $this-&gt;db-&gt;select();     
$selectCount-&gt;from($selectUnion,'count(*)');

</code></pre>

<p>Regards,
Thorsten</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-06-18T17:24:02.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 16144 and merged to release-1.8 in revision 16145</p>

        </div>
    </div>
    </div>

