<h2>ZF-513: [Incubator] [Coding Standard] Zend_Http_Cookiejar to Zend_Http_CookieJar</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2006-11-08T14:47:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>"Cookie jar" is two words, so it should probably be Zend_Http_CookieJar instead.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-09T15:58:30.000+0000</p> 
        <div class="body">
            <p>Assigning to Shahar Evron.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2006-11-10T13:47:56.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 1546.</p>

<p>Nothing a couple of bash + sed lines can't handle ;)</p>

        </div>
    </div>
    </div>

