<h2>ZF-5210: Incorrect Package in API Doc - Zend_Twitter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-12-11T07:46:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-16T06:41:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When searching through the API Documentation a friend and I found a package in the package listing called Zend_Twitter. It had two entries; one was RememberTheMilk which had twitter.php and the other was Twitter that had exception.php. When looking in the downloaded framework, Zend_Twitter does not exist and there is no RememberTheMilk support. Just giving a heads up.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-11T17:38:40.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r13173</p>

        </div>
    </div>
    </div>

