<h2>ZF-5873: Zend_Controller_Action_Helper_Redirector kills the session</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-02-24T03:49:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-25T09:24:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Christer Edvartsen (cogo)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11767/Redirector.php.patch">Redirector.php.patch</a></li>
            <li><a href="/issues/secure/attachment/11768/RedirectorTest.php.patch">RedirectorTest.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the redirectAndExit() method in the Zend_Controller_Action_Helper_Redirector class the session is closed. This causes problems when the session needs to be available in a function that is registered as a shutdown function.</p>

<p>An option should be available so the session is not closed automatically.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christer Edvartsen (cogo) on 2009-02-24T03:55:23.000+0000</p> 
        <div class="body">
            <p>The following patch implements an option that be be used to skip closing of the session. The default is to close it. The patch has been made against revision 14153 of <a href="http://framework.zend.com/svn/framework/standard/trunk/library/Zend/Controller/Action/Helper/Redirector.php">http://framework.zend.com/svn/framework/…</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christer Edvartsen (cogo) on 2009-02-24T04:03:40.000+0000</p> 
        <div class="body">
            <p>This patch adds a test method that tests the setting/getting of the new option. The patch is made against the same revision as the other patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by sebastien crocquesel (cortex) on 2009-02-25T02:37:53.000+0000</p> 
        <div class="body">
            <p>That sounds good to me. We already talk about this on the ML and agree with this new behavior. Letting default to do the close to avoid the php writing session bug on redirect.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christer Edvartsen (cogo) on 2009-02-25T08:37:23.000+0000</p> 
        <div class="body">
            <p>Closed in revision 14164</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-02-25T09:24:50.000+0000</p> 
        <div class="body">
            <p>cogo nice work. Just a reminder, since this implements some new functionality, please do not merge to the 1.7 release branch; the fix will need to wait to release until 1.8.</p>

        </div>
    </div>
    </div>

