<h2>ZF-5972: Could not remove first file validator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-09T08:18:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-10T05:33:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.7 (16/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>if (!$index = array_search($key, $this-&gt;_files[$file]['validators'])){
==&gt; if ($index ===0) the test is skipped and the validator is not removed</p>

<p>=&gt; better use :
if ( ($index = array_search($key, $this-&gt;_files[$file]['validators'])) === false ) {</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-03-10T05:32:33.000+0000</p> 
        <div class="body">
            <p>That's correct behaviour.</p>

<p>It is not allowed to delete the Upload validator as it's essential for file uploads. And the upload validator is always attached as first validator for file elements.</p>

        </div>
    </div>
    </div>

