<h2>ZF-5232: testDoesNotFailOnObjectInput(Zend_Validate_AbstractTest)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-12-12T11:26:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>testDoesNotFailOnObjectInput(Zend_Validate_AbstractTest) stops unit tests execution without any output (trunk version, tested at Linux and Windows)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-12-13T12:09:46.000+0000</p> 
        <div class="body">
            <p>I can not verify this...</p>

<p>Running on Windows, trunk, php 5.2.5, this test passes without problems and outputs no error (14 tests, 34 exceptions tested).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-15T09:42:42.000+0000</p> 
        <div class="body">
            <p>Problem still exists in my environment. Working on it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-16T10:23:21.000+0000</p> 
        <div class="body">
            <p>The problem is caused by the fact that stdClass objects can't be converted to string, <em>and</em> [ZF-4463] fix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-18T07:28:45.000+0000</p> 
        <div class="body">
            <p>Fixed.</p>

        </div>
    </div>
    </div>

