<h2>ZF-5793: Support of &quot; `:col` &quot; in PDO Mysql query</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-15T16:01:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-18T11:19:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pieter Kokx (kokx)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-1398">ZF-1398</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>(sorry for my English)</p>

<pre class="highlight"><code> 
try {
    $db = Zend_Db::factory('Pdo_Mysql', 
        array('host' =&gt; '127.0.0.1' , 'username' =&gt; 'root' , 'password' =&gt; '' , 'dbname' =&gt; 'test',
            'driver_options' =&gt; array(PDO::MYSQL_ATTR_DIRECT_QUERY =&gt; 'SET NAMES \'utf8\'')));
} catch (Zend_Db_Exception $e) {    // on passe l'exception sous silence, elle sera gérée dans le système MVC plus tard 
}
Zend_Registry::set('Zend_Db', $db);
$result = $db-&gt;query("SELECT col as `:col` FROM  `table`");
</code></pre>

<p>Output :</p>

<pre class="highlight"><code> 
<b>Fatal error</b>:  Uncaught exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[HY093]: Invalid parameter number: no parameters were bound' in C:\www\web\default\allgamestats\v2\Zend\Db\Statement\Pdo.php:238
Stack trace:
#0 ..\Zend\Db\Statement.php(283): Zend_Db_Statement_Pdo-&gt;_execute(Array)
#1 ..\Zend\Db\Adapter\Abstract.php(433): Zend_Db_Statement-&gt;execute(Array)
#2 ..\Zend\Db\Adapter\Pdo\Abstract.php(230): Zend_Db_Adapter_Abstract-&gt;query('SELECT ip as `:...', Array)
#3 ..starter.php(21): Zend_Db_Adapter_Pdo_Abstract-&gt;query('SELECT ip as `:...')
#4 {main}
  thrown in <b>..\Zend\Db\Statement\Pdo.php</b> on line <b>238</b><br /></code></pre>

<p>I have localized this error, it's in class Zend_Db_Statement and protected function _parseParameters().</p>

<p>But the query works with : 
"SELECT col as ':col' FROM  <code>table</code>"
replace <code></code> with -&gt; ' '</p>

<p>I do not know if the use of `` is a convention of MySQL, but phpMyAdmin uses this !</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pieter Kokx (kokx) on 2010-02-18T10:57:10.000+0000</p> 
        <div class="body">
            <p>This problem occurs because currently, all statements are runned as prepared statements. Which is already reported in ZF-1398.</p>

        </div>
    </div>
    </div>

