<h2>ZF-559: DocBlock Standardization</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2006-11-15T13:03:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-09-02T10:39:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.6.0 (02/Sep/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-691">ZF-691</a></li>
            <li><a href="/issues/browse/ZF-3065">ZF-3065</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The coding standards should provide accurate docblocks that can be cut and pasted into code by framework developers:</p>

<p><a href="http://framework.zend.com/wiki/x/PQ">http://framework.zend.com/wiki/x/PQ</a></p>

<p>The current examples do not reflect de facto standards in the framework code base.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2006-12-28T14:51:10.000+0000</p> 
        <div class="body">
            <p>Linked to doc standards cleanup</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simone Carletti (weppos) on 2007-11-11T18:13:09.000+0000</p> 
        <div class="body">
            <p>+1 for this ticket.</p>

<p>I'm feeling a bit confused.
<a href="http://framework.zend.com/wiki/display/ZFDEV/PHP+Coding+Standard+%28draft%29#PHPCodingStandard%28draft%29-InlineDocumentation">Here</a>   you suggest to use a block with a license that is no longer the right one (see ZF-507).</p>

<p>Here ZF-703 Bill agree to include SVN $Id$ keyword in files but I can't find many files using it in the latest ZF release.</p>

<p>Many files have different copyright string with basically the same information</p>

<p>{quote}
Copyright (c) 2005-2007 Zend Technologies USA Inc. (<a href="http://www.zend.com">http://www.zend.com</a>)
Copyright (c) 2005-2008 Zend Technologies USA Inc. (<a href="http://www.zend.com">http://www.zend.com</a>)
Copyright (c) 2005-2007 Zend Technologies USA Inc. (<a href="http://www.zend.com/">http://www.zend.com/</a>)
Copyright (c) 2007 Jordan Raub <a href="mailto:ludicruz@yahoo.com">ludicruz@yahoo.com</a> and Felix Jendrusch <a href="mailto:felixjendrusch@googlemail.com">felixjendrusch@googlemail.com</a>
{quote}</p>

<p>A definitive standard would be more than welcome. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-03-21T17:05:30.000+0000</p> 
        <div class="body">
            <p>This issue should have been fixed for the 1.5 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T13:12:05.000+0000</p> 
        <div class="body">
            <p>This doesn't appear to have been fixed in 1.5.0. Please update if this is not correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-04-18T17:04:41.000+0000</p> 
        <div class="body">
            <p>Thomas, aren't you working on this now? If so, please close this when you are finished. Otherwise, feel free to unassign it from yourself.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-04-18T17:13:21.000+0000</p> 
        <div class="body">
            <p>I'm working on the coding standard testbed which will then also close this issue.</p>

<p>Actually I've already fixed this issue for the existing files, but as new files are added we will for now have the problem also for them. See r9245 where darby added the header for a new file afterwards.</p>

<p>I will keep this issue opened until I have finished the testbed.
Ralph and me are working on closing the whole bunch of issues related to this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T21:22:01.000+0000</p> 
        <div class="body">
            <p>Updating to comply with new IT component conventions.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-06-16T07:49:39.000+0000</p> 
        <div class="body">
            <p>The Docblock is checked and forced by the new CodeSniffer ruleset.
Actually all files within the core have the new docblock integrated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-09-02T10:39:21.000+0000</p> 
        <div class="body">
            <p>Updating for the 1.6.0 release.</p>

        </div>
    </div>
    </div>

