<h2>ZF-5666: jQuery UI TabContainer rendering incorrectly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-01T02:15:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-11T03:25:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.5 (16/Feb/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Brian Passavanti (gottaloveit)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6981">ZF-6981</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There's a bug in the jQuery UI TabContainer helper that makes the tabs not render correctly.</p>

<p>Screenshot of tabs:
!<a href="http://www.freeimagehosting.net/uploads/th.5a232fe8db.png">http://freeimagehosting.net/uploads/…</a>!
<a href="">www.freeimagehosting.net/image.php?5a232fe8db.png</a>" rel="nofollow"&gt;Full Size</p>

<p>The problem is the addition of child element in the javascript function, as shown in the below diff that fixed the problem.</p>

<pre class="highlight"><code>
// Diff output
122c122
&lt;         $js = sprintf('%s("#%s &gt; ul").tabs(%s);',
---
&gt;         $js = sprintf('%s("#%s").tabs(%s);',
</code></pre>

<p>Screenshot after diff:
!<a href="http://www.freeimagehosting.net/uploads/th.aaa4bd0ecb.png">http://freeimagehosting.net/uploads/…</a>!
<a href="">www.freeimagehosting.net/image.php?aaa4bd0ecb.png</a>" rel="nofollow"&gt;Full Size</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-02-01T02:34:52.000+0000</p> 
        <div class="body">
            <p>Changed assignment to me.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-02-01T03:47:38.000+0000</p> 
        <div class="body">
            <p>Hello Brian,</p>

<p>can you tell me the jQuery UI Version that you are using?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-02-03T10:39:08.000+0000</p> 
        <div class="body">
            <p>Schedulded for the next release (Either 1.8 or 1.7.5)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laura Dean (ldean) on 2009-03-02T18:32:56.000+0000</p> 
        <div class="body">
            <p>Hi, I am trying to get this component working for subforms and mine does not display with tabs.</p>

<p>It does work with the following diff (and without the diff noted previously):</p>

<p>93c93
&lt;            $list = '</p>

<p>&lt;</p>

<h2>ul class="ui-tabs-nav"&gt;'.PHP_EOL;</h2>

<blockquote>
<pre><code>       $list = '
</code></pre>
</blockquote>

<div><ul><li>'.PHP_EOL;

133c133
&lt;              . '</li></ul></div>

<h2>'.PHP_EOL;</h2>

<blockquote>
<pre><code>         . '&lt;/div&gt;&lt;/div&gt;'.PHP_EOL;
</code></pre>
</blockquote>

<p>I am using the following JQuery includes:
    </p>

<p>The screenshots look like they were taken from the example at <a href="http://www.zendframework.com/manual/en/zendx.jquery.form.html">http://zendframework.com/manual/en/…</a></p>

<p>I was trying to get that example working before implementing with my own forms and am wondering if the rest of the example is available somewhere (headers, javascript, css stylesheet).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-03-02T23:42:55.000+0000</p> 
        <div class="body">
            <p>@Laura: which UI version and which stylesheet are you using?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laura Dean (ldean) on 2009-03-09T10:28:08.000+0000</p> 
        <div class="body">
            <p>Here are the contents of my jquerytest.phtml (jquerytestAction in the controller is taken directly from <a href="http://www.zendframework.com/manual/en/zendx.jquery.form.html">http://zendframework.com/manual/en/…</a>):</p>

<hr /><p></p>jQuery UI Tabs - Default functionality<p></p>

<p></p>

<h2>&lt;?=$this-&gt;form ?&gt;</h2>

<p>I did also try adding this line with same functional results (different styling):
</p>

<p>ZendX is from the Zend 1.7.4 release.</p>

<p>(Sorry for the slow replay, was expecting the issue tracker to email me... will have to look for that setting...)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Laura Dean (ldean) on 2009-03-10T07:41:50.000+0000</p> 
        <div class="body">
            <p>Okay, I get it... should have been $("#tabContainer").tabs() in the javascript...</p>

<p>I still think it would be useful to add this to the example, along with the javascript and stylesheet includes.</p>

        </div>
    </div>
    </div>

