<h2>ZF-5346: AMF3 Messages with Object as first param fails with badVersion</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-23T12:30:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-16T12:16:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.8 (30/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Joshua McDonald (roosterjm2k2)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wade Arnold (wadearnold)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>AMF3 calls will fail if the first or only parameter passed to the call is an object.  These are calls from Flash, Actionscript 3 netConnection</p>

<p>The fix to the problem seems to be to remove the check on line 184 of Request.php.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wade Arnold (wadearnold) on 2008-12-23T13:10:36.000+0000</p> 
        <div class="body">
            <p>Can you supply the simplest code snippet for PHP and AS3 to make this happen. I have an object test that works fine in AS3 from Flex and can not re-create the issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wade Arnold (wadearnold) on 2009-03-16T12:16:31.000+0000</p> 
        <div class="body">
            <p>Changes have been committed to the trunk that resolve the issue. Test case was created and committed.</p>

        </div>
    </div>
    </div>

