<h2>ZF-5162: Trivial grammar mistake</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2008-12-04T12:13:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T15:30:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>10.3.3. Environmental Accessor Methods</p>

<p>Scroll down to paragraph that starts with
'registerPlugin(Zend_Controller_Plugin_Abstract $plugin, $stackIndex = null)  allows you to'</p>

<p>Remove the 'a' in 'register a plugin objects'</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-04T19:53:32.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r13033 . (Zend_Controller-FrontController.xml)</p>

        </div>
    </div>
    </div>

