<h2>ZF-5297: READ FIRST: Incorrect year returned by Zend_Date.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-17T05:20:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-03T14:34:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Postponed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5296">ZF-5296</a></li>
            <li><a href="/issues/browse/ZF-3724">ZF-3724</a></li>
            <li><a href="/issues/browse/ZF-5281">ZF-5281</a></li>
            <li><a href="/issues/browse/ZF-7474">ZF-7474</a></li>
            <li><a href="/issues/browse/ZF-5120">ZF-5120</a></li>
            <li><a href="/issues/browse/ZF-5719">ZF-5719</a></li>
            <li><a href="/issues/browse/ZF-8687">ZF-8687</a></li>
            <li><a href="/issues/browse/ZF-4820">ZF-4820</a></li>
            <li><a href="/issues/browse/ZF-5723">ZF-5723</a></li>
            <li><a href="/issues/browse/ZF-10776">ZF-10776</a></li>
            <li><a href="/issues/browse/ZF-4656">ZF-4656</a></li>
            <li><a href="/issues/browse/ZF-8703">ZF-8703</a></li>
            <li><a href="/issues/browse/ZF-5371">ZF-5371</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Dear Sir/Madam,</p>

<p>Recently a lot of ZF users are filing a bug that Zend_Date returns the wrong year, 2009 instead of 2008. This is however expected behaviour, and NOT A BUG!</p>

<h1>From the FAQ:</h1>

<p>When using own formats in your code you could come to a situation where you get for example 29.12.2009, but you expected to get 29.12.2008.</p>

<p>There is one year difference: 2009 instead of 2008. You should use the lower cased year constant. See this example:
$date-&gt;toString('dd.MM.yyyy');
instead of</p>

<h1>$date-&gt;toString('dd.MM.YYYY');</h1>

<h1>From the manual</h1>

<p>Note that the default ISO format differs from PHP's format which can be irritating if you have not used in previous. Especially the format specifiers for Year and Minute are often not used in the intended way.</p>

<p>For year there are two specifiers available which are often mistaken. The Y specifier for the ISO year and the y specifier for the real year. The difference is small but significant. Y calculates the ISO year, which is often used for calendar formats. See for example the 31. December 2007. The real year is 2007, but it is the first day of the first week in the week 1 of the year 2008. So, if you are using 'dd.MM.yyyy' you will get '31.December.2007' but if you use 'dd.MM.YYYY' you will get '31.December.2008'. As you see this is no bug but a expected behaviour depending on the used specifiers.</p>

<h1>For minute the difference is not so big. ISO uses the specifier m for the minute, unlike PHP which uses i. So if you are getting no minute in your format check if you have used the right specifier.</h1>

<p>Please leave this issue open at least until January 2009.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ivo Jansch (ijansch) on 2010-01-04T07:17:05.000+0000</p> 
        <div class="body">
            <p>I think one of the reasons this confuses so many people is a misinterpretation of the ISO spec. The manual claims 'ISO uses weeknumberbasedyear, so 1-1-2010 is actually 2009 according to ISO, so it's intended behaviour'.</p>

<p>ISO would cease to exist if it could rightfully claim that 1-1-2010 is actually in 2009.</p>

<p>ISO has 2 ways of representing the year number:</p>

<p>1-1-2009 according to ISO 8601 Calendrial year: 2009
1-1-2009 according to ISO 8601 Weeknumberbased year: 2008</p>

<p>The first one is the most commonly used and the one to be used in full date representations. Zend_Date wrongfully ignores the first one and claims the second one is the only 'iso correct date'. This is wrong and causes confusion to people who use the common YYYY representation in their formatting. In my opinion, it IS a bug, and YYYY should use the ISO 8601 calendrial year representation. This means it will correctly represent 1-1-9 as '2009', and still be ISO compliant. The less common weeknumber based representation could then use a less obvious formatting string.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-04T08:42:51.000+0000</p> 
        <div class="body">
            <p>Clearly, there is (a) confusion by many, many users of the component, and (b) confusion as to implementation of the specification. Zend_Date usage should be predictable, and if it is not, should be fixed.</p>

<p>PHP's DateTime is how people expect Zend_Date to act. If it does not, it should be corrected.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-01-04T08:47:18.000+0000</p> 
        <div class="body">
            <p>It should. But, if we were to change this (no matter in a major, minor or mini release) it would break a lot of sites, without people knowing. With other BC breaks you get an exception, notice, etc. However, that would be not really possible with any change we're discussing here.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ivo Jansch (ijansch) on 2010-01-04T08:53:31.000+0000</p> 
        <div class="body">
            <p>Dolf: I think that's ok, I doubt many people are actually using the weeknumber based year; there are hardly any use case scenario's that need this particular weird year.</p>

<p>Most of the people currently using it will not notice a change, in fact it might fix a problem they didn't yet know they had.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-08-01T01:22:32.000+0000</p> 
        <div class="body">
            <p>Issue postponed for 2.0</p>

        </div>
    </div>
    </div>

