<h2>ZF-505: Need to get the current code into svn.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2006-11-08T04:53:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mat Scales (mat)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Mat Scales (mat)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Need to find out how the tools directory is going to work with respect to where classes and scripts will live and commit the code.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

