<h2>ZF-5419: Ability to change the word</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-01-07T02:21:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-17T14:15:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We should be able to influence the outcome of the word generation for the captcha, either by setting filters (example, toUpperCase) and/or by setting the char pool from which we want our words generated. The quick fix is to make Zend_Captcha_Word::_setWord() public (which delegates the word generation to the developer), but a better fix would be to enable us with above proposed solutions.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Tim Fountain (tfountain) on 2009-01-08T13:43:29.000+0000</p> 
        <div class="body">
            <p>As an example of why being able to set the char pool would be useful: It can be quite hard to differentiate the characters 1 and l; and a, o and 0 in some fonts (especially with all the captcha image effects applied), so it'd be good to be able to drop these chars out.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-02-27T10:36:57.000+0000</p> 
        <div class="body">
            <p>Maybe the easiest way would be to extends this class (Zend_Captcha_Word) and override _generateWord?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-06-17T14:15:07.000+0000</p> 
        <div class="body">
            <p>I think extending the class is the right way to go here. Just override _generateWord with any algorithm you like.</p>

        </div>
    </div>
    </div>

