<h2>ZF-5796: Wrong date format, wrong interpreted by twitter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-16T05:23:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-20T07:04:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.6 (02/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mario Volke (webholics)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The current $_dateFormat (line 58 of Zend/Service/Twitter.php) value isn't correctly interprated by twitter.
It often leads to empty responses when there has to be new tweeds.</p>

<p>I would therefore strongly suggest to use the same format as twitter uses itself in the responses:</p>

<p>Mon Feb 16 13:44:39 +0000 2009</p>

<p>$_dateFormat = 'D M d H:i:s O Y';</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-02-16T06:12:47.000+0000</p> 
        <div class="body">
            <p>The problem with your format is it's not a valid HTTP-formatted date as the since header is being sent across in the header <em>If-Modified-Since</em></p>

<p>I suggest changing it to: <em>D, d M Y H:i:s T</em> so it's a valid HTTP-formatted date.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-02-20T07:04:30.000+0000</p> 
        <div class="body">
            <p>This was checked into svn with r14124 and into the release branch with r14125</p>

        </div>
    </div>
    </div>

