<h2>ZF-5831: Zend_Amf_Server getDirectory returns the wrong variable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-18T14:44:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-25T14:52:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Wade Arnold (wadearnold)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5388">ZF-5388</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This issue appears to have been resolved in trunk, revision 13480, but to my surprise this was not fixed in the 1.7.5 release.</p>

<p>public function getDirectory()
{
    return $_directory;
}</p>

<p>Should return $this-&gt;_directories</p>

<p>My company has developed a basic but highly useful service browser that works with Zend_Amf we'd like to release into the wild as open source, but would like to avoid users having to hack the Server.php file to get it to work. What release can we expect this fix in?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wade Arnold (wadearnold) on 2009-03-16T13:59:10.000+0000</p> 
        <div class="body">
            <p>This has been resolved in the trunk. The change was committed with a bug fix for ZF-5388 and that is pending a merge into the next release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wade Arnold (wadearnold) on 2009-03-16T14:15:01.000+0000</p> 
        <div class="body">
            <p>The resolution for this issue where committed with the  ZF-5388 bug.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andy Mayer (ncalishome) on 2009-03-17T19:53:15.000+0000</p> 
        <div class="body">
            <p>Thanks for the reply. When you say "next release" I take it you're talking about 1.8?</p>

<p>I just download 1.7.7 and it's still not fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wade Arnold (wadearnold) on 2009-03-24T12:49:02.000+0000</p> 
        <div class="body">
            <p>The change has been updated into the 1.7 release branch and will be a part of the next mini release. Please let me know more about your service browser! fire me an email!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andy Mayer (ncalishome) on 2009-03-25T14:51:44.000+0000</p> 
        <div class="body">
            <p>Thanks for the update Wade. I sent you an email this morning with PHP code and a link to an AIR app, so please be on the lookout :)</p>

        </div>
    </div>
    </div>

