<h2>ZF-5311: A set of Zend_Gdata_YouTube unit tests failures</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-12-18T07:49:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
1) testSampleEntryShouldHaveNoExtensionElementsV2(Zend_Gdata_YouTube_PlaylistListFeedTest)
Failed asserting that </p><p></p><p></p><p></p><p></p><p></p>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-12-18T08:38:04.000+0000</p> 
        <div class="body">
            <p>Reassigning to Jochen Hartmann.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-18T14:50:02.000+0000</p> 
        <div class="body">
            <p>Fixed in r13359.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-18T14:54:44.000+0000</p> 
        <div class="body">
            <p>Merged into 1.7 in r13360.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-18T15:25:38.000+0000</p> 
        <div class="body">
            <p>Added another fix in r13361</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-18T15:35:51.000+0000</p> 
        <div class="body">
            <p>Merged to 1-7 in r13362.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-19T10:46:43.000+0000</p> 
        <div class="body">
            <p>Problem still exists :(</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-19T16:16:36.000+0000</p> 
        <div class="body">
            <p>Resolved with a few merges that were missed. Merged in r13379, r13380, r13382.</p>

        </div>
    </div>
    </div>

