<h2>ZF-5279: Zend_Db_Table_Abstract::select() should accept an array of fields to be fetched from DB</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-12-16T03:53:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ionut Stan (igstan)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'd like to propose the addition of an optional parameter to Zend_Db_Table_Abstract::select().
Its default value should be Zend_Db_Select::SQL_WILDCARD. Alternatively an array should be
used, whose values correspond to fields in the current table. A quick, untested example:
\
\</p>

<pre class="highlight"><code>
/**
 * Returns an instance of a Zend_Db_Table_Select object.
 *
 * @param  mixed $fields Fields to select from the table. Defaults to all.
 * @return Zend_Db_Table_Select
 */
public function select($fields = Zend_Db_Select::SQL_WILDCARD)
{
    require_once 'Zend/Db/Table/Select.php';
    $select = new Zend_Db_Table_Select($this);
    $select-&gt;from($this-&gt;_name, $fields);
    return $select;
}
</code></pre>

<p>Having this, one can write:</p>

<pre class="highlight"><code>
public function getByDestination($continentId, $countryId, $cityId)
{
    return $this-&gt;fetchAll(
        $this-&gt;select(array('name'))
             -&gt;where('continent_id = ?', $continentId)
             -&gt;where('country_id = ?',   $countryId)
             -&gt;where('city_id = ?',      $cityId)
             -&gt;order('name ASC')
             -&gt;limit(10)
    );
} 
</code></pre>

<p>I don't know whether this should be also applied to Zend_Db_Adapter_Abstract::select()
and Zend_Db_Select::__construct(). In this case the passed array should probably be
a multidimensional array in which keys are table names and values are arrays of fields
to be fetched. Actually, Zend_Db_Select objects can be supported as values too.</p>

<p>If there's interest in these additions I'd gladly conduct further investigations inside the
code base.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:47.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

