<h2>ZF-5313: testList(Zend_Translate_Adapter_ArrayTest) unit tests failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-12-18T08:00:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
11) testList(Zend_Translate_Adapter_ArrayTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [de] =&gt; de
 )
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-18T08:07:35.000+0000</p> 
        <div class="body">
            <p>Additional failures which seems to be coused by the same problem:</p>

<p>{panel}
18) testList(Zend_Translate_Adapter_TbxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [fr] =&gt; fr
 )</p>

<p>...</p>

<p>20) testList(Zend_Translate_Adapter_TmxTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [fr] =&gt; fr
 )</p>

<p>...</p>

<p>22) testList(Zend_Translate_Adapter_XliffTest)
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ -1,5 +1,4 @@
 Array
 (
     [en] =&gt; en
-    [fr] =&gt; fr
 )
{panel}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-12-20T03:27:16.000+0000</p> 
        <div class="body">
            <p>Should be fixed with r13389</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2008-12-21T01:50:29.000+0000</p> 
        <div class="body">
            <p>Fixed and merged into release-1.7 branch with r13404.</p>

        </div>
    </div>
    </div>

