<h2>ZF-5307: testSamplePropertiesAreCorrectV2(Zend_Gdata_YouTube_PlaylistListEntryTest) and testConvertPlaylistListEntryToAndFromStringV2(Zend_Gdata_YouTube_PlaylistListEntryTest) unit tests errors</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-12-18T07:41:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
3) testSamplePropertiesAreCorrectV2(Zend_Gdata_YouTube_PlaylistListEntryTest)
Zend_Gdata_App_InvalidArgumentException: Property getMajorProtocolVersion does not exist
/home/cawa/ZendFramework/svn/framework/branches/release-1.7/library/Zend/Gdata/App/Base.php:448
/home/cawa/ZendFramework/svn/framework/branches/release-1.7/library/Zend/Gdata/YouTube/PlaylistListEntry.php:237</p>

<p>4) testConvertPlaylistListEntryToAndFromStringV2(Zend_Gdata_YouTube_PlaylistListEntryTest)
Zend_Gdata_App_InvalidArgumentException: Property getMajorProtocolVersion does not exist
/home/cawa/ZendFramework/svn/framework/branches/release-1.7/library/Zend/Gdata/App/Base.php:448
/home/cawa/ZendFramework/svn/framework/branches/release-1.7/library/Zend/Gdata/YouTube/PlaylistListEntry.php:237
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-12-18T08:40:36.000+0000</p> 
        <div class="body">
            <p>Assigning to [~jhartmann].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-18T15:37:25.000+0000</p> 
        <div class="body">
            <p>Fixed in r13359 and r13361. Merged to 1-7 in r13360 and r13362 respectively.</p>

        </div>
    </div>
    </div>

