<h2>ZF-5940: wiki Subversion+Standards page link to incubator is wrong</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-04T09:22:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-30T07:42:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                clive darr (osde8info)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Daniel Lo (danlo)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://zendframework.com/wiki/display/ZFDEV/Subversion+Standards">http://zendframework.com/wiki/display/…</a></p>

<p>points to</p>

<p><a href="http://framework.zend.com/developer/browser/trunk/incubator">http://framework.zend.com/developer/browser/…</a></p>

<p>instead of</p>

<p><a href="http://framework.zend.com/svn/framework/standard/incubator/">http://framework.zend.com/svn/framework/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by clive darr (osde8info) on 2009-03-04T09:24:29.000+0000</p> 
        <div class="body">
            <p>and gives the user the error</p>

<p>An error occurred with this request: Action "browser" does not exist and was not trapped in __call().</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-07-30T07:42:35.000+0000</p> 
        <div class="body">
            <p>This issue seems to be solved by Daniel ,at 5th Mar 2009.</p>

        </div>
    </div>
    </div>

