<h2>ZF-5386: Zend_Captcha_Image Empty Image Directory Cleanup Command Bug</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-30T17:40:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-06T10:12:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Brad Gushurst (bradgman)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
            <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Info:</p>

<p>Apache 2
PHP 5.2.6
OS: Windows XP
XAMPP</p>

<p>Overview:</p>

<p>I setup a Zend_Form_Element_Captcha during which time I filled out all properties except the imgDir and imgUrl.</p>

<p>Problem:</p>

<p>When testing during this setup without the directories specified ... obviously it should fail ... but the cleanup command ran during one of the calls ... PHP attempted to clear out the hard drives root directory.</p>

<p>It looks like if an empty directory is specified it attempts to delete the root.</p>

<p>Output:</p>

<p>Warning: unlink(\IO.SYS) [function.unlink]: Permission denied in C:\zf\standard\trunk\library\Zend\Captcha\Image.php on line 572
Warning: unlink(\MSDOS.SYS) [function.unlink]: Permission denied in C:\zf\standard\trunk\library\Zend\Captcha\Image.php on line 572
Warning: unlink(\NTDETECT.COM) [function.unlink]: Permission denied in C:\zf\standard\trunk\library\Zend\Captcha\Image.php on line 572
Warning: unlink(\ntldr) [function.unlink]: Permission denied in C:\zf\standard\trunk\library\Zend\Captcha\Image.php on line 572
Warning: unlink(\pagefile.sys) [function.unlink]: Permission denied in C:\zf\standard\trunk\library\Zend\Captcha\Image.php on line 572</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-02-06T10:10:26.000+0000</p> 
        <div class="body">
            <p>In general, imgDir  has defaults, so if you just don't set it it should use this default. But I'll add safeguard to not do cleaning in imgdir is empty or / or .</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-02-06T10:12:19.000+0000</p> 
        <div class="body">
            <p>added check for empty dir</p>

        </div>
    </div>
    </div>

