<h2>ZF-5354: Atom feed item links are not displayed when rel attribute is missing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-27T04:48:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-17T11:41:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Atom feed item links are not displayed/included in the array when a rel attribute is missing (example: try to consume this arom feed: <a href="http://www.heise-online.co.uk/news/atom.xml">http://www.heise-online.co.uk/news/atom.xml</a>)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-09-17T11:41:12.000+0000</p> 
        <div class="body">
            <p>Added support for querying Atom entries for "alternate" links even if the relation is not present on the original link element. This is a required behaviour according to the Atom 1.0 RFC.</p>

        </div>
    </div>
    </div>

