<h2>ZF-5170: Zend_Db_Adapter_Pdo_Mssql memory leak?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-05T16:33:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-17T17:34:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Kliewe (mkliewe)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11672/memleak.zip">memleak.zip</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>I have a problem with Zend_Db when using a mssql-database.
I'm working several month with Zend Framework now, and was writing a kind of "windows service" in php (with php cli as service or scheduled task). This script runs very long (many days/weeks) in a loop. But I experienced memory problems with Zend_Db.</p>

<p>With each SQL-Query the Zend_Db object seems to grow a bit, depending on the select-result-size!!! Even with only one result row, the script-memory-usage grows. If I do INSERTs or UPDATES, all works fine, but when doing SELECTs, the script-memory-usage grows and grows. And my script runs many days and has 100.000 selects a day, which results in &gt;100MB memory usage growth per day. So I have to restart the script every day ;-(</p>

<p>Zend_Db seems to cache that results or so, I don't know. Zend_Db_Profiler is disabled of cause.</p>

<p>I did a few tests, tested PEAR-MDB2 and also Zend_Db Pdo_Sqlite-Adapter . With these two methods I didn't experience a memory growth.</p>

<p>I will attach my test files, so you can check it on your own. You will need PEAR MDB2 installed to run it (or you disable that part).
I will also attach my results (results.txt), where you can see, that sqlite and mdb2 don't grow, but mssql does!</p>

<p>I cannot use Zend_Db with that bug. Please fix it soon!</p>

<p>Michael</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michael Kliewe (mkliewe) on 2008-12-05T16:34:44.000+0000</p> 
        <div class="body">
            <p>zip archive with my test script and results.txt, where you can see the problem with mssql-adapter</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Petr Gottvald (gotys) on 2009-09-08T00:51:17.000+0000</p> 
        <div class="body">
            <p>I ran into the same exact issue yesterday. It doesn't seem Zend_Db was written with memory leaks in mind. Running a PHP Daemon using Zend_Db is impossible right now. I am examining the source codes of Zend_Framework right now and will report if I find something.</p>

<p>Someone please fix this!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Petr Gottvald (gotys) on 2009-09-08T02:05:25.000+0000</p> 
        <div class="body">
            <p>Well, I think I solved my problem . It was much easier then I thought. My memory kept leaking with when I had the Query Profiler turned on. I turned it off, now memory stopped leaking. Let me know if this solved your issue as well.</p>

<p>Petr</p>

        </div>
    </div>
    </div>

