<h2>ZF-5532: Zend_Cache_Frontend_Page - possible DOS risk...strip get variables from $_SERVER['REQUEST_URI'] when making ID</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-12T12:59:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-21T12:25:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Fabien MARTY (fab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Say that I set the frontend options of Zend_Cache_Frontend_Page with 'make_id_with_get_variables' to false ...</p>

<p>Intuitively, I would assume that the same cache ID/file would be created for any of the following GET requests:
/page.php
/page.php?var=1
/page.php?var=77&amp;var2=22</p>

<p>And I assumed that only ONE cache file would be created for page.php, regardless of the GET variables tagged onto the end of the request.  However for each of the three examples above, I get 3 separate cache files stored.</p>

<p>The reason is because the REQUEST_URI used as the cache ID - which includes the GET variables anyway. So, setting 'make_id_with_get_variables' to false is moot, as each of the three URIs above are already unique BECAUSE of their GET variables.</p>

<p>The ID name should be based off of the requested URI with the QUERY_STRING stripped off.<br />
With that configuration:
1) make_id_with_get_variables = false would only save ONE cache file for the above URIs
1) make_id_with_get_variables = true would save ONE cache file for each unique query string request</p>

<p>This issue could also bring about risk of DOS attack.
With 'make_id_with_get_variables' to false, an attacker could constantly query urls like:
/page.php?var=randomString
Which could fill up the file space, even though the GET variables should have no effect on the name of the cache file. (Yes this could happen in other types of cache setups as well, but in this specific case it should not be happening).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by John Brown (johniskew) on 2009-03-18T06:53:09.000+0000</p> 
        <div class="body">
            <p>Added in DOS possibility, and clarified some of the explanation.   Originally I put "improvement" by mistake.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2009-03-29T00:56:35.000+0000</p> 
        <div class="body">
            <p>I just commited a fix into SVN trunk, can you try it ?</p>

<p>If it's ok for you, I will backport on the 1.7 branch</p>

<p>thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by John Brown (johniskew) on 2009-04-21T12:08:27.000+0000</p> 
        <div class="body">
            <p>Sorry for the delay...I think its fixed!</p>

        </div>
    </div>
    </div>

