<h2>ZF-5277: fix_dst doesn`t work correctly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-16T00:30:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the following example, the fix_dst option doesn`t work correctly.</p>

<pre class="highlight"><code>
ini_set('date.timezone', 'UTC');

Zend_Date::setOptions(array('fix_dst' =&gt; true));

$date = new Zend_Date(mktime(22, 0, 0, 10, 25, 2008));
$date-&gt;setTimezone('Europe/Berlin');
$date-&gt;add(1, Zend_Date::DAY);
$date-&gt;sub(1, Zend_Date::SECOND);
echo $date-&gt;get(Zend_Date::DATE_SHORT) . ' ' . $date-&gt;get(Zend_Date::TIME_MEDIUM);
</code></pre>

<p>Current result:
26.10.08 22:59:59</p>

<p>Expected result:
26.10.08 23:59:59</p>

<p>This bugreport relates to a post in the german ZF-Forum.
<a href="http://www.zfforum.de/showthread.php?t=2853">http://www.zfforum.de/showthread.php?t=2853</a></p>

<p>When I set the default timezone to Europe\Berlin and not to UTC it works, but this is not the required approach.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-12-16T01:09:25.000+0000</p> 
        <div class="body">
            <p>Debugging your example I get:</p>

<pre class="highlight"><code>
$date = new Zend_Date(mktime(22, 0, 0, 10, 25, 2008));
</code></pre>

<p>The date object contains</p>

<pre class="highlight"><code>
2008-10-25T22:00:00+00:00
</code></pre>

<p>which is correct... now you set the timezone</p>

<pre class="highlight"><code>
$date-&gt;setTimezone('Europe/Berlin');
</code></pre>

<p>and the object changes to</p>

<pre class="highlight"><code>
2008-10-26T00:00:00+02:00
</code></pre>

<p>which is correct because we are in summertime on this date so GMT+2
Now you add one day</p>

<pre class="highlight"><code>
$date-&gt;add(1, Zend_Date::DAY);
</code></pre>

<p>but there is a change from summer to wintertime... so the object changes to</p>

<pre class="highlight"><code>
2008-10-26T23:00:00+01:00
</code></pre>

<p>because this day has only 23 hours, but also the zone changes to GMT+1
Substracting one second makes no difference</p>

<pre class="highlight"><code>
$date-&gt;sub(1, Zend_Date::SECOND);
</code></pre>

<p>as the zone does not change on 22-23h.</p>

<pre class="highlight"><code>
2008-10-26T22:59:59+01:00
</code></pre>

<p>I see no problem at all.</p>

        </div>
    </div>
    </div>

