<h2>ZF-5440: Foriegn characters corrupt in body and subject of email i.e é is the €. î etc</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-01-09T10:57:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-26T09:45:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>$mail = new Zend_Mail('utf-8');
        $mail-&gt;setBodyHtml('é is the €.'); //Alternatively using setBodyHtml for HTML messages
        $mail-&gt;setFrom('username@domain.com', 'Some Sender'); //Adds a 'from' header
        $mail-&gt;addTo('username@domain.com', 'Some Recipient');
        $mail-&gt;setSubject('TestSubject');
        $mail-&gt;send();</p>

<p>no special characters are being shown in email body or subject so the euro symbol nor any foreign language characters are getting encoded properly. I played with the charset and that doesn't help a bi</p>

<p>I also tested with other words in german</p>

<pre><code>    $mail-&gt;setBodyText("Umsätze."); //Alternatively using setBodyHtml for HTML messages
</code></pre>

<p>comes out</p>

<p>Umstze  which can't be right as it simply removed the ä characters and any other german accents</p>

<p>I also upgraded to 1.7.2 and no go</p>

<p>I FOUND THE RESOLUTION TO THIS ISSUE IT IS THE ENCODING</p>

<p>$mail = new Zend_Mail('utf-8');
        $mail-&gt;setBodyHtml('é is the €.','UTF-8',Zend_Mime::ENCODING_8BIT); //Alternatively using setBodyHtml for HTML messages
        $mail-&gt;setFrom('username@domain.com', 'Some Sender'); //Adds a 'from' header
        $mail-&gt;addTo('username@domain.com', 'Some Recipient');
        $mail-&gt;setSubject('TestSubject','UTF-8',Zend_Mime::ENCODING_8BIT);
        $mail-&gt;send();</p>

<p>changing the encoding from the default base64 to Zend_Mime::ENCODING_8BIT did the trick!</p>

<p>this same issue with drawText for Zend_Pdf is resolved with drawtext,$text,$h,$v,'UTF-8');</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-10T05:25:10.000+0000</p> 
        <div class="body">
            <p>I try to reproduce it in ver. 1.7.2 .
I get following string as the subject.
It is equal to my expect.
=C3=A9 is the =E2=82=AC.</p>

<p>I think the 2 characters are special character in many language, maybe except for central europe.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-13T06:19:57.000+0000</p> 
        <div class="body">
            <p>It may need to research .</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-01-14T21:43:05.000+0000</p> 
        <div class="body">
            <p>Hi, Chris.</p>

<p>I think you should try ISO-8859-1, ISO-8859-2, or other ISO-8859-x instead of UTF-8.</p>

<p>And header fields permit only Base64 or QuotedPrintable scheme , not 7bit or 8bit.
So, please try the QuotedPrintable scheme.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by chris manjoine (manjoine) on 2009-01-19T07:57:44.000+0000</p> 
        <div class="body">
            <p>for ($x=1; $x &lt;=16; $x++){
            $mail = new Zend_Mail('ISO-8859-'.$x);
            $mail-&gt;setBodyHtml('é is the €. #'.$x); //Alternatively using setBodyHtml for HTML messages
            $mail-&gt;setFrom('myemail', 'Some Sender'); //Adds a 'from' header
            $mail-&gt;addTo('myemail', 'Some Recipient');
            $mail-&gt;setSubject('é is the €. #'.$x);
            $mail-&gt;send();
        }</p>

<p>i ran this with all SO types and nothing non of them worked even close everyone dropped the é and replaced the € with Û or something else.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by chris manjoine (manjoine) on 2009-01-19T08:15:29.000+0000</p> 
        <div class="body">
            <p>for ($x=1; $x &lt;=16; $x++){
            $mail = new Zend_Mail('ISO-8859-'.$x);
            $mail-&gt;setBodyHtml('Vielen Dank für Ihre Buchung €. #'.$x); //Alternatively using setBodyHtml for HTML messages
            $mail-&gt;setFrom('myemail@doma.com', 'Some Sender'); //Adds a 'from' header
            $mail-&gt;addTo('myemail@doma.com', 'Some Recipient');
            $mail-&gt;setSubject('Vielen Dank für Ihre Buchung €. #'.$x);
            $mail-&gt;send();
        }</p>

<p>this might ref 1688 a bit too but stilll not go I can't get foreign chars to go in the subject using Zend_Mail setSubject in Version 1.7.2</p>

        </div>
    </div>
    </div>

