<h2>ZF-5578: Zend_Config support in Zend_Uri</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-01-18T09:39:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-17T13:49:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Uri</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12207/ZF-5578-2.patch">ZF-5578-2.patch</a></li>
            <li><a href="/issues/secure/attachment/12205/ZF-5578.patch">ZF-5578.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A grep on the root of the Zend directory shows that Zend_Uri is among a small few components that do not currently support receiving a Zend_Config instance via their setConfig methods. This capability should be as simple as adding a check similar to the following and updating docblocks accordingly.</p>

<pre class="highlight"><code>
if ($config instanceof Zend_Config) {
    $config = $config-&gt;toArray();
} elseif (!is_array($config) {
    // ...
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2009-09-17T08:04:43.000+0000</p> 
        <div class="body">
            <p>Attached patch to allow using Zend_Config. Also includes three new tests.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2009-09-17T10:30:12.000+0000</p> 
        <div class="body">
            <p>Added missing require_once for Zend_Config to patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2009-09-17T13:49:21.000+0000</p> 
        <div class="body">
            <p>Fixed in r18194.</p>

        </div>
    </div>
    </div>

