<h2>ZF-597: Status codes for Zend_Controller_Response</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-11-25T14:56:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently I don't see a way to change the HTTP status code using a response object of Zend_Controller_Response_Abstract. (Btw. why is the HTTP specific headers handling in ...Abstract. I expect it in ...Http)</p>

<p>Mayby we can abuse a "Status" header line. This could look like</p>

<pre class="highlight"><code>
public function __toString()
{
  if (!headers_sent()) {
    foreach ($this-&gt;_headers as $header) {
      if (strtolower($header['name']) == 'status')
        header($header['name'] . ': ' . $header['value'], null, (int) $header['value']);
      else
        header($header['name'] . ': ' . $header['value']);
    }
  }
  //...
</code></pre>

<p>Use case:
```</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-28T17:46:17.000+0000</p> 
        <div class="body">
            <p>Assigning to Matthew, scheduling for possible fix in the 0.6.0 release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-28T22:11:41.000+0000</p> 
        <div class="body">
            <p>HTTP headers are in the abstract as we realized that most apps will be written for the web, but may be re-tooled later for other environments; by having the header() handling in the abstract, we ensure interoperability between both web and non-web environments (non-web environments may choose to simply ignore them or implement them as empty methods).</p>

<p>I like the idea of using the Status keyword, and will implement that shortly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-28T22:15:29.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 1917.</p>

        </div>
    </div>
    </div>

