<h2>ZF-5088: Translation Proposal</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-11-28T03:00:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-12T14:24:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alberto Maturano (maturano)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5100">ZF-5100</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11663/Zend_Form-Introduction.xml">Zend_Form-Introduction.xml</a></li>
            <li><a href="/issues/secure/attachment/11662/Zend_Form-Introduction.xml.diff">Zend_Form-Introduction.xml.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Improve translation. It may seem different from the original, but the current text really don't have much sense. In this way suggested is understood much better in Spanish, which is the important thing.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alberto Maturano (maturano) on 2008-11-28T03:04:47.000+0000</p> 
        <div class="body">
            <p>I followed the instructions on Wiki: <a href="http://framework.zend.com/wiki/display/ZFDEV/Submitting+a+Bug+Fix?showComments=true&amp;showCommentArea=true#addcomment">http://framework.zend.com/wiki/display/…</a></p>

<p>but I don't have clear what file have to upload. So .... Please say me for futures issues.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-03T06:12:53.000+0000</p> 
        <div class="body">
            <p>Hi, Alberto.</p>

<p>You can login SVN repository?
There is Zend_Form-Introduction.xml  in 2 places for version 1.7.x</p>

<p>1)
 <a href="http://framework.zend.com/svn/framework/standard/trunk/documentation/manual/es/module_specs/Zend_Form-Introduction.xml">http://framework.zend.com/svn/framework/…</a> .</p>

<p>2)
 <a href="http://framework.zend.com/svn/framework/standard/branches/release-1.7/documentation/manual/es/module_specs/Zend_Form-Introduction.xml">http://framework.zend.com/svn/framework/…</a> .</p>

<p>I hope it will help You.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alberto Maturano (maturano) on 2008-12-03T08:18:10.000+0000</p> 
        <div class="body">
            <p>Hi Satoru.</p>

<p>I don't have acces to the SVN.</p>

<p>I have the translation from trunk, is the more recent. This is wrong?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-04T02:53:41.000+0000</p> 
        <div class="body">
            <p>Hi, Alberto.</p>

<p>It is correct. You can translate from English version in trunk.
<a href="http://framework.zend.com/svn/framework/standard/trunk/documentation/manual/en/module_specs">http://framework.zend.com/svn/framework/…</a></p>

<p>The English version in trunk is master document.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T15:45:52.000+0000</p> 
        <div class="body">
            <p>Alberto, did you get SVN access from Matthew?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alberto Maturano (maturano) on 2008-12-04T15:56:05.000+0000</p> 
        <div class="body">
            <p>Hi Will.
No, I haven't.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alberto Maturano (maturano) on 2008-12-08T23:01:18.000+0000</p> 
        <div class="body">
            <p>No more applicable. Resolved in revision 13068</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2008-12-11T17:57:02.000+0000</p> 
        <div class="body">
            <p>Hi, Alberto.</p>

<p>Sorry if you have already known in following.</p>

<p>If you want to release new document from 1.7.2, you should also commit to branches/release-1.7/documentation/manual/es/module-specs .</p>

<p>But If you want to release from 1.8 (or bigger),  you may only commit to trunk/documentation/manual/es/module-specs .</p>

<p>Have a good days!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alberto Maturano (maturano) on 2008-12-12T14:24:25.000+0000</p> 
        <div class="body">
            <p>I didn't know. Thanks for the information Satoru.</p>

        </div>
    </div>
    </div>

