<h2>ZF-5979: Zend_Auth_Adapter_DbTable breaks on 1.7.6</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-09T16:02:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-09T18:47:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Aaron Bach (bachya)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Auth_Adapter_DbTable appears to break with 1.7.6.</p>

<p>Example code:</p>

<pre class="literal"> 
// Grab information for database.
$configuration = new Zend_Config_Ini(
    APPLICATION_PATH . '/config/app.ini', 
    APPLICATION_ENVIRONMENT
);
        
// Set up authentication stuff (credentials to
// use and how they should be related to DB).
$this-&gt;_auth = new Zend_Auth_Adapter_DbTable(
    Zend_Db::factory($configuration-&gt;database),
    'user',
    'username',
    'password',
    "MD5( CONCAT ( MD5( ? ) , MD5( salt ) ) )"
);
</pre>

<p>...later on...</p>

<pre class="literal"> 
$this-&gt;_auth-&gt;setIdentity($_POST['username'])
     -&gt;setCredential($_POST['password']);

$result = $this-&gt;_auth-&gt;authenticate();
</pre>

<p>This worked as expected in version 1.7.5, but after upgrade to 1.7.6, the following error message is received: "The supplied parameters to Zend_Auth_Adapter_DbTable failed to produce a valid sql statement, please check table and column names for validity."</p>

<p><em>Update:</em> This error does not occur on my Windows box, but does occur on my OS X box.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Aaron Bach (bachya) on 2009-03-09T18:13:01.000+0000</p> 
        <div class="body">
            <p>Never mind.  This has been resolved.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-03-09T18:47:08.000+0000</p> 
        <div class="body">
            <p>Closing per request from reporter.</p>

        </div>
    </div>
    </div>

