<h2>ZF-5854: Doesn't work with domains without two dots, such as dev.local</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-22T06:10:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                removed user (sandstrom)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Cookie</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Http_Cookie doesn't work with local domains without two dots, such as dev.local. With the native php cookie method one can use false instead of the domain, e.g. setcookie('key', 'val', time() + 7200, '/', false); to make it work.</p>

<p>This doesn't work with the Zend component. See this thread for a more elaborate discussion on the problem.</p>

<p><a href="http://www.zfforums.com/zend-framework-components-13/web-web-services-22/zend_http_cookie-localhost-282.html">http://zfforums.com/zend-framework-components-13/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2009-07-25T04:31:25.000+0000</p> 
        <div class="body">
            <p>I am not entirely sure what you are trying to do - are you trying to replace setcookie() with Zend_Http_Cookie? If so that's not what it's for. 
Can you provide some reproduction code so I understand what you're trying to achieve?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:08.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

