<h2>ZF-5035: Zend_Uri_Http::fromString throws InvalidArgumentException</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2008-11-23T09:39:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T08:49:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kazusuke Sasezaki (sasezaki)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Udo Telaar (udo)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Uri</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6212">ZF-6212</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend_Uri_Http::fromString, if $uri is false, throws InvalidArgumentException. But, InvalidArgumentException is not extends Zend_Exception.</p>

<pre class="highlight"><code> 
        if (is_string($uri) === false) {
            throw new InvalidArgumentException('$uri is not a string');
        }
</code></pre>

<p>should be</p>

<pre class="highlight"><code> 
        if (is_string($uri) === false) {
            require_once 'Zend/Uri/Exception.php';
            throw new Zend_Uri_Exception('$uri is not a string');
        }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-04-04T20:18:38.000+0000</p> 
        <div class="body">
            <p>Fixed in r14650.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-04-05T04:17:07.000+0000</p> 
        <div class="body">
            <p>copy from trunk to 1.7 branch so that it is scheculed in next mini release.</p>

        </div>
    </div>
    </div>

