<h2>ZF-5929: Zend_Dojo_View_Helper_Dojo_Container::registerDijitLoader when parseOnLoad is true</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-03T03:57:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-30T15:38:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Elvin ?iriyev (elvinsh)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6563">ZF-6563</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14695/Container.php">Container.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Dojo generates an extra dojo.parser.parse() call which breaks dijits.</p>

<p>This happens when you have enabled parseOnLoad in djConfig, and use dijit based form elements.</p>

<p>Steps:
- Enable parseOnLoad in Zend_Dojo
- Add a form with dijits</p>

<p>Result:
- The dojo view helper generates a script which runs dojo.parser.parse() in the end, which makes dojo parse the dijits in the document twice, breaking them.</p>

<p>Expected:
- If parseOnLoad is enabled, the line running dojo.parser.parse() should never be generated.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jani Hartikainen (jhartikainen) on 2010-12-13T04:23:08.000+0000</p> 
        <div class="body">
            <p>Cleaned up the description</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emanuele Deserti (lord_lele) on 2011-10-18T10:43:15.000+0000</p> 
        <div class="body">
            <p>I have resolved patching Zend/Dojo/View/Helper/Dojo/Container.php</p>

<p>In line 871 add this:</p>

<pre><code>        if ($this-&gt;getDjConfigOption('parseOnLoad') === false) {

            $js =&lt;&lt;&lt;EOJ
</code></pre>

<p>function() {
    dojo.forEach(zendDijits, function(info) {
        var n = dojo.byId(info.id);
        if (null != n) {
            dojo.attr(n, dojo.mixin({ id: info.id }, info.params));
        }
    });
}
EOJ;</p>

<pre><code>        }
</code></pre>

<p>Not elegant, but it's working...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emanuele Deserti (lord_lele) on 2011-10-18T10:46:54.000+0000</p> 
        <div class="body">
            <p>Here's the patched file.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sammie S. Taunton (diemuzi) on 2011-10-30T15:38:29.000+0000</p> 
        <div class="body">
            <p>Thank you, I thought I was doing something completely off the wall until I found this =)</p>

        </div>
    </div>
    </div>

