<h2>ZF-5344: _renderExtras doesn't check for JQuery.noConflict mode</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-23T09:04:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-03T11:01:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.3 (19/Jan/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5396">ZF-5396</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In ZendX_JQuery_View_Helper_JQuery_Container when the _renderExtras method is executed, it calls a number of actions to performed at the document.ready event.  However, this call explicitly uses the $ to grab the document element and does not check to see whether or not noConflict mode has been enabled for the jQuery lib.  This call needs to check to see which jQueryHandler should be used.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-01-06T01:30:55.000+0000</p> 
        <div class="body">
            <p>Will be included in the next release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-01-14T13:54:05.000+0000</p> 
        <div class="body">
            <p>merged back into 1.7 release branch</p>

        </div>
    </div>
    </div>

