<h2>ZF-5140: Document that Static routes require sane parameters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-12-02T11:43:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-02T11:47:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Due to fixes for ZF-3465, some users have discovered that a bug in routing allowed them to define Static routes that did not contain necessary dispatching defaults, such as the controller, action, or module. A warning should be added to the Static route documentation indicating that sane default values should be supplied.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-12-02T11:47:43.000+0000</p> 
        <div class="body">
            <p>Note add in r12988; will publish no later than 1.7.2 release.</p>

        </div>
    </div>
    </div>

