<h2>ZF-5144: Variation of Zend_Http_Client_Adapter_Socket with DNS caching</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-12-02T21:05:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Turland (elazar)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11667/SocketWithDnsCache.php">SocketWithDnsCache.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Attached is a minor variation of the Zend_Http_Client_Adapter_Socket class that extends it to add DNS caching. This is potentially useful for improving performance under the following circumstances:</p>

<ul><li>The server operating system does not support DNS caching, either natively nor via installed software, or the developer using ZF does not have the necessary privileges to augment the server to that end.</li>
<li>The ZF-based application using Zend_Http_Client targets multiple remote hosts and alternates hosts between requests more often than not or has another requirement that mandates establishing multiple connections to the same host or hosts over the course of its runtime.</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:06.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

