<h2>ZF-523: Update RewriteRouter docs in incubator to reflect current usage</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-11-09T14:33:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10160/Zend_Controller-ProvidedSubclasses.xml">Zend_Controller-ProvidedSubclasses.xml</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Please update the RewriteRouter documentation in the incubator, in the Zend_Controller-Provided_Subclasses.xml file, to reflect current usage. Examples in there show the following notation:</p>

<pre class="highlight"><code>
$router-&gt;addRoute('user', ':controller/:action);
</code></pre>

<p>which should actually be:</p>

<pre class="highlight"><code>
$router-&gt;addRoute(
    new Zend_Controller_Router_Route('user', ':controller/:action')
);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:08:10.000+0000</p> 
        <div class="body">
            <p>Changing fix version to unknown.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:24:58.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.6.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2006-11-14T02:15:20.000+0000</p> 
        <div class="body">
            <p>This one needs a bigger overhault as Router slightly changed it's function in the new MVC structure.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (maugrim) on 2006-11-15T10:50:44.000+0000</p> 
        <div class="body">
            <p>I've started editing Zend_Controller-ProvidedSubclasses.xml and will commit it shortly.</p>

<p>I added the references to Zend_Controller_Router_Route which was missing. I also altered the description of the compat route (it currently does allow additional parameters without defining specific routes). Also moved most of the RewriteBase spiel up to the section on Zend_Controller_Request_Http where it now belongs for the setBaseUrl() method proxied to Zend_Http_Request.</p>

<p>Hopefully this covers most of the out of sync issues. After committing, let me know of any improvements that could be made.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2006-11-15T11:35:48.000+0000</p> 
        <div class="body">
            <p>Attaching amended XML file (awaiting SVN access to commit, or for someone else to do so).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2006-11-16T09:21:41.000+0000</p> 
        <div class="body">
            <p>Have completed the update across two commits. Added rewrite rules for IIS and Lighttpd. Beefed up the description of Zend_Controller_Request_Http. Edited the remaining text for consistency. See r1644.</p>

        </div>
    </div>
    </div>

