<h2>ZF-5237: Allow for support of new XML elements in PlaylistListEntry in v2 of YouTube API.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2008-12-12T15:50:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Allow for support of new XML elements in PlaylistListEntry in v2 of YouTube API.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-16T00:44:14.000+0000</p> 
        <div class="body">
            <p>Fixed in r13285, merged to 1-7 branch in r13308.</p>

        </div>
    </div>
    </div>

