<h2>ZF-5206: Missing method getCurrentRouteName in API Doc</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-12-11T01:49:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dennis Becker (radhad)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Nowhere in the docs is described, how to get the current route name used forthe controller-action request. It is not in the "Reference Guide" nor in the API Doc, but in the API Doc should every method listet. Please add the method getCurrentRouteName() to Zend_Controller_Router_Route_Interface and to all classes which extends this class.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-12-11T05:10:47.000+0000</p> 
        <div class="body">
            <p>getCurrentRouteName() is a method of Zend_Controller_Router_Rewrite -- which is the appropriate class for it to be in. Zend_Controller_Router_Route_Interface defines routes that are attached to the rewrite router, and getCurrentRouteName() is used to retrieve the name of the current route that the rewrite router matched.</p>

<p>The method is not part of the router interface as we do not envision that every router would necessarily allow attaching multiple route objects.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dennis Becker (radhad) on 2008-12-11T05:27:27.000+0000</p> 
        <div class="body">
            <p>Hmm... The Framework uses internally Zend_Controller_Router_Rewrite ? Shouldn't this method not be mentioned then somewhere in the Reference Guide? I have searched such a function for about an hour to find out that the instance of Zend_Controller_Front =&gt; getRouter() has this information and I think a lot of other developer would also need this quite often.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-12-11T06:13:24.000+0000</p> 
        <div class="body">
            <p>Re-opening; should document the getCurrentRoute() and getCurrentRouteName() methods.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2008-12-11T06:17:17.000+0000</p> 
        <div class="body">
            <p>Updated in trunk with r13154; will release with 1.7.2.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dennis Becker (radhad) on 2008-12-11T06:28:54.000+0000</p> 
        <div class="body">
            <p>Thank you for updating the docs.</p>

        </div>
    </div>
    </div>

