<h2>ZF-5117: Nested calls to $this-&gt;action in views resets the Request object parameters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2008-12-01T02:17:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-14T17:13:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A simple test case consisting of a controllers and 4 views.
&lt;?php
class TestController extends Zend_Controller_Action{
    
    public function indexAction(){      
    }
    
    public function nestedAction(){     
    }
    
    public function deepNestedAction(){     
    }
    
    public function deepNestedSecondAction(){       
    }

    public function preDispatch(){
        $this-&gt;_helper-&gt;layout-&gt;disableLayout();
    }
    
    public function postDispatch(){
        $this-&gt;view-&gt;request = $this-&gt;getRequest();
    }
}
?&gt;
File index.phtml
Index params: &lt;? print_r($this-&gt;request-&gt;getParams()); ?&gt;<br />
&lt;?= $this-&gt;action('nested', 'test', null, $this-&gt;request-&gt;getParams()); ?&gt;</p>

<p>File nested.phtml
Nested params: &lt;? print_r($this-&gt;request-&gt;getParams()); ?&gt;<br />
&lt;?= $this-&gt;action('deep-nested', 'test', null, $this-&gt;request-&gt;getParams()); ?&gt;<br />
&lt;?= $this-&gt;action('deep-nested-second', 'test', null, $this-&gt;request-&gt;getParams()); ?&gt;</p>

<p>Files deep-nested.phtml and deep-nested-second.phtml
Deep nested params:
&lt;? print_r($this-&gt;request-&gt;getParams()); ?&gt;</p>

<p>Request parameters are present in deep-nested.phtml but are completely empty in deep-nested-second.phtml
It seems like when you list $this-&gt;action calls on the second level of nesting, the first call somehow resets the request params.
This does not happen when listing $this-&gt;action calls on the first level of nesting.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-04T15:52:12.000+0000</p> 
        <div class="body">
            <p>Reporter, in the future you might want to specify the component. That way, it will get to the right person faster. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-14T17:13:56.000+0000</p> 
        <div class="body">
            <p>Matthew, any comment on this one??</p>

        </div>
    </div>
    </div>

