<h2>ZF-5161: Fix @subpackage statement in Zend_Gdata classes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2008-12-04T11:42:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-21T05:03:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.2 (23/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Fix @subpackage statement in Zend_Gdata classes as well as in Gdata.php. Also creating a new subpackage, just called Gdata for the gdata specific classes that while inheriting from Zend_Gdata_App should show up in their own subpackage in the API docs to make for easier reading.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-04T15:35:58.000+0000</p> 
        <div class="body">
            <p>Fixed in r13021 and 13022. Merging to 1.7 branch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-12-04T23:47:55.000+0000</p> 
        <div class="body">
            <p>Note that this has NOT been merged into the release-1.7 branch as of r13033.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-05T10:59:28.000+0000</p> 
        <div class="body">
            <p>Merged in r13039.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-12-05T11:19:47.000+0000</p> 
        <div class="body">
            <p>Changing from "Improvement" to "Docs: Improvement".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2008-12-05T11:20:12.000+0000</p> 
        <div class="body">
            <p>Marking as resolved in next mini release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-05T13:41:56.000+0000</p> 
        <div class="body">
            <p>Thanks. Fixed the remaining for Gdata classes, merged in r13047.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-19T11:41:43.000+0000</p> 
        <div class="body">
            <p>Missed an Extension in /Gdata/Books</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2008-12-19T11:41:55.000+0000</p> 
        <div class="body">
            <p>Merged in r13380</p>

        </div>
    </div>
    </div>

