<h2>ZF-5077: Object of class Zend_Locale to string conversion</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2008-11-26T13:32:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-12-01T13:50:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.1 (01/Dec/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5030">ZF-5030</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <h2>The issue is originaly reported by Ilya Gruzinov (see [ZF-4992]).</h2>

<p>This is reproducible with 1.7.0. version, but only on php &lt;5.2(i test on 5.1.6)</p>

<h1>php LocaleTest.php</h1>

<p>PHPUnit 3.3.5 by Sebastian Bergmann.</p>

<p>E......................E....</p>

<p>Time: 4 seconds</p>

<p>There were 2 errors:
{panel}
1) testObjectCreation(Zend_LocaleTest)
Object of class Zend_Locale to string conversion
/tmp/ZendFramework-1.7.0/library/Zend/Locale.php:885
/tmp/ZendFramework-1.7.0/library/Zend/Locale.php:189</p>

<p>2) testIsLocale(Zend_LocaleTest)
Object of class Zend_Locale to string conversion
/tmp/ZendFramework-1.7.0/library/Zend/Locale.php:885
/tmp/ZendFramework-1.7.0/library/Zend/Locale.php:732</p>

<p>FAILURES!
Tests: 28, Assertions: 171, Errors: 2.
{panel}</p>

<p>I think next lines can explain where mistake:
[<a href="http://www.php.net/manual/en/language.oop5.magic.php">http://php.net/manual/en/…</a>] :</p>

<p>It is worth noting that before PHP 5.2.0 the __toString method was only called when it was directly combined with echo() or print(). Since PHP 5.2.0, it is called in any string context (e.g. in printf() with %s modifier) but not in other types contexts (e.g. with %d modifier). Since PHP 5.2.0, converting objects without __toString method to string would cause E_RECOVERABLE_ERROR.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-26T13:50:09.000+0000</p> 
        <div class="body">
            <p>I think this issue is already fixed in trunk/branch...
Line 885 is a require_once call which does no string conversion.</p>

<p>And any given Zend_Locale instance will be forced to string at line 846/847 by calling toString on the instance.</p>

<p>Can you please test it against trunk.
I can not reproduce it on Windows with 5.1.4</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ilya Gruzinov (shagren) on 2008-11-27T07:16:37.000+0000</p> 
        <div class="body">
            <p>Trunk now:</p>

<p>Time: 4 seconds</p>

<p>There was 1 failure:</p>

<p>1) testIsLocale(Zend_LocaleTest)
Failed asserting that  is true.</p>

<p>FAILURES!
Tests: 29, Assertions: 189, Failures: 1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-27T07:21:03.000+0000</p> 
        <div class="body">
            <p>Ilva:
This failure is ZF-4992</p>

<p>Please to not throw together different issues.
This is useless and make only more work as it should.</p>

<p>And it just raises the time we need for fixing.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2008-11-27T07:22:39.000+0000</p> 
        <div class="body">
            <p>So you are no longer getting the failure of this issue in your environment on trunk ?
Is that correct ?</p>

<p>Then this issue can be closed and we can work on ZF-4992</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ilya Gruzinov (shagren) on 2008-11-27T07:44:30.000+0000</p> 
        <div class="body">
            <p>Yes, it is correct. This issue can be closed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-12-01T13:50:45.000+0000</p> 
        <div class="body">
            <p>Updating these issues to mark them resolved for 1.7.1.</p>

        </div>
    </div>
    </div>

