<h2>ZF-5809: typo in &quot;caution&quot; part, section 37.4.2 (Zend_Pdf): &quot;withing&quot; vs. &quot;within&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-02-17T00:02:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T15:51:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.6 (02/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Remy Damour (remy215)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11758/Screenshot-3.png">Screenshot-3.png</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>It looks like there is a small typo within "caution" part of section 37.4.2 (Zend_Pdf):
bq.Important! Cloned page shares some PDF resources with a template page, so it can be used only <em>withing</em> the same document...
It may be "within".</p>

<p>By the way, "caution" img does not load (cf. screenshot)</p>

<p>Regards,
Remy</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Remy Damour (remy215) on 2009-02-17T00:05:18.000+0000</p> 
        <div class="body">
            <p>Caution img does not load</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-02-17T06:26:00.000+0000</p> 
        <div class="body">
            <p>The caution tag is used only in the section.</p>

<p>I find the same problem  with ``` tag also in following.</p>

<p>Zend_Db_Table.xml
Zend_Registry.xml
Zend_Rest_Client.xml
Zend_Search_Lucene-Charset.xml</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-04-03T18:20:39.000+0000</p> 
        <div class="body">
            <p>Hi, Remy.
Please create or clone new issue about image file.</p>

        </div>
    </div>
    </div>

