<h2>ZF-5737: Fix typo in Rating.php extension class.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-02-10T18:11:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-17T09:32:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.5 (16/Feb/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jochen Hartmann (jhartmann)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-02-17T06:43:41.000+0000</p> 
        <div class="body">
            <p>Hi, Jochen.</p>

<p>Can I help You?
I will be happy if you tel me where is there typo.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jochen Hartmann (jhartmann) on 2009-02-17T09:32:36.000+0000</p> 
        <div class="body">
            <p>This was a duplicate issue created accidentally. The real one is ZF-5738 which was resolved for 1.7.5</p>

        </div>
    </div>
    </div>

