<h2>ZF-5880: Remove mention of setting gd:when valueString in Zend_Gdata_Calendar documentation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-02-24T15:05:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-02T14:12:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.7 (16/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Gdata_Calendar docbook manual includes an example where a gd:when valueString is set. However, the Calendar API discards this data.</p>

<p>To prevent confusion, this part of the example should be removed from the manual.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-02-24T15:25:49.000+0000</p> 
        <div class="body">
            <p>Patch sent to [~jhartmann] for review:</p>

<p><a href="http://codereview.appspot.com/21064">http://codereview.appspot.com/21064</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-03-02T14:12:36.000+0000</p> 
        <div class="body">
            <p>Reviewed by [~jhartmann].
Committed to trunk as r14201.
Committed to release-1.7 as r14202.
Marking as fixed for next-mini release (should be 1.7.7).</p>

<pre class="literal">
commit 18339606f181cc9b20fd51678086c1859790927b
Author: tjohns 
Date:   Mon Mar 2 22:01:25 2009 +0000

    ZF-5880: Update Zend_Gdata_Calendar documentation to indicate that the gd:when
    valueString property is unused.
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/trunk@14201">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac1e357ba

commit 9a725f9ca475cb6638d3fae2475c83d39995e435
Author: tjohns 
Date:   Mon Mar 2 22:07:06 2009 +0000

    Merge r14201 from trunk to release-1.7.
    
    ZF-5880: Update Zend_Gdata_Calendar documentation to indicate that the gd:when
    valueString property is unused.
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/branches/release-1.7@14202">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac1e357ba
</pre>

        </div>
    </div>
    </div>

