<h2>ZF-5437: isDate potentially unsafe</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Performance Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-01-09T07:29:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-02-06T09:42:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The use of {{Date::isDate()}} can potentially lead to a DOS attack on a site where dates are validated using {{Zend_Validate_Date}}, consider the following example:</p>

<p>{{$formElement-&gt;addValidator( new Zend_Validate_Date( 'DD.MM.YYYY', new Zend_Locale( 'de_DE' ) );}}</p>

<p>User Input such as {{12.12.123123123}} (basically anything really far in the future) will send CPU usage to 100%</p>

<p>Maybe the function should have some kind of sensible bounds built in or at least the documentation should make users aware of this.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-01-09T15:47:49.000+0000</p> 
        <div class="body">
            <p>Could be just me, but doesn't this go for all resource-intensive 'scripts' (sorry Thomas)? If more resources than available are requested on purpose, a server is considered under attack. I can't see how this specifically relates to Zend_Date (or the Zend Framework in general).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-02-06T09:42:56.000+0000</p> 
        <div class="body">
            <p>Fixed with r13997</p>

        </div>
    </div>
    </div>

