<h2>ZF-5797: Online Programmer's Reference Guide has a javascript error.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-02-16T06:18:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T14:07:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.8 (30/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I find a javascript error when I browse <a href="http://framework.zend.com/manual/en/">http://framework.zend.com/manual/en/</a> .</p>

<p>The message says there is some error of  identifier,  string or numeral  in the line 45 letter 1 .</p>

<p>I think a code causes this error.
The code is in the component list in rightside of the online manual as following.</p>

<pre class="highlight"><code>
var zend = {
    showVideo: function(target) {
        dojo.query(".video-box").forEach(function(item){
            dojo.style(item, { display: "none" });
        });
        dojo.query(".video-tab").forEach(function(item){
            dojo.removeClass(item, 'current');
        });
        dojo.style(target, { display: "block" });
        var link = target + '-link';
        dojo.addClass(link, "current");
    },
};
</code></pre>

<p>You can find ```  in line 44  if you display html source .</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-04-03T18:30:42.000+0000</p> 
        <div class="body">
            <p>Today, I find this issue to be fixed. 
I do not know when it was fixed,  so I set 1.7.8 to fix version.</p>

        </div>
    </div>
    </div>

