<h2>ZF-5974: Call to the method toJson when possible in Zend_Json_Encoder::_encodeObject</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-03-09T10:23:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-23T23:40:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sylvain Filteau (sylvain)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json</li>
            <li>zf-caretaker-adamlundrigan</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9521">ZF-9521</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11790/fix.diff">fix.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When a class implement the method toJson, Zend_Json::encode (using the builtin encoder) should call this method when encoding object in the structure.</p>

<p>Here is a code sample :</p>

<pre class="highlight"><code>
&lt;?php

set_include_path('/home/sylvain/src/ZendFramework/library');

require_once('Zend/Loader.php');

Zend_Loader::registerAutoload();

class JsonEncodable {
        public function toJson() {
                return '"Encodable object"';
        }
}

$struct = array(
        'encodable_object' =&gt; new JsonEncodable()
);

Zend_Json::$useBuiltinEncoderDecoder = true;
echo Zend_Json::encode($struct);

</code></pre>

<p>This code should return :</p>

<pre class="highlight"><code>
{"encodable_object":"Encodable object"}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Sylvain Filteau (sylvain) on 2009-03-09T10:24:34.000+0000</p> 
        <div class="body">
            <p>Here is my implementation of the patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sylvain Filteau (sylvain) on 2009-03-09T10:42:34.000+0000</p> 
        <div class="body">
            <p>Maybe it would be cleaner to add an interface (Zend_Json_Encodable) with the method toJson ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-03-10T10:33:50.000+0000</p> 
        <div class="body">
            <p>This would only work for the internal encoder, therefore it should be implemented in such a way, that it doesnt hurt the compability with the json_encode functionality.</p>

<p>The use of an interface Zend_Json_Encodable is a good choice in my opinion. But we should get in touch with the ext/json author to discuss, weather and how he plans to implement nested object serialization via an interface, so that we don't drift out if a to be come php interface uses some other method instead of toJson.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sylvain Filteau (sylvain) on 2009-03-10T12:47:20.000+0000</p> 
        <div class="body">
            <p>@Benjamin Eberlei : That's true, and I sent an email to the author of ext/json a couple of minutes ago asking him what was his plans about it</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bert Van Hauwaert (becoded) on 2009-09-11T07:34:30.000+0000</p> 
        <div class="body">
            <p>@Sylvain Filteau: Did you recieved an answer on it?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sylvain Filteau (sylvain) on 2009-09-11T07:51:59.000+0000</p> 
        <div class="body">
            <p>@Benjamin Eberlei : I didn't receive an answer from him... and I don't think I will ever receive one ! ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sylvain Filteau (sylvain) on 2010-04-01T12:28:32.000+0000</p> 
        <div class="body">
            <p>Instead of limiting my feature to the builtin encoder, maybe I could add it to the magic trick used by <a href="http://framework.zend.com/manual/1.10/en/zend.json.advanced.html#zend.json.advanced.expr">http://framework.zend.com/manual/1.10/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sylvain Filteau (sylvain) on 2010-06-03T12:10:45.000+0000</p> 
        <div class="body">
            <p>Something that could be interesting in this issue :</p>

<p><a href="http://schlueters.de/blog/archives/135-Jason,-let-me-help-you!.html">http://schlueters.de/blog/archives/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-23T23:40:08.000+0000</p> 
        <div class="body">
            <p>This is a duplicate of ZF-9521.</p>

        </div>
    </div>
    </div>

