<h2>ZF-6547: Method setValueDisabled does not exist, Zend_Form_Element_Exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-05T15:48:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-06T18:30:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello 
when i tried to use setValueDisabled but i got an exception which said
Uncaught exception 'Zend_Form_Element_Exception' with message 'Method setValueDisabled does not exist</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-05T17:36:11.000+0000</p> 
        <div class="body">
            <p>This method only exists on Zend_Form_Element_File; it will not work for other elements.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by islam mohmed el naggar (islamelnaggar) on 2009-05-06T16:00:33.000+0000</p> 
        <div class="body">
            <p>setValueDisabled the method doesn't exists in Zend_Form_Element_File for version 1.8.0 
this exception thrown when i call this method for the file element not for any element!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-06T18:30:03.000+0000</p> 
        <div class="body">
            <p>I have just checked trunk and the 1.8 release branch, and this method <em>does</em> exist in Zend_Form_Element_File in both places. The only revision of Zend_Form_Element_File in the 1.8 release branch was created when the branch was created.</p>

<p>You either do not have 1.8.0, or you have an earlier version of Zend Framework installed earlier on your include_path.</p>

        </div>
    </div>
    </div>

