<h2>ZF-6342: Extra &lt;?php statements in files when creating a new project</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-19T12:39:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-19T22:35:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using {{zf create project test}}.</p>

<p>The index.php and IndexController.php files both have an additional &lt;?php  statement at the top...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alejandro Henríquez Lazo (ahenriquez) on 2009-04-19T17:53:46.000+0000</p> 
        <div class="body">
            <p>this issues was reported in ZF-6241</p>

        </div>
    </div>
    </div>

