<h2>ZF-6656: Autoloader_Ressource doc : wrong example</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-05-14T09:41:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.loader.autoloader-resource.html">http://framework.zend.com/manual/en/…</a>
30.3.1. Resource autoloader usage</p>

<p>It says that
{quote}
Within this directory, all code is prefixed with the namespace "My_". Within the "acls" subdirectory, the component prefix "Acl_" is added, giving a final class name of "My_Acl_Site". Similarly, the "forms" subdirectory maps to "Form_", giving "My_Form_Login". <em>The "models" subdirectory has no component namespace, giving "My_User".</em>
{quote}</p>

<p>The bold sentence is wrong. Any class that is not in a ResourceType directory, cannot be loaded by the Ressource Autoloader</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maxim Stepanov (mast) on 2010-06-11T08:25:27.000+0000</p> 
        <div class="body">
            <p>Just found the same issue. Is there a way to get My_User loaded using Zend_Loader_Autoloader_Resource?</p>

        </div>
    </div>
    </div>

