<h2>ZF-6432: Fatal error in Zend_Filter_ LocalizedToNormalized constructor.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-26T15:29:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-26T18:10:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This happens when I don't pass first constructor's parameter and leave it null:</p>

<p>Fatal error: Unsupported operand types in C:...some-path-here...\Zend\Filter\LocalizedToNormalized.php on line 81.</p>

<p>Environment:
PHP Version 5.2.4
Zend Framework from trunk</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-04-26T18:10:47.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk and 1.8 release branch.</p>

        </div>
    </div>
    </div>

