<h2>ZF-6408: Let Zend_Filter_File_Rename accept filename only as target</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-04-24T01:11:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-11T13:08:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jan Sorgalla (jsorgalla)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6851">ZF-6851</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Let Zend_Filter_File_Rename accept filename only as target:</p>

<pre class="highlight"><code>
$filter = Zend_Filter_File_Rename('filename.ext');
</code></pre>

<p>The full path should be gathered from the dirname(source).</p>

<p>I'm not sure if its a BC, because at the moments this would be handled as a relative path (like ./filename.text)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-06-11T13:08:01.000+0000</p> 
        <div class="body">
            <p>New feature implemented with r16009</p>

        </div>
    </div>
    </div>

