<h2>ZF-6499: Zend/Tool/Framework/Manifest/Metadata.php missing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-02T03:12:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-22T06:58:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Adam Golebiowski (adamg)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend/Tool/Framework/Metadata/Dynamic.php require_once()'s Zend/Tool/Framework/Manifest/Metadata.php which is missing in both 1.8.0 release and svn trunk (r15045).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Piotr Czachur (zimnyx) on 2009-05-19T07:44:09.000+0000</p> 
        <div class="body">
            <p>Confirmed in 1.8.1.</p>

<p>This should have higher priority!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-05-22T06:58:56.000+0000</p> 
        <div class="body">
            <p>Fixed in r15677</p>

        </div>
    </div>
    </div>

