<h2>ZF-6827: Fatal error: Call to a member function setFetchMode() on a non-object in /var/www/html/library/Zend/Db/Statement/Pdo.php on line 426</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-27T16:54:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-27T18:09:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jonathan Block (block.jon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I get the "Call to a member function setFetchMode() on a non-object" with a segmentation fault when i run this code:</p>

<pre><code>    $locationTable = new DatabaseTable_Location();
    $locationRow = $locationTable-&gt;fetchRow('id = ' . $locationid);
</code></pre>

<p>and when $locationid is null.</p>

<p>please advise. How do I find the version of zend framework? I downloaded it a couple of months ago...</p>

<p>Jon</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-27T16:59:29.000+0000</p> 
        <div class="body">
            <p>Do you get an exception, or a segfault?</p>

<p>You can find the version of ZF by looking in /library/Zend/Version.php . If you could test this against 1.8.2 or trunk it would be highly appreciated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Block (block.jon) on 2009-05-27T17:49:04.000+0000</p> 
        <div class="body">
            <p>I was using 1.7.2!! Wow that's old.</p>

<p>I upgraded to 1.8.2. This issue seems to be resolved in 1.8.2 because I see a meaningful SQL error.</p>

<p>Thank you!!</p>

<p>Also, I tried to get the source from the svn trunk. Your "Readme.txt" indicates:</p>

<p>"The URL for the trunk of the Zend Framework SVN repository is:
<a href="http://framework.zend.com/svn/framework/trunk">http://framework.zend.com/svn/framework/trunk</a>"</p>

<p>I therefore tried to "svn ls <a href="http://framework.zend.com/svn/framework/trunk">http://framework.zend.com/svn/framework/trunk</a>" but i get:</p>

<p>my-macbook-pro:library jon$ svn ls <a href="http://framework.zend.com/svn/framework/trunk">http://framework.zend.com/svn/framework/trunk</a>
svn: URL '<a href="http://framework.zend.com/svn/framework/trunk">http://framework.zend.com/svn/framework/trunk</a>' non-existent in that revision</p>

<p>So, that's a different problem I suppose.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-27T18:09:37.000+0000</p> 
        <div class="body">
            <p>I'm closing this issue because it apparently was solved already.</p>

<p>What the URL is concerned, I opened up a new issue for that: ZF-6829</p>

        </div>
    </div>
    </div>

