<h2>ZF-6705: Element Class (Form) _loadValidator() uses unset() on an offset and this throw a fatal error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-17T14:31:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                ramon himera (ramonhimera)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Element Class (Form) _loadValidator() uses unset() on an offset and this throw a fatal error when trying to clear $validator['options']['messages'] on line 1969. The error was thrown when i called form-&gt;isValid() using a custom validator.</p>

<p>Element.php (_loadValidator):
            if (isset($validator['options']['messages'])) {
                $messages = $validator['options']['messages'];
                unset($validator['options']['messages']);
            }</p>

<p>In my form class:
        $name = new Zend_Form_Element_Text('name');
        $name-&gt;setLabel('Event name:')-&gt;setRequired(true);
        $name-&gt;addPrefixPath('BC_Validate', 'BC/Validate', 'validate');
        $name-&gt;addValidator('EventName', false);</p>

<p>File BC/Validate/EventName.php defines the function isValid($value, $context)</p>

<p>I had to check the type before resetting the variable to empty.
The version i am using is 1.6.0 but i noted the line of code is still present in 1.80 but i havent tested on this.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:23.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

