<h2>ZF-6808: doc typo</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-05-26T07:59:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-26T08:38:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Josh Ribakoff (jshpro2)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>there are two ways to archive this
<a href="http://framework.zend.com/manual/en/zend.controller.router.html#zend.controller.router.default-routes">http://framework.zend.com/manual/en/…</a></p>

<p>archive = achieve?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-26T08:38:04.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.8 release branch.</p>

        </div>
    </div>
    </div>

