<h2>ZF-6562: Zend_Paginator_Adapter_DbSelect fails on HAVING clause</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-06T09:14:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-18T21:24:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Paginator_Adapter_DbSelect seems to create a wrong query for getting the count when the query has a 'HAVING' in it.</p>

<p>Simplified example:</p>

<p>$select = $db-&gt;select()
    -&gt;from('user', 'user_id AS foo')
    -&gt;having('foo &gt; ?', 4);</p>

<p>// query is: SELECT <code>user</code>.<code>user_id</code> AS <code>foo</code> FROM <code>user</code> HAVING (foo &gt; 4)</p>

<p>$paginator = new Zend_Paginator(new Zend_Paginator_Adapter_DbSelect($select));</p>

<p>Created query is: 
SELECT COUNT(*) AS <code>zend_paginator_row_count</code> FROM <code>user</code> HAVING (foo &gt; 4)</p>

<p>which is obviously not working.</p>

<p>Haven't tested it yet in 1.8.0.</p>

<p>BR
 anselm</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-06-18T21:24:06.000+0000</p> 
        <div class="body">
            <p>Resolved in r16157 and merged to release-1.8 in r16158</p>

        </div>
    </div>
    </div>

