<h2>ZF-6683: Zend_Locale_Format::getNumber() parses French thousands separator incorrectly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-15T16:19:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-23T14:09:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In many French locales it is correct to use a space as a thousands separator.  As an example, the US English method of writing 1,000,000 in French Canada is 1 000 000.</p>

<p>The output of Zend_Locale_Format::getNumber('1 324',array('locale' =&gt; 'fr_CA') is 1 as opposed to the correct 1324.  Naturally this is a simplified example; the typical use case is to take a locale specific string (possibly with currency indicators) and convert it into a number that can be compared etc, which works fine in other locales, such as the German locale that uses periods as thousands separators.</p>

<p>Workaround is to strip spaces out of all inputs to getNumber ATM.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-23T14:07:45.000+0000</p> 
        <div class="body">
            <p>According to CLDR the grouping character for 'fr' is a chr(/u00A0) and not chr(/u0020).
Using the proper grouping character, the numbers are recognised as expected.</p>

<p>Example:</p>

<pre class="highlight"><code>
var_dump(Zend_Locale_Format::getNumber('1 324',array('locale' =&gt; 'fr_CA')));
</code></pre>

<p>Note that even if it looks like the digits are seperated by a space, it's another character (A0 instead of 20) which is not a space but a "no-break-space".</p>

<p>Note also that this is defined by CLDR and not by ZF as grouping character for the locale 'fr'</p>

        </div>
    </div>
    </div>

