<h2>ZF-6380: The use of the dialog helper does not exist.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-22T08:34:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-22T20:44:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jay M. Keith (jmkeith)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to the documentation one only needs to use $this-&gt;dialog($id, $content, $params, $attribs); in order to create a jQuery UI dialog.</p>

<p>Expected outcome:
the use of $this-&gt;dialog("dialog", "content here", array(), array()); within a view script will produce the appropriate jQuery Dialog.</p>

<p>Actual outcome:</p>

<p>An exception will be thrown:</p>

<pre class="literal">
Fatal error: Uncaught exception 'Zend_Loader_PluginLoader_Exception' with message 'Plugin by name 'Dialog' was not found in the registry; used paths: ZendX_JQuery_View_Helper_: ZendX/JQuery/View/Helper/ Zend_View_Helper_: Zend/View/Helper/'
</pre>

<p>Even though the appropriate paths are set.</p>

<p>Workaround:
using $this-&gt;dialogContainer("dialog", "content here", array(), array()); will create the appropriate code to initiate a jQuery UI dialog</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-04-22T20:44:35.000+0000</p> 
        <div class="body">
            <p>This is an documentation issue and is now fixed in trunk.</p>

        </div>
    </div>
    </div>

