<h2>ZF-6966: Zend_Db forces 'naming convention'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-09T07:40:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-20T14:57:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Here's my setup:</p>

<pre class="highlight"><code>
db.params....
db.params.adapter = vendor_Db_Adapter_XXX
</code></pre>

<p>Whenever I use this, Zend_Db::factory() does not honor my naming convention, but instead forces an upper case letter, thus making it {{Vendor_Db_Adapter_XXX}}, instead of {{vendor_Db_Adapter_XXX}} which leads to an error ({{Zend_Loader}} can't find the class, etc.).</p>

<p>The quickfix is of course an include statement, which doesn't hurt anyway since I am using my custom adapter on each request, but I wanted to file this bug anyway to get it fixed. Wouldn't hurt to be more open in this case. I also know sure that this cannot be introduced/changed without breaking BC.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-06-09T07:50:34.000+0000</p> 
        <div class="body">
            <p>Isn't this an issue with Zend_Loader rather than Zend_Db? Anyways, Zend_Loader is based on the ZF naming conventions. If you want to deviate from that I suppose you'll need to use your own autoloader (or try the fallback autoloader).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Butts (jimbojsb) on 2009-08-17T11:50:49.000+0000</p> 
        <div class="body">
            <p>@Dolf agree this is a Zend_Loader issue, and even then, not really an issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-17T12:36:57.000+0000</p> 
        <div class="body">
            <p>The problem is with the code in the factory that does this:</p>

<pre class="highlight"><code>
        /*
         * Form full adapter class name
         */
        $adapterNamespace = 'Zend_Db_Adapter';
        if (isset($config['adapterNamespace'])) {
            if ($config['adapterNamespace'] != '') {
                $adapterNamespace = $config['adapterNamespace'];
            }
            unset($config['adapterNamespace']);
        }
        $adapterName = strtolower($adapterNamespace . '_' . $adapter);
        $adapterName = str_replace(' ', '_', ucwords(str_replace('_', ' ', $adapterName)));
</code></pre>

<p>Unfortunately, we cannot fix this until 2.0 time.  I would postpone, but the likelyhood of this exact code making it into 2.0 is highly unlikely since 2.0 will more than likely take advantage of real namespaces.</p>

<p>As Dolf mentioned above, this can be handled with a custom Zend_Loader_Autoloader.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-09-20T14:57:04.000+0000</p> 
        <div class="body">
            <p>Fixed with the solution in ZF-5606</p>

        </div>
    </div>
    </div>

