<h2>ZF-6453: Zend_Db_Table_Abstract::_setup does not call _setupMetadata or _setupPrimaryKey</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-28T14:26:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T02:40:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Roger Hunwicks (rhunwicks)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In ZF 1.7.8 (as supplied with Zend Server) and ZF 1.8.0PR (as linked from <a href="http://framework.zend.com">http://framework.zend.com</a>) the _setup method in Zend_Db_Table_Abstract is:</p>

<pre class="literal">
    protected function _setup()
    {
        $this-&gt;_setupDatabaseAdapter();
        $this-&gt;_setupTableName();
    }
</pre>

<p>whereas on 1.6.2 it is:</p>

<pre class="literal">
    protected function _setup()
    {
        $this-&gt;_setupDatabaseAdapter();
        $this-&gt;_setupTableName();
        $this-&gt;_setupMetadata();
        $this-&gt;_setupPrimaryKey();
    }
</pre>

<p>One result of this is that if the primary key is defined using:</p>

<pre class="literal">
    _primary = array ( 'ID' );
</pre>

<p>then the primary key starts off as a zero-based array (the PHP default) and then changes to a 1-based array the first time that _setupPrimaryKey is called, e.g. by a call to $table-&gt;select().</p>

<p>However, I am sure there are lots of other unintended sideffects from not calling _setupMetadata.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Roger Hunwicks (rhunwicks) on 2009-05-04T01:46:13.000+0000</p> 
        <div class="body">
            <p>This issue also affects the released 1.8.0</p>

<p>It seems as though current development is being done in the root: branch (<a href="http://framework.zend.com/code/browse/Zend_Framework/standard/trunk/library/Zend/Db/Table/Abstract.php#broot">http://framework.zend.com/code/browse/…</a>:) and that the most recent version of that (<a href="http://framework.zend.com/code/browse/Zend_Framework/standard/trunk/library/Zend/Db/Table/Abstract.php#r13554">http://framework.zend.com/code/browse/…</a>) is the one included in ZF 1.8.0.</p>

<p>The error seems to have been introduced in Rev 12290 - see <a href="http://framework.zend.com/code/browse/Zend_Framework/standard/trunk/library/Zend/Db/Table/Abstract.php?r1=12245&amp;r2=12290">http://framework.zend.com/code/browse/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roger Hunwicks (rhunwicks) on 2009-05-04T01:48:01.000+0000</p> 
        <div class="body">
            <p>Changed affected versions to include 1.8.0</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by paveli (paveli) on 2009-06-24T03:40:10.000+0000</p> 
        <div class="body">
            <p>... and this issue also affects the released 1.8.4</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Virgil Daniel Ratiu (vratiu) on 2009-06-24T03:51:55.000+0000</p> 
        <div class="body">
            <p>See here why         $this-&gt;_setupMetadata();
was removed
<a href="http://framework.zend.com/issues/browse/ZF-3771">http://framework.zend.com/issues/browse/ZF-3771</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-29T02:40:33.000+0000</p> 
        <div class="body">
            <p>This was changed in ZF-2510 to allow lazy-loading of those items.  You must extend Zend_Db_Table_Abstract to either provide an alternate implementation or simply call the existing implementations:</p>

<pre class="highlight"><code>
class My_Table extends Zend_Db_Table_Abstract 
{
    protected function _setup()
    {
        parent::_setup();
        $this-&gt;_setupMetadata();
    }
}
</code></pre>

        </div>
    </div>
    </div>

