<h2>ZF-6051: Zend_Cache compressing output</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-03-17T23:33:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-02T06:21:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Maxime (maxime)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11853/ZF-issue.zip">ZF-issue.zip</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When you cache some html, css, javascript data, you store them as they were created : with spaces, comments, new and empty lines, very long names for css classes or javascript's variables.
I think we can improve Zend_Cache : we should be able to compress cached data. I don't think about gzip, but for example, something like Dojo Shrinksafe for javascript :
 - delete unneeded spaces and lines
 - delete comments
 - change size of variable</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maxime (maxime) on 2009-03-18T00:41:38.000+0000</p> 
        <div class="body">
            <p>This can be helpful : <a href="http://svn.fckeditor.net/FCKpackager/trunk/fckpackager.php">http://svn.fckeditor.net/FCKpackager/trunk/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michael Contento (kaffeefleck) on 2009-03-18T01:20:35.000+0000</p> 
        <div class="body">
            <p>AFAIK the best compressor for CSS/JS is YUI -&gt; <a href="http://www.julienlecomte.net/yuicompressor/">http://www.julienlecomte.net/yuicompressor/</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maxime (maxime) on 2009-04-02T02:12:43.000+0000</p> 
        <div class="body">
            <p>Hello,</p>

<p>This is some new code to add to ZF. It extends ZF_Cache in order to compress data.
A doc file explains how it works.</p>

<p>I hope it can be integrated to a next ZF release.</p>

<p>Regards.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maxime (maxime) on 2009-07-17T09:52:12.000+0000</p> 
        <div class="body">
            <p>Can this compress feature be added to ZF ?
How can i help to do this ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien MARTY (fab) on 2009-07-17T11:01:29.000+0000</p> 
        <div class="body">
            <p>change Assignee because I'm inactive now</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-02T06:21:23.000+0000</p> 
        <div class="body">
            <p>I find the 2 proposals here;</p>

<ol><li><p>Zend_Cache_Backend_Compression
<a href="http://framework.zend.com/wiki/display/ZFPROP/Zend_Cache_Backend_Compression+-+Maxime+Varinard">http://framework.zend.com/wiki/display/…</a></p></li>
<li><p>Zend_Compress
<a href="http://framework.zend.com/wiki/display/ZFPROP/Zend_Compress+Proposal+-+Steven+Brown">http://framework.zend.com/wiki/display/…</a></p></li>
</ol>
        </div>
    </div>
    </div>

