<h2>ZF-6558: Zend_Translate should find sources based solely on dir/file structure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-06T06:56:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-13T12:07:55.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using the array adapter (not sure if it happens with other adapters), if you have multiple language files distributed over multiple folders and more than one file has the same index for a translate element ZF "chooses" one of the files and uses it, often generating wrong translations. For an example, if I have:</p>

<p>application/views/scripts/index/index.phtml and
application/views/scripts/contact/index.phtml</p>

<p>and I have my language files like this:</p>

<p>application/languages/en/US/index/index.php and
application/languages/en/US/contact/index.php</p>

<p>and both language files return a 'title' index, I may end up with the wrong 'title' translated. I believe Zend_Translate should look for sources based solely in folder/file structure, connecting views and language files.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-13T12:07:33.000+0000</p> 
        <div class="body">
            <p>You misunderstood how translation works:
There is no way to have two identical messageIds translated into two different translations.</p>

<p>Example:
When you write in your code...</p>

<p>translate('Title');</p>

<p>and the same in another file then the messageId 'Title' is used for both files.</p>

<p>On the other hand, when you have the messageId 'Title' in two different files then you will not know which of them will be used because the used adapter is responsible for this.</p>

<p>There is no way to support this as translations are not related to the path of a file, but to the text which has to be translated.</p>

<p>To have a solution you must use different messageIds:
For example 'Title_Index' and 'Title_Contact' when you are not using real content. Because when you have "My Title" in two files, the translation is for both files equal.</p>

        </div>
    </div>
    </div>

