<h2>ZF-6955: Cookie support for Zend_Soap_Client</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-06-08T07:44:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-24T05:00:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Lukas Drbal (lestr)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11991/svnPatch_Rev15953">svnPatch_Rev15953</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi!</p>

<p>It is possible to implement method SoapClient::__setCookie() [<a href="http://php.net/manual/en/soapclient.setcookie.php">http://php.net/manual/en/soapclient.setcookie.php</a>] to Zend_Soap_Client?</p>

<p>Its blocker for me :-/</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Lukas Drbal (lestr) on 2009-06-09T01:10:07.000+0000</p> 
        <div class="body">
            <p>Adding patch that resolves this issue.</p>

<p>Please comment on.</p>

<p>Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-06-11T03:01:04.000+0000</p> 
        <div class="body">
            <p>Implemented in trunk, will be in next minor release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lukas Drbal (lestr) on 2009-06-11T05:00:30.000+0000</p> 
        <div class="body">
            <p>Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lukas Drbal (lestr) on 2009-06-24T05:00:42.000+0000</p> 
        <div class="body">
            <p>It is not in 1.8.4 :-(
Why please? Its blocker for me :-/</p>

        </div>
    </div>
    </div>

