<h2>ZF-6942: Missing Dependency: Session_Resource with SaveHandler_DbTable dont bootstrap db resource</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-06T11:26:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-17T15:44:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Krebs (kingcrunch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6974">ZF-6974</a></li>
            <li><a href="/issues/browse/ZF-7168">ZF-7168</a></li>
            <li><a href="/issues/browse/ZF-6651">ZF-6651</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12100/Session.diff">Session.diff</a></li>
            <li><a href="/issues/secure/attachment/12099/Session.php">Session.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using Resource_Session with the DbTable-Savehandler cause an exception, if the Db-Resource is not called before.</p>

<p>Version is trunk 15883</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-06-16T04:28:28.000+0000</p> 
        <div class="body">
            <h1>ZF-6974 explains the problem with more details</h1>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Vladimir Michailenko (mich) on 2009-06-17T10:15:36.000+0000</p> 
        <div class="body">
            <h1>ZF-6974 is marked as resolved, but this issue is still presenting in the trunk for me.</h1>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Weinstock (adamweinstock) on 2009-07-14T00:46:06.000+0000</p> 
        <div class="body">
            <p>I'm getting this too.</p>

<p>The problem occurs because Zend_Application_Bootstrap_BootstrapAbstract::getPluginResourceNames() calls Zend_Application_Bootstrap_BootstrapAbstract::getPluginResources() which in turn calls Zend_Application_Bootstrap_BootstrapAbstract::_loadPluginResource(). This instantiates but does not execute instances of the registered resource objects, causing Zend_Application_Resource_Session::setSaveHandler() to instantiate an instance of Zend_Db_Table_Abstract before the Db resource is actually executed. Since Zend_Application_Resource_Db doesn't call Zend_Db_Table::setDefaultAdapter() until it's init() method is called, the desired behavior fails.</p>

<p>The simplest solution seems to be to remove the call to getPluginResources() in Zend_Application_Bootstrap_BootstrapAbstract::getPluginResourceNames(). This seems to be working for me, but may cause problems, so another solution may be more desirable. In any case, this bug will definitely cause problems with other resources down the line and should be fixed up.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Krebs (kingcrunch) on 2009-07-14T01:09:02.000+0000</p> 
        <div class="body">
            <p>I think it should call bootstrap("db"), if the Db-Savehandler is used, because its a direct dependency and the manual mention, that dependencies should be solved this way. Maybe the savehandler-class call it itself, instead of the session-pluginresource.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Weinstock (adamweinstock) on 2009-07-14T11:25:05.000+0000</p> 
        <div class="body">
            <p>I disagree Sebastian.  Technically Zend_Application_Resource_Session is not dependent on Zend_Application_Resource_Db, so I don't think we should force this in the code.</p>

<p>If we wanted to focus the solution within the Zend_Application_Resource_Session class, we could think about restructuring things so the save handler instance, in this case an object of Zend_Db_Table_Abstract, isn't created until Zend_Application_Resource_Session::init() is called.  In fact, I don't see why we can't move all of the logic in Zend_Application_Resource_Session::setSaveHandler() to Zend_Application_Resource_Session::init().</p>

<p>However, as I noted above, the problem we are encountering is tied to the way resources are setup, loaded, and executed, so it may be best to tackle the underlying logic to prevent future bugs with different resources.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Krebs (kingcrunch) on 2009-07-14T11:32:31.000+0000</p> 
        <div class="body">
            <p>{quote}I disagree Sebastian. Technically Zend_Application_Resource_Session is not dependent on Zend_Application_Resource_Db, so I don't think we should force this in the code. {quote}
Not the whole resource, but the Db-savehandler.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Weinstock (adamweinstock) on 2009-07-14T11:48:08.000+0000</p> 
        <div class="body">
            <p>Yes, but Zend_Session_SaveHandler_DbTable isn't dependent on Zend_Application_Resource_Db either.  It's a subclass of Zend_Db_Table_Abstract and must have an instance of Zend_Db_Adapter_Abstract set as it's adapter, but that adapter doesn't need to be created through an application resource.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Vladimir Michailenko (mich) on 2009-07-23T15:14:01.000+0000</p> 
        <div class="body">
            <p>Moved  SaveHandler initialization from setOptions() to init() method (db should be initialized at this point).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexandre Nault (anault) on 2009-07-23T19:28:31.000+0000</p> 
        <div class="body">
            <p>This patch works for me!</p>

<p>Thank you for it.</p>

<p>Issue ZF-7168 resolved with the patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-09-17T15:13:44.000+0000</p> 
        <div class="body">
            <p>Applied the patch and wrote a unittest suite for Session resource, merged into 1.9 release branch.</p>

        </div>
    </div>
    </div>

