<h2>ZF-6195: A set of &quot;Zend_File_Transfer_Exception: Wether APC nor uploadprogress extension installed&quot; exceptions</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2009-04-02T13:44:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-03T14:23:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
2) testNoUploadInProgress(Zend_File_Transfer_Adapter_HttpTest)
Zend_File_Transfer_Exception: Wether APC nor uploadprogress extension installed
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/File/Transfer/Adapter/Http.php:286</p>

<p>3) testUploadProgressFailure(Zend_File_Transfer_Adapter_HttpTest)
Zend_File_Transfer_Exception: Wether APC nor uploadprogress extension installed
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/File/Transfer/Adapter/Http.php:286</p>

<p>4) testUploadProgressAdapter(Zend_File_Transfer_Adapter_HttpTest)
Zend_File_Transfer_Exception: Wether APC nor uploadprogress extension installed
/home/cawa/ZendFramework/svn/framework/trunk/library/Zend/File/Transfer/Adapter/Http.php:286
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-04-02T14:00:34.000+0000</p> 
        <div class="body">
            <p>If  APC or uploadprogress extensions are required and it's correct behavior, then it's better to skip test.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-04-03T10:34:13.000+0000</p> 
        <div class="body">
            <p>Should be fixed with r14621</p>

        </div>
    </div>
    </div>

