<h2>ZF-6531: Nice to have functions to retrieve sender email and name each separately</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-05T01:03:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>From header returns only the name of the sender when the email address of the sender is like : John Doe <a href="mailto:john@domain.net">john@domain.net</a></p>

<p>If i retreive the messages with my email reader, the source of the message contains John Doe <a href="mailto:john@domain.net">john@domain.net</a> but Zend_Mail_Storage_Pop3 returns me only 'John Doe'</p>

<p>This is the code i'm using.</p>

<pre class="highlight"><code>
$mail = new Zend_Mail_Storage_Pop3(array('host'     =&gt; $myserver,  'user'     =&gt; $myusername,  'password' =&gt; $mypassword));

foreach ($mail as $i =&gt; $message) {
    echo "MESSAGE $i</code></pre><pre><code>";
    foreach ($message-&gt;getHeaders() as $name =&gt; $value) {
        if (is_string($value)) {
            echo "$name: $value\n";
            continue;
        }
        foreach ($value as $entry) {
            echo "$name: $entry\n";
        }
    }
    echo "</code></pre><code>";
}
</code>

<p>I made the test with different mails servers (including gmail) and i have every times the same result</p>

<p>Regards</p>

<p>HJ</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Henry Jean (henryjean) on 2009-05-11T02:40:29.000+0000</p> 
        <div class="body">
            <p>Sorry, not a bug.
The getFrom() returns the from correctly. 'name '. The browser just don't show the email because it's between &lt; and &gt;.
It would be nice to have separate functions to retrieve the sender email and the sender name.</p>

<p>Regards</p>

<p>HJ</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-05T00:14:29.000+0000</p> 
        <div class="body">
            <p>I changed a summary to make it easier to understand.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:43.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

