<h2>ZF-6714: Zend_Decorator not exists.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-05-18T08:25:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T15:54:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Document
<a href="http://framework.zend.com/svn/framework/standard/trunk/documentation/manual/en/module_specs/Zend_Form-Decorators.xml">http://framework.zend.com/svn/framework/…</a></p>

<p>Missing! "Zend_Form".
Zend_Decorator_Interface &amp; Zend_Decorator_Abstract not exsits.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-20T06:49:19.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r15644</p>

        </div>
    </div>
    </div>

