<h2>ZF-6086: Bogus formatter given to Zend/Log/Writer/Abstract.php should throw an exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-22T01:48:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-22T17:54:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6085">ZF-6085</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If I give a bogus formatter to a writer, the formatter is accepted silently.</p>

<p>If I try to use the writer, a fatal error (eg "Fatal error: Call to a member function format() on a non-object in /usr/share/php5/Zend/Log/Writer/Stream.php on line 93") is outputted.</p>

<p>I think that the fatal error should be avoided and an exception should be thrown when the bogus formatter is set.</p>

<p>Regards,
HUjuice</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Martin de Keijzer (martin1982) on 2009-03-22T16:00:51.000+0000</p> 
        <div class="body">
            <p>2 identical issues logged</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-03-22T17:54:16.000+0000</p> 
        <div class="body">
            <p>This issue is a duplicate. Closing.</p>

        </div>
    </div>
    </div>

