<h2>ZF-6289: Zend_Config_Writer_Ini jumbling sections</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-13T15:19:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-08-21T07:00:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.8 (25/Aug/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Karl Pierce (fish3046)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config_Writer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10095">ZF-10095</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The issue is with Zend_Config_Writer_Ini.  When you build a Zend_Config object and add data elements to it, the writer writes them out to the file in the order they were added.  This creates problems when you add sections, then add more root level data to the config afterwards.  For example, creating an object like this:
        $schema = new Zend_Config(array(
            'menuName'          =&gt; $this-&gt;menuName,
            'tableName'         =&gt; $this-&gt;tableName,
            'fields'                =&gt; array(),
            'type'              =&gt; $this-&gt;type,
            'order'             =&gt; $this-&gt;order
        ), true);
The fields section is build later (i have the code available but i don't think it matters) but the basic idea is to have a [fields] section with various elements beneath it.  When Zend_Config_Writer_Ini writes this out to the file, it will print out like this:</p>

<p>menuName = "Multi Record"
tableName = "multi_record"
[fields]
data = "data"</p>

<p>type = "multi"
order = 1</p>

<p>This puts <code>type</code> and <code>order</code> under the [fields] section, when it should be up next to tableName and menuName, which is under the root section.  I feel the solution would be to process seperate sections last, so all root keys are not written at the bottom like this changing their context.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2010-04-25T01:09:34.000+0000</p> 
        <div class="body">
            <p>Fixed in r21983.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2010-06-02T11:42:57.000+0000</p> 
        <div class="body">
            <p>Jan,</p>

<p>You've marked this as fixed in 1.10.4, but it doesn't seem to have been merged from trunk to the branch?</p>

<p>Is there a reason it wasn't merged?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2010-06-02T23:43:55.000+0000</p> 
        <div class="body">
            <p>I only commited my changes to trunk but there shouldn't be any problems to not merge them to the mentioned branch or a newer one.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-08-21T07:00:20.000+0000</p> 
        <div class="body">
            <p>Applied to branch release-1.10 in r22869.</p>

        </div>
    </div>
    </div>

