<h2>ZF-6185: Zend_Db missing an implementation of PDO::exec()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-02T00:51:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-27T11:43:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11851/patch-zend-db-adapter-abstract.txt">patch-zend-db-adapter-abstract.txt</a></li>
            <li><a href="/issues/secure/attachment/11852/test-zend-db-adapter-test-common.txt">test-zend-db-adapter-test-common.txt</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This prevents Zend_Db from being a drop in replacement for PDO applications.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Lukas Smith (lsmith) on 2009-04-02T00:53:18.000+0000</p> 
        <div class="body">
            <p>see <a href="http://php.net/manual/en/pdo.exec.php">http://php.net/manual/en/pdo.exec.php</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Silvan Zurbruegg (silvan) on 2009-04-02T01:35:12.000+0000</p> 
        <div class="body">
            <p>patch for Zend/Db/Adapter/Abstract.php.</p>

<p>contains missing function exec()</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Silvan Zurbruegg (silvan) on 2009-04-02T01:36:05.000+0000</p> 
        <div class="body">
            <p>unittests for /Zend/Db/Adapter/TestCommon.php</p>

<p>unittests for exec() method.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-04-17T00:43:01.000+0000</p> 
        <div class="body">
            <p>Just for my information, why don't you want to use the query() method? (except to retrieve number of rows)</p>

<p>With you proposition, there is also no profiling.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lukas Smith (lsmith) on 2009-04-17T01:24:01.000+0000</p> 
        <div class="body">
            <p>Two reasons:
1) for certain queries you dont need a result set and therefore creating the statement instance is needless overhead
2) exec() returns the number of affected rows, that I would have to get with another method call if I were to use query()</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lukas Smith (lsmith) on 2009-04-17T01:26:19.000+0000</p> 
        <div class="body">
            <p>Also semantically it is important to know that this is not a select query, for example if one would want to run an explain automatically. These are also usually not the type of queries that need profiling and if they do .. though I invite you to add profiling support.</p>

<p>Finally the lack of the exec() method prevents Zend_Db to work as a drop in replacement for PDO projects.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-04-17T03:59:08.000+0000</p> 
        <div class="body">
            <p>Thanks Lukas.</p>

<p>Ralph, I can apply the patch and test it against all PDO adapters with limitation mentions above =&gt; no profiling.</p>

<p>Your opinion?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-04-26T18:57:08.000+0000</p> 
        <div class="body">
            <p>Patch applied to trunk and 1.8 release branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-04-27T11:42:19.000+0000</p> 
        <div class="body">
            <p>Modified in SVN15204</p>

<p>Tested with all adapters:</p>

<pre class="highlight"><code>
PHPUnit 3.3.15 by Sebastian Bergmann.

Zend Framework - Zend_Db
 Zend_Db_Adapter_Pdo_MssqlTest
 ...

 Zend_Db_Adapter_Pdo_MysqlTest
 ...

 Zend_Db_Adapter_Pdo_OciTest
 ...

 Zend_Db_Adapter_Pdo_PgsqlTest
 ..F

 Zend_Db_Adapter_Pdo_SqliteTest
 ...

Time: 10 seconds

There was 1 failure:

1) testAdapterExecModifiedNone(Zend_Db_Adapter_Pdo_PgsqlTest)
Expected exec() to return zero affected rows; got 1
Failed asserting that &lt;&lt;&lt;</code></pre><p></p>
        </div>
    </div>
    </div>

