<h2>ZF-6215: Code coverage of Zend_ProgressBar_Adapter_Console is to low</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-04-05T09:10:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-05T09:22:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_ProgressBar</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11859/ZF-6215.diff">ZF-6215.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Code coverage of Zend_ProgressBar_Adapter_Console is to low</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Diego Tremper (diegotremper) on 2009-04-05T09:12:38.000+0000</p> 
        <div class="body">
            <p>I create a patch for this issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-04-05T09:22:50.000+0000</p> 
        <div class="body">
            <p>Thanks for the patch.</p>

        </div>
    </div>
    </div>

