<h2>ZF-6614: Zend_Feed_Rss pubDate should be localtime rather than gmdate('r')</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-11T19:02:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-18T11:32:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                twk (twk)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>zend/feed/rss.php line 425 and other places makes pubDate like the following.
            $pubdate = $this-&gt;_element-&gt;createElement('pubDate', gmdate('r', $pubdate));
This always generates timzone +0000 like "Tue, 12 May 2009 02:01:07 +0000".</p>

<p>I think the feed should generate in local timezone.</p>

<p>Something like 
$pubdate = new Zend_Date($pubdate);
$pubdate = $this-&gt;_element-&gt;createElement('pubDate', $pubdate-&gt;get(Zend_Date::RSS));
would generate in local time zone.  (though this adds dependency to Zend_Date)</p>

<p>I do not know about the atom class, but the same issue may exist.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by twk (twk) on 2009-05-11T19:08:40.000+0000</p> 
        <div class="body">
            <p>atom uses date(DATE_ATOM) and it shows in the local timezone.
so you may just use date(DATE_RSS) for rss?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-09-18T11:32:55.000+0000</p> 
        <div class="body">
            <p>Fixed in r18265</p>

        </div>
    </div>
    </div>

