<h2>ZF-6315: Add flag to describe Instance to have it ignore terminated instances.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-04-16T05:36:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-18T13:25:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon_Ec2</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add a boolean flag to the describe method in the instance class that will allow the user to ignore terminated instances when they describe instances.</p>

<p>This it will default to false.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-04-18T13:25:14.000+0000</p> 
        <div class="body">
            <p>This was fixed with r14990</p>

        </div>
    </div>
    </div>

