<h2>ZF-6636: Lucene Search doesn't find keyword indexed fields</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-13T09:33:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-05T02:35:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mickael Bailly (dready92)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-2982">ZF-2982</a></li>
            <li><a href="/issues/browse/ZF-623">ZF-623</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend Search Lucene doesn't seem to search in keyword fields with the find method ?</p>

<p>To reproduce :</p>

<p>$index = Zend_Search_Lucene::create('testing');
$lucene_doc = new Zend_Search_Lucene_Document();
$lucene_doc-&gt;addField(Zend_Search_Lucene_Field::Keyword('_id', 'doc1'));
$index-&gt;addDocument($lucene_doc);
$index-&gt;commit();</p>

<p>$hits = $index-&gt;find('doc1');</p>

<p>echo count($hits)." result(s)\n"; // echoes "0 result(s)"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Hendra Christian (hendrachristian) on 2009-10-29T17:58:10.000+0000</p> 
        <div class="body">
            <p>I have a slightly different problem. When I index with keyword, I can do a search but it's case sensitive. The others (text, unStored) works fine (case insensitive).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hendra Christian (hendrachristian) on 2009-10-29T18:24:49.000+0000</p> 
        <div class="body">
            <p>I'm sorry, ignore my message above. I was using 1.9.3PL where it happened, it seems to be working fine when I upgraded to 1.9.5.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hendra Christian (hendrachristian) on 2009-10-29T18:31:45.000+0000</p> 
        <div class="body">
            <p>My bad! It is still happening. Was looking at the wrong file just now. Terribly sorry for the unnecessary post above.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-05T02:35:50.000+0000</p> 
        <div class="body">
            <p>This issue is very old.  It would be difficult, at this late stage in ZFv1's lifecycle, to fix this adequately without introducing a backwards-compatibilty break.</p>

        </div>
    </div>
    </div>

