<h2>ZF-6383: limit raised on preg_replace when using javascriptCaptureStart/javascriptCaptureEnd on a long script</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-22T09:38:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-18T09:44:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Guillaume ORIOL (goriol)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I discovered an issue when using the javascriptCaptureStart/javascriptCaptureEnd function pair on a captured exceeding a certain limit (about 50KB in my case). The function returns only a semi-colon.</p>

<p>I have the following code in a view script:
&lt;?php $this-&gt;dojo()-&gt;javascriptCaptureStart(); ?&gt;
 var data = &lt;?php echo $this-&gt;data; ?&gt;;
 ...
&lt;?php $this-&gt;dojo()-&gt;javascriptCaptureEnd(); ?&gt;</p>

<p>And, as the number of rows in my database table is growing, $this-&gt;data is getting bigger and bigger. Finally, over ~50KB, the PHP tag pair is replaced by a semi-colon and nothing else (not even the "var data =" preceeding that tag). I was able to trace this issue back to the function addJavascript($js) in Zend_Dojo_View_Helper_Dojo_Container and more precisely to the preg_replace function:</p>

<p>If you look closely to the regexp, you'll see a question mark following ".<em>" in parenthesis.
On my server:
$a = str_repeat('a', 49997);
$a = preg_replace('/^\s</em>(.<em>?)\s</em>$/s', '$1', $a);
would return the string but:
$a = str_repeat('a', 49998);
$a = preg_replace('/^\s<em>(.</em>?)\s*$/s', '$1', $a);
would return NULL.
If I remove the question mark, preg_replace operates properly, whatever size the string is.</p>

<p>Eric Coleman said it could be solved by a configuration directive:
<a href="http://us.php.net/manual/en/pcre.configuration.php">http://us.php.net/manual/en/pcre.configuration.php</a></p>

<p>Could it be those 2 configurable limits causing the problems?  We had
some problems here a while back with hitting the backtrack limit which
was causing weird behaviour, perhaps your running into the same
issues.</p>

<p>Matthew Weier O'Phinney suggested the following solution:</p>

<pre><code>if (preg_match('/^(\s+)/', $a, $matches)) {
    $a = substr($a, strlen($matches[1]));
}
if (preg_match('/(\s+)$/', $a, $matches)) {
    $a = substr($a, 0, strlen($a) - strlen($matches[1]));
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2011-02-18T09:44:09.000+0000</p> 
        <div class="body">
            <p>Please reopen if I am wrong, but if you are hitting limits set by PHP, then you should raise those limits or find an alternative route to express large amounts of data.  If your dataset groups, perhaps it should be loaded through a separate request (ajax), in chunks.</p>

        </div>
    </div>
    </div>

