<h2>ZF-6554: need to make forward to an existing email</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-06T03:27:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-07T12:27:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi people.</p>

<p>It will be very nice to be able to make forward to an existing email.
This will prevent lot of work and bugs like: what will happen if you have an html but set it text? what will happen if you have attachments or is multipart and other.</p>

<p>I searched for this but didnt found anything so please forgive me if this request or feature exists already.
Is first time I came here :).</p>

<p>How I see it now:</p>

<pre class="highlight"><code>
//take an existing email
$oldMail = new Zend_Mail_Storage_Imap();

//make new Zend_Mail that can accept a Zend_Mail_Storage_xx object
$mail = new Zend_Mail($oldMail);

//set new to
$mail-&gt;addTo($oneEmail);

//send
$mail-&gt;send();
</code></pre>

<p>greets,
Alex</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michael Kliewe (mkliewe) on 2009-05-06T08:28:23.000+0000</p> 
        <div class="body">
            <p>This would be very nice. I also have a project where I need to forward a mail (from imap storage).</p>

<p>Because it is not possible with ZF, I have to do it with PEAR.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-06-09T00:20:06.000+0000</p> 
        <div class="body">
            <p>Sorry, I have been inactive since last April.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by John Kelly (postalservice14) on 2010-12-02T15:43:13.000+0000</p> 
        <div class="body">
            <p>As a short term solution, would object cloning work? [<a href="http://php.net/manual/en/language.oop5.cloning.php">http://php.net/manual/en/language.oop5.cloning.php</a>]</p>

<pre class="highlight"><code>
$mail = clone $oldMail;
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michael Kliewe (mkliewe) on 2010-12-02T23:56:47.000+0000</p> 
        <div class="body">
            <p>The problem is when reading a mail from an IMAP server you get a Zend_Mail_Message object, but for sending a mail you need a Zend_Mail object. And there is no easy convert function for that.</p>

<p>Perhaps the problem is now a bit more clear.</p>

        </div>
    </div>
    </div>

