<h2>ZF-640: checking if class exists tries to load class if defined autoload</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-12-12T13:19:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>File: Zend/Controller/Dispatcher.php
line: 542</p>

<p>if (class_exists($class)) {
  return true;
}</p>

<p>should only test without autoloading if autoload is defined, because class loading is implemented below checking</p>

<p>if (class_exists($class, false)) {
  return true;
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-12-12T13:28:41.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 2267</p>

        </div>
    </div>
    </div>

