<h2>ZF-6944: Zend_Mail does not always set the mandatory MIME-Version mail-header field</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-07T08:44:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-04T01:51:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When sending Mime-Email the mandatory header file MIME-Version is not always set.</p>

<p>Example to reproduce the error:</p>

<pre class="highlight"><code>
  $mail = new Zend_Mail();
  $mail-&gt;setFrom('xxxx@xxxx.de', 'Tester');
  $mail-&gt;addTo('xxxx@xxxx.de');
  $mail-&gt;setSubject('testmail');
  $mail-&gt;setBodyText('Test Test äöü ','ISO-8859-1','quoted-printable');
  $transp = new Zend_Mail_Transport_Smtp('xxxx.xxx.de');
  $mail-&gt;send($transp);
</code></pre>

<p>Remarks: In Body text there are german umlauts (Real-names are replaced by xx)</p>

<p>When looking at the generated Mail, it is lacking the header field:</p>

<p>MIME-Version: 1.0</p>

<p>The error could be corrected in File Zend/Mail/Transport/Abstract.php in function _getHeaders($boundary) with adding the following code:</p>

<pre class="highlight"><code>
else $this-&gt;_headers['MIME-Version'] = array('1.0');
</code></pre>

<p>just befor the return $this-&gt;_headers; at the end of the function.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-06-07T19:06:38.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r15933</p>

        </div>
    </div>
    </div>

