<h2>ZF-6527: Enable the Zend_Rest_Server's namespace support</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-05-04T18:58:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-05T05:28:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Due to the consistency between Zend_Xmlrpc_Server and Zend_Rest_Server.
I simply added the namespace support in Zend_Rest_Server.</p>

<pre class="highlight"><code>
public function setClass($classname, $namespace = '', $argv = array())
{
    $this-&gt;_args = $argv;
    foreach ($this-&gt;_reflection-&gt;reflectClass($classname, $argv)-&gt;getMethods() as $method) {
        $this-&gt;_functions[$namespace.".".$method-&gt;getName()] = $method;
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-05T05:28:39.000+0000</p> 
        <div class="body">
            <p>Actually, we plan to deprecate Zend_Rest_Server in favor of an MVC-based solution, and are accepting no new features to it at this time.</p>

        </div>
    </div>
    </div>

