<h2>ZF-6626: Additions to Zend_Db_Table</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-12T14:33:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-13T12:35:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                -.- (campasau)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3399">ZF-3399</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <ol><li>It would be nice if you can get the name of the Zend_Db_Table.</li>
<li>As mentioned <a href="http://framework.zend.com/issues/browse/ZF-3399">before</a> it would be nice if you can specify a $_selectClass in Zend_Db_Table</li>
</ol><pre class="highlight"><code>
    protected $_selectClass = 'Zend_Db_Table_Select';
    
    /**
     * Returns the name of the table.
     * 
     * @return string
     */
    public function getName()
    {
        return $this-&gt;_name;
    }
    
    /**
     * Returns an instance of a Zend_Db_Table_Select object.
     *
     * @return Zend_Db_Table_Select
     */
    public function select()
    {
        @Zend_Loader::loadClass($this-&gt;_selectClass);
        return new $this-&gt;_selectClass($this);
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-05-13T12:35:18.000+0000</p> 
        <div class="body">
            <p>Use $table-&gt;info(Zend_Db_Table_Abstract::NAME) that mainly acts as a "catch-all getter"</p>

        </div>
    </div>
    </div>

