<h2>ZF-6540: Zend_Serivce_Amazon_S3 should urlencode the filename/objectname before using it</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-05T08:20:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-08T13:58:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gianluca Sforna (giallu)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Right now the Amazon S3 component is not able to work on filenames/objectnames containing chars unsuitable for URL. A small test case:</p>

<p>include "Zend/Service/Amazon/S3.php";
$zend = new Zend_Service_Amazon_S3(key1,key2);
$zend-&gt;putObject( "giallutest/this is a test", "HELLO WORLD!" );</p>

<p>fails with:
PHP Fatal error:  Uncaught exception 'Zend_Uri_Exception' with message 'Invalid URI supplied' in /home/giallu/Desktop/zend/ZendFramework-1.8.0-minimal/library/Zend/Uri/Http.php:156</p>

<p>The solution to this problem, as noted in:
<a href="http://developer.amazonwebservices.com/connect/thread.jspa?threadID=15787&amp;tstart=45">http://developer.amazonwebservices.com/connect/…</a>
is to always urlencode() the object name.</p>

<p>Please also note the Zend_Serivce_Amazon_S3 component is missing from this tracker...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-05T08:50:33.000+0000</p> 
        <div class="body">
            <p>Assigning to Stas</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-05-08T13:58:36.000+0000</p> 
        <div class="body">
            <p>fixed, thanks</p>

        </div>
    </div>
    </div>

