<h2>ZF-6824: if the user is not using a route paramater named action active pages dont register correctly.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-27T05:54:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-19T08:13:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Josh Ribakoff (jshpro2)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Robin Skoglund (robinsk)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6823">ZF-6823</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you define a route with a module + controller, zend_navigation_page_mvc cant recognize it as active. For instance if you create a  route with module Foo and controller Bar, and then create a page with that module + controller it won't register in active breadcrumbs. If I <em>do</em> specify the default action parameter of index then it does work correctly. Trivial but a user may not be using a route param called action</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-27T06:01:14.000+0000</p> 
        <div class="body">
            <p>This is a known issue with the routing subsystem, and is documented in the manual: <a href="http://framework.zend.com/manual/en/zend.navigation.pages.html#zend.navigation.pages.mvc.example.routes">http://framework.zend.com/manual/en/…</a></p>

<p>It will be fixed in ZF 2.0 :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-27T06:02:13.000+0000</p> 
        <div class="body">
            <p>Related to the routing/navigation.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (jshpro2) on 2009-05-27T06:07:51.000+0000</p> 
        <div class="body">
            <p>Yeah I saw that, if the module + controller match, that should be 2/2 matched paramaters though. If there is no paramater named "action" for this route. Not sure if thats the same thing</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-09-19T07:02:12.000+0000</p> 
        <div class="body">
            <p>Routing in ZF always resolves to a module, controller, <em>and</em> action. If a page/route does not contain any information on 'action', Zend_Navigation_Page_Mvc will not make any assumptions. This is a strict approach, used to prevent false positives (which would occur more frequently than the case is in this issue).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (jshpro2) on 2009-09-19T08:13:37.000+0000</p> 
        <div class="body">
            <p>Hey Robin,</p>

<p>I meant more if the user had overridden the routing subsystem and their paradigm did not contain controller module or action ( for instance the Magento codebase completely overrode that subsystem ). I agree it may not be within the scope of the component though, thanks for following up.</p>

<p>Josh</p>

        </div>
    </div>
    </div>

