<h2>ZF-6493: ZendX_JQuery UI CDN URL Incorrect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-01T14:22:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-02T00:46:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using the ZendX_JQuery View Helper to include the JQuery UI JavaScript files from the Google CDN, an incorrect URL is returned.</p>

<p><a href="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery-ui.min.js">http://ajax.googleapis.com/ajax/libs/…</a></p>

<p>Is given as the output where as the actual location of the jquery-ui.min.js file is in the jqueryui folder (example below):</p>

<p><a href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.1/jquery-ui.min.js">http://ajax.googleapis.com/ajax/libs/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stefan Gehrig (sgehrig) on 2009-05-02T00:46:12.000+0000</p> 
        <div class="body">
            <p>Duplicate of ZF-6373 (<a href="http://framework.zend.com/issues/browse/ZF-6373">http://framework.zend.com/issues/browse/ZF-6373</a>)</p>

        </div>
    </div>
    </div>

