<h2>ZF-6782: use of Zend_Locale in Zend_Translate</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-22T09:34:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-22T10:13:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ionut Dinu (tunder)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Translate()-&gt;setLocale('en_US')-&gt;translate('something')</p>

<p>is not equal with</p>

<p>Zend_Translate()-&gt;setLocale('en')-&gt;translate('something')</p>

<p>if, let's say, I want to define ONLY 'en' or 'en_US', which, in my opinion, is the same.</p>

<p>To have Zend_Translate understand both locales, I have to duplicate the translations for both locales. This is not an option in case of large translations files on large projects.</p>

<p>Suggestion: use only the language part of the locale or, even better, if the locale have an exact match in the translation arrays use it, else use only the language part of locale.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-22T10:13:00.000+0000</p> 
        <div class="body">
            <p>Of course they are not equal.</p>

<p>You have to keep in mind that languages differ per region.
Brittish english is not american english.</p>

<p>And many bigger sites support both.</p>

<p>So simple as is:
When you support only one english dialect use "en".
But when you also support other dialects then use full locales.</p>

<p>Note:
According to the manual the locale "en_US" is automatically degraded to "en" when "en_US" is not available.
This is no fault, this is expected I18N behaviour and not ZF specific.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-22T10:13:58.000+0000</p> 
        <div class="body">
            <p>Closing as non-issue.
Please read the manual for details about how I18N works with translation and degrading.</p>

        </div>
    </div>
    </div>

