<h2>ZF-6903: function with protected-like name declared public</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2009-06-04T11:14:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T09:29:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Remy Damour (remy215)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Udo Telaar (udo)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12400/fix_ZF-6903.diff">fix_ZF-6903.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>It's probably just a typo, in Zend_Dojo_View_Helper_Dijit, method <em>Zend_Dojo_View_Helper_Dijit:_createFormElement()</em> is declared public when its name suggests it's protected/private.</p>

<p>Regards,
Remy</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-20T09:29:36.000+0000</p> 
        <div class="body">
            <p>This is because it's meant to be public, but not intended for general consumption; it is used by a number of the various dijit helpers in order to create the markup, but in most cases only used internally.</p>

        </div>
    </div>
    </div>

