<h2>ZF-6049: Bug with 'literal' style not being importable from WSImport</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-17T11:43:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-30T15:50:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Soap_Wsdl</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6349">ZF-6349</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following issue came up on the mailing list:</p>

<p>Hello,</p>

<p>I have been trying to generate a java client to a soap service that is
built with zf. The wsdl file is generated with Zend_Soap_AutoDiscover
but I am not able to create the java client. Attached is the a dummy
service and the code that creates the wsdl file. Im trying to create
my java client using wsimport from jaxws.
<a href="https://jax-ws.dev.java.net/jax-ws-ea3/docs/wsimport.html">https://jax-ws.dev.java.net/jax-ws-ea3/docs/…</a>.</p>

<p>Any other suggestions and or experiences on how to best create a java
client for a zf soap service is welcome.</p>

<p>This is the error I get.</p>

<p>sh wsimport.sh <a href="http://localhost/soap/?wsdl">http://localhost/soap/?wsdl</a>
[ERROR] Invalid wsdl:operation "method1": its a document-literal
operation,  message part must refer to a schema element declaration
  line 2 of <a href="http://localhost/soap/?wsdl">http://localhost/soap/?wsdl</a></p>

<p>I tried to patch the Zend_Soap_Wsdl to use literal according to this
thread <a href="http://www.nabble.com/Problems-generating-WebService-client-from-WSDL-with-WSImport-td18614100.html">http://nabble.com/Problems-generating-WebService-c…</a>
but then of course I have to provide a schema for my operations. My
patch is pretty stupid but available here if anyone interested,
<a href="http://gist.github.com/80610">http://gist.github.com/80610</a></p>

<p>When that patch applied I get the following error instead. Which seems
to indicate that the wsdl file is correct if I am not mistaken.</p>

<p>$ sh wsimport.sh <a href="http://localhost/soap/?wsdl">http://localhost/soap/?wsdl</a>
[ERROR] Schema descriptor {<a href="http://localhost/soap/%7Dmethod1Request">http://localhost/soap/}method1Request</a> in
message part "inputParam" is not defined and could not be bound to
Java. Perhaps the schema descriptor
{<a href="http://localhost/soap/%7Dmethod1Request">http://localhost/soap/}method1Request</a> is not defined in the schema
imported/included in the WSDL. You can either add such
imports/includes or run wsimport and provide the schema location using
-b switch.
  line 2 of <a href="http://localhost/soap/?wsdl">http://localhost/soap/?wsdl</a></p>

<p>My test code, also available here if it is broken below.
<a href="http://gist.github.com/80612">http://gist.github.com/80612</a></p>

<pre class="highlight"><code>
&lt;?php
require_once "Zend/Loader.php";
Zend_Loader::registerAutoload();

class MyClass {
    /**
     * This method takes ...
     *
     * @param integer $inputParam
     * @return string
     */
    public function method1($inputParam) {
        return rand(1,10);
    }
}

if(isset($_GET['wsdl'])) {
    $autodiscover = new Zend_Soap_AutoDiscover();
    $autodiscover-&gt;setBindingStyle(
                    array('style' =&gt; 'document',
                          'transport' =&gt; '<a href="http://schemas.xmlsoap.org/soap/http">http://schemas.xmlsoap.org/soap/http</a>')
                );
    $autodiscover-&gt;setOperationBodyStyle(
                  array('use' =&gt; 'literal')
                );

    $autodiscover-&gt;setClass('MyClass');
    $autodiscover-&gt;handle();
} else if (isset($_GET['client'])) {
    $client = new Zend_Soap_Client("http://localhost/soap/?wsdl");
    echo $client-&gt;method1(10);
} else {
    $soap = new Zend_Soap_Server("http://localhost/soap/?wsdl");
    $soap-&gt;setClass('MyClass');
    $soap-&gt;handle();
}</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-05-30T15:50:28.000+0000</p> 
        <div class="body">
            <p>This is a duplicate.</p>

        </div>
    </div>
    </div>

