<h2>ZF-6382: Create UTF-8 validator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-04-22T09:00:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-13T12:00:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I would like to suggest to create and supply within Zend_Validate an UTF-8 validator. This validator should asserts the data passed is valid UTF-8 string.</p>

<p>Invalid user-supplied UTF-8 strings could results to a major security issues. Please, take a look into <a href="http://code.google.com/docreader/#p=doctype&amp;s=doctype&amp;t=ArticleMalformedUtf8">http://code.google.com/docreader/…</a> for additional information.</p>

<p>Thank you.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-13T12:00:56.000+0000</p> 
        <div class="body">
            <p>The provided usecase should be fixed by this proposal:
<a href="http://framework.zend.com/wiki/display/ZFPROP/Zend_Filter_Html+-+Thomas+Weidner">http://framework.zend.com/wiki/display/…</a></p>

<p>Closing as "needs proposal"</p>

        </div>
    </div>
    </div>

