<h2>ZF-6750: RecursiveFilterIterator.php extension</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-20T11:16:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-21T07:18:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend/Tool/Framework/Loader/IncludePathLoader/RecursiveFilterIterator.php0000664 should be Zend/Tool/Framework/Loader/IncludePathLoader/RecursiveFilterIterator.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-05-21T06:27:44.000+0000</p> 
        <div class="body">
            <p>Sounds as if you might have local svn issues?  Perhaps you have a conflict in files somewhere, maybe you edited it?</p>

<p>I cannot seems to find what you are describing</p>

<pre class="highlight"><code>
~/tmp/tmpsvn$ svn co <a href="http://framework.zend.com/svn/framework/standard/tags/release-1.8.1/library/Zend/Tool/Framework/Loader/IncludePathLoader/">http://framework.zend.com/svn/framework/…</a> ipl-tag
A    ipl-tag/RecursiveFilterIterator.php
Checked out revision 15665.
~/tmp/tmpsvn$ svn co <a href="http://framework.zend.com/svn/framework/standard/trunk/library/Zend/Tool/Framework/Loader/IncludePathLoader/">http://framework.zend.com/svn/framework/…</a> ipl-trunk
A    ipl-trunk/RecursiveFilterIterator.php
Checked out revision 15665.
~/tmp/tmpsvn$ svn co <a href="http://framework.zend.com/svn/framework/standard/branches/release-1.8/library/Zend/Tool/Framework/Loader/IncludePathLoader/">http://framework.zend.com/svn/framework/…</a> ipl-release
A    ipl-release/RecursiveFilterIterator.php
Checked out revision 15665.
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Davor Bagaric (kangarooit) on 2009-05-21T07:18:12.000+0000</p> 
        <div class="body">
            <p>Sorry, archive manager created that bug.
I apologize.</p>

        </div>
    </div>
    </div>

