<h2>ZF-6598: Zend_Application_Resource_Session break Zend_Session</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-10T11:22:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-12T08:08:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When unused option are set for Zend_Session, Zend_Session throw an exeption.</p>

<p>On the last trunk version of Zend_Application_Resource_Session, the boostrap object as been added to the options then break Zend_Session because it doesnt accept the boostrap object.</p>

<p>I must add this to fix the problem in the init() method of Zend_Application_Resource_Session before Zend_Session::setOptions($options); :</p>

<p>if (isset($options['bootstrap'])) {
    unset($options['bootstrap']);
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-12T08:08:13.000+0000</p> 
        <div class="body">
            <p>setOptions now no longer merges the "bootstrap" option.</p>

        </div>
    </div>
    </div>

