<h2>ZF-6674: automatic start of Zend_Application_Resource_Modules</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-05-15T06:25:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-21T11:39:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think it would be more suitable, when the module resource loader (Zend_Application_Resource_Modules) would be launched automaticly when there are more modules defined then the default module.
I could not imagine whats the benefit is to triger this behavior explicitly by e.g. "resources.modules[] = " in the application config.
Maybe it makes more sense to suppress this feature by a config directive if its undesired.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-15T07:02:59.000+0000</p> 
        <div class="body">
            <p>The module resource loader is initialized by Zend_Application_Module_Bootstrap -- and you need to define a bootstrap for each module you define. However, this is an opt-in situation -- if you need bootstrapping for that module, you add it, but if you don't, then you don't.</p>

<p>While I can see your point about doing this automatically, many developers prefer to opt-in to behavior rather than opt out. I'd prefer to see some discussion on this point on list.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Adler (madler) on 2009-05-15T13:15:54.000+0000</p> 
        <div class="body">
            <p>I have to apologize for the unfortunate formulated request.</p>

<p>I meant the resource plugin Zend_Application_Resource_Modules that initializes available module bootstraps.</p>

<p>As you wrote above the opt-in functionality is to provide a bootstrap for a module or not and this is the way that I also prefer.
But in my opinion, the module bootstrap loader (Zend_Application_Resource_Modules) itself should be loaded automatically.
This is currently not the case. The module bootstrap loader have to be invoked by "resources.modules[] = " in the application config or somehow else.
I hope I didn't spread more confusion this time :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-08-21T11:39:22.000+0000</p> 
        <div class="body">
            <p>Not all ZF applications are modular (I'd venture to guess most aren't, but I'd gladly be proven wrong); modular functionality is completely optional, and a consideration for each individual project to decide. Additionally, all resource plugins shipped with ZF are opt-in only by design. We will not enable this by default at this time.</p>

        </div>
    </div>
    </div>

