<h2>ZF-646: Write Zend_XmlRpc_Client Docs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2006-12-13T12:42:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T18:50:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mike Naberezny (mike)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_XmlRpc_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Please write docbook manual documentation for the Zend_XmlRpc_Client component.</p>

<p>This is task-oriented end-user documentation for usage of the component.  It should be consistent with the style of the rest of our docbook manual for other components.  It should cover the range of functionality of the component, as accessible from an application developer.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mike Naberezny (mike) on 2006-12-16T06:55:26.000+0000</p> 
        <div class="body">
            <p>Changeset 2399</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T18:50:18.000+0000</p> 
        <div class="body">
            <p>Changing to comply with new IT coventions for components.</p>

        </div>
    </div>
    </div>

