<h2>ZF-6217: Dojo 1.3.0 is aviable...</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-04-05T22:47:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-01T06:20:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthias Sch. (matthias-sch)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>... and ready to include? ;-)
<a href="http://www.dojotoolkit.org/downloads">http://www.dojotoolkit.org/downloads</a></p>

<p>greetings</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthias Sch. (matthias-sch) on 2010-03-31T23:35:10.000+0000</p> 
        <div class="body">
            <p>could be closed ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-04-01T06:20:58.000+0000</p> 
        <div class="body">
            <p>Dojo 1.3.0 released with ZF in 1.8.0.</p>

        </div>
    </div>
    </div>

