<h2>ZF-6522: There is no way to pass models to viewHelpers</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-04T11:57:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-04T13:08:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Josh Ribakoff (jshpro2)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If I wanted to create a view helper for a form element, lets say a "tree selector" that has a variable # of dropdowns that update eachother with ajax, there is currently no hooks to do so. Different tree elements for instance would have a different "deepness" and some may need 2 dropdowns some may need 5. Currently there is no way to pass information to viewhelpers from the element class.</p>

<p>The user is stuck hacking their decorators to pass this information along to the helper ( such as ):
if( $element instanceof K12_Form_Element_Multitree )
        {
            return $element-&gt;getView()-&gt;$helper(
                $this-&gt;getName(),
                $element-&gt;getValue(),
                $attribs,
                $element-&gt;getTree() // the data I need my helper to see
            );
        }</p>

<p>This is an acceptable work-around unless you need to use the standard decorators with your elements.</p>

<p>My suggestion would be to have the viewHelper decorator by default either pass the element object to the form viewHelpers, so the helpers may "pull" the data they need off the elements, or some way for elements to "push" an ad-hoc array of custom parameters to the viewHelpers</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-04T11:59:53.000+0000</p> 
        <div class="body">
            <p>What do models have got to do with this?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (jshpro2) on 2009-05-04T12:07:26.000+0000</p> 
        <div class="body">
            <p>I am trying to create a custom tree input element. I will re-use this to collect various tree form data throughout an application. Some trees only have 2 levels ( country -&gt; state ). Some may have many levels. There is no way to create a viewHelper for this without creating one for each depth level I would need, or hacking the decorators ( which prevents users of my input element from using standard decorators ).</p>

<p>Replace the word "model" with "integer representing how many levels deep the helper should render" ( although other users of the component may wish to pass something other than an integer for this purpose. ) My solution would be to apply preserve whole object and pass the whole element object in the viewHelper decorator. ( why can't elements be considered models? )</p>

<p>In this case I only need to pass an extra integer and cannot. Since it is a framework though many users may need to pass something other than an integer, such as an array of configuration options, or their model.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (jshpro2) on 2009-05-04T12:09:27.000+0000</p> 
        <div class="body">
            <p>Forgot to mention you can just use the elementOptions paramater but then other various methods stomp on your data if it is not an array in the proper format. Perhaps the recommended course of action would be to override said methods, I'm just making a suggestion to make the component more flexible than that though.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-04T12:10:36.000+0000</p> 
        <div class="body">
            <p>There are ways to do this already.</p>

<p>First, you can grab a helper instance from the view:</p>

<pre class="highlight"><code>
$helper = $view-&gt;getHelper('HelperName');
$helper-&gt;setModel($model);
</code></pre>

<p>Second, you can construct your helper such that passing no arguments to it will return an instance of itself (this is a technique used widely in the standard helpers shipped in ZF):</p>

<pre class="highlight"><code>
class My_View_Helper_Foo extends Zend_View_Helper_Abstract
{
    public function foo($value = null)
    {
        if (0 == func_num_args()) {
            return $this;
        }
        // ...
    }
}

$this-&gt;foo()-&gt;setModel($this-&gt;model);
</code></pre>

<p>Either way, it's trivial to do already with current functionality.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (jshpro2) on 2009-05-04T12:24:06.000+0000</p> 
        <div class="body">
            <h1>1 it looks like $this-&gt;_view is NULL until a certain time ( when form is actually assigned to view? )</h1>

<h1>2 Perhaps I am mistaken, but that would be static state. If I had 2 elements right after another they'd stomp on eachother's values. I would have to create a concrete subclass for each helper since the viewHelper architecture holds onto a singleton instance. My suggestion was intended to remove the need for concrete subclasses, allowing developers to abstract this</h1>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-04T12:59:44.000+0000</p> 
        <div class="body">
            <p>Regarding (1), yes, $_view is null until setView() is called (which typically happens at rendering time).</p>

<p>Regarding (2), state is shared, though it's not via a singleton. Zend_View maintains a per-instance registry of helpers and filters, and those objects are re-used on demand. However, if you are (a) writing a custom view helper, and (b) setting state and rendering directly from your decorator, there's no worries about collisions, as the calls are sequential.</p>

<p>As for modifying the behavior of the ViewHelper decorator, I see no reason to do so at this time. It was written to target the existing view helpers, none of which are aware of the actual element object they are rendering. It is the job of the decorator to choose which facets of the element need to be passed to the decorator -- in this regards, it's more like a <em>data mapper</em>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (jshpro2) on 2009-05-04T13:08:43.000+0000</p> 
        <div class="body">
            <p>Ok thank you so much for taking the time to address this, it really makes me glad I recommend the FW to other developers. Data Mapper hmmm? I'm working on one of those ( my code isnt that good though I'm still learning ).</p>

<p>I guess my point of contention was that I was reluctant to create a decorator for the element, because I followed the tutorial in the docs about making a composite decorator. I overrode createElement on Zend_Form to apply this decorator so I would not have to repeat the code setting up this decorator. I guess the best thing to do in my situation is go back to my if() statement in the decorator, I guess beggars can't be choosers and I understand now more where you're coming from.</p>

<p>Thanks for your advice though</p>

        </div>
    </div>
    </div>

