<h2>ZF-6202: Remoting Authentication support not present, should be added</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-04-03T00:32:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-05T11:07:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Flash player provides a way to pass authentication credentials through the AMF header (DSRemoteCredentials).
Zend AMF v1.7.5 does not reads this from the request and hence does not provide any support for remoting authentication.</p>

<p>The source code in Zend/Amf/Server.php contains the function:
protected function _handle(Zend_Amf_Request $request) which handles the request, this has a '@todo   implement AMF header authentication' comment on it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-06-05T11:07:43.000+0000</p> 
        <div class="body">
            <p>fix committed to trunk</p>

        </div>
    </div>
    </div>

