<h2>ZF-6037: setSalt on Zend_Form_Element_Hash doesn't work as expected</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-15T03:49:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Setting the salt after object construction will have no effect on the session namespace. The salt must be passed to the construct method as an option. If setting the salt manually afterwards the session name won't be updated.</p>

<p>A workaround which should work is to do this after setting the salt manually:</p>

<p>$hash-&gt;setSession(new Zend_Session_Namespace($hash-&gt;getSessionName()));
$hash-&gt;initCsrfToken();</p>

<p>I don't know if this is a desired behaviour. If not, perhaps adding the two calls above to the setSalt method would work.
Another method (which might work) would be to have the session created just before being output, eg. in the __toString method.</p>

<p>__toString() {</p>

<p>// setup sessions etc;
return parent::__toString();</p>

<p>}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by removed user (sandstrom) on 2009-03-15T03:50:07.000+0000</p> 
        <div class="body">
            <p>One could also make the setSalt method protected, thus forcing the to be passed to the construct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:12.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

