<h2>ZF-6694: Patch to load plugins with priority in Zend_Application_Resource_FrontController</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-05-17T07:32:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-29T19:12:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6704">ZF-6704</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently there is no option to configure the priority of front controller plugins loaded via Zend_Application_Resource_FrontController</p>

<p>The suppied patch, or a similar piece of code would allow the following config file options</p>

<pre class="literal">
resources.frontController.plugins.foo = "My_Plugin_Foo"
</pre>

<pre class="literal">
resources.frontController.plugins.foo.class = "My_Plugin_Foo"
resources.frontController.plugins.foo.priority = 99
</pre>

<pre class="highlight"><code>
diff --git a/ZendFramework/library/Zend/Application/Resource/Frontcontroller.php b/ZendFramework/library/Zend/Application/Resource/Frontcontroller.php
index 68ab8c1..5c237d3 100644
--- a/ZendFramework/library/Zend/Application/Resource/Frontcontroller.php
+++ b/ZendFramework/library/Zend/Application/Resource/Frontcontroller.php
@@ -87,8 +87,7 @@ class Zend_Application_Resource_Frontcontroller extends Zend_Application_Resourc
                     
                 case 'plugins':
                     foreach ((array) $value as $pluginClass) {
-                        $plugin = new $pluginClass();
-                        $front-&gt;registerPlugin($plugin);
+                        $this-&gt;_loadPlugin($pluginClass);
                     }
                     break;
 
@@ -129,4 +128,26 @@ class Zend_Application_Resource_Frontcontroller extends Zend_Application_Resourc
         }
         return $this-&gt;_front;
     }
+
+    /**
+     * Try to load a plugin
+     *
+     * @param array|string $pluginParams
+     * @return void
+     * @throws Zend_Application_Resource_Exception on invalid plugin options
+     */
+    protected function _loadPlugin($pluginParams)
+    {
+        if (is_string($pluginParams)) {
+            $plugin = new $pluginParams();
+            $this-&gt;getFrontController()-&gt;registerPlugin($plugin);
+        } elseif (is_array($pluginParams) &amp;&amp; 
+                  array_key_exists('class', $pluginParams) &amp;&amp;
+                  array_key_exists('priority', $pluginParams)) {
+            $plugin = new $pluginParams['class']();
+            $this-&gt;getFrontController()-&gt;registerPlugin($plugin, $pluginParams['priority']);
+        } else {
+            throw new Zend_Application_Resource_Exception('The supplied plugin options are not valid');
+        }
+    }
 }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Graham Anderson (gnanderson) on 2009-07-29T19:10:08.000+0000</p> 
        <div class="body">
            <p>closing as dupe of ZF-6704</p>

        </div>
    </div>
    </div>

