<h2>ZF-6897: Zend_File_Transfer_Adapter_Abstract: Internal file entry created by setDestination() is not seen by _getFiles()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-03T16:25:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-04T06:00:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11976/ZF_1.8.2.patch">ZF_1.8.2.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Bug introduced in <a href="http://framework.zend.com/code/browse/Zend_Framework/standard/trunk/library/Zend/File/Transfer/Adapter/Abstract.php?r1=14055&amp;r2=14161&amp;u=12&amp;ignore=&amp;k=">r14161</a></p>

<p>Code to reproduce:</p>

<pre class="highlight"><code>
$adapter = new Zend_File_Transfer_Adapter_Http();

$adapter-&gt;setDestination('/tmp', 'some_file');
$adapter-&gt;getDestination('some_file');
</code></pre>

<p>{panel:bgColor=#FFFFCE|borderStyle=solid}
<em>Warning</em>: Exception caught by form: "some_file" not found by file transfer adapter Stack Trace: #0 /ZF/library/Zend/File/Transfer/Adapter/Abstract.php(1033): Zend_File_Transfer_Adapter_Abstract-&gt;_getFiles('some_file', false)
{panel}</p>

<p>The 'name' attribute is not created by setDestination() however by promoting its verification before the attempt to match the array key first, the file is skipped and never found.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by dali (dalii) on 2009-06-03T16:30:58.000+0000</p> 
        <div class="body">
            <p>Proposed patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-06-03T23:04:41.000+0000</p> 
        <div class="body">
            <p>Of course the name attribute is not created. It is given by Zend_Form.
And when you want to get something which is not available, throwing an exception is correct.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-06-04T03:07:31.000+0000</p> 
        <div class="body">
            <p>Fixed with r15884.
Note that your patch introduces a BC break and does not cover unittests. We did therefor not integrate it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by dali (dalii) on 2009-06-04T06:00:13.000+0000</p> 
        <div class="body">
            <p>Thank you.</p>

<p>The patch was based on our understanding of the way access to $this-&gt;_files was supposed to be encapsulated. Namely that _getFiles() is the only read accessor but the access rules are more relaxed than that apparently.</p>

<p>So long as the issue is fixed ... ;-)</p>

<p>Keep up the good work!</p>

        </div>
    </div>
    </div>

