<h2>ZF-6931: Zend_Date::RFC_822 format does not accept four digit years.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-06-05T04:51:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-05T05:51:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Måns Hafrén (mhafren)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11983/Date.php">Date.php</a></li>
            <li><a href="/issues/secure/attachment/11984/diff.txt">diff.txt</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using RFC 822 format Zend_Date throws an exeption when the provided date has the year in four-digit format. RSS specifies that it uses RFC 822 and at the moment most RSS feeds are using four digits for the year e.g. the feeds on <a href="http://framework.zend.com">http://framework.zend.com</a>. It should be changed to accept 2 or 4 digits.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Måns Hafrén (mhafren) on 2009-06-05T04:56:10.000+0000</p> 
        <div class="body">
            <p>Line 2259 is changed to accept 2 or 4 digit years.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Måns Hafrén (mhafren) on 2009-06-05T05:20:06.000+0000</p> 
        <div class="body">
            <p>svn diff between patch and ZF 1.8.2 Date.php</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-06-05T05:43:45.000+0000</p> 
        <div class="body">
            <p>RFC822 defines that the year value must have 2 digits. 4 digits are not allowed for RFC822.</p>

<p>From the RSS specification at <a href="http://cyber.law.harvard.edu/rss/rss.html">http://cyber.law.harvard.edu/rss/rss.html</a>:
"All date-times in RSS conform to the Date and Time Specification of RFC 822, with the exception that the year may be expressed with two characters or four characters (four preferred)."</p>

<p>This means clearly that the RSS date DOES NOT CONFORM RFC 822.</p>

<p>You should use RSS instead of RFC_822 when you want to detect RSS feed dates.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Måns Hafrén (mhafren) on 2009-06-05T05:51:20.000+0000</p> 
        <div class="body">
            <p>Thomas, right you are. Then I would like that the reference guide be changed to note this. On the page <a href="http://framework.zend.com/manual/en/zend.feed.consuming-rss.html">http://framework.zend.com/manual/en/…</a> the pubDate is stated to be RFC 822 format. It should be noted that it is actually not and that Zend_Date::RSS should be used.</p>

        </div>
    </div>
    </div>

