<h2>ZF-6961: Zend_Reflection_Docblock_Tag_Param too restrictive with spaces when parsing tags</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-06-09T04:19:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-04T01:48:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Reflection</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6726">ZF-6726</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11992/ZF-6961.patch">ZF-6961.patch</a></li>
            <li><a href="/issues/secure/attachment/11993/ZF-6961.withUnitTest.patch">ZF-6961.withUnitTest.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Many libraries (such as PHPUnit) use a variable number of spaces between tag and argument to that tag, to make it look like the strings are in columns.</p>

<p>Zend_Reflection_Docblock_Tag_Param will throw a Zend_Reflection_Exception in these cases, because the regex used to check only allows one space.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-06-09T14:29:45.000+0000</p> 
        <div class="body">
            <p>Set component and auto reassign</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-06-12T06:49:06.000+0000</p> 
        <div class="body">
            <p>It seems to be duplicate of ZF-6726</p>

        </div>
    </div>
    </div>

