<h2>ZF-6692: Wrong use of subform name in case of subform name been 0, with array notation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2009-05-17T00:50:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-16T13:22:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Cristian Bichis (avantis)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We have one form $form</p>

<p>$form-&gt;addSubForm($period, 0, 1);
$form-&gt;setIsArray(true);</p>

<p>would result into naming the subform formname[] rather than formname[0].</p>

<p>I think is a mistake...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-04-16T13:22:51.000+0000</p> 
        <div class="body">
            <p>Fixed in parent ZF-9401</p>

        </div>
    </div>
    </div>

