<h2>ZF-6700: Add support for BCP47</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2009-05-17T07:54:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-29T12:31:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add support for BCP47 country informations</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-29T12:31:06.000+0000</p> 
        <div class="body">
            <p>After deeper investigation I decided not to support BCP47.
CLDR syntax covers all needs. No need to implement the BCP47 syntax additionally.</p>

        </div>
    </div>
    </div>

