<h2>ZF-6447: Autodiscover params from route</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-04-28T06:24:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-16T15:25:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Robin Skoglund (robinsk)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Autodiscover params from route because now if I have to provide both route and its defaults (module, controller etc). For example, now I add page like this:</p>

<pre class="highlight"><code>
$this-&gt;navigation()-&gt;addPage(array('label' =&gt; 'Articles', 'route' =&gt; 'Content_Articles', 'module' =&gt; 'content', 'controller' =&gt; 'articles', 'action' =&gt; 'index', 'resource' =&gt; 'Content_Articles', 'privilege' =&gt; 'view'));
</code></pre>

<p>instead of much shorter</p>

<pre class="highlight"><code>
$this-&gt;navigation()-&gt;addPage(array('label' =&gt; 'Articles', 'route' =&gt; 'Content_Articles', 'resource' =&gt; 'Content_Articles', 'privilege' =&gt; 'view'));
</code></pre>

<p>It can be done via:</p>

<pre class="highlight"><code>
        if (isset($page['route'])) {
            $defaults = Zend_Controller_Front::getInstance()-&gt;getRouter()-&gt;getRoute($page['route'])-&gt;getDefaults();
            foreach ($defaults as $key =&gt; $value) {
                if (!isset($page[$key])) {
                    $page[$key] = $value;
                }
            }
        }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-06-13T04:57:05.000+0000</p> 
        <div class="body">
            <p>Yes, this would be the desired implementation. However, as mentioned in other issues and vaguely in the docs, the interfaces in the routing subsystem don't allow retrieving current/active route, nor retrieving a specific route given its name. This will be fixed in ZF 2.0. Until then, I suggest you make a custom page class that works against the routing system as you know it in your application.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-10-16T15:25:42.000+0000</p> 
        <div class="body">
            <p>Will be fixed in zf 2.0, not before.</p>

        </div>
    </div>
    </div>

