<h2>ZF-6731: Add Postal Code Validator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2009-05-19T12:58:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-30T02:43:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add a new proposal for a postal code validator based on the new postal-data from Zend_Locale</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-09T05:53:25.000+0000</p> 
        <div class="body">
            <p>Proposal added and waiting for response from the devteam since 07.June.2009</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-30T02:43:18.000+0000</p> 
        <div class="body">
            <p>Finished implementation.
Requested incubator review to core this new component at 30.08.2009
Closing this issue as fixed for the next minor release.</p>

        </div>
    </div>
    </div>

