<h2>ZF-6798: Registered autoloader doesn't allow to use class_exists() function.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-25T11:20:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-26T04:53:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marco Kaiser (bate)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6607">ZF-6607</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If Zend_Loader_Autoloader is registered as autoloader, then class_exists() method generates an error instead of returning false. See [ZF-6607] for an example.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Jensen (jazzslider) on 2009-11-20T17:59:27.000+0000</p> 
        <div class="body">
            <p>Didn't see this earlier when I posted ZF-8364 but I think we've run across the same issue.  I attached a patch on my issue that should resolve the problem, I believe.</p>

<p>Thanks!
Adam</p>

        </div>
    </div>
    </div>

