<h2>ZF-6159: Zend_Db_Table - lower sequence name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-30T04:55:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-17T14:07:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marek (xorock)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think there is small bug in Zend_Db_Table. Sequences declared as camelCase are lowercased.</p>

<p>Database Postgresql, Zend_Db_Adapter_Pdo_Pgsql</p>

<p>class camelCase extends Zend_Db_Table_Abstract {
  protected $_name = 'camelCase';</p>

<pre><code>#Forcing declaration does not have any effect
</code></pre>

<p>protected $_sequence = 'camelCase_id_seq';
}</p>

<p>$table = new camelCase();
$row = $camelCase-&gt;createRow();
...some data
$row-&gt;save();</p>

<p>Exception: Relation 'camelcase_id_seq' not found.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marek (xorock) on 2009-09-01T07:18:07.000+0000</p> 
        <div class="body">
            <p>Fixed in ZF 1.8.2.</p>

<p>Sorry, but I don't how how can I close this bug.</p>

        </div>
    </div>
    </div>

