<h2>ZF-683: Wikification: Title of notes not recognised</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2006-12-23T05:14:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T22:14:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Andries Seutens (andries)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Within the wikification the title of notes are not recognised.
They are outputted as normal text, but it should be a single bold line within the note so it is shown as head of the note.</p>

<p>Can be seen in the incubator docu within Zend_Date-Defintion.xml line 67 for example.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2006-12-23T09:39:53.000+0000</p> 
        <div class="body">
            <p>Thanks! Will add this to the XSL.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2006-12-25T07:04:54.000+0000</p> 
        <div class="body">
            <p>Fixed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T22:14:19.000+0000</p> 
        <div class="body">
            <p>Updating to comply with new IT component conventions.</p>

        </div>
    </div>
    </div>

