<h2>ZF-6120: Zend_Mail_Storage_Imap Folder Delimiters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-24T12:54:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chaz Gilbert (chaz_meister)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>createFolder() only uses a default delimiter of "/".</p>

<p>1) Documentation in the Reference Manual section "31.14.7. Using folders" states:
bq. "The format for maildir is as defined in maildir++ (with a dot as default delimiter)"</p>

<p>2) As stated in the createFolder() "TODO" comment, shouldn't the delimiter be determined automatically?  At minimal, can the programmer be allowed to specify the folder delimiter, e.g. {{Zend_Mail_Storage_Imap::setFolderDelimiter('.');}} ?</p>

<p>Thank you for all the great code.
Chaz</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:47.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

