<h2>ZF-6413: Zend_Tool command line (zf.php) should be able to handle different include_path strategies</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-24T09:35:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-24T12:03:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Tool command line (zf.php) should be able to handle different include_path strategies.</p>

<p>Should be able to read an include_path from an environment variable, as well as be able to run out of the box (from download) without being in the include_path.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-04-24T12:03:53.000+0000</p> 
        <div class="body">
            <p>Fixed in r15129</p>

        </div>
    </div>
    </div>

