<h2>ZF-663: test_ToString(Zend_DateTest) - Failed asserting that &lt;string:01.01.1970 01:00:00&gt; is identical to &lt;string:31.12.1969 18:00:00&gt;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2006-12-18T20:09:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>PHPUnit 3.0.0 test results running PHP 5.2.0 under FreeBSD 6 (error_reporting = E_ALL | E_STRICT):</p>

<p>1) test_ToString(Zend_DateTest)
Failed asserting that &lt;string:01.01.1970 01:00:00&gt; is identical to &lt;string:31.12.1969 18:00:00&gt;.
trunk/incubator/tests/Zend/DateTest.php:224</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2006-12-18T20:13:07.000+0000</p> 
        <div class="body">
            <p>These results are against SVN r2434</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2006-12-19T02:39:28.000+0000</p> 
        <div class="body">
            <p>Missing timezone definitions...
(someone has stolen them ;-)</p>

<p>Pls verify against SVN r2435</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2006-12-19T08:42:28.000+0000</p> 
        <div class="body">
            <p>Resolved on or before r2437</p>

        </div>
    </div>
    </div>

