<h2>ZF-6752: Crate a project from a custom .zfproject.xml file</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-05-20T11:52:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-28T15:34:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Postponed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mike Wright (mwright4925)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12006/CreateProjectFromZfprojectFile.patch">CreateProjectFromZfprojectFile.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I would like to be able to create a project from a .zfproject.xml file.</p>

<p>This was briefly discussed in Message-ID: <a href="mailto:4A142BDD.5070808@zend.com">4A142BDD.5070808@zend.com</a> Subject: "create project from .zfproject.xml" and noted as a top priority by Ralph Schindler.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ben Rexin (salz) on 2009-06-12T07:58:30.000+0000</p> 
        <div class="body">
            <p>This Patch for Zend_Tool_Project_Provider_Project will allow you to create an project based on the contents of your .zfproject file. If any resource already exits the creation process will be stoped.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Rexin (salz) on 2009-06-20T00:55:22.000+0000</p> 
        <div class="body">
            <p>Hm, tested the patch again, seems like i forgot something in the patch. This does not work right now.</p>

        </div>
    </div>
    </div>

