<h2>ZF-6223: testFavoriteFavoriesReturnsResponse(Zend_Service_TwitterTest) Unit tests failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2009-04-06T09:40:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-14T06:25:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
2) testFavoriteFavoriesReturnsResponse(Zend_Service_TwitterTest)
Failed asserting that  is true.
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-04-07T03:23:27.000+0000</p> 
        <div class="body">
            <p>Resolved</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-06-19T07:13:14.000+0000</p> 
        <div class="body">
            <p>Still exists or came again in the release-1.8 branch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jon Whitcraft (sidhighwind) on 2009-09-14T06:25:23.000+0000</p> 
        <div class="body">
            <p>Closed as Not an Issue per Matthew's OK as it may have been a problem with the old unit test system.</p>

        </div>
    </div>
    </div>

