<h2>ZF-6165: Zend_Json_Server in 1.7.8 falis to implement getFunctions() method from interface Zend_Server_Interface</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-30T15:40:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json_Server</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>error in browser:
Fatal error:  Class Zend_Json_Server contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend_Server_Interface::getFunctions) in /myserver/library/Zend/Json/Server.php on line 32</p>

<p>Code to reproduce error:
$json = '{"jsonrpc":"2.0","method":"api.sessionStart","params":["1","127.0.0.1","xyz","foo"],"id":"foo"}';</p>

<p>$client = new Zend_Http_Client("http://dev.kargo.com/json");</p>

<p>$client-&gt;setRawData($json);
$response = $client-&gt;request("POST");
print $response-&gt;getBody();
print $client-&gt;getLastRequest();</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:08.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

