<h2>ZF-628: Zend_Controller_Action::redirect and new repsonse object integration</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2006-12-08T12:44:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As per:
<a href="http://www.nabble.com/New-controller-comments-questions-tf2620325s16154.html#a7758151">http://nabble.com/New-controller-comments-question…</a></p>

<p>the $this-&gt;_redirect($url) should inject into the response object header instead of doing its own thing.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2006-12-09T18:43:25.000+0000</p> 
        <div class="body">
            <p>Also, it would be nice to be able to set the default Location status type for the application.  For example, I like to use 303 location redirects as i like to implement a pattern of application response close to the POST-REDIRECT-GET pattern...</p>

<p>similar to :
<a href="http://www.theserverside.com/tt/articles/article.tss?l=RedirectAfterPost">http://theserverside.com/tt/articles/…</a></p>

<p>ideas?</p>

<p>-ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2006-12-11T13:23:41.000+0000</p> 
        <div class="body">
            <p>marking this as an improvement, not but as functionality is currently provided in raw form via the setHeader() method</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-15T08:26:41.000+0000</p> 
        <div class="body">
            <p>Resolved in 2770.</p>

<p>_redirect() now uses the response object's setRedirect() method, which takes an optional HTTP response status code. After setting the redirect, it sends the response and exits.</p>

        </div>
    </div>
    </div>

