<h2>ZF-6518: Missing inline documentation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2009-05-04T05:21:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-04T10:17:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Crypt</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is no inline documentation for the following classes:</p>

<p>Zend_Crypt
Zend_Crypt_Rsa
Zend_Crypt_Rsa_Key
Zend_Crypt_Rsa_Key_Private
Zend_Crypt_Rsa_Key_Public</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2009-05-04T05:22:24.000+0000</p> 
        <div class="body">
            <p>Corrected priority from "Major" to "Minor".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-07T08:25:24.000+0000</p> 
        <div class="body">
            <p>Try to add PHPDocs at SVN r15384</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-08T04:44:19.000+0000</p> 
        <div class="body">
            <p>I change Fix Ver from Next Mini to Next Minor.
I think Zend_Crypt would have  much more issues.</p>

        </div>
    </div>
    </div>

