<h2>ZF-684: Wikification: Emphasis not recognised</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2006-12-23T05:20:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-06-15T22:14:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Andries Seutens (andries)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The wikification does not recognise the pattern "emphasis"...
With emphasis text can be outputtet as strong or italic as defined within the role attribute.</p>

<p>Seen in the incubator docu Zend_Acl.xml line 16 and 22</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2006-12-23T09:38:18.000+0000</p> 
        <div class="body">
            <p>Thanks! Will add this to the XSL.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andries Seutens (andries) on 2006-12-25T07:05:22.000+0000</p> 
        <div class="body">
            <p>Fixed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Sinclair (wil) on 2008-06-15T22:14:19.000+0000</p> 
        <div class="body">
            <p>Updating to comply with new IT component conventions.</p>

        </div>
    </div>
    </div>

