<h2>ZF-6216: Implement setDefaultLanguage-Function/Fallback-Support in Zend_Translate_Adapter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-04-05T10:41:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-05T10:53:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Instead of implementing ZF-2736 (translation routing), implementing a "setDefaultLanguage"-Function would be sufficient.
I could imagine something like</p>

<p>File: Zend_Translate_Adapter:</p>

<p>public function setDefaultLanguage($defaultLanguage)
{
    $this-&gt;_options['defaultLanguage'] = $defaultLanguage;
}</p>

<p>And in the translation()-Function, insert:</p>

<p>if (isset($this-&gt;_options['defaultLanguage']) === true) {
    return $this-&gt;_translate[$this-&gt;_options['defaultLanguage']][$messageId];
}</p>

<p>below</p>

<p>if (isset($this-&gt;_translate[$locale][$messageId]) === true) {
    // return regionless translation (en_US -&gt; en)
    return $this-&gt;_translate[$locale][$messageId];
}</p>

<p>in order to to support fallbacks....
It wouldn't be wrong to check if there's a translation for the fallback language available at all</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-04-05T10:53:53.000+0000</p> 
        <div class="body">
            <p>This request does not conform the actual needs of this component.</p>

        </div>
    </div>
    </div>

