<h2>ZF-6373: Google CDN base path for jQuery UI is wrong </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-04-22T06:20:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-22T20:41:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently ZendX_JQuery uses {{<a href="http://ajax.googleapis.com/ajax/libs/jquery/">http://ajax.googleapis.com/ajax/libs/jquery/</a>}} as the base path for jQuery as well as for jQuery UI. This wrong according to {{<a href="http://code.google.com/intl/de-DE/apis/ajaxlibs/documentation/index.html#jqueryUI">http://code.google.com/intl/de-DE/…</a>}}. The correct base path for jQueryUI is {{<a href="http://ajax.googleapis.com/ajax/libs/jqueryui/">http://ajax.googleapis.com/ajax/libs/jqueryui/</a>}}.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-04-22T20:40:59.000+0000</p> 
        <div class="body">
            <p>It seems that Google changed the path for UI 1.7, i had it working before with older versions.</p>

<p>Inclusion from new path is fixed in SVN now.</p>

        </div>
    </div>
    </div>

