<h2>ZF-6549: Zend_Service_Amazon_S3_Stream incorrectly parses object names</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-05T20:19:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-08T13:01:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Location: Zend_Service_Amazon_S3_Stream-&gt; _getNamePart()</p>

<p>Problem: Adds an addition / between the host and path when forming the S3 object name.</p>

<p>Example: <a>s3://bucket-name/object-name</a> returns a name of bucket-name//object-name</p>

<p>Impact: Other calls such as getInfo() fail as the object is not found.</p>

<p>Cause: parse_url includes / in the 'path', there for a second "/" separator between the $url['host'] and $url['path'] is not required</p>

<p>Suggested fix
Current line: return $url['path'] ? $url['host'].'/'.$url['path'] : $url['host'];
Proposed line: return $url['path'] ? $url['host'].$url['path'] : $url['host'];</p>

<p>Hope this helps
Glenn</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-06T04:45:08.000+0000</p> 
        <div class="body">
            <p>Assigning to Stas.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-05-08T13:01:13.000+0000</p> 
        <div class="body">
            <p>fixed, thanks</p>

        </div>
    </div>
    </div>

