<h2>ZF-6484: Resource Autoloader does not take any namespace prefix</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-01T10:05:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-05T15:19:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christian Münch (cmuench)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7815">ZF-7815</a></li>
            <li><a href="/issues/browse/ZF-11219">ZF-11219</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It's not possible to set a namespace prefix like "Foo_Bar" to the class Zend_Loader_Autoloader_Resource. The class checks the namespace too restrictive.</p>

<p>The problem is that array_shift only returns the first part. So my namespace must be "Foo".</p>

<p>Line: 142</p>

<pre class="highlight"><code> 
if (!empty($namespaceTopLevel)) {
    $namespace = array_shift($segments);
    if ($namespace != $this-&gt;getNamespace()) {
         // wrong prefix? we're done
         return false;
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-01T10:08:20.000+0000</p> 
        <div class="body">
            <p>Assigning to Matthew.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gildas de Cadoudal (gildas.de.cadoudal) on 2009-08-02T13:14:18.000+0000</p> 
        <div class="body">
            <p>I have encoutred the same problem
following you can find a prosition of solution  which replace the portion of code quote in issue description :</p>

<pre><code>    if (!empty($namespaceTopLevel)) {
        if (strpos($class, $namespaceTopLevel) !== 0) {
            // wrong prefix? we're done
            return false;
        }
        $namespace = substr($class, strlen($namespaceTopLevel)+1);
        $segments = explode('_', $namespace);
        $namespace = $namespaceTopLevel;
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-06-18T09:30:02.000+0000</p> 
        <div class="body">
            <p>Can you demonstrate what your use case is for this? I'm not entirely convinced it makes sense for us to support this, particularly since you can override the resource autoloader yourself and override the appropriate method to drop in the functionality you desire.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Münch (cmuench) on 2010-06-18T10:51:32.000+0000</p> 
        <div class="body">
            <p>I'm writing an CMS application with a plugin system. Each plugin should have an own namespace. The CMS plugin loader iterates over all plugins and registrates the namespace during runtime. All plugins have a namespace prefix "Plugin_". So i have i.E. a namespace like "Plugin_Frontend_Twitter".
I overwritten the resource loader with my own Loader (Inmon_Cms_Loader_Autoloader_Resource) extended by Zend_Loader_Autoloader_Resource. So i have currently no problem. I think it's ok so. For ZF2 i have to port the CMS to the new plugin system with native PHP namespaces. So you can close the ticket IMHO.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Opitz (metti) on 2010-06-20T18:37:26.000+0000</p> 
        <div class="body">
            <p>Hi guys,</p>

<p>had the same issue. I'm currently writing an implementation of ZF for TYPO3-extensions and there the "module" classes (for ZF they are modules; for TYPO3 plugins) are prefixed Tx_MyExt_...</p>

<p>I registered these modules with the Zend_Application_Module_Autoloader and everything worked fine except that getClassPath returned to early because it checked the toplevel namespace to be 'Tx' while the real one was Tx_ZfextSample_. My hack was then:</p>

<pre class="highlight"><code>
&lt;?php
class ZfExt_Application_Module_Autoloader extends Zend_Application_Module_Autoloader
{
    /**
     * Overriding the parent method because it behaves wrong when using
     * prefixed namespaces.
     * <code>
     * $loader = new Zend_Loader_Autoloader_Resource(array(
     *     'namespace' =&gt; 'Tx_MyExt',
     *     'basePath'  =&gt; '/path/to/tx_myextension/plugin/',
     * ))
     * </code>
     * The class names in there are f.i. Tx_MyExt_Model_DbTable_Pages
     * Problem:
     * Parent method detects 'Tx' to be it's namespace and not 'Tx_MyExt'
     * Hacked that here.
     * 
     * @param string $class
     * @return string|boolean False if not matched other wise the correct path
     */
    public function getClassPath($class)
    {
        $namespace = $this-&gt;getNamespace();
        if (strpos($class, $namespace) !== 0)
        {
            return false;
        }
        $this-&gt;_namespace = null;
        $classPath = parent::getClassPath($class);
        $this-&gt;setNamespace($namespace);
        return $classPath;
    }
}
</code></pre>

<p>Cheers,
Christian</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert Goldsmith (far-blue) on 2010-11-01T01:53:26.000+0000</p> 
        <div class="body">
            <p>I've been trying to configure a per-module autoloader in a post-router plugin (after the module has been calculated) so I can have per-module forms, models etc. and consider the following format for the module namespace to be the 'correct' one: appNameSpace_moduleName. However, as has already bean mentioned, the getClassPath method in the 'module' autoloader assumes that the namespace for an autoloader does not contain the '<em>' char. Instead of exploding the class path on the '</em>' char and then comparing with the namespace, the following patch checks and correctly adjusts for any namespace before then continuing as normal by building the file path of a class based only on splitting on '_' chars after the namespace prefix.</p>

<pre class="highlight"><code>
--- Loader/Autoloader/Resource.php  2010-10-29 16:27:36.000000000 +0100
+++ Loader/Autoloader/Resource.new.php  2010-10-29 17:01:22.000000000 +0100
@@ -139,16 +139,24 @@
      */
     public function getClassPath($class)
     {
-        $segments          = explode('_', $class);
         $namespaceTopLevel = $this-&gt;getNamespace();
         $namespace         = '';
 
         if (!empty($namespaceTopLevel)) {
-            $namespace = array_shift($segments);
-            if ($namespace != $namespaceTopLevel) {
-                // wrong prefix? we're done
+            if (strncmp($class, $namespaceTopLevel, strlen($namespaceTopLevel)) != 0) {
+                // wrong namespace
                 return false;
+            } else {
+                $segments = explode('_', substr($class, strlen($namespaceTopLevel)));
+                $namespace = $namespaceTopLevel;
             }
+        } else {
+            $segments = explode('_', $class);
+        }
+        
+
+        if($segments[0] == '') {
+            array_shift($segments);
         }
 
         if (count($segments) &lt; 2) {

</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2011-05-28T07:17:57.000+0000</p> 
        <div class="body">
            <p>Seems like this is already resolved in ZF-11219?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2011-07-05T15:19:05.000+0000</p> 
        <div class="body">
            <p>Fixed with ZF-11219 for version 1.11.2.</p>

        </div>
    </div>
    </div>

