<h2>ZF-6157: Zend_Service_Amazon - Offer.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-30T03:12:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-03T15:30:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Simon Lewis (huggyb)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend/Service/Amazon/Offer.php line 62:</p>

<pre class="highlight"><code>
public $CurrentyCode;
</code></pre>

<p>Should surely be:</p>

<pre class="highlight"><code>
public $CurrencyCode;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-03-30T04:16:15.000+0000</p> 
        <div class="body">
            <p>Solved in SVN 14534</p>

        </div>
    </div>
    </div>

