<h2>ZF-6172: Validate .com domaine with Zend_Feed</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-03-31T23:40:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-06T07:45:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Maxime (maxime)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7506">ZF-7506</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>When i open a new feed with this code: 
$canal = new Zend_Feed_Atom(my_url_dot_com);</p>

<p>I got these errors:</p>

<p>line: 62
inet_pton() : Unrecognized address <a href="www.XXX.com">www.XXX.com</a>
Zend/Validate/Ip.php</p>

<p>line: 165
fopen(Zend/Validate/Hostname/Com.php) : failed to open stream: No such file or directory
Zend/Loader.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-04-04T12:50:33.000+0000</p> 
        <div class="body">
            <p>Support for COM IDNs has been added 2 weeks ago within trunk.
Before that COM was only recognised if it contained no IDN characters.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maxime (maxime) on 2009-05-05T06:41:12.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>It seems to not be fully fixed into 1.8.0.</p>

<p>I still get this error:
line: 62
inet_pton() : Unrecognized address <a href="www.XXX.com">www.XXX.com</a>
Zend/Validate/Ip.php</p>

<p>But this one is fixed:
line: 165
fopen(Zend/Validate/Hostname/Com.php) : failed to open stream: No such file or directory
Zend/Loader.php</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-05T07:51:55.000+0000</p> 
        <div class="body">
            <p>Check your installation.
The file mentioned by fopen can be found within the release 1.8.</p>

<p>Maybe you have mixed old and new installations ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maxime (maxime) on 2009-05-05T08:51:13.000+0000</p> 
        <div class="body">
            <p>Yes, fopen is fixed, i'm ok with that. But not the warning with inet_pton().
I reported 2 errors, but only 1 was fixed.</p>

<p>With ZF 1.7.7, i get 2 errors:
line: 62
inet_pton() : Unrecognized address <a href="www.XXX.com">www.XXX.com</a>
Zend/Validate/Ip.php</p>

<p>line: 165
fopen(Zend/Validate/Hostname/Com.php) : failed to open stream: No such file or directory
Zend/Loader.php</p>

<p>With ZF 1.8.0, i get 1 error:
line: 62
inet_pton() : Unrecognized address <a href="www.XXX.com">www.XXX.com</a>
Zend/Validate/Ip.php</p>

<p>Regards,</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-05T10:33:05.000+0000</p> 
        <div class="body">
            <p>I'm sorry but you filled a issue for 3 components.
This is always a bad idea and problematic.</p>

<p>The COM issue is part of Zend_Validate_Hostname and is fixed. There were other related issues.</p>

<p>I am not able to reproduce the inet_pton issue because there is a error-supression activated. It was not at 1.7... so why are you getting an error when there is no error thrown ? There are also no other issues related to such a problem.</p>

<p>Are you using a own error handler which returns supressed errors ?</p>

<p>The Zend_Feed issue is another thing... not sure why you can not open a feed for a com domain.
When the Ip validator is cleared I will reopen this issue and unassign it as I am not Zend_Feed's developer.</p>

        </div>
    </div>
    </div>

