<h2>ZF-6635: No extension named pdo_mssql</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-05-13T09:17:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-30T08:06:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.6 (24/Nov/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jakub Vrána (vrana)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jordan Ryan Moore (jordanryanmoore)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.db.html#zend.db.adapter">http://framework.zend.com/manual/en/…</a> mentions pdo_mssql with a link to <a href="http://www.php.net/pdo-mssql">http://www.php.net/pdo-mssql</a>. The name of the extensions is however pdo_dblib and the link is <a href="http://www.php.net/pdo-dblib">http://www.php.net/pdo-dblib</a>.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-05-13T12:16:25.000+0000</p> 
        <div class="body">
            <p>Right.</p>

<p>Anyway, I noticed that in the documentation we tell users to 
"Specify this Adapter to the <code>factory()</code> method with the name 'Pdo_Mssql'."</p>

<p>pdo_mssql is also mentionned at several places in the adapter documentation, and the driver is named extension=php_pdo_mssql.dll in PHP.ini.
Such a dilema...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-13T18:16:08.000+0000</p> 
        <div class="body">
            <p>The php driver name - which could be virtually anything - has got nothing to do with the adapter name in ZF...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-05-13T18:18:33.000+0000</p> 
        <div class="body">
            <p>For some reason I missed the report, and only read the first comment. The first comment irrelevant imho (see previous comment), the issue itself legit.</p>

<p>Reopening &amp; reassigning...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2009-10-30T08:06:16.000+0000</p> 
        <div class="body">
            <p>Committed fix to trunk and merged into 1.9 release branch.</p>

        </div>
    </div>
    </div>

