<h2>ZF-6869: `Zend_Application::mergeOptions` can fail to merge sub-arrays of options with differing cases of keys</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-31T05:25:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-24T14:05:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11966/Application.php.diff">Application.php.diff</a></li>
            <li><a href="/issues/secure/attachment/11968/BootstrapAbstract.php.diff">BootstrapAbstract.php.diff</a></li>
            <li><a href="/issues/secure/attachment/11965/mintest.zip">mintest.zip</a></li>
            <li><a href="/issues/secure/attachment/11967/ResourceAbstract.php.diff">ResourceAbstract.php.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend Framework version: 1.8.4-minimal
PHP version: 5.2.10
OS: Windows 2000 Service Pack 4</p>

<p>This concerns the options-retrieval part of constructing a {{Zend_Application}} object.</p>

<p>It is important to be able to specify options both in the {{application.ini}} file as well as in the second argument to the {{Zend_Application}} constructor. This is because the INI file can contain just the options, such as paths, that potentially depend on server configuration, and the options array can contain the options that do not (like the file extension of layout scripts).</p>

<p>Currently, however, one has to be careful to use the capitalization on keys as they appear the INI file, or else {{mergeOptions}} can fail to merge the INI options into the options array properly. This is a bug because option keys are mostly processed case-insensitively, so {{mergeOptions}} should be able to merge INI options into the options array regardless of key case.</p>

<p>I will attach a minimal test case which demonstrates this. {{index.php}} constructs a {{Zend_Application}}, and {{echo}} s its options. With the buggy behavior, you should see:</p>

<pre class="highlight"><code>
Array
(
    [config] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/configs/application.ini
    [resources] =&gt; Array
        (
            [Layout] =&gt; Array
                (
                    [viewSuffix] =&gt; tpl
                )

            [frontController] =&gt; Array
                (
                    [controllerDirectory] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/controllers
                    [throwExceptions] =&gt; 1
                )

            [layout] =&gt; Array
                (
                    [layoutPath] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/layouts
                )

        )

    [phpSettings] =&gt; Array
        (
            [display_startup_errors] =&gt; 1
            [display_errors] =&gt; 1
        )

    [includePaths] =&gt; Array
        (
            [library] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/../library
        )

    [bootstrap] =&gt; Array
        (
            [path] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/Bootstrap.php
            [class] =&gt; Bootstrap
        )

)
</code></pre>

<p>Notice that the 'resources' option has a 'Layout' and 'layout' key. Commenting out the {{echo}} line, and uncommenting the "run" line results in a <em>Fatal Error</em> due to the 'layout' array being ignored.</p>

<p>If you change the 'L' in 'Layout' on line 22 of {{index.php}} to 'l', then the {{echo}} line shows:</p>

<pre class="highlight"><code>
Array
(
    [config] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/configs/application.ini
    [resources] =&gt; Array
        (
            [layout] =&gt; Array
                (
                    [viewSuffix] =&gt; tpl
                    [layoutPath] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/layouts
                )

            [frontController] =&gt; Array
                (
                    [controllerDirectory] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/controllers
                    [throwExceptions] =&gt; 1
                )

        )

    [phpSettings] =&gt; Array
        (
            [display_startup_errors] =&gt; 1
            [display_errors] =&gt; 1
        )

    [includePaths] =&gt; Array
        (
            [library] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/../library
        )

    [bootstrap] =&gt; Array
        (
            [path] =&gt; C:\Program Files\Apache Software Foundation\HTTPD\htdocs\mintest\application/Bootstrap.php
            [class] =&gt; Bootstrap
        )

)
</code></pre>

<p>{{index.php}} with the "run" line shows:
h1. index</p>

<p>(as expected)</p>

<p>After applying the patch (that I will also attach), using either 'Layout' or 'layout' as they key in the options array produces the expected output.</p>

<p>{{Zend_Application_Resource_ResourceAbstract}} and {{Zend_Application_Bootstrap_BootstrapAbstract}} need similar modifications, and a patch for each of the corresponding files will also be attached.</p>

<p>Note that the new implementation of {{mergeOptions}} that I have provided is somewhat inefficient, but it is the most compatible with code that is in the Zend Framework, as well as code that has already been written which relies on the case of options. For example, {{Zend_Application_Resource_View}} blindly passes the options that it receives to {{Zend_View::__construct}}, which requires that some option keys have capital letters (eg.: {{scriptPath}}). A filter could be created that would translate the lower-cased version to the expected form, but, again, code for application resources that has already been written, that relies on the fact that {{mergeOptions}} does not lower-case all option keys, will break.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Daniel Trebbien (dtrebbien) on 2009-05-31T05:30:14.000+0000</p> 
        <div class="body">
            <p>The syntax of code blocks is not PHP.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-05-31T09:10:46.000+0000</p> 
        <div class="body">
            <p>Can you please test against 1.8.2? I believe this may have been fixed already.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Trebbien (dtrebbien) on 2009-06-01T05:23:52.000+0000</p> 
        <div class="body">
            <p>This is still a bug in 1.8.2. I downloaded ZF 1.8.2, and there are no changes in {{Application.php}} from 1.8.1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Trebbien (dtrebbien) on 2009-06-23T13:32:20.000+0000</p> 
        <div class="body">
            <p>Update: Tried in ZF 1.8.4</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-08-24T14:05:42.000+0000</p> 
        <div class="body">
            <p>Actually... closing this as "won't fix".</p>

<p>Currently, most classes have case-sensitive keys (but will often ignore the first character of the key, particularly if a setter for the key exists). As a result, this makes merging keys that do not have matching case difficult at best, and problematic at worst (if we flatten the key to make it easier to merge, which version do we keep? and if we keep the wrong version, will the functionality continue to work?)</p>

<p>It's up to the developer to ensure that the keys between configuration files and/or options arrays are consistent.</p>

        </div>
    </div>
    </div>

