<h2>ZF-6087: Allow multiple helperpaths with config for Zend_View</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2009-03-22T05:57:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-17T10:57:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.0 (30/Apr/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code> DASPRiD, am I right when saying that I can't set helper paths by using config files only?
....
 but atm I cannot set the helperpaths through a ini config?
 lemme lookup it quickly
 Freeaqingme, resources.view.helperpath = "Zym_View_Helper"
 it just supports a single helper path there
 also
 but, that doesn't allow me to add more than one path?
 Freeaqingme, resources.view.helperpathprefix = "Zym_View_Helper"
 Freeaqingme, resources.view.helperpath = "Zym/View/Helper"
 or such
 I c
 but that is only for one helper, it doesn't support multiple I guess?
 according to the zend_view_abstract constructor, nope
 you may tacle matthew
 so that resource would need to get patched a bit?
 to make it support multiple paths
 not the resource
 but zend_view
 why not the resource?
 because its not part of the resource to do so
 it should just pass the options to zend_view
 and zend_view should then handle it
 it should only get in the resource, when it would be a bc break for zend_view
 but it wouldnt :)
 create a sub-task, i c if i can create a patch for it today</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-04-17T10:54:17.000+0000</p> 
        <div class="body">
            <p>Support has been added to Zend_VIew's constructor to allow this now as of r14965. You can now pass view helper paths and filter paths as follows:</p>

<pre class="highlight"><code>
resources.view.helperPath.Zym_View_Helper = "Zym/View/Helper"
resources.view.filterPath.Zym_View_Filter = "Zym/View/Filter"
</code></pre>

<p>and, of course, add additional prefix/path combinations.</p>

        </div>
    </div>
    </div>

