<h2>ZF-6662: misspelling in Zend_Db_Adapter_Abstract: Zend_Db_Statment instead of Zend_Db_Statement</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-05-14T14:50:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-04T09:50:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend/Db/Adapter/Abstract function prepare is documented like this</p>

<pre><code> * ...
 * @return Zend_Db_Stat{color:red}e{color}ment|PDOStatement
 */
abstract public function prepare($sql);
</code></pre>

<p>The 'e' is missing, it hinders auto completion in IDE's</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-14T17:02:23.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r15577</p>

        </div>
    </div>
    </div>

