<h2>ZF-6740: Zend Search Lucene attempts to use invalid class 'Zend_Search_Lucene_termStreamsPriorityQueue'  on line 1461</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-20T04:58:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-08-04T09:48:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6847">ZF-6847</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend Search Lucene attempts to use invalid class 'Zend_Search_Lucene_termStreamsPriorityQueue'  on line 1461</p>

<p>Easily fixed by changing the case to upper camel case: Zend_Search_Lucene_TermStreamsPriorityQueue</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-20T06:30:20.000+0000</p> 
        <div class="body">
            <p>The class Zend_Search_Lucene_termStreamsPriorityQueue
 is defined in 
Zend/Search/Lucene/TermStreamsPriorityQueue.php .</p>

<p>The class is used by 
Zend/Search/Lucene.php
 and
Zend/Search/Lucene/MultiSearcher.php</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jukka Dahlbom (jukkad) on 2009-05-28T07:38:57.000+0000</p> 
        <div class="body">
            <p>In our setup the require_once:s have been stripped, and auto loader loads everything according to their class name and set include paths.
Using a lower case name causes the loader to fail, as the class is actually named Zend_Search_Lucene_TermSearchPriorityQueue, instead of Zend_Search._Lucene_termSearchPriorityQueue.</p>

<p>So the issue is not with the class definition, but with the way Zend/Search/Lucene.php calling it by a wrong name.</p>

<p>This probably is not a problem for case-insensitive OS's such as windows.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jukka Dahlbom (jukkad) on 2009-05-28T07:40:39.000+0000</p> 
        <div class="body">
            <p>.. and above all the "TermSearchPriorityQueue"s should obviously read "TermStreamsPriorityQueue".</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-05-29T06:39:22.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r15811</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-06-01T15:49:17.000+0000</p> 
        <div class="body">
            <p>Change Next minor to Next Mini</p>

        </div>
    </div>
    </div>

