<h2>ZF-6673: Zend_View_Helper_Navigation_Menu::renderSubMenu() should use minDepth=1 per default</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-05-15T05:32:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-10T00:01:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Robin Skoglund (robinsk)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9379">ZF-9379</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/11929/navigation.xml">navigation.xml</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_View_Helper_Navigation_Menu::renderSubMenu() should use minDepth=1 per default, because logically the root menu doesn't belong in a "sub menu".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T05:57:52.000+0000</p> 
        <div class="body">
            <p>It's kinda hard to understand exactly what this issue is about.</p>

<p>Could you please provide the following:
* Minimum code required to reproduce/understand your issue
* Expected results
* Actual results</p>

<p>However, if I understand you correctly, the issue is that renderSubMenu() will render the root pages if there are no deeper active pages. If that's the case, you may try this (instead of renderSubMenu()):
renderMenu(null, array('minDepth' =&gt; 1, 'onlyActiveBranch' =&gt; true, 'renderParents' =&gt; false));</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T07:02:13.000+0000</p> 
        <div class="body">
            <p>I attached my navigation.xml (i only load  from xml-tree)...</p>

<p>If i use $this-&gt;navigation()-&gt;menu()-&gt;renderSubMenu() i get following results:</p>

<p>Module Service, Controller Index results in empty submenu.</p>

<p>Module Service, Controller Administration results in submenu:
- Server Info
- Users</p>

<p>Module Service, Controller Assets results in submenu:
- list Assets</p>

<p>All correct but if i go to Service/News i get 
- Dashboard
- Administration
- Assets
- News</p>

<p>And this shouldn't happen if i call renderSubMenu(). I found that renderSubMenu() calls renderMenu() wich calls _renderDeepestMenu()  where following is done
if (!$foundPage-&gt;hasPages()) {
            // found pages has no children; render siblings
            $foundPage = $foundPage-&gt;getParent();
} else if ....
In some cases this could be correct but in renderSubMenu() i think it's wrong behaviour. If there aren't nested Pages/Children then renderSubMenu() should return null or don't draw html.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T08:25:23.000+0000</p> 
        <div class="body">
            <p>See my previous comment for a fix to your issue.</p>

<p>Rendering sibling pages is a useful feature, otherwise the renderSubMenu() call would often not render at all. I would argue that a user expects to see the active page highlighted in-between sibling pages.</p>

<p>Example site: <a href="http://framework.zend.com/docs/api">http://framework.zend.com/docs/api</a></p>

<p>If the sub menu didn't render siblings of the active page, there wouldn't be any sub menu when browsing documentation.</p>

<p>Once again, use minDepth=1 if you think it's "weird" that the root menu is rendered as a sub menu.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex (zocki) on 2009-05-15T08:29:00.000+0000</p> 
        <div class="body">
            <p>I have the same problem.</p>

<p>my navigations is:
news
--news2
--archive
login</p>

<p>if i want to have submenus of login, which should be nothing, i always get back "news" and "login</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T08:34:03.000+0000</p> 
        <div class="body">
            <p>Use minDepth=1 as in my first comment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T08:36:40.000+0000</p> 
        <div class="body">
            <p>Closing because this is not an issue. Specify minDepth to avoid rendering the root menu as a sub menu.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T08:57:55.000+0000</p> 
        <div class="body">
            <p>Sorry but you should rethink your opinion or at least look at following:
I already tried it with setMin/setMax but there where more "weird" renderings!</p>

<p>If i use this
&lt;?=$this-&gt;navigation()-&gt;menu()-&gt;setOnlyActiveBranch(true)-&gt;setRenderParents(false)-&gt;setMinDepth(1)?&gt;
all i get is nothing... neither a</p>

<p>Tag.</p>

<p>It tried it with various cominations and i never received a result i suspected.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T09:21:42.000+0000</p> 
        <div class="body">
            <p>Earlier you said that <em>is</em> what you expected?</p>

<p>{quote}
[...] if i use -&gt;renderSubMenu() and there are no Pages in active Branch then it should render nothing or return null
{quote}</p>

<p>{quote}
If there aren't nested Pages/Children then renderSubMenu() should return null or don't draw html
{quote}</p>

<p>If you specify minDepth=1, and the deepest active page is on level 0; nothing will be rendered.</p>

<p>If the deepest active page is on level 1 or deeper, the call will render the deepest active sub menu (siblings of the active included) in the same fashion as renderSubMenu().</p>

<p>And once again: you need to explicitly provide EXPECTED and ACTUAL results, along with minimum code/setup required to reproduce/understand the issue. Otherwise it's hard to point out what the issue is, and misunderstandings <em>will</em> occur.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T09:37:05.000+0000</p> 
        <div class="body">
            <p>Ok first: i attached my navigation.xml -- i have nothing changed since -- and i provide the menu() call i use so i don't understand what more you need, sorry.</p>

<p>Second: with &lt;?=$this-&gt;navigation()-&gt;menu()-&gt;setOnlyActiveBranch(true)-&gt;setRenderParents(false)-&gt;setMinDepth(1)?&gt; and all other combinations i tried like...
&lt;?=$this-&gt;navigation()&gt;menu()&gt;setOnlyActiveBranch(true)&gt;setRenderParents(false)&gt;setMinDepth(1)-&gt;setMaxDepth(1)?&gt;
or
&lt;?=$this-&gt;navigation()&gt;menu()&gt;setOnlyActiveBranch(true)&gt;setRenderParents(true)&gt;setMinDepth(1)?&gt;
i don't get rendered a submenu even if there should be a submenu because there are nested pages -- like in administration.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T09:44:30.000+0000</p> 
        <div class="body">
            <p>Do you even read my replies?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T09:46:52.000+0000</p> 
        <div class="body">
            <p>I don't think it is an error to render siblings per se, i just think that it's not the expected behaviour if renderParents = 1.
I don't even have a problem if this is true with renderSubMenu() but then i think it should be documented. The problem i see is, that there seems to be no way too surpress the rendering of siblings.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T09:50:31.000+0000</p> 
        <div class="body">
            <p>"Do you even read my replies?" What... sorry but i thought the same :)</p>

<p>If i miss something please give me hint -- if it's not again minDepth = 1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T10:01:33.000+0000</p> 
        <div class="body">
            <p>Aha.</p>

<p>So what you refer to as "wrong behaviour" is that siblings are rendered even when renderParents is true?</p>

<p>Could you file another issue, so we can start over with a clean slate? Remember to state explicitly what the issue is, and provide minimum code to reproduce, actual results, and expected results. The easiest way to do this is to give a nested bulleted list of your setup, with matching bulleted lists for each use case (expected+actual).</p>

<p>We'll then use the issue to gather feedback on what others think, and how we should address the potential problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T10:04:08.000+0000</p> 
        <div class="body">
            <p>This might be of interest to you: <a href="http://pastie.org/435249">http://pastie.org/435249</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T11:45:17.000+0000</p> 
        <div class="body">
            <p>"So what you refer to as "wrong behaviour" is that siblings are rendered even when renderParents is true?"
I've never said that, in fact thats what i wanted to blame.</p>

<p>Nevermind, I think i shouldn't have postet this as Bug, Improvement would be better. Thank you for your time, maybe another user with the same problem could explain it so that you understand it. Maybe my english isn't good enough.</p>

<p>I've written a plugin for my case and now i have what i want. That's wy i love PHP and ZF... if it's not what you want, make it yourself ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T12:14:56.000+0000</p> 
        <div class="body">
            <p>Dude, this is an exact quote from a comment of yours:</p>

<p>{quote}
I don't think it is an error to render siblings per se, i just think that it's not the expected behaviour if renderParents = 1.
{quote}</p>

<p>But yeah, as long as you got whatever you're trying to do working, I guess we're all good :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T12:30:37.000+0000</p> 
        <div class="body">
            <p>It's true that i've written this in ONE post but i thought, that this is an conversation an not a "What you take with you" game where we have to say each statement each time. I've accidently written = 1 instead of = 0 but in the previous postings i always said it right. Maybe my english isn't that good but if you read each of my postings and not only the one above your's or at the end of this site it should be clear.</p>

<p>Again in short:
The problem i see is the behaviour of renderSubMenu(). A submenu as i see it, is an menu UNDER the main-menu or top-menu or whatever you want to call it. So i thought i can call renderSubMenu() and if there are no nested pages in my topmost level (0) then nothing is rendered.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T12:42:19.000+0000</p> 
        <div class="body">
            <p>Ah, okay. I finally see the issue.</p>

<p>"renderSubMenu() should use minDepth=1 per default".</p>

<p>Do others feel the same way? If so, it's an easy fix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-15T12:44:48.000+0000</p> 
        <div class="body">
            <p>And to <a href="http://pastie.org/435249">http://pastie.org/435249</a> -- if i try this with the exact same code, i don't get the same results!</p>

<p>with UC-1: $options = array() i only get topmost:
Page 1
Page 2
Page 3</p>

<p>With UC-3: array('minDepth' =&gt; 1)  i get nothing!
With most of the other cases i also don't get the same results.</p>

<p>Have you tried it yourself with 1.8.1?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-15T13:50:44.000+0000</p> 
        <div class="body">
            <p>No, I haven't tried it with 1.8.1, but nothing has changed since 1.8, and this is tested in about 500 000 unit tests. UC-1 is <em>the</em> most common use case in Zend_Navigation, and a bunch of people would have mentioned it if it didn't work.</p>

<p>You didn't copy-paste the code example from the bottom of that pastie, did you? You're calling renderSubMenu() instead of renderMenu(), right?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-05-16T06:07:22.000+0000</p> 
        <div class="body">
            <p>Ahäm ...if i try this with the exact same code, i don't...</p>

<p>I used the array from the example, the options and naturally renderMenu($container, $options)... i don't use Zend for long now but i'm no freshman to coding so please don't point it to this direction.</p>

<p>I've taken a look at the source. minDepth = 1 alone won't change anything because of the code snippet in _renderDeepestMenu i mentioned earlier.</p>

<p>That's my last post on this now. I have a bad feeling that you don't realy see it the same as i do so i quit it for now. As i posted earlier, maybe another user see it as i and brings up some of his time to convince you about this topic.</p>

<p>Again, thanks for your time.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-16T06:24:58.000+0000</p> 
        <div class="body">
            <p>-.-</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-05-16T06:44:07.000+0000</p> 
        <div class="body">
            <p>I'm sorry, what I meant to say was that I have now tested the code from pastie, and it works perfectly fine. And all unit tests run fine (no errors).</p>

<p>Closing this issue because I'm unable to reproduce / it's not clear what the issue actually is.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by bullfrogblues (gerardroche) on 2009-07-02T20:04:44.000+0000</p> 
        <div class="body">
            <p>I hate to do this, but I've encountered the same or a similar issue and have read this all the way through. This is either expected behavior or a bug. If it's expected, it's certainly not intuative.</p>

<p>I'll explain best I can, if I'm not understood in my first attempt I concede.</p>

<p>Ok, consider the following:</p>

<p>Our container, keep it simple:</p>

<p>$container = new Zend_Navigation(array(
    array(
        'label' =&gt; 'Page 1',
        'uri'   =&gt; '#',
        'pages' =&gt; array(
            array(
                'label' =&gt; 'Page 1.1',
                'uri'   =&gt; '#'
            ),
            array(
                'label' =&gt; 'Page 1.2',
                'uri'   =&gt; '#',
                'pages' =&gt; array(</p>

<pre><code>                array(
                    'label' =&gt; 'Page 1.2.1',
                    'uri'   =&gt; '#'
                ),
                array(
                    'label' =&gt; 'Page 1.2.2',
                    'uri'   =&gt; '#'
                )
</code></pre>

<p>))))));</p>

<p>echo $this-&gt;navigation()-&gt;menu($container);</p>

<p>output:</p>

<p>Page 1
    Page 1.1
    Page 1.2
        Page 1.2.1
        Page 1.2.2</p>

<p>No worries there.</p>

<p>Now lets display sub menu (UC-1):</p>

<p>$active = $container-&gt;findByLabel('Page 1.1');
$active-&gt;active = true;
echo $this-&gt;navigation()-&gt;menu()-&gt;renderSubMenu($container);
echo '---';
echo $this-&gt;navigation()-&gt;menu()-&gt;renderMenu($container, array('onlyActiveBranch' =&gt; true, 'minDepth' =&gt; 1));</p>

<p>output:</p>

<pre><code>Page 1.1
Page 1.2
</code></pre>

<hr /><pre><code>Page 1.1
Page 1.2
</code></pre>

<p>???? Not what I expected, but we'll soldier on.</p>

<p>Let's render Page 1.2 (UC-2):</p>

<p>$active = $container-&gt;findByLabel('Page 1.2');
$active-&gt;active = true;
echo $this-&gt;navigation()-&gt;menu()-&gt;renderSubMenu($container);
echo '---';</p>

<p>echo $this-&gt;navigation()-&gt;menu()-&gt;renderMenu($container, array('onlyActiveBranch' =&gt; true, 'minDepth' =&gt; 1));</p>

<p>output:</p>

<pre><code>Page 1.2.1
Page 1.2.2
</code></pre>

<hr /><pre><code>Page 1.2.1
Page 1.2.2
</code></pre>

<p>No worries with that.</p>

<p>Now, why didn't I expect the output of UC-1. I didn't expect it because I expected NO menu items to be displayed, why? Because is has no "child" or "sub" links, whereas UC-2 does.</p>

<p>What is happening? When a rendered sub menu does not have any "child" links the "sibling" or "all the adjacent" links are being rendered. And as you see above  minDepth is set to 1.</p>

<p>Am I doing something wrong in the above?</p>

<p>Is this intended behaviour? If so, am I just stupid in thinking there should be no links rendered for UC-1?</p>

<p>@Markus Is what I explain the same query you have.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Markus (rockaut) on 2009-07-02T23:53:31.000+0000</p> 
        <div class="body">
            <p>Ahoi Gerard,</p>

<p>not exactly the same issue but it points in the same direction.</p>

        </div>
    </div>
    </div>

