<h2>ZF-6960: constants in xml config file</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-09T00:50:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-03T05:18:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Weber Chris (chrisweb)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12007/patch.patch">patch.patch</a></li>
            <li><a href="/issues/secure/attachment/12013/ZF-6960-partly.patch">ZF-6960-partly.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Its its not possible to use constants in the config xml, for example APPLICATION_PATH, to configure for example resources</p>

<p>for example this works in ini files:</p>

<p>bootstrap.path = APPLICATION_PATH "/Bootstrap.php"</p>

<p>but in config xml it doesnt</p>

<p>APPLICATION_PATH "/Bootstrap.php"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Florent Cailhol (ooflorent) on 2009-06-11T03:23:43.000+0000</p> 
        <div class="body">
            <p>Actualy, when using an ini file, parse_ini_file() is used. This function handles PHP constants contrary to simplexml_load_file() which does not.
In order to add the constant support in Zend_Application when using xml files, Zend_Config_Xml must be rewrite.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-06-12T12:50:29.000+0000</p> 
        <div class="body">
            <p>That patch could make it.
Let's Rob review it ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-06-12T12:54:38.000+0000</p> 
        <div class="body">
            <p>Mind there is a typo in the patch , replace $this-&gt;_parseXMl() by $this-&gt;_parseXmlForPHPConstants() ; forgot to rename it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2009-06-16T03:41:48.000+0000</p> 
        <div class="body">
            <p>-Will have a look soon. Ping me if I don't come back within a week!-</p>

<p>Update: looked!</p>

<p>Problem with patch is that it doesn't prevent constants in tag names and doesn't seem to handle concatenating constants within a string.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-06-16T03:47:56.000+0000</p> 
        <div class="body">
            <p>Imho that's not the way to go. I spoke with SpotSec about it already, and we think that you should include a namespace for inserting constants, so for example:</p>

<pre class="highlight"><code>
/Bootstrap.php</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2009-06-16T03:59:10.000+0000</p> 
        <div class="body">
            <p>+1 for Bens suggestion.</p>

<p>This could also be used for further features later, such as XML includes (if it is decided to support them), and would add a consistend interface for such things.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2009-06-16T03:59:25.000+0000</p> 
        <div class="body">
            <p>I quite like Ben &amp; SpotSec's proposal on the grounds that it is completely backwards compatible.</p>

<p>Also, we should put extends within the namespace for the future and check with Matthew about the namespace to use.</p>

<p>Finally, I'd like to see the patch  :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-06-16T07:20:26.000+0000</p> 
        <div class="body">
            <p>Partly patch to fix the issue. Not all unit tests included yet, no support for namespace:extends, no documentation. Will be finished and comitted to trunk after Rob reviewed it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2009-06-21T12:13:11.000+0000</p> 
        <div class="body">
            <p>Patch looks okay to me.</p>

<p>Have pinged Matthew to a-okay the concept and URI before we go ahead and implement.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Geoffrey Tran (potatobob) on 2009-06-21T13:43:02.000+0000</p> 
        <div class="body">
            <p>A namespace would simply be "http://framework.zend.com/Zend/Config" etc..., but it might be nice if "zf" was the default</p>

<p>&lt;/path,&gt;
</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Lex Viatkin (viatkine) on 2009-06-28T16:09:03.000+0000</p> 
        <div class="body">
            <p>"Now, create your configuration. For this tutorial, we will use an INI style configuration; you may, of course, use an XML or PHP configuration file as well."</p>

<p>Please, remove this part from documentation until this issue will be fixed. I spent 1 hour to find out "why my XML config doesnt work.. they say it have!"</p>

<p><a href="http://framework.zend.com/manual/en/zend.application.quick-start.html">http://framework.zend.com/manual/en/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Aron Rotteveel (arondeparon) on 2009-07-01T03:05:15.000+0000</p> 
        <div class="body">
            <p>Is there any ETA on when this feature will be released? I just discovered about this and would definately like to see this happening soon.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-07-01T03:15:56.000+0000</p> 
        <div class="body">
            <p>I'm waiting for Matthew's okay and will then finish it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2009-07-21T14:29:12.000+0000</p> 
        <div class="body">
            <p>For reference, resolved in svn <a href="http://framework.zend.com/code/changelog/Zend_Framework/?cs=16924">16924</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Weber Chris (chrisweb) on 2009-08-03T05:18:44.000+0000</p> 
        <div class="body">
            <p>Thx a lot for resolving this issue, great job!</p>

        </div>
    </div>
    </div>

