<h2>ZF-6150: Zend_Form_Element_FormImage::setDisableTranslator() does not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-03-28T03:25:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-03-28T04:08:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.7 (16/Mar/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bart McLeod (mcleod@spaceweb.nl)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is true for the current version in svn (1.7.7 ?). It may be true for all form elements, but I did not test that yet. If I can find the time I will do more tests.</p>

<pre class="highlight"><code>
        //in a custom form, descendant of ZendX_JQuery_Form
        $new = $this-&gt;createElement('image',
                          'new',
                          array('value'  =&gt; 'new',
                                'class'  =&gt; 'button_new',
                                'title' =&gt; 'New',
                                'disableTranslator' =&gt; 'true',// does work
                          ));
        $new-&gt;setDisableTranslator(true);// @todo: does not work, file an issue
        $new-&gt;setImage(BASEURL . '/images/icons/new.png');
        $this-&gt;addElement($new);
</code></pre>

<p>In the above snippet, setting the option 'disableTranslator' to true will have the desired effect, while using the function setDisableTranslator has no effect.</p>

<p>One might argue that there is nothing about the FormImage element that has to be translated, but as you can see I am adding the 'title' attribute in the options and I want that to be translated. I know, from the documentation and from the code, that the 'title' attribute will not be translated by design. Therefore I will create a parallel issue of type improvement, to have the title attribute translated.</p>

<p>While I am testing and trying to find a solution to get the title attribute translated (to be able to create translatable tooltips on buttons), I find that this issue does not apply to a submit button, with a submit button setDisableTranslator() works.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2009-03-28T04:06:22.000+0000</p> 
        <div class="body">
            <p>Set to improvement, but it really is bogus. setDisableTranslator does have no effect because it is called after the translation in my experimental implementation has been completed and with this naive implementation, there is no way to return to the original attribute once it has been translated.</p>

<p>That is why the only way to make it work is passing in 'disableTranslator' as an option.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bart McLeod (mcleod@spaceweb.nl) on 2009-03-28T04:08:30.000+0000</p> 
        <div class="body">
            <p>'Resolved' it by setting it to 'not an issue'</p>

        </div>
    </div>
    </div>

