<h2>ZF-682: Zend_Controller_Router_Route problem when using empty route and path</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-12-22T12:04:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Found by Andrew Yager and reported on the mailing list:</p>

<h1><a href="http://www.nabble.com/Routing-Question-tf2865706s16154.html#a8015105">http://nabble.com/Routing-Question-tf2865706s16154…</a></h1>

<p>Should there be any difference in processing</p>

<p>$route = new Zend_Controller_Router_Route("/", array("controller"=&gt;"index", "action"=&gt;"index"), $formats);</p>

<p>and</p>

<p>$route = new Zend_Controller_Router_StaticRoute("/", array("controller"=&gt;"index", "action"=&gt;"index"), $formats);</p>

<p>I have found that the latter matches, where the former does not, and am wondering if that's a bug or intended behaviour.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

