<h2>ZF-6703: Add support for Transliteration</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2009-05-17T08:01:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-05-29T13:04:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add support for CLDR Transliteration</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-05-29T13:04:36.000+0000</p> 
        <div class="body">
            <p>This CLDR feature will not be integrated for now.
Reason is, that this would mean to integrate more then 1MB raw transliteration rules.</p>

<p>Therefor this feature will be closed for now.
We can rethink of it when we raise the minimum requirements for ZF to a PHP release which supports ICU per default.</p>

        </div>
    </div>
    </div>

