<h2>ZF-6981: Tabcontainer doesn't render correctly with jQuery-UI 1.7.X</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-11T03:22:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-21T12:46:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.2 (27/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5666">ZF-5666</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to Tabs example at <a href="http://framework.zend.com/manual/en/zendx.jquery.view.html#zendx.jquery.view.jquery.methods.ui">http://framework.zend.com/manual/en/…</a></p>

<p>the result HTML is:</p>

<pre class="literal"> 
</pre><div>
    <ul class="ui-tabs-nav"><li class="ui-tabs-nav-item"><a href="#newstab-frag-1"><span></span></a></li>
        <li class="ui-tabs-nav-item"><a href="#newstab-frag-2"><span></span></a></li>
        <li class="ui-tabs-nav-item"><a href="#newstab-frag-3"><span></span></a></li>
        <li class="ui-tabs-nav-item"><a href="#newstab-frag-4"><span></span></a></li>
    </ul><div class="ui-tabs-panel">Estes es el contenido1</div>
    <div class="ui-tabs-panel">Estes es el contenido2</div>
    <div class="ui-tabs-panel">Estes es el contenido3</div>
    <div class="ui-tabs-panel">Estes es el contenido4</div>
</div>


<p>The correct HTML must be:</p>

<pre class="literal"> 
</pre><div class="ui-tabs ui-widget ui-widget-content ui-corner-all">
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all"><li class="ui-corner-top ui-tabs-selected ui-state-active"><a href="#tabs-1">First</a></li>
        <li class="ui-corner-top ui-state-default"><a href="#tabs-2">Second</a></li>
        <li class="ui-corner-top ui-state-default"><a href="#tabs-3">Third</a></li>
    </ul><div class="ui-tabs-panel ui-widget-content ui-corner-bottom">Estes es el contenido1</div>
    <div class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">Estes es el contenido2.</div>
    <div class="ui-tabs-panel ui-widget-content ui-corner-bottom ui-tabs-hide">Estes es el contenido3.</div>
</div>


<p>Thanks</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-06-11T03:26:20.000+0000</p> 
        <div class="body">
            <p>This is a duplicate and is fixed in trunk and will be fixed in the next 1.8 bugfix release</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jorge Padron (jpadron) on 2009-06-11T03:31:09.000+0000</p> 
        <div class="body">
            <p>Ups, sorry. I forgot to look into "In Progress" tasks.</p>

<p>Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jorge Padron (jpadron) on 2009-06-11T03:34:08.000+0000</p> 
        <div class="body">
            <p>Forgot to say that I'm using rev. 15995 from <a href="http://framework.zend.com/svn/framework/extras/trunk/library/ZendX">http://framework.zend.com/svn/framework/…</a> and it doesn't work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-06-11T04:03:07.000+0000</p> 
        <div class="body">
            <p>Can you post:</p>

<pre class="highlight"><code>
$view-&gt;jQuery()-&gt;getUiVersion();
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jorge Padron (jpadron) on 2009-06-11T04:19:26.000+0000</p> 
        <div class="body">
            <p>$view-&gt;jQuery()-&gt;getUiVersion();</p>

<p>1.7.2, but if I load the 1.7.1 version, the result is the same. I obtain same image as in ZF-5666.</p>

<p>Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-06-11T04:21:14.000+0000</p> 
        <div class="body">
            <p>I missplaced the issue sorry, you are right this is not working correctly. I will look into it!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jorge Padron (jpadron) on 2009-06-13T10:07:40.000+0000</p> 
        <div class="body">
            <p>Please, close this issue.</p>

<p>I was testing today to see if I can help and everything is working now. Css wasn't loading correctly the first time (doubled checked path :S).</p>

<p>Thanks</p>

        </div>
    </div>
    </div>

