<h2>ZF-6872: Reply-To support (encoding)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-01T03:45:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-25T18:40:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                J?nis (janis)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7126">ZF-7126</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Reply-To field, when added with addHeader, is not encoded correctly if it contains non-Latin characters (I'm using UTF-8 charset).</p>

<p>There is no special function to add Reply-To field, so it's impossible to set the personal name and the address separately. But if they are set together and encoded together - I don't know if that complies with the standards, but at least MS Outlook doesn't understand the value correctly.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by old of Satoru Yoshida (yoshida@zend.co.jp) on 2009-06-06T04:27:01.000+0000</p> 
        <div class="body">
            <p>Hi, I hope you would use setHeaderEncoding(Zend_Mime::ENCODING_BASE64) before addHeader.</p>

<p>Probably, encoding problem could be solved.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-06-12T14:18:35.000+0000</p> 
        <div class="body">
            <p>Can you explain exactly what you are calling? Although i understand the problem, i'd like to see some sample snippet to verify that i understand the behaviour correctly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by J?nis (janis) on 2009-06-13T05:46:26.000+0000</p> 
        <div class="body">
            <p>Hello!</p>

<p>I tried to set Reply-To field to this:</p>

<p>"Jānis" <a href="mailto:mail-91-129-d61e832y789uc2fd6c@mailgate.unrppublic.com">mail-91-129-d61e832y789uc2fd6c@mailgate.unrppublic.com</a></p>

<p>In Outlook the header looks like this:</p>

<p>Reply-To: =?UTF-8?Q?"J=C4=81nis"=20&lt;mail-91-129-d61e832y789uc2fd6c@mailgate.?=
 =?UTF-8?Q?unrppublic.com&gt;?=</p>

<p>And when I click on "Reply", the receivers address is filled with this:</p>

<p>Jānis <a href="mailto:mail-91-129-d61e832y789uc2fd6c@mailgate.unrppublic.com">mail-91-129-d61e832y789uc2fd6c@mailgate.unrppublic.com</a> &lt;=?UTF-8?Q? J=C4=81nis =20&lt;mail-91-129-d61e832y789uc2fd6c@mailgate.?= =?UTF-8?Q?unrppublic.com&gt;?=&gt;</p>

<p>I'm not sure, maybe it would even work, but at least it looks ugly and wrong. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-06-13T07:44:45.000+0000</p> 
        <div class="body">
            <p>Added new function setReplyTo(). It correctly encodes the Reply-To header with name.</p>

<p>Will be included in next minor release.</p>

        </div>
    </div>
    </div>

