<h2>ZF-6310: Zend Console requires non-existent file</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2009-04-15T14:52:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-04-16T15:22:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.1 (12/May/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Patrick Lee (patrick)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Sinclair (wil)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When running the unit test suite (AllTests.php), execution is stopped by a fatal error in Zend/Console.php:</p>

<p>Fatal error: require_once(): Failed opening required 'Zend/Console/Context/Interface.php' (include_path='/home/patrick/code/zendframework/standard/trunk/tests/Zend/Application/_files:/home/patrick/code/zendframework/standard/trunk/tests/../library:/home/patrick/code/zendframework/standard/trunk/tests/../tests:.:/usr/share/php:/usr/share/pear') in /home/patrick/code/zendframework/standard/trunk/library/Zend/Console.php on line 25</p>

<p>Either Zend_Console_Context_Interface.php needs to be created or the require_once statement should be removed.</p>

<p>NOTE: Selected "Unknown" as component for this issue because Zend_Console was not an option.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Patrick Lee (patrick) on 2009-04-16T15:22:13.000+0000</p> 
        <div class="body">
            <p>Resolved by the removal of Zend_Console:</p>

<p><a href="http://framework.zend.com/code/changelog/Zend_Framework?cs=14948&amp;csize=1">http://framework.zend.com/code/changelog/…</a></p>

        </div>
    </div>
    </div>

