<h2>ZF-6013: Zend_Test generates vague failure messages</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-03-12T12:06:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-18T00:55:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Test_PHPUnit</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There was 1 failure:</p>

<p>1) testExpiredPasswordForcesPasswordChange(Default_AuthControllerTest)
Failed asserting last controller used was "auth"</p>

<p>This message could be a lot more explict. e.g. Failed asserting last controller used ("index") was "auth"</p>

<p>The same goes for the redirect failures as well. PHPUnit itself always gives very explicit failure messages - "Failed asserting 0 equals 1".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Till Klampaeckel (till) on 2009-03-30T11:30:15.000+0000</p> 
        <div class="body">
            <p>Matthew,</p>

<p>I could improve these easily. Should I add a patch first here</p>

<p>Till</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-03-30T11:59:11.000+0000</p> 
        <div class="body">
            <p>Till -- yes, please do. Make sure the patch includes changes to the unit tests so I don't have to hunt those down.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-09-18T00:55:22.000+0000</p> 
        <div class="body">
            <p>Fixed and merged into 1.9 release branch.</p>

        </div>
    </div>
    </div>

