<h2>ZF-6746: Cache in Zend_Paginator not working</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-05-20T08:30:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-17T23:15:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.3 (09/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                julien PAULI (doctorrock83)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Paginator makes cache ids from spl_object_hash($this), which changes throught HTTP request making Paginator unable to load its data back from cache, and also making it duplicate them in the cache.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ionut Dinu (tunder) on 2009-05-27T05:47:10.000+0000</p> 
        <div class="body">
            <p>Related to "Zend_Paginator makes cache ids from spl_object_hash($this)":</p>

<p>it gives me same cache id for same adapter made from 2 different Zend_Db_Table_Select objects
to test:</p>

<p>$table = new zend_db_tabe();
$select1 = $table-&gt;select()-where('some_field_1 = ?', 'some value');
$select2 = $table-&gt;select()-where('some_field_1 = ?', 'some other value');</p>

<p>$paginaor = new Zend_Paginator::Factory($select1);
and 
$paginaor = new Zend_Paginator::Factory($select2);</p>

<p>return the same cache id, even though the results of the 2 selects are different.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ionut Dinu (tunder) on 2009-05-28T03:45:32.000+0000</p> 
        <div class="body">
            <p>is it possible to cache the total number of items? I noticed that the select that counts the total number of items that need to be paginated is not cached.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-06-03T14:27:44.000+0000</p> 
        <div class="body">
            <p>Fixed in r15883
Warning, could lead to BC breaks with old cache entries as the tagging system has been reviewed and improved. Tests are welcome</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dane Horak (danehorak) on 2009-06-11T13:17:08.000+0000</p> 
        <div class="body">
            <p>When using Zend_Db_Profiler_Fierbug there are a few properties that store microtime values which when serializing the adapter cause it to produce a different hash value each time. Because this hash value is used to identify what cached data to load, Zend_Cache is unable to find any cache associated to this identifier.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by ivan (ivan.veretelnyk) on 2009-08-17T15:19:56.000+0000</p> 
        <div class="body">
            <p>This cache stuff broken again in 1.9.1
Zend_Paginator_Adapter_DbTableSelect
 public function getItems($offset, $itemCountPerPage)
    {
        echo md5(serialize($this));echo "<br />";
        $this-&gt;_select-&gt;limit($itemCountPerPage, $offset);
        echo md5(serialize($this));echo "<br />";
        return $this-&gt;_select-&gt;getTable()-&gt;fetchAll($this-&gt;_select);
    }</p>

<p>this will show you issue, you will see two different strings and paginator will never load data from cache.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-08-17T23:14:57.000+0000</p> 
        <div class="body">
            <p>Caching in Paginator is relatively tricky, which is one of the reasons why we didn't implement it initially.</p>

<p>ivan: Could you open a new issue for this?</p>

<p>julien: Do you want to look into this? Or shall I give it a go later today?</p>

        </div>
    </div>
    </div>

