<h2>ZF-7256: Cannot redeclare class Zend_Search_Lucene_Search_Query error </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-14T02:10:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Andy Barker (cruxburn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Error occurs on our dev environment (FreeBSD 7.1 using Apache/2.2.9 (FreeBSD) DAV/2 PHP/5.2.8 with Suhosin-Patch)
this error does not occur when running under local development windows environment on ZendServer CE 4.0.3 (Zend-Server-CE-4.0.3RC6-Windows_x86)</p>

<p>upon attempting to open or create an index</p>

<p>...
$luceneIndex = Zend_Search_Lucene::open($indexPath);</p>

<p>or</p>

<p>$luceneIndex = Zend_Search_Lucene::create($indexPath);</p>

<p>in Lucene/Search/QueryParser.php Class file
Any of the Preprocessing classes when required will produce
Fatal error: Cannot redeclare class Zend_Search_Lucene_Search_Query in /home/slweb/ZendFramework/library/Zend/Search/Lucene/Search/Query.php on line 40</p>

<pre><code>/** Zend_Search_Lucene_Search_Query_Preprocessing_Phrase */
require_once 'Zend/Search/Lucene/Search/Query/Preprocessing/Phrase.php';

/** Zend_Search_Lucene_Search_Query_Preprocessing_Term */
require_once 'Zend/Search/Lucene/Search/Query/Preprocessing/Term.php';

/** Zend_Search_Lucene_Search_Query_Preprocessing_Fuzzy */
require_once 'Zend/Search/Lucene/Search/Query/Preprocessing/Fuzzy.php';
</code></pre>

<p>Fix--&gt;
inside Zend/Search/Lucene/Search/Query/Preprocessing.php Class if comment out 
     //require_once 'Zend/Search/Lucene/Search/Query.php'; 
then error is removed</p>

<p>Also in Lucene/Search/QueryParser.php Class file
when QueryParserContext.php Class file is required will produce
Fatal error: Cannot redeclare class Zend_Search_Lucene_Index_Term in /home/slweb/ZendFramework/library/Zend/Search/Lucene/Index/Term.php on line 38</p>

<pre><code>/** Zend_Search_Lucene_Search_QueryParserContext */
require_once 'Zend/Search/Lucene/Search/QueryParserContext.php';
</code></pre>

<p>Fix--&gt;
inside 'Zend/Search/Lucene/Search/QueryEntry/Term.php' and 'Zend/Search/Lucene/Search/QueryEntry/Phrase.php' if comment out
    //require_once 'Zend/Search/Lucene/Analysis/Analyzer.php'; 
then error is removed</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-11-02T05:54:22.000+0000</p> 
        <div class="body">
            <p>This problem may happen if some include path changes are applied during script execution and old and new include path contain different ZF copies. So there are different files (and classes) with the same names.</p>

<p>It seems corresponding classes are loaded by autoloader <em>before</em> include path change, then they are tried to be loaded by corresponding require_once.</p>

<p>Your fix will make Zend_Search_Lucene broken in other environments, so please be careful.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:12.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

