<h2>ZF-7127: Problem with Where-clause in select for paginator</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-25T12:58:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-29T09:00:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
            <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7259">ZF-7259</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Until version 1.8.3 the following code worked perfectly but with the update to ZF 1.8.4 the following error occurs:
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'c.ModuleName' in 'where clause'</p>

<pre><code>    $select = $this-&gt;db-&gt;select();
    $select-&gt;from(array("c" =&gt; "mvc_pagecalls"),
                      array("ModuleName", "ControllerName", "ActionName", "ObjectID"))
           -&gt;group("c.ModuleName")
           -&gt;group("c.ControllerName")
           -&gt;group("c.ActionName")
           -&gt;group("c.ObjectID")
           -&gt;where("c.ModuleName = ?", 'admin');
    $paginator = new Zend_Paginator(new Zend_Paginator_Adapter_DbSelect($select));
    $paginator-&gt;setItemCountPerPage(20);
    $paginator-&gt;setCurrentPageNumber($this-&gt;_getParam("page", 1));
    $this-&gt;view-&gt;paginator = $paginator;
</code></pre>

<p>so i tried to dump the sql-string ($select-&gt;__tostring) and execute it in the phpmyadmin. The query was valid and successful.</p>

<p>So it seems as the version 1.8.4 has a bug in Db_Select or Paginator.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-06-25T14:03:15.000+0000</p> 
        <div class="body">
            <p>Resolved in r16293. Merged to release-1.8 in r16294.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2009-08-23T06:52:16.000+0000</p> 
        <div class="body">
            <p>Same problem occurred to me,  I took the class Zend_Paginator_Adapter_DbSelect of the trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-08-26T07:54:25.000+0000</p> 
        <div class="body">
            <p>Ramon: can you try to reproduce the error and paste the corresponding query?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2009-08-29T09:00:47.000+0000</p> 
        <div class="body">
            <p>Jurrien Stutterheim: error was in version 1.8.4 solved my problem when I took the svn/trunk, and was resolved in version 1.9.</p>

<p>Reported in ZF-7259.</p>

<p>No problem.</p>

        </div>
    </div>
    </div>

