<h2>ZF-7631: Zend_Validate_NotEmpty compatibility</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-18T23:23:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-06-09T05:54:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.2 (25/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Edi Skraba (edspiner)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7449">ZF-7449</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Validate_NotEmpty doesn't accept anything else then string, int, float, bool but it was. Now object, arrays, etc are returnd as "empty"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-18T23:55:20.000+0000</p> 
        <div class="body">
            <p>No they're not.
You should look which sort of failure is returned.</p>

<p>In the above case you get "Invalid type given, value should be float, string, or integer".</p>

<p>I agree that Arrays are missing.
But a object can never be empty.
To check a object for emptyness is quite useless and in my eyes a failure.
Same for ressources.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Edi Skraba (edspiner) on 2009-08-19T01:53:16.000+0000</p> 
        <div class="body">
            <p>About objects:</p>

<p>What if i have such code:</p>

<p>{{$value = ($_POST['value']) ? new Zend_Date($_POST['value']) : null;}}</p>

<p>And im checking:
{{Zend_Validate::is($value,'NotEmpty')}}</p>

<p>I know that i can make a different solution but - as above - i don't know what's the type of $value  - i just wan't to check if it's "NotEmpty".</p>

<p>As You said the objects are never empty so it could bo something like:
{{if(is_object($value)) return true;}}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-19T13:08:38.000+0000</p> 
        <div class="body">
            <p>Fixed...</p>

<p>Allowed arrays. Objects and Ressources are disallowed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Baumann (t11n) on 2010-06-09T05:53:59.000+0000</p> 
        <div class="body">
            <p>Please see ZF-9968</p>

        </div>
    </div>
    </div>

