<h2>ZF-7854: cant create module controller with zf.bat tool</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-16T01:15:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:55.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8305">ZF-8305</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When i want to create module controller with zf.bat i get error</p>

<p>PHP Fatal error:  Call to a member function search() on a non-object in C:\wamp\www\ZendFramework-1.9.2\library\Zend\Tool\Project\Provider\Controller.php on line 104</p>

<p>Fatal error: Call to a member function search() on a non-object in C:\wamp\www\ZendFramework-1.9.2\library\Zend\Tool\Project\Provider\Controller.php on line 104</p>

<p>This happens when we want to create controller on a module which don't exist.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bo?tjan Kristl (bkristl) on 2009-09-16T01:36:33.000+0000</p> 
        <div class="body">
            <p>This happens when we want to create controller on a module which don't exist.</p>

        </div>
    </div>
    </div>

