<h2>ZF-7008: Method setReturnPath() not working</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-06-13T11:02:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-30T00:30:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bogdan Martinescu (yolau)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8988">ZF-8988</a></li>
            <li><a href="/issues/browse/ZF-8273">ZF-8273</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It seems that the method setReturnPath() is not working as it should and is not overwriting the default path.</p>

<p>Code example:</p>

<pre class="highlight"><code>
$reqMail = new Zend_Mail();
$reqMail-&gt;setBodyText($content);
$reqMail-&gt;setFrom("some@email.com", "Name");
$reqMail-&gt;setReturnPath('some@email.com'); 
$reqMail-&gt;setSubject($subject);
$reqMail-&gt;addTo('other@email.com');
$reqMail-&gt;addBcc("anemail@yahoo.com");
$reqMail-&gt;send();
</code></pre>

<p>The result email doesn't have the set ReturnPath.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bogdan Martinescu (yolau) on 2009-06-13T14:45:08.000+0000</p> 
        <div class="body">
            <p>I looked into this for the past hour and I am now not sure if this is considered a bug or no.</p>

<p>Facts: To have a Sendmail keep the ReturnPath you have to send an additional parameter to the PHP mail function, more precise "-femail@address.com"
The send() method from Zend/Mail.php doesn't do that as it calls Zend_Mail_Transport_Sendmail with no parameters to be passed to the PHP function mail().
The workaround to this is to create a Zend_Mail_Transport_Sendmail object with the proper parameter before initiating the Zend_Mail object, but this in my view will need you to set the ReturnPath twice, once in the call $tr = new Zend_Mail_Transport_Sendmail('-femail@domain.com');  and the second time with the setReturnPath("email@domain.com") method from Zend/Mail.php</p>

<p>A better approach would be to change line 949 from the file Zend/Mail.php from:
$transport = new Zend_Mail_Transport_Sendmail();
to:
if (!empty($this-&gt;_returnPath))
                    $transport = new Zend_Mail_Transport_Sendmail("-f" . $this-&gt;_returnPath);
                else
                    $transport = new Zend_Mail_Transport_Sendmail();</p>

<p>This could have a side effect though...If the user runs PHP in safe_mode() and he calls the method setReturnPath from Zend/Mail.php this will ultimately result in a PHP error due to the addition parameter given to the mail() function.</p>

<p>I am looking for your input on this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-09-18T02:39:35.000+0000</p> 
        <div class="body">
            <p>Personally I think setReturnPath() is just wrong on Zend_Mail, it should be a Transport option.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-14T05:15:06.000+0000</p> 
        <div class="body">
            <p>I agree with Benjamin.</p>

<p>I also think _returnPath parameter should be move into parameter of transport.</p>

<p>And it might be better to split Zend_Mail into 3 parts, for example :
Zend_Mail_Sender
Zend_Mail_Server (it would include transport classes)
Zend_Mail_Reader (or _Receiver)</p>

<p>I change this issue into next major.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-11-20T03:56:03.000+0000</p> 
        <div class="body">
            <p>I don't agree with the separation of names, however we should discuss this on the 2.0 Roadmap, can you add a note on the moving of setReturnPath() to the wiki page?</p>

<p><a href="http://framework.zend.com/wiki/display/ZFDEV2/Mail+sending+and+building+enhancements+2.0">http://framework.zend.com/wiki/display/…</a></p>

<p>So we dont forget it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-27T07:07:49.000+0000</p> 
        <div class="body">
            <p>Hi, Benjamin, :D  Sorry for late comment.</p>

<p>Yes I will add some commment the page in this weekend.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-05T20:21:56.000+0000</p> 
        <div class="body">
            <p>I will close once as document issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-06T00:26:41.000+0000</p> 
        <div class="body">
            <p>Soved in SVN trunk r19450</p>

        </div>
    </div>
    </div>

