<h2>ZF-708: Document Gdata delete() method better</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-01-02T14:50:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-01-15T17:11:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the documentation for submitting a delete request through Gdata, the code example says to use the href attribute of a  element in a feed entry.  This is incorrect.  The delete() method takes the id of the entry as its argument.</p>

<p>Please correct the code sample, and write a paragraph to describe explicitly which feed entry element to use for the argument of delete().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-04T09:34:27.000+0000</p> 
        <div class="body">
            <p>Wrote a small amount of new doc in Zend_Gdata-Introduction.xml.</p>

        </div>
    </div>
    </div>

