<h2>ZF-783: Problems with $this-&gt;redirect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-22T10:42:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>After upgrading to 0.7.0 i get the following error when using $this-&gt;_redirect("/"), it used to work fine on earlier versions.</p>

<p>Fatal error: Call to a member function setRedirect() on a non-object in /home/irendon/projects/nofep/Zend_0_7_0/library/Zend/Controller/Action.php on line 520</p>

<p>It seems SetRedirect never gets created in the function.</p>

<p>Thanks,</p>

<p>Ivan</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-22T11:06:03.000+0000</p> 
        <div class="body">
            <p>I suspect the issue is that you are overriding __construct() in your action controller, and the response object is not being set. Lines 519-520 read:</p>

<pre class="highlight"><code>
$response = $this-&gt;getResponse();
$response-&gt;setRedirect($url, $code);
</code></pre>

<p>The error you're getting indicates to me that $response is not a response object -- which would only be the case if you didn't set it in the controller.</p>

<p>If you are overriding __construct() in your action controller, try either renaming the method to init() or doing something like the following:</p>

<pre class="highlight"><code>
public function __construct(Zend_Controller_Request_Abstract $request, Zend_Controller_Response_Abstract $response, array $invokeArgs = null)
{
    parent::__construct($request, $response, $invokeArgs);
    // continue processing
}
</code></pre>

<p>Let me know if none of these solutions work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by irendon (irendon) on 2007-01-22T11:30:36.000+0000</p> 
        <div class="body">
            <p>Thanks for your answer.</p>

<p>Issue has been fixed, please close the ticket.</p>

<p>Ivan.</p>

        </div>
    </div>
    </div>

