<h2>ZF-7217: Zend Session error handler converts too wide array of errors to exceptions</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-07T06:17:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-21T03:21:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7288">ZF-7288</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In PHP 5.3 Zend_Session won't start session because of</p>

<p>Zend_Session::start() - (...)/Zend/Cache/Backend/File.php(Line:961): Error #8192 Function set_magic_quotes_runtime() is deprecated</p>

<p>Zend_Session_Exception::handleSessionStartError() should not handle low-level errors such as E_STRICT or especially E_DEPRECATED in PHP 5.3</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-07-07T06:33:42.000+0000</p> 
        <div class="body">
            <p>Shouldn't this has been spotted by the unittests already?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2009-11-21T03:20:57.000+0000</p> 
        <div class="body">
            <p>Problem resolved in version 1.9.0.</p>

        </div>
    </div>
    </div>

