<h2>ZF-7563: Zend_Session_SaveHandler_DbTable Throws Zend_Db_Table_Select  and Zend_Db_Table_Abstract: errors</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-11T14:03:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-24T06:12:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using version 1.9 trying to save my session into a database I get a couple of errors.</p>

<pre class="highlight"><code>
// set up the session DB Table
         $config = array(
             'name'           =&gt; 'session',
             'primary'        =&gt; 'id',
             'modifiedColumn' =&gt; 'modified',
             'dataColumn'     =&gt; 'data',
             'lifetimeColumn' =&gt; 'lifetime',
             'lifetime'       =&gt; 604800,
             'db'             =&gt; Zend_Registry::get('db_master') 
         );

        //create your Zend_Session_SaveHandler_DbTable and
        //set the save handler for Zend_Session
        Zend_Session::setSaveHandler(new Zend_Session_SaveHandler_DbTable($config));
         
        Zend_Session::start();
</code></pre>

<p>Gives me these errors:
Fatal error: Cannot redeclare class Zend_Db_Table_Select in /Zend/Db/Table/Select.php on line 220</p>

<p>Fatal error: Access to undeclared static property: Zend_Db_Table_Abstract::$_writeClosed in Unknown on line 0</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Periko (perikitown) on 2010-02-23T17:41:38.000+0000</p> 
        <div class="body">
            <p>This is happening almost the same to me when trying to implemenet session handler DBTable.</p>

<p>What did you do in order to avoid theses errors?? I'm following the manual <a href="http://framework.zend.com/manual/en/zend.session.savehandler.dbtable.html">http://framework.zend.com/manual/en/…</a> and I have tried to debug this error without success!</p>

<p>Thank you for any help!</p>

<p>(I'm not sure, Should I had have to clone this issue to get any answer?)
(ZF version: 1.10.0)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-02-24T04:21:04.000+0000</p> 
        <div class="body">
            <p>@Periko 
Please post your code so I try to simulate from it(could post in <a href="http://pastebin.com/">http://pastebin.com/</a>).</p>

<p>Thanks ;).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Joe H (clips401) on 2010-02-24T06:12:10.000+0000</p> 
        <div class="body">
            <p>@Periko,
I have not made any code modifications to get this to work.  I noticed this was happening on my server with CentOS 5 and PHP 5.3.</p>

<p>I ended up reinstalling Cent and re-compiling PHP and this cleared up the strange errors I was getting.  I did not change any code.</p>

<p>I'm still not sure what the root cause of this was.  I racked my brain for a couple of days trying to figure this one out because there is not really a workaround that I know of if you have this issue.  The only thing that worked for me was reinstalling everything on the server, and that cleared it up.</p>

        </div>
    </div>
    </div>

