<h2>ZF-7176: Zend PDF loads Zend_Memory_Container_Locked Object into Properties Array - which may cause fatal error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-01T16:58:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Memory</li>
            <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7177">ZF-7177</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12054/Acrobat-Info.png">Acrobat-Info.png</a></li>
            <li><a href="/issues/secure/attachment/12053/metadata.xmp">metadata.xmp</a></li>
            <li><a href="/issues/secure/attachment/12052/Nonlinear+Interation+Between+Shunting+and+Adaptation+Controls+a+Switch+Between+Integration+and+Coincidence+Detection+2006-3877.pdf">Nonlinear Interation Between Shunting and Adaptation Controls a Switch Between Integration and Coincidence Detection 2006-3877.pdf</a></li>
            <li><a href="/issues/secure/attachment/12051/reproduce.php">reproduce.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have at least one PDF where when loaded by Zend_PDF, Zend_Memory_Container_Locked objects are pulled into the Document Type Dictionary properties array.</p>

<p>Array
(
...
    [SaveStreams] =&gt; Array
        (
            [Q] =&gt; Zend_Memory_Container_Locked Object
                (
                    [value] =&gt;  Q 
                )</p>

<pre><code>        [q] =&gt; Zend_Memory_Container_Locked Object
            (
                [value] =&gt;  q 
            )

    )

[Changes] =&gt; Array
    (
        [0] =&gt; Array
            (
                [Creator] =&gt; SPDF
                [Producer] =&gt; SPDF
                [ModDate] =&gt; D:20060401000353-05'00'
                [CreationDate] =&gt; D:20060401000353-05'00'
            )

        [1] =&gt; Array
            (
                [Version] =&gt; 3.0, SPDF Build Number 1085 for Linux 7, Application Build Date: May 15 2003
                [ModDate] =&gt; D:20060401050353-00'00'
                [Product] =&gt; AppendPro
                [Vendor] =&gt; Appligent
            )

    )
</code></pre>

<p>...
)</p>

<p>If you then modify the properties array, saving crashes with a fatal error.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Hiestand (dimmer) on 2009-07-01T16:59:29.000+0000</p> 
        <div class="body">
            <p>Code sufficient to reproduce the error</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Hiestand (dimmer) on 2009-07-01T17:02:07.000+0000</p> 
        <div class="body">
            <p>PDF through which this bug is reproducible. It does have an atypical properties structure.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Hiestand (dimmer) on 2009-07-01T17:03:19.000+0000</p> 
        <div class="body">
            <p>metadata output from adobe acrobat - may not be useful.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Hiestand (dimmer) on 2009-07-01T17:10:34.000+0000</p> 
        <div class="body">
            <p>Interestingly, Adobe Acrobat ignores the array(s). This also may not be useful.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Hiestand (dimmer) on 2009-07-01T17:11:46.000+0000</p> 
        <div class="body">
            <p>A work-around for this issue is to wipe the metadata and start over from scratch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Hiestand (dimmer) on 2010-04-19T16:12:10.000+0000</p> 
        <div class="body">
            <p>This is still a problem in 1.10.3</p>

<p>error message:
PHP Catchable fatal error: Object of class Zend_Memory_Container_Locked could not be converted to string in /www/ZendFramework/library/Zend/Pdf/Element.php on line 155</p>

        </div>
    </div>
    </div>

