<h2>ZF-7002: Zend_Application_Resource_Modules class_exists shouldn't try to load bootstrap class</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-12T19:28:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-24T20:48:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On line 71, Zend_Application_Resource_Modules checks if the bootstrap class for a specific module is loaded using class_exists. However, the second argument for class_exists isn't set to false. The result is that the autoloader will try to load the bootstrap class automatically. This is not desirable if you don't want to create a bootstrap class for your modules. Also, the resource seems to already be setup to try and load the class if it's not loaded already. Suggested fix:</p>

<p>Change:</p>

<pre class="highlight"><code>
To:
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-06-18T21:09:52.000+0000</p> 
        <div class="body">
            <p>Resolved in r16155 and merged to release-1.8 in r16156</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Miroslav Kubelik (koubel) on 2009-06-20T08:26:08.000+0000</p> 
        <div class="body">
            <p>I think this partially solves ZF-6658.</p>

<p>Maybe same problem with class_exists is in ZF-6672, can you please reassign and fix ZF-6672 also?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Jones (leeked) on 2009-06-24T20:48:34.000+0000</p> 
        <div class="body">
            <p>This fixes ZF-6707 also.</p>

        </div>
    </div>
    </div>

