<h2>ZF-7753: Zend_Rest_Route doesn't accepts 'action' for url assembling</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-09-02T03:35:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-29T19:42:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
            <li>Zend_Rest_Route</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12185/zend_rest_route.diff">zend_rest_route.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Rest_Route doesn't accepts 'action' for url assembling.</p>

<p>E.g.</p>

<pre class="highlight"><code>
$navi = new Zend_Navigation();
$page = Zend_Navigation_Page::factory(array('controller' =&gt; 'page',  'label'    =&gt; 'Pages');
$page2 = Zend_Navigation_Page::factory(array('controller' =&gt; 'page',  'label' =&gt; 'New page', 'action' =&gt; 'new');
$page2-&gt;setParent($page);
$navi-&gt;addPage($page);

Zend_Registry::set('Zend_Navigation', $navi);
</code></pre>

<p>then in the view</p>

<pre class="highlight"><code>
&lt;?=$this-&gt;navigation()-&gt;menu(); ?&gt;
</code></pre>

<p>will result into</p>

<pre class="highlight"><code>
</code></pre><code>
                <a href="/page">Page</a>
                </code><code>
                        <a href="/page">Create new page</a>
                    
                
</code>

<p>Solution:
Modify the assemble() method.</p>

<p>In Zend_Rest_Route, line 248, add:</p>

<pre class="highlight"><code>
if(isset($params[$this-&gt;_actionKey])) {
            $action = $params[$this-&gt;_actionKey];
            if($action === $this-&gt;_defaults[$this-&gt;_actionKey]) {
                $action = '';
            } else {
                $action = '/' . $params[$this-&gt;_actionKey];
            }
        } else {
            $action = '';
        }
</code></pre>

<p>In Zend_Rest_Route, line 261, replace:</p>

<pre class="highlight"><code>
if (!empty($url) || $controller !== $this-&gt;_defaults[$this-&gt;_controllerKey]) {
                $url = '/' . $controller . $url;
}
</code></pre>

<p>with</p>

<pre class="highlight"><code>
$url = '/' . $controller . $action . $url;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alex Zinchenko (admloki) on 2009-09-02T06:26:58.000+0000</p> 
        <div class="body">
            <p>Much elegant solution.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Zinchenko (admloki) on 2009-09-02T06:28:07.000+0000</p> 
        <div class="body">
            <p>Now it's really elegant solution.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-09-02T06:29:18.000+0000</p> 
        <div class="body">
            <p>You need to specify the route with your pages:</p>

<pre class="highlight"><code>
page2 = Zend_Navigation_Page::factory(array('route' =&gt; 'routeName', 'controller' =&gt; 'page',  'label' =&gt; 'New page', 'action' =&gt; 'new');
</code></pre>

<p>and then it should work. I've had success with this approach using the actions "index", "get", "post", "put", and "delete"; I haven't tried "edit" or "new", but both should work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Zinchenko (admloki) on 2009-09-02T07:34:37.000+0000</p> 
        <div class="body">
            <p>My application uses Zend_Rest_Route as default router.
I don't think its because of undefined route name in Zend_Navigation_Page initialization.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Zinchenko (admloki) on 2009-09-02T07:38:51.000+0000</p> 
        <div class="body">
            <p>Matthew, i checked that - solution you provided not working.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Zinchenko (admloki) on 2009-09-02T13:25:32.000+0000</p> 
        <div class="body">
            <p>Found a solution for issue <a href="http://framework.zend.com/issues/browse/ZF-7760">ZF-7760</a>. Please check.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-09-19T15:57:52.000+0000</p> 
        <div class="body">
            <ol><li>Are you absolutely sure you're using a REST route?</li>
<li>Have you tried specifying the route in the page, as Matthew suggests?</li>
<li>If none of the two above work out for you, could you provde minimum code required to reproduce the bug?</li>
</ol>
        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luke Crouch (lcrouch) on 2009-09-29T13:36:41.000+0000</p> 
        <div class="body">
            <p>sorry for the hiatus everyone. busy having a baby. ;)</p>

<p>is this still an issue? reading the comment backlog, I can't tell if Matthew's solution worked or not, and I've never used Zend_Navigation. can someone write a test case that replicates the way Zend_Navigation could/should use the route for pagination url's?</p>

<p>thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-10-16T15:34:06.000+0000</p> 
        <div class="body">
            <p>It's been a few weeks now, so I guess this is not an issue anymore.</p>

<p>Alex: Could you provide a reproducable case?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-10-16T16:58:31.000+0000</p> 
        <div class="body">
            <p>So, after having a hard time to reproduce the behavior I was totally unable to. The code I used:</p>

<pre class="highlight"><code>&lt;?php
error_reporting(E_ALL|E_STRICT);

require_once 'Zend/Navigation.php';
require_once 'Zend/View.php';
require_once 'Zend/Navigation/Page.php';
require_once 'Zend/View/Helper/Navigation.php';
require_once 'Zend/Controller/Front.php';
require_once 'Zend/Controller/Request/Http.php';

Zend_Controller_Front::getInstance()-&gt;getRouter()-&gt;addDefaultRoutes();
Zend_Controller_Front::getInstance()-&gt;setRequest('Zend_Controller_Request_Http');

$navi = new Zend_Navigation();
$page = Zend_Navigation_Page::factory(array('controller' =&gt; 'page',  'label'    =&gt; 'Pages'));
$page2 = Zend_Navigation_Page::factory(array('controller' =&gt; 'page',  'label' =&gt; 'New page', 'action' =&gt; '$
$page2-&gt;setParent($page);
$navi-&gt;addPage($page);

$helper = new Zend_View_Helper_Navigation();
$helper-&gt;setView(new Zend_View());

echo $helper-&gt;menu($navi);
</code></pre>

<p>Therefore closing this issue as cannot reproduce. A next time you create an issue, please make sure to include <em>all</em> relevant code, preferably in a way it can be tested in cli mode. Furthermore it's unclear what the expected outcome of your code is, making it all totally vague.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luke Crouch (groovecoder) on 2009-10-17T13:07:27.000+0000</p> 
        <div class="body">
            <p>Thanks Dolf.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rick Jones (r13ckj) on 2011-01-29T18:59:08.000+0000</p> 
        <div class="body">
            <p>Hi Dolf, I think I'm experiencing the same issue. In your test you're not adding a REST route. Wouldn't that be why you can't reproduce the issue?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rick Jones (r13ckj) on 2011-01-29T19:41:59.000+0000</p> 
        <div class="body">
            <p>Ah! My issue was slightly different - I was using post action in nav conf. Now I understand more about how REST routing works in Zend Framework, I've figured it out. There doesn't appear to be an issue here. As Matthew said it might be a problem by not declaring routes in nav conf.</p>

        </div>
    </div>
    </div>

