<h2>ZF-7445: Zend Tool can't find project profiles on windows</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-02T11:17:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-29T21:38:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Peter Aba (thoer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I was following the ZF beginners guide, and had a lot of frustration because I could not create a new controller at all!</p>

<p>Tracing it back, I found that Zend_Tool_Project_Provider_Abstract was adding an unnecessary DIRECTORY_SEPARATOR at the beginning of each directorynames it generated. Fast solution:
@ line 126</p>

<pre class="highlight"><code>
            $projectDirectoryAssembled = DIRECTORY_SEPARATOR . implode(DIRECTORY_SEPARATOR, $parentDirectoriesArray);
--&gt;
            $projectDirectoryAssembled = implode(DIRECTORY_SEPARATOR, $parentDirectoriesArray);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Tobias (shnapoo) on 2009-08-03T01:54:19.000+0000</p> 
        <div class="body">
            <p>You're a hero!</p>

<p>I stumbled upon the same bug when creating a module on Windows ("project was not found" error message). Applying the fast solution to file</p>

<p>library\Zend\Tool\Project\Provider\Abstract.php</p>

<p>helped immediately.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Peter Aba (thoer) on 2009-08-03T03:40:08.000+0000</p> 
        <div class="body">
            <p>I feel stupid for adding the substr first when I actually described what needs to be done just right, I must have been tired. the DIRECTORY_SEPARATOR is simply not needed on windows systems.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-10T08:45:04.000+0000</p> 
        <div class="body">
            <p>Duplicate of ZF-7465, please see that issue for resolution.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Del Rio (ddelrio1986) on 2009-09-29T21:30:52.000+0000</p> 
        <div class="body">
            <p>I am getting this error with ZF 1.9.3PL1. I created a new project like this:</p>

<p>zf.bat create project</p>

<p>Then I tried to make a module like so:</p>

<p>zf.bat create module user</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Del Rio (ddelrio1986) on 2009-09-29T21:38:19.000+0000</p> 
        <div class="body">
            <p>I added the ZF library folder to my include_path and it seems to work now. Sorry about the false alarm.</p>

        </div>
    </div>
    </div>

