<h2>ZF-7565: Notes of Zend_Config_Ini parameter &quot;allowModifications&quot; is misleading</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-08-11T22:35:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-13T20:50:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.2 (25/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.config.adapters.ini.html#zend.config.adapters.ini.table">http://framework.zend.com/manual/en/…</a></p>

<blockquote>
  <p>allowModifications: Set to TRUE to allow subsequent modification of loaded file.</p>
</blockquote>

<p>I thought wrongly that modifications affect to the file, by calling automatically Zend_Config_Ini_Writer methods.
This is not true.</p>

<p>To be clearer,  you should replace this sentence with something like the following
"Set to TRUE to allow subsequent modification of loaded setting data."</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-08-12T07:31:07.000+0000</p> 
        <div class="body">
            <p>Solved in SVN r17564</p>

        </div>
    </div>
    </div>

