<h2>ZF-711: Unit test failure in Zend/Controller/Request/HttpTest::test__Isset()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-01-03T19:37:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There was 1 failure:</p>

<p>1) test__Isset(Zend_Controller_Request_HttpTest)
Failed asserting that  is identical to .
C:\zf\tests\Zend\Controller\Request\HttpTest.php:162
There was 1 incomplete test:</p>

<p>1) test100Continue(Zend_Http_ResponseTest)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-03T23:08:13.000+0000</p> 
        <div class="body">
            <p>Here's some information about my environment:</p>

<p>PHP 5.2.0 (cli) (built: Nov  2 2006 11:57:36)
Copyright (c) 1997-2006 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2006 Zend Technologies
    with Xdebug v2.0.0RC1, Copyright (c) 2002, 2003, 2004, 2005, 2006, by Derick Rethans</p>

<p>PHP was bundled with XAMPP 1.5.5.
PHPUnit 3.0.0
Operating system: Windows XP SP2
Running tests/AllTests.php from cmd.exe.</p>

<p>I also got the following Notice:</p>

<p>Notice: Undefined index:  PATH in C:\zf\tests\Zend\Controller\Request\HttpTest.php on line 131</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-04T10:00:18.000+0000</p> 
        <div class="body">
            <p>This appeared to be an issue of testing, rather than code -- evidently, 'PATH' doesn't exist in $_ENV on Windows. I setup the tests to grab the first set key in $_ENV and test against that. Please verify that revision 2603 fixes the issue.</p>

        </div>
    </div>
    </div>

