<h2>ZF-7169: Zend_Search_Lucene_Document_Pdf</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-07-01T05:10:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-04T06:05:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ing. Jitka Darbujanova (jitka_sunny)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12512/Pdf.php">Pdf.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This is feature request for such a component.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Nils Caspar (pencil) on 2009-12-10T03:26:24.000+0000</p> 
        <div class="body">
            <p>What's the status?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pedro Pinto (_pn_boy) on 2009-12-15T23:43:15.000+0000</p> 
        <div class="body">
            <p>There seams to be a way to implement this: <a href="http://github.com/philipnorton42/PDFSearch">http://github.com/philipnorton42/PDFSearch</a></p>

<p>not tested ...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pedro Pinto (_pn_boy) on 2009-12-18T01:37:57.000+0000</p> 
        <div class="body">
            <p>Possible solution in attached file</p>

<p>example usage:
        Zend_Loader::loadClass('Zend_Search_Lucene_Document_Pdf');
        $content = Zend_Search_Lucene_Document_Pdf::loadPdfFile('example.pdf');</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by ollie harridge (ollietb) on 2010-03-23T08:42:46.000+0000</p> 
        <div class="body">
            <p>The solution posted here only works with English characters.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Przemek (cojack) on 2011-02-04T06:05:28.000+0000</p> 
        <div class="body">
            <p>In 178 line you are using:</p>

<p>if (substr($chunk["filter"], "FlateDecode") !== false) {</p>

<p>it should be:</p>

<p>f (strpos($chunk["filter"], "FlateDecode") !== false) {</p>

<p>substr as second param gets int not a string. This generate a lot of php warnings.</p>

        </div>
    </div>
    </div>

