<h2>ZF-7293: Zend_Filter_Input mapping key names</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-07-16T02:56:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                -.- (campasau)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter_Input</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be cool to mapping the field names to another name.
Something like this:</p>

<pre class="highlight"><code> 
$filters = array(
  'oldname' =&gt; array(
     'mapping_to' =&gt; 'newname'
  )
);
</code></pre>

<p>Note that you have to name your validators with the 'mapping_to' name.
Here my extended version:</p>

<pre class="highlight"><code> 
My_Filter_Input extends Zend_Filter_Input
{

   const MAPPING_TO = 'mapping_to';

   protected function _filterRule(array $filterRule)
  {
     parent::_filterRule($filterRule);

     $field = $filterRule[self::FIELDS];

     if (!array_key_exists($field, $this-&gt;_data)) {
         return;
     }

     if (isset($filterRule[self::MAPPING_TO])) {
         $this-&gt;_data[$filterRule[self::MAPPING_TO]] = $this-&gt;_data[$field];
         unset($this-&gt;_data[$field]);
     }
  }

}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:52.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

