<h2>ZF-7298: Zend_Controller_Router_Route_Module doesn't have Translate abilities</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-07-17T03:39:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-12T06:52:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12953/Zend_Controller_Router_Route_Module.patch">Zend_Controller_Router_Route_Module.patch</a></li>
            <li><a href="/issues/secure/attachment/12082/Zend_Controller_Router_Route_Module.patch">Zend_Controller_Router_Route_Module.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>You can't translate default Route (Route_Module), because it doesn't have abilities to do it. Additionaly, you can't use other route as default , which can translate, because only Route_Module handle right requests (as /[module/][controller/][action/], where everything is optional, module too).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Kusmierz (raistlin) on 2009-07-17T03:43:09.000+0000</p> 
        <div class="body">
            <p>Default, my patch doesn't change anything. If you change default route to something like:</p>

<pre><code>'default' =&gt; array(
    'type' =&gt; 'Zend_Controller_Router_Route_Module',
    'dispatcher' =&gt; null,
    'request' =&gt; null,
    'translatable' =&gt; true
)
</code></pre>

<p>you get abilities to translate default route. I think there should be also static method changing this ability (ie. Zend_Controller_Router_Route_Module::setTranslate(bool); )</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-17T04:41:42.000+0000</p> 
        <div class="body">
            <p>Deleting Zend_Translate as effected component because this is no Zend_Translate issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hugo (huhu) on 2010-03-27T03:51:30.000+0000</p> 
        <div class="body">
            <p>The provided patch does not work correctly when matching translated modules. I adapted it so that it also correctly handles translated module names and attached a new patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hugo (huhu) on 2010-03-27T03:52:20.000+0000</p> 
        <div class="body">
            <p>This patch replaces the previous one, which did not match translated module names.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoit Sagols (bsagols) on 2010-05-18T04:19:10.000+0000</p> 
        <div class="body">
            <p>hi, do we know in which release the patch will be included?
Is the patch safe for production environment?
thx - benoit</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoit Sagols (bsagols) on 2010-05-31T07:43:05.000+0000</p> 
        <div class="body">
            <p>Hi
I'm using the patch in production, so far so good.
I had to make a little change in the code although. Instead of defaulting _translatable to false in the __contruct method, I've set it to true and now everything works fine. I don't quite undestancd what _translatable is for...</p>

<p>As in Zend_Controller_Router_Route_Module patch, this is set to false in the constructor and never again manipulated afterwards... On the contrary in Zend_Controller_Router_Route, the similar variable _translatable is initialized in the contructor, looking for segments to translate in the url (looking for "@" sign...).</p>

<p>Hope this helps.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert (rs) on 2010-06-11T09:44:05.000+0000</p> 
        <div class="body">
            <p>hi,</p>

<p>this issue exists nearly a year, an nobody seems really to care.</p>

<p>i don't get it, actually this is a basic functionality and should be handled on major priority.</p>

<p>I also posted a, from my perspective, major issue affecting the basic JSON serialization.  (<a href="http://framework.zend.com/issues/browse/ZF-9416">http://framework.zend.com/issues/browse/ZF-9416</a>) This was fixed after nearly 3 month. This is a completely unacceptable timeframe for every kind of project.</p>

<p>I don't know if you guys are payed by zend or if you doing it for fun in your freetime, but by next project will not base on the ZF.</p>

<p>br
robert</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hugo (huhu) on 2011-02-12T06:52:39.000+0000</p> 
        <div class="body">
            <p>When is this going to be fixed? It does not only affect version 1.8.4, but all version up to and including 1.11.3.</p>

        </div>
    </div>
    </div>

