<h2>ZF-7589: Zend_Date::setDate when parsing the date to set in an array</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-13T16:04:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-14T14:56:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.2 (25/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Björn Graf (bjoern)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12140/Zend_Date.setDate-with-array.patch">Zend_Date.setDate-with-array.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using Zend_Date::setDate with the date to set in an array throws an exception in Zend/Date.php, line 2846 due to the use of an undefined variable in the if clause.</p>

<p>The simple test below demonstrates the problem.</p>

<p>The expected result of this test is to pass, the actual result is a Zend_Date_Exception with the message "no day,month or year given in array".</p>

<pre class="highlight"><code>
public function testSetDateWithArray()
{
    $locale = new Zend_Locale('en-US');
    $date = new Zend_Date(1234567890, null, $locale);

    $array = array('year' =&gt; 2009, 'month' =&gt; 8, 'day' =&gt; 14);
    $result = $date-&gt;setDate($array, null, $locale);

    $this-&gt;assertSame('2009-08-14T04:31:30+05:00', $result-&gt;get(Zend_Date::W3C));
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Björn Graf (bjoern) on 2009-08-13T16:06:04.000+0000</p> 
        <div class="body">
            <p>This patch contains a fix for the problem and the test to verify its correctness.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-14T14:55:07.000+0000</p> 
        <div class="body">
            <p>Fixed with r17607</p>

        </div>
    </div>
    </div>

