<h2>ZF-7130: Zend Translate Adapter folder scan issue for variable strlen locale folders</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-25T21:54:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-11T08:02:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8286">ZF-8286</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Problem with using variable string length folder names when scanning the translate folder.</p>

<p>e.g. 
$translate = new Zend_Translate('array',
    $this-&gt;_root . '/data/locale/translate',
    'en_GB',
    array(
        'scan' =&gt; Zend_Translate::LOCALE_DIRECTORY
    )
);
It scans through the directory alphabetically, but ignores valid directories that are of shorter string length than the previously matched directory.</p>

<p>Zend_Translate_Adapter line 159:</p>

<p>if (strlen($prev) &lt;= strlen($file)) {</p>

<p>e.g:
path/to/translate/en
path/to/translate/en_GB
path/to/translate/ja</p>

<p>ignores 'ja'. manually added required translation files (old method) for now.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-25T12:55:27.000+0000</p> 
        <div class="body">
            <p>Fixed with r17813</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Baumann (t11n) on 2009-11-11T06:18:45.000+0000</p> 
        <div class="body">
            <p>Fix has not been released yet. In ZF 1.9.5, I still have the problem. See my Issue #8286.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-11T08:02:54.000+0000</p> 
        <div class="body">
            <p>You may note that this issue is marked as "fixed with next minor release".
This means 1.10.</p>

<p>When you are in need of this code then you must use SVN trunk.</p>

        </div>
    </div>
    </div>

