<h2>ZF-768: Automatically fix invalid property keys</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-01-18T15:42:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Rob Allen (rob)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Morph Zend_Config::_isValidKeyName() into Zend_Config::_formatKey() where _formatKey() works very similar to Zend_Dispatcher::_formatName().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2007-02-28T14:41:07.000+0000</p> 
        <div class="body">
            <p>Not going to fix this as it breaks predictability.</p>

<p>At the moment, you get an exception if a key is invalid which tells you what happened. If we automatically morphed it into it into a valid key, it would require the user to work out that the key name has been changed by the class and no notification has been given.</p>

        </div>
    </div>
    </div>

