<h2>ZF-7732: Zend_Pageinator : clearPageItemCache()'s var &quot;$cleanTags&quot; is not required.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-31T06:38:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-06-02T23:12:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.6 (22/Jun/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kazusuke Sasezaki (sasezaki)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1.8.0 or over : Zend_Pageinator's method clearPageItemCache() has this code.</p>

<p>$cleanTags = self::CACHE_TAG_PREFIX;</p>

<p>I think that there is no reason, and removing it is better.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

