<h2>ZF-7500: Zend_Locale::setDefault throws Exception with broken string</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-06T02:45:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-09T01:18:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.1 (11/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When providing an invalid locale code (for instance "en-US" instead of "en_US"), Zend_Locale::setDefault throws the exception with text "Unknown locale 'Array' can not be set as default!".</p>

<p>It should state the unknown locale to pinpoint the issue.</p>

<pre class="highlight"><code>$locale = explode('_', (string) $locale); // $locals now contains an array
            
if (isset(self::$_localeData[$locale[0]]) === true) {
  self::$_default = array($locale[0] =&gt; $quality);
} else {
  require_once 'Zend/Locale/Exception.php';
  throw new Zend_Locale_Exception("Unknown locale '" . (string) $locale . "' can not be set as default!"); // casting array to string results in "Array"
}</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-09T01:18:31.000+0000</p> 
        <div class="body">
            <p>Fixed with r17478</p>

        </div>
    </div>
    </div>

