<h2>ZF-7578: Zend_Mail bug: Html mail does not work in apple mail</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-12T19:31:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-19T05:23:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I try to send a html email like that:</p>

<hr /><p>$mailer = new Zend_Mail('utf-8'); 
$mailer-&gt;addTo(...); 
$mailer-&gt;setSubject(...); 
$mailer-&gt;setBodyHtml('.....', 'utf8');<br />
$mailer-&gt;setFrom(...);</p>

<h2>$mailer-&gt;send();</h2>

<p>When i receive this mail in gmail everything is good i can see html page.
But when i receive this mail using apple mail i see the html content becoming an attachment.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (GIATA mbH) (mben) on 2009-10-02T03:11:43.000+0000</p> 
        <div class="body">
            <p>Hi</p>

<p>Currently I had a similar problem with Windows Live Mail 2008/9 but after testing many different configuration I could fix it:
-&gt; mail.add_x_header = Off in php.ini</p>

<p>I don't no if this was the bug described here "http://bugs.php.net/bug.php?id=48620" or if this is an bug/feature of the Mail Client.
But if it is activated the Client breaks parsing Mail after this Header and display the source starting on this position.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-04T23:43:18.000+0000</p> 
        <div class="body">
            <p>Hi, xinghao.</p>

<p>Do you use Chinese language with Zend_Mail? If so , I will be happy if you try followings.</p>

<p>1)
set encoding hz-gb-2312 (GB2312) or Big5 instead of UTF-8 to Zend_Mail().</p>

<p>2)
setBodyText(mb_convert_encoding($txt, 'YOUR ENCODING', mb_detect_encoding($txt)) , $charset , $encoding );</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-01-19T05:23:14.000+0000</p> 
        <div class="body">
            <p>I will close this because no responce for one month or more.
It seems to be client-dependent problem for me.</p>

        </div>
    </div>
    </div>

