<h2>ZF-7708: Zend_Db_Statement calls _prepare() but is not part of the interface or abstract</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-27T14:46:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-27T15:05:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>to Zend_Db_Statement:</p>

<pre class="highlight"><code>

    /**
     * Internal method called by abstract statment constructor to setup
     * the driver level statement
     * 
     * @return void
     */
    protected function _prepare($sql)
    {
        return;
    }

</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-27T15:05:36.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk in r17856 and in branch release 1.9 in r17858</p>

        </div>
    </div>
    </div>

