<h2>ZF-7896: Does zend_rest_route respect RESTful protocol stand</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-19T08:40:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-30T10:49:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.7 (11/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                jean-rubin (jrleonard)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Luke Crouch (lcrouch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Route</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi, 
from my understanding of RESTful protocol, the server side is supposed to accept a request like this:
/REST/1
It should also be able to interpret 
/REST/?id=1 or /REST/type="x"</p>

<p>In the current implementation however we can only do the first kind of url. Is it up to us to test for is sent and act accordingly?
JR</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-09-19T09:21:36.000+0000</p> 
        <div class="body">
            <p>Typically, ReST says that there should be a <em>single</em> URI for any given resource, and that it should be returned in the Location header on successful creation. While it may be useful to support both styles, it would also add significant complexity for very little benefit.</p>

<p>Luke, any thoughts on this?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luke Crouch (lcrouch) on 2009-09-19T17:04:50.000+0000</p> 
        <div class="body">
            <p>You should already be able to send a request like:</p>

<p>/REST/?id=1</p>

<p>If that's not working, it's a bug and I'll fix it.</p>

<p>As for the other URI, it could (and probably should?) be expressed:</p>

<p>/REST/type/x</p>

<p>I'd like to see the context for an identifier like /REST/type="x". I've never seen query params supplied like that without a '?' character in a URI.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by jean-rubin (jrleonard) on 2009-09-20T04:16:41.000+0000</p> 
        <div class="body">
            <p>In the case you have a table like
ID     name type
1  bar type1
2 baz type2
3 foo type2
4 bat type1</p>

<p>/rest/1 should give you the data pertaining to the row with id 1 and so on.
/rest/?id=1  should give the same as /rest/1 but currently that doesn't work (I have build 18038)</p>

<p>/rest/?type=2, which I figure should return 2 baz type2 and 3 foo type2 doesn't work either but I suspect it might not be RESTful. I was just looking for confirmation. 
JR</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luke Crouch (lcrouch) on 2009-09-22T09:51:42.000+0000</p> 
        <div class="body">
            <p>Ah, in that case if you want to return more than one resource, Zend_Rest_Route and Zend_Rest_Controller are designed to do so like this:</p>

<p>/rest/index/type/type2</p>

<p>Which will route to RestController::indexAction() with type=&gt;type2 parameter, which you can then use to query the DB where type = 'type2' and go from there.</p>

<p>I'll recreate a test for the /rest/?id=1 and try to get that fixed. In the meantime, try using /rest/1</p>

<p>Thanks,
-L</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luke Crouch (lcrouch) on 2009-12-30T10:49:08.000+0000</p> 
        <div class="body">
            <p>Fixed support for ?param=value query param values.</p>

        </div>
    </div>
    </div>

