<h2>ZF-7288: Zend_Session::start overwrites error handler to test if session start failed</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-15T12:44:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-15T14:23:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
            <li>FixForZF1.12</li>
            <li>zf-crteam-review</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7217">ZF-7217</a></li>
            <li><a href="/issues/browse/ZF-12111">ZF-12111</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think it is better to check this by using error_get_last (<a href="http://de.php.net/manual/en/function.error-get-last.php">http://de.php.net/manual/en/…</a>)
and since PHP 5.3 you can simply check the return value of session_start.</p>

<p>This could be the new session_start check</p>

<pre class="highlight"><code>
if (version_compare(PHP_VERSION, '5.3.0', '&lt;')) {
    $errBefore = error_get_last();
    @session_start();
    $errAfter = error_get_last();
    if ($errBefore != $errAfter) {
        throw new Zend_Session_Exception('Failed to start session: ' . $errAfter['message']);
    }
} else {
    if (@session_start() === false) {
        $errLast = error_get_last();
        throw new Zend_Session_Exception('Failed to start session: ' . $errLast['message']);
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2009-07-15T12:58:44.000+0000</p> 
        <div class="body">
            <p>ZF-7288 would fix ZF-7217, too</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Goran Juric (gog) on 2009-11-12T14:54:48.000+0000</p> 
        <div class="body">
            <p>As much as I can see from the PHP docs, there is no need for error suppression in the else block.</p>

<p>session_start() returns either true or false in PHP 5.3</p>

<p>I guess this is not the only thing that should change with 5.3 becoming more and more popular. I think there should be a single place where we could document issues like this one, so once the 5.3 becomes a requirement for running ZF we can get rid of the BC code.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-31T14:25:46.000+0000</p> 
        <div class="body">
            <p>But it restores the error handler right after:</p>

<pre class="highlight"><code>
if (self::$_throwStartupExceptions) {
    require_once 'Zend/Session/Exception.php';
    set_error_handler(array('Zend_Session_Exception', 'handleSessionStartError'), $errorLevel);
}

$startedCleanly = session_start();

if (self::$_throwStartupExceptions) {
    restore_error_handler();
}
</code></pre>

<p>So I don't see what the issue is.  Could someone provide an example of why this behavior is bad/wrong?</p>

        </div>
    </div>
    </div>

