<h2>ZF-7161: Class does not load with Zend framework 1.8.4</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-30T02:15:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-31T21:10:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gaurav Priyadarshi (gauravp)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12049/amf_config.ini">amf_config.ini</a></li>
            <li><a href="/issues/secure/attachment/12050/EmployeeService.php">EmployeeService.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>We use the following gateway to handle the amf requests:</p>

<pre class="highlight"><code>
&lt;?php
ini_set("display_errors", 1);
$dir = dirname(__FILE__);
$webroot = $_SERVER['DOCUMENT_ROOT'];
$configfile = "$dir/amf_config.ini";

//default zend install directory
$zenddir = $webroot. '/ZendFramework/library';

//Load ini file and locate zend directory
if(file_exists($configfile)) {
    $arr=parse_ini_file($configfile,true);
    if(isset($arr['zend']['zend_path'])){
        $zenddir = $arr['zend']['zend_path'];
    }
}


// Setup include path
    //add zend directory to include path
set_include_path(get_include_path().PATH_SEPARATOR.$zenddir);
// Initialize Zend Framework loader
require_once 'Zend/Loader/Autoloader.php';
Zend_Loader_Autoloader::getInstance();
// Load configuration
$default_config = new Zend_Config(array("production" =&gt; false), true);
$default_config-&gt;merge(new Zend_Config_Ini($configfile, 'zendamf'));
$default_config-&gt;setReadOnly();
$amf = $default_config-&gt;amf;

// Store configuration in the registry
Zend_Registry::set("amf-config", $amf);
// Initialize AMF Server
$server = new Zend_Amf_Server();
$server-&gt;setProduction($amf-&gt;production);
if(isset($amf-&gt;directories)) {
    $dirs = $amf-&gt;directories-&gt;toArray();
    foreach($dirs as $dir) {
        $server-&gt;addDirectory($dir);
    }
}

// Initialize introspector for non-production
if(!$amf-&gt;production) {
    $server-&gt;setClass('Zend_Amf_Adobe_Introspector', '', array("config" =&gt; $default_config, "server" =&gt; $server));
    $server-&gt;setClass('Zend_Amf_Adobe_DbInspector', '', array("config" =&gt; $default_config, "server" =&gt; $server));
}
// Handle request
echo $server-&gt;handle();
</code></pre>

<p>With Zend framework 1.8.3 this works fine, but with Zend Framework 1.8.4, we receive the following error:</p>

<pre class="highlight"><code>
Server error Class "EmployeeService" does not exist 
#0 C:\wamp\www\ZendFramework\library\Zend\Amf\Server.php(540): Zend_Amf_Server-&gt;_dispatch('count', Array, 'EmployeeService') 
#1 C:\wamp\www\ZendFramework\library\Zend\Amf\Server.php(616): Zend_Amf_Server-&gt;_handle(Object(Zend_Amf_Request_Http)) 
#2 C:\wamp\www\TestZend184-debug\gateway.php(49): Zend_Amf_Server-&gt;handle() 
#3 {main} 
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-06-30T09:49:41.000+0000</p> 
        <div class="body">
            <p>Please attach config file and describe where EmployeeService class is.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gaurav Priyadarshi (gauravp) on 2009-06-30T11:13:25.000+0000</p> 
        <div class="body">
            <p>the amf_config.ini file</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gaurav Priyadarshi (gauravp) on 2009-06-30T11:15:37.000+0000</p> 
        <div class="body">
            <p>Find the attached files.
amf_config_ini file resides in the same dir as the gateway file.
EmployeeService.php resides under services folder under this directory.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-06-30T16:56:36.000+0000</p> 
        <div class="body">
            <p>I think I know what the problem is. For some reason in 1.8.4 package there's an old version of Zend/Loader/PluginLoader.php. Take the new one here:</p>

<p><a href="http://framework.zend.com/svn/framework/standard/branches/release-1.8/library/Zend/Loader/PluginLoader.php">http://framework.zend.com/svn/framework/…</a></p>

<p>It should work with it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-07-31T21:10:51.000+0000</p> 
        <div class="body">
            <p>It seems to be solved at 1.8.4PL</p>

        </div>
    </div>
    </div>

