<h2>ZF-701: When encoding a float the &quot;.&quot;-character should always be used as decimalpoint.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-12-29T18:26:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Emil Hesslow (wizkid)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Json</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The decimalpoint should always be a "."-character when encoding a float because if I use floats in an array it could become {"float":5,6,"float2":56,66} which is not good.</p>

<p>I think the reason that I see this is because I use swedish locale and in Sweden we use the ","-character as decimalpoint.</p>

<p>The easiest solution I found was to change row 213 in Encoder.php from:
$result = (string)$value;
to
$result = (string)str_replace(',', '.', $value);</p>

<p>Not sure if that is the way to do it but it works for me.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-04-02T13:49:45.000+0000</p> 
        <div class="body">
            <p>The notation you provide is invalid javascript anyways, due to the extra commas used in a list context -- I have yet to find a js implementation that can parse it.</p>

<p>BTW, ext/json will actually decode this to NULL as it is unable to parse it.</p>

        </div>
    </div>
    </div>

