<h2>ZF-7807: Zend_Db_Adapter_Pdo: oci : function describeTable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-09T04:34:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-19T10:15:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.6 (24/Nov/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The left join from all_cons_columns to all_constraints does not include the owner.</p>

<p>This creates a cartesian product if there are more than one identical db-schemes installed in one Database (i.e. two different test schemes in one Database).</p>

<p>It may also give wrong results, if the constraint does exist in one scheme and is missing in the other.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-11-19T10:15:14.000+0000</p> 
        <div class="body">
            <p>Fixed with r19047
Reported to 1.9 branch with r19048</p>

        </div>
    </div>
    </div>

