<h2>ZF-786: Dispatcher should throw Zend_Controller_Disptacher_Exception if controllerfile not found</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-23T02:11:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Maier (daimaju)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10230/patch1.patch">patch1.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,
at the moment Zend_Controller_Dispatcher throws a Zend_Exception when calling dispatch() and the controllerfile doesn't exist.
In Version 0.6 it used to throw Zend_Controller_Dispatcher_Exception and I think it should keep doing that ;-)</p>

<p>Also I'd like to mention that the "lazy loading" of Zend/Controller/Dispatcher/Exception.php makes no sense, as it is required at the top of the file. But that's not very important I guess :-)</p>

<p>Regards
 Michael</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michael Maier (daimaju) on 2007-01-23T02:14:36.000+0000</p> 
        <div class="body">
            <p>Attached patch, as pasting it messed it up..</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michael Maier (daimaju) on 2007-01-23T02:33:20.000+0000</p> 
        <div class="body">
            <p>Please remove the attached patch, as its not working..</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-25T09:05:18.000+0000</p> 
        <div class="body">
            <p>Assign to Matthew.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-25T16:23:08.000+0000</p> 
        <div class="body">
            <p>This behaviour makes sense -- we're not catching and re-throwing the exception thrown by Zend::loadClass() -- as this is not a dispatcher issue, but a class loading issue.</p>

<p>The extraneous includes at the top of the class have been removed as of revision 3004.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-29T09:12:11.000+0000</p> 
        <div class="body">
            <p>Inability to load an action controller class via Zend::loadClass() is not a dispatcher issue, but rather a problem with the userland class/file naming conventions.</p>

<p>One note, however: isDispatchable() has been modified to check and see if a class file is readable; dispatch() checks that a class isDispatchable() prior to calling loadClass(), and throws an exception if it that check fails. So, a fix is present, but was not targeted at this issue</p>

        </div>
    </div>
    </div>

