<h2>ZF-7233: Zend_InfoCard_Exception_Abstract declared twice in Zend/InfoCard/Exception.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-07-09T08:16:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_InfoCard</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_InfoCard_Exception_Abstract  declared twice:
{quote} 
if (class_exists("Zend_Exception")) {
    abstract class Zend_InfoCard_Exception_Abstract extends Zend_Exception
    {
    }
} else {
    abstract class Zend_InfoCard_Exception_Abstract extends Exception
    {
    }
}
{quote}</p>

<p>Proposed substitution:
{quote} 
if (!class_exists("Zend_Exception")) {
    require_once 'Zend/Exception.php';
}</p>

<p>abstract class Zend_InfoCard_Exception_Abstract extends Zend_Exception   {   }
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by John Coggeshall (coogle) on 2009-07-10T00:03:59.000+0000</p> 
        <div class="body">
            <p>This is intentional, as the Zend_InfoCard component is shipped separately from Zend Framework as a whole and thus the Zend_Exception class is not always available.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ben Scholzen (dasprid) on 2009-07-29T12:38:07.000+0000</p> 
        <div class="body">
            <p>Well, but this is currently against the coding standard, and Zend_Infocard could, just like the other standalone package Zend_Amf, ship Zend_Exception with it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-29T12:40:49.000+0000</p> 
        <div class="body">
            <p>Also Zend_Gdata is shipped as standalone package with Zend_Exception and does not use such a switch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tobias Gies (tobias) on 2009-07-29T12:40:56.000+0000</p> 
        <div class="body">
            <p>I agree with Ben on this. Shipping Zend_Exception with Zend_InfoCard does neither hurt performance nor add significant size to the download, and keeping consistence with the other standalone component can't be too bad either. Violating the CS for something as trivial as an Exception class ain't worth it imho.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:16.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

