<h2>ZF-7343: Problem deserializing multiple calls</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-21T14:47:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There still seem to be issues with the deserialization of multiple simultaneous calls as I still get a 'Net.Connection.Error'
if multiple calls are made (I just upgraded ZendAMF to 1.8.4PL1).</p>

<p>My setup: I'm calling my web service from Flex with a NetConnection call. The web service is implemented
with the Kohana framework. Using the ZendAmf component works great except for this flaw.</p>

<p>The Flex application makes 4 calls with the following parameters
1 - Object (String, String, String, String)
2 - String
3 - String
4 - String</p>

<p>The Request-&gt;readMessage() method recognizes 4 bodies and fails when reading the 3rd as $data (around line 185 in Request.php) is an empty array.</p>

<p>I have changed the sequence in which these calls are made and the error goes away if the call with the Object is the last. Unfortunately I can not force this
sequence as the components making these calls can be arranged in an arbitrary sequence.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:39.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

