<h2>ZF-7356: Invalid timezone in supplementalData.xml</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-22T16:43:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-26T14:28:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.1 (11/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It version 1.9.0a1 it seems that there is a problem with Zend/Locale/Data/supplementalData.xml</p>

<p>Line 3763 is</p>

<p></p>

<p>but should be</p>

<p></p>

<p>I found the problem by running the following.</p>

<p>Zend_Locale::clearCache();
$date = new Zend_Date();
foreach (Zend_Locale::getTranslationList('TimezoneToWindows') as $name =&gt; $timezone) {
    $date-&gt;setTimezone($timezone);
}</p>

<p>Throws an exception: Fatal error:  Uncaught exception 'Zend_Date_Exception' with message 'timezone (Africa/Reykjavik) is not a known timezone'</p>

<p>Thrown in ZendFramework-1.9.0a1/library/Zend/Date/DateObject.php on line 1004</p>

<p>This doesn't appear to be a problem in 1.8.4PL1</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-07-22T17:57:08.000+0000</p> 
        <div class="body">
            <p>Reykjavik in Africa, that will heat up some things :D</p>

<p>All the files in that Data/ directory are CLDR files. We are not allowed to edit them, so you should probably file an issue at the CLDR issue tracker.</p>

<p>I'm leaving this issue open to let Thomas Weidner decide what should be further done with it ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-25T10:23:23.000+0000</p> 
        <div class="body">
            <p>This problem is not a ZF issue it's a CLDR issue (the I18n database ZF is using).</p>

<p>Please commit a issue to CLDR (<a href="www.unicode.org/cldr">www.unicode.org/cldr</a>) as we're not allowed to deliver changed 
database content.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dylan Arnold (dtron) on 2009-07-26T14:28:27.000+0000</p> 
        <div class="body">
            <p>I just checked version 1.7.1 of the CLDR and it appears to be fixed.</p>

        </div>
    </div>
    </div>

