<h2>ZF-7932: Zend Mail will add a &quot;= &quot; in the subject, if subject contains unpritable characters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-23T04:59:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-24T17:33:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
$mail = new Zend_Mail("UTF-8");
$mail-&gt;setFrom($senderEmail, $senderName);

$mail-&gt;addTo('xxx@xxx.com');
$mail-&gt;setSubject("Inloggningsuppgifter till PriceRunners Återförsäljargränssnitt");
$mail-&gt;setBodyHtml("<b>Inloggningsuppgifter till PriceRunners Återförsäljargränssnitt</b>\n");
</code></pre>

<p>I will get the email with the subject  "Inloggningsuppgifter till  PriceRunners  Återförsäljargr= nssnitt"</p>

<pre class="highlight"><code>
protected function _encodeHeader($value)  {
      if (Zend_Mime::isPrintable($value)) {
          return $value;
      } else {
          $quotedValue = Zend_Mime::encodeQuotedPrintable($value);
          $quotedValue = str_replace(array('?', ' ', '_'), array('=3F', '=20', '=5F'), $quotedValue);
          return '=?' . $this-&gt;_charset . '?Q?' . $quotedValue . '?=';
      }
}
</code></pre>

<p>The Zend_Mime::encodeQuotedPrintable($value);    but havnt give the function the second parameter
or else the system will add  "=\n"   at position 74</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-09-24T11:16:12.000+0000</p> 
        <div class="body">
            <p>seriously 1.6.2? please upgrade to at least 1.8.4 this issue should be fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-09-24T17:33:37.000+0000</p> 
        <div class="body">
            <p>I tried to reproduce using trunk (somewhere near-updated) and was not able to reproduce the issue.  Meaning the subject did contain a lot of =-characters, but all according to the specs, given the fact that my client (kmail in this case) did not display any of them. Please note that a lot of effort has been put in utf8 and zend_mail recently, and that you should probably upgrade if you encounter this problem (or try backporting zend_mail).</p>

        </div>
    </div>
    </div>

