<h2>ZF-7162: Zend_Db_Table_Row should only update modified fields</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-06-30T05:00:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sven Franke (snefit)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When changing a value in a Zend_Db_Table_Row it is always set as a modified field so it is always issued in an update.</p>

<p>I think that it can be improved by checking the value with the _cleanData to see if it is modified (to another value than the original).</p>

<p>Original:</p>

<pre class="highlight"><code>
    public function __set($columnName, $value)
    {
        $columnName = $this-&gt;_transformColumn($columnName);
        if (!array_key_exists($columnName, $this-&gt;_data)) {
            require_once 'Zend/Db/Table/Row/Exception.php';
            throw new Zend_Db_Table_Row_Exception("Specified column \"$columnName\" is not in the row");
        }
        $this-&gt;_data[$columnName] = $value;
        $this-&gt;_modifiedFields[$columnName] = true;
    }
</code></pre>

<p>Suggested:</p>

<pre class="highlight"><code>
    public function __set($columnName, $value)
    {
        $columnName = $this-&gt;_transformColumn($columnName);
        if (!array_key_exists($columnName, $this-&gt;_data)) {
            require_once 'Zend/Db/Table/Row/Exception.php';
            throw new Zend_Db_Table_Row_Exception("Specified column \"$columnName\" is not in the row");
        }
        $this-&gt;_data[$columnName] = $value;
        
        if ($value === $this-&gt;_cleanData[$columnName]) {
            if (isset($this-&gt;_modifiedFields[$columnName])) {
                unset($this-&gt;_modifiedFields[$columnName]);   
            }
        } else {
            $this-&gt;_modifiedFields[$columnName] = true;
        }
    }
</code></pre>

<p>In this case the field is only 'modified' when it is not the same as the original value (in _cleanData).</p>

<p>Why? I know you only need to set the real modified fields to the row but sometimes it is more convieniant to update the complete row with setFromArray even when not all fields are changed.</p>

<p>The created query is smaller because only the real modified fields are used in the query.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marcus Welz (lucidix) on 2009-08-14T13:24:48.000+0000</p> 
        <div class="body">
            <p>This ticket has my vote. I've been trying to come up with instances where you don't want that. I guess one is when you use timestamps in mysql -- unless you specify the value explicitly (such as the timestamp it already contained which, using this patch, you can't) it'll update the column to the current time.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sven Franke (snefit) on 2009-08-14T13:46:05.000+0000</p> 
        <div class="body">
            <p>Thanks for voting....</p>

<p>IMHO I think that the timestamp field isn't an issue, it is how MySQL uses the timestamp field. If you don't specify an value, it will update to the current time.</p>

<p>I've used similar solutions like the suggested one in several projects when not using ZF. I think it is not efficient to update all fields when you only want to update a single or some fields ;)</p>

<p>I hope this will get into the next release....</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Timon Zielonka (zukunft) on 2010-03-24T05:16:43.000+0000</p> 
        <div class="body">
            <p>Thanks for this suggestion.</p>

<p>I think, in ZF 1.10.2 the modification must be done in Zend_Db_Table_Row_Abstract.php.</p>

        </div>
    </div>
    </div>

