<h2>ZF-7060: Usage of Zend_Wildfire is not documented</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-06-20T15:08:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-09T17:34:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christoph Dorn (cadorn)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Wildfire</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It seems that only  zend_wildfire's page in the reference guide only describes where the component is used by other components in ZF. It does not at all explain how to use the component yourself, which seems pretty useful to know to me ;)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoph Dorn (cadorn) on 2009-06-20T15:22:44.000+0000</p> 
        <div class="body">
            <p>I am currently working on expanding the features and API of Zend_Wildfire. Once this is done I will be including full documentation.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christoph Dorn (cadorn) on 2010-10-09T17:34:27.000+0000</p> 
        <div class="body">
            <p>This needs to be discussed in light of ZF 2.</p>

<p>The original goal was to provide only support for the log writer and DB profiler. There is a lot of room for expansion to include other components.</p>

<p>Zend_Wildfire needs to be refactored slightly to take advantage of new features developed with FirePHP 1.0. I would want to do the refactoring before documenting the API. This was always planned which is why documentation was omitted.</p>

        </div>
    </div>
    </div>

