<h2>ZF-7004: Add Ec2 Elastic Load Balancing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-06-13T03:31:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jon Whitcraft (sidhighwind)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon_Ec2</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7005">ZF-7005</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add the new Ec2 Elastic Load Balancing Support to the Ec2 Component.</p>

<p>Dev Guide: <a href="http://docs.amazonwebservices.com/ElasticLoadBalancing/latest/DeveloperGuide/">http://docs.amazonwebservices.com/ElasticLoadBalan…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2010-04-28T04:13:40.000+0000</p> 
        <div class="body">
            <p>I have partially implemented EBS support here: <a href="http://github.com/shevron/zf-amazonaws-elasticlb">http://github.com/shevron/zf-amazonaws-elasticlb</a> 
I'd love to continue working on it, but wanted to coordinate with you first.</p>

<p>If you have no objections, I'll write up a proposal and get this committed to the incubator.</p>

        </div>
    </div>
    </div>

