<h2>ZF-7469: some Full Name Locale not exists in Zend_Locale_Data_Translation::$localeTranslation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-04T06:00:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-09T09:48:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Reza Salimian (rsalimian)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7468">ZF-7468</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre><code>    in Zend_Locale_Data_Translation::$localeTranslation, 
    some Full Name Locale are not in array like this:

    'Farsi'         =&gt; 'fa',
    'Iran'          =&gt; 'IR'

    it causes that getEnvironment function in Zend_Locale class returns empy array and then an exception occured.

    whether i should add it manually to array or there is anather way?
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-09T09:48:40.000+0000</p> 
        <div class="body">
            <p>New feature added with r17485</p>

        </div>
    </div>
    </div>

