<h2>ZF-7844: SETNULL option not provied in onUpdate or onDelete statements</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-14T09:06:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-12T09:01:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christoph Rust (crust)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If a reference map in zend db contains 'onDelete' =&gt; self::SET_NULL this is not executed in the database.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matus Zeman (matuszemi) on 2011-02-28T05:08:21.000+0000</p> 
        <div class="body">
            <p>This was my quick fix:
ZF 1.10.8
Zend_Db_Table_Abstract::_cascadeDelete() - line: 1190</p>

<pre class="highlight"><code>
                case self::SET_NULL:
                        $where = array();
                        $data = array();
                        
                        for ($i = 0; $i &lt; count($map[self::COLUMNS]); ++$i) {
                            $col = $this-&gt;_db-&gt;foldCase($map[self::COLUMNS][$i]);
                            $refCol = $this-&gt;_db-&gt;foldCase($map[self::REF_COLUMNS][$i]);
                            $type = $this-&gt;_metadata[$col]['DATA_TYPE'];
                            $where[] = $this-&gt;_db-&gt;quoteInto(
                                $this-&gt;_db-&gt;quoteIdentifier($col, true) . ' = ?',
                                $primaryKey[$refCol], $type);
                                
                            $data[$col] = null;
                        }
                        
                        $rowsAffected += $this-&gt;update($data, $where);
                        break;
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maxim Postoronca (max4ever) on 2011-10-12T09:01:33.000+0000</p> 
        <div class="body">
            <p>this option is also missing from _cascadeUpdate in version 1.11.11</p>

        </div>
    </div>
    </div>

