<h2>ZF-7831: No &quot;images/&quot; folder in downloadable documentation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-09-11T09:02:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-04T13:15:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8178">ZF-8178</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Downloadable documentation lacks "images/" folder, therefore all items like images/note.png etc are broken.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-05-04T13:15:40.000+0000</p> 
        <div class="body">
            <p>Closing as not reproduceable.</p>

<p>I just downloaded actual documentation and images/ folder was present. Probably fixed in past.</p>

        </div>
    </div>
    </div>

