<h2>ZF-7120: Add multiple file upload example to documentation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-06-25T05:30:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-02T10:05:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add multiple files upload example to documentation which has normal form element also (for example one text field). $form-&gt;getValues() seems to destroy $upload_adapter stuff.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-06-25T05:44:21.000+0000</p> 
        <div class="body">
            <p>What do you mean with "destroys adapter stuff" ?</p>

<p>And regarding "normal form element"... also the file element is a normal form element.</p>

<p>There is a description of how to add form elements to a form, which has nothing to do with Zend_File_Translate. And there is also a description of how a multi-file form element has to be created.</p>

<p>Can you be more descriptive on what you did not find or what you expect ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T10:05:36.000+0000</p> 
        <div class="body">
            <p>Closing issue due to non-response</p>

        </div>
    </div>
    </div>

