<h2>ZF-7644: Specific query does not work with $this-&gt;getAdapter ()-&gt;query($sql);</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-20T02:21:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T02:43:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jens Tirsvad Nielsen (tirsvad)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>My sql statement don't work with $this-&gt;getAdapter ()-&gt;query ($sql). It come with no error but stopping at once!!</p>

<p>But works when i used php mysqli_query.</p>

<p><em>File /configs/application.ini</em></p>

<pre class="highlight"><code>
;error reporting
    phpSettings.display_startup_errors = 1
    phpSettings.display_errors = 1
</code></pre>

<pre class="highlight"><code>
;resources.database
    resources.db.adapter = "mysqli"
    resources.db.params.host = "....."
    resources.db.params.dbname = "......"
    resources.db.params.username = "....."
    resources.db.params.password = "....."
    resources.db.params.charset = "utf8"
    resources.db.isDefaultTableAdapter = true
</code></pre>

<p><em>my model file</em></p>

<pre class="highlight"><code>
class tbdkStreetsModel extends Zend_Db_Table_Abstract {
    protected $_name = 'dkStreets';
    function updateRows($data) {
        if (is_array ( $data )) {
            $rs = new tbdkMunicipalityModel ( );
            $sql = 'REPLACE INTO `' . $this-&gt;_name . '` (`MunicipalityCode`,`StreetCode`,`StreetName`,`StreetNameForAddressingName`,`StreetFromStreetCode`,`StreetToStreetCode`,`StreetFromMunicipalityCode`,`StreetToMunicipalityCode`) VALUES' . "\n";
            $komma = '';
            foreach ( $data as $value ) {
                $sql .= $komma . '(' . $value ['MunicipalityCode'] . ',' . $value ['StreetCode'] . ',"' . $value ['StreetName'] . '","' . $value ['StreetNameForAddressingName'] . '",';
                if ($value ['StreetFromStreetCode'] == '0000') {
                    $sql .= "NULL,";
                } else {
                    $sql .= $value ['StreetFromStreetCode'] . ',';
                }
                if ($value ['StreetToStreetCode'] == '0000') {
                    $sql .= "NULL,";
                } else {
                    $sql .= $value ['StreetToStreetCode'] . ',';
                }
                if ($value ['StreetFromMunicipalityCode'] == '0000' || !$rs-&gt;fetchRow('MunicipalityCode = '. $value ['StreetFromMunicipalityCode'] )) {
                    $sql .= 'NULL,';
                } else {
                    $sql .= $value ['StreetFromMunicipalityCode'] . ',';
                }
                if ($value ['StreetToMunicipalityCode'] == '0000' || ! $rs-&gt;fetchRow ('MunicipalityCode = '.$value ['StreetToMunicipalityCode'] )) {
                    
                    $sql .= 'NULL)' . "\n";
                } else{
                    $sql .= $value ['StreetToMunicipalityCode'] . ')' . "\n";
                }
                $komma = ",";
            }
        }
        //
        //$sql .= 'ON DUPLICATE KEY UPDATE StreetName=VALUES(StreetName),StreetNameForAddressingName=VALUES(StreetNameForAddressingName),StreetFromStreetCode=VALUES(StreetFromStreetCode),StreetToStreetCode=VALUES(StreetToStreetCode),StreetFromMunicipalityCode=VALUES(StreetFromMunicipalityCode),StreetToMunicipalityCode=VALUES(StreetToMunicipalityCode);' . "\n";
        //echo ('</code></pre><pre><code>' . $sql . '</code></pre><code>');

/*      $conn = mysqli_connect( '....','.....','.....', '......');
        if( mysqli_connect_errno() )  {
            die( 'Cannot connect to database ' . mysqli_connect_error() );  
        }
        mysqli_query($conn, "SET NAMES 'utf8';");
        mysqli_query($conn, "SET CHARACTER SET 'utf8';" );
        mysqli_query($conn, $sql);
        if( mysqli_connect_errno() )  {
            die( 'SQL Error .: ' . mysqli_connect_error() );  
        }
        return true;
*/

        return $this-&gt;getAdapter ()-&gt;query ($sql);
    }
}
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-20T06:03:53.000+0000</p> 
        <div class="body">
            <p>It is hard to decipher what the actual query is that is failing.  Also, can you produce an error code or error message?</p>

<p>-ralph</p>

        </div>
    </div>
    </div>

