<h2>ZF-7672: Zend_Form_Element getTranslator function is MEGA slow (fix included)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Performance Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-24T05:47:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-13T13:15:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                jaap vstr (jaapvstr)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form_Element getTranslator function would sometimes get me a page load time of 20seconds (1500 calls when calling onValidate).
I finally found a way to improve performance by 18 seconds:</p>

<p>remove</p>

<pre class="highlight"><code>
and it's suddenly only 2 seconds total page load time.

</code></pre>

<pre><code>public function getTranslator()
{
    if ($this-&gt;translatorIsDisabled()) {
        return null;
    }

    if (null === $this-&gt;_translator) {
</code></pre>

<p>//            require_once 'Zend/Form.php'; &lt;---- // FIXED LINE
            return Zend_Form::getDefaultTranslator();
        }
        return $this-&gt;_translator;
    }
```</p>

<p>Ofcource it can be added on top of the class instead.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-13T13:15:09.000+0000</p> 
        <div class="body">
            <p>Fixed with r18966</p>

        </div>
    </div>
    </div>

