<h2>ZF-748: testOrderbyParam(Zend_Gdata_CalendarTest) failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-01-13T11:13:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1) testOrderbyParam(Zend_Gdata_CalendarTest)
Zend_Feed_Exception: DOMDocument cannot parse XML: DOMDocument::loadXML(): Premature end of data in tag feed line 1 in Entity, line: 34
/home/sebastian/Work/ZendFramework/library/Zend/Feed.php:189
/home/sebastian/Work/ZendFramework/library/Zend/Gdata.php:121
/home/sebastian/Work/ZendFramework/library/Zend/Gdata/Calendar.php:95
/home/sebastian/Work/ZendFramework/tests/Zend/Gdata/CalendarTest.php:135
/opt/php/bin/phpunit:40
There was 1 failure:</p>

<p>1) testSetArrayProperty(Zend_ViewTest)
array (
)
Failed asserting that  is equal to </p><p></p>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-07T10:13:46.000+0000</p> 
        <div class="body">
            <p>I frequently have the experience of running the unit tests and getting failures.  When I run the unit tests again after making no changes, they succeed if Google servers respond correctly.  I can only conclude that Google's servers do not give correct responses every time.</p>

<p>Can you please run the test again and tell me if it succeeds?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-02-07T11:46:02.000+0000</p> 
        <div class="body">
            <p>They succeed. May it be a solution to mock the google services?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-07T11:58:45.000+0000</p> 
        <div class="body">
            <p>Google actually changes their protocol from time to time, so that's why I designed the tests to be "live" and actually touch the Google servers.  Their protocol is complex, involving special HTTP headers and often responses contain redirects.  It would be hard to create mock object for Gdata.</p>

<p>My idea to solve this would be to split the unit tests into "static" and "live" tests.  Static tests just test the methods of the Gdata classes, like setting properties and so on.  The "live" tests actually contact Google servers.  The default unit tests would run only the static tests.  The user would have to enable live tests by defining a parameter in /tests/TestConfiguration.php.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-07T11:59:36.000+0000</p> 
        <div class="body">
            <p>May I close this bug report with a resolution of "can not reproduce?"</p>

<p>Or shall I change the bug summary to the test refactoring I described above?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-02-07T12:09:49.000+0000</p> 
        <div class="body">
            <p>In my eyes the tests should be refactored. Another solution may be to check the reachability of the servers and if they are not reachable mark the test as skipped.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-15T12:16:45.000+0000</p> 
        <div class="body">
            <p>I'm closing this issue as "cannot reproduce" since the failures occur irregularly.</p>

<p>I will open a new issue to perform the refactoring on the Gdata tests to do static tests by default, and live tests only when an option is enabled in the TestConfiguration.php file.</p>

        </div>
    </div>
    </div>

