<h2>ZF-7304: add magic function</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-07-18T08:46:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-28T07:26:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>__get support for method getPart($part)</p>

<p>__unset support for method reset( $part = null )</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-03-28T07:26:28.000+0000</p> 
        <div class="body">
            <p>Need to improve the proposal.</p>

        </div>
    </div>
    </div>

