<h2>ZF-7662: Zend_Locale_Data - Missing ldml.dtd and ldmlSupplemental.dtd</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-22T18:28:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-07T04:34:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.2 (25/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dan Entous (dan_nl)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I noticed that when Eclipse finished validating the /library/Zend folder it had several warnings for the /library/Zend/Locale/Data folder. I looked a bit further and found that the xml DOCTYPE references are all referring to a folder and files that didn't exist in the full 1.9.1 (may apply to other versions as well) release I downloaded ... /../common/dtd/ and then to either <a href="">www.unicode.org/cldr/dtd/1.7/ldml.dtd</a>" rel="nofollow"&gt;ldml.dtd or <a href="">www.unicode.org/cldr/dtd/1.7/ldmlSupplemental.dtd</a>" rel="nofollow"&gt;ldmlSupplemental.dtd.</p>

<p>Would it make sense to include the dtd files with the distribution in /library/Zend/common/dtd/ or change the xml DOCTYPE reference to the dtd urls?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-23T01:29:28.000+0000</p> 
        <div class="body">
            <p>Nope...</p>

<p>The dtd files are too large to be integrated and they are not needed for proper working.</p>

<p>Additionally we are not allowed to change the source files which we are distributing (except stripping comments).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rick Schmitty (rschmitty) on 2010-01-07T03:36:55.000+0000</p> 
        <div class="body">
            <p>What is the proper work around for getting those files in then?</p>

<p>Surely you don't leave eclipse with 475 warnings by default leaving you to sift through them when a warning you care about comes up</p>

<p>I tried adding the 1.7.2 dtd files but they errored, which version is zend basing the local off of?</p>

<p><a href="http://unicode.org/cldr/dtd/">http://unicode.org/cldr/dtd/</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dan Entous (dan_nl) on 2010-01-07T04:30:46.000+0000</p> 
        <div class="body">
            <p>In my developer environment I ended up adding a folder for the dtd's at the root level of the Zend folder and added the dtd files; Eclipse no longer displayed the warnings.</p>

<p>/Zend/common/</p>

<p>ldml.dtd               68K (<a href="http://unicode.org/cldr/dtd/1.7/ldml.dtd">http://unicode.org/cldr/dtd/1.7/ldml.dtd</a>)
ldmlSupplemental.dtd   24K (<a href="http://unicode.org/cldr/dtd/1.7/ldmlSupplemental.dtd">http://unicode.org/cldr/dtd/…</a>)</p>

<p>BTW: Before copying the dtd's from unicode.org I had to make sure FF was set to utf-8 character encoding. For some reason the unicode.org server was not serving the dtd's as utf-8 but as iso-8859-1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dan Entous (dan_nl) on 2010-01-07T04:34:45.000+0000</p> 
        <div class="body">
            <p>... no changes to the /Zend/Locale/Data/ XML files.</p>

        </div>
    </div>
    </div>

