<h2>ZF-7989: Where does &quot;View&quot; come in in your plugin</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-09-30T07:54:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-18T13:51:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.7 (11/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.dojo.build-layers.html#zend.dojo.build-layers.profiles">http://framework.zend.com/manual/en/…</a></p>

<p>contains a method</p>

<pre class="highlight"><code>
    public function getBuild()
    {
        if (null === $this-&gt;_build) {
            $this-&gt;_build = new Zend_Dojo_BuildLayer(array(
                'view'      =&gt; $view,
                'layerName' =&gt; 'custom.main',
            ));
        }
        return $this-&gt;_build;
    }
</code></pre>

<p>uh.... where does the $view variable get set?</p>

<p>Thanks</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-09-30T15:50:21.000+0000</p> 
        <div class="body">
            <p>set component and auto reassign</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2009-11-29T07:29:08.000+0000</p> 
        <div class="body">
            <p>The method specified in the description is in the example under the link <a href="http://framework.zend.com/manual/en/zend.dojo.build-layers.html#zend.dojo.build-layers.usage">http://framework.zend.com/manual/en/…</a></p>

<p>The $view should be an instance of Zend_View. Will we add the process of obtaining it in this example?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-12-18T13:51:07.000+0000</p> 
        <div class="body">
            <p>Example updated to pull view from ViewRenderer.</p>

        </div>
    </div>
    </div>

