<h2>ZF-74: Uncomment default route in Zend_Controller_RewriteRouter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2006-06-20T17:38:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:44:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.1.4 (29/Jun/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Ratzloff (mratzloff)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It's not a big deal to define this manually, but it's a pretty basic route that seems like it would be helpful to have.  Might reduce confusion from new users.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

