<h2>ZF-7175: Localization of number use 0xC2A0 instead [space] character</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-01T15:31:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-01T22:45:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Subj.</p>

<p>This problem block user input of localized numbers with spaces, bacause Zend_Locale_Format::isNumber return false on its.</p>

<p>Test:</p>

<pre class="highlight"><code>
$options = array(
    'locale' =&gt; 'ru'
);

$normalized = '1111'; // string(4) "1 111"
$localizedByMe = '1 111'; // string(5) "1 111"

$localizedByFilter = Zend_Locale_Format::toNumber($normalized, $options); // string(6) "1 111" - 6, not 5

for ($i=0; $i</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-01T22:44:43.000+0000</p> 
        <div class="body">
            <p>This is not a failure.
This locale, and also french for example, define that the separation must be done with a "non-breaking" space.</p>

<p>The reason behind this is simple:</p>

<p>Think of a number at the end of a line when usng a automated line break.
The 1 would be at line 1, and the 111 would be at line 2. So for your user it would seem that you have 2 numbers.</p>

<p>So when using a space as separation, the given input will be recognised as 2 different numbers which, of course, means that false will be returned.</p>

<p>This is expected and correct behaviour.</p>

<p>When you have to work with localized userinput and want to convert spaces in non-breaking spaces, you should use for example a regex filter to change the character. Or your input field changes this itself.</p>

        </div>
    </div>
    </div>

