<h2>ZF-7581: Sync trunk and release-1.9 branch (cs-17363 related)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2009-08-13T06:39:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-24T06:58:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7548">ZF-7548</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There was a commit (<a href="http://framework.zend.com/code/changelog/Zend_Framework/standard/branches/release-1.9/tests/Zend?cs=17363">cs-17363</a>) which directly updates some functionality. 
As a result release-1.9 branch and trunk became unsynckronized.</p>

<p>Nethertheless, it's really nice improvement since it improves class docblocks and adds @group annotations for large number of files.</p>

<p>So it's good to merge this commit back to the trunk instead of reverting it at all.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-08-13T06:45:09.000+0000</p> 
        <div class="body">
            <p>Merging back has to exclude:
* tests/Zend/AllTests.php
* tests/Zend/Db/SkipTests.php
* tests/Zend/CodeGenerator/Php/_files/*</p>

<p>since they  were reverted in the release branch because of some reasons</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-08-13T07:12:55.000+0000</p> 
        <div class="body">
            <p>Direct merging <a href="http://framework.zend.com/code/changelog/Zend_Framework/standard/branches/release-1.9/tests/Zend?cs=17363">cs-17363</a> into trunk already produce the following conflicts:
{panel}
C      tests/Zend/Gdata/HealthOnlineTest.php
C      tests/Zend/Gdata/Health/ProfileListEntryTest.php
C      tests/Zend/Gdata/Health/ProfileEntryTest.php
C      tests/Zend/Gdata/Health/ProfileFeedTest.php
C      tests/Zend/Gdata/Health/QueryTest.php
C      tests/Zend/Ldap/AllTests.php
C      tests/Zend/Ldap/AttributeTest.php
C      tests/Zend/Ldap/ConverterTest.php
C      tests/Zend/Ldap/FilterTest.php
C      tests/Zend/View/Helper/CycleTest.php
C      tests/Zend/Tool/AllTests.php
C      tests/Zend/Amf/AllTests.php
C      tests/Zend/Amf/Contact.php
C      tests/Zend/Amf/ResponseTest.php
C      tests/Zend/Amf/ContactVO.php
C      tests/Zend/Amf/AuthTest.php
C      tests/Zend/Amf/TypeLoaderTest.php
C      tests/Zend/Amf/_files/services/My/ServiceA.php
C      tests/Zend/Amf/_files/services/ServiceC.php
C      tests/Zend/Amf/Resources/StreamContext.php
C      tests/Zend/Amf/ResourceTest.php
C      tests/Zend/Amf/RequestTest.php
C      tests/Zend/Cache/ZendServerDiskTest.php
C      tests/Zend/Cache/ZendServerShMemTest.php
{panel}</p>

<p>So this files should be merged manually, then <a href="http://framework.zend.com/code/changelog/Zend_Framework/standard/branches/release-1.9/tests/Zend?cs=17363">cs-17373</a> should be reverted for files mentioned above and committed trunk update reapplied to branch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-08-13T11:03:41.000+0000</p> 
        <div class="body">
            <p>Commit is merged back to trunk except files mentioned above. They still need manual merging.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-08-19T10:17:54.000+0000</p> 
        <div class="body">
            <p>The following files are also already merged into trunk:
{panel}
tests/Zend/Ldap/AllTests.php
tests/Zend/Ldap/FilterTest.php
tests/Zend/Amf/AllTests.php
tests/Zend/Amf/TypeLoaderTest.php
tests/Zend/Amf/_files/services/My/ServiceA.php
tests/Zend/Amf/_files/services/ServiceC.php
{panel}</p>

<p>1.9 branch is synchronized with r17681.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2009-08-19T15:21:48.000+0000</p> 
        <div class="body">
            <p>Thank you very much for doing the unpleasant work of conflict resolution on the merge.  My apologies for not getting cs-17363 right to begin with.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-08-20T06:35:36.000+0000</p> 
        <div class="body">
            <p>np Bill! :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-08-20T06:36:05.000+0000</p> 
        <div class="body">
            <p>The rest of confilcted files is merged</p>

        </div>
    </div>
    </div>

