<h2>ZF-7503: Incorrect inflection when creating an action through zf.bat</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-06T04:56:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-20T21:13:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
c:\xampp\htdocs\abc&gt;zf create action noPrivilegies error 1 default
Creating an action named noPrivilegies inside controller at c:\xampp\htdocs\abc/application/modules/default/controllers/ErrorController.php
Updating project profile 'c:\xampp\htdocs\abc/.zfproject.xml'
Creating a view script for the noPrivilegies action method at c:\xampp\htdocs\abc/application/modules/default/views/scripts/error/noPrivilegies.phtml
Updating project profile 'c:\xampp\htdocs\abc/.zfproject.xml'
</code></pre>

<p>As you can see the view script created does not match the default inflection rules for view scripts. When I try to go to the action it complains that the viewscript no-privilegies.phtml does not exist.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Patrik Åkerstrand (machine) on 2009-08-06T04:58:43.000+0000</p> 
        <div class="body">
            <p>Improved formatting</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-11-20T21:13:24.000+0000</p> 
        <div class="body">
            <p>This was fixed as part of 1.10 when "canonical naming" was introduced. If you still feel there is an issue (although I just tested this scenario), please reopen.</p>

<p>-ralph</p>

        </div>
    </div>
    </div>

