<h2>ZF-7255: Unclear term in Zend Framework quickstart tutorial</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-07-13T22:44:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-03T13:43:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On this page:  <a href="http://framework.zend.com/docs/quickstart/create-a-layout">http://framework.zend.com/docs/quickstart/…</a></p>

<p>is this statement</p>

<p>"Now that we've initialized Zend_Layout and set the Doctype, let's create our site-wide layout:"</p>

<p>"Zend_Layout" appears to be a term relating to an object, element or something else that is in the code but it is not.  As far as I can tell, we haven't "initialized" anything with the name "Zend_Layout" by that point in the tutorial.  It is referenced in the phrasing above, but does not appear in the code.  Confusing.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Steven Morehouse (s_mack) on 2009-07-14T08:49:40.000+0000</p> 
        <div class="body">
            <p>Clearly, something is missing (and if not then the wording MUST change) because when I follow the link to the Zend_Layout documentation, I see this:</p>

<p>bq: First, let's look at how to initialize Zend_Layout for use with the MVC:</p>

<pre class="highlight"><code>
// In your bootstrap:
Zend_Layout::startMvc();
</code></pre>

<p>And further down in the documentation not relating to MVC, there's this:</p>

<pre class="highlight"><code>
$layout = new Zend_Layout();
</code></pre>

<p>neither of which are on the aforementioned quick start page immediately before "Now that we've initialized Zend_Layout and set the Doctype, let's create our site-wide layout:"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-05-03T13:43:57.000+0000</p> 
        <div class="body">
            <p>Closing as not reproduceable.</p>

<p>First we can read:</p>

<pre class="highlight"><code>
In Zend Framework, Zend_Layout combines the ideas behind these patterns. Instead of each action view script needing to include site-wide artifacts, they can simply focus on their own responsibilities.
</code></pre>

<p>Then we can read:</p>

<pre class="highlight"><code>
To get started using Zend_Layout, first we need to inform our bootstrap to use the Layout resource. This can be done using the zf enable layout command: 
</code></pre>

<p>And at last:</p>

<pre class="highlight"><code>
Now that we've initialized Zend_Layout and set the Doctype, let's create our site-wide layout: 
</code></pre>

<p>For me this is logically even if I did not work with Zend_Layout until now.</p>

<p>When you want to have a "rewritten content" I would propose that you note what should be changed.</p>

<p>As this issue is also several months old and related to an outdated release I close it as not reproduceable.</p>

        </div>
    </div>
    </div>

