<h2>ZF-7029: Zend_Service_Amazon_S3 - Incorrect IP address matching in createBucket method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-16T12:47:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-17T14:05:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The regular expression used by the createBucket method to detect an IP address is incorrect. The period characters in the regular expression are not escaped causing detection of one or more numeric digits followed by any character.</p>

<p>Example:</p>

<p>createBucket detects a match and throws an exception when passed the bucket name bf6a1588-48ce-4900-9a62-7d08eab1a02f</p>

<p>Possible Solutions:</p>

<p>The current regular expression should have period characters escaped like so:
(\d+).(\d+).(\d+).(\d+)</p>

<p>Use a much more complex regular expression to detect all 4 numbers in the IP address are in the range 0..255:
(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-06-16T14:49:02.000+0000</p> 
        <div class="body">
            <p>Assigning to Stas.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-06-17T14:05:33.000+0000</p> 
        <div class="body">
            <p>Fixed, thanks.</p>

        </div>
    </div>
    </div>

