<h2>ZF-7372: Zend_Tool fails when Custom Providers are defined with multiple parameters that start with the same letter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-23T16:47:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-20T21:20:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Postponed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Khary Sharpe (ksharpe)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>You are not able to name parameters starting with the same first letter.</p>

<p>If a method is defined as follows:</p>

<pre class="highlight"><code>
public function foo($testvar, $testVariable)
</code></pre>

<p>This will result in the following error:</p>

<p>An Error Has Occurred
Option "-t" is being defined more than once.</p>

<p>As these are two separate parameters, it would be expected that the method declaration would be valid.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

