<h2>ZF-7325: Zend_Gdata uses split() which is deprecated since PHP 5.3</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-20T12:45:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-21T16:11:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The now-deprecated split() function is used is various Zend_Gdata classes, which causes the tests to fail.
preg_split() or explode() should be used instead.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-07-21T15:28:22.000+0000</p> 
        <div class="body">
            <p>Updated description to indicate that this affects more than just Zend_Gdata_Youtube.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-07-21T16:10:06.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk by r16937.</p>

<p>Resolving as fixed for next minor version.</p>

<pre class="literal">
commit cc110429f4fa8c0ad98136c856f9c6c5e9bcc28c
Author: tjohns 
Date:   Tue Jul 21 22:49:14 2009 +0000

    ZF-7325: Replace calls to split() in Zend_Gdata with calls to explode() or preg_spllit().
    
    The split() function is depreciated as of PHP 5.3.0.
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/trunk@16937">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac1e357ba

 demos/Zend/Gdata/Blogger.php                 |    8 ++++----
 demos/Zend/Gdata/Gbase.php                   |    2 +-
 demos/Zend/Gdata/MyLibrary/demo.php          |    2 +-
 demos/Zend/Gdata/Spreadsheet-ClientLogin.php |   12 ++++++------
 library/Zend/Gdata/YouTube/VideoEntry.php    |    2 +-
 tests/Zend/Gdata/YouTube/VideoEntryTest.php  |    4 ++--
 6 files changed, 15 insertions(+), 15 deletions(-)
</pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-07-21T16:11:56.000+0000</p> 
        <div class="body">
            <p>....which will be 1.9 ;)</p>

        </div>
    </div>
    </div>

