<h2>ZF-7450: Action helper contextswitch - Headers of context xml can not be modified</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-03T02:38:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Though context xml is removed and then added with new headers, the headers are not acknowledged.</p>

<p>Works fine for the other default context json and all new context switches though:</p>

<pre class="highlight"><code> 
$contextSwitch-&gt;removeContext('xml');
$contextSwitch-&gt;removeContext('json');

        $context = 'xml';
        $spec = array(
            'headers'       =&gt; array(
                'Content-type' =&gt; 'text/xml',
                'Expires' =&gt; 'Mon, 26 Jul 1997 05:00:00 GMT',
                'Last-Modified' =&gt; gmdate( 'D, d M Y H:i:s' ) . ' GMT',
                'Cache-Control' =&gt; 'no-cache, must-revalidate',              
                'Pragma' =&gt; 'no-cache'   
            ),
            'callbacks'     =&gt; array(
                'post'          =&gt; array($this,'showXml')
            )
        );
        $contextSwitch-&gt;addContext($context, $spec);

        $context = 'json';
        $spec = array(
            'headers'       =&gt; array(
                'Content-type' =&gt; 'text/json',
                'Expires' =&gt; 'Mon, 26 Jul 1997 05:00:00 GMT',
                'Last-Modified' =&gt; gmdate( 'D, d M Y H:i:s' ) . ' GMT',
                'Cache-Control' =&gt; 'no-cache, must-revalidate',              
                'Pragma' =&gt; 'no-cache'                 
            ),
            'callbacks'     =&gt; array(
                'post'          =&gt; array($this,'showJson')
            )
        );
        
        $contextSwitch-&gt;addContext($context, $spec);
</code></pre>

<pre class="literal">
wrong for xml:
curl -I "http://url/format/xml"
HTTP/1.1 200 OK
Date: Mon, 03 Aug 2009 09:17:30 GMT
Server: Apache
Vary: Accept-Encoding
Content-Type: text/xml

correct for json:
curl -I "http://url/format/json"
HTTP/1.1 200 OK
Date: Mon, 03 Aug 2009 09:17:28 GMT
Server: Apache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Last-Modified: Mon, 03 Aug 2009 09:17:28 GMT
Cache-Control: no-cache, must-revalidate
Pragma: no-cache
Vary: Accept-Encoding
Content-Type: text/json
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:02.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

