<h2>ZF-7866: Zend_Gdata_Gbase  Batch support</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-09-17T04:19:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-04T23:19:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Vladas Dirzys (funkyfly)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be great to have batch support not only for Gbase Java api, but also for the Zend_Gdata.
Because it is needed, and it saves a lot of requests then it is needed to export huge amount of items.</p>

<p>Building XML your self, can't be really  a solution for this task :-)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-04T23:19:01.000+0000</p> 
        <div class="body">
            <p>Zend_Gdata_Gbase was discontinued by Google on June 1st, 2011 and has been removed from Zend Framework in 1.12.0.  The classes remain, but will throw a {{Zend_Exception}} when instantiated. 
Announcement: <a href="http://googlemerchantblog.blogspot.ca/2010/12/new-shopping-apis-and-deprecation-of.html">http://googlemerchantblog.blogspot.ca/2010/12/…</a></p>

        </div>
    </div>
    </div>

