<h2>ZF-7553: Possible inconsitent behaviour of match and assemble functions in Zend_Controller_Router_Route using translated segments</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-10T09:25:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It seems to me that the assemble function in Zend_Controller_Router_Route could use a little adjustment to equalize its behaviour to the match function when using translated segments.</p>

<p>Assemble uses Zend_Controller_Router_Route-&gt;getLocale() to determine the current locale (if no @locale is given in the data array).</p>

<pre class="highlight"><code>
    public function assemble($data = array(), $reset = false, $encode = false, $partial = false)
    {
        if ($this-&gt;_isTranslated) {
            $translator = $this-&gt;getTranslator();
            
            if (isset($data['@locale'])) {
                $locale = $data['@locale'];
                unset($data['@locale']);
            } else {
                $locale = $this-&gt;getLocale();
            }
        }
        ...
</code></pre>

<p>The match function does a direct query to Zend_Translate_Adapter-&gt;getMessages() which results in Zend_Translate_Adapter-&gt;_options['locale'] being used as current locale.</p>

<pre class="highlight"><code>
    public function match($path, $partial = false)
    {
        if ($this-&gt;_isTranslated) {
            $translateMessages = $this-&gt;getTranslator()-&gt;getMessages();
        }
        ...
</code></pre>

<pre class="highlight"><code>
    public function getMessages($locale = null)
    {
        if ($locale === 'all') {
            return $this-&gt;_translate;
        }

        if ((empty($locale) === true) or ($this-&gt;isAvailable($locale) === false)) {
            $locale = $this-&gt;_options['locale'];
        }

        return $this-&gt;_translate[(string) $locale];
    }
</code></pre>

<p>So in some cases one could end up with match and assemble using different locales.
Shouldn't match better look something like this:</p>

<pre class="highlight"><code>
    public function match($path, $partial = false)
    {
        if ($this-&gt;_isTranslated) {
            $locale = $this-&gt;getLocale();
            $translateMessages = $this-&gt;getTranslator()-&gt;getMessages($locale);
        }
        ...
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:58.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

