<h2>ZF-7417: clarify confusion between 'resource plugins' and 'resources' in docs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-07-29T20:14:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-21T13:53:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.2 (25/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                jw (ronny stalker)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7416">ZF-7416</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This issue was spawned from this forum question: <a href="http://www.nabble.com/confusion-between-resource-plugins-and-resources-in-docs-to24400044.html#a24731301">http://nabble.com/confusion-between-resource-plugi…</a></p>

<p>The Problem
By reading the ZF Docs for Zend_Controller and Zend_View, the reader is habituated into a more pedantic mode of thought. That is, we learn that the terms to describe objects are very specific.</p>

<ul><li>An 'action controller' is very different to a 'front controller' which is different to a 'controller plugin' which is very different to a 'controller helper'</li>
<li>A 'View' is very different to a 'view helper'</li>
</ul><h2>However, the documentation for Zend Application is written in a slightly less pedantic way:</h2>

<p>Under section "4.3.2. Resource Plugins" 
It says:
"Resources need only implement Zend_Application_Resource_Resource, or, more simply still, extend Zend_Application_Resource_ResourceAbstract. "</p>

<p>Under section "4.4. Examples"
It says:</p>

<h2>"Resource plugins implement Zend_Application_Bootstrap_Resource, which defines simply that they allow injection of the caller and options, and that they have an init() method. "</h2>

<p>Note:
 * that the words 'Resources' and 'Resource plugins' are used interchangeably to mean the same thing.
 * there is a typo in the second paragraph: 'Zend_Application_Bootstrap_Resource' should be 'Zend_Application_Resource_Resource' 
    - (issue ticket for typo already is submitted @ ZF-7416 ).</p>

<p>--</p>

<p>Now imagine a newbie  coming to the Zend Framework and reading the documentation on Zend_Application <em>before</em> they read the Zend_Controller (which seems quite likely these days).
Instead they will be habituated to read the docs in a less pedantic way.</p>

<p>So, if there is no consistency in the language used to describe a 'resource plugin' or 'resource' within the Zend_Application docs...it will lead to even more confusion when the reader arrives at Zend_Controller and starts learning about 'controllers' and 'controller plugins'.</p>

<p>Just my thoughts.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by jw (ronny stalker) on 2009-07-29T20:23:15.000+0000</p> 
        <div class="body">
            <p>Worth being aware of the two issues :
* Typo
* improvement to docs</p>

<p>to make 'find and replace' go smoothly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-08-21T13:53:49.000+0000</p> 
        <div class="body">
            <p>Language updated and made more consistent. Fixes applied to trunk and 1.9 release branch.</p>

        </div>
    </div>
    </div>

