<h2>ZF-7885: testRequestMethodShouldBeNullByDefault(Zend_Controller_Request_HttpTestCaseTest) unit tests failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2009-09-18T06:58:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-21T07:47:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.3 (22/Sep/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
4) testRequestMethodShouldBeNullByDefault(Zend_Controller_Request_HttpTestCaseTest)
Failed asserting that  is null.
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-09-18T07:00:23.000+0000</p> 
        <div class="body">
            <p>Threre are an additional related failure:</p>

<p>{panel}
5) testShouldAllowSpecifyingRequestMethod(Zend_Controller_Request_HttpTestCaseTest)
Failed asserting that  is null.
{panel}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-09-21T07:47:50.000+0000</p> 
        <div class="body">
            <p>Fixed in 1.9 release branch and backported to trunk. Related to ZF-6162.</p>

        </div>
    </div>
    </div>

