<h2>ZF-7088: POP3 Email extraction daemon script segfaults Apache with PHP 5.3.0RC4</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-22T15:14:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-22T15:21:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12042/WikiarticleController.php">WikiarticleController.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'll start to isolate the issue now. It can be any of these:</p>

<p>POP3, String processing, cURL, utf8, PDO MySql.... PHP devs asked me to create it quicker and to start to play.
Same script works perfectly in RC3, but crashes Apache in RC4.</p>

<p>Will update this ticket with more information as soon as I get more and more details.</p>

<p>Will attach base script (which runs daemon) and processor as soon as possible.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Guilherme Blanco (guilhermeblanco) on 2009-06-22T15:16:20.000+0000</p> 
        <div class="body">
            <p>Daemon and processor actions</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-06-22T15:20:47.000+0000</p> 
        <div class="body">
            <p>If you get a segfault it's a bug in apache or php. This is also proven by the fact that under RC3 it worked all ok. You'll need to report this 'issue' (probably along with code to reproduce) in the php.net or apache issue tracker.</p>

        </div>
    </div>
    </div>

