<h2>ZF-7820: Bug when inheriting new class from Zend_View_Helper_Navigation_Menu</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-10T04:31:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-10T12:32:47.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Vladislav (artte-zf)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Robin Skoglund (robinsk)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7819">ZF-7819</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>i want redefine some functions in this class to improve it for my project, but i need make small but not simple changes, so make partials or write absolutely new class haven't any sense. TO problem..
I wrote this code and created new model:</p>

<pre class="highlight"><code>
&lt;?php
class MenuRenderer extends Zend_View_Helper_Navigation_Menu
{

}
</code></pre>

<p>and in view script:</p>

<pre class="highlight"><code>
    $mr=new MenuRenderer;
    echo $mr-&gt;render($this-&gt;lm);
</code></pre>

<pre class="highlight"><code>
Fatal error: Call to a member function escape() on a non-object in D:\Apache\htdocs\libs\Zend\View\Helper\HtmlElement.php on line 92
</code></pre>

<hr /><pre class="highlight"><code>
    $mr=new MenuRenderer;
    $mr-&gt;setview($this);
    echo $mr-&gt;render($this-&gt;lm);
</code></pre>

<p>work's fine</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Vladislav (artte-zf) on 2009-09-10T05:12:18.000+0000</p> 
        <div class="body">
            <p>needed to set view, (<a href="http://framework.zend.com/issues/browse/ZF-7819">http://framework.zend.com/issues/browse/ZF-7819</a>) - answer there, and it's clonned issue, sorry</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2009-09-10T05:49:36.000+0000</p> 
        <div class="body">
            <p>Closing as requested</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-09-10T05:52:05.000+0000</p> 
        <div class="body">
            <p>I changed code tag in the description.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2009-09-10T12:32:43.000+0000</p> 
        <div class="body">
            <p>A quick side note,
If you had used your view helper as view helpers are intended to be used, you would not have this problem of needing to call $mc-&gt;setView($this);</p>

<p>You should really add a helper path to include a path to your helper which would allow the helper to be loaded automatically, rather than making an instance of it directly in your view.</p>

        </div>
    </div>
    </div>

