<h2>ZF-7591: Zend_Translate_Adapter_Csv is not working perfectly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-14T00:23:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-14T00:34:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Translate_Adapter_Csv is not working perfectly in the below situation :-</p>

<p>It is working for two columns input and output is an array with [first_column]=&gt;second_column. Where first_column is the key and 2nd column is the value.</p>

<p>Now If I have some input file with more than 2 columns and I need all information. It will not work.</p>

<p>In Zend_Translate_Adapter_Csv :: _loadTranslationData() method , we are doing the the below,</p>

<p>$this-&gt;_data[$locale][$data[0]] = $data[1]; //hard coding the row number. Instead of that we can do some validation and then</p>

<p>$this-&gt;_data[$locale][] = $data;</p>

<p>could you please check that and let me know if there is any other solution</p>

<p>Thank you,
Mukul</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-14T00:34:53.000+0000</p> 
        <div class="body">
            <p>The described Issue is not reproducable with the actual release.</p>

<p>When there are 2 rows than the value is attached as string, else they are attached as array because then they are plural notations.</p>

<p>You should not that the manual clearly describes that plural translations only work AS WITH ZF 1.9.</p>

        </div>
    </div>
    </div>

