<h2>ZF-7156: Zend_Form_Element_Submit should accept the same parameter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-06-29T05:13:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-29T05:49:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dominique Lorre (dlorre)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Greetings,</p>

<p>This code only creates one button (compute) :</p>

<hr /><pre><code>    $complete = new Zend_Form_Element_Submit('submit');
    $complete-&gt;setValue("complete") ;
    $complete-&gt;setLabel("Complete") ;

    $compute = new Zend_Form_Element_Submit('submit');
    $compute-&gt;setValue("compute") ;
    $compute-&gt;setLabel("Compute") ;
                      $this-&gt;addElements(array($complete, $compute));
</code></pre>

<hr /><p>And this code creates two buttons:</p>

<hr /><pre><code>    $complete = new Zend_Form_Element_Submit('complete');
    $complete-&gt;setValue("complete") ;
    $complete-&gt;setLabel("Complete") ;

    $compute = new Zend_Form_Element_Submit('compute');
    $compute-&gt;setValue("compute") ;
    $compute-&gt;setLabel("Compute") ;
                      $this-&gt;addElements(array($complete, $compute));
</code></pre>

<hr /><p>Hence it makes the code a bit more complicated than it should be, so if the first method was supported it would help a lot. Thank you.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-06-29T05:34:11.000+0000</p> 
        <div class="body">
            <p>Won't fix. All elements within a form need a unique identifier so that they may be retrieved individually.</p>

<p>One solution is to create a sub form named 'submit' with two buttons, 'complete' and 'compute'. This way you can then check to see which $submit value was returned in the form.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dominique Lorre (dlorre) on 2009-06-29T05:49:18.000+0000</p> 
        <div class="body">
            <p>The second version of the code is enough of a workaround, thank you. Created a sub form would only add complexity.. this was suggested only because I find it clumsy.</p>

        </div>
    </div>
    </div>

