<h2>ZF-792: Components (Symfony-like defenition) in MVC </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2007-01-24T04:01:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2008-03-21T16:25:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.5.0 (17/Mar/08)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I didn't found in ZFW future like component is Symfony.
I'm writen it.
<a href="http://rt.avlab.ru/wp-content/uploads/2007/01/loadcomponent.zip">http://rt.avlab.ru/wp-content/uploads/…</a></p>

<p>For more information see <a href="http://rt.avlab.ru/2007/01/14/zend-framework-realizatsiya-komponent-v-shablone/">http://rt.avlab.ru/2007/01/…</a> (russian)</p>

<p>If you know more right way, notify me, please.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-25T09:05:18.000+0000</p> 
        <div class="body">
            <p>Assign to Matthew.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-29T09:37:13.000+0000</p> 
        <div class="body">
            <p>From reviewing the code, it looks like this is a Zend_View helper class designed to allow pulling in content from another controller action, and that it has some amount of caching included in the interface.</p>

<p>What I'm wondering is: why would you do this instead of using _forward() in the action controller? Can you give me some details on what prompted this particular design, and use cases?</p>

<p>Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roman Tolkachyov (rammstein) on 2007-01-29T11:09:32.000+0000</p> 
        <div class="body">
            <p>That's right - this is a Zend_View helper.
Some code for example</p>

<pre class="highlight"><code>
      require_once 'Zend/Controller/Action.php';
       
      class IndexController extends Zend_Controller_Action
      {
      public function indexAction()
      {
      $View = new Zend_View();
      $View-&gt;addHelperPath('../application/helpers/', 'Avlab_View_Helper_');
      $View-&gt;addScriptPath('../application/views/');
       
      echo $View-&gt;render('indexView.php');
      }
       
      public function componentAction()
      {
      echo "It's work!!!";
      }
       
      public function noRouteAction()
      {
      $this-&gt;_redirect('/');
      }
      }
</code></pre>

<p>indexView.php</p>

<pre class="highlight"><code>
There are 3 component call:
&lt;?echo $this-&gt;loadComponent('index', 'component');?&gt;
&lt;?echo $this-&gt;loadComponent('index', 'component');?&gt;
&lt;?echo $this-&gt;loadComponent('index', 'component');?&gt;
</code></pre>

<p>We don't need to controll call chain in controller by using _forward(). In other way we should notify next controller2 about what controller3 it must forward to and then notify controller 3 what controller4 must forward to etc.
It very hard.</p>

<p>In other way we should modify _forward() to allow constructions like that:</p>

<pre class="highlight"><code>
$this-&gt;_forward('controller', 'component1');
$this-&gt;_forward('controller', 'component2');
$this-&gt;_forward('controller', 'component3');
// etc
</code></pre>

<p>it's means, that next action is 'component1' and after it will execute action component2 will start etc.</p>

<p>But it isn't right alternative. I can't say rightly why, because I have troubles in my english :) You may read symfony-book by this subject.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-11-16T10:31:50.000+0000</p> 
        <div class="body">
            <p>Please review the Zend_View_Helper_Action view helper in the incubator. This component will be available for the 1.1.0 release as part of the Zend_View Enhanced proposal, and accomplishes what you've outlined.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-12-11T15:10:54.000+0000</p> 
        <div class="body">
            <p>Action view helper merged to core.</p>

        </div>
    </div>
    </div>

