<h2>ZF-7592: Union syntax error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-14T02:31:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-02T15:32:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexandr Kovalenko (sander)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4338">ZF-4338</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>File: Zend/Db/Select.php
Line: 1088</p>

<p>// wrong
$sql .= $target;</p>

<p>// right
$sql .= '(';
$sql .= $target;
$sql .= ')';</p>

<pre class="highlight"><code>
$select = $db-&gt;select()-&gt;union(array($select1, $select2))-&gt;order('field1ASC')-&gt;limit(3);
// expected (SELECT table1.id FROM table1  WHERE foo = 'bar') UNION (SELECT table2.id FROM table2 WHERE foo = 'bar') ORDER BY field1 ASC LIMIT 3 
// receive SELECT table1.id FROM table1  WHERE foo = 'bar' UNION SELECT table2.id FROM table2 WHERE foo = 'bar' ORDER BY field1 ASC LIMIT 3 
</code></pre>

<p>To fixed it i must do next:</p>

<pre class="highlight"><code>
$select-&gt;union(array('(' . $select1 . ')', '(' . $select2 . ')'))-&gt;order('field1ASC')-&gt;limit(3);
</code></pre>

<p>it is wrong</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexandr Kovalenko (sander) on 2009-08-14T02:51:46.000+0000</p> 
        <div class="body">
            <p>also you may change this 2 line:
from
    $parts = count($this-&gt;_parts[self::UNION]);
  to 
    $parts = count($this-&gt;_parts[self::UNION]) - 1;
and 
  from 
    $cnt &lt; $parts - 1 
  to 
    $cnt &lt; $parts</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Denis Baklikov (denis.baklikov) on 2009-08-18T08:52:31.000+0000</p> 
        <div class="body">
            <p>Which database are you using? MySQL or PostgreSQL?
I have just checked this syntax (without bracket sign) in Oracle and it works OK.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexandr Kovalenko (sander) on 2009-08-18T10:53:20.000+0000</p> 
        <div class="body">
            <p>MySQL</p>

<p>SELECT * FROM test WHERE test_status = 4 ORDER BY r_id DESC
UNION 
SELECT * FROM test WHERE test_status = 3 ORDER BY r_id ASC</p>

<h6>#</h6>

<p>Error Code : 1221
Incorrect usage of UNION and ORDER BY</p>

<h6>#</h6>

<p>(SELECT * FROM test WHERE test_status = 4 ORDER BY r_id DESC)
UNION 
(SELECT * FROM test WHERE test_status = 3 ORDER BY r_id ASC)</p>

<h3>#</h3>

<p>OK</p>

<h3>#</h3>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jordan Ryan Moore (jordanryanmoore) on 2009-10-23T09:06:58.000+0000</p> 
        <div class="body">
            <p>This is a duplicate of ZF-4338.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mario Ferreira (ztrange) on 2010-02-02T15:25:17.000+0000</p> 
        <div class="body">
            <p>Hello... Is this not a critical bug? No one is assigned to it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-02-02T15:32:03.000+0000</p> 
        <div class="body">
            <p>Someone is assigned to it. However, because this issue has already been reported before, this issue was closed (hence the term 'duplicate'). Please also see ZF-4338 .</p>

        </div>
    </div>
    </div>

