<h2>ZF-7789: Zend lucene search result will lose some records when using the index created by java lucene</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-07T00:56:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-08-20T11:08:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Kevin (mincer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5545">ZF-5545</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12187/index.zip">index.zip</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I was using zend search to search a string cross multi-fields from the index created by java lucene 1.9.1, the search result missed one record. Please follow the steps below to reproduce it.</p>

<ol><li><p>copy the index files in attachment to "C:\index"</p></li>
<li><p>write a php script including the following code
$index = Zend_Search_Lucene::open("C:\index");
$query = Zend_Search_Lucene_Search_QueryParser::parse("contents:role AND tags:abc");
$hits = $index-&gt;find($query);</p></li>
<li><p>run it and you will see the search result count will be three. The correct count should be four.</p></li>
</ol>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kevin (mincer) on 2009-09-07T00:58:51.000+0000</p> 
        <div class="body">
            <p>index file created by java lucene</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hying (hying) on 2010-01-13T00:32:35.000+0000</p> 
        <div class="body">
            <p>I have the same problem with an java created index.
With luke.jar i can see the document contains words like 'behrenz'. But if i search for 'behr<em>' with Zend, no results are found. The search for 'behre</em>' or 'beh*' however returns the correct result.</p>

<p>Any ideas?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hying (hying) on 2010-03-16T09:13:55.000+0000</p> 
        <div class="body">
            <p>Hi Kevin,</p>

<p>i think i resolved the problem for Version 1.9.7 to 1.10.2:
add this line:</p>

<pre class="highlight"><code> 
  $docsFilter = new Zend_Search_Lucene_Index_DocsFilter();
</code></pre>

<p>into the file:
/Search/Lucene/Search/Query/MultiTerm.php
at line 531 
bevore the second foreach over '$this-&gt;_terms'</p>

<p>Not sure but i think the $docsFilter will be changend during the call</p>

<pre class="highlight"><code> 
  $termDocs = $reader-&gt;termDocs($term, $docsFilter);
</code></pre>

<p>in line 345</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Hying (hying) on 2010-03-16T09:27:39.000+0000</p> 
        <div class="body">
            <p>Sorry, it must be added in line 351 of the file /Search/Lucene/Search/Query/MultiTerm.php and not line 531</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2010-08-20T11:05:35.000+0000</p> 
        <div class="body">
            <p>It seems it duplicates ZF-5545 issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2010-08-20T11:08:30.000+0000</p> 
        <div class="body">
            <p>Resolved since duplicated issue is fixed</p>

        </div>
    </div>
    </div>

