<h2>ZF-7763: Zend_Navigation_Page_Mvc generates incorrect urls using routes with *</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-02T12:59:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-19T06:56:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Robin Skoglund (robinsk)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I've just started with ZF, so maybe its not actualy a bug, but for me its an unexpected thing.
I'm using route with * modifier to accept additonal params via url. Next is code from docs, the only modification is "/*" in the end of the route</p>

<pre class="highlight"><code>
// the following route is added to the ZF router
Zend_Controller_Front::getInstance()-&gt;getRouter()-&gt;addRoute(
    'article_view', // route name
    new Zend_Controller_Router_Route(
        'a/:id/*',
        array(
            'module'     =&gt; 'news',
            'controller' =&gt; 'article',
            'action'     =&gt; 'view',
            'id'         =&gt; null
        )
    )
);

// a page is created with a 'route' option
$page = new Zend_Navigation_Page_Mvc(array(
    'label'      =&gt; 'A news article',
    'route'      =&gt; 'article_view',
    'module'     =&gt; 'news',    // required for isActive(), see note above
    'controller' =&gt; 'article', // required for isActive(), see note above
    'action'     =&gt; 'view',    // required for isActive(), see note above
    'params'     =&gt; array('id' =&gt; 42)
));

// returns: /a/42
$href = $page-&gt;getHref();
</code></pre>

<p>Actualy will return
<em>/a/42/module/news/controller/article/action/view</em>
module, controller and action were treated as url parameters.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by David Caunt (dcaunt) on 2009-09-02T13:02:47.000+0000</p> 
        <div class="body">
            <p>I've suffered from this problem as well - if its not a bug I think the manual may be missing some information.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robin Skoglund (robinsk) on 2009-09-19T06:56:28.000+0000</p> 
        <div class="body">
            <p>The "weirdness" you experience is just the way Zend_Controller_Router* works, and it is not a bug.</p>

        </div>
    </div>
    </div>

