<h2>ZF-7047: Zend_Form_Element_MultiCheckbox fails to instanciate using the element factory because of a case sensitive problem</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-19T02:03:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-27T12:20:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Nicolas Grevet (nyko18)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5368">ZF-5368</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When trying to create a form using the element factory, I'm facing a little problem. Every Zend_Form_Element_X class has a naming convention where the first letter is in upper case and the rest in lower case. Each one except Zend_Form_Element_MultiCheckbox, and when you try to create this element using the factory, it fails because it should be called using an upper case letter in the middle of the parameter :
{quote}
// This fails because there's no upper case letter at 'checkbox'
$element = $form-&gt;createElement('multicheckbox', 'set of elements');</p>

<p>// This works even with no upper case letter at 'select'
$element = $form-&gt;createElement('multiselect', 'set of elements');</p>

<p>// This works, but seems unnatural and causes problems with automatism
$element = $form-&gt;createElement('multiCheckbox', 'set of elements');
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Cristian Bichis (avantis) on 2010-01-05T01:37:05.000+0000</p> 
        <div class="body">
            <p>Yes, seems to be a problem related to this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-07-27T12:20:43.000+0000</p> 
        <div class="body">
            <p>ZF-5368:
{quote}For the record, Multiselect is the one that is misnamed, but we cannot rename it as it would introduce a BC break.{quote}</p>

        </div>
    </div>
    </div>

