<h2>ZF-7204: Create link that always redirects to the latest download package</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-07-06T08:59:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ben Ramsey (ramsey)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6297">ZF-6297</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Please create a central link (i.e. <a href="http://framework.zend.com/releases/latest.tar.gz">http://framework.zend.com/releases/latest.tar.gz</a> ) that always redirects  (or symlinks) to the latest Zend Framework release package. This way, third parties could create installers or deployment processes that can point to one location to download the most recent release package.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-20T13:49:24.000+0000</p> 
        <div class="body">
            <p>I will talk with Zend management to see if this is a feature we can implement.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-11-20T13:49:55.000+0000</p> 
        <div class="body">
            <p>There's a url available from which you can retrieve the latest stable release of ZF. By using this url, you don't have to download all of ZF first, which seems to me as an advantage over having to download the entire package each and every time. Therefore I'm closing this one as a duplicate</p>

<p>Url is: <a href="http://framework.zend.com/api/zf-version">http://framework.zend.com/api/zf-version</a></p>

<p>Edit; please see Matthew's comment. Will leave up to him (that means I'm not closing it ;))</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-20T13:53:35.000+0000</p> 
        <div class="body">
            <p>Actually, the API version is not the same thing as a link to the latest downloadable package.</p>

<p>Per our discussion on IRC, perhaps another REST API method for retrieving the URL to the latest downloadable package might solve this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:29.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

