<h2>ZF-799: Zend_Session_Core::setId() does not report failure under certain circumstances</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-25T21:35:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>session_id() must be called before session_start().</p>

<p>When not using cookie-based sessions, setId() does not throw an exception, if session_start() has already been called.</p>

<p>See <a href="http://www.php.net/session_id">http://www.php.net/session_id</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-25T22:12:26.000+0000</p> 
        <div class="body">
            <p>See Fisheye link above for changeset info.</p>

        </div>
    </div>
    </div>

