<h2>ZF-7102: Exception not propogated correctly if thrown from constructor</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-23T10:42:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-31T21:03:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stanislav Malyshev (stas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Consider a PHP Class with the following constructor:</p>

<pre><code>public function __construct() {
    $this-&gt;connection = mysql_connect($this-&gt;server,  $this-&gt;username,  $this-&gt;password);

    if(mysql_error()) {
        $msg = mysql_errno() . ": " . mysql_error();
        throw new Exception('MySQL Error - '. $msg);
    }

    mysql_select_db($this-&gt;databasename);
}
</code></pre>

<p>when an exception is thrown, Zend AMF ignores it and throws an exception with the message "Error instantiating class"</p>

<pre><code>            try {
                $object = $info-&gt;getDeclaringClass()-&gt;newInstance();
            } catch (Exception $e) {
                require_once 'Zend/Amf/Server/Exception.php';
                throw new Zend_Amf_Server_Exception('Error instantiating class ' . $class . ' to invoke method ' . $info-&gt;getName(), 621);
            }
</code></pre>

<p>While throwing this exception, ZendAMF should append the error message from the caught exception.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2009-06-30T17:26:17.000+0000</p> 
        <div class="body">
            <p>fixed</p>

        </div>
    </div>
    </div>

