<h2>ZF-732: Unit test failure, probably bug in unit test.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-09T11:32:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>phpunit  Zend_DateTest.php
X-Powered-By: PHP/5.1.6
Content-type: text/html</p>

<p>PHPUnit 3.0.0 by Sebastian Bergmann.</p>

<p>....................F....................
....E...........</p>

<p>Time: 00:05</p>

<p>There was 1 error:</p>

<p>1) testAddArpa(Zend_DateTest)
Zend_Date_Exception: invalid date (Fri, 05 Jan 07 03:35:53 GMT) operand, RFC 822 date format expected
/var/www/html/zftrunk/incubator/library/Zend/Date.php:1010
/var/www/html/zftrunk/incubator/library/Zend/Date.php:2972
/var/www/html/zftrunk/incubator/library/Zend/Date.php:2678
/var/www/html/zftrunk/incubator/library/Zend/Date.php:2700
/var/www/html/zftrunk/incubator/tests/Zend/DateTest.php:3256
/usr/local/php5/bin/phpunit:40
There was 1 failure:</p>

<p>1) testAdd(Zend_DateTest)  &lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt; looks like unit test is wrong, and not code
Failed asserting that </p><p></p>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-01-09T12:42:02.000+0000</p> 
        <div class="body">
            <p>I will check this, but also to mention :
With SVN 2659 no failure did show up, so anywhen after that commit the error was included.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-09T12:54:29.000+0000</p> 
        <div class="body">
            <p>$ svn update
At revision 2671.</p>

<p>$ php -v
PHP 5.1.6 (cgi-fcgi) (built: Oct 24 2006 19:38:28)
Copyright (c) 1997-2006 The PHP Group
Zend Engine v2.1.0, Copyright (c) 1998-2006 Zend Technologies</p>

<p>$ uname -a
Linux sandbox.zend.com 2.6.9-34.EL #1 Fri Feb 24 16:44:51 EST 2006 i686 i686 i386 GNU/Linux</p>

<p>Do you have an account on <a href="http://framework.zend.com/wiki/display/ZFDEV/Sandbox">http://framework.zend.com/wiki/display/…</a> ?</p>

<pre class="highlight"><code>
        $retour = $date-&gt;set(1234567890);
        $this-&gt;assertSame((string)$retour,'1234567890');
        $this-&gt;assertSame((string)$date-&gt;add(10),'1234567900');
        $this-&gt;assertSame((string)$date-&gt;add(-10),'1234567890');
        $this-&gt;assertSame((string)$date-&gt;add(1),'1234567890');
</code></pre>

<p>I do not see an intuitive reason why the last line of code would result add() yielding '1234567890' instead of '1234567891'.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-09T12:55:19.000+0000</p> 
        <div class="body">
            <p>The code above is from the unit test     public function testAdd()  in Zend/DateTest.php</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-09T12:57:16.000+0000</p> 
        <div class="body">
            <p>I suspect one of the recent commits fixed a bug, and now the unit test is failing, because the unit test was buggy.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-01-09T13:00:14.000+0000</p> 
        <div class="body">
            <p>Within SVN 2670 the following lines were changed by to throw an failure:</p>

<ul><li>$this-&gt;assertSame($date-&gt;add(0),'1234567890');</li>
<li>$this-&gt;assertSame((string)$date-&gt;add(1),'1234567890');</li>
</ul><p>I reverted the changed 1 to 0 as the addition of positive values is already checked with add(10).</p>

<p>Fixed with SVN 2672</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-09T13:10:02.000+0000</p> 
        <div class="body">
            <p>yup .. looks like that was my fault .. not sure how that 0 got changed to a 1 .. thanks :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-01-09T13:10:51.000+0000</p> 
        <div class="body">
            <p>Related to you question before:</p>

<p>No I dont have an account on the sandbox...
But I have my own testserver and I always test before I commit changed functions.</p>

<p>Related to reason:</p>

<p>The initial reason was to check if add(0) behaves correct.
You just changed the test and forgot also to change the result... only a typo.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-09T13:23:38.000+0000</p> 
        <div class="body">
            <p>I remember now .. I was running a quick test while we were chatting yesterday.  I forgot to undo the change.  Then there was a separate issue relating to needing the (string) cast in order for the unit tests to work correctly, when bcmath is not enabled.  So I expected that line of code to show up in "svn diff", but forgot to put the 1 back to 0.  Then I thought somehow the unit test was wrong, so I committed the code anyway, even though the code didn't pass that unit test.  I was right .. unit test was wrong .. but I made it wrong .. lol .. oops.</p>

        </div>
    </div>
    </div>

