<h2>ZF-7703: Int validator assumes 'en' Locale integers are valid, despite specifying a different locale</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-27T12:05:31.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-13T10:40:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12164/Int.php-greedy-locale.patch">Int.php-greedy-locale.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you specify a locale, the isValid() method validates the value with Zend_Locale_Format::isInteger() using the specified locale. However, In addition to the specified locale, it also validates with an 'en'-based Zend_Locale.</p>

<p>Should the validator assume that in all cases an 'en'-localized value is required, even though the user has explicitly defined which locale they wish to validate with?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Luke Barton (lbarton) on 2009-08-27T12:06:15.000+0000</p> 
        <div class="body">
            <p>Patch amending functionality.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-09-13T10:40:26.000+0000</p> 
        <div class="body">
            <p>Added with r18097</p>

        </div>
    </div>
    </div>

