<h2>ZF-7310: indexing stops after using it for 2 months.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-19T09:50:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-22T04:24:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>My senior left the company after establishing the search job function using zend search lucene without much documentation. I picked this up a few days ago ever since our employer posted job but it was not showing in our search job list. We've checked the DB and has confirmed nothing to do with the PHP side. The only suspect would be the indexing don't work any more. We have 2 domain using zend search lucene, the other one which is not so active work fine. The one domain which uses doesn't work anymore after 2 months using them.</p>

<p>I have been looking up and down for the solution, but to realize there's little reference online. I don't even know where to start debugging. Could you assist in leading me so that I can provide all the necessary info you might be requesting? Everything is working find 2 days ago.</p>

<p>I sincerely appreciate your help.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-07-20T15:13:46.000+0000</p> 
        <div class="body">
            <p>Without any code or exceptions this is kinda hard to solve. After all, we don't know your entire application. Maybe your cronjob (or whatever you use for updating the indexes) hasn't started any more lately?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-07-22T04:24:16.000+0000</p> 
        <div class="body">
            <p>I'm closing this issue as cannot reproduce as for there is no way to see what your problem is, and it seems to me pretty unlikely to be a bug in ZF.</p>

<p>Please reopen when you are able to reproduce this issue (or give a more specific clue on what's going wrong &amp; where it's going wrong).</p>

        </div>
    </div>
    </div>

