<h2>ZF-7924: BC Break in Zend_Db::factory()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-22T11:30:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-22T12:17:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.4 (13/Oct/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As noted on fw-general and #zftalk.dev, 1.9.3 introduces a BC break in regards to the documented (per API, not manual) behavior of Zend_Db::factory(), namely that the argument is case sensitive. The break should be reverted, while still supporting the fix for the adapter namespace case insensitivity.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-09-22T12:17:07.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk at r18372 and in branch release 1.9 at r18373</p>

        </div>
    </div>
    </div>

