<h2>ZF-7433: Wrong Dojo Version in ZF 1.9 Release</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-31T10:31:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-21T11:15:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to the release log of ZF1.9 the Dojo Release should be version 1.3.2. But it still seems to be 1.3.0. 
And why is it a dev-version? shouldn't it be a productive version for a stable ZF Release?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-09-21T11:14:03.000+0000</p> 
        <div class="body">
            <p>We tag to the 1.3 release branch, and report whatever the current version is available at the time.</p>

<p>The reason we tag to a release branch is to ensure we have the build tools available in the version we distribute, which is not possible if we use an official build.</p>

        </div>
    </div>
    </div>

