<h2>ZF-7112: Controller tests for modules won't be stored to module tests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-24T05:04:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-30T19:50:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.4 (03/Mar/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dennis Becker (radhad)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When you create a controller with "zf create controller index 1 blog", the IndexControllerTest.php get's stored under with the following comment:</p>

<p>Creating a controller test file at /..../tests/application/controllers/IndexControllerTest.php</p>

<p>But it should be stored unter</p>

<p>/..../tests/application/modules/blog/controllers/IndexControllerTest.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alex (zocki) on 2009-07-30T05:19:13.000+0000</p> 
        <div class="body">
            <p>I also noticed this issue. Also when you create another index controller in another module it will overwrite the existing IndexControllerTest in tests/controllers</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Przemys?aw Wróbel (wrobel) on 2011-01-05T01:22:59.000+0000</p> 
        <div class="body">
            <p>I have the same problem. Tests for contollers does not support modular structure!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-04-30T19:50:14.000+0000</p> 
        <div class="body">
            <p>Already was fixed in 1.11.4 see article <a href="http://dz.zend.com/a/13192">http://dz.zend.com/a/13192</a></p>

        </div>
    </div>
    </div>

