<h2>ZF-7438: A few typos prevent zf.php from using the ZEND_TOOL_INCLUDE_PATH_PREPEND environment variable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-01T01:56:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-12T10:39:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.1 (11/Aug/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                adsfadsf (staskorz)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12118/zf.php.patch">zf.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When the environment variable "ZEND_TOOL_INCLUDE_PATH_PREPEND" is set, zf.php throws notices and refuses to work because it cannot find "Zend Framework", even though its path is set in "ZEND_TOOL_INCLUDE_PATH_PREPEND".</p>

<p>Inspecting "zf.php" revealed the following:</p>

<ol><li><p>on line 67:
    $_ENV['HOME']
must be changed to:
    $_zf['HOME']</p></li>
<li><p>on line 140:
double "$$" should be changed to single "$"</p></li>
</ol><p>Patch:</p>

<p>67c67</p>

<h2>&lt;         $_zf['STORAGE_DIR'] = $_ENV['HOME'] . '/.zf/';</h2>

<blockquote>
<pre><code>    $_zf['STORAGE_DIR'] = $_zf['HOME'] . '/.zf/';
</code></pre>
  
  <p>140c140</p>
</blockquote>

<h2>&lt;         if (isset($zfIncludePath['prepend']) &amp;&amp; ($zfIncludePath['prepend'] !== false) &amp;&amp; (($zfIncludePath['prependRealpath'] = realpath($$zfIncludePath['prepend'])) !== false)) {</h2>

<blockquote>
<pre><code>    if (isset($zfIncludePath['prepend']) &amp;&amp; ($zfIncludePath['prepend'] !== false) &amp;&amp; (($zfIncludePath['prependRealpath'] = realpath($zfIncludePath['prepend'])) !== false)) {
</code></pre>
</blockquote>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-10T10:11:36.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk in r17522 and 1.9 release branch in r17524</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-08-12T10:39:25.000+0000</p> 
        <div class="body">
            <p>Updating fix information</p>

        </div>
    </div>
    </div>

