<h2>ZF-7836: SubForm elements not aware of all parents. (before render)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-12T09:43:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gustav Ernberg (gernberg)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Sample code</p>

<pre class="highlight"><code>
class Test extends Zend_Form{
    function init() {
        $this-&gt;setElementsBelongTo("tree");
        $branch = new Zend_Form();
        $branch-&gt;setElementsBelongTo("branch");
        $branch-&gt;addElement("text", "leaf");
        $this-&gt;addSubForm($branch, "branch");
        echo $this-&gt;getSubForm("branch")-&gt;getElement("leaf")-&gt;getFullyQualifiedName();
    }
}
</code></pre>

<p>Echos "branch[leaf]" and not expected "tree[branch][leaf]"
When the whole form is rendered the getFullyQualifiedName() of the element is (as expected) "tree[branch][leaf]".</p>

<p>Am I missing something here?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:38.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

