<h2>ZF-7387: Zend_Queue_Adapter_Db calls getLogger(undefined)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-26T07:00:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-07T18:04:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Queue</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Queue_Adapter_Db's create method call "getLogger " (initial commit remain?).
So, createing new queue is not succeed.
"Fatal error: Call to undefined method Zend_Queue_Adapter_Db::getLogger() in /usr/share/php/Zend/Queue/Adapter/Db.php on line 178"</p>

<p>please remove "getLogger()" line.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-07-26T08:31:38.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and 1.9 release branch.</p>

        </div>
    </div>
    </div>

