<h2>ZF-7295: Zend_Date toString('e') function counts weekdays now from 0</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-07-16T04:54:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-25T15:15:01.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Date toString() function with parameter 'e' counts weekdays now from 0 instate from 1 like it  is written in the documentation.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-25T15:10:09.000+0000</p> 
        <div class="body">
            <p>'e' which is equal to WEEKDAY_DIGIT counts from 0 to 6 as mentioned in the manual.</p>

<p>I have not found a description where it was mentioned that it counts from 1 to 7 (which is only the case for WEEKDAY_8601).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-25T15:15:00.000+0000</p> 
        <div class="body">
            <p>Mentioned issue not reproducable.</p>

<p>Fixed only a wrong constant (which also uses 0-6) but no description like mentioned from the reporter has been found.</p>

        </div>
    </div>
    </div>

