<h2>ZF-7864: Zend_Currency::toCurrency() ignores option param &quot;currency&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-17T02:47:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-28T11:02:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dennis Becker (radhad)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Currency</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12246/CurrencyTest.php.patch">CurrencyTest.php.patch</a></li>
            <li><a href="/issues/secure/attachment/12203/Zend_Currency.patch">Zend_Currency.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I always use an instance of Zend_Currency to display prices etc. Now I ran into a bug after upgrading from 1.7.8 to 1.9.2 - the toCurrency method ignores the currency value in the option array.  Here is a small test I used:</p>

<pre class="highlight"><code>
$value = '';
$currencyObject = new Zend_Currency('de_DE');
$value = $currencyObject-&gt;toCurrency(2.3, array('currency' =&gt; 'USD', 'precision' =&gt; 4));
Zend_Debug::dump($value); // prints "2,3000 €" - expected "2,3000 $"

$value = '';
$currencyObject = new Zend_Currency('USD', 'de_DE');
$value = $currencyObject-&gt;toCurrency(2.3, array('precision' =&gt; 4));
Zend_Debug::dump($value); // prints "2,3000 $" as expected
</code></pre>

<p>The first example is often used, because I cannot know which currency should be used for the customer - so setting the currency while converting is a must have for me. If I see it right, the bug depends on getSymbol() which results in an error if no locale is given. I will add a patch which corrects the problem for me.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dennis Becker (radhad) on 2009-09-18T02:19:13.000+0000</p> 
        <div class="body">
            <p>I will add additionally a Unit-Test patch ( I read the "Bughunt day" notification today) so that it does not need to be double-researched. This will take some minutes I think ;) Just wait until I have uploaded it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dennis Becker (radhad) on 2009-09-22T06:27:17.000+0000</p> 
        <div class="body">
            <p>Added UnitTest to CurrencyTest.php</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-09-28T10:56:51.000+0000</p> 
        <div class="body">
            <p>Note that this "patch" introduces a new problem and can not be used as is.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-09-28T11:02:18.000+0000</p> 
        <div class="body">
            <p>Note that your provided example set's another display type at initiation than at output. This leads to the behaviour that the output uses another display that the one you set. If you would set the wished display type then the code would work. This has not changed since ZF 1.7.8.</p>

<p>Fixed with a new feature to automatically detect the wished display type. (r18432)</p>

        </div>
    </div>
    </div>

