<h2>ZF-7432: Problem updating tinyint</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-31T08:21:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-09T21:45:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>I'm with a problem, i have a tinyint field and i'm trying to update this field but it always update to "1" value wherever the value i send, i will post my code</p>

<p>$data = array(
'moderate' =&gt; 2
);
$select = $this-&gt;db-&gt;quoteInto('id=?',$image-&gt;id);
$r = $tableImages-&gt;update($data,$select);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-07-31T10:06:22.000+0000</p> 
        <div class="body">
            <p>I have attempted to reproduce, but cannot.  I am using mysql 5.0.51a-log, updating a field that is defined by tinyint(1).</p>

<p>Without more details, and the specifics of your database, its hard to determine what is going wrong.  I have a feeling though, that the problem you are experiencing is not Zend_Db related, but is database and/or scheam specific.</p>

<p>If you have more details, feel free to reopen.</p>

<p>Thanks,
Ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Cardozo (jonathan.cardozo) on 2009-07-31T10:54:07.000+0000</p> 
        <div class="body">
            <p>I will post my table sql</p>

<p>CREATE TABLE <code>pepsi_ecards_images</code> (
  <code>id</code> int(11) NOT NULL auto_increment,
  <code>user_id</code> int(11) default '0',
  <code>filename</code> varchar(255) default NULL,
  <code>moderate</code> tinyint(1) default '0',
  <code>created_at</code> datetime default NULL,
  <code>from_country</code> varchar(3) default NULL,
  <code>from</code> tinyint(4) default '0',
  PRIMARY KEY  (<code>id</code>)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Cardozo (jonathan.cardozo) on 2009-07-31T11:12:09.000+0000</p> 
        <div class="body">
            <p>I will post my table sql</p>

<p>CREATE TABLE <code>pepsi_ecards_images</code> (
<code>id</code> int(11) NOT NULL auto_increment,
<code>user_id</code> int(11) default '0',
<code>filename</code> varchar(255) default NULL,
<code>moderate</code> tinyint(1) default '0',
<code>created_at</code> datetime default NULL,
<code>from_country</code> varchar(3) default NULL,
<code>from</code> tinyint(4) default '0',
PRIMARY KEY (<code>id</code>)
) ENGINE=InnoDB AUTO_INCREMENT=51 DEFAULT CHARSET=utf8;</p>

<p>database</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2009-07-31T12:57:57.000+0000</p> 
        <div class="body">
            <p>Sorry, still cannot reproduce.  I added a record (with id 51 as expected) to your schema you provided, and ran this code:</p>

<pre class="highlight"><code>
$db = Zend_Db::factory('Pdo_Mysql', array('username' =&gt; 'developer', 'dbname' =&gt; 'test', 'password' =&gt; 'developer'));
Zend_Db_Table::setDefaultAdapter($db);

$table = new Zend_Db_Table('pepsi_ecards_images');

$table-&gt;update(array('moderate' =&gt; 4), 'id = 51');
var_dump($table-&gt;fetchAll()-&gt;toArray());
</code></pre>

<p>After checking the database, i can see the value that i provided.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Cardozo (jonathan.cardozo) on 2009-08-03T11:29:53.000+0000</p> 
        <div class="body">
            <p>The problem persists, after many tests, i put my sqls in a logfile and see that the value dont is inserter the SQL persists with "?" when i put new</p>

<p>$data = array(
                    'moderate' =&gt; new Zend_Db_Expr("2")
                );</p>

<p>the sql is correct but the value dont change in DB</p>

<p>I create a file only to execute this sabe SQl and it works, my conclusin is the problem is witch zend framework.</p>

<p>this is my code of my file that wworks</p>

&lt;?php
error_reporting(E_ALL);
$banco = new PDO('mysql:host=XXXXXX;dbname=XXXXXX, 'pepsimundo_web','XXXXX');
$dados = array(5,52);
$r = $banco-&gt;prepare('UPDATE `pepsi_ecards_images` SET `moderate` = ? WHERE (id = ?)')-&gt;execute($dados);
var_dump($r);
?&gt;

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-08-03T11:49:23.000+0000</p> 
        <div class="body">
            <p>If this would indeed proof to be an issue within ZF, a lot of people would have this problem (which is not the case). That by itself makes me believe it's /not/ a bug in ZF (besides, noone seems to be able to reproduce). So you really need to do some debugging here (it's probably something very simple).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Aleksandar (tasmaniski) on 2012-02-09T21:34:50.000+0000</p> 
        <div class="body">
            <p>Nope, doesn't work. Here is my code:</p>

<p>// this is my model where I trying to update column in mysql which is type tinyint, 
class Application_Model_DbTable_Users extends Zend_Db_Table_Abstract {
    public function updateRow($data, $id) {
        $this-&gt;update($data, array('id = ?' =&gt; $id) );
    }
}
// so $data = array('is_active'=&gt;1)</p>

<p>when I try to update column in db my model function updateRow(...) doesnt work,
but if I write my model in this way</p>

<p>class Application_Model_DbTable_Users extends Zend_Db_Table_Abstract {
    public function updateRow($data, $id) {
        $this-&gt;update($data, "id = $id"));
    }
}</p>

<p>It works ??</p>

<p>Any idea?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Aleksandar (tasmaniski) on 2012-02-09T21:45:17.000+0000</p> 
        <div class="body">
            <p>No, sorry, 
it work! My mistake...</p>

        </div>
    </div>
    </div>

