<h2>ZF-7407: *_Transfer_Adapter_Http</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-28T12:49:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-28T13:31:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dustin Sweigart (dustins)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7376">ZF-7376</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am not positive if this is a bug or me just not understanding how this is working, but in the adapter abstract it casts every option value as a boolean, which causes problems when it tries to access the magicFile option because it is then set as a boolean instead of the magic file path string.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-28T13:30:29.000+0000</p> 
        <div class="body">
            <p>Duplicate of ZF-7376.</p>

        </div>
    </div>
    </div>

