<h2>ZF-749: Exception handling for certain errors fail to provide correct diagnostic information</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-13T18:01:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Changeset 2511 removed the use of Zend::exception(), but dropped the information regarding function and line number:
<a href="http://framework.zend.com/fisheye/browse/Zend_Framework/trunk/library/Zend/Session/Core.php?r1=2462&amp;r2=2511">http://framework.zend.com/fisheye/browse/…</a></p>

<p>These areas in the code need to be refactored to produce correct stack traces and accurate diagnostic information.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-13T23:02:02.000+0000</p> 
        <div class="body">
            <p>See Fisheye link for changeset info.</p>

        </div>
    </div>
    </div>

