<h2>ZF-742: Unnecessary Cloning of $this</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-01-12T12:53:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10206/cloning.patch">cloning.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Numerous operations unecessarily return cloned instances of the object.
I will attach suggested patch to improve performance.</p>

<p>All unit tests for Zend_Locale*, Zend_Date*, and Zend_Meausre* classes pass after applying the patch.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-12T12:54:09.000+0000</p> 
        <div class="body">
            <p>please review and comment</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-01-12T12:55:41.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
-        if ($part !== null or (!is_numeric($date))) {
+        if (($part !== null &amp;&amp; $part !== Zend_Date::TIMESTAMP) or (!is_numeric($date))) {
</code></pre>

<p>The patch also contains another minor tweak to remove a great deal of extra processing when constructing new Zend_Date's from timestamps.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-01-13T15:39:02.000+0000</p> 
        <div class="body">
            <p>Reviewed and accepted</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-01-13T15:39:54.000+0000</p> 
        <div class="body">
            <p>Proposed change included with SVN 2729</p>

        </div>
    </div>
    </div>

