<h2>ZF-7101: Cannot call include_once('Zend/Gdata/App.php') before calling include_once('Zend/Gdata.php')</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-23T09:45:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-23T10:12:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the event a user attempts to call include_once('Zend/Gdata/App.php') before calling include_once('Zend/Gdata.php'), the following error is output:</p>

<pre class="literal">
PHP Fatal error:  Class 'Zend_Gdata_App' not found in .../library/Zend/Gdata.php on line 240
PHP Stack trace:
PHP   1. {main}() php shell code:0
PHP   2. include_once() php shell code:1
PHP   3. require_once() .../library/Zend/Gdata/App.php:26
PHP   4. require_once() .../library/Zend/Gdata/Feed.php:0
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-06-23T10:12:13.000+0000</p> 
        <div class="body">
            <p>Fixed for trunk as r16261.</p>

<p>{quote}
<em>commit 53e7ee007f43122aa606b24fcd1388f1d5976c35</em>
Author: tjohns &lt;tjohns@44c647ce-9c0f-0410-b52a-842ac1e357ba&gt;
Date:   Tue Jun 23 16:54:56 2009 +0000</p>

<pre><code>ZF-7101: Remove dependency on Zend_Gdata_Feed in Zend_Gdata_App, since this is circular and App classes shouldn't depend on non-App classes.

Old dependency chain: Zend_Gdata_App -&gt; Zend_Gdata_Feed -&gt; Zend_Gdata -&gt; Zend_Gdata_App
New dependency chain: Zend_Gdata_App -&gt; Zend_Gdata_App_Feed

git-svn-id: &lt;a rel="nofollow" href="http://framework.zend.com/svn/framework/standard/trunk@16261"&gt;http://framework.zend.com/svn/framework/&amp;hellip;&lt;/a&gt; 44c647ce-9c0f-0410-b52a-842ac1e357ba
</code></pre>

<p>library/Zend/Gdata/App.php |    4 ++--
 1 files changed, 2 insertions(+), 2 deletions(-)
{quote}</p>

        </div>
    </div>
    </div>

