<h2>ZF-7245: subTime() throws an exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-11T17:13:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-12T00:53:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm trying to use Zend_Date-&gt;subTime(), but it keeps giving me an exception. Now I could very well be misusing this functionality as for it isn't documented in the reference guide.</p>

<p>Exception:</p>

<pre class="highlight"><code>$ php5 test.php

Fatal error: Uncaught exception 'Zend_Date_Exception' with message 'Unknown date format, neither date nor time in 'c' found' in /home/dolf/Projects/.ZS4E.Workspace/ZF-Standard-Trunk/library/Zend/Date.php:2687
Stack trace:
#0 /home/dolf/Projects/.ZS4E.Workspace/ZF-Standard-Trunk/library/Zend/Date.php(2753): Zend_Date-&gt;_time('sub', '2009-07-01', 'c', NULL)
#1 /home/dolf/Projects/.ZS4E.Workspace/ZF-Standard-Trunk/library/test.php(5): Zend_Date-&gt;subTime('2009-07-01', 'c')
#2 {main}
  thrown in /home/dolf/Projects/.ZS4E.Workspace/ZF-Standard-Trunk/library/Zend/Date.php on line 2687</code></pre>

<p>Code:</p>

<pre class="highlight"><code>$ cat test.php
&lt;?php
require_once 'Zend/Date.php';
$date = new Zend_Date('2009-07-11 21:07:46',Zend_Date::ISO_8601);

echo $date-&gt;subTime('2009-07-01',Zend_Date::ISO_8601);</code></pre>

<p>This was done on trunk</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-12T00:32:55.000+0000</p> 
        <div class="body">
            <p>According to API doc the method subTime() substracts the time part of a date from the actual set date.</p>

<p>But you did not gave a time part, only a date part... as no time part has been found in your input a exception is thrown.</p>

        </div>
    </div>
    </div>

