<h2>ZF-7785: Zend_controller request can not find param</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-06T14:09:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-18T23:55:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is a small bug stpid mistake in zend request of a Zend_Controller_Action class.</p>

<p>If you have get requests of an url the method $this-&gt;getRequest(); can't find last param if there is no value defined for this last param.</p>

<p>If I display this getrequest method with var_dump() function I can see all params but not the last one.</p>

<p>for testing I used the following url:</p>

<p>/test/detail/su/31/tab/3/pa/1/cpho//csub/eee/csur//cfor//cfor1/</p>

<p>So I get this array back:</p>

<p>array(10) {
    ["controller"]=&gt;
    string(8) "test"
    ["action"]=&gt;
    string(6) "detail"
    ["su"]=&gt;
    string(2) "31"
    ["tab"]=&gt;
    string(1) "3"
    ["pa"]=&gt;
    string(1) "1"
    ["cpho"]=&gt;
    string(0) ""
    ["csub"]=&gt;
    string(3) "eee"
    ["csur"]=&gt;
    string(0) ""
    ["cfor"]=&gt;
    string(0) ""
    ["module"]=&gt;
    string(7) "default"
  }</p>

<p>This is stupid if I always check at request that the last param was gave over by this url but only rendered if this param has a value. Sometimes it also can have a empty value.</p>

<p>Because of this I think that this bug should fixed.</p>

<p>best regards</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2009-09-17T14:17:10.000+0000</p> 
        <div class="body">
            <p>Please take a look at your url:</p>

<p>{{/test/detail/su/31/tab/3/pa/1/cpho{color:red}//{color}csub/eee/csur{color:red}//{color}cfor//cfor1/}}</p>

<p>It contains // which should cause your problem.</p>

<pre class="highlight"><code>array(10) {
  ["module"] =&gt; string(7) "default"
  ["controller"] =&gt; string(4) "test"
  ["action"] =&gt; string(6) "detail"
  ["su"] =&gt; string(2) "31"
  ["tab"] =&gt; string(1) "3"
  ["pa"] =&gt; string(1) "1"
  ["cpho"] =&gt; string(0) ""
  ["csub"] =&gt; string(3) "eee"
  ["csur"] =&gt; string(0) ""
  ["cfor"] =&gt; string(0) ""
}</code></pre>

<pre class="highlight"><code>array(9) {
  ["module"] =&gt; string(7) "default"
  ["controller"] =&gt; string(4) "test"
  ["action"] =&gt; string(6) "detail"
  ["su"] =&gt; string(2) "31"
  ["tab"] =&gt; string(1) "3"
  ["pa"] =&gt; string(1) "1"
  ["cpho"] =&gt; string(4) "csub"
  ["eee"] =&gt; string(4) "csur"
  ["cfor"] =&gt; string(5) "cfor1"
}</code></pre>

        </div>
    </div>
    </div>

