<h2>ZF-7077: Zend_Gdata MIME streaming support broken</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-21T20:45:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-06-21T21:02:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.8.4 (23/Jun/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The MIME streaming support in Zend_Gdata is currently very broken. It sometimes works, but uploads fail under certain conditions (which are not fully understood).</p>

<p>For example, when uploading very small videos, the video may be included twice within the HTTP request.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-06-21T20:50:30.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk by r16229.</p>

<pre class="literal">
commit 5aa2e3fe8acae2c676e1b782b77d408e56e0e7d4
Author: tjohns 
Date:   Mon Jun 22 03:48:59 2009 +0000

    Patch to fix several bugs in Zend_Gdata_YouTube and Zend_Gdata multipart MIME support.
    
    ZF-7075: Update Zend_Gdata URL constants to include 'api' projection.
    ZF-7076: User specified URLs are now preferred over edit links when working with Zend_Gdata media entries.
    ZF-7077: Rewrite Zend_Gdata MIME streaming support to correct erratic behavior.
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/trunk@16229">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac1e357ba

 library/Zend/Gdata/App.php                        |    2 +-
 library/Zend/Gdata/HttpAdapterStreamingSocket.php |    7 +-
 library/Zend/Gdata/MediaMimeStream.php            |  424 +++------------------
 library/Zend/Gdata/MimeBodyString.php             |   91 +++++
 library/Zend/Gdata/MimeFile.php                   |   65 ++++
 library/Zend/Gdata/YouTube.php                    |    8 +-
 6 files changed, 216 insertions(+), 381 deletions(-)
</pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-06-21T21:02:43.000+0000</p> 
        <div class="body">
            <p>Merged r16229 from trunk to release-1.8.</p>

<p>Marking as fixed for next mini release.</p>

<pre class="literal">
commit 6b8e06a2df94cc3c87dfb90d2bb1afc91ab26681
Author: tjohns 
Date:   Mon Jun 22 03:57:13 2009 +0000

    Merge r16229 from trunk to release-1.8.
    
    Patch to fix several bugs in Zend_Gdata_YouTube and Zend_Gdata multipart MIME support.
    
    ZF-7075: Update Zend_Gdata URL constants to include 'api' projection.
    ZF-7076: User specified URLs are now preferred over edit links when working with Zend_Gdata media entries.
    ZF-7077: Rewrite Zend_Gdata MIME streaming support to correct erratic behavior.
    
    git-svn-id: <a href="http://framework.zend.com/svn/framework/standard/branches/release-1.8@16234">http://framework.zend.com/svn/framework/…</a> 44c647ce-9c0f-0410-b52a-842ac1e357ba

 library/Zend/Gdata/App.php                        |    2 +-
 library/Zend/Gdata/HttpAdapterStreamingSocket.php |    7 +-
 library/Zend/Gdata/MediaMimeStream.php            |  424 +++------------------
 library/Zend/Gdata/MimeBodyString.php             |   91 +++++
 library/Zend/Gdata/MimeFile.php                   |   65 ++++
 library/Zend/Gdata/YouTube.php                    |    8 +-
 6 files changed, 216 insertions(+), 381 deletions(-)
</pre>

        </div>
    </div>
    </div>

