<h2>ZF-7434: Too many pages with empty content</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-31T10:39:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-04-10T19:03:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.6 (05/May/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I use a Paginator with DBSelect for querying the database. See the following code:</p>

<pre class="highlight"><code>
        $select = $this-&gt;db-&gt;select();
        $select-&gt;from(array("v" =&gt; "table"), 
                      array("DateDayFormat" =&gt; new Zend_Db_Expr("DATE_FORMAT(v.FirstVisitTime, '%d.%m.%Y')"),
                            "PageCalls" =&gt; new Zend_Db_Expr("SUM(v.PageCalls)"),
                            ))
               -&gt;group("DATE(v.FirstVisitTime)")
               -&gt;order("DATE(v.FirstVisitTime) DESC");
        $paginator = new Zend_Paginator(new Zend_Paginator_Adapter_DbSelect($select));
        $paginator-&gt;setItemCountPerPage(20);
        $paginator-&gt;setCurrentPageNumber($this-&gt;_getParam("page", 1));
        $this-&gt;view-&gt;paginator = $paginator;
</code></pre>

<p>The select should return 6.5 pages, but there are 42 pages. the 7th to the 42nd page are empty. 
this problem occurs also with other selects, so it seems to be a bug - or did you change something, that would explain this strange behavior?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-07-31T10:48:30.000+0000</p> 
        <div class="body">
            <p>Could you paste the result of this snippet?</p>

<pre class="highlight"><code>
echo $paginator-&gt;getAdapter()-&gt;getCountSelect();
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Master Surfer (mastersurfer84) on 2009-07-31T10:51:54.000+0000</p> 
        <div class="body">
            <p>The Result is:
SELECT COUNT(1) AS <code>zend_paginator_row_count</code> FROM <code>mvc_visitors</code> AS <code>v</code></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jurrien Stutterheim (norm2782) on 2009-07-31T11:17:43.000+0000</p> 
        <div class="body">
            <p>Could you try rewriting your code like the following snippet and see if it gives the expected result? Could you also echo the count select again with the following snippet?</p>

<pre class="highlight"><code>
$select = $this-&gt;db-&gt;select();
$select-&gt;from(array("v" =&gt; "table"), 
              array("DateDayFormat" =&gt; new Zend_Db_Expr("DATE_FORMAT(v.FirstVisitTime, '%d.%m.%Y')"),
                    "PageCalls" =&gt; new Zend_Db_Expr("SUM(v.PageCalls)"),
                    ))
       -&gt;group(new Zend_Db_Expr("DATE(v.FirstVisitTime)"))
       -&gt;order(new Zend_Db_Expr("DATE(v.FirstVisitTime) DESC"));
</code></pre>

<p>My guess is that the lack of Zend_Db_Expr is causing the problems. I'm going to see if this is something Zend_Paginator can do something about.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Master Surfer (mastersurfer84) on 2009-07-31T12:37:32.000+0000</p> 
        <div class="body">
            <p>so, i changes the group and order clauses as you wrote.
unfortunately the result is the same.
here the count infos:</p>

<p>the count-select-string:
string(72) "SELECT COUNT(1) AS <code>zend_paginator_row_count</code> FROM <code>mvc_visitors</code> AS <code>v</code>"</p>

<p>and the result of this query
array(1) {
  [0] =&gt; array(1) {
    ["zend_paginator_row_count"] =&gt; string(3) "839"
  }
}</p>

<p>that is the same as the direct query in phpmyadmin. so the sql works correct (why shouldn't it ;-) )</p>

<p>this problem occoured first with 1.9 release. i think the aggregation in the sql is the problem, but in 1.8.x it worked all fine.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2009-11-19T21:34:40.000+0000</p> 
        <div class="body">
            <p>Problem object Zend_Db_Expr in class Zend_Paginator_Adapter_DbSelect::getCountSelect()
line 231</p>

<pre class="highlight"><code>
 !($groupParts[0] instanceof Zend_Db_Expr)
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-02-17T19:41:23.000+0000</p> 
        <div class="body">
            <p>This problem only occur with one column in the group and when the same column is envolved by a Zend_Db_Expr().</p>

<p>Reproduced with:</p>

<pre class="highlight"><code>
$select-&gt;from('test', 'group')
       -&gt;group(new Zend_Db_Expr('group'));
</code></pre>

<p>Fix in Zend_Paginator_Adapter_DbSelect in the line 232 condition current code</p>

<pre class="highlight"><code>
} else if (!empty($groupParts) &amp;&amp; $groupParts[0] !== Zend_Db_Select::SQL_WILDCARD &amp;&amp;
           !($groupParts[0] instanceof Zend_Db_Expr)) {
               $groupPart = $db-&gt;quoteIdentifier($groupParts[0], true);
}
</code></pre>

<p>Change to</p>

<pre class="highlight"><code>
} else if (!empty($groupParts)) {
    $groupPart = $db-&gt;quoteIdentifier($groupParts[0], true);
}
</code></pre>

<p>Also was deleted the condition <em>$groupParts[0] !== Zend_Db_Select::SQL_WILDCARD</em> no makes sense group by * until because this already is a error of SQL.</p>

<p>Grettings
Ramon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-02-17T19:53:43.000+0000</p> 
        <div class="body">
            <p>I've added a fix for this issue in r23717 in trunk.
Please test your applications against this.</p>

<p>If this works for everyone, I will merge to 1.11.</p>

<p>Thanks since already
Ramon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-04-10T19:03:53.000+0000</p> 
        <div class="body">
            <p>Merged r23855 to release branch 1.11.</p>

        </div>
    </div>
    </div>

