<h2>ZF-7719: Zend_Date change default output format</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-08-29T03:18:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8937">ZF-8937</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I miss some functionality like Zend_Date::setDefaultFormat('mm.YY'); or Zend_Date::setOption('defaultOutput', 'mm.YY');
that will change the default output format for __toString() etc application wide for any instanciated Zend_Date.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2009-11-20T13:25:41.000+0000</p> 
        <div class="body">
            <p>Per the documentation (and the code) there's a toString() method, which accepts the date format as it's first parameter: <a href="http://framework.zend.com/manual/en/zend.date.constants.html#zend.date.constants.phpformats">http://framework.zend.com/manual/en/…</a></p>

<p>So this could be easily achieved as:</p>

<pre class="highlight"><code>
define(MY_DATE_FORMAT, 'Y-m-d H:i:s');

echo $date-&gt;toString(MY_DATE_FORMAT);
</code></pre>

        </div>
    </div>
    </div>

