<h2>ZF-7437: Zend_Rest_Route defaulting to a non-existent 'listAction'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-31T21:41:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-08-25T22:30:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Luke Crouch (lcrouch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Rest_Route</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7598">ZF-7598</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12117/ZF-7437.patch">ZF-7437.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When extending Zend_Rest_Controller you are required to define the index, get, post, put, and delete actions.</p>

<p>Yet Zend_Rest_Route attempts to call the non-existent 'listAction' in the following block of code in match():</p>

<pre class="highlight"><code>
            // Check for leading "special get" URI's 
            $specialGetTarget = false;
            if ($pathElementCount &amp;&amp; array_search($path[0], array('index', 'new')) &gt; -1) { 
                $specialGetTarget = array_shift($path);
            } elseif ($pathElementCount == 1) {
                 $params['id'] = array_shift($path);
            } elseif ($pathElementCount == 0 || $pathElementCount &gt; 1) {
                $specialGetTarget = 'list';
            }
</code></pre>

<p>This results in the following exception and trace:</p>

<pre class="literal">
Exception information:

Message: Action "list" does not exist and was not trapped in __call()
Stack trace:

#0 /Users/hobodave/dev/php/blog/library/Zend/Controller/Action.php(515): Zend_Controller_Action-&gt;__call('listAction', Array)
#1 /Users/hobodave/dev/php/blog/library/Zend/Controller/Dispatcher/Standard.php(289): Zend_Controller_Action-&gt;dispatch('listAction')
</pre>

<p>The documentation doesn't mention any 'listAction', which leads me to believe the correct solution is to change 'list' to 'index'.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by David Abdemoulaie (hobodave) on 2009-07-31T22:06:31.000+0000</p> 
        <div class="body">
            <p>Attached patch creating a new unit test to cover this, as well as the fix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Holger Schäfer (hschaefer123) on 2009-08-14T05:23:34.000+0000</p> 
        <div class="body">
            <p>I'm using rest services implementing Zend_Rest_Controller as action controller. The service interface
lacks the used listAction.
Fixing this problems maybe needs also changes in the service interface (listAction()....)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Luke Crouch (groovecoder) on 2009-08-19T06:47:14.000+0000</p> 
        <div class="body">
            <p>Hey guys ... sorry for the delay.</p>

<p>I'll get started on this and the other Zend_Rest bugs ASAP.</p>

<p>thanks,
-L</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-08-21T19:04:45.000+0000</p> 
        <div class="body">
            <p>Set component and change assinee</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-08-25T22:30:04.000+0000</p> 
        <div class="body">
            <p>Set Fix Version. may be SVN r17812.</p>

        </div>
    </div>
    </div>

