<h2>ZF-729: Unable to delete calender events when using ClientLogin authentication method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-08T21:26:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I do not seem to be able to delete calender events if I have used the ClientLogin authentication method. It does work with AuthSub however. I have tried with my own code and also the demo that was provided.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-12T12:58:28.000+0000</p> 
        <div class="body">
            <p>I can't find any mention in the Gdata Calendar or Protocol documentation that suggests there is an incompatibility between AuthSub and ClientLogin with respect to delete requests.   I just tried a delete of a calendar entry with both AuthSub and ClientLogin, and I dumped out the Zend_Http_Response object.  But I see that the response is different when using the two authentication methods.</p>

<p>Here's the response when using AuthSub.  This successfully deletes the calendar entry:</p>

<pre class="highlight"><code>
Zend_Http_Response Object
(
    [version:protected] =&gt; 1.1
    [code:protected] =&gt; 200
    [message:protected] =&gt; OK
    [headers:protected] =&gt; Array
        (
            [Cache-control] =&gt; private
            [Content-length] =&gt; 0
            [Date] =&gt; Fri, 12 Jan 2007 18:39:47 GMT
            [Content-type] =&gt; text/html
            [Server] =&gt; GFE/1.3
        )

    [body:protected] =&gt; 
)
</code></pre>

<p>Here's what is returned when using ClientLogin.  This does not delete the calendar entry:</p>

<pre class="highlight"><code>
Zend_Http_Response Object
(
    [version:protected] =&gt; 1.1
    [code:protected] =&gt; 200
    [message:protected] =&gt; OK
    [headers:protected] =&gt; Array
        (
            [Content-type] =&gt; application/atom+xml; charset=UTF-8
            [Last-modified] =&gt; Wed, 10 Jan 2007 20:04:49 GMT
            [Cache-control] =&gt; max-age=0, must-revalidate, private
            [Content-length] =&gt; 1898
            [Date] =&gt; Fri, 12 Jan 2007 18:38:40 GMT
            [Server] =&gt; GFE/1.3
        )


    [body:protected] =&gt; <a href="http://www.google.com/calendar/feeds/default/private/full/4vupp9846lj16gb4aq8gqh7nrc">http://google.com/calendar/feeds/…</a>...
)
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-12T13:46:55.000+0000</p> 
        <div class="body">
            <p>I have committed a fix in revision 2711 in our subversion repository.  The problem was in a place where the Http Client used by the ClientLogin authentication did not correctly set the 'strictredirects' property, so the redirect of the DELETE was being converted into a GET request.  This returns a status of 200, but of course does not actually delete the calendar entry.</p>

<p>With the fixed code, the CalendarDemo-ClientLogin.php script works, with no modification.  So any PHP code using Zend_Gdata should be able to take advantage of this fix with no code change.</p>

        </div>
    </div>
    </div>

