<h2>ZF-7551: Router_Route + translate, warning when translation is unavailable</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-10T08:47:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marek (xorock)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>With translated routes and locale based on BROWSER detection, when specific gettext translation is unavailable Zend_Controller_Router_Route throws warnings.</p>

<p>Notice: Undefined index: fr in .../Zend/Translate/Adapter.php on line 403 
Warning: array_search(): Wrong datatype for second argument in .../Zend/Controller/Router/Route.php on line 257</p>

<p>Zend_translate started with options:</p>

<pre class="highlight"><code>
array('scan' =&gt; Zend_Translate::LOCALE_DIRECTORY, 'disableNotices' =&gt; true)
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-08-13T00:27:11.000+0000</p> 
        <div class="body">
            <p>@Marek:
Before line 257 var_dump($translateMessages); and give us the result as attachment.</p>

<p>@Matthew:
Sidenote: Retrieving ALL messages of this language (as done on line 209 of Router can be a performance headache because one language could hold more than 5000 translations. And loading 5000 translations just to match one single translation instead of using translate() or isTranslated() is no good way.</p>

<p>I would request to rework this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marek (xorock) on 2009-08-13T05:05:43.000+0000</p> 
        <div class="body">
            <p>It's NULL because...
Let's say I have folder structure /application/translations/de|ro and some Controller Plugin which tries to discover language in routeStartup and if !Zend_Locale::isLocale fallback to en_US. All messages are written in english - $this-&gt;translate('message') same as @rule in Router_Route. Now if You change browser's locale to 'en'  You'll get this warning because translation /translations/en/something.mo does not exist. Default translation is used.</p>

<p>In answer to Your sidenote. Whole Zend_Translate/Locale is terribly slow. Benchmark before (fastcgi, APC enabled): 29 req/s, after (with cache set both for Locale and Translate) 16 req/s. Almost 50% decrease.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marek (xorock) on 2009-08-16T00:14:42.000+0000</p> 
        <div class="body">
            <p>I see another problem. Just updated PHP to 5.3 and now, when translation is not provided, routing doesn't work. I always get index/index. And that is why there shouldn't be warnings in production code ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:27.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

