<h2>ZF-7786: Zend_CodeGenerator_Php_Property_DefaultValue doesn't handle boolean and null correct</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-06T15:11:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-09-06T19:00:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Janko Richter (jankorichter)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_CodeGenerator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_CodeGenerator_Php_Property_DefaultValue:: generate() handles boolean and null values
not correct. I fixed it with :</p>

<pre class="highlight"><code>
       switch ($type) {
            case self::TYPE_STRING:
                $output .= "'" . $value . "'";
                break;
            case self::TYPE_BOOLEAN:
              $output .= $value ? 'true' : 'false';
              break;
            case self::TYPE_NULL:
                $output .= 'null';
                break;
            case self::TYPE_NUMBER:
            case self::TYPE_INTEGER:
.......
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-09-06T18:56:28.000+0000</p> 
        <div class="body">
            <p>set component and auto reassign .</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-09-06T19:00:43.000+0000</p> 
        <div class="body">
            <p>I find this issue may be solved in ZF-7783 after last my comment. 
I think it seems to be duplicate of the ZF-7783</p>

        </div>
    </div>
    </div>

