<h2>ZF-7257: Zend_Cache_Frontend_Page to enable graceful expiry.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-07-14T05:48:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This means that we could enable a feature that does a graceful cache serving, that when a cache is rebuilding, the subsequent connection will be then served with the stale copy.</p>

<p>This is to have to option to avoid a connection flood for highly active sites to be building multiple cache because one of of cached being expired, then there are parallel connection for the same url.</p>

<p>I hope the above explanation are clear, example to point to is the varnish's graceful cache.</p>

<p>I hope this is the right channel as well as. Sorry if it wasn't.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:38.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

