<h2>ZF-7183: Zend_Filter_StringTrim does not work correctly with input which begins with a unicode char</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-07-02T09:38:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-06T10:23:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.0 (31/Jul/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-170">ZF2-170</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>After last update from svn repository i have a bug using Zend_Filter_StringTrim.</p>

<p>I got an error <em>"Invalid type given, value should be float, string, or integer"</em> after having submitted a form with a Russian text. (Example: Зенд)
I don't know about other languages, but everything is fine with a text in English.</p>

<p>Code is simple:</p>

<pre class="highlight"><code> 
$name = new Zend_Form_Element_Text('name');
$name-&gt;setRequired(true)
             -&gt;addValidator($validName)
             -&gt;addFilter(new Zend_Filter_StringTrim());
</code></pre>

<p>If the last line is commented out, everything is ok.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T09:42:41.000+0000</p> 
        <div class="body">
            <p>What is the value of $validName ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T12:00:49.000+0000</p> 
        <div class="body">
            <p>Code:</p>

<p>$validName = new Zend_Validate();
$validName-&gt;addValidator(new Zend_Validate_StringLength(1, 64))
                      -&gt;addValidator(new Zend_Validate_Regex('/^[\p{L}]+$/u'));</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T12:08:36.000+0000</p> 
        <div class="body">
            <p>Same problem without validators.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T12:12:08.000+0000</p> 
        <div class="body">
            <p>I don't see that you are using Zend_Filter_StringLength.
Nor is this filter used by any validator you've used in the provided code.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T12:19:11.000+0000</p> 
        <div class="body">
            <p>I'm using <em>strong</em>Zend_Filter_StringTrim<em>strong</em>.
I'm not using Zend_Filter_StringLength at all.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T12:42:11.000+0000</p> 
        <div class="body">
            <p>Using this example code I see no problems:</p>

<pre class="highlight"><code>
$filter = new Zend_Filter_StringTrim();
var_dump($filter-&gt;filter('Зенд'));
</code></pre>

<p>This means that the StringTrim filter DOES work with cyrillic text.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T12:45:44.000+0000</p> 
        <div class="body">
            <p>No reason to get loud.</p>

<p>Now that you've changed the issue report I see that you've used Zend_Form.
Have you tried to reproduce this behaviour without Zend_Form ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T13:09:06.000+0000</p> 
        <div class="body">
            <p>I created empty file and put your code inside:</p>

<pre class="highlight"><code>
$filter = new Zend_Filter_StringTrim();
var_dump($filter-&gt;filter('Зенд'));
</code></pre>

<p>Result: null</p>

<pre class="highlight"><code>
$filter = new Zend_Filter_StringTrim();
var_dump($filter-&gt;filter('Zend'));
</code></pre>

<p>Result: string 'Zend' (length=4)</p>

<p>Also i tried to use German: Gerüst</p>

<p>Result: string 'Gerüst' (length=7)</p>

<p>Very strange things...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T13:09:46.000+0000</p> 
        <div class="body">
            <p>I created empty file and put your code inside:</p>

<pre class="highlight"><code>
$filter = new Zend_Filter_StringTrim();
var_dump($filter-&gt;filter('Зенд'));
</code></pre>

<p>Result: null</p>

<pre class="highlight"><code>
$filter = new Zend_Filter_StringTrim();
var_dump($filter-&gt;filter('Zend'));
</code></pre>

<p>Result: string 'Zend' (length=4)</p>

<p>Also i tried to use German: Gerüst</p>

<p>Result: string 'Gerüst' (length=7)</p>

<p>Very strange things...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T13:16:12.000+0000</p> 
        <div class="body">
            <p>Next experiment...</p>

<p>File: Zend/Filter/StringTrim.php</p>

<p>LINE 112: return preg_replace("/$pattern/usSD", '', $value);</p>

<p>Works as expected without "u" modificator</p>

<p>LINE 112: return preg_replace("/$pattern/sSD", '', $value); - works.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T13:19:26.000+0000</p> 
        <div class="body">
            <p>Added unittest with r16417</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-07-02T13:27:34.000+0000</p> 
        <div class="body">
            <p>I know... you should have tried with "Übung".
Reason seems that the author of this component missed to test input which begins with a unicode char.</p>

<p>As you may have noted I've already added the proper unittest to check this behaviour with the mentioned release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nelius (nelius.in) on 2009-07-02T13:47:01.000+0000</p> 
        <div class="body">
            <p>Yes, same problem with "Übung".  :)
Because of the error my registration form doesnt work.</p>

<p>I will edit this issue Summary: "Zend_Filter_StringTrim does not work correctly with input which begins with a unicode char"</p>

<p>Thank you for your help Thomas!</p>

        </div>
    </div>
    </div>

