<h2>ZF-7100: Zend_Paginator can raise a divide by 0 warning </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-06-23T08:42:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-07-07T10:05:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ryan Mauger (bittarman)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jurrien Stutterheim (norm2782)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Paginator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If itemCountPerPage is set to 0 or setItemCountPerPage is not called, a divide by 0 warning may be raised.</p>

<p>This could be avoided by either setting some default item count per page, or throwing an exception if the _calculatePageCount method is called without first setting a valid itemCountPerPage.</p>

<p>Throwing an exception should be prefered, as userland code could set the value to 0 if there is incorrect filtering.
Relying on a php warning should not be correct however.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Groeneveld (frenkel) on 2009-07-02T10:26:07.000+0000</p> 
        <div class="body">
            <p>This problem can be resolved by not using _itemCountPerPage in the Paginator, but calling getItemCountPerPage (which will return the default value if none is set).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2009-07-07T10:05:34.000+0000</p> 
        <div class="body">
            <p>This has been duplicated by ZF-7207 (<a href="http://tinyurl.com/lqyqym">http://tinyurl.com/lqyqym</a>)  and has now been resolved.</p>

        </div>
    </div>
    </div>

