<h2>ZF-7811: Wildcard data (captured by *) is not translated in routes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-09-09T08:14:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Stéphane (stephane)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12191/Route.php">Route.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Localization of urls work perfectly, except for wildcard parameters. For example, if we define the following route :</p>

<p>bq. @contents/@pages/:@action/*</p>

<p>We can handle urls like this in English:</p>

<p>bq. <a href="http://domain.com/contents/pages/list/">http://domain.com/contents/pages/list/</a></p>

<p>And the corresponding urls in French:</p>

<p>bq. <a href="http://domain.com/contenus/pages/lister/">http://domain.com/contenus/pages/lister/</a></p>

<p>But considering now parameters (key-value pairs) defined by the '*' in the route, we could have in English:</p>

<p>bq. <a href="http://domain.com/contenus/pages/lister/sortby/date/status/not-published">http://domain.com/contenus/pages/…</a></p>

<p>However, the following (the same parameters in French) will not work:</p>

<p>bq. <a href="http://domain.com/contenus/pages/lister/trierpar/date/statut/non-publie">http://domain.com/contenus/pages/…</a></p>

<p>So parameters defined by the '*' are never translated, whereas they should (and can) be. You will find attached to this issue a patch of the {{Zend_Controller_Router_Route}} class to make this work (it modifies the {{match()}} and {{assemble()}} methods).</p>

<p>Note this patch leveraged the patch proposed in the issue ZF-6654.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stéphane (stephane) on 2009-09-09T08:17:15.000+0000</p> 
        <div class="body">
            <p>The sections to modify are delimited by :</p>

<pre class="highlight"><code> 
// PATCH (Start)
...
// PATCH (End)
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:39.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

