<h2>ZF-727: Loading of helpers is not LIFO</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-08T15:54:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.7.0 (18/Jan/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I've had my own URL helper in 0.2. After upgrading to 0.6, which has a URL helper built-in, the built-in helper is always loaded first.</p>

<p>{panel:title=From the documentation}
In fact, you can "stack" paths using the addHelperPath() method. As you add paths to the stack, Zend_View will look at the most-recently-added path for the requested helper class. This allows you to add to (or even override) the initial distribution of helpers with your own custom helpers.
{panel}</p>

<pre class="highlight"><code>
$view = new Zend_View();
$view-&gt;addHelperPath('/path/to/helpers', 'Zend_View_Helper');
</code></pre>

<p>In {{Zend_View_Abstract::_addPath()}}, new paths are added to the beginning of the array but in {{Zend_View_Abstract::_loadClass()}} they are reversed before iteration. This way it is actually FIFO.</p>

<p>If I remove {{array_reverse()}} in {{foreach}}, everything is OK.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-01-15T06:49:36.000+0000</p> 
        <div class="body">
            <p>Resolved in revision 2766; thanks for the catch!</p>

        </div>
    </div>
    </div>

