<h2>ZF-7534: The Reveive method on Zend_Queue Adapters creates multiple consumers when running in a polling mode </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-08-07T21:34:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-18T00:28:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dheeraj Saxena (kkarank)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Anton C. Swartz IV (necrogami)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Queue</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12134/Activemq-ZF7534.php">Activemq-ZF7534.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am trying to setup a listener for messages send to an ActiveMq Broker from Zend_Queue. My client code in the listener class looks like this</p>

<pre class="highlight"><code>
while (1)
      {
                          
                  if ($messages=$this-&gt;queue-&gt;receive(1))
                  {
                        foreach ($messages as $message)
                        {
                              if (($msg=$message-&gt;body) != null)
                              {
                                    //do my processing and then delete the message from queue
                                    $this-&gt;queue-&gt;deleteMessage($message);
                              }
                        }
                  }
                        
      }
</code></pre>

<p>The problem is with the following code in the ZF Supplied ActiveMQ Adapter (happens around lines 208)</p>

<pre class="highlight"><code>
   // signal that we are reading
        if ($this-&gt;isConnected == 0)
        {
        $frame = $this-&gt;_client-&gt;createFrame();
        $frame-&gt;setCommand('SUBSCRIBE');
        $frame-&gt;setHeader('destination', $queue-&gt;getName());
        $frame-&gt;setHeader('ack','client');
        $this-&gt;_client-&gt;send($frame);
        $this-&gt;isConnected = 1;
        }
</code></pre>

<p>When running in a listening mode , this code creates multiple consumers for every call to receive even though there are no messages on the queue. A better way would have been to strip this code from receive into a seperate method (something like checkmessage or getMessageCount..) and call that before calling receive? Also, it would be nice to have a generic listener in the framework itself that just needs the name of a queue/topic and possibly a polling interval and which can invoke predefined code when it receives a message. Thats how most adapters in EAI systems work.</p>

<p>Again, for now I have written my own adapter that works around this. The documentation on this functionality is sparse so raising an Issue just in case I might have missed something.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Daniel Lo (danlo) on 2009-08-08T12:55:46.000+0000</p> 
        <div class="body">
            <p>If you have already solved this issue, please submit a patch :)</p>

<p>I will check into this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Lo (danlo) on 2009-08-08T13:07:02.000+0000</p> 
        <div class="body">
            <p>I checked around, but there is no method to obtain the number of messages in the queue.  If you know of such a method for ActiveMQ please let me know.</p>

<p>Sources:</p>

<ul><li><a href="http://stomp.codehaus.org/Protocol">http://stomp.codehaus.org/Protocol</a></li>
<li><a href="http://activemq.apache.org/stomp.html">http://activemq.apache.org/stomp.html</a></li>
</ul><p>Continuing to look into this...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dheeraj Saxena (kkarank) on 2009-08-08T20:03:37.000+0000</p> 
        <div class="body">
            <p>The proposed fix will stop the adapter from creating multiple consumers. Instead of hardcoding the value of isConnected, keeping it configurable will give a user the option to have a set number of consumers depending upon expected load and application specificity.</p>

<p>/Dheeraj</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dheeraj Saxena (kkarank) on 2009-08-08T20:13:48.000+0000</p> 
        <div class="body">
            <p>Daniel,</p>

<p>A simple way would be to check that there is a valid MESSAGE frame on a target queue before receive (in its current incarnation) is called. I believe this can be easily done in the _canRead() method?( i may be wrong but the brief look I had at its code seemed to suggest that as the ideal place for such logic)</p>

<p>Using this and my proposed fix would  a) make the adapter create a subscriber on demand  and b) let the user control the number of  required consumers based on his application needs (my current application suffices 1 consumer as i use the queue to process sparse email sending for comments placed on my message board. In another application though I have over 100 messages per sec flowing into the broker so I would like to have more consumers)</p>

<p>This would be a great load balancing act .</p>

<p>Dheeraj</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Lo (danlo) on 2009-08-16T09:10:17.000+0000</p> 
        <div class="body">
            <p>We are currently waiting for Matthew O'Phinney to get back from vacation to comment on this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Olmos (ndrtek_rob) on 2009-08-28T23:32:05.000+0000</p> 
        <div class="body">
            <p>The only method I have found to get the number of pending messages (along with other items) is:</p>

<h1>Activate the ActiveMQ.Agent topic (and JMX)</h1>

<h1>Send a "query -QQueue=" message</h1>

<h2><em>Required</em>: Set a reply-to header with a queue or topic</h2>

<h1>Parse the number from the response</h1>

<p>You might be able to return only the line or number of messages with more options to the command but I haven't tried.</p>

<p><a href="http://activemq.apache.org/activemq-command-line-tools-reference.html">http://activemq.apache.org/activemq-command-line-t…</a>
<a href="http://activemq.apache.org/command-agent.html">http://activemq.apache.org/command-agent.html</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Anton C. Swartz IV (necrogami) on 2010-12-18T00:28:14.000+0000</p> 
        <div class="body">
            <p>I fixed this issue in ZF-7948</p>

        </div>
    </div>
    </div>

