<h2>ZF-8458: Typo in Zend_Translate-Plurals</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-12-03T14:32:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-03T14:43:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christoph Löffler (loeffler.de)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is a typo in 57.6 Plural notations for Translation:</p>

<p>"But as you may imaging each language has it's own definition of plurals. "</p>

<p>should be: "But as you may imagine each language has it's own definition of plurals. "</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-03T14:40:57.000+0000</p> 
        <div class="body">
            <p>There are more than 12000 known typos and failures.
Please dont fill an issue for each single typo, just fix it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-03T14:43:11.000+0000</p> 
        <div class="body">
            <p>Fixed with r19383</p>

        </div>
    </div>
    </div>

