<h2>ZF-8321: testSetAndGetMagicFile(Zend_Validate_File_MimeTypeTest) unit tests failure</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2009-11-17T06:05:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T11:56:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate_File</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{panel}
1) testSetAndGetMagicFile(Zend_Validate_File_MimeTypeTest)
Failed asserting that  is true.
/home/cawa/ZendFramework/svn/framework/trunk/tests/Zend/Validate/File/MimeTypeTest.php:171
{panel}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-11-17T06:23:53.000+0000</p> 
        <div class="body">
            <p>testSetAndGetMagicFile expects empty string returned by getMagicFile() method.</p>

<p>But, if any of the following files exists, it used as an initial magic file value.
{panel}
/usr/share/misc/magic
/usr/share/misc/magic.mime
/usr/share/misc/magic.mgc
/usr/share/mime/magic
/usr/share/mime/magic.mime
/usr/share/mime/magic.mgc
/usr/share/file/magic
/usr/share/file/magic.mime
/usr/share/file/magic.mgc
{panel}</p>

<p>PS getMagicFile() initializes Zend_Validate_File_MimeType::$_magicfile property from the specified list only if 'MAGIC' environment variable not set. But it does nothing if 'MAGIC' env variable is present. Is it correct?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-17T06:35:10.000+0000</p> 
        <div class="body">
            <p>Alex -- I believe this is a problem with Zend Server. I've had similar issues testing. If I specify the path to the magic file, it works fine, but relying on the MAGIC env variable does not.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-18T03:40:16.000+0000</p> 
        <div class="body">
            <p>I am not using Zend_Server. So there is no way for me to reproduce this behaviour.</p>

<p>Would it work if the test checks is MAGIC is set? And if not set, simply ignore all further tests?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-19T06:25:05.000+0000</p> 
        <div class="body">
            <p>Should be fixed with r19033.
Can you evaluate and give feedback?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-20T11:56:43.000+0000</p> 
        <div class="body">
            <p>Closing as fixed.
Please reopen when it's still buggy.</p>

        </div>
    </div>
    </div>

