<h2>ZF-8686: Zend_View_Helper_Navigation_Menu doesn't reconginze the active page, when using chained routes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-01T11:54:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-21T08:19:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>I noticed the Zend_View_Helper_Navigation_Menu doesn't work properly with chained routes (having one hostname route into chain), because it doesn't seems to mark properly the active page with active class. I guess is a matter of wrong Zend_Navigation_Mvc_Page isActive or something...</p>

<p>Sample routes config used for this:</p>

<pre><code>    $hostnameRoute = new Zend_Controller_Router_Hostname(
        ':subsite.domain.com',
        array( 'subsite'=&gt;'www' ),
        array( 'subsite' =&gt; implode('|', $subsites) )
    );

    $typeplain = new Zend_Controller_Router_Type(
        ':type/:rank/:id/*',
        array('module'=&gt;'resources', 'controller'=&gt;'types', 'action'=&gt;'view', 'rank'=&gt;'latest', 'id'=&gt;0),
        array('type' =&gt; implode('|', $types), 'rank'=&gt;'latest|sponsored|recommended', 'id'=&gt;'\d+')
    );

    $router-&gt;addRoute('type', $hostnameRoute-&gt;chain($typeplain));
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Cristian Bichis (avantis) on 2010-01-01T12:38:15.000+0000</p> 
        <div class="body">
            <p>Sorry, was my own code error... That's not an issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-09-21T08:19:21.000+0000</p> 
        <div class="body">
            <p>Reporter claims no longer an issue.</p>

        </div>
    </div>
    </div>

