<h2>ZF-8607: [QS] Error creating action 'sign' for 'guestbook'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-22T02:46:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-07T07:12:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Conrad Taylor (conradwt)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8588">ZF-8588</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm getting the following error message for the Quick Start Tutorial:</p>

<p>$ zf.sh create action sign guestbook</p>

<p>PHP Fatal error:  Cannot redeclare class Zend_Loader in /Users/conradwt/php.dir/projects/zend-framework/library/Zend/Loader.php on line 31</p>

<p>Fatal error: Cannot redeclare class Zend_Loader in /Users/conradwt/php.dir/projects/zend-framework/library/Zend/Loader.php on line 31</p>

<p>Next, I'm using the lastest version from trunk.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by fisharebest (fisharebest) on 2010-02-07T08:03:50.000+0000</p> 
        <div class="body">
            <p>This is an issue of case-sensitivity.  Although the zftool capitalises the controller when you create it, it doesn't when you try to use it.  Try this:</p>

<p>zf.bat create action sign Guestbook</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-02-07T10:06:57.000+0000</p> 
        <div class="body">
            <p>Also, please test against trunk; Ralph has implemented some changes that should (a) make it possible to lowercase the initial letter (it will then ucfirst() it), as well as (b) warn you about what it's doing when it detects this is the case.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-02-07T10:07:46.000+0000</p> 
        <div class="body">
            <p>Assigning to Ralph, and marking as a Zend_Tool issue. The documentation has been revised already, and will release with 1.10.1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralf Eggert (ralf) on 2010-05-29T08:27:27.000+0000</p> 
        <div class="body">
            <p>duplicates</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-09-07T07:12:18.000+0000</p> 
        <div class="body">
            <p>This was fixed as part of the 1.10.x release series.</p>

        </div>
    </div>
    </div>

