<h2>ZF-8841: Zend_Service_Twitter need more timeline options home_timeline as well as friends_timeline</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-16T12:12:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have been playing with the Twitter part of zend framework,and I missed the ReTweets.</p>

<p>So I hacked the zend/services/twitter.php file so the public function statusFriendsTimeline
references home_timeline instead friends_timeline and it works great for my needs.
They are identical functions.</p>

<p><a href="http://apiwiki.twitter.com/Twitter-REST-API-Method:-statuses-home_timeline">http://apiwiki.twitter.com/Twitter-REST-API-Method…</a></p>

<p><a href="http://framework.zend.com/manual/en/zend.service.twitter.html#zend.service.twitter.status">http://framework.zend.com/manual/en/…</a></p>

<p>I would like to see both methods supported.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

