<h2>ZF-845: Multi cookie</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2007-02-02T16:33:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Simone Carletti (weppos)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Cookie</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It would be great a multi cookie support (see <a href="http://www.zend.com/codex.php?id=679&amp;single=1">http://www.zend.com/codex.php?id=679&amp;single=1</a>).</p>

<p>According to multi cookie idea Zend_Http_Cookie::setValue() should be able to accept an array as argument and choose to serialize or not stored data depending on cookie type (multi or single value).
Zend_Http_Cookie::getValue() should return a single value or an array.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-02-05T11:19:23.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>This is a bit problematic as far as I am concerned because I am not aware of any "standard" way of serializing arrays as a cookie value.  Remember that the Http_Client is used to communicate with many different web servers running many different apps and languages - not just PHP.</p>

<p>You could always overload the Zend_Http_Cookie class to support this for your own needs. I suggest you open a discussion about this in fw-webservices@lists.zend.com and see what the community suggest.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simone Carletti (weppos) on 2007-02-05T13:09:21.000+0000</p> 
        <div class="body">
            <p>{quote}
This is a bit problematic as far as I am concerned because I am not aware of any "standard" way of serializing arrays as a cookie value.
{quote}</p>

<p>You're right, but consider that serialize and unserialize process will be done by Zend_Http_Cookie class and outside data will be set and get using arrays.
Data stream will be</p>

<p>array() --&gt; Zend_Http_Cookie --&gt; serialize() --&gt; cookie
and
cookie --&gt; unserialize() --&gt; Zend_Http_Cookie --&gt; array()</p>

<p>Actually data stream is</p>

<p>string --&gt; Zend_Http_Cookie --&gt; cookie
and
cookie --&gt; Zend_Http_Cookie --&gt; string</p>

<p>{quote}
You could always overload the Zend_Http_Cookie class to support this for your own needs. I suggest you open a discussion about this in fw-webservices@lists.zend.com and see what the community suggest.
{quote}</p>

<p>Thanks for your suggestion!
I will try to code something and I will share my ideas on web services mailing list. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2007-03-02T07:09:16.000+0000</p> 
        <div class="body">
            <p>Please reopen this as an improvement suggestion if you think this is still important after discussing with fw-webservices@lists.zend.com</p>

<p>Shahar.</p>

        </div>
    </div>
    </div>

