<h2>ZF-8769: Zend_Search_Lucene and how to implement non-default positionIncrement of token ?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-10T13:09:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-23T19:46:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Oleg (wtfowned)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>// Rewrote everything i wrote 2 days ago :/</p>

<p>For example, i made another token filter, that stems russian words.
But as we know, there can be more than one baseform of word. So, here we can get help from token positionIncrement.</p>

<p>From docs about positionIcrenemt:</p>

<pre class="highlight"><code>
/**
* Some common uses for this are:
* Set it to zero to put multiple terms in the same position.  This is
* useful if, e.g., a word has multiple stems.  Searches for phrases
* including either stem will match.  In this case, all but the first stem's
* increment should be set to zero: the increment of the first instance
* should be one.
*/
</code></pre>

<p>Okey, so whats the best way to implement this ? As i understand, i should to rewrite everything, including Zend_Search_Lucene_Analysis_Analyzer abstract class.</p>

<p>I want some improvements of api, that, for example, i could just add synonyms or all base forms ( as in my case ) for token.</p>

<p>I hope you understood, thanks ;)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-02-23T19:46:26.000+0000</p> 
        <div class="body">
            <p>Reassign it to the leader.</p>

        </div>
    </div>
    </div>

