<h2>ZF-8265: Zend_Form_Element_Radio generates non valid html</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-09T17:17:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T11:19:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.6 (24/Nov/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12398/FormLabel.diff">FormLabel.diff</a></li>
            <li><a href="/issues/secure/attachment/12399/FormLabelTest.diff">FormLabelTest.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
        $this-&gt;addElement('radio', 'test', array(
            'label'    =&gt; 'test',
            'multiOptions' =&gt; array('Mr' =&gt; 'Mr','Ms' =&gt; 'Ms','Miss'
            =&gt; 'Miss','Mrs' =&gt; 'Mrs'),
        ));
</code></pre>

<pre class="highlight"><code>
//generated output
test

 Mr
<br />
Ms<br />
Miss<br />
Mrs
</code></pre>

<p>: 'disablefor' is not valid (X)HTML attribute in any case.</p>

<p>Proposed fix:</p>

<p>&lt;</p>

<p>pre class="literal"&gt;</p>

<h1>Index: FormLabel.php</h1>

<p>--- FormLabel.php   (revision 19018)
+++ FormLabel.php   (working copy)
@@ -54,9 +54,13 @@
         }</p>

<pre><code>     $value = ($escape) ? $this-&gt;view-&gt;escape($value) : $value;
</code></pre>

<p>-        $for   = (empty($attribs['disableFor']) || !$attribs['disableFor'])
-               ? ' for="' . $this-&gt;view-&gt;escape($id) . '"'
-               : '';
+        if (empty($attribs['disableFor']) || !$attribs['disableFor']) {
+            $for = ' for="' . $this-&gt;view-&gt;escape($id) . '"';
+        }
+        else {
+            $for = '';
+            unset($attribs['disableFor']); //Remove $attribs['disableFor'] from array
+        }</p>

<pre><code>     // enabled; display label
     $xhtml = '&lt;label'
</code></pre>

<p></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-11-09T17:24:11.000+0000</p> 
        <div class="body">
            <p>What is the outcome you had expected, and how do you propose to solve this (without losing functionality, while generating valid html for other versions)?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ernest Szulikowski (est) on 2009-11-09T17:41:07.000+0000</p> 
        <div class="body">
            <p>The expected outcome is just 
</p>
test, 
instead of 

test

<p>as attribute 'disabledfor' is not allowed in any of HTML (and XHTML) flavors.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ernest Szulikowski (est) on 2009-11-09T17:43:58.000+0000</p> 
        <div class="body">
            <p>I think the expected behaviour was meant to be like commented by Mr O'Phinney:</p>

<p><a href="http://framework.zend.com/issues/browse/ZF-6426?focusedCommentId=35231&amp;page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#action_35231">http://framework.zend.com/issues/browse/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ernest Szulikowski (est) on 2009-11-10T06:29:51.000+0000</p> 
        <div class="body">
            <p>I found problem in Zend_View_Helper_FormLabel.</p>

<p>If 'disableFor' attribute is set (and for radio it is) $for is cleaned to empty string, but disableFor attribute still exists $attribs array, so $this-&gt;_htmlAttribs($attribs) produces all attribs for label including disablefor="1". The simple solution could be just to remove array element:</p>

<p>//        $for   = (empty($attribs['disableFor']) || !$attribs['disableFor'])
//               ? ' for="' . $this-&gt;view-&gt;escape($id) . '"'
//               : '';</p>

<pre><code>    if (empty($attribs['disableFor']) || !$attribs['disableFor']) {
        $for = ' for="' . $this-&gt;view-&gt;escape($id) . '"';
    }
    else {
        $for = '';
        //Remove $attribs['disableFor'] from array
        unset($attribs['disableFor']);
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ernest Szulikowski (est) on 2009-11-10T06:32:22.000+0000</p> 
        <div class="body">
            <p>if (empty($attribs['disableFor']) || !$attribs['disableFor']) {
$for = ' for="' . $this-&gt;view-&gt;escape($id) . '"';
}
else {
$for = '';
unset($attribs['disableFor']);
}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ernest Szulikowski (est) on 2009-11-10T06:42:16.000+0000</p> 
        <div class="body">
            <p>I found problem in Zend_View_Helper_FormLabel.</p>

<p>If 'disableFor' attribute is set (and for radio it is) $for is cleaned to empty string, but disableFor attribute still exists $attribs array, so $this-&gt;_htmlAttribs($attribs) produces all attribs for label including disablefor="1". The simple solution could be just to remove array element:</p>

<p>//        $for   = (empty($attribs['disableFor']) || !$attribs['disableFor'])
//               ? ' for="' . $this-&gt;view-&gt;escape($id) . '"'
//               : '';</p>

<pre><code>    if (empty($attribs['disableFor']) || !$attribs['disableFor']) {
        $for = ' for="' . $this-&gt;view-&gt;escape($id) . '"';
    }
    else {
        $for = '';
        //Remove $attribs['disableFor'] from array
        unset($attribs['disableFor']);
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ernest Szulikowski (est) on 2009-11-11T02:03:27.000+0000</p> 
        <div class="body">
            <p>Sorry for double post.</p>

<p>Anyone can confirm this ?</p>

<p>What shall I do now ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mon Zafra (monzee) on 2009-11-19T21:23:53.000+0000</p> 
        <div class="body">
            <p>Added code to unset 'disableFor' attribute if set, attached the patch and test. Please review.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mon Zafra (monzee) on 2009-11-19T22:20:11.000+0000</p> 
        <div class="body">
            <p>Changed diffs to svn-generated diffs instead of Netbeans.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Craig Slusher (sleek) on 2009-11-19T22:41:28.000+0000</p> 
        <div class="body">
            <p>Accidentally assigned to myself.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-20T11:19:45.000+0000</p> 
        <div class="body">
            <p>Patches applied to trunk and 1.9 release branch -- thanks!</p>

        </div>
    </div>
    </div>

