<h2>ZF-8883: Mature change &quot;added usage of registry local&quot; (r17798)  not merged into 1.9.7</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2010-01-20T06:52:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-20T07:45:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Thomas,
this change was made about half an year ago, why it is not present in 1.9.7?
Maybe it was forgotten during merging trunk to 1.9.7...</p>

<p>We really like to see your great code improvements in relased code, not only in trunk :-)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-20T07:17:56.000+0000</p> 
        <div class="body">
            <p>@Piotr: most likely the change is considered a BC break or an addition to the API -- and, as such, can only occur in minor releases. As 1.9 has been out since early August, my guess (Thomas will verify) is that the change will be reflected in the 1.10 release (which will be out soon).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-20T07:45:17.000+0000</p> 
        <div class="body">
            <p>API additions are not allowed to be integrated within mini-releases.</p>

<p>Additionally this change introduces a change in behaviour. Even if not being a BC break, it could lead to misinterpretation when such a change is done in a bugfix-release. How it behaves depends on application settings.</p>

<p>This change was done 24.Aug. (timeframe from 1.9.3)
You may also have noted that the issue which this change points to (ZF-7489) is marked as fixed for "the next minor release", which is ZF 1.10 ;-)</p>

<p>You'll not have to wait longer than a few days for 1.10.
Therefor closing this issue as fixed.</p>

        </div>
    </div>
    </div>

