<h2>ZF-8135: fetchOne/fetchRow LIMIT 1 inconsistency</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-23T10:27:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-04T09:08:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Fankhauser (chris.fankhauser)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The fetchRow and fetchOne functions in Pdo behave differently than the ones in the Table object.  The Table ones correctly(?) specify LIMIT 1, whereas the ones in Pdo are essentially fetching an entire result set and then grabbing the [0] element of it.</p>

<p>This results in a significant performance hit on large tables, but can be worked-around by manually putting in "LIMIT 1" on individual queries or, of course, self-patching those two functions in Pdo.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-06-18T15:07:13.000+0000</p> 
        <div class="body">
            <p>Can you supply proof-of-concept patch and/or patch for the buggy behavior?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-10-04T09:08:47.000+0000</p> 
        <div class="body">
            <p>Reporter has not followed up.</p>

        </div>
    </div>
    </div>

