<h2>ZF-8751:  add ZendX_Application_Resource as a default plugin path for the bootstrap</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2010-01-08T12:00:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-01T08:09:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.3 (01/Feb/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13442/ZF-8751.patch">ZF-8751.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-13T21:33:41.000+0000</p> 
        <div class="body">
            <p>Attached patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-19T03:28:40.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r23889 still was not yet merged to branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-01T08:09:36.000+0000</p> 
        <div class="body">
            <p>Merged r23602</p>

        </div>
    </div>
    </div>

