<h2>ZF-8348: Zend_Filter_Compress tests dont clean-up correctly -&gt; Massive failures</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-19T13:22:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T11:40:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This happens on linux, php 5.3</p>

<pre class="highlight"><code>
25) testBasicUsage(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

26) testTarGetSetOptions(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

27) testTarGetSetArchive(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

28) testTarGetSetTarget(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

29) testTarCompressToFile(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

30) testTarCompressDirectory(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

31) testTarToString(Zend_Filter_Compress_TarTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/TarTest.php:84

32) testBasicUsage(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

33) testZipGetSetOptions(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

34) testZipGetSetArchive(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

35) testZipGetSetTarget(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

36) testZipCompressFile(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

37) testCompressNonExistingTargetFile(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

38) testZipCompressDirectory(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80

39) testZipToString(Zend_Filter_Compress_ZipTest)
rmdir(/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/../_files/_compress/Compress/First/Second): Directory not empty
/home/benny/code/www/wsnetbeans/zf/trunk/tests/Zend/Filter/Compress/ZipTest.php:80
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-20T05:07:33.000+0000</p> 
        <div class="body">
            <p>I just wondered why you attached the issue to yourself.
Btw, as it's only a unittest error, and it has no effect on the class itself, it's not critical in my eyes.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-20T10:19:04.000+0000</p> 
        <div class="body">
            <p>Please give the file(s) which are not cleaned in that directories.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-11-20T10:45:15.000+0000</p> 
        <div class="body">
            <p>It has an .svn subdirectory that can't be cleared.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-20T11:40:22.000+0000</p> 
        <div class="body">
            <p>Fixed with r19131</p>

        </div>
    </div>
    </div>

