<h2>ZF-8564: Zend_Service_Amazon_S3::getMimeType()  should use strtolower on extension to detect path like moo.JPG</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-12-17T03:30:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-20T19:46:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Service_Amazon_S3::getMimeType()    is best effort function anyhow. It's not something reliable so it can at least try to be more forgiving to input.</p>

<p>I belive it should do 
$ext = strtolower($ext)</p>

<p>Doing that it will successfully consider moo.JPG of type image/jpeg and not binary/octet-stream as is now.
Cheers</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Julian Davchev (jmut) on 2009-12-17T03:30:59.000+0000</p> 
        <div class="body">
            <p>Updating component to Zend_Service_Amazon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-20T19:46:31.000+0000</p> 
        <div class="body">
            <p>Solved in SVN trunk r19824</p>

        </div>
    </div>
    </div>

