<h2>ZF-8113: htmlspecialchars() expects parameter 1 to be string, array given</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-21T05:05:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-02-12T11:25:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Krzysztof Szatanik (diabl0)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8112">ZF-8112</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Source File:    Zend\View\Abstract.php : 850
Function Name:  htmlspecialchars
Error String:   htmlspecialchars() expects parameter 1 to be string, array given<br />
Error Type: E_WARNING</p>

<p>Function Name: htmlspecialchars
Function Arguments:
  1. array ( 
    'isEmpty' =&gt; 'Value is required and can\'t be empty',
  )
  2. 2
  3. 'utf-8'</p>

<p>BackTrace:</p>

<p>htmlspecialchars()
Zend_View::escape() at C:\HTDOCS\recepcja\library\Zend\View\Abstract.php : 850 
Zend_View::formErrors() at C:\HTDOCS\recepcja\library\Zend\View\Helper\FormErrors.php : 80 
Zend_View_Helper_FormErrors::formErrors()
Zend_View::__call() at C:\HTDOCS\recepcja\library\Zend\View\Abstract.php : 342 
Zend_View::render() at C:\HTDOCS\recepcja\library\Zend\Form\Decorator\Errors.php : 60 
Zend_Form_Decorator_Errors::render() at C:\HTDOCS\recepcja\library\Zend\Form.php : 2626 
cytologia_forms_LaborantForm::__toString() at C:\HTDOCS\recepcja\library\Zend\Form.php : 2641</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Emilio (nicoliky) on 2013-02-12T11:25:36.000+0000</p> 
        <div class="body">
            <p>This is a little hack that works for me</p>

<p>class MySubForm Date extends Zend_Form_Subform {
...
    public function getMessages($name = null, $suppressArrayNotation = false) {
        $messages = parent::getMessages($name, $suppressArrayNotation);</p>

<pre><code>    return !isset($messages[$this-&gt;getName()]) ? $messages : null;     
}
</code></pre>

<p>...
}</p>

        </div>
    </div>
    </div>

