<h2>ZF-8872: return $this, Zend_Validate_PostCode::setFormat()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-19T07:10:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-20T23:27:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12649/PostCode.php.patch">PostCode.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>add return $this in method Zend_Validate_PostCode::setFormat() and too add comment
@return Zend_Validate_PostCode Provides a fluent interface</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Martin de Keijzer (martin1982) on 2010-01-20T10:52:10.000+0000</p> 
        <div class="body">
            <p>Added the requested patch after seeing that most Validator classes return the instance on the set method.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-20T23:27:45.000+0000</p> 
        <div class="body">
            <p>Fixed with r20460</p>

        </div>
    </div>
    </div>

