<h2>ZF-8767: Zend_Validate_NotEmpty reports self::INVALID for every type of validation error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-10T12:32:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-11T06:14:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Tomasz Sterna (smoku)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12594/Zend_Validate_NotEmpty.patch">Zend_Validate_NotEmpty.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>self::INVALID is set to "Invalid type given, value should be float, string, array, boolean or integer", but it is reported for "" string, 0 integer, 0.0 float, array().</p>

<p>"" is an empty string, but it is a string. 0 is an integer etc. so the message is plainly wrong.
It should be self::IS_EMPTY =&gt; "Value is required and can't be empty".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Tomasz Sterna (smoku) on 2010-01-10T12:33:53.000+0000</p> 
        <div class="body">
            <p>Here's a patch that fixes this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-10T14:48:08.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tomasz Sterna (smoku) on 2010-01-10T15:40:20.000+0000</p> 
        <div class="body">
            <p>User named 'thomas' already merged my patch in r20180 not mentioning this bug in the commit.</p>

<p>Was that you?
 If so, why don't you just admit that you merged my patch to SVN, instead of pretending, that the bug was "already fixed"?</p>

<p>$ svn log -c20180 library/Zend/</p>

<hr /><p>r20180 | thomas | 2010-01-10 21:43:25 +0100 (nie) | 3 linie</p>

<p>[GENERIC] Zend_Validate:</p>

<ul><li>fixed wrong messages</li>
</ul><hr /><p>$ svn diff -c20180 library/Zend/ | head -n 20</p>

<p>Index: library/Zend/Validate/NotEmpty.php</p>

<p>===================================================================</p>

<p>--- library/Zend/Validate/NotEmpty.php  (wersja 20179)</p>

<p>+++ library/Zend/Validate/NotEmpty.php  (wersja 20180)</p>

<p>@@ -164,7 +164,7 @@</p>

<pre><code>     if ($type &gt;= self::SPACE) {

         $type -= self::SPACE;

         if (is_string($value) &amp;&amp; (preg_match('/^\s+$/s', $value))) {
</code></pre>

<ul><li><pre><code>         $this-&gt;_error(self::INVALID);
</code></pre></li>
<li><pre><code>         $this-&gt;_error(self::IS_EMPTY);

         return false;

     }

 }
</code></pre></li>
</ul><p>@@ -173,7 +173,7 @@</p>

<pre><code>     if ($type &gt;= self::NULL) {

         $type -= self::NULL;

         if (is_null($value)) {
</code></pre>

<ul><li><pre><code>         $this-&gt;_error(self::INVALID);
</code></pre></li>
<li><pre><code>         $this-&gt;_error(self::IS_EMPTY);

         return false;
</code></pre></li>
</ul><p>[...]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-10T23:17:12.000+0000</p> 
        <div class="body">
            <p>I'm in several online forums.</p>

<p>Sometimes I fix things when they are mentioned within a forum without raising an issue myself. And sometimes it collidates with another user reporting the same issue.</p>

<p>As there is only one solution for this problem, by using the correct constant, I would not be too strict in the wording "my patch". Other people come to the same conclusion without looking into your patch.</p>

<p>You may also have noted that email delivery for issues is delayed. The time this issue was sent to me, the fix was already committed.</p>

<p>I'm sorry when such a situation is problematic for you. When you want I could wait some weeks in future before fixing things which are mentioned to me in a public discussion. :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Tomasz Sterna (smoku) on 2010-01-10T23:52:30.000+0000</p> 
        <div class="body">
            <p>Do you really expect me to believe that accidentally both two of my issues reported within an hour was "already fixed" with no other commits within a week, just these two just after the bug reports? And you are so busy, that you do not remember what exactly happened few hours ago and need to be speculative with "sometimes".</p>

<p>I do not really care about giving credit for a few-liner patch.
What struck me is the bizarre attitude of not admitting "yes, there was a bug" and pretending that the reports were invalid in a first place.</p>

<p>You just lost more than one user - I will discourage every person asking my advice and reading my blog from using ZF, because your development methods are doubtful and not transparent. EOT</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-11T06:14:04.000+0000</p> 
        <div class="body">
            <p>There were 40 commits within the last week by me, not only 2.
And yes I am busy in my sparetime on sunday at home.</p>

<p>No one said that this report is invalid. I just said "probably fixed in trunk". The issue itself is marked as "fixed" and not as "not an issue" or "incomplete". In my eyes "fixed" is the proper status.</p>

<p>And there is also a changeset connected to this issue which tests this behaviour.</p>

        </div>
    </div>
    </div>

