<h2>ZF-8438: Route params patch for Zend_Navigation_Page_Mvc</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-12-02T00:19:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-06T09:24:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.8 (07/Jul/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Kai Uwe (kaiuwe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8830">ZF-8830</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I make my root navigation, it makes my links filled with all params as module, controller action.</p>

<p>Example:</p>

<p>route: profile/* &gt; should render link <a href="/profile">Profile</a></p>

<p>but instead it renders:
<a href="/profile/module/user/controller/index/action/read">Profile</a></p>

<p>I made following additions and changes to.
Zend/Navigation/Page/Mvc.php</p>

<p>I added variable:</p>

<pre class="highlight"><code>
public static $router = null;
</code></pre>

<p>And the get method for router:</p>

<pre class="highlight"><code>
public static function getRouter()
{
  if (null === self::$router) {
    self::$router = Zend_Controller_Front::getInstance()-&gt;getRouter();
  }

  return self::$router;
}
</code></pre>

<p>Then I added some route checking to end of method getHref():</p>

<pre class="highlight"><code>
$router = self::getRouter();
        
if ($router-&gt;hasRoute($this-&gt;getRoute()))
{
  $route = $router-&gt;getRoute($this-&gt;getRoute());
    
  // gets route defaults and compares it to given params, then
  // returns only the ones are not found from route defaults        
  $params = array_diff($params, $route-&gt;getDefaults());
}
        
$url = self::$_urlHelper-&gt;url($params,$this-&gt;getRoute(),$this-&gt;getResetParams());

return $this-&gt;_hrefCache = $url;
</code></pre>

<p>br, Marko</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-15T00:16:19.000+0000</p> 
        <div class="body">
            <p>Added code tags</p>

        </div>
    </div>
    </div>

