<h2>ZF-8195: Call to undefined function getCommentCount() </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-31T16:12:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-25T16:42:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.6 (24/Nov/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bradley Holt (bradley.holt)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Reader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12352/Atom.patch">Atom.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When importing the following feed:</p>

<p><a href="http://vermontdailynews.com/feed/atom/">http://vermontdailynews.com/feed/atom/</a></p>

<p>and then iterating through the Entries and calling getCommentCount() on each, I get the following error:</p>

<p>Fatal error: Call to undefined function getCommentCount() in path\to\library\Zend\Feed\Reader\Entry\Atom.php on line 298</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thierry Jossermoz (thierry@jossermoz.net) on 2009-11-05T18:39:55.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>There was a typo in Zend_Feed_Reader_Entry_Atom on line 298:</p>

<p>{{$commentcount = $this-&gt;getExtension('Thread')&gt;getCommentCount();}}</p>

<p>Attached patch fixes the issue:</p>

<p>{{$commentcount = $this-&gt;getExtension('Thread')-&gt;getCommentCount();}}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-11-23T08:08:27.000+0000</p> 
        <div class="body">
            <p>Fixed in r19192.</p>

<p>Extremely silly oversight on my part - I've added a task to add test coverage for the method in Atomland which is apparently missing. May have missed it in a commit previously.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-11-23T08:12:27.000+0000</p> 
        <div class="body">
            <p>Reopen to set fix version to next mini release</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bradley Holt (bradley.holt) on 2009-11-25T16:42:29.000+0000</p> 
        <div class="body">
            <p>Seems to be working fine now, thanks!</p>

        </div>
    </div>
    </div>

