<h2>ZF-8558: Backward incompatible change in rev 19661</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-16T11:10:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-13T06:26:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Emil Ivanov (vladev)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8763">ZF-8763</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Let me try to explain it with some code:</p>

<p>Application dispatching:</p>

<pre class="highlight"><code>
$front = Zend_Controller_Front::getInstance();
try {
   $front-&gt;dispatch();
} catch (My_Controller_Outcome_Result $e) {
   $front-&gt;getResponse()-&gt;sendResponse();
   // Ignore
}
</code></pre>

<p>{{My_Controller_Outcome_Result}} exceptions (thrown somewhere in actions) usually indicate a redirect
(or other event that should stop the execution)</p>

<p>Prior to 19661 I was actually getting a {{My_Controller_Outcome_Result}}
exception, but after that the instance is {{Zend_Controller_Exception}},
so the catch fails.</p>

<p>I managed to locate the change in ZF rev 19661 (trunk).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Nicolas Grevet (nyko18) on 2009-12-18T07:54:28.000+0000</p> 
        <div class="body">
            <p>I <em>really</em> hope this gets fixed soon.
I don't know how we're supposed to try/catch our own code if the Zend Framework now only throws Zend_Controller_Exception for everything that's thrown out of the code.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-12-21T06:52:36.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2010-01-05T03:05:21.000+0000</p> 
        <div class="body">
            <p>The same pattern is used in Zend_Controller_Dispatcher_Standard, line 301. Can that be fixed as well? (r19833 fixed only Zend_Controller_Front)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-12T13:09:35.000+0000</p> 
        <div class="body">
            <p>Opening due to user reports</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-12T13:15:03.000+0000</p> 
        <div class="body">
            <p>Fixed in r20244 in trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2010-01-13T04:21:51.000+0000</p> 
        <div class="body">
            <p>The same thing is happening in various places in Zend_Controller_Plugin_Broker as well. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-13T05:21:31.000+0000</p> 
        <div class="body">
            <p>Verified; will remove those wrapped exceptions shortly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-13T05:30:30.000+0000</p> 
        <div class="body">
            <p>Plugin broker no longer wraps re-thrown exceptions in trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Emil Ivanov (vladev) on 2010-01-13T06:26:52.000+0000</p> 
        <div class="body">
            <p>Everything seems fine now. Thank you! :)</p>

        </div>
    </div>
    </div>

