<h2>ZF-898: Zend/Db/Adapter/Pdo/Pgsql.php - quoteIdentifier() is wrong!</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2007-02-09T12:38:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mark Gibson (jollytoad)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>quoteIdentifer() is implemented incorrectly.</p>

<p>Here's the fix:</p>

<pre class="highlight"><code>
Index: <a>C:/patch/lib/Zend/Db/Adapter/Pdo/Pgsql.php</a>
===================================================================
--- <a>C:/patch/lib/Zend/Db/Adapter/Pdo/Pgsql.php</a>
+++ <a>C:/patch/lib/Zend/Db/Adapter/Pdo/Pgsql.php</a>
@@ -53,7 +53,7 @@
      */
     public function quoteIdentifier($ident)
     {
-        return '"' . $this-&gt;quote($ident) . '"';
+        return '"' . str_replace('"','""',$ident) . '"';
     }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mark Gibson (jollytoad) on 2007-02-09T12:41:50.000+0000</p> 
        <div class="body">
            <p>BTW, here's the relevant section in the PostgreSQL manual if it helps confirm the fix:</p>

<p><a href="http://www.postgresql.org/docs/8.2/interactive/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS">http://postgresql.org/docs/8.2/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-09T20:03:34.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3093.</p>

<p>Actually a lot of identifier quoting was wrong, not only for PostgreSQL.</p>

        </div>
    </div>
    </div>

