<h2>ZF-8567: methods for setting messageId and clearing several headers</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-12-17T07:04:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-30T23:45:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.1 (10/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8577">ZF-8577</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I should implement tests for setting messageId and tests for clearing headers.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-01-30T23:45:00.000+0000</p> 
        <div class="body">
            <p>Solved at SVN r20781</p>

        </div>
    </div>
    </div>

