<h2>ZF-8354: Dispatcher : include_once statement can generate a Warning if the file does not exists</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-20T06:09:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-25T06:40:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marco Kaiser (bate)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following (around line 337) from Zend_Controller_Dispatcher_Standard should be refactored:</p>

<pre class="highlight"><code>
$dispatchDir = $this-&gt;getDispatchDirectory();
        $loadFile    = $dispatchDir . DIRECTORY_SEPARATOR . $this-&gt;classToFilename($className);

        if (!include_once $loadFile) {
            require_once 'Zend/Controller/Dispatcher/Exception.php';
            throw new Zend_Controller_Dispatcher_Exception('Cannot load controller class "' . $className . '" from file "' . $loadFile . "'");
        }
</code></pre>

<p>include_once statement can generate a Warning if the file does not exists
It should be @include_once or check with file_exists</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Raphael Dehousse (thymus) on 2009-11-20T06:10:16.000+0000</p> 
        <div class="body">
            <p>I'm not able to reopen the issue ZF-4736</p>

<p>So, I clone it to say :</p>

<p>Hello,</p>

<p>This issue should be reopened because the include_once statement can generate a Warning if the file does not exists.
It should be @include_once or check with file_exists</p>

<p>Thanks to fix this</p>

<p>Cheers,</p>

<p>Raphaël Dehousse</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marco Kaiser (bate) on 2009-11-20T06:59:27.000+0000</p> 
        <div class="body">
            <p>fixed with r19092</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-25T06:34:16.000+0000</p> 
        <div class="body">
            <p>Marco -- please modify this to use Zend_Loader::isReadable() in place of file_exists. file_exists() does not take into account the include_path, and as such could generate a false negative.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marco Kaiser (bate) on 2009-11-25T06:40:34.000+0000</p> 
        <div class="body">
            <p>fixed with r19235</p>

        </div>
    </div>
    </div>

