<h2>ZF-8798: Zend_Amf should support compression on both ends</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-01-12T21:42:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Brannon B. King (brannon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I would like the ability to easily turn on compression in the Zend_Amf transfers. The client side ByteArray class supports a compress method which corresponds to the gzuncompress command in PHP and vice-versa. I have some large data that I would prefer go compressed for both size and obfuscation on the wire, although its security is not critical. I would (and do) compress it manually, but it is nice to not have to write your method parameters to an array and vice-versa in each AS3 method before calling or receiving data from the NetConnection. It is also nice if you can send complex arrays and have those translated to/from PHP directly. Is there a public function I could call to do this complex type reconstruction manually on the PHP side if I do compress my complex array manually by first writing it to another array on the client side?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Brannon B. King (brannon) on 2010-01-12T21:47:30.000+0000</p> 
        <div class="body">
            <p>I'd love to see a similar feature for encryption, but I recognize that this is more difficult as Flash/Flex/AS3 is lacking in the encryption arena.</p>

        </div>
    </div>
    </div>

