<h2>ZF-8517: Wrong key for ´searchAttr´ in ´storeParams´  ´url´ on load when using setValue() on Zend_Dojo_Form_Element_FilteringSelect</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-10T07:37:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I use a simple filteringSelect in a form using the declarative method.</p>

<pre class="highlight"><code>
$fooElem = new Zend_Dojo_Form_Element_FilteringSelect(
    'foo',
    array(
        'label' =&gt; 'foo',
        'storeId'   =&gt; 'fooStore',
        'storeType' =&gt; 'dojox.data.QueryReadStore',
        'storeParams' =&gt; array(
            'url' =&gt; '/issues/ajax/data'
        ),
        'dijitParams' =&gt; array(
            'searchAttr' =&gt; 'name'
        )
    )
);
#$fooElem-&gt;setValue('xxx');
</code></pre>

<p>The store gets the data from the following url on load:</p>

<pre class="highlight"><code>
<a href="/issues/ajax/data?name=&amp;start=0">http://.../issues/ajax/data?name=&amp;start=0</a>
</code></pre>

<p>The key for the ´searchAttr´ in the query string is named correctely as ´name´. This happens by default even without setting it explicitly in the ´dijitParams´ array.</p>

<p>Next I set the value on the element:</p>

<pre class="highlight"><code>
$fooElem-&gt;setValue('xxx');
</code></pre>

<p>For some reason the key for the ´searchAttr´ in the query string has changed into ´id´, allthough it is explicitly set in the ´dijitParams´ array:</p>

<pre class="highlight"><code>
<a href="/issues/ajax/data?id=xxx&amp;start=0">http://.../issues/ajax/data?id=xxx&amp;start=0</a>
</code></pre>

<p>The programmatic method acts the same way. This is the ´zendDijits´ Code:</p>

<pre class="highlight"><code>
var zendDijits = [{"id":"foo","params":{"store":"fooStore","searchAttr":"name","dojoType":"dijit.form.FilteringSelect"}},{"id":null,"params":{"dojoType":"dijit.form.Form"}}];
</code></pre>

<p>The element created looks like this:</p>

<pre class="highlight"><code>
</code></pre>

<p>It obviously includes invalid tags. See issue <a href="http://framework.zend.com/issues/browse/ZF-6052">http://framework.zend.com/issues/browse/ZF-6052</a>!</p>

<p>Unfortunately I can't see any difference between the code that could cause the wrong url. So I guess this problem occurs in dojo itself?!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:58.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

