<h2>ZF-8221: unregisterPlugin type problem</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-04T15:24:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Nicolas Ruflin (ruflin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following problem occurs with Zend_Controller_Plugin_Broker if you try to unregister a plugin.</p>

<p>If you try to unregister a plugin with the following code it doesn't work:</p>

<p>$frontController-&gt;unregisterPlugin(new Xodoa_Controller_Plugin_Auth());</p>

<p>Xodoa_Controller_Plugin_Auth extends Zend_Controller_Plugin_Abstract (so it's an instanceof)</p>

<p>To get it working there are two options. On line 98 in the Broker class it's possible to remove the true flag inside the array search method, that it doesn't compare the types. It seems like something goes wrong with the types inside array_search.</p>

<p>$key = array_search($plugin, $this-&gt;_plugins);</p>

<p>Or the other option is to pass the parameter to the function unsregisterPlugin as a string:</p>

<p>$frontController-&gt;unregisterPlugin('Xodoa_Controller_Plugin_Auth');</p>

<p>I expected that it's possible to also pass the object (like mentioned in the function documentation) to the function. The input parameter passes the first instanceof if clause, but then throws an exception because no key is found inside array_search with exactly the same type (inside the array it seems to strings).</p>

<p>I used this for my testing inside a class that extends Zend_Test_PHPUnit_ControllerTestCase.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2009-11-05T01:19:11.000+0000</p> 
        <div class="body">
            <p>Can help.
Note line 11.</p>

<pre class="highlight"><code>
&lt;?php
class Test 
{
    public $value;
}
class Test2
{
    
}
$test = new Test();
//$test-&gt;value = 10;
var_dump(array_search(new Test(), array(new Test2() , $test)));
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-05T06:00:18.000+0000</p> 
        <div class="body">
            <p>You must pass the original plugin instance to unregisterPlugin(), not a new instance.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Nicolas Ruflin (ruflin) on 2009-11-05T06:14:31.000+0000</p> 
        <div class="body">
            <p>Ok, that makes sense. Because of the if clause I thought it only needs to be an instance.</p>

<p>The following code works (like you described):</p>

<p>$frontController = $this-&gt;getFrontController();
$plugin = $frontController-&gt;getPlugin('Xodoa_Controller_Plugin_Auth');
$frontController-&gt;unregisterPlugin($plugin);</p>

<p>So it seems like I just expected that it works different from the documentation. Perhaps it would be good to add a note to the documentation about that.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:15.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

