<h2>ZF-8632: Support dijit.form.Select</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2009-12-25T11:32:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-21T10:50:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8137">ZF-8137</a></li>
            <li><a href="/issues/browse/ZF-12221">ZF-12221</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Dojot Toolkit 1.4 Dojox.form.DropDownSelect has been moved to dijit.form.Select</p>

<p><a href="http://docs.dojocampus.org/releasenotes/1.4#dijit-form-select">http://docs.dojocampus.org/releasenotes/1.4/…</a></p>

<p>I think, we must add Zend_Dojo_Form_Element_Select , Zend_Dojo_View_Helper_Select classes?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

