<h2>ZF-8870: sending typed objects with references</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-19T06:52:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-06T19:37:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Wade Arnold (wadearnold)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
            <li>zf-caretaker-adamlundrigan</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Sending an array with typed objects, which contain typed objects themselves causes an "Unknows Definition reference" in Zend_Amf_Parse_Amf3_Deserializer (line 304).</p>

<p>Tracing that error back to Zend_Amf_Parse_Amf0_Deserializer i found that the deserializer is created newly everytime readAmf3TypeMarker is called (line 297).</p>

<p>Changing this behaviour back (caching the amf3-parser and using a getter for it) this issue is resolved.</p>

<p>The working Zend_Amf_Parse_Amf0_Deserializer i took was from june 2009 - zendfw 1.8</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stefan Klug (stefanklug) on 2010-01-21T07:09:43.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>The solution provided above is no valid fix, as the caching of the Amf3 Parser was removed on purpose. See the fix for ZF-6393.
If someone (Matthias?) could provide a failing testcase, I can work on a solution.</p>

<p>Regards Stefan</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stefan Klug (stefanklug) on 2010-01-21T07:24:32.000+0000</p> 
        <div class="body">
            <p>It might be, that this issue boils down to the problem (and fix) mentioned in ZF-8015.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthias Steinböck (rocksocke) on 2010-01-22T12:22:39.000+0000</p> 
        <div class="body">
            <p>hi!</p>

<p>thanks for your response! i didn't want to post a invalid fix sorry... i didn't find a fix in ZF-8015 though it seems that its the same problem, but i can't say it for sure.</p>

<p>in fact i'm no expert on the amf-protocol. i can post my logs in the next days. i'd really appreciate if you'd find time to check this...</p>

<p>thanks again!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-11-08T18:28:41.000+0000</p> 
        <div class="body">
            <p>Is this still an issue?</p>

        </div>
    </div>
    </div>

