<h2>ZF-8191: It is not possible to jump through modules with the actionStack helper if you change the inflectorTarget of the viewRenderer.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-30T10:23:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                André Schade (toocan)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I changed the inflectorTarget so I have the context it to have all views in a context in same (sub)directory
":controller/:context:action.:suffix" if we hav a context.
But when I do so I am not able anymore to jump to other modules by using the actionStack in the controller, the _forward syntax or the action helper in the view itself.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by André Schade (toocan) on 2009-12-02T14:03:40.000+0000</p> 
        <div class="body">
            <p>addition: you can jump through the module (different controller, action etc.) but it does'nt mater what module you choose, you will stay in the module you started.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-02-28T10:12:02.000+0000</p> 
        <div class="body">
            <p>Detached Zend_Filter_Inflector from assigned components.
The filter itself works as expected.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by André Schade (toocan) on 2010-09-07T06:37:30.000+0000</p> 
        <div class="body">
            <p>I prepared a small example app (16KB), but I cannot attach anything. Is this normal?
Where shoudl I put this so you can have have look at it?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by André Schade (toocan) on 2010-09-07T07:19:29.000+0000</p> 
        <div class="body">
            <p>example: <a href="http://lab.script-artists.de/targetInflector.zip">inflectortarget.zip</a></p>

        </div>
    </div>
    </div>

