<h2>ZF-8461: Zend_Application phpSettings should be mentioned</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-12-04T00:12:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:52:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marko Korhonen (back-2-95)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Application phpSettings setting "phpSettings.date.timezone" should be mentioned here:</p>

<p><a href="http://framework.zend.com/manual/en/zend.date.html#zend.date.setdefaulttimezone">http://framework.zend.com/manual/en/…</a></p>

<p>For example I can define timezone in my application.ini my declaring this setting as follows:</p>

<p>phpSettings.date.timezone = "Europe/Helsinki"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-04T01:01:24.000+0000</p> 
        <div class="body">
            <p>Change affected component to Zend_Application.
Timezone IS mentioned by Zend_Date.</p>

<p>Which other component you are using side by side with Zend_Date does not change the setting itself. These components are completly independent from each other.</p>

<p>PHP configuration settings should be mentioned within Zend_Application because there are also other configuration settings beside timezone which should be done when using Zend_Application.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:52:58.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

