<h2>ZF-8961: Add a description for Zend_Filter_Dir</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task: Docs</dd>

    <dt>Created:</dt>
    <dd>2010-01-27T13:05:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-22T03:09:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wil Moore III (wilmoore) (wilmoore)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Add a description for Zend_Filter_Dir</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Moore III (wilmoore) (wilmoore) on 2010-05-21T22:50:22.000+0000</p> 
        <div class="body">
            <p>added manual chapter/section with description and examples for Zend_Filter_Dir. Also corrected a typo in Zend_Filter_Digits.
Implemented via [SVN:r22243:wilmoore].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-05-22T01:28:33.000+0000</p> 
        <div class="body">
            <p>Reopened issue</p>

<p>This was a notification for myself and the added section is incomplete.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Wil Moore III (wilmoore) (wilmoore) on 2010-05-22T03:09:34.000+0000</p> 
        <div class="body">
            <p>modificaions to chapter for Zend_Filter_Dir per documentation spec. Documentation test is passing.</p>

        </div>
    </div>
    </div>

