<h2>ZF-8898: Handling xmlrpc i8 Tags </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-01-22T01:27:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-08T13:06:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christian Lallemand (ccd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_XmlRpc_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10453">ZF-10453</a></li>
            <li><a href="/issues/browse/ZF-8623">ZF-8623</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12670/zf_big_int_i8.patch">zf_big_int_i8.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When i receive a xmlrpc respose with a i8 tag inside, Zend can't print this value !!! 
I have attached a patch File that fixed this problem</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Lallemand (ccd) on 2010-01-22T01:29:13.000+0000</p> 
        <div class="body">
            <p>Patch File to Fix I8 Tag handling</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2010-11-18T11:37:38.000+0000</p> 
        <div class="body">
            <p>As discussed in #zftalk.dev i refactored Zend_XmlRpc_Value_BigInteger because some major bugs made this class unusable.</p>

<p>Because of some big mistakes in Zend_XmlRpc_Value_BigInteger and it's tests it was not possible to not break backward compatibility.</p>

<p>Fixed in r23363.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2011-01-08T13:02:36.000+0000</p> 
        <div class="body">
            <p>Only tests are merged to branch, Should be done the merged of the correction also or revert tests flawed of the branch already that this issue break BC.</p>

        </div>
    </div>
    </div>

