<h2>ZF-8579: Zend_Navigation doesn't work properly with hostname routes (chained)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-18T03:17:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-26T09:35:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Cristian Bichis (avantis)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Kai Uwe (kaiuwe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>For this route configuration the Navigation side doesn't seems to work properly.</p>

<pre><code>    $hostnameRoute = new Zend_Controller_Router_Hostname(
        ':site.domain.com',
        array( 'site'=&gt;'www' ),
        array( 'site' =&gt; 'www|a|b|c' )
    );

    $defaultplain = new Zend_Controller_Router_Route(
        ':module/:controller/:action/*',
        array('module'=&gt;'default', 'controller'=&gt;'index', 'action'=&gt;'index')

    );

    $router-&gt;addRoute('default', $hostnameRoute-&gt;chain($defaultplain));
</code></pre>

<p>Passing to container a page like this:</p>

<p>array('label'=&gt;$page['name'], 'site'=&gt;'a', 'route'=&gt;'default', 'reset_params'=&gt;true);</p>

<p>Would result into href been: <a href="www.domain.com">www.domain.com</a>, and NOT a.domain.com as expected.</p>

<p>Of course, if i manually use the Url view helper like this:</p>

<p>$href= $url-&gt;url(array('site'=&gt;'a'), 'default', true)</p>

<p>would result into a correctly: a.domain.com.</p>

<p>So i guess the Zend_Navigation_Page_Mvc is not working properly with hostname/chained routes...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-09T05:15:10.000+0000</p> 
        <div class="body">
            <p><em>Please use code tags!</em></p>

<p>There is no bug!
Read the documentation carefully: "<a href="http://framework.zend.com/manual/en/zend.navigation.pages.html#zend.navigation.pages.mvc">Zend_Navigation: Pages - Zend_Navigation_Page_Mvc</a>"</p>

<pre class="highlight"><code>
array(
    'label'      =&gt; 'Foo',
    'route'      =&gt; 'foo',
    'controller' =&gt; 'index',
    'action'     =&gt; 'index',
    'params'     =&gt; array(
        'site' =&gt; 'a'
    ),
),
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Cristian Bichis (avantis) on 2011-05-26T09:22:33.000+0000</p> 
        <div class="body">
            <p>You are right, i just tested.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-05-26T09:28:08.000+0000</p> 
        <div class="body">
            <p>Hello Cristian,
please give feedback if you have tested it.</p>

<p>Thanks and greetings.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Cristian Bichis (avantis) on 2011-05-26T09:35:36.000+0000</p> 
        <div class="body">
            <p>It works as you mentioned. So was right to close the ticket as Not an Issue.</p>

        </div>
    </div>
    </div>

