<h2>ZF-843: Notice in Getopt when called with invalid key</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-02-02T16:07:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Console_Getopt</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Cal Evans (cal@calevans.com) writes:</p>

<p>I'm working with getopt and I'm running into an issue.  If I fire getOption() with an invalid key, it returns null like it should but it throws a notice:</p>

<p>Notice: Undefined index:  module in /home/devzone/zendlib/incubator/library/Zend/Console/Getopt.php on line 520</p>

<p>Line 520:</p>

<pre class="highlight"><code>
        $flag = $this-&gt;_ruleMap[$flag];
</code></pre>

<p>If you change that to:</p>

<pre class="highlight"><code>
        $flag = @$this-&gt;_ruleMap[$flag];
</code></pre>

<p>Then the notice goes away. However, I'm not sure of the ramifications of that.  Everything SEEMS to work just fine.</p>

<p>Also, just a nit-pick here. (on a beautiful piece of code) the docbloc for getOption lists the parameter as $key but the actual function says $flag.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-13T15:08:30.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3905.</p>

        </div>
    </div>
    </div>

