<h2>ZF-8941: FormCheckbox renders hidden field with array element</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-01-26T11:12:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Pedro Pinto (_pn_boy)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12683/ZF-8941.patch">ZF-8941.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>in a view:</p>

<p>$this-&gt;formCheckbox('example[index1]', 'Example1', $attribs);
$this-&gt;formCheckbox('example[index2]', 'Example2', $attribs);</p>

<p>will incorrectly render the hidden field, although this is an array.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pedro Pinto (_pn_boy) on 2010-05-07T13:30:33.000+0000</p> 
        <div class="body">
            <p>a better solution, somehow cleaner, might be to change, in the class Zend_View_Helper_FormCheckbox:
if (!$disable &amp;&amp; !strstr($name, '[]')) {
to:
if (!$disable &amp;&amp; !strstr($name, ']')) {</p>

<p>another example of broken behaviour (code snippet):
foreach ($images as $image)
$this-&gt;formCheckbox('image_del[' . $image-&gt;id . ']', $image-&gt;id);</p>

<p>using "$this-&gt;formCheckbox('image_del[]', $image-&gt;id);" ain't an option, since it will render a image_del id in the form elements, over and over again, which also ain't valid html/xhtml</p>

        </div>
    </div>
    </div>

