<h2>ZF-8585: Exception mentions a non-existing method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-19T11:09:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-20T07:51:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>File: class Zend_View_Helper_HeadMeta
Versio: $Id: HeadMeta.php 16971 2009-07-22 18:05:45Z mikaelkael $</p>

<p>public function offsetSet($index, $value)
    {
        if (!$this-&gt;_isValid($value)) {
            require_once 'Zend/View/Exception.php';
            throw new Zend_View_Exception('Invalid value passed to offsetSet; please use offsetSetMeta()');
        }</p>

<pre><code>    return $this-&gt;getContainer()-&gt;offsetSet($index, $value);
}
</code></pre>

<p>When trying to set an offset:
$this-&gt;view-&gt;headMeta()-&gt;offsetSet('keywords', '123');</p>

<p>exception is thrown with a note that offsetSetMeta() should be used but such method does not exist:
$this-&gt;view-&gt;headMeta()-&gt;offsetSetMeta('keywords', '123'); throws:
Zend_View_Exception: Method "offsetSetMeta" does not exist</p>

<p>Also, line 154 of Zend_View_Helper_HeadMeta:
if ($action == 'set') {
  //var_dump($this-&gt;getContainer());
}
I believe this should be cleaned up.</p>

<p>Juraj</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-12-21T07:01:41.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk and 1.9 release branch</p>

        </div>
    </div>
    </div>

