<h2>ZF-8748: Zend_Db_Adapter_Pdo_Dblib SQL-Server query leaves results pending</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-08T09:18:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-06-18T12:38:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When executing stored procedure on SQL Server from within loop, subsequent queries in loop return Zend_Db_Statement_Exception:
SQLSTATE[HY000]: General error: 20019 Attempt to initiate a new SQL Server operation with results pending. [20019]</p>

<p>$db = $this-&gt;getAdapter();
foreach($data as $k =&gt; $v){
    $sql = "EXECUTE sp_DoSomething {$db-&gt;quote($k)}, {$db-&gt;quote($v)}";
    $result = $db-&gt;query($sql)-&gt;fetchAll(); 
}</p>

<p>Current workaround is to reconnect after each loop iteration, which is expensive.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-01-08T10:10:54.000+0000</p> 
        <div class="body">
            <p>I need a small reproduction to be able to verify this, so can you provide:</p>

<p>a) an DDL that is needed, including the table in question and the stored procedure in question
b) a script including dbadapter creation as well as code that will rais the notice/error/exception</p>

<p>Thanks!
Ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-06-18T12:38:34.000+0000</p> 
        <div class="body">
            <p>Cannot reproduce this issue, please attach more information.</p>

        </div>
    </div>
    </div>

