<h2>ZF-8510: Zend_Dojo_Form fails to submit in FF</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-09T15:43:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-11T12:25:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                cg (s3ct0r)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The following code will yield a form however submission would not work;</p>

<p>class Form_DojoCurve extends Zend_Dojo_Form
{
    public function __construct($options = null) {
        parent::__construct($options);
    }</p>

<pre><code>public function init() {
    $fc = Zend_Controller_Front::getInstance();

    $this-&gt;setMethod('post');
    $this-&gt;setName('curveform');
    $this-&gt;setAction($fc-&gt;getBaseUrl() . '/index/validate');

    $field = new Zend_Dojo_Form_Element_FilteringSelect('issuer');
    $field-&gt;setLabel('Issuer')
            -&gt;setAutoComplete(true)
            -&gt;setStoreId('issuersStore')
            -&gt;setStoreType('dojox.data.QueryReadStore')
            -&gt;setStoreParams(array('url' =&gt; $fc-&gt;getBaseUrl() . '/form-feeder/issuers'))
            -&gt;setAttrib("searchAttr", "DESCR")
            -&gt;setAttrib("searchDelay", "600")
            -&gt;setRequired(true);      

    $this-&gt;addElement($field);

    $this-&gt;addElements(array(
        'go' =&gt; array('type' =&gt; 'submit',
        'options' =&gt; array('label' =&gt; 'Go!'))
        ));
}
</code></pre>

<p>}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by cg (s3ct0r) on 2009-12-09T15:46:54.000+0000</p> 
        <div class="body">
            <p>Submission works fine in IE.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by cg (s3ct0r) on 2009-12-11T11:33:28.000+0000</p> 
        <div class="body">
            <p>Resolved, wrapping</p>

<p>&lt;</p>

<p>form&gt; inside</p>

<p>&lt;</p>

<p>table&gt; caused FF problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-12-11T12:25:49.000+0000</p> 
        <div class="body">
            <p>Closing per reporter comments.</p>

        </div>
    </div>
    </div>

