<h2>ZF-887: Zend_Db_Select: support for queries without a FROM clause</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-02-08T19:07:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Some RDBMS brands, such as MySQL and MS SQL Server, support SQL queries that have no FROM clause.  They have a select-list and can accept ORDER BY and LIMIT clauses, but not WHERE, GROUP BY, or HAVING.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-08T20:52:10.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3320.</p>

<p>Note that if you have no FROM clause specified, the WHERE, GROUP BY and HAVING clauses are silently ignored.  No error or exception is generated.</p>

        </div>
    </div>
    </div>

