<h2>ZF-8298: Zend/Cache/Backend/Sqlite.php return empty result</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-12T19:02:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-17T18:21:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Supplying the multiple tags to "public function getIdsMatchingTags($tags = array())" return empty result.</p>

<p>Solution:</p>

<p>Changing "$ids = array_intersect($ids, $ids2);" to "$ids = array_merge($ids, $ids2);" returns correct result.</p>

<p>Tested current version, not sure about other ones.</p>

<p>Cheers</p>

<p>P.S.
if you are fixing the issue with above solution then there is not differents between</p>

<p>public function getIdsMatchingTags($tags = array())</p>

<p>and</p>

<p>public function getIdsMatchingAnyTags($tags = array())</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Tankersley (dragonmantank) on 2009-12-17T18:21:49.000+0000</p> 
        <div class="body">
            <p>Could not reproduce as of r19737</p>

<p>getIdsMatchingAnyTags() is using an array_merge()
getIdsMatchingTags() is using an array_intersect()</p>

<p>Both are working as intended</p>

        </div>
    </div>
    </div>

