<h2>ZF-8620: Requirements documentation has broken links to PHP manual</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-12-22T17:46:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-15T11:40:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12538/ZF-8620.patch">ZF-8620.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/requirements.html">http://framework.zend.com/manual/en/…</a></p>

<p>This document links to <a href="http://www.php.net/manual/en/language.oop5.reflection.php">http://php.net/manual/en/…</a> which does not exist (anymore).</p>

<p>It should link to <a href="http://www.php.net/manual/en/book.reflection.php">http://www.php.net/manual/en/book.reflection.php</a>.</p>

<p>When I need to find something, I usually (ab)use <a href="http://php.net/reflection">http://php.net/reflection</a> which not only redirects me to a mirror, but gives me good results most of the time.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christopher Thomas (cwt137) on 2009-12-23T06:44:11.000+0000</p> 
        <div class="body">
            <p>Here is a patch to change the urls in the English docs</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Vincent de Lau (vdelau) on 2009-12-23T07:34:23.000+0000</p> 
        <div class="body">
            <p>Patch looks ok, should be committed AFAICT.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-15T11:40:44.000+0000</p> 
        <div class="body">
            <p>Fixed with r21512</p>

        </div>
    </div>
    </div>

