<h2>ZF-8133: 2 Routes in Zend_Controller_Router_REST documentation are bold without reason?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-10-23T07:54:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-18T10:12:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12509/Zend_Controller-Router-Route-Rest.xml.diff">Zend_Controller-Router-Route-Rest.xml.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It seems as if the two urls on the bottom of this table ( <a href="http://framework.zend.com/manual/en/zend.controller.router.html#zend.controller.router.routes.rest">http://framework.zend.com/manual/en/…</a> ) are printed in bold without any (good) reason. If there's a good reason to let those two lines be in bold please comment &amp; close this issue. If not, I will remove the bold tags in a week or so.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2009-12-17T14:15:29.000+0000</p> 
        <div class="body">
            <p>I don't see any links printed in bold. Maybe they got fixed in the meantime?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert Basic (robertbasic) on 2009-12-17T14:50:41.000+0000</p> 
        <div class="body">
            <p>The diff attached changes the  tag in the last two urls to  which should fix this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2009-12-18T10:12:11.000+0000</p> 
        <div class="body">
            <p>Patch applied with r19753</p>

        </div>
    </div>
    </div>

