<h2>ZF-8772: Maybe a spelling error.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-10T18:14:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-12T17:34:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ryan Forrester (ryanjf)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Pdf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8795">ZF-8795</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Line 554 of Zend/Pdf/Font.php has the word Exception spelled wrong:
require_once 'Zend/Pdf/Excaption.php';</p>

<p>Maybe should be?:
require_once 'Zend/Pdf/Exception.php';</p>

<h2>Error I'm getting:</h2>

<p>Warning: Zend_Pdf_Font::require_once(Zend/Pdf/Excaption.php) [function.Zend-Pdf-Font-require-once]: failed to open stream: No such file or directory in /var/www/ybs-certificates/www/Zend/Pdf/Font.php on line 554</p>

<h2>Fatal error: Zend_Pdf_Font::require_once() [function.require]: Failed opening required 'Zend/Pdf/Excaption.php' (include_path='.:/usr/share/<a>php:/usr/share/pear</a>') in /var/www/ybs-certificates/www/Zend/Pdf/Font.php on line 554</h2>

<p>Cheers,
Ryan</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-01-11T18:15:45.000+0000</p> 
        <div class="body">
            <p>Hi, Ryan. Thank You for report.</p>

<p>Solved in SVN r20211.</p>

        </div>
    </div>
    </div>

