<h2>ZF-8937: would be great to have an ability to set default format for Zend_Date</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-26T08:01:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-26T10:21:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Yegor Bugayenko (yegor256)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7719">ZF-7719</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Would be great to have an ability to set a default format for Zend_Date objects, instead of doing this thing every time:</p>

<p>&lt;?php
echo Zend_Date::now()-&gt;get(Zend_Date::DATE_MEDIUM);</p>

<p>I would do this instead:</p>

<p>&lt;?php
Zend_Date::setDefaultFormat(Zend_Date::DATE_MEDIUM);
echo Zend_Date::now();</p>

<p>What do you think?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-26T10:21:09.000+0000</p> 
        <div class="body">
            <p>Closing as duplicate</p>

        </div>
    </div>
    </div>

