<h2>ZF-8572: Zend_db_Select::union() does not accept Zend_Db_Select objects/strings</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-17T14:21:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Grégory PLANCHAT (gplanchat)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{{Zend_Db_Select}}'s {{union()}} method does not follow the docs specifications, it just returns {{$this}} if the {{$select}} param isn't an array.</p>

<p>I made a trivial fix:</p>

<pre class="highlight"><code>
Index: library/Zend/Db/Select.php
===================================================================
--- library/Zend/Db/Select.php
+++ library/Zend/Db/Select.php
@@ -271,7 +271,7 @@
     public function union($select = array(), $type = self::SQL_UNION)
     {
         if (!is_array($select)) {
-            $select = array();
+            $select = array($select);
         }
 
         if (!in_array($type, self::$_unionTypes)) {
</code></pre>

<p>I use ZF v1.9.6</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:23.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

