<h2>ZF-8278: Out of memory on large sends</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-11-10T07:11:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-17T06:06:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When sending large amounts of email using the Zend_Mail_Transport_Protocol classes it causes an out of memory problem. This is because each time the protected send method is called it attaches the request to the end of the log. In cases when a lot of emails are being sent this grows eventually causing the memory limit error.</p>

<p>I'm not sure this is the correct solution but I fixed it by resetting the log every time the send method is called:</p>

<pre class="highlight"><code>
class Yourlibrary_Mail_Transport_Smtp extends Zend_Mail_Transport_Smtp
{
    /**
     * Send a mail using this transport
     *
     * @param  Zend_Mail $mail
     * @access public
     * @return void
     * @throws Zend_Mail_Transport_Exception if mail is empty
     */
    public function send(Zend_Mail $mail)
    {
        $connection = $this-&gt;getConnection();
        if ($connection instanceof Zend_Mail_Protocol_Smtp) {
            $connection-&gt;resetLog();
        }
        return parent::send($mail);
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Fabio Napoleoni (fabio) on 2009-11-10T16:28:14.000+0000</p> 
        <div class="body">
            <p>In my case the patch work, I send a small list of about 800 members and without this class my script crashes unless I raise memory limit up to 256M or even 512M.</p>

<p>But with this class the problem is gone.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-14T05:32:56.000+0000</p> 
        <div class="body">
            <p>I think notation would be helpful.
The notation in document should notice in case user send many mails.</p>

<p>So, I change this issue to Docs: Improvement.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-11-16T20:13:22.000+0000</p> 
        <div class="body">
            <p>I added limitation of log counts at SVN r19008 (trunk).</p>

<p>I will be happy if you would try new code ;-)
This improvement would be released at 1.10.0 or later.</p>

        </div>
    </div>
    </div>

