<h2>ZF-8741: Zend_Cache_Core::getIdsMatchingAnyTags() not implemented</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-07T11:14:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-01T18:10:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Cache backends implementing the extended interface all have a getIdsMatchingAnyTags() method. However, this is not implemented in Zend_Cache_Core, so the backend method can not be called.</p>

<p>A new method Zend_Cache_Core::getIdsMatchingAnyTags() should be created similar to Zend_Cache_Core::getIdsMatchingTags().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-01T12:53:51.000+0000</p> 
        <div class="body">
            <p>Thank You for report, I will be happy if You try trunk code ( SVN r20815)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sven Axelsson (svenax) on 2010-02-02T00:45:36.000+0000</p> 
        <div class="body">
            <p>The impementation looks fine.</p>

<p>However, there ought to be unit tests that test calling all extended backend functions through Zend_Cache_Core, not just load, save, test, clean. And that would mean having Zend_Cache_Backend_Test implement the extended interface to make those methods available.</p>

<p>I could do that if there's interest for it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-20T05:05:32.000+0000</p> 
        <div class="body">
            <p>Yes, it's right, Sven. 
We should implement missing test and do several changes that the test needs.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-03-01T18:10:14.000+0000</p> 
        <div class="body">
            <p>merged SVN trunk r20815 to 1.10 branch at SVN r21290.</p>

        </div>
    </div>
    </div>

