<h2>ZF-8780: Review of various parts of the german translation of the manual</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-11T14:48:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-23T07:29:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Uli Wolf (uli)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
            <li>Zend_Debug</li>
            <li>Zend_Server_Reflection</li>
            <li>Zend_TimeSync</li>
            <li>Zend_Uri</li>
            <li>Zend_Wildfire</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12598/r20208.zip">r20208.zip</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I did a review of the German translation of the documentation, attached you can find the related patches various parts (i think they speak for themselves). If you do have any feedback, do not hesitate to contact me.</p>

<p>Edit: The Patches are created against r20208</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Uli Wolf (uli) on 2010-01-11T14:50:39.000+0000</p> 
        <div class="body">
            <p>Patches:</p>

<p>Zend_Date-Additional
Zend_Date-Basic
Zend_Date-Creation
Zend_Date-Theory
Zend_Debug
Zend_Server
Zend_Server_Reflection
Zend_TimeSync
Zend_TimeSync-Working
Zend_Uri
Zend_Wildfire</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-23T07:29:28.000+0000</p> 
        <div class="body">
            <p>Patch branched with r20550.</p>

        </div>
    </div>
    </div>

