<h2>ZF-8747: lowercase check on isValidModule but call array as given produce error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-07T21:36:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>on ZF 1.9.6 Standard Dispatcher the isValidModul() method checks the given $request-&gt;getModulName() in lowercase but doesn't use lowercase in getControllerClass():</p>

<pre><code>public function isValidModule($module)
{
    //...
    $module        = strtolower($module);
    $controllerDir = $this-&gt;getControllerDirectory();
    foreach (array_keys($controllerDir) as $moduleName) {
        if ($module == strtolower($moduleName)) {
            return true;
        }
    }
    //...
}

public function getControllerClass(Zend_Controller_Request_Abstract $request)
{
    //...
    $controllerDirs      = $this-&gt;getControllerDirectory();
    $module = $request-&gt;getModuleName();
    if ($this-&gt;isValidModule($module)) {
        $this-&gt;_curModule    = $module;
        $this-&gt;_curDirectory = $controllerDirs[$module];
    } 
    //...
}
</code></pre>

<p>Error: Undefined Index: X  ... because of the unknown array key in $controllerDirs[$module]</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Michael Parkin (mikeparkin) on 2010-07-24T02:51:34.000+0000</p> 
        <div class="body">
            <p>I have just experienced the same error with 1.10, the problem is that isValidModule runs strtolower to compare module names but then uses a non-strtolower string to index the $controllerDirs array which causes an error</p>

        </div>
    </div>
    </div>

