<h2>ZF-807: Zend_Auth - Login vs. Identity</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-01-26T08:54:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In keeping with the idea that Zend_Auth is used to authenticate, or identify, the requester, the name of the {{isLoggedIn()}} method is suggested to change to {{hasIdentity()}}, which may be more clear. If a requester has not been identified through authentication, then {{hasIdentity()}} returns false. Only if a requester has successfully authenticated would {{hasIdentity()}} return true.</p>

<p>Also, the {{logout()}} method would accordingly be changed to something like {{removeIdentity()}}.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Ratzloff (mratzloff) on 2007-01-26T12:01:16.000+0000</p> 
        <div class="body">
            <p>In light of ZF-806 this makes sense.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-02-14T16:33:37.000+0000</p> 
        <div class="body">
            <p>Resolved with SVN <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=3412">r3412</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-02-15T18:56:04.000+0000</p> 
        <div class="body">
            <p>I might suggest distinguishing between authentication identities (e.g. username used with a password), and authorization identities (e.g. user id from the primary key column in the users table).  The mere presence of an authorization identity is sufficient to indicate authentication previously succeeded.</p>

        </div>
    </div>
    </div>

