<h2>ZF-8481: Misspelling - Zend_OpenId_Consumer</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2009-12-06T06:28:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-07T00:24:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the German ZF-Docs is a little mistake on Zend_OpenId_Consumer introduction:
Zend_OpenId_Consumer kann verwendet {color:red}werdeb{color}  um OpenID Authentifizierung auf Webseiten zu implementieren.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2009-12-06T13:44:31.000+0000</p> 
        <div class="body">
            <p>I believe in Thomas would resolve this ;-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-07T00:24:27.000+0000</p> 
        <div class="body">
            <p>Fixed with r19479</p>

        </div>
    </div>
    </div>

