<h2>ZF-8065: Zend_Search_Lucene get only n top results</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Performance Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-10-13T06:49:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-16T08:22:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Mazalov (alex347)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Please add a limit for n top results to Zend_Search_Lucene.
I have a big database and setResultSetLimit is not satisfactory.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-10-16T06:58:57.000+0000</p> 
        <div class="body">
            <p>Generating "N top results" needs to compose whole result set and calculate <em>all</em> scores.
That takes exactly the same time as returning all results.</p>

<p>One suggestion which may help, you should be careful with using results. First access to the returned hit (access to any field instead id and score) provokes whole document retrieving (stored fields retrieving). It takes additional time. So, only use top N results (first N results from whole result set) adn don't touch others. That will give you exactly the same functionality as "returning top N results".</p>

<p>If you still see such functionality useful, even it doesn't give any performance improvement, please reopen issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Mazalov (alex347) on 2009-10-16T08:22:18.000+0000</p> 
        <div class="body">
            <p>I have 10M records in database. One query could match 500k records.
I will never need more than 1k results.</p>

<p>Yes, it still needs to calculate all scores but don't need to sort and keep in memory all other 499k records. CPU usage will decrease noticeably.</p>

        </div>
    </div>
    </div>

