<h2>ZF-8743: StripTags filter should never allow comments</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-07T13:50:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-11T13:06:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.7.9 (11/Jan/10)</li>
            <li>1.8.5 (11/Jan/10)</li>
            <li>1.9.7 (11/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, the StripTags filter allows optionally allowing comments. However, this should never be allowed, as it's possible to perform IE-style conditional comments that could open XSS attack vectors:</p>

<pre class="highlight"><code>
$filter = new Zend_Filter_StripTags;                                                                          
$filter-&gt;setCommentsAllowed(true);                                                                            
$html = "";                                       
$out = $filter-&gt;filter($html);
// results in:
//  
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-07T14:55:46.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk and 1.9, 1.8, and 1.7 release branches.</p>

        </div>
    </div>
    </div>

