<h2>ZF-895: Various Date related Unit Tests failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-02-09T01:15:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
            <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>3) testisDate(Zend_FilterTest)
"1997-07-16" is a valid date
Failed asserting that  is identical to .
/home/sebastian/Work/ZendFramework/tests/Zend/FilterTest.php:180</p>

<p>4) testTestDate(Zend_Filter_InputTest)
Failed asserting that  is equal to </p><p></p><p></p>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-09T02:18:56.000+0000</p> 
        <div class="body">
            <p>Issue related to ZF-882 / ZF-883.
See added comments there for further information.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-10T06:55:33.000+0000</p> 
        <div class="body">
            <p>After looking in this I think the problems are related to this:</p>

<p>3) testisDate</p>

<p>-&gt; always takes the standard locale. But the standardformat in different environments is not always as expected by this test</p>

<p>-&gt; always verifies strict... maybe loose checking should also be implemented
(isDate -&gt; strict, isFixedDate -&gt; loose). 2000-01-10 is not the same as 01-10-2000.
isDate gives false, isFixedDate gives true for such inputs.</p>

<p>4) testTestDate
 -&gt; see 3 -&gt; locale and strict problem</p>

<p>5) testBasic
 -&gt; see 3</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-02-11T18:39:02.000+0000</p> 
        <div class="body">
            <p>I am working on some related issues that will address the date related issues above.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-02-13T13:04:21.000+0000</p> 
        <div class="body">
            <p>The issue of providing "isDate()" behavior involves many issues:</p>

<h1>What date formats should be supported?</h1>

<h1>A locale is needed for proper interpretation/normalization of dates containing month names.</h1>

<h1>Should  Zend_Validate_Date normalize month names (including abbreviated ones) in the input in order to parse the date?  Should this be done always, or only when requested?</h1>

<h1>What is the format of the date checked? (developer requested, default format for which locale?)</h1>

<h1>If the format defaults to the default format of the default locale, then the <em>exact</em> same "is date" Zend_Validate_Date check might succeed for one web visitor, but not for another from a different locale.  Is this behavior desired or should it be optional and only selected when explicitly requested by the developer?</h1>

<h1>Should Zend_Validate_Date require the developer to specify the date format?</h1>

<h1>Should Zend_Validate_Date require the developer to specify the locale?</h1>

<h1>Should Zend_Validate_Date indicate success for all dates that are valid, <em>after</em> checking for detectable errors, and correcting correctable errors?</h1>

<h1>Should the automatic correction above happen with or without the developers explicit consent / request?</h1>

<h1>Should Zend_Validate_Date even check dates in strings, or should it just wrap PHP's checkdate() function?</h1>

<p>The Zend_Locale_Format::isDate() and isLooseDate() related functions are designed for quite robust operation, and might or might not serve the needs of Zend_Validate_Date, depending on the latter's requirements.  Clarification of requirements is needed before I can make recommendations for resolving the issues outlined above.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-02-13T14:24:04.000+0000</p> 
        <div class="body">
            <p>Fixed in SVN <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=3382">r3382</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-02-14T01:10:14.000+0000</p> 
        <div class="body">
            <p>I can verify the fixes on my machine.</p>

        </div>
    </div>
    </div>

