<h2>ZF-8479: Resource Plugins Automatic Initialization</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-12-05T14:53:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-06T04:44:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bruno Pirajá Moyle (brunitto)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As defined in the {{Zend_Application_Bootstrap_BootstrapAbstract}} class, any component is initialized using the configuration file {{resources}} key. This is fine, as most resources have required initialization options. However, when a resource don't have such options, in order to initialize is needed to cheat the bootstrap object by using a dumb options like {{resources.customResource = ""}}.</p>

<p>My suggestion is that if the bootstrap object received a {{pluginPaths}} option then it could additionally look inside a resource plugins repositories ({{application/resources}} for instance) and automatically initializes any resource within it - by reading the directories entries.</p>

<p>Thats all</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-12-05T15:02:56.000+0000</p> 
        <div class="body">
            <p>What you describe is not cheating, it's just a limitation of the ini-notation. As documented very clearly, the resource names should be stored as keys inside an array, which what you do by 'cheating' (as you described it) with ini files.</p>

<p>Furthermore, I'm against the functionality you're requesting. By doing more and more things automaticly, it becomes less clear to the user what's happening behind the scenes, and it also makes it more slower. While performance is something very important with bootstrapping.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-12-05T20:46:29.000+0000</p> 
        <div class="body">
            <p>We explicitly chose not to take this route for a number of reasons. First, not every resource is going to be needed for every application, and often you will want to develop a library of resources from which you make selections for your application. By taking the route we did, this is possible -- and we do not need to treat the resources shipped with ZF any differently than those developed by end-users.</p>

<p>Second, as Dolf indicates, scanning a directory is a fairly significant performance hit -- and can be better or worse depending on the operating system.</p>

<p>Third, also noted by Dolf, it's better to be explicit about what resources you are using than to automatically inject resources. This makes it clear what resources your application is actually consuming, and allows you to tune your application accordingly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bruno Pirajá Moyle (brunitto) on 2009-12-06T04:44:27.000+0000</p> 
        <div class="body">
            <p>Well done, the arguments were clearly and killing, thanks for the quick reply.</p>

        </div>
    </div>
    </div>

