<h2>ZF-8085: Mixed end-of-line characters in ZF source files</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2009-10-17T05:53:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-18T13:18:19.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Anthon Pang, VIP Software Technologies Inc. (vipsoft)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7316">ZF-7316</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Regression of ZF-4118</p>

<p>It would be nice if all the source files used newlines (instead of CR/LF or plain CR).  After fixing this, please consider setting "svn:eol-style native" on these files.</p>

<p>These are the files:</p>

<p>./Paginator/ScrollingStyle/Sliding.php
./Paginator/ScrollingStyle/All.php
./Paginator/ScrollingStyle/Interface.php
./Paginator/ScrollingStyle/Jumping.php
./Paginator/ScrollingStyle/Elastic.php
./Paginator/Exception.php
./Paginator/AdapterAggregate.php
./Paginator/Adapter/DbTableSelect.php
./Paginator/Adapter/Iterator.php
./Paginator/Adapter/Null.php
./Paginator/Adapter/Array.php
./Paginator/Adapter/Interface.php
./Locale/Data/uz_Cyrl_UZ.xml
./Locale/Data/sv.xml
./Locale/Data/ar_LB.xml
./Locale/Data/wal_ET.xml
./Locale/Data/es_HN.xml
./Locale/Data/fur.xml
./Locale/Data/mk_MK.xml
./Locale/Data/es_GT.xml
./Locale/Data/dv_MV.xml
./Locale/Data/ha_Latn_NG.xml
./Locale/Data/af.xml
./Locale/Data/fur_IT.xml
./Locale/Data/mn_Mong.xml
./Locale/Data/ug_Arab.xml
./Locale/Data/bn_IN.xml
./Locale/Data/bg_BG.xml
./Locale/Data/gez_ET.xml
./Locale/Data/es_SV.xml
./Locale/Data/es_ES.xml
./Locale/Data/ko.xml
./Locale/Data/zh_CN.xml
./Locale/Data/ug.xml
./Locale/Data/de_DE.xml
./Locale/Data/ha_Latn_GH.xml
./Locale/Data/en_PH.xml
./Locale/Data/so_SO.xml
./Locale/Data/ha_NG.xml
./Locale/Data/ar_LY.xml
./Locale/Data/es.xml
./Locale/Data/lo.xml
./Locale/Data/he.xml
./Locale/Data/tg_Cyrl.xml
./Locale/Data/ve.xml
./Locale/Data/ta.xml
./Locale/Data/fa_IR.xml
./Locale/Data/nr.xml
./Locale/Data/pt_BR.xml
./Locale/Data/ku_IQ.xml
./Locale/Data/ln_CG.xml
./Locale/Data/uk.xml
./Locale/Data/be_BY.xml
./Locale/Data/mn_Cyrl_MN.xml
./Locale/Data/kk_Cyrl.xml
./Locale/Data/tg_TJ.xml
./Locale/Data/gl.xml
./Locale/Data/es_CO.xml
./Locale/Data/nr_ZA.xml
./Locale/Data/xh_ZA.xml
./Locale/Data/cch_NG.xml
./Locale/Data/fr_FR.xml
./Locale/Data/it_CH.xml
./Locale/Data/so.xml
./Locale/Data/trv_TW.xml
./Locale/Data/kk.xml
./Locale/Data/sr_Latn_ME.xml
./Locale/Data/haw_US.xml
./Locale/Data/pt.xml
./Locale/Data/ps_AF.xml
./Locale/Data/sk.xml
./Locale/Data/el.xml
./Locale/Data/cy.xml
./Locale/Data/ps.xml
./Locale/Data/in.xml
./Locale/Data/mn_Mong_CN.xml
./Locale/Data/kok.xml
./Locale/Data/zu_ZA.xml
./Locale/Data/kam.xml
./Locale/Data/he_IL.xml
./Locale/Data/ha_NE.xml
./Locale/Data/is_IS.xml
./Locale/Data/ms.xml
./Locale/Data/wo.xml
./Locale/Data/sr_Latn_YU.xml
./Locale/Data/cs.xml
./Locale/Data/zh_Hans_MO.xml
./Locale/Data/fil_PH.xml
./Locale/Data/sid.xml
./Locale/Data/kn.xml
./Locale/Data/wal.xml
./Locale/Data/es_EC.xml
./Locale/Data/tt_RU.xml
./Locale/Data/es_CR.xml
./Locale/Data/sq_AL.xml
./Locale/Data/pt_PT.xml
./Locale/Data/es_AR.xml
./Locale/Data/ii_CN.xml
./Locale/Data/ml.xml
./Locale/Data/mr_IN.xml
./Locale/Data/sr_Cyrl_BA.xml
./Locale/Data/es_VE.xml
./Locale/Data/si_LK.xml
./Locale/Data/en_JM.xml
./Locale/Data/kpe_LR.xml
./Locale/Data/uz_Arab.xml
./Locale/Data/vi_VN.xml
./Locale/Data/el_POLYTON.xml
./Locale/Data/cch.xml
./Locale/Data/characters.xml
./Locale/Data/nl_NL.xml
./Locale/Data/tr.xml
./Locale/Data/sh_CS.xml
./Locale/Data/gez_ER.xml
./Locale/Data/ve_ZA.xml
./Locale/Data/sr_Cyrl.xml
./Locale/Data/id_ID.xml
./Locale/Data/so_DJ.xml
./Locale/Data/sr_RS.xml
./Locale/Data/hy_AM_REVISED.xml
./Locale/Data/cs_CZ.xml
./Locale/Data/kl.xml
./Locale/Data/sh.xml
./Locale/Data/dz.xml
./Locale/Data/ts.xml
./Locale/Data/no.xml
./Locale/Data/fo.xml
./Locale/Data/en_BW.xml
./Locale/Data/bn_BD.xml
./Locale/Data/tig_ER.xml
./Locale/Data/en_MP.xml
./Locale/Data/sk_SK.xml
./Locale/Data/ja_JP.xml
./Locale/Data/sr_Cyrl_CS.xml
./Locale/Data/lt_LT.xml
./Locale/Data/en.xml
./Locale/Data/tg.xml
./Locale/Data/ca_ES.xml
./Locale/Data/syr.xml
./Locale/Data/ml_IN.xml
./Locale/Data/mo.xml
./Locale/Data/en_IE.xml
./Locale/Data/bs.xml
./Locale/Data/ne_IN.xml
./Locale/Data/ar_DZ.xml
./Locale/Data/it.xml
./Locale/Data/be.xml
./Locale/Data/lv.xml
./Locale/Data/tt.xml
./Locale/Data/ee_GH.xml
./Locale/Data/es_NI.xml
./Locale/Data/ku_IR.xml
./Locale/Data/ia.xml
./Locale/Data/nl_BE.xml
./Locale/Data/uz_Cyrl.xml
./Locale/Data/gaa.xml
./Locale/Data/hu_HU.xml
./Locale/Data/ur.xml
./Locale/Data/se.xml
./Locale/Data/om.xml
./Locale/Data/th_TH.xml
./Locale/Data/es_DO.xml
./Locale/Data/hr.xml
./Locale/Data/es_CL.xml
./Locale/Data/el_CY.xml
./Locale/Data/nb_NO.xml
./Locale/Data/en_US.xml
./Locale/Data/zh_HK.xml
./Locale/Data/ar_YE.xml
./Locale/Data/kfo.xml
./Locale/Data/zh.xml
./Locale/Data/si.xml
./Locale/Data/dz_BT.xml
./Locale/Data/pa_Arab_PK.xml
./Locale/Data/ug_Arab_CN.xml
./Locale/Data/de_CH.xml
./Locale/Data/ar_QA.xml
./Locale/Data/ts_ZA.xml
./Locale/Data/sr_Latn.xml
./Locale/Data/yo.xml
./Locale/Data/uz_Latn.xml
./Locale/Data/en_CA.xml
./Locale/Data/mt_MT.xml
./Locale/Data/pl_PL.xml
./Locale/Data/ak_GH.xml
./Locale/Data/or_IN.xml
./Locale/Data/haw.xml
./Locale/Data/am.xml
./Locale/Data/sv_FI.xml
./Locale/Data/bs_BA.xml
./Locale/Data/zh_Hant_TW.xml
./Locale/Data/en_AU.xml
./Locale/Data/dv.xml
./Locale/Data/kaj_NG.xml
./Locale/Data/eu.xml
./Locale/Data/et_EE.xml
./Locale/Data/root.xml
./Locale/Data/ku.xml
./Locale/Data/nds_DE.xml
./Locale/Data/se_NO.xml
./Locale/Data/zh_SG.xml
./Locale/Data/ar_SY.xml
./Locale/Data/iu.xml
./Locale/Data/lt.xml
./Locale/Data/te.xml
./Locale/Data/az_Cyrl.xml
./Locale/Data/sa.xml
./Locale/Data/mk.xml
./Locale/Data/ar_EG.xml
./Locale/Data/hy.xml
./Locale/Data/da_DK.xml
./Locale/Data/supplementalData.xml
./Locale/Data/sr_YU.xml
./Locale/Data/ne.xml
./Locale/Data/ti_ET.xml
./Locale/Data/nl.xml
./Locale/Data/fr.xml
./Locale/Data/en_BZ.xml
./Locale/Data/aa_DJ.xml
./Locale/Data/ha_Arab_SD.xml
./Locale/Data/bo.xml
./Locale/Data/en_VI.xml
./Locale/Data/mn_MN.xml
./Locale/Data/sq.xml
./Locale/Data/uz_AF.xml
./Locale/Data/es_PR.xml
./Locale/Data/sw_TZ.xml
./Locale/Data/ak.xml
./Locale/Data/kfo_CI.xml
./Locale/Data/ar_SA.xml
./Locale/Data/ha_Arab.xml
./Locale/Data/eu_ES.xml
./Locale/Data/az_AZ.xml
./Locale/Data/ti_ER.xml
./Locale/Data/bn.xml
./Locale/Data/nso.xml
./Locale/Data/ta_IN.xml
./Locale/Data/fa_AF.xml
./Locale/Data/aa_ET.xml
./Locale/Data/yo_NG.xml
./Locale/Data/pa_PK.xml
./Locale/Data/mn.xml
./Locale/Data/ar_JO.xml
./Locale/Data/km_KH.xml
./Locale/Data/ja.xml
./Locale/Data/hy_AM.xml
./Locale/Data/ku_TR.xml
./Locale/Data/tn_ZA.xml
./Locale/Data/wo_Latn_SN.xml
./Locale/Data/kpe_GN.xml
./Locale/Data/kk_Cyrl_KZ.xml
./Locale/Data/zh_MO.xml
./Locale/Data/az_Cyrl_AZ.xml
./Locale/Data/ss.xml
./Locale/Data/lv_LV.xml
./Locale/Data/st_ZA.xml
./Locale/Data/gv_GB.xml
./Locale/Data/kaj.xml
./Locale/Data/sr_Cyrl_RS.xml
./Locale/Data/pa_Arab.xml
./Locale/Data/sr_Latn_CS.xml
./Locale/Data/rw_RW.xml
./Locale/Data/gu.xml
./Locale/Data/sh_BA.xml
./Locale/Data/bo_IN.xml
./Locale/Data/kok_IN.xml
./Locale/Data/kl_GL.xml
./Locale/Data/en_Dsrt.xml
./Locale/Data/numberingSystems.xml
./Locale/Data/zh_Hans.xml
./Locale/Data/om_ET.xml
./Locale/Data/wo_Latn.xml
./Locale/Data/sr_BA.xml
./Locale/Data/ee_TG.xml
./Locale/Data/zh_Hant_MO.xml
./Locale/Data/mn_CN.xml
./Locale/Data/ar_TN.xml
./Locale/Data/en_Shaw.xml
./Locale/Data/ru_RU.xml
./Locale/Data/ga_IE.xml
./Locale/Data/kn_IN.xml
./Locale/Data/en_HK.xml
./Locale/Data/ku_Arab_IQ.xml
./Locale/Data/fr_CA.xml
./Locale/Data/sr_Cyrl_ME.xml
./Locale/Data/fa.xml
./Locale/Data/af_ZA.xml
./Locale/Data/az.xml
./Locale/Data/es_PA.xml
./Locale/Data/ha.xml
./Locale/Data/ha_GH.xml
./Locale/Data/uz_Latn_UZ.xml
./Locale/Data/my.xml
./Locale/Data/ha_Latn.xml
./Locale/Data/om_KE.xml
./Locale/Data/zh_Hant.xml
./Locale/Data/zu.xml
./Locale/Data/ca.xml
./Locale/Data/ss_ZA.xml
./Locale/Data/pa_IN.xml
./Locale/Data/en_Dsrt_US.xml
./Locale/Data/so_KE.xml
./Locale/Data/nds.xml
./Locale/Data/es_BO.xml
./Locale/Data/ny.xml
./Locale/Data/fr_LU.xml
./Locale/Data/en_MT.xml
./Locale/Data/kk_KZ.xml
./Locale/Data/as.xml
./Locale/Data/ku_SY.xml
./Locale/Data/hu.xml
./Locale/Data/uz.xml
./Locale/Data/ha_Arab_NG.xml
./Locale/Data/ro_MD.xml
./Locale/Data/ln.xml
./Locale/Data/ku_Arab_IR.xml
./Locale/Data/ky.xml
./Locale/Data/kpe.xml
./Locale/Data/gl_ES.xml
./Locale/Data/pa_Guru_IN.xml
./Locale/Data/sr_CS.xml
./Locale/Data/ar_OM.xml
./Locale/Data/sa_IN.xml
./Locale/Data/to_TO.xml
./Locale/Data/en_ZA.xml
./Locale/Data/ga.xml
./Locale/Data/hi.xml
./Locale/Data/ln_CD.xml
./Locale/Data/el_GR.xml
./Locale/Data/syr_SY.xml
./Locale/Data/tl.xml
./Locale/Data/en_MH.xml
./Locale/Data/id.xml
./Locale/Data/en_UM.xml
./Locale/Data/fr_MC.xml
./Locale/Data/en_TT.xml
./Locale/Data/uk_UA.xml
./Locale/Data/fr_BE.xml
./Locale/Data/vi.xml
./Locale/Data/nn.xml
./Locale/Data/sl_SI.xml
./Locale/Data/st.xml
./Locale/Data/mt.xml
./Locale/Data/uz_Arab_AF.xml
./Locale/Data/en_GU.xml
./Locale/Data/uz_UZ.xml
./Locale/Data/kcg_NG.xml
./Locale/Data/en_GB.xml
./Locale/Data/zh_Hans_HK.xml
./Locale/Data/ny_MW.xml
./Locale/Data/fo_FO.xml
./Locale/Data/ka.xml
./Locale/Data/wo_SN.xml
./Locale/Data/am_ET.xml
./Locale/Data/sr_Cyrl_YU.xml
./Locale/Data/sl.xml
./Locale/Data/et.xml
./Locale/Data/se_FI.xml
./Locale/Data/de_LU.xml
./Locale/Data/mn_Cyrl.xml
./Locale/Data/de_LI.xml
./Locale/Data/ku_Arab.xml
./Locale/Data/kw_GB.xml
./Locale/Data/so_ET.xml
./Locale/Data/ka_GE.xml
./Locale/Data/lo_LA.xml
./Locale/Data/ku_Arab_SY.xml
./Locale/Data/fr_CH.xml
./Locale/Data/sid_ET.xml
./Locale/Data/en_AS.xml
./Locale/Data/ug_CN.xml
./Locale/Data/da.xml
./Locale/Data/pa.xml
./Locale/Data/likelySubtags.xml
./Locale/Data/my_MM.xml
./Locale/Data/es_PY.xml
./Locale/Data/gsw_CH.xml
./Locale/Data/metazoneInfo.xml
./Locale/Data/ar_BH.xml
./Locale/Data/km.xml
./Locale/Data/zh_Hans_SG.xml
./Locale/Data/ro.xml
./Locale/Data/bo_CN.xml
./Locale/Data/ku_Latn.xml
./Locale/Data/pl.xml
./Locale/Data/en_NA.xml
./Locale/Data/cy_GB.xml
./Locale/Data/ar_IQ.xml
./Locale/Data/ur_PK.xml
./Locale/Data/xh.xml
./Locale/Data/nb.xml
./Locale/Data/de_AT.xml
./Locale/Data/de_BE.xml
./Locale/Data/nso_ZA.xml
./Locale/Data/zh_Hans_CN.xml
./Locale/Data/sv_SE.xml
./Locale/Data/ur_IN.xml
./Locale/Data/ss_SZ.xml
./Locale/Data/to.xml
./Locale/Data/ig.xml
./Locale/Data/kam_KE.xml
./Locale/Data/es_PE.xml
./Locale/Data/is.xml
./Locale/Data/aa_ER.xml
./Locale/Data/ig_NG.xml
./Locale/Data/byn_ER.xml
./Locale/Data/it_IT.xml
./Locale/Data/fi.xml
./Locale/Data/ar.xml
./Locale/Data/ky_KG.xml
./Locale/Data/en_PK.xml
./Locale/Data/zh_TW.xml
./Locale/Data/oc.xml
./Locale/Data/es_MX.xml
./Locale/Data/kw.xml
./Locale/Data/ko_KR.xml
./Locale/Data/byn.xml
./Locale/Data/en_ZW.xml
./Locale/Data/gsw.xml
./Locale/Data/rw.xml
./Locale/Data/ne_NP.xml
./Locale/Data/st_LS.xml
./Locale/Data/cop.xml
./Locale/Data/sr_ME.xml
./Locale/Data/ha_SD.xml
./Locale/Data/te_IN.xml
./Locale/Data/ar_MA.xml
./Locale/Data/tg_Cyrl_TJ.xml
./Locale/Data/aa_ER_SAAHO.xml
./Locale/Data/ku_Latn_TR.xml
./Locale/Data/ar_SD.xml
./Locale/Data/ti.xml
./Locale/Data/th.xml
./Locale/Data/ms_MY.xml
./Locale/Data/ii.xml
./Locale/Data/es_UY.xml
./Locale/Data/nn_NO.xml
./Locale/Data/sh_YU.xml
./Locale/Data/az_Latn.xml
./Locale/Data/en_SG.xml
./Locale/Data/ms_BN.xml
./Locale/Data/sw.xml
./Locale/Data/sr_Latn_RS.xml
./Locale/Data/sw_KE.xml
./Locale/Data/sr_Latn_BA.xml
./Locale/Data/iw.xml
./Locale/Data/fil.xml
./Locale/Data/ru.xml
./Locale/Data/aa.xml
./Locale/Data/ru_UA.xml
./Locale/Data/hr_HR.xml
./Locale/Data/trv.xml
./Locale/Data/az_Latn_AZ.xml
./Locale/Data/tr_TR.xml
./Locale/Data/de.xml
./Locale/Data/en_US_POSIX.xml
./Locale/Data/en_NZ.xml
./Locale/Data/oc_FR.xml
./Locale/Data/gez.xml
./Locale/Data/gv.xml
./Locale/Data/eo.xml
./Locale/Data/postalCodeData.xml
./Locale/Data/zh_Hant_HK.xml
./Locale/Data/gu_IN.xml
./Locale/Data/es_US.xml
./Locale/Data/ee.xml
./Locale/Data/gaa_GH.xml
./Locale/Data/tig.xml
./Locale/Data/af_NA.xml
./Locale/Data/telephoneCodeData.xml
./Locale/Data/mr.xml
./Locale/Data/en_BE.xml
./Locale/Data/en_IN.xml
./Locale/Data/pa_Guru.xml
./Locale/Data/fi_FI.xml
./Locale/Data/ha_Latn_NE.xml
./Locale/Data/tn.xml
./Locale/Data/fr_SN.xml
./Locale/Data/hi_IN.xml
./Locale/Data/as_IN.xml
./Locale/Data/kcg.xml
./Locale/Data/ro_RO.xml
./Locale/Data/or.xml
./Locale/Data/ar_KW.xml
./Locale/Data/bg.xml
./Locale/Data/sr.xml
./Locale/Data/ar_AE.xml
./CodeGenerator/Php/Parameter.php
./CodeGenerator/Php/Member/Container.php
./CodeGenerator/Php/Docblock/Tag/License.php
./CodeGenerator/Php/Docblock/Tag/Return.php
./CodeGenerator/Php/Docblock/Tag.php
./CodeGenerator/Php/Parameter/DefaultValue.php
./CodeGenerator/Exception.php
./Crypt.php
./Service/Amazon/Exception.php
./Service/ReCaptcha/Exception.php
./Service/ReCaptcha/MailHide/Exception.php
./Service/ReCaptcha/MailHide.php
./Service/ReCaptcha/Response.php
./Service/SlideShare/SlideShow.php
./Service/SlideShare/Exception.php
./Service/Twitter.php
./Feed/Builder/Header/Itunes.php
./Feed/Reader/Extension/Podcast/Entry.php
./Feed/Reader/Extension/Podcast/Feed.php
./Feed/Builder.php
./View/Helper/PaginationControl.php
./Mail/Part/Interface.php
./Mail/Message/Interface.php
./Mail/Storage/Writable/Interface.php
./Text/Figlet/zend-framework.flf
./Ldap/Attribute.php
./Ldap/Dn.php
./Ldap/Ldif/Encoder.php
./Ldap/Node/RootDse/OpenLdap.php
./Ldap/Node/RootDse/ActiveDirectory.php
./Ldap/Node/RootDse/eDirectory.php
./Ldap/Node/Schema/ActiveDirectory.php
./Ldap/Node/Schema/AttributeType/OpenLdap.php
./Ldap/Node/Schema/AttributeType/ActiveDirectory.php
./Ldap/Node/Schema/AttributeType/Interface.php
./Ldap/Node/Schema/Item.php
./Ldap/Node/Schema/ObjectClass/OpenLdap.php
./Ldap/Node/Schema/ObjectClass/ActiveDirectory.php
./Ldap/Node/Schema/ObjectClass/Interface.php
./Ldap/Node/ChildrenIterator.php
./Ldap/Node/RootDse.php
./Ldap/Node/Schema.php
./Ldap/Node/Abstract.php
./Ldap/Node/Collection.php
./Ldap/Converter.php
./Ldap/Collection/Iterator/Default.php
./Ldap/Filter.php
./Ldap/Node.php
./Ldap/Filter/Not.php
./Ldap/Filter/Mask.php
./Ldap/Filter/String.php
./Ldap/Filter/Or.php
./Ldap/Filter/Exception.php
./Ldap/Filter/And.php
./Ldap/Filter/Logical.php
./Ldap/Filter/Abstract.php
./Ldap/Collection.php
./Rest/Controller.php
./Crypt/DiffieHellman.php
./Crypt/Math/BigInteger/Bcmath.php
./Crypt/Math/BigInteger/Gmp.php
./Crypt/Math/BigInteger/Exception.php
./Crypt/Math/BigInteger/Interface.php
./Crypt/Math/Exception.php
./Crypt/Math/BigInteger.php
./Crypt/Rsa.php
./Crypt/Math.php
./Crypt/Rsa/Key.php
./Crypt/Rsa/Key/Public.php
./Crypt/Rsa/Key/Private.php
./Crypt/Exception.php
./Crypt/DiffieHellman/Exception.php
./Crypt/Hmac.php
./Crypt/Hmac/Exception.php
./Application/Resource/Translate.php
./Form/Decorator/Tooltip.php
./Amf/Adobe/DbInspector.php
./Amf/Adobe/Auth.php
./Amf/Adobe/Introspector.php
./Amf/Auth/Abstract.php
./Amf/Parse/Resource/Stream.php
./Amf/Parse/Resource/MysqlResult.php
./Amf/Value/MessageBody.php
./Amf/Value/Messaging/CommandMessage.php
./Amf/Value/Messaging/ErrorMessage.php
./Test/DbStatement.php
./Test/DbAdapter.php
./Test/PHPUnit/DatabaseTestCase.php
./Test/PHPUnit/Db/Metadata/Generic.php
./Test/PHPUnit/Db/DataSet/DbTableDataSet.php
./Test/PHPUnit/Db/DataSet/DbRowset.php
./Test/PHPUnit/Db/DataSet/DbTable.php
./Test/PHPUnit/Db/DataSet/QueryTable.php
./Test/PHPUnit/Db/DataSet/QueryDataSet.php
./Test/PHPUnit/Db/Exception.php
./Test/PHPUnit/Db/Operation/DeleteAll.php
./Test/PHPUnit/Db/Operation/Truncate.php
./Test/PHPUnit/Db/Operation/Insert.php
./Test/PHPUnit/Db/SimpleTester.php
./Test/PHPUnit/Db/Connection.php
./Validate/File/Crc32.php
./Validate/Hostname/Com.php
./Loader/Exception.php
./Db/Table/Select.php
./Db/Statement/Mysqli.php
./Db/Statement/Pdo/Oci.php
./Db/Statement/Pdo/Ibm.php
./Db/Adapter/Pdo/Mssql.php
./Search/Lucene/Index/TermsStream/Interface.php
./Search/Lucene/Search/Highlighter/Interface.php
./Search/Lucene/Search/Highlighter/Default.php
./Search/Lucene/Search/Query/Preprocessing.php
./Search/Lucene/Search/Query/Preprocessing/Term.php
./Search/Lucene/Search/Query/Preprocessing/Phrase.php
./Search/Lucene/Search/Query/Preprocessing/Fuzzy.php
./Search/Lucene/MultiSearcher.php
./Search/Lucene/TermStreamsPriorityQueue.php
./Soap/Wsdl/Strategy/ArrayOfTypeComplex.php
./Soap/Wsdl/Strategy/Composite.php
./Soap/Wsdl/Strategy/AnyType.php
./Soap/Wsdl/Strategy/Interface.php
./Soap/Wsdl/Exception.php
./Log/Writer/Null.php
./Log/Writer/Mock.php
./Log/Writer/Abstract.php
./InfoCard/Xml/Security.php
./Cache/Backend/ZendServer/ShMem.php
./Cache/Backend/ZendServer/Disk.php
./Filter/Callback.php
./Filter/Word/Separator/Abstract.php
./Filter/Word/SeparatorToDash.php
./Filter/Word/SeparatorToSeparator.php
./Filter/Word/UnderscoreToDash.php
./Filter/Word/DashToUnderscore.php
./ProgressBar/Adapter/Console.php
./Tool/Framework/Metadata/Basic.php
./Tool/Framework/Action/Interface.php
./Tool/Framework/System/Action/Create.php
./Tool/Framework/Provider/Signature.php
./Tool/Framework/Provider/Exception.php
./Tool/Framework/Exception.php
./Tool/Framework/Client/Request.php
./Tool/Framework/Client/Config.php
./Tool/Framework/Client/Exception.php
./Tool/Project/Context/Filesystem/Directory.php
./Tool/Project/Context/Filesystem/Abstract.php
./Tool/Project/Context/System/ProjectProvidersDirectory.php
./Tool/Project/Context/System/ProjectDirectory.php
./Tool/Project/Context/Zf/TestLibraryFile.php
./Tool/Project/Context/Zf/LayoutsDirectory.php
./Tool/Project/Context/Zf/TestApplicationControllerDirectory.php
./Tool/Project/Context/Zf/ApplicationDirectory.php
./Tool/Project/Context/Zf/LibraryDirectory.php
./Tool/Project/Context/Zf/DataDirectory.php
./Tool/Project/Context/Zf/LogsDirectory.php
./Tool/Project/Context/Zf/CacheDirectory.php
./Tool/Project/Context/Zf/ActionMethod.php
./Tool/Project/Context/Zf/SearchIndexesDirectory.php
./Tool/Project/Context/Zf/ModelFile.php
./Tool/Project/Context/Zf/ZfStandardLibraryDirectory.php
./Tool/Project/Context/Zf/ViewFiltersDirectory.php
./Tool/Project/Context/Content/Engine.php
./Tool/Project/Context/Content/Engine/Phtml.php
./Tool/Project/Context/Content/Engine/CodeGenerator.php
./Tool/Project/Provider/Manifest.php
./Tool/Project/Provider/Project.php
./Tool/Project/Provider/Form.php
./Tool/Project/Profile.php
./Tool/Project/Profile/FileParser/Xml.php
./Tool/Project/Profile/FileParser/Interface.php
./Tool/Project/Profile/Resource.php
./Tool/Project/Profile/Iterator/EnabledResourceFilter.php
./Tool/Project/Profile/Resource/Container.php
./Tool/Project/Profile/Resource/SearchConstraints.php
./Translate/Adapter.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-10-17T12:28:46.000+0000</p> 
        <div class="body">
            <p>I checked complete actual trunk. There were only 2 files which did not conform line endings. And only one was a framework file.</p>

<p>I can not confirm that those 200 files you noted have a non-unix line ending.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-10-17T12:39:20.000+0000</p> 
        <div class="body">
            <p>Erased set components.</p>

<p>No single file of these components has a false EOL.
And non, wether the set nor the not set components have the eol style set.</p>

<p>I still don't close this issue, so Matthew can deside if a new svn keyword should be added to all files.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Anthon Pang, VIP Software Technologies Inc. (vipsoft) on 2009-10-17T15:03:27.000+0000</p> 
        <div class="body">
            <p>Maybe the problem is on the server that packages releases.</p>

<p>For reference: I downloaded ZendFramework-1.9.4-minimal.zip.  My previous list included files with "No newline at end of file"; however, there are files with non-Unix line endings. (I can open it with VIM and see the ^M, or use "od -c" to see the \r \n.)</p>

<p>Specifically:</p>

<p>Amf/Adobe/Auth.php
Amf/Adobe/DbInspector.php
Amf/Adobe/Introspector.php
Amf/Auth/Abstract.php
Amf/Parse/Resource/MysqlResult.php
Amf/Parse/Resource/Stream.php
Amf/Value/MessageBody.php
Amf/Value/Messaging/CommandMessage.ph
Amf/Value/Messaging/ErrorMessage.php
Cache/Backend/ZendServer/Disk.php
Cache/Backend/ZendServer/ShMem.php
Locale/*
Search/Lucene/Index/TermsStream/Interface.php
Search/Lucene/MultiSearcher.php
Search/Lucene/Search/Highlighter/Default.php
Search/Lucene/Search/Highlighter/Interface.php
Search/Lucene/Search/Query/Preprocessing/Fuzzy.php
Search/Lucene/Search/Query/Preprocessing/Phrase.php
Search/Lucene/Search/Query/Preprocessing/Term.php
Search/Lucene/Search/Query/Preprocessing.php
Search/Lucene/TermStreamsPriorityQueue.php
Service/Twitter.php
Text/Figlet/zend-framework.flf</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-10-18T01:38:31.000+0000</p> 
        <div class="body">
            <p>There is no standard which defines the there must be a newline at the end of a file. This is no failure.</p>

<p>Regarding Unix EOL... I checked the complete trunk and there is no non-Unix EOL within the library as checked with r18639.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-10-18T01:42:32.000+0000</p> 
        <div class="body">
            <p>Additionally note that /r/n is allowed when it's not used as EOL...</p>

<p>For example there are regex'es within the ZF library which ARE using /r/n.
This is allowed behaviour.</p>

<p>I used the AnyEdit tools within Eclipse (don't ask how much memory and time it used to work ;-) ) to convert all EOL's within the library and as noted before only 2 files were found at all before I did this check.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Anthon Pang, VIP Software Technologies Inc. (vipsoft) on 2009-11-05T23:48:19.000+0000</p> 
        <div class="body">
            <p>The problem is in the packaging.  Files where the most recent commit was to fix line endings, are not being packaged up.  Instead, outdated files are included in ZendFramework-1.9.4-minimal.zip.</p>

<p>For example, the 1.9.5 .zip file contains r16971 of Zend/Amf/Adobe/Auth.php, but svn shows r17420 was commited 2009-08-07.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-11-06T06:05:49.000+0000</p> 
        <div class="body">
            <p>@Anthon Please note that latest revisions in trunk do not necessarily reflect the latest revisions in the release branch. Changesets that only affect line endings are not always merged into release branches.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Anthon Pang, VIP Software Technologies Inc. (vipsoft) on 2009-11-07T16:08:48.000+0000</p> 
        <div class="body">
            <p>Thanks. I hadn't looked at the release branch.</p>

<p>Since this is fixed in trunk, I suppose this issue can now be closed, unless you want to run "svn propset svn:eol-style native" on text files.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-18T13:18:19.000+0000</p> 
        <div class="body">
            <p>Closing as fixed for the next minor release as mentioned.</p>

        </div>
    </div>
    </div>

