<h2>ZF-8144: Add support for categories in Zend_Feed_Reader</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2009-10-24T21:22:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-03T11:26:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Bradley Holt (bradley.holt)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Reader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>A getCategories method on Zend_Feed_Reader_FeedInterface and Zend_Feed_Reader_EntryInterface would be very useful. A cursory glance shows that both Atom and RSS support categories.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-11-21T09:21:07.000+0000</p> 
        <div class="body">
            <p>Support for both Feed and Entry level categories (via getCategories()) added to trunk. Will be formally released in 1.10 since it's new to the API.</p>

<p>Someone owes me a beer ;).</p>

        </div>
    </div>
    </div>

