<h2>ZF-808: Zend_Auth - Authentication Failure Messages</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-01-26T08:56:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Auth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Because a single authentication attempt may possibly result in multiple reasons why the attempt failed, the authentication attempt should make available these messages. In the context of the current Zend_Auth_Token_Interface, the {{getMessage()}} method could be changed to {{getMessages()}}, where the method returns an array of string messages that explain why the authentication failed. For example, an authentication attempt may result in an array of messages such as "{{user may only log in between 8:00am and 5:00pm}}" and "{{user may not log in from 10.0.0.1}}". This change would support receiving failure messages from validator chains, as from Zend_Validate, currently in the incubator.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-02-14T16:33:15.000+0000</p> 
        <div class="body">
            <p>Resolved with SVN <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=3412">r3412</a>.</p>

        </div>
    </div>
    </div>

