<h2>ZF-8773: Zend_Navigation: Rendering &quot;sub-navigation&quot; does not work as expected</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-10T21:34:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-01-22T10:40:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9524">ZF-9524</a></li>
            <li><a href="/issues/browse/ZF-9379">ZF-9379</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12596/ZF-Nav-Ex.zip">ZF-Nav-Ex.zip</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Bear with me as I try to convey what I am trying to do with what is actually happening:</p>

<p>Using Zend_Navigation, I want to render a "main navigation" as tabs across the top of my pages. Then, depending on which "tab" is selected, I want to display - if they exist as  in the configuration - "sub navigation" items to the left of the page's content. Conversely, if I am on a tab that does not have any child pages - via  in the configuration - I do not want any "sub navigation" links to display.</p>

<p>What actually happens, depending on the way that I call the navigation rendering is that I will 1) get nothing in the sub  navigation, 2) get every link in the sub navigation, regardless of whom its parent is (versus which tab is selected), or 3) I will only get the immediate child link instead of children, grandchildren, etc.</p>

<p>I have pieced together a very simple configuration file, two controllers, a layout, and the respective view scripts necessary to display what I am trying to describe. I have created the three cases that I described above using Zend_Navigation, and then I have created what I am actually trying to do (manually) in each page.</p>

<p>Either Zend_Navigation is not working correctly, cannot support such an obvious use-case, or I am not understanding how to set it up to do what I am trying to do. Whichever the case may be, I would greatly appreciate any and all assistance that you can provide me on this. I have already waste half of a day trying to figure this out, and frankly, I am at my wit's end with this component. I really would love to take advantage of Zend_Navigation (and its ACL integration).</p>

<p>Thank you.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

