<h2>ZF-8625: AutoComplete API changed, view helper does not work any more</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-24T01:43:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-29T03:02:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8985">ZF-8985</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12541/patch.diff">patch.diff</a></li>
            <li><a href="/issues/secure/attachment/12540/patch.diff">patch.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>First of all, autocomplete is a feature that has been switched from JQuery Core to a plugin.
So if you don't download the plugin, the autocomplete() view helper wont work at all.</p>

<p>Second : it looks like the API of autocomplete has changed. The 'url' parameter has become a real parameter. The actual view helper does not take care of the new parameters and API changes, producing a wrong html code which cant be used with autocomplete anymore.</p>

<p>The patch is attached</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-12-24T01:44:01.000+0000</p> 
        <div class="body">
            <p>Attached the original patch</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by julien PAULI (doctorrock83) on 2009-12-24T02:29:01.000+0000</p> 
        <div class="body">
            <p>Other patch with less bug and less parse errors :p</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2010-01-29T03:00:54.000+0000</p> 
        <div class="body">
            <p>AutoComplete is re-introduced with jQuery UI 1.8 - I change the API of the helper to comply with that one.</p>

        </div>
    </div>
    </div>

