<h2>ZF-825: Zend_Db_Adapter_Pdo_Mysql not compatible with Zend_Db_Adapter_Abstract</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-01-30T07:11:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Maier (daimaju)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm getting the following errors when using the Pdo-Adapter for Mysql (Revision 3091) :</p>

<p>Fatal error: Declaration of Zend_Db_Adapter_Pdo_Mysql::describeTable() must be compatible with that of Zend_Db_Adapter_Abstract::describeTable()</p>

<p>and after adding the missing paramter ($schemeName = null) :</p>

<p>Fatal error: Class Zend_Db_Adapter_Pdo_Mysql contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Zend_Db_Adapter_Abstract::getQuoteIdentifier)</p>

<p>Edit: The changes to Zend_DB_Adapter_Abstract have been made in Revision 3085. I just checked and all Adapters except for Db2 have the same problem</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-01-30T15:51:41.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3093.</p>

        </div>
    </div>
    </div>

