<h2>ZF-8415: Zend_Filter_PregReplace is not in the docs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs: Task </dd>

    <dt>Created:</dt>
    <dd>2009-11-28T18:27:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-03T13:03:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Need to document Zend_Filter_PregReplace.  It is in core (see ZF-1213) but not documented.</p>

<p>[<a href="http://framework.zend.com/svn/framework/standard/trunk/library/Zend/Filter/PregReplace.php">http://framework.zend.com/svn/framework/…</a>]</p>

<ul><li>[<a href="http://framework.zend.com/manual/en/zend.filter.html">http://framework.zend.com/manual/en/…</a>]</li>
<li>[<a href="http://framework.zend.com/manual/en/zend.filter.set.html">http://framework.zend.com/manual/en/…</a>]</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-03T13:03:14.000+0000</p> 
        <div class="body">
            <p>Added with r19380</p>

        </div>
    </div>
    </div>

