<h2>ZF-8172: Exposing more than object Key in S3 getObjectsByBucket</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-10-28T11:25:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Andy Thompson (at465)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Could Zend_Service_Amazon_S3::getObjectsByBucket() have an additional parameter to make it return the other parameters from GET Bucket? or as another function? These currently are retrieved as part of the API call and discarded in favour of just returning the Key for each file.</p>

<p>Without this functionality, there is no way, other than to repeatedly call getInfo with the results from the function (which is extremely wasteful in time and cost), to get the LastModified/ETag/Size etc of the files in a bucket, something that folder sync applications would need to do regularly.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:16.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

