<h2>ZF-8508: Wrong documentation in &quot;63.2.7. From Request to Response&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-12-09T08:00:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-12T19:19:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Lars Strojny (lars)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_XmlRpc_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think that the text on your site at <a href="http://framework.zend.com/manual/en/zend.xmlrpc.client.html">http://framework.zend.com/manual/en/…</a> at 
"63.2.7. From Request to Response" contains an error.</p>

<p>I think it should be:</p>

<p>// $client-&gt;getLastRequest() returns instanceof Zend_XmlRpc_Request
  // $client-&gt;getLastResponse() returns instanceof Zend_XmlRpc_Response</p>

<p>and not:</p>

<p>// $server-&gt;getLastRequest() returns instanceof Zend_XmlRpc_Request
  // $server-&gt;getLastResponse() returns instanceof Zend_XmlRpc_Response</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Lars Strojny (lars) on 2009-12-12T19:19:14.000+0000</p> 
        <div class="body">
            <p>Fixed in r19604. Thanks for the bugreport.</p>

        </div>
    </div>
    </div>

