<h2>ZF-8812: Zend_Controller_Router_Route_Chain fails with some combinations of routes in the chain</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-13T19:54:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-20T11:46:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10536">ZF-10536</a></li>
            <li><a href="/issues/browse/ZF-9030">ZF-9030</a></li>
            <li><a href="/issues/browse/ZF-7368">ZF-7368</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13335/Chain.php.diff">Chain.php.diff</a></li>
            <li><a href="/issues/secure/attachment/13336/ChainTest.php.patch">ChainTest.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Here are the pieces of relevant code and test cases:</p>

<pre class="highlight"><code>
$front = Zend_Controller_Front::getInstance();
$router = $front-&gt;getRouter();
$request = new Zend_Controller_Request_Http();
$front-&gt;setRequest($request);

$router-&gt;removeDefaultRoutes();
$languageRoute = new Zend_Controller_Router_Route_Regex('([a-z]{2})?', array('language' =&gt; 'xx'), array(1 =&gt; 'language'), '%s');
$moduleRoute = new Zend_Controller_Router_Route_Module(array(), Zend_Controller_Front::getInstance()-&gt;getDispatcher(), $request);
$defaultRoute = $languageRoute-&gt;chain($moduleRoute);
$router-&gt;addRoute('default', $defaultRoute);
</code></pre>

<p>Inside the {{match()}} method of Zend_Controller_Router_Route_Chain, if the request URI is {{'/en/'}} or {{'/en'}}, then {{$subPath}} will become {{bool(false)}} after the {{match()}} call to the regex route. Therefore, not only will the module route never get picked up, but the match() method of the chain route will return {{bool(false)}}.</p>

<p>I was able to patch this by changing:</p>

<pre class="highlight"><code>
if ($key &gt; 0 &amp;&amp; $matchedPath !== null) {
</code></pre>

<p>to</p>

<pre class="highlight"><code>
if ($key &gt; 0 &amp;&amp; $matchedPath !== null &amp;&amp; $subPath !== '' &amp;&amp; $subPath !== false) {
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ziad (ziadx) on 2010-01-13T19:56:17.000+0000</p> 
        <div class="body">
            <p>formatting</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-01-14T04:40:35.000+0000</p> 
        <div class="body">
            <p>Assigning to Ben.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by David Nussio (david) on 2010-01-19T00:17:28.000+0000</p> 
        <div class="body">
            <p>I'm using Ziad's patch that solve similar case.</p>

<p>resources.router.routes.defaultmodule.type = Zend_Controller_Router_Route_Module
resources.router.routes.defaultmodule.defaults.module = "default"
resources.router.routes.defaultmodule.defaults.controller = "index"
resources.router.routes.defaultmodule.defaults.action = "index"</p>

<p>resources.router.routes.language.type = Zend_Controller_Router_Route
resources.router.routes.language.route = ":language"
resources.router.routes.language.reqs.language = "^(it|fr|en|de)$"
resources.router.routes.language.defaults.language = "en"</p>

<p>resources.router.routes.default.type = Zend_Controller_Router_Route_Chain
resources.router.routes.default.chain = "language, defaultmodule"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by David Nussio (david) on 2010-03-03T02:44:31.000+0000</p> 
        <div class="body">
            <p>Hello, could you change the priority of this task?
I have to patch every new release to do work route chain defaults value.
Thanks, great work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kevin Horst (kevinh) on 2010-07-03T06:51:37.000+0000</p> 
        <div class="body">
            <p>also tested with 1.10.1</p>

<p>resources.frontcontroller.defaultModule               = "default"
resources.frontcontroller.controllerDirectory         = APPLICATION_PATH "/controllers"
resources.frontcontroller.moduleDirectory             = APPLICATION_PATH "/modules"</p>

<p>resources.router.routes.defaultRoute.type             = Zend_Controller_Router_Route_Module"
resources.router.routes.defaultRoute.abstract         = "On"
resources.router.routes.defaultRoute.route            = ":module"
resources.router.routes.defaultRoute.defaults.module  = "default"</p>

<p>resources.router.routes.language.type                 = "Zend_Controller_Router_Route"
resources.router.routes.language.route                = ":lang"
resources.router.routes.language.reqs.lang            = "^(en|de)$"
resources.router.routes.language.defaults.lang        = "en"</p>

<p>resources.router.routes.default.type                  = "Zend_Controller_Router_Route_Chain"
resources.router.routes.default.chain                 = "language, defaultRoute"</p>

<p>test url -&gt; request-object</p>

<p>/                     -&gt; /en/default/index/index
/en                   -&gt; /en/default/index/index
/de                   -&gt; /de/default/index/index
/en/admin/index/index -&gt; /en/admin/index/index
/en/index             -&gt; /en/default/index/index</p>

<p>works all great. i think, this is a blocker.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2010-10-09T06:13:11.000+0000</p> 
        <div class="body">
            <p>Patch and unit test added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kim Blomqvist (kblomqvist) on 2010-10-16T02:23:16.000+0000</p> 
        <div class="body">
            <p>To get unit test work, patch from ZF-10536 should be added first.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-10-20T11:46:11.000+0000</p> 
        <div class="body">
            <p>Applied to both trunk and 1.11 release branch -- thanks!</p>

        </div>
    </div>
    </div>

