<h2>ZF-8947: Zend DB Select Limit Not Executing Properly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-26T20:27:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-30T12:54:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Select</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9796">ZF-9796</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you specify a DB table then use select statement with an order and limit clause, the output for the limit range is wrong.</p>

<p>$nUserId = 123;
$select = $this-&gt;_table-&gt;select();
$select-&gt;where('user_id = ?', $nUserId)
               -&gt;order('createddate DESC')
               -&gt;limit(0, 200);</p>

<p>print $select;</p>

<p>// SELECT <code>myRecords</code>.* FROM <code>myRecords</code> WHERE (user_id = '123') 
// ORDER BY <code>createddate</code> DESC LIMIT 2147483647 OFFSET 2</p>

<p>The limit is supposed to be 0 not 2147483647</p>

<p>Regards,
Cliburn M. Solano</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dan Johansson (datasage) on 2011-12-30T20:33:33.000+0000</p> 
        <div class="body">
            <p>I just ran into this bug too, in my quick test, order does not seem to matter. It seems to be related to building a query off of Zend_Db_Table though. I am using zf 1.11.11.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dan Johansson (datasage) on 2011-12-30T20:34:48.000+0000</p> 
        <div class="body">
            <p>It also only occurs if the first argument is 0. Set the argument to 1 and it behaves as expected.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dan Johansson (datasage) on 2011-12-30T20:37:14.000+0000</p> 
        <div class="body">
            <p>Maybe i should reread the documentation first. The argument order is opposite of what is expected in mysql. This is not a bug.</p>

        </div>
    </div>
    </div>

