<h2>ZF-8593: Wrong link href in GData provisioning</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2009-12-21T05:54:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-21T14:07:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.7 (11/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Josh Ribakoff (josh.ribakoff@gmail.com)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.gdata.gapps.html">http://framework.zend.com/manual/en/…</a></p>

<p>On this page ^^^ the link that says "Provisioning API V2.0 Reference." has the wrong HREF</p>

<p>Actual
<a href="http://code.google.com/apis/calendar/overview.html">http://code.google.com/apis/calendar/overview.html</a>
Expected
<a href="http://code.google.com/apis/apps/gdata_provisioning_api_v2.0_reference.html">http://code.google.com/apis/apps/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-12-21T14:03:46.000+0000</p> 
        <div class="body">
            <p>Fixed for 1.10.</p>

<p>{quote}
commit 581d31ee7307797d60a40567fa9ee4bc323d152e
Author: tjohns &lt;tjohns@44c647ce-9c0f-0410-b52a-842ac1e357ba&gt;
Date:   Mon Dec 21 21:52:54 2009 +0000</p>

<pre><code>ZF-8593: Fix incorrect link to Google Apps Provisioning API Reference in Zend_Gdata_Gapps user manual.

Old link: &lt;a rel="nofollow" href="http://code.google.com/apis/calendar/overview.html"&gt;http://code.google.com/apis/calendar/overview.html&lt;/a&gt;
New link: &lt;a rel="nofollow" href="http://code.google.com/apis/apps/gdata_provisioning_api_v2.0_reference.html"&gt;http://code.google.com/apis/apps/&amp;hellip;&lt;/a&gt;

git-svn-id: &lt;a rel="nofollow" href="http://framework.zend.com/svn/framework/standard/trunk@19867"&gt;http://framework.zend.com/svn/framework/&amp;hellip;&lt;/a&gt; 44c647ce-9c0f-0410-b52a-842ac1e357ba
</code></pre>

<p>{quote}</p>

<p>{quote}
commit 9c6e1cb00a6a931a8e919e209693c0dcff275162
Author: tjohns &lt;tjohns@44c647ce-9c0f-0410-b52a-842ac1e357ba&gt;
Date:   Mon Dec 21 22:01:13 2009 +0000</p>

<pre><code>Merge r19867 from trunk to release-1.10.

ZF-8593: Fix incorrect link to Google Apps Provisioning API Reference in Zend_Gdata_Gapps user manual.

Old link: &lt;a rel="nofollow" href="http://code.google.com/apis/calendar/overview.html"&gt;http://code.google.com/apis/calendar/overview.html&lt;/a&gt;
New link: &lt;a rel="nofollow" href="http://code.google.com/apis/apps/gdata_provisioning_api_v2.0_reference.html"&gt;http://code.google.com/apis/apps/&amp;hellip;&lt;/a&gt;

git-svn-id: &lt;a rel="nofollow" href="http://framework.zend.com/svn/framework/standard/branches/release-1.10@19869"&gt;http://framework.zend.com/svn/framework/&amp;hellip;&lt;/a&gt; 44c647ce-9c0f-0410-b52a-842ac1e357ba
</code></pre>

<p>{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2009-12-21T14:07:27.000+0000</p> 
        <div class="body">
            <p>Since this is a simple change, I've merged it back into release-1.9.
This should be fixed in 1.9.7.</p>

<p>{quote}
commit 19f4dd3ffc2ad22ada7d955839b5a088aedf131a
Author: tjohns &lt;tjohns@44c647ce-9c0f-0410-b52a-842ac1e357ba&gt;
Date:   Mon Dec 21 22:06:13 2009 +0000</p>

<pre><code>Merge r19867 from trunk to release-1.9.

ZF-8593: Fix incorrect link to Google Apps Provisioning API Reference in Zend_Gdata_Gapps user manual.

Old link: &lt;a rel="nofollow" href="http://code.google.com/apis/calendar/overview.html"&gt;http://code.google.com/apis/calendar/overview.html&lt;/a&gt;
New link: &lt;a rel="nofollow" href="http://code.google.com/apis/apps/gdata_provisioning_api_v2.0_reference.html"&gt;http://code.google.com/apis/apps/&amp;hellip;&lt;/a&gt;

git-svn-id: &lt;a rel="nofollow" href="http://framework.zend.com/svn/framework/standard/branches/release-1.9@19871"&gt;http://framework.zend.com/svn/framework/&amp;hellip;&lt;/a&gt; 44c647ce-9c0f-0410-b52a-842ac1e357ba
</code></pre>

<p>{quote}</p>

        </div>
    </div>
    </div>

