<h2>ZF-8448: Translate_Adapter throws warning if $messageId is object</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-02T14:24:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-18T05:44:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michal Vrchota (techi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Sometimes object is passed to the $messageId (i.e. via Zend_Form instance of class with toString() magic method is passed as value)
however that $messageId is not translated and gives</p>

<p>PHP Warning:  Illegal offset type in isset or empty in /home/www/app/library/Zend/Translate/Adapter.php on line 682</p>

<p>This should fix the problem
 if (is_object($messageId))
     $messageId = (string)$messageId;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-02T14:49:29.000+0000</p> 
        <div class="body">
            <p>Zend_Translate MUST have an string as key.
Other types are not allowed and should not be given.</p>

<p>Using toString implicitly by isTranslated() would add problems.
In my opinion it's better to have this warning to force the user to prevent those problems.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Vrchota (techi) on 2009-12-02T18:27:19.000+0000</p> 
        <div class="body">
            <p>The thing is, that it is very difficult to track down the source code - where the object was passed. So I suggest to throw an exception instead.</p>

<p>IMHO 1 exception (which can be easily tracked) is better then thousands of pointless warnings in php error log</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-03T03:22:07.000+0000</p> 
        <div class="body">
            <p>I agree on the notice being suppressed.
But I do not agree on throwing an exception while translating.</p>

<p>Calling "translate()" it is NOT ALLOWED to throw an exception in any case.
The return value must be equal with the input when no translation can be done.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-12-03T03:58:17.000+0000</p> 
        <div class="body">
            <p>Notices are no longer given with r19367.
Exceptions will not be integrated for translation.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Renat Ismagilov (rismagi) on 2010-01-18T04:56:39.000+0000</p> 
        <div class="body">
            <p>Translate_Adapter still throws warnings by isTranslated method:</p>

<pre><code>    if (isset($this-&gt;_translate[$locale][$messageId]) === true) {
        // return original translation
        return true;
    }
</code></pre>

<p>should be fixed also.</p>

        </div>
    </div>
    </div>

