<h2>ZF-8330: Zend_Feed_Reader::findFeedLinks() doesn't handle relative feed URIs</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-18T13:25:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-20T12:01:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.6 (24/Nov/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexandre Gomes Gaigalas (alganet)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Reader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12407/FeedSet.patch">FeedSet.patch</a></li>
            <li><a href="/issues/secure/attachment/12408/ReaderTest.patch">ReaderTest.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Feed_Reader::findFeedLinks() doesn't handle relative feed URIs:</p>

<p>Code:</p>

<pre class="highlight"><code>
print_r(Zend_Feed_Reader::findFeedLinks('<a href="http://meiobit.com">http://meiobit.com</a>'));
</code></pre>

<p>Output:</p>

<pre class="highlight"><code>
stdClass Object
(
    [rss] =&gt; /rss.xml
)
</code></pre>

<p>Expected:</p>

<pre class="highlight"><code>
stdClass Object
(
    [rss] =&gt; <a href="http://meiobit.com/rss.xml">http://meiobit.com/rss.xml</a>
)
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-11-20T09:14:27.000+0000</p> 
        <div class="body">
            <p>Fixed in r19103.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Sorgalla (jsorgalla) on 2009-11-20T11:46:09.000+0000</p> 
        <div class="body">
            <p>This will still fail on uri's with paths, ie.:</p>

<p><a href="http://example.com/sub">http://example.com/sub</a>:
</p>

<p>or</p>

<p><a href="http://example.com/sub">http://example.com/sub</a>:
</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jan Sorgalla (jsorgalla) on 2009-11-20T11:47:21.000+0000</p> 
        <div class="body">
            <p>Attached patches fixing the uri with paths (reason for reopening the issue)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2009-11-20T12:01:10.000+0000</p> 
        <div class="body">
            <p>Patches applied in r19136.</p>

<p>On a separate note - very good catch!</p>

        </div>
    </div>
    </div>

