<h2>ZF-8031: Provide a static method for setting default filter that are always applied when Zend_Form is used</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-10-07T14:16:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T20:53:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Janimatti Ellonen (jme)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Sometimes you may want to use certain filters as defaults in each instantiated Zend_Form object. One example could be the StringTrim filter that helps you get rid of any accidental white spaces submitted by the user.</p>

<p>You could accomplish this by creating your own form class (that extends Zend_Form) and adding some default filters in the constructor. This approach forces you to use your custom class, which may not be waht you really want.</p>

<p>Zend_Form::setDefaultFilters(array)
Zend_Form::addDefaulFilter(..)
etc...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Mauger (bittarman) on 2009-10-07T14:20:49.000+0000</p> 
        <div class="body">
            <p>I like the idea, but I wouldn't like to see it as a static method, but instead a method which can be called prior to adding elements to a form, so it will automagically add these filters when addElement is subsiquently called.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Janimatti Ellonen (jme) on 2009-10-07T14:25:40.000+0000</p> 
        <div class="body">
            <p>But the you would still have to call that method manually, each time you are using Zend_Form, right?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2012-11-20T20:53:39.000+0000</p> 
        <div class="body">
            <p>Bulk change of all issues last updated before 1st January 2010 as "Won't Fix".</p>

<p>Feel free to re-open and provide a patch if you want to fix this issue.</p>

        </div>
    </div>
    </div>

