<h2>ZF-8740: Zend_Search_Lucene_Document_Html::getLinks() should parse AREA tags</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-07T11:05:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-19T00:27:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.4 (28/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                John Nunez (jnuneznj)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12592/Html.patch">Html.patch</a></li>
            <li><a href="/issues/secure/attachment/12591/Html.php">Html.php</a></li>
            <li><a href="/issues/secure/attachment/12655/ZF-8740.patch">ZF-8740.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Search_Lucene_Document_Html will not list links from image maps.  To resolve we just need to add code to pull in all urls from the AREA tag's href. I have a fix ready.  Where should I post it?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by John Nunez (jnuneznj) on 2010-01-07T11:09:03.000+0000</p> 
        <div class="body">
            <p>Here is the file which contains the fix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christopher Thomas (cwt137) on 2010-01-08T06:44:12.000+0000</p> 
        <div class="body">
            <p>It is better to submit a patch than the whole file. It is hard to see what has changed if you provide the whole file. If you don't know how to make a patch, it is easy. Just run this command at the root of your svn repo: "svn diff &gt; file_name.patch" (without quotes).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christopher Thomas (cwt137) on 2010-01-21T06:13:31.000+0000</p> 
        <div class="body">
            <p>Hello, I've added some unit tests to your patch. Please see attached file.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2010-04-18T12:02:39.000+0000</p> 
        <div class="body">
            <p>Fixed.</p>

<p>Nice patch, Christopher!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2010-04-18T12:08:25.000+0000</p> 
        <div class="body">
            <p>Wrong issue was resolved :)
So, I've reopened it</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2010-04-19T00:27:39.000+0000</p> 
        <div class="body">
            <p>Fixed in the trunk and in the release branch.</p>

<p>Must say again, good patch, John and Christopher! :)</p>

        </div>
    </div>
    </div>

