<h2>ZF-8475: Dojo form button can't submit a value</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-04T14:21:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-12-05T07:06:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                boris (jer)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5056">ZF-5056</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>this bug is related to this one <a href="http://framework.zend.com/issues/browse/ZF-5056">http://framework.zend.com/issues/browse/ZF-5056</a>.
But for Zend_Form there is a workaround - just to use Zend_Form_Element_Submit instead of Zend_Form_Element_Button, for Zend_Dojo_Form_Element_Button there is no alternative</p>

<pre class="highlight"><code>
$form = new Zend_Dojo_Form()
$form-&gt;setMethod('post')
$button = new Zend_Dojo_Form_Button(
    'Save',
    array(              
        'label'     =&gt; 'Save',
        'id'        =&gt; 'id',
        'type'      =&gt; 'Submit',
        'value'     =&gt; 'Save',
    )
);
$form-&gt;addElement($button);
$form-&gt;populate($_POST);

$form-&gt;getElement('Save')-&gt;isChecked();
</code></pre>

<p>isChecked() will never return true (tested FF, IE8, Chrome, Safari, Opera), because value attribute of button is always empty due to the way Zend_Form_Decorator_ViewHelper works (it just never gives button a value attribute!)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-12-05T07:05:47.000+0000</p> 
        <div class="body">
            <p>Use Zend_Dojo_Form_SubmitButton if you need a submittable dijit.form.Button, or provide an onclick callback that submits the button:
```
$button = new Zend_Dojo_Form_Button(
    'Save',
    array(<br />
        'label'     =&gt; 'Save',
        'id'        =&gt; 'id',
        'type'      =&gt; 'Submit',
        'value'     =&gt; 'Save',
                'onclick'       =&gt; 'dijit.byId("formid").submit()',
    )
);
{note}</p>

        </div>
    </div>
    </div>

