<h2>ZF-8873: improvement in classes Zend_Mail_Transport</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-01-19T10:08:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-06T02:24:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12644/Zend_Mail_Transport.patch">Zend_Mail_Transport.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the classes Zend_Mail_Transport_Sendmail and Zend_Mail_Transport_Smtp
renamed method _sendMail() to sendMail(), compatibility keeping.</p>

<p>added Fluent Interface in Zend_Mail_Transport_Smtp::setConnection().</p>

<p>configuration made in Zend_Mail_Transport_Smtp::_sendMail() been
created a protected method responsible by configuration. called Zend_Mail_Transport_Smtp::setDefaultConnection().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-28T01:48:28.000+0000</p> 
        <div class="body">
            <p>Up priority for development-2.0</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-06-09T00:23:17.000+0000</p> 
        <div class="body">
            <p>Sorry, I have been inactive since last April.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2010-09-19T01:14:08.000+0000</p> 
        <div class="body">
            <p>Why wait for ZF2 and not the next minor release?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-12-06T02:24:17.000+0000</p> 
        <div class="body">
            <p>Resolved in ZF2</p>

        </div>
    </div>
    </div>

