<h2>ZF-8439: Lifetime expiration time of 0 should be considered as forever</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-12-02T01:24:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-01-09T20:34:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Bennewitz (private) (mabe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The function _expireTime of Zend_Cache_Backend_File should be changed, so that a lifetime of 0 is considered (like null) to last forever.</p>

<p>This is the behaviour in PHP's sessions and thus one most likely expects other modules to work as well.</p>

<p>Moreover it's not possible to set a null-value if the cache is configured via an ini file.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2009-12-19T07:39:10.000+0000</p> 
        <div class="body">
            <p>That's a common behavior of all Zend_Cache backends. So this modification changes API and breaks backward compatibility.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2012-01-09T20:34:37.000+0000</p> 
        <div class="body">
            <p>This issue can't be fixed in ZF1 because of bc.</p>

<p>It's no longer present in ZF2 because the ttl option is an integer and all adapters defines 0 as forever.
(values lower than 0 throws an InvalidArgumentException)</p>

        </div>
    </div>
    </div>

