<h2>ZF-8714: Undefined variable: testModelResource /Zend/Tool/Project/Provider/Model.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-05T09:25:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-21T05:59:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Andreas Baumgart (polycaster)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There seems to be some debugging code still alive in Model.php.</p>

<p>Tested with current trunk and PHP 5.3.0.</p>

<p>Scenario, error message and stacktrace:</p>

<p>andreas@wonderlustking-2:~/Workspace/blog.andreas.polycast.de # zf create model articles
Creating a model at /Users/andreas/Documents/Workspaces/BrainStore/blog.andreas.polycast.de/application/models/Articles.php</p>

<p>Notice: Undefined variable: testModelResource in /Users/andreas/Documents/Workspaces/BrainStore/ZendFramework/library/Zend/Tool/Project/Provider/Model.php on line 145</p>

<p>Call Stack:
    0.0013     797568   1. {main}() /Users/andreas/WebStack/PHP-5.3.0/bin/zf.php:0
    0.0014     797568   2. ZF::main() /Users/andreas/WebStack/PHP-5.3.0/bin/zf.php:616
    0.0049    1234208   3. ZF-&gt;run() /Users/andreas/WebStack/PHP-5.3.0/bin/zf.php:74
    0.0049    1234208   4. ZF-&gt;_runTool() /Users/andreas/WebStack/PHP-5.3.0/bin/zf.php:117
    0.0060    1355768   5. Zend_Tool_Framework_Client_Abstract-&gt;dispatch() /Users/andreas/WebStack/PHP-5.3.0/bin/zf.php:592
    0.1131    7492488   6. Zend_Tool_Framework_Client_Abstract-&gt;_handleDispatch() /Users/andreas/Documents/Workspaces/BrainStore/ZendFramework/library/Zend/Tool/Framework/Client/Abstract.php:241
    0.1131    7493088   7. Zend_Tool_Framework_Client_Abstract-&gt;_handleDispatchExecution() /Users/andreas/Documents/Workspaces/BrainStore/ZendFramework/library/Zend/Tool/Framework/Client/Abstract.php:322
    0.1131    7493528   8. call_user_func_array() /Users/andreas/Documents/Workspaces/BrainStore/ZendFramework/library/Zend/Tool/Framework/Client/Abstract.php:328
    0.1131    7493952   9. Zend_Tool_Project_Provider_Model-&gt;create() /Users/andreas/Documents/Workspaces/BrainStore/ZendFramework/library/Zend/Tool/Framework/Client/Abstract.php:0</p>

<p>Updating project profile '/Users/andreas/Documents/Workspaces/BrainStore/blog.andreas.polycast.de/.zfproject.xml'</p>

<p>Cheers!
Andreas</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-01-05T10:52:31.000+0000</p> 
        <div class="body">
            <p>Please test the version in trunk from r20089</p>

<p>Thanks!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andreas Baumgart (polycaster) on 2010-01-05T10:58:16.000+0000</p> 
        <div class="body">
            <p>Works fine now. 
Thank you!</p>

        </div>
    </div>
    </div>

