<h2>ZF-8044: Zend_date::setTime bug</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-10T08:02:23.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-15T13:29:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre><code>    Zend_Date::setOptions(array('format_type' =&gt; 'php'));

    $date = new Zend_Date();
    var_dump($date-&gt;toString("d.m.Y H:i:s"));
    $date-&gt;setTime("23:59:59");
    var_dump($date-&gt;toString("d.m.Y H:i:s"));
</code></pre>

<p>Result:
string(19) "10.10.2009 18:56:09" 
string(19) "11.10.2009 00:45:59"</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-10-15T13:29:57.000+0000</p> 
        <div class="body">
            <p>Not reproducable with actual trunk.
Probably fixed by another issue / bug fix.</p>

<p>Set as fixed with next minor release.</p>

        </div>
    </div>
    </div>

