<h2>ZF-8876: UnitTest failure on Windows</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-19T14:49:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-21T09:06:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_CodeGenerator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12646/zend_codegenerator.patch">zend_codegenerator.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <pre class="highlight"><code>
D:\Users\mabe\workspace\Zend&gt;"d:\Users\mabe\Program Files\php\php5.2.9\php.exe"
ZF-STD-TRUNK\tests\Zend\CodeGenerator\AllTests.php
PHPUnit 3.3.9 by Sebastian Bergmann.

..S......................................................... 60 / 99
..........F............................

Time: 0 seconds

There was 1 failure:

1) testPropertyMultilineValue(Zend_CodeGenerator_Php_PropertyTest)
Failed asserting that two strings are equal.

D:\Users\mabe\workspace\Zend\ZF-STD-TRUNK\tests\Zend\CodeGenerator\Php\PropertyT
est.php:91
D:\Users\mabe\workspace\Zend\ZF-STD-TRUNK\tests\Zend\CodeGenerator\AllTests.php:
43
D:\Users\mabe\workspace\Zend\ZF-STD-TRUNK\tests\Zend\CodeGenerator\AllTests.php:
57

FAILURES!
Tests: 99, Assertions: 123, Failures: 1, Skipped: 1.
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-01-19T14:51:30.000+0000</p> 
        <div class="body">
            <p>With the added patch all tests pass on my system.
Can you take a look in my changes please.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-01-21T09:06:10.000+0000</p> 
        <div class="body">
            <p>This was fixed in part with the efforts of ZF-8809</p>

        </div>
    </div>
    </div>

