<h2>ZF-8778: Spelling error in Zend/View/Abstract.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-01-11T10:29:39.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-11T18:25:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>in file "Zend/View/Abstract.php" the docblock for "public function render($name)" contains a little spelling error.
The word "script" appears twice in @param.</p>

<pre class="highlight"><code>
/**
* Processes a view script and returns the output.
*
* @param string $name The script script name to process.
* @return string The script output.
*/
</code></pre>

<p>Should be:</p>

<pre class="highlight"><code>
/**
* Processes a view script and returns the output.
*
* @param string $name The script name to process.
* @return string The script output.
*/
</code></pre>

<p>Nothing important, I just wanted to let you know.</p>

<p>Regards,
Rene</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-01-11T18:07:52.000+0000</p> 
        <div class="body">
            <p>Thank You for report, Rene Roesch.</p>

<p>Solved in SVN r20210. I found same issue on Zend/View/Interface.php , too.</p>

        </div>
    </div>
    </div>

