<h2>ZF-8815: Zend_Form_Element_Multi isValid problem with inArray </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-14T04:48:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Magnier (bagron)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When the value is a pure number, php cast the key in integer ( it's in the php doc ), but after, in the inArray Valid when php compare int(1) to '1 what you want', the response is true !</p>

<h2>reproductible with this code :</h2>

<p>$element = new Zend_Form_Element_Select('test');
$element-&gt;addMultiOptions(
    array(
        1 =&gt; 'test1'
    )
);</p>

<h2>$element-&gt;isValid('1 azd'); // return true</h2>

<p>Perhaps the more easy is to force the key in string in the Zend_Form_Element_Multi-&gt;isValid()
Actually, when the value is valided, false data can pass through without alert !</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-15T12:17:44.000+0000</p> 
        <div class="body">
            <p>The solution could be to add</p>

<pre class="highlight"><code>
...
    $options = array_map('strval',$options);

    $this-&gt;addValidator(
        'InArray',
        true,
        array(
            'haystack' =&gt; $options,
            'strict' =&gt; true
        )
    );
...
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-15T13:31:01.000+0000</p> 
        <div class="body">
            <p>I must correct myself it is even not needed to add the keys
haystack and strict to the validator options.</p>

<p>Just array_map is enough.</p>

        </div>
    </div>
    </div>

