<h2>ZF-8295: Some dates not converted properly</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-12T08:19:07.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-12T09:00:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am using Zend AMF to pass data from my Adobe Air application to my PHP/MySQL web application.  When I pass the dates 1/1/2010, 1/2/2010, or 1/3/2010 from my Air application, they show up in my web application with the year 2009 rather than 2010. I was not able to replicate this phenomenon for any other dates including those same dates in other years.</p>

<p>For example, when I pass the date 1/3/2010 from my Air application my php service grabs it as a Zend_Date object:
[sale_date] =&gt; Zend_Date Object
               (
                   [_locale:private] =&gt; en_US
                   [_fractional:private] =&gt; 0
                   [_precision:private] =&gt; 3
                   [_unixTimestamp:private] =&gt; 1262494800
                   [_timezone:private] =&gt; US/Eastern
                   [_offset:private] =&gt; 18000
                   [_syncronised:private] =&gt; 0
                   [_dst:protected] =&gt; 1
               )
When I convert this date to string (sale_date-&gt;toString('M-d-Y')), the result is '2009-1-3'.  This same phenomenon happens with 1/1/2010 and 1/2/2010 as well. Those dates will translate in php to 1/1/2009 and 1/2/2009 respectively.</p>

<p>However, when I pass the date 1/4/2010 from my Air application, my php service grabs it as a Zend_Date object:
 [sale_date] =&gt; Zend_Date Object
               (
                   [_locale:private] =&gt; en_US
                   [_fractional:private] =&gt; 0
                   [_precision:private] =&gt; 3
                   [_unixTimestamp:private] =&gt; 1262581200
                   [_timezone:private] =&gt; US/Eastern
                   [_offset:private] =&gt; 18000
                   [_syncronised:private] =&gt; 0
                   [_dst:protected] =&gt; 1
               )
When I convert this date to string (sale_date-&gt;toString('M-d-Y')), the result is '2010-1-4'.  It works as expected.  This is true with most other dates that I try.</p>

<p>I can only find this problem with 1/1/2010, 1/2/2010, and 1/3/2010, but I only tested about 15 other dates.</p>

<p>Please let me know if I can provide any other information.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2009-11-12T08:26:32.000+0000</p> 
        <div class="body">
            <p>Does this behavior still occur when you use 'y' instead of 'Y'?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jason S (shrensky) on 2009-11-12T08:35:05.000+0000</p> 
        <div class="body">
            <p>Dolf, great question.  I checked, and your suggestion solves the problem.  Thank you.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-12T08:44:50.000+0000</p> 
        <div class="body">
            <p>From the manual:
<a href="http://framework.zend.com/manual/en/zend.date.constants.html">http://framework.zend.com/manual/en/…</a>
{quote}
Note that the default ISO format differs from PHP's format which can be irritating if you have not used in previous. Especially the format specifiers for Year and Minute are often not used in the intended way.</p>

<p>For year there are two specifiers available which are often mistaken. The Y specifier for the ISO year and the y specifier for the real year. The difference is small but significant. Y calculates the ISO year, which is often used for calendar formats. See for example the 31. December 2007. The real year is 2007, but it is the first day of the first week in the week 1 of the year 2008. So, if you are using 'dd.MM.yyyy' you will get '31.December.2007' but if you use 'dd.MM.YYYY' you will get '31.December.2008'. As you see this is no bug but a expected behaviour depending on the used specifiers. 
{quote}</p>

<p>From the FAQ:
<a href="http://framework.zend.com/wiki/display/ZFFAQ/Internationalization">http://framework.zend.com/wiki/display/…</a>
{quote}
When using own formats in your code you could come to a situation where you get for example 29.12.2009, but you expected to get 29.12.2008.</p>

<p>There is one year difference: 2009 instead of 2008. You should use the lower cased year constant. See this example:</p>

<p>$date-&gt;toString('dd.MM.yyyy');<br />
$date-&gt;toString('dd.MM.yyyy');</p>

<p>Note the lower cased "y" which makes the difference and outputs the real year.
{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jason S (shrensky) on 2009-11-12T09:00:12.000+0000</p> 
        <div class="body">
            <p>Thank you for the follow up Thomas.  Until now, I did not appreciate the distinction.</p>

        </div>
    </div>
    </div>

