<h2>ZF-8588: Fatal error: Cannot redeclare class Zend_Loader in /path-to-zend/Loader.php on line 31</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-20T11:35:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-07T07:12:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Stelly (mjstelly)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8098">ZF-8098</a></li>
            <li><a href="/issues/browse/ZF-8607">ZF-8607</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>While following Rob Allen's "Getting Started with Zend Framework for version 1.9.0" tutorial, section "Setting up the Controller", he instructs the user to perform the following tasks:</p>

<p>zf create action add index 
zf create action edit index 
zf create action delete index</p>

<p>After inputting the first line, the CLI returns:
Fatal error: Cannot redeclare class Zend_Loader in /path-to-zend/Loader.php on line 31</p>

<p>Scouring the online forums for dozens of hours, I finally stumbled upon this link <a href="http://forums.zend.com/viewtopic.php?f=69&amp;t=813&amp;p=16266#p16266">http://forums.zend.com/viewtopic.php/…</a>. Commenting out the include_path line in the DEFAULT applications.ini solved the problem.</p>

<p>The folks on IRC @ zftalk said that line should never be included in applications.ini.
I suggest that Zend Tool be fixed so that it doesn't do that anymore.</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralf Eggert (ralf) on 2010-05-29T05:46:09.000+0000</p> 
        <div class="body">
            <p>I think, this issue can be closed. The fatal error mentioned in the report is not thrown any more with ZF 1.10.5. The issue should only stay open if this line should not be added to the application.ini when creating a new project through Zend_Tool:</p>

<p>includePaths.library = APPLICATION_PATH "/../library"</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-09-07T07:12:10.000+0000</p> 
        <div class="body">
            <p>This was fixed as part of the 1.10.x release series.</p>

        </div>
    </div>
    </div>

