<h2>ZF-80: Zend_Controller_Action::_getParam default return value logic error (TRAC#90 ralph)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2006-06-20T23:20:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.2.0 (29/Oct/06)</li>
            <li>0.6.0 (16/Dec/06)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zend Framework (zend_framework)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/developer/ticket/90">http://framework.zend.com/developer/ticket/90</a></p>

<p>Logically, if no param by the expected name is passed to the controller, the default return valued from _getParam should be NULL not FALSE.</p>

<p>More notes here:</p>

<p><a href="http://www.zend.com/lists/fw-general/200605/msg00983.html">http://zend.com/lists/fw-general/…</a></p>

<p>...</p>

<p>a better demonstration:</p>

<pre class="highlight"><code>
<a href="http://localhost/controller/some/">http://localhost/controller/some/</a>

public function someAction()
{

   $id = $this-&gt;_getParam("id");

   if (!is_null($id))
        echo "I am not null\n";

   if (isset($id))
        echo "I am set\n";

}

produces

I am not null I am set
</code></pre>

<p>When indeed id was not set and should be null.</p>

<p>proposed change to _getParam():</p>

<pre class="highlight"><code>
    /**
     * Gets a parameter that was passed to this controller.  If the
     * parameter does not exist, NULL will be return.
     *
     * If the parameter does not exist and $default is set, then
     * $default will be returned instead of FALSE.
     *
     * @param string $paramName
     * @param string $default
     * @return mixed
     */
    final protected function _getParam($paramName, $default=null)
    {
        if (array_key_exists($paramName, $this-&gt;_params)) {
            return $this-&gt;_params[$paramName];
        }

        return $default;
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Zend Framework (zend_framework) on 2006-06-20T23:21:29.000+0000</p> 
        <div class="body">
            <p>05/26/06 18:12:31: Modified by gavin</p>

<pre><code>* owner changed from zend to jayson.
* priority changed from major to minor.
</code></pre>

<p>I do see value in allowing ZF applications to distinguish between: 1) parameters that were not provided in the URL, 2) parameters that were provided in the URL, but had no value specified in the URL, and 3) parameters that were provided in the URL along with a value (at least 1 character).</p>

<p>Regardless of opinions about best practices and how an application was designed, all 3 of these cases can and do occur.
05/27/06 12:21:56: Modified by ralph@smashlabs.com</p>

<p>Indeed, to take care of 1) and 2) it sounds as if a method likely named _hasParam() of return boolean would suffice. And I agree on point three. Lets not be confused about what a character is though (in the php everything is a string sense of the word ;) ). If the controller sees /id// in the url, it should assume that id has no value, or is NULL. On the otherhand, if it sees /id/%20/, id would then have the value of " "... a string of length 1.</p>

<p>According to what you said, lets consider the following code:</p>

<p>if ($this-&gt;_hasParam("id"))
    $id = $this-&gt;_getParam("id");</p>

<p>-&gt; <a href="http://localhost/controller/action/id/%20/">http://localhost/controller/action/id/%20/</a>
      _hasParam would return true, _getParam would return " ".</p>

<p>-&gt; <a href="http://localhost/controller/action/id//">http://localhost/controller/action/id//</a>
      _hasParam would return true, _getParam would return NULL;</p>

<p>-&gt; <a href="http://localhost/controller/action/">http://localhost/controller/action/</a>
      _hasParam would return false</p>

<p>ps. i agree that this is a minor issue, but if possible it would be nice to see this implemented in 0.1.4
05/28/06 20:52:53: Modified by bell@creativenerd.com</p>

<p>Why NULL, why not make this return an empty string? Then you eliminate the need for _hasParam()</p>

<p>-&gt; <a href="http://localhost/controller/action/id//">http://localhost/controller/action/id//</a>
      _hasParam would return true, _getParam would return NULL;</p>

<p>05/29/06 01:43:47: Modified by ralph@smashlabs.com</p>

<p>An empty string is not null NULL, an empty string implies a variable is set, which the url <a href="http://localhost/controller/action/id//">http://localhost/controller/action/id//</a> seems to imply otherwise. That url string lexically says to me "$id = null;". Essentially, this comes down to expected behavior when used in any of the contexts listed here: <a href="http://us2.php.net/manual/en/types.comparisons.php">http://us2.php.net/manual/en/types.comparisons.php</a></p>

<p>Furthermore, the very definition of null seems best to suit this senerio <a href="http://us2.php.net/manual/en/language.types.null.php">http://us2.php.net/manual/en/…</a> "it has not been set to any value"</p>

<p>-ralph
06/12/06 06:04:53: Modified by URL
dkny watches timberland boots on sale breitling watches adipex phentermine corum watches harley davidson womens boots below the knee boots personalized luggage tag used rolex watches steel toe boots chippewa boots croton watches womens shoes wide width sketchers shoes dunham hiking boots watches swiss army fendi sunglasses mature women in pantyhose and silk stockings volcom purses women motorcycle boots
06/14/06 17:44:28: Modified by gavin</p>

<p>Although not exactly the same issue, the final solution for both Zend_Controller_Action and Zend_Input_Filter should have consistent semantics. For example, null indicates parameter not available/given, an empty string indicates the parameter was supplied / is available, and a non-empty string would contain the value of the parameter.</p>

<p>References:</p>

<pre><code>* &lt;a rel="nofollow" href="http://www.zend.com/lists/fw-general/200604/msg00380.html"&gt;http://zend.com/lists/fw-general/&amp;hellip;&lt;/a&gt;
* #142 
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2006-11-04T07:36:53.000+0000</p> 
        <div class="body">
            <p>The MVC implementation in 0.2.0 (incubator; also current SVN) implemented this as the Request object was designed to return null when a value was missing or a key does not exist.</p>

<p>In revision 1469, added _hasParam() per the commentary to this issue.</p>

        </div>
    </div>
    </div>

