<h2>ZF-8125: Zend_Form doen't set correctly a validator if have set only 1 option</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-22T15:21:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-11-12T15:06:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form cannot set correctly options of validator's element if 1 options is set.</p>

<p>Replication bug : create a Zend_Form with config ini :</p>

<p>..other element..
elements.email.type = "text"
elements.email.options.attribs.class = "element"
elements.email.options.attribs.id = "email"
elements.email.options.label = "Email"
elements.email.options.required = true
elements.email.options.validators.mail.validator = "EmailAddress"
elements.email.options.validators.mail.options.validateMx = true
elements.email.options.filters.lower.filter = "StringToLower"
..other element..</p>

<p>It not set correctly Zend_Validator_EmailAddress , the option validateMx is skipped.</p>

<p>if add 
elements.email.options.validators.mail.options.allow = 1
or
elements.email.options.validators.mail.options.mouse = "abcd"</p>

<p>validator take all options.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2009-11-12T15:06:45.000+0000</p> 
        <div class="body">
            <p>Already fixed in past with r18058 since 10.Sept.</p>

        </div>
    </div>
    </div>

