<h2>ZF-8294: OpenId Consumer doesn't work with Google as a provider</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-11-12T06:13:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-13T13:04:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>In Progress</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Torio Farazdagi (torio)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_OpenId</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6905">ZF-6905</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using the sample code provided in the manual, it's not possible to authenticate with Google - using <a href="https://www.google.com/accounts/o8/id">https://www.google.com/accounts/o8/id</a> - it is however possible to authenticate with e.g. myopenid without issue.</p>

<p>Error message returned: "Discovery failed"</p>

<p>Using latest 1.9 branch of ZF.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Tomek Pęszor (admirau) on 2009-12-19T11:53:35.000+0000</p> 
        <div class="body">
            <p>The same for me, with ZF 1.9.6</p>

<p>Here are some workarounds for this issue:
<a href="http://ak33m.com/?p=71">http://ak33m.com/?p=71</a></p>

<p>(be sure to read the comments too)</p>

        </div>
    </div>
    </div>

