<h2>ZF-8055: Bug when using ZendX_JQuery_Form_Decorator_DialogContainer
</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-12T10:22:53.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-29T02:37:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.1 (10/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Itanjaka Mandresi (mandresi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <ol><li>When using the <em>ZendX_JQuery_Form_Decorator_DialogContainer</em>, the content is not rendered. It seems that this is because the <em>dialogContainer</em> method has different syntax in comparison to <em>accordionContainer</em> and <em>tabContainer</em>.
\
\
{quote}
{{public function dialogContainer($id, {color:red}$content{color} , $params=array(), $attribs=array())}}</li>
</ol><p>{{public function accordionContainer($id=null, array $params=array(), array $attribs=array())}}
{{public function tabContainer($id=null, $params=array(), $attribs=array())}}
{quote} 
\</p>

<p>The <em>dialogContainer</em> syntax does not correspond to what is used inside the <em>ZendX_JQuery_Form_Decorator_UiWidgetContainer -&gt; render</em> method when rendering.</p>

<p>\
\
2. In the other hand, <em>ZendX_JQuery_Form_Decorator_UiWidgetContainer -&gt; render</em> contains the following instruction :</p>

<pre class="literal"> 
      $attribs     = array_merge($this-&gt;getAttribs(), $this-&gt;getOptions());
</pre>

<p>That causes the DIV container of the dialog to inherit of all attributes of the element (form for example)</p>

<p>So you can see results like that :</p>

<pre class="highlight"><code>
</code></pre><div><code> 
...
</code></div><code>
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2009-12-16T14:18:38.000+0000</p> 
        <div class="body">
            <p>This is very weird.. I am going to look into it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2010-01-29T02:37:30.000+0000</p> 
        <div class="body">
            <p>Both issues are fixed now in trunk, and merged back into 1.10 release branch.</p>

<p>Additionally i added a section to the manual about Dialog Container rendering in the Zend Form context.</p>

        </div>
    </div>
    </div>

