<h2>ZF-8080:  Zend_Application_Bootstrap_BootstrapTest &quot;No default controller directory registered with front controller&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2009-10-16T08:35:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2009-10-22T07:21:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.9.5 (27/Oct/09)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8118">ZF-8118</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>{quote} weierophinney, I get this error when running Zend/Application/AllTests.php, should I add an issue? testRunShouldDispatchFrontController(Zend_Application_Bootstrap_BootstrapTest) \n Zend_Application_Bootstrap_Exception: No default controller directory registered with front controller
 Freeaqingme: let me run locally.
 sure
...
 It's running fine for me.
 no errors whatsoever.
 oh, odd -- I get the error only when I run Zend_Application_Bootstrap_BootstrapTest by itself.
 Freeaqingme: yes, add an issue, and I'll look into it.
 sure{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2009-10-16T10:30:47.000+0000</p> 
        <div class="body">
            <p>Resolved in trunk and 1.9 release branch.</p>

        </div>
    </div>
    </div>

