<h2>ZF-8138: Zend_Db_Statement_Sqlsrv -&gt; nextRowset  () is not implemented</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-10-24T06:45:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-16T11:28:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Roman (romeo.deepmind)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Juozas Kaziukenas (juokaz)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>this method only throws exception.</p>

<p>doesn't return anything and doesn't switch to next recordset</p>

<p>i used a quick (and maybe dirty) workaround for this</p>

<pre><code>public function nextRowset()
{
    if (($result = sqlsrv_next_result($this-&gt;_stmt)) === true) {
        $this-&gt;_keys = null;
    }

    return $result;
}
</code></pre>

<p>this worked perfect for me</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Juozas Kaziukenas (juokaz) on 2010-04-16T11:28:44.000+0000</p> 
        <div class="body">
            <p>Fixed in r21887</p>

        </div>
    </div>
    </div>

