<h2>ZF-8807: Bug in Zend_File_Transfer addValidators</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-13T06:13:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-01-13T07:00:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.0 (27/Jan/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_File_Transfer</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I want use</p>

<pre><code>    $upload = new Zend_File_Transfer_Adapter_Http();

    $validators = array(
        array('MimeType',  true, array('image/jpeg', 'image/gif', 'image/png')),
        array('FilesSize', true, array('max' =&gt; '1MB', 'messages' =&gt; 'файл больше 1 MБ')),
    );

   $upload-&gt;addValidators($validators, 'img');
</code></pre>

<p>Set validators only to img and breakOnFailure = true</p>

<p>Because format</p>

<pre><code>    $validators = array(
        'MimeType' =&gt; array('image/jpeg', 'image/gif', 'image/png'),
        'FilesSize' =&gt; array('max' =&gt; '1MB', 'messages' =&gt; 'файл больше 1 MБ'),
    );
</code></pre>

<p>always has breakOnFailure = false;</p>

<p>But bug in abstract class Zend_File_Transfer_Adapter_Abstract
<a href="http://framework.zend.com/issues/browse/ZF-8693">http://framework.zend.com/issues/browse/ZF-8693</a></p>

<p>Set always files to null, and my validators set to all files!!! Must be set only to img.</p>

<p>Please change invalid case!</p>

<pre><code>                    if ($argc &gt; 0) {
                        $validator = array_shift($validatorInfo);

                        if (2 &lt;= $argc)
                            $breakChainOnFailure = array_shift($validatorInfo);

                        if (3 &lt;= $argc)
                            $options = array_shift($validatorInfo);

                        if (4 &lt;= $argc)
                            $files = array_shift($validatorInfo);

                        $this-&gt;addValidator($validator, $breakChainOnFailure, $options, $files);
                    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-01-13T07:00:32.000+0000</p> 
        <div class="body">
            <p>This is a duplicate of ZF-8693.</p>

<p>ZF-8693 is already fixed for the next minor release.
Please be patient until it has been released or use trunk when you can't wait.</p>

        </div>
    </div>
    </div>

