<h2>ZF-8382: Zend_Log_Writer_Syslog does not utilize formatter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2009-11-24T05:51:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-30T09:43:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.3 (01/Feb/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Markus Warg (edgarwahn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benoît Durand (intiilapa)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12727/chrismsnz-zf-syslog-format-1.patch">chrismsnz-zf-syslog-format-1.patch</a></li>
            <li><a href="/issues/secure/attachment/12728/chrismsnz-zf-syslog-format-2.patch">chrismsnz-zf-syslog-format-2.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>You can set an formatter for an Zend_Log_Writer_Syslog object. But as it seems this formatter is never used.</p>

<p>In my opinion the formatter should be utilized, once you are allowed to set one... See this very trivial patch to Zend/Log/Writer/Syslog.php:</p>

<p>--- Syslog.php  (revision 19)
+++ Syslog.php  (working copy)
@@ -170,6 +170,8 @@
             $this-&gt;_initializeSyslog();
         }</p>

<ul><li>syslog($priority, $event['message']);</li>
<li>$line = $this-&gt;_formatter-&gt;format($event);</li>
<li></li>
<li>syslog($priority, $line);
 }
}</li>
</ul>
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Smith (chrismsnz) on 2010-02-08T14:45:46.000+0000</p> 
        <div class="body">
            <p>Hi, I've run into this problem, too.</p>

<p>The above patch will fail with an error if a user tries to write to a syslog with no formatter.</p>

<p>There are two solutions:</p>

<p>(1) Detect if there's a formatter set &amp; use it if there is [chrismsnz-zf-syslog-format-1.patch]
- Inconsistent with how the other writer's formatters are initialised</p>

<p>(2) Set a default formatter (same approach as the other writers) [chrismsnz-zf-syslog-format-2.patch]
- May need to override the default simple formatter string as it's probably not appropriate for syslog.</p>

<p>Approach #2 is probably preferred.</p>

<p>Cheers,
Chris.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Smith (chrismsnz) on 2010-02-08T14:46:24.000+0000</p> 
        <div class="body">
            <p>Added patches referenced in the above comment</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-10-20T19:31:14.000+0000</p> 
        <div class="body">
            <p>Assigned to [~intiilapa]</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-12-17T11:39:32.000+0000</p> 
        <div class="body">
            <p>The reason we didn't provide formatter support originally is because you're using the syslog facility -- syslog() is expecting both a priority and a message as arguments, and usually indicates the priority in the log itself. Using the Simple formatter, we'd end up seeing the priority duplicated in such logs.</p>

<p>As such, patch 1 makes more sense -- if no formatter is present, simply use the current approach (syslog($priority, $message)), and if and only if a formatter has been explicitly provided, use it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2010-12-18T05:19:57.000+0000</p> 
        <div class="body">
            <p>r23551</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-12-30T09:43:36.000+0000</p> 
        <div class="body">
            <p>Reopening in order to correct fix version.</p>

        </div>
    </div>
    </div>

