<h2>ZF-8452: Zend Form Element Select Implied Multiple Select</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2009-12-03T02:16:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2013-01-07T17:40:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.2 (25/Feb/13)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/15228/ZF-8452.patch">ZF-8452.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using Zend_Form_Element_Select in conjunction of setIsArray it is implied that you want a multiple select, when you may not. Now this is definitely a feature for those who want it, but for those who want multiple selects it's a problem.</p>

<p>For example if I use the following code:</p>

<pre class="highlight"><code>
$field = new Zend_Form_Element_Select('field');
$field-&gt;setIsArray(true)
      -&gt;setMultiOptions(array(
        'a' =&gt; 'A',
        'b' =&gt; 'B',
        'c' =&gt; 'C',
      ));
</code></pre>

<p>I get the following output:</p>

<pre class="highlight"><code>
ABC</code></pre>

<p>When I want the desired output:</p>

<pre class="highlight"><code>
ABC</code></pre>

<p>I have looked into work arounds for this problem, but I don't feel they're appropriate for such a simple problem which can easily be corrected by removal of three lines.</p>

<p>Now I propose either we remove the offending code which is on 77 to 79 of Zend_View_Helper_FormSelect which will simply mean people wanting multiple select will be required to add setAttrib('multiple', 'multiple') but will break backwards compatability I believe, or add an option to disable that code.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andrew Phillipo (aphillipo) on 2010-07-06T02:54:10.000+0000</p> 
        <div class="body">
            <p>Yes, this is extremely strange behaviour; I have been trying to figure out why it is doing this, so thanks for the bug report to know that I'm not going mad.  I have no idea how to build a normalselect box in Zend forms, will post here when I figure it out.  Seems like creating a normal, simple select box should be simpler, but then that could be said about so much of zend.</p>

<p>Please fix.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Justin Jahn (4sak3n0ne) on 2010-09-08T13:40:37.000+0000</p> 
        <div class="body">
            <p>A <a href="http://www.zfforums.com/zend-framework-general-discussions-1/general-q-zend-framework-2/form-select-defaults-multi-when-name-ends-4900.html#post16675">ZFForums</a> article describes a temporary fix for this issue.</p>

<pre class="highlight"><code>
&lt;?php
    $element = new Zend_Form_Element_Select('selectbox', array('multiple' =&gt; false ));
    $element-&gt;setIsArray(true);
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Steinmann (cmiwebstudio) on 2012-12-26T23:58:37.000+0000</p> 
        <div class="body">
            <p>I agree this it a temporary fix, however, there are circumstances where this wouldn't be an option (creating a new instance).  One should be able to getElement and add this setIsArray attribute and NOT automatically turn your select into a multi select.  This is oversight at best.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Steinmann (cmiwebstudio) on 2012-12-27T00:02:46.000+0000</p> 
        <div class="body">
            <p>I should also mention this issue stil exists in Zf 1.12.1 many years after this issue was reported.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-12-28T10:04:55.000+0000</p> 
        <div class="body">
            <p>I will look into it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jonathan Steinmann (cmiwebstudio) on 2012-12-29T15:10:59.000+0000</p> 
        <div class="body">
            <p>Here's the work around:</p>

<p>$element = $this-&gt;getElement('element');
$element-&gt;setMultiOptions(array('a' =&gt; 'A'))
        -&gt;setIsArray(true)
        -&gt;setOptions(array('multiple' =&gt; false);</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-12-30T15:08:48.000+0000</p> 
        <div class="body">
            <p>@Jonathan
Look at the comment from Justin Jahn. ;)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-01-05T16:21:49.000+0000</p> 
        <div class="body">
            <p>Patch with fix and unit test added. (includes changes from {{assertType}} to {{assertTrue}})</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2013-01-07T17:40:28.000+0000</p> 
        <div class="body">
            <p>Fixed on trunk (25182) and release-1.12 (25183)</p>

        </div>
    </div>
    </div>

