<h2>ZF-829: no methods to delete script-, helper-, filter directories</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2007-01-30T16:54:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:43.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>the abstract class Zend_View_Abstract don't implement methods to delete/unset setted/added [script | helper | filter] directories but the Zend_View_* helper and filter files are added automatic.</p>

<p>If I don't use your helper or filter this directories will include anyway ( performance ? )</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-02-08T09:26:51.000+0000</p> 
        <div class="body">
            <p>First: to reset the filter, helper, and script paths, simply call the relevant setter method with an empty value:</p>

<pre class="highlight"><code>
$view-&gt;setScriptPath('');
$view-&gt;setHelperPath('');
$view-&gt;setFilterPath('');
</code></pre>

<p>You are correct -- it still keeps the paths to the Zend_View_Helper/_Filter classes; these are not removed, as they are considered standard functionality for Zend_View.</p>

<p>However, the classes in the helper and filter paths are lazy loaded -- i.e., included only when called. If you never call one of the standard helpers or filters, the classes will never be loaded.</p>

        </div>
    </div>
    </div>

