<h2>ZF-8578: Zend_Service_Amazon_S3::cleanBucket() does not clean all objects as documentation implies</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2009-12-18T02:57:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-05-27T15:10:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.7 (02/Jun/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Julian Davchev (jmut)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Enrico Zimuel (zimuel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>From what I see in trunk cleanBucket is still removing only objects returned by</p>

<p>$objects = $this-&gt;getObjectsByBucket($bucket);</p>

<p>This is wrong as it would return default value by amazon which is 1000 objects hence not cleaning whole bucket</p>

<p>Several options:
- Documentation asks for users to call cleanBucket() until false returned
- cleanBucket() makes use of $params argument that is currently in trunk (no stable release of it)</p>

<p>More on this</p>

<p>Excerpt from <a href="http://developer.amazonwebservices.com/connect/entry.jspa?externalID=1904">http://developer.amazonwebservices.com/connect/…</a>
Efficiently Deleting Objects</p>

<p>Deleting a large number of objects for which you don't have an external list can be made faster and easier by using the marker function of the LIST operation.  Call LIST to get an initial set of objects to DELETE.  Step through the list deleting each and saving the key of the last object in the list.  Call LIST again using the last object deleted as a marker, and repeat this process until all desired objects have been deleted.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Enrico Zimuel (zimuel) on 2011-05-27T14:42:30.000+0000</p> 
        <div class="body">
            <p>Fixed on trunk (commit 24047): added a while to delete more than 1000 objects using the suggestion reported here (Efficiently Deleting Objects): <a href="http://developer.amazonwebservices.com/connect/entry.jspa?externalID=1904">http://developer.amazonwebservices.com/connect/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Enrico Zimuel (zimuel) on 2011-05-27T15:10:36.000+0000</p> 
        <div class="body">
            <p>Resolved in branches/release-1.11 (commit 24048)</p>

        </div>
    </div>
    </div>

