<h2>ZF-880: getDate() / _parseDate() automatically process abbreviated month names, even when not selected</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-02-08T13:57:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Gavin (gavin)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I think abbreviated month names should not be processed in _parseDate() unless selected via the $format.
Currently, selecting 'd' in $format also enables automatically process abbreviated month names, even when not selected.</p>

<p>Feedback is welcome.  Do you agree?  Is there a reason for the current behavior?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-09T01:48:05.000+0000</p> 
        <div class="body">
            <p>I do not agree...</p>

<p>The standard useage of getDate is to use the standard format for dates because the user does not know about formating rules.</p>

<p>But the standardformat does not always include month and daynames.
Also fixing this to the EXACT format you will have the problem that dates are not recognised anymore.</p>

<p>'10.10.2006' and '10.Oktober.2006' and '10.Okt.2006'</p>

<p>are german dates and should all be recognised by the standard format.
Same useage for all other locales.</p>

<p>Otherwise a user has to seperate if he uses a month name or an abbreviated name or a number.</p>

<p>In my opinion the standard format should accept all various combinations of dates for a locale and not only one of them.</p>

<p>Otherwise this would be no benefit for the user.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-02-11T18:36:36.000+0000</p> 
        <div class="body">
            <p>Ok, you convinced me :)</p>

<p>Instead, why not always translate day and month names, if the $format contains 'd' or 'M' or 'EEEE' or 'MMMM'?
This feature seems quite useful, and a major advantage unique to the ZF and the i18n components.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-12T01:17:56.000+0000</p> 
        <div class="body">
            <p>This is already be done by _parseDate()...</p>

<p>EEEE, the full dayname is deleted because having 'Monday' is not enough to say which day was meant.</p>

<p>d, the daynumber, is used as expected</p>

<p>MMMM, the full monthname is parsed if the format defines a full monthname, otherwise the abbreviated monthname is searched and if found converted to a monthnumber.</p>

<p>So after all actions we have a monthnumber 'M' which is used for parsing through the date.</p>

<p>The only thing which is now handled else is that if full month is defined also only full months are searched and not the abbreviated ones... but this was only done for speed...</p>

<p>We can also say that if 'M' is presented within the format always full and abbreviated months have to be searched.</p>

<p>Note:
The standardformats from CLDR only define M and MMMM...
The formats MM, MMM and MMMMM are not included in this definitions so I did not integrate them for parsing... reason was also speed...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-23T15:33:43.000+0000</p> 
        <div class="body">
            <p>Solved with SVN 3595.</p>

<p>Now full and abbreviated month names are always parsed as soon as a "M" is given in the format.</p>

<p>Also daynames are always parsed as soon as "E" is given.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gavin (gavin) on 2007-02-23T16:25:00.000+0000</p> 
        <div class="body">
            <p>Excellent.  Now we have consistency.  The sequence of processing is also critical to avoid potential bugs.
For example, processing abbreviations first might result in wrong matches in some locales/languages.</p>

<p>I realize that many of the CLDR format specifiers are not supported, but _parseDate() now recognizing all the most popular and frequently occuring specifiers, so I think we are done for now :)</p>

        </div>
    </div>
    </div>

