<h2>ZF-9794: Add support to load jQuery UI themes from google CDN</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-05-03T07:41:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-09-23T11:34:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>In Progress</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13592/Container.php">Container.php</a></li>
            <li><a href="/issues/secure/attachment/14660/Container.php.patch">Container.php.patch</a></li>
            <li><a href="/issues/secure/attachment/14655/Container.php.patch">Container.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Much like the ajax libraries are available via the google CDN, the CSS and image files for the jQuery UI themes are also available via google CDN.
This is not documented as good as the library documentation itself, however there have been some good blog postings about this.
Read the details here: <a href="http://encosia.com/2009/10/11/do-you-know-about-this-undocumented-google-cdn-feature/">http://encosia.com/2009/10/…</a></p>

<p>This would be a very great enhancement in my opionen, as this enables the developer to use jQuery + UI without hosting any of the files himself, which made it a bummer for myself.</p>

<p>Currently I'm getting this done formyself via the following line of code in the layout script</p>

<pre class="highlight"><code>
&lt;?php echo $this-&gt;jQuery()-&gt;addStyleSheet('<a href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/themes/blitzer/jquery-ui.css">http://ajax.googleapis.com/ajax/libs/…</a>') ?&gt;
</code></pre>

<p>If this feature will be added to one of the future releases, we need to make sure to tell the implementor of ZendX_Application_Resource_Jquery that support for the UI theme is added to the resource plugin.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alex Frenkel (sirshurf) on 2011-01-10T05:44:52.000+0000</p> 
        <div class="body">
            <p>Since we now have options to fetch from GOOGLE CDN language for UI and the thems I am adding support for that.</p>

<p>The support would not affect back.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Frenkel (sirshurf) on 2011-01-10T06:12:16.000+0000</p> 
        <div class="body">
            <p>Here is the fix to work with the Translation files from google CDN.</p>

<p>It uses the full translation file and selecting regional using reginal selection API for JQuery.</p>

<p>Looks like I dont have SVN access from this client, I will add Test case and normal submission later.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Frenkel (sirshurf) on 2011-09-23T10:52:47.000+0000</p> 
        <div class="body">
            <p>This patch has support for language files...</p>

<p>Plus support for setting correct language in datepicker.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alex Frenkel (sirshurf) on 2011-09-23T11:34:34.000+0000</p> 
        <div class="body">
            <p>Finished adding support for themes and for languages.</p>

<p>Plus switched all request from deprecated methods.</p>

        </div>
    </div>
    </div>

