<h2>ZF-9434: StripTags returns empty string when stripping html comments </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-16T08:02:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-18T12:01:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The implementation of Zend_Filter_StripTags fails on the next code (similar to issue ZF-8894):</p>

<pre class="literal">
$value = 'test  test </pre><div>div-content</div>';

$stripTags = new Zend_Filter_StripTags();    
$string = $stripTags-&gt;filter($value); 


<p>The expected result is "test test</p>

<div>div-content</div>

<p>" but an empty string is returned.</p>

<p>The error generates on this line of the Zend_Filter_StripTags implementation:</p>

<pre class="literal">
$value = 'test  test </pre><div>div-content</div>';
$valueCopy = preg_replace('#
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-18T12:01:07.000+0000</p> 
        <div class="body">
            <p>Fixed with r21553</p>

        </div>
    </div>
    </div>

