<h2>ZF-9102: Zend_Http_Client unit tests may fail (in CommonHttpTests) if the test domain is a local single term word</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-02-06T08:16:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-06T08:19:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>For example: <a href="http://zftest">http://zftest</a> instead of <a href="http://zftest/path">http://zftest/path</a> (or something more likely to be used from a proper domain). There is a dirname() call on line 515 which spots the lack of a path separator and assumes this is root-like on linux, this substituting in a single separator at the end of the domain. This is expected dirname() behaviour. Zend_Http_Client behaviour is NOT impacted, this is just a small test code issue.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-06T08:19:29.000+0000</p> 
        <div class="body">
            <p>Fixed in r20940</p>

        </div>
    </div>
    </div>

