<h2>ZF-9195: Numerous files contain ASCII 0x0d (CR) characters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2010-02-16T16:43:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-30T00:03:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ross Smith (rasa7777)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10669">ZF-10669</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Files that contain embedded ASCII 0x0d characters in them can cause some subversion clients to abort with the fatal error message</p>

<p>"Inconsistent line ending style"</p>

<p>The following script identifies files that have ASCII 0x0d's in them:</p>

<h1>!/bin/sh</h1>

<p>for i in \
demos/Zend/Pdf/test.pdf \
tests/Zend/Http/_files/response_crlf \
tests/Zend/Http/_files/response_multibyte_body \
tests/Zend/Http/_files/response_chunked_case \
tests/Zend/Http/_files/response_leadingws \
tests/Zend/Http/_files/response_chunked \
library/Zend/Service/DeveloperGarden/Wsdl/ccsPort.xsd \
library/Zend/Http/Client.php \
documentation/manual/tr/ref/language-snippets.xml \
documentation/manual/he/ref/requirements.xml \
documentation/manual/he/ref/language-snippets.xml \
documentation/manual/he/module_specs/Zend_View-Helpers-Doctype.xml \
documentation/manual/bg/ref/language-snippets.xml \
documentation/manual/sr/ref/language-snippets.xml \
documentation/manual/nl/ref/language-snippets.xml \
documentation/manual/sk/ref/language-snippets.xml \
documentation/manual/sk/module_specs/Zend_Controller-ActionHelpers-FlashMessenger.xml \
documentation/manual/ja/module_specs/Zend_Search_Lucene-Queries.xml \
documentation/manual/ko/ref/language-snippets.xml \
documentation/manual/de/ref/language-snippets.xml \
documentation/manual/pl/ref/language-snippets.xml \
documentation/manual/cs/ref/language-snippets.xml \
documentation/manual/it/ref/language-snippets.xml \
documentation/manual/uk/ref/language-snippets.xml \
documentation/manual/id/ref/language-snippets.xml \
documentation/manual/ro/ref/language-snippets.xml \
documentation/manual/ru/ref/language-snippets.xml \
documentation/manual/zh/ref/language-snippets.xml \
documentation/manual/zh/module_specs/Zend_Dojo-View-Dojo.xml \
documentation/manual/sl/ref/language-snippets.xml \
documentation/manual/fa/ref/language-snippets.xml \
documentation/manual/hu/ref/language-snippets.xml \
documentation/manual/hu/module_specs/Zend_Controller-QuickStart.xml \
documentation/manual/ar/ref/language-snippets.xml \
externals/dojo/util/resources/logo/positive/dojox.logo.eps \
externals/dojo/util/resources/logo/positive/dojo.logo.eps \
externals/dojo/util/resources/logo/positive/dijit.logo.eps \
externals/dojo/util/resources/logo/negative/dojox.logo.neg.eps \
externals/dojo/util/resources/logo/negative/dojo.logo.neg.eps \
externals/dojo/util/resources/logo/negative/dijit.logo.neg.eps
do
    echo -----------------------------------------------------------------------
    echo $i:
    od -a $i | egrep '\bcr\b' | head -n 1
    od -t x1 $i | egrep '\b0d\b' | head -n 1
done</p>

<p>And here is the output:</p>

<hr /><p>demos/Zend/Pdf/test.pdf:
0001060   f  cr  nl   0  sp   8  cr  nl   0   0   0   0   0   0   0   0</p>

<h2>0001060 66 0d 0a 30 20 38 0d 0a 30 30 30 30 30 30 30 30</h2>

<p>tests/Zend/Http/_files/response_crlf:
0000000   H   T   T   P   /   1   .   0  sp   2   0   0  sp   O   K  cr</p>

<h2>0000000 48 54 54 50 2f 31 2e 30 20 32 30 30 20 4f 4b 0d</h2>

<p>tests/Zend/Http/_files/response_multibyte_body:
0000340   8  nl  nl   2   e   d  cr  nl   W dle   W  rs   W dle  sp   W</p>

<h2>0000340 38 0a 0a 32 65 64 0d 0a d7 90 d7 9e d7 90 20 d7</h2>

<p>tests/Zend/Http/_files/response_chunked_case:
0000000   H   T   T   P   /   1   .   1  sp   2   0   0  sp   O   K  cr</p>

<h2>0000000 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d</h2>

<p>tests/Zend/Http/_files/response_leadingws:
0000000   H   T   T   P   /   1   .   1  sp   2   0   0  sp   O   K  cr</p>

<h2>0000000 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d</h2>

<p>tests/Zend/Http/_files/response_chunked:
0000000   H   T   T   P   /   1   .   1  sp   2   0   0  sp   O   K  cr</p>

<h2>0000000 48 54 54 50 2f 31 2e 31 20 32 30 30 20 4f 4b 0d</h2>

<p>library/Zend/Service/DeveloperGarden/Wsdl/ccsPort.xsd:
0004160  cr  nl  ht   &lt;   x   s   d   :   c   o   m   p   l   e   x   T</p>

<h2>0004160 0d 0a 09 3c 78 73 64 3a 63 6f 6d 70 6c 65 78 54</h2>

<p>library/Zend/Http/Client.php:
0004040   E   C   T   '   ;  cr  nl  sp  sp  sp  sp   c   o   n   s   t</p>

<h2>0004040 45 43 54 27 3b 0d 0a 20 20 20 20 63 6f 6e 73 74</h2>

<p>documentation/manual/tr/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/he/ref/requirements.xml:
0770060  cr  nl   1   Z   e   n   d   _   D   b  cr  nl   1   Z   e   n</p>

<h2>0770060 0d 0a 31 5a 65 6e 64 5f 44 62 0d 0a 31 5a 65 6e</h2>

<p>documentation/manual/he/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/he/module_specs/Zend_View-Helpers-Doctype.xml:
0001360   s   t   i   t   e   m   &gt;  cr  nl  sp  sp  sp  sp  sp  sp  sp</p>

<h2>0001360 73 74 69 74 65 6d 3e 0d 0a 20 20 20 20 20 20 20</h2>

<p>documentation/manual/bg/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/sr/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/nl/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/sk/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/sk/module_specs/Zend_Controller-ActionHelpers-FlashMessenger.xml:
0000060   s   s   e   n   g   e   r   "   &gt;  cr  nl  sp  sp  sp  sp   &lt;</p>

<h2>0000060 73 73 65 6e 67 65 72 22 3e 0d 0a 20 20 20 20 3c</h2>

<p>documentation/manual/ja/module_specs/Zend_Search_Lucene-Queries.xml:
0000500 soh dc3   c soh   (   c stx stx   c soh   '   c soh  cr   c soh</p>

<h2>0017520 61 6d 6c 69 73 74 69 6e 67 3e 0a 0d 0a 20 20 20</h2>

<p>documentation/manual/ko/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/de/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl   &lt;   !   -   -  sp   E   N   -</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 3c 21 2d 2d 20 45 4e 2d</h2>

<p>documentation/manual/pl/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/cs/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/it/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/uk/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/id/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/ro/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/ru/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/zh/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/zh/module_specs/Zend_Dojo-View-Dojo.xml:
0001260   f  ht  vt   e   .  rs   g  so   0   f can   /   e  cr  sp   d</p>

<h2>0037000 6f 64 65 3e 3a 0d 0a 20 20 20 20 20 20 20 20 20</h2>

<p>documentation/manual/sl/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/fa/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/hu/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>documentation/manual/hu/module_specs/Zend_Controller-QuickStart.xml:
0004100   o   n   /  cr  nl  sp  sp  sp  sp   c   o   n   t   r   o   l</p>

<h2>0004100 6f 6e 2f 0d 0a 20 20 20 20 63 6f 6e 74 72 6f 6c</h2>

<p>documentation/manual/ar/ref/language-snippets.xml:
0000040   f   -   8   "   ?   &gt;  cr  nl  nl   &lt;   !   -   -  sp   l   i</p>

<h2>0000040 66 2d 38 22 3f 3e 0d 0a 0a 3c 21 2d 2d 20 6c 69</h2>

<p>externals/dojo/util/resources/logo/positive/dojox.logo.eps:
0000600  cr   %   A   I   9   _   P   r   i   n   t   i   n   g   D   a</p>

<h2>0000600 0d 25 41 49 39 5f 50 72 69 6e 74 69 6e 67 44 61</h2>

<p>externals/dojo/util/resources/logo/positive/dojo.logo.eps:
0000020   P   S   F   -   3   .   0  cr   %   A   D   O   _   D   S   C</p>

<h2>0000020 50 53 46 2d 33 2e 30 0d 25 41 44 4f 5f 44 53 43</h2>

<p>externals/dojo/util/resources/logo/positive/dijit.logo.eps:
0000560   V   e   r   s   i   o   n   :  sp   1   3   .   0   .   0  cr</p>

<h2>0000560 56 65 72 73 69 6f 6e 3a 20 31 33 2e 30 2e 30 0d</h2>

<p>externals/dojo/util/resources/logo/negative/dojox.logo.neg.eps:
0000600   .   0   .   0  cr   %   A   I   9   _   P   r   i   n   t   i</p>

<h2>0000600 2e 30 2e 30 0d 25 41 49 39 5f 50 72 69 6e 74 69</h2>

<p>externals/dojo/util/resources/logo/negative/dojo.logo.neg.eps:
0000020   P   S   F   -   3   .   0  cr   %   A   D   O   _   D   S   C</p>

<h2>0000020 50 53 46 2d 33 2e 30 0d 25 41 44 4f 5f 44 53 43</h2>

<p>externals/dojo/util/resources/logo/negative/dijit.logo.neg.eps:
0000560   V   e   r   s   i   o   n   :  sp   1   3   .   0   .   0  cr
0000560 56 65 72 73 69 6f 6e 3a 20 31 33 2e 30 2e 30 0d</p>

<p>Obviously, these files</p>

<p>demos/Zend/Pdf/test.pdf
tests/Zend/Http/_files/response_crlf
tests/Zend/Http/_files/response_multibyte_body
tests/Zend/Http/_files/response_chunked_case
tests/Zend/Http/_files/response_leadingws
tests/Zend/Http/_files/response_chunked</p>

<p>should probably not be changed, but the remaining files should be converted to Unix format, to minimize the above mentioned "Inconsistent line ending style" issue.</p>

<p>The easiest way to fix this issue is to run the dos2unix command on these files. Please note that dos2unix may need to be run multiple times.</p>

<p>Thanks!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-15T11:18:30.000+0000</p> 
        <div class="body">
            <p>Closing as fixed</p>

<p>All other files are not needed to be changed (PDF file, XSD file, Dojo files...)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ross Smith (rasa7777) on 2011-03-30T00:03:37.000+0000</p> 
        <div class="body">
            <p>This is <em>still</em> an issue. For example:</p>

<p>$ svn export <a href="http://framework.zend.com/svn/framework/standard/tags/release-1.11.4">http://framework.zend.com/svn/framework/…</a>
$ cd release-1.11.4
$ svn import . <a href="http://example.com/svn/zend/release-1.11.4">http://example.com/svn/zend/release-1.11.4</a>
...
Adding         library/Zend/Service/DeveloperGarden/Wsdl/IPLocation.wsdl
Adding         library/Zend/Service/DeveloperGarden/Wsdl/TokenService.wsdl
Adding         library/Zend/Service/DeveloperGarden/Wsdl/ccsPort.xsd
svn: Inconsistent line ending style
$</p>

        </div>
    </div>
    </div>

