<h2>ZF-9839: Zend_Cache_Backend_BlackHole fails to &quot;save&quot; items when default front end config is used</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-05-14T08:39:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using Zend_Cache_Backend_BlackHole with the Core frontend using default options, the Core instance attempts to do write control verification, which isn't supported by the BlackHole backend by design.  The simple solution is to specify this option when creating the Core instance, but it takes some digging to figure out why it is failing.</p>

<p>A more elegant solution might be to throw an exception when the load method is called on the BlackHole backend or if the desire is to maintain API compatibility, maybe throw an exception when write control is attempted with this backend (since it will always fail) and explicitly state that the write control option is incompatible with that backend.</p>

<p>Alternatively, I suppose you could specify a set of frontend options supported by each backend, but that seems overkill for this edge case.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-05-14T09:15:21.000+0000</p> 
        <div class="body">
            <p>OK I understand your problem but if I test the backend's name to throw an exception or to auto disable write_control it doesn't handle self defined backends :(
I would like to disable write_control by default because it's not supported by all backends but this would change the configuration on some apps.</p>

<p>-&gt; We will disable write_control by default on ZF 2.0. Please disable it by your self if you use the BlackHole backend.</p>

        </div>
    </div>
    </div>

