<h2>ZF-9417: Zend_View_Helper_Currency toString() for null and empty values</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-03-12T05:33:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-08-08T02:58:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.8 (25/Aug/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Simon Corless (sico)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I believe Zend_View_Helper_Currency should have some form of toString method in order to format null values. Currently if you supply null to the currency() method you receive the view helper as expected.</p>

<p>However when using database values where it may well be possible to retrieve a null value this can cause confusion and problems with the script. Whereas if null or a string was returned you wouldn't need to account for special conditions.</p>

<p>I think it would be nice if the currency view helper implemented a way to return null (or an empty string) itself (or in fact a default value if supplied). This way the logic wouldn't need to be carried out beforehand or after in the view script. The toString method would have the same signature as the currency method but return a string regardless of the values.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-08-08T02:58:05.000+0000</p> 
        <div class="body">
            <p>Closing as won't fix</p>

<p>Two things to note:
You should never directly output content from a database into the view without checking it. And this means also null-values.</p>

<p>And there would be no way to call the toString method from the view helper directly. This would mean that you initiate the helper manually which would negotate the simple use which all view helpers actually provide ($this-&gt;currency, $this-&gt;url,...). $this-&gt;toString does not work... and $this-&gt;currency-&gt;toString would also not be ok because the currency view helper would then work different to all other view helpers.</p>

        </div>
    </div>
    </div>

