<h2>ZF-9094: Binary attachments in examples encoded with Zend_Mime::ENCODING_8BIT</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-02-05T07:51:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-28T03:28:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zoran Zaric (zoran.zaric)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On <a href="http://framework.zend.com/manual/en/zend.mail.attachments.html">http://framework.zend.com/manual/en/…</a> the examples don't work, the images are encoded with Zend_Mime::ENCODING_8BIT, which breakes them, Zend_Mime::ENCODING_BASE64 should be used (as the text says).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-02-05T08:20:27.000+0000</p> 
        <div class="body">
            <p>Reassigned Satoru Yoshida</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-05T18:22:05.000+0000</p> 
        <div class="body">
            <p>Ok, Ramon, I'll see it :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-02-06T06:09:17.000+0000</p> 
        <div class="body">
            <p>Thank you Satoru assigned the you, because I see you involved in issues Zend_Mail ;).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-28T03:28:39.000+0000</p> 
        <div class="body">
            <p>Thank You for report, Solved at SVN r21230</p>

        </div>
    </div>
    </div>

