<h2>ZF-9400: Optionally prevent escaping in Decorators</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2010-03-11T03:09:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4299">ZF-4299</a></li>
            <li><a href="/issues/browse/ZF-7403">ZF-7403</a></li>
            <li><a href="/issues/browse/ZF-5081">ZF-5081</a></li>
            <li><a href="/issues/browse/ZF-2605">ZF-2605</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This needs further investigation as other Decorators may require this too.</p>

<pre class="highlight"><code>
...
    if (false === $this-&gt;getOption('escape')) {
        $view-&gt;setEscape('strval');
    }
...
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

