<h2>ZF-9837: Broken link in Zend_Dojo manual</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-05-14T04:59:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-20T12:10:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Julian Davchev (jmut)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Joel Clermont (jclermont)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13095/ZF-9837-2.patch">ZF-9837-2.patch</a></li>
            <li><a href="/issues/secure/attachment/13090/ZF-9837.patch">ZF-9837.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><a href="http://framework.zend.com/manual/en/zend.dojo.view.html#zend.dojo.view.dijit.layout">http://framework.zend.com/manual/en/…</a></p>

<p>Link "read more about them in the Dojo manual"    is broken</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Julian Davchev (jmut) on 2010-05-14T05:00:04.000+0000</p> 
        <div class="body">
            <p>Lowering priority..definately not major</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Julian Davchev (jmut) on 2010-05-14T05:09:03.000+0000</p> 
        <div class="body">
            <p>Actually all links on that page  to dojotoolkit.org  book are wrong.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Joel Clermont (jclermont) on 2010-05-20T11:59:03.000+0000</p> 
        <div class="body">
            <p>ZF-9837-2.patch contains fixes for all references to the old dojotoolkit.org URLs. The previous patch only caught a few.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-05-20T12:10:56.000+0000</p> 
        <div class="body">
            <p>Patch applied to trunk and 1.10 release branch.</p>

        </div>
    </div>
    </div>

