<h2>ZF-9254: statuses/featured Not in Twitter API</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-24T07:06:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:35.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christopher Thomas (cwt137)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Twitter</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The method statuses/featured is not apart of the Twitter API. <a href="http://apiwiki.twitter.com/Twitter-API-Documentation">http://apiwiki.twitter.com/Twitter-API-Documentati…</a>. If a http client goes to <a href="http://twitter.com/statuses/featured.xml">http://twitter.com/statuses/featured.xml</a> or <a href="http://api.twitter.com/1/statuses/featured.xml">http://api.twitter.com/1/statuses/featured.xml</a>, a 404 is returned, which confirms it is not apart of the API. I propose removing the method userFeatured() in Zend_Service_Twitter and the associated unit test.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shaun Farrell (farrelley) on 2010-05-18T07:10:46.000+0000</p> 
        <div class="body">
            <p>Zend_Service_Twitter should be changing sometime.  Do to Oauth being the only way to authenticate the Twitter classes will not work.</p>

        </div>
    </div>
    </div>

