<h2>ZF-9284: Enable 2LO by making oauth_token optional in Zend/Oauth/Http/Utility.php</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-27T16:24:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-28T05:47:46.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ryan Boyd (rboyd)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Oauth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12810/ZF-9284.patch">ZF-9284.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In 2-legged OAuth, the oauth_token is not used-- requests are made purely based on the consumer key/secret.  Suggest adding a check to Zend_Oauth_Http_Utility::assembleParams so that the oauth_token value is only sent if non-null.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ryan Boyd (rboyd) on 2010-02-27T16:28:31.000+0000</p> 
        <div class="body">
            <p>Attached patch modifies Zend_Oauth_Http_Utility::assembleParams to make the oauth_token param only set if non-null</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-28T05:47:45.000+0000</p> 
        <div class="body">
            <p>Implemented in r21232 and merged to release-1.10 for next mini-release. Thanks for the patch!</p>

        </div>
    </div>
    </div>

