<h2>ZF-9273: Phpdoc Type in Zend_Amf_Parse_Amf0_Deserializer::readReference()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-02-26T07:34:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-28T18:06:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There is a typo in the phpdocs for Zend_Amf_Parse_Amf0_Deserializer::readReference().</p>

<p>The word 'refrence' should be spelt 'reference'.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-27T02:38:24.000+0000</p> 
        <div class="body">
            <p>Thank You for report, Solved at SVN r20391</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Morgan (robsta) on 2010-02-28T06:10:30.000+0000</p> 
        <div class="body">
            <p>Nice Work, I'm glad you picked up on those other typos as well.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-28T18:06:35.000+0000</p> 
        <div class="body">
            <p>Thank You, Rob.
I think who wrote TYPO might write same one elsewhere.
So, I searched and corrected it, and would in future ;-)</p>

        </div>
    </div>
    </div>

