<h2>ZF-9492: change visibility of Zend_Layout::_setMvcEnabled()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-03-20T18:23:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-16T15:51:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Layout</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Current code</p>

<pre class="highlight"><code>
protected function _setMvcEnabled($mvcEnabled)
</code></pre>

<p>Change for</p>

<pre class="highlight"><code>
public function setMvcEnabled($mvcEnabled)
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-03-21T05:19:04.000+0000</p> 
        <div class="body">
            <p>Can you explain the use case for this request?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-03-21T06:51:24.000+0000</p> 
        <div class="body">
            <p>@Matthew 
I do not see much use for the method _setMvcEnabled protected
The value, could be set in the constructor, without the method.</p>

<pre class="highlight"><code>
$layout = new Zend_Layout($options, true);
$layout-&gt;setMvcEnabled(false);   // reset config of the initMvc
</code></pre>

<p>Thanks.</p>

        </div>
    </div>
    </div>

