<h2>ZF-9818: NotEmpty and &quot;0&quot; value not behaving as expected</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-05-09T07:43:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-10T00:13:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Remy Damour (remy215)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>According to online manual:
{quote}Default behaviour for Zend_Validate_NotEmpty</p>

<p>By default, this validator works differently than you would expect when you've worked with PHP's empty() function. In particular, this validator will evaluate both the integer 0 and <em>string '0' as empty</em>.{quote}</p>

<p>Quick test:</p>

<pre class="highlight"><code>
$validator = new Zend_Validate_NotEmpty();
echo (int)$validator-&gt;isValid('0'); // *output: 1*
</code></pre>

<p>Problem comes from default value of $_type set to 237 instead of self::ALL (= 255)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-05-09T09:53:03.000+0000</p> 
        <div class="body">
            <p>No issue...</p>

<p>Zend_Validate_NotEmpty behaves different than empty() because of Zend_Form</p>

<p>When you need php's behaviour of empty() then set the options properly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christopher Thomas (cwt137) on 2010-05-09T09:53:57.000+0000</p> 
        <div class="body">
            <p>A lot of times Zend_Validate is used to validate data from form fields. So, I think the behavior is correct and this is a non issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Remy Damour (remy215) on 2010-05-10T00:13:14.000+0000</p> 
        <div class="body">
            <p>then this is a documentation issue</p>

        </div>
    </div>
    </div>

