<h2>ZF-9218: When entering a page through named route Zend_View_Helper_Url uses that route and not the default anymore</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-20T04:48:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-20T04:52:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                exceptione (exceptione)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The problem is detailed here also: <a href="http://n4.nabble.com/Zend-View-Helper-Url-current-route-td667704.html">http://n4.nabble.com/Zend-View-Helper-Url-current-…</a></p>

<p>When one enters a page via a named router, any call to Zend_View_Helper_Url will generate urls for that named route.</p>

<pre class="highlight"><code>
'shop_product_show' =&gt; new Zend_Controller_Router_Route(
        'shop_products/show/:product_id',
        array(
            'module'        =&gt; 'default',
            'controller'    =&gt; 'shop_products',
            'action'        =&gt; 'show'
        )
    ) 
</code></pre>

<pre class="highlight"><code>
$this-&gt;url(array(
    'module'        =&gt; 'foo',
    'controller'    =&gt; 'bar',
    'action'        =&gt; 'doh'
))

// result: /shop_products/show/1 

$this-&gt;url(array(
    'module'        =&gt; 'foo',
    'controller'    =&gt; 'bar',
    'action'        =&gt; 'doh'
), 'default');

// result: /foo/bar/doh

</code></pre>

<p>This makes Zend_View_Helper_Url brittle, because a template might work fine, until the time you reach the page via a named route.</p>

<p>The linked page contains a possible solution:
{quote}
For instance, when I change lines in Zend_View_Helper_Url::url() from:</p>

<pre class="highlight"><code>
if (empty($name)) {
   try {
      $name = $router-&gt;getCurrentRouteName();
    } catch (Zend_Controller_Router_Exception $e) {
      $name = 'default';
    }
}
</code></pre>

<p>to:</p>

<pre class="highlight"><code>
if (empty($name)) {
   $name = 'default';
}
</code></pre>

<p>I obtain expected behavior
{quote}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-20T04:52:33.000+0000</p> 
        <div class="body">
            <p>It is duplicate of ZF-9216.</p>

        </div>
    </div>
    </div>

