<h2>ZF-9680: Fatal error: Call to a member function isDeleted() on a non-object in Zend/Search/Lucene.php on line 709</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-04-15T02:37:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-09-21T04:06:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Code to reproduce:</p>

<p>$Zend_Search_Lucene_Proxy = Zend_Search_Lucene::create('/tmp/LuceneSearchEngine');
$Zend_Search_Lucene_Proxy-&gt;setMaxBufferedDocs(500);
$Zend_Search_Lucene_Proxy-&gt;setMergeFactor(5);
$Zend_Search_Lucene_Proxy-&gt;maxDoc();
$doc = new Zend_Search_Lucene_Document();
$doc-&gt;addField(Zend_Search_Lucene_Field::Keyword('<strong>id</strong>', 'myId'));
$doc-&gt;addField(Zend_Search_Lucene_Field::UnStored('bla', 'blubb'));
$Zend_Search_Lucene_Proxy-&gt;addDocument($doc);
$Zend_Search_Lucene_Proxy-&gt;maxDoc();
$Zend_Search_Lucene_Proxy-&gt;isDeleted(0);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2010-05-20T23:43:57.000+0000</p> 
        <div class="body">
            <p>Fixed in r22220.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2010-09-21T03:54:08.000+0000</p> 
        <div class="body">
            <p>Merged into release branch</p>

        </div>
    </div>
    </div>

