<h2>ZF-9225: Zend_Filter_Inflector:&gt;setConfig() throws the exception 'Zend_Loader_PluginLoader_Exception'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-21T16:24:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-07T11:59:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Filter_Inflector</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-8997">ZF-8997</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12780/ZF-9225.zip">ZF-9225.zip</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Filter_Inflector:&gt;setConfig(), problem to set the option 'filterPrefixPath'.
Zend_Filter_Inflector:&gt;addFilterPrefixPath(), should be called before of Zend_Filter_Inflector:&gt;addRules($value);</p>

<p>case</p>

<pre class="highlight"><code>
$options = array(
    'target' =&gt; ':controller/:action',
    'rules'  =&gt; array(
        ':action'     =&gt; 'Custom',
        ':controller' =&gt; 'Word_CamelCaseToDash'
    ),
    'filterPrefixPath' =&gt; array('My_Filter_' =&gt; 'My/Filter/')
);

new Zend_Filter_Inflector(new Zend_Config($options));
</code></pre>

<p>Will cause an exception because the configuration of the path is after setting the 'rules'. See line 508 in Zend_Filter_Inflector.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-02-21T16:49:32.000+0000</p> 
        <div class="body">
            <p>code reproduced in ZF-9225.zip</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-07T01:45:37.000+0000</p> 
        <div class="body">
            <p>@Ramon:
Why did you attach this issue manually to me?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-07T01:49:25.000+0000</p> 
        <div class="body">
            <p>Example and Description Header do not match...
In non of your examples "setConfig()" is called.</p>

<p>This method is deprecated and will not be called by the Inflector itself.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-03-07T06:22:35.000+0000</p> 
        <div class="body">
            <p>@Thomas
Attaches to you because you were looking at the issue ZF-8997 ;).
With the resolution of the issue ZF-8997, Zend_Filter_Inflector:&gt;setConfig() has become obsolete.</p>

<p>But this occurs in Zend_Filter_Inflector:&gt; setOptions() also.</p>

<p>No problem</p>

<pre class="highlight"><code>
$options = array(
    'target' =&gt; ':controller/:action',
    'filterPrefixPath' =&gt; array('My_Filter_' =&gt; 'My/Filter/')
    'rules'  =&gt; array(
       ':action'     =&gt; 'Custom',
       ':controller' =&gt; 'Word_CamelCaseToDash'
     ), 
);
Zend_Filter_Inflector:&gt;setOptions($options);
</code></pre>

<p>Problem</p>

<pre class="highlight"><code>
$options = array(
    'target' =&gt; ':controller/:action',
    'rules'  =&gt; array(
       ':action'     =&gt; 'Custom',
       ':controller' =&gt; 'Word_CamelCaseToDash'
     ),
    'filterPrefixPath' =&gt; array('My_Filter_' =&gt; 'My/Filter/')
);
Zend_Filter_Inflector:&gt;setOptions($options);
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-07T11:59:03.000+0000</p> 
        <div class="body">
            <p>Fixed with r21372</p>

        </div>
    </div>
    </div>

