<h2>ZF-9457: addTranslation blowing up with 'failed to open dir: Too many open files'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-18T05:28:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-18T06:18:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ashley Kitson (akzincdig)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>ZF Version 1.11.0dev</p>

<p>Following error is being thrown
SEVERITY: E_USER_ERROR
ERRNO: 0
TEXT: RecursiveDirectoryIterator::__construct(/usr/local/ZWare/lib/ZWMod/default/language/.svn/tmp/prop-base): failed to open dir: Too many open files
LOCATION: /usr/local/ZWare/lib/Zend/Translate/Adapter.php, line 177
Showing backtrace:
[9] RecursiveDirectoryIterator.__construct("/usr/local/ZWare/lib/ZWMod/default/language/.svn/tmp/prop-base", "0") # line    0, file: unknown
[8] RecursiveDirectoryIterator.getChildren() # line  177, file: /usr/local/ZWare/lib/Zend/Translate/Adapter.php
[7] Zend_Translate_Adapter.addTranslation("/usr/local/ZWare/lib/ZWMod/default/language") # line    0, file: unknown
[6] call_user_func_array(Array[2], Array[1]) # line  175, file: /usr/local/ZWare/lib/Zend/Translate.php
[5] Zend_Translate.__call("addTranslation", Array[1]) # line    0, file: unknown
[4] Zend_Translate.addTranslation("/usr/local/ZWare/lib/ZWMod/default/language") # line  131, file: /usr/local/ZWare/lib/ZWare/Service/Language.php
[3] ZWare_Service_Language.addTranslation("/usr/local/ZWare/lib/ZWMod/default/language") # line  100, file: /usr/local/ZWare/lib/ZWare/Service/Module.php
[2] ZWare_Service_Module.load() # line   45, file: /var/www/vhosts/ffx/application/bootstrap.php
[1] include("/var/www/vhosts/ffx/application/bootstrap.php") # line    2, file: /var/www/vhosts/ffx/httpdocs/index.php</p>

<p>Zend_Translate is initially being set up as follows:
self::$_translator = new Zend_Translate('tmx',$dir,null,array('ignore' =&gt; '.')); //$dir = /usr/local/ZWare/lib/ZWare/language</p>

<p>It is then subsequently called to add new translation paths with:
self::$_translator-&gt;addTranslation($source);</p>

<p>Language file caching is being used.</p>

<p>It appears that even though we want to ignore file paths with . (i.e. to avoid .svn) the recursive iterator at l176 of Zend_Translate_Adapter is not ignoring them during its directory scan and is running out of file handles.  I increased PHP memory to 256MB from 128MB and this <em>appears</em> to have solved the problem.  I don't think you can do anything with this unless you replace the recursivedirectoryiterator with the way we used to do these things or perhaps file a request upstream to PHP devs to allow filtering in the iterator.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-18T06:11:26.000+0000</p> 
        <div class="body">
            <p>Closing as non-issue</p>

<p>We can not remove SPL methodology. The problem is that the mass of files you are looping through is too much.</p>

<p>The only solution would be
* To add more memory
* To avoid searching that much files/directories (by collecting together into one or a handful directories instead of searching the whole HDD)
* File an issue within PHP</p>

        </div>
    </div>
    </div>

