<h2>ZF-9658: headMeta() modifiers</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2010-04-12T08:33:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I am trying to make my XHTML 1.0  Strict validation and I get an error.  I have some Meta Tag information that is in French while the rest of the site is in English.</p>

<p>XHTML1.0 requires that you declare the "xml:lang" attribute whenever you declare the "lang" attribute.  However try as I might I can't get the headMeta-&gt;appendName() method to accept the "xml:lang" modifier, but it does accept the "lang" modifier.</p>

<p>Thank-you</p>

<p>sylvain</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by __jul__ (__jul__) on 2010-04-17T17:25:59.000+0000</p> 
        <div class="body">
            <p>I think this should be a "Bug" instead of a "Coding Standards Violation".</p>

        </div>
    </div>
    </div>

