<h2>ZF-9348: Zend_Form isValid() does not validate SubForm with equal named Child Element</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2010-03-05T21:33:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-31T09:18:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7793">ZF-7793</a></li>
            <li><a href="/issues/browse/ZF-3393">ZF-3393</a></li>
            <li><a href="/issues/browse/ZF-9327">ZF-9327</a></li>
            <li><a href="/issues/browse/ZF-5801">ZF-5801</a></li>
            <li><a href="/issues/browse/ZF-3924">ZF-3924</a></li>
            <li><a href="/issues/browse/ZF-8022">ZF-8022</a></li>
            <li><a href="/issues/browse/ZF-8203">ZF-8203</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When adding a SubForm with Name foo and an Element to that SubForm which
is named foo as well, isValid fails to validate the Elements Value.</p>

<p>Following is happening:
the call</p>

<pre class="highlight"><code>
$data = $this-&gt;_dissolveArrayValue($data, $this-&gt;getElementsBelongTo());
</code></pre>

<p>will convert</p>

<pre class="highlight"><code>
$data = array('foo'=&gt; array('bar' =&gt; $wantedData));
$elementsBelongTo = foo[bar]
</code></pre>

<p>into</p>

<pre class="highlight"><code>
$data = $wantedData;
</code></pre>

<p>But only if isArray() === true.</p>

<p>So when a SubForm which (isArray() === true) by default, has a child with the same name</p>

<pre class="highlight"><code>
$subforname  = 'baz'
$elementname = 'baz'
$elementsBelongTo = 'foo[bar]'
$data = array('foo' =&gt; array('bar' =&gt; array('baz' =&gt; 'Element Value')));

($data = array('baz' =&gt; 'Element Value')) === $this-&gt;_dissolveArrayValue($data, $elementsBelongTo);
</code></pre>

<p>and then later on</p>

<pre class="highlight"><code>
if (isset($data[$key])) {
    /**
     * yes because array('baz' =&gt; 'Element Value');
     */
    $valid = $form-&gt;isValid($data[$key]) &amp;&amp; $valid;
    /**
     * OOuuuchh
     */
}
</code></pre>

<p>My Statement is that _dissolveArrayValue should be called even when !isArray()
because that does not matter anyway as ElementsBelongTo returns $formName when !isArray()
and then _dissolveArrayValue will dissolve for $formName instead of $elementsBelongTo.</p>

<p>So now i know that this is wrong because $form-&gt;getElementsBelongTo() returns the name only when
(true === $form-&gt;isArray() &amp;&amp; null === $form-&gt;_elementsBelongTo)</p>

<p>So the right solution is</p>

<pre class="highlight"><code>
if (isset($data[$key]) &amp;&amp; !$form-&gt;isArray()) {
    /**
     * now we can be sure that $this-&gt;_dissolveArrayValue did not dissolve anything
     */
    $valid = $form-&gt;isValid($data[$key]) &amp;&amp; $valid;
}
</code></pre>

<p>Word.</p>

<p>This patch definitely fixes the issue.</p>

<pre class="highlight"><code>
Index: tests/Zend/Form/FormTest.php
===================================================================
--- tests/Zend/Form/FormTest.php        (Revision 21667)
+++ tests/Zend/Form/FormTest.php        (Arbeitskopie)
@@ -1473,7 +1473,25 @@
         $this-&gt;assertTrue($this-&gt;form-&gt;isValid($data));
     }
 
+    public function testIsValidEqualSubFormAndElementName()
+    {
+        $this-&gt;form-&gt;addSubForm(new Zend_Form_SubForm(), 'foo')
+                   -&gt;foo-&gt;addElement('text', 'foo')
+                        -&gt;foo-&gt;setRequired(true)
+                             -&gt;addValidator('Identical',
+                                            false,
+                                            array('Foo Value'));
+        $foo = array('foo' =&gt;
+                     array('foo' =&gt; 'Foo Value'));
 
+        $this-&gt;assertTrue($this-&gt;form-&gt;isValid($foo));
+
+        $this-&gt;form-&gt;foo-&gt;setIsArray(false);
+
+        $this-&gt;assertTrue($this-&gt;form-&gt;isValid($foo));
+    } 
+
+
     // Display groups
 
     public function testCanAddAndRetrieveSingleDisplayGroups()
Index: library/Zend/Form.php
===================================================================
--- library/Zend/Form.php       (Revision 21667)
+++ library/Zend/Form.php       (Arbeitskopie)
@@ -2044,7 +2044,7 @@
             if (null !== $translator &amp;&amp; !$form-&gt;hasTranslator()) {
                 $form-&gt;setTranslator($translator);
             }
-            if (isset($data[$key])) {
+            if (isset($data[$key]) &amp;&amp; !$form-&gt;isArray()) {
                 $valid = $form-&gt;isValid($data[$key]) &amp;&amp; $valid;
             } else {
                 $valid = $form-&gt;isValid($data) &amp;&amp; $valid;
</code></pre>

<p>And for Rob :)</p>

<pre class="highlight"><code>
    public function testIsValidEqualSubFormAndElementName()
    {
        $this-&gt;form-&gt;addSubForm(new Zend_Form_SubForm(), 'foo')
                   -&gt;foo-&gt;addElement('text', 'foo')
                        -&gt;foo-&gt;setRequired(true)
                             -&gt;addValidator('Identical',
                                            false,
                                            array('Foo Value'));
        $foo = array('foo' =&gt;
                     array('foo' =&gt; 'Foo Value'));


        $this-&gt;assertTrue($this-&gt;form-&gt;isValid($foo));

        $this-&gt;form-&gt;foo-&gt;setIsArray(false);

        $this-&gt;assertTrue($this-&gt;form-&gt;isValid($foo));
    }
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-29T06:06:57.000+0000</p> 
        <div class="body">
            <p>Updated the Test, checks now against $form-&gt;setIsArray(false) as well.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-03-31T09:18:06.000+0000</p> 
        <div class="body">
            <p>Patch applied to trunk and 1.10 release branch.</p>

        </div>
    </div>
    </div>

