<h2>ZF-959: Simplification for Zend_Locale</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2007-02-23T13:38:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-948">ZF-948</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Actally while integrating some new functions for Zend_Locale I looked through the actual API and found that it needs a little bit tweaking...</p>

<p>Actually I am speaking of the localizing functions:
getLanguageDisplay
getScriptDisplay
getCalendarDisplay and so on</p>

<p>I think for simplification it would be better to have them combined.</p>

<p>getDisplay($what, $detail, $locale)
getDisplay('country', 'AT', $locale);</p>

<p>getList($what, $locale);
getList('script', 'arab', $locale);</p>

<p>The following details and lists will be added :
Language, Script, Country, Territory, Calendar, Timezone, Timezone_Short, Currency, Currency_Sign, Currency_Detail, Territory_Detail, Language_Detail</p>

<p>Instead of 24 functions we will have only 2 functions which simplifies the API.</p>

<p>Thoughts, Opinion ??</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-23T13:48:33.000+0000</p> 
        <div class="body">
            <p>Yes it does reduce the number of functions, and it may help to reduce code duplication.  But then the developer must know which values are legal for the $what argument.</p>

<p>Also people who use code-completion tools may have an easier time understanding the explicit function names like getLanguageDisplay(), instead of getDisplay().</p>

<p>Also the unit tests give more assurance that we have tested all types of Display and List functions because code coverage tells us that we have tested each function.  If you combine the functions into 2 functions, then code coverage will only tell us that we have covered at least one type of display or list, not all of them.</p>

<p>One idea is that you can implement getDisplay() and getList() as you have described with a $what argument.  Then keep all the other functions but they are very simple:  they only call getDisplay() and getList() with the correct value for the $what argument.</p>

<p>Those are some thoughts.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-23T14:15:20.000+0000</p> 
        <div class="body">
            <p>I would only have the often called types with two seperated functions because I dont think that Timezone_Short names or Territory_Details are often called.</p>

<p>So we would have</p>

<p>getDisplay
getLanguageDisplay
getCountryDisplay
getCurrencyDisplay
getTerritoryDisplay</p>

<p>and the related List functions. This is like with Zend_Date... the often used types like Time, Iso, Hour have an own function but Date_Medium or Hour_Short have not.</p>

<p>And I also think that "Display" is not the right word...</p>

<p>"Name" or "Data" is more related to what the functions does.</p>

<p>getLanguageData.... 
Data seems to me better than Display.</p>

<p>Also some of these functions do not return display strings. This is why I think "Data" is more related.</p>

<p>Additionally when calling getData or getList without parameter a list of all useable parameters will be returned.</p>

<p>This are my additionally thoughts...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-25T03:04:23.000+0000</p> 
        <div class="body">
            <p>I had an discussion today in the zf channel.
We had come to the conclusion that we should change this function names to a more speaking one which is recognised also by non english people.</p>

<p>getTranslation
getTranslationList</p>

<p>would better say what this functions are doing.
Then we would additionally have</p>

<p>getLanguageTranslation
getCountryTranslation
getScriptTranslation
getTerritoryTranslation</p>

<p>and the related getxxxTranslationList functions.
Even if the names of the functions are now longer, they do more say what they should return which is better for the user.</p>

<p>I already implemented the List functions based on the old naming and adpoted the docu to reflect what information now can be used without the need of translating them.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-28T15:13:46.000+0000</p> 
        <div class="body">
            <p>Resolved with SVN 3675.</p>

<p>Also unit tests and docu has been reworked / added.</p>

        </div>
    </div>
    </div>

