<h2>ZF-9979: Function Cache makeid 'Incorrect function name'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-06-11T03:36:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-06-30T10:35:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.7 (28/Jul/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Bennewitz (private) (mabe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9422">ZF-9422</a></li>
            <li><a href="/issues/browse/ZF-2066">ZF-2066</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using call like in the call_user_func_array docs example <a href="http://php.net/manual/en/function.call-user-func-array.php">http://php.net/manual/en/…</a>, if we try to call the method of an object, it throws Zend_Cache::throwException('Incorrect function name');</p>

<p>Example:
$api = new MyApi();
$xml = $cache-&gt;call(array($api, 'searchProducts'), $args);</p>

<p>So I would modify the "incorrect..." by this:
if (!is_string($name)) {
    //Zend_Cache::throwException('Incorrect function name');
    $name = print_r($name, true);
}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mauro Asprea (brutuscat) on 2010-06-25T03:39:00.000+0000</p> 
        <div class="body">
            <p>To clarify, this is how the _makeid of the Zend_Cache_Frontend_Function should look like:</p>

<pre><code>private function _makeId($name, $parameters)
{
    if (!is_string($name)) {
        //Zend_Cache::throwException('Incorrect function name');
        $name = print_r($name, true);
    }
    if (!is_array($parameters)) {
        Zend_Cache::throwException('parameters argument must be an array');
    }
    return md5($name . serialize($parameters));
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-06-29T10:21:07.000+0000</p> 
        <div class="body">
            <p>I committed some changes to the function frontend to allow all types of callbacks.
(r22503 @ trunk)</p>

<p>Please tell me if it will close your issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2010-06-30T10:06:32.000+0000</p> 
        <div class="body">
            <p>fixed in r22504 (1.10 branch) &amp; r22503 (trunk)</p>

        </div>
    </div>
    </div>

