<h2>ZF-917: Zend_Controller Unit Tests failing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-02-15T08:32:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Michal Minicki (martel)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>1) testAssembleNoModuleOrController(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that  is equal to &lt;string:defctrl/act/foo/bar&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:128</p>

<p>2) testAssembleNoController(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that  is equal to &lt;string:mod/defctrl/act/foo/bar&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:163</p>

<p>3) testAssembleNoActionWithParams(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that &lt;string:mod/ctrl&gt; is equal to &lt;string:mod/ctrl/defact/foo/bar&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:184</p>

<p>4) testAssembleNoModuleOrControllerMatched(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that  is equal to &lt;string:defctrl/act/foo/bar&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:196</p>

<p>5) testAssembleModuleAndControllerMatched(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that  is equal to &lt;string:m/ctrl/act/foo/bar&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:223</p>

<p>6) testAssembleNoControllerMatched(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that  is equal to &lt;string:mod/defctrl/act/foo/bar&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:236</p>

<p>7) testAssembleNoActionMatched(Zend_Controller_Router_Route_ModuleTest)
Failed asserting that  is equal to &lt;string:def/con&gt;.
/home/sebastian/Work/ZendFramework/tests/Zend/Controller/Router/Route/ModuleTest.php:248</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-02-15T09:07:34.000+0000</p> 
        <div class="body">
            <p>What version of PHP are you using? I ran tests a few minutes ago, and they ran fine on PHP 5.2.1.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-02-15T09:22:51.000+0000</p> 
        <div class="body">
            <p>Martel is doing some work on the Module router and rewrite router, and these will be fixed within the next few hours.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-02-15T10:06:54.000+0000</p> 
        <div class="body">
            <p>5.2.1 as well.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michal Minicki (martel) on 2007-02-15T13:38:51.000+0000</p> 
        <div class="body">
            <p>Everything should be working smoothly again.</p>

<p>Thanks for paying attention for such things, Sebastian :)</p>

        </div>
    </div>
    </div>

