<h2>ZF-949: Fixes for Example: Simplified access of authorization ids</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2007-02-22T14:03:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Session</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The require_once upon Zend_Auth_Result is not needed, since the adapter interface already includes the class.</p>

<p>The Zend_Session_Namespace instantiations are missing the "new" keyword.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-02-22T14:15:00.000+0000</p> 
        <div class="body">
            <p>Fixed in SVN <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=3566">r3566</a></p>

        </div>
    </div>
    </div>

