<h2>ZF-9869: The load method on the memcached can only fetch one key at a time</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-05-20T14:38:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-01-09T19:30:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Marc Bennewitz (private) (mabe)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9370">ZF-9370</a></li>
            <li><a href="/issues/browse/ZF-10874">ZF-10874</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently, the load() method on the memcached backend does not support fetching more than one key at a time. Hence, fetching a hundred keys requires a hundred calls.</p>

<p>A lot of resources would be saved if one could do bulk fetching. The memcached driver (and a lot of the other backends, e.g. xcache and apc) support bulk fetching out of the box. Creating a new method (for example, loadArrayOfIds()) would make it possible to keep BC compatibility whilst adding this helpful functionality.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Bennewitz (private) (mabe) on 2012-01-09T19:30:07.000+0000</p> 
        <div class="body">
            <p>this issue won't be fixed in ZF1
-&gt; fixed in ZF2-134</p>

        </div>
    </div>
    </div>

