<h2>ZF-9249: Inconsistent line ending style in Zend_Http_Client</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2010-02-24T01:50:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-24T17:44:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Http_Client</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Line 78 ending with CRLF</p>

<p>lestr@lestr-nb:~/ext/svn/ZendFramework/trunk$ svn blame library/Zend/Http/Client.php |head -n 78|tail -n 1
 19706  maartenba     const CONNECT = 'CONNECT';</p>

<p>its same on releace branche</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-02-24T17:44:23.000+0000</p> 
        <div class="body">
            <p>Thank You for Report, Solved at r21203.</p>

        </div>
    </div>
    </div>

