<h2>ZF-9724: Allow changing dispatcher class via application configuration file</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-04-21T06:37:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-12T19:18:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application</li>
            <li>zf-crteam-review</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14932/ZF-9724.patch">ZF-9724.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello 
using zend_application frontController resource plugin, i can't set the dispatcher class i want to use. what we can did old days using An instance from frontController</p>

<p>$frontController-&gt;setDispatcher(Whatever_Dispatcher());</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-24T03:47:56.000+0000</p> 
        <div class="body">
            <p>Downgrading this to an "Improvement" request, as being able to override dispatcher from application.ini is not a common use case and there are workarounds (like a Zend_Application resource plugin)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-24T04:01:11.000+0000</p> 
        <div class="body">
            <p>I've attached a patch which implements the requested feature + unit test and manual page update (en)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-05-12T19:18:11.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk (1.12.0): r24798</p>

        </div>
    </div>
    </div>

