<h2>ZF-9561: Zend_Mail_Protocol_Imap::readResponse ignoring final line of return</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-29T03:02:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mark Graeme McIntyre (mark.mcintyre@everlution.com)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail_Storage</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Mail_Protocol_Imap::readResponse contains the following code:</p>

<pre class="literal">
302 $lines = array();
303 while (!$this-&gt;readLine($tokens, $tag, $dontParse)) {
304     $lines[] = $tokens;
305 }
306 
307 if ($dontParse) {
308     // last to chars are still needed for response code
309     $tokens = array(substr($tokens, 0, 2));
310 }   
311 // last line has response code
312 if ($tokens[0] == 'OK') {
313     return $lines ? $lines : true;
314 } else if ($tokens[0] == 'NO'){
315     return false;
316 }   
317 return null;
</pre>

<p>This fails to allow collection of final line of response, crucial for operations such as IMAP COPY (on servers implementing UIDPLUS) where new UID is generated and returned in final line of response:
" OK [COPYUID ] Done"</p>

<p>Zend_Mail_Protocol_Imap::readResponse should include final line in return</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Mark Graeme McIntyre (mark.mcintyre@everlution.com) on 2010-03-29T03:04:56.000+0000</p> 
        <div class="body">
            <p>Fixed Description formatting</p>

        </div>
    </div>
    </div>

