<h2>ZF-9804: Zend_Mime* throw Zend_Mime_Exception rather than Zend_Exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-05-05T03:19:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-30T07:19:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>Next Major Release ()</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Andy Thompson (at465)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mime</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13055/zfmimeexception.patch">zfmimeexception.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have need of being able to catch mime component exceptions separately from other zend exceptions. Zend_Mime_Decode and Zend_Mime_Message both throw Zend_Exception, which I think should throw Zend_Mime_Exception.</p>

<p>I'll include a patch with the changes.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-06-12T06:26:23.000+0000</p> 
        <div class="body">
            <p>Sorry, I have been inactive since last April.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-06-21T14:46:09.000+0000</p> 
        <div class="body">
            <p>came back :)</p>

        </div>
    </div>
    </div>

