<h2>ZF-9430: Zend_Form issue on setName() all elements</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2010-03-16T02:24:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-22T13:38:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Steven Vandeputte (steven.vandeputte)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I want to change the name of every element in my form by adding a prefix.
Below you can see the code that I used in my controller.</p>

<p>{Code}
//Code in controller
$form = new Zend_Form();
$txtField = new Zend_Form_Element_Text('txtElement');
$form-&gt;addElement($txtField);</p>

<p>$elements = $form-&gt;getElements();
foreach($elements as $element){
   $element-&gt;setName('search_'.$element-&gt;getName());
}</p>

<p>$this-&gt;view-&gt;form = $form;
{Code}</p>

<p>Now I expect that every element in my form has the prefix 'search_'.
It works fine for the textfield itself and the dt elements but there's a problem with the dd element that doesn't change.
Below you can see the html output.</p>

<p>{Code}
//output html</p>


   <dl class="zend_form"><dt> </dt>
      <dd>   ==&gt;here I expect "search_txtElement-element"
         </dd>
   </dl>

<p>{Code}</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-03-16T07:18:53.000+0000</p> 
        <div class="body">
            <p>This cannot work at the moment as the id is set up for Zend_Decorator_HtmlTag
in Zend_Form_Element::loadDefaultDecorators() when constructing the element.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-04-22T13:38:41.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk and sheduled for next minor release. See parent ZF-6741.</p>

        </div>
    </div>
    </div>

