<h2>ZF-9076: Allow string in Zend_Form constructor to set &quot;action&quot; attribute</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-03T18:46:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-04T17:13:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Phil Brown (philbrown)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I often find 90% of my forms are instantiated like this</p>

<pre class="highlight"><code>
$form = new Zend_Form(array('action' =&gt; '/some/action/url/path'));
</code></pre>

<p>Any chance we could get the constructor slightly modified as below</p>

<pre class="highlight"><code>
public function __construct($options = null)
{
    if (is_string($options)) {
        $options = array('action' =&gt; $options);
    }
    
    // the rest is unmodified
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-02-04T05:15:35.000+0000</p> 
        <div class="body">
            <p>You can always extend Zend_Form in your own library to provide this logic, and then extend that class in all your forms. :)</p>

<p>We won't do this in ZF, however, as it's unclear what a string argument would be:
* the form name?
* the form action?
* the form method?
All three of those values are strings, and any one of them may be a default condition you want to set.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Phil Brown (philbrown) on 2010-02-04T17:12:59.000+0000</p> 
        <div class="body">
            <p>Ah, but the form action is the only required HTML attribute. Anyway, extending the class is exactly what I'm currently doing.</p>

        </div>
    </div>
    </div>

