<h2>ZF-966: Notices when running Unit Tests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-02-25T02:52:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Notice: Undefined offset:  3 in /home/sebastian/Work/ZendFramework/library/Zend/Locale/Data.php on line 381</p>

<p>Call Stack:
    0.0002      53048   1. {main}() /opt/php/bin/phpunit:0
    0.0024     168772   2. require('/opt/php/lib/php/PHPUnit/TextUI/Command.php') /opt/php/bin/phpunit:44
    0.0658    2696744   3. PHPUnit_TextUI_Command::main() /opt/php/lib/php/PHPUnit/TextUI/Command.php:401
    3.2811   35920752   4. PHPUnit_TextUI_TestRunner-&gt;doRun() /opt/php/lib/php/PHPUnit/TextUI/Command.php:100
    3.2816   35921772   5. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/TextUI/TestRunner.php:247
    3.5449   35932776   6. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    4.5956   37490892   7. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    7.6787   37711220   8. PHPUnit_Framework_TestSuite-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:491
    7.6787   37711220   9. PHPUnit_Framework_TestCase-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:510
    7.6787   37711220  10. PHPUnit_Framework_TestResult-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:223
    7.6788   37711220  11. PHPUnit_Framework_TestCase-&gt;runBare() /opt/php/lib/php/PHPUnit/Framework/TestResult.php:529
    7.6789   37711220  12. PHPUnit_Framework_TestCase-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:243
    7.6789   37711220  13. ReflectionMethod-&gt;invoke() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:300
    7.6789   37711220  14. Zend_DateTest-&gt;testSub() /home/sebastian/Work/ZendFramework/tests/Zend/DateTest.php:0
    8.8502   37736584  15. Zend_Date-&gt;sub() /home/sebastian/Work/ZendFramework/tests/Zend/DateTest.php:3122
    8.8780   37738488  16. Zend_Date-&gt;get() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:1064
    8.8798   37737196  17. Zend_Date-&gt;toString() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:873
    8.8800   37737196  18. Zend_Date-&gt;get() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:451
    8.8801   37737196  19. Zend_Locale_Data::getContent() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:657</p>

<p>Notice: Undefined index:  sun in /home/sebastian/Work/ZendFramework/library/Zend/Date.php on line 658</p>

<p>Call Stack:
    0.0002      53048   1. {main}() /opt/php/bin/phpunit:0
    0.0024     168772   2. require('/opt/php/lib/php/PHPUnit/TextUI/Command.php') /opt/php/bin/phpunit:44
    0.0658    2696744   3. PHPUnit_TextUI_Command::main() /opt/php/lib/php/PHPUnit/TextUI/Command.php:401
    3.2811   35920752   4. PHPUnit_TextUI_TestRunner-&gt;doRun() /opt/php/lib/php/PHPUnit/TextUI/Command.php:100
    3.2816   35921772   5. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/TextUI/TestRunner.php:247
    3.5449   35932776   6. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    4.5956   37490892   7. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
    7.6787   37711220   8. PHPUnit_Framework_TestSuite-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:491
    7.6787   37711220   9. PHPUnit_Framework_TestCase-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:510
    7.6787   37711220  10. PHPUnit_Framework_TestResult-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:223
    7.6788   37711220  11. PHPUnit_Framework_TestCase-&gt;runBare() /opt/php/lib/php/PHPUnit/Framework/TestResult.php:529
    7.6789   37711220  12. PHPUnit_Framework_TestCase-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:243
    7.6789   37711220  13. ReflectionMethod-&gt;invoke() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:300
    7.6789   37711220  14. Zend_DateTest-&gt;testSub() /home/sebastian/Work/ZendFramework/tests/Zend/DateTest.php:0
    8.8502   37736584  15. Zend_Date-&gt;sub() /home/sebastian/Work/ZendFramework/tests/Zend/DateTest.php:3122
    8.8780   37738488  16. Zend_Date-&gt;get() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:1064
    8.8798   37737196  17. Zend_Date-&gt;toString() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:873
    8.8800   37737196  18. Zend_Date-&gt;get() /home/sebastian/Work/ZendFramework/library/Zend/Date.php:451</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2007-02-25T03:29:47.000+0000</p> 
        <div class="body">
            <p>This issue has already been fixed as with SVN 3611.</p>

        </div>
    </div>
    </div>

