<h2>ZF-9158: Zend_View_Helper_PartialLoop - accept additional parameters to pass to partial</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-12T10:15:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:37.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using partialLoop it would be good to be able to pass in an additional array of parameters to be assigned as the same view variables in every iteration of the partial.</p>

<p>For example consider the following:</p>

<p>{{$this-&gt;partialLoop('/blogpostitems.phtml',$this-&gt;blogentries);}}</p>

<p>It may be that blogpostitems.phtml can do several things when rendering blog post items, including displaying comments, allow comment posts etc..  So, ideally a 4th parameter could allow us to pass in 'configuration' data to blogposts.phtml.  For example:</p>

<p>{{$this-&gt;partialLoop('/blogpostitems.phtml',$this-&gt;blogentries,null,array('showComments'=&gt;true,'allowCommentPosts'=&gt;true));}}</p>

<p>Assigning the 4th array of parameters as view variable and consequently allowing:</p>

<p>{{if ($this-&gt;showComments)....  etc.}}</p>

<p>I've seen work arounds which involve assigning variables to placeholders or the layout, but in my mind they're not pretty.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

