<h2>ZF-9378: LDAP auth passw bug?</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-09T05:24:24.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-15T07:58:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Stefan Gehrig (sgehrig)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Ldap</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In LDAP auth, if you type a correct username and password.
And then if you type some other random characters after your correct password it will be correct.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stefan Gehrig (sgehrig) on 2010-03-09T10:26:16.000+0000</p> 
        <div class="body">
            <p>Please provide some more information on what you do (code snippet to reproduce the behavior). It's aso important to get some more info on which LDAP server you're using and what's really happening on the server (server log files),</p>

<p>Generally it's highly doubtable that Zend_Ldap is doing something wrong here as it's not able to bind you to an LDAP server with wrong credentials given that the server is configured correctly.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stefan Gehrig (sgehrig) on 2010-03-15T07:58:32.000+0000</p> 
        <div class="body">
            <p>Cannot be reproduced. No further information given.</p>

        </div>
    </div>
    </div>

