<h2>ZF-9657: incorrect case error in Zend_Amf_Request</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-04-12T08:00:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Amf_Request::initialize() method throws an exception on case-sensitive file systems due to incorrect case preventing the autoloader from including Zend_Amf_Parse_Amf0_Deserializer.</p>

<p>The Deserializer.php file is found in the 'Zend/Amf/Parse/Amf0/' folder, not 'Zend/Amf/Parse/AMF0/'</p>

<p>I fixed this issue on my own system by replacing</p>

<p>$this-&gt;_deserializer = new Zend_Amf_Parse_AMF0_Deserializer($this-&gt;_inputStream);</p>

<p>with</p>

<p>$this-&gt;_deserializer = new Zend_Amf_Parse_Amf0_Deserializer($this-&gt;_inputStream);</p>

<p>If I can provide any more information that may be of use to you, please ask.</p>

<p>Thanks</p>

<p>Matt</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matt Pearson (_pez) on 2010-04-12T08:11:19.000+0000</p> 
        <div class="body">
            <p>Sorry. I see that this issue has been resolved in 1.7.8. Please close this issue.</p>

<p>Thanks guys :)</p>

<p>Matt</p>

        </div>
    </div>
    </div>

