<h2>ZF-9954: formErrors : this decorator is badly written</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-06-07T03:05:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-09T08:29:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                coba (coba)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-11151">ZF-11151</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13211/FormErrors.php.patch">FormErrors.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>let's me show you this method :</p>

<pre class="highlight"><code>
   /**
     * Get showCustomFormErrors
     * 
     * @return bool
     */
    public function getShowCustomFormErrors()
    {
        if (null === $this-&gt;_showCustomFormErrors) {
            if (null === ($how =  $this-&gt;getOption('showCustomFormErrors'))) {
                $this-&gt;setShowCustomFormErrors($this-&gt;_defaults['showCustomFormErrors']);
            } else {
                $this-&gt;setShowCustomFormErrors($show);
                $this-&gt;removeOption('showCustomFormErrors');
            }
        }
    }
</code></pre>

<p>1/ this method is apparently a getter and there is no return instruction.
2/ We have two variables : $how and $show.</p>

<p>Same errors with getOnlyCustomFormErrors().</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-06-07T03:46:26.000+0000</p> 
        <div class="body">
            <p>This was fixed in <a href="http://framework.zend.com/code/changelog/Standard_Library?cs=22316">http://framework.zend.com/code/changelog/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by jah (jahra) on 2010-07-13T08:31:50.000+0000</p> 
        <div class="body">
            <p>Please apply the attached patch which fixes the typo mentioned in the original comment ({{$how}} instead of {{$Show}}).</p>

        </div>
    </div>
    </div>

