<h2>ZF-9674: Zend_Log_Filter_Abstract has wrong subpackage</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-04-13T13:33:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-16T12:15:38.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.4 (28/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Juozas Kaziukenas (juokaz)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13005/ZF-9674.patch">ZF-9674.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christopher Thomas (cwt137) on 2010-04-16T06:56:10.000+0000</p> 
        <div class="body">
            <p>Attached is a patch to fix the problem</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Juozas Kaziukenas (juokaz) on 2010-04-16T12:15:38.000+0000</p> 
        <div class="body">
            <p>Fixed in r21892</p>

        </div>
    </div>
    </div>

