<h2>ZF-9226: Abstract ZendX_JQuery_View_Helper_AjaxLink and recreate AjaxLink implementing this abstraction</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-21T17:29:47.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>In Progress</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12783/ZF-9226-01.patch">ZF-9226-01.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently ZendX_JQuery_View_Helper_AjaxLink is usefull, but not that useful.
If you need anything else than a hyperlink tag with a JQuery request, you'll find yourself 
writing JQuery instead.
Also, Zend_View_Helper_Url return a url which can be used in many situations. You'd expect to find something like 
ZendX_JQuery_View_Helper_Url then, not ZendX_JQuery_View_Helper_AjaxLink which then returns an entire hyperlink tag.</p>

<p>ZendX_JQuery_View_Helper_AjaxLink will be abstracted into ZendX_JQuery_View_Helper_RequestAbstract.
AjaxLink will then be recreated implementing RequestAbstract.
Also ZendX_JQuery_View_Helper_Request will be created, which will basically just return an inline JQuery function.</p>

<p>This is as per discussion with the ZendX_JQuery maintainer Beberlei.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maghiel Dijksman (maghiel) on 2010-02-21T20:08:48.000+0000</p> 
        <div class="body">
            <p>Patch attached; first implementation.
Needs some polishing but all unit tests (at least those of Zend_JQuery_View_jQueryTest)
pass.
Also some new tests need to be added and the documentation needs editing.</p>

<p>Time for bed for me now so I thought I'd submit this working patch as a peak :)</p>

        </div>
    </div>
    </div>

