<h2>ZF-9061: Zend_Db_Table_Abtract insert() should respect _defaultValues</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-02T07:47:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-01T06:11:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Trahey (ctrahey)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-4759">ZF-4759</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Perhaps Zend_Db_Table_Abstract insert() method should use any values previously set by setDefaultValues()</p>

<p>Inside insert() method:</p>

<p>/**
 * set default insert values from $_defaultValues
 * array_merge will override a key's value in arg1 with arg2 if the key is present in arg2
 */
$data = array_merge($this-&gt;getDefaultValues(), $data);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Trahey (ctrahey) on 2010-02-02T11:21:52.000+0000</p> 
        <div class="body">
            <p>It may also be wise to use the createRow() method, since this is semantically appropriate and already uses the _defaultValues</p>

        </div>
    </div>
    </div>

