<h2>ZF-9057: Converting date</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-02T05:00:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-22T13:54:03.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                André Luiz Martins PIgnata (andrepignata)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have this code:
$data = new Zend_Date($post['_datafim']);
$data-&gt;setLocale('en_US');
$datafim = $data-&gt;get('YYYY-MM-dd');</p>

<p>When $post['_datafim'] = '01/01/2010' i expect that $datafim returns '2010-01-01', but it returns '2009-01-01'.
This issue ocurrs with dates '01/01/2010','02/01/2010' and '03/01/2010', but from '04/01/2010' it returns correctly.
If I use $data-&gt;toString(), they return correctly too. But if I use $data-&gt;toString('YYYY-MM-dd') the return is wrong again.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-02-02T05:39:29.000+0000</p> 
        <div class="body">
            <p>Closing as non-issue.</p>

<p>Please read the manual:
<a href="http://framework.zend.com/manual/en/zend.date.constants.html#zend.date.constants.selfdefinedformats">http://framework.zend.com/manual/en/…</a></p>

<p>{quote}
Note that the default ISO format differs from PHP's format which can be irritating if you have not used in previous. Especially the format specifiers for Year and Minute are often not used in the intended way.</p>

<p>For year there are two specifiers available which are often mistaken. The Y specifier for the ISO year and the y specifier for the real year. The difference is small but significant. Y calculates the ISO year, which is often used for calendar formats. See for example the 31. December 2007. The real year is 2007, but it is the first day of the first week in the week 1 of the year 2008. So, if you are using 'dd.MM.yyyy' you will get '31.December.2007' but if you use 'dd.MM.YYYY' you will get '31.December.2008'. As you see this is no bug but a expected behaviour depending on the used specifiers.</p>

<p>For minute the difference is not so big. ISO uses the specifier m for the minute, unlike PHP which uses i. So if you are getting no minute in your format check if you have used the right specifier. 
{quote}</p>

<p>Or look into the FAQ where often made failures are mentioned:
<a href="http://framework.zend.com/wiki/display/ZFFAQ/Internationalization">http://framework.zend.com/wiki/display/…</a></p>

<p>{quote}
Why are my dates formatted wrong? Why do I get the false year value?</p>

<p>When using own formats in your code you could come to a situation where you get for example 29.12.2009, but you expected to get 29.12.2008.</p>

<p>There is one year difference: 2009 instead of 2008. You should use the lower cased year constant. See this example:</p>

<p>$date-&gt;toString('dd.MM.YYYY'); 
$date-&gt;toString('dd.MM.yyyy'); 
Note the lower cased "y" which makes the difference and outputs the real year.
{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stephan &quot;Bladed&quot; de Souza (bladed) on 2010-02-02T05:59:39.000+0000</p> 
        <div class="body">
            <p>I posted some examples for this issue at ZFBrasil on Google Groups: <a href="http://groups.google.com/group/zfbrasil/browse_thread/thread/fe3f705e18ac2411">http://groups.google.com/group/zfbrasil/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-11-22T11:48:23.000+0000</p> 
        <div class="body">
            <p>Correct fix version as it has been deleted unintentionally by another user</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-11-22T13:54:02.000+0000</p> 
        <div class="body">
            <p>With issues that are not considered an issue there is no fix version. If you think I'm wrong, please show me the commit in the relevant release branch.</p>

        </div>
    </div>
    </div>

