<h2>ZF-9604: Action helpers with PHP namespaces do not work</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-04-03T08:45:33.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-12-18T12:55:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.2 (30/Dec/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10158">ZF-10158</a></li>
            <li><a href="/issues/browse/ZF-9016">ZF-9016</a></li>
            <li><a href="/issues/browse/ZF-7350">ZF-7350</a></li>
            <li><a href="/issues/browse/ZF-8205">ZF-8205</a></li>
            <li><a href="/issues/browse/ZF-7907">ZF-7907</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The issue is Zend_Controller_Action_HelperBroker::getHelper().</p>

<p>I think the helper is stored in the stack as "Namespace\MyHelper", and then the code tries to access it from the stack using the name "MyHelper", i.e., without the namespace.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Wil Moore III (wilmoore) (wilmoore) on 2010-11-21T02:44:13.000+0000</p> 
        <div class="body">
            <p>Actually, the problem is Zend_Controller_Action_Helper_Abstract#getName.</p>

<p>It assumes only "_" in the name but doesn't consider names with "\".</p>

<p>If you extend Zend_Controller_Action_Helper_Abstract and override getName(), your helpers will work. I've been using the following:</p>

<pre><code>public function getName() {
    $full_class_name = get_class($this);

    if (strpos($full_class_name, '_') !== false) {
        $helper_name = strrchr($full_class_name, '_');
        return ltrim($helper_name, '_');
    } else {
        return $full_class_name;
    }
}
</code></pre>

<p>BTW, the fix for issue ZF-10158 corrects this: <a href="http://framework.zend.com/issues/browse/ZF-10158">http://framework.zend.com/issues/browse/ZF-10158</a></p>

<p>That being the case, this issue should be moved or closed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-12-18T12:55:48.000+0000</p> 
        <div class="body">
            <p>Fixed with the issue ZF-9604.</p>

        </div>
    </div>
    </div>

