<h2>ZF-9985: Zend_Amf authentication does not handle Zend_Amf_MessageHeaders as it should</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-06-14T07:33:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-07-14T12:30:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jelle-Jan van Veelen (pelle)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Wade Arnold (wadearnold)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Amf</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using authentication in an AMF request, Zend_Amf_Server fails to recognise the appropriate headers.</p>

<p>In Zend_Amf_Server on line 496 it starts to handle the Authentication. First, it gets the AMF headers, and then checks if there is a array key called 'Credentials' (Zend_Amf_Constants::CREDENTIALS_HEADER). If there is, then it checks if there is a userid property:</p>

<pre class="highlight"><code>
$handleAuth = false;
if ($this-&gt;_auth) {
    $headers = $request-&gt;getAmfHeaders();
    if (isset($headers[Zend_Amf_Constants::CREDENTIALS_HEADER]) &amp;&amp;
        isset($headers[Zend_Amf_Constants::CREDENTIALS_HEADER]-&gt;userid)) {
        $handleAuth = true;
    }
}
</code></pre>

<p>But, there is no array key called Credentials, because all headers are simply pushed in the headers array (see Zend_Amf_Request line 121:</p>

<pre class="highlight"><code>
// Iterate through the AMF envelope header
while ($headerCount--) {
    $this-&gt;_headers[] = $this-&gt;readHeader();
}
</code></pre>

<p>When outputting the headers ($request-&gt;getAmfHeaders(), line 498, Zend_Amf_Server) this is what you get:</p>

<pre class="highlight"><code>
Array
(
    [0] =&gt; Zend_Amf_Value_MessageHeader Object
        (
            [name] =&gt; Credentials
            [mustRead] =&gt; 1
            [length] =&gt; 43
            [data] =&gt; stdClass Object
                (
                    [userid] =&gt; *snip*
                    [password] =&gt; *snip*
                )

        )
)
</code></pre>

<p>But according to the code, it looks like it expects something like this:</p>

<pre class="highlight"><code>
Array (
    [Credentials] =&gt; Object
        (
           [userid] =&gt; *snip*
           [password] =&gt; *snip*
        )
)
</code></pre>

<p>Proposed solution: Loop through the headers, and check if there is a Zend_Amf_Value_MessageHeader which has a $name property that is called 'Credentials', and then check if the Zend_Amf_Value_MessageHeader $data property has as $userid property.</p>

<p>The problem is in version 1.10.0 but I also checked the latest version (1.10.5), but it does not seem changed since 1.10.0.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Alireza Eliaderani (cubny) on 2011-07-09T12:34:57.000+0000</p> 
        <div class="body">
            <p>using 1.11.8 and still have this problem, any solution?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kevin Schroeder (kschroeder) on 2011-07-14T12:30:54.000+0000</p> 
        <div class="body">
            <p>I believe you can find a solution at <a href="http://www.eschrade.com/page/authentication-using-zend_amf/">http://eschrade.com/page/…</a></p>

        </div>
    </div>
    </div>

