<h2>ZF-9044: Zend_Application_Resource_Frontcontroller doesn't allow to force the index of a plugin we want to register</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-01T13:30:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-02T10:43:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.1 (10/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Mickael Perraud (mikaelkael)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The current registration only accept the name of the plugin:
 resources.frontController.plugins.memoryusage = "Mp_Controller_Plugin_MemoryUsage"</p>

<p>One possibility:
 resources.frontController.plugins.memoryusage.class = "Mp_Controller_Plugin_MemoryUsage"
 resources.frontController.plugins.memoryusage.index = 200</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-02-01T14:11:23.000+0000</p> 
        <div class="body">
            <p>Done. To be released in ZF 1.10.1</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-02-01T14:20:57.000+0000</p> 
        <div class="body">
            <p>Hey(!) that suggestion was mine!</p>

<p>Anyhow, functionality implemented.</p>

<p>EDIT: Oh, I commented that already, just didn't resolve it. My bad.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2010-02-01T14:32:50.000+0000</p> 
        <div class="body">
            <p>Yes, it was effectively your proposition.</p>

<p>I wanted to keep this in memory if the correction would be long. But you were faster than I had imagined it! (y)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2010-02-02T01:20:08.000+0000</p> 
        <div class="body">
            <p>An addition in the documentation could be great.
I can add it if you want.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-02-02T01:24:31.000+0000</p> 
        <div class="body">
            <p>I was planning on doing that today. However, if you feel like adding it, please feel free to do so (that is appreciated).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Mickael Perraud (mikaelkael) on 2010-02-02T10:43:52.000+0000</p> 
        <div class="body">
            <p>Documentation added with r20837 and merge to 1.10 branch with r20838</p>

        </div>
    </div>
    </div>

