<h2>ZF-9693: Allowing inheritance of Zend_Uri_Http</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-04-16T07:28:12.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-03T11:50:14.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jean-Sebastien HEDDE (jeanseb)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Uri</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13008/patch.txt">patch.txt</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Uri seems to be a bit closed to inheritance.</p>

<p>I made a little patch which permit to specify a custom "adapter" in the factory.</p>

<p>PS : this patch allow to work arround <a href="http://bugs.php.net/bug.php?id=47689">http://bugs.php.net/bug.php?id=47689</a> (apache crash with long uri).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jean-Sebastien HEDDE (jeanseb) on 2010-04-28T13:19:20.000+0000</p> 
        <div class="body">
            <p>Any feedback ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2010-05-03T07:19:47.000+0000</p> 
        <div class="body">
            <p>Thanks for the patch, looks great. It was applied and I added some documentation.</p>

<p>This is now committed to trunk in r.22081, and will be merged into the release branch if approved.</p>

<p>Cheers!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2010-05-03T11:50:09.000+0000</p> 
        <div class="body">
            <p>merged into the 1.10 release branch in r.22083</p>

        </div>
    </div>
    </div>

