<h2>ZF-9264: Running Gapps class's suspend() or restore() on non-existing accounts results in fatal error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-25T08:03:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-04T16:33:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.7 (28/Jul/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chua Chee How (chuacheehow)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Trevor Johns (tjohns)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12801/patch.diff">patch.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When the suspend() or restore() method in Zend_Gdata_Gapps is run on a non-existing user, a fatal error is thrown.</p>

<p>Test code:</p>

<p>$domain = 'gsatech.com.sg';
  $username = "admin_account@$domain";
  $password = 'password';</p>

<p>$client = Zend_Gdata_ClientLogin::getHttpClient($username, $password, Zend_Gdata_Gapps::AUTH_SERVICE_NAME);
  $gapps = new Zend_Gdata_Gapps($client, $domain);</p>

<p>$nonExistingUser = 'nobodynobody';
  $gapps-&gt;suspendUser($nonExistingUser);</p>

<p>The above will result in the error:</p>

<p>Fatal error: Call to undefined method stdClass::save() in /home/cheeze/public_html/jotterlab/library/Zend/Gdata/Gapps.php on line 788</p>

<p>A similar problem exists for restoreUser().</p>

<p>A better solution is to throw an exception. The following lines:</p>

<p>if ($user === null) {
    throw new Zend_Gdata_Gapps_ServiceException();
  }</p>

<p>can be placed right after the calling of retrieveUser() in both the functions.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chua Chee How (chuacheehow) on 2010-02-25T08:05:58.000+0000</p> 
        <div class="body">
            <p>The attached file is the diff output from svn diff</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Trevor Johns (tjohns) on 2010-10-04T16:33:15.000+0000</p> 
        <div class="body">
            <p>Fixed by r22511.</p>

        </div>
    </div>
    </div>

