<h2>ZF-9614: Images of the manual not are loaded</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-04-04T13:03:56.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-06T12:31:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Barcode</li>
            <li>Zend_Controller</li>
            <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9314">ZF-9314</a></li>
            <li><a href="/issues/browse/ZF-9934">ZF-9934</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Images are not being loaded for version 1.10 of the manual.</p>

<p>See
<a href="http://framework.zend.com/manual/1.9/en/zend.controller.basics.html">Zend_Controller Basics in 1.9</a></p>

<p><a href="http://framework.zend.com/manual/1.10/en/zend.controller.basics.html">Zend_Controller Basics in 1.10</a></p>

<p>Other components with the same problem:
<a href="http://framework.zend.com/manual/1.10/en/zend.db.adapter.html#zend.db.adapter.example-database">Zend_Db</a>
<a href="http://framework.zend.com/manual/1.10/en/zend.barcode.creation.html#zend.barcode.creation.renderering">Zend_Barcode</a></p>

<p>I believe it is a general problem of the version 1.10 of the manual.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-04-05T11:21:37.000+0000</p> 
        <div class="body">
            <p>The site sources have been fixed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Getelman (dget) on 2010-06-17T21:34:24.000+0000</p> 
        <div class="body">
            <p>It appears the same problem has come up again. It's also true on the layout page, barcode page, and all pages with images.</p>

        </div>
    </div>
    </div>

