<h2>ZF-9499: Zend_Currency code example typo</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-03-21T10:49:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-21T11:43:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Micha Verboeket (mverboeket)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Currency</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Currency 1.10 documentation code examples has a typo:
"20.print $currency-&gt;add($currency2);"</p>

<p>$currency2 should be $currency_2 (mind the underscore)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Micha Verboeket (mverboeket) on 2010-03-21T10:52:29.000+0000</p> 
        <div class="body">
            <p>Affected component</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-21T11:43:34.000+0000</p> 
        <div class="body">
            <p>Fixed with r21600</p>

        </div>
    </div>
    </div>

