<h2>ZF-9371: Zend_Form_Element duplicate and missing label translation Issues</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2010-03-08T14:32:20.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-11-11T19:10:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10066">ZF-10066</a></li>
            <li><a href="/issues/browse/ZF-8694">ZF-8694</a></li>
            <li><a href="/issues/browse/ZF-10066">ZF-10066</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13186/fix-double-translation.patch">fix-double-translation.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In version 1.10.x</p>

<pre class="highlight"><code>
public function getLabel()
{
    $translator = $this-&gt;getTranslator();
    if (null !== $translator) {
        return $translator-&gt;translate($this-&gt;_label);
    }

    return $this-&gt;_label;
}
</code></pre>

<p>It cause problem, because the translation is running twice.
1. When calling getLabel()
2. And the Translate adapter globaly</p>

<p>Before version 1.10.x worked fine.</p>

<pre class="highlight"><code>
public function getLabel()
{
    return $this-&gt;_label;
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-04-03T05:22:05.000+0000</p> 
        <div class="body">
            <p>Updated title to reflect that this issue is a parent of SubTasks now.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-05-28T05:44:49.000+0000</p> 
        <div class="body">
            <p>After reading through the Sub Tasks, older issues and most important
the <a href="http://framework.zend.com/wiki/display/ZFDEV2/Zend_Form+2.0#Zend_Form2.0-Translation">Zend_Form-2.0 wiki</a>, i will move all translate calls from 
Zend_Form and Zend_Form_Element_* into Zend_Form_Decorator_*
// edit
and into Zend_View_Helper_Form* according to where the final rendering occurs,
in a way that the original Element attributes won't be translated.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-06-17T13:02:00.000+0000</p> 
        <div class="body">
            <p>We had a discussion in irc where wwe thought about implementing 
a Decorator_Translate to do all the translations for configured
attribs and/or values. <a href="http://zftalk.com/logs/view/zftalk.dev/2010/06/03/">http://zftalk.com/logs/view/zftalk.dev/2010/06/03/</a></p>

<p>Any Comments?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Holger Schletz (hschletz) on 2010-06-20T11:42:25.000+0000</p> 
        <div class="body">
            <p>This may be a good idea or not, but it looks like a long term solution to me. For the moment, I'd be more than happy to see the fixes (which have been around for months and work flawlessly) finally make it into a release. It's really annoying to apply them after every update.</p>

<p>Is there any good reason why this has not been addressed yet?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by René Kerner (johndoe) on 2010-06-29T04:50:14.000+0000</p> 
        <div class="body">
            <p>vice versa linked...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-06-30T14:41:47.000+0000</p> 
        <div class="body">
            <p>Holger which fixes are you refering to?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Holger Schletz (hschletz) on 2010-07-04T07:30:41.000+0000</p> 
        <div class="body">
            <p>One of the fixes (including tests) is attached to ZF-8764. I can't find the other one ATM (already too many open bug reports about this). I have attached a patch that fixes both issues (without the tests).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Gabriel Schuster (g.schuster) on 2011-02-16T14:49:12.000+0000</p> 
        <div class="body">
            <p>2011 and still no fix for this...
Can it really be true that there's no committer that is willing to apply a patch?
Why not just fix it to prevent translate-logs filling with garbage and developing cool things like Decorator_Translate later?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kai Uwe (kaiuwe) on 2011-02-17T00:10:14.000+0000</p> 
        <div class="body">
            <p>??developing cool things like Decorator_Translate??</p>

<p><a href="http://framework.zend.com/wiki/display/ZFDEV2/Zend_Form+2.0#Zend_Form2.0-Translation">Zend_Form 2.0 - Recommendations: Translation</a></p>

<p>{quote}
Translation should be moved to the view layer. The View and Decorator chains would receive the Translator object and use it to translate appropriate labels and metadata. As such, the form, its elements, and the individual validator and validator chains would need no such knowledge of this information.
{quote}</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rob Allen (rob) on 2011-11-11T19:10:45.000+0000</p> 
        <div class="body">
            <p>Duplicate of ZF-8694</p>

        </div>
    </div>
    </div>

