<h2>ZF-9501: &quot;zf create action&quot; causes malformed PHP when non-empty action methods already exist</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-21T12:07:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-01T17:30:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.12.0 (27/Aug/12)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
            <li>FixForZF1.12</li>
            <li>zf-caretaker-adamlundrigan</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9310">ZF-9310</a></li>
            <li><a href="/issues/browse/ZF-9018">ZF-9018</a></li>
            <li><a href="/issues/browse/ZF-10244">ZF-10244</a></li>
            <li><a href="/issues/browse/ZF-12040">ZF-12040</a></li>
            <li><a href="/issues/browse/ZF-11785">ZF-11785</a></li>
            <li><a href="/issues/browse/ZF-10396">ZF-10396</a></li>
            <li><a href="/issues/browse/ZF-11472">ZF-11472</a></li>
            <li><a href="/issues/browse/ZF-11647">ZF-11647</a></li>
            <li><a href="/issues/browse/ZF-9502">ZF-9502</a></li>
            <li><a href="/issues/browse/ZF-10121">ZF-10121</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have controller which has this code in the start of the class:</p>

<pre><code>public function preDispatch()
{
    $acl = Zend_Registry::get('acl');

            if(!$acl-&gt;isAllowed(Zend_Registry::get('role'), 'admin', $this-&gt;getRequest()-&gt;action)) {
                if(!Zend_Auth::getInstance()-&gt;hasIdentity()) {
                    $this-&gt;_forward('noauth', 'error');
                } else {
                    $this-&gt;_forward('noacl', 'error');
                }
            }
}
</code></pre>

<p>when I run zf create action for this file, the resulting PHP file comes out broken - this method has one closing brace } missing.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Stanislav Malyshev (stas) on 2010-03-21T12:15:57.000+0000</p> 
        <div class="body">
            <p>Also just noticed - it does not preserve the formatting of the document completely. While all the lines are ok, indentation is often messed up.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rodrigo Neves (xmajox) on 2010-07-16T01:46:52.000+0000</p> 
        <div class="body">
            <p>This also happens to me. Together with the tab messup, it really becomes a pain to use zend tool.</p>

<p>All the controller gets wrecked every single time a new action is added wich really starts to get into you once the controller starts to get big.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Rodrigo Neves (xmajox) on 2010-07-16T02:19:49.000+0000</p> 
        <div class="body">
            <p>Just upgraded to 1.10.6 to make sure, and it still happens.</p>

<p>It removes any closing bracket that's right before the method's one. i.e.:</p>

<p>function yadayadaAction(){</p>

<p>/* lots of code */</p>

<p>if (something){
   ...
 }
}</p>

<p>The if's closing bracket gets removed.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Youssef Eldakar (snowsmash) on 2010-08-03T01:00:28.000+0000</p> 
        <div class="body">
            <p>I can confirm this on 1.10.3.</p>

<p>Youssef Eldakar
Bibliotheca Alexandrina</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-20T10:10:06.000+0000</p> 
        <div class="body">
            <p>This problem is related to Zend_Reflection_Method::getBody().</p>

<p>Greetings
Ramon</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-11-20T10:12:54.000+0000</p> 
        <div class="body">
            <p>Is related to with issue ZF-9018.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Max Gordon (mgordon) on 2011-01-05T12:41:08.000+0000</p> 
        <div class="body">
            <p>I've noticed that whenever I have a try{}catch() the code breaks up and the comments get an additional empty line, heres code:</p>

<pre class="highlight"><code>
class IndexController extends Zend_Controller_Action {
    public function init() {
    }

    /**
     * a test action
     */
    public function funkyAction() {
        $this-&gt;view-&gt;title = "COOOL";
    }

    public function indexAction() {
        try {
            $this-&gt;view-&gt;title = "Testing Zend_Tool bug";
        } catch (Exception $exc) {
            echo $exc-&gt;getTraceAsString();
        }
    }

    /**
     * a test action
     */
    public function unfunkyAction() {
        $this-&gt;view-&gt;title = "UNCOOOL";
    }
}
</code></pre>

<pre class="highlight"><code>
class IndexController extends Zend_Controller_Action
{
    public function init()
    {
    }

    /**
     * a test action
     *
     */
    public function funkyAction()
    {
        $this-&gt;view-&gt;title = "COOOL";
    }

    public function indexAction()
    {
        try {
            $this-&gt;view-&gt;title = "Testing Zend_Tool bug";
        } catch (Exception $exc) {
            echo $exc-&gt;getTraceAsString();
        
    }

    /**
     * a test action
     *
     */
    public function unfunkyAction()
    {
        $this-&gt;view-&gt;title = "UNCOOOL";
    }

    public function testAction()
    {
        // action body
    }
}
</code></pre>

<p>Note missing } in the try and the extra comment line:
    /**
     * a test action
     *
     */</p>

<p>This was done with the ZF 1.11.2</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simone Marchioni (simo75) on 2011-02-03T03:20:59.000+0000</p> 
        <div class="body">
            <p>Same problem here. ZF version: 1.11.0
If I add an action with a command like this:</p>

<p>zf create action </p>

<p>there are 2 kind of problems:</p>

<ol><li>The controller source is bad indented</li>
<li>The last closing bracket inside <em>EVERY</em> action method is removed, leaving you with corrupted PHP code</li>
</ol><p>Note: the error #2 is for every structure control enclosed with curly braces, so this problem is valid if you have a while, an if, a try/catch, and so on... The closing bracket is stripped away.</p>

<p>I'm trying to teach ZF inside our company but If the basic Tools like Zend_Tool don't function properly I can't tell people to switch to them.
This bug is almost an year old: hope to see it fixed soon. I'll vote for it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Oliver Spooner (ospooner) on 2011-02-16T09:04:21.000+0000</p> 
        <div class="body">
            <p>Not that this will stop the indentation problem, but it only removes a curly bracket if it is the last thing before the closing bracket of the function. This means you can stop Zend Tool from breaking the code by adding a commented line before the closing bracket:</p>

<p>public function myAction()
{
  if($whatever) {
  }
  // Comment added here stops the curly bracket getting removed from the line above.
}</p>

<p>Still not ideal, but it does at least mean you can add actions using zf.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Daniel Kraaij (daank) on 2011-04-07T12:03:10.000+0000</p> 
        <div class="body">
            <p>I'm having the same problem, but only in the following situation.</p>

<pre class="highlight"><code>
    public function removeAction()
    {
        if (NULL !== ($itemId = $this-&gt;_getParam('id', null))) {
            $cartMapper = new Application_Model_CartMapper();
            if ($cartMapper-&gt;removeItem($itemId)) {
                $this-&gt;_redirect('/cart');
            }
        }
    }

</code></pre>

<pre class="highlight"><code>

    public function removeAction()
    {
        if (NULL !== ($itemId = $this-&gt;_getParam('id', null))) {
            $cartMapper = new Application_Model_CartMapper();
            if ($cartMapper-&gt;removeItem($itemId)) {
                $this-&gt;_redirect('/cart');
            }
        
    }
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2011-10-17T16:27:14.000+0000</p> 
        <div class="body">
            <p>This issue stems from problems with {{Zend_Reflection_Method::getBody}}, as outlined in ZF-9018.  An interim fix has been suggested there.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-06-01T17:30:59.000+0000</p> 
        <div class="body">
            <p>Fixed in ZF-9501</p>

        </div>
    </div>
    </div>

