<h2>ZF-9723: Zend_Feed_Reader::detectType, Notice: Undefined variable: doc [...] on line 430</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-04-21T02:02:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-29T04:31:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Feed_Reader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13025/Reader.php.patch">Reader.php.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Occurs when calling Zend_Feed_Reader::detectType().
Due to a variable name typo in Line 430:
$status = $doc-&gt;loadXML($feed);</p>

<p>This should be: 
$status = $dom-&gt;loadXML($feed);</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Sebastian Knüll (sknuell) on 2010-04-21T02:03:29.000+0000</p> 
        <div class="body">
            <p>Patch as described in report.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-04-28T08:51:29.000+0000</p> 
        <div class="body">
            <p>Resolved in r22031. This is what you get for missing the odd test or two ;).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Knüll (sknuell) on 2010-04-28T13:30:20.000+0000</p> 
        <div class="body">
            <p>I definitely like the test method name! :-)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-04-29T04:31:46.000+0000</p> 
        <div class="body">
            <p>Well, it was a silly thing to forget a test for ;).</p>

        </div>
    </div>
    </div>

