<h2>ZF-9482: Minor error on Code example in the ZendX_Console_Process_Unix documentation</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-03-19T04:39:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-16T12:13:23.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.4 (28/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Juozas Kaziukenas (juokaz)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_Console_Process_Unix</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Reference: <a href="http://framework.zend.com/manual/en/zendx.console.process.unix.overview.html">http://framework.zend.com/manual/en/…</a></p>

<p>Current example shows:</p>

<pre class="highlight"><code>
// Stay in the loop if BOTH processes are running...
while ($process1-&gt;isRunning() &amp;&amp; $process2-&gt;isRunning()) {
    sleep(1);
}
</code></pre>

<p>It should be:</p>

<pre class="highlight"><code>
// Stay in the loop if one of the processes is running...
while ($process1-&gt;isRunning() || $process2-&gt;isRunning()) {
    sleep(1);
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Juozas Kaziukenas (juokaz) on 2010-04-16T12:13:23.000+0000</p> 
        <div class="body">
            <p>Fixed in r21891</p>

        </div>
    </div>
    </div>

