<h2>ZF-9178: Translation of Zend_Validate messages to russian language</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-15T02:37:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-15T12:35:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.2 (24/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12739/Zend_Validate_Messages_ru_Ru.php">Zend_Validate_Messages_ru_Ru.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend Framework comes now with translation resources.
So in attachment - russian translation of Zend_Validate messages
Translation made by Andrew Kozlov, Alexander Mahomet, Stepan Tanasiychuk, Andrew Vasil'ev and other members of community zendframework.ru</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-02-15T12:32:20.000+0000</p> 
        <div class="body">
            <p>Implemented with r21057</p>

<p>Thanks for this contribution.
Note: Please keep in touch with changes and new translation on the english original or with the resource testbed.</p>

        </div>
    </div>
    </div>

