<h2>ZF-9338: Zend_Form_Element_Captcha loads two decorators in its render() function shd be in loadDefaultDecorator();</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-03-05T05:13:28.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-24T05:53:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Captcha</li>
            <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-7552">ZF-7552</a></li>
            <li><a href="/issues/browse/ZF-5197">ZF-5197</a></li>
            <li><a href="/issues/browse/ZF-8094">ZF-8094</a></li>
            <li><a href="/issues/browse/ZF-10804">ZF-10804</a></li>
            <li><a href="/issues/browse/ZF-9268">ZF-9268</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Form_Element_Captcha should use its loadDefaultDecorators() method to add two captcha specific decorators instead of using its render() method for this purpose , as a result currently its impossible to disable captcha decorator ,currently if someone like to create its own captcha decorator has to create his own captcha element.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Petr Gottvald (gotys) on 2010-05-06T09:04:08.000+0000</p> 
        <div class="body">
            <p>Decorating the Zend_Form_Element_Captcha seems almost imposible. Please fix this issue!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-06-07T00:30:10.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
$form = new Zend_Form();
$form-&gt;addElement('captcha', 'CaptchaName',
          array('captcha' =&gt; new Zend_Captcha_Figlet(),
                        'prefixPath' =&gt; array('decorator' =&gt; array('App_Form_Decorator' =&gt; 'App/Form/Decorator/'))));
$form-&gt;render();
echo '</code></pre><pre><code>' . var_export(array_keys($form-&gt;CaptchaName-&gt;getDecorators()),1) . '</code></pre><code>';

array (
  0 =&gt; 'App_Form_Decorator_Captcha',
  1 =&gt; 'App_Form_Decorator_Captcha_Word',
  2 =&gt; 'Zend_Form_Decorator_Errors',
  3 =&gt; 'Zend_Form_Decorator_Description',
  4 =&gt; 'Zend_Form_Decorator_HtmlTag',
  5 =&gt; 'Zend_Form_Decorator_Label',
)
</code>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-06-07T00:30:42.000+0000</p> 
        <div class="body">
            <p>Closing as won't fix as the Decorators are probably going to be refactored in 2.0 - 
and until then the suggested workaround seems sufficient for me.</p>

        </div>
    </div>
    </div>

