<h2>ZF-997: Support full set of available search options</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-03-01T16:07:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.2 (06/Apr/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Darby Felton (darby)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Flickr</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In protected Zend_Service_Flickr::_validateTagSearch($options) an array of valid options is defined. Since it was defined, Flickr has added new options for search. The complete list can be found here. <a href="http://www.flickr.com/services/api/flickr.photos.search.html">http://flickr.com/services/api/…</a></p>

<p>Current:
$valid_options = array('api_key', 'method', 'user_id', 'per_page', 'page', 'extras', 'min_upload_date',
 'min_taken_date', 'max_upload_date', 'max_taken_date', 'tag_mode', 'tags');</p>

<p>Proposed:
$valid_options = array('api_key', 'method', 'user_id', 'per_page', 'page', 'extras', 'min_upload_date',
 'min_taken_date', 'max_upload_date', 'max_taken_date', 'tag_mode', 'tags','sort','privacy_filter','bbox','accuracy','machine_tags', 'machine_tag_mode','group_id','text' );</p>

<p>=C=</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-03-01T16:14:59.000+0000</p> 
        <div class="body">
            <p>Assign to Darby.
Correct typo in Summary.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-28T16:20:29.000+0000</p> 
        <div class="body">
            <p>Updated summary and changed to bug, since it is improper behavior to throw an exception upon using an option that should be available through the component API.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-29T17:37:53.000+0000</p> 
        <div class="body">
            <p>Updated fix version to 0.9.2.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Darby Felton (darby) on 2007-03-30T15:56:10.000+0000</p> 
        <div class="body">
            <p>Resolved with <a href="http://framework.zend.com/fisheye/changelog/Zend_Framework/?cs=4284">SVN r4284</a>.</p>

        </div>
    </div>
    </div>

