<h2>ZF-9601: Zend_Validate_Barcode make call of the method Zend_Validate_Abstract:&gt;_setValue($value)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-04-02T17:34:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-03T03:38:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.4 (28/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>current code
line 192 in file, Zend/Validate/Barcode.php</p>

<pre class="highlight"><code>
$this-&gt;_value = (string) $value;
</code></pre>

<p>Change to</p>

<pre class="highlight"><code>
$this-&gt;_setValue($value);
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-04-02T23:59:03.000+0000</p> 
        <div class="body">
            <p>What's the benefit/improvement of deleting (string)?
Could be a problem in my eyes when the given value is no string.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-04-03T03:30:42.000+0000</p> 
        <div class="body">
            <p>Changed with r21748</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-04-03T03:35:06.000+0000</p> 
        <div class="body">
            <p>@Thomas
I agree it would be a problem, but before of the assignment is made a validate of the type of given passed.</p>

<p>line 187 the 190 in, Zend/Validate/Barcode.php</p>

<pre class="highlight"><code>
if (!is_string($value)) {
    $this-&gt;_error(self::INVALID);
    return false;
}
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-04-03T03:38:20.000+0000</p> 
        <div class="body">
            <p>@Thomas
Thanks, Disregard my comment above.</p>

        </div>
    </div>
    </div>

