<h2>ZF-9687: Dojo unit tests php fatal error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-04-15T14:20:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-03T03:57:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.4 (28/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Georgy Turevich (georgy)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
            <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13001/ZF_9687_fix.patch">ZF_9687_fix.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When run tests for Dojo</p>

<pre class="literal">

it stops with fatal error
</pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Georgy Turevich (georgy) on 2010-04-15T14:26:11.000+0000</p> 
        <div class="body">
            <p>Fix for this bug in attachment.</p>

<p>All tests for Dojo and Form passed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-07-03T03:57:10.000+0000</p> 
        <div class="body">
            <p>Resolved in the commit ZF-9586 see <a href="http://framework.zend.com/code/viewrep/Zend_Framework/standard/trunk/library/Zend/Form/Element.php?r1=21782&amp;r2=21893">r21893</a></p>

        </div>
    </div>
    </div>

