<h2>ZF-9092: Because parse_ini_file() interprets NULL as an empty string, Zend_Cache_Core's lifetime setting cannot be configured from an INI file.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-02-05T06:30:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-22T01:33:55.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.1 (10/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Configuring Zend_Cache via an INI file runs afoul of parse_ini_file() - used in Zend_Config - which translates a value of NULL to an empty string. This prevents setting the Zend_Cache_Core lifetime to NULL except manually. To fix this, Zend_Cache_Core should interpret any empty value as being equivelant to NULL. This imposes no breaks in behaviour (that is intended) but will break behaviour where empty strings were used either by intent or accident. The scope of the latter is not considered, in my opinion, worth preserving since it serves no actual purpose.</p>

<p>On a separate note, the Zend_Cache tests have no test for a NULL value anywhere.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-06T09:14:26.000+0000</p> 
        <div class="body">
            <p>Patched in SVN</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Winkel (storeman) on 2010-02-22T01:33:53.000+0000</p> 
        <div class="body">
            <p>I'm having trouble with this patch. In development environment I use a lifetime setting of zero in the ini file.</p>

<p>I've spend a lot of time debugging to try and find the error I got. Seems to be my lifetime of zero in my cache.ini file. Setting it to 1 resolved this problem, but I think this isn't a proper solution.</p>

<p>because:</p>

<p>empty("0") validates to true, it's set to NULL.</p>

<p>Better is: (string)intval($value) != $value</p>

        </div>
    </div>
    </div>

