<h2>ZF-9888: Zend_Test_PHPUnit_Db_Operation_Truncate Fails On A MS SQL Server Table With A Foreign Key Relation  </h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-05-25T13:49:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-25T14:01:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Benjamin Eberlei (beberlei)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Test_PHPUnit</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Truncate command fails on sql server when the table has foreign key relations.  This is expected.  Instead the truncate command should do a "delete" operation and then reset the index key.  The following SQL Transact functions will do the same as truncate and will work on a table with a FK relation:</p>

<p>DELETE from "table_name"
DBCC CHECKIDENT("table_name", RESEED, "reseed_value")</p>

<p>=========== code to reproduce ================</p>

<p>$connection = new Zend_Test_PHPUnit_Db_Connection($db, 'users');
$dbTester = new Zend_Test_PHPUnit_Db_SimpleTester($connection);</p>

<p>// getDataSetFile returns path to an xml file with 
$dbFixture = 
    new PHPUnit_Extensions_Database_DataSet_FlatXmlDataSet($this-&gt;getDataSetFile());</p>

<p>$dbTester-&gt;setupDatabase($dbFixture);</p>

<p>================================================</p>

<p>============= Database ====================
table: users</p>

<h1>relate users to another table.</h1>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Benjamin Eberlei (beberlei) on 2010-05-25T13:53:57.000+0000</p> 
        <div class="body">
            <p>Zend_Test_PHPUnit_Db expects you to sort the tables in the XML files in an order that allows for a non-conflicting FK truncation. Since it cannot know which is the correct order without doing lots of inference.</p>

<p>If you don't want that you can add your own Set Up Operation using PHPUnit's APIs.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Brian Strickland (strick) on 2010-05-25T14:01:16.000+0000</p> 
        <div class="body">
            <p>I've done that (backwards order)</p>

<p>  &lt;= relates to users</p>

<p>When truncate is ran, the "roles" table is wiped out and then it fails on "users"</p>

<p>TRUNCATE will not work on MS SQL SERVER tables that have a relation, no matter if they are empty or not:  <a href="http://msdn.microsoft.com/en-us/library/ms177570.aspx">http://msdn.microsoft.com/en-us/library/…</a></p>

        </div>
    </div>
    </div>

