<h2>ZF-9333: problems to work with dates after 31 Dec 2037 in UTC+0 time zones</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-04T16:11:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Martin Minka (k2s)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Date</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It seams that Zend_Date has problems to work with dates after 31 Dec 2037 in UTC+0 time zones. It starts to shift time -1 hour.</p>

<p>Example of this issue is reproduced here <a href="http://www.k2s.sk/grid/date.php">http://www.k2s.sk/grid/date.php</a> and I am pasting the code also here:</p>

<pre class="highlight"><code>
require "Zend/Date.php";

// don't use locale detected from browser to understand month names
require "Zend/Registry.php";
$locale = new Zend_Locale("en_GB");
Zend_Registry::set("Zend_Locale", $locale);

function tryDates($dates)
{
    echo "<b>converting dates:</b> ";
    foreach ($dates as $str=&gt;$expected) {
        $date = new Zend_Date($str); 
        $day = $date-&gt;get("yyyy-MM-dd");
        if ($day!=$expected) {
            echo "<span style="color:#FF0000;">$day</span>";
        } else {
            echo "<span style="color:#008000;">$day</span>";
        }
        echo " (".$date-&gt;toString(Zend_Date::ISO_8601)."), ";
    }
    echo "<br />";
}
function runTestInTimeZone($timeZone)
{
    date_default_timezone_set($timeZone);
    echo "</code></pre><h3><code>time zone: ".date_default_timezone_get()."</code></h3><code>";
    echo "loop for dates in years 2037-2050:<br />";
    for ($y=2037; $y&lt;=2050; $y++) {
        $y_1 = $y-1;
        tryDates(array("31 Dec $y_1"=&gt;"$y_1-12-31", "1 Jan $y"=&gt;"$y-01-01", "5 Jan $y"=&gt;"$y-01-05"));
    }
    echo "";
}

echo &lt;&lt;Zend_Date time zone problem
It seams that Zend_Date has problems to work with dates after 31 Dec 2037 in UTC+0 time zones. It starts to shift time -1 hour.
HTML;

echo "</code><h2><code>Code to reproduce the problem</code></h2><code>";
highlight_file(__FILE__);
echo "</code><h2><code>Results:</code></h2><code>";
runTestInTimeZone('GMT');
runTestInTimeZone('Europe/London');
runTestInTimeZone('Europe/Lisbon');
runTestInTimeZone('Europe/Bratislava');
runTestInTimeZone('Europe/Amsterdam');
runTestInTimeZone('America/Chicago');
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-05T14:48:24.000+0000</p> 
        <div class="body">
            <p>Your example give an exception:</p>

<p>"Fatal error: Uncaught exception 'Zend_Date_Exception' with message 'Unable to parse date '31 Dec 2036' using 'dd.MM.yyyy HH:mm:ss' "</p>

<p>This is no problem of Zend_Date as you define to use dd.MM.yyyy HH:mm:ss bus you give dd MMM yyyy.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-05T14:50:30.000+0000</p> 
        <div class="body">
            <p>Reducing from Critical to Minor...
Example failes by design.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Minka (k2s) on 2010-03-05T16:15:56.000+0000</p> 
        <div class="body">
            <p>Thomas,
have you visited my working example at <a href="http://www.k2s.sk/grid/date.php">http://www.k2s.sk/grid/date.php</a> ?</p>

<p>The code should work for you if you change:</p>

<pre class="highlight"><code>
$date = new Zend_Date($str);
</code></pre>

<p>to</p>

<pre class="highlight"><code>
$date = new Zend_Date($str, "dd MMM yy"); 
</code></pre>

<p><em>Zend_Date is not reliable on future dates and that is in my opinion critical bug.</em></p>

<p>The error you are getting is not relevant to the problem I am describing and which is easily to see at <a href="http://www.k2s.sk/grid/date.php">http://www.k2s.sk/grid/date.php</a>. I think it is caused by some locale configuration differences.</p>

<p>I found the problem, I am trying to show here, on many forums, but without solutions. The time is shifted in Europa/London timezone in very strange way on some dates.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Minka (k2s) on 2010-03-05T16:18:28.000+0000</p> 
        <div class="body">
            <p><em>I think it is caused by some locale configuration differences.</em> - is related to the error you are getting with my code, I don't know why Zend_Date has problems with some dates in some timezones.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-13T02:43:27.000+0000</p> 
        <div class="body">
            <p>Also the online example fails by design.
It returns the same exception as when running it locally.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Minka (k2s) on 2010-03-14T08:06:37.000+0000</p> 
        <div class="body">
            <p>ok, I tested the example with IE set to use Language germany and you are right it fails, because of the Month name parsin.</p>

<p>I added following code to force Zend_Date to use english to parse the month names:</p>

<pre class="highlight"><code>
// don't use locale detected from browser to understand month names
require "Zend/Registry.php";
$locale = new Zend_Locale("en_GB");
Zend_Registry::set("Zend_Locale", $locale);
</code></pre>

<p>It should work now for you now here: <a href="http://www.k2s.sk/grid/date.php">http://www.k2s.sk/grid/date.php</a></p>

<p>If for any other reason it will not work, pls. download the output here: <a href="http://www.k2s.sk/grid/dateproblem.pdf">http://www.k2s.sk/grid/dateproblem.pdf</a></p>

        </div>
    </div>
    </div>

