<h2>ZF-9239: require_once() is missing in Zend_Cache_Manager</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-23T05:54:36.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-23T10:56:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.2 (24/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Cache</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12790/patch.diff">patch.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Cache_Manager object expects that you load Zend_Cache class before using it.</p>

<p>h3. Usage</p>

<pre class="highlight"><code>
&lt;?php

$manager = new Zend_Cache_Manager();
// ...
$manager-&gt;getCache('default');
</code></pre>

<p>h3. Expected result</p>

<p>No error</p>

<p>h3. Actual result</p>

<p>Fatal error: Class 'Zend_Cache' not found in /path/to/library/Zend/Cache/Manager.php on line 167</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Renan de Lima (renanbr) on 2010-02-23T05:55:50.000+0000</p> 
        <div class="body">
            <p>patch for this issue</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-23T10:56:21.000+0000</p> 
        <div class="body">
            <p>Fixed in r21162</p>

        </div>
    </div>
    </div>

