<h2>ZF-9571: captcha and session</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Task</dd>

    <dt>Created:</dt>
    <dd>2010-03-29T13:53:25.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-05T02:00:22.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>What's different:
second:
$captcha = $f-&gt;createElement('captcha','captcha',array('captcha' =&gt; 'Image',
     'captchaOptions' =&gt; array(
     'font'=&gt;_CPTFONT,
     'ImgDir' =&gt; _CPTSAVEDIR,
     'ImgUrl' =&gt; _IMG,
     'DotNoiseLevel' =&gt; 0 ,
     'LineNoiseLevel' =&gt; 0,
     'lang' =&gt; 'pl',
     'Width' =&gt; '300',
     'Height' =&gt; '70',
    )));
    $captcha
    -&gt;setRequired(true);</p>

<p>second :
     $capImage = new Zend_Captcha_Image();
     $capImage-&gt;setFont( _CPTFONT );
     $capImage-&gt;setImgDir( _CPTSAVEDIR );
     $capImage-&gt;setImgUrl( _IMG' );
     $capImage-&gt;setDotNoiseLevel( 0 );
     $capImage-&gt;setLineNoiseLevel( 0 );
     $capImage-&gt;setWidth( '300' );
     $capImage-&gt;setHeight( '70' );
     $capImage-&gt;generate();</p>

<pre><code> $captcha = new Zend_Form_Element_Captcha( 'captcha' , array('captcha' =&gt; $capImage ));
 $captcha-&gt;setRequired(true);
 $captcha-&gt;setLabel('Przepisz kod:');
</code></pre>

<p>at first example captcha is working good.
at second, i thing .. session working bad?
return error : badCaptcha 
why? i dont know.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-04-05T02:00:17.000+0000</p> 
        <div class="body">
            <p>Remove $capImage-&gt;generate() and it will work, Closing as a Non-issue.</p>

        </div>
    </div>
    </div>

