<h2>ZF-962: Zend_Db_Table::insert() has wrong param in docblock</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-02-23T20:44:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Diego Tremper (diegotremper)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Bill Karwin (bkarwin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Table</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>currently :</p>

<pre class="highlight"><code>
    /**
     * Inserts a new row.
     *
     * Columns must be in underscore format.
     *
     * @param array $data Column-value pairs.
     * @param string $where An SQL WHERE clause.
     * @return int The last insert ID.
     */
</code></pre>

<p>expected:</p>

<pre class="highlight"><code>
    /**
     * Inserts a new row.
     *
     * Columns must be in underscore format.
     *
     * @param array $data Column-value pairs.
     * @return int The last insert ID.
     */
</code></pre>

<p>Regards,
Diego Tremper</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Diego Tremper (diegotremper) on 2007-02-23T20:48:13.000+0000</p> 
        <div class="body">
            <p>how I can have permission will be commit?</p>

<p>Thanks.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-25T17:08:14.000+0000</p> 
        <div class="body">
            <p>Assign to Bill Karwin.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-25T17:40:53.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3640.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-25T17:41:37.000+0000</p> 
        <div class="body">
            <p>Reword summary.</p>

        </div>
    </div>
    </div>

