<h2>ZF-9154: Zend_Layout fails to output response if XDebug extension is enabled</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-02-12T06:11:05.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-02-15T04:33:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Layout</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>This seems to have been around for a long time, but it keeps appearing/disappearing depending on how applications are written. Basically, if XDebug is enabled, Zend_Layout gets extremely upset. Some pages render, but others (including the zftool inspired ErrorController) do not. It appears almost impossible to predict what will/will not render but the trend (if any) leans towards simpler View (less PHP) not rendering. That's completely speculative - just saying ;).</p>

<p>To be precise, ALL pages are rendered (in their entirety) but many (always the same ones) get swallowed somewhere in Zend_Layout (output buffering?) leading to an immediate blank page output. Trying to be even more precise, the output is completely empty - i.e. it is always a HTTP 1/x 200 with no content (even if a controller sets another response code). This appears to be the webserver/PHP's default doing - the application just outputs nothing whatsoever.</p>

<p>Since I can't reduce this into a simple test case, I'll just point to one afflicted application (all the configs are there, the layout, the views, etc).</p>

<p><a href="http://github.com/padraic/ZFPlanet">http://github.com/padraic/ZFPlanet</a></p>

<p>This has a simple app. See the readme - just needs a database, liberal permissions on ./data and ./public/cached, and away you go. Now, with XDebug enabled, all you need to do is try hitting a non-existent controller (can check config to make sure exceptions are not thrown - or just run in production mode (env flag as usual)). The ErrorController is reached, its View is rendered (check response object), but nothing will be shown in the browser. To get something on screen - disable Zend_Layout in the ErrorController and, hey presto, you get output. You also get output, without any changes, simply by disabling XDebug.</p>

<p>The problem here is sort of obvious - is it Zend_Layout's fault or XDebug's? No idea myself. I've seen this on both PHP 5.2 and PHP 5.3 (latest of each), both with the most recent appropriate XDebug versions for those two PHP versions. I've been able to trace everything until it hits Zend_Layout's output buffering area - after that things just got lost. I'll keep chipping away at it but I'm reporting it here since my Zend_Layout knowledge is marginal at best.</p>

<p>Obviously, this can be worked around - throw all exceptions if XDebug is enabled. But this still makes testing awkward without constantly either staging the app to another non-XDebug server, or just disabling XDebug dynamically. Neither workaround is ideal.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-12T11:16:06.000+0000</p> 
        <div class="body">
            <p>Almost nevermind... Disabling XDebug worked for a while, then I edited a View, and the blank page returned...sigh. It's still hit or miss - the application works flawlessly for absolutely everything else, but most new controllers refuse to render, or render only after refreshing a browser many times. I'm moving to a clean system to see if I can diagnose it more cleanly and tick off any other causes (like a dodgy Apache install).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-12T12:02:29.000+0000</p> 
        <div class="body">
            <p>After doing some more tracing (I'll boot into XDebug profiling tomorrow), the common thread is the Zend_Layout output buffering. Fiddle with output buffering enough times (from php.ini and/or http.ini in the demo app where the dispatcher buffer is disabled (using page caching on some other pages - not this one)) and it sometimes renders. I'd guess that Zend_Layout is not clearing the full buffer or its interaction with other buffers is somehow off. Checking up to the point of buffering show the response is completely rendered - it's just not escaping Zend_Layout's clutches as browser output. Disabling Zend_Layout shows the non-layout encumbered output hits the browser as normal.</p>

<p>After starting from a completely clean system (Ubuntu Jaunty with a basic from-repository PHP5+Apache) I can replicate this. I'll try reducing it to a unit test tomorrow if possible. At that time I'll try attaching some system info (php config/profile cachegrind) to the issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-13T08:31:00.000+0000</p> 
        <div class="body">
            <p>Update on the symptoms after some testing:</p>

<ol><li>XDebug does cause Zend_Layout to fail when rendering from the ErrorController. Disabling Zend_Layout or removing XDebug allows the ErrorController output to reach the browser.</li>
<li>The other blank pages are different. They are blank regardless of whether XDebug is installed or not.</li>
</ol><p>So this was really two symptoms, not one, as I originally believed. So there is SOME kind of interaction with XDebug. Working on profiling now to try and trace down a common root.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2010-02-15T04:33:28.000+0000</p> 
        <div class="body">
            <p>After some tracing I figured out what was happening - in using Doctrine, my version seems to have issues in certain use cases when shifting around the controller stack (e.g. using _forward()). I'll hammer at that now ;). Not a ZF issue at all.</p>

        </div>
    </div>
    </div>

