<h2>ZF-9772: Zend_Element missing clearMessages() method</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-04-29T11:59:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-28T23:23:27.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Stewart Lord (stewartlord)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/14943/ZF-9772.diff">ZF-9772.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It is not possible to clear the protected _messages array on a form element. It might also be desirable to have a setMessages() method.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Artem Stepin (nemesis2010) on 2010-05-28T14:12:41.000+0000</p> 
        <div class="body">
            <p>I couldn't imagine any case where you need to delete the messages (which are provided by your validators). In case of setMessages you could use Zend_Translate, then the validators return the translated messages and you don't need any further steps.</p>

<p>Regards,
Artem Stepin</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Stewart Lord (stewartlord) on 2010-05-28T18:02:29.000+0000</p> 
        <div class="body">
            <p>If you want to check if a value is valid, but don't want to pollute the element's messages, clearMessages and setMessages would both be handy. As it stands, you must clone the element to avoid polluting the messages.</p>

<p>Regards,
Stew</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Artem Stepin (nemesis2010) on 2012-02-28T23:23:27.000+0000</p> 
        <div class="body">
            <p>i've added a "clearMessages" method to Zend_Form/Zend_Form_Element and additionaly "addMessage" and "addMessages" to Zend_Form_Element (corresponding tests included)</p>

        </div>
    </div>
    </div>

