<h2>ZF-9008: Add support for &quot;Button&quot; jQuery UI Element</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Sub-task</dd>

    <dt>Created:</dt>
    <dd>2010-01-29T03:59:45.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_JQuery</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The new "button" jQuery UI element allows to make fancy Checkboxes, Radio and Buttons in Forms.</p>

<p>There should be a simple form-decorator that renders radio, buttons and such with "button" or "buttonset".</p>

<p>I don't bother about adding new view helpers for those elements, they can easily be progressivly enhanced by calling:</p>

<pre class="highlight"><code>
$this-&gt;jQuery()-&gt;addOnLoad('$(".myRadio").button()');
</code></pre>

<p>Maybe it would be a good idea though to add a view helper with something like:</p>

<pre class="highlight"><code>
$this-&gt;jQueryButton('.mySubmit');
$this-&gt;jQueryButtonSet('.myRadio', array('text' =&gt; false, 'primary' =&gt; 'icon-myradio'));
</code></pre>

<p>Which could be used inside the Form Decorator also.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

