<h2>ZF-9971: Zend_Locale_Format::toNumber  get unexcepted value when BCMath is not available</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-06-10T00:10:50.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-06-10T11:49:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.6 (22/Jun/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When i use 
&lt;?
$b = 1.995934;
$options = array(
     'locale' =&gt; 'sv_SE'
    ,'precision' =&gt; 2
);
echo Zend_Locale_Format::toNumber($b, $options) . "\n"; exit;
//except: 1,99  (2,00 also can be acceptable)
//output: 1,00
?&gt;</p>

<p>When disable the BCMath, So the calculation will use the Zend_Locale_Math_PhpMath</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-06-10T11:49:08.000+0000</p> 
        <div class="body">
            <p>Please note that 1.6 is no longer supported.
This is a 2 year old release.</p>

<p>It can be assumed that the problem was already reported and solved in the last 2 years. Additionally not reproduceable with actual release. Therefor closing as won't fix.</p>

        </div>
    </div>
    </div>

