<h2>ZF-9922: Zend_Dojo_View_Helper should support omitModuleCheck in requireModule()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-05-31T12:28:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:38:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Jakob Schumann (j-schumann)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Dojo</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The dojo() view helper allows loading modules on demand via dojo()-&gt;requireModule($modules) but doesn't support the second parameter 'omitModuleCheck' the dojo.require() function implements (<a href="http://api.dojotoolkit.org/jsdoc/HEAD/dojo.require">http://api.dojotoolkit.org/jsdoc/HEAD/dojo.require</a>) while this parameter is very useful when loading 3rd party JS libraries that do not implement the dojo.provide('module').</p>

<p>The view helper should be extended to allow registerModule(string|array $modules, bool omitModuleCheck = false) which sets the flag for the single module given | all modules in the array.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

