<h2>ZF-9507: Zend_Tool no longer uses IncludePathLoader</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-03-22T09:38:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris Morrell (inxilpro)
            </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Tool</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12945/zend-tool-doc.diff">zend-tool-doc.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Currently the section "How Zend Tool finds your Providers" on <a href="http://framework.zend.com/manual/en/zend.tool.framework.writing-providers.html">http://framework.zend.com/manual/en/…</a> indicates that Zend Tool uses the IncludePathLoader to load additional providers.  That is no longer the case.  It now uses the BasicLoader, which means that you have to manually add your providers/manifests to Zend Tool.</p>

<p>I have created a simple patch for trunk/documentation/manual/en/module_specs/Zend_Tool_Framework-WritingProviders.xml that fixes this issue in the documentation.  I'll attach it as soon as the issue is created.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Morrell (inxilpro) on 2010-03-22T09:40:20.000+0000</p> 
        <div class="body">
            <p>Simple fix.  It could be fleshed out some but at least it fixes the issue and points the end user in the right direction.</p>

        </div>
    </div>
    </div>

