<h2>ZF-9532: Conditional comments in headStyle()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Patch</dd>

    <dt>Created:</dt>
    <dd>2010-03-24T10:50:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-01-27T10:17:10.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.3 (01/Feb/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alan Willms (dyulax)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Benoît Durand (intiilapa)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13037/HeadStyleTest.php">HeadStyleTest.php</a></li>
            <li><a href="/issues/secure/attachment/13034/Zend_View_Helper_HeadStyle.patch">Zend_View_Helper_HeadStyle.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The followting code:</p>

<p>$this-&gt;headStyle()-&gt;appendStyle("
body { 
    behavior:url('" . SERVER_STATIC_URL . PATH_URL_JAVASCRIPT . "iefix/csshover3.htc');
}
", array('conditional' =&gt; 'IE 6'));</p>

<p>Will generate this HTML:</p>

<p>
&lt;![endif]--&gt;</p>

<p>Note that the , before "", so that remains an unfinished tag and commentary end, invalidating the HTML.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by __jul__ (__jul__) on 2010-04-24T16:32:13.000+0000</p> 
        <div class="body">
            <p>I've written a patch which resolves this issue.</p>

<p>It's my first patch, so please let me know if you require any additional information.</p>

<p>Cheers,
Jeremy</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-04-27T05:30:47.000+0000</p> 
        <div class="body">
            <p>Could you provide a unit test in your patch, please?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by __jul__ (__jul__) on 2010-04-27T15:52:06.000+0000</p> 
        <div class="body">
            <p>Test attached. :)</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Symphony IT (symphony) on 2011-01-26T08:24:32.000+0000</p> 
        <div class="body">
            <p>This is still an unresolved issue. It's still adding the nested comments in to the html and thus causing HTML validation issues.</p>

<p>Could you please sort this asap, it should be a relatively easy fix, especially since jul has provided you with the code.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2011-01-27T10:17:06.000+0000</p> 
        <div class="body">
            <p>Fix r23680</p>

        </div>
    </div>
    </div>

