<h2>ZF-9549: Use fallback for language name</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-26T13:41:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-26T15:43:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                fisharebest (fisharebest)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Locale</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Locale::getTranslation('es_AR', 'language', 'en') returns false;</p>

<p>It should either fall back to this:</p>

<p>Zend_Locale::getTranslation('es', 'language', 'en')</p>

<p>Or (to be clever?) it could translate the language/territory separately</p>

<p>Zend_Locale::getTranslation('es', 'language', 'en').' ('.Zend_Locale::getTranslation('AR', 'territory', 'en').')'</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-26T15:42:40.000+0000</p> 
        <div class="body">
            <p>Why should the translation itself fall back ??
This is unlogic.</p>

<p>The locale can fall back, but not the translation.</p>

<p>When you are requesting the translation for "country" why should it then fall back to "city" ?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-26T15:43:00.000+0000</p> 
        <div class="body">
            <p>Closing as non-issue</p>

        </div>
    </div>
    </div>

