<h2>ZF-918: Notice: Undefined variable for Zend_Validate Unit Tests</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2007-02-15T08:33:43.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.8.0 (21/Feb/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sebastian Nohn (nohn)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Simon R Jones (studio24)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/10261/Hostname.php">Hostname.php</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Notice: Undefined variable: utf8 in /home/sebastian/Work/ZendFramework/library/Zend/Validate/Hostname.php on line 238</p>

<p>Call Stack:
    0.0002      53028   1. {main}() /opt/php/bin/phpunit:0
    0.0023     168752   2. require('/opt/php/lib/php/PHPUnit/TextUI/Command.php') /opt/php/bin/phpunit:44
    0.0796    2696744   3. PHPUnit_TextUI_Command::main() /opt/php/lib/php/PHPUnit/TextUI/Command.php:401
    4.4366   33524036   4. PHPUnit_TextUI_TestRunner-&gt;doRun() /opt/php/lib/php/PHPUnit/TextUI/Command.php:100
    4.4371   33524980   5. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/TextUI/TestRunner.php:247
    4.6985   33536032   6. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
   66.2879   45961400   7. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
   67.3070   45995884   8. PHPUnit_Framework_TestSuite-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:478
   67.5591   45998020   9. PHPUnit_Framework_TestSuite-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:491
   67.5591   45998152  10. PHPUnit_Framework_TestCase-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestSuite.php:510
   67.5591   45998284  11. PHPUnit_Framework_TestResult-&gt;run() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:223
   67.5592   45999252  12. PHPUnit_Framework_TestCase-&gt;runBare() /opt/php/lib/php/PHPUnit/Framework/TestResult.php:529
   67.5592   45999896  13. PHPUnit_Framework_TestCase-&gt;runTest() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:243
   67.5592   46001064  14. ReflectionMethod-&gt;invoke() /opt/php/lib/php/PHPUnit/Framework/TestCase.php:300
   67.5593   46001228  15. Zend_Validate_HostnameTest-&gt;testDashes() /home/sebastian/Work/ZendFramework/tests/Zend/Validate/HostnameTest.php:0
   67.6681   46004964  16. Zend_Validate_Hostname-&gt;isValid() /home/sebastian/Work/ZendFramework/tests/Zend/Validate/HostnameTest.php:120</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Simon R Jones (studio24) on 2007-02-15T08:46:58.000+0000</p> 
        <div class="body">
            <p>Sebastian - can you try this file and let me know if it resolves the issue. If so, I'll commit it.</p>

<p>The $utf8 variable was accidentally left over from my IDN hostname testing, which I've removed for this release.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Sebastian Nohn (nohn) on 2007-02-15T10:09:35.000+0000</p> 
        <div class="body">
            <p>Works with that file.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon R Jones (studio24) on 2007-02-15T10:16:00.000+0000</p> 
        <div class="body">
            <p>Fixed in revision 3435</p>

        </div>
    </div>
    </div>

