<h2>ZF-9498: Zend_Currency service ignored</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-21T10:46:02.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-21T14:20:52.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Currency</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Zend_Currency service seems to be ignored. When exactly following the documentation 1.10 code examples, this are the results:
Expected result: '$ 3.000'
Actual result: '$2,000.00' 
According to the documentation: "The above example will return '$ 3.000' because the 1.000 EUR will be converted by a rate of 2 to 2.000 USD."</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Micha Verboeket (mverboeket) on 2010-03-21T10:52:00.000+0000</p> 
        <div class="body">
            <p>Affected component</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-21T11:49:40.000+0000</p> 
        <div class="body">
            <p>Please describe what exactly you mean.</p>

<p>There are about 500 different code examples through the complete documentation.</p>

<p>What did you do, which code did you use and what did you expect?
Which ZF release and which PHP release were you using?</p>

<p>We need some more informations to be able to reproduce your failure.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Micha Verboeket (mverboeket) on 2010-03-21T12:08:30.000+0000</p> 
        <div class="body">
            <p>I used the 2 code examples on the English reference guide of the framework version 1.10 (<a href="http://framework.zend.com/manual/en/zend.currency.exchange.html">http://framework.zend.com/manual/en/…</a>)
I am using php 5.3.0</p>

<p>This is the code I used:</p>

<pre class="highlight"><code> 
class ZFCustom_CurrencyExchange implements Zend_Currency_CurrencyInterface
{
    public function getRate($from, $to)
    {
        if ($from !== "USD") {
            throw new Exception('We can only exchange USD');
        }
        
        switch ($to) {
            case 'EUR':
                return 0.5;
            case 'JPE':
                return 0.7;
       }
 
       throw new Exception('Unable to exchange $to');
    }
}
</code></pre>

<p>and</p>

<pre class="highlight"><code> 
$currency = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'USD',
    )
);
 
$service  = new ZFCustom_CurrencyExchange();
 
// attachons le service de change
$currency-&gt;setService($service);

 
$currency_2 = new Zend_Currency(
    array(
        'value'    =&gt; 1000,
        'currency' =&gt; 'EUR',
    )
);
 
print $currency-&gt;add($currency_2);
</code></pre>

<p>The locale is registered with:</p>

<pre class="highlight"><code> 
Zend_Registry::set('Zend_Locale',new Zend_Locale('en_US'));
</code></pre>

<p>And as I said:
Expected result: '$ 3.000'
Actual result: '$2,000.00'</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-21T14:20:51.000+0000</p> 
        <div class="body">
            <p>Fixed with r21602</p>

        </div>
    </div>
    </div>

