<h2>ZF-9902: Setting two times headMeta for same name is generating duplicated tags name tags</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-05-27T10:16:46.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-11-20T21:37:26.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13113/HeadMeta.php">HeadMeta.php</a></li>
            <li><a href="/issues/secure/attachment/13112/Zend_View_Helper_HeadMeta.patch">Zend_View_Helper_HeadMeta.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>$view-&gt;headMeta()-&gt;prependName('keywords', 'keywords1');
$view-&gt;headMeta()-&gt;prependName('keywords', 'keywords2');</p>

<p>I was expecting to generate:</p>

<p></p>

<p>But actually is generating</p>

<p></p>

<p>Which is weird...</p>

<p>I tested on 1.10.2, but i guess would be same on 1.10.5...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Artem Stepin (nemesis2010) on 2010-05-27T16:01:18.000+0000</p> 
        <div class="body">
            <p>I also had this problem. Here is my quick fix. Now if you use "appendXXXX" or "prependXXXX", then the content is appended or prefixed in XXXX(separated by commas). Unfortunately, it does not work with offset functions and you couldn't delete one entry from the enumeration. Therefore, it is not a general solution. Not yet ...</p>

<p>Regards,
Artem Stepin</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Cristian Bichis (avantis) on 2010-05-27T23:37:10.000+0000</p> 
        <div class="body">
            <p>I think the HeadMeta should work on this cases similar with headTitle, so can specify a separator (setSeparator) and to generate only one tag, not multiple...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Artem Stepin (nemesis2010) on 2010-05-28T00:06:03.000+0000</p> 
        <div class="body">
            <p>Every meta tag could have a 'lang' attribute, so you could define keywords or whatever in different languages. You need sometimes more than one meta tag with same name.</p>

        </div>
    </div>
    </div>

