<h2>ZF-9722: Impossible to nest decorators inside Zend_Form_Decorator_Label</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-04-21T01:21:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-09T16:46:18.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matthew Way (mattyway)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-6667">ZF-6667</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>It is impossible to nest decorators inside Zend_Form_Decorator_Label in a way similar way to what the HtmlTag decorator does by default. At the moment, it is only possible to append or prepend the label tag, not nest it. I want to create markup that looks like this:</p>

<pre class="highlight"><code> 

    Country
    
</code></pre>

<p>(This is the markup required for Uni-Form [<a href="http://sprawsm.com/uni-form/">http://sprawsm.com/uni-form/</a>] to have multiple elements on one line)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

