<h2>ZF-9011: Unable to set additional parameters for Sendmail transport when using mail application resource</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-01-29T05:19:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-02-02T21:34:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.1 (10/Feb/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Matt Cockayne (matt.cockayne)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
            <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5337">ZF-5337</a></li>
            <li><a href="/issues/browse/ZF-9034">ZF-9034</a></li>
            <li><a href="/issues/browse/ZF-11022">ZF-11022</a></li>
            <li><a href="/issues/browse/ZF-9033">ZF-9033</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12691/Zend_Mail_Transport_Sendmail.diff">Zend_Mail_Transport_Sendmail.diff</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When Implementing the Zend_Application_Resouce_Mail for use with sendmail the transport class has no way to correctly accept and additionalParameters</p>

<p>I have modified my version to suit my needs by altering the constructor of the transport class to identify the parameters as an array and treat them accordingly</p>

<p>patch attached</p>

<p>this will allow the use of application configs such as</p>

<pre class="highlight"><code>
; Relevant
resources.mail.transport.type = sendmail
resources.mail.transport.envelope = "-tjohn@example.com"

; Irrelevant
resources.mail.defaultFrom.email = john@example.com
resources.mail.defaultFrom.name = "John Doe"
resources.mail.defaultReplyTo.email = Jane@example.com
resources.mail.defaultReplyTo.name = "Jane Doe"</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-01-30T18:38:56.000+0000</p> 
        <div class="body">
            <p>Thank you for reporting this issue. Will be released in the next minor release, possibly earlier.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-02-01T11:41:03.000+0000</p> 
        <div class="body">
            <p>Will be released next mini release.</p>

        </div>
    </div>
    </div>

