<h2>ZF-9692: Sqlsrv Db adapter documentation doesn't specify that driver is supposed to be used with 2005 and greater server versions</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-04-16T06:07:59.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-16T06:19:06.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Juozas Kaziukenas (juokaz)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Juozas Kaziukenas (juokaz)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Sqlsrv Db adapter documentation doesn't specify that driver is supposed to be used with 2005 and greater server versions</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Juozas Kaziukenas (juokaz) on 2010-04-16T06:19:06.000+0000</p> 
        <div class="body">
            <p>Fixed in r21877</p>

        </div>
    </div>
    </div>

