<h2>ZF-9302: Add missing break to Zend_Validate::is()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-01T20:00:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-04T12:54:42.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Validate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I don't know whether this is a real bug but I think Zend_Validate::is() with own namespaces is working by a fluke.</p>

<pre class="highlight"><code>Zend_Validate::is(123, 'Int', array(), array('My_Validate'));

// My/Validate/Int.php
// Zend/Validate/My/Validate/Int.php</code></pre>

<pre class="highlight"><code>Zend_Validate::is(123, 'Int', array(), array('My_Validate'));

// My/Validate/Int.php</code></pre>

<pre class="highlight"><code>Index: library/Zend/Validate.php
===================================================================
--- library/Zend/Validate.php   (revision 21290)
+++ library/Zend/Validate.php   (working copy)
@@ -204,7 +204,7 @@
                     $file  = str_replace('_', DIRECTORY_SEPARATOR, $class) . '.php';
                     if (Zend_Loader::isReadable($file)) {
                         Zend_Loader::loadClass($class);
-                        $className = $class;
+                        $className = $class; break;
                     }
                 }
             }</code></pre>

<p>This patch is not breaking any unit tests.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-04T12:54:12.000+0000</p> 
        <div class="body">
            <p>Fixed with r21328</p>

        </div>
    </div>
    </div>

