<h2>ZF-9882: Translate data writer</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-05-23T23:39:35.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-22T11:44:53.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Normally site administrator is not technical enough to write translation files manually in XML or even INI and CSV format. So they requires feature to add translation data from admin panel.</p>

<p>So, there should be a facility to write translate data with different adapter. For example, I use CSV as translate adapter, by simply calling write method of translate adapter should add or update translation data into configured CSV file.</p>

<p>This feature would really be helpful in multilingual application.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-05-24T14:35:51.000+0000</p> 
        <div class="body">
            <p>Why don't you use fputcsv when you want to write CSV files?</p>

<p>For Zend_Translate it is impossible to write in the wished formats.
Some formats are defined very loosly... TMX for example allows to have about 10 different notations how a translation file has to look like.</p>

<p>Other formats like gettext are binary, which makes them very hard to write. You must keep the order, which means that it is almost impossible to add a translation in between when you don't have the original po files.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Riesen (christianriesen) on 2010-06-26T12:48:41.000+0000</p> 
        <div class="body">
            <p>You could implement that very easy by extending the translate adapter you use, overwrite the logging function and, while logging enabled just go through all pages. Then implement in the logging whatever writer you want. I have a writer that inserts it into a database, which I can then turn into an array file with a simple script. With a small interface attached, I can give others access to the database to translate the strings into other languages.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-07-31T08:30:50.000+0000</p> 
        <div class="body">
            <p>Closing as non issue
Such a feature is already available.</p>

<p>See <a href="http://www.thomasweidner.com/flatpress/2010/07/30/how-to-add-missing-translations/">http://thomasweidner.com/flatpress/2010/…</a> for an example.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-11-22T11:44:53.000+0000</p> 
        <div class="body">
            <p>Correct fix version as it has been deleted unintentionally by another user</p>

        </div>
    </div>
    </div>

