<h2>ZF-9190: Error in Docbook transformation for 'imageobject'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-02-16T07:45:32.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-02T08:28:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.11 (29/Sep/11)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Looks like there is a problem in the docbook transformation for the online documentation.</p>

<p>There are no closing quotes for both the <em>src</em> attribute of the <em>img</em> tag and the <em>href</em> attribute for the <em>a</em> tag.</p>

<p><a href="http://framework.zend.com/manual/en/learning.quickstart.intro.html">http://framework.zend.com/manual/en/…</a></p>

<pre class="highlight"><code>
</code></pre><div class="inlinemediaobject"><code>
 </code><div class="imageobject"><code>
  <a href="/images/manual/images/d481d625821a97b9a5eb2cec99dca50e-learning.quickstart.intro.mvc.png"></a>
  
 </code></div><code>
</code></div><code>
</code>

<p><a href="http://framework.zend.com/manual/en/zend.controller.basics.html">http://framework.zend.com/manual/en/…</a></p>

<pre class="highlight"><code>
</code></pre><div class="inlinemediaobject"><code>
 </code><div class="imageobject"><code>
  <a href="/images/manual/images/d481d625821a97b9a5eb2cec99dca50e-zend.controller.basics.png"></a>
  
 </code></div><code>
</code></div><code>
</code>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Arystan Dyussenov (kazanbas) on 2010-03-08T04:51:26.000+0000</p> 
        <div class="body">
            <p>This bug prevents images in documentation from being displayed.</p>

<p>It can also be seen on the following page:</p>

<p>[<a href="http://framework.zend.com/manual/en/learning.quickstart.create-model.html">http://framework.zend.com/manual/en/…</a>]</p>

<pre class="highlight"><code>
</code></pre><div class="inlinemediaobject"><code>
  </code><div class="imageobject"><code>
    <a href="/images/manual/images/d481d625821a97b9a5eb2cec99dca50e-learning.quickstart.create-model.png"></a>
    
  </code></div><code>
</code></div><code>
</code>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-10-02T08:28:49.000+0000</p> 
        <div class="body">
            <p>This problem must have been fixed in past. It is no longer reproduceable within the manual.</p>

        </div>
    </div>
    </div>

