<h2>ZF-9196: Zend_Db_Profiler_FirebugTest fails when you don't have the extension PDO_SQLITE installed.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Unit Tests: Problem</dd>

    <dt>Created:</dt>
    <dd>2010-02-17T00:49:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-07-15T21:23:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.7 (28/Jul/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Profiler</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13108/FirebugTest.patch">FirebugTest.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Zend_Db_Profiler_FirebugTest fails to tearDown() correctly when you don't have the pecl PDO_SQLITE extension installed.</p>

<p>"Fatal error: Call to a member function getConnection() on a non-object in .../release-1.9.2/tests/Zend/Db/Profiler/FirebugTest.php on line 104"</p>

<p>A fix would be to check to see if the PDO_SQLITE extension is loaded at the top of the tearDown() function</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dennis Becker (radhad) on 2010-05-26T01:23:57.000+0000</p> 
        <div class="body">
            <p>I have created a patch to solve this problem!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-07-15T21:23:07.000+0000</p> 
        <div class="body">
            <p>Fixed with the r22570.</p>

        </div>
    </div>
    </div>

