<h2>ZF-9575: Hardcoded paths in the ZF Library - 'views'</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-30T10:06:51.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-30T14:22:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Controller</li>
            <li>Zend_Db</li>
            <li>Zend_Gdata</li>
            <li>Zend_Service_Amazon</li>
            <li>Zend_Service_SlideShare</li>
            <li>Zend_Tool</li>
            <li>Zend_View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I had thought I had full control over my directory structure.  As such I very much dislike naming the MVC directories in the plural and so named them as 'controller', 'model', and 'view'.  To my dismay, there are hardcoded path references within the ZF library to 'views'.</p>

<p>In my mind this is a coupling that shouldnt be there.  Lets make this more flexible shall we?  Convention is OK, but something like this makes little sense when all other directories are allowed to be named whatever the developer chooses.  Why is the view directory the only one required to be named something specific?</p>

<p>Also please consider the bootstrap file sets the front controller's 'controller' directory.  Similarly there should be a way to set the view directory as well.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-03-30T11:00:47.000+0000</p> 
        <div class="body">
            <p>All of these are configurable.</p>

<ul><li>To modify where the ViewRenderer looks for view scripts, configure it; try adding the following to a resource initializer in your bootstrap:</li>
</ul><pre class="highlight"><code>
$vr = Zend_Controller_Action_HelperBroker::getStaticHelper('ViewRenderer');
$vr-&gt;setViewBasePathSpec(':moduleDir/view');
</code></pre>

<ul><li>Provide an alternate resource autoloader to your module bootstraps; this can be done to remove pluralizations, add extra mappings, and more. As an example, the following defines a new resource autoloader, a base bootstrap class that uses that resource autoloader, and a bootstrap:</li>
</ul><pre class="highlight"><code>
My_Resource_Autoloader extends Zend_Application_Module_Autoloader
{
    public function initDefaultResourceTypes()
    {
        $this-&gt;addResourceType('viewhelper', 'View_Helper', 'view/helper');
        // etc.
}

My_Bootstrap extends Zend_Application_Module_Bootstrap
{
    public function getResourceAutoloader()
    {
        if ((null === $this-&gt;_resourceLoader)
            &amp;&amp; (false !== ($namespace = $this-&gt;getAppNamespace()))
        ) {
            $r    = new ReflectionClass($this);
            $path = $r-&gt;getFileName();
            $this-&gt;setResourceLoader(new My_Resource_Autoloader(array(
                'namespace' =&gt; $namespace,
                'basePath'  =&gt; dirname($path),
            )));
        }
        return $this-&gt;_resourceLoader;
    }
}

Somemodule_Bootstrap extends My_Bootstrap
{
}
</code></pre>

<p>Basically, the paths are <em>not</em> hardcoded, and can be configured whenever and however you want; you just need to know where and when to configure them.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by matthew ishii (mishii1776) on 2010-03-30T11:05:57.000+0000</p> 
        <div class="body">
            <p>Matthew - Very sorry, I had done a grep on the source and had seen 'views' in quotations - I made a risky assumption that this meant it was not configurable or changed later if configured differently.</p>

<p>Thank you for showing me how this is possible - again I apologize.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2010-03-30T14:22:29.000+0000</p> 
        <div class="body">
            <p>No worries -- just wanted to point out where and how to configure. :)</p>

        </div>
    </div>
    </div>

