<h2>ZF-9582: Maybe it could be possible, to access the unexpected status code found in Zend_Mail_Protocol_Abstract::_expect()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2010-03-31T11:04:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-27T03:34:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Maybe it could be possible, to access the unexpected status code found in Zend_Mail_Protocol_Abstract::_expect() it could be a good idea to return it via  Zend_Mail_Protocol_Exception as a code parameter ...</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-04-01T00:45:38.000+0000</p> 
        <div class="body">
            <p>Hello, Eutychus. I have changed that _expect() method recently, so I will be happy if You try new version 1.10.3 .</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eutychus (eutychus) on 2010-04-01T09:16:04.000+0000</p> 
        <div class="body">
            <p>???</p>

<p>Maybe I am blind ...</p>

<p>If I look at the current _expect() of the trunk I find:</p>

<p>{quote}
    /**
     * Parse server response for successful codes
     *
     * Read the response from the stream and check for expected return code.
     * Throws a Zend_Mail_Protocol_Exception if an unexpected code is returned.
     *
     * @param  string|array $code One or more codes that indicate a successful response
     * @throws Zend_Mail_Protocol_Exception
     * @return string Last line of response string
     */
    protected function _expect($code, $timeout = null)
    {
        $this-&gt;_response = array();
        $cmd  = '';
        $more = '';
        $msg  = '';
        $errMsg = '';</p>

<pre><code>    if (!is_array($code)) {
        $code = array($code);
    }

    do {
        $this-&gt;_response[] = $result = $this-&gt;_receive($timeout);
        list($cmd, $more, $msg) = preg_split('/([\s-]+)/', $result, 2, PREG_SPLIT_DELIM_CAPTURE);

        if ($errMsg !== '') {
            $errMsg .= ' ' . $msg;
        } elseif ($cmd === null || !in_array($cmd, $code)) {
            $errMsg =  $msg;
        }

    } while (strpos($more, '-') === 0); // The '-' message prefix indicates an information string instead of a response string.

    if ($errMsg !== '') {
        /**
         * @see Zend_Mail_Protocol_Exception
         */
        require_once 'Zend/Mail/Protocol/Exception.php';
        throw new Zend_Mail_Protocol_Exception($errMsg);
    }

    return $msg;
}
</code></pre>

<p>{quote}</p>

<p>The code returned by for example an SMTP Server is passed to Zend_Mail_Protocol_Exception.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eutychus (eutychus) on 2010-04-01T09:19:31.000+0000</p> 
        <div class="body">
            <p>Fu**</p>

<p>what happended to my quotation??</p>

<p>Whatever ...</p>

<p>The call of "throw new Zend_Mail_Protocol_Exception($errMsg);" does not seem to me that there the for example Smtp Server result is passed to the Exception ...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2010-04-15T23:14:25.000+0000</p> 
        <div class="body">
            <p>Sorry, sadly, I can not understand difference between current output and the result that you expect it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Eutychus (eutychus) on 2010-04-27T03:34:02.000+0000</p> 
        <div class="body">
            <p>Maybe there is a missunderstanding on my side ... is there a way to receive the smtp status code if an email isn't property submitted?</p>

        </div>
    </div>
    </div>

