<h2>ZF-9903: Zend_Application_Resource_Multidb could store instance of the adapters in Zend_Registry</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-05-27T10:41:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-10-31T03:43:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ramon Henrique Ornelas (ramon)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Dolf Schimmel (Freeaqingme) (freak)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Application_Resource</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-10355">ZF-10355</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13110/ZF-9903.patch">ZF-9903.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Could has a option of stored of the object adapters in Zend_Registry.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-05-27T10:45:59.000+0000</p> 
        <div class="body">
            <p>Attached patch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-06-24T18:11:24.000+0000</p> 
        <div class="body">
            <p>We could. But since Zend_App already acts as a DI-container it makes no sense of storing them elsewhere as well.</p>

        </div>
    </div>
    </div>

