<h2>ZF-927: Zend_Mail strips down empty newlines in body message</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2007-02-16T14:25:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:50.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I have posted this to the fw-general list before and it is still not fixed in r3503. Tested on PHP 5.2.0 and 5.2.1</p>

<p>Zend_Mail strips down empty newlines in the message body set by setBodyText():</p>

<pre class="highlight"><code>
$mail = new Zend_Mail();
$mail-&gt;setSubject('my subject');
$mail-&gt;setBodyText("my body\r\n\r\n...after two newlines");
$mail-&gt;setFrom('info@onlime.ch');
$mail-&gt;addTo('test@email.com');
// print_r($mail);
$mail-&gt;send();
</code></pre>

<p>A print_r($mail) before sending the mail looks correct:</p>

<pre class="highlight"><code>
...
    [_bodyText:protected] =&gt; Zend_Mime_Part Object
        (
            [type] =&gt; text/plain
            [encoding] =&gt; quoted-printable
            [id] =&gt; 
            [disposition] =&gt; inline
            [filename] =&gt; 
            [description] =&gt; 
            [charset] =&gt; iso-8859-1
            [boundary] =&gt; 
            [_content:protected] =&gt; my body

...after two newlines
            [_isStream:protected] =&gt; 
        )
...
</code></pre>

<p>In the resulting email the empty newline is cut down though and we get:</p>

<pre class="highlight"><code>
my body
...after two newlines
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2007-02-16T15:46:11.000+0000</p> 
        <div class="body">
            <p>What transport are you using? SMTP or the default?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Philip Iezzi (iezzip) on 2007-02-16T16:07:48.000+0000</p> 
        <div class="body">
            <p>I'm using default transport, mail gets send over the mail()-function in Zend_Mail_Transport_Sendmail::_sendMail() as far as I know.
Same applies to issue [#ZF-928].</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Philip Iezzi (iezzip) on 2007-02-16T16:09:38.000+0000</p> 
        <div class="body">
            <p>besides, I have tested it on both Win32 and Debian Linux under PHP 5.2.0 and 5.2.1</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2007-02-20T15:16:11.000+0000</p> 
        <div class="body">
            <p>I've committed a patch to Zend_Mime, Zend_Mime_Part, and Zend_Mime_Message that should correct the issue; please test and confirm.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Philip Iezzi (iezzip) on 2007-02-20T16:47:58.000+0000</p> 
        <div class="body">
            <p>Sorry Matthew to disappoint you. Now it even seems to be worse.</p>

<p>"my body\r\n\r\n...after two newlines" on win32, result:</p>

<pre class="highlight"><code>my body
...after two newlines</code></pre>

<p>"my body\r\n\r\n...after two newlines" on linux, result:</p>

<pre class="highlight"><code>my body



...after two newlines</code></pre>

<p>4 newlines!, while the \r seems to get encoded to a weird character, source of email:</p>

<pre class="highlight"><code>my body=0D
=0D
...after two newlines</code></pre>

<p>"my body\n\n...after two newlines" on linux, result:</p>

<pre class="highlight"><code>my body
...after two newlines</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Simon Mundy (peptolab) on 2007-03-14T17:35:21.000+0000</p> 
        <div class="body">
            <p>Hi Phillip - has this been resolved for you with the more recent svn commits?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Philip Iezzi (iezzip) on 2007-03-14T17:43:37.000+0000</p> 
        <div class="body">
            <p>Yep! This seems to be resolved in the current trunk.</p>

        </div>
    </div>
    </div>

