<h2>ZF-9644: Not all instances are returned by describe()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-04-09T13:41:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-04-28T15:13:49.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Shahar Evron (shahar)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Service_Amazon_Ec2</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12984/zf9644-r21805.patch">zf9644-r21805.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When trying to call -&gt;describe() with two instance IDs in an array, I only get info of 1 instance in the response, despite the fact that the response XML from EC2 contains both instances I've asked for. Both instances are up and running.</p>

<p>The code I'm using:</p>

<pre class="highlight"><code>
$info = $instance-&gt;describe(
   array('i-16cd7c61', 'i-14cd7c63')
);

var_dump($info, $instance-&gt;getHttpClient()-&gt;getLastResponse()-&gt;getBody());
</code></pre>

<p>and the output:</p>

<pre class="highlight"><code>
array(1) {
  ["instances"]=&gt;
  array(1) {
    [0]=&gt;
    array(17) {
      ["reservationId"]=&gt;
      string(10) "r-304dec47"
      ["ownerId"]=&gt;
      string(12) "--deleted--"
      ["groupSet"]=&gt;
      array(1) {
        [0]=&gt;
        string(9) "zs-node01"
      }
      ["instanceId"]=&gt;
      string(10) "i-14cd7c63"
      ["imageId"]=&gt;
      string(12) "ami-d78ea5a3"
      ["instanceState"]=&gt;
      array(2) {
        ["code"]=&gt;
        string(2) "16"
        ["name"]=&gt;
        string(7) "running"
      }
      ["privateDnsName"]=&gt;
      string(43) "ip-10-224-98-212.eu-west-1.compute.internal"
      ["dnsName"]=&gt;
      string(48) "ec2-79-125-61-48.eu-west-1.compute.amazonaws.com"
      ["keyName"]=&gt;
      string(7) "pokus01"
      ["productCode"]=&gt;
      string(0) ""
      ["instanceType"]=&gt;
      string(8) "m1.small"
      ["launchTime"]=&gt;
      string(24) "2010-04-09T19:27:04.000Z"
      ["availabilityZone"]=&gt;
      string(10) "eu-west-1b"
      ["kernelId"]=&gt;
      string(12) "aki-02486376"
      ["ramediskId"]=&gt;
      string(0) ""
      ["amiLaunchIndex"]=&gt;
      string(1) "1"
      ["monitoringState"]=&gt;
      string(8) "disabled"
    }
  }
}
string(3475) "&lt;?xml version="1.0"?&gt;
fc2b5bd3-a59e-437b-b4a1-4824e129f926r-304dec47--deleted--zs-node01i-16cd7c61ami-d78ea5a3<code>16</code>
                        runningip-10-228-99-116.eu-west-1.compute.internalec2-79-125-55-74.eu-west-1.compute.amazonaws.compokus010m1.small2010-04-09T19:27:04.000Zeu-west-1baki-02486376ari-fa4d668edisabledi-14cd7c63ami-d78ea5a3<code>16</code>
                        runningip-10-224-98-212.eu-west-1.compute.internalec2-79-125-61-48.eu-west-1.compute.amazonaws.compokus011m1.small2010-04-09T19:27:04.000Zeu-west-1baki-02486376ari-fa4d668edisabled"
</code></pre>

<p>Note how the dumped array only shows one instance, but the XML contains both.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2010-04-09T13:50:12.000+0000</p> 
        <div class="body">
            <p>Attached is a dead-simple patch against rev. 21805 which seems to solve the problem, at least for my use case. Not sure it's the right way.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Shahar Evron (shahar) on 2010-04-28T15:13:48.000+0000</p> 
        <div class="body">
            <p>Fixed in r22046</p>

        </div>
    </div>
    </div>

