<h2>ZF-9315: Typo in german translation Zend_Translate-Adapters</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Problem</dd>

    <dt>Created:</dt>
    <dd>2010-03-03T12:25:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-03-04T11:59:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.3 (01/Apr/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Translate</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12821/Zend_Translate-Adapters.xml">Zend_Translate-Adapters.xml</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>found a typo in Zend_Translate-Adapters.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoph Löffler (loeffler.de) on 2010-03-03T12:27:56.000+0000</p> 
        <div class="body">
            <p>Attached file corrects the typo in line 125</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2010-03-04T11:59:24.000+0000</p> 
        <div class="body">
            <p>Fixed with r21324</p>

        </div>
    </div>
    </div>

