<h2>ZF-9525: isRunning always returns true...</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-03-24T00:35:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-24T03:26:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Chris de Kok (mech7)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>ZendX_Console_Process_Unix</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-9481">ZF-9481</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The isRunning always returns true.. causing the script to hang:</p>

<p>example:</p>

<p>Run Script:</p>

<pre class="highlight"><code>
&lt;?php
require_once('process.php');

// This part should last about 10 seconds, not 20.
$process1 = new ConvertPDF();
$process1-&gt;start();
echo 'PID:'. $process1-&gt;getPid();
 
$process2 = new ConvertPDF();
$process2-&gt;start();
 
while ($process1-&gt;isRunning() || $process2-&gt;isRunning()) {
    var_dump($process2-&gt;isRunning());
    //echo 'Running';
    sleep(1);
}
echo 'All processes completed';
</code></pre>

<p>Worker Script (process.php):</p>

<pre class="highlight"><code>
&lt;?php
set_include_path ( '../flipbook/protected/vendors/' );
require_once('../flipbook/protected/vendors/ZendX/Console/Process/Unix.php');
class ConvertPDF extends ZendX_Console_Process_Unix {
    protected function _run(){
         for ($i = 0; $i &lt; 3; $i++) {
            //echo 'Converting &amp; counting:'.$i ."/n";   
            sleep(1);
        }
    }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>
    <p class="comments">No comments to display</p>
    
</div>

