<h2>ZF-96: Implement Search Highlighting</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2006-06-21T13:59:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2007-07-05T14:43:09.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>0.9.0 (17/Mar/07)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Alexander Veremyev (alexander)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Search_Lucene</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm sure that this is on the horizon, but I thought I'd go ahead an create a feature request for "keyword in context"</p>

<p><a href="http://lucene.apache.org/java/docs/api/org/apache/lucene/search/highlight/package-summary.html">http://lucene.apache.org/java/docs/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by joshua may (josh) on 2006-07-04T00:33:15.000+0000</p> 
        <div class="body">
            <p>i'm not sure if comments are supposed to be used for this or not, but:</p>

<p>i too am so so so in favour of this being included as a feature in zend_search_lucene.. will make it so much more useful for me (and i'm guessing others)..</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:10:27.000+0000</p> 
        <div class="body">
            <p>Changing fix version to unknown.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2006-11-13T15:26:53.000+0000</p> 
        <div class="body">
            <p>Changing fix version to 0.6.0.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Veremyev (alexander) on 2007-02-22T12:09:11.000+0000</p> 
        <div class="body">
            <p>Done.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Bill Karwin (bkarwin) on 2007-02-22T12:12:00.000+0000</p> 
        <div class="body">
            <p>Updating Fix version, since the commits for this fix came in after we released ZF 0.8.</p>

        </div>
    </div>
    </div>

