<h2>ZF-9949: Zend_Db_Profiler_Query::getStartedMicrotime() is wanted</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-06-05T08:31:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-11-19T01:08:48.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.1 (30/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Yegor Bugayenko (yegor256)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Richard Tuin (richardtuin)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db_Profiler</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/13464/ZF-9949-rtuin.patch">ZF-9949-rtuin.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Method Zend_Db_Profiler_Query::getStartedMicrotime() would be really useful. Without it there is no other way to get an access to this information.</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-18T14:41:26.000+0000</p> 
        <div class="body">
            <p>Made an implementation and unit test for this issue.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2010-11-18T15:40:52.000+0000</p> 
        <div class="body">
            <p>Patch needs to be committed before marking resolved. Will evaluate patch tomorrow.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Richard Tuin (richardtuin) on 2010-11-19T01:08:46.000+0000</p> 
        <div class="body">
            <p>Patch has been marked resolved after it was reviewed and committed by Bittarman:</p>

<p>[22:45:23] [SVN:r23382:bittarman] ZF-9949: Merging r23381 to release branch 1.11 (See: <a href="http://tinyurl.com/2g3hvuq">http://tinyurl.com/2g3hvuq</a>)</p>

        </div>
    </div>
    </div>

