<h2>ZF-9870: Zend_Log - line 303 - Allow us to define timestamp</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-05-20T22:21:09.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-31T11:59:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.11.0 (02/Nov/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Jan Pieper (jpieper)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Log</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>As mentioned in summary, the timestamp value is hardcoded as date('c'). For some of us we use a specific time stamp pattern for our logging to allow for easy parsing via pre-defined regexes. It would be nice if we could override the value before being passed to $event var.</p>

<p>For now I have created a child class which extends Zend_Log and copied the Log() function contents to the child class to override, kinda messy but gets us by.</p>

<p>Thanks.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Jan Pieper (jpieper) on 2010-05-23T14:03:40.000+0000</p> 
        <div class="body">
            <p>Added in r22267.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ramon Henrique Ornelas (ramon) on 2010-05-29T21:07:53.000+0000</p> 
        <div class="body">
            <p>Not was applied in branch.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Dolf Schimmel (Freeaqingme) (freak) on 2010-05-31T11:58:35.000+0000</p> 
        <div class="body">
            <p>Closing since new functionality should not be introduced in mini releases and the fix already was applied in trunk.</p>

        </div>
    </div>
    </div>

