<h2>ZF-9682: Zend_Form_Element_Radio added with Zend_Form with added prefix paths does not load correct Label decorator (unit test + patch provided)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-04-15T02:45:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2010-05-12T03:05:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul>        <li>1.10.5 (26/May/10)</li>
    </ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Raphael Dehousse (thymus)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christian Albrecht (alab)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12997/Zend_Form_Element_Radio-Label_Decorator.patch">Zend_Form_Element_Radio-Label_Decorator.patch</a></li>
            <li><a href="/issues/secure/attachment/12998/Zend_Form_Element_RadioTest-Label_Decorator.patch">Zend_Form_Element_RadioTest-Label_Decorator.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Dears,</p>

<p>Let's say you have a Zend_Form. You add an elements prefix path (addElementsPrefixPath). Then, you build a Zend_Form_Element_Radio and add it.</p>

<p>You will see that your radio element does not have the good label decoractor. Why?
Because any Zend_Form_Element loadDefaultDecorators in the construct. The loadDefaultDecorators of radio element do a "getDecorator('Label')" that will load the label decorator if not loaded.
Since the addElement add the elements prefix path, it's too late because the label decorator is already loaded.
Others element do a addDecorator - that won't load the decorator if it's a string, the decorator will be loaded in the render method.</p>

<p>The workaround is to specify the prefix paths in the constructor of the radio element, but then, first, you have to "duplicate" this add prefix path, second, it's not the same behavior than the others elements.</p>

<p>I will attach a patch for this and a test case a bit later.</p>

<p>Cheers,</p>

<p>Raphaël Dehousse</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Raphael Dehousse (thymus) on 2010-04-15T04:40:14.000+0000</p> 
        <div class="body">
            <p>This is a patch for the tests suite of Zend_Form_Element_RadioTests</p>

<p>The test added should fail before the patch and should succeed with the patch.</p>

<p>Patch to apply in tag 1.10.3</p>

<p>Cheers,</p>

<p>Raphaël Dehousse</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Raphael Dehousse (thymus) on 2010-05-11T23:51:43.000+0000</p> 
        <div class="body">
            <p>It affects also release 1.10.4</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Christian Albrecht (alab) on 2010-05-12T03:04:42.000+0000</p> 
        <div class="body">
            <p>Fixed in trunk r22151 and merged into 1.10 release branch.</p>

        </div>
    </div>
    </div>

