<h2>ZF-9484: INSERT DELAYED (mysql adapter)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2010-03-19T20:04:06.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-03-22T23:41:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Open</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Josh Ribakoff (josh.ribakoff@gmail.com)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-3107">ZF-3107</a></li>
            <li><a href="/issues/browse/ZF-7149">ZF-7149</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
        <li><a href="/issues/secure/attachment/12941/delayed.patch">delayed.patch</a></li>
        </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Mysql has an INSERT DELAYED syntax. Supporting it in Zend_Framework is critical for an application that heavily relies on Mysql.</p>

<p>Will attach an overly simplified (but probably working) patch</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Marc Hodgins (mjh_ca) on 2010-11-10T10:36:01.000+0000</p> 
        <div class="body">
            <p>This patch will break non-MySQL adapters.  Is there a cross-platform equivalent of DELAYED for the other databases?  With your patch, setting delayed=true will cause the query to fail with a syntax error on a PostgreSQL, Oracle, etc.  So, this definitely does not belong in the abstract adapter unless there is a way to make it cross-platform.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Josh Ribakoff (josh.ribakoff@gmail.com) on 2010-11-10T11:43:54.000+0000</p> 
        <div class="body">
            <p>Could you just call it insertDelayed() instead of insert(), and not put it on the abstract adapter? I would think it belongs on the mysql adapter, since it is coupled w/ mysql.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kamil Dziedzic (arvenil) on 2011-03-06T17:22:26.000+0000</p> 
        <div class="body">
            <p>Here is a patch to resolve this issue and #ZF-3107. If you don't like it please write what's wrong with it so I could fix it.</p>

<p><a href="http://www.kamil.klecza.pl/zend/ZF-3107_ZF-9484.patch">http://kamil.klecza.pl/zend/ZF-3107_ZF-9484.patch/</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kamil Dziedzic (arvenil) on 2011-03-22T23:41:13.000+0000</p> 
        <div class="body">
            <p>Hello again. I've signed CLA and here is updated patch to ZF 1.11.4 and now it also includes changes to one more similar ticket #ZF-7149.</p>

<p><a href="http://framework.zend.com/issues/secure/attachment/13816/ZF-3107_ZF-7149_ZF-9484.patch">http://framework.zend.com/issues/secure/…</a></p>

<p>I'm waiting for comments.</p>

        </div>
    </div>
    </div>

