<h2>ZF2-401: Add support for RDFa 1.1 doctype</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2012-07-17T05:14:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-20T15:24:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\View</li>
            <li>doctype</li>
            <li>rdfa</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The doctype for RDFa 1.0 is currently supported in the Doctype view helper (Zend\View\Helper\Doctype).</p>

<p>Since 7. June 2012 RDFa 1.1 is now a formal W3C recommendation:
<a href="http://www.w3.org/TR/xhtml-rdfa/">http://www.w3.org/TR/xhtml-rdfa/</a></p>

<p>It would be great support for its doctype could be added. This would allow the use of various new metainformation attributes (vocab, etc).</p>

<p>Patch:
File: Doctype.php</p>

<p>Add (line 31)
    const XHTML1_RDFA11         = 'XHTML1_RDFA11';</p>

<p>Add (line 72 + 1)
                self::XHTML1_RDFA11         =&gt; 'ofollow" href="www.w3.org/MarkUp/DTD/xhtml-rdfa-2.dtd"&gt;www.w3.org/MarkUp/DTD/xhtml-rdfa-2.dtd"&gt;',</p>

<p>Add (Line 126 + 2)
                case self::XHTML1_RDFA11:</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-07-18T16:54:24.000+0000</p> 
        <div class="body">
            <p><a href="https://github.com/zendframework/zf2/pull/1921">Pull Request #1921</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Evan Coury (evan.pro) on 2012-07-20T15:24:02.000+0000</p> 
        <div class="body">
            <p>Merged, thanks!</p>

        </div>
    </div>
    </div>

