<h2>ZF2-489: Form View Helpers do not translate placeholder attribute</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-08-22T15:29:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-09-05T22:25:54.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
        None
                    </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-450">ZF2-450</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Form View Helpers for labels and selects use the translator object to translate labels and select options. Unfortunately, all text based view helpers do not translate any placeholder attribute. This should be added.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralf Eggert (ralf) on 2012-08-23T20:33:06.000+0000</p> 
        <div class="body">
            <p>I add this here, since it is somehow connected. When I add a submit button to a form, the value attribute holds the text displayed on the button. Unfortunately, this value text is not translated at all. Zend\Form\View\Helper\FormSubmit needs to be change to get the value translated if a translator object is set. FormReset and FormButton have the same problem.</p>

<p>Either FormInput::render() must be changed for this or FormSubmit, FormReset and FormButton need to have their own render() method for translation the value attribute.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-08-23T21:11:25.000+0000</p> 
        <div class="body">
            <p>Ralf -- I think that particular instance is fixed on current master due to a PR I merged earlier today. Can you please test?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Martin (cgmartin) on 2012-08-23T21:20:00.000+0000</p> 
        <div class="body">
            <p>Matthew - The earlier PR I think only addressed FormButton. FormSubmit and FormReset are currently still outstanding.</p>

<p>I have a PR ready for FormSubmit (marked for 2.1): <a href="https://github.com/zendframework/zf2/pull/2124">https://github.com/zendframework/zf2/pull/2124</a>
...but FormReset would need the same logic. I will update FormReset and commit to this same PR.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralf Eggert (ralf) on 2012-08-23T21:21:27.000+0000</p> 
        <div class="body">
            <p>Matthew,</p>

<p>I looked here</p>

<p><a href="https://github.com/zendframework/zf2/tree/master/library/Zend/Form/View/Helper">https://github.com/zendframework/zf2/…</a></p>

<p>But there was only a change 5 hours ago for FormMultiCheckbox. I don't see any changes for both the placeholder translation nor the value attribute translation for submit, button and reset.</p>

<p>Am I looking at the wrong place?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralf Eggert (ralf) on 2012-08-23T21:25:33.000+0000</p> 
        <div class="body">
            <p>I wonder why this is marked for 2.1...</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris Martin (cgmartin) on 2012-08-23T21:58:19.000+0000</p> 
        <div class="body">
            <p>Updated PR and included FormReset: <a href="https://github.com/zendframework/zf2/pull/2124">https://github.com/zendframework/zf2/pull/2124</a></p>

<p>On IRC, Matthew mentioned this could probably go into 2.0.1 (earlier than 2.1).</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralf Eggert (ralf) on 2012-08-23T22:01:21.000+0000</p> 
        <div class="body">
            <p>Nice one!</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Robert Boloc (robertboloc) on 2012-08-30T11:17:49.000+0000</p> 
        <div class="body">
            <p>pull request with fix for the view helpers <a href="https://github.com/zendframework/zf2/pull/2270">https://github.com/zendframework/zf2/pull/2270</a></p>

        </div>
    </div>
    </div>

