<h2>ZF2-22: Provide methods for manipulating the Service Locator Map</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2011-06-16T02:54:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-23T17:18:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Di</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Quote Matthew "to eliminate the need for extension, we could simply provide methods for manipulating the map."</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-23T17:18:33.000+0000</p> 
        <div class="body">
            <p>This issue is old and Zend\Di has changed much since it was created.  Please open a new ticket if any specific issues related to this still exist with Zend\Di.</p>

        </div>
    </div>
    </div>

