<h2>ZF2-145: Zend\GData\Youtube throws an Exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-01-23T16:50:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-02T20:13:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Pierre-Louis LAUNAY (laupifrpar)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>When I want get a VideoEntry of YouTube:</p>

<p>$youtube = new \Zend\GData\YouTube();
$videoEntry = $youtube-&gt;getVideoEntry('6GXdJh8nNyk');</p>

<p>An Exception is thrown:</p>

<p>500 Internal Server Error - InvalidArgumentException
A field name was provided without a field value
In the file Zend/Http/Headers.php</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-23T15:24:56.000+0000</p> 
        <div class="body">
            <p>Could you please provide the stack trace?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Samir El Aouar (dagon) on 2012-02-28T16:29:05.000+0000</p> 
        <div class="body">
            <p>Hi,</p>

<p>I got same problem with \Zend\GData\Docs();</p>

<p>$docs = new \Zend\GData\Docs($client);
$feed = $docs-&gt;getDocumentListFeed();</p>

<p>The error is thrown because the default value for $contentType argument in Zend\GData\App::performHttpRequest (line 581) is null, and generates a key-value pair "Content-Type" =&gt; null (line 611) for Zend\Http\Header::addHeaderLine method (line 219).</p>

<p>Fatal error:  Uncaught exception 'Zend\Http\Exception\InvalidArgumentException' with message 'A field name was provided without a field value' in /home/usuarios/samir/public_html/zf2/library/Zend/Http/Headers.php:219
Stack trace:</p>

<h1>0 /home/usuarios/samir/public_html/zf2/library/Zend/Http/Headers.php(190): Zend\Http\Headers-&gt;addHeaderLine('Content-Type', NULL)</h1>

<h1>1 /home/usuarios/samir/public_html/zf2/library/Zend/Http/Client.php(537): Zend\Http\Headers-&gt;addHeaders(Array)</h1>

<h1>2 /home/usuarios/samir/public_html/zf2/library/Zend/GData/App.php(632): Zend\Http\Client-&gt;setHeaders(Array)</h1>

<h1>3 /home/usuarios/samir/public_html/zf2/library/Zend/GData/GData.php(219): Zend\GData\App-&gt;performHttpRequest('GET', '<a href="http://docs.goo">http://docs.goo</a>...', Array, NULL, NULL, NULL)</h1>

<h1>4 /home/usuarios/samir/public_html/zf2/library/Zend/GData/App.php(861): Zend\GData\GData-&gt;performHttpRequest('GET', '<a href="http://docs.goo">http://docs.goo</a>...', Array)</h1>

<h1>5 /home/usuarios/samir/public_html/zf2/library/Zend/GData/App.php(752): Zend\GData\App-&gt;get('<a href="http://docs.goo">http://docs.goo</a>...', NULL)</h1>

<h1>6 /home/usuarios/samir/p in /home/usuarios/samir/public_html/zf2/library/Zend/Http/Headers.php on line 219</h1>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-03-01T22:42:07.000+0000</p> 
        <div class="body">
            <p>This should be fixed with pull request <a href="https://github.com/zendframework/zf2/pull/871">#871</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-03-02T20:13:41.000+0000</p> 
        <div class="body">
            <p>Fixed in beta3</p>

        </div>
    </div>
    </div>

