<h2>ZF2-172: Stdlib\SignalHandlers tests will fail in PHP5.4 or over</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-02-23T14:57:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-03-24T01:50:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I run test such as</p>

<p>$ ~/php-src-trunk/sapi/cli/php ~/tmp/phpunit35_14/bin/phpunit --bootstrap tests/Bootstrap.php tests/Zend/Stdlib</p>

<p>PHPUnit 3.5.15 by Sebastian Bergmann.</p>

<p>..........................................................
Fatal error: Call to undefined function ZendTest\Stdlib\SignalHandlers\InstanceMethod::handler() in /home/kazusuke/dev/zendframework_zf2/library/Zend/Stdlib/CallbackHandler.php on line 176</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-02-23T19:07:40.000+0000</p> 
        <div class="body">
            <p>PR submitted: <a href="https://github.com/zendframework/zf2/pull/822">https://github.com/zendframework/zf2/pull/822</a></p>

        </div>
    </div>
    </div>

