<h2>ZF2-552: Zend\Validator\EmailAddress handle  \' character</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-09-13T19:02:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-09-13T21:11:58.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Abdul Malik Ikhsan (samsonasik)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Validator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>i test :
[code]<br />
        $validator = new \Zend\Validator\EmailAddress();
        if ($validator-&gt;isValid('samsona\'sik@gmail.com')) {<br />
            /* email appears to be valid <em>/
             echo 'email is valid';
        } else {
            /</em> email is invalid; print the reasons */
            foreach ($validator-&gt;getMessages() as $message) {
                echo "$message\n";
            }
        }
[/code]
and appears email is valid.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-09-13T21:11:46.000+0000</p> 
        <div class="body">
            <p>The "'" character is perfectly valid as part of the local part of an email address (the portion preceding the @ separating the local and domain segments).</p>

<p>See <a href="http://en.wikipedia.org/wiki/Email_address#Local_part">http://en.wikipedia.org/wiki/Email_address/…</a> for details.</p>

        </div>
    </div>
    </div>

