<h2>ZF2-463: Zend\Navigation\Container::addPage does not inject RouteMatch or Router</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-08-12T11:04:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:14:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Steve Talbot (stevetalbot)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Navigation</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If you create a Zend\Navigation\Navigation using the DefaultNavigationFactory, the Router and RouteMatch are automatically injected into every MVC page.</p>

<p>However, if you subsequently add MVC pages to the Navigation using the Navigation::addPage method, the Router and RouteMatch are not injected for you.  You can set a default router on Zend\Navigation\Page\Mvc, but you have to set the RouteMatch manually every time.</p>

<p>Would you please consider making one of the following modifications:</p>

<ol><li><p>Change Zend\Navigation\Page\Mvc so you can specify a default RouteMatch as well as a default Router.</p></li>
<li><p>Change Zend\Navigation\AbstractContainer so that it automatically injects the Router and RouteMatch on every call to addPage.</p></li>
</ol><p>Many thanks!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-09-18T20:54:02.000+0000</p> 
        <div class="body">
            <p>I think your first suggestion is a good idea.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:14:59.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2525">https://github.com/zendframework/zf2/issues/2525</a></p>

        </div>
    </div>
    </div>

