<h2>ZF2-23: Form\Decorator\File not render</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-06-21T07:36:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-11-10T12:12:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Pádraic Brady (padraic)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
            <li>Decorator</li>
            <li>zf-crteam-padraic</li>
            <li>zf-crteam-priority</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>File decorator use old (Zend\View\ViewEngine) code.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Pádraic Brady (padraic) on 2011-08-13T17:15:57.000+0000</p> 
        <div class="body">
            <p>Marked as not an issue given Zend\Form and Zend\View are both in development and the ZF2 master branch will see significant change in the future.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Andrey Kolyshkin (morfi) on 2011-11-10T12:12:33.000+0000</p> 
        <div class="body">
            <p>Fix in github</p>

        </div>
    </div>
    </div>

