<h2>ZF2-79: File Decorator incorrect call of helper leads loss of attributes</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-17T18:17:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-10-27T19:27:28.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Thomas Weidner (thomas)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
            <li>Zend\View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi all!</p>

<p>In view helper FormFile on line 52 __invoke prototype:</p>

<pre class="highlight"><code>
    public function __invoke($name, $attribs = null)
</code></pre>

<p>But file decorator call this method (with proxy of course) with 3 arguments:</p>

<pre class="highlight"><code>
    $markup[] = $view-&gt;formFile($name, null, $attribs);
</code></pre>

<p>This leads to the loss of an element's attributes.</p>

<p>Files:
- Zend/Form/Decorator/File.php:127
- Zend/Form/Decorator/File.php:130
- Zend/Form/Decorator/FormFile.php:52 in f4e41abad2</p>

<p>Congratulations with the first beta!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-10-27T19:27:28.000+0000</p> 
        <div class="body">
            <p>Fixed with <a href="https://github.com/zendframework/zf2/pull/523">GH-523</a></p>

        </div>
    </div>
    </div>

