<h2>ZF2-334: ssh connection for Document List</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-05-31T15:07:22.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-04T14:09:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Gdata</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In order to use the document list API, we need to use SSH url.</p>

<p>But in library\Zend\GData\Docs.php at line 38, the url is '<a href="http://docs.google.com/feeds/documents/private/full">http://docs.google.com/feeds/documents/…</a>' instead of <a href="https://docs.google.com/feeds/documents/private/full">https://docs.google.com/feeds/documents/…</a></p>

<p>We could give a specific url to documentListFeed function but as to a functional address in the constants, no ?</p>

<p>I have try with personnal and pro account it works with https and not with http.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-03T19:26:46.000+0000</p> 
        <div class="body">
            <p>I guess that when you are talking about SSH url you really want to say HTTP secure url.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Fabien Chambosse (fchambos) on 2012-06-04T10:31:51.000+0000</p> 
        <div class="body">
            <p>Excuse me, I wanted talking about SSL (and of course no SSH). So yes I speak of HTTP secure url.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-04T14:09:20.000+0000</p> 
        <div class="body">
            <p>Fixed with <a href="https://github.com/zendframework/zf2/pull/1441">https://github.com/zendframework/zf2/pull/1441</a></p>

        </div>
    </div>
    </div>

