<h2>ZF2-81: E_STRICT error in Mvc\Bootstrap &quot;Redefining already defined constructor for class Zend\Mvc\Bootstrap&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-10-24T01:31:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-23T19:30:33.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Ice Wolf (icywolfy)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Mvc</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>(Zend\Mvc is not a valid component, according to the input box on this ticket form)</p>

<p>Strict standards: Redefining already defined constructor for class Zend\Mvc\Bootstrap in /www/fdev/Libraries/Zend/Mvc/Bootstrap.php on line 88.</p>

<p>Zend\Mvc\Bootstrap cannot implement interface Bootstrapper without throwing E_STRICT notice.
The interface requires a method "bootstrap" which is the name of the constructor for the class "Bootstrap" (in addition to __construct() )
Thus, the error "redifining already defined constructor".</p>

<p>Fixing this will require renaming the class, or the interface method,
Which implies updating the QuickStart guide as one of the two lines below will have to be updated to meet this fix.
 "
$bootstrap      = new Zend\Mvc\Bootstrap($moduleManager);
$bootstrap-&gt;bootstrap($application);
 "</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-02-23T19:11:18.000+0000</p> 
        <div class="body">
            <p>Which version of PHP is raising this?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Evan Coury (evan.pro) on 2012-02-23T19:26:38.000+0000</p> 
        <div class="body">
            <p>This appears to have been fixed in 5.3.3 / 5.2.14.</p>

<p><a href="https://bugs.php.net/bug.php?id=52160">https://bugs.php.net/bug.php?id=52160</a></p>

<p>Since we're targeting 5.3.3+ for ZF2, I'd say this is not an issue.</p>

<p>Source: <a href="http://www.php.net/ChangeLog-5.php">http://www.php.net/ChangeLog-5.php</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Evan Coury (evan.pro) on 2012-02-23T19:30:33.000+0000</p> 
        <div class="body">
            <p>This only affects versions of PHP below ZF2's target version (5.3.3).</p>

        </div>
    </div>
    </div>

