<h2>ZF2-368: ServiceManagerAwareInterface not working? It's not Bug ZF2-332</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-20T10:10:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-24T07:43:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Shangzhi Pan (shangzhi)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\ServiceManager</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>I'm trying to build a ZF2 application at the moment and I'm using the latest Github source of ZF2. I already checked that I have the fixed version of Bug ZF2-332</p>

<p>I wrote a Controller Plugin and impremented the ServiceManagerAwareInterface. But somehow it does not call setServiceManager() in my plugin. If I write an exit into the setServiceManager() it does not exit there. PHP is giving me a 'Fatal error: Call to a member function get() on a non-object' on this line:$userSerivce = $this-&gt;getServiceManager()-&gt;get('user_service');</p>

<p>I've googled and tried almost everything... Nothing seems to work. Have I done something wrong or is this a bug?</p>

<p>Here is my test code:</p>

<p>Plugin.php:</p>

<p>namespace MyApp\Controller\Plugin;</p>

<p>use Zend\Mvc\Controller\Plugin\AbstractPlugin;
use Zend\ServiceManager\ServiceManager;
use Zend\ServiceManager\ServiceManagerAwareInterface;</p>

<p>class AppAuthentication extends AbstractPlugin implements ServiceManagerAwareInterface
{</p>

<pre><code>protected $serviceManager;

public function hasIdentity()
{       
$userSerivce = $this-&gt;getServiceManager()-&gt;get('user_service');             
}

public function getServiceManager()
{
    return $this-&gt;serviceManager;
}

public function setServiceManager(ServiceManager $serviceManager)
{
    $this-&gt;serviceManager = $serviceManager;
}
</code></pre>

<p>}</p>

<p>module.config.php:</p>

<p>'controller' =&gt; array(
        'classes' =&gt; array(
            'app' =&gt; 'MyApp\Controller\EywaController',
            'appIndex' =&gt; 'MyApp\Controller\IndexController'
        ),
        'map' =&gt; array(
            'appauth' =&gt; 'MyApp\Controller\Plugin\AppAuthentication',
        ),
    ),</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Shangzhi Pan (shangzhi) on 2012-07-24T07:43:08.000+0000</p> 
        <div class="body">
            <p>This problem vanished with the release of Beta 5... So never mind :)</p>

        </div>
    </div>
    </div>

