<h2>ZF2-270: Validator\Db\NoRecordExists - Fatal error: Class 'Zend\Db\Table\AbstractTable' not found</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-17T14:39:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-09T14:15:39.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Roman Vidyayev (cmple)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Validator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-200">ZF2-200</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The NoRecordExists, RecordExists validator must be re factored to comply with the Zend\Db changes</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by simon liu (simonliu) on 2012-04-18T02:55:12.000+0000</p> 
        <div class="body">
            <p>Roman, do you means Zend\Validator\Db\AbstractDb must be re factored? since there is no external class in NoRecordExists or RecordExists.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roman Vidyayev (cmple) on 2012-04-18T14:29:06.000+0000</p> 
        <div class="body">
            <p>Yes, its the Zend\Validator\Db\AbstractDb class</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roman Vidyayev (cmple) on 2012-04-18T14:32:09.000+0000</p> 
        <div class="body">
            <p>Adding pull request:
<a href="https://github.com/zendframework/zf2/pull/1054">https://github.com/zendframework/zf2/pull/1054</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-05-09T14:13:21.000+0000</p> 
        <div class="body">
            <p>Fixed with <a href="https://github.com/zendframework/zf2/pull/1178">https://github.com/zendframework/zf2/pull/1178</a></p>

        </div>
    </div>
    </div>

