<h2>ZF2-300: Allow Zend\Config\Reader\Xml to support multiple values of the same name as an array</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-05-14T10:18:03.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-04T18:00:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                simon liu (simonliu)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                simon liu (simonliu)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>see: 
<a href="http://framework.zend.com/issues/browse/ZF-2285">http://framework.zend.com/issues/browse/ZF-2285</a>
<a href="http://framework.zend.com/issues/browse/ZF-2437">http://framework.zend.com/issues/browse/ZF-2437</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by simon liu (simonliu) on 2012-05-16T02:24:30.000+0000</p> 
        <div class="body">
            <p>I fix it, pull request is here:</p>

<p><a href="https://github.com/zendframework/zf2/pull/1224">https://github.com/zendframework/zf2/pull/1224</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-04T18:00:21.000+0000</p> 
        <div class="body">
            <p>PR Merged</p>

        </div>
    </div>
    </div>

