<h2>ZF2-428: RowGateway\AbstractRowGateway delete method does not do anything.</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-07-26T16:27:30.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-18T09:17:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Demian Katz (demiankatz)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The RowGateway\AbstractRowGateway class defines a delete method, but the body has not been implemented yet as of ZF2 RC1.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-18T09:17:08.000+0000</p> 
        <div class="body">
            <p>delete() method is implemented in the new RC4.</p>

        </div>
    </div>
    </div>

