<h2>ZF2-116: Zend\Filter\StaticFilter not working as expected</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-12-07T20:13:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-06T11:09:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Brandon Mueller (fatmuemoo)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Filter</li>
            <li>Zend\Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>While trying to use a static filter, I discovered that some of the filters where throwing an Exception from the Loader. In fact, I ran a test and descovered that 109 out 113 plugins failed.</p>

<p>Code for the test here:
<a href="http://www.pastebucket.com/1185">http://www.pastebucket.com/1185</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-06T10:49:26.000+0000</p> 
        <div class="body">
            <p>First the pastebucket provided is testing Validator\StaticValidator instead of Filter\StaticFilter</p>

<p>Fixing this I obtained 27 out 113 failed and some PHP errors</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-06T11:08:13.000+0000</p> 
        <div class="body">
            <p>I don't found any issue, some Filters need arguments and others have external dependencies.</p>

<p>All are loaded without exceptions</p>

        </div>
    </div>
    </div>

