<h2>ZF2-566: Undefined indexes and huge args-data in Zend\Log\Formatter\ExceptionHandler::format</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-09-17T19:24:11.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:12:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Log</li>
            <li>Zend\Log\Formatter\ExceptionHandler</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend\Log\Formatter\ExceptionHandler::format the assumtion is made that the indexes <em>file</em>, <em>line</em>, <em>class</em> and <em>type</em> always exist:</p>

<pre class="highlight"><code>
foreach ($event<a href="http://framework.zend.com/issues/browse/ZF2-562">'extra']['trace'] as $trace) {
    $outputTrace .= "File  : {$trace['file']}\n"
                  . "Line  : {$trace['line']}\n"
                  . "Func  : {$trace['function']}\n"
                  . "Class : {$trace['class']}\n"
                  . "Type  : " . $this-&gt;getType($trace['type']) . "\n"
                  . "Args  : " . print_r($trace['args'], true) . "\n";
}</a></code></pre>

<p>But:</p>

<h1>The first trace does not contain the <em>file</em> and <em>line</em> indexes</h1>

<h1>When the trace refers to a function (like call_user_func()), the indexes <em>class</em> and <em>type</em> do not exist</h1>

<h1>print_r($trace['args'], true) creates a huge, huge string of data because all classes and their descendants are completely added as a string</h1>

<p>I honestly think the logging (of exceptions) needs a serious rewrite, because there are just so many errors in it that it is unusable in this stage (also see [ZF2-562 and <a href="http://framework.zend.com/issues/browse/ZF2-563">ZF2-563</a>).</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:12:24.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2592">https://github.com/zendframework/zf2/issues/2592</a></p>

        </div>
    </div>
    </div>

