<h2>ZF2-317: Controller not found automagically..</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-05-25T10:12:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:15:15.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Mvc\Controller</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The docs mention this:</p>

<p>"ZendSkeletonApplication ships with a "default route" that will likely get you to this action. That route basically expects "/{controller}/{action}", which allows you to specify this: "/zend-user-hello/world". We're going to create a route here mainly for illustration purposes, as creating explicit routes is a recommended practice. The application will look for a Zend\Mvc\Router\RouteStack instance to setup routing. The default generated router is a Zend\Mvc\Router\Http\TreeRouteStack. "</p>

<p>Only with me the route is never found untill i add the controller in the module config:</p>

<p>'controller' =&gt; array(
 'classes' =&gt; array(
   'My-App-Index' =&gt; 'MyApp\Controller\IndexController',
 ),
)</p>

<p>Am not sure if this is supposed to be like this or if this is a bug?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by BLANCHON Vincent (blanchon_vincent) on 2012-05-26T16:06:45.000+0000</p> 
        <div class="body">
            <p>Can you add your routes, controller and Di configuration ?</p>

<p>With default route, ControllerLoader find a "index" controller, you must write Di alias or an "index" key in "controller" configuration.</p>

<p>If you just add</p>

<pre class="highlight"><code>
'My-App-Index' =&gt; 'MyApp\Controller\IndexController',
</code></pre>

<p>Your app can't work.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris de Kok (mech7) on 2012-05-26T19:01:52.000+0000</p> 
        <div class="body">
            <p>Actually it does work with beta 4 with only this. But the documentation has a note:
<a href="http://packages.zendframework.com/docs/latest/manual/en/zend.mvc.quick-start.html">http://packages.zendframework.com/docs/latest/…</a></p>

<p>"Note
ZendSkeletonApplication ships with a "default route" that will likely get you to this action. That route basically expects "/{controller}/{action}", which allows you to specify this: "/zend-user-hello/world". We're going to create a route here mainly for illustration purposes, as creating explicit routes is a recommended practice. The application will look for a Zend\Mvc\Router\RouteStack instance to setup routing. The default generated router is a Zend\Mvc\Router\Http\TreeRouteStack."</p>

<p>Which does not mention adding the controller to the configuration first before it can be found by the default route, which is confusing as ZF 1 will load controllers automatically not needing to add them to the config first.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Chris de Kok (mech7) on 2012-05-26T19:22:00.000+0000</p> 
        <div class="body">
            <p>Yes i understand this part is in the controller confguration but i think you are missing my point. My point is that the documentation is misleading as it explains that the default route will take me to this controller and action. Which it cannot untill i add it to the configuration.
It would be better to add this to the documentation so it is less confusing for end users.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by BLANCHON Vincent (blanchon_vincent) on 2012-05-26T19:23:39.000+0000</p> 
        <div class="body">
            <p>Ok you use a configuration like :</p>

<pre class="highlight"><code>
'defaults' =&gt; array(
      'controller' =&gt; 'My-App-Index',
            'action'     =&gt; '???',
),
</code></pre>

<p>So if you defined</p>

<pre class="highlight"><code>
'My-App-Index' =&gt; 'MyApp\Controller\IndexController',
</code></pre>

<p>it's work ok. But without that, app cannot work, because ControllerLoader (based on ServiceManager) don't know what is the controller associated to 'My-App-Index' identifier.</p>

<p>Evan Coury work on a feature based on the route /module/controller/action and i think this feature will resolve this problem.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:15:15.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2484">https://github.com/zendframework/zf2/issues/2484</a></p>

        </div>
    </div>
    </div>

