<h2>ZF2-544: Collection extract method updates targetElement object to an existing value</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-09-11T09:11:08.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:14:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Oliver Leisalu (inditel)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Collection extract method updates targetElement object property into an existing value. This will cause a lot of problems if adding new elements is allowed.</p>

<p>In extract method foreach cluase current code:
$this-&gt;targetElement-&gt;object = $value;
$values[$key] = $this-&gt;targetElement-&gt;extract();</p>

<p>It should be something like this:
$prevValue = $this-&gt;targetElement-&gt;object;
$this-&gt;targetElement-&gt;object = $value;
$values[$key] = $this-&gt;targetElement-&gt;extract();
$this-&gt;targetElement-&gt;object = $prevValue;</p>

<p>If this is not done, targetElement will have values from the last object that was in the list - for example ID.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:14:34.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2574">https://github.com/zendframework/zf2/issues/2574</a></p>

        </div>
    </div>
    </div>

