<h2>ZF2-578: ServiceListener and factories</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-09-21T08:36:10.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:11:05.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                BLANCHON Vincent (blanchon_vincent)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Mvc</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In Zend/Mvc/Service/ServiceListenerFactory.php :</p>

<p>3 factories :</p>

<p>'factories' =&gt; array(
    'ConsoleRouter' =&gt; 'Zend\Mvc\Service\RouterFactory',
    'HttpRouter' =&gt; 'Zend\Mvc\Service\RouterFactory',
    'Router' =&gt; 'Zend\Mvc\Service\RouterFactory',
),</p>

<p>I think :</p>

<blockquote>
  <p>we must mark "ConsoleRouter" and "HttpRouter" like alias
  or we must mark "ConsoleRouter" like invokable with "Zend\Mvc\Router\Http\TreeRouteStack" and "HttpRouter" with "Zend\Mvc\Router\Console\SimpleRouteStack" because with this version (2.0.0), if i get "ConsoleRouter" with ServiceManager, i am not sure i will have a instance of the console router, because "Zend\Mvc\Service\RouterFactory" choose automatically !</p>
</blockquote>

<p>What is your feedback ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:11:05.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2603">https://github.com/zendframework/zf2/issues/2603</a></p>

        </div>
    </div>
    </div>

