<h2>ZF2-395: DI doesnt contruct object properly when default contructor param other then null</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-07-15T00:26:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:15:08.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Marek Nos (fabicz)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Di</li>
            <li>Zend\ServiceManager</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Having this in config:</p>

<pre class="highlight"><code>
'di' =&gt; array(
    'instance' =&gt; array(
        'alias' =&gt; array(
            'Session' =&gt; 'Zend\Session\Container',
        ,
    ),
),
</code></pre>

<p>And running $this-&gt;locator-&gt;get('Session') gives exception:</p>

<p>1) An abstract factory could not create an instance of session(alias: Session).
2) An exception was raised while creating "Session"; no instance returned
3)</p>

<pre class="highlight"><code>

Zend\Session\Exception\InvalidArgumentException

Soubor:

    D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Session\Container.php:64

Zpráva:

    Name passed to container is invalid; must consist of alphanumerics, backslashes and underscores only

Trasování zásobníku (Stack trace):

    #0 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Di\Di.php(382): Zend\Session\Container-&gt;__construct(NULL, NULL)
    #1 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Di\Di.php(204): Zend\Di\Di-&gt;createInstanceViaConstructor('Zend\Session\Co...', Array, 'Session')
    #2 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Di\Di.php(153): Zend\Di\Di-&gt;newInstance('Session', Array)
    #3 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\ServiceManager\Di\DiServiceFactory.php(101): Zend\Di\Di-&gt;get('Session', Array)
    #4 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\ServiceManager\Di\DiAbstractServiceFactory.php(42): Zend\ServiceManager\Di\DiServiceFactory-&gt;get('Session', Array, true)
    #5 [internal function]: Zend\ServiceManager\Di\DiAbstractServiceFactory-&gt;createServiceWithName(Object(Zend\ServiceManager\ServiceManager), 'session', 'Session')
    #6 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(672): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'session', 'Session')
    #7 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(803): Zend\ServiceManager\ServiceManager-&gt;createServiceViaCallback(Array, 'session', 'Session')
    #8 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(446): Zend\ServiceManager\ServiceManager-&gt;createFromAbstractFactory('session', 'Session')
    #9 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(391): Zend\ServiceManager\ServiceManager-&gt;create(Array)
    #10 D:\workspaces\Babysitting\ZendApplication\module\User\src\User\Controller\User.php(18): Zend\ServiceManager\ServiceManager-&gt;get('Session')
    #11 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(137): User\Controller\User-&gt;loginAction()
    #12 [internal function]: Zend\Mvc\Controller\AbstractActionController-&gt;execute(Object(Zend\Mvc\MvcEvent))
    #13 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(453): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #14 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(193): Zend\EventManager\EventManager-&gt;triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #15 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Mvc\Controller\AbstractActionController.php(104): Zend\EventManager\EventManager-&gt;trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #16 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Mvc\DispatchListener.php(139): Zend\Mvc\Controller\AbstractActionController-&gt;dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #17 [internal function]: Zend\Mvc\DispatchListener-&gt;onDispatch(Object(Zend\Mvc\MvcEvent))
    #18 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(453): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #19 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\EventManager\EventManager.php(193): Zend\EventManager\EventManager-&gt;triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #20 D:\workspaces\Babysitting\ZendApplication\vendor\zendframework\zendframework\library\Zend\Mvc\Application.php(305): Zend\EventManager\EventManager-&gt;trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #21 D:\workspaces\Babysitting\ZendApplication\public\index.php(12): Zend\Mvc\Application-&gt;run()
    #22 {main}
</code></pre>

<p>Seems it tries to contruct object with null params even they are all optional.</p>

<p>Expected behaviour same as if I put this into the config:</p>

<pre class="highlight"><code>
'service_manager' =&gt; array(
    'invokables' =&gt; array(
        'Session' =&gt; 'Zend\Session\Container',
    ),
),
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:15:08.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2500">https://github.com/zendframework/zf2/issues/2500</a></p>

        </div>
    </div>
    </div>

