<h2>ZF2-223: 404s ActionController::notFound should not modify the route match</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-03-15T01:44:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:15:24.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Mvc</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Raising a 404 in a controller by calling notFound causes the view layer to look for the wrong template.</p>

<p>It shouldn't modify the routematch. Per weirophinney:</p>

<p>"We need to alter this to not modify the route match; it's a bad practice
stemming from the hack we used for view rendering prior to introducing
the new view layer. "</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:15:24.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2464">https://github.com/zendframework/zf2/issues/2464</a></p>

        </div>
    </div>
    </div>

