<h2>ZF2-434: Zend\View\HelperPluginManager fails when no translation key exists in configuration</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-07-31T14:14:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-31T14:47:44.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\I18n</li>
            <li>Zend\View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When using ZendSkeletonApplication with translation stripped out, I see the following error when using a view helper (HeadTitle in this case):</p>

<pre class="highlight"><code>
Uncaught exception 'Zend\I18n\Exception\InvalidArgumentException' with message 'Zend\I18n\Translator\Translator::factory expects an array or Traversable object; received "NULL"'
</code></pre>

<p>This is caused by Zend\I18n\Translator\TranslatorServiceFactory not checking that 'translator' config key exists before passing it to Translator::factory.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-07-31T14:29:32.000+0000</p> 
        <div class="body">
            <p>ZF2 PR: <a href="https://github.com/zendframework/zf2/pull/2063">https://github.com/zendframework/zf2/pull/2063</a></p>

        </div>
    </div>
    </div>

