<h2>ZF2-75: Fixes CS for some abstract classes (classname, and location)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Coding Standards Violation</dd>

    <dt>Created:</dt>
    <dd>2011-10-01T07:52:41.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-09T15:30:55.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Benoît Durand (intiilapa)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\I18n</li>
            <li>Zend\Ldap</li>
            <li>Zend\Pdf</li>
            <li>Zend\Tag</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>source : <a href="https://dl.dropbox.com/u/5759329/Zf2CodingStandards-r2.html#toc_1.3.3"></a><a href="https://dl.dropbox.com/u/5759329/Zf2CodingStandards-r2.html#toc_1.3.3">https://dl.dropbox.com/u/5759329/…</a></p>

<p>{quote}
Abstract Classes</p>

<p>Abstract classes follow the same conventions as classes, with one additional rule: abstract class names MUST begin with the term, "Abstract". As examples, "AbstractAdapter" and "AbstractWriter" are both considered valid abstract class names.</p>

<p>Abstract classes SHOULD be in the same namespace as concrete implementations.
{quote}</p>

<pre class="highlight"><code>
$ grep -r "abstract class" library/ | grep -v Abstract | grep -v " \* "
</code></pre>

<p>Matthew or Ralph, can you add Zend\Mvc in components list please?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Thomas Weidner (thomas) on 2011-10-03T20:38:04.000+0000</p> 
        <div class="body">
            <p>Zend_Translator changed with <a href="https://github.com/zendframework/zf2/pull/460">GH-460</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-02-26T11:19:55.000+0000</p> 
        <div class="body">
            <p>Zend_Navigation changed with <a href="https://github.com/zendframework/zf2/pull/823">GH-823</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-03-14T12:03:00.000+0000</p> 
        <div class="body">
            <p>I will fix this for Zend\Ldap component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-05-22T10:57:49.000+0000</p> 
        <div class="body">
            <p>Zend_Form removed as affected component.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-05-23T15:22:15.000+0000</p> 
        <div class="body">
            <p>I close this issue in favor of the open story in AgileZen (#52)</p>

        </div>
    </div>
    </div>

