<h2>ZF2-316: Locale XML files for zh_CN and zh_TW are missing</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-05-25T08:34:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-09T15:31:12.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\I18n</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When setting the locale of \Zend\Date\Date to zh_CN or zh_TW, the following exceptions are thrown:</p>

<hr /><p>Fatal error: Uncaught exception 'Zend\Locale\Exception\InvalidArgumentException' with message 'Missing locale file '/var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/../../../../resources/cldr/zh_Hans_CN.xml'' in /var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/Cldr.php on line 142
( ! ) Zend\Locale\Exception\InvalidArgumentException: Missing locale file '/var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/../../../../resources/cldr/zh_Hans_CN.xml' in /var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/Cldr.php on line 142</p>

<hr /><p>Fatal error: Uncaught exception 'Zend\Locale\Exception\InvalidArgumentException' with message 'Missing locale file '/var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/../../../../resources/cldr/zh_Hant_TW.xml'' in /var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/Cldr.php on line 142
( ! ) Zend\Locale\Exception\InvalidArgumentException: Missing locale file '/var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/../../../../resources/cldr/zh_Hant_TW.xml' in /var/www/www.example.com/vendor/zendframework/zendframework/library/Zend/Locale/Data/Cldr.php on line 142</p>

<hr />
    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-04T14:24:20.000+0000</p> 
        <div class="body">
            <p>This will not be fixed until the new i18n component is released.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-26T14:11:14.000+0000</p> 
        <div class="body">
            <p>Finally this will not be fixed since Zend\Date and Zend\Locale will be removed in favor of the native PHP classes.</p>

<p><a href="http://framework.zend.com/wiki/display/ZFDEV2/RFC+-+i18n+layer">http://framework.zend.com/wiki/display/…</a></p>

        </div>
    </div>
    </div>

