<h2>ZF2-457: Fatal error: Call to undefined method Zend\Form\Element::getCheckedValue() in Zend\Form\View\Helper\FormCheckbox.php on line 48</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-08-09T15:23:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-18T09:23:29.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zion Ng (kitthrng)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
            <li>Zend\Form\Element\Checkbox</li>
            <li>checkbox</li>
            <li>formCheckbox</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Got the error shown in Summary when using the formCheckbox helper to render a checkbox.
Tested against zendframework-zf2-release-2.0.0rc2-86-g8fb1930</p>

<pre class="highlight"><code>
// sample form
namespace Web\Form;
use Zend\Form\Form;
class Test extends Form
{
    public function __construct($name = null)
    {
        parent::__construct($name);

        $this-&gt;setAttribute('method', 'post');

        $this-&gt;add(array(
            'name' =&gt; 'testcheck',
            'attributes' =&gt; array(
                'type' =&gt; 'checkbox',
                'checked' =&gt; false,
            ),
            'options' =&gt; array(
                'label' =&gt; 'Test option',
            ),
        ));
    }
}
</code></pre>

<pre class="highlight"><code>
// sample controller
public testAction()
{
    $form = new \Web\Form\Test();
    return array('form' =&gt; $form);
}
</code></pre>

<pre class="highlight"><code>
// sample view script
&lt;?php echo $this-&gt;formCheckbox($form-&gt;get('testcheck')); ?&gt;
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Chris Martin (cgmartin) on 2012-08-12T14:05:11.000+0000</p> 
        <div class="body">
            <p>The formCheckbox helper requires that the Element is of type Zend\Form\Element\Checkbox in order to get extra information for rendering the checkbox (checked, unchecked, useHiddenElement values).</p>

<p>Added PR to ensure that Checkbox Element is used:
<a href="https://github.com/zendframework/zf2/pull/2156">https://github.com/zendframework/zf2/pull/2156</a></p>

<p>Downgrading issue from Blocker to Major since there is a workaround via Zend\Form\Element\Checkbox.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-18T09:23:29.000+0000</p> 
        <div class="body">
            <p>Patch merged</p>

        </div>
    </div>
    </div>

