<h2>ZF2-354: Wrong paramater for file_put_contents</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-11T16:09:49.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-13T19:51:40.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Config</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In the AbstractWriter, line 65, a wrong parameter is passed to the file_put_contents function.
$exclusiveLock is used but $flags would make more sense.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-13T19:51:40.000+0000</p> 
        <div class="body">
            <p>This will be fixed with <a href="https://github.com/zendframework/zf2/pull/1479">https://github.com/zendframework/zf2/pull/1479</a></p>

        </div>
    </div>
    </div>

