<h2>ZF2-465: Some view helpers depend on renderer methods not defined in Zend\View\Renderer\RendererInterface</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-08-14T09:18:55.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:16:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The Partial view helper plugin currently has dependencies on renderer methods such as vars() and setVars() which are provided by Zend\View\Renderer\PhpRenderer but are not defined in Zend\View\Renderer\RendererInterface.  This limits the usefulness of the Partial helper plugin (and any others which utilise it internally) since they can only be used with the PHP Renderer.</p>

<p>On quick inspection a handful of other helpers appear to be affected, including Layout and HeadMeta, which require the plugin() method.</p>

<p>If the provided view helpers are only intended to be used with PHP templates then Zend\View\Helper\AbstractHelper::setView() should require a concrete implementation of Zend\View\Renderer\PhpRenderer rather than any implementation of Zend\View\Renderer\RendererInterface.</p>

<p>Ideally, Zend\View\Renderer\RendererInterface would be updated to include these additional methods or perhaps an AbstractRenderer could be provided?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:16:34.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2526">https://github.com/zendframework/zf2/issues/2526</a></p>

        </div>
    </div>
    </div>

