<h2>ZF2-447: Inconsistency in 'controller' key causes error with Zend\Navigation\Page::isActive()</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-08-04T09:34:57.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:15:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Zion Ng (kitthrng)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Navigation</li>
            <li>RouteMatch</li>
            <li>Zend\Navigation\Page\Mvc</li>
            <li>isActive</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Problem getting the router, menu view helper and breadcrumbs view helper to work in sync.</p>

<p>Sample dump of {{$reqParams}} and {{$myParams}} at line 120 of {{Zend\Navigation\Page::isActive()}}, just before {{if (null !== $this-&gt;getRoute()}} on line 121:</p>

<pre class="highlight"><code>
  '__NAMESPACE__' =&gt; string 'Web\Controller' (length=14)
  'controller' =&gt; string 'Web\Controller\Tools' (length=20)
  'action' =&gt; string 'calendar' (length=8)
  '__CONTROLLER__' =&gt; string 'tools' (length=5)
</code></pre>

<pre class="highlight"><code>
  'controller' =&gt; string 'tools' (length=5)
  'action' =&gt; string 'calendar' (length=8)
</code></pre>

<p>The 'controller' key is checked to see if the page is active, which in this case fails, unless {{<strong>CONTROLLER</strong>}} is used for comparison.</p>

<pre class="highlight"><code>
'Home' =&gt; array(
    'label' =&gt; 'Home',
    'route' =&gt; 'web',
    'controller' =&gt; 'index',
    'action' =&gt; 'index',
),
'Calendar' =&gt; array(
    'label'  =&gt; 'Calendar',
    'route' =&gt; 'web',
    'controller' =&gt; 'tools',
    'action' =&gt; 'calendar',
),
</code></pre>

<p>If 'controller' for 'Calendar' is set to 'Web\Controller\Tools', isActive would work but the href generated would be /web/Web/Controller/Tools/calendar and not/web/tools/calendar.
The breadcrumbs view helper detects 'Home' as the active page even though 'Calendar' is the actual active page.</p>

<pre class="highlight"><code>
'router' =&gt; array(
    'routes' =&gt; array(
        'web' =&gt; array(
            'type'    =&gt; 'Zend\Mvc\Router\Http\Segment',
            'options' =&gt; array(
                'route'    =&gt; '/web[/:controller][/:action]',
                'constraints' =&gt; array(
                    'controller' =&gt; '[a-zA-Z][a-zA-Z0-9_-]*',
                    'action'     =&gt; '[a-zA-Z][a-zA-Z0-9_-]*',
                ),
                'defaults' =&gt; array(
                    '__NAMESPACE__' =&gt; 'Web\Controller',
                    'controller'    =&gt; 'index',
                    'action'        =&gt; 'index',
                ),
            ),
            'may_terminate' =&gt; true,
            'child_routes' =&gt; array(
                'wildcard' =&gt; array(
                    'type' =&gt; 'Zend\Mvc\Router\Http\Wildcard',
                    'options' =&gt; array(
                        'key_value_delimiter' =&gt; '/',
                        'param_delimiter' =&gt; '/',
                    ),
                    'may_terminate' =&gt; true,
                ),
                'trailingSlash' =&gt; array(
                    'type' =&gt; 'Zend\Mvc\Router\Http\Literal',
                    'options' =&gt; array(
                        'route'    =&gt; '/',
                        'defaults' =&gt; array(
                        ),
                    ),
                ),
            ),
        ), // end web route
    ), // end routes
), // end router
</code></pre>

<p>The other alternative might be to create a route for each page. But if there are 10 controllers each having 5 actions, 50 routes would need to be defined?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-09-18T20:32:37.000+0000</p> 
        <div class="body">
            <p>Code tags added.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-09-18T20:55:26.000+0000</p> 
        <div class="body">
            <p>I will write an unit test to check your router and navigation configuration.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:15:02.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2515">https://github.com/zendframework/zf2/issues/2515</a></p>

        </div>
    </div>
    </div>

