<h2>ZF2-251: Zend\Di\Definition\CompilerDefinition</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-03T05:47:44.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-26T15:52:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                BLANCHON Vincent (blanchon_vincent)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Di</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi,</p>

<p>In Zend\Di\Definition\CompilerDefinition :</p>

<p>public function getClassSupertypes($class)
{
        if (!array_key_exists($class, $this-&gt;classes[$class])) {
[...]</p>

<p>Use array_key_exists($class, $this-&gt;classes) and not array_key_exists($class, $this-&gt;classes[$class])</p>

<p>And in line 57 :</p>

<p>public function addCodeScannerFile(FileScanner $fileScanner)</p>

<p>Not namespace add for Zend\Code\Scanner\FileScanner, so for zf2 FileScanner is a Zend\Di\Definition\FileScanner class but don't exist.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by BLANCHON Vincent (blanchon_vincent) on 2012-04-03T10:28:15.000+0000</p> 
        <div class="body">
            <p>same thing in RuntimeDefinition :</p>

<p>public function getClassSupertypes($class)
    {
        if (!array_key_exists($class, $this-&gt;classes[$class])) {
            $this-&gt;processClass($class);
        }
        return $this-&gt;classes[$class]['supertypes'];
    }</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by BLANCHON Vincent (blanchon_vincent) on 2012-04-03T18:26:24.000+0000</p> 
        <div class="body">
            <p>Ok, pull request #1004 to fix</p>

        </div>
    </div>
    </div>

