<h2>ZF2-564: NoRecordExists and RecordExists 'exclude' field string</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-09-16T16:05:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:12:25.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Egidio Caprino (aegidius)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Validator</li>
            <li>validator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello.</p>

<p>If you provide a string SQL query to a NoRecordExists or to a RecordExists validator, this will ignore the given value.</p>

<p>For example this validator just execute the query with "isConfirmed = 1 OR registrationDate &gt;= '$expirationDate'" WHERE clausole and return true if the result give 1 or more rows.</p>

<p>$validator = new NoRecordExists(array(
    'adapter' =&gt; $this-&gt;getAdapter(),
    'table'   =&gt; 'users',
    'field'   =&gt; 'username',
    'exclude' =&gt; "isConfirmed = 1 OR registrationDate &gt;= '$expirationDate'"
));</p>

<p>The aspected action is that validator execute the query with that string WHERE clausole and then search in the result to check if there are some record that match against the given value for the username field.</p>

<p>Egidio</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Andrej Baranov (andrejandb) on 2012-09-17T21:45:02.000+0000</p> 
        <div class="body">
            <p>because 'exclude' - is expression, and need write like:
'exclude' =&gt; "(isConfirmed = 1 OR registrationDate &gt;= '$expirationDate')"</p>

<p>because without '()' result SQL: 
WHERE username = :value AND isConfirmed = 1 OR registrationDate &gt;= '$expirationDate'</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Egidio Caprino (aegidius) on 2012-09-18T06:13:12.000+0000</p> 
        <div class="body">
            <p>Thank you very much.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:12:25.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2590">https://github.com/zendframework/zf2/issues/2590</a></p>

        </div>
    </div>
    </div>

