<h2>ZF2-370: sqlsrv_connect is not called when doing a connection to a Microsoft Sql Server</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-21T08:17:19.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-27T20:12:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
            <li>Zend_Db</li>
            <li>zf2</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hello,</p>

<p>I followed the tutorial of Rob Allen with ZF2 beta 4
when i'm doing</p>

<p>$this-&gt;getDatasTable()-&gt;fetchAll()</p>

<p>I'm getting the folloing error:</p>

<pre class="highlight"><code>
PHP Warning:  sqlsrv_prepare() expects parameter 1 to be resource, null given in C:\inetpub\wwwroot\LinuxWebApp\source\vendor\zendframework\zendframework\library\Zend\Db\Adapter\Driver\Sqlsrv\Statement.php on line 153
</code></pre>

<p>In config/autoload/global.php I have:</p>

<pre class="highlight"><code>
return array(
'db' =&gt; array(
    'driver' =&gt; 'Sqlsrv',
    'dsn'            =&gt; 'sqlsrv:dbname=xxx;hostname=xxx',
    'username'       =&gt; 'xxx',
    'password'       =&gt; 'xxx',
    'driver_options' =&gt; array(
        PDO::MYSQL_ATTR_INIT_COMMAND =&gt; 'SET NAMES \'UTF8\''
    ),
),
);
</code></pre>

<p>And it seem that sqlsrv_connect (Zend/Db/Adapter/Driver/Sqlsrv/Connection.php) is not called.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-07-11T19:05:35.000+0000</p> 
        <div class="body">
            <p>Are you trying to use the PDO-Sqlsrv extension? or the ext/sqlsrv extension?  I can't seem to tell from your code samples.</p>

<p>-ralph</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-08-14T15:49:18.000+0000</p> 
        <div class="body">
            <p>No feedback.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jean Rumeau (rumeau) on 2012-08-18T05:23:30.000+0000</p> 
        <div class="body">
            <p>Im having this issue too.</p>

<p>I remove the driver options and im using the <em>ext/sqlsrv</em> extension.</p>

<p>Im using:</p>

<pre class="highlight"><code>'db' =&gt; array(
        'driver'        =&gt; 'Sqlsrv',
        'database'      =&gt; 'xxxxx',
    'hostname'      =&gt; 'xxxxxxxxx'
    ),
</code></pre>

<p>and the credentials are in a local.php file</p>

<p>I run a debug and it looks like the connect method is never being called, also the <em>$this-&gt;sqlsrv</em> property is always null.</p>

<p>Also im using the 2.0.0rc4 version.</p>

<p>Please ask if you need further information.</p>

<p>Thanks</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-08-21T17:47:31.000+0000</p> 
        <div class="body">
            <p>I've got a pull request into master that perhaps might fix your issue (<a href="https://github.com/zendframework/zf2/pull/2213">https://github.com/zendframework/zf2/pull/2213</a>).</p>

<p>First, the PDO version of Sqlsrv is currently not officially supported, that is slated for 2.1</p>

<p>The ext/sqlsrv driver is supported.  In the mean time, can you paste the actual code that is failing into this issue?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Jean Rumeau (rumeau) on 2012-08-21T19:20:48.000+0000</p> 
        <div class="body">
            <p>I've just formatted my PC and installed Zend Server CE again, with the sqlsrv extension included and the problem is gone.</p>

<p>I think the problem was the sqlsrv extension i was using, as i installed it manually before.</p>

<p>The strange thing is that the same extension was working well with ZF 1.11.X, the fact is that a clean install of Zend Server CE with sqlsrv native client, provided a working sqlsrv extension.</p>

<p>The code i was using was the code provided in the sample <a href="http://packages.zendframework.com/docs/latest/manual/en/user-guide/overview.html">Getting Started with Zend Framework 2</a> available in the docs, updated to work with the RC4.</p>

<p>I can't provide more feedback because im not sure of the difference between the bundled ext/sqlsrv extension against the SQLSRV extensions provided by Microsoft.</p>

        </div>
    </div>
    </div>

