<h2>ZF2-267: PHP 5.4 + Zend GDATA + YouTube + OAuth Consumer =&gt; No Request Token</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-04-15T21:12:58.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-15T21:41:57.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christoph Brosdau (boredom1)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Christoph Brosdau (boredom1)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Gdata</li>
            <li>Zend\Oauth</li>
            <li>GData</li>
            <li>OAuth</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <ul><li>we want to create a youtube connection via OAuth (as on PHP 5.2 and ZF 1.11):</li>
</ul><p>...</p>

<p>$this-&gt;oauthoptions = array(
            'requestScheme' =&gt; \Zend\OAuth\OAuth::REQUEST_SCHEME_HEADER,
            'version' =&gt; '1.0',
            'consumerKey' =&gt; self::GOOGLEAPI_KEY,
            'consumerSecret' =&gt; self::GOOGLEAPI_SECRET,
            'signatureMethod' =&gt; 'HMAC-SHA1',
            'callbackUrl' =&gt; self::CALLBACK_URL,
            'requestTokenUrl' =&gt; '<a href="https://www.google.com/accounts/OAuthGetRequestToken">https://google.com/accounts/OAuthGetRequestToken/</a>',
            'userAuthorizationUrl' =&gt; '<a href="https://www.google.com/accounts/OAuthAuthorizeToken">https://google.com/accounts/OAuthAuthorizeToken/</a>',
            'accessTokenUrl' =&gt; '<a href="https://www.google.com/accounts/OAuthGetAccessToken">https://google.com/accounts/OAuthGetAccessToken/</a>'
        );
        $this-&gt;consumer=new \Zend\OAuth\Consumer($this-&gt;oauthoptions);</p>

<ul><li>this should then lead to RequestTokens:
$this-&gt;consumer-&gt;getRequestToken(array('scope' =&gt; '<a href="http://gdata.youtube.com">http://gdata.youtube.com</a>'));</li>
</ul><p>BUT the following is the result:</p>

<p>ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/OAuth.php -&gt; Zend\OAuth\OAuth
ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/Consumer.php -&gt; Zend\OAuth\Consumer
ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/Config/StandardConfig.php -&gt; Zend\OAuth\Config\StandardConfig
ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/Config.php -&gt; Zend\OAuth\Config
ZEND AUTOLOAD: .../libraries/gdata/Zend/Uri/UriFactory.php -&gt; Zend\Uri\UriFactory
ZEND AUTOLOAD: .../libraries/gdata/Zend/Uri/Uri.php -&gt; Zend\Uri\Uri
ZEND AUTOLOAD: .../libraries/gdata/Zend/Uri/Http.php -&gt; Zend\Uri\Http
ZEND AUTOLOAD: .../libraries/gdata/Zend/Validator/Hostname.php -&gt; Zend\Validator\Hostname
ZEND AUTOLOAD: .../libraries/gdata/Zend/Validator/AbstractValidator.php -&gt; Zend\Validator\AbstractValidator
ZEND AUTOLOAD: .../libraries/gdata/Zend/Validator/Validator.php -&gt; Zend\Validator\Validator
ZEND AUTOLOAD: .../libraries/gdata/Zend/Validator/Ip.php -&gt; Zend\Validator\Ip
ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/Http/UserAuthorization.php -&gt; Zend\OAuth\Http\UserAuthorization
ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/Http.php -&gt; Zend\OAuth\Http
ZEND AUTOLOAD: .../libraries/gdata/Zend/OAuth/Http/Utility.php -&gt; Zend\OAuth\Http\Utility
Fatal error: Call to a member function getToken() on a non-object in ....libraries/gdata/Zend/OAuth/Http/UserAuthorization.php on line 60</p>

<p>and actually, the reason is /Zend/OAuth/Http/UserAuthorization:
 -&gt; _consumer-&gt;getLastRequestToken() returns NULL, so everything else failed.</p>

<p>public function assembleParams()
    {
        $params = array(
        'oauth_token' =&gt; $this-&gt;_consumer-&gt;getLastRequestToken()-&gt;getToken(),
        );
...
        return $params;
    }</p>

<p>Thanks for your Efforts!
Christoph, Germany</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoph Brosdau (boredom1) on 2012-04-15T21:41:57.000+0000</p> 
        <div class="body">
            <p>problem found. double call of getRequestTokens.</p>

        </div>
    </div>
    </div>

