<h2>ZF2-89: Either include Zend\Tool and Zend\Console in the Standard Distribution or exclude zf.php from it</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2011-10-27T13:08:34.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-31T15:52:07.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Constantin Ehrenstein (skiller)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li></li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-90">ZF2-90</a></li>
            <li><a href="/issues/browse/ZF2-82">ZF2-82</a></li>
            <li><a href="/issues/browse/ZF2-103">ZF2-103</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Similar to well-established workflows in ZF1, I tried to create a ZF2 project via the CLI after downloading the standard distribution.</p>

<p>After figuring out what to tweak to get rid of the ZF ERROR messages, I tried</p>

<pre class="highlight"><code>
$&gt; zf create project

and got


Fatal error: Class 'Zend\Tool\Framework\Client\Console\Console' not found in /Applications/ZendFramework2beta/bin/zf.php on line 611

Call Stack:
    0.0025     801144   1. {main}() /Applications/ZendFramework2beta/bin/zf.php:0
    0.0224     801144   2. ZF::main() /Applications/ZendFramework2beta/bin/zf.php:636
    0.0589     922024   3. ZF-&gt;run() /Applications/ZendFramework2beta/bin/zf.php:74
    0.0590     922024   4. ZF-&gt;_runTool() /Applications/ZendFramework2beta/bin/zf.php:117
</code></pre>

<p>and after pulling Zend\Tool I got</p>

<pre class="highlight"><code>
Fatal error: Class 'Zend\Console\Getopt' not found in /Applications/ZendFramework2beta/library/Zend/Tool/Framework/Client/Console/ArgumentParser.php on line 250

Call Stack:
    0.0017     801144   1. {main}() /Applications/ZendFramework2beta/bin/zf.php:0
    0.0019     801144   2. ZF::main() /Applications/ZendFramework2beta/bin/zf.php:636
    0.0151     922024   3. ZF-&gt;run() /Applications/ZendFramework2beta/bin/zf.php:74
    0.0151     922024   4. ZF-&gt;_runTool() /Applications/ZendFramework2beta/bin/zf.php:117
    0.0369    1247128   5. Zend\Tool\Framework\Client\AbstractClient-&gt;dispatch() /Applications/ZendFramework2beta/bin/zf.php:612
    0.3756    6003432   6. Zend\Tool\Framework\Client\Console\Console-&gt;_preDispatch() /Applications/ZendFramework2beta/library/Zend/Tool/Framework/Client/AbstractClient.php:218
    0.3871    6321704   7. Zend\Tool\Framework\Client\Console\ArgumentParser-&gt;parse() /Applications/ZendFramework2beta/library/Zend/Tool/Framework/Client/Console/Console.php:201
    0.3871    6322312   8. Zend\Tool\Framework\Client\Console\ArgumentParser-&gt;_parseGlobalPart() /Applications/ZendFramework2beta/library/Zend/Tool/Framework/Client/Console/ArgumentParser.php:136
</code></pre>

<p>After pulling Zend\Console there was an issue with Zend\Code\Generator\FileGeneratorRegistry::registerFileCodeGenerator() not defined, but that's a different story.</p>

<p>So my suggestion is to either include those packages in the Standard Distribution or leave out the zf command line tool altogether.</p>

<p>If zf.php should be there in order to handle ZF configuration, I recommend rewriting it so it fails gracefully when a user tries to create zf components with it from the Standard Distribution.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Christoffer Holmstedt (christoffer) on 2011-11-05T10:09:16.000+0000</p> 
        <div class="body">
            <p>I can confirm this. Running "zf show version" yields</p>

<p>[05-Nov-2011 11:05:26] PHP Fatal error:  Class 'Zend\Tool\Framework\Client\Console\Console' not found in /var/applications/ZendFramework-2.0.0beta1/bin/zf.php on line 611</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Benoît Durand (intiilapa) on 2011-11-06T13:15:35.000+0000</p> 
        <div class="body">
            <p>Matthew can you fix this in beta1?</p>

<p>Standard distribution is already decided in <a href="http://framework.zend.com/wiki/pages/viewpage.action?pageId=43745438">RFC</a>.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-23T15:48:40.000+0000</p> 
        <div class="body">
            <p>Zend\Tool does not work with ZF2.  You can clone the <a href="https://github.com/zendframework/ZendSkeletonApplication">ZendSkeletonApplication</a> to get a base working ZF2 project.</p>

<p>Closing as "Wont' Fix" (See <a href="http://framework.zend.com/issues/browse/ZF2-103?focusedCommentId=49688&amp;page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-49688">Matthew's comment on ZF2-103 here</a>)</p>

        </div>
    </div>
    </div>

