<h2>ZF2-256: Automatic rendering view of current module</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-04-05T19:17:13.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-23T13:20:02.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In my app, i have two modules :</p>

<p>ModOne and ModTwo. Each modules have directory 'view' in module directory with scripts.
In each module, i have one controller IndexController with an action index.</p>

<p>In Mod1 config :</p>

<pre class="highlight"><code>
'Zend\View\Resolver\TemplatePathStack' =&gt; array(
                'parameters' =&gt; array(
                    'paths'  =&gt; array(
                        'mod1' =&gt; __DIR__ . '/../view',
                    ),
                ),
            ),
</code></pre>

<p>In Mod2 config :</p>

<pre class="highlight"><code>
'Zend\View\Resolver\TemplatePathStack' =&gt; array(
                'parameters' =&gt; array(
                    'paths'  =&gt; array(
                        'mod2' =&gt; __DIR__ . '/../view',
                    ),
                ),
            ),
</code></pre>

<p>First literal route "/mod1" route to Mod1 index/index.
Second literal route "/mod2" route to Mod2 index/index.</p>

<p>But, with the zf2, the Zend\View\Resolver\TemplatePathStack, the resolve method get the first which matched. But, two paths are good : Mod1/view and Mod2/view.</p>

<p>So route "www.exemple.com/mod1" route to Mod1 controller and display Mod1/index/index.
So route "www.exemple.com/mod1" route to Mod1 controller BUT display Mod1/index/index, not Mod2/index/index.</p>

<p>I know why, because Zend\View\Resolver\TemplatePathStack :</p>

<pre class="highlight"><code>
public function resolve($name, Renderer $renderer = null)
{
        [...]

        foreach ($this-&gt;paths as $path) {
            $file = new SplFileInfo($path . $name);
</code></pre>

<p>The two paths are valid, because there is "index" directory in each modules, and an "index" script in each modules.</p>

<p>Alias, namespaced controlle name or setPaths() of Zend\View\Resolver\TemplatePathStack can resolve problem, but why can we add this native comportement ? ZF1 to ZF2 migration can be hard because developer use lot of IndexController name ?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by BLANCHON Vincent (blanchon_vincent) on 2012-04-16T09:15:39.000+0000</p> 
        <div class="body">
            <p>I think the task of Evan Coury "Create "default" module route"in the board should be fix that</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by BLANCHON Vincent (blanchon_vincent) on 2012-05-23T13:20:02.000+0000</p> 
        <div class="body">
            <p>Evan resolve that with beta4 :)</p>

        </div>
    </div>
    </div>

