<h2>ZF2-345: After using Forward plugin render fails on Resolver error</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-07T06:24:18.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:15:13.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Yonni Mendes (yonman)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Mvc</li>
            <li>Mvc</li>
            <li>Plugin</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using beta4.
After using the forward plugin in a controller action and then returning a <em>different</em> view model causes a resolver error:</p>

<pre class="highlight"><code>

class IndexController extends ActionController
{
 public function indexAction() {
  $viewModel = $this-&gt;forward()-&gt;dispatch('SomeOtherController', array(...));
  .
  .
  .
  return new ViewModel(array(...));
 }
}
</code></pre>

<p>The above snippet causes the InjectViewModel::injectViewModel triggered by the 'render' event to introduce a 2nd view model under the layout, which calls to a mangled view script made of the original action's name and the forwarded view script's directory name... which doesn't exist and so fails.</p>

<pre class="literal">
PHP Fatal error:  Uncaught exception 'Zend\View\Exception\RuntimeException' with message 'Zend\View\Renderer\PhpRenderer::render: Unable to render template "servers/web-api/index"; resolver could not resolve to a file
</pre>

<p>Note the path above - servers is the namespace, web-api is the name of the "other controller" and index is the action for the "current controller".</p>

<p>Work around -
Return the forward's output view model. This seems to avoid the issue some-why.</p>

<pre class="highlight"><code>

class IndexController extends ActionController
{
 public function indexAction() {
  $viewModel = $this-&gt;forward()-&gt;dispatch('SomeOtherController', array(...));
  .
  .
  .
  return $viewModel;
 }
}
</code></pre>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:15:13.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2490">https://github.com/zendframework/zf2/issues/2490</a></p>

        </div>
    </div>
    </div>

