<h2>ZF2-221: Joins in Zend\Db\Sql\Select should allow providing aliased field names</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-03-13T19:11:17.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-11T21:06:32.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Guillaume Métayer (willy0275)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The join() method in Zend\Db\Sql\Select.php doesn't allow passing an aliased field name in the $columns parameter. The array should allow passing the fields as an associative array, for example array('aliasedName' =&gt; 'fieldName') ... It's very important in complex joins where some field names are identical and clashing.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Martin Hujer (mhujer) on 2012-04-02T20:32:11.000+0000</p> 
        <div class="body">
            <p>Testcase</p>

<pre class="highlight"><code>
--- a/tests/Zend/Db/Sql/SelectTest.php
+++ b/tests/Zend/Db/Sql/SelectTest.php
@@ -305,6 +305,11 @@ class SelectTest extends \PHPUnit_Framework_TestCase
         $select9 = new Select;
         $select9-&gt;from('foo')-&gt;join('zac', 'm = n', array('bar', 'baz'));
         $sql9 = 'SELECT "foo".*, "zac"."bar", "zac"."baz" FROM "foo" INNER JOIN "zac" ON "m" = "n"';
+        
+        // join with column aliases
+        $select9a = new Select;
+        $select9a-&gt;from('foo')-&gt;join('zac', 'm = n', array('bar', 'bat' =&gt; 'baz'));
+        $sql9a = 'SELECT "foo".*, "zac"."bar", "zac"."baz" AS "bat" FROM "foo" INNER JOIN "zac" ON "m" = "n"';
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-05-11T19:59:53.000+0000</p> 
        <div class="body">
            <p>This is fixed in latest master, please try it.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Martin Hujer (mhujer) on 2012-05-11T21:06:32.000+0000</p> 
        <div class="body">
            <p>Works fine. Thanks.</p>

        </div>
    </div>
    </div>

