<h2>ZF2-459: Wrong phpdoc comments and non-existing classes used</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-08-10T00:11:15.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:16:34.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Michael Kliewe (mkliewe)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
            <li>Zend\Paginator</li>
            <li>Zend\View</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-467">ZF2-467</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm using RC3.</p>

<p>There are a lot classes used that do not exist. If you search for the following strings you will find them. I don't know how to fix them, because I don't know what the correct replacement/new class is in zf2.</p>

<p>\Zend\Db\Table
\Zend\Db\Metadata\Table
\Zend\Db\Metadata\ColumnCollection
\Zend\Db\Metadata\ConstraintCollection</p>

<p>"ConstraintKeyObject" is wrong, and I cannot find a method "getColumnName()" anywhere
/** @var $key \Zend\Db\Metadata\Object\ConstraintKeyObject */
$primaryKey[] = $key-&gt;getColumnName();</p>

<p>Should that be \PDO::FETCH_ASSOC?
Db\Db::FETCH_ASSOC</p>

<p>Search for "\Zend\Loader\PluginLoader\Exception"</p>

<p>Search in whole project for "Object\ConstraintKeyObject"</p>

<p>PHPStorm tells me this is wrong (or bad code)? But maybe this is a false positive of PHPStorm.
$this-&gt;handles[$index] = &amp; $handles;</p>

<p>It would be cool if someone could have a look at all those classes and repair it.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-15T06:33:20.000+0000</p> 
        <div class="body">
            <p>[~mkliewe] Thank you for the report. Please the next time add the class which you found the issue.</p>

<p>The first block is a obsolete class will be removed by this PR <a href="https://github.com/zendframework/zf2/pull/2169">https://github.com/zendframework/zf2/pull/2169</a></p>

<p>The second and fifth part will be fixed by [~ralph]</p>

<p>About the third part probably should be PDO, however Paginator still having old code not related with the new Zend\Db 2.0 API</p>

<p>About the fourth is obviously that the function only will throw a RuntimeException and neither Zend\Loader... or InvalidArgumentException so you can replace the @throws safely with RuntimeException and send us a PR with the patch</p>

<p>finally about the sixth I don't know.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-20T20:30:15.000+0000</p> 
        <div class="body">
            <p>Left fix some occurrences of ConstraintKeyObject</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-08-21T17:51:52.000+0000</p> 
        <div class="body">
            <pre class="highlight"><code>
$this-&gt;handles[$index] = &amp; $handles;
</code></pre>

<p>Is valid, and I've seen that issue in PHPStorm. Where is that line exactly?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Michael Kliewe (mkliewe) on 2012-08-21T18:16:01.000+0000</p> 
        <div class="body">
            <p>If I search for "= &amp; " in the whole project I find 26 occurrences. But only 5 of them are underlined in red (in PHPStorm). The files are:
Zend/Cache/Storage/Plugin/ClearExpiredByFactor.php
Zend/Cache/Storage/Plugin/ExceptionHandler.php
Zend/Cache/Storage/Plugin/IgnoreUserAbort.php
Zend/Cache/Storage/Plugin/OptimizeByFactor.php
Zend/Cache/Storage/Plugin/Serializer.php</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:16:34.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2522">https://github.com/zendframework/zf2/issues/2522</a></p>

        </div>
    </div>
    </div>

