<h2>ZF2-1: Zend\Db\Db on line 253 prints a string instead of throwing a proper exception</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2010-12-09T04:05:38.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2011-06-07T15:26:20.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Alexander Thomas (fanatique)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Satoru Yoshida (satoruyoshida)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>On line 253 in Zend\Db\Db the string "FAILED TO FIND $adapterName\n"; is printed.</p>

<p>Afterwards the execution is stopped although it should throw a Zend\Db\Adapter\Exception to enable handling this error properly.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-04-28T16:11:11.000+0000</p> 
        <div class="body">
            <p>I can not find the string commented in trunk.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Alexander Thomas (fanatique) on 2011-04-28T17:27:30.000+0000</p> 
        <div class="body">
            <p>I just double checked that the problem still exists in the repository.</p>

<p>Maybe I should point out that this ticket refers to <em>ZF2</em> (therefore it is set to "affects next major release")?</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Satoru Yoshida (satoruyoshida) on 2011-04-29T03:56:25.000+0000</p> 
        <div class="body">
            <p>Hi, Alexsander. Do you mean the string "FAILED TO FIND" exists in <a href="http://framework.zend.com/svn/framework/standard/trunk/library/Zend/Db">http://framework.zend.com/svn/framework/…</a> ?</p>

<p>I will be happy if You would tell me using version and exactly file name in your environment.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Kazusuke Sasezaki (sasezaki) on 2011-06-07T15:26:20.000+0000</p> 
        <div class="body">
            <p>(FYI)  Ralph changed this issue 05/May/11.(please see this issue's History page). and, he is working for refactoring  Zend\Db.
exactly, This issue will be closed when refactored Zend\Db is merged.</p>

        </div>
    </div>
    </div>

