<h2>ZF2-512: InputFilter cannot be serialized</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-08-31T07:02:54.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:14:45.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Filter</li>
            <li>Zend\InputFilter</li>
            <li>Zend\Validator</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Both ValidatorChain and InputFilterChain have references to ServiceManager, which in turn registers Traits. For this reason chains cannot be serialized, and as a result InputFilter cannot be serialized.</p>

<p>According to my tests, cached (and serialized) InputFilter adds 10X performance improvement compared to InputFilter that is initialized from the scratch.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Juha Suni (zuhac) on 2012-08-31T07:03:10.000+0000</p> 
        <div class="body">
            <p>Pull request coming soon, the fix is dead simple.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:14:45.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2548">https://github.com/zendframework/zf2/issues/2548</a></p>

        </div>
    </div>
    </div>

