<h2>ZF2-257: Update all docblocks to use consistent copyright/license header. Version: 2012</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Docs:  Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-04-06T07:38:01.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-11T06:33:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>    </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>There are 126 occurrences to the period * @copyright  Copyright (c) 2005-2010 Zend Technologies USA Inc. (<a href="http://www.zend.com">http://www.zend.com</a>)</p>

<p>There are 152 occurrences to the period * @copyright  Copyright (c) 2005-2011 Zend Technologies USA Inc. (<a href="http://www.zend.com">http://www.zend.com</a>)</p>

<p>Command used grep "201[0-1] Zend T" zf2/* -R</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Dave Stephenson (dbstephenson) on 2012-04-09T15:19:24.000+0000</p> 
        <div class="body">
            <p>Pull Request sent for branch that addresses the above.</p>

<p><a href="https://github.com/dbstephenson/zf2/tree/ZF2-257">https://github.com/dbstephenson/zf2/tree/ZF2-257</a></p>

        </div>
    </div>
    </div>

