<h2>ZF2-323: PluginBroker and load with alias</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-05-26T16:24:29.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-11T10:13:31.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Loader</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>If the first load method in PluginBroker :</p>

<pre class="highlight"><code>
$locator  = $this-&gt;getServiceLocator();
        // Pulling by alias
        if ($locator) {
            try {
                $instance = $locator-&gt;get($plugin);
            } catch (ServiceManagerException $e) {
                // not returning an instance is okay; there are other ways to 
                // retrieve the plugin later
                $instance = false;
            }

            if ($instance) {
                if ($this-&gt;getRegisterPluginsOnLoad()) {
                    $this-&gt;register($pluginName, $instance);
                }
                return $instance;
            }
        }
</code></pre>

<p>With these lines i can write in my controller :</p>

<pre class="highlight"><code>
public function indexAction()
    {
        $manager = $this-&gt;plugin('ViewManager'));
    }
</code></pre>

<p>I think is not the PluginBroker job, so to fix that i propose to verify alias configuration with :</p>

<pre class="highlight"><code>
$class = $this-&gt;getClassLoader()-&gt;load($plugin);
if (empty($class) &amp;&amp; !class_exists($plugin)) {
            throw new Exception\RuntimeException('Unable to locate class associated with "' . $pluginName . '"');
        }
</code></pre>

<p>just before the loading by alias and keep the use of servicemanager to load alias and complete class name.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-26T12:39:22.000+0000</p> 
        <div class="body">
            <p>You can try to use ServiceManager instead of ServiceManager like this PR <a href="https://github.com/zendframework/zf2/pull/1550">https://github.com/zendframework/zf2/pull/1550</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-11T10:13:31.000+0000</p> 
        <div class="body">
            <p>Closed because Zend\Loader\PluginBroker has been removed in favor of Zend\ServiceManager</p>

        </div>
    </div>
    </div>

