<h2>ZF2-386: Improper escaping in Db\Sql\Select join conditions</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-07-06T05:56:42.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-11T19:09:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Using parentheses in join conditions causes incorrect quoting. For example:</p>

<p>{{$select = new Zend\Db\Sql\Select;}}
{{$select-&gt;from('foo')-&gt;join('bar', '(foo.foo_id = bar.bar_id OR foo.bar_id = bar.bar_id) AND (foo.a = bar.a)');}}</p>

<p>results in the join condition being:</p>

<p>{{SELECT "foo".*, "bar".* FROM "foo" INNER JOIN "bar" ON "(foo"."foo_id" = "bar"."bar_id" OR "foo"."bar_id" = "bar"."bar_id)" AND "(foo"."a" = "bar"."a)"}}</p>

<p>This can be remedied by placing spaces between parentheses and identifiers. However, this is solution is neither ideal nor immediately obvious.</p>

<p>Additionally, it is currently not possible (as far as I am aware) to use expressions like CONCAT in join conditions, again due to improper escaping. An acceptable alternative might be to accept a Db\Sql\Expression as a join condition and leave escaping up to the user in that case.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-07-11T19:09:56.000+0000</p> 
        <div class="body">
            <p>Fixed in pull request #1849</p>

        </div>
    </div>
    </div>

