<h2>ZF2-99: Zend\Http\Client\Adapter\Socket throws TimeoutException when the response status is 302 and keepalived enabled</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2011-11-11T12:56:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-06T16:27:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Shuhei Tanuma (chboie)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Http</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        
<h1>302 Moved</h1>
The document has moved
<a href="">www.google.co.jp/</a>"&gt;here.

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Kazusuke Sasezaki (sasezaki) on 2011-11-11T16:28:15.000+0000</p> 
        <div class="body">
            <p>This bug is caused by "headers key(ZF1 strtolower --&gt; ZF2 ucrfirst-uchrfirst)"
quick patch is here.
<a href="https://gist.github.com/1358388">https://gist.github.com/1358388</a></p>

<p>after ZF2-100 pull-request is merged or not, I will patch Socket Adapter &amp; Proxy Adapter.
<a href="https://github.com/zendframework/zf2/pull/588">https://github.com/zendframework/zf2/pull/588</a></p>

<p>Thanks for your report.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-06T16:27:17.000+0000</p> 
        <div class="body">
            <p>I tried to code and for me works well.</p>

        </div>
    </div>
    </div>

