<h2>ZF2-306: View Helper FormElements renders reversed options ($val=&gt;$key)</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-05-17T20:46:52.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-29T20:29:17.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi there,
All View Helpers with option attribute renders reversed options ($val=&gt;$key):
FormMultiCheckbox , FormSelect, FormRadio</p>

<p>ex:</p>

<pre class="highlight"><code>
$id_sexe = new Element('id_sexe');
$id_sexe-&gt;setAttributes(array(
'type' =&gt; 'radio'
'label' =&gt; 'gender',
'options' =&gt; array(1=&gt;'man',2=&gt;'woman') 
));
</code></pre>

<p>generates options like this: 12</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by David Quintard (booradley) on 2012-05-23T14:38:30.000+0000</p> 
        <div class="body">
            <p><a href="https://github.com/zendframework/zf2/blob/master/library/Zend/Form/View/Helper/FormMultiCheckbox.php#L149">https://github.com/zendframework/zf2/…</a></p>

<p>According to me,</p>

<pre class="highlight"><code>
foreach ($options as $label =&gt; $value) {
</code></pre>

<p>shoud be:</p>

<pre class="highlight"><code>
foreach ($options as $value =&gt; $label) {
</code></pre>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Matthew Weier O'Phinney (matthew) on 2012-05-29T19:28:41.000+0000</p> 
        <div class="body">
            <p>The design is label/value pairs (where the key is the label, and the value, well, the value). The options should read "man" =&gt; 1, "woman" =&gt; 2 to display in the way you desire.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by David Quintard (booradley) on 2012-05-29T20:29:17.000+0000</p> 
        <div class="body">
            <p>Ok, i understand, thank you Matthew</p>

        </div>
    </div>
    </div>

