<h2>ZF2-475: Add support of multi-insertion in 1 query</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>New Feature</dd>

    <dt>Created:</dt>
    <dd>2012-08-18T13:37:21.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-21T18:05:51.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
            <li>Insert</li>
            <li>Sql</li>
            <li>Zend_Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>sorry for my ESL</p>

<p>I sometimes have to insert multiple rows (like import batch).
Insert one by one may be very slow when I have 10000+ rows to insert.</p>

<p>I don't know about others dbms, but MySQL support multi-insertions, and it's way faster to insert 100 values in one query.</p>

<p>{quote}
INSERT INTO tbl_name (a,b,c) VALUES
(1,2,3),
(4,5,6),
(7,8,9);
{quote}</p>

<p>It's should be nice to enhance Zend\Db\Sql\Insert, or create a new class to handle multi-insertion.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-08-21T18:05:51.000+0000</p> 
        <div class="body">
            <p>I don't think this will be supported directly inside Zend\Db as multi-inserts are mostly (AFAIK) a MySQLism.  I think it makes a ton of sense to have a Module or library separate from ZF that has additional enhancements specificially for Mysql (or whatever database) though, I'd like to see that live in ZFCommons.</p>

<p>So, for now, closing as won't fix.</p>

        </div>
    </div>
    </div>

