<h2>ZF2-274: HTML5 forms in Zend Framework</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-04-22T07:30:26.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-04-22T13:17:59.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Frank Brückner (frosch)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Form</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Hi there,
With html5 we need now to generate input forms with new types: (email,url,number,range
Date pickers (date, month, week, time, datetime, datetime-local).
For example jquery tools (and most of new javascript validator plugins) uses validators based upon these types: 
<a href="http://jquerytools.org/documentation/validator/index.html">http://jquerytools.org/documentation/validator/…</a></p>

<p>Will zf2 implement these types ?</p>

<p>See <a href="http://www.enrise.com/2010/12/html5-zend-framework-form-elements/">http://enrise.com/2010/12/…</a></p>

<p>Best regards</p>

<p>David</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Frank Brückner (frosch) on 2012-04-22T09:55:47.000+0000</p> 
        <div class="body">
            <p>Yes! Look here:
* <a href="http://zend-framework-community.634137.n4.nabble.com/Forms-status-td4575373.html">Mailing list</a>
* <a href="http://framework.zend.com/wiki/display/ZFDEV2/RFC+-+Forms">RFC - Forms</a>
* <a href="https://github.com/weierophinney/zf2/blob/feature/forms/library/Zend/Form/TODO.md"></a><a href="https://github.com/weierophinney/zf2">https://github.com/weierophinney/zf2</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by David Quintard (booradley) on 2012-04-22T13:17:59.000+0000</p> 
        <div class="body">
            <p>Thank you very much Franck.</p>

<p>"If there's time, and no later than beta5, I
   plan to support HTML5 specialized input types as well. " (Matthiew)</p>

        </div>
    </div>
    </div>

