<h2>ZF2-363: Zend\Mail\Header\MimeVersion should use &quot;MIME-Type&quot; instead of &quot;Mime-Type&quot;</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-06-17T10:44:14.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-06-27T07:04:56.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Steffen Weber (steffen)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Mail</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>In ZF1 this header was named "MIME-Version". In ZF2 this has been changed to "Mime-Version". Mail headers are case-insensitive, but who knows how many buggy clients are out there and the RFC uses "MIME-Version", too: <a href="http://tools.ietf.org/html/rfc2045">http://tools.ietf.org/html/rfc2045</a></p>

<p>The affected methods are "getFieldName" and "toString".</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-21T21:56:01.000+0000</p> 
        <div class="body">
            <p>Hi Steffen if you want you can send the fix directly to GitHub</p>

<p><a href="https://github.com/zendframework/zf2/edit/master/library/Zend/Mail/Header/MimeVersion.php">https://github.com/zendframework/zf2/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Steffen Weber (steffen) on 2012-06-22T11:21:09.000+0000</p> 
        <div class="body">
            <p>Cool, I did not know about the online editor at GitHub! :)</p>

<p>Pull request: <a href="https://github.com/zendframework/zf2/pull/1551">https://github.com/zendframework/zf2/pull/1551</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-06-27T07:04:56.000+0000</p> 
        <div class="body">
            <p>Patch merged</p>

        </div>
    </div>
    </div>

