<h2>ZF2-166: Redundant argument passed in ZendSkeleton</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-02-16T19:19:48.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-16T19:33:16.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Roberto Wesley Overdijk (rwoverdijk)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Roberto Wesley Overdijk (rwoverdijk)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Loader</li>
            <li>ZendSkeleton</li>
            <li>index.php</li>
            <li>redundant,</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>The index.php of the ZendSkeleton application sets an argument, which is the exact same (default) value for the factory when passed null.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Roberto Wesley Overdijk (rwoverdijk) on 2012-02-16T19:32:39.000+0000</p> 
        <div class="body">
            <p>The argument has been removed</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roberto Wesley Overdijk (rwoverdijk) on 2012-02-16T19:33:15.000+0000</p> 
        <div class="body">
            <p>Method removed, pull request sent.</p>

        </div>
    </div>
    </div>

