<h2>ZF2-157: pdo adapter mysql is not in the pdo Namespace</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-02-09T22:06:27.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-02-24T20:21:30.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
        None
                    </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>is there a reason to hold the class "PdoMysql" in the Namespace "\Zend\Db\Adapter"</p>

<p>i think a better place is "\Zend\Db\Adapter\Pdo" like the old class Zend_Db_Adapter_Pdo_Mysql</p>

<p>thx for you time ;)</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Adam Lundrigan (adamlundrigan) on 2012-02-23T18:49:36.000+0000</p> 
        <div class="body">
            <p>The Zend\Db component currently in ZF2 master is being rewritten (by Ralph Schindler; see branches listed under Zend\Db on <a href="http://zf2.evan.pro/">http://zf2.evan.pro/</a>), and should be included in the beta3 or beta4 release of ZF2.</p>

        </div>
    </div>
    </div>

