<h2>ZF2-572: Step Validator uses the unprecise fmod function and fails for floats that are internally represented differently</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-09-19T09:55:37.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-10-08T20:12:21.000+0000</dd>

    <dt>Status:</dt>
    <dd>Closed</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Philipp Dobrigkeit (pdobrigkeit)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Matthew Weier O'Phinney (matthew)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Validator</li>
            <li>validating</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Giving the step validator a value that cannot be correclty interpreted gives seemingly wrong results in the fmod function.</p>

<p>For example value 15.5, step 0.1 gives a fmod of 0.099999999999999 and not 0.0.</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-10-08T20:12:21.000+0000</p> 
        <div class="body">
            <p>This issue has been closed on Jira and moved to GitHub for issue tracking.  To continue following the resolution of this issues, please visit: <a href="https://github.com/zendframework/zf2/issues/2597">https://github.com/zendframework/zf2/issues/2597</a></p>

        </div>
    </div>
    </div>

