<h2>ZF2-362: Quotation in Mysql SQL adapter</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-06-15T12:13:40.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-11T19:08:36.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Sergey Romanov (serhioromano)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>When I create query with Select() and convert it into string it shows this</p>

<p>SELECT "user"."id" AS id, "user"."name" AS name FROM "user" WHERE "user"."email" = 'my@email.com';</p>

<p>I think for mysql syntax more correct way would be to use ` quote for table name and fields. And " to use for strings. Although it works this way, all syntax highlighters will highlight this as strings and this is important to make SQL visibility if you create lage project with build in SQL tracker.</p>

<p>I think the default quote for this have to be like this</p>

<p>SELECT <code>user</code>.<code>id</code> AS id, <code>user</code>.<code>name</code> AS name FROM <code>user</code> WHERE <code>user</code>.<code>email</code> = 'my@email.com';</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-07-11T19:08:36.000+0000</p> 
        <div class="body">
            <p>To create the SQL string for mysql, you would need to do the following:</p>

<pre class="highlight"><code>
use Zend\Db\Sql\Select;
use Zend\Db\Adapter\Platform\Mysql as MysqlPlatform;

$select = new Select();
// ...
$sql = $select-&gt;toSqlString(new MysqlPlatform); // you can also get that from $adapter-&gt;platform;
</code></pre>

        </div>
    </div>
    </div>

