<h2>ZF2-309: support of [] operator in nested ini config</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-05-18T20:07:04.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-25T08:09:04.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Christian R (foobarbar)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ben Scholzen (dasprid)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Config</li>
            <li>[]-operator</li>
            <li>config</li>
            <li>ini</li>
            <li>zend</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
    </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p><em>Example:</em></p>

<pre class="highlight"><code>foo.bar = foobar
foobar[] = foobarArray
foo.baz[] = foobaz1
foo.baz[] = foobaz2</code></pre>

<p><em>Expected:</em></p>

<pre class="highlight"><code>
array (
  'foo' =&gt;
  array (
    'bar' =&gt; 'foobar',
    'baz' =&gt;
    array (
      0 =&gt; 'foobaz1',
      1 =&gt; 'foobaz2',
    ),
  ),
  'foobar' =&gt;
  array (
    0 =&gt; 'foobarArray',
  )
)</code></pre>

<p><em>Actual:</em></p>

<pre class="highlight"><code>array (
  'foo' =&gt; 
  array (
    'bar' =&gt; 'foobar',
  ),
  'foobar' =&gt; 
  array (
    0 =&gt; 'foobarArray',
  ),
  'foo.baz' =&gt; 
  array (
    0 =&gt; 'foobaz1',
    1 =&gt; 'foobaz2',
  ),
)</code></pre>

<p>I just rewrote the application.config.php of an example ZF2 project into the INI equivalent (or what I thought would be). I was pretty much confused that the nested part (foo.baz) was not resolved correctly. Is that for any specific/important reason? Could we add this as an improvement?</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Robert Boloc (robertboloc) on 2012-08-24T10:04:15.000+0000</p> 
        <div class="body">
            <p>pull request: <a href="https://github.com/zendframework/zf2/pull/2233">https://github.com/zendframework/zf2/pull/2233</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-25T08:09:04.000+0000</p> 
        <div class="body">
            <p>Patch merged. Thank you for your contribution</p>

        </div>
    </div>
    </div>

