<h2>ZF2-161: InvalidArgumentException in CLDR lookup functions</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-02-12T17:35:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-07-09T15:31:11.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                fisharebest (fisharebest)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Maks 3w (maks3w)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\I18n</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-167">ZF2-167</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>Version: Github download 2012-02-11</p>

<p>Sample code:</p>

<p>echo \Zend\Locale\Locale::getTranslation('de', 'language', 'de');
echo \Zend\Locale\Data\Cldr::getContent('ar', 'defaultnumberingsystem');</p>

<p>Expected output:</p>

<p>"Deutsch"
"arab"</p>

<p>Actual output:</p>

<p>Uncaught exception 'Zend\Locale\Exception\InvalidArgumentException' with message 'Unknown detail (language) for parsing locale data.'
Uncaught exception 'Zend\Locale\Exception\InvalidArgumentException' with message 'Unknown detail (defaultnumberingsystem) for parsing locale data.'</p>

<p>These are the ZF2 equivalents of ZF1 functions, both of which produce the expected output:</p>

<p>Zend_Locale::getTranslation();
Zend_Locale_Data::getContent();</p>

<p>Possible solution:</p>

<p>The function \Zend\Locale\Data\Cldr::getContent() has a long switch statement (lines 900-1300) containing each of the possible CLDR lookups.  It does not have the cases for 'language' or 'defaultnumberingsystem'.  These could be added as follows:</p>

<p>case 'language':
    $temp = self::_getFile('main/' . $locale, '/ldml/localeDisplayNames/languages/language[@type=\'' . $value . '\']');
    break;</p>

<p>case 'defaultnumberingsystem':
    $temp = self::_getFile('main/' . $locale, '/ldml/numbers/defaultNumberingSystem');
    break;</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-05-06T18:44:51.000+0000</p> 
        <div class="body">
            <p>This break was introduced in the following commit <a href="https://github.com/zendframework/zf2/commit/046f5654a26c2f369eaf398123c4a6fa3f4943dd#library/Zend/Locale/Data/Cldr.php">https://github.com/zendframework/zf2/…</a></p>

<p>Now I'm studying the reasons behind this.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-05-08T16:08:03.000+0000</p> 
        <div class="body">
            <p>Finally this will not be fixed because there is a plan to remove this component.</p>

<p>With beta5 a new component will be released to cover this features.</p>

<p>As workaround you can use the functions provided by AbstractLocale (getDisplayLanguage, getDisplayScript, getDisplayRegion)</p>

        </div>
    </div>
    </div>

