<h2>ZF2-195: Zend\Db (beta3): unable not to quote a column value</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Bug</dd>

    <dt>Created:</dt>
    <dd>2012-03-06T18:00:16.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-05-11T16:36:00.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Fabrizio Balliano (balliano)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                Ralph Schindler (ralph)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Db</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF2-199">ZF2-199</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>I'm trying to use tablegateway to insert values in a mysql' spatial column:
<a href="http://pastebin.com/K6ECz0h4">http://pastebin.com/K6ECz0h4</a>
but there's no way not to quote the "points" column, in ZF1 we had the Zend_Expr but I can't find anything like that in ZF2.</p>

<p>Same issue applies to Zend\Db\Sql\Insert
Thank you very much!</p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by Roger Hunwicks (rhunwicks) on 2012-03-09T20:49:06.000+0000</p> 
        <div class="body">
            <p>Please can someone with the correct privileges assign this to component Zend\Db</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Roger Hunwicks (rhunwicks) on 2012-03-20T06:10:18.000+0000</p> 
        <div class="body">
            <p>This is probably fixed by <a href="https://github.com/ralphschindler/zf2/commits/feature/db-sql-expressions">https://github.com/ralphschindler/zf2/…</a> if you "use Zend\Db\Sql\Expression" and then do</p>

<pre class="highlight"><code>
"point" =&gt; new Expression("GEOMFROMTEXT('POINT({$_REQUEST["lat"]} {$_REQUEST["lng"]})')"),
</code></pre>

<p>I'm hoping those changes will be merged into the master branch for Beta4.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-05-11T14:09:20.000+0000</p> 
        <div class="body">
            <p>I'll look into this today, I think it's a good idea.</p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Ralph Schindler (ralph) on 2012-05-11T16:36:00.000+0000</p> 
        <div class="body">
            <p>Fixed in 36e30cf (pull request #1206)</p>

        </div>
    </div>
    </div>

