<h2>ZF2-293: Support multiple versions of AWS API</h2>

<dl class="metadata">
    <dt>Issue Type:</dt>
    <dd>Improvement</dd>

    <dt>Created:</dt>
    <dd>2012-05-09T12:20:00.000+0000</dd>

    <dt>Last Updated:</dt>
    <dd>2012-08-21T19:42:41.000+0000</dd>

    <dt>Status:</dt>
    <dd>Resolved</dd>

    <dt>Fix version(s):</dt>
    <dd><ul></ul></dd>

    <dt>Reporter:</dt>
    <dd>
                Adam Lundrigan (adamlundrigan)
            </dd>

    <dt>Assignee:</dt>
    <dd>
                John Kelly (postalservice14)
            </dd>

    <dt>Tags:</dt>
    <dd><ul>        <li>Zend\Service</li>
            <li>AWSEcommerceService</li>
            <li>Amazon</li>
            <li>Zend\Service\Amazon</li>
        </ul></dd>

    <dt>Related issues:</dt>
    <dd><ul>
        <li><a href="/issues/browse/ZF-5434">ZF-5434</a></li>
        </ul></dd>

    <dt>Attachments:</dt>
    <dd><ul>
    </ul></dd>
</dl>

<div class="description">
    <h3>Description</h3>

    <div class="body">
        <p>[Cloned from ZF-5434, originally posted by [~baxter]]</p>

<p>I think it would be a good idea to be able to specify the version you'd like to use. An example would be:</p>

<p>$amazon = new Zend\Service\Amazon('****','CA');
$amazon-&gt;setVersion('2008-08-19');
$results = $amazon-&gt;itemSearch(array(
'SearchIndex' =&gt; 'Jewelry',
'Keywords' =&gt; 'gold necklace',
'ResponseGroup' =&gt; 'Small,ItemAttributes,Images,SalesRank,Reviews,EditorialReview,Similarities,ListmaniaLists'
));</p>

<p>From taking a quick look through the only update I can see to the class would be the following:</p>

<p>adding the public function setVersion which would set $this-&gt;version
in _prepareOptions check to see if this-&gt;version is set and if so update the query to include the Version parameter
in _checkErrors update the namespace to '<a href="http://webservices.amazon.com/AWSECommerceService/'.$this">http://webservices.amazon.com/AWSECommerceService/…</a>-&gt;version</p>

<p>quoted from the amazon best practises:</p>

<p>"Amazon Associates Web Service makes frequent releases. Each release either adds functionality or increases the accuracy, speed, and stability of Amazon Associates Web Service. Most releases do both. Check <a href="http://aws.amazon.com/resources">http://aws.amazon.com/resources</a> frequently for documentation about the latest release.</p>

<p>To use the latest version of the API, you must include the version parameter in your requests. Otherwise, Amazon Associates Web Service uses the default API version, which is from 2005-10-05"</p>

<p><a href="http://developer.amazonwebservices.com/connect/entry.jspa?externalID=1057">http://developer.amazonwebservices.com/connect/…</a></p>

    </div>
</div>

<div class="comments">
    <h3>Comments</h3>

    <div class="comment">
        <p class="metadata">Posted by John Kelly (postalservice14) on 2012-08-20T15:36:11.000+0000</p> 
        <div class="body">
            <p>Pull Request Sent: <a href="https://github.com/zendframework/ZendService_Amazon/pull/9">https://github.com/zendframework/…</a></p>

        </div>
    </div>
        <div class="comment">
        <p class="metadata">Posted by Maks 3w (maks3w) on 2012-08-21T19:42:41.000+0000</p> 
        <div class="body">
            <p>Patch merged, thank you</p>

        </div>
    </div>
    </div>

