<?php 
$this->headTitle()->prepend('Security');
$this->headTitle()->prepend('Advisories');
$this->headTitle()->prepend($advisory['title']);
$this->render('security/sidebar');

$id = $this->advisory['id'];
if (!$this->resolver()->resolve('security/advisory/' . $id)) {
    $this->error = 'Invalid advisory identifier';
}
?>
<section class="security">
    <h1>Security Advisory</h1>

<?php if ($this->error): ?>
    <p><?php echo $this->error ?></p>
<?php else: ?>
    <?php echo $this->render('security/advisory/' . $id) ?>
<?php endif ?>
</section>
