<?php 
$first   = $this->advisories->getIterator()->current();
$headers = $this->response->getHeaders();
$headers->addHeaderLine('Content-Type', 'application/rss+xml');
$headers->addHeaderLine('Last-Modified', $first['date']);
$headers->addHeaderLine('ETag', '"' . md5($first['date']) . '"');
?>
<?php echo '<?xml version="1.0" encoding="utf-8"?>' . "\n" ?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
    <channel>
        <title>Zend Framework Security Advisories</title>
        <link>http://framework.zend.com/security/reports</link>
        <atom:link href="http://framework.zend.com/security/feed" rel="self" type="application/rss+xml" />
        <language>en-us</language>
        <managingEditor>zf-security@zend.com (Zend Framework Security)</managingEditor>
        <lastBuildDate><?php echo $first['date'] ?></lastBuildDate>
        <description>
            Reported and patched vulnerabilities in Zend Framework.
        </description>
    <?php foreach ($this->advisories as $advisory => $info): ?>
        <item>
            <title><?php echo $this->escapeHtml($info['title']) ?></title>
            <link>http://framework.zend.com<?php echo $this->url('security/advisory', array('advisory' => $advisory)) ?></link>
            <guid>http://framework.zend.com<?php echo $this->url('security/advisory', array('advisory' => $advisory)) ?></guid>
            <description><![CDATA[
<?php echo $this->render('security/advisory/' . $advisory) ?>
]]></description>
            <pubDate><?php echo $this->escapeHtml($info['date']) ?></pubDate>
            <author>zf-security@zend.com (Zend Framework Security)</author>
        </item>
    <?php endforeach ?>
    </channel>
</rss>
