<h2>ZF2014-01: Potential XXE/XEE attacks using PHP functions: simplexml_load_*, 
    DOMDocument::loadXML, and xml_parse</h2>

<p>
    Numerous components utilizing PHP's <code>DOMDocument</code>, 
    <code>SimpleXML</code>, and <code>xml_parse</code> functionality are vulnerable to
    two types of attacks:
</p>

<ul class="ul">
    <li>
        XML eXternal Entity (XXE) Injection attacks. The above mentioned
        extensions are insecure by default, allowing external entities to be 
        specified by adding a specific DOCTYPE element to XML documents and 
        strings. By exploiting this vulnerability an application may be coerced
        to open arbitrary files and/or TCP connections.
    </li>

    <li>
        XML Entity Expansion (XEE) vectors, leading to Denial of Service 
        vectors. XEE attacks occur when the XML DOCTYPE declaration includes XML
        entity definitions that contain either recursive or circular references;
        this leads to CPU and memory consumption, making Denial of Service 
        exploits trivial to implement.
    </li>
</ul>

<h3>Action Taken</h3>

<p>
    Continuing on the patches performed in <a href="<?php echo $this->url('security/advisory', array('advisory' => 'ZF2012-02')) ?>">ZF2012-02</a>
    and <a href="<?php echo $this->url('security/advisory', array('advisory' => 'ZF2012-05')) ?>">ZF2012-05</a>,
    we extended the patch to all the usage of the PHP functions 
    <code>simplexml_load_*</code>, <code>DOMDocument::loadXML</code>, and 
    <code>xml_parse</code>, in order to prevent XXE and XEE attacks across
    the framework.
</p>

<p>
    We have provided new components, <code>Zend_Xml_Security</code> in ZF1 and 
    the standalone <code>ZendXml</code>, that scan and load XML documents to 
    prevent the previous attacks. The XXE attack is prevented using the 
    <code>libxml_disable_entity_loader()</code> function to 
    disable the loading of ENTITY nodes. The XXE attack is prevented by checking
    for the presence of ENTITY elements in the document type declaration; in 
    such cases, we throw an Exception with an error message indicating that we 
    don't accept ENTITY declarations in XML documents for security reasons.
</p>

<p>
    Moreover, because of <a href="https://bugs.php.net/bug.php?id=64938">PHP 
    bug 64938</a>, we have decided to manage the PHP-FPM scenario using an 
    heuristic approach. We perform a search inside the XML string to find usage of any
    <code>&lt;!ENTITY"</code> element, and, on detection, raise an exception.
</p>

<p>
    Note: the libxml library used by PHP to manage XML documents has been fixed 
    against XEE attacks starting from libxml2 version 2.9. If you are using this 
    version you can use the existing PHP functions without security concerns.
</p>

<p>
    The following components/libraries were patched, at the version specified:
</p>

<ul class="ul">
    <li>Zend Framework 1, version 1.12.4</li>
    <li>Zend Framework 2, versions 2.1.6 and 2.2.6</li>
    <li>ZendOpenId, version 2.0.2</li>
    <li>ZendRest, version 2.0.2</li>
    <li>ZendService_Amazon, version 2.0.3</li>
    <li>ZendService_Api, version 1.0.0</li>
    <li>ZendService_AudioScrobbler, version 2.0.2</li>
    <li>ZendService_Nirvanix, version 2.0.2</li>
    <li>ZendService_SlideShare, version 2.0.2</li>
    <li>ZendService_Technorati, version 2.0.2</li>
    <li>ZendService_WindowsAzure, version 2.0.2</li>
</ul>

<h2>Other Information</h2>

<p>About XML eXternal Entity (XXE) attacks:</p>

<ul class="ul">
    <li><a href="https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing">https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing</a></li>
    <li><a href="http://websec.io/2012/08/27/Preventing-XEE-in-PHP.html">http://websec.io/2012/08/27/Preventing-XEE-in-PHP.html</a></li>
</ul>

<p>About XML Entity Expansion (XEE) attacks:</p>

<ul class="ul">
    <li><a href="http://en.wikipedia.org/wiki/Billion_laughs">http://en.wikipedia.org/wiki/Billion_laughs</a></li>
    <li><a href="http://projects.webappsec.org/w/page/13247002/XML%20Entity%20Expansion">http://projects.webappsec.org/w/page/13247002/XML%20Entity%20Expansion</a></li>
    <li><a href="http://cwe.mitre.org/data/definitions/776.html">http://cwe.mitre.org/data/definitions/776.html</a></li>
</ul>

<h3>Acknowledgments</h3>

<p>
    The Zend Framework team thanks the following for identifying the issues and 
    working with us to help protect its users:
</p>

<ul class="ul">
    <li>Lukas Reschke (lukas@owncloud.org) for reporting the potential XXE attacks in some components of ZF1, not previously fixed, and to suggest a possible fix for PHP-FPM scenarios</li>
    <li>Pádraic Brady (padraic.brady@gmail.com) for implementing the first XEE security patch (ZF2012-02)</li>
    <li>Enrico Zimuel (enrico@zend.com) for improving the previous solution, extending it to all the use cases.</li>
</ul>

