<?php $this->placeholder('sidebar')->captureStart(); ?>
<div id="selectversion">
    Select a version:
    <select onchange="javascript:location.href='/manual/'+this.value+'/en/';">
        <?php foreach ($this->versions as $ver) {
            $selected = '';
            if ($ver === $this->version) {
                $selected = 'selected="selected"';
            }
            echo "<option $selected>$ver</option>";
        } ?>
    </select>
    <?php if ('1.' === substr($this->version, 0, 2)): ?>
        <img class="logo" alt="Logo" src="<?php echo $this->basePath('images/manual/zf_logo.png') ?>">
    <?php endif ?>
</div>
<?php echo $this->sidebar; ?>
<?php $this->placeholder('sidebar')->captureEnd(); ?>

