<?php $this->placeholder('sidebar')->captureStart(); ?>
<div id="selectversion">
    Select a version:
    <select onchange="javascript:location.href='/manual/'+this.value+'/en/';">
        <?php foreach ($this->versions as $ver) {
            $selected = '';
            if ($ver === $this->version) {
                $selected = 'selected="selected"';
            }
            echo "<option $selected>$ver</option>";
        } ?>
    </select>
</div>
<?php echo $this->sidebar; ?>
<?php $this->placeholder('sidebar')->captureEnd(); ?>
