<?php
$this->headLink()->prependStylesheet('//ajax.googleapis.com/ajax/libs/dojo/1.8/dijit/themes/claro/claro.css');
$this->layout()->bodyClass = 'claro';

$dojoDataConfig = 'async: true, parseOnLoad: true';
$this->placeholder('scripts')->append(sprintf(
    '<script data-dojo-config="%s" src="//ajax.googleapis.com/ajax/libs/dojo/1.8.0/dojo/dojo.js"></script>', 
    $dojoDataConfig
));

$this->inlineScript()->captureStart(); ?>
    // Require the Dialog class
    require(["dijit/registry", "dojo/parser", "dojo/ready", "dijit/Dialog", "dijit/form/Button"], function(registry, parser, ready){
        // Show the dialog
        showDocDownloads = function(id) {
            registry.byId(id).show();
        }

        // Hide the dialog
        hideDialog = function(id) {
            registry.byId(id).hide();
        }

        ready(function(){
            parser.parse();
        });
    });
<?php $this->inlineScript()->captureEnd(); ?>
