<?php $this->placeholder('sidebar')->captureStart() ?>
<ul>
    <li><a href="<?php echo $this->url('contact') ?>">Contact Form</a></li>
    <li><a href="<?php echo $this->url('archives') ?>">List Archives</a></li>
    <li><a href="<?php echo $this->url('archives/subscribe') ?>">Subscription Information</a></li>
    <li><a href="<?php echo $this->url('irc') ?>">IRC</a></li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd() ?>

