<?php
$this->layout()->bodyId = 'security';

$this->placeholder('sidebar')->captureStart();
?>
<ul>
    <li<?= ($this->active == 'overview' ? ' class="active"' : '') ?>>
        <a href="<?= $this->url('security') ?>">Overview</a>
    </li>
    <li<?= ($this->active == 'advisories' ? ' class="active"' : '') ?>>
        <a href="<?= $this->url('security/default', array('action' => 'advisories')) ?>">Advisories</a>
    </li>
    <li>
        <a href="<?= $this->url('security/default', array('action' => 'feed')) ?>">Feed</a>
    </li>
</ul>
<?php $this->placeholder('sidebar')->captureEnd(); ?>
