<?= $this->partial('partners/sidebarmicrosoft') ?>
<?= $this->partial('partners/header', array('title'  => 'Partners Program',
                                            'active' => 'technology')) ?>

<?= $this->dynamicHeader('subPageMainHeader', 'Technology Partners') ?>

<table style="text-align: left;" border="0" cellpadding="1" cellspacing="5">
	<tbody>
		<tr>
		    <td style="text-align: center; vertical-align: middle;"><a href="http://www.microsoft.com/" target="_blank">
		      <img style="width: 247px; height: 40px;" alt="" src="/images/partners/microsoft_logo_lg.gif"></a></td>
		</tr>
	</tbody>
</table>
<br/>

<p class="first">
Microsoft has been a leading industry voice in the creation of an identity metasystem, an
ecosystem designed to enable the exchange of personal identity information on the Internet
so all parties may understand whom they are working with online.
</p>

<div class="dotted-line"></div>

<p>
Three core elements make up the identity metasystem: the people who are presenting their identity,
the Web site or online service requesting proof of identity, and the identity providers who 
some information about those people. 
</p>

<p>
In May 2007 Microsoft announced the availability of Identity Selector Interoperability Profile
specifications under the Open Specification Promise
(<a href="http://www.microsoft.com/interop/osp/default.mspx" target="_blank">OSP</a>) to enhance
interoperability in the identity metasystem for client computers using any platform. 
</p>

<p>
Information Cards help both site owners and visitors to manage, control, and exchange digital
identities more safely and consistently. Digital identities are represented visually and are stored
locally on the user's desktop. Each card represents a set of claims that relate to that particular
user, such as first name, last name, and e-mail address. Every card carries its own name, as well as
an image and the details of who issued that card.
</p>

<p>
Windows CardSpace&reg; is one of the key components of interoperable Microsoft&reg; identity solutions,
which enable Web applications and services to validate user identity through Information Cards. This
identity-selector technology makes sign-ins and sign-ups much easier, yet delivers much greater
security than password-based Web logons--shielding users from online identity theft, fraud and
privacy concerns.
</p>

<p>
Microsoft is very happy to work with Zend Technologies to enable information card support available
for PHP language through Zend Framework and the standalone implementations. 
</p>

<p>
<a href="http://informationcardphp.com" target="_blank">http://informationcardphp.com</a>
</p>
