<?=$this->partial ( 'download/sidebar' ) ?>
<?= $this->partial('download/header', array('title'  => 'Downloads',
                                            'active' => 'simplecloud')) ?>

<?= $this->dynamicHeader('subPageMainHeader', 'SimpleCloud API' . ' Downloads') ?>

<p>
    Everything you need to start writing scalable, highly available, and 
    resilient cloud applications that are portable across all major cloud 
    vendors.
</p>

<div class="dotted-line"></div>

<p class="first">
    Starting with version 1.11.0, SimpleCloud is now officially available as 
    the <code>Zend_Cloud</code> component of Zend Framework. You may 
    <a href="/download/latest">download</a> it as part of the official Zend Framework
    distribution, using either a full or minimal package.
</p>

