<?php
$bodyId = '';
if ($this->bodyId) {
    $bodyId = $this->escapeHtmlAttr($this->bodyId);
}
?>
<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
    <head>
        <!-- Meta -->
        <meta charset="utf-8">

        <!-- Set the viewport width to device width for mobile -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <?php echo $this->headTitle('Zend Framework')->setSeparator(' - ')->setAutoEscape(false); ?>

        <!-- CSS, feeds and favicon -->
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('images/favicon.ico')))
    ->prependAlternate($this->url('security/default', array('action' => 'feed')), 'application/rss+xml', 'Zend Framework Security Advisories')
    ->prependAlternate($this->basePath('blog/feed-atom.xml'), 'application/atom+xml', 'Zend Framework Blog Atom Feed')
    ->prependAlternate($this->basePath('blog/feed-rss.xml'), 'application/rss+xml', 'Zend Framework Blog RSS Feed')
    ->prependStylesheet($this->basePath('css/app.min.css'))
    ->prependStylesheet($this->basePath('css/foundation.min.css'))
    ->setIndent(8) ?>

        <!-- JavaScript -->
        <?php echo $this->headScript()->prependFile($this->basePath('js/modernizr.foundation.js')) ?>
        
        <!-- IE Fix for HTML5 Tags -->
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body<?php echo ($bodyId ? ' id="' . $bodyId . '"' : ''); ?>>

        <!-- Header -->
        <header id="header" class="row">

            <!-- Logo -->
            <div class="three mobile-two columns" id="logo">
                <h1>
                    <a href="<?php echo $this->url('home') ?>" title="">
                        <img src="<?php echo $this->basePath('images/logo.png') ?>" width="173" height="41" alt="Zend Framework">
                    </a>
                </h1>
            </div>

            <!-- Menu -->
            <div class="six mobile-two columns" id="menu">
                <nav class="top-bar">
                    <ul>
                        <li class="name show-for-small">Menu</li>
                        <li class="toggle-topbar show-for-small"><a href="#"></a></li>
                        <li<?php echo ($this->active == 'about' ? ' class="active"' : ''); ?>><a href="<?php echo $this->url('about') ?>">About</a></li>
                        <li<?php echo ($this->active == 'learn' ? ' class="active"' : ''); ?>><a href="<?php echo $this->url('learn') ?>">Learn</a></li>
                        <li<?php echo ($this->active == 'start' ? ' class="active"' : ''); ?>><a href="<?php echo $this->url('downloads') ?>">Get Started</a></li>
                        <li<?php echo ($this->active == 'participate' ? ' class="active"' : ''); ?>><a href="<?php echo $this->url('participate') ?>">Participate</a></li>
                        <li class="show-for-small">
                            <!-- Search form for small screens -->
                            <form method="get" action="//www.google.com/search<?php // echo $this->url('search') ?>" target="_blank">
                                <input type="text" name="q" maxlength="255" placeholder="Search in the site">
                                <input type="hidden" name="sitesearch" value="framework.zend.com">
                            </form>
                        </li>
                    </ul>
                </nav>
            </div>

            <!-- Search form -->
            <form method="get" action="//www.google.com/search<?php // echo $this->url('search') ?>" target="_blank" class="three columns hide-for-small">
                <input type="text" name="q" maxlength="255" placeholder="Search in the site">
                <input type="hidden" name="sitesearch" value="framework.zend.com">
            </form>

            <!-- Link to Github -->
            <?php if ('home' == $bodyId): ?>
                <a id="github-link" href="https://github.com/zendframework/zf2">
                    <img src="<?php echo $this->basePath('images/fork-us-on-github.png') ?>" alt="Fork us on GitHub">
                </a>
            <?php endif ?>
        </header>
        
        <div id="top-header-shadow"></div>

        <?php if ('home' == $bodyId): ?>
            <?php echo $this->content ?>
        <?php else: ?>
            <div class="show-for-small" id="navigation-button">
                <a href="#navigation" class="secondary round button">&hellip;</a>
            </div>
            <div class="row">
                <!-- Navigation -->
                <nav id="navigation" class="three columns">
                    <?php echo $this->placeholder('sidebar') ?>
                </nav>

                <!-- Content -->
                <div id="content" class="nine columns" role="main">
                    <?php echo $this->content ?>
                </div>
            </div>
        <?php endif ?>

        <!-- Footer -->
        <footer id="footer">
            <div class="row">
                <div class="two mobile-two columns">
                    <h4>About</h4>
                    <ul class="ref">
                        <li class="link-highlight"><a href="<?php echo $this->url('about') ?>">Overview</a></li>
                        <li><a href="<?php echo $this->url('about/faq') ?>">ZF2 FAQ</a></li>
                        <li><a href="<?php echo $this->url('about/faq-v1') ?>">ZF1 FAQ</a></li>

                        <?php /*
                          <li><a href="">Case Studies</a></li>
                          <li><a href="">By the Numbers</a></li>
                         */ ?>
                        <li><a href="<?php echo $this->url('security') ?>">Security</a></li>
                        <li><a href="<?php echo $this->url('changelog') ?>">Changelog</a></li>
                        <li><a href="<?php echo $this->url('phly-blog/index') ?>">Blog</a></li>
                    </ul>
                </div>

                <div class="two mobile-two columns">
                    <h4>Learn</h4>
                    <ul class="ref">
                        <li><a href="<?php echo $this->manualUrl('user-guide/overview.html', 'en', '2.3') ?>">User Guide</a></li>
                        <li><a href="<?php echo $this->manualUrl('index.html', 'en', '2.3') ?>">Reference Guide</a></li>
                        <li><a href="<?php echo $this->url('docs/api') ?>">APIs</a></li>
                        <!--              <li><a href="">Webinars</a></li>-->
                        <li><a href="<?php echo $this->url('learn/training-and-certification') ?>">Training &amp; Certification</a></li>
                        <li><a href="<?php echo $this->url('learn/support-and-consulting') ?>">Support &amp; Consulting</a></li>
                    </ul>
                </div>

                <hr>

                <div class="two mobile-two columns">
                    <h4>Get Started</h4>
                    <ul class="ref">
                        <li><a href="<?php echo $this->url('downloads') ?>">Downloads</a></li>
                        <li><a href="<?php echo $this->url('downloads', array('action' => 'skeleton-app')) ?>">Get the Skeleton App</a></li>
                        <li><a href="http://modules.zendframework.com" target="_blank">Find modules for your application</a></li>
                    </ul>
                </div>

                <div class="two mobile-two columns">
                    <h4>Participate</h4>
                    <ul class="ref">
                        <li><a href="<?php echo $this->url('participate') ?>">Overview</a></li>
                        <li><a href="<?php echo $this->url('participate/contribute') ?>">Contributors Guide</a></li>
                        <li><a href="<?php echo $this->url('participate/user-groups') ?>">User Groups</a></li>
                        <li><a href="<?php echo $this->url('participate/blogs') ?>">Blogs</a></li>
                        <li><a href="<?php echo $this->url('participate/contributors') ?>">Contributors</a></li>
                        <li><a href="<?php echo $this->url('participate/logos') ?>">Logos</a></li>
                    </ul>
                </div>

                <div class="two mobile-four columns offset-by-two" id="contact-menu">
                    <h4>Contact Us</h4>
                    <ul class="ref">
                        <li><a href="<?php echo $this->url('contact')  ?>">form</a></li>
                        <li><a href="<?php echo $this->url('archives') ?>">mailing lists</a></li>
                        <li><a href="<?php echo $this->url('irc') ?>">IRC</a></li>
                    </ul>
                </div>
            </div>

            <div class="row">
                <div id="social-links" class="block-grid four-up mobile-two-up">
                    <div>
                        <a href="https://github.com/zendframework/zf2">
                            <img src="/images/social-github.png"> Fork us on github
                        </a>
                    </div>

                    <div>
                        <a href="https://twitter.com/zfdevteam">
                            <img src="/images/social-twitter.png"> ZF on Twitter
                        </a>
                    </div>

                    <div>
                        <a href="<?php echo $this->url('phly-blog/feed-rss') ?>">
                            <img src="/images/social-rss.png"> Blog Feed
                        </a>
                    </div>

                    <div>
                        <a href="<?php echo $this->url( 'security/default', array('action' => 'feed')) ?>">
                            <img src="/images/social-rss.png"> Security Feed
                        </a>
                    </div>
                </ul>
            </div>

            <div id="footer-copyright" class="row">
                <p>&copy; 2006 - <?php echo date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                <a href="#header" id="to_top">
                    <img src="<?php echo $this->basePath('images/arrow.png') ?>" width="22" height="20" alt="" title="back to top">
                </a>
            </div>
        </footer>

        <!-- Included JS Files -->
<?php echo $this->inlineScript()->prependFile($this->basePath('js/app.js'))
    ->prependFile($this->basePath('js/foundation.min.js'))
    ->prependFile($this->basePath('js/jquery.js'))
    ->setIndent(8) ?>

        <!-- Initialize JS Plugins -->
        <script>
            $(document).foundationNavigation();
        </script>

        <!-- Google Analytics -->
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          
          ga('create', 'UA-291885-1', 'auto');
          ga('send', 'pageview');
        </script>

        <!-- Eloqua integration -->
        <script src="<?php echo $this->basePath('js/elqNow/elqCfg.js') ?>"></script>
        <script src="<?php echo $this->basePath('js/elqNow/elqImg.js') ?>"></script>
        <script src="http://www.googleadservices.com/pagead/conversion.js"></script>
        <noscript>
            <div style="display: inline;">
                <img height="1" width="1" style="border-style:none;" alt="" src="http://googleads.g.doubleclick.net/pagead/viewthroughconversion/1072138399/?value=0&amp;label=PTX5CIfdwAMQn5Ge_wM&amp;guid=ON&amp;script=0">
            </div>
        </noscript>

        <!-- LivePerson integration -->
        <script>
            var lpMTagConfig = {'lpServer' : "server.iad.liveperson.net",'lpNumber' : "10919998",'lpProtocol' : "https"}; function lpAddMonitorTag(src){if(typeof(src)=='undefined'||typeof(src)=='object'){src=lpMTagConfig.lpMTagSrc?lpMTagConfig.lpMTagSrc:'/hcp/html/mTag.js';}if(src.indexOf('http')!=0){src=lpMTagConfig.lpProtocol+"://"+lpMTagConfig.lpServer+src+'?site='+lpMTagConfig.lpNumber;}else{if(src.indexOf('site=')<0){if(src.indexOf('?')<0)src=src+'?';else src=src+'&';src=src+'site='+lpMTagConfig.lpNumber;}};var s=document.createElement('script');s.setAttribute('type','text/javascript');s.setAttribute('charset','iso-8859-1');s.setAttribute('src',src);document.getElementsByTagName('head').item(0).appendChild(s);} if (window.attachEvent) window.attachEvent('onload',lpAddMonitorTag); else window.addEventListener("load",lpAddMonitorTag,false);
        </script>

        <!-- marketo integration -->
        <script type="text/javascript">
            document.write(unescape("%3Cscript src='//munchkin.marketo.net/munchkin.js' type='text/javascript'%3E%3C/script%3E"));
        </script>
        <script>Munchkin.init('074-LXC-746');</script>

        <!-- bizo integration -->
        <script type="text/javascript">
            var _bizo_data_partner_id = "6662";
        </script>

        <script type="text/javascript">
            (function() {
                var s = document.getElementsByTagName("script")[0];
                var b = document.createElement("script");
                b.type = "text/javascript";
                b.async = true;
                b.src = (window.location.protocol === "https:" ? "https://sjs" : "http://js") + ".bizographics.com/insight.min.js";
                s.parentNode.insertBefore(b, s);
            })();
        </script>

        <noscript>
            <img height="1" width="1" alt="" style="display:none;" src="//www.bizographics.com/collect/?pid=6662&fmt=gif" />
        </noscript>
    </body>
</html>
