<?php if ($this->message == 'Page not found'): ?>
    <div class="error-404">
        <div class="error-404-speech-bubble">
            <?php echo $this->dynamicHeader('subPageMainHeader', $this->message); ?>

            <p class="first">
                <?php
                    $notFoundText = array(
                        "NO, Zend Framework is <strong>not</strong> to blame for this!",
                        "We hear Symfony doesn't have this problem.",
                        $this->text,
                    );
                    echo $notFoundText[array_rand($notFoundText)];
                ?>
            </p>
        </div>
    </div>
<?php else: ?>
    <?php echo $this->dynamicHeader('subPageMainHeader', $this->message); ?>

    <p class="first">
        <?php
            $notFoundText = array(
                "NO, Zend Framework is <strong>not</strong> to blame for this!",
                "We hear Symfony doesn't have this problem.",
                $this->text,
            );
            echo $notFoundText[array_rand($notFoundText)];
        ?>
    </p>
<?php endif; ?>

<?php
$config = Zend_Registry::get('config');
if ($config->mvc->showTrace):
?>
    <div class="dotted-line"></div>

    <h2>Backtrace</h2>
    <pre class="error">
        <?php echo $this->exception->getMessage(); ?>
        <?php echo $this->exception->getTraceAsString(); ?>
    </pre>

    <h2>Request</h2>
    <pre class="error">
        <?php echo var_export($this->request->getParams(), 1); ?>
    </pre>
<?php endif; ?>
