<?php
$this->layout()->bodyId = 'home';
?>
    <!-- Intro -->
    <div class="row" id="intro">
    <img src="<?php echo $this->basePath('images/head-bottom-picture.png') ?>"
        <?php /* width="992" height="267" */ ?> alt="" />
    </div>

    <!-- Download -->
    <div class="row" id="download">
        <div class="twelve columns">
            <a href="<?php echo $this->url('downloads', array('action' => 'latest')) ?>"></a>
        </div>
    </div>

    <div id="background">
        <div class="row">
            <h1 class="text-center"><a href="/expressive">Announcing Expressive RC1<br />PSR-7 Middleware</a></h1>
        </div>
    </div>

    <!-- Why? -->
    <div class="row" id="reasons">
        <div class="six columns">
            <h1>Why use Zend Framework?</h1>
            <div class="row">
                <div class="six mobile-two columns">
                    <h3 id="modular">Modular</h3>
                    <p>Building blocks that can be used piece by piece with other applications or frameworks</p>
                </div>
                <div class="six mobile-two columns">
                    <h3 id="secure">Secure</h3>
                    <p>All the cryptographic and secure coding tools you need to do things right</p>
                </div>
            </div>
            <div class="row">
                <div class="six mobile-two columns">
                    <h3 id="extensible">Extensible</h3>
                    <p>Easy to adapt the framework to your needs</p>
                </div>
                <div class="six mobile-two columns">
                    <h3 id="community">Community</h3>
                    <p>A vibrant and active contributor and user base for getting help and giving back</p>
                </div>
            </div>
            <div class="row">
                <div class="six mobile-two columns">
                    <h3 id="high-performing">High Performing</h3>
                    <p>Engineered with performance tuning in mind</p>
                </div>
                <div class="six mobile-two columns">
                    <h3 id="enterprise-ready">Enterprise Ready</h3>
                    <p>A proven history of success running business critical and high-usage applications</p>
                </div>
            </div>
        </div>
        <div class="six columns">
          <a href="/blog/announcing-the-zend-framework-3-roadmap.html">
          <img src="images/Zend-Framework3-homepage-banner.png" alt="Zend Framework 3 Announcement">
          <?php /* <a
             href="http://shop.zend.com/en/zend-server-licensing.html">
            <img src="images/Zend-Server-for-Zend-Framework-Promotion.png" alt="">
                 */ ?>
          </a>
        </div>
        <?php /*
        <div class="three columns">
            <div id="zf2a-course">
            <a href="http://www.zend.com/en/services/certification/framework-2/">
                <img src="<?php // echo $this->basePath('images/ZF2-Certification-390x300px.png') ?>"
                    alt="New! Zend Framework 2 Certification!">
            </a>
            </div>
            <a href="http://www.zend.com/en/services/certification/framework-2/"></a>
            <?php // echo $this->render('trainingads') ?>
        </div>
         */ ?>
    </div>

    <!-- Links -->
    <div id="background">
        <div class="row">
            <h1 class="text-center">Maximize Development Productivity</h1>
        </div>

        <div class="row dev-tools images">
            <div class="tool">
                <a href="https://apigility.org"><img src="images/ag-hero.png" alt="Apigility" width="200"></a>
            </div>

            <div class="tool">
              <a href="http://www.zend.com/en/products/server/z-ray">
                <img src="images/Z-ray-new-icon-146x90px.png" alt="Z-Ray">
              </a>
            </div>

            <div class="tool">
              <a href="http://www.zend.com/en/products/studio">
                <img src="images/zend-studio-logo-346x54px.png" alt="Zend Studio">
              </a>
            </div>
        </div>

        <div class="row dev-tools info">
            <div class="tool">
              <p class="caption">
                The world's easiest way to create high-quality APIs.
              </p>
              <a href="https://apigility.org"><img src="images/Learn-more-button-166x37px.png" alt="Learn more"></a>
            </div>

            <div class="tool">
              <p class="caption">
                Write Better Code Faster.
              </p>
              <a href="http://www.zend.com/en/products/server/z-ray">
                <img src="images/Learn-more-button-166x37px.png" alt="Learn more">
              </a>
            </div>

            <div class="tool">
              <p class="caption">
                The PHP IDE for Smarter Development.
              </p>
              <a href="http://www.zend.com/en/products/studio">
                <img src="images/Learn-more-button-166x37px.png" alt="Learn more">
              </a>
            </div>
        </div>

        <div class="row">
            <div class="twelve columns" id="links">
                <dl class="tabs">
                    <dd class="active"><a href="#news-content">News</a></dd>
                    <dd><a href="#get-started-content">Get Started</a></dd>
                    <dd><a href="#get-involved-content">Get Involved</a></dd>
                </dl>
                <ul class="tabs-content">
                    <li class="active" id="news-contentTab">
{%news%}    
                    </li>
                    <li id="get-started-contentTab">
                        <h5><a href="/manual/2.2/en/user-guide/overview.html">Get started with ZF2</a></h5>
                        <h5><a href="/manual/2.2/en/index.html">Read the ZF2 reference guide</a></h5>
                        <h5><a href="/manual/1.12/en/learning.quickstart.html">Get started with ZF1</a></h5>
                        <h5><a href="/manual/1.12/en/manual.html">Read the ZF1 reference guide</a></h5>
                    </li>
                    <li id="get-involved-contentTab">
                        <h5><a href="/participate/contributor-guide/">Read the ZF2 Contributor Guide</a></h5>
                        <h5><a href="/participate/conferences/">Find conferences</a></h5>
                        <h5><a href="/participate/blogs/">Find tips on ZF2 blogs</a></h5>
                        <h5><a href="/participate/contributor-guide-v1/">Contribute to ZF1</a></h5>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <!-- Events -->
    <?php /* Waiting for a future implementation
    <div class="row" id="events">
        <h5>Upcoming Events</h5>
        <div class="events-container scrollpane">
            <ul>
                <li>
                    <span>UK</span>
                    <ul class="cities">
                        <li>June 20 - <span>London</span></li>
                        <li>June 26 - <span>Bristol</span></li>
                    </ul>
                </li>

                <li>
                    <span>USA</span>
                    <ul class="cities">
                        <li>August 24 - <span>NYC</span></li>
                        <li>August 25 - <span>LA</span></li>
                    </ul>
                </li>

                <li>
                    <span>USA</span>
                    <ul class="cities">
                       <li>August 24 - <span>NYC</span></li>
                       <li>August 25 - <span>LA</span></li>
                    </ul>
                </li>
            </ul>
        </div>

        <a href="" class="more">more &raquo;</a>
    </div>
     */ ?>

    <!-- Clients -->
    <div class="row" id="clients">
        <h2>Who uses Zend Framework?</h2>
        <ul class="block-grid four-up mobile-two-up">
            <li><a href="http://www.alliedbeverage.com/" target="_blank"><img alt="Allied Beverage" src="<?php echo $this->basePath('/images/homepage/AlliedBeveragel-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.autotrack.nl/" target="_blank"><img alt="AutoTrack.nl" src="<?php echo $this->basePath('/images/homepage/AutoTrack-nl-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.bbc.co.uk/" target="_blank"><img alt="BBC" src="<?php echo $this->basePath('/images/homepage/BBC-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.bnpparibas.com/" target="_blank"><img alt="BNP Paribas" src="<?php echo $this->basePath('/images/homepage/BNP-Paribas-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.caringbridge.org/" target="_blank"><img alt="CaringBridge.org" src="<?php echo $this->basePath('/images/homepage/CaringBridge-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://centroy.com/" target="_blank"><img alt="Centroy" src="<?php echo $this->basePath('/images/homepage/Centroy-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.webex.com/" target="_blank"><img alt="Cisco WebEx" src="<?php echo $this->basePath('/images/homepage/CiscoWebEx-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.nrholding.com/" target="_blank"><img alt="Netretail Holding" src="<?php echo $this->basePath('/images/homepage/Netretail-Holding-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.offers.com/" target="_blank"><img alt="Offers.com" src="<?php echo $this->basePath('/images/homepage/Offers-com-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.serpro.gov.br/" target="_blank"><img alt="SERPRO" src="<?php echo $this->basePath('/images/homepage/Serpro-logo-color.png') ?>" width="162" height="44" /></a></li>
            <li><a href="http://www.shaklee.com/" target="_blank"><img alt="Shaklee" src="<?php echo $this->basePath('/images/homepage/Shaklee-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.villeroy-boch.com/" target="_blank"><img alt="Villeroy &amp; Boch" src="<?php echo $this->basePath('/images/homepage/VilleroyBoch-logo-color.png') ?>" width="162" height="44"/></a></li>
            <li><a href="http://www.gsminfo.nl/mobiele-telefoons" target="_blank"><img alt="GSMInfo.nl" src="<?php echo $this->basePath('/images/homepage/GSMinfo-logo-color.png') ?>" width="162" height="44"/></a></li>
        </ul>
    </div>

    <div id="dialog_promo" class="row" style="display:none">
        <div class="twelve columns hide-for-medium-down">
            <div>
                <a href="http://www.zend.com/en/products/server/z-ray-zend-framework-demo?utm_source=zfslide" id="promoLink">
                    <div id="promo-image"><img src="images/Z-ray-AD-for-Framework-1142x256px.png" alt=""></div>
                </a>
                <div id="promoClose">
                    <img src="images/X-icon-17x16px.png" alt="" title="">
                </div>
            </div>
        </div>
    </div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {	
    if (getCookie('promoClosed') != 1) {
    	setTimeout(function() {
    		$( "#dialog_promo" ).slideDown( 2000 );
        }, 1000);
    }
	$(document).on('click','#promoClose',function(){
		setCookieAndClose();
	});
	$(document).on('click', '#promoLink', function(){
		setCookieAndClose();
	});
});

function getCookie(name) {
	  var value = "; " + document.cookie;
	  var parts = value.split("; " + name + "=");
	  if (parts.length == 2) return parts.pop().split(";").shift();
	}
	 
function closeDialog() {
	$("#dialog_promo").slideUp();
}

function setCookieAndClose() {
    var days = 30;
	var date = new Date();
	date.setTime(date.getTime()+(days * 24 * 60 * 60 * 1000))
	document.cookie="promoClosed=1; path=/; expires=" + date.toUTCString();
	$("#dialog_promo").slideUp();	
}
<?php $this->inlineScript()->captureEnd();
