<p>
    This is the 1.8.2 release of Zend Framework, the second maintenance release
    in the 1.8 series. It features primarily improvements to <kbd>Zend_Db</kbd>,
    as well as a number of fixes to allow autoloading of user-defined extensions
    (instead of requiring developers to load classes manually or rely on
    <kbd>Zend_Loader::loadClass()</kbd>). In all, more than 50 issues were
    closed for the release.
</p>
