<?php 
if ($this->version) {
    $this->version = str_replace('-', '.', $this->version);
    echo $this->dynamicHeader('subPageMainHeader', 'Roadmap: ' . $this->version);
    echo '<div class="dotted-line"></div>';
    $script = 'roadmap/' . $this->version . '.phtml';
    if (!$this->getScriptPath($script)) {
        echo '<p>No roadmap yet created.</p>';
    } else {
        echo $this->render($script);
    }
} else {
    echo $this->dynamicHeader('subPageMainHeader', 'Roadmap');
    echo '<div class="dotted-line"></div>';
    echo '<p>Please select a version from the sidebar.</p>';
}

$it       = new DirectoryIterator(dirname(__FILE__));
$versions = array();
foreach ($it as $file) {
    if ($file->isDir()) {
        continue;
    }
    $name = $file->getFilename();
    if (preg_match('/^(\d+\.\d+(\.\d+)?)\.phtml$/', $name, $matches)) {
        $versions[$matches[1]] = $name;
    }
}
ksort($versions);
?>

<?php $this->rightNav()->captureStart('append', 'All versions') ?>
<ul>
    <?php foreach (array_keys($versions) as $version): ?>
    <li><a href="/roadmap/<?php echo $version ?>"><?php echo $version ?></a></li>
    <?php endforeach ?>
</ul>
<? $this->rightNav()->captureEnd() ?>

