<?php
$this->layout()->bodyId = 'changelog';
$this->render('page-controller/about/sidebar', array('active' => 'changelog'));
$this->headTitle()->prepend('Changelog: ' . $this->version);
?>
<h1>Changelog</h1>

<div href="#" class="button dropdown right">
    Versions
    <ul>
        <?php foreach ($this->versions as $version): ?>
            <li>
                <a href="<?php echo $this->url('changelog/release', array('version' => $version)) ?>">
                    <?php echo $this->escapeHtml($version) ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php
// If we have notes for this release, render them
$changelogNotes = 'changelog/notes/' . $this->version . '.phtml';
if ($this->resolver()->resolve($changelogNotes)) {
    echo $this->render($changelogNotes);
}
?>

<?php if (is_array($this->issues)): ?>

<h2><?php echo $this->version ?></h2>

<table class="twelve">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title <small>(JIRA Link)</small></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->issues as $issue): ?>
            <td><?php echo $issue['key'] ?></td>
            <td>
                <?php
                printf(
                    '<a href="/issues/browse/%s">%s</a>',
                    $issue['key'],
                    $this->escapeHtml($issue['summary'])
                )
                ?>
            </td>
        <?php endforeach ?>
    </tbody>
</table>

<?php else: ?>

<?php
// Extract date
$date = trim(substr(
    $this->issues,
    strpos($this->issues, "\n\n")
));
$date = substr($date, 0, strpos($date, "\n\n"));
?>

<h2><?php printf('%s (%s)', $this->version, $date) ?></h2>

<table class="twelve">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title <small>(GitHub Link)</small></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $issues = explode("\n- ", $this->issues);
        unset($issues[0]); // Remove version and date

        foreach ($issues as $issue):
        ?>
            <tr>
                <td>#<?php echo substr($issue, 0, strpos($issue, ':')) ?></td>
                <td>
                    <?php
                    printf(
                        '<a href="%s">%s</a>',
                        substr($issue, strrpos($issue, '(') + 1, -1),
                        substr($issue, strpos($issue, ':') + 1, strrpos($issue, '(') - 5)
                    )
                    ?>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

<?php endif; ?>
