  <div id="footer">
      <div class="footer">
        <address>
            &copy; 2006 - <?php echo date('Y') ?> by <a href="http://www.zend.com/" target="_blank">Zend Technologies Ltd.</a> All rights reserved.<br />
        </address>
        <ul class="footer-nav">
            <li><a href="/about/faq">FAQ</a><span class="divider">|</span></li>
            <li><a href="/about/zf2-faq">ZF2 FAQ</a><span class="divider">|</span></li>
            <li><a href="/sitemap">Sitemap</a><span class="divider">|</span></li>
            <li><a href="/wiki">Wiki</a><span class="divider">|</span></li>
            <li><a href="/issues">Issue Tracker</a><span class="divider">|</span></li>
            <li><a href="/code">Code Browser</a><span class="divider">|</span></li>
            <li><a href="/license">License</a><span class="divider">|</span></li>
            <li><a href="/changelog">Changelog</a><span class="divider">|</span></li>
            <li><a href="/roadmap">Roadmap</a><span class="divider">|</span></li>
            <li><a href="/cla">CLA</a><span class="divider">|</span></li>
            <li><a href="/security">Security</a><span class="divider">|</span></li>
            <li><a href="/contact">Contact Us</a></li>
        </ul>
    </div>
  </div>
