  <div id="top">
    <div class="top">
      <h1 class="logo"><a href="/" title="ZF Zend Framework">ZF Zend Framework</a></h1>
      <ul id="top-nav" class="top-nav">
        <li><a href="/about/overview" class="level1">About</a>
          <ul>
            <li><a href="/about/overview">Overview</a></li>
            <li><a href="/about/components">Components</a></li>
            <li><a href="/about/casestudies">Case Studies</a></li>
            <li><a href="/about/numbers">By the Numbers</a></li>
            <li><a href="/about/faq">FAQ</a></li>
            <li class="last"><a href="/about/zf2-faq">ZF2 FAQ</a></li>
          </ul>
        </li>
        <li><a href="/download/overview" class="level1">Downloads</a>
          <ul>
            <li><a href="/download/overview">Overview</a></li>
            <li><a href="/download/latest">Latest Release</a></li>
            <li><a href="/download/gdata">Google Data APIs</a></li>
            <li><a href="/download/infocard">Microsoft InfoCard</a></li>
            <li><a href="/download/amf">Adobe AMF</a></li>
            <li><a href="/download/archives">Archives</a></li>
          </ul>
        </li>
        <li><a href="/docs/overview" class="level1">Documentation</a>
          <ul>
            <li><a href="/docs/overview">Overview</a></li>
            <li><a href="/manual/en/learning.quickstart.intro.html">QuickStart</a></li>
            <li><a href="/docs/api">APIs</a></li>
            <li><a href="/manual/manual">Reference Guide</a></li>
            <li><a href="/docs/translations">Translations</a></li>
            <li class="last"><a href="/docs/multimedia">Multimedia</a></li>
          </ul>
        </li>
        <li><a href="/community/overview" class="level1">Community</a>
          <ul>
            <li><a href="/community/overview">Overview</a></li>
            <li><a href="/zf2">ZF2 Development</a></li>
            <li><a href="/community/resources">Resources</a></li>
            <li><a href="/community/contributors">Contributors</a></li>
            <li><a href="/community/groups">User Groups</a></li>
            <li class="last"><a href="/community/logo">Logo</a></li>
          </ul>
        </li>
        <li><a href="/services/overview" class="level1">Services</a>
          <ul>
            <li><a href="/services/overview">Overview</a></li>
            <li><a href="/services/support">Support</a></li>
            <li><a href="/services/training">Training</a></li>
            <li><a href="/services/consulting">Consulting</a></li>
            <li class="last"><a href="/services/certification">Certification</a></li>
          </ul>
        </li>
      </ul>
      <div id="top-search">
        <form action="/search">
          <fieldset>
          <legend>Search</legend>
          <div class="field"><input type="text" name="query" value="Search the entire site" onclick="this.value=='Search the entire site'?this.value='':''" onblur="this.value==''?this.value='Search the entire site':''" /></div>
            <input name="language" type="hidden" value="en" />
            <input name="type" type="hidden" value="all" />
          <input type="image" src="/images/btn_search-go.gif" alt="Go" title="Go" class="btn_go" />
          </fieldset>
        </form>
      </div>
      <p class="behind-the-site">
        <a href="/behind-the-site"><img src="/images/behind-the-site.gif"
            alt="Behind the Site" title="Behind the Site" border="0" /></a>
      </p>
    </div>
  </div>
